### ISSUE TITLE
Not able to create new folders in bookmarks tree

### ISSUE THREAD

**Issue by Balengo** [piroor/treestyletab#1000]
Hi,
with the new version (0.16.2015111001) I can't anymore create new folders in bookmarks tree.
I tried several methods (among them right-clicking in drop down menu, opening the library, ecc).
When I try, I get a Pop-up message box with no text and the buttons OK and Cancel (Ok doesn't do anything).
 Also the function to bookmark the whole tree of tabs from the right-click menu on the tab has the same behaviour.
Disabling Tree Style Tab removes the problem.
I run FF42 on Win 7 64 bit.

Thanks

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/
See also http://stackoverflow.com/questions/31952727/how-can-i-disable-firefox-addons-signature-checking if you cannot install the development build.

**Comment by Balengo** [comment]
Now I've updatet to version 0.16.2015122501 (still FF 42.0) and the problem is solved.
Many thanks
