### ISSUE TITLE
Password store

### ISSUE THREAD

**Issue by labrute57** [piroor/treestyletab#1001]
Hey,

As I active treestyletab i can not store the password, the messagebox is trunk as you can see on the screenshot
![capture d ecran - 22112015 - 08 43 35](https://cloud.githubusercontent.com/assets/555168/11322639/abcdd732-90f5-11e5-9907-29cdcfb363e0.png)

Best regards
Frederic

**Comment by piroor** [comment]
I also met same problem sometimes, but can't reproduce it now...

**Comment by piroor** [comment]
Seems duplicated #999.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
