### ISSUE TITLE
NEW FEATURE-- Create New, Unassigned Tab

### ISSUE THREAD

**Issue by alphaa10** [piroor/treestyletab#1005]
Feature request-- Create new, unassigned Tab, but group that new tab with the parent tab
Steps to Reproduce-- Using Tree Style Tab, when we open a link and create a new tab, we simply right-click to open a context menu, and create that new tab. Normally, the new tab is placed under its parent tab, unless TST is otherwise configured. Sometimes, however, we need to create a new tab which is not created as a child of the current parent tab, but keep that new tab near the current group.
Expected Result-- The only means to create a blank tab is to go all the way to the bottom of the vertical stack of tabs, and click on the (+) bar. 
Actual Result-- Clicking on the (+) bar creates a new tab at the top of the tab stack, rather than near the current parent tab.
Desired Result-- Create new tab from context window, as usual, but place the new tab near the current group

**Comment by piroor** [comment]
How about this?: TST Configuration => New Tab => Open new blank tab as => the next sibling of the current tab

**Comment by alphaa10** [comment]
Thanks !

    "Next sibling of the
    current tab" works just as
    well as creating a new,
    blank tab ex nihilo.

    Happy New Year to you, Piroor.

    BG

    On 12/25/2015 4:08 AM,
    piroor wrote:
>
>     How about this?: TST
>     Configuration => New Tab
>     => Open new blank tab as
>     => the next sibling of
>     the current tab
>
>     —
>     Reply to this email
>     directly or view it on
>     GitHub
>     <https://github.com/piroor/treestyletab/issues/1005#issuecomment-167212324>.
>
