### ISSUE TITLE
NewTabPlus.uc.js併用時、検索ボックスから新しいタブで開いてくれない

### ISSUE THREAD

**Issue by tanakah** [piroor/treestyletab#1008]
・Windows10 64bit
・Firefox42 64bitを使用
・TSTはNightlyの最新版treestyletab.xpi 01-Dec-2015 11:28のもの を使用
・TMP等のタブ拡張機能は未使用

ロケーションバーや検索ボックスから新しいタブで開いてくれるようにしてくれるユーザースクリプトである[NewTabPlus.uc.js](http://u6.getuploader.com/script/download/1111/NewTabPlus.uc.js)というものを利用しているのですが、TSTのあるバージョンから検索ボックスから新しいタブで開いてくれなくなりました。
こちらで確認した所、TSTバージョン 0.15.20150902901までは正しく機能（検索ボックスから新しいタブで開いてくれる）していましたが、それ以降のバージョンで機能しなくなったようです。

TSTで修正するべき問題なのか、スクリプト側で修正するべき問題なのか判断がつきませんが、一応報告をしました。

**Comment by piroor** [comment]
ツリー型タブでFirefox自身の関数やメソッドを書き換えていた箇所の多くについて、これまで拘っていた「元の関数のソースを文字列として書き換えて関数を再定義するやり方」から「関数を置き換えて、必要なケースだけハンドルしてそれ以外は元の関数に委譲するやり方」に変更したのですが、その影響です。
ツリー型タブが置き換えた後の関数を`toString()`した結果は元の関数と全く異なる内容になっていますので、必要な箇所だけを`replace()`で書き換えるやり方では挙動を変えられなくなっています。
ツリー型タブが置き換える前の元の関数の方を書き換えるようにするか、ツリー型タブが今取っているのと同じようなやり方を取るようにするように、スクリプトを修正してもらうのがよいと思います。

ツリー型タブでこのように実装を変えたのは、ES6の仕様に合わせて　const/letで宣言された変数のスコープが変更された結果、関数を文字列として書き換えて再定義するやり方では再定義後に参照できなくなる変数が発生するリスクが飛躍的に増大したことが理由です。なので、残念ですが元のやり方に戻すという選択肢はありません。

**Comment by piroor** [comment]
「ツリー型タブが置き換える前の元の関数の方を書き換える」についてですが、ツリー型タブが関数を置き換えている箇所については基本的に、「`__treestyletab__元の関数名」という名前で元の関数を保持するようにしています。例えば`window.openLinkIn`は`window.__treestyletab__openLinkIn`という具合です。

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
