### ISSUE TITLE
「タブバーを自動的に縮める」設定での挙動　スクロールバーが戻ってしまう。

### ISSUE THREAD

**Issue by uriginal** [piroor/treestyletab#1009]
いつも大変お世話になっております。
数年便利にこのアドオンを使わせて頂いていますが、
この度初めて通常ウインドウ表示のとき「タブバーを自動的に縮める」設定で使用することにした際
問題が発生しています。

タブの数が多くなるとタブバーにスクロールバーが表示されるのですが
このスクロールバーを引っ張っても、タブが縮まる瞬間にまるでバネの様に元の位置に戻ってしまい、
スクロールバーを動かせません。
アドオンの入れ直しをして、設定の数値などを変更したりしてみても変わりません。

普段複数画面で使用しています、ウィンドウを一つにしても効果はありません。
ただ気になるのは複数画面で使用している際、タブバーを左に表示した状態で
左の画面へカーソルを持っていくと右画面のタブが広がったままになってしまうのが
関係ないとは思いますが少し「想定外の動きかな？」と思っています。

何か改善策などありますでしょうか。。
一度「firefoxをリフレッシュ」機能を実行して
tabmixなどタブ系のアドオンは今入れていませんがもう一度すべて削除して試した方がよろしいでしょうか。

**Comment by piroor** [comment]
これはツリー型タブ自体の問題ですね。
実は何も対策を打っていない状態だとタブバーの伸縮時にスクロール位置が0にリセットされてしまうという問題があり、伸縮の前後でスクロール位置が同じになるように内部的に対策しているのですが、それと、「スクロール位置の範囲外にあるタブがアクティブになった時は自動的にその位置までスクロールする」という処理とがバッティングしているのではないかと思います。

**Comment by uriginal** [comment]
なるほど！現象が大変よく分かりました。確かにアクティブなタブの位置に戻そうとしているようです。
スクロールバーを動かしている間に勝手にタブが縮んでしまうことが改善されればさしあたり困らなそうではありますね。。

これまでの使用されてる方に発生していなかったように見えたので自分の側の問題かと思ったのですが
待ってみるしかない様子ですね。

ありがとうございます！

**Comment by piroor** [comment]
元々の導入経緯はこれですね。
https://github.com/piroor/treestyletab/commit/bf84e78673e28232a29be02c4557f52627f9bef2
自動で「隠す」の時だけ働かせたかったようなので、自動で「縮める」のときはスクロールさせないようにしようと思います。

**Comment by piroor** [comment]
63e291b603c804de1614097b9e75d7ada544ed37 で対処したので、解消されたと思われます。

**Comment by uriginal** [comment]
解消しました！ありがとうございます！助かりました。。
