### ISSUE TITLE
When entering and exiting "Customize" mode, TreeStyleTab prints error messages to console

### ISSUE THREAD

**Issue by vi** [piroor/treestyletab#1012]
For example,
```
JavaScript error: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/tab-firefox.js, line 98: TypeError: can't access dead object
```

In general "Customize" feels less fluent and more fragile with TreeStyleTab.

**Comment by piroor** [comment]
Which version of Firefox? I don't see the error on my Firefox 42 on Windows 7.

**Comment by piroor** [comment]
If you have any other addon, it possibly triggers the error.

**Comment by vi** [comment]
38.0.6. There are a number of other addons (including TabMixPlus).

**Comment by piroor** [comment]
This still doesn't happen for me with Firefox 38.4.0 + TST + Tab Mix Plus. Combination with some other addon may trigger this error...

**Comment by piroor** [comment]
I close this for now. If the problem is still there, please add a comment.
