### ISSUE TITLE
Pinned Tab cases visual artifact when viewing full-screen HTML5 video (grey bar in top left corner)

### ISSUE THREAD

**Issue by ivanatpr** [piroor/treestyletab#1014]
Pinning tabs causes a thin grey bar to show on in the top left corner of the screen when viewing full-screen HTML5 video. [See example screenshot here](https://i.imgur.com/PzYeuwS.png). This happens when viewing any video from any tab (i.e. the tab where you're playing the video doesn't ithave to be pinned)

I've playing around with this a lot and here are a few things I've observed:

* Issue is consistently reproducible for me: the grey bar always goes away as soon as I unpin all my pinned tabs and always comes back if I set a tab back to pinned.
  * However, I noticed one very curious exception: If you change the page title of the pinned tab then the issue goes away. I noticed this because I had inbox.gmail.com pinned, which has a built in Hangouts IM client that will change the page title when you receive a message. However, I can easily reproduce the behavior by simply opening the developer tools console in the pinned tab and directly changing "document.title". The grey bar comes back if I refresh the pinned tab.
* Appears to affect any HTML5 video:
  * Youtube example (same video as screenshot): https://www.youtube.com/watch?v=5BhHkvHcUfo
The width of the bar appears to follow the width of the pinned tab.
  * Non-Youtube examples showing multiple video formats:  http://www.quirksmode.org/html5/tests/video.html
* Issue is present regardless of the value of "extensions.treestyletab.pinnedTab.faviconized" in about:config. 
* The width of the grey bar seems to equal the width of the pinned tab. It'll be very short if the tab is faviconized. Otherwise, if not faviconized, I can make it wider or shorter by adjusting the width of the tab bar.
* It doesn't seem to matter what the pinned tab is. I noticed it with inbox.gmail.com, which I happen to always keep pinned, but I was able to replicate the issue by pinning other sites as well.

I have reproduced the issue with all the following versions:
* Tree Style Tab 0.16.2015113001.1-let-fixed
  * Windows 10, Firefox 42
  * Windows 7, Firefox 42 and Firefox 43
  * Windows 7, Firefox Developer Edition 44.0a2 
* Tree Style Tab Nightly 0.16.2015121100a004038
  * Windows 7, Firefox 43
  * Windows 7, Firefox Developer Edition 44.0a2

**Comment by piroor** [comment]
The commit ca63c220f9cb1a68f57b175f6799afb243663c71 should fix this.

**Comment by ivanatpr** [comment]
Can confirm that the issue appears to be fixed in Version 0.16.2015122501

Thanks piroor! I wish I could contribute code fixes myself, but I don't know my way around XUL yet and I have limited experience with Javascript. However, I am a professional software developer (mainly do backend work using C#, SQL, Java, Python Bash, etc...) and quick learner, so if you have any tasks or issues I might be able to help with, please reach out to me.

**Comment by piroor** [comment]
Thank you for confirmation! I close this. And, If you see any open issue (including other my addons) which can be fixed by you, please send pull requests to me freely.
