### ISSUE TITLE
Closing the parent in a collapsed tree always closes entire tree

### ISSUE THREAD

**Issue by hsvallfors** [piroor/treestyletab#1017]
When a tab tree is collapsed, closing the root tab of the tree will close the entire tree regardless of the "when parent tab is closed" setting. Not sure if this is intended or not, but I'd prefer it didn't matter if the tree is open or closed. I run the setting "promote all child tabs to the level of the current tab".

**Comment by piroor** [comment]
Seems dup of #781.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
