### ISSUE TITLE
Tab bar shrinks on scrolling

### ISSUE THREAD

**Issue by CassandraDied** [piroor/treestyletab#1018]
If you have a long list with tabs, it is shrinked, and it unshrinks on mouse over.
When you try to scroll, tab bar shrinks. You have to move mouse a little to make it large again.
All trees are collapsed, “Fix position and width” is enabled.
Narrowing and enlarging again while scrolling looks not nice. Is it a bug or by design?

**Comment by piroor** [comment]
Thanks, confirmed and fixed by these commits: 279abc811c5381d3f6c0d5ed22aa322928b4c3d3 and ff08f39190c36cd6e3933f96394a83232f11a45c
