### ISSUE TITLE
'New tab' button is missing when tab bar has scrollbar

### ISSUE THREAD

**Issue by sebenik** [piroor/treestyletab#1019]
Normally you would see the new tab button at the bottom of the tree tab view like this:
![](http://i.imgur.com/D4rFHQI.png)

In case of many tabs so that scroll-bar appears, the new tab button is missing when you scroll to the bottom of the tree view:
![](http://i.imgur.com/MylYwCB.png)

Tested on Windows 10 & Firefox 43.0.4

**Comment by piroor** [comment]
This problem doesn't happen for me. Could you try "Restore Defaults" from the toolbar customization? And, if you use Tab Mix Plus or something, confliction of both addons can cause such an issue.

**Comment by sebenik** [comment]
I disabled Tab Mix Plus and indeed that fixed the problem.
This is not a treestyletab issue.

Anyway i found a solution - open TabMixPlus options and under Display->TabBar set the show New tab button to the 'on right side' not 'after last one'.

![](http://i.imgur.com/GNgwX7B.png)

**Comment by dlricher** [comment]
WOW! that worked for me.....
