### ISSUE TITLE
Settings item in Tools menu

### ISSUE THREAD

**Issue by dogancelik** [piroor/treestyletab#1020]
**Optional** Settings menu item in Tools menu would be really handy oppose to searching for Options button in Add-ons page.

![tst](https://cloud.githubusercontent.com/assets/486818/12198255/f14a351c-b616-11e5-89e8-df0500f02f23.png)

**Comment by piroor** [comment]
I have no motivation to add such a menu item, sorry. See the comment: https://github.com/piroor/treestyletab/issues/940#issuecomment-144966907

**Comment by dogancelik** [comment]
Is there a function to open Settings dialog like below?
```js
coomanPlus.openCookieEditor();
s3menuwizard.open_options_window();
```
So users can add the item themselves

**Comment by piroor** [comment]
No such function. TST's configuration dialog is only shown by Firefox's addon manager -　I entrust anything around the configuration dialog to Firefox itself, so I really don't know details how to do it manually. And I believe that it is not a task of addon authors.

**Comment by piroor** [comment]
In other words, I don't want to treat how to open configuration dialogs by myself because the most well-mannered way to open configuration UI of addons can change on future versions of Firefox. I hope to spend more time to fix other critical bugs instead of maintaining such unnecessary codes.

**Comment by piroor** [comment]
And, as my comments on the referred issue #940, if you are annoyed by something and you have to open TST's configuration dialog again and again, then the problem should be solved with any other method better than adding menu item to open the configuration dialog.

**Comment by dogancelik** [comment]
Thank you for sharing your thoughts.

I found a way to open Settings dialog using [S3 Menu Wizard](https://addons.mozilla.org/en-US/firefox/addon/s3menu-wizard/)

### Steps

Create an item and put this code in *onCommand* event
```js
openDialog('chrome://treestyletab/content/config.xul', '', 'chrome,titlebar,toolbar,centerscreen,modal');
```

and use this CSS to change the icon of the menu item:
```
list-style-image: url('chrome://treestyletab/content/res/icon.png');
```

### Result
![result](https://cloud.githubusercontent.com/assets/486818/12368056/539a3b8e-bbf0-11e5-928a-eb1250c23d8b.png)

Hope it helps people with same request :)

**Comment by piroor** [comment]
Thanks!
