### ISSUE TITLE
Pressing Ctrl to show the panel on auto-hide mode conflict with browser.ctrlTab.previews

### ISSUE THREAD

**Issue by ooker777** [piroor/treestyletab#1023]
I set the `browser.ctrlTab.previews` to `true`, then I cannot make the panel reveals when pressing the <kbd>Ctrl</kbd> button. If possible, I prefer to modify the trigger to another key or combination.

**Comment by piroor** [comment]
The commit 9302255cf9593c4a7d41df19b04c3922a24044b7 should fix this.

**Comment by ooker777** [comment]
I'm not really familiar with GitHub, can you show me how to implement this code? Thanks.

**Comment by piroor** [comment]
The development build from the latest code is available: http://piro.sakura.ne.jp/xul/xpi/nightly/
Note, you'll have to disable signature check to ignore "unsigned package" error. http://stackoverflow.com/questions/31952727/how-can-i-disable-firefox-addons-signature-checking

**Comment by ooker777** [comment]
it works, thanks
