### ISSUE TITLE
Show bar on tab change

### ISSUE THREAD

**Issue by edrex** [piroor/treestyletab#1024]
I use tree style tab with VimFx, to provide a keyboard driven experience with a tab tree. The two plugins work nicely together.

My one complaint is, with the tab bar set to auto hide, when I switch tabs using a keyboard shortcut (either `Ctrl-Tab` or VimFx' `J`/`K`) the tab bar remains hidden.

I'd like to propose that the auto hide tab bar shows itself whenever the currently active tab changes. What do you think? Sorry if this is a duplicate, lots of issues to search through :)

PS: Thank you for making tree style tab, it is excellent.

**Comment by lydell** [comment]
Go to: Tree Style Tab Preferences > Auto Hide > Show tab bar automatically when

Enable:

- Control-Tab to switch tabs
- New tabs are opened or some tabs are closed

**Comment by edrex** [comment]
oh, perfect! I should have looked into the prefs more first.
