### ISSUE TITLE
Hovering tab bar moves focus off text box (Gmail only)

### ISSUE THREAD

**Issue by jimbo1qaz** [piroor/treestyletab#1026]
0.16.2015122501 on Firefox Dev 45.0a2.

I was writing a Gmail message, then my mouse moved over the tab bar. The message editor lost focus, instead focusing the page (backspace changed pages instead of deleting text).

**Comment by piroor** [comment]
This doesn't happen on my Firefox 43 + [TST development build](http://piro.sakura.ne.jp/xul/xpi/nightly/). Is this Firefox 45 specific issue?

**Comment by piroor** [comment]
I close this for now. If the problem is still there, please add a comment.
