### ISSUE TITLE
Child tabs open in the wrong position

### ISSUE THREAD

**Issue by ivan** [piroor/treestyletab#1030]
After upgrading from 3a7577d22c9b8ed4c343b1a1cc3107162b958013 to d5b05b6017c8102e11b15bc1fc463d412ef34678, I frequently see child tabs open in the wrong position, like this:

```
Root tab
  new tab opens here
  A
  B
  C
  D
```

```
Root tab
  new tab opens here
  A
  new tab opens here
  B
  C
  D
```

```
Root tab
  new tab opens here
  A
  new tab opens here
  B
  new tab opens here
  C
  D
```

I am using Firefox 43.0.4 on Ubuntu and I have the 'Insertion position of new child tabs' set to 'Insert to the top of the tree, as the first child'

Possibly related to #1028.

**Comment by piroor** [comment]
Thanks. Commits 0dab3f30ec675484019a043a0bbfffcaa22e6967 and 84c08225928a4d93620a8467cf2f4339fa9063ab should fix this issue.

**Comment by ivan** [comment]
Thanks for the fix!  I haven't had any further problems.
