### ISSUE TITLE
Issues and Requests

### ISSUE THREAD

**Issue by rayman89** [piroor/treestyletab#1031]
When changing the options for what happens with new tabs after you change the middle click the new tabs created/grouped will be always without title and favicon. Restarting the browser fixes it.

This add-on affects how the new tabs open and opening a new tab with TMP how i have it configured should open next to the current tab but with this add-on installed it opens as the last tab.

Would it be possible to make the tabs that belong to a tree be colored by group (each group a different color).

A way to specify what happens when you open links from a page right now it always makes them childs or siblings I would like to be able to make them open as independent tabs (maybe make a combination of x + middle click on a link from a page makes them open as independent tabs).

The option to auto contract a group when you click on an independent tab

The ability to contract the group by double clicking on any tab of the group not just the parent.

When using it with multiple tab handler to create a new group would it be possible to have the option to make the first tab the visible tab of the group instead of creating a new folder like tab?

Thanks for making, maintaining this add-on and for taking the time to read this.

**Comment by piroor** [comment]
Could you post one issue per one topic? One issue with multiple topics is very hard to be tracked.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
