### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by rayman89** [piroor/treestyletab#1034]
Could you consider:

1)  Making a way to specify what happens when you open links from a page right now it always makes them childs or siblings I would like to be able to make them open as independent tabs (maybe make a combination of x + middle click on a link from a page makes them open as independent tabs).

2) The option to auto contract a group when you click on an independent tab

3) The ability to contract the group by double clicking on any tab of the group not just the parent.

4) When using it with multiple tab handler to create a new group would it be possible to have the option to make the first tab the visible tab of the group instead of creating a new folder like tab?

Thanks for making, maintaining this add-on and for taking the time to read this.

PD: Is it ok to make 1 topic for more than 1 request or should I spread these as well?

**Comment by rayman89** [comment]
Also It would be nice to have the option to break a tree and make all the elements independent tabs cause as now you have to drag the tabs out of the tree to make them independent.

**Comment by piroor** [comment]
> PD: Is it ok to make 1 topic for more than 1 request or should I spread these as well?

If there are multiple sub requests strongly depending on a request, then I think they can be posted as an issue. Otherwise, requests in different contexts should be different issues.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
