### ISSUE TITLE
Bookmarks from sidebar opened as child tabs

### ISSUE THREAD

**Issue by heftig** [piroor/treestyletab#1036]
Current behavior: Middle-clicking on a bookmark in the sidebar opens the bookmark as a child to the current tab.

Expected behavior: The bookmark should be opened as a new root tab at the end of the bar.

TST master, FDE 46.0a2

**Comment by piroor** [comment]
Recent changes can affect to this issue. Could you try the latest development build again?

**Comment by heftig** [comment]
Fixed, thanks.
