### ISSUE TITLE
Draggin tabs from one window to an other Issue

### ISSUE THREAD

**Issue by rayman89** [piroor/treestyletab#1037]
I dont know if this is an issue or is just not implemented but when dragin and droping the parent tab of a tree from window A to window B only that tab you are dragging will be put on window B and it will always be placed at the end of the tabs independently of where you pointed it should go. 

If try to drag in combination with multiple tab handler and select the whole tree and drag the tabs to an other window  all the tabs will be put as independent tabs at the end of the tab list independently of where you pointed it should go

**Comment by piroor** [comment]
When a parent tab is moved between multiple windows, all descendant tabs are expected to be moved also. This seems a regression. Sorry.

**Comment by piroor** [comment]
After these commits it works for me now: fe7cf571f57893ece3e22e3db33c91f1fe021b54, 49a025a1da619550e0e30685db12bae9075f4c14, and 120dc6b52204b76e8d276ec51ebb65fc072b8f71.

**Comment by rayman89** [comment]
Thanks it works now.
