### ISSUE TITLE
Cannot collapse/expand tabs in horizontal layout

### ISSUE THREAD

**Issue by mnieber** [piroor/treestyletab#1039]
When I put the tabs at the top of the screen, they have no buttons to collapse or expand the tab group (these only appear when I put the tabs on the left of the screen).

Firefox version 42 on Linux Mint

**Comment by piroor** [comment]
See the configuration dialog. Ability to collapse/expand tree is customizable for each direction.

**Comment by mnieber** [comment]
Aha, great!
