### ISSUE TITLE
Does not show tabs in latest Pale Moon

### ISSUE THREAD

**Issue by darnkitten** [piroor/treestyletab#1043]
In Pale Moon 25.8 and Pale Moon 26, no tab bar was displayed anywhere, though closing the window still gave a "closing ## tabs" warning.

**Comment by piroor** [comment]
Tree Style Tab now drops support for versions older than Firefox 38. Sorry, I never support expired versions of Firefox (and other projects based on such versions) anymore. If you really need TST for them, fork this project and rollback to an old revision which supports the version of Firefox you are using. Thanks.
