### ISSUE TITLE
Show tab-bar automatically when switching tabs in Vimperator

### ISSUE THREAD

**Issue by psamim** [piroor/treestyletab#1044]
Hi,

There is an option in the auto-hide section to show tab-bar automatically when switching tabs. It does not work when switching tabs with Vimperator.

Thanks

**Comment by piroor** [comment]
"TST Configuration" => "Auto Hide" => "Show tab bar automatically when" => "New tabs are opened or some tabs are closed" will do it. However it has some subeffects - the tab bar will be shown when you close any tab, and the tab bar will be collapsed automatically after a delay.

**Comment by psamim** [comment]
@piroor Thanks!
