### ISSUE TITLE
タブを一番上か下までスクロールすると、タブバーが自動で縮まってしまう

### ISSUE THREAD

**Issue by 888kk** [piroor/treestyletab#1045]
ブログのBBSにも書かせて頂きましたが、

>「タブバーを自動的に縮める」に設定した際、
>マウスカーソルをタブ上に置いてタブバーを広げた状態で、
>スクロールバーを一番上か一番下まで持っていくと、
>マウスカーソルの位置に関わらず勝手にタブバーが縮んでしまいます。

上記の事象について、
pcxFirefoxのver44.0x64上で
ツリー型タブ0.16.2015122501をインストール中に事象が発生しておりました。
アナウンス頂いたnightlyの0.16.2016012800a214113に更新したところ発生しなくなりました。

再現性確認のため、pcxFirefoxのv44.0x64をポータブル環境で新たにインストールし、
ツリー型タブ0.16.2015122501のみを入れた状態で事象の確認を行ったところ再現しました。

その際のツリー型タブの設定は以下の様に変更しております。
「自動的に隠す」-「通常のウインドウ表示の時」-「タブバーを自動的に縮める」にチェック
反応する領域：0ピクセルの範囲
遅延：0ミリ秒
以上の状態で、
スクロールバーが出現するまでタブを複数個開き、同様の操作を行うと事象が再現しました。
その様子をgifを撮影しましたのでご確認下さい。
http://i.imgur.com/k1Rlu27.gifv

**Comment by piroor** [comment]
確認いただいてありがとうございます。開発版の方で直っているようであれば修正済みということにする運用なので、本件は解決ということにさせてくださいませ。（新しい問題がどんどん報告されるので、キリのいい所でのリリースにこぎ着けられていないです。すみません）

**Comment by piroor** [comment]
新しいバージョンをリリースしたのでcloseします。
