### ISSUE TITLE
Pinned tab layout issues Linux

### ISSUE THREAD

**Issue by Arkonos** [piroor/treestyletab#1046]
While pinned tabs get displayed like I expect them to on Windows, I can't say the same for Linux.

Default, Sidebar Theme:
http://puu.sh/n07jQ/759b4add76.png
Icons appear but hide folders and bookmarks

Metal, Mixed, Flat, Plain Theme:
http://puu.sh/n07nc/bb6668cca1.png
Only last pinned tab appears, others are clickable via the thin line on top.
Pinned tab shown (here Youtube) completely blocks first bookmark

Vertigo Theme:
http://puu.sh/n07vw/4a4508819d.png
Same as before, but this time, the first bookmark is visible but still not clickable.

Location of the clickable thin line varies for different themes.

Works on Windows 8 & 10 x64 with FF44.0
Does not work on Fedora 23 x64 with FF44.0
Same Hardware for Windows 10 and Fedora, different PC for Win 8
Addon version 0.16.2015122501
Addon settings identical

**Comment by Rhotias** [comment]
I'm on Fedora 22 x64 (GNOME 3.16.2) with FF44.0, and TST 0.16.2015122501 displays pinned tabs properly with all skins. You may have another addon that isn't behaving properly in Linux, have you tried disabling everything besides TST?

**Comment by Arkonos** [comment]
I thought I had disabled every tab related addon, but I missed classic theme restorer. Weirder still as I also have it active on the windows machines.
Sorry for this then.
