### ISSUE TITLE
Setting "fixed position" + "tabs on top" leads to occluded notifications

### ISSUE THREAD

**Issue by mnieber** [piroor/treestyletab#1047]
If you have the tabs on top with a fixed position and height, then firefox notifications (for example: from the key store) almost entirely disappear: the left-most part is still visible, but most of the notification is painted over with the normal screen content.

There is a good work-around though: just disable "fix position and height".

**Comment by piroor** [comment]
On Ubuntu, I couldn't reproduce this.Could you add screenshots?

**Comment by mnieber** [comment]
I'm on Linux Mint, this is what it looks like

![treetabbug](https://cloud.githubusercontent.com/assets/818892/12997477/f1058bf4-d139-11e5-94ce-d773fd237077.png)

**Comment by piroor** [comment]
Here are detailed result of my research: #1132
For aggregation I add "duplicated" tab to this and close.
