### ISSUE TITLE
新しいタブを開く際の不具合

### ISSUE THREAD

**Issue by 888kk** [piroor/treestyletab#1048]
Nightlyの0.16.2016012800a214113にて、
新規タブを開く際の挙動に不具合がありましたので報告します。

「新しいタブ」設定で、
「新しい空のタブを【現在のタブの子】として開く」と設定した時に、
新しいタブが右端（ツリーで言うと一番下）に開いてしまいます。
ver0.16.2015122501では正常に動作するのを確認しています。

**Comment by piroor** [comment]
すみません。多分 bb4a172308d46ee6a1b538546bccdefb18745645 で直ったと思います。

**Comment by piroor** [comment]
新しいバージョンをリリースしたので一旦closeとします。
