### ISSUE TITLE
Tabbar resets to 5 px after restart of ff (mac only)

### ISSUE THREAD

**Issue by gitgetgot** [piroor/treestyletab#1049]
Hi,
I have ff 43.0.4. on mac with el capitan.

Settings for tst are:

```
tab bar position (.) right

[ ] Fix position and witdth of tab bar : 333 px width
```
but on every ff restart, the tabbar is very small and I need to resize it by hand to the correct size.

I  have the same settings on my win7 pc with the same firefox version and its working great, as expected. Only mac has problems.

I wanted you to send my settings, but it seems, they're not fully stored in prefs.js or in extensions.json.
Anyhow, here are the settings, I found in prefs.js
`user_pref("extensions.treestyletab.allowSubtreeCollapseExpand.vertical", false);
user_pref("extensions.treestyletab.autoCollapseExpandSubtreeOnAttach", false);
user_pref("extensions.treestyletab.autoCollapseExpandSubtreeOnSelect", false);
user_pref("extensions.treestyletab.maxTreeLevel.vertical", 300);
user_pref("extensions.treestyletab.openGroupBookmark.behavior", 2817);
user_pref("extensions.treestyletab.prefsVersion", 11);
user_pref("extensions.treestyletab.show.context-item-reloadDescendantTabs", true);
user_pref("extensions.treestyletab.show.context-item-removeAllTabsButThisTree", true);
user_pref("extensions.treestyletab.show.context-item-removeDescendantTabs", true);
user_pref("extensions.treestyletab.tabbar.autoHide.area", 10);
user_pref("extensions.treestyletab.tabbar.autoHide.mode.fullscreen", 2);
user_pref("extensions.treestyletab.tabbar.autoHide.mode.toggle", 1);
user_pref("extensions.treestyletab.tabbar.autoHide.mode.toggle.fullscreen", 2);
user_pref("extensions.treestyletab.tabbar.autoShow.accelKeyDown", false);
user_pref("extensions.treestyletab.tabbar.fixed.horizontal", false);
user_pref("extensions.treestyletab.tabbar.height", 28);
user_pref("extensions.treestyletab.tabbar.narrowScrollbar", false);
user_pref("extensions.treestyletab.tabbar.position", "right");
user_pref("extensions.treestyletab.tabbar.shrunkenWidth", 36);
user_pref("extensions.treestyletab.tabbar.style", "flat");
user_pref("extensions.treestyletab.tabbar.width", 285);
user_pref("extensions.treestyletab.tabsOnTop.originalState", false);
user_pref("extensions.treestyletab.tooltip.mode", 0);
user_pref("extensions.treestyletab.twisty.style", "retro");
user_pref("extensions.treestyletab@piro.sakura.ne.jp.install-event-fired", true);
`
and what I've found in extensions.json
`{"id":"treestyletab@piro.sakura.ne.jp","syncGUID":"PT5n5_IZ69_X","location":"app-profile","version":"0.16.2015122501","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":"chrome://treestyletab/content/config.xul","optionsType":null,"aboutURL":null,"iconURL":"chrome://treestyletab/content/res/icon.png","icon64URL":null,"defaultLocale":{"name":"Tree Style Tab","description":"Show tabs like a tree.","creator":"YUKI \"Piro\" Hiroshi","homepageURL":"http://piro.sakura.ne.jp/xul/_treestyletab.html.en"},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Users/user/Library/Application Support/Firefox/Profiles/xwn3hruw.default/extensions/treestyletab@piro.sakura.ne.jp.xpi","installDate":1429380747000,"updateDate":1451232837000,"applyBackgroundUpdates":1,"bootstrap":false,"size":1330574,"sourceURI":"https://addons.cdn.mozilla.net/user-media/addons/5890/tree_style_tab-0.16.2015122501-fx.xpi?filehash=sha256%3A53b6621f631425920b415ce17dfa487877eb4101fe1c4df17030a0e2d68e4583","releaseNotesURI":"https://addons.mozilla.org/versions/updateInfo/1793268/en-US/","softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[{"locales":["en-US"],"name":"Tree Style Tab","description":"Show tabs like a tree.","creator":"YUKI \"Piro\" Hiroshi","homepageURL":"http://piro.sakura.ne.jp/xul/_treestyletab.html.en","contributors":["Zusukar (auto-shrink mode)","Alice0775 (compatibility problem)","Philipp von Weitershausen (Sidebar style)","wanabe (some bug fixes)","Tetsuharu OHZEKI (code cleanup)","mnoorenberghe (Firefox 36 support)","Xidorn Quan (Firefox 40+ support)"]},{"locales":["ja"],"name":"ツリー型タブ","description":"タブをツリー状に表示します。","creator":"YUKI \"Piro\" Hiroshi","homepageURL":"http://piro.sakura.ne.jp/xul/_treestyletab.html","contributors":["Zusukar (auto-shrink mode)","Alice0775 (compatibility problem)","Philipp von Weitershausen (Sidebar style)","wanabe (some bug fixes)","Tetsuharu OHZEKI (code cleanup)","mnoorenberghe (Firefox 36 support)","Xidorn Quan (Firefox 40+ support)"]},{"locales":["it-IT"],"name":"Tree Style Tab","description":"Permette di visualizzare la barra delle schede in forma di albero","creator":"YUKI \"Piro\" Hiroshi","homepageURL":"http://piro.sakura.ne.jp/xul/_treestyletab.html.en","translators":["Godai71.Extenzilla (it-IT locale)"],"contributors":["Zusukar (auto-shrink mode)","Alice0775 (compatibility problem)","Philipp von Weitershausen (Sidebar style)","wanabe (some bug fixes)","Tetsuharu OHZEKI (code cleanup)","mnoorenberghe (Firefox 36 support)","Xidorn Quan (Firefox 40+ support)"]},{"locales":["zh-CN"],"name":"Tree Style Tab","description":"以树的形式显示标签。","creator":"YUKI \"Piro\" Hiroshi","homepageURL":"http://piro.sakura.ne.jp/xul/_treestyletab.html.en","translators":["Fatiaomao (zh-CN locale)","hzhbest (zh-CN locale)"],"contributors":["Zusukar (auto-shrink mode)","Alice0775 (compatibility problem)","Philipp von Weitershausen (Sidebar style)","wanabe (some bug fixes)","Tetsuharu OHZEKI (code cleanup)","mnoorenberghe (Firefox 36 support)","Xidorn Quan (Firefox 40+ support)"]},{"locales":["es-ES"],"name":"Tree Style Tab (Pestañas estilo árbol)","description":"Muestra las pestañas en vista de árbol","creator":"YUKI \"Piro\" Hiroshi","homepageURL":"http://piro.sakura.ne.jp/xul/_treestyletab.html.en","translators":["tito (es-ES locale)"],"contributors":["Zusukar (auto-shrink mode)","Alice0775 (compatibility problem)","Philipp von Weitershausen (Sidebar style)","wanabe (some bug fixes)","Tetsuharu OHZEKI (code cleanup)","mnoorenberghe (Firefox 36 support)","Xidorn Quan (Firefox 40+ support)"]},{"locales":["de-DE"],"name":"Tree Style Tab","description":"Stellt Tabs in einer Baumstukur dar","creator":"YUKI \"Piro\" Hiroshi","homepageURL":"http://piro.sakura.ne.jp/xul/_treestyletab.html.en","translators":["Andy Pillip (de-DE locale)"],"contributors":["Zusukar (auto-shrink mode)","Alice0775 (compatibility problem)","Philipp von Weitershausen (Sidebar style)","wanabe (some bug fixes)","Tetsuharu OHZEKI (code cleanup)","mnoorenberghe (Firefox 36 support)","Xidorn Quan (Firefox 40+ support)"]},{"locales":["zh-TW"],"name":"Tree Style Tab","description":"樹狀分頁顯示。","creator":"YUKI \"Piro\" Hiroshi","homepageURL":"http://piro.sakura.ne.jp/xul/_treestyletab.html.en","translators":["HkYtrewq (zh-TW locale)","Tsprajna (zh-TW locale)","bootleq (zh-TW locale)"],"contributors":["Zusukar (auto-shrink mode)","Alice0775 (compatibility problem)","Philipp von Weitershausen (Sidebar style)","wanabe (some bug fixes)","Tetsuharu OHZEKI (code cleanup)","mnoorenberghe (Firefox 36 support)","Xidorn Quan (Firefox 40+ support)"]},{"locales":["ru"],"name":"Tree Style Tab (Древовидный стиль вкладок)","description":"Отображение вкладок в виде дерева","creator":"YUKI \"Piro\" Hiroshi","homepageURL":"http://piro.sakura.ne.jp/xul/_treestyletab.html.en","translators":["L'Autour (ru locale)","Infocatcher (ru locale)"],"contributors":["Zusukar (auto-shrink mode)","Alice0775 (compatibility problem)","Philipp von Weitershausen (Sidebar style)","wanabe (some bug fixes)","Tetsuharu OHZEKI (code cleanup)","mnoorenberghe (Firefox 36 support)","Xidorn Quan (Firefox 40+ support)"]},{"locales":["pl"],"name":"Tree Style Tab","description":"Wyświetla karty w układzie drzewa.","creator":"YUKI \"Piro\" Hiroshi","homepageURL":"http://piro.sakura.ne.jp/xul/_treestyletab.html.en","translators":["Leszek(teo)Życzkowski (pl locale)"],"contributors":["Zusukar (auto-shrink mode)","Alice0775 (compatibility problem)","Philipp von Weitershausen (Sidebar style)","wanabe (some bug fixes)","Tetsuharu OHZEKI (code cleanup)","mnoorenberghe (Firefox 36 support)","Xidorn Quan (Firefox 40+ support)"]},{"locales":["fr-FR"],"name":"Tree Style Tab","description":"Show tabs like a tree.","creator":"YUKI \"Piro\" Hiroshi","homepageURL":"http://piro.sakura.ne.jp/xul/_treestyletab.html.en","translators":["Laurent Haas (fr-FR locale)","AxlMun (fr-FR locale)"],"contributors":["Zusukar (auto-shrink mode)","Alice0775 (compatibility problem)","Philipp von Weitershausen (Sidebar style)","wanabe (some bug fixes)","Tetsuharu OHZEKI (code cleanup)","mnoorenberghe (Firefox 36 support)","Xidorn Quan (Firefox 40+ support)"]},{"locales":["sv-SE"],"name":"Tree Style Tab","description":"Visar flikar i en trädstruktur.","creator":"Hiroshi Shimoda","homepageURL":"http://piro.sakura.ne.jp/xul/_treestyletab.html.en","translators":["Mikael Hiort af Ornäs (sv-SE)"],"contributors":["Zusukar (krymp automatiskt-läget)","Alice0775 (kompatibilitetsproblem)","Philipp von Weitershausen (sidopanelens utseende)","wanabe (some bug fixes)","Tetsuharu OHZEKI (code cleanup)","mnoorenberghe (Firefox 36 support)","Xidorn Quan (Firefox 40+ support)"]},{"locales":["da-DK"],"name":"Tree Style Tab","description":"Viser faner som mappetræer.","creator":"Hiroshi Shimoda","homepageURL":"http://piro.sakura.ne.jp/xul/_treestyletab.html.en","translators":["Regmos (da-DK)"],"contributors":["Zusukar (auto minimering)","Alice0775 (kompatibilitetsproblem)","Philipp von Weitershausen (sidebjælkens stil)","wanabe (some bug fixes)","Tetsuharu OHZEKI (code cleanup)","mnoorenberghe (Firefox 36 support)","Xidorn Quan (Firefox 40+ support)"]},{"locales":["cs"],"name":"Tree Style Tab","description":"Uspořádává panely do stromu.","creator":"YUKI \"Piro\" Hiroshi","homepageURL":"http://piro.sakura.ne.jp/xul/_treestyletab.html.en","translators":["Vlastimil Ovčáčík (cs)"],"contributors":["Zusukar (auto-shrink mode)","Alice0775 (compatibility problem)","Philipp von Weitershausen (Sidebar style)","wanabe (some bug fixes)","Tetsuharu OHZEKI (code cleanup)","mnoorenberghe (Firefox 36 support)","Xidorn Quan (Firefox 40+ support)"]}],`

Let me know, if I can be of further assistance...

**Comment by piroor** [comment]
On Ubuntu, I couldn't reproduce this.

Could you try the latest development build? http://piro.sakura.ne.jp/xul/xpi/nightly/
And, if you use any other addon, could you confirm that this happens with no other addon except TST itself?

**Comment by gitgetgot** [comment]
its fixed. 
I now switch to another vertical tab manager as recommended, thank you.
