### ISSUE TITLE
Scrollbar doesn't work

### ISSUE THREAD

**Issue by SlugFiller** [piroor/treestyletab#1051]
Windows 10, Firefox 47.0a1, treestyletab a1c378f7b4fef4629c6709e37d1840d9e34cb7fd. Scrolling with the mousewheel works, but clicking anywhere on the scrollbar has no effect. Dragging the scrollbar drags the whole window.

This might have to do with the RTL scrollbar. I get the attempt to make the scrollbar look nice, but so long as it's non-functional, I'd rather just have this optional, and have a working, if a bit less pretty, scrollbar.

**Comment by piroor** [comment]
I've tested Nightly 47.0a1 64bit on Windows 10 with TST master HEAD with no other addon, but the problem does not appear for me. Do you use any other addon related the tab bar?

**Comment by SlugFiller** [comment]
Session Manager and Auto Unload Tab, but neither should have any influence on tab bar appearance. It seems the scroll bar behaves like the window's title bar. Double clicking on it causes the window to become maximized, as well.

Most of the settings are on default value except:
extensions.treestyletab.autoCollapseExpandSubtreeOnAttach;false
extensions.treestyletab.autoCollapseExpandSubtreeOnSelect;false
extensions.treestyletab.tabbar.narrowScrollbar;false

Theme is Mixed and twisties are set to Auto.
Windows theme is the "Windows" default theme.

**Comment by SlugFiller** [comment]
I just want to point out that this is still not working for me. Due to the changes in Firefox's addon signing policy, I am only able to test the release version marked 0.17.2016031101. However, I am testing it on Nightly 49.0a1 (2016-04-27).

The scrollbar continues to behave like the window title when clicked, dragged, or double clicked. Additionally, I've confirmed that this doesn't happen to other RTL scrollbars. If there's some way I can reproduce a similar scrollbar in a web page, and reproduce the error, I might be able to submit this upstream. But, for the moment, I can only reproduce this with the scrollbar produced by TST.

Also, I don't know if this matters, but I can get similar behavior by clicking on the empty area left of a child tab.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
