### ISSUE TITLE
Option to ask what to do when closing a tab tree parent

### ISSUE THREAD

**Issue by Vampire** [piroor/treestyletab#1053]
Currently there is an option where you can configure what to do if a tab tree parent is closed (close sub-tabs, promote sub-tabs, take first as new parent, ...).
I'd like to have an option that I get asked what to do when closing a tab tree parent.

**Comment by piroor** [comment]
Nice idea!

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
