### ISSUE TITLE
Option to additionally show the normal tab bar

### ISSUE THREAD

**Issue by Vampire** [piroor/treestyletab#1054]
I would like to have the tree style display at the left to see a nice tree view (horizontally this doesn't display too nice the hierarchy), but additionally have the normal tab bar.
So it would be great to have the option to additionally show the standard tab bar.

**Comment by piroor** [comment]
Because TST's "tree-like tabs" is the Firefox's tab bar itself, we cannot show both Firefox's original version and modified by TST version in same time.
