### ISSUE TITLE
Option to not expand trees automatically

### ISSUE THREAD

**Issue by Vampire** [piroor/treestyletab#1055]
It would be nice to have an option to not automatically expand a tree on selection.
Currently if I click on a tree parent, the tree gets expanded. But I only want to see the parent unless I explicitly expand the tree by exand icon or double-click

**Comment by piroor** [comment]
See TST's configuration dialog's "Tree" pane. The second checkbox does it.

**Comment by Vampire** [comment]
Then the german localization is wrong. The second checkbox reads "Nicht aktive Zweige zuklappen" which in english means "Collapse inactive trees"

**Comment by piroor** [comment]
Oh, it should be corrected. Could you update the translation and send it as a pull request? You can do it with these steps:

 1. Go to https://github.com/piroor/treestyletab/blob/master/locale/de-DE/treestyletab/treestyletab.dtd
 2. Click the "Edit this file" button (pencil icon).
 3. Fix the translation.
 4. Choose "Create a new branch for this commit and start a pull request." and click the "Propose file change" button.

**Comment by Vampire** [comment]
Well, I prefer doing a fork and using proper tools locally. :-)
Anyway, I went over the whole German file and adapted the translations to the en-US file.
Here you are: #1059 :-)

**Comment by piroor** [comment]
Thanks a lot again! I close this.
