### ISSUE TITLE
Trees for pinned tabs

### ISSUE THREAD

**Issue by Vampire** [piroor/treestyletab#1056]
It would be cool to have tab trees also in the pinned tabs. :-)

**Comment by piroor** [comment]
I cannot imagine how it works. Could you draw a sketch?

**Comment by Vampire** [comment]
Something like this:
![mockup](https://cloud.githubusercontent.com/assets/325196/12982079/ad914db4-d0e3-11e5-9caa-db6c10375168.png)

**Comment by piroor** [comment]
Thanks. Hmm, but I usually use vertical tab bar, and the mockup seems not suitable for pinned tabs in the vertical tab bar...(In vertical tab bar, pinned tabs are placed like icons on the destkop.)

**Comment by Vampire** [comment]
Doesn't make any difference, does it?
![mockup-vertical](https://cloud.githubusercontent.com/assets/325196/13004601/aba852c4-d17c-11e5-8ff7-bf205ae6d7f1.png)

**Comment by piroor** [comment]
Sorry, I think that such a micro indentation is not good feedback indicating the pinned tab is a child of a preceding not-indented tab. When the width of the tab bar is thinner than total width of all pinned tabs, they are shown like:

~~~
[A][B][C][D][H]
[I][J]
[K            ]
[L            ]
[M            ]
...
~~~

Then, if the tab `[D]` has three children `[E]`, `[F]`, and `[G]`, they will be expanded as:

~~~
[A][B][C][D][E]
[F][G][H][I][J]
[K            ]
[L            ]
[M            ]
...
~~~

I think indentation doesn't match to such flow-able items.

**Comment by Vampire** [comment]
Well, even if indentation is not applied (I think you could make this separately configurable as currently for not-pinned tabs if you think some people like to indent normal tabs but not pinned tabs. But what I really would like to have is to be able to reload all those tabs at once or collapse them if I don't need them all at once currently. :-)

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
