### ISSUE TITLE
Duplicate extension name

### ISSUE THREAD

**Issue by sergwish** [piroor/treestyletab#1057]
With Russian language pack as default, add-ons manager shows extension name as
Tree Style Tab (Древовидный стиль вкладок)
which has both English and Russian names. Essentially, the name is duplicated. Name that long also widens add-ons sidebar contents in OmniSidebar too much.

Please, either remove English name or Russian name, e.g. like in Session Manager.

**Comment by piroor** [comment]
Thanks. The commit f5348dc fixes it.
