### ISSUE TITLE
[Tab Mix Plus] regression in 0.16.2016021201

### ISSUE THREAD

**Issue by her34** [piroor/treestyletab#1058]
i tried new version 0.16.2016021201 and found regressions. both bugs do not happen in 0.16.2015122501.
1. open group of bookmarks always takes focus. In tab mix plus there is option under 'events', 'tab opening', focus from 'group of bookmarks'. even when box is un-checked new TST will make group of bookmarks take focus.
2. when opening new tab, during loading there is a spinning circle animating and whole tab blinks/flickers during tab loading. the whole tab (spinning circle and tab title text) all blink really fast until tab finishes loading then it stops.

**Comment by sifusor** [comment]
The "open all in tabs" problem still happens in Ver.0.17.2016030402. I set bookmark groups to open in background but it doesn't work.

Will this be fixed soon?

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
