### ISSUE TITLE
[Tab Mix Plus] タブをロックしてそのタブ中のリンクを開こうとするとそのタブで開かれる

### ISSUE THREAD

**Issue by machaking** [piroor/treestyletab#1060]
Firefox標準機能であるロック機能でタブをロックしてもそのタブでリンクを開いてしまいます。(本来なら新しいタブに開かれる)
このアドオンを切ったところロック機能復活、一つ前のバージョンでは異常無かったので現在はそれを使っています。
Ver.ツリー型タブ (Tree Style Tab) 0.16.2016021201 
　　  FireFox 44.0.2

**Comment by piroor** [comment]
Firefox標準の機能にはタブをロックするという物は無かったと思います。
ピン留めのことでしょうか？

**Comment by machaking** [comment]
あ、すいません確認しましたところ標準ではなくてTabMixPlusの機能でした。
このアドオンと競合してるんでしょうかね？

**Comment by piroor** [comment]
#1058 でも報告がありますが、TMPとの併用時の動作で問題が生じているようです。
この2件以外にもまだまだ何か起こっていそうな気がします。
自分はTMPを使っていないので、確認できておりませんが……

**Comment by machaking** [comment]
了解しました。
それ以上のことは解らないので前バージョンで様子見ることにします。
ありがとうございました。

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
