### ISSUE TITLE
Regression in 'Add secret preferences to control feedback cases' commit

### ISSUE THREAD

**Issue by Happy-Dude** [piroor/treestyletab#1061]
Hey piroor,

There is a regression in commit 799504b8bf54492103973c49e3cfd783e54a586f; after making the XPI for the addon with this commit, TreeStyleTabs appears like the following:

<img width="94" alt="screen shot 2016-02-13 at 1 08 03 pm" src="https://cloud.githubusercontent.com/assets/1098725/13029218/af35b8c8-d253-11e5-935d-44fa9070e7ce.png">

I am not sure what could have caused this bug. Can you investigate?

**Comment by piroor** [comment]
Sorry, fixed by be6df2121f0aa82cdd5877e81717221aafe94bdc.
