### ISSUE TITLE
extensions.treestyletab.autoAttach - false is now broken since update Ver.0.16.2016021201

### ISSUE THREAD

**Issue by titch71** [piroor/treestyletab#1062]
I've tried all the other extensions that try to provide a vertical tab solution but none come close but would prefer to organise the tabs myself and have all new tabs created as individual tabs - this worked until the last update.

I had initially tried this but the preference isnt available

If you don't want that Tree Style Tab automatically builds the tree of tabs, you should disable "extensions.treestyletab.autoAttachNewTabsAsChildren" by about:config. Then, you'll see tree only when you make a tree by hand, ex. drag and drop.

Is there any way to re-enable this feature.

**Comment by vityas-off** [comment]
I can confirm this.

**Comment by piroor** [comment]
Thanks, I forgot the preference can be disabled. b833326 should fix this.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
