### ISSUE TITLE
Homepage tabs open as child as first homepage (0.16.2016021201 regression)

### ISSUE THREAD

**Issue by ceribik** [piroor/treestyletab#1063]
After updating to 0.16.2016021201 (stable version), all my homepage tabs open as a child of the first listed homepage.

**Comment by piroor** [comment]
The commit 9580dc574fda37bef858ae3db90fb3dba4f7121c should fix this.

**Comment by ceribik** [comment]
Thanks, will test once the dev build updates.

**Comment by cd2016** [comment]
Look forward to this fix too!

**Comment by cd2016** [comment]
0.16.2016021602 still opens my 2nd and 3rd homepage tabs as children of the first homepage. Is there is a setting to change?

**Comment by piroor** [comment]
Sorry, I forgot the old behavior... And, the default behavior of the home button with multiple home pages seems not compatible to TST. Hmm, do you think how it should work?

 * Middle click of the button:
   1. open flat tabs
   2. open grouped tabs (current TST)
   3. ???
 * Single left click of the button:
   1. load the first item into the current tab and open others as new children (current TST)
   2. open new flat tabs
   3. open new grouped tabs
   4. ???

**Comment by cd2016** [comment]
Single left click of the Home button should open flat tabs.

**Comment by piroor** [comment]
Thanks. I think so for most cases. However, Firefox without TST always replaces the current tab with the first home page by single click. I think I should replace the current tab with new tabs, if here is only one visible tab.

**Comment by cd2016** [comment]
I've been using TST for a while now and all three of my homepages used to always opened flat when starting FF until recent updates.

**Comment by ceribik** [comment]
Same here.

**Comment by cd2016** [comment]
I agree with ceribik; I am concerned only when opening (starting) FF. No opinion on clicking HOME button.

**Comment by piroor** [comment]
Behaviors around multiple hope pages are now fixed.

 * On the startup, home page tabs are opened flat tabs.
 * Left click on the home button opens new separate home tabs.
 * Middle click on the home button opens new grouped home tabs.

**Comment by cd2016** [comment]
I apologize, but I'm new to GitHub... how can I test this?

**Comment by piroor** [comment]
See: https://github.com/piroor/treestyletab/blob/master/CONTRIBUTING.md
