### ISSUE TITLE
[Tab Mix Plus] Links don't work in Ver.0.16.2016021201

### ISSUE THREAD

**Issue by DyNama2015** [piroor/treestyletab#1064]
did a google search in FF 44.0.2 after TST updated, nothing happens when i click on any of the links. links work in other browsers, work when TST is disabled, work after regressing to the 20151225 version.

**Comment by Faelights** [comment]
I have also experienced this issue, I've been middle-clicking to get around the issue and still get automatic tree structure to form.

**Comment by piroor** [comment]
Firefox 44.0.2 + TST without Tab Mix Plus works for me.

**Comment by LordKor** [comment]
All the same: FF 44.0.2 x64 with Tab Mix Plus 0.4.2.0 - bookmarks won't open.
Works well in 0.16.20151225

**Comment by Faelights** [comment]
So I checked out my options in Tab Mix Plus - looks like it's "Force to Open in New Tab" that's causing the trouble for me. Turned it off in TMP and the Google search links work again.

**Comment by piroor** [comment]
Thanks. My another addon "Open Link in New Tab" https://addons.mozilla.org/firefox/addon/open-link-in-new-tab/ will work together with TST for the purpose.

**Comment by Faelights** [comment]
Thanks!

**Comment by Jestengel** [comment]
Upgraded to FF 44.0.2, Win10 x64. With "Force to Open in New Tab" checked in TMP my links no longer work as mentioned by Faelights above. Your app at https://addons.mozilla.org/firefox/addon/open-link-in-new-tab/ does not work in my setup. Love TST. Use it on the left. Any other suggestions? Meanwhile, on a possibly related note ???? All my favicons are gone sine FF 44.0.2 and one of my bookmark icons (Ultimate Guitar) disappeared from the bookmark bar. Domo'

**Comment by piroor** [comment]
Note, Open Link in New Tab is exclusive for TMP. If you install it with TST
and TMP, You have to disable TMP.

**Comment by boomshankerx** [comment]
FYI Version 0.16.2015122501 links work fine. 
https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/versions/0.16.2015122501

Downgrade and disable updates until issue has been resolved.

**Comment by zekeblue** [comment]
I've been bitten as well.  I use TMP "freeze tabs" (lock & protect) for tabs that I want to remain put.  I've had it so any links clicked in a frozen tab open in a new tab - even those that link to another page on the same site.  Clicking a link to a page in the same site in the newly opened unfrozen tab would open in the same tab.  With the latest TST, all links open in new tabs.  The Open Link in New Tab add-on doesn't recreate this scenario.  It is basically all or nothing and doesn't pay attention to whether a tab is frozen or not.

Also went back to previous version and am hoping this will not remain a permanent situation.

**Comment by DyNama2015** [comment]
Thanks, @piroor, for Tree Style Tab, you've made an addon that is essential...but Tab Mix Plus is too, valuable for locking tabs, merging windows, and undoing closed tabs. You know the latest version of TST conflicts with TMP. I hope either that will be fixed soon, or TMP, which does accommodate other addons, will be changed.

**Comment by zekeblue** [comment]
I've added to a thread in the TMP forum where related issue is being discussed:
http://tabmixplus.org/forum/viewtopic.php?f=2&t=19479

**Comment by onemen** [comment]
I will update Tab mix code

**Comment by zekeblue** [comment]
Thanks onemen!  I've replied in your forum with prefs for both extensions as requested.

**Comment by zekeblue** [comment]
There is a dev build in the TMP thread linked in my message above.  Works fine for me with the latest TST release.

Thanks to onemen!

**Comment by piroor** [comment]
@onemen Thanks a lot!!

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
