### ISSUE TITLE
vimperator で新しいタブを開くとサブツリーに追加される

### ISSUE THREAD

**Issue by elzzup** [piroor/treestyletab#1065]
別のアドオン vimperator での新規タブ作成時(:tabnew コマンド)の挙動が変わってしまいました
現在のタブの子要素に追加されてしまいます
対処できませんでしょうか？
ちなみにFirefox 本体のショートカットキーやメニューからのタブ作成は正常に動作しています

あと補足情報ですが
vimperator のバックグラウンドで開く動作も正常に今までどおり動いています
https://github.com/piroor/treestyletab/commit/f4fff38
この辺りのコミットを境に変わっているみたいです

**Comment by piroor** [comment]
最新の開発版では状況に変化はありますでしょうか？
http://piro.sakura.ne.jp/xul/xpi/nightly/
まだ再現するようなら、vimperatorの新しいタブを開く操作をフックして明示的に「子タブでないタブを開く」ように指示しないといけないです。

**Comment by elzzup** [comment]
vimperator が 46.0 に対応できていなくて
45.0 で確認してみたところ変わらず同じバグが再現されました

```
Firefox:	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0
treestyletab.xpi 	15-Feb-2016 01:40 	1.3M
Vimperator:	3.11.3 (created: 2016/02/15 03:15:55)
```

すいません私は問題の詳細に理由についてわかってないのですが vimperator 側で対応すべきな問題でしたでしょうか？

**Comment by piroor** [comment]
* Vimperatorの新しいタブを開くコマンドの実装: https://github.com/vimperator/vimperator-labs/blob/master/common/content/tabs.js#L867
 * 実際にタブを開いている箇所: https://github.com/vimperator/vimperator-labs/blob/master/common/content/liberator.js#L852

`BrowserOpenTab()`（新しいタブを開くボタンで実行される処理）のような関数を呼んでいるのであればTSTの「新しいタブを開く時に……」の設定が反映されるのですが、それよりも低レイヤのAPIである`gBrowser.loadOneTab()`を直接使っているため、TSTが気を利かせて子タブとして開いている状況ということのようです。

解決策としては、

 1. TST側で自動的にタブを子タブにする条件をもっと厳しくする。
 2. TSTにVimperator用のハックを仕込んで、明示的にツリー外のタブとして開くようにする。
 3. Vimperator側でTSTのAPIを呼んで明示的にツリー外のタブとして開くようにする。

の3通りがあり得ます。
1については自分は今以上にいい判別のやり方を思いつけずにいて、3については向こうのプロジェクトの方針次第ということになるので、取れる現実的な解決策は2になりそうなのですが、そうするとVimperatorのバージョンアップで動かなくなるリスクが増大するという不安はあります。

他のアドオンでも同じような問題が起こる事を考えると、1について良案を頂ければ採用したいというのが正直な所です。

**Comment by xsgoodbox** [comment]
I can confirm having the same issue since 0.16.2016021201

**Comment by piroor** [comment]
0bfedf7 で、タブを現在のタブの子にする条件をもう少し厳しくしてみました。
http://piro.sakura.ne.jp/xul/xpi/nightly/ で状況に改善があるかを試して頂けませんでしょうか？

After the commit 0bfedf7 TST detects new "possibly child" tabs more strictly. Could you try new development build? http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by elzzup** [comment]
```
treestyletab.xpi 	16-Feb-2016 10:02 	1.3M
Vimperator:	3.11.3
```

```﻿﻿Firefox:	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0``` と ```Firefox/44.0``` にて修正されているのを確認できました

ありがとうございます

**Comment by piroor** [comment]
確認ありがとうございます。closeします。
