### ISSUE TITLE
links within a `jar:...` tab won't open in new tabs

### ISSUE THREAD

**Issue by lilydjwg** [piroor/treestyletab#1067]
Firefox reports an exception about `nsURI userPass` when I'm about to open a link in a new tab from a `jar:...` tab by middle clicks or Ctrl+right clicks.

The `jar:...` URL is for viewing into zip files, like `jar:file:///home/lilydjwg/.../python.zip!/index.html`. I have some local docs and I compress them to save space (and maybe it's faster to load; anyway Firefox extensions do this often).

The exception happens here in window.js line 1346:

```javascript
	onBeforeOpenLinkWithTab : function TSTWindow_onBeforeOpenLinkWithTab(aTab, aParams) 
	{
		if (!aTab)
			return;
        // Here!
		log('onBeforeOpenLinkWithTab '+[aTab, JSON.stringify(aParams), this.checkToOpenChildTab(aTab)]);

		if (!this.checkToOpenChildTab(aTab)) {
			if (!aParams.fromChrome)
				this.handleNewTabFromCurrent(aTab);
			else if (!aParams.relatedToCurrent && !aParams.referrerURI)
				this.readyToOpenOrphanTabNow(aTab);
		}
	},
```

Removing `JSON.stringify(aParams)` solves the issue for me.

Sorry I haven't recorded more details. It's annoying to restart Firefox multiple times.

**Comment by piroor** [comment]
Thanks. 1126c9f should fix the error.

**Comment by lilydjwg** [comment]
It now works for me, thanks!
