### ISSUE TITLE
Left/middle-clicking bookmarks toolbar doesn't work in 0.16.2016021201

### ISSUE THREAD

**Issue by roukaour** [piroor/treestyletab#1068]
When I left-click or middle-click a bookmark, it does not open the link. This appears in the error console each time I click:

> Timestamp: 2/16/2016 2:38:19 AM
> Error: TypeError: cyclic object value
> Source File: resource://treestyletab-modules/window.js
> Line: 1346

(It is still possible to right-click a bookmark and choose "Open", "Open in a New Tab", etc.)

**Comment by piroor** [comment]
Could you add more details? I wrote a list of typical helpful information: https://github.com/piroor/treestyletab/blob/master/CONTRIBUTING.md

**Comment by roukaour** [comment]
I tried reproducing the issue and it's no longer happening. (Possibly because Tree Style Tab updated to 0.16.2016021602?) Thanks for your response.
