### ISSUE TITLE
Remove configurations which revoke "tree of tabs" feature

### ISSUE THREAD

**Issue by piroor** [piroor/treestyletab#1070]
* "Allow to collapse/expand tree" checkbox for both vertical and horizontal tab bar
 * "Indent tabs" checkbox (which allows you to disable indentation)

Internal implementations still there, because they are required by some public APIs to disable tree temporary.
This is just removing of configuration UI and preference items.

The main motivation of this change is redirecting people who don't like "tree" to other vertical tab bar addons. Reducing of code is not the main motivation.
So, I also have to show a redirection message on the migration phase, for people who use those preferences.

**Comment by piroor** [comment]
Done.

**Comment by Vanav** [comment]
Sad to hear this :-(
My bad, I don't use indent, because I want to save horizontal screen space and I don't want to spend time on maintaining trees in order. But I like compatibility, support, author's responsiveness and the rapid development of this extension, hardly anyone else can compare here.

**Comment by piroor** [comment]
Sorry, but I think TST is too complex and too large just for a vertical tab bar. If you like, fork this project and remove all "tree" features, then it will work as a "vertical tab bar" addon, and it will be another new alternative of TST.

**Comment by Vanav** [comment]
I think about flat vertical tab bar as just a visual form of TST: zero vert./horiz. indents and hide collapse icons. No new code or features are required. It is not a use of complex instrument for primitive tasks, it is just a change of visual from of tree to be more compact. So, if this will not simplify development, better to not hard-code minimum indent size.

If you want to clean settings page and code, maybe you'll give us just a CSS code to do this? The only function change I can think of is to disable collapse, but maybe TST already doesn't collapse on its own.

**Comment by piroor** [comment]
Actually it is not easy. For example:

 * TST injects some codes to Firefox's internal functions to support drag and drop of tabs in vertical tab bar.
 * TST undocks the tab bar internally from the flowing context of the toolbox and place at left or right as a floating box. I think it is required to make the vertical tab bar highly compatible with other addons.

In old days I tried to make the tab bar vertical only with CSS but I gave up, because resizable vertical tab bar cannot be done without script.
So I think that removing needless codes from forked TST is easier than building CSS rules to make the tab bar vertical from scratch.

**Comment by Vanav** [comment]
I mean: keep current TST extension (without "Allow to collapse" and "Indent tabs" checkbox) and add userstyle CSS to hide indents and collapse icons for those users, who want to have a compact tree.

**Comment by piroor** [comment]
Oops, I misunderstood. Thanks.

However, it still not easy. Simply stated, you'll have to do all same things happening on `gBrowser.treeStyleTab.treeViewEnabled=false`. See also: https://github.com/piroor/treestyletab/blob/master/modules/browser.js#L5456

Because the main motivation of this change is immigrating people like you from TST to more suitable addons like [Vertical Tabs](https://addons.mozilla.org/firefox/addon/vertical-tabs/) or [Side Tabs](https://addons.mozilla.org/firefox/addon/side-tabs/) or something alternative, I don't want to talk about details anymore, sorry. If I describe it completely, people who don't want tree features can stay on TST and we'll be unhappy forever.

**Comment by Dreamkeeper** [comment]
If there any way to disable the ability to collapse trees? I really like using trees and I like to have all my tabs in sight, it is annoying to click to collapse and expand sub-trees. For now I use version 0.16.2016021602, still, I think it would stop working on future version of Firefox. Any ideas?

**Comment by piroor** [comment]
You can prevent TST to collapse existing tree if a new tree is created. See TST's configurations.At the "Tree" pane, you'll see a checkbox to control the behavior.

**Comment by Dreamkeeper** [comment]
I need to entirely disable the ability to collapse a tree. Sometimes I just misclick one of these tiny arrows and the tree collapses and I cannot see some important tabs. Also these arrows take screen space, if I'm not going to use them, I don't want them to be displayed.
Can you please add an option to disable this function? From the comments to the extension I can notice that I'm not the only one who wants this option.

**Comment by piroor** [comment]
I'm very sorry but this is a design decision. Such an option won't be restored in future releases. If you really  need it, you have to fork this project by yourself...

**Comment by grahamperrin** [comment]
Found, thanks to @asamuzaK:

* https://github.com/piroor/treestyletab/blob/master/README.md#user-content-similar-projects ▶ Vertical tab bar without tree or grouping

**Comment by irvinm** [comment]
@grahamperrin also see:  https://github.com/piroor/treestyletab/issues/1544#issuecomment-522902490
