### ISSUE TITLE
Side Bar weird looking now after update 

### ISSUE THREAD

**Issue by ng4ever** [piroor/treestyletab#1072]
After updating to the latest Tree Style Tab my side bar now looks like this. Anyway to fix it please ?

http://i.imgur.com/Qh845ft.jpg

**Comment by phorham** [comment]
Confirmed... Also seeing this behaviour since the update to 0.16.2016021602 (Attached screenshot)

http://paste.opensuse.org/view/raw/ce94a338

**Comment by piroor** [comment]
Do you use a secret preference `extensions.treestyletab.tabbar.style.aero`=`true` on about:config?

**Comment by ng4ever** [comment]
No mine is set to false.

**Comment by piroor** [comment]
Hmm, then, any userChrome.css?

**Comment by ng4ever** [comment]
Nope no userChrome.css

**Comment by phorham** [comment]
In my case:
extensions.treestyletab.tabbar.style.aero = false

I have the following in userChrome.css 

`/*
 * ==== styles for TreeStyleTabs ====
 */

/*
 * background colour to match openSUSEgreen theme
 */
.tabbrowser-tabs[treestyletab-mode="vertical"] {
  background: #EFF9E4 !important; }
.treestyletab-tabbar-toolbar[treestyletab-mode="vertical"] {
  background: #A9CE80 !important; } 

/*
 * basic tab style
 */
.tabbrowser-tabs[treestyletab-mode="vertical"] .tabbrowser-tab {
  border: solid #DDF1C7 1px !important;
  margin-top: 0px !important; /* cannot change top margin, breaks pinned tabs */
  margin-right: 0px !important;
  padding-top: 2px !important;
  padding-bottom: 2px !important; } 
  
/* 
 * apply gradient to selected tab background
 */
.tabbrowser-tabs[treestyletab-mode="vertical"] .tabbrowser-tab[selected='true'] {
  background: linear-gradient(#9EBA95, #E6F0DF) !important;
  border: solid green 1px !important;
  border-radius: 6px !important; } 

/* 
 * apply partial border to unselected tab background - need to move right margin
 * to avoid 1px gap, moved back on hover.
 */
.tabbrowser-tabs[treestyletab-mode="vertical"] .tabbrowser-tab:not([selected='true']) {
  border-bottom: solid #A9CE80 1px !important;
  border-left: solid #A9CE80 1px !important;
  margin-right: -1px !important; } 

/*
 * apply hover effects
 */
.tabbrowser-tabs[treestyletab-mode="vertical"] .tabbrowser-tab[selected='true']:hover {
  border: solid black 1px !important;
  border-radius: 6px !important;
  background: -moz-menuhover !important;
  color: -moz-menuhovertext !important; }

.tabbrowser-tabs[treestyletab-mode="vertical"] .tabbrowser-tab:not([selected='true']):hover {
  border: solid black 1px !important;
  margin-right: 0px !important;   /* move margin back */
  border-radius: 6px !important;
  background: -moz-menuhover !important;
  color: -moz-menuhovertext !important; }
  
/*
 * ==== end styles for TreeStyleTabs ====
 */

`

**Comment by phorham** [comment]
Correctly formatted userCrome.css here:

http://paste.opensuse.org/view/raw/f2d20e00

**Comment by piroor** [comment]
@phorham Thanks. If the lighter background of the tab bar is from your userChrome.css, then you need to override style definitions introduced by these commits:

 * 1190268f01091e7b783b44de750c107ca0d80259
 * 536f011419f4f93fe7c48ad31ec1bd8034e4b6a6
 * bc3493db26b717ace583b3df2f96244ab57deb76

**Comment by ng4ever** [comment]
Ok but I have no idea what that means ? Please help. Thanks.

**Comment by piroor** [comment]
@ng4ever Thanks. Do you use any third party's theme? And, do you activate the "auto hide tab bar" feature?

**Comment by ng4ever** [comment]
No third party theme. No I do not activate the auto hide tab bar.

Thanks.

**Comment by ng4ever** [comment]
Here a list of my addons installed

- Add-on Update Checker
- BetterPrivacy
- Classic Theme Restorer
- Cleanest Addon Manager
- Complete YouTube Saver
- Copy Plain Text 2
- Download Cleaner
- DownThemAll!
- Extension Options Menu
- Flagfox
- Flash Control
- Form History Control
- Greasemonkey
- Linkification
- Menu Wizard
- Minimize On Start and Close
- NoScript
- Organize Status Bar (Revived)
- Pinboard.in
- Redirect Bypasser
- RoboForm Toolbar
- Stylish
- Tab Utilities Fixed
- Tree Style Tab

**Comment by piroor** [comment]
@ng4ever Please see the guideline: https://github.com/piroor/treestyletab/blob/master/CONTRIBUTING.md I'm very sorry but I have no time to try all combinations of your addons.

**Comment by piroor** [comment]
@phorham For example:

```
.tabbrowser-tabs[treestyletab-mode="vertical"] .scrollbox-innerbox {
  background: linear-gradient(to right,
                              #EFF9E4 0%,
                              #EFF9E4 10%,
                              rgba(0,0,0,0) 11%,
                              rgba(0,0,0,0) 100%) !important;
}
```

**Comment by ng4ever** [comment]
phorham did piroor fix help you ?

**Comment by ng4ever** [comment]
piroor ok thanks. I may just shrink the side bar to not see the difference. I hope I don't have to though.

**Comment by ng4ever** [comment]
Good news I think I found the culprit addon. Classic Theme Restorer.

When I disable it the side bar looks normal again.

**Comment by piroor** [comment]
> Good news I think I found the culprit addon. Classic Theme Restorer.

@ng4ever Thanks!

**Comment by phorham** [comment]
@piroor 
OK Many Thanks... :)

I've not time to try that now, I'll look at it tomorrow.

**Comment by ng4ever** [comment]
Ok your welcome. Hope to hear from you tomorrow! 

I messaged Classic Theme Restorer developer as well.

**Comment by piroor** [comment]
Anyway this problem is a "regression" introduced by these commits;

 * 1190268
 * 536f011
 * bc3493d

They are introduced to solve #240. So I think I have to give up the "improvement"...

**Comment by ng4ever** [comment]
Good news piroor I fixed the issue with a Classic Theme Restorer option thanks to Aris! 

I used remove tabs toolbar background (toolbars 3 category) option and it works!

**Comment by piroor** [comment]
After 172df77, this problem seems disappeared for me.

**Comment by phorham** [comment]
@piroor 

Yes, additional css to override style definitions for the commit to solve #240 works OK.

I see that now I probably don't need it after the above commit :)

I'll leave it in place until that commit makes it's way into a release on AMO

Again, many thanks for your work.
