### ISSUE TITLE
Tab tooltips are inconsistent

### ISSUE THREAD

**Issue by Vampire** [piroor/treestyletab#1076]
If you look at this screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/325196/13142223/fbded3b2-d63b-11e5-9bd3-f192585f5ff1.png)

you see some inconsistencies:
- When rendering tree nicely in tooltip, not all child tabs are rendered. The width is calculated correctly though I guess, because the Amazon Tab has a quite long title
- In the text rendering there is "Collapse tree:" in the first line in the nicely rendered version it is not
- Why is "Collapse tree:" there at all?

**Comment by piroor** [comment]
Thanks. This seems to be fixed by the commit 409103c9ba06c3db841f3d5f11b62ce0124a15e7.

**Comment by Vampire** [comment]
Just to be complete, in both, the text and the nice version "Collapse tree:" is sometimes shown and sometimes not. I couldn't find a pattern yet as to when it is shown and when not.

**Comment by piroor** [comment]
"Collapse tree:" is shown when you are pointing the twisty of tabs.

**Comment by Vampire** [comment]
Hm, I think the recognition might be broken. For me sometimes if I am on the twisty, the shadow and "Collapse tree" sometimes do appear and sometimes not. And also if I am on the favicon the shadow and "Collapse tree" sometimes do appear and sometimes not. But at least it seems consistent, so if the shadow is shown, the "Collapse tree" is added, if not, then not.

Btw. is it intended that the tree expands / collapses if the favicon is clicked?
I find this rather disturbing as I often click on the favicon to select a tab and thus cause the tree to collapse / expand unexpectedly.
I'd prefer if only the twisty is the trigger for collapse / expand.

If this is technically not possible as the twisty is just an overlay over the favicon (just a wild guess), then it would be nice if it could be configured that only double-click on the tab does collapse / expand.

**Comment by piroor** [comment]
Favicon in a tab works as a twisty if it is a parent tab. (In other words, clickable area of a twisty is always expanded covering the favicon.) So TST shows "Collapse(expand) this tree" for both twisty and favicon. The detection logic is common for both cases: clicking and pointing. So, if you  actually see the "Collapse (expand) this tree", the point works as a twisty, and if you don't see the header, clicking on the point will just select the tab itself.

**Comment by Vampire** [comment]
Nope, that is not the case. I can make a video for you if you don't believe ;-)
I can collapse / expand, even if the header and shadow is not shown. ;-)

**Comment by piroor** [comment]
OK, I got it. It is a horizontal tab bar specific problem. For vertical tab bar, as I commented it works as expected, but it seems unstable on horizontal tab bar...

**Comment by piroor** [comment]
TST updates the state of "twisty-hover" with mouseover event around tabs, but if you move your cursor from bottom, mouseover event doesn't fired on the twisty. Otherwise, if you move your cursor from top, it is detected as "twisty-hover" as I expected. hmm, to solve this problem I have to listen every mousemove event around tabs, but I'm worrying about it slows Firefox by too much mousemove events...

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
