### ISSUE TITLE
Vimperator - relatedToCurrent:true

### ISSUE THREAD

**Issue by cyber-duracel** [piroor/treestyletab#1077]
## Short description

Please create an option enabling users to choose between open new tabs from Vimperator (t, T) in the place where I ask for it as children / siblings and the new behavior 
## Steps to reproduce
1. Install FF 44 (Mozilla/5.0 (X11; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0 Iceweasel/44.0)
2. Install Tree Style Tab (I have the GIT version from 19/02/2016, it shows 0.16.2016021602)
3. Install Vimperator (I have the GIT version from 19/02/2016, 3.11.3 (created: 2016/02/19 17:34:02))
4. Open a new tab via 't' or 'T' 
## Expected result

A new tab will be open bellow the current tab as a sibling (or a child)
## Actual result

A new tab is opened at the end
## Environment
- Platform (OS): Debian Stretch / Sid
- Version of Firefox: (Mozilla/5.0 (X11; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0 Iceweasel/44.0)
- Version (or revision) of Tree Style Tab: 3.11.3 (created: 2016/02/19 17:34:02)

Thank you very much for your time

**Comment by piroor** [comment]
This seems related to #1065 and https://github.com/5digits/dactyl/issues/140 except the expected result is inverted. In short: A new Vimperator command like `:tabchildopen ` (told at https://github.com/5digits/dactyl/issues/140#issuecomment-185644232 ) is required.

**Comment by cyber-duracel** [comment]
Yes, it was working like this till the recent fix for #1065 and it's still working as expected without Tree Style Tab. As I am not capable of writing it myself, what should I do?

**Comment by cyber-duracel** [comment]
Additionally I am using Tab Mix Plus (addon) where is set that I wish to get a new tab next to current one as well. Would be possible to cooperate / respect this?

**Comment by piroor** [comment]
Is this a problem with a combination of three addons: TST, Vimperator, and Tab Mix Plus?

I've tried Vimperator with no other addon (including TST). Both commands `t` and `T` open new tabs at the end of the tab bar for me. Then, after TST is installed, `t` and `T` still produce same result: new tabs a the end of the tab bar. So, around the combination of TST and Vimperator, the current behavior seems natural. If you saw child tabs from `t` or `T` with old TST, it was a bug already fixed - as you know, it was #1065.

If the problem appears only when all three addons are activated, and new tabs should be opened next to the current tab by TMP, then I think it should be solved by TMP itself.

**Comment by cyber-duracel** [comment]
Hi piroor,

I've tried just with Vimperator and TMP it's working as I expect (the old behavior with child / sibling not opening them at the end). I fully understand you fixed it as a bug reported by somebody else. I was just asking if this behavior could be optional via some checkbox or config option? If not, no problem, I will need to get used it or find another vertical tab with similar features as TST. Thanks a lot for your effort

**Comment by piroor** [comment]
> I was just asking if this behavior could be optional via some checkbox or config option?

Sorry I have no plan to add such an option. 

BTW, there is an Vimperator plugin written by "caisui": https://gist.github.com/caisui/1245345 Possibly it helps you.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
