### ISSUE TITLE
Settings don't sync across multiple computers

### ISSUE THREAD

**Issue by SRGOM** [piroor/treestyletab#1078]
## Steps to reproduce
1. Create a new sync profile
2. Now  have the tst-bar appear on the right side and make some other changes
3. Use that profile on another computer
## Expected result

The new computer should have tst appear on the right side
## Actual result

The new computer has tst appear on the left side
## Environment
- Platform (OS): Linux 
- Version of Firefox: 44.0.2
- Version (or revision) of Tree Style Tab: 0.16.2016021602

**Comment by piroor** [comment]
Could you add sync preferences to https://github.com/piroor/treestyletab/blob/master/defaults/preferences/treestyletab.js ? Then I'll merge them except I think it should not be synched for different environment - for example, width of the tab bar.

**Comment by SRGOM** [comment]
Sorry, as i noted in the other pull request I have zero experience with add-ons. Let me see if I can find a similar functionality in another add-on and I'll try to push changes there.

Btw, will TST work with firefox electrolysis?

**Comment by piroor** [comment]
There is an old document: https://developer.mozilla.org/en-US/docs/Archive/Mozilla/Firefox_Sync/Syncing_custom_preferences
It is archived but the contents seems still correct. So you'll have to add a line like:

```
pref("services.sync.prefs.sync.extensions.treestyletab.(...)", true);
```

for each preference which should be synchronized.

**Comment by cipri-tom** [comment]
so, this is no longer necessary, right ? What version will it be in ?

**Comment by majutsushi** [comment]
What makes you think that this is no longer necessary? It's certainly not syncing anything yet.

Incidentally, the most important setting to synchronize for me would be the extra style rules, but they don't seem to be stored in a pref, so I don't know what would be required to sync them.

**Comment by cipri-tom** [comment]
@majutsushi the merged pull request makes me think it is no longer necessary.

But it is not syncing anything yet because I believe that commit didn't make it in a release version, which is why I asked what version will it be in.

I think the `style` in [this comment](https://github.com/piroor/webextensions-lib-configs/pull/1#issuecomment-344839493) refers exactly to that, the extra rules.

But I'm not sure how to use this. It seems users need to setup something, somewhere 😄

**Comment by majutsushi** [comment]
Ah, I missed the referenced issue somehow. It would indeed be great if syncing everything works in the next release.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
