### ISSUE TITLE
Feature request: Setting to open new tab as the first child in the child tree and push other chidren down

### ISSUE THREAD

**Issue by SRGOM** [piroor/treestyletab#1079]
## Steps to reproduce

 1. Middle click link1 and link2 on the same page to open them in new background tabs in this order

## Expected result

link2 should be the first child and link1 the second child

## Actual result

link1 is the first child and link2 is the second child.

This should be a customizable setting for those who want it. Why? Because sometimes when I have a lot of children for the parent and I click a link on the parent, I have to search for where the new tab opened. 

## Environment

 * Platform (OS): Linux 
 * Version of Firefox: 44.0.2
 * Version (or revision) of Tree Style Tab: 0.16.2016021602

**Comment by piroor** [comment]
Did you try TST's configuration => "Tree" => "Insertion position of new child tabs" => "Insert to the top of the tree, as the first child"?

**Comment by SRGOM** [comment]
Sorry, yeah...
