### ISSUE TITLE
bind() function in Firebase-util.js is not working in IE, Firebase.util.join() also not working throwing errors

### ISSUE THREAD

**Issue by upatnso** [piroor/treestyletab#1081]
## Short description

bind() function in Firebase-util.js is not working in IE, Firebase.util.join() also not working in IE throwing Exceptions
## Steps to reproduce
1. 
2. 
3. 
## Expected result

Firebase Chat window should open with all the friends in the bottom of Salesforce community page
## Actual result

Friends List not showing in Firebase chat and its making the page not responding. When debugged the page with F12 developer tools found some exceptions in the page as mentioned below.
1. SCRIPT5022: Exception thrown and not caught 

```
firebase-util.js, line 405 character 10
function bind(oThis) {
      if (typeof this !== "function") {
         // closest thing possible to the ECMAScript 5 internal IsCallable function

          new TypeError("Function.prototype.bind - what is trying to be bound is not callable");
      }
```
1. Exception while Calling Firebase.util.join() 

![firebase util join](https://cloud.githubusercontent.com/assets/17468187/13313711/f1360a90-dbc5-11e5-958c-236d44ac6905.PNG)
## Environment
- Platform (OS): Windows
- Version of IE: 9,10,11.
- Version (or revision) of Tree Style Tab: 

Could you please look into it and let us know whether it is known issue ?

Thanks & Regards,
Sobhan.

**Comment by piroor** [comment]
Does "IE" mean "Internet Explorer"? This is an issue tracker for the "Tree Style Tab" project, and it is a Firefox addon, not Internet Explorer.

**Comment by upatnso** [comment]
Hi Piroor,

How to move this bug request to correct Repository? Actually i have created one Repository upatnso/Firebase-util.

Thanks,
Sobhan.

**Comment by piroor** [comment]
https://github.com/firebase/firebase-util ?

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
