### ISSUE TITLE
Unmute not working if no sound is currently played

### ISSUE THREAD

**Issue by shredher** [piroor/treestyletab#1082]
## Short description
This sounds odd, but is actually a problem. If the website is not playing any sounds currently you are not able to unmute.

Why would you:
If you run WhatsApp web App for instance (or any other browser messaging service) and accidentally muted the tab while clicking on it, you might want to unmute it again. This is not possible while no sound is beeing played. You would have to be fast enough to navigate to the tab when the next message arrives.

It works natively on Firefox.

## Steps to reproduce
 1. Open a messenger like Whats App Web App, Facebook or whatever
 2. Wait for a message to arrive
 3. While the sound of an arriving message is beeing played, mute it.
 4. After reading the message, klick the "unmute" symbol or select it from context menu

## Expected result
The tab should be unmuted now

## Actual result
Nothing happens

## Environment

 * Platform (OS): Win10 Pro
 * Version of Firefox: 44.0.2
 * Version (or revision) of Tree Style Tab: 0.16.2016021602

**Comment by mausalimi** [comment]
i can confirm this is also the case here, using youtube.

**Comment by piroor** [comment]
I cannot reproduce this problem with the latest development build of TST. My case is:

 1. Open a new tab and search a video.
 2. Open a link to a video as a child tab. Then, there are two tabs: the parent (has no sound indicator) and the child (has a sound indicator).
 3. Click the indicator on the child tab and confirm that it stops the sound.
 4. Click the indicator on the child tab again. It restarts the sound.
 5. Collapse the tree. Then, there is only the parent tab is visible and the indicator is shown on the parent tab now.
 6. Click the indicator on the parent tab. Then it stops the sound of the collapsed child tab.
 7. Click the indicator on the parent tab again. Then it restarts the sound of the collapsed child tab.

Another case:

 1. Open a new tab and search a video.
 2. Open a link to a video into the tab itself. Then, there is one tab with video.
 3. Open a new child tab from the video tab. Then, there are two tabs: the parent (has a sound indicator) and the parent (has no sound indicator).
 4. Click the indicator on the parent tab. Then it stops the sound.
 5. Click the indicator again. Then it restarts the sound.
 6. Collapse the tree. Then, the parent tab still has its own sound indicator.
 7. Click the indicator on the parent tab. Then it stops the sound.
 8. Click the indicator again. Then it restarts the sound.

If your case is quite different from my case, could you describe yours with details like above?

**Comment by mausalimi** [comment]
well, i did something like this:

1. open a YT video
2. play it
3. mute it
4. stop video play

now the indicator can't be used to unmute. this works without TST.
as soon as you press the play button again, the indicator is working again.

doesn't worry me personally, but obviously others... :) 
couls also be the thread starter meant something else.

**Comment by shredher** [comment]
Yup, that's the Problem

1. open YT video
2. play it
3. mute it
4. navigate to google.com

now you are unable to unmute unless sound is played.

This is the problem when using Webmessenger like "messenger.com"

The mute/unmute function is only briefly available while the sound of an arriving message is played. Once muted, you'll have a hard time unmute.

**Comment by piroor** [comment]
Thanks, confirmed!

**Comment by piroor** [comment]
* 9770fa7bd8c365378cd05a787fc975b2f87ea70e
 * 979beab611ad058fa40070063472741def335b16
 * 36656e0523a647e73315a05a352b2f6faa4f2499

These commits fixed this problem for me.

**Comment by mausalimi** [comment]
it does work for me now. :)

good work.
