### ISSUE TITLE
Issue based in stupidity - How do I move tabs to the left side?

### ISSUE THREAD

**Issue by secretagency** [piroor/treestyletab#1084]
## Short description

Issue based in stupidity - How do I move tabs to the left side?  They got moved to the right side somehow.
## Steps to reproduce
1. 
2. 
3. 
## Expected result

  Tabs on left side of browser.
## Environment

  Ubuntu
- Platform (OS): 
- Version of Firefox:      Firefox Dev Edition
- Version (or revision) of Tree Style Tab:

**Comment by Rhotias** [comment]
Go to Tree Style Tab Configuration (in the Add-ons menu), then under the Appearance tab select Left for the tab bar position

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
