### ISSUE TITLE
Problem: Bookmarks

### ISSUE THREAD

**Issue by dicoxanaz** [piroor/treestyletab#1085]
New Tree Style Tab breaks bookmark focus option in Tab Mix Plus
## Steps to reproduce
1. In Tab Mix Plus set tab opening group of bookmarks to unchecked box
2. In firefox open group of bookmarks using option [open all in tabs]
## Expected result

Focus should stay on current tab.
## Actual result

Focus changes to tab from first bookmark
## Environment

Firefox 44.0.2
Tree Style Tab 0.17.2016030402 
Tab Mix Plus 0.4.2.0

**Comment by piroor** [comment]
Tab Mix Plus 0.4.2.2 is now available on Mozilla Add-ons, and it includes compatibility improvement about TST.  Did you try it?

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
