### ISSUE TITLE
Tabs opening non-indented on first use.

### ISSUE THREAD

**Issue by phorham** [piroor/treestyletab#1086]
## Short description
Upon first use tabs which where previously grouped/indented are opening flat.

## Steps to reproduce

 1.  Start Firefox
 2.  Use "Open all In Tabs" from FF bookmark
 3. 

## Expected result
As per this screenshot:
http://paste.opensuse.org/view/raw/95228dce
(from a user account which has not yet been updated to 0.17.2016030402

## Actual result
As per this screenshot:
http://paste.opensuse.org/view/raw/42ef5599

## Environment

 * Platform (OS): linux (openSUSE Tumbleweed 20160303)
 * Version of Firefox: 44.0.2
 * Version (or revision) of Tree Style Tab: 0.17.2016030402

**Comment by phorham** [comment]
Sorry, forgot to add, these are the "Behaviour of 'Open All in Tabs' for bookmark folders" settings:

Selected - Open as a tree...
Checked - Put tabs under a dummy...
'Restore' - tree structure...

**Comment by piroor** [comment]
I couldn't reproduce this, by described steps, on Firefox 45. Any other condition to reproduce? For example, Tab Mix Plus or something.

**Comment by phorham** [comment]
OK... I think I've found the cause of this.

It looks as if the FF Preference "Show a blank page" / "about:blank" is implicated in some way...


Disabled all extensions apart from TST - Problem IS present.

Clean FF profile (temporarily renamed .mozilla) + TST 0.17.2016030402 - Problem NOT present. 
  Progressively change TST preferences to the settings I had been using - Problem NOT present.
  Progressively change FF preferences to the settings I had been using - Problem NOT present - UNTIL:

FF Preference "General - When Firefox starts:"
Set to "Show a blank page" (my normal setting for this) - Problem IS present.
Set to "Show my home page" (with a homepage URL set) - Problem NOT present.
If I change the URL to "about:blank" - Problem IS present.

**Comment by phorham** [comment]
Couple of screen-shots to illustrate:

http://paste.opensuse.org/view/raw/45e3a9bf
Firefox set to "Show a blank page"

http://paste.opensuse.org/view/raw/786a0da1
Firefox set to "Show my home page"

I'm able to reproduce this with a completely new (linux) user with a new Firefox (44.0.2) / TST (0.17.2016030402) install.

**Comment by piroor** [comment]
Thanks, confirmed!

**Comment by piroor** [comment]
The commit fbbc1cd fixes this for me.

**Comment by phorham** [comment]
Just to confirm: 0.17.2016031101 fixes this issue

Thanks.
