### ISSUE TITLE
Latest Versions of Firefox, I have to keep re-installing TST

### ISSUE THREAD

**Issue by seraphimalia** [piroor/treestyletab#1088]
## Short description

With version 45 of Firefox, It appears that the plugin is not fully compatible.  When installing from Plugins, It has a fellow button instead of a green button.  After installing and restarting FF Tree Style Tabs (TST) works fine.  If I Quit FF and Start it up again, TST is disabled.  I have to search for plugin, and click install again and restart FF for it to work.  Please Help
## Steps to reproduce
1. Install TST in FF and restart - TST works
2. Quit FF and Open FF again
3. TST no longer enabled.
## Expected result

TST remains enabled when Quitting FF and Opening it again
## Actual result

TST is disabled when FF is Opened after Quitting.  Plugins List shows "Tree Style Tab cannot be verified for use in Firefox and has been disabled."  
<img width="838" alt="screenshot at mar 09 22-56-00" src="https://cloud.githubusercontent.com/assets/4745922/13650183/23f9f2c8-e64a-11e5-95a8-beba2a545585.png">
## Environment
- Platform (OS): Mac OSX 10.11
- Version of Firefox: 45
- Version (or revision) of Tree Style Tab: 0.17.2016030402

**Comment by piroor** [comment]
If you installed TST from my website, the XPI file is not signed and disabled by Firefox by default. Signed version is available on AMO: https://addons.mozilla.org/ja/firefox/addon/tree-style-tab/

**Comment by emilv** [comment]
I used to have this problem too in 0.16 (OS X 10.11, latest Firefox), and it did only intermittently go away by reinstalling. Sometimes the problem have gone away only to reappear after upgrading the browser. I just tried to completely remove the extension and installing it anew from the exact link @piroor linked above. It now seems to work. I now can restart, force quit, etc.

I suggest that you keep this issue open until the next version of Firefox. Perhaps there's something going on when updating the browser?

**Comment by wsmwk** [comment]
@seraphimalia, do you still see this problem?

**Comment by emilv** [comment]
I just updated to 47.0 and did not have this problem! 👯

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
