### ISSUE TITLE
Possible to have the bar not take up empty space?

### ISSUE THREAD

**Issue by SRGOM** [piroor/treestyletab#1089]
## Short description
Currently the bar takes  up the entire height of screen 

## Expected result
Would it be possible that it takes up only as much as is needed to show all the tabs?

## Environment

 * Platform (OS): Linux/Windows
 * Version of Firefox: 44.0.2
 * Version (or revision) of Tree Style Tab: 0.16.2016021602

**Comment by piroor** [comment]
Please describe "steps to reproduce". If you have any screenshot, it will help me too. See also the guideline: https://github.com/piroor/treestyletab/blob/master/CONTRIBUTING.md

**Comment by SRGOM** [comment]
Its a feature request so probably the format doesn't fit but what  I'm looking for is unlike the current situation where the sidebar takes up the entire vertical length, would it be possible for it to take only as much space as the number of tabs? (This would mean that the space used by tabs overlaps some webpage content so if there was an easy way to slide the tab-bar up and down, that would help)

**Comment by piroor** [comment]
OK, I misunderstood. I've added some guides about future requests.

If the blank area of the tab bar goes away, it means that rest tabs can cover the web page itself. You still cannot click links covered under the tab bar. So, next you'll say: "something new feature is required to operate links covered under the tab bar."

So I think some other solutions are better than adding a new "feature" to TST:

 * TST configuration => "Auto hide" => "for Normal Window Mode" => "Auto Hide tab bar". I think that this is the most smart solution.
 * Install [Ez Sidebar 4.x](https://addons.mozilla.org/firefox/addon/ez-sidebar/versions/) and combine it with another addon which provide tab list in the sidebar. (In old days, "Tab SIdebar", "Pano" and some other projects for the purpose. Sorry, I don't know still active project...) Floated sidebar is resizable as you like.
 * install [Unified Sidebar](https://addons.mozilla.org/firefox/addon/unified-sidebar/) and use the blank space to show Firefox's Sidebar.

**Comment by piroor** [comment]
Or, [All Tabs Helper](https://addons.mozilla.org/firefox/addon/all-tabs-helper/?src=search) seems similar to what you want.

**Comment by SRGOM** [comment]
This is helpful, thanks!
