### ISSUE TITLE
[Tab Mix Plus, Firegestures] "unsafe CPOW usage forbidden" warning after bug 1233497

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#1093]
## Short description
After [Bug 1233497 - Make unsafe CPOWs from non-addon browser code throw by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1233497), an unknown conflict among Tab Mix Plus, Tree Style Tab, and Firegestures triggers "Unsafe CPOW usage forbidden" warning. It disables scroll-to-top/bottom gesture from Firegestures.
## Steps to reproduce

1. In a new profile in Nightly, make sure dom.ipc.cpows.forbid-unsafe-from-browser is set to true (default)
2. Install the latest versions of the 3 extensions:

    Tree Style Tab 0.17.2016031101 or nightly
    Tab Mix Plus 0.4.2.1pre.160228a2 or 0.4.2.2: https://addons.mozilla.org/en-US/firefox/addon/tab-mix-plus/versions/
	Firegestures 1.10.5: https://addons.mozilla.org/en-US/firefox/addon/firegestures/versions/
3. Restart browser.
4. Draw the gesture for scroll-to-top/bottom. (Default is holding Right-click, then LEFT,UP or LEFT,DOWN)

## Expected result
The page should scroll to top/bottom without errors.

## Actual result
The gestures fail. Error shown in statusbar is `Gesture failed: (Error: Unsafe CPOW usage forbidden)`. A similar warning appears in browser console as well.

Disabling either TMP or TST does not trigger the "unsafe CPOW usage forbidden" warning. I think the culprit may lie on the interaction between Tab Mix Plus and Tree Style Tab, but FireGestures somehow exposes the bug.

## Workaround
Toggling dom.ipc.cpows.forbid-unsafe-from-browser fixes the issue.

## Environment

 * Platform (OS): Win10 64bit
 * Version of Firefox: Current Nightly
 * Version (or revision) of Tree Style Tab: 0.17.2016031101 or nightly

The issue is crossposted to other extensions' pages and Bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1243625
https://github.com/gomita/firegestures/issues/116
http://tabmixplus.org/forum/viewtopic.php?f=3&t=15740&p=70304#p70304

**Comment by piroor** [comment]
Confirmed. The error seems to be raised from http://mxr.mozilla.org/mozilla-central/source/js/ipc/JavaScriptParent.cpp#79

**Comment by piroor** [comment]
https://github.com/gomita/firegestures/blob/master/chrome/content/firegestures/browser.js#L329
This code raises the error. Same error appears with a debug code `Services.console.logStringMessage(' location = '+this.sourceNode.ownerDocument.defaultView.location.href);`.

**Comment by piroor** [comment]
The error disappears when I disable this line: https://github.com/gomita/firegestures/blob/master/chrome/content/firegestures/browser.js#L80

**Comment by piroor** [comment]
Turning `extensions.treestyletab.compatibility.FireGestures` to `false` suppresses the error. Hmm, I think I have to rewrite hack for FireGestures...

**Comment by piroor** [comment]
The commit 3ea008482bc20a9911d93c6f883f420c29406ebc solves this problem for me.

**Comment by Fanolian** [comment]
I can verify the latest TST nightly build (0.17.2016031800a192017) fixes the issue. Thanks for the fix.

Just a question, why does the bug involve with Tab Mix Plus too? Do you know if TMP also does some hacks to FireGestures, and somehow your old hack conflicts with TMP's?
