### ISSUE TITLE
Tab overlay when moving tabs breaks

### ISSUE THREAD

**Issue by ng4ever** [piroor/treestyletab#1096]
When I enable Tab Utilities Fixed (https://addons.mozilla.org/en-US/firefox/addon/tab-utilities-fixed/) the tab overlay when moving tabs to show me where the tab will go disappear :(

Anyway to fix this or should I contact the developer of Tab Utilities Fixed ?

Here is screenshots of my example: 

This is with Tab Utilities Fixed disabled

http://i.imgur.com/6u14xdc.jpg

This is with Tab Utilities Fixed enabled

http://i.imgur.com/CM348G5.jpg

**Comment by ng4ever** [comment]
Sorry it is hard to explain but some kind of tab overlay disappears when enabling Tab Utilities Fixed extension is all I know. I was hoping to get it fixed.

**Comment by ng4ever** [comment]
Nevermind it was fixed today by Tab Utilities Fix addon author! 

https://github.com/yfdyh000/tabutils/releases

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
