### ISSUE TITLE
Selected tab is colour-filled, same colour as the title.

### ISSUE THREAD

**Issue by Tmplt** [piroor/treestyletab#1103]
## Short description

After the update of GTK to v3.20, I get the following colour issue with TSB:

![colour issue](https://u.pomf.is/ptlvum.png)
## Steps to reproduce
1. Install latest GTK version.
2. Install TSB and Firefox.
3. Select any theme (I do this with `lxappearance` in Arch Linux.
## Expected result

The selected tab's title should be readable.
## Actual result

The selected tab's title isn't readable.
## Environment
- Platform (OS): Arch Linux
- Version of Firefox: 45.0.1
- Version (or revision) of Tree Style Tab: `843f6d98`

**Comment by Darksonn** [comment]
I'm having the same issue on both of my computers. I'm also on arch linux.

**Comment by jplatte** [comment]
Same here with a dark theme, and I'm also pretty sure I didn't have heavy-contrast borders around the tabs before.

And even more annoyingly, Firefox often crashes when I try to move a tab via drag-and-drop. That might be unrelated though.

**Comment by ubitux** [comment]
Same issue here with the following GTK configuration:
```
[~]☭ cat ~/.config/gtk-3.0/settings.ini 
[Settings]
gtk-icon-theme-name = Numix
gtk-theme-name = Numix
gtk-font-name = ProFont 10
gtk-application-prefer-dark-theme = true
```

(and running firefox with `MOZ_ALLOW_GTK_DARK_THEME=true` to workaround bugzilla #1272332)

It looks like this: http://i.imgur.com/pFCb3ze.png

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
