### ISSUE TITLE
Treestyle on OSX

### ISSUE THREAD

**Issue by syn74ks** [piroor/treestyletab#1104]
## Short description

The tabs do not work on my El Capitan Macbook Pro. Using the latest version of all software.
## Steps to reproduce
1. Install the addon
2. Doesnt work properly
## Expected result

The result should look the same as on Windows based machines
## Actual result

The tabs don't cascade downward or form a hierarchy. Instead, they pile up on top of each other. New tabs also behave the same way.
## Environment
- Platform (OS): OSX - El Capitan
- Version of Firefox: 45.0.2
- Version (or revision) of Tree Style Tab: 0.15.2015030601.1-signed

**Comment by piroor** [comment]
I'm very sorry but currently it is hard to test on latest Mac OS for me. I need contribution from Mac OS users...

**Comment by sumyungguy** [comment]
Works fine for me, even on those older versions. Could try updating to latest Firefox and TST?

**Comment by syn74ks** [comment]
yep, tried this - always up to date.

could possibly be another addon/extension.

ill diasble all and try again.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
