### ISSUE TITLE
Dragged tab position not updated below bottom tab

### ISSUE THREAD

**Issue by jimbo1qaz** [piroor/treestyletab#1106]
## Description

First I drag a tab out of its initial position, so that its tab insertion cursor is formed and moved. I do not release the mouse, but continue dragging. Afterwards, the tab insertion cursor will no longer update if the tab is dragged below the last tab and new-tab button.
## Reproduction
1. Enable tree style tabs, tabs on side
2. Drag a tab
3. Quickly move the mouse down, below the bottom tab
### Alternative method

Drag the tab one spot out of its initial position. Then drag it horizontally out of the tab bar, down below the existing tabs, and back into the tab bar region.
## Expected result

Tab insertion marker (black line) moves to below the bottom tab.
## Actual result

Tab insertion marker (black line) remains at the last known position within the existing tabs.

Interesting observation: If you create a space between bottom tab and (+), then drag tab out of side, and back into tab bar below (+), you can see the tab title move downwards, into the space.
## Environment
- Platform (OS): Debian 8 x64
- Version of Firefox: Firefox Dev 47.0a2
- Version (or revision) of Tree Style Tab: Latest dev (March 2016)

**Comment by piroor** [comment]
I couldn't reproduce it on my PC, or I misunderstood your report. Could you take a screenshot to describe the wrong result? Gimp has a feature to take a screenshot with delay.
