### ISSUE TITLE
TST doesn't work anymore with double click on empty space workaround to open a new tab

### ISSUE THREAD

**Issue by Tragen** [piroor/treestyletab#1108]
In bug #831 I asked why the scroll down button will overlap with the addon bar when I use this code to open a new tab when I double click the empty area below the tabs.

`#navigator-toolbox > #TabsToolbar
{
-moz-binding: url("chrome://global/content/bindings/toolbar.xml#toolbar")!important;
}`

piroor told me that I should use this code to fix it.

`#navigator-toolbox > #TabsToolbar {
  -moz-binding: url("chrome://treestyletab/content/treestyletab.xml#toolbar")!important;
}`

The new code worked great until FF46. Now with the code from piroor, I cannot open any tab anymore. The first code works but has the bug described in #831.
What is the new solution to get it working without overlapping?

**Comment by piroor** [comment]
The CSS code I wrote still works for me on Nightly 49.0a1 on Windows 7. Any other tab-related addon possibly conflict to TST?

**Comment by Tragen** [comment]
I've tried it with a new VM with FF46 and a new profile only with TST installed and it doesn't work for me. No new tabs are shown.

**Comment by Xaphiosis** [comment]
Try this:

```
#navigator-toolbox > #TabsToolbar {
    -moz-binding: url("chrome://browser/content/customizableui/toolbar.xml#toolbar") !important;
}
```

**Comment by Xaphiosis** [comment]
This works in FF46/47, but still has the problem described in #831

```
#navigator-toolbox > #TabsToolbar {
    -moz-binding: url("chrome://browser/content/customizableui/toolbar.xml#toolbar") !important;
}
```

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
