### ISSUE TITLE
 Does not auto-hide when mouse not inside page

### ISSUE THREAD

**Issue by jimbo1qaz** [piroor/treestyletab#1109]
## Short description
1. After hovering (expanding) tab bar, if I move my mouse over toolbars or menus, the tab bar will not close.
2. If I expand a bookmark folder, then click a bookmark, the tab bar will not close until I move the mouse.
## Steps to reproduce
1. Move mouse over tab bar
2. Move mouse out of window, or onto top toolbar (menu, url bar, bookmarks, etc.)
3. (optional) Open bookmark folder, then (middle)-click on bookmark
## Expected result

Tab bar collapses.
## Actual result

Tab bar does not collapse until I move cursor over window. If I click bookmark, cursor is already over window, but tab bar does not collapse.
## Environment
- Platform (OS): Ubuntu Studio 16.04
- Version of Firefox: 46.0 Ubuntu
- Version (or revision) of Tree Style Tab: 2016-04-01

**Comment by lv7777** [comment]
I confirmed both bug.

# environment

* windows10
* firefox45.02 release ver
* TST commit 85432c

**Comment by lv7777** [comment]
The both bug cause by not collapse when mouse focus on tool bar, In the first place,this behave was possibility of on purpose.

**Comment by lv7777** [comment]
And, bug2 was caused when expand side bar and open new window.

**Comment by piroor** [comment]
> After hovering (expanding) tab bar, if I move my mouse over toolbars or menus, the tab bar will not close.

It is by design. I didn't write any code to hide the tab bar when the cursor goes out of the tab bar, instead, the tab bar will be hidden/collapsed when the cursor moves onto the content area, to expand visible area for the contents.

**Comment by piroor** [comment]
> If I expand a bookmark folder, then click a bookmark, the tab bar will not close until I move the mouse.

I think this is a difficult issue. I think that the tab bar should be kept open in some cases - for example, a new tab is opened by clicking on the "+" button.  We have to decide when the tab bar should be hidden/collapsed and when they should be open, for various situations. 
I dislike too much "options" for the purpose to customize details, instead, TST should decide to hide/collapse the tab bar or not intelligently.

**Comment by jimbo1qaz** [comment]
My opinion: The toolbar should remain open iff the cursor is on the tab bar
(not other toolbars).

**Comment by jimbo1qaz** [comment]
autohide no longer exists
