### ISSUE TITLE
Tree swallows next tab on switching to tab group

### ISSUE THREAD

**Issue by sambc** [piroor/treestyletab#111]
Using the 'tab groups' feature of FF4, I see a strange behaviour. It doesn't always happen, but it usually does. Actually, there are two, but one is easier to describe.

The first one, the oddest, is that, on switching to a tab group, it at first displays as expected, clicks on the tab bar doing  nothing, and then each top-level tree (as in not tabs that have no children) will 'swallow' the next tab or tree down from it, making the tab (or root of the tree) a child of the root of the tree doing the swallowing, after all existing children. A tree that has been swallowed doesn't swallow anything in its turn.

The harder one to describe, and I don't know if it's TST causing it or not, is that sometimes, on switching away from a group, if I then switch back, or even look at the order of the tabs using crtl-shift-e or the 'tab groups menu' extension, they have either reversed or rotated. It's odd. It's not likely that that's TST, I suppose, but I thought it might be worth mentioning.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
