### ISSUE TITLE
when paste text,collapse tree was expanded

### ISSUE THREAD

**Issue by lv7777** [piroor/treestyletab#1114]
## Short description

I have been noticed it about or a while, when paste text to textarea, tree was expanded. 
this bug coursed by often pasting, but I have feeling that it caused coping.
And this bug not cause surely. cause occasionally

---

ja

前から気になっていたのですが、textarea内のtextをpasteしたときにtreeがexpandする時があります。
このバグはpasteするときに大体なりますが、copyする時にもなった記憶があります。

また、かならず発生するバグではありません。たまになります。
## Steps to reproduce
1. set TST on collapse mode
2. copy something.
3. paste something.
## Expected result

tree was expanded in a moment,but re-collapse soon.

(ja)一瞬だけtreeが開きすぐに戻る。
## Actual result

No effect on TST

(ja)何もtree style tabには影響がない。
## Environment
- Platform (OS): windows 10
- Version of Firefox: 45.02 release version
- Version (or revision) of Tree Style Tab: least build

**Comment by piroor** [comment]
タブバーを自動的に隠す（縮める）モードでタブバー自体が一瞬だけ自動表示されるという現象であれば、おそらく、Ctrlキーの長押しでタブバーを自動表示する機能が働いているのではないでしょうか。
Ctrl-Tab/Ctrl-Shift-Tabでタブを切り替えるときに隠れたままだと困るので、このときは自動的にタブバーを表示する（Ctrl-Tabでのタブ切り替えが終わったらまた隠れる）ようになっています。

**Comment by lv7777** [comment]
なるほど。
jsでイベントでctrlと同時に押されてるキーが英字キーの場合自動的に表示しない、みたいな処理を入れてもいいかもしれません。

**Comment by piroor** [comment]
英字キーの方から先に指が離れると、タイミング次第ではCtrlキー単独で押されていると見なされてしまって、それでこの機能が働いているのではないかと予想しています。Ctrlキーを押してすぐではなく一定時間後に状態を見て、Ctrlキーが単独で押されていればこの機能が発動する、というような設計になっていたと思うので。（うろ覚えです）

Ctrlキー単独またはCtrl-Tab/Ctrl-Shift-Tab以外の組み合わせのキーが一度でも押されたらタイマーをキャンセルする、という処理を入れるといいかもしれません。

**Comment by lv7777** [comment]
このバグに今取り掛かっているんですがこの処理を実行している箇所をもし覚えているなら教えていただけないでしょうか？

`extensions.treestyletab.tabbar.autoShow.accelKeyDown.delay`が関係してることは分かりました。

個人的には
https://github.com/piroor/treestyletab/blob/master/content/treestyletab/windowHelperHacks.js#L538
とか怪しいなぁと思っているんですが

**Comment by piroor** [comment]
window.jsのhandleEventから辿るといけるんじゃないかと思います。

**Comment by piroor** [comment]
* https://github.com/piroor/treestyletab/blob/master/modules/window.js#L717
 * https://github.com/piroor/treestyletab/blob/master/modules/window.js#L837
 * https://github.com/piroor/treestyletab/blob/master/modules/window.js#L880

このあたりだったかと。

**Comment by lv7777** [comment]
window.jsのイベントリスナーでonkeydownを発火して、その中でカスタムイベントを作りkEVENT_TYPE_TAB_FOCUS_SWITCHING_KEY_DOWNイベントを発火して

https://github.com/piroor/treestyletab/blob/8c74d7ac6203b4a96723e51a4c12869f66e2d2d4/modules/autoHide.js#L1449
で実際の表示非表示が行われていることを確認しました。

**Comment by lv7777** [comment]
簡単にできるかと思ったら以外にめんどくさそうです。
イベントリスナーをsettimeoutの中で仕掛けてその返り値を見て判断する的な

**Comment by lv7777** [comment]
https://github.com/piroor/treestyletab/blob/master/modules/autoHide.js#L1434
に
```
		var keyarr = [];

		w.addEventListener('keydown', function(aEvent){
			keyarr.push(aEvent.keyCode)
		}, true);
```
を追加してもなぜか発火してくれない。。。
デバッガで追うと`w.addEventListener('keydown', function(aEvent){`までは来てるのに中身だけ実行されない・・・

**Comment by piroor** [comment]
まさにリンク先の行の位置にそのコード片が追加されている状況でしょうか？
そうなのであれば、その箇所は元を辿ると「keydownイベントが発火した事をトリガーとして実行されている処理」の中にあることになるので、そのトリガーになったkeydownイベント自体をハンドルすることはできず、それ以降に新たに発火した　keydownイベントしか受け取れないと思います。

**Comment by piroor** [comment]
https://github.com/piroor/treestyletab/issues/1114#issuecomment-217202109 に書いたアイデア自体が的外れである可能性もあって（この部分を書いたのはかなり前なので、自分も詳細をだいぶ忘れています）、その場合は、今の実装をきちんと把握した上でどこを変えないといけないかを分析し直さないといけないかもです……

**Comment by lv7777** [comment]
全く同じ環境なのに(git status見ても変更してないしfirefox環境はjpmに任せてあるので勝手にプロファイル作ってくれる)なんかいきなりちゃんと出るようになりました。。。なにこれ。。。

発火するようになったのはいいんですけどなんかcrtlやらaltキー、shiftキーが200個ぐらい発火されてますね。。。どっかで疑似発火でもしてるのかな。。。
ちなみに規則性はないっぽいです。

まあctrl関係はTreeStyleTabService.accelKeyPressedに任せておけばいいのでちゃんとデータが受け取れれば後は自分でできるはずです。(ここの環境がグローバルで保存されてるので少しめんどくさそうですが)

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
