### ISSUE TITLE
[core]update AboutModule.js

### ISSUE THREAD

**Issue by lv7777** [piroor/treestyletab#1115]
console

```
Warning: 'nsIOService::NewChannel()' deprecated, please use 'nsIOService::NewChannel2()'

Warning: 'nsIAboutModule->newChannel(aURI)' deprecated, please use 'nsIAboutModule->newChannel(aURI, aLoadInfo)'

```

**Comment by lv7777** [comment]
今朝確認したんですけどfirefox dev editonや通常リリースだとこのログは表示されませんでした。
下手に更新しないほうがいい気がします
___
# environment

* firefox 46.0.1 release
* firefox 48.0a2 dev edition

どちらもwindows 10です

**Comment by piroor** [comment]
APIの変更が予定されてる部分てことですかね？ 要注意ですね。。。

**Comment by piroor** [comment]
https://dev.mozilla.jp/2016/05/firefox-48-addon-compatibility/
ここに情報が載ってました。Firefox 45は当分サポート対象に含めておくつもりなので、このメソッド名の変更の前後の両バージョンへの対応が必要です。

**Comment by lv7777** [comment]
memo:

https://developer.mozilla.org/ja/docs/XPCOM_Interface_Reference/nsIIOService#newChannel2%28%29
```
nsIChannel newChannel2(
   aSpec,//newChannelと同じ
   in string aOriginCharset,//null
   in nsIURI aBaseURI,//null
   in nsIDOMNode aLoadingNode,//意味不明だがとりあえずアドオンから読み出すときはnullを使用
   in nsIPrincipal aLoadingPrincipal,//Services.scriptSecurityManager.getSystemPrincipal()
   in nsIPrincipal aTriggeringPrincipal,//特に変なことをしなければprincipalと同じ
   in uint32_t aSecurityFlags,//特殊なことをしていないのでCi.nsILoadInfo.SEC_NORMAL
   in uint32_t aContentPolicyType,
/*
https://dxr.mozilla.org/mozilla-beta/source/dom/base/nsIContentPolicyBase.idl#91かもしくは
https://dxr.mozilla.org/mozilla-beta/source/dom/base/nsIContentPolicyBase.idl#68
とりあえずTYPE_OTHERでも問題なさそう？
*/
);
```

**Comment by piroor** [comment]
ゼロから調べると大変なので、about:addonsなどのabout: URIを実装している部分を参考にするといいかもです。
http://mxr.mozilla.org/mozilla-central/source/browser/components/about/AboutRedirector.cpp
http://mxr.mozilla.org/mozilla-central/source/netwerk/base/nsNetUtilInlines.h#205
……って、これを見るとまだFirefox本体もNewChannel2は使ってないんですね。
今の段階で頑張らなくても、Firefox本体の側でabout: URIの実装が書き直されたあとでそれを参考にするのが楽かなあと思いました。
（自分は基本的に、ドキュメントが不足してるXPCOMコンポーネントの使い方はFirefoxの中で同じような使い方をしてる部分を見て真似ることが多い）

**Comment by lv7777** [comment]
一応できました。
newchannel～～みたいなwarningは消えました。

が今度は
```
警告: 'nsIOService::NewChannel()' は非推奨です。'nsIOService::NewChannel2()' を使用してください。AboutGroup.js:50:9
```
というwarningが発生しました

**Comment by lv7777** [comment]
```javascript
		//return Services.io.newChannel('chrome://treestyletab/content/group.xul', null, null);
		return Services.io.newChannel2(
			'chrome://treestyletab/content/group.xul',
			null,
			null,
			null,
			Services.scriptSecurityManager.getSystemPrincipal(),
			Services.scriptSecurityManager.getSystemPrincipal(),
			Components.interfaces.nsILoadInfo.SEC_REQUIRE_SAME_ORIGIN_DATA_IS_BLOCKED,
			Components.interfaces.nsIContentPolicy.TYPE_OTHER
		);
```

nsILoadInfo.idlを見ても、SEC_NORMALはセキュリティフラグを指定しない設定っぽいので、
https://dxr.mozilla.org/mozilla-beta/source/netwerk/base/nsILoadInfo.idlを確認して、
aloadinfoをSEC_REQUIRE_SAME_ORIGIN_DATA_INHERITSやSEC_REQUIRE_SAME_ORIGIN_DATA_IS_BLOCKEDなどに変えてみたのですが相変わらず出ることを確認しました。
また、aTriggeringPrincipalを変更しても相変わらずwarningが出てました

また、デバッガーで追ってみると、Services.io.newChannel2が走った時ではなく、geturiflagsが走ったときに発生していることも確認しました。

**Comment by lv7777** [comment]
でなんかfirefox側が原因かな？と思っていろいろググってみたらそれっぽいのが出ました。
https://bugzilla.mozilla.org/show_bug.cgi?id=1268595

**Comment by piroor** [comment]
Closed by #1137
