### ISSUE TITLE
[feature request] Visually distinguish tabs that aren't loaded

### ISSUE THREAD

**Issue by theres-waldo** [piroor/treestyletab#1118]
Firefox has a feature where it remembers your tabs after a restart, but it doesn't load them until you activate them.

It would be nice if there was a way to visually distinguish tabs that aren't loaded from tabs that are, for example by having the tab title be slightly transparent for tabs that aren't loaded.

**Comment by piroor** [comment]
You can do it by userChrome.css or something. For example:

~~~
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

.tabbrowser-tab[pending="true"] label {
  opacity: 0.5;
}
~~~

**Comment by theres-waldo** [comment]
Thanks! I guess this is orthogonal to Tree Style Tab, then.

**Comment by theres-waldo** [comment]
Is there some different CSS that can be used for the WebExtension version?
