### ISSUE TITLE
Does not expand trees when navigating by keyboard (ctrl-pageup/down)

### ISSUE THREAD

**Issue by jimbo1qaz** [piroor/treestyletab#1119]
## Short description
Collapsed trees do not expand when navigating by keyboard

## Steps to reproduce
1. Open two tabs
2. Middle-click a link in each tab
3. Switch between them using ctrl-pageup/down (ctrl-tab, ctrl-shift-tab)

## Expected result
Trees expand when selected, so I can enter trees.

## Actual result
Trees do not expand. Mouse is required to enter collapsed trees.

## Environment
 * Platform (OS): Cinnamon GTK3
 * Version of Firefox: 46.0 Ubuntu
 * Version (or revision) of Tree Style Tab: 0.17.2016031101

**Comment by lv7777** [comment]
note: diffed HTML element (collapse tab and open tree tab)
maybe linedpanel isn't important.

collapsed
```
linkedpanel="panel-3-3" 
treestyletab-subtree-collapsed="true"
```

open
```
linkedpanel="panel-3-16"
treestyletab-subtree-collapsed="false"  
treestyletab-subtree-expanded-manually="true"
```

**Comment by lv7777** [comment]
and this 2 statement was defined **constants.js** around line 54,55.

**Comment by lv7777** [comment]
tab tree was controlled by `collapseExpandSubtree()` on **browser.js**, line 6503
it is also decision whenever this tab is parent, So this bug was resolved only insert this function proper place.

**Comment by piroor** [comment]
@jimbo1qaz did you talk about auto-expansion of collapsed tree while Ctrl-PageUp/PageDown? Then, the feature seems working correctly for me with TST latest development build and Firefox 46 on Windows. When a parent tab with collapsed children is focused, you'll have to keep the Ctrl key pressed for a while.

**Comment by piroor** [comment]
@jimbo1qaz and, you need to set `extensions.treestyletab.autoExpandSubtreeOnSelect.whileFocusMovingByShortcut.delay` to `0` via `about:config` to expand collapsed trees immediately  on focus. The delay is 800msec by default.
