### ISSUE TITLE
Ghost previews in Windows7 superbar

### ISSUE THREAD

**Issue by Aglan** [piroor/treestyletab#112]
Ghost previews in Windows7 superbar appears if tab tree was closed. Without Tree Style Tab there is no ghost previews.
<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/402/43864954.png/'><img src='http://img402.imageshack.us/img402/2719/43864954.png' border='0'/></a>

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
