### ISSUE TITLE
Bug 1269462  breaks Bookmarks Toolbar , Hamburger Menu and Customize Toolbar tree style tab0.17.2016051600a094946

### ISSUE THREAD

**Issue by alice0775** [piroor/treestyletab#1123]
## Short description
On Latest Nightly49.0a1 and TST 0.17.2016051600a094946,
Bookmarks Toolbar is Empty.
Not respond Hamburger Menu.
Customize Toolbar tab is empty

This is regression of Bug 1269462.

## Steps to reproduce

 1. 
 2. 
 3. 

## Environment

 * Platform (OS):  Windows10
 * Version of Firefox: 49.0a1
 * Version (or revision) of Tree Style Tab: 0.17.2016051600a094946

**Comment by TheSweetLily** [comment]
Not sure I follow. 
Things seem to be working fine for me?

**Comment by alice0775** [comment]
The problem occurs if titlebar disabled(default) and on window10

**Comment by Fanolian** [comment]
Fixed in Nightly 0520 build, possibly by bug 1273094.

**Comment by piroor** [comment]
Is this issue closable?

**Comment by Fanolian** [comment]
I think it can be closed now.

**Comment by piroor** [comment]
Thanks!
