### ISSUE TITLE
Session store + other issues starting with Firefox Nightly 2016-05-16

### ISSUE THREAD

**Issue by mayhemer** [piroor/treestyletab#1125]
TST 0.151.2015103100a005614

Please see mozilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1273445, with description, regression ranges and stacks:

[JavaScript Error: "TypeError: browserEnum.getNext(...).gBrowser is undefined" {file: "resource://app/components/nsBrowserGlue.js" line: 251}]

[JavaScript Error: "TypeError: gBrowser.treeStyleTab is undefined" {file: "chrome://treestyletab/content/windowHelper.js line 48 > eval" line: 59}]
TabsInTitlebar._update@chrome://treestyletab/content/windowHelper.js line 48 > eval:59:11
TabsInTitlebar.init@chrome://browser/content/browser-tabsintitlebar.js:45:7
gBrowserInit.onLoad@chrome://browser/content/browser.js:992:5
onload@chrome://browser/content/browser.xul:1:1

[JavaScript Error: "treestyletab: doPatching: [object XULElement]._setEffectAllowedForDataTransfer is missing!" {file: "resource://treestyletab-modules/utils.js" line: 329}]
utils_assertFunctionExists@resource://treestyletab-modules/utils.js:329:33
TSTWH_updateTabDNDObserver@chrome://treestyletab/content/windowHelper.js:137:3
TSTBrowser_init@resource://treestyletab-modules/browser.js:841:3
TSTWindow_initTabBrowser@resource://treestyletab-modules/window.js:475:4
TSTWindow_init@resource://treestyletab-modules/window.js:437:3
TSTWindow_handleEvent@resource://treestyletab-modules/window.js:618:12
EventListener.handleEvent*TreeStyleTabWindow@resource://treestyletab-modules/window.js:83:2
@chrome://treestyletab/content/treestyletab.js:22:2
@chrome://treestyletab/content/treestyletab.js:1:2

**Comment by mayhemer** [comment]
Reproducible also with TST 0.17.2016051600a094946 (had to update manually...)

[JavaScript Error: "TypeError: gBrowser.treeStyleTab is undefined" {file: "chrome://treestyletab/content/windowHelper.js line 47 > eval" line: 59}]
TabsInTitlebar._update@chrome://treestyletab/content/windowHelper.js line 47 > eval:59:11
TabsInTitlebar.init@chrome://browser/content/browser-tabsintitlebar.js:45:7
gBrowserInit.onLoad@chrome://browser/content/browser.js:992:5
onload@chrome://browser/content/browser.xul:1:1

Other errors disappeared, symptoms remain the same.

**Comment by piroor** [comment]
This problem doesn't happen on my environment. I thought that Sync can be the trigger but still doesn't happen after I activate Firefox Sync on Nightly.

**Comment by piroor** [comment]
I've checked all commits in the regression range https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=4a8ed77f6bb573f20980056bf8c1dadd125c1a85&tochange=d0be57e84807ce0853b2406de7ff6abb195ac898 but I couldn't find out possible related changes except them:

 * https://hg.mozilla.org/integration/mozilla-inbound/rev/74637d664acf
 * https://hg.mozilla.org/integration/mozilla-inbound/rev/c67242e935ee

**Comment by piroor** [comment]
Does this problem related to Sync, or not? Could you try to reproduce the problem without Sync?

**Comment by KWierso** [comment]
If it helps, I see an error in the Browser Console when starting up Nightly with TST enabled:
TypeError: aEvent.target.getSelection(...) is null
chrome://treestyletab/content/content-utils.js
Line 49, column 16

I haven't had a chance to try without Sync or other extensions, will try to do that sometime this weekend.

**Comment by mayhemer** [comment]
I probably won't get to this sooner than in two weeks or even more.  I'm currently on an older version of Nightly and not updating.  Please bare with me :)  I really want to help fix this.  TST is the most important add-on for me.

**Comment by lv7777** [comment]
@mayhemer please tell me your environments (firefox version and OS and so on)

**Comment by mayhemer** [comment]
Browser: http://ftp.mozilla.org/pub/firefox/nightly/2016/05/2016-05-16-03-02-11-mozilla-central/
Win 10, sync turned on, add-ons: FireGestures, Tab Groups, Ctrl-Tab

**Comment by mayhemer** [comment]
This seems to be fixed for me with today nightly [1].  Unfortunately, no idea since when this has been fixed.

[1] 
BuildID=20160630030207
Milestone=50.0a1
SourceRepository=https://hg.mozilla.org/mozilla-central
SourceStamp=d700dc054751333e0735f975fce3d3adf153c62a
