### ISSUE TITLE
regression bug on keyDown event

### ISSUE THREAD

**Issue by lv7777** [piroor/treestyletab#1127]
## Short description
see #1126 ,holding on key repeat only special key(e.g. ctrl,shift).

___

- [ ]  AHB_onKeyDown@resource://treestyletab-modules/autoHide.js:1442:11
- [ ] AHB_handleEvent@resource://treestyletab-modules/autoHide.js:1289:12
- [ ] TSTBase_fireCustomEvent@resource://treestyletab-modules/base.js:619:10
- [ ] TSTWindow_onKeyDown@resource://treestyletab-modules/window.js:873:3
- [ ] TSTWindow_handleEvent@resource://treestyletab-modules/window.js:718:12
- [ ] EventListener.handleEvent*TSTWindow_startListenKeyEventsFor@resource://treestyletab-modules/window.js:805:4
- [ ] TSTWindow_onPrefChange@resource://treestyletab-modules/window.js:2020:6
- [ ] TSTWindow_init@resource://treestyletab-modules/window.js:480:3
- [ ] EventListener.handleEvent*TreeStyleTabWindow@resource://treestyletab-modules/window.js:93:2@
- [ ] chrome://treestyletab/content/treestyletab.js:30:2
@chrome://treestyletab/content/treestyletab.js:1:2

## Steps to reproduce

 1. right click on tab bar,and click "collapse mode"
 2. holding on ctrl mode(make sure access key(by default : ctrl) )
 3. 

## Expected result

Evely one type key, only one keyDown occarred.

## Actual result

keyDown event occurred many time.

## Environment

 * Platform (OS): windows 10
 * Version of Firefox: 48.a2
 * Version (or revision) of Tree Style Tab: leastest 

note: 
keyEvent is sensitive.
a little bit differ environment was occurred by big diffed result.

**Comment by piroor** [comment]
I think we cannot "change" the behavior of the keydown event itself. Instead, we should accept it and redesign codes to handle the event based on the actual behavior.

Expected/actualの表現が「keydownイベントがどれだけ発火されるか」にフォーカスしていますが、これはDOMの仕様だったりGeckoの実装だったりによって起こっていることで、アドオンのレイヤからどうこうできるものではないというのが自分の認識です。
もし仮に「このような状況で、keydownイベントを1回だけ発火させるようにしたい」とお考えなのであれば、そのアプローチは現実的でないと思いますし、またこのようなkeydownイベントの挙動はかねてからの物だと思われますので、Geckoの挙動変更の提案としても受理されにくいと思います。

keydownイベントの扱いに起因して問題が起こっている、という事実には気をつけ続ける必要がありますが、issueの立て方・問題への取り組み方としては、それによって引き起こされているもっと表面的な現象（UIの挙動）の方にフォーカスするのが良いと思います。

**Comment by piroor** [comment]
ということを踏まえると、こちらはcloseして #1114 を継続というのが妥当そうな気がしています。

**Comment by lv7777** [comment]
@piroor 
keydownイベントに関してはネットとかで調べてみると一度目のkeydownの値を保持しておいて、keyup時にそのイベントを渡すみたいな実装が多いっぽいです。
TSTでもどっかでそんなような処理をしてるところを見た気がする・・・
その時に今回は時間が重要になるので最初の一回はnew Dateでも取っておくのがいいかと思います。
