### ISSUE TITLE
Developer Tools menu is (almost) empty

### ISSUE THREAD

**Issue by mystor** [piroor/treestyletab#1128]
## Short description
When treestyletab is installed, the developer tools menu under Tools is almost empty, and does not contain useful entries such as `Toggle Tools`. As a related effect, the keyboard shortcuts to open developer tools do not function correctly.

## Steps to reproduce
 1. Install treestyletab from addons.mozilla.org
 2. Open Tools->Developer Tools

## Expected result
All normal Developer Tools options are available, including Toggle Tools, Inspector, and Web Console. The keyboard shortcuts for these options function correctly.

## Actual result
The only available Developer Tool is Page Source. The keyboard shortcuts for the other developer tools do not function correctly.

## Environment

 * Platform (OS): Mac OS X 10.10
 * Version of Firefox: 49 nightly
 * Version (or revision) of Tree Style Tab:  0.17.2016031101

**Comment by lv7777** [comment]
I seem that behave was occurred by other problem(i.e. firefox bug or environment).

at least, my environment was not occurred.
___
* firefox 49 nightly.
* windows 10
* TST current master branch

**Comment by mystor** [comment]
After updating nightly, the problem went away. It was probably on ffx's side.

Thanks. I'll re-open if I discover a more reliable reproduction mechanism.
