### ISSUE TITLE
Can't open multiple tabs from bookmarks

### ISSUE THREAD

**Issue by sale-1** [piroor/treestyletab#1129]
From Firefox archive I only can open a one bookmark at a time with mouse right click.

## Steps to reproduce

 1. Ctrl+Shift+B
 2. Select more than 2 bookmarks
 3. Right click --> open all in tabs

## Expected result

Should open new tabs for each selected bookmark. Some months ago I had no problem: after "open all in tabs" it automatically returned to the main FF window and all the opened bookmarks were loading. 

## Actual result

nothing happens. 

## Environment

 * Platform (OS): Windows 7
 * Version of Firefox: 46.0.1
 * Version (or revision) of Tree Style Tab: 0.17.2016031101
 * Other active extensions: Tab Mix Plus 0.4.2.2 + Classic Theme restorer 1.5.2 (both no matter active/not). I've also tried "Open Bookmarks in New Tab 2.0.2016021001" but nothing happens.

**Comment by lv7777** [comment]
this bug was fixed by me :)
related #1098

**Comment by sale-1** [comment]
Thanks! I saw #1098 issue before, but did not understand the end. And it is sad, I don't have skills to twist the code...

**Comment by piroor** [comment]
You can try an unsinged package from http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by sale-1** [comment]
Thanks for trying!

**Comment by sale-1** [comment]
Now working OK!
