### ISSUE TITLE
"新しいタブを追加"の位置が一番下になったまま戻らない

### ISSUE THREAD

**Issue by lv7777** [piroor/treestyletab#1131]
## Steps to reproduce
1. タブを自動的に縮めるをクリック
2. その後右端の左右に大きさを変えれるところ(半透明になっている方)を持ちタブバーの大きさをデフォルトより(実体化されているところより)小さくする。
3. そうすると”新しいタブを追加"の位置が一番下に行く。
## Expected result

そもそも下に行かない
## Actual result

下に行ったまま戻らない。
## Environment
- Platform (OS): windows 10
- Version of Firefox: firefox 48.a02
- Version (or revision) of Tree Style Tab: master branch

**Comment by piroor** [comment]
状況が今ひとつ分からないので、スクリーンショットを貼っていただけますでしょうか？

**Comment by lv7777** [comment]
<img width="151" alt="aa" src="https://cloud.githubusercontent.com/assets/8572307/15737492/3b52cb82-28e1-11e6-84a2-f079c915f7af.png">
こんな感じです。"新しいタブの追加"が一番下に吹っ飛んでいます

**Comment by piroor** [comment]
ありがとうございます！

**Comment by piroor** [comment]
「自動的にタブバーを縮める」を有効にした状態で再現を試みたのですが、再現できませんでした。ただ、Nightly 49.0a1において、「自動的にタブバーを縮める」を無効化した後のタイミングでよく似た状況が再現しました。タブバーのtabs要素に`overflow="true"`が意図せず設定されてしまっているためにこの表示になっているということなのですが、これはタブがタブバーから溢れた時にだけ設定されることが期待される属性なので、どこかの時点でタブバーが溢れたかどうかの判定がおかしくなっているのだと思われます。

**Comment by piroor** [comment]
Firefox自身によってoverflow属性が設定・変更されるのはoverflow/underflowイベントが発生した時。意図せずoverflow/underflowが発生した時に、overflow属性が変更されうる。
http://mxr.mozilla.org/mozilla-central/source/browser/base/content/tabbrowser.xml#4833

TSTでも何箇所かでこの属性を設定している。このどれかの判定が狂っていると、このような状況が発生しうる。

~~~
$ git grep "'overflow'"
...
modules/browser.js:             b.mTabContainer.removeAttribute('overflow');
modules/browser.js:                             container.removeAttribute('overflow');
...
modules/browser.js:             b.mTabContainer.removeAttribute('overflow');
modules/browser.js:                     container.removeAttribute('overflow');
modules/browser.js:                     b.mTabContainer.setAttribute('overflow', true);
modules/browser.js:                             container.setAttribute('overflow', true);
modules/browser.js:                     b.mTabContainer.removeAttribute('overflow');
modules/browser.js:                             container.removeAttribute('overflow');
...
modules/browser.js:                             tabs.setAttribute('overflow', 'true');
modules/browser.js:                             tabs.removeAttribute('overflow');
~~~

**Comment by lv7777** [comment]
自分でも改めてやってみたのですがデフォルト(実体化している)のタブバーの幅を大きくしてその状態で仮想タブを縮めるてもこの状態は発生しませんでした。
実体化しているタブがアイコンの大きさぐらいより小さいときに発生してます。

**Comment by piroor** [comment]
確認できました！ 縮んだ状態のタブバー幅が極端に小さい時にこの現象が起こるようです。（ところで、TSTでは「タブバーを自動で縮める」モードでの各状態を「shrunken（縮んだ）」と「expanded（展開された）」と表現しているので、再現条件の説明もそれらの用語に合わせていただけると理解しやすくなって助かります……！）

**Comment by piroor** [comment]
というか、自動で縮めるにしていなくても、極端にタブバーの幅を狭くするとこの現象が起こるようですね。（その後幅を広げてもoverflowの状態は元に戻らない）

**Comment by piroor** [comment]
ダサイ解決策ですが、 7d023b1 でタブバーの更新処理が走るタイミングで常にoverflowの状態をチェックするようにしました。誤判定でoverflow=trueになってしまったとしても、すぐに正しい状態に戻るようになったと思います。

**Comment by lv7777** [comment]
ありがとうございます。
> （→PR歓迎ということで……）

ではcloseしないままのほうがいいですね。

> 再現条件の説明もそれらの用語に合わせていただけると理解しやすくなって助かります

これなんですけどあの薄くなってる状態もexpandedでいいんですか？
shrunkenの状態からマウスをhoverしてもexpandedにならないのでこういう用語にしたのですが。

**Comment by piroor** [comment]
> これなんですけどあの薄くなってる状態もexpandedでいいんですか？

内部的にはそういう扱いですね。タイミングが悪くてexpandedの幅の方がshrunkenよりも小さくなってしまっているということかなぁ（先日入れた変更のregressionかもです）

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
