### ISSUE TITLE
TST greatly affects performance (lags, long UI freezes) when resizing Fx window

### ISSUE THREAD

**Issue by Drugoy** [piroor/treestyletab#1133]
## Short description
Resizing firefox window (with at least a few tabs (doesn't matter loaded or not) on the tab-bar) causes long UI freezes / lags cause by TST.

## Steps to reproduce

 1. Open 5 tabs.
 2. Resize Firefox window by dragging its corner (with periodical 'stops' in dragging).
 3. Try to hover & click some elements and see if they respond and how fast they respond.
 4. Watch TST performance in about:performance tab

## Expected result
No UI freezes, the browser is responsible almost instantly after the redraw that takes places after resizing the window.

## Actual result
Long UI freezes, elements react to :hover and clicks with noticeable delay (or do not react to some of them at all).
about:performance tab show TST being at fault of poor performance.

## Environment

 * Platform (OS): Windows 7 SP1 x64
 * Version of Firefox: any up to 47.
 * Version (or revision) of Tree Style Tab: 

I use TST with horizontal single line top toolbar without visual deep hierarchy (visually there are just parent tabs and child tabs, just 2 levels).

Disabling TST made the issues go away.

The issue is less noticeable on a clean profile without add-ons.

Also, opening Inspector (Ctrl+Shift+C) makes those lags even longer. With TST disabled - it almost doesn't affect the performance (the UI is fully responsive right after the repaint that happens during/after the drag'n'drop of the corner).

**Comment by piroor** [comment]
Does this problem appear only with TST? If you use other addons, combination of them can cause it. Then, could you shrink the list of addons? (I'm sorry if you saw this problem with TST and a clean profile.)

**Comment by wsmwk** [comment]
@Drugoy, can you update your bug please?

**Comment by Drugoy** [comment]
You may close it or do whatever: I stopped using TST after figuring out it was causing those damn huge lags.
