### ISSUE TITLE
Don't use `new Function()`

### ISSUE THREAD

**Issue by piroor** [piroor/treestyletab#1138]
I got a review comment from AMO editor:

> I apologize but in the last review i mised your eval statement. Can you please change this with a non-eval non-function protype method: (new Function('return refNode = '+insertBefore))(); in browser.js
> 
> I did not reject this version as it will disable your whole listing. Please update soon.

For this situation we seems to migrate it to XPath or something more safer way.

**Comment by lv7777** [comment]
@piroor need contribution?

**Comment by piroor** [comment]
Maybe yes. However this should be done by https://github.com/piroor/multipletab also.

**Comment by piroor** [comment]
Sorry, finally it has been done by myself.

https://github.com/piroor/multipletab/compare/69197de463d38a7bd8d3f70a3ccc0e2e90a120a6...0959b3362b1615ec6916a95749810ec6850b8866
https://github.com/piroor/treestyletab/compare/cdc3a181ac657bb8d3592de35eb6f3943ae526a6...c58e8a95fcbb35cabb47dcee6e45d1a878a24941
