### ISSUE TITLE
If the current tab is the last in the branch of a tree, then a new tab opens through one of the current tab

### ISSUE THREAD

**Issue by Dook1** [piroor/treestyletab#1140]
## Short description

If the current tab is the **LAST** in the branch of a tree, then a new tab opens through one of the current tab (video attached).
Setting: 
 extensions.treestyletab.controlNewTabPosition=false 
 browser.tabs.insertRelatedAfterCurrent=false
## Steps to reproduce
1. Start Filrefox with clean profile.
2. Install TST.
3. Set: 
   extensions.treestyletab.controlNewTabPosition=false
   browser.tabs.insertRelatedAfterCurrent=false
4. Select **LAST** tab in the branch of any tree as current.
5.  Open new tab (button or Ctrl+T)
## Expected result

A new tab should be opened next to the current.
## Actual result

A new tab is opened through one of the current.
## Environment
- Platform (OS): Windows 8.1
- Version of Firefox: 48b1
- Version (or revision) of Tree Style Tab: 0.17.2016061501

![untitled-3](https://cloud.githubusercontent.com/assets/18645441/16231556/5e214d62-37cf-11e6-960d-d3dab983b961.gif)

**Comment by piroor** [comment]
This doesn't happen on my environment. Is this a conflict of TST and Tab Mix Plus?

**Comment by Dook1** [comment]
I reset the settings of TMP and this problem has been resolved. But this error apparently is related to #1143

**Comment by Dook1** [comment]
I reset the settings of TMP and this problem has been resolved. But this error apparently is related to #1143

**Comment by piroor** [comment]
#1143 seems to be fixed by 2b13d99. Does it affect to this issue?

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
