### ISSUE TITLE
Prevent Automatic Collapse/Expand to keep all tab depths/tab titles in view

### ISSUE THREAD

**Issue by ghost** [piroor/treestyletab#1142]
## Short description

In the past, there was an option to prevent the collapse/expand of tab trees, which basically allowed you to see all tabs and all depths at once. This is great on a wide screen monitor where you can afford to widen the tab tree sidebar considerably, and it helps when bouncing between multiple trees. Trees end up lost with the current behavior as the original feature was stripped.
## Steps to reproduce
1. Start Firefox with clean profile.
2. Install TST.
3. Open up several nested trees and click between parent tabs
## Expected result

Desired behavior is to keep all expanded unless manually collapsed via arrow
## Actual result

Current behavior causes clicked parent trees to automatically expand on click and the previous parent tree to collapse at the same time, preventing the user from maintaining a view of all tab titles at all times. User must manually expand all parent trees to prevent automatic collapse/expand. Adds lots of user burden.
## Environment
- Platform (OS): Any
- Version of Firefox: Any
- Version (or revision) of Tree Style Tab: Current

**Comment by TheSweetLily** [comment]
I've noticed this too.

**Comment by mhicklen** [comment]
Seems you can cope with the behavior under the options -> Tree -> 2nd option "When a tab gets focus, expand its tree and collapse others automatically" though it isn't clear if this will forcibly prevent the collapse/expand.

Basically I want to be able to remove the collapse/expand arrows and know that I'm never missing a tab.

**Comment by piroor** [comment]
This is an intentional decision. In short; because I never use it. My hands are already full to fix problems around my usecase.

**Comment by piroor** [comment]
> Cool. There's a lot of stuff you put into it that I never use. Can you remove that?

Possibly yes, when a difficult problem is reported around a feature I don't use. Actually, the optional behavior "never collapse tabs" produced some odd behaviors around tabs "visually not collapsed, but internally collapsed". It was hard for me to solve various problems around such a special status appearing only in the mode.

**Comment by TheSweetLily** [comment]
Mh, I see. Thanks for the explanation for why it's gone.

**Comment by sumyungguy** [comment]
@mhicklen You said "Desired behavior is to keep all expanded unless manually collapsed via arrow". If you uncheck all boxes under "Tree" preferences, that's exactly what happens. I don't understand what you're asking for?

**Comment by chronometric** [comment]
Indeed....I'm a 100-500 tab user, and I just keep all trees open at all times. Always know where everything is, only collapse something when I'm about to close it or send it to another group.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
