### ISSUE TITLE
If the current tab is the last in the branch of a tree, and insertNewChildAt=0, autoAttach.newTabCommand=3, a new tab will open in the beginning of the tree

### ISSUE THREAD

**Issue by Dook1** [piroor/treestyletab#1143]
## Short description

If the current tab is the last in the branch of a tree, and options set to: 
insertNewChildAt=0 ("Insertion position of new child tabs" - "Insert to the top of the tree, as the first child") 
autoAttach.newTabCommand=3 ("Open new blank tab as" - "the next sibling of the current tab")
a new tab((button or Ctrl+T) will open in the beginning of the tree.
## Steps to reproduce
1. Start Filrefox with clean profile.
2. Install TST.
3. Set: 
4. insertNewChildAt=0  ("Insertion position of new child tabs" - "Insert to the top of the tree, as the first child")
5. autoAttach.newTabCommand=3 ("Open new blank tab as" - "the next sibling of the current tab")
6. Select LAST tab in the branch of any tree as current.
7. Open new tab (button or Ctrl+T)
## Expected result

A new tab should be opened next to the current.
## Actual result

A new tab is opened in the beginning of the tree.
## Environment
- Platform (OS): Windows 8.1
- Version of Firefox: 48b5
- Version (or revision) of Tree Style Tab: 0.17.2016061501
  ![untitled331](https://cloud.githubusercontent.com/assets/18645441/16583736/34503e8e-42c0-11e6-970a-766aecc20478.gif)

**Comment by Dook1** [comment]
Its not related to TMP. TMP is disabled.

**Comment by piroor** [comment]
Thanks, I've confirmed.

**Comment by piroor** [comment]
The commit 2b13d99 should fix this issue.

**Comment by Dook1** [comment]
This commit works, but only if the new tab is created through a button or Ctrl-T. But if in TMP set extensions.tabmix.openTabNext=true and a new tab is created for example through context search(right click) or running the html file from the Explorer, everything is still - a new tab is created at the beginning of the tree.

**Comment by piroor** [comment]
Sorry, I missed an edge case about the really last tab. By recent commits the behavior should work correctly. Could you try the dev build again?

**Comment by Dook1** [comment]
Now tab will not open at all.

**Comment by Dook1** [comment]
And now tab opens in a new window.

**Comment by piroor** [comment]
Does the fix 6f658d4eefe7f1330ceae0f97a295df83ea7ea7d work for you?

**Comment by Dook1** [comment]
Now: 
1) button or Ctrl-T opens the new tab  - as the next sibling (it's correct)
2) context search(right click) opens the new tab - as child of the current tab (can be called "correct", but it's a stretch)
3) running the external html file from the Explorer open the new tab - **at the beginning of the tree** **(it's incorrect)**

**Comment by piroor** [comment]
The commit 81e2c10 possibly affects to this problem. Any status change?

**Comment by Dook1** [comment]
No, problem is still

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
