### ISSUE TITLE
New Tab button/tab is missing from the bottom of the tree

### ISSUE THREAD

**Issue by albirch** [piroor/treestyletab#1144]
## Short description
When I clean install everything and install, I don't see the New Tab button/tab at the bottom of the tree. Not sure what is wrong with it.
## Steps to reproduce

 1. Start Filrefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Expected result
New Tab button/tab on the bottom of the tree (the little tab with a plus sign)

## Actual result
No New Tab button/tab at the bottom of the tree

## Environment

 * Platform (OS): Win10 
 * Version of Firefox: 47.0.1 x64
![capture](https://cloud.githubusercontent.com/assets/8645125/16662774/e61efab0-442d-11e6-950a-f9554c6757b5.PNG)

 * Version (or revision) of Tree Style Tab: 0.17.2016061501

**Comment by albirch** [comment]
Looks like an FF configuration issue on my end. I will close this.

**Comment by MelOrecklin** [comment]
I have the same problem.  

Tree Style was installed a few days ago on Windows 10 fully-patched.  The Firefox version is 47.0
