### ISSUE TITLE
vertigoスキンとdevtool.theme="dark"を使ったときタイトルの文字色が白くなる

### ISSUE THREAD

**Issue by lv7777** [piroor/treestyletab#1145]
## Short description
firefox 通常版を使うとタブバーの背景がfirefoxのデフォルトのテーマの白基準になるのですが、それとなおかつabout:configからdevtool.themeの色をdarkに変えるとタイトルの文字色が白になり、タブバーの背景が白のため、読みにくくなります。

## Steps to reproduce

 1. Start Filrefox(release version) with clean profile.
 2. Install TST.
 3. open about:config
 4. search devtools.theme and set "dark"
 5. open about:addons and click treestyletab "設定"
 6. set skin on "vertigo"

## Expected result

タイトルの文字色が黒になる

## Actual result

タイトルの文字色が白くなっている。

## Environment

 * Platform (OS): windows10
 * Version of Firefox: 47.0.1
 * Version (or revision) of Tree Style Tab: 0.17.2016061501

**Comment by piroor** [comment]
https://github.com/piroor/treestyletab/issues/1146#issuecomment-231415123 の理由で、こちらも改善が必要という認識です。
