### ISSUE TITLE
vertigo skinもしくはdefault skinを使用してdevtools.theme="dark"を指定したとき"タブを追加"の色が周りと合わない

### ISSUE THREAD

**Issue by lv7777** [piroor/treestyletab#1146]
## Short description

firefox 通常版を使うとタブバーの背景がfirefoxのデフォルトのテーマの白基準になるのですが、それとなおかつabout:configからdevtool.themeの色をdarkに変えると"タブを追加"ボタンに関係するcss変数の値がこの値で判断しているため、"タブを追加"ボタンが周りが白の状態でも黒になりUIが悪くなります。

## Steps to reproduce

 1. Start Filrefox(release version) with clean profile.
 2. Install TST.
 3. open about:config
 4. search devtools.theme and set "dark"

## Expected result

デフォルトskinやvertigo skinでの予想している動作が
* 開発者ツールで設定した色に合わせる

なのか
* デフォルトのfirefoxのテーマに合わせる

のかわからないため正しい動作がわかりません。

期待している動作はどちらでしょうか？ @piroor 
## Actual result

"タブを追加"ボタンが黒基準になっていてなおかつ周りの色が白基準になっていて見にくい。

## Environment

 * Platform (OS): windows 10
 * Version of Firefox: 47.0.1(通常リリース
 * Version (or revision) of Tree Style Tab:  0.17.2016061501

**Comment by lv7777** [comment]
related #788 #1111

**Comment by piroor** [comment]
> 期待している動作はどちらでしょうか？ @piroor 

「開発者ツールの配色」ではなく、「その時のFirefoxのUI全体の配色」に合った状態になる事が期待されます。

**Comment by piroor** [comment]
言葉が足りてませんでした。以上を踏まえると、全体の色は明るいのに開発者ツールは暗いという場合には、全体の色の方に合わせたいです。

**Comment by lv7777** [comment]
そうするとcss側はjsの値を取ってこれないし、周りの色で判定すると重複もあり得るのでエレガントな解決方法ではないため、thememanager.jsあたりで`extensions.treestyletab.tabbar.style`の値を取ってきてそれに応じて読み込むcssを変えるとかがよさそうですかね。

**Comment by lv7777** [comment]
あとはXMLにcurrentskinのような属性をつけてcss変数で判定する方法もアリですね。
この方法なら #1145 も一気に解決します。

**Comment by piroor** [comment]
> あとはXMLにcurrentskinのような属性をつけてcss変数で判定する方法もアリですね。

この方法が有力な気がします。
https://dxr.mozilla.org/mozilla-central/source/browser/base/content/browser-devedition.js
この`DevEdition`というオブジェクトがブラウザウィンドウの名前空間にある場合にのみmodules/window.jsで特別な処理をする、みたいな感じかなあと予想してます。そうすれば、

~~~
:root[devtoolstheme="dark"] {
~~~

を

~~~
:root[devtoolstheme="dark"][treestyletab-devedition="true"] {
~~~

のようにして「Developer Edition且つdarkの時だけスタイルを反映」ということができますね。

**Comment by piroor** [comment]
「何らかの」と書きましたが、真面目にやると結構大変（`TabAttributesObserver`がやっているような方法でMutationObserverを登録して、ルート要素の`devtoolstheme`属性の値を監視し、変更されたら`DevEdition.isThemeCurrentlyApplied`の値を見て`treestyletab-devedition`属性の値を切り替える、みたいなことになる）ですね……

筋はあまり良くないですが、windowHelper.jsの中でやっているような方法で`DevEdition._updateDevtoolsThemeAttribute`を上書きして後処理を追加するというのが一番簡単そうだと思いました。
コストとメリット･デメリットを考えると、バランスの良い落とし所はこれではないかな？と思ってます。

**Comment by lv7777** [comment]
windowsHelper.jsを調べてみたのですが`DevEdition._updateDevtoolsThemeAttribute`をいじっているような処理が見つかりませんでした。。。

> 真面目にやると結構大変

そうですかね？
MutationObserverを見てみたのですがdevtoolsthemeの値を監視してcallbackでXULの`devtoolstheme`が指定されている所のdomの属性をlabel.setAttributeで変更するだけでいい気がしますが、

> 変更されたらDevEdition.isThemeCurrentlyApplied
の
https://hg.mozilla.org/mozilla-central/rev/484fe7759dd4#l1.18
の処理っていりますかね？

まあ後者のMutationObserverのほうだと`属性の値を見て属性を変えてその値を見る`という冗長感が否めないですが・・・

**Comment by piroor** [comment]
> windowsHelper.jsを調べてみたのですがDevEdition._updateDevtoolsThemeAttributeをいじっているような処理が見つかりませんでした。。。

すみません、説明が不足していました。
windowHelper.jsには「Firefoxの各種サービスオブジェクトやtabbrowser要素などのメソッドを置き換えて再定義するコード」がまとめられています。
それらの例と同じ要領で`DevEdition._updateDevtoolsThemeAttribute`を再定義して必要な後処理を追加すれば良いだろう、ということを言いたかったのでした。

**Comment by lv7777** [comment]
必要な後処理というのは_updateDevtoolsThemeAttributeでxulのcssを直接いじってcss変数で使用する属性は追加しないということでしょうか？

**Comment by piroor** [comment]
いえ、`_updateDevtoolsThemeAttribute`の後処理で`document.documentElement.setAttribute('treestyletab-devedition', true)`などとやって、この属性がある時だけdark用の配色を反映するようにセレクタの指定を変更するということのつもりでした。

というか、よく考えたらそもそもこのメソッドの後処理でやる必要すらなくて、TreeStyleTabWindowの初期化処理の中で`if (typeof this.window.DevEdition === 'undefined')`みたいな条件で分岐して上記の属性を設定すれば済みそうですね。
無駄に混乱させてしまいました。ごめんなさい。

**Comment by lv7777** [comment]
> というか、よく考えたらそもそもこのメソッドの後処理でやる必要すらなくて、TreeStyleTabWindowの初期化処理の中でif (typeof this.window.DevEdition === 'undefined')みたいな条件で分岐して上記の属性を設定すれば済みそうですね。

firefox developer edition(49.0a2)でもfx通常リリース(47.0)でもwindow.DevEditionオブジェクトが存在することを確認しています。
このバグが発動する条件として
`firefox 通常リリース && (vertigo skin || 通常のスキン) && (devtools.theme == 'dark')`
というのがあります。

firefoxがdev editionか通常リリースかを判断する方法が欲しいんですけどそういった方法を誰か知っている方はいませんか？

**Comment by lv7777** [comment]
また、`if (typeof this.window.DevEdition === 'undefined')`で判断する方法だと、treestyletabの起動時のスキンで新しいタブを追加が判断されてしまうのでskinが変わった時に対応できない気がします。

**Comment by lv7777** [comment]
windows.jsでxulの要素を取ってこようとしたのですがdocumentがないと言われたのでgrepで検索したらbookmarksOverlayEditable.jsあたりで使っていたのでそこでwindow.DevEdition._updateDevtoolsThemeAttributeをオーバーライドしたら無事に`devtools.theme`の値を変えた時にオーバーライドで追加したメソッドが反応するようになりました。

**Comment by piroor** [comment]
> firefox developer edition(49.0a2)でもfx通常リリース(47.0)でもwindow.DevEditionオブジェクトが存在することを確認しています。

おお、それは残念。一気に解決かと思ったんですけどね……

> firefoxがdev editionか通常リリースかを判断する方法が欲しいんですけどそういった方法を誰か知っている方はいませんか？

Developer EditionかどうかはFirefoxのビルドオプションで切り替えられているので、そのビルドオプションが有効な時だけ定義されている物や値を使うというのがいいと思います。
DXRで「DevEdition」で検索していたら「isDevEdition」という関数が見つかったのでそこで参照しているAppConstantsというJSコードモジュールのMOZ_DEV_EDITIONというプロパティの値を見てみたら、ビルドオプションによってプロパティの値が切り替わるようでした。
https://dxr.mozilla.org/mozilla-central/search?q=DevEdition&=mozilla-central
https://dxr.mozilla.org/mozilla-central/search?q=isInDevEdition
https://dxr.mozilla.org/mozilla-central/search?q=file%3AAppConstants.jsm&redirect=false
https://dxr.mozilla.org/mozilla-central/source/toolkit/modules/AppConstants.jsm#56
これを参照するのが確実そうです。

と、mozilla-centralだけだと不安だったので念のためESR45ブランチも見てみたら、こちらではこの定数プロパティが定義されていませんでした。
https://dxr.mozilla.org/mozilla-esr45/search?q=file%3AAppConstants.jsm&redirect=true
https://dxr.mozilla.org/mozilla-esr45/source/toolkit/modules/AppConstants.jsm

hg blameの結果 https://hg.mozilla.org/mozilla-central/annotate/88bebcaca249aeaca9197382e89d35b02be8292e/toolkit/modules/AppConstants.jsm#l56 を見てみたところ、
https://hg.mozilla.org/mozilla-central/diff/b1db238e620f/toolkit/modules/AppConstants.jsm#l55
https://hg.mozilla.org/mozilla-central/rev/b1db238e620f
https://bugzilla.mozilla.org/show_bug.cgi?id=1233470
でこの定数プロパティが定義されていて、Firefox 46以降でないと存在しないようです。

とはいえ、今のDeveloper EditionはいずれにせよFirefox 46よりは新しいバージョンなので、このプロパティが存在して且つtrueならDeveloper Editionと見なせる、ということには変わりは無さそうです。

**Comment by piroor** [comment]
> windows.jsでxulの要素を取ってこようとしたのですがdocumentがないと言われたのでgrepで検索したらbookmarksOverlayEditable.jsあたりで使っていたのでそこでwindow.DevEdition._updateDevtoolsThemeAttributeをオーバーライドしたら無事にdevtools.themeの値を変えた時にオーバーライドで追加したメソッドが反応するようになりました。

window.jsはCu.importで読み込まれるため、XULドキュメントの名前空間では実行されず、バックステージパスという特別な名前空間の中で実行されます。なので、グローバルオブジェクトはXULウィンドウではありませんし、単にdocumentと書いてもその名前空間のグローバルオブジェクトにはプロパティが存在しないため、エラーになります。
TreeStyleTabWindowは初期化の時に引数でDOMウィンドウを渡されて、それをインスタンスごとのメンバ変数として保持しているので、各メソッドからはthis.windowやthis.documentで参照できます。

**Comment by piroor** [comment]
ただ、メソッドを置き換える系の処理はTreeStyleTabWindowの定義の中には書かずに、windowHelper.jsのTreeStyleTabWindowHelper.initTabbrowserMethodsやTreeStyleTabWindowHelper.preInitなどで定義するように分けています。これは、Firefoxのメソッドを置き換える処理があちこちに散らばっていると見通しが悪くなると判断してのことです。
なので、今回DevEdition._updateDevtoolsThemeAttributeを置き換える処理も、windowHelper.jsの中に書いて頂けると、より設計意図に合ったコードになります。

**Comment by piroor** [comment]
↑で長々書いてしまいましたが、

> というか、よく考えたらそもそもこのメソッドの後処理でやる必要すらなくて、TreeStyleTabWindowの初期化処理の中でif (typeof this.window.DevEdition === 'undefined')みたいな条件で分岐して上記の属性を設定すれば済みそうですね。

と書いた通り、AppConstants.MOZ_DEV_EDITIONがtrueかどうかでこの判断ができそうなので、メソッドの置き換えは不要ですね。単にTreeStyleTabWindow.prototype.initあたりでthis.document.documentElementの属性を設定するということになります。

**Comment by lv7777** [comment]
> と書いた通り、AppConstants.MOZ_DEV_EDITIONがtrueかどうかでこの判断ができそうなので、メソッドの置き換えは不要ですね。単にTreeStyleTabWindow.prototype.initあたりでthis.document.documentElementの属性を設定するということになります。

この方法だと、例えば最初にmixedスキンでその後デフォルトに変えてその後vertigoスキンに変えた時に対応できませんでした。
mixedスキンの場合は周りの色が黒なのですが、vertigo skinの場合は同じ条件でも周りの色が白になるため、オブザーバーによって属性をつけたり外したりしないと周りの色に対応できません。
ググったらprefsにaddObserverを使用すれば監視できるっぽいのでそれを使おうかと考えているのですが、addObserverの引数にxpcomを使用しないといけない感じです。

**Comment by piroor** [comment]
状況がよく分からなくなってきたので改めて整理します。

 * 今のTSTのスタイル指定で言う、普通のカラーセットが使われるべき場面
   * Developer Edition以外で、Vertigo以外で、devtools.theme=lightである
   * Developer Edition以外で、Vertigo以外で、devtools.theme=darkである
   * Developer Edition以外で、Vertigoで、devtools.theme=lightである
   * Developer Edition以外で、Vertigoで、devtools.theme=darkである
   * Developer Editionで、Vertigo以外で、devtools.theme=lightである
   * Developer Editionで、Vertigoで、devtools.theme=lightである
   * Developer Editionで、Vertigoで、devtools.theme=darkである
 * 今のTSTのスタイル指定で言う、darkテーマ用のカラーセットが使われるべき場面
   * Developer Editionで、Vertigo以外で、devtools.theme=darkである

こういう事で良いでしょうか？
間違っていたら訂正して頂けると助かります。

仮に上記の通りなのであれば、ブラウザウィンドウのルート要素にはTSTのスキン名も属性値で設定されているので、それと https://github.com/piroor/treestyletab/issues/1146#issuecomment-232350845 の変更で設定されるようになる属性値を組み合わせれば、

~~~
:root[devtoolstheme="dark"] {
~~~

を

~~~
:root[devtoolstheme="dark"][treestyletab-devedition="true"]:not([treestyletab-style~="vertigo"]) {
~~~

という風に「Developer Editionで、Vertigo以外で、devtools.theme=darkである」をCSSセレクタだけで表現できるのではないか？と思いました。

**Comment by lv7777** [comment]
`firefox 通常リリース && (vertigo skin || 通常のスキン) && (devtools.theme == 'dark')`
というのがこのバグが発動する条件です。周りが普通のカラーセットですがタブのみdarkカラーセットが使用されてしまいます。


`:root[devtoolstheme="dark"][treestyletab-style]:not([treestyletab-style~="vertigo"])`
という条件で通常エディションのほうについてはfixできました。
ただしdeveditionのほうでdarkに指定されるはずのものが指定されないレグレッションバグが起こるのを確認しています。

**Comment by lv7777** [comment]
というかtreestyletab-styleなんて属性があったんですね・・・orz
最初にそれっぽい属性を確認したつもりでしたが見逃してました・・・
これがあればオブザーバー要らないですね。
本格的にオブザーバー実装する前でよかった・・・

**Comment by piroor** [comment]
ブラウザツールボックスのインスペクタでルート要素を見ると色々設定してるのが見れますよ！
https://developer.mozilla.org/ja/docs/Tools/Browser_Toolbox

**Comment by piroor** [comment]
期待される結果

 * 今のTSTのスタイル指定で言う、普通のカラーセットが使われるべき場面
   * Developer Edition以外で、devtools.theme=lightである
   * Developer Edition以外で、devtools.theme=darkである
   * Developer Editionで、devtools.theme=lightである
 * 今のTSTのスタイル指定で言う、darkテーマ用のカラーセットが使われるべき場面
   * Developer Editionで、devtools.theme=darkである

実際の結果

 * 今のTSTのスタイル指定で言う、普通のカラーセットが使われるべき場面
   * Developer Edition以外で、Mixed/Plain/Sidebar/Metalで、devtools.theme=lightである
   * Developer Edition以外で、Mixed/Plain/Sidebar/Metalで、devtools.theme=darkである
   * Developer Edition以外で、Vertigo/Defaultで、devtools.theme=lightである
   * Developer Editionで、Mixed/Plain/Sidebar/Metalで、devtools.theme=lightである
   * Developer Editionで、Vertigo/Defaultで、devtools.theme=lightである
 * 今のTSTのスタイル指定で言う、darkテーマ用のカラーセットが使われるべき場面
   * Developer Editionで、Mixed/Plain/Sidebar/Metalで、devtools.theme=darkである
   * Developer Editionで、Vertigo/Defaultで、devtools.theme=darkである
   * Developer Edition以外で、Vertigo/Defaultで、devtools.theme=darkである ←現状ではこれがおかしい

ですかね？

**Comment by piroor** [comment]
間違えてました。もう1回やり直し。
改めて、本当に期待されている結果（ここまでで自分と大沼さんの間でコンセンサスを得ていなかったようなので、あくまで、自分が思う期待値ということですが）を書き出してみました。

期待される結果

 * 今のTSTのスタイル指定で言う、普通のカラーセットが使われる条件
   * Developer Edition以外で、devtools.theme=lightである
   * Developer Edition以外で、devtools.theme=darkである
   * Developer Editionで、devtools.theme=lightである
 * 今のTSTのスタイル指定で言う、darkテーマ用のカラーセットが使われる条件
   * Developer Editionで、devtools.theme=darkである

それに対して、実際の結果はこうですね。

 * 今のTSTのスタイル指定で言う、普通のカラーセットが使われる条件
   * Developer Edition以外で、devtools.theme=lightである
   * Developer Editionで、devtools.theme=lightである
 * 今のTSTのスタイル指定で言う、darkテーマ用のカラーセットが使われる条件
   * Developer Edition以外で、devtools.theme=darkである←現状ではこれがおかしい
   * Developer Editionで、devtools.theme=darkである

「Developer Edition以外で、Mixed/Plain/Sidebar/Metalで、devtools.theme=darkである」という条件の時、「文字の色が背景と近くて見えにくい」という問題は起こっていませんが、そもそも周りのカラーセットと合っていないという点ではやはりこれも問題だというのが自分の考えです。

という話を踏まえると、上記の「期待される結果」に基づいて考えると単純に、Developer Editionかどうかの判別結果を属性値として保存する修正を入れた上で

~~~
:root[devtoolstheme="dark"][treestyletab-devedition="true"]
~~~

とするのが一番いい（TSTで選択されたテーマごとにどうこうする必要は無い）と思えるんですが、どうでしょうか？

**Comment by lv7777** [comment]
Vertigo/Defaultはdevtools.themeの値を透過させます。
それ以外の場合はfxのデフォルトのテーマ(e.g. deveditionならdarkテーマ用のカラーセット)を透過させます。

`:root[devtoolstheme="dark"][treestyletab-devedition="true"]`
これだとdeveditionではない時(通常のカラーテーマの場合)はすべて白になってしまいます。
Vertigo/Defaultはdevtools.themeの値を透過させますので通常リリース&& devtools.theme==darkの場合でも白になってしまいます。この場合周りは黒でタブのみ白という状態です。

(検証してないので正確ではありません。

**Comment by piroor** [comment]
堂々巡りのようなやり取りを何度もすみません。ここまでのコメントで自分は、両者の認識のずれから来る混乱を避けるために、敢えて全パターンを列挙する書き方を敢えてしています。大沼さんの認識とこちらの認識のずれを明らかにするために、次からは面倒でも大沼さんの方で認識されている全パターンも列挙して書いていただけると幸いです……

**Comment by piroor** [comment]
補足です。
この問題について想定外のRegressionの発生を避けるためには、期待される結果を正確に書き出して、それに基づいて最適なやり方を取るようにゼロベースで考える、場合によっては現在の実装を捨てることも厭わないという考え方が必要だと思っています。
自分が全パターンの列挙に拘っているのはそれが理由なのでした。

**Comment by lv7777** [comment]
了解です。自分は

期待される結果

    今のTSTのスタイル指定で言う、普通のカラーセット(白)が使われる条件
        Developer Edition以外(通常)で、devtools.theme=lightである
        Developer Edition以外で、devtools.theme=darkである && Mixed/Plain/Sidebar/Metalである
        Developer Editionで、devtools.theme=lightである && Vertigo/Defaultである 
    今のTSTのスタイル指定で言う、darkテーマ用のカラーセットが使われる条件
        Developer Editionで、devtools.theme=darkである
        Developer Editionで、devtools.theme=lightである && Mixed/Plain/Sidebar/Metalである 
        Developer Edition以外(通常)で、devtools.theme=darkである && Vertigo/Defaultである
       

現状でおかしいのは

        Developer Edition以外で、devtools.theme=darkである && Vertigo/Defaultである

だと思っています。

**Comment by piroor** [comment]
すみません、今ようやく気が付きました。

> デフォルトskinやvertigo skinでの予想している動作が
>
> * 開発者ツールで設定した色に合わせる
> 
> なのか
>
> * デフォルトのfirefoxのテーマに合わせる
> 
> のかわからないため正しい動作がわかりません。
> 
> 期待している動作はどちらでしょうか？ @piroor 

これに対する最初の自分の回答

> 言葉が足りてませんでした。以上を踏まえると、全体の色は明るいのに開発者ツールは暗いという場合には、全体の色の方に合わせたいです。

の後に提案した解決策がずれてたんですね。
全体の色に合わせるためにはTSTのカラーセットを切り替えるだけでは駄目で、「DevEditionではない時に、VertigoかDefaultが選択されていて、devtools.theme=darkだったら、タブの背景になる部分に新たに明るいグレーを設定する」ということが必要です。

というのも、いまdevtools.theme=darkの時に暗い色で見えている部分は、TST無しの状態の時には本来であれば見えていない部分なんです。
なので、ここの色がdevtools.theme=darkの時に変わってしまっているというのは自分としては完全に見落とし・想定外だったのでした。

自分の誤解・誤認のせいで無駄なやり取りを何度も発生させてしまってすみませんでした……

**Comment by lv7777** [comment]
ということはpirrorさんは以下の状態が望ましい状態になっているという認識ですか？

devtools.themeの値は関係なくてdeveditionの場合テーマにかかわらずすべて黒ベースである
通常リリースの場合はすべて白ベースである。

**Comment by piroor** [comment]
> devtools.themeの値は関係なくてdeveditionの場合テーマにかかわらずすべて黒ベースである
> 通常リリースの場合はすべて白ベースである。

いえ、自分の期待する状態は https://github.com/piroor/treestyletab/issues/1146#issuecomment-233127444 に書いたパターンです。つまり、DevEditionかつdevtools.theme=darkの時だけTSTもdarkの配色になる、そうでないときはlightの配色にする（この時、VertigoとDefaultでは追加の色指定が必要←これが追加の要件）ということです。

で、

> 「DevEditionではない時に、VertigoかDefaultが選択されていて、devtools.theme=darkだったら、タブの背景になる部分に新たに明るいグレーを設定する」ということが必要です。

じゃあ何色を設定すればいいんだという話なんですが、非DevEditionのFirefox自身のテーマだと

~~~
#appcontent:not(:-moz-lwtheme) {
  background-color: -moz-dialog;
}
~~~

となっているようなので、これに合わせるのがよいのではないかと思っています。

**Comment by piroor** [comment]
やっぱりなんか自分の提案した解決策が間違ってる気がします。
すみません、自分の考えと現状と期待される状態の整理のためにちょっと時間を下さい。

**Comment by lv7777** [comment]
了解です。

**Comment by piroor** [comment]
https://github.com/piroor/treestyletab/issues/1146#issuecomment-233128393 への反応を忘れていました。

> 期待される結果
> 
>     今のTSTのスタイル指定で言う、普通のカラーセット(白)が使われる条件
>         Developer Edition以外(通常)で、devtools.theme=lightである
>         Developer Edition以外で、devtools.theme=darkである && Mixed/Plain/Sidebar/Metalである
>         Developer Editionで、devtools.theme=lightである && Vertigo/Defaultである 
>     今のTSTのスタイル指定で言う、darkテーマ用のカラーセットが使われる条件
>         Developer Editionで、devtools.theme=darkである
>         Developer Editionで、devtools.theme=lightである && Mixed/Plain/Sidebar/Metalである 
>         Developer Edition以外(通常)で、devtools.theme=darkである && Vertigo/Defaultである

こちらは、最後の2行が自分の期待する状態と異なっています。

**Comment by piroor** [comment]
大沼さんの書かれたパターン一覧の書き方を自分の期待値に当てはめると、以下が自分の期待する状態ということになります。

~~~
今のTSTのスタイル指定で言う、普通のカラーセット(白)が使われる条件
    Developer Edition以外で、devtools.theme=lightである
    Developer Edition以外で、devtools.theme=darkである && Vertigo/Defaultである
    Developer Edition以外で、devtools.theme=darkである && Mixed/Plain/Sidebar/Metalである
    Developer Editionで、devtools.theme=lightである && Mixed/Plain/Sidebar/Metalである 
    Developer Editionで、devtools.theme=lightである && Vertigo/Defaultである 
今のTSTのスタイル指定で言う、darkテーマ用のカラーセットが使われる条件
    Developer Editionで、devtools.theme=darkである
~~~

**Comment by piroor** [comment]
以上を踏まえて、自分の考える期待値を満たすためにゼロベースで考えられる最適な方法は、 https://github.com/piroor/treestyletab/issues/1146#issuecomment-233127444 に書いた以下のものだと思います。

> 単純に、Developer Editionかどうかの判別結果を属性値として保存する修正を入れた上で
> 
> ~~~
> :root[devtoolstheme="dark"][treestyletab-devedition="true"]
> ~~~
> 
> とするのが一番いい（TSTで選択されたテーマごとにどうこうする必要は無い）

**Comment by piroor** [comment]
Fixed by #1151
