### ISSUE TITLE
[Feature Request] Hide close-button until hovering on tab

### ISSUE THREAD

**Issue by Mehradzie** [piroor/treestyletab#1147]
Would be nice to hide the _close-button_ to open up some real state for the title of the tab.
Then show the close button when hovering on the tab wish to be closed.

There is an add-on already which removes the close-buttons except the active one and I think even having the close-button on the active tab is the waste of real state.

[tabs closebutton restored](https://addons.mozilla.org/en-US/firefox/addon/tabs-closebutton-restored/)

**Comment by piroor** [comment]
I won't do it by TST itself, because it is not related to "tree". I recommend you to use TST with another addon for the purpose (control visibility of the close button in tabs) or using custom userChrome.css like:

~~~
.tabbrowser-tab:not(:hover) .tab-close-button {
  visibility: collapse !important;
}
~~~

**Comment by chronometric** [comment]
Doesn't Vivaldi do this by default with the tree setup? Whenever I have a hidden X on a tab it turns into trouble (for me, a heavy user)....doesn't appear until hovering longer than expected, or needing to click the X several times. 

The size issue is a valid one, though...if anything, in TST it would be nice to get rid of the ellipsis **...** and view more of the title....for those of us more utilitarian. Just a thought ^^

**Comment by paride** [comment]
@piroor Your solution does hide the button in the standard tab bar, but not in the tab tree sidebar, which is what I believe the OP asked for...

**Comment by paride** [comment]
@piroor Your solution does hide the button in the standard tab bar, but not in the tab tree sidebar, which is what I believe the OP asked for...

**Comment by piroor** [comment]
For TST 2.x, you need to use different CSS style rule: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#only-show-tab-close-button-on-hover-1448

**Comment by paride** [comment]
@piroor Thanks. I added
```
.tab:not(:hover) .closebox {
  display: none;
}
```
to my `userChrome.css`, but it has no effect. Does it work for you?

**Comment by piroor** [comment]
Go to TST's configuration and scroll down, then you'll see a text field with the caption "Extra style rules  for sidebar contents". It is the place you should put the CSS codes into.

**Comment by MurzNN** [comment]
Another code snippet for Tree Style Tab Close button only on active and hovered tabs:
```
.tab:not(:hover):not(.active) .closebox {
  display: none;
}
```

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
