### ISSUE TITLE
style pinned tabs like normal tab tree without close button, may be replace close button with pin icon

### ISSUE THREAD

**Issue by hoang17** [piroor/treestyletab#1148]
Right now pinned tab is style as an icon which is hard to click and see. Can we make it so if a tab or a tree is pinned, the appearance is not changed only the tab is pinned on top and can not be close, the close icon is changed to pin icon will be nice!
Thanks for making awesome addons!

**Comment by piroor** [comment]
Go to `about:config` and set `extensions.treestyletab.pinnedTab.faviconized` to `false`, then you'll get the expected result.

**Comment by hoang17** [comment]
it worked! thanks @piroor for your quick response!
