### ISSUE TITLE
[feature request] link: children Tab: focus

### ISSUE THREAD

**Issue by Golddouble** [piroor/treestyletab#1149]
When I open a new blank tab, this tab becomes the focus. I like this.
But when I click on a link in  website and a new tab opens as a child, this tab does not get the focus. So I would appreciate if there would be an option in the Configuration, so that in this case also the opend tab get the focus.

 * Platform (OS): Windows 7, 32bit
 * Version of Firefox: 47.0.1
 * Version (or revision) of Tree Style Tab: 0.17.2016061501

**Comment by piroor** [comment]
Firefox's options => "General" => "Tabs" => "When I open a link in a new tab, switch to it immediately"

If the box is checked, new tabs from links are opened without focus. Could you confirm the configuration?

**Comment by Golddouble** [comment]
Thank you @piroor. I have missed this option. Now it works for me too.
