### ISSUE TITLE
Tabs opened as "next sibling" appear in the wrong place

### ISSUE THREAD

**Issue by sumyungguy** [piroor/treestyletab#1150]
## Short description
A regression in 0.17.2016071200a095841 nightly: When selecting "Open new blank tab as the next sibling of the current tab", the new tab goes in the wrong place. It is directly below the original tab, even when the tab has children.
## Steps to reproduce

 1. Start Filrefox with clean profile.
 2. Install TST Nightly from 2016-07-12
 3. Set "Open new blank tab as the next sibling of the current tab"
 4. Open some tabs like this:

    ![screenshot_176](https://cloud.githubusercontent.com/assets/5410893/16890794/445ff5a0-4af2-11e6-8f2c-f6dae3344549.png)
 5. Create a new tab from menu, button, or keyboard shortcut.

## Expected result
The new sibling tab should go after the end of the current tab's children.

## Actual result
The sibling tab is placed inside the tree, even though it is not part of the tree:

![screenshot_177](https://cloud.githubusercontent.com/assets/5410893/16890826/957fae1c-4af2-11e6-9864-e2381dee5074.png)

If the tree is collapsed, the sibling tab remains outside:

![screenshot_178](https://cloud.githubusercontent.com/assets/5410893/16890964/f6b2fbfc-4af3-11e6-9ca4-baf4a63c3966.png)

The same thing happens with middle-click on Reload, to duplicate as the next sibling of the source tab, but only if the source tab has a parent. Starting again with the first image, after middle-click on Reload, it's correct:

![screenshot_179](https://cloud.githubusercontent.com/assets/5410893/16890887/473233fa-4af3-11e6-8979-c0acb0fe0171.png)

But duplicating the IBM tab gives the error, that the duplicate sibling appears inside the tree, though it is not part of the tree:

![screenshot_180](https://cloud.githubusercontent.com/assets/5410893/16890913/663224c2-4af3-11e6-8663-eacfb56100de.png)

## Environment

 * Platform (OS): MacOS
 * Version of Firefox: 47.0.1
 * Version (or revision) of Tree Style Tab: 0.17.2016071200a095841

**Comment by piroor** [comment]
Confirmed. This happens when the current tab has no next sibling tab.

**Comment by piroor** [comment]
The commit 81e2c10 fixes this problem for me.

**Comment by sumyungguy** [comment]
Fixed for me in the latest nightly, thanks!
