### ISSUE TITLE
Tree Style with CleanLinks

### ISSUE THREAD

**Issue by Golddouble** [piroor/treestyletab#1152]
## Short description

Does Tree Style Tab not work together with CleanLinks? (https://addons.mozilla.org/de/firefox/addon/clean-links/)
## Steps to reproduce

I deactivate CleanLinks and go to 
**_Edit:_**
https://www.google.de/?gws_rd=ssl#q=bauchschmerzen

I click on a google link **with the middle mouse button** and now the link opens in a child tab. This is what I want to see. Then I activate CleanLinks and now the same google link opens an independent Tab.
## Expected result

The behavior should be the same in both variants.
## Actual result

It is different.
## Environment
- Platform (OS): Windows 7 32 bit
- Version of Firefox: 47.0.1
- Version (or revision) of Tree Style Tab: newest

**Comment by Golddouble** [comment]
Edit:
The link I had inserted before was a mistake. 
The actual corrected link shows what I mean.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
