### ISSUE TITLE
[core] using const instead of var

### ISSUE THREAD

**Issue by lv7777** [piroor/treestyletab#1153]
## description

some time ago,I retrieving "const" in TST repo, and discovered that the repo used a little bit of const.
I want to using `var` instead of `const`.

I suggest unify only using `const`.
this is better than mingled `var` and `const`.

const have many profit compared to var.
in this case, mainly, decrease bug.  

---

先ほど、constでTSTのリポジトリを検索したとき、少数ですがconstが使われていることがわかりました。
前からvarよりconstがいいなあと思っていましたが、
var と constが混在しているなら、constで統一してみてはどうでしょうか？

constの利点はたくさんあります。
主にこの場合の利点としては、バグが少なくなることです。

**Comment by myokoym** [comment]
定数にconstを使うように統一していくのはよいことだと思いました。
今後のメンテナンスがしやすくなりそうだからです。

ただ、constにすることでデグレしてしまう可能性がある（思わぬ箇所で代入していた、など）のであれば、
既存のコードに対しては無理にやらなくてもいいのかなと思います。

まずは、新しく書くコードはconstを使うようにしていく、というのから始めるのがいいのかなと思いました。
既存のコードに対しては、確実にconstにできるところから少しずつやるというのでどうでしょうか。

**Comment by lv7777** [comment]
なるほど。

ただ、ownerの @piroor さんの意見でこういったものがあります。

```
物理で慣性の法則という物がありますが、ソフトウェアの開発や設計の意志決定でも似たような事が言えると自分は思っています。XPCOMコンポーネントに依存した設計で今の所進んできたツリー型タブというアドオンは、その設計の方向で進むという慣性が強く働いていると言えます。

それに対してWebExtensionsは、ベクトルとして別の方向を目指す事になるので、本気でやるならそれまでの慣性を打ち消すだけの大きな力を投入する必要があります。先に述べたような強い慣性が働いている現状で、これらの個別の部分で別方向のベクトルの小さな力を投入し続けても、良くて焼け石に水、悪ければ今はたらいている慣性に対するノイズになってしまうと自分は考えています。それよりは、ブランチを切って全面的にWebExtensionsベースで作り直し始めるなどのような形（例えば、MozLondonのイベントレポートにも書いたハイブリッドアドオンの形もアリだと思います）にした上で、その時に初めてそのベクトルで全力を投入する方がいいのではないでしょうか？ ……というのが自分の考えです。どうでしょうか。

```
#1137 より引用

そのため、一気にやるほうがownerとしては望ましいのかなと思っています。

**Comment by lv7777** [comment]
ただ、今回の場合は #1137 と違い、かなり広範囲に及ぶのでとても一回のコミットで行うのは現実的だとは思いません。

なので自分も
> 既存のコードに対しては、確実にconstにできるところから少しずつやるというのでどうでしょうか。

という意見に賛成です

**Comment by piroor** [comment]
constの利点については同意です。定数でない物をconstと宣言する事には「`if (variable == "literal")` と書くとうっかり`=`を1つ忘れて `if (variable = "literal")` となってしまった時にエラーに気付けないので、 `if ("literal" == variable)` と書く方がよい」という話と似た感じの違和感があるのですが、その例に比べるとconstの使用はそれほど抵抗なく多くの人に受け入れられている概念のように思える（統計的裏付けはありません。自分の観測範囲での主観的イメージです）ので、導入に踏み切ってよいと思います。

懸念されるデメリットとしては以下の点があります。

 1. 変数のスコープの関係で、単純にvarからconstに置き換えると動かなくなるケース例がある。グローバルスコープでの `var EXPORTED_SYMBOLS = ['...'];` などがその代表例で、別のファイルで書かれたスクリプトから参照される必要がある物はconstでは定義できない。
 2. varで宣言された変数の値を再代入していく前提のコードが多々あるので、それらをconst前提のコードに書き換える必要がある。
 3. 各変数がvarやletで定義されている事を前提に書かれた「他のアドオンの中に含まれる、ツリー型タブ用に動的に反映されるパッチ」が動作しなくなる恐れがある。

1、2については、壊さないように慎重に少しずつやる以外にないと思います。

3については、そのような例がどれだけあるか・実際にあるのかどうかも含めて不明です。ただ、ツリー型タブの開発方針として「作者自身がPrime Userで、作者環境で問題にならない変更なら基本的に入れてしまう」というポリシーはあるので、ここはそれほど重大に捉えなくてもよいだろうと思っています。

以下は余談です。

> constの利点はたくさんあります。
> 主にこの場合の利点としては、バグが少なくなることです。

この点について参考文献（例えば今パッと検索すると https://sbfl.net/blog/2016/07/14/javascript-var-let-const/ が見つかりました）が提示されていると、より説得力が増すのではないかと思いました。

また、自分がいくつか挙げたようにデメリットも無くはないので、何かの提案の際にはメリットとデメリットの両方を挙げられるようにしておくとよいと思います。
良い事ずくめに見える新しい物の導入には大抵デメリットもセットで存在していて、見落としているか無意識に無視・軽視している事が多いという経験則が自分はあります。
実例として、別のThudnerbirdアドオンでは、先行実装となるFirefox独自拡張の新しいJSの記法を積極的に取り入れてみたけど、最終的なES2016等の仕様には取り入れられなくて、結局はFirefoxからも廃止されてしまいました、その記法をガンガンに使って実装した箇所は丸ごと書き直しになってしまいました、みたいな事がありました。
なので、そういう悲しい結末を回避してなるべく長く動くコードにするためにも、何か新しい提案をするときは自分の普段の視点以外からも敢えて意地悪な見方を色々してみるとよいのではないかと思います。
（そういう慎重な言い方をした提案よりも、メリットしか見えないイケイケドンドンな提案の方が人に受け入れられてもらいやすいのだ、という考え方もあるとは思いますが、先のThunderbirdアドオンのような例もあるので、自分は慎重なスタイルの方が好みです。）

**Comment by piroor** [comment]
> そのため、一気にやるほうがownerとしては望ましいのかなと思っています。

それはちょっと僕の意図を誤解されていると思いました。
別の言葉で言い直すと、「プロジェクトの進む方向性が北を向いているのに、いきなり南向きのコミットが1つだけ入ってきても、その流れはその後の大量の北向きのコミットでかき消されてしまうので、プロジェクトの進路が南に向いて、南向きのコミットがどんどん入り始めるような時になってから、その一環としてやる方がよいのでは」……という感じでしょうか。うまく言えてなかったらすみません。

var/letからconstへの置き換えは、この例えで言うと「真北に進んでいる時に北北西のコミットを加える」くらいの感じかなあと思っています。なので、前の議論ほどの違和感は無いです。

**Comment by lv7777** [comment]
>　また、自分がいくつか挙げたようにデメリットも無くはないので、何かの提案の際にはメリットとデメリットの両方を挙げられるようにしておくとよいと思います。

わかりました。今後issueを立てるときに参考にします。

> 実例として、別のThudnerbirdアドオンでは、先行実装となるFirefox独自拡張の新しいJSの記法を積極的に取り入れてみたけど、最終的なES2016等の仕様には取り入れられなくて、結局はFirefoxからも廃止されてしまいました、その記法をガンガンに使って実装した箇所は丸ごと書き直しになってしまいました、みたいな事がありました。

言語レベルで仕様が変更になるとどうしようもないので辛いですよね・・・

> var/letからconstへの置き換えは、この例えで言うと「真北に進んでいる時に北北西のコミットを加える」くらいの感じかなあと思っています。なので、前の議論ほどの違和感は無いです。

了解です。では進めていきたいと思います。

最初はeslintのno-varルールでエラーを出して、修正してから手動でテストをしようかなと思っています。
http://eslint.org/docs/rules/no-var

**Comment by piroor** [comment]
> 最初はeslintのno-varルールでエラーを出して、修正してから手動でテストをしようかなと思っています。

一気に置換してしまってから、動かしてみて駄目なところを戻していくということでしょうか？
だとすると、通りにくいコードパスの部分で見落としが起こりそうで怖いです……

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
