### ISSUE TITLE
[Suggestion] Allow cancel in the dialog related to opening a bookmark folder as tabs

### ISSUE THREAD

**Issue by f6fvy** [piroor/treestyletab#1155]
When middle-clicking (or "Open as tabs") on a folder of bookmarks, a dialog pops up to choose between opening them as separate tabs or as a tree.

The closing icon of the dialog currently acts as one of these options, while it would be (IMHO) much useful to let it act as a "Cancel" action. Or maybe you could add an additional "Cancel" button to the dialog ?

Thanks !

**Comment by piroor** [comment]
How the choice "Cancel" should work? Does it simply ignore the action and no tab will be opened?

**Comment by f6fvy** [comment]
Absolutely. And the ESC key should do the same.

**Comment by piroor** [comment]
By recent commits I've introduced this behavior. Thanks to the suggestion!

But there is one problem: the "cancel" button has to be placed as the second button, not the third button. This limitation is due to the bug of Firefox itself: https://bugzilla.mozilla.org/show_bug.cgi?id=345067

**Comment by f6fvy** [comment]
Very good ! Thanks !

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
