### ISSUE TITLE
focus after a tab is closed

### ISSUE THREAD

**Issue by Golddouble** [piroor/treestyletab#1156]
## Short description

I would appreciate if we can add settings which allows the user to set the behavior of the focus when he closes a tab.
## Steps to reproduce
1. I have 5 Tabs open
2. I click on the second, so that the second gets the focus
3. I click on the fifth, so that the fifth gets the focus
4. I click on the second, so that the second gets the focus
5. I click on the second tab with the middle mouse button, so that the second tab closes
## desired result

I would like that tab 5 now gets the focus, because this was the tab I have touched before I closed the second tab. 
## Actual result

The originally third tab becomes the focus.
## Environment
- Platform (OS): Windows 7, 32bit
- Version of Firefox: 47.0.1
- Version (or revision) of Tree Style Tab: Ver.0.17.2016061501

**Comment by Orin321** [comment]
Hmm... This seems to be the exact way how my current setup works. Thoutgh, I'd like on the contrary to have a way to configure the behavior you was seeing - ie when I have several tabs/subtabs, and I close one of them, I'd like to focus the next tab in the tree...
Is there any way I overlooked how to make this? 

Debian stretch
FF 59.0.2 (64 bits)
TreeStleTabs 2.4.18

**Comment by piroor** [comment]
Some extensions provide the behavior you described. For example, [Tab Deque](https://addons.mozilla.org/firefox/addon/tab-deque/) looks working with TST as expected for me.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
