### ISSUE TITLE
moving Tabs

### ISSUE THREAD

**Issue by Golddouble** [piroor/treestyletab#1157]
## Short description

Sometimes moving tabs does not functin proper.
## Steps to reproduce

Look at this animation:
http://www.bilder-upload.eu/show.php?file=7b5e19-1469865798.gif
## Environment
- Platform (OS): Windows 7 32bit
- Version of Firefox: 47.0.1
- Version (or revision) of Tree Style Tab: 0.17.2016061501

**Comment by piroor** [comment]
I've released a new version 0.17.2016083001 (not reviewed yet but you can try it from "all versions" page on AMO website). It includes a change about this problem: now the droppable area of a tab is enlarged. Could you try it?

**Comment by Golddouble** [comment]
Thank you. I was not able to install this version, because it is not signed. Would be great if you could sign it.

**Comment by piroor** [comment]
We have to wait it is reviewed and signed by AMO editors. I don't know when it is signed, sorry...

**Comment by Golddouble** [comment]
It's always the same with Version 0.18.2016090802:
http://www.bilder-upload.eu/show.php?file=0da1da-1473410653.gif

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
