### ISSUE TITLE
Slow restart to unresponsive when a lot of tabs.

### ISSUE THREAD

**Issue by karlcow** [piroor/treestyletab#1159]
## Short description
Restarting the browser is slow and leads to dialogs for unresponsiveness script

## Steps to reproduce

 1. Start Firefox with 300+ tabs with TST already installed
    
    Using Firefox 49.0a2 (2016-08-01) with ~300 tabs.
    Each time I have to restart the browser (clean start or after a crash), the browser seems to be freezing and then a message appears with one of those. 
    
    ![capture d ecran 2016-08-04 a 09 54 24](https://cloud.githubusercontent.com/assets/505230/17386990/8a39f656-5a2a-11e6-962e-8b4477a2dbbe.png)
    ![capture d ecran 2016-08-04 a 09 56 14](https://cloud.githubusercontent.com/assets/505230/17386989/8a399292-5a2a-11e6-9288-9b10c9d5271e.png)
    ![capture d ecran 2016-08-04 a 10 01 07](https://cloud.githubusercontent.com/assets/505230/17386991/8a3cb6de-5a2a-11e6-99ce-27373d40ace9.png)
    
    It happens every time.

2. Eventually click on Continue and wait a bit, the tabs will appear. 
    

After this he usage is normal

## Expected result

To have TST restarting right away.

## Actual result

Waiting for a bit. (~10 to 20s)

## Environment

 * Platform (OS): Mac OSX 10.11.6 (15G31)
 * Version of Firefox: 49.0a2 (2016-08-01)
 * Version (or revision) of Tree Style Tab: Last updated 18 june 2016 / 0.17.2016061501

**Comment by piroor** [comment]
It seems hard for me to prepare such 300 or more tabs just for testing. And, the structure of dirty tree can make Firefox slow. (In other words, I possibly cannot reproduce the problem with my clean tree created for testing.) Could you share a session file saved by the Session Manager addon?

**Comment by karlcow** [comment]
@piroor  I will close this one as invalid. Sorry about that.

I did a couple of additional tests yesterday after this report and using Tab Center in the test pilot without TreeStyleTab and the same number of tabs. And I was able to reproduce it. 

So there is definitely an issue but it's the number of tabs and Firefox.

Thanks for jumping in so quickly.
