### ISSUE TITLE
tabs wrong place

### ISSUE THREAD

**Issue by Tragen** [piroor/treestyletab#1160]
I have a tab and I open new child tabs with middle click on a link. Since FF48 and/or last TST update, I very often get the tabs at the end of the list instead of a children to the current tab.

**Comment by Tragen** [comment]
Looks like the error comes from the extension "Clean Links" when you have "Event Delegation Mode" setting turned on. It's the default mode.

**Comment by piroor** [comment]
I've tried Clean Linsk 2.7.1-signed.1-signed on Nightly 51.0a1, with TST development build. They seem work correctly with the active "Event Delegation Mode" feature for me. Any other condition to reproduce the problem? You'll see a template of good issue reports from https://raw.githubusercontent.com/piroor/treestyletab/master/ISSUE_TEMPLATE.md and there is also a guideline to post more helpful information: https://github.com/piroor/treestyletab/blob/master/CONTRIBUTING.md

**Comment by Tragen** [comment]
I will do it the next time, sorry.
I did some more tests. I happens with this parameter enabled but is hard to reproduce.
It only happens when you have hundreds of open tabs and FF is slow.

## Environment

 * Platform (OS): Microsoft Windows [Version 10.0.10586] x64
 * Version of Firefox: 48 x64
 * Version (or revision) of Tree Style Tab:  0.17.2016061501
 * Version (or revision) of Clean Links:  2.7.1-signed.1-signed

**Comment by Golddouble** [comment]
Please compare with the issue https://github.com/piroor/treestyletab/issues/1152
-> The behaviour is with google links.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
