### ISSUE TITLE
Sign Development Version

### ISSUE THREAD

**Issue by findow** [piroor/treestyletab#1161]
Mozilla just released Firefox 48 and it does not allow to install extensions that are not signed, but I like to test the Development Version of TST downloadable from your site: would it be possible for you to sign the nigthly version of your addon?
Ublock Origin author does release a signed version of his development addon at each release, could you please do the same?
And also, could you please release an updated version on Mozilla Addon site since there there is an older version than the nigthly one?
Thanks. Regards.

**Comment by piroor** [comment]
By a limitation of signing system, we cannot provide signed development build of TST. Instead, you can use a unbranded Firefox to try unsigned addon packages. See: https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds

**Comment by findow** [comment]
Ok, I understand.
Could you please upload an updated version on Mozilla site?
I will move to the signed version from now on, but I'd like this latest nightly version to be signed considering that it is the one I'm using.
Thanks.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
