### ISSUE TITLE
Many CSS warnings consoled

### ISSUE THREAD

**Issue by asamuzaK** [piroor/treestyletab#1162]
## Short description
There are many CSS warnings consoled related to Tree Style Tab.

## Steps to reproduce

 1. Start Filrefox with clean profile.
 2. Install TST.
 3. Restart Firefox
 4. Open browser console `Ctrl + Shift + J`

## Expected result
No warnings (or a few).

## Actual result
Many warnings.

## Environment

 * Platform (OS): Win 10 
 * Version of Firefox: Development Edition
 * Version (or revision) of Tree Style Tab: Latest nightly

## Log
> 不明なプロパティ ‘box-flex’ が使用されています。  このスタイル宣言は無視されました。treestyletab.css:63:9
> 不明なプロパティ ‘appearance’ が使用されています。  このスタイル宣言は無視されました。treestyletab.css:174:11
> 不明なプロパティ ‘box-flex’ が使用されています。  このスタイル宣言は無視されました。treestyletab.css:205:9
> 不明なプロパティ ‘box-pack’ が使用されています。  このスタイル宣言は無視されました。treestyletab.css:207:9
> 不明なプロパティ ‘box-flex’ が使用されています。  このスタイル宣言は無視されました。treestyletab.css:221:9
> 不明なプロパティ ‘box-align’ が使用されています。  このスタイル宣言は無視されました。treestyletab.css:232:10
> 不明なプロパティ ‘appearance’ が使用されています。  このスタイル宣言は無視されました。treestyletab.css:424:11
> 不明なプロパティ ‘box-flex’ が使用されています。  このスタイル宣言は無視されました。treestyletab-tmp.css:24:9
> 不明なプロパティ ‘appearance’ が使用されています。  このスタイル宣言は無視されました。base.css:45:11
> 不明なプロパティ ‘-moz-border-radius’ が使用されています。  このスタイル宣言は無視されました。base.css:53:19
> 不明なプロパティ ‘box-flex’ が使用されています。  このスタイル宣言は無視されました。base.css:79:9
> 不明なプロパティ ‘-moz-border-radius’ が使用されています。  このスタイル宣言は無視されました。base.css:114:19
> 不明なプロパティ ‘box-pack’ が使用されています。  このスタイル宣言は無視されました。twisty.css:15:9
> 不明なプロパティ ‘box-align’ が使用されています。  このスタイル宣言は無視されました。twisty.css:17:10
> 不明なプロパティ ‘box-flex’ が使用されています。  このスタイル宣言は無視されました。twisty.css:19:9
> 不明なプロパティ ‘appearance’ が使用されています。  このスタイル宣言は無視されました。tmp.css:41:11
> 不明なプロパティ ‘box-flex’ が使用されています。  このスタイル宣言は無視されました。tmp.css:69:9
> 不明なプロパティ ‘box-align’ が使用されています。  このスタイル宣言は無視されました。tmp.css:71:10
> 不明なプロパティ ‘box-pack’ が使用されています。  このスタイル宣言は無視されました。tmp.css:73:9
> 不明なプロパティ ‘box-orient’ が使用されています。  このスタイル宣言は無視されました。tmp.css:75:11
> 不明なプロパティ ‘box-align’ が使用されています。  このスタイル宣言は無視されました。ui-base.css:6:10
> 不明なプロパティ ‘box-pack’ が使用されています。  このスタイル宣言は無視されました。ui-base.css:8:9
> 不明なプロパティ ‘appearance’ が使用されています。  このスタイル宣言は無視されました。ui-base.css:168:11
> 不明なプロパティ ‘appearance’ が使用されています。  このスタイル宣言は無視されました。ui-base.css:309:11
> 不明なプロパティ ‘padding-start’ が使用されています。  このスタイル宣言は無視されました。ui-base.css:323:14
> 不明なプロパティ ‘box-align’ が使用されています。  このスタイル宣言は無視されました。ui-base.css:347:10
> 不明なプロパティ ‘box-pack’ が使用されています。  このスタイル宣言は無視されました。ui-base.css:349:9
> 不明なプロパティ ‘box-align’ が使用されています。  このスタイル宣言は無視されました。ui-base.css:356:10
> 不明なプロパティ ‘box-pack’ が使用されています。  このスタイル宣言は無視されました。ui-base.css:358:9
> 不明なプロパティ ‘-moz-box-shadow’ が使用されています。  このスタイル宣言は無視されました。ui-base.css:406:16
> 不明なプロパティ ‘user-focus’ が使用されています。  このスタイル宣言は無視されました。ui-base.css:418:11
> 不明なプロパティ ‘outline-radius’ が使用されています。  このスタイル宣言は無視されました。ui-base.css:439:15

**Comment by piroor** [comment]
There are two problems: about unprefixed properties and "-moz-" prefixed properties.

1) unprefixed properties

Basically I believe that we should use prefixed version property with unprefixed version for future compatibility. So I think some unimplemented unprefixed properties like "padding-start" should be left there. However, there is an exception: if the property is guaranteed that it is never unprefixed. Some "-moz-" prefixed properties are based on old CSS3 working drafts, so I think those properties won't be unprefixed.

But currently I have very few time to research that. I need pull requests to remove CSS declarations for such prefixed versions.

2) "-moz-" prefixed properties

After unprefixed version is activated on Gecko, we can remove declarations for old prefixed version. But I think TST should work with latest Firefox ESR (45.x), so only unprefixed properties obsolete on Firefox 45 and later can be removed. I also need pull requests to do it.

**Comment by asamuzaK** [comment]
PR for the start [remove deprecated -moz-* properties by asamuzaK · Pull Request #1163 · piroor/treestyletab](https://github.com/piroor/treestyletab/pull/1163)

**Comment by asamuzaK** [comment]
以下、英語でやりとりするのめんどくさいんで日本語でいいですか？w

box-*:
flexboxの新仕様に置き換えるべきかと

appearance:
none / auto 以外は除かれています [CSS Basic User Interface Module Level 4](https://drafts.csswg.org/css-ui-4/#appearance-switching)
-moz-appearanceは残してappearanceは削除するのはどうでしょう？

padding-start:
padding-inline-start
padding-block-start
がそれぞれ提案されています [CSS Logical Properties Level 1](https://drafts.csswg.org/css-logical-props/#propdef-padding-inline-start)
-moz-padding-startは残してpadding-startは削除？

user-focus:
CSS3からは削除されています [-moz-user-focus - CSS | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/-moz-user-focus)
-moz-user-focusは残してuser-focusは削除？

outline-radius:
どの仕様にもありません [-moz-outline-radius - CSS | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/-moz-outline-radius)
-moz-outline-radiusは残してoutline-radiusは削除？

**Comment by piroor** [comment]
早速のPRありがとうございます！
また、各仕様の現状を調査していただいてありがとうございます。この部分の心理的ストレスが大きくて自分では調査できていなかったので、非常に助かります。

> flexboxの新仕様に置き換えるべきかと

-moz-box-flexや-moz-box-ordinalはXULのflex属性やordinalと対応している事を過去にDOMまわりのソースを調査して確証を得ていますが、flexboxの似た機能がXULの上でどう影響を及ぼすのか・XULの属性と併用された時にどうなるのかについて自信を持ってこうと言える材料がないので、この点は慎重に進めないといけないと思っています。

> appearance:

これは、XULが削除されるよりも前に「CSS4のappearanceを実装するが、独自拡張としてauto以外の値も受け付ける」「よって-moz-appearanceは削除する」という事になるリスクがどれくらいあるかどうかによると思います。
自分は、「可能性はゼロではない以上は残しておきたい」「デメリットはwarningが出る事程度で、エラーになるわけではないから」と考える立場なので、上記のリスクが十分に低いという確証が得られるまでは心情として同意しにくいのが正直な所です。

それ以外の物は、この名前でunprefixedになる可能性は十分に低そうなので、prefixedの方は削除で良いと思います。

**Comment by asamuzaK** [comment]
> それ以外の物は、この名前でunprefixedになる可能性は十分に低そうなので、prefixedの方は削除で良いと思います。

「unprefixedの方は削除」でいいですか？

**Comment by asamuzaK** [comment]
2nd patch [Remove unprefixed CSS properties which are not in any spec by asamuzaK · Pull Request #1164 · piroor/treestyletab](https://github.com/piroor/treestyletab/pull/1164)

**Comment by asamuzaK** [comment]
box-*について
標準化される可能性はないので、こちらも-moz-box-*だけ残しておくのはどうでしょうか？

**Comment by asamuzaK** [comment]
そしてappearanceについて
まだ仕様としても固まっておらず、仮に今のeditors draftの方向性で固まるとしても、noneには併せてall:unsetが必要とか、いずれにせよ修正の必要がありそうなのでunprefixedの併記が将来的な互換性の担保となる可能性は低そうです
prefixedとunprefixedを併記することに私も基本的には賛成ですが、appearanceに関してはかつてのgradientsやflexboxのような迷走がありますので、prefixedのみとしておいた方がメンテナンス性が多少高まる気もしています（現にツリー型タブでも古い-moz-*-gradientsがいくつか残っているのを今回確認しましたが、それによる互換性の問題は起きていないようですし）

もっともこのあたりは私見まじりの提案なので、判断はお任せします

**Comment by piroor** [comment]
> 「unprefixedの方は削除」でいいですか？

はい。すみません誤記でした。

> box-*について
> 標準化される可能性はないので、こちらも-moz-box-*だけ残しておくのはどうでしょうか？

了解です。きちんとは見ていませんが、CSS flexboxとの仕様の違いが大きいのであれば実装も共有されないのだろうという推測に基づいて、unprefixed版は削除で良いと思います。

appearanceについても了解です。こちらもunprefixed版は削除で良いと思います。
この辺は自分よりも最新の仕様の動向に詳しい方の肌感覚の方が信頼に足ると思っています。

色々調べていただいて＆説明を頂いて本当にありがとうございます！

**Comment by asamuzaK** [comment]
了解しました
追ってbox-\*系とappearanceの2つにわけてPRを投げます

あと念のため付記
[-moz-outline-radius が削除されます | Firefox サイト互換性情報](https://www.fxsitecompat.com/ja/docs/2015/moz-outline-radius-will-be-removed/)
現時点ではいつ削除されるかは決まっていませんが、将来的には削除されるようです

**Comment by asamuzaK** [comment]
3rd patch for appearance and box-\* [Remove unprefixed appearance and unprefixed box-\* by asamuzaK · Pull Request #1165 · piroor/treestyletab](https://github.com/piroor/treestyletab/pull/1165)

同じファイルに混在しているケースが多かったので、2つではなく1つのPRにまとめました

**Comment by piroor** [comment]
ありがとうございます！マージしました。
-moz-outline-radiusも、その時が来たら削除ということで了解です。

**Comment by asamuzaK** [comment]
Follow up [Pick up where the modification has not been applied by asamuzaK · Pull Request #1166 · piroor/treestyletab](https://github.com/piroor/treestyletab/pull/1166)

**Comment by asamuzaK** [comment]
I want to check with the latest nightly, but maybe is nightly not working anymore? [Index of /xul/xpi/nightly](https://piro.sakura.ne.jp/xul/xpi/nightly/)

**Comment by piroor** [comment]
Sorry, it is my fault. Webhook was unexpectedly stopped. Now latest development build based on the master is available again.

**Comment by asamuzaK** [comment]
Thanks.
Confirmed that there is no warning anymore.
