### ISSUE TITLE
Display problems with horizontal tabbar

### ISSUE THREAD

**Issue by numberZero** [piroor/treestyletab#1167]
## Short description
When I set tab panel position to top, its appearance become unaffected by the tab panel style option (tree node style is still regarded). When I try to move it to the bottom, the tab panel disappears completely.

## Steps to reproduce

 1. Install TST on IceCat.
 2. Change the tab panel position to top or bottom.

## Expected result
Properly styled tabs at the top or the bottom, according to the setting.

## Actual result
Default-styled Firefox tabs at the top, or no tab panel at all.

## Environment

 * Platform (OS): Parabola x86_64 (based on Arch Linux)
 * Version of Firefox: [IceCat](https://www.gnu.org/software/gnuzilla/) 38.8.0-gnu2 (latest available)
 * Version (or revision) of Tree Style Tab: 0.17.2016061501

**Comment by piroor** [comment]
It is a designed behavior. TST don't include rich style definitions for top and bottom tab bar because it is mainly designed to work with vertical tab bar. I don't use horizontal tab bar with TST, so I have no plan to add/maintain style rules for horizontal tab bar. Sorry.

**Comment by numberZero** [comment]
Then it should disable style selection when horizontal tab bar is chosen. It does that already for one checkbox (“Инвертировать вид вкладок” in Russian, haven’t managed to make it display english UI), so the inconsistency is a bit confusing.
