### ISSUE TITLE
Unsafe/forbidden cpow usage warnings when viewing images

### ISSUE THREAD

**Issue by quilloss** [piroor/treestyletab#1169]
## Short description
Tree style tab produce ```unsafe/forbidden CPOW usage``` warnings when opening an image/video via right click -> view image.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Restart Firefox.
 4. Right click an image -> View Image.
 5. Open Browser Console.

## Expected result
No  ```unsafe/forbidden CPOW usage``` warnings.

## Actual result
![tst_error](https://cloud.githubusercontent.com/assets/8151080/17467253/dc653018-5d4e-11e6-8db5-67d4e2c9bbec.png)
Tree style tab still works properly. However it is has the largest performance impact according to about:performance.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 50.0a2
 * Version (or revision) of Tree Style Tab: 0.17.2016061501 (release) and 0.17.2016080700a235116 (nightly)

**Comment by piroor** [comment]
Thanks. This has been fixed by 9b5570006cf0e2f55502a4dcd71375d9d39632c2.
