### ISSUE TITLE
Tab coloring for contextual identities (new Nightly feature)

### ISSUE THREAD

**Issue by Happy-Dude** [piroor/treestyletab#1171]
## Short description
Mozilla pushed out a new feature in their Nightly builds called "contextual identities":
> The Containers Feature in Firefox Nightly enables users to login to multiple accounts on the same site simultaneously and gives users the ability to segregate site data for improved privacy and security.

Read more about it here: https://blog.mozilla.org/tanvi/2016/06/16/contextual-identities-on-the-web/

These containerized tabs are colored differently, with blue for personal, orange for work, green for banking, and pink for shopping. When using TreeStyleTabs with Nightly, I can open a new container and see an indication that the tab is containerized in the AwesomeBar, but with no indication in the actual tab.

Can TreeStyleTabs be updated to add these tab-indicator colors for easier distinction?

## Steps to reproduce

 1. Start Nightly with clean profile.
 2. Install TST.
 3. Open a new container tab via File -> New Container Tab

## Expected result
A new container tab will be opened with an indication of what container it is in the AwesomeBar and on top of the tab.

## Actual result
There is an indicator in the AwesomeBar, but no indicator in the tab.

## Environment
 * Platform (OS):  Mac OS X, User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:51.0) Gecko/20100101 Firefox/51.0 (but affects all versions)
 * Version of Firefox: Firefox Nightly 51.0a1, build ID 20160811030201
 * Version (or revision) of Tree Style Tab: 0.17.2016080700a235116

**Comment by piroor** [comment]
Contextual tab's color is updated by `ContextualIdentityService.setTabStyle()`
https://dxr.mozilla.org/mozilla-central/rev/01748a2b1a463f24efd9cd8abad9ccfd76b037b8/toolkit/components/contextualidentity/ContextualIdentityService.jsm#269

**Comment by piroor** [comment]
The commit a50337a should implement this. It seems work for me on Windows 7.

**Comment by Happy-Dude** [comment]
Thanks @piroor !
I tested it on Mac OS X with the 20160825030226 build, and I noticed a few bugs. 

When I right click and open a link in a contextual tab, the indicator shows up, disappears, then stays. Also I open a new contextual tab from the File menu, I see the indicator then it disappears. Only when I load a page does it stay.

Might there be some weird logic between the new tab creation, the page-load-spin-wheel animation, and the contextual indicator?

I've attached some short GIFs demonstrating what I am seeing:

TST disabled:
![tst-disabled](https://cloud.githubusercontent.com/assets/1098725/17971445/8061e716-6aa0-11e6-8644-ca707a5c5dc3.gif)

TST enabled:
![tst-enabled](https://cloud.githubusercontent.com/assets/1098725/17971450/84f30a30-6aa0-11e6-8409-d15242e26c64.gif)

**Comment by piroor** [comment]
I think the commit 1f8e42b432f1cbc8f8004ba7c6538f72a7311c6c should fix the odd behavior.

**Comment by andrebeat** [comment]
Using the "sidebar" skin doesn't seem to set the correct style for the selected tab when it uses a context.

![selected normal](https://dl.dropboxusercontent.com/u/7018537/tst-selected1.png)

![selected context](https://dl.dropboxusercontent.com/u/7018537/tst-selected2.png)

I'm on OSX and using the latest Firefox Developer Edition (50a2).

**Comment by Happy-Dude** [comment]
I also have another slight request: can the color indicator be a bit thicker by a few pixels?
(Just a personal preference, no change is necessary if you don't think so.)

**Comment by piroor** [comment]
I've done some changes around the problem. How about the latest development build?

**Comment by andrebeat** [comment]
Using 35ac452 solved the issue I reported.

**Comment by Happy-Dude** [comment]
Everything looks great from my side as well; thanks so much for the new feature :)

**Comment by piroor** [comment]
I've released a new version 0.17.2016083001 includes commits for this issue, thus I close this.
