### ISSUE TITLE
Button to Add New Tab is Invisible

### ISSUE THREAD

**Issue by misson20000** [piroor/treestyletab#1175]
## Steps to reproduce

I'm not sure. This issue does not happen on a fresh profile and happens every now and then on my regular browsing profile. Usually a restart of the browser fixes it, but not this time. Having never tried to develop or debug a Firefox addon, I have no idea what measures I could take to identify the problem. If there's anything I should do to get more information, go ahead and ask.
## Expected result

Tab bar looks like this:
![selection_059](https://cloud.githubusercontent.com/assets/616626/17638333/3977bb5c-609e-11e6-9989-2cdf05091557.png)
## Actual result

Tab bar looks like this:
![selection_060](https://cloud.githubusercontent.com/assets/616626/17638343/48182eda-609e-11e6-8b0d-2523cead4b21.png)
(ignore the width differences)
## Environment
- Platform (OS): Arch Linux
- Version of Firefox: 48.0, also happens on Firefox Nightly 51.0a1 (2016-08-12)
- Version (or revision) of Tree Style Tab: 0.17.2016061501

**Comment by misson20000** [comment]
Actually, this might be a problem with Firefox itself. The new tab button does not show up when I disable TST.

**Comment by misson20000** [comment]
Fixed by disabling TST, opening the customize view, putting the add new tab button back where it belongs, and re-enabling TST. It's strange that this happened, though, because I never moved the add new tab button.

**Comment by piroor** [comment]
You mean: TST unexpectedly moves the "new tab" button from the tab bar to the customization palette?

**Comment by piroor** [comment]
TST does something around tab bar's initialization process, so it can conflict with other addons which have its own toolbar button, if it includes any code to insert its button to the tab bar. Any other addon like that?

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
