### ISSUE TITLE
Bug: When using GTK2 builds of Firefox, scrolling using the mouse wheel on the tab panel switches through the tabs, rather than scrolling the panel.

### ISSUE THREAD

**Issue by ethus3h** [piroor/treestyletab#1176]
Note: Similar to #1094.
## Short description
When using GTK2 builds of Firefox, scrolling using the mouse wheel on the tab panel switches through the tabs, rather than scrolling the panel.
## Steps to reproduce

 1. Start Firefox 45.3.0 ESR, 64-bit GNU/Linux official binary, with clean profile.
 2. Install TST.
 3. Scroll tab panel using mouse wheel.
( 4. …profit?)

## Expected result
Tab panel scrolls.

## Actual result
A glitchy combination of scrolling the tab panel and switching between the various open tabs. (Scrolling slowly seems to make it more likely to scroll the panel, while scrolling quickly or past the end of the available selection of tabs seems to make it more likely to change which tab is selected.)

## Environment

 * Platform (OS): Gentoo GNU/Linux (Linux elegiac 4.1.15-gentoo-r1-Wreathe-7.3-2016Aug09 #1 SMP Tue Aug 9 13:05:52 EDT 2016 x86_64 Intel(R) Core(TM)2 Duo CPU P7550 @ 2.26GHz GenuineIntel GNU/Linux)
 * Version of Firefox: 45.3.0 ESR
 * Version (or revision) of Tree Style Tab: 0.17.2016061501

**Comment by piroor** [comment]
The behavior is defined as a build option specific behavior of Firefox itself.
https://dxr.mozilla.org/mozilla-central/rev/7963ebdd52b93f96b812eff2eab8d94097147b9c/toolkit/content/widgets/tabbox.xml#577
TST cannot cancel and override the behavior in legal way...

**Comment by ethus3h** [comment]
Aah, I'll patch that in my build then. Thanks! :)
