### ISSUE TITLE
Merging the address bar with the title bar

### ISSUE THREAD

**Issue by mathearts** [piroor/treestyletab#1177]
## Short description

Is it possible to merge the address bar with minimize-maximize-close buttons so that a little bit of vertical space is freed? Basicly the same thing that Firefox does automatically in the fullscreen mode. 

I'll gladly welcome just an userChrome.css fix, I don't request a setting in the UI. Thank you very much!

![screenshot 14](https://cloud.githubusercontent.com/assets/20880213/17649153/8e8f6ece-622d-11e6-96af-f801ca443335.png)
- Platform (OS): Windows
- Version of Firefox: 50 DevEd 
- Version (or revision) of Tree Style Tab: latest as of today

**Comment by ethus3h** [comment]
Yeah, I think so, but what does this have to do with TST?

**Comment by mathearts** [comment]
When vertical tabs are enabled, they shift from the title bar to the side, leaving an empty title bar with only the minimize-maximize-close buttons and the tab name:
<img width="540" alt="test" src="https://cloud.githubusercontent.com/assets/20880213/17651814/35921aec-626e-11e6-9f23-55482e0da694.PNG">

This title bar is somewhat redundant and its omission would save some vertical space. The TabTree Firefox extension does this by default.

**Comment by piroor** [comment]
Basically TST forces to Firefox to show the system title bar, and userChrome.css cannot unify your navigation bar and the title bar. Thus I've added new secret preference `extensions.treestyletab.blockTabsInTitlebar` by the commit 4b2fae85b4256ff86f643305bfb55700abc3b7ea so you'll be able to customize your navigation toolbar via userChrome.css with `extensions.treestyletab.blockTabsInTitlebar`=`false`.

**Comment by piroor** [comment]
Anyway I believe that it is not a "tree" related feature and I won't add any option like "nav bar in the title bar". The only one thing I can do is that adding the extensions.treestyletab.blockTabsInTitlebar=false.

**Comment by mathearts** [comment]
Thank you very much, this secret preference did help me in what I was trying to achieve.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
