### ISSUE TITLE
Drag-dropping a link from outside doesn't work anymore (FF 49)

### ISSUE THREAD

**Issue by laggingreflex** [piroor/treestyletab#1178]
## Short description
I think due to a recent update in Firefox, Tree Style Tab is no longer able to handle links that are drag-dropped from other applications like from Chrome or OneNote. They used to work earlier. Now the only drag-drop that works is the links from the same FF window. Not from other outside applications or even from other Profiles of FF. It would work if you drop it into the address bar, so that TST isn't actually the one that's handling the drag-dropped link, but if you drop it into the TST sidebar nothing happens. 

## Steps to reproduce

 1. Start Filrefox with clean profile.
 2. Install TST.
 3. Try to drag a URL link from another application like Chrome and drop into TST sidebar

## Expected result
A new tab with that URL should open up

## Actual result
Nothing happens

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 49.0b3
 * Version (or revision) of Tree Style Tab: 0.17.2016061501

**Comment by piroor** [comment]
Thanks. The commit b067c7e7a72b6150ec76d06abc3b88e89c550021 should fix this problem.

**Comment by piroor** [comment]
I've released a new version 0.17.2016083001 includes commits for this issue, thus I close this.
