### ISSUE TITLE
TST's option icons got removed by bug 1284497

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#1180]
## Short description
[Bug 1284497 - Remove obsolete windowed preferences content that we're inadvertently still shipping](https://bugzilla.mozilla.org/show_bug.cgi?id=1284497)
I guess TST is still using those icons that will be removed in Firefox 50.
![tst_options](https://cloud.githubusercontent.com/assets/771216/17970756/79c6b9a8-6b0a-11e6-93e6-63b92dfee923.PNG)

## Steps to reproduce

 1. Start Nightly with clean profile.
 2. Install TST.
 3. Open TST's options window

## Expected result
All icons are present.

## Actual result
Some icons are missing.

## Environment

 * Platform (OS): Win10 Anniversary Update
 * Version of Firefox: current Nightly (2016-08-25)
 * Version (or revision) of Tree Style Tab: current TST nightly (0.17.2016082500a214144)

**Comment by piroor** [comment]
Thank you for pointing. Finally I've given up to provide icons for the pane switcher because Firefox 50 and later has no suitable icons for some panes like "Tab"...

**Comment by piroor** [comment]
I've released a new version 0.17.2016083001 includes commits for this issue, thus I close this.
