### ISSUE TITLE
Lost all tabs after update

### ISSUE THREAD

**Issue by guilhas** [piroor/treestyletab#1183]
## Short description
After last update lost all tabs.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install https://addons.mozilla.org/firefox/addon/vertical-tabs-reloaded/
 3. Remove vertical-tabs-reloaded
 4. Install TST
 5. Restart

## Expected result
Side bar with previous opened tabs

## Actual result
![ff error 20160908_1341](https://cloud.githubusercontent.com/assets/456810/18349778/b4f56f7c-75ca-11e6-988c-43db95f9912b.png)

All tabs disappear
Buttons highlighted not clickable
Open tabs and restart, disappear again

## Environment

 * Platform (OS): Win 7 64bit
 * Version of Firefox: ESR 45.3.0
 * Version (or revision) of Tree Style Tab: 0.18.2016090801

**Comment by piroor** [comment]
Thanks a lot. I successfully reproduce the problem and I've found that this problem is caused by a recent change. It's a regression...

**Comment by piroor** [comment]
0.18.2016090802 is now available on AMO.

**Comment by guilhas** [comment]
Solved. Thanks.

Best addon ever.

**Comment by mausalimi** [comment]
for me there is still something wrong in this

		if ('TabsInTitlebar' in window) {
                   ............ 
               }

the top border of firefox is about twice as high as it should be.
