### ISSUE TITLE
Microphone activity icon bleeds out of pinned tabs

### ISSUE THREAD

**Issue by Happy-Dude** [piroor/treestyletab#1185]
## Short description

Similar to #945, Mozilla has an icon next to tabs with which we can see that there is microphone use from the tab. We can click the icon to enable/disable it, etc. (Like the sound mute button.)

Like in #945, the icon was bleeding out of pinned tabs. Can TST be tweaked a bit to include the microphone icon in the same way + size?
## Steps to reproduce
1. Start Firefox with clean profile with TST installed.
2. Start an instance where the browser uses HTML5 microphone. An easy way would be to test on Discord voice chat (https://discordapp.com/).
3. Join a voice-enabled channel and enable permissions to share/use the device.
## Expected result

Microphone icon would either appear to the side of the pinned tab or replace it like with TST disabled:

![screen shot 2016-09-08 at 3 40 07 pm](https://cloud.githubusercontent.com/assets/1098725/18366117/0239eaa0-75db-11e6-8ea9-41695825ba19.png)
## Actual result

Microphone icon appears besides the favicon:

![screen shot 2016-09-08 at 3 35 36 pm](https://cloud.githubusercontent.com/assets/1098725/18366136/15ade88e-75db-11e6-8951-69cb0b2ae79b.png)
## Environment
- Platform (OS): Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:51.0) Gecko/20100101 Firefox/51.0
- Version of Firefox: Firefox Nightly 51.0a1 (20160908030434)
- Version (or revision) of Tree Style Tab: 0.18.2016090800a235718

**Comment by piroor** [comment]
Thanks! The commit 258437a fixes it for me.
