### ISSUE TITLE
Empty title bar

### ISSUE THREAD

**Issue by Andrey-dc** [piroor/treestyletab#1186]
Since version 0.18.2016090601 i have empty title bar in my firefox. It looks like this
![tst018_cr](https://cloud.githubusercontent.com/assets/16253156/18386425/a711a67a-769f-11e6-8219-7840d97e8c82.png)

Usually that is the place where my menubar and bookmarks are located. This is how it looks like with TST downgraded to 0.17.2016061501
![tst017_cr](https://cloud.githubusercontent.com/assets/16253156/18386674/19437c54-76a1-11e6-9edb-24bc3dfa165f.png)

Is it intended behavior or a bug? Can i make use of my title bar again by setting some options?

I've tried clean firefox profile and empty title bar appears as soon as i install tst of version above 0.17.2016061501
The value of extensions.treestyletab.blockTabsInTitlebar doesn't affect this behavior either.

I'm using Firefox 48.0.2 on win7x64 machine

**Comment by Andrey-dc** [comment]
Sure, but i didn't do anything special i'm afraid.
First i've created new profile in profile manager.
![new](https://cloud.githubusercontent.com/assets/16253156/18393889/025dce44-76c0-11e6-931b-60d99bf3258b.png)
Then enabled menu bar. 
![new2](https://cloud.githubusercontent.com/assets/16253156/18393912/1999bed8-76c0-11e6-84d8-185a3cfb9357.png)
Installed latest version of tst and restarted.
![new3](https://cloud.githubusercontent.com/assets/16253156/18393952/452d5a64-76c0-11e6-9f16-3a5719794af1.png)
And this one is with older version of tst
![new4](https://cloud.githubusercontent.com/assets/16253156/18393975/5f6113ee-76c0-11e6-82bd-a1af95ce2071.png)

**Comment by mausalimi** [comment]
seems to be the same as what i posted here: https://github.com/piroor/treestyletab/issues/1183

if i replace that code with an older one, it works again.

**Comment by piroor** [comment]
The commit 771a3bd should fix it. Thanks to very helpful screenshots!
