### ISSUE TITLE
Latest version does not work with Tab Groups addon

### ISSUE THREAD

**Issue by montypython77** [piroor/treestyletab#1189]
## Short description
Latest version broke all my groups made by addon TabGroups (https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/?src=ss), which is official tab groups plugin since Firefox stopped supporting tab groups in v44. Also, pinned tabs do not display correctly as small icons above the tree, they are just missing. After update, I lost all groups (some 200 tabs), but luckily, I had a backup. I went back to TreeSytleTab version 0.17.2016061501, where TabGroups work correctly.
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): Windows 10 Pro
 * Version of Firefox: 47.0.1
 * Version (or revision) of Tree Style Tab: 0.18.2016090802

**Comment by piroor** [comment]
Could you try the latest development build of TST?
http://piro.sakura.ne.jp/xul/xpi/nightly/
To try it, you will need to use beta or unbranded version of Firefox.
https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds

BTW, Firefox 47 is now outdated thus I don't test TST on Fx47 anymore. Please use Fx48, Firefox Beta, Nightly, or Fx45ESR.

**Comment by montypython77** [comment]
Yes, you are correct. Somehow Firefox always notified me that 47.0.1 is latest version, when I checked and auto update did not work either.
After updating Firefox to 48.0.2, TST works ok with TabGroups.
Sorry for false alarm, I should checked better.
BTW, thanks for great plugin.
