### ISSUE TITLE
Can't disable tree collapse

### ISSUE THREAD

**Issue by stonewareslord** [piroor/treestyletab#1190]
## Short description

When `extensions.treestyletab.twisty.style` is set to `none`and `extensions.treestyletab.twisty.expandSensitiveArea` is set to `false`, the tree still collapses when the favicon is clicked
## Steps to reproduce
1. Start Firefox with clean profile.
2. Install TST.
3. Go to about:config and set above values
4. Restart
5. Open webpage, control click on link so current tab has a child
6. Click current webpage's favicon
## Expected result

The tab is selected. Tree twisties are hidden and the option to hide child tabs on favicon click is off, so there should be no collapse.
## Actual result

The children are collapsed.
## Environment
- Platform (OS): Gentoo Linux
- Version of Firefox: v48.0.1
- Version (or revision) of Tree Style Tab: 0.18.2016090802

**Comment by piroor** [comment]
Currently it is a designed behavior. Here is the method to find "twisty" from a click event:
https://github.com/piroor/treestyletab/blob/c35e23955587b1b70c64fc7ee18789908cdc0e56/modules/base.js#L515
and there is a logic to use the favicon instead of the twisty, if the twisty is invisible.
https://github.com/piroor/treestyletab/blob/c35e23955587b1b70c64fc7ee18789908cdc0e56/modules/base.js#L533
If I remove these codes, you'll no able to expand a tree it is unexpectedly collapsed  by some reason. So I put this "fallback" logic for safety.

**Comment by stonewareslord** [comment]
if it isn’t possible to permanently disable collapsing, would that be a feature you’d be willing to add? Maybe the fallback logic could test for if the tree is closed and only expand tabs, never collapse them.

**Comment by piroor** [comment]
By some reasons I removed the ability to keep all tree expanded at #1070 - it was a design decision. 

Basically the twisty configuration "None" was for people who want to collapse/expand just clicking on the favicon, with any visual feedback. And basically TST is not designed to work with "always expanded tree". Sorry.

**Comment by NN---** [comment]
Tree collapsing drives me crazy.
I installed TST to see all tabs at once but instead I see nothing :(

**Comment by CrashNBurn71** [comment]
So don't click on the favicon?  With tabs on the left|right there's lots of room to activate a tab without triggering child-expansion|collapse.

**Comment by stonewareslord** [comment]
That isn't so easy with a setup like mine where the width of the tabbar is just as wide was a favicon plus a few pixels: 
![screen shot 2016-12-19 at 12 11 00 pm](https://cloud.githubusercontent.com/assets/7482347/21321823/74cb6248-c5e4-11e6-923a-4aeb28381512.png)

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
