### ISSUE TITLE
SpeedDial and open in background

### ISSUE THREAD

**Issue by duzers** [piroor/treestyletab#1195]
## Short description

Open in background in SpeedDial doesn't work after version 0.16.2015122501
## Steps to reproduce
1. Start Firefox with clean profile.
2. Install TST.
3. Install SpeedDial https://addons.mozilla.org/pl/firefox/addon/speed-dial/
4. There is an options "Mouse click actions" for dials. For middle click there is "Open in background tab".  With TST my dials always open in a new tab.
## 
## 
## Environment
- Platform (OS):  Windows 7, 10 x64
- Version of Firefox:  48.0.2 32bit
- Version (or revision) of Tree Style Tab: all after version 0.16.2015122501

**Comment by piroor** [comment]
Could you describe details of the problem? And you seem to use very old version of TST. If possible, please try TST latest version 0.18.2016090802 on Firefox 48.

**Comment by duzers** [comment]
Ok. It is ok, now?

**Comment by piroor** [comment]
Thanks, I've confirmed that middle-clicked thumbnail in a Speed Dial tab is always opened as a foreground tab instead of a background tab.

**Comment by piroor** [comment]
I've found the reason why new tabs are always opened in foreground - it was my mistake. The commit bbeb869 fixes this problem. Thanks again!

**Comment by duzers** [comment]
This problem come back with new version of three style tab.

**Comment by piroor** [comment]
Thanks! 4d7f6bb should fix this.
