### ISSUE TITLE
Empty bar above tabs bar when opening maximized firefox

### ISSUE THREAD

**Issue by magroski** [piroor/treestyletab#1198]
## Short description

An empty bar is appearing above the tabs bar when I open maximized Firefox after setting the TST position to TOP
## Steps to reproduce
1. Start Firefox with clean profile.
2. Install TST.
3. Go to add-ons settings
4. Set TST appearance to Top (Firefox default)
5. Maximize Firefox window
6. Close Firefox
7. Open Firefox
## Expected result

![ff](https://cloud.githubusercontent.com/assets/2437681/18876029/7ef77efa-849e-11e6-830b-1fd06501187a.png)
## Actual result

![ff2](https://cloud.githubusercontent.com/assets/2437681/18876035/851afa5a-849e-11e6-9459-45bfbfdc6c1c.png)
## Environment
- Platform (OS): Windows 10 
- Version of Firefox: 49.0.1
- Version (or revision) of Tree Style Tab: 0.18.2016090802
## Workaround

Alternative 1: After opening Firefox (maximized), click the maximize button to restore default window size, then click it again to maximize. Firefox will maximize and the tabs will fall in line with the window action buttons.

Alternative 2: Press alt to show the menu options, then press alt again to hide it. The tabs will fall in line with the window action buttons.

**Comment by GiftWolf** [comment]
Same issue with the tab bar on the left i.e. default settings. An empty titlebar appears when resizing the window. However your workarounds don't work then.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
