### ISSUE TITLE
When autohide is on, cannot delete word on facebook chat

### ISSUE THREAD

**Issue by pihentagy** [piroor/treestyletab#1199]
## Set
1. Set Auto Hide tab bar
2. Set Ctrl to show tabs on a very small delay (0 or 1)
3. Go to facebook, start writing a message
4. Try to delete a word by Ctrl+Backspace
## Expected result

Word is deleted
## Actual result

Word not deleted, chat window loses focus
## Environment
- Platform (OS): Ubuntu
- Version of Firefox: 49.0
- Version (or revision) of Tree Style Tab: 0.18.2016090802

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
