### ISSUE TITLE
Auto hide delay

### ISSUE THREAD

**Issue by LT11222** [piroor/treestyletab#1200]
It appears that in the settings window where you set the autohide delay value:

![delay](https://cloud.githubusercontent.com/assets/7864188/19001578/ccbf48ba-8715-11e6-8c77-50a67cf9635d.png)

This value sets the **extensions.treestyletab.tabbar.autoHide.delay** property, instead of the **extensions.treestyletab.tabbar.autoHide.delay.show** property.

I'm using the most recent TST version from the firefox addons site that I just redownloaded today.

**Comment by piroor** [comment]
Thanks, I missed that...
