### ISSUE TITLE
selectedTab=newTab after addTab("",{relatedToCurrent:true}) opens a new tab at the end of all tabs

### ISSUE THREAD

**Issue by Dook1** [piroor/treestyletab#1201]
## Short description

If after _newTab=browser.addTab("",{relatedToCurrent:true})_ follows _browser.selectedTab=newTab_, the new tab is opened as **independent tab**, but should be opened as **a child of the current tab**.
## Steps to reproduce

var browser=window.getBrowser();
var newTab=browser.addTab("",{relatedToCurrent:true});
browser.selectedTab=newTab;
## Expected result

A new tab should be opened as **a child of the current tab**.
## Actual result

A new tab should be opened as **an independent tab**.

**Comment by Dook1** [comment]
browser.js:      if (!tab.owner || tab != b._lastRelatedTab)
In this case b._lastRelatedTab is nul.

**Comment by LookingForWayOut** [comment]
I am commenting because I have the same issue. I am no Firefox expert. Is there a fix to this I can try? My coding abilities very basic to understand if the above would work or not.
Thank you.

**Comment by Dook1** [comment]
Replace in browser.js:
   **if (!tab.owner || tab != b._lastRelatedTab)**
to:
**if (!tab.owner)**

**Comment by piroor** [comment]
The commit 6d0199b should fix this problem.

Basically Firefox's "tab.owner" and "tabbrowser._lastRelateTab" information are too volatile. The commit introduces some hooks for those properties to store "parent tab" information until TST uses it.

**Comment by Dook1** [comment]
Thanks. Fixed.

**Comment by timss** [comment]
Possible regression: #1264
