### ISSUE TITLE
Blank Titlebar when Classic Theme Restorer > Options > Firefox Button > Use Firefox Titlebar enabled

### ISSUE THREAD

**Issue by tanstaafl** [piroor/treestyletab#1203]
## Short description

Conflict with Classic Theme Restorer (tried 1.5.7 and 1.5.6) when enabling Firefox button > Use Firefox titlebar instead of OS titlebar

Normally the Menu bar is drawn in the titlebar with this option enabled. This still works correctly with Tree Style Tab after 0.17.2016061501

With all later versions of Tree Style Tab, this is broken. Instead of drawing the menu bar in the titlebar, the titlebar is blank (except for the Firefox button), and the menu bar is displayed below it.
## Steps to reproduce

I installed fresh Firefox 49.0.1, clean/fresh profile, installed Classic Theme Restorer 1.5.7, draw in titlebar works as expected.

Install Tree Style Tab latest version, titlebar is blank

Install Tree Style Tab 0.17.2016061501, menu bar is drawn inside titlebar as expected.
## Environment
- Platform (OS): Windows 7 Pro 64bit
- Version of Firefox: 49.0.1
- Version (or revision) of Tree Style Tab: tried from version 0.17.2016061501 through latest 802.

**Comment by tanstaafl** [comment]
Ok, figured out how to install the dev version in my standard release version of Firefox 49... so, did that, and the titlebar is no longer blank, but it is wonky... the top 10 or so pixels are getting cut off...

So, looks like you are aware of the issue, and are working on fixing it?

**Comment by tanstaafl** [comment]
Clarification: by 'no longer blank', I mean that the menu bar is now getting drawn in the titlebar again, but it is moved too far up - as I said, the top 10 or 15 pixels are cut off...

**Comment by VVelda** [comment]
Alto affected by this bug on Cyberfox 49.0. Tree Style Tab reshow menu bar toolbar every browser start during TST own start. But menu isn't displayed, only blank space for toolbar. This is, how it looks like:
![tst-menu](https://cloud.githubusercontent.com/assets/3459338/19417528/a491ab48-93af-11e6-8cf3-a9d57be898c4.png)
It's annoying, 'cause I need to hide it every restart.

**Comment by piroor** [comment]
Does this still happen with the latest development build? http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by piroor** [comment]
Note, you need to use the unbranded  build of Firefox to try the unsigned XPI. https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds

**Comment by VVelda** [comment]
Latest build still re-enables menu bar after browser start, but now without the blank space, so it is much better, thanks.
In fact, there is some "negative blank space:
![tst](https://cloud.githubusercontent.com/assets/3459338/19418301/76ea2078-93c1-11e6-91d6-662edc965836.png)
"
However, that does not matter. Just curious why it is every time reenabled.

**Comment by tanstaafl** [comment]
When you said 'negative blank space', this is what I meant when I said it is wonky - the top 10 or so pixels are getting cut off.

And it is not necessary to use the unbranded build to install unsigned addons... just follow the instructions here:

http://www.ghacks.net/2016/08/14/override-firefox-add-on-signing-requirement/

**Comment by tanstaafl** [comment]
Also, VVelda, the number of pixels getting cut off appear to be about the same as the number of pixels of the blank space showing in your screenshot with Menu bar enabled...

**Comment by VVelda** [comment]
Luckily, any problem described to install unsigned extension to Cyberfox. :-)

**Comment by tanstaafl** [comment]
So, for now I'm stuck disabling auto-update for Tree Styl;e Tab, but really dislike having to do this, as it gets to be a maintenance nightmare (I manage a smallish 60+ workstation user base)...

Any chance this gets fixed sooner rather than later?

**Comment by tanstaafl** [comment]
So... any chance of this getting fixed any time soon? I'm startinng to worry that pinning TST to this old version that doesn't have the bug will end up causing even more problems down the road.

**Comment by tanstaafl** [comment]
Ok, so I just checked again and presto! The latest nightly - 0.18.2016110400a153928 - is back to normal!

Thanks!!

Now - any chance of submitting a fixed version to Mozilla now? I don't mind being on a dev build myself, but not for our regular users.

**Comment by piroor** [comment]
Can I close this?

**Comment by tanstaafl** [comment]
Yes, thanks!

**Comment by tanstaafl** [comment]
A question if you don't mind...

I googled and didn't find an answer...

Are you planning on converting Tree Style Tab to a Web Extension? It is
on my 'Must Have' list.

Maybe now is a good time to start donating to some of my favorite Addon
Authors... ;)

Thanks very much for an incredibly useful Addon!

Charles

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
