### ISSUE TITLE
Additional shortcuts for opening new tab as Root, Sibling, or Child

### ISSUE THREAD

**Issue by Andrade** [piroor/treestyletab#1205]
I'm a heavy keyboard user and usually I open new tabs with <kbd>Ctrl + T</kbd>. Is it possible to have additional shortcuts for opening the new tab in a different place?

The idea would be to have something like:
- <kbd>?????</kbd> to open new tab as a root tab
- <kbd>?????</kbd> to open a new tab as sibling of the current tab
- <kbd>?????</kbd> to open a new tab as a child of the current tab

I left the shortcuts as <kbd>?????</kbd> since I don't know what would be appropriate keys. (Maybe the user could assign keys of her choosing through configuration options?) One of these would certainly be <kbd>Ctrl + T</kbd>.

**Comment by sumyungguy** [comment]
Use Dorando Keyconfig addon, and the examples in the Wiki:
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-keyboard-shortcuts

**Comment by piroor** [comment]
Because it is the red ocean, I don't want to add new keyboard shortcuts to TST. It will conflict to other addons (I don't know them). Instead, as described above, I recommend you to use another addon for keyboard shortcut management.

**Comment by Andrade** [comment]
The Dorando Keyconfig addon does the job and was easy to setup using @sumyungguy's instructions.
