### ISSUE TITLE
When opening a new tab, the entry in the tab tree is initially not rendered

### ISSUE THREAD

**Issue by HighCommander4** [piroor/treestyletab#1206]
## Steps to reproduce

Open a new blank tab, or open a link in a new tab.
## Expected result

The entry for the new tab in the tab tree (showing the website icon and page title) is immediately rendered.
## Actual result

The entry remains blank (not rendered), until further user action, such as activating it, or hovering the mouse over it. Please see this screenshot, which shows this happening for the second tab:

![treestyletab-no-rendering](https://cloud.githubusercontent.com/assets/1751085/19532676/ca8dfa38-960a-11e6-82f5-6c89a4b63e84.png)
## Environment
- Platform (OS): Debian Linux (stable)
- Version of Firefox: Nightly (2016-01-17)
- Version (or revision) of Tree Style Tab: 0.18.2016090802

This problem has appeared recently with Firefox Nightly (last week or two).

**Comment by DimitryAndric** [comment]
I'm seeing exactly the same on OSX Nightly 52.0a1 (2016-10-28) (64-bit), with TST 0.18.2016090802 (latest signed version from addons.mozilla.org).  So it is not OS dependent, at least. :)

**Comment by piroor** [comment]
This is dup of #1202, so I close this.
