### ISSUE TITLE
random performance hit

### ISSUE THREAD

**Issue by br4nnigan** [piroor/treestyletab#1209]
Hello piroor,

i have an issue that i have researched thoroughly. Because i couldn't reproduce it with a clean FF profile it's not really an issue but i want to ask your for your help anyway. I could reproduce this with only treestyletab active, without treestyletab this does not occur.

The issue is: sometimes plugin-container CPU consumption goes up from like 7 to 14 and the performance takes a huge hit. Scrolling is really laggy and it's almost impossible to close a tab by clicking the X, because it is so unresponsive (have to use ctrl+w). 

Then when i **close a random tab or open a blank new tab** performance goes back to normal. That's crazy, right? 

Do you have an explanation for this or maybe can even track it down to a bug in the addon?

**Comment by br4nnigan** [comment]
No this does not occur with TST disabled. I always have about 50 tabs open, with 3-6 being loaded.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
