### ISSUE TITLE
Feature - Click to unhide

### ISSUE THREAD

**Issue by MaikoID** [piroor/treestyletab#1210]
## Short description

Hi, it would be nice if we can click to unhide the tab bar instead of use the mouse hover. What do you guys think about it ?

**Comment by piroor** [comment]
In the mode, when the tab bar should be shrunken? After the mouse moves out from the tab bar?

**Comment by MaikoID** [comment]
yes, it sounds nice. The hoover is not good when using dual monitors because the tab bar popups and it remains open hidding the pages content, common case, when you are doing another thing in the second monitor and want  to read the web page from Firefox.

**Comment by piroor** [comment]
Implemented by the commit 220395c9efb9a530fa391e8b47d39428339fe1fb and followings.
