### ISSUE TITLE
Auto-hide width

### ISSUE THREAD

**Issue by lasers** [piroor/treestyletab#1211]
Hi. I would like to make a request for something like "Auto shrink tab bar (icon only)" feature. I also found somebody else's same request. https://github.com/piroor/treestyletab/issues/799 

Instead of implementing "Auto shrink tab bar (icon only)" feature, you could implement an "Auto-hide width" textbox option where the users can input their auto-hide width? That way, some people can get their icons and the others can get their preferable width distance. 

What do you think?

![tabtreestyle](https://cloud.githubusercontent.com/assets/852504/19831932/a5a9b4ea-9ddb-11e6-908e-a0867dd98504.png)

**Comment by piroor** [comment]
Sorry but I have no plan to put a text box for the preference. There are some reasons:

 * I don't want to add more configuration UI to the configuration dialog, because there are already too much items. I believe that most people don't want to control the shrunken width to exact 16px. Instead the tab bar should be resized by dragging of the separator roughly.
 * You can set the exact width of the tab bar with about:config. Go to about:config and change the value of a secret (internal) preference: `extensions.treestyletab.tabbar.shrunkenWidth`.

**Comment by lasers** [comment]
Thank you for that useful internal preference. I set it to 32 just now so I will see how it feels to have something small like this... for few days.. 

Mozilla Firefox team came out with Tab Center which is somewhere like TST if you want to check it out. I like how fluid Tab Center feel sometimes, but I think I like TST better because I probably want it to stay static most of the time.

Also, I have been using this extensions for days... I want to know if it would be feasible to add a trigger like `promoteCurrentTab()` for all tabs?

Reason: Sometimes, I'm finished with the trees after few days and would "nuke" all trees, sort the tabs by URLs, then start weeding out duplicates and the tabs I no longer wanted/needed. I don't like to manually promote all tabs.

Second thing about `promoteCurrentTab()` is that I'm able to use it with Vimperator that will let me run loop on all tabs (if you don't want to make `promoteAllTab()` button for others to use)... I would like to `promoteCurrentTab()` to promote tabs without loading unloaded tabs.

**Comment by piroor** [comment]
TST has an API: `gBrowser.treeStyleTab.detachAllChildren(aParentTab)`. I think it will work for your need. Could you try it?

**Comment by lasers** [comment]
Good news. I hate width 32 already and went back to 140. I couldn't tell what I had without names and trees. Bad news. It didn't work. I got `ReferenceError: aParentTab is not defined`. I tried allTabs too. What else should I try?

**Comment by piroor** [comment]
`aParentTab` is one of tabs which has children. You need to specify something actually. For example: `gBrowser.treeStyleTab.detachAllChildren(gBrowser.selectedTab)`, `gBrowser.treeStyleTab.detachAllChildren(gBrowser.tabs[0])`, etc.

**Comment by lasers** [comment]
I tried `gBrowser.treeStyleTab.detachAllChildren(gBrowser.selectedTab)` or that another one on demoted tabs. It does not work for me. Keep in mind that I don't know any Javascript and I have been trying random things I found online... to no effect. I already got what I came here for with auto-width though... That feature sounds good on the paper but not lot of practical... so thank you for that.
