### ISSUE TITLE
modules/lib/prefs.js should be updated

### ISSUE THREAD

**Issue by asamuzaK** [piroor/treestyletab#1212]
## Short description
"JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead" warning message is logged because of module/lib/prefs.js

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open console (Ctrl + Shift + J)
 4. 

## Expected result
No warning message

## Actual result
"JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead" warning is logged

## Environment

 * Platform (OS): Win 10
 * Version of Firefox: 51.0a2
 * Version (or revision) of Tree Style Tab: 0.18.2016101300a233642

## Note
"リンクを新しいタブで開く" has the same issue.

**Comment by piroor** [comment]
Now the library must be updated to the revision 16.
https://github.com/piroor/fxaddonlib-prefs/blob/master/prefs.js

**Comment by piroor** [comment]
Done!

**Comment by asamuzaK** [comment]
Confirmed. Thanks!
