### ISSUE TITLE
New independent tab position

### ISSUE THREAD

**Issue by ziima** [piroor/treestyletab#1214]
## Short description
I started to use Tree Style Tab, but one thing doesn't suits me. I set the new blank tab to open as independent, but I miss the option to define its position. They always open at the bottom, not at the top (or next to the active tab). I found no setting for that.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open new tab

## Expected result
New tab is opened at the top or next to the active tab.

## Actual result
New tab is opend at the bottom

## Environment

 * Platform (OS): Debian
 * Version of Firefox: 45.4
 * Version (or revision) of Tree Style Tab: 0.18.2016090802

**Comment by piroor** [comment]
See TST configuration => "New Tab" => "Open new blank tab as:", then you'll find out the choice.

**Comment by ziima** [comment]
Found it. Though I consider "the next sibling of the current tab" somewhat cryptic.

**Comment by ziima** [comment]
Thanks anyway :)
