### ISSUE TITLE
Swithng between tabs by scrolling doesn't work

### ISSUE THREAD

**Issue by kanmeiban** [piroor/treestyletab#1216]
## Short description

Neither mouse nor trackpad. Noticed this around March-April 2016, since Firefox fourty-something.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open several tabs
 4. Try to scroll in the tab area

## Expected result

Switch between tabs.

## Actual result

Nothing.

## Environment

 * Platform (OS): Mac OS X 10.11.6 (El Capitan)
 * Version of Firefox: 49.0.2
 * Version (or revision) of Tree Style Tab: 0.18.2016090802

**Comment by Keith94** [comment]
It's not supposed to switch tabs by default, as far as I know.. You can use an add-on like [Tab Wheel Scroll](https://addons.mozilla.org/addon/tab-wheel-scroll/).

**Comment by kanmeiban** [comment]
@Keith94 Thank you very much for clearing this out! It is really strange that scroll used to work with TreeStyleTab until recently.
