### ISSUE TITLE
QUESTION - Is There a Search Bar?

### ISSUE THREAD

**Issue by LookingForWayOut** [piroor/treestyletab#1217]
Hello. I am trying this out, which ever version I downloaded today on FF50 on Windows 7. I am trying to find alternatives to TabKit2. Anyway, is there a search ability to search through your tabs for matching words to title/content? I could not find any reference to it in this site, not that this is a forum, or online. Wanted to come ask directly.
As trying this out, seems clean and simple. Does what I need. A few issues trying to move a tab to become a child, or a parent, but otherwise seems slick. Am testing it out more as the weeks go on. Just wanted to ask if there is a hidden option for searching through the tabs.
Thank you.

**Comment by piroor** [comment]
TST doesn't have such a feature because it is designed to provide "tree of tabs" feature. If you know any other addon to provide only the feature to shrink tabs by the search term, I'll make TST compatible to work with it. However, I won't merge the feature to TST natively.

**Comment by GDXN** [comment]
As the features don't exist the function can be obtained with this extensions: "Tabhunter" and "Search Tab" let you search for words in tab title, and "Hugo Search All Tabs" is for searching in all tabs at the same time. I prefer the extension like TST, extension that do only one thing very well and without bloatware.

**Comment by piroor** [comment]
* [Tabhunder](https://addons.mozilla.org/firefox/addon/tabhunter/): opens new dialog to search tabs.
 * [Search Tab](https://addons.mozilla.org/firefox/addon/search-tab/): provides a search field in the status bar. But current Firefox doesn't have status bar by default.
 * [Hugo Search All Tabs](https://addons.mozilla.org/firefox/addon/hugo/): provides its custom sidebar to find tabs.

Hmm, "Search Tab" sounds like the one I told but it doesn't work for me on Nightly 55.0a1...

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
