### ISSUE TITLE
Scroll button do not hide.

### ISSUE THREAD

**Issue by Aglan** [piroor/treestyletab#122]
From time to time, when I collapse tree and have free space in tabbar scroll buttons still stay on tabbar to.
<a target="_blank"; href="http://itmages.ru/image/view/210619/8c433cd7"><img src="http://storage7.static.itmages.ru/i/11/0613/s_1307992514_8c433cd7bc.jpeg" /></a>

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
