### ISSUE TITLE
Option "next sibling of the current tab" still broken for the last subtree

### ISSUE THREAD

**Issue by rstarkov** [piroor/treestyletab#1221]
## Short description

Issue #1193 is not really fixed fully. When new blank tabs open as "the next sibling of the current tab", sometimes the tree is mis-shaped, in release 0.18.2016111701, but only in specific circumstances.

## Steps to reproduce
1. Start Firefox with clean profile.
2. Install TST.
3. In TST options, select "the next sibling of the current tab" under "New Tabs"
4. Create a tab tree like this:
   - tab 1
     - tab 2
   - tab 3
     - tab 4
       - tab 5
5. Activate tab 4
6. Press Ctrl+T

## Expected result

   - tab 1
     - tab 2
   - tab 3
     - tab 4
       - tab 5
     - [new tab]

## Actual result

   - tab 1
     - tab 2
   - tab 3
     - tab 4
     - [new tab]
       - tab 5

**Comment by piroor** [comment]
Confirmed.

**Comment by piroor** [comment]
The commit 1eb0502 should fix this.
