### ISSUE TITLE
piroor, help please with issue about Tree Style Tab in Pale Moon

### ISSUE THREAD

**Issue by supermariomd** [piroor/treestyletab#1223]
piroor, Hi.
I am love your beautiful extension.
I am using **Tree Style Tabs Version 0.14.2014051101.1-signed** for over a few  years successfully with Pale Moon. But now, after updating to PM ver. 27 i can't use this bunch.

Description about this issue is here https://forum.palemoon.org/viewtopic.php?f=46&t=13665&p=99921#p98379

My environment is Windows 8.1 64bit using Pale Moon 27.0.1 64bit + Tree Style Tabs Version 0.14.2014051101.1-signed

**Comment by piroor** [comment]
Sorry but I have no motivation to maintain TST for Pale Moon by many reasons:

 * I don't use it. (This is the main reason.)
 * Now my hands are full with too much tasks so I had to triage many things.
 * Pale Moon is based on too old Firefox, and the official Firefox goes ahead day by day. It is impossible to support both too old and latest versions of Firefox and Pale Moon, with reasonable costs.

Please fork TST for your purpose and maintain it by yourself, please.

**Comment by kerframil** [comment]
@supermariomd There is a compatible fork here: https://github.com/oinkin/treestyletab
