### ISSUE TITLE
Missing titlebar menu after installing TST

### ISSUE THREAD

**Issue by Coldblackice** [piroor/treestyletab#1225]
## Short description
After installing TST on a fresh install/profile of Cyberfox, the titlebar menu is no longer able to be accessed. Pressing ALT does nothing.

## Steps to reproduce

 1. Start Cyberfox with clean profile.
 2. Install TST.
 3. Titlebar menu can no longer be accessed (press ALT key -> nothing)

## Expected result

After pressing ALT, the titlebar menu *should* appear (File|Edit|Tools|etc)

## Actual result

Titlebar menu can no longer be accessed (press ALT key -> nothing). This happens immediately after TST is installed.

## Environment

 * Platform (OS): Win7 Ultimate x64
 * Version of Firefox: Cyberfox 50.0.2
 * Version (or revision) of Tree Style Tab: 0.18.2016111701

**Comment by piroor** [comment]
Sorry but TST is not designed for Cyberfox. Cyberfox seems a modified version of Firefox, so you have to modify TST to work with it. However I'm using official Firefox and I have no motivation to maintain my addon for different application I never use. Please fork TST for Cyberfox and maintain it by yourself for your purpose.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
