### ISSUE TITLE
Phrase "Connecting…" is slightly off the tab due to bug 658467

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#1226]
## Short description
Video of the problem: https://gfycat.com/ComposedPlainGermanspaniel
Screenshot of the problem: 
![bug658467](https://cloud.githubusercontent.com/assets/771216/21075058/ae7a27d8-bf43-11e6-81cc-277bd4206796.PNG)

## Steps to reproduce

 1. Start Nightly 2016-12-10 or later with clean profile.
 2. Install TST.
 3. Load any page.
 4. Observe the phrase "Connecting…" on the tab.

## Expected result
The phrase is not displaced.

## Actual result
The phrase is slightly off the tab due to some changes in [bug 658467 - Fade out tab label on overflow instead of ellipsis ](https://bugzilla.mozilla.org/show_bug.cgi?id=658467)

## Environment

 * Platform (OS): Windows 10 AU
 * Version of Firefox: Nightly 2016-12-10 build
 * Version (or revision) of Tree Style Tab: TST nightly (0.18.2016113000a095431)

**Comment by Fanolian** [comment]
Confirmed fixed by 2c1a12713662cac89ff6d06114adfea51c2cbdf0. Thanks.

**Comment by piroor** [comment]
Thank you for the detailed report! It greatly helped me ;)
