### ISSUE TITLE
TitleBar doesn't show tab title

### ISSUE THREAD

**Issue by NN---** [piroor/treestyletab#1227]
Is there any possibility to display full tab title in title bar ?
Currently I see only small favicon without any text.
In order to see title I have to hold Ctrl and wait and even after that the TST doesn't show full title since I don't want it to be expanded to the whole screen.

**Comment by piroor** [comment]
Title bar is not controlled by TST. I think you should use something another addon with TST...

**Comment by CrashNBurn71** [comment]
With tabs on the left|right, Titlebar is populated as expected.

**Comment by piroor** [comment]
I think I possibly misunderstood your report. Could you post some screenshots?

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
