### ISSUE TITLE
Tab title's descenders are clipped off due to bug 658467

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#1228]
## Short description
After [Bug 658467 - Fade out tab label on overflow instead of ellipsis](https://bugzilla.mozilla.org/show_bug.cgi?id=658467) (300% zoom): 
![tst_bad](https://cloud.githubusercontent.com/assets/771216/21098084/8267d86a-c0a2-11e6-82fc-0690200740fc.PNG)

Before bug 658467:
![tst_good](https://cloud.githubusercontent.com/assets/771216/21098176/e1540510-c0a2-11e6-8d50-22778427df18.PNG)

## Steps to reproduce

 1. Start Nightly 2016-12-10 or later with clean profile.
 2. Install TST 0.18.2016121200a114025 or 0.18.2016111701.
 3. Find a tab title with characters with descenders (g, j, p, q, y).

## Expected result
Whole character is shown for gjpqy.

## Actual result
The bottom part of these characters are clipped off.

## Environment

 * Platform (OS): Windows 10 AU
 * Version of Firefox: Nightly 2016-12-11
 * Version (or revision) of Tree Style Tab: 0.18.2016121200a114025 (with the fix 2c1a12713662cac89ff6d06114adfea51c2cbdf0 from #1226) or 0.18.2016111701 (current release)

**Comment by piroor** [comment]
Thanks. bd4599e fixes this for me on Windows, but not well at the Metal theme yet...

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
