### ISSUE TITLE
With 'mixed' style, new tab button inconsistently placed

### ISSUE THREAD

**Issue by DimitryAndric** [piroor/treestyletab#1229]
## Short description

Since Nightly 2016-12-10, with the 'mixed' style, the new tab (plus) button is semi-randomly displayed at the bottom of the tab tree, or sometimes at the bottom of the window.

Whenever new tabs are opened, the button seems to move to the bottom of the window, when some (but not all) tabs are closed, the button moves back to the bottom of the tabs tree.

## Steps to reproduce

 1. Start Firefox Nightly 2016-12-10 or later with clean profile.
 2. Install TST 0.18.2016111701 (latest on addons.m.o).
 3. Go to TST preferences, select 'mixed' appearance.
 4. Open a few tabs, close some tabs.
 5. Observe the new tab button semi-randomly jumping about.

E.g. sometimes the tab bar looks like this:
![before](https://cloud.githubusercontent.com/assets/9060368/21112372/d2f95a1c-c0a5-11e6-9e6f-e5bb9e1b9060.png)

Randomly, it can also look like this:
![after](https://cloud.githubusercontent.com/assets/9060368/21112376/d92f321c-c0a5-11e6-87df-c9cacdd7fce2.png)

## Expected result

New tab button should permanently stay at the bottom of the tab list (unless the tab list is filling up the whole window)

## Actual result

New tab button is sometimes at the bottom of the tab list, sometimes at the bottom of the window, even if the tab list does not fill up the window.

## Environment

 * Platform (OS): OSX
 * Version of Firefox: Nightly 2016-12-10
 * Version (or revision) of Tree Style Tab: 0.18.2016111701

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
