### ISSUE TITLE
Wrong placement of child tabs count in Nightly

### ISSUE THREAD

**Issue by f1u77y** [piroor/treestyletab#1230]
## Short description
Wrong placement of child tabs count in Nightly
## Steps to reproduce

 1. Start Nightly with clean profile.
 2. Install TST.
 3. Open one tab in browser
 3. Open some tab as sibling of current
 4. Collapse the tree

## Expected result
Placement of child tabs count is the same as in Firefox 50.1.0(with the same steps)
![Screenshot of Firefox 50.1.0](http://imgur.com/1EuwrSh.png)

## Actual result
Placement of child tabs differs
![Screenshot of Nightly](http://imgur.com/sjCsH3Q.png)

## Environment

 * Platform (OS): GNU/Linux
 * Version of Firefox: Nightly 53.0a1.20161212
 * Version (or revision) of Tree Style Tab: 0.18.2016111701

**Comment by f1u77y** [comment]
[Could be related](https://bugzilla.mozilla.org/show_bug.cgi?id=658467)

**Comment by piroor** [comment]
By recent commits this problem seems go away. Could you try the latest development build? http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by f1u77y** [comment]
Oh, forgot to try it before submitting the issue.
Yes, it works.
