### ISSUE TITLE
Page title misplaced shortly after being changed

### ISSUE THREAD

**Issue by BlackVoid** [piroor/treestyletab#1233]
## Short description
When a page changes the title or a new page is loaded the title is shortly (0.1s) place incorrectly and not snipped.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Go to a page where the title is refreshed (also seen when loading a new page)

## Expected result
When the title is updated the text is not moved temporary and is snipped right away.

![2](https://cloud.githubusercontent.com/assets/673720/21482387/bb77cf94-cb73-11e6-806a-3fa823aa4bfd.png)

## Actual result

![1](https://cloud.githubusercontent.com/assets/673720/21482388/bb77c7c4-cb73-11e6-9ec4-a92a95434ae3.png)

## Environment

 * Platform (OS): Fedora 23
 * Version of Firefox: 53.0a1 (Nightly)
 * Version (or revision) of Tree Style Tab: 0.18.20161111701

**Comment by piroor** [comment]
Dup of #1226 ?

**Comment by BlackVoid** [comment]
Seems like the same issue
