### ISSUE TITLE
Compatibility issue [Tab Groups] - new tab hangs Firefox when it overlaps with bottom edge of window

### ISSUE THREAD

**Issue by maricn** [piroor/treestyletab#1236]
## Short description
The issue is with enormous performance impact when the window's height is just right so that new tab button is positioned on the bottom, overlapping with bottom edge of window. It then starts blinking and about:performance shows Tree Style Tab uses over 50% CPU and has framerate impact 9/10.

Possibly related to [issue#1229](https://github.com/piroor/treestyletab/issues/1229)

## Steps to reproduce

 1. Start Firefox with Tab Groups and Tree Style Tab addons.
 2. Open as many tabs as needed to populate almost whole window height.

## Expected result

No special performance impact.

## Actual result

Firefox hangs, 9/10 framerate impact from treestyletab, and new tab button blinks.
![screen shot 2016-12-29 at 11 57 46](https://cloud.githubusercontent.com/assets/3995223/21542682/cef2a406-cdbf-11e6-9c2b-77a6437cd610.png)

## Environment

 * Platform (OS): OSX Sierra 10.12.2
 * Version of Firefox: 50.1.0
 * Version (or revision) of Tree Style Tab: 0.18.2016111701

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
