### ISSUE TITLE
API to reset tabs tree data

### ISSUE THREAD

**Issue by onemen** [piroor/treestyletab#1238]
Tabmix have an option to restore into current window: "Restore, Overwrite Existing Window(s)"

Restoring saved session with a tree data onto existing tree not working as expected.

Is there a treeStyleTab API to reset the tree data before restoring ?

**Comment by piroor** [comment]
It can be done by `gBrowser.treeStyleTab.resetAllTabs(true)`. It is currently not declared as "public API", but if you use this, I add the tag for the method.

**Comment by onemen** [comment]
Thank you.
I will test it in the next development version

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
