### ISSUE TITLE
[feature request] Shortcut for adding sibling tabs

### ISSUE THREAD

**Issue by DonyorM** [piroor/treestyletab#1239]
## Short description
Right now you can set where new tabs (created with Ctrl+T) appears (sibling, child, root, etc.). This if fine, but I would like to be able to open a sibling tab with a shortcut as well. Having to drag the new tab up to the current tab is extremely annoying.

Would it be possible to add a new shortcut (possible Alt+T) to allow creating a new tab as a sibling to the current tab?

I haven't worked much with the firefox API, but if I can I'll try to submit a pull request to add this feature. Any pointers would be much appreciated.

**Comment by sumyungguy** [comment]
The feature is already there!
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-keyboard-shortcuts#as-sibling-tab

You can also make shortcuts to move tabs, which can be easier than dragging them.
