### ISSUE TITLE
Site icon overlaid by default tab icon when using Silvermel theme

### ISSUE THREAD

**Issue by Kakurady** [piroor/treestyletab#124]
When using Charamel/Silvermel  theme avaliable from addons.mozilla.org together with treestyletab, the tabs' icon (xui:image with class "tab-icon-image") is overlaid by a default tab icon (xui:image with class "tab-extra-status" ) so it's difficult to see the actual icon.

This does not matter whether the extension bundled with Silvermel (Silvermel XT) is enabled or disabled.

Silvermel version: 1.4.1
treestyletab version: 0.1.2.2011060202
Firefox version: Mozilla/5.0 (X11; Linux x86_64; rv:2.0.1) Gecko/20100101 Firefox/4.0.1

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
