### ISSUE TITLE
Tab Mix Plus 0.5.0.2 version conflicts with TreeStyleTab sidebar tabs style on Firefox 53

### ISSUE THREAD

**Issue by MurzNN** [piroor/treestyletab#1240]
After updating from Tab Mix Plus 0.5.0.1 to Tab Mix Plus 0.5.0.2 on Firefox 52 alpha version - tab title width is overflow sidebar with tabs, here is screenshot with problem: http://i.imgur.com/uH9Zk51.png
If I revert back version 0.5.0.1 - tab with goes normally, here is same tabs screenshot: http://i.imgur.com/Y8NYhmo.png
At first I report this problem into Tab Mix Plus forum: http://tabmixplus.org/forum/viewtopic.php?f=2&t=19749 but he ask me to post issue in TreeStyleTab, so I duplicate this issue here.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
