### ISSUE TITLE
Border glitch on tab select

### ISSUE THREAD

**Issue by damat** [piroor/treestyletab#1242]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set Appearance to Vertigo 
 4. Select unselected tab

## Expected result
Tab switches to selected smoothly

## Actual result
http://i.imgur.com/jRf7HC8.gif 
On down event there's an a different border for several frames. I wasn't able to detect the source of this border. And there's no such glitch in other Appearance styles

## Environment

 * Platform (OS): Win 8 x64
 * Version of Firefox: 50.1.0
 * Version (or revision) of Tree Style Tab: 0.18.2016111701

**Comment by piroor** [comment]
The curvy border problem doesn't happen on my Windows 7 PC so it possibly happens on Windows 8 and later. I'll try this on Win10 PC...

**Comment by damat** [comment]
Can't reproduce it now, seems to be self-fixed =) 
Thank you for the best extension ever made!

**Comment by piroor** [comment]
Thank you for confirmation!
