### ISSUE TITLE
[feature request] Add ability to visually mark (star/label) a tab for quicker location

### ISSUE THREAD

**Issue by donjohnson** [piroor/treestyletab#1243]
When I have a lot of tabs open and the majority have similar titles, it can be difficult to find the tab I'm looking for. 

It would be nice if there were some way to identify the tab more quickly, possibly by adding a (*) to the title, adding a color label to the tab, or some other appearance tweak.

**Comment by Keith94** [comment]
This add-on might do the trick: https://addons.mozilla.org/en-US/firefox/addon/highlight-tabs/

![178442](https://cloud.githubusercontent.com/assets/5490615/22223068/56724aaa-e16e-11e6-8fea-4ac6c4eecc66.png)

**Comment by piroor** [comment]
I won't implement this by TST, instead I recommend you to use the another addon suggested by Keith94.
