### ISSUE TITLE
[feature request] Store tab navigation history for quick cycling

### ISSUE THREAD

**Issue by donjohnson** [piroor/treestyletab#1244]
It would be nice if the last 4-5 tabs I've accessed could be stored in a list that I could alt-tab (or similar) through them, ordered by most recently used.

**Comment by piroor** [comment]
A secret feature of Firefox itself possibly help you. Go to `about:config` and set `browser.ctrlTab.previews` to `true`.

**Comment by piroor** [comment]
Anyway this won't be "fixed" by Tree Style Tab addon because it is not related to "tree".
