### ISSUE TITLE
"New tab" icon is stretched on macOS Sierra

### ISSUE THREAD

**Issue by thSoft** [piroor/treestyletab#1245]
## Short description

The "New tab" icon is stretched in all skins except Metal.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set the tab bar skin to anything but Metal.
 4. The "New tab" icon is stretched horizontally.

## Expected result

Metal skin:
<img width="245" alt="metal" src="https://cloud.githubusercontent.com/assets/118109/22289961/8ae45f1c-e2fe-11e6-855c-e78be346e7fd.png">

## Actual result

Mixed skin:
<img width="246" alt="mixed" src="https://cloud.githubusercontent.com/assets/118109/22289974/a3339592-e2fe-11e6-909f-fef669d012f1.png">

## Environment

 * Platform (OS): macOS Sierra 10.12.2
 * Version of Firefox: 50.1.0
 * Version (or revision) of Tree Style Tab: 0.18.2016111701

**Comment by talklittle** [comment]
Metal theme was fixed as a special case in #1194 

You can try a similar fix for the other themes by editing the respective CSS files.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
