### ISSUE TITLE
Can't open new tab with double-click after Firefox upgrade to 51.0

### ISSUE THREAD

**Issue by igordavid** [piroor/treestyletab#1246]
## Short description
After upgrading to Firefox 51.0 64-bit I can't open new tab with double click.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Enable TST and restart Firefox 
 4. Double-click on empty area below tabs

## Expected result
Open new tab

## Actual result
Nothing happens

## Environment

 * Platform (OS): OS MAC 10.11.6, EL Capitan
 * Version of Firefox: Firefox 51.0 64-bit
 * Version (or revision) of Tree Style Tab: 0.18.2016111701

**Comment by piroor** [comment]
I won't "fix" this by TST itself. See also #695.
