### ISSUE TITLE
[Privacy] Allow hidden tab bar to be 0 pixel wide. Current minimum is 1, easy to fingerprint TST users.

### ISSUE THREAD

**Issue by Okamoi** [piroor/treestyletab#1249]
## Short description

Window size is a widely used avenue for browser fingerprinting scripts.
`window.innerWidth`, `window.outerWidth`, `window.screen.width` give different values unless you set about:config `privacy.resistFingerprinting` to `true`. A maximized or fullscreen window in particular will easily let such a script detect that Tree Style Tabs is installed even if the user configured TST to prevent it from modifying window settings.

More precisely, if you set the left (or right) tab bar to auto hide, and set the toggler width to 0 through `extensions.treestyletab.tabbar.togglerSize`, the styling will still take 1 pixel.

It should take 0. The fix implies setting CSS borders to 0 when `extensions.treestyletab.tabbar.togglerSize` is `0`. Currently, the border remains 1 no matter what.

## Why implement

Fingerprinting protection. We can assume that people keeping tabs on top with indent don't care about it, but those who go as far as setting togglerSize to `0` could be.

Additionally, the toggler thing has been added because of plugins, who could prevent mouse events from reaching TST if they were embedded to the side of the screen. But plugins are on their way out, and disabled with `privacy.resistFingerprinting` set to `true`.

Moreover, a user who sets `togglerSize` to `0` probably knows what he has done, plugins or not, and how to fix it if ever necessary.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set `extensions.treestyletab.tabbar.togglerSize` to `0`
 4. Set `extensions.treestyletab.tabbar.autoHide.mode` to `1`
 5. Set `extensions.treestyletab.tabbar.autoHide.mode.toggle` to `1`
 6. Maximize your window so that its width takes all your screen (easier to spot the issue that way)
 7. Open scratchpad (MAJ+F4) and type: `alert(window.screen.width - window.innerWidth);`
 8. Execute the script. 

## Expected result
The alert box should display 0.

## Actual result
The alert box actually displays 1, something that really stands out for fingerprinters even though the user possibly wanted to HIDE that he had TST installed.

The cause lies in CSS files like [these](https://github.com/piroor/treestyletab/search?utf8=%E2%9C%93&q=treestyletab-tabbar-position%3D%22left%22), which set a border of 1px. Applies to left tab bar and right tab bar. Bottom and top may have similar CSS borders, I haven't tested this. All panel styles should have this, Standard, Vertigo, whatever. ([Link to a relevant line in the source](https://github.com/piroor/treestyletab/blob/bd4599e218d049f00b7d154f811d0372761a2d39/skin/classic/treestyletab/ui-base.css#L284))

## Fix suggestion

Either set the relevant CSS borders to 0 only if `extensions.treestyletab.tabbar.togglerSize` is `0`, or just remove the relevant borders altogether without conditionals.

Thanks if you can consider this issue, and THANKS for Tree Style Tabs! I really hope it can be converted to a WebExtension, both because of its features and its ability to remove UI clutter to increase real estate for content.

## Environment

 * Platform (OS): Windows 7 64-bit
 * Version of Firefox: 51.0.1 32-bit
 * Version (or revision) of Tree Style Tab: Latest (0.18.2016111701)

**Comment by piroor** [comment]
Thanks！ I think these commits should solve the fingerprinting problem. How do you think?

63f3d54a3146bf3ceba18f60e4fa99147f4aaa7e
7a492bcf5fa9a4159d4aecbe8fac7f11e63e8d82

**Comment by Okamoi** [comment]
Thanks, that was fast :)

Isn't that fix hiding the toggler even on default config, where its width is `5px` ? That indeed defeats fingerprinting but isn't the same as removing the toggler completely from the code base ? I didn't think you would go that far :)

There is one problem though, I think: setting the margin to `-togglerSize` will not fix the issue when `togglerSize <= 0`. When it's equal to 0, the margin is 0, which means the `1px` border ends up eating screen space and being fingerprintable. When it's negative the margin becomes positive, eating up screen space.

Essentially, margin should probably be a hard coded `-1px` when `togglerSize <= 0`.
