### ISSUE TITLE
Not drawing in all available space

### ISSUE THREAD

**Issue by Anntoin** [piroor/treestyletab#1251]
## Short description

On startup the firefox window is being drawn in a portion of the available space. Specifically with a multimonitor setup it looks to be the size of the smallest screen, see screenshots below. After resizing window e.g. toggle fullscreen it snaps back into place.

I think this is related to tree-style tabs as with the plugin disabled firefox uses the entire screen at startup as expected.

Seems similar to https://github.com/piroor/treestyletab/issues/1091

## Steps to reproduce

 1. Start Firefox on larger monitor window.

## Expected result
![firefox tst cropping 2017-02-17 23-42-26](https://cloud.githubusercontent.com/assets/3289027/23087292/e343be68-f56a-11e6-9418-f0882cda5d98.png)

## Actual result
![firefox tst cropping 2017-02-17 23-41-26](https://cloud.githubusercontent.com/assets/3289027/23087294/e735a7d4-f56a-11e6-9948-58990a1f0ad4.png)

## Environment

 * Platform (OS):  Linux Ubuntu 16.04 i3 window manager
 * Version of Firefox: 51.0.1
 * Version (or revision) of Tree Style Tab: 18.2016111701 & 18.2017021100a040247

**Comment by piroor** [comment]
Hmm, this doesn't happen on my Windows PC so this is possibly a Linux specific issue.

**Comment by piroor** [comment]
Hmm, I couldn’t reproduce this problem on Ubuntu 16.04LTS + Nightly 55.0a1 + TST@6a9dce125ef443e1ed96cdf611dfd5d1b5692eca ...

If you use something other addons with TST, they may affect.

**Comment by jjdelc** [comment]
I also use Ubuntu i3 and I had this happen before I used TST as well. I don't see it happening with nightly.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
