### ISSUE TITLE
when Tree Style Tab is installed, the drag link function of Easy DragtoGo++  doesn't work

### ISSUE THREAD

**Issue by OmTatSat** [piroor/treestyletab#1253]
## Short description
when Tree Style Tab is installed, the drag link function of Easy DragtoGo++  doesn't work. Please fix.
## Steps to reproduce
drag link to the right

## Expected result
new tab opened

## Actual result
nothing

## Environment

 * Platform (OS): win 7 x64
 * Version of Firefox: Cyberfox 51.0.3 browser.tabs.remote.force-enable true
 * Version (or revision) of Tree Style Tab: last

**Comment by piroor** [comment]
When a link is dropped, an error is logged in the browser console:

~~~
TypeError: this.aDragSession is null[Learn More]  easydragtogo.js:390:77
	openURL chrome://easydragtogo/content/easydragtogo.js:390:77
	onDrop chrome://easydragtogo/content/easydragtogo.js:934:14
	onLoad/< chrome://easydragtogo/content/easydragtogo.js:113:21
~~~

This seems to be a bug of the compatibility code of Easy DragtoGo++, so it should be tracked by the author.

**Comment by OmTatSat** [comment]
Nothing can do from side of Tree Style Tab?
If author of Easy DragtoGo++ will not want to fix it

**Comment by piroor** [comment]
I think TST must not touch the code, to avoid confusion. If I add a code to modify the compatibility code *in the Easy DragToGo++ addon*, it will disturb his future work. (Actually I suffered from such a "patching hell" by TST and Tab Mix Plus - they patched each other.)

**Comment by OmTatSat** [comment]
I write review https://addons.mozilla.org/ru/firefox/addon/easy-dragtogo-plus-plus/
But i don't think Author will create fix((
Because there is no single Author(

"ALL thanks go to user Konstantin
and japanese coders and users trailed from
http://latinum.seesaa.net/article/442921904.html"

patching each other - i agree this is not good, but maybe sometimes this is the only way out))

**Comment by piroor** [comment]
Then, I think that it is the good time that you migrate from an abandoned addon to another living (actively maintained) alternative ;) Basically such legacy (non WebExtensions) addons will die at Firefox 57 and the addon has no future if it is not maintained actively.

**Comment by OmTatSat** [comment]
I tried a lot of alternatives, but find worked extensions only with poor functionality(
Are you know good alternative?

**Comment by piroor** [comment]
Sorry, I don't know that. If there is no alternative  for your demand, I think you need to develop new addon for yourself - I started this project by same reason.

**Comment by OmTatSat** [comment]
Ohh, i can only change a few simplest strokes of code with help of google in worked addon, but develop new addon, i think is not possible((
Maybe you can make separate patch for Easy DragtoGo++?

**Comment by OmTatSat** [comment]
Please...

**Comment by piroor** [comment]
Please help you by yourself, my hands are already full to support my addons...

**Comment by OmTatSat** [comment]
Ok, sorry
