### ISSUE TITLE
'Restore tabs' does not work when undoing parent tab closure

### ISSUE THREAD

**Issue by TrimHG** [piroor/treestyletab#1254]
## Short description

'Restore tabs' stopped working when undoing closing of a parent tab.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set TST to close all children when a parent tab is closed
 4. Create a group of several tabs (2 is enough)
 5. Close the parent group
 6. Right click on the tab panel and select Undo Close Tab
 7. A dialog will be shown asking whether I want to restore children tabs as well
 8. Select 'Restore tabs'

## Expected result

Children tabs are restored.

## Actual result

Only parent tab is restored.
## Environment

 * Platform (OS): Windows 7 x64
 * Version of Firefox: 51.0.1 x64
 * Version (or revision) of Tree Style Tab:  0.18.2016111701

**Comment by piroor** [comment]
This is caused a change introduced by https://bugzilla.mozilla.org/show_bug.cgi?id=1288247 and the commit 162ac232db10ddaaf4db3132610d876400653ed0 fixes this for me. Thanks!
