### ISSUE TITLE
No support for Firefox containers

### ISSUE THREAD

**Issue by jjdelc** [piroor/treestyletab#1258]
## Short description

The container tab color isn't showing on vertical tabs. https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers

## Steps to reproduce

 1. Start Firefox Nightly with clean profile.
 2. Install TST.
 3. Open a tab in any specific container

## Expected result
The tab should have a color hint indicating the container it belongs to

## Actual result
Tabs does not have any indicator as if it was a "no container" tab.

## Environment

 * Platform (OS): Ubuntu 16.04
 * Version of Firefox: Nightly 55
 * Version (or revision) of Tree Style Tab: 0.1929170311...

**Comment by jjdelc** [comment]
Adding that when a new tab is opened from a container tab is does not open nested but parallel ignoring the parent relationship.

**Comment by harningt** [comment]
It appears that, at least with the new "Containers" experiment available through Mozilla's "Test Pilot" at least shows the color hint below the tab.

Regarding child tab creation when inside a container tab, this issue is still present.

# Environment

- Platform (OS): Ubuntu 16.04
- Version of Firefox: Nightly 54.0a2
- Version (or revision) of Tree Style Tab: 0.19.2017031101

**Comment by jjdelc** [comment]
I used the test pilot experiment but disabled it as it had very poor performance compared to the built in feature that's available in nightly. 

What the test pilot does though is switch the color on the tabs to be on the bottom instead of the default (on top). It looks like this behavior makes the color tabs show.

**Comment by mikaeleiman** [comment]
In FF53 I saw the context color markers as a single pixel line to the left of the tab icon (tree on right side of screen) - but I no longer see them in FF54. This is on MacOS.

**Comment by piroor** [comment]
I couldn't reproduce this anymore, with latest development build of TST http://piro.sakura.ne.jp/xul/xpi/nightly/ on Nightly 56.0a1 20170615031719.

**Comment by mikaeleiman** [comment]
Update: I see the colored lines again on FF54/MacOS. Weird, but it seems to have resolved itself :/

**Comment by BrianGilbert** [comment]
Confirm that tree style tabs is showing container colouring on tab in FF Nightly, as well as the new tab link allowing you to select which container.

**Comment by harningt** [comment]
Appears to be resolved on my side as well.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
