### ISSUE TITLE
Slow website alerts start from edge of window behind tab sidebar

### ISSUE THREAD

**Issue by jjdelc** [piroor/treestyletab#1259]
## Short description

When Firefox has one of those "Some page is making firefox slow [Wait] [Stop it]", the bar should stop from the edge of the content but it starts from the edge of the window so the sidebar is covering the first few words from the left.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Go to any slow website (sometimes Facebook for me)

## Expected result

When the site is slow, the alert should start on the left of the content next to the tab bar

## Actual result

The alert starts behind the tabbar covering the first few words,

## Environment

 * Platform (OS): Ubuntu 16.04
 * Version of Firefox: Nightly 55
 * Version (or revision) of Tree Style Tab:  0.19.20170311

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
