### ISSUE TITLE
Firefox 52: Tab icons lost after restart

### ISSUE THREAD

**Issue by sagamusix** [piroor/treestyletab#1260]
## Short description

After upgrading to Firefox 52, even with TST 0.19 2017031101, tabs show the default icon after restarting the browser. Tabs are configured to not load until they are clicked on. At that point, the correct favicon is shown. Prior to Firefox 52, I could always see the cached favicons after restarting.

## Environment

 * Platform (OS):  Windows 7
 * Version of Firefox:  Firefox 52
 * Version (or revision) of Tree Style Tab: 0.19 2017031101

**Comment by piroor** [comment]
I saw similar problem. Try this: [Latest topics &gt; Tree structure and tab icons are always lost after restart - outsider reflex](http://piro.sakura.ne.jp/latest/blosxom/mozilla/extension/treestyletab/2017-03-12_tree-structure-lost.htm#topic2017-03-12_tree-structure-lost "Latest topics &gt; Tree structure and tab icons are always lost after restart / 再起動すると必ずツリー構造やタブのアイコンが失われる - outsider reflex")

**Comment by sagamusix** [comment]
Thanks for the suggestion, now the icons are kept between restarts. I'll leave the issue open in case you decide to programmatically work around this problem, so that it is fixed for all users automatically.

**Comment by tanev** [comment]
Hi, just wanted to confirm that I'm also seeing the same issue after updating to the latest Firefox 52. Unfortunately the proposed fix have not worked for some reason. Attempting to stop the browser asks if I'm sure that I want to close all 72 tabs and they are not reopened after restart (I'd have to restore the last session).

Environment: Linux Mint 18.1 Serena
Version of Firefox: 52.0 (64-bit)
Version of Tree Style Tab: 0.19.2017031101

Please let me know if you need more information on any of the above.

Thanks!

**Comment by irvinm** [comment]
It looks like the favicons missing might be core to Firefox 52.

https://bugzilla.mozilla.org/show_bug.cgi?id=1345456

**Comment by tanev** [comment]
I believe there are two distinct bugs involved, one is the above mentioned missing favicons, however the other one possibly involves the treestyletab plugin. 

To reproduce it from a clean environment I've installed a clean Ubuntu Xenial LXC, then installed the latest available firefox (version 52.0+build2-0ubuntu0.16.04.1), then opened firefox within through ssh with X-forwarding and installed the latest treestyletab plugin:
Tree Style Tab: 0.19.2017031101

Steps to reproduce:
- open a website: e.g. https://www.linuxmint.com/start/serena/
- open one or more child tabs with scroll click/ctrl + left mouse click on one or more of the links inside - a tab tree is being created with this
- open a new tab with the "+" button or ctrl+t keyboard shortcut directly and open another website, e.g. DuckDuckGo search - [screenshot](http://pasteboard.co/LgyqOBlkk.png)
- try to move the tab between the linuxmint tab tree with ctrl+shift+up arrow - [result screenshot](http://pasteboard.co/LgAKe1H1G.png)

Result: The tab stays at the root level even within the tabs in the parent tree. Also folding the parent tree does not hide the newly added tab inside the tree - [screenshot](http://pasteboard.co/LgBwOOe10.png)

Expected: The newly added tab gets into the correct level inside the parent tree and gets hidden in case the tree is folded.

Please let me know in case you need more information on any of the above. I'll keep the LXC up in case there's some debug information to be extracted from it.

Best,
T.

**Comment by guri** [comment]
having the same problem but without the errors mentioned.

**Comment by sagamusix** [comment]
The bug I reported has been fixed, so if you have a similar bug, please open a new issue to keep things tidy.
