### ISSUE TITLE
Firefox 52: Opening a new tab does not draw it immediately

### ISSUE THREAD

**Issue by sagamusix** [piroor/treestyletab#1261]
## Short description

After upgrading to Firefox 52, even with TST 0.19 2017031101, newly opened tabs that are added at the end of the tab list are not drawn immediately. They only become visible after hovering the tab bar or otherwise modifying the bar, e.g. by opening a branch.

## Environment

 * Platform (OS):  Windows 7
 * Version of Firefox:  Firefox 52
 * Version (or revision) of Tree Style Tab: 0.19 2017031101

**Comment by piroor** [comment]
It is a known issue at Firefox 52 and fixed by Firefox 53. See also #1202.

**Comment by sagamusix** [comment]
Thanks for pointing out the duplicate. I applied the mentioned workaround there (browser.tabs.animate=false) since I do not particularly care about animations anyway, so that fixes it for me.
