### ISSUE TITLE
Incompatible with Focus Last Selected Tab

### ISSUE THREAD

**Issue by syliew** [piroor/treestyletab#1262]
neither [Focus Last Selected Tab 0.9.6.2](http://www.gozer.org/mozilla/extensions/) nor https://addons.mozilla.org/en-US/firefox/addon/fww-flst/ work with tst enabled, though both extensions work on their own.

using latest stable firefox, tst and windows 7.

**Comment by mr-rak** [comment]
Same problem.
I use https://addons.mozilla.org/en-US/firefox/addon/fww-flst/   tab flipping works сorrectly, but focus last selected tab after close tab - not work.  I tried debugging and find function for open tab in FLST, function use gBrowser.selectedTab. TST block this?
![firefox_2017-03-21_18-32-30](https://cloud.githubusercontent.com/assets/6695875/24159115/ece49a04-0e66-11e7-8cee-d2603fb420d2.jpg)

**Comment by dufferzafar** [comment]
Did any of you find a workaround or anything?

I just want a hotkey that when pressed takes me to the last tab I was on, and was surprised to see that it's not supported natively by TST - surely I can't be the only one who wants this?

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
