### ISSUE TITLE
Tab mix styles not displaying correctly

### ISSUE THREAD

**Issue by onemen** [piroor/treestyletab#1266]
TreeStyleTabs have several options to "Skin of the tab bar"

Some of which covers [Tab mix tab style](http://tabmixplus.org/support/viewtopic.php?t=3&p=display-tab)

let me know if it is possible to change to style either in TreeStyleTabs or in Tab mix to fix this issue

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
