### ISSUE TITLE
ContextualIdentityService.getIdentityFromId is not defined in Firefox 54+

### ISSUE THREAD

**Issue by pintassilgo** [piroor/treestyletab#1268]
https://github.com/piroor/treestyletab/blob/e38865a2b99e64fd3c3ceed11c1df27a92b4edba/modules/browser.js#L5222

Replaced by

`ContextualIdentityService.getPublicIdentityFromId`

So...
`let identity = ContextualIdentityService.getIdentityFromId ? ContextualIdentityService.getIdentityFromId(userContextId) : ContextualIdentityService.getPublicIdentityFromId(userContextId);`

**Comment by piroor** [comment]
Fixed by fe53b9b. Thanks!
