### ISSUE TITLE
When re-opening a closed tab, it opens as collapsed.

### ISSUE THREAD

**Issue by pbarney** [piroor/treestyletab#1269]
## Short description
When I close a tab, but change my mind and re-open it with CTRL-SHIFT-T, the tab re-opens, but is collapsed. This is new behavior after latest release.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a new sub-tab, then close it
 4. Press CTRL-Shift-T to re-open it

## Expected result
Tab should open in same state as when it was closed.

## Actual result
Tab opens in a collapsed state

## Environment

 * Platform (OS): Win 7 (64 bit) SP1
 * Version of Firefox: 52.0.1
 * Version (or revision) of Tree Style Tab: 0.19.2017031101

**Comment by Adelscott** [comment]
Experiencing same problem here

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
