### ISSUE TITLE
Undoing a closing of tab triggers the opening of a collapsed tabs group

### ISSUE THREAD

**Issue by Adelscott** [piroor/treestyletab#1270]
## Short description

When I close a tab, but change my mind and re-open it with CTRL-SHIFT-T (or Tab Mix Plus button), it triggers the opening of another tabs group that was collapsed

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a group of tabs
 4. Collapse the group of tabs
 5. Open a new tab outside of that group
 6. Close the tab
 7. Undo the closing
 8. The group of tabs opens itself

## Expected result

The collapsed group of tabs shouldn't be impacted

## Actual result

The collapsed group of tabs expands itself

## Environment

 * Platform (OS): Windows 7
 * Version of Firefox: 52.0.1
 * Version (or revision) of Tree Style Tab: 0.19.2017031101

**Comment by fissie** [comment]
Confirming, Firefox 52.0 (64bit) on Linux, same behavior. 

Somehow, it also seems to get worse when Electrolysis is involved - if Electrolysis is disabled, then reopening closed tabs will reopen groups (which cannot be collapsed again, collapse button does nothing - until browser restart, which restores the collapsed state). This is *without* tab mix plus in my case, I don't have it installed.

With Electrolysis enabled, even creating a new tab via ctrl+t or clicking links to open new tabs will pretty quickly trigger this behavior and expand all groups.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
