### ISSUE TITLE
reopen tab does not place tab in tab tree anymore

### ISSUE THREAD

**Issue by Vampire** [piroor/treestyletab#1271]
Since a recent update of Firefox, a reopened tab is not placed in the tree where it was before anymore. Before this update this worked properly. Now the tab is simply opened right-most on top-level.

**Comment by Canule** [comment]
Can confirm on two devices (win7/10), showing a part of all the tabs and all as root.
One session with 87 tabs eventually recovered partly after restarts(sub tabs grouped again) but the pinned tabs only shows 1/2 rows -> https://www2.pic-upload.de/img/32899084/wubu.png and not all tabs are listed.

**Comment by Vampire** [comment]
@Canule if I got you right, you should open a separate issue. I'm talking about closing a tab and then reopening the closed tab, e. g. with Ctrl+Shift+t, not about reopening of tabs on browser restart.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
