### ISSUE TITLE
New tabs are opened as siblings to current tab

### ISSUE THREAD

**Issue by jdobbs** [piroor/treestyletab#1272]
With version 0.19.2017031101 on Firefox 52.0.2 I noticed whenever a new tab is opened it's opened a sibling to the tab which is active. In the past new tabs (CTRL-T or even clicking on the plus at the bottom of the tab list) would open as a parent tab at the bottom of the tab list. How do I get that functionally back?

**Comment by tgy** [comment]
This issue has already been reported: https://github.com/piroor/treestyletab/issues/1264

**Comment by sumyungguy** [comment]
@tgy, this is probably not related to #1264, which is about tabs opening from other addons as child tabs. The issue reported here is tabs opening from the new tab button as sibling tabs.

@jdobbs, if you still didn't solve this, please check  TST preferences-->New Tabs-->Open new blank tab as-->an independent tab

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
