### ISSUE TITLE
Option to Bookmark a tree into a markdown file

### ISSUE THREAD

**Issue by vonHabsi** [piroor/treestyletab#1274]
## Short description
Functionality request
Add option to Bookmark Tree to a file or the clipboard

## Functionality Description
What I am looking for is the ability to create a markdown file of the tree structure that can be saved to a location, popped up in a dialog for copying, or copied onto the clipboard.

Quite simply is should be a plain markdown file that indents the lines in accord with their position tree structure, and contains the page title, url, and the page key words or a little metadata.

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
Sorry, I have no plan to implement it as a builtin feature of TST. Instead here is a simple script to export tabs as a markdown text:

~~~
var TST = gBrowser.treeStyleTab;
var markdown = TST.rootTabs.map(function toMarkDown(aTab) {
  var indent = '  ';
  var item = '* [' + aTab.label + '](' + aTab.linkedBrowser.currentURI.spec + ')\n';
  return item + TST.getChildTabs(aTab).map(toMarkDown, TST).join('').replace(/^/g, indent);
}, TST).join('');
markdown;
~~~

To run it, you need to do:

 1. Set `devtools.chrome.enabled` to `true` via `about:config`.
 2. Ctrl-Shift-J to open "Browser Console".
 3. Copy and paste the script above.
 4. Hit the Enter key.

Then you'll see Markdown text in the console. If it is too long, you'll need to click the `[...]` part of the output.

**Comment by vonHabsi** [comment]
I want to use your code with the tree walking code used in menu functions like **Reload this Tree**  to generate a nested list of the URLs. I also want to be able to add such a function to the menu.

Where in the code do I have to look if I want to implement this? I am totally new to Firefox addon development and would greatly appreciate the help.

**Comment by piroor** [comment]
Now this is possible with the addon: https://addons.mozilla.org/firefox/addon/copy-selected-tabs-to-clipboar/ The default format "Markdown (list)" generates indented list.
