### ISSUE TITLE
Middle clicking in the Synced Tabs sidebar opens as child tab

### ISSUE THREAD

**Issue by heftig** [piroor/treestyletab#1275]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set up Firefox Sync with an account that already has a device with tabs.
 4. Open up the *Synced Tabs* sidebar.
 5. Middle- (or Ctrl-) click a page in the sidebar.

## Expected result

Page opens as a new root tab.

## Actual result

Page opens as a child of the current tab.

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 54.0a2
 * Version (or revision) of Tree Style Tab: 0.19.2017031101 d1fe45cfacd700def5c727dfed85b8790de411f6

**Comment by piroor** [comment]
Fixed by 36e596b. Thanks!
