### ISSUE TITLE
In latest Firefox Nightly, opening links from Outlook emails no longer works

### ISSUE THREAD

**Issue by HighCommander4** [piroor/treestyletab#1279]
## Short description

In the latest Firefox Nightly, opening links from some websites, notably Outlook and other email clients, no longer works.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Log in to an email client like Outlook. For me, Gmail and Yahoo email are also affected.
 4. Load an email that contains a link and click on the link.

## Expected result

The target of the link is opened in a new tab.

## Actual result

A new blank tab is opened. Sometimes, it's three blank tabs.

Outlook, Gmail, and Yahoo are affected, but regular websites aren't. I think it may have to do with whether the link is configured to open in a new tab by default (true for email clients, false for regular websites).

## Environment

 * Platform (OS): Linux (Debian stable)
 * Version of Firefox: Latest Nightly
 * Version (or revision) of Tree Style Tab: 0.19.2017031101

**Comment by piroor** [comment]
Same to https://bugzilla.mozilla.org/show_bug.cgi?id=1359544 ?

**Comment by HighCommander4** [comment]
Yes, that sounds like it! 

Is there a package of Tree Style Tab available that includes the fix commit?

**Comment by Fanolian** [comment]
@piroor, would you mind updating the .xpi at http://piro.sakura.ne.jp/xul/xpi/nightly/? Thanks.

**Comment by HighCommander4** [comment]
I see there is a new nightly build up. I tried it, and I can verify the issue is fixed in it. Thanks!
