### ISSUE TITLE
FF53 new hotspot login detection bugs

### ISSUE THREAD

**Issue by Tragen** [piroor/treestyletab#1280]
![2017-05-02 23_51_34-](https://cloud.githubusercontent.com/assets/1700241/25662122/9b7ad024-3013-11e7-9ff4-1759c17b3acc.png)

Since FF53 there is a detection if you need to login to a hotspot and a new tab opens automatically.
With TST you can see the info banner is behind the tabs.

**Comment by piroor** [comment]
Thanks, I've confirmed with the code `CaptivePortalWatcher._showNotification()`. Hmm...

**Comment by piroor** [comment]
0cd0615 should fix this. Thanks!
