### ISSUE TITLE
Tree Style Tabs Not Supported on Firefox 53

### ISSUE THREAD

**Issue by hdjr** [piroor/treestyletab#1285]
## Short description
While trying to add this addon, FF 53 will not let me install it and says it is unsupported

## Steps to reproduce

 1. Start Firefox 53
 2. Navigate to Addons Manager and try to Install TST.

## Environment

 * Platform (OS): Ubuntu 16.02 LTS
 * Version of Firefox:  53
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
Latest development build works for me. http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by hdjr** [comment]
Thanks Piroor! Will this be pushed to the FF AMO anytime soon?

**Comment by piroor** [comment]
I'll release a new version after some easy bugs are fixed.

**Comment by hdjr** [comment]
Hello Piroor,

I confirmed that the dev build you sent me from http://piro.sakura.ne.jp/xul/xpi/nightly/ is indeed working. I did have to disable the require plugin signature verification from Firefox, but it did load. I will enable the signature signing verification again. Please update me when you push the update to AMO. 

P.S. When you submit to AMO, will it be available instantly or is there some delay?

Thanks!

**Comment by piroor** [comment]
It has been review and published. Check the page please. https://addons.mozilla.org/firefox/addon/tree-style-tab/

**Comment by hdjr** [comment]
You're the best! Thanks a lot! :1st_place_medal:
