### ISSUE TITLE
When # tabs open is > window height, a newly opened tab is not being displayed in the visible area (it is not scrolling to the very bottom) - this has been the case for several weeks.

### ISSUE THREAD

**Issue by torevor** [piroor/treestyletab#1286]
## Short description
When # tabs open is > window height, a newly opened tab is not being displayed in the visible area (it is not scrolling to the very bottom) - this has been the case for several weeks.

## Steps to reproduce
Open lots of tabs until exceeds ability to view all.
Open a new tab - it will be active, but will not be visible.

## Expected result
New tab will be highlighted and visible.

## Environment

 * Platform (OS):  Windows 7 x64
 * Version of Firefox:   53.03 (64 Bit)
 * Version (or revision) of Tree Style Tab:   0.19.2017031101

**Comment by piroor** [comment]
Maybe fixed by 455c8d8

**Comment by Tragen** [comment]
It's working for me now.

**Comment by torevor** [comment]
Fixed, thanks!
