### ISSUE TITLE
Feature Request: Option to disable closing tabs with middle click

### ISSUE THREAD

**Issue by sriedel** [piroor/treestyletab#1287]
I'm using a thinkpad laptop and use middle click + track point to scroll. Sometimes trying to scroll TST results in the clicked tab closing because I didn't hold the middle mouse button for long enough, closing the tab in question.

FF itself doesn't provide an option for this, and I've tried the "Enhanced Middle Click" extension to disable this behaviour, however that extension doesn't seem to work with TST. 

I realize that people may be using the middle mouse button to close tabs, which is why I ask for this to be an option (disabled by default to preserve the current behaviour).

Running FF 53.0.3, TST 0.19.2017031101 on Linux/X11.

**Comment by Rondom** [comment]
Have you tried Tab Mix Plus?

**Comment by piroor** [comment]
Sorry, it won't be implemented natively because it is not related to "tree". Instead, now I'm trying to fix compatibility issue with the addon Enhanced Middle Click...

**Comment by piroor** [comment]
I've researched the addon https://addons.mozilla.org/firefox/addon/enhanced-middle-click/ and I've realized that the addon doesn't work on the tab bar even if TST ist not installed - it is by design. You need to do middle-click on the content area.

**Comment by sriedel** [comment]
@piroor: Oh damn, looks like I misunderstood the purpose of the plugin (it was suggestion in a forum where the same issue as my original one was asked about, and I didn't look to closely). Sorry about the noise :(

@rondom: I'll have a look, thank you for the suggestion.

**Comment by lostmsu** [comment]
@piroor Tab Mix Plus is no longer available. Doesn't Tree Style Tabs handle all the mouse stuff now?

**Comment by piroor** [comment]
TST 2.x doesn't provide this "feature" by self, but it can be done by APIs. Here is a list of addons which extend TST: https://github.com/piroor/treestyletab#addons-extend-tst and one of them can do that. if no one does that, you need to implement an addon to cancel middle click notified by TST via its API: https://github.com/piroor/treestyletab/wiki/API-for-other-addons#when-a-tab-is-clicked
