### ISSUE TITLE
'Move to Group' Causes Tabs to Disappear

### ISSUE THREAD

**Issue by LazyGenius88** [piroor/treestyletab#129]
*This behavior is pretty consistent on my machine, using this version of Firefox 5.0. I have not tested on other versions or machines (See below for list of installed Extensions & Plugins)*

How to re-produce:
-----------------------------------
**Cause**:
* Highlight two or more tabs with Multiple Tab Handler.
* Right-click --> Move to Group --> New Group.

**Effect**: 
* Tabs disappear, and become hidden from view (but not actually closed/deleted)
* When you Right-click on toolbar menu --> Customize, it will disable Vertical Tabs... but still this group of tabs stay hidden
* The animation is as if you just closed the tabs
* Activate tab WILL change (i.e., if the tab you are actively viewing is included in the tabs selected for "Move to Group," your actively viewed tab will be switched to non-hidden tab upon forming of the New Group)
* The only way to select these 'hidden tabs' is with Ctrl+# or Ctrl+Tab
* Session Manager sees these hidden tabs, however it marks them with an asterisk (*) under the "Hidden" attribute column. And it also formats their tab names as a light-grey and italicized.
* If you go to close the Firefox Window that the 'hidden tabs' are placed, Firefox will include the hidden tabs in the total number of tabs it warns that you are about to close.

<h1>Firefox 5.0 - PortableApps</h3>
Released: June 21st, 2011

**Installed Extensions *AND* Plugins:**
Adblock Plus 1.3.8
Adblock Plus Pop-up Addon 0.2.7
Add-on Compatibility Reporter 0.8.5
Adobe Acrobat - Create PDF 1.1
Adobe Acrobat 10.1.0.534
avast! WebRep 20110101 [DISABLED]
CoLT 2.5.2
Default 5.0
Download Manager Tweak 0.9.5
Download Statusbar 0.9.8
Element Hiding Helper for Adblock Plus 1.1.1
Feedback 1.1.1
Firebug 1.7.3
FlashGot 1.3.0.2
Google Earth Plugin 1.0.0.1
Google Talk Plugin 2.1.6.0
Google Talk Plugin Video Accelerator 0.1.44.5
Google Update 1.2.183.39
Greasemonkey 0.9.5
HttpFox 0.8.9
Informational Tab 0.3.2011020301
iTunes Application Detector 1.0.1.1
Java Deployment Toolkit 6.0.250.6 6.0.250.6
Java(TM) Platform SE 6 U25 6.0.250.6
Menu Editor 1.2.7
Microsoft Office 2010 14.0.4730.1010
Microsoft Office 2010 14.0.4761.1000
Mozilla Archive Format 1.0.0
Multiple Tab Handler 0.6.2011051101
Nightly Tester Tools 3.1.5.1
Restartless Restart 7
Session Manager 0.7.5
Shockwave Flash 10.3.181.26
Shockwave for Director 11.5.8.612
Silverlight Plug-In 4.0.60531.0
Skipp Redirect 2.8.0009
Surfulater Integration 3.30.00 [DISABLED]
Tree Style Tab 0.12.2011060202
User Agent Switcher 0.7.3
Windows Live® Photo Gallery 14.0.8117.416

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
