### ISSUE TITLE
With Tab Mix Plus, some new tabs are opened in the wrong place.

### ISSUE THREAD

**Issue by sumyungguy** [piroor/treestyletab#1293]
## Short description
Using TMP, sometimes tabs open differently from preferences.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install Tree Style Tab.
 3. Install Tab Mix Plus.
 4. Set TST-New Tabs-Open new blank tab as - a sibling of the current tab; click new tab button.
 5. Set Open new blank tab as - the next sibling of the current tab; click new tab button.
 6. Middle click new tab button.

## Expected result
Tabs open as requested, just as when Tab Mix Plus is not installed.

## Actual result
4. When current tab is top level tab, new blank tab opens as child instead of sibling.
5. When current tab is last tab and is top level tab, new blank tab opens as child instead of sibling.
6. New blank tab opens as next sibling instead of preference set in TST.

Could be partly related to issue #1264

## Environment

 * Platform (OS): macOS 10.12.5
 * Version of Firefox: 54.0
 * Version (or revision) of Tree Style Tab: 0.19.2017061601

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
