### ISSUE TITLE
[Nighlty] Unable to open bookmark entries by mouse clicks due to Bug 1354159

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#1298]
## Short description
Since 2017-06-30 build, I cannot open bookmarks entries by left/middle clicks.
The corresponding error message in Browser Console is
 `TypeError: aView is undefined  bookmark.js:501:6`
Mozregression points to [Bug 1354159 - Add a 'Bookmarks' button to the Library panel](https://bugzilla.mozilla.org/show_bug.cgi?id=1354159).

## Steps to reproduce

 1. Start Nightly with clean profile.
 2. Install TST.
 3. Open a bookmark entry with left or middle click.

## Expected result
A new page opens.

## Actual result
Nothing happens. Browser Console shows  `TypeError: aView is undefined  bookmark.js:501:6`.
I can open a bookmark with right click -> Open (with a new tab/window/private window).

## Environment

 * Platform (OS):  Win 10 CU
 * Version of Firefox: Nightly 2017-06-30 build
 * Version (or revision) of Tree Style Tab: 0.19.2017062500a201909

**Comment by strigona** [comment]
This issue is now present in Firefox Beta 56.0b3 and is only present with TST installed.

**Comment by Guik** [comment]
How can we install the fix on non Nightly FF ?

**Comment by strigona-worksight** [comment]
When this ticket was opened, Firefox Nightly was version 56, which has since transitioned to a beta release. There is no Web Extension release of Tree Style Tabs.

#1224 appears to be the Web Extensions ticket.

**Comment by Guik** [comment]
Sorry I mean on Normal FF release v 56

**Comment by strigona-worksight** [comment]
There is no fix as far as I know.

**Comment by strigona-worksight** [comment]
For what it's worth, I didn't notice there was a commit associated to this ticket when it was closed. It's possible that the fix is not in a release yet, but I don't know for sure.

**Comment by strigona-worksight** [comment]
Fix was July 12, last release was June 15. I'd just wait it out - you can still open bookmarks by Right-Clicking them.
