### ISSUE TITLE
tst1.4.9 Print preview tab not dissapearing on close tab without closing print preview first

### ISSUE THREAD

**Issue by Canule** [piroor/treestyletab#1299]
With print page preview open, when closing that tab without closing the preview first, there remains a leftover of that tab(disappears after restart FF), 
![tab](https://www2.pic-upload.de/img/33471422/bug.jpg)
## Steps to reproduce

 1. Open new tab(doesn't matter at what position in tree)
 2. Hit config»print page (tree style stays visible next to preview, the print preview gets added as last tab)
 3. Close the tab you print previewing[x] without closing print preview
 4. The print preview tab without text label stays behind(but in some way attached to the page you want to print)
 5. restart to recover(get rid of the print preview tab)

## Expected result
Print preview underneath the tab to print.
Remove preview tab on close[x]

## Actual result
Print preview at bottom of tree / wont dissapear.
You may overwrite with a new tab, but you wont be able to close[x] it (tab object unlinked?)

## Environment

 * Platform (OS): win10 
 * Version of Firefox: 54.0.1
 * Version (or revision) of Tree Style Tab: 1.4.9

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
