### ISSUE TITLE
Where is the sessionstore data stored?

### ISSUE THREAD

**Issue by andyalford** [piroor/treestyletab#1302]
Hi guys, I love this addon to Firefox.

I changed computer, copied across AppData from old computer to new computer.
Reinstall Firefox and all the same settings and addons are there
But I have lost my (very long) list of tabs
I've tried copying the Roaming / Local Mozilla directories again with overwrite, but still nothing in the tree

Please can you tell me which file now stores the tree, and I can manually compare dates and copy over.  
Thanks!

**Comment by piroor** [comment]
You should migrate one file and folder: "sessionstore-backups" and "sessionstore.js".
