### ISSUE TITLE
Unsupported for firefox 47.0.2

### ISSUE THREAD

**Issue by gtmsingh** [piroor/treestyletab#1303]
## Short description
Support for Firefox 47 is not available

## Steps to reproduce
Go to [this](https://addons.mozilla.org/en-US/firefox/search/?q=tree+style+tab&appver=47.0.2) link, to find out that it is not supported

## Expected result
Ideally on hovering over the extension it should have green colored ***Add to Firefox*** instead of grayed out ***Add to Firefox***

## Actual result
It shows grayed out ***Add to Firefox***

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 47.0.2
 * Version (or revision) of Tree Style Tab: 0.19.2017061601

**Comment by MonkAlex** [comment]
What about old version of TST?

https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/versions/?page=1#version-0.18.2016111701

**Comment by gtmsingh** [comment]
Thanks, that worked!
