### ISSUE TITLE
FirefoxNightly 20170804100354 seems to break TST completely

### ISSUE THREAD

**Issue by DimitryAndric** [piroor/treestyletab#1304]
## Short description
After updating to FirefoxNightly 57.0a1 20170804100354, TST 0.19.2017071400a112358 does not seem to be functional anymore. No tab tree is displayed, and no sidebar is visible at all.

## Steps to reproduce
1. Install FirefoxNightly from https://ftp.mozilla.org/pub/firefox/nightly/2017/08/2017-08-04-10-03-54-mozilla-central/
2. Start FirefoxNightly with clean profile.
3. Install TST 0.19.2017071400a112358 from http://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab.xpi
4. Restart FirefoxNightly.
5. Observe no sidebar, no tab tree, and no tabs at all, even.

## Expected result
Visible tab tree, working tabs.

## Actual result
No tab tree, no sidebar.

## Environment
 * Platform (OS): macOS 10.12.6
 * Version of Firefox: 57.0a1 20170804100354
 * Version (or revision) of Tree Style Tab: 0.19.2017071400a112358

**Comment by TheSweetLily** [comment]
Guessing it's related to this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1347507 / https://www.reddit.com/r/firefox/comments/6qdm1q/nightly_57_is_coming_nightly_57_is_coming/dkxb7yc/

So Tree Style Tab is essentially dead now if you're on Nightly and want to stay updated. :/

**Comment by theres-waldo** [comment]
Nightly can still load non-WebExtension addons (and will be able to for the foreseeable future), so it should in principle be possible to get it working again.

**Comment by piroor** [comment]
The broken appearance is triggered by removing of legacy "mTabContainer" property. By recent commits I've updated my codes for the change.

**Comment by lizzard** [comment]
Thank you so much, the latest version from http://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab.xpi now works in Firefox 57 nightly!  I'm so happy!

**Comment by mimoo** [comment]
Thanks for posting this!

**Comment by hlovdal** [comment]
I can confirm that nightly 20170804100354 together with the addon from addons.mozilla.org shows no tab bar at all, but the piro.sakura.ne.jp version works fine. Thank you for the update.

**Comment by jryans** [comment]
Thanks for keeping this add-on functional even in 57. I don't know how to use a browser without TST anymore, and WebExt APIs aren't quite ready in this area yet. 😅

**Comment by DimitryAndric** [comment]
Thanks @piroor, with 0.19.2017080500a005738 this issue is solved.

**Comment by vonHabsi** [comment]
Can this issue be pinned and kept open for a while, or a notice place to draw peoples attention to it.
Users are bound enquire regularly as they start switching to Nightly 57, or perhaps a notice about it should be placed on the home page.

**Comment by louiz** [comment]
It looks like it’s broken again, with today’s nightly (57.0a1 (2017-08-08)), even with @lizzard version (which was working fine yesterday).

**Comment by ralesk** [comment]
Tonight's one (09-Aug-2017 22:10) works again.
