### ISSUE TITLE
No option to make Tree-Style Tabs use all vertical space

### ISSUE THREAD

**Issue by soc** [piroor/treestyletab#1305]
## Short description
_(This is more of a feature request, I apologize if that's not the right venue for it.)_
It should be possible to make tree-style tabs take all the vertical space.
Currently the extension can take only the vertical space under the location bar, which consumes the whole width of the window.

Here is an example of Tab Center using all the vertical space:
https://testpilot.firefox.com/static/images/experiments/tab-center/details/tab-center-1.ceef2f45.jpg

(Ignore the extra "fluff" of the "new tab" and search bar elements, I just like to have tabs there.)

This is beneficial for two reasons:
- Less confusing hierarchy of UI elements: The location bar should hierarchically be part of the currently active tab, not the other way around. (It's the same reason why Firefox changed from having the tabs underneath the location bar to having tabs above the location bar.)
- Slightly more efficient use of screen space.

## Desired result
Tree-style tabs can take all the vertical space:
http://imgur.com/a/cWEsE

## Actual result
Tree-style tabs live under the location bar:
http://imgur.com/a/OemGy

**Comment by piroor** [comment]
I'm very sorry but I won't implement this change by two reasons:

 * The largest reason: it is *impossible* on a regular addon based on WebExtensions API compatible to Firefox 57. Like as [Tab Center Redux](https://addons.mozilla.org/en-us/firefox/addon/tab-center-redux/), we must use "sidebar" API on Firefox 57 but the API doesn't provide such appearance. In WebExtensions world, "the API doesn't provide the feature" means "no addon can do it".
 * A minor reason: I believe that the top-left corner of the window should be handled by the most frequently used toolbar button: "Go Back". If I expand the tab bar to covering the top-left corner, people will be annoyed by hard-to-be-clicked "Back" button.

**Comment by soc** [comment]
Thanks @piroor for the detailed explanation, not the answer I hoped to hear, but I really appreciate how much effort you are putting into this extension and I'm very grateful for that.

Responding to your minor reason (not that it matters, but I felt my explanation wasn't clear enough): I was only asking for an option to adjust this, not doing this by default for all users.
I use mouse gestures, so the most frequently used toolbar button gets zero usage from me and I think I'm not the only one. The back button is only still there because it is built into the location bar and I can't get rid of it.

Nevertheless, thanks again!
