### ISSUE TITLE
Children and Tree menu options don't display in TST 0.19.2017080500a005738

### ISSUE THREAD

**Issue by vonHabsi** [piroor/treestyletab#1308]
## Short description
Tree and child related menu options don't appear anymore
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a tab and add a few child tabs
 4.  Open TST preferences and in the Menu tab ensure that items like `Reload this Tree`, `Reload Children`, `Close This Tree`, `Close Children`, `Bookmark` this Tree etc are checked
  5. Switch back the tabs and right click on a tab the menu items for the options mentioned above and similar ones are not present

## Expected result
menu items for the options mentioned above and similar ones should be displayed.

## Actual result
menu items for the options mentioned above and similar ones are not present
In Firefox 55 using TST 0.19.2017061601 from AMO they show up OK

## Environment

 * Platform (OS): Linux
 * Version of Firefox: Firefox 57.0a1 - 20170803100354
 * Version (or revision) of Tree Style Tab: 0.19.2017080500a005738

**Comment by thomasklash** [comment]
Hey there,
I compiled a working version here
https://github.com/thomasklash/treestyletab/releases/tag/0.19.201708101

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
