### ISSUE TITLE
FirefoxNightly 20170808114032 breaks TST again (differently from #1304)

### ISSUE THREAD

**Issue by DimitryAndric** [piroor/treestyletab#1309]
## Short description
After updating to FirefoxNightly 57.0a1 20170808114032, TST 0.19.2017080500a005738 does not seem to be functional anymore. No tab tree is displayed, and no sidebar is visible at all. Regular tabs only appear at the top of the window.

## Steps to reproduce
1. Install FirefoxNightly from http://ftp.mozilla.org/pub/firefox/nightly/2017/08/2017-08-08-11-40-32-mozilla-central/
2. Start FirefoxNightly with clean profile.
3. Install TST 0.19.2017080500a005738 from http://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab.xpi
4. Restart FirefoxNightly.
5. Observe no sidebar, no tab tree, but regular tabs at the top of the window.

## Expected result
Visible tab tree, working tabs.

## Actual result
No tab tree, no sidebar.

## Environment
 * Platform (OS): macOS 10.12.6
 * Version of Firefox: 57.0a1 20170808114032
 * Version (or revision) of Tree Style Tab: 0.19.2017080500a005738

**Comment by Tragen** [comment]
FF57 doesn't allow normal addons anymore. Only webextension addons are allowed and TST isn't a webextension. I don't know if it can be done or will be done.

**Comment by TheSweetLily** [comment]
Legacy addons are allowed, but the underlying legacy code is being removed, so addons that depend on removed legacy code stop working.

**Comment by ralesk** [comment]
Tonight's TST nightly fixes it again (0.19.2017080900a220959).

**Comment by BrianGilbert** [comment]
You also need to update to the latest nightly build for it to work.

**Comment by thomasklash** [comment]
Hey guys, 

I compiled the latest TST on the latest Firefox, it works

https://github.com/thomasklash/treestyletab/releases/tag/0.19.201708101

**Comment by TheSweetLily** [comment]
New mail from Firefox dev mailing list as a heads-up:

> "After lots of recent discussion, it is finally happening.  The patch to flip the default setting to disallow legacy extensions is in autoland at the moment and, barring some snafu, should be in tomorrow's Nightly builds.  This is a bit anti-climactic since a few other changes that have already landed that broke a bunch of existing extensions.
> 
> Also this has been discussed in a few other threads but repeating here for folks that may have missed it: there is a preference that Nightly users can flip to re-enable loading of legacy extensions in the addons manager (of course this setting won't magically make extensions that rely on the sdk or any changed internal interfaces work).  We will continue to honor this preference in Nightly builds and in unbranded builds, but when 57 (and later versions) go to beta and eventually to release, that preference will be ignored.  If you're familiar with addon signing and the circumstances in which we allow it to be disabled, legacy extensions are handled in the same way.
> 
> If you notice any problems or have questions, you can contact me directly, use the dev-addons mailing list, or drop into #webextensions on IRC.
> 
> :highfive:s all around!
> 
> -Andrew"

**Comment by DimitryAndric** [comment]
Yeah, so much for the useful legacy extensions I still want to use. In any case, let's close this one.
