### ISSUE TITLE
Tab focus became very annoying

### ISSUE THREAD

**Issue by idl0r** [piroor/treestyletab#1310]
Hi,

since either a Firefox or a TST Update, the tab focus became really annoying to me.

## Short description

When a tab reloads or when there is any action with it, the scrollbar/slider moves up, trying to focus that tab. The actual tab will not be changed, just the scrollbar position / tab list.

Steps to reproduce

## Steps to reproduce

 1. Start Firefox with clean profile
 2. Install TST and restart
 3. Open at least that many tabs, so that a scrollbar appears, I'd suggest to open a few more to make it better reproducible
 4. Scroll down to the bottom of the list
5. Select a tab somewhere in the middle and open google or any other side (now it should already try to focus on that tab an move up)
6. Select the bottom tab
7. Right click on the google tab and hit reload (it might try to focus it again)

## Expected result
The focus/scrollbar should not be changed, not even when I select a tab or it should be a toggle option to allow focusing a selected tab

## Actual result
The focus on a tab with any kind of action will be taken by moving the scrollbar, if a tab reloads, if I reload a tab (sometimes), when FF does some background action it may also happen to kinda switch focus (just moving the scrollbar / tab list)

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 55.0, 54.0.1, 52.0.2
 * Version (or revision) of Tree Style Tab: latest

**Comment by mathearts** [comment]
Same issue on 57.0a1, latest version of TST.

**Comment by idl0r** [comment]
Working fine in 2.x.
