### ISSUE TITLE
tree view frame overlaps on main firefox frame

### ISSUE THREAD

**Issue by jreybert** [piroor/treestyletab#1312]
## Short description
Since few weeks, I get the following behavior:
![treeview](https://user-images.githubusercontent.com/533068/29206942-6c6f6d16-7e84-11e7-815d-1d65c93b29e6.png)

It is quite random. Sometimes, when I close a tab, things come back to normal, then I scroll to another tab, and issue comes back.

Is it a known issue? I can try with a clean firefox setup if needed.

## Steps to reproduce

Don't know, random issue.

## Environment

 * Platform (OS):  Linux Centos 7.3
 * Version of Firefox: 56 (waas the same with 55)
 * Version (or revision) of Tree Style Tab: 0.19.2017061601

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
