### ISSUE TITLE
Ability to group container specific tabs togther?

### ISSUE THREAD

**Issue by BrianGilbert** [piroor/treestyletab#1313]
## Short description
Wondering if it would be possible to add a way for container tabs to be grouped together, ideally this would be a tabbed interface that separated container tabs by their container altogether, though I'm not sure how well that would scale if a user had lots of containers. 

If I use the create tab + at the bottom of my tab list it should create tab in the current container on fast click with a click hold allowing you to create in any containers tab list.

Not sure if this is out of scope but it would be great to see what others think about the idea, more than happy to create some mockups if the suggestion is seen favorably.

**Comment by piroor** [comment]
Managing of tabs based on containers is out of purpose of Tree Style Tab. For your information, Firefox Multi-Account Container has a command to sort tabs with containers (but sadly the feature is not compatible with TST - tree structure is broken after tabs are sorted. I created a [pull request](https://github.com/mozilla/multi-account-containers/pull/1377) to improve its compatibility with TST.)

By the way, TST already has some features for containers:

* An option to inherit the container of the current tab when a new blank tab is opened.
* A context menu command to create a new group from multilselected tabs via Ctrl/Shift-click.
