### ISSUE TITLE
Nightly 57: Icons in main toolbar look squished when TST is collapsed

### ISSUE THREAD

**Issue by jryans** [piroor/treestyletab#1316]
## Short description

If you collapse the TST tab bar on the side and refocus the window, the toolbar icons are squished. This was discussed in https://bugzilla.mozilla.org/show_bug.cgi?id=1383879#c47, but the fix landed in that bug doesn't appear to help the TST case.

I would guess a similar `position: relative` might be needed when TST collapses `TabsToolbar`.

The problem may be specific to macOS. In the bug above, [comment 53](https://bugzilla.mozilla.org/show_bug.cgi?id=1383879#c53) states that platform specific CSS is used.

## Steps to reproduce

1. Start Firefox with clean profile.
2. Install TST.
3. Set TST to appear on the left.
4. Collapse the TST tab bar.
5. Switch away to a different window.
6. Refocus the window with collapsed tab bar.

## Expected result

Icons in the main toolbar shouldn't get squished.

## Actual result

<img width="1290" alt="2017-08-21 at 12 08" src="https://user-images.githubusercontent.com/279572/29530465-84bbbc5c-8669-11e7-8db1-ebd6403b1066.png">

## Environment

 * Platform (OS): macOS 10.12.6
 * Version of Firefox: Firefox 57 (2017-08-21)
 * Version (or revision) of Tree Style Tab: 0.19.2017080900a220959

**Comment by piroor** [comment]
WebExtensions version for Fx57 and later is now in progress. Please see https://github.com/piroor/treestyletab/issues/1224#issuecomment-326467198 and https://github.com/piroor/treestyletab/issues/1224#issuecomment-326469215.
