### ISSUE TITLE
Tab title overlaps tab icon

### ISSUE THREAD

**Issue by theres-waldo** [piroor/treestyletab#1319]
## Short description

For some tabs, the tab title overlaps the tab icon.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a tab and load a page that doesn't have its own icon, like a file:// URL.

## Expected result

If an icon is present, the tab title does not overlap it.

## Actual result

The default icon (a grey globe of some sort, it's hard to make out) is drawn, but the beginning of the tab title overlaps it, as illustrated in this screenshot.

![tst-icon-overlap](https://user-images.githubusercontent.com/6721837/29630255-8c0eb6de-8809-11e7-8b20-d7d7e51b79ef.png)

The Firefox change that likely triggered this is that in the default tab bar, this default grey icon is no longer shown for tabs that don't have their own icon. For such tabs, there is no icon at all.

## Environment

 * Platform (OS): Debian Jessie
 * Version of Firefox: Today's nightly (2017-08-23)
 * Version (or revision) of Tree Style Tab: 0.19.2017081600a122011

**Comment by BrianGilbert** [comment]
not a problem with TST nightly, so fair to say it's resolved in the next stable release of TST.

**Comment by DimitryAndric** [comment]
No, I also have this with TST Nightly 0.19.2017082500a124310 on Firefox Nightly 57.0a1 20170824100243, for example:
![overlap](https://user-images.githubusercontent.com/9060368/29705800-e8bb26a2-897f-11e7-8163-13a25e6f8d5b.png)
In this screenshot, the first and third tabs are 'normal', the second is from a mailing list webserver, which does not have a favicon.

**Comment by theres-waldo** [comment]
For me, this issue is gone in the latest Firefox Nightly.

**Comment by DimitryAndric** [comment]
Indeed, using TST Nightly 0.19.2017082700a202100 on Firefox Nightly 57.0a1 20170827100428, the overlap is gone.  No idea when that got fixed, though.
