### ISSUE TITLE
Close buttons disappearing when scroll bar appears

### ISSUE THREAD

**Issue by acertain** [piroor/treestyletab#1320]
## Short description
Close buttons on unfocused tabs disappear when scroll bar appears. Regression from FF 54 to FF 55.

## Steps to reproduce

 1. Start Firefox v55 with clean profile.
 2. Install TST.
 3. Open a few tabs
 4. Make the window vertically smaller so that all the tabs don't fit.

## Expected result
The close buttons on all the tabs continue to show.

## Actual result
The close buttons on all tabs except the focused one disappear.

## Environment

 * Platform (OS): Windows 10 Version 1703
 * Version of Firefox: On FF 54.0.1, it works as expected. On FF 55.0.x it does not.
 * Version (or revision) of Tree Style Tab: Both release (0.19.2017061601) and nightly

**Comment by acertain** [comment]
What does it mean that you marked it "Legacy?" Does it mean that there's no way to fix it with the new FF APIs?

**Comment by piroor** [comment]
The tag means that this problem happens only on legacy version 0.19.x for Fx56 or olders, and it may not happen on renewed version 2.x for Fx57 and later. To concentrate my resource to develop 2.x, bugs on legacy versions may stay there except fatal problems.

**Comment by acertain** [comment]
OK. Thanks.

**Comment by mike2003** [comment]
I have same problem/ How fit it???

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
