### ISSUE TITLE
FirefoxNightly 20170831100258 breaks TST again (different from #1304 and and #1309)

### ISSUE THREAD

**Issue by DimitryAndric** [piroor/treestyletab#1321]
## Short description
After updating to FirefoxNightly 57.0a1 20170831100258, TST 0.19.2017083100a200605 has again stopped functioning completely, in the same fashion as #1304 and #1309. No tab tree is displayed, and no sidebar is visible at all. Regular tabs only appear at the top of the window.

## Steps to reproduce
1. Install FirefoxNightly from http://ftp.mozilla.org/pub/firefox/nightly/2017/08/2017-08-31-10-02-58-mozilla-central/
2. Start FirefoxNightly with clean profile.
3. Install TST 0.19.2017083100a200605 from http://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab.xpi
4. Restart FirefoxNightly.
5. Observe no sidebar, no tab tree, but regular tabs at the top of the window.

## Expected result
Visible tab tree, working tabs.

## Actual result
No tab tree, no sidebar.

## Environment
 * Platform (OS): macOS 10.12.6
 * Version of Firefox: 57.0a1 20170831100258
 * Version (or revision) of Tree Style Tab: 0.19.2017083100a200605

Btw @piroor, if you are getting annoyed by these repeating bug reports, please tell me, and I will stop submitting them. :)

**Comment by aspera7** [comment]
Confirming not working on latest nightly + TST, bookmarks broken as well
Platform: Win 10

**Comment by BrianGilbert** [comment]
Another confirmation, OSX

**Comment by post-temporal** [comment]
Confirm on win 7x64 
Also the same using TST nightly 1st Sept

**Comment by piroor** [comment]
WebExtensions version for Fx57 and later is now in progress. Please see https://github.com/piroor/treestyletab/issues/1224#issuecomment-326467198 and https://github.com/piroor/treestyletab/issues/1224#issuecomment-326469215.
