### ISSUE TITLE
[Nighlty] Unable to open bookmark entries by mouse clicks due to Bug 1394556 (differ from #1298)

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#1322]
## Short description
It is a new issue introduced on 2017-08-31 build and it is slightly different from #1298.
This time the error message shown in Browser Console is `TypeError: window.gBrowser.treeStyleTab is undefined   bookmark.js:505:3`.
Mozregression points to [Bug 1394556 - Compile JSM/component scripts in strict mode by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1394556)
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST (which is not working anyway #1321)
 3. Open a bookmark entry with left or middle click.

## Expected result
A new page opens.

## Environment

    Platform (OS): Win 10 CU
    Version of Firefox: Nightly 2017-08-31 build (Build ID: 20170831100258)
    Version (or revision) of Tree Style Tab: 0.19.2017083100a200605

**Comment by piroor** [comment]
WebExtensions version for Fx57 and later is now in progress. Please see https://github.com/piroor/treestyletab/issues/1224#issuecomment-326467198 and https://github.com/piroor/treestyletab/issues/1224#issuecomment-326469215.
