### ISSUE TITLE
Photon-friendry icon

### ISSUE THREAD

**Issue by piroor** [piroor/treestyletab#1326]
Currently there is only a screenshot-based icon. It should be replaced to another one which is designed to match to the Photon's template.
http://design.firefox.com/photon/welcome.html

アイコンを、白黒のシンプルな物で用意する。

**Comment by asamuzaK** [comment]
2つ方法があります。

アイコンをSVGで作って、色は`fill="context-fill"`にしておく。
（私が採用しているのはこの方法です）
ただし、ユーザーがabout:configで`svg.context-properties.content.enabled`を有効化する必要があります。
ref [1377302 - Support fill=&quot;context-fill&quot; for WebExtension icons](https://bugzilla.mozilla.org/show_bug.cgi?id=1377302 "1377302 - Support fill=&quot;context-fill&quot; for WebExtension icons")

もう1つは、manifest.jsonでダークテーマ用のアイコンを指定する。
ただし、これはまだドキュメント化されていませんし（私は確認できていない）、いったんバックアウトされかけた経緯があるので先行き不透明です。
ref [1329242 - Ability to specify a different icon for browserActions in dark themes.](https://bugzilla.mozilla.org/show_bug.cgi?id=1329242 "1329242 - Ability to specify a different icon for browserActions in dark themes.")

**Comment by piroor** [comment]
なるほど、この設定を有効にするようにという説明があったのはそういう理由だったのですね。
そこまで考えだすと泥沼にはまりそうなので、浮いてるけど当面はこのままでいいかなという気がしてきました……

**Comment by piroor** [comment]
とりあえず24ピクセル以下の物はそれらしい物を作って入れてみました。
theme_iconsもバリデーションエラーが出ない程度には正しい書き方をしているつもりですが、何が悪いのか実際の表示には反映されていないという状況です。

**Comment by piroor** [comment]
Changes to introduce theme_icons are backed out for now, because it blocks initialization of TST after install or startup.

**Comment by asamuzaK** [comment]
参考まで

management API で適用されているテーマを抽出して、テーマと対になるアイコンを指定（path）し
`browserAction.setIcon({path});`
とすれば、ツールバーのアイコンを動的に変更することは可能です

https://github.com/asamuzaK/sidebarTabs/blob/master/src/js/sidebar.js#L322
https://github.com/asamuzaK/sidebarTabs/blob/master/src/js/sidebar.js#L383
https://github.com/asamuzaK/sidebarTabs/blob/master/src/js/sidebar.js#L403
https://github.com/asamuzaK/sidebarTabs/blob/master/src/js/sidebar.js#L2388
この例では、テーマに合わせてサイドバーの適用CSSを変更しています

ただし、今後、theme API が整って WebExtensions なテーマが増えてきたら、別途対応が必要になるかもしれません
個人的には
`fill: context-fill`
がその解決策だと思っていますが、デフォルトで有効化されるかは現時点では未知数

**Comment by piroor** [comment]
こういうのは宣言的にできるようにしておかないと、些細なことのために要求するパーミッションを増やさざるを得ず、パーミッション確認の形骸化を加速する、ということの好例みたいな例ですね……
