### ISSUE TITLE
[Feature request] Create dummy grouping tabs instead of closed parent tabs and entitle them as these closed parent tabs

### ISSUE THREAD

**Issue by EightAitches** [piroor/treestyletab#133]
I'd like to propose adding an option letting TST to replace parent tabs with dummy grouping tabs in such a way, that they will be having closed parents' tabs titles, so the multi-levelling in tab tree won't be broken and mixed up together after closing some done/read parent tabs. (BTW, now it's possible to create grouping tabs and entitling them manually.)

This feature is exactly like "When a parent tab is closed" --> "Promote the first child tab as the new parent" feature, but instead of promotion of child tabs to parent levels there will be created dummy grouping tabs (which is more logical, intuitive and useful IMO).

I've drawn a mockup of new options' approximate placement in preferences window, but wordings may be changed because I'm obviously not a native English speaker :) Here: http://img695.imageshack.us/img695/2694/treestyletabgrouping.png

*UPD*

In addition, I've illustrated the logic of some little more advanced grouping tabs handling, simply put, if a grouping tab has no siblings, then it is closed: http://img13.imageshack.us/img13/5757/advancedgroupingtabshan.png

**Comment by piroor** [comment]
Implemented by the commit b4f153d.
