### ISSUE TITLE
Provide context menu on tabs and tree items

### ISSUE THREAD

**Issue by piroor** [piroor/treestyletab#1333]
See also: [1280347 - Add ability to provide custom HTML elements working as alias of existing Firefox UI items, especially tabs](https://bugzilla.mozilla.org/show_bug.cgi?id=1280347 "1280347 - Add ability to provide custom HTML elements working as alias of existing Firefox UI items, especially tabs")

I have no plan to implement fully-HTML-based custom menu system inside the sidebar area.

**Comment by piroor** [comment]
> I have no plan to implement fully-HTML-based custom menu system inside the sidebar area.

The reason:

As I told at https://bugzilla.mozilla.org/show_bug.cgi?id=1280347 I don't want to include any "context menu" implementation (not "context menu item"!) in my addon, because it introduces new hell - I'll have to struggle to synchronize my own menu to Firefox's tab context menu for new features, removed features, and so on. Moreover, it won't help us from incompatibility of multiple addons - some addon will adds context menu items for Firefox's tab context menu, but it will ignore TST's menu even if TST provides any API to insert custom context menu items from other addons.

**Comment by asamuzaK** [comment]
See also [1376251 - Allow sidebar extensions access to native tab context menu](https://bugzilla.mozilla.org/show_bug.cgi?id=1376251 "1376251 - Allow sidebar extensions access to native tab context menu")

**Comment by piroor** [comment]
By recent commits, now context menu items for tree are available on tabs and pages. They are not available on the sidebar. I'm still waiting that something solution is landed...

**Comment by mathearts** [comment]
Tab Center Redux implements basic custom context menu, you could check the code here: https://github.com/eoger/tabcenter-redux 

But I respect your choice not to deal with custom menus.

**Comment by piroor** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1376251 and https://bugzilla.mozilla.org/show_bug.cgi?id=1396031 are now marked as "wontfix" for Firefox 57. I must give up to wait for those bugs to be fixed...

**Comment by piroor** [comment]
Reluctantly done.
