### ISSUE TITLE
Support container tabs

### ISSUE THREAD

**Issue by piroor** [piroor/treestyletab#1334]
I need WebExtensions API to do that.

コンテナタブ対応は可能か？ APIはあるのか？

**Comment by asamuzaK** [comment]
ref [contextualIdentities - Mozilla | MDN](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextualIdentities "contextualIdentities - Mozilla | MDN")

**Comment by piroor** [comment]
Thanks! The document https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab said that `browser.tabs.Tab.cookieStoreId` will wok for the purpose that it seems not implemented yet on Nightly 57...

**Comment by asamuzaK** [comment]
It is already implemented. The document has not been updated.

**Comment by asamuzaK** [comment]
Ah, need to set `privacy.userContext.enabled` to true in about:config.

**Comment by piroor** [comment]
https://github.com/piroor/treestyletab/issues/1224#issuecomment-326531600

> You can also use the cookieStoreId property on the Tab object: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab
> 
> Example usage of this API: https://github.com/jonathanKingston/sea-containers

**Comment by piroor** [comment]
Done by recent commits. Thank you for advises!
