### ISSUE TITLE
Provide API to insert something like thumbnails

### ISSUE THREAD

**Issue by piroor** [piroor/treestyletab#1338]

**Comment by piroor** [comment]
See also:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/sendMessage
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onMessageExternal

**Comment by piroor** [comment]
Currently a container element `li.tab > span.extra-items-container.behind` is there. Other addons should insert elements inside it via APIs.

**Comment by irvinm** [comment]
@piroor please close this.

**Comment by piroor** [comment]
The API is still not implemented, but I lost the motivation to implement that for myself to migrate the addon Informational Tab. Reasons:

* "Highlight unread tabs" feature is now available with custom CSS on TST.
* "Progress bar on tabs" feature is still impossible to be implemented with WebExtensions API.
* "Thumbnail on tabs" feature is not attractive for me anymore.

So, I close this for now. When someone requests me to add such an API, I'll retry that.
