### ISSUE TITLE
Toolbar button to show TST sidebar directly (is it possible?)

### ISSUE THREAD

**Issue by piroor** [piroor/treestyletab#1341]
ツールバーに「ツリー型タブを開く」ボタンを置き、一発でサイドバーを開けるようにしたい。
やっぱり無いと不便。

**Comment by yfdyh000** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1341126
https://hg.mozilla.org/mozilla-central/rev/cc12e0c71046#l8.28

**Comment by piroor** [comment]
Thanks!

**Comment by piroor** [comment]
Done by b3b90119b3b183dc4196b0ddcd72e8e9d7139fee
