### ISSUE TITLE
The tab tree breaks down

### ISSUE THREAD

**Issue by Siorik** [piroor/treestyletab#1346]
## Short description
The tab tree breaks down when you just changing active tab.
Some parts of tree are open, some part of tree are separate on 2 different trees, grouped parts of tree are become work in a wrong way (plus on one group opens other part of tree or second tree)

I don't want to fully clean of my FF profile, I just want to reset windows order tree or to reset settings of addon. How to do that? Where I can find file with settings of a tree or file with tree structure? 
I want to delete or edit it (if it's possible) and then try to re-make windows order. Maybe after resetting everything will be fine.

I have FF 55.0.3 32 bit and Addon version 0.19.2017090201

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
