### ISSUE TITLE
Tabs structure lost on manual session restore on TST 2.0a

### ISSUE THREAD

**Issue by kulmegil** [piroor/treestyletab#1347]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. In Firefox options, For "When Firefox starts" select "Show your home page" 
 4. Create some tabs tree
 5. Restart Firefox
 6. Select "Restore Previous Session" button on start page (about:home)

## Expected result

Structure for restored tabs preserved.

## Actual result

Structure is lost. All restored tabs are flattened into a single branch.
The bug is reproducible as long as tabs are not restored imminently on startup.

## Environment

 * Platform (OS):  Windows 7 64-bit
 * Version of Firefox:   57.0a1 (2017-09-04) (64-bit)
 * Version (or revision) of Tree Style Tab:  2.0a (2017-09-05)

**Comment by piroor** [comment]
This seems to be fixed by recent commits.
