### ISSUE TITLE
Webextensions: hide horizontal tabs in top of window?

### ISSUE THREAD

**Issue by BrianGilbert** [piroor/treestyletab#1349]
Not sure if you are waiting on an API to do this, but it is acheivable by adding the following in userChrome.css, wondering if it would be possibly to ad a setting that switched this on/off now?

```
#TabsToolbar {
    visibility: collapse;
}
```

**Comment by piroor** [comment]
It is discussed at https://bugzilla.mozilla.org/show_bug.cgi?id=1332447

**Comment by PlugaruT** [comment]
that css is not working in firefox dev on linux.

**Comment by nh2** [comment]
> that css is not working in firefox dev on linux.

For me it works on Linux in FF Nightly 57.0a1 (2017-09-18) in [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css).

**Comment by rubenvarela** [comment]
Will test nightly in a bit. 

Currently 57.0b3 on macOS 10.12, it's not working.

**Comment by collinbarrett** [comment]
The CSS works for me on Win 10 Firefox Developer Edition 57.03b.

**Comment by rubenvarela** [comment]
Thank you.
I'll test in a new profile. I wonder if there's something weird on mine then.

**Comment by jpdeplaix** [comment]
```css
#TabsToolbar {
    visibility: collapse !important;
}   
```
is also working for me on Linux with FF 57.0b9.

**Comment by mgsloan** [comment]
Putting the bits together, here's what worked for me in firefox built from recent master:

```
cd ~/.mozilla/firefox/fifoxxzm.default/
mkdir chrome
cd chrome
vim userChrome.css  # Or whatever you choose, of course
```

Then put the following in `userChrome.css`:

```
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

#TabsToolbar {
    visibility: collapse !important;
}
```

**Comment by kanmeiban** [comment]
@collinbarrett To make hidden top tab header usable on Mac, insert flexible space to the left.

**Comment by Walkman100** [comment]
@collinbarret Same here on macOS 10.12.6 and FF 57.0 64-bit, but it only happens in windowed-mode, i.e. if FF is in fullscreen (which I keep it in) then it's completely usable.

**Comment by collinbarrett** [comment]
ah, thanks @kanmeiban . that helps. do you  know if the flexible space can be resized?

**Comment by WaDelma** [comment]
The provided CSS worked fine with my crummy mint laptop, but on work laptop with win10 it turned top header dark blue. The buttons there still highlight and work though.

**Comment by collinbarrett** [comment]
a summary gist if helpful to anyone:
https://gist.github.com/collinbarrett/45c90f7d427e08d69d32dfef402c86f6

**Comment by thedarb** [comment]
Running 58.02 build for Linux Mint.  Followed @mgsloan instructions, and not seeing any effect.  Did 58.0x break this?

**Comment by jpdeplaix** [comment]
For the record, Firefox 59 is introducing an "Experimental Tab Hiding" feature

https://blog.mozilla.org/addons/2018/01/26/extensions-firefox-59/

**Comment by bughit** [comment]
The current wiki [snippet](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-horizontal-tabs-at-the-top-of-the-window-1349) produces the following on win7, with the menu visible:

![image](https://user-images.githubusercontent.com/895588/38462893-d9acd258-3abb-11e8-8161-66d1147c845b.png)

How do you reduce the title-bar height?

**Comment by photonometric** [comment]
@bughit Having the same trouble. Not sure if there is a more elegant solution yet, but if Title Bar is checked in customization, the top of the window looks normal (empty space is filled properly).

**Comment by bughit** [comment]
@K7and Thanks, that worked, the following further reduces the title bar (with menu) height

```css
#titlebar {margin-bottom: -26px !important;}
```
The default was -20.

**Comment by K7and** [comment]
@bughit 
With -26px margin, [x] button is already over addons' icons (1050px screen height).
22-23px is the most accurate for me. Thanks

**Comment by piroor** [comment]
I close this because this is out of the range of WebExtensions-based extension.
