### ISSUE TITLE
Child links of the bottom tab not inserted at the top of the tree

### ISSUE THREAD

**Issue by gonhidi** [piroor/treestyletab#1350]
[console.txt](https://github.com/piroor/treestyletab/files/1281161/console.txt)
## Short description

By default, new tabs created by following links from a parent tab are created as sibling child tabs, the newer ones at the bottom of the sibling list. There is an option so that the new children appear at the top of the sibling list instead of at the bottom. If this option is selected and the parent tab has just been moved to the bottom of the TST tab list, the tabs created by opening a second and further links do not appear as described; instead they are created at the root level at the bottom, each one below the previous one.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Configure TST to “insert at the top of the tree, as the first child” for new child tabs.
 4. Move a childless tab (the ‘parent tab’) to the bottom of the tab list (it can hang from the root or from a tree), select it, and load a page with links.
 5. Open a new link as a child tab (e.g. by middle clicking or using the “Open Link in New Tab” entry of the right-click context menu).
 6. Repeat the previous step.

## Expected result

The last step should create a tab that is a sibling of the first and it should appearing above it, as the first of the children.

## Actual result

The last step creates the tab at the bottom of the tab lists and it hangs from the root, at the top level, with no parent tab.

## Observations

Further tries of the last step lead to repetitions of the actual results. If one selects a different tab and then selects back the parent tab, the behaviour becomes the expected one. The attached Firefox console output comes from opening three links as child tabs (the last two of the three are not placed where expected), changing from the parent tab and back to it, and then opening a fourth link (which is placed were expected, as the first child of the parent tab).

## Environment

 * Platform (OS): macOS Sierra 10.12.6
 * Version of Firefox: Nightly 57.0a1 (2017-09-05) (64-bit)
 * Version (or revision) of Tree Style Tab: Git build from commit 99017ef280e47982dfa890f2caaf2d2104f2f435 (HEAD -> master, tag: 0.19.2017090601, origin/master, origin/HEAD)

**Comment by piroor** [comment]
I cannot reproduce this anymore on my environment. Some recent commits possibly solve the issue, so could you re-confirm it with the latest build?: http://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi

**Comment by gonhidi** [comment]
Using the current/linked build, the bug as described (as well as in a slightly wider sense)[1] seems fixed. Thank you.

[1] The problem also manifested itself with ’parent tabs’ that were not the last, though not exactly as reported (child tabs remained in the proper level but the order was not as expected).
