### ISSUE TITLE
Show TST sidebar on startup

### ISSUE THREAD

**Issue by theres-waldo** [piroor/treestyletab#1351]
I'm using the new WebExt version of TST with Firefox Nightly. It generally works great!

However, I have to open the sidebar via View -> Sidebar -> Tree Style Tab every time I start Firefox. Is there a way to have the sidebar shown automatically on startup?

**Comment by piroor** [comment]
It is clearly impossible due to Firefox's limitation. https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Sidebars says:

> When an extension that defines a sidebar is first installed, its sidebar will be opened automatically. This is intended to help the user understand that the extension includes a sidebar. Note that it's not possible for extension to open sidebars programmatically: sidebars can only be opened by the user.

**Comment by theres-waldo** [comment]
Thanks. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1397487 about this.

In the meantime, is it possible to mitigate this by assigning a keyboard shortcut to View -> Sidebar -> Tree Style Tab (similar to how VIew -> Sidebar -> Bookmarks has a keyboard shortcut)?

**Comment by piroor** [comment]
Now `F1` is available to toggle TST's sidebar. d972b05c582438300299929d86ba9289650a6f40

**Comment by piroor** [comment]
Because https://bugzilla.mozilla.org/show_bug.cgi?id=1385630 is now FIXED, I close this.
