### ISSUE TITLE
TST sidebar goes into infinite loop, never completes startup

### ISSUE THREAD

**Issue by jryans** [piroor/treestyletab#1352]
## Short description

With WE TST using rev c56f846ab38191e1413eb301556d700a9b198050 or later, the sidebar never completes startup, and the Firefox parent process goes over 100% CPU (seems like an infinite loop somewhere).

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST WE at rev c56f846ab38191e1413eb301556d700a9b198050 or later.

## Expected result

Sidebar should finish loading.

## Actual result

Sidebar never completes, instead the loading icon is shown forever.

## Environment

 * Platform (OS): macOS 10.12.6
 * Version of Firefox: Firefox 57 (2017-09-05)
 * Version (or revision) of Tree Style Tab: TST WE rev c56f846ab38191e1413eb301556d700a9b198050

**Comment by piroor** [comment]
It seems caused by newly added permissions. After I restart Firefox, the problem disappeared for me. Could you try that?

**Comment by jryans** [comment]
For me, restarting Firefox doesn't fix it. Same behavior as before the restart: sidebar never completes, parent process goes over 100% CPU.

**Comment by piroor** [comment]
Any error reported in the browser console, Ctrl-Shift-J?

**Comment by jryans** [comment]
With debug mode on, I do see messages like:

tst<BG>:    onMessage: timeout!  Object { type: "treestyletab:request:ping" } Object { id: "treestyletab@piro.sakura.ne.jp", url: "moz-extension://8c4c571f-cd0f-f247-…", extensionId: "treestyletab@piro.sakura.ne.jp", contextId: "47075-0" }

However, these also seem to show up in the working version as well, so it might be unrelated.

Here are full logs:

[Working Log](https://github.com/piroor/treestyletab/files/1285334/working-tst.txt)
[Broken Log](https://github.com/piroor/treestyletab/files/1285331/broken-tst.txt)

In the broken version, tabs now have a `cookieStoreId` (as expected from the change). I am not really using containers, so I believe they all say "firefox-default".

Ah, but after diffing the logs, I see the broken version has:

```
TypeError: aCode is undefined[Learn More]  sidebar.js:217:7
```

...which is called by `updateContextualIdentitiesSelector`.

After logging the `identity` object, I have things like:

```
{"name":"Personal","icon":"fingerprint","color":"blue","cookieStoreId":"firefox-container-1"}
```

...so there is no `colorCode` property for me.

**Comment by piroor** [comment]
Thank you for information. Hmm, I still cannot reproduce the problem, but I agree that current codes are too fragile for unexpected cases. By the commit 1f035b52dba623afabd5f5ab45c914ede916560d TST becomes robust for such cases. Could you try it?

**Comment by jryans** [comment]
Yes, that commit fixes the issue for me, thanks! 😁 

On this profile, I used to have the [TestPilot Containers experiment](https://testpilot.firefox.com/experiments/containers) enabled, which allowed tweaking container colors. I no longer have the experiment installed, but perhaps that has affected the reported color data.

**Comment by piroor** [comment]
Thanks again!

**Comment by jryans** [comment]
Ah, I guess in the end, updating Nightly might have fixed it... It looks like `colorCode` was added by https://hg.mozilla.org/mozilla-central/rev/34d6906c2559, which first appeared in 20170906 Nightly, which is one day after the one I was using.
