### ISSUE TITLE
Webextensions: treestyletab-group feature

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#1353]
In the old version, you could create a tab that could be named and would have all the URLs of its children on that page.  Ex:  about:treestyletab-group?New%20Computer

Any idea if this is possible with Webextensions or is on your to-do list?

This would be a GREAT feature while the whole "Tab Groups" replacement strategy is ironed out.  At least having "root" tabs that can be named would help with organizing tabs.

**Comment by piroor** [comment]
It has been migrated partially. You'll see a group tab when you open a bookmark folder in tabs. However, it has very long internal URI string like `moz-extension://d04ef1b4-1d5b-4aa8-9950-465e1394005f/resources/group-tab.html?title=foobar%20and%20more&temporary=true` ...

**Comment by piroor** [comment]
The API says that we can provide only few well-known about: URIs, about:newtab, about:bookmark and about:history. https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/chrome_url_overrides

**Comment by theres-waldo** [comment]
How do you "open a bookmark folder in tabs"? I don't care about the URL, I just want something with a title that I can use as a parent to group children.

**Comment by piroor** [comment]
It seems impossible for WebExtensions based addons because there is no API to hook the timing "a bookmark folder is (going to be) opened".

Of course it is possible if I totally reimplement bookmark sidebar or bookmark menu by self inside TST's sidebar or toolbar button, but it is stupid way...

**Comment by theres-waldo** [comment]
Sorry, maybe I am confused. I'm not actually looking for any functionality related to bookmarks. I was just trying to understand what you meant by your earlier comment.

I am just looking for a way to create a tab whose sole purpose is to act as a "folder" to group other tabs, like `about:treestyletab-group` in the legacy extension.

I worked around it myself, by creating a local page like this:

```
<head>
  <link rel="icon" type="image/x-icon" href="{path to folder icon}" />
</head>
Enter title:
<input type="text" oninput="document.title = this.value;">
```

Surely, an extension can provide a page like this?

**Comment by piroor** [comment]
@theres-waldo TST 2.0a actually cannot detect user's action to open bookmarks in tabs. Instead, when multiple tabs are opened in 100msec, TST conjectures that they are from a bookmark folder, then TST simply opens a dummy tab to group them. Because there is no information about the source bookmark folder, the dummy tab is simply named from the first tab. (On the other hand, legacy TST 0.19.x injects some codes to open bookmark folders and prepares a dummy tab with the folder's name.)

> Could the extension provide a page like this?

I also tried it, but I still don't know how to embed runnable scripts in such page. When I embed some JS codes to a builtin resource, it was simply ignored...

**Comment by nt1m** [comment]
@piroor There is a way to detect navigation originating from bookmarks, I don't think it's as precise as knowing which folder it is from, but [TransitionType](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webNavigation/TransitionType) of the webNavigation API provides a "auto_bookmark" type.

You might be able to associate this data with tabs.onCreated(), and detect a sequence of bookmark-related navigation.

**Comment by piroor** [comment]
@nt1m The information seems not available on Firefox. I've test it with a code like:

```javascript
browser.webNavigation.onCommitted.addListener(onCommitted);
function onCommitted(aDetails) {
  log('onCommitted ', aDetails);
}
```

but all events say that their "transionType" is "link", even if the tab is opened from bookmarks.

**Comment by nt1m** [comment]
@piroor Looking at the Firefox source code, the only case that's supported is clicking a bookmark from the urlbar popup. You might want to file a bug for the remaining cases (bookmarks toolbar/sidebar, ...).

**Comment by sumyungguy** [comment]
For a short answer to irvinm's question of how to manually make a "dummy tab" with title, the same as previous "bookmark with `about:treestyletab-group?TabTitle`", some answers are found in issue #854. Unfortunately it doesn't yet have the feature of listing the tree, changing the title, etc.

**Comment by piroor** [comment]
By recent commits, `about:treestyletab-group` is redirected to actual `moz-extension:` URL by TST automatically. You don't need to use the actual very long URL anymore.

**Comment by irvinm** [comment]
Thank you @piroor.  Your work is always appreciated.

What do you think about maybe just creating a right-click option to "Create Tab Group" which could create a new child\sibling tab to "about:treestyletab-group?TabTitle" then the user does not even need to remember the simplified URL and they can just edit the "TabTitle" in the URL to whatever they want?

On a side note, it looks like you are missing the "?title=xxx" from your redirection.  I noticed by using your simplified method that the tab title always showed "Group" as the title vs. what was in the URL.

**Previous working: (Title = New Egg)**
moz-extension://599b265a-a2d6-43d3-9e62-6323b543c717/resources/group-tab.html?title=New%20Egg&temporary=true

**New redirection: (Title = Group)**
moz-extension://599b265a-a2d6-43d3-9e62-6323b543c717/resources/group-tab.html?Test&temporary=true

**Comment by piroor** [comment]
Basically TST is designed for "tree of tabs", not for "grouped tabs". This dummy tab feature is just made to create new tree from tabs opened by bookmark folders, because they don't have any logical "parent". So I don't hope to add any feature to open such a dummy tab intentionally - it is a design decision.

However, as a workaround for people who want to open new dummy tab manually, a new bookmark item with the URI `about:treestyletab-group?New%20Group` (or something) is still available.

**Comment by irvinm** [comment]
Thanks for the feedback about the feature request.  (I figured it couldn't hurt to ask, right?)

There is still an issue with the redirect that it doesn't populate the "tab title" properly.  The redirect is missing the "title=".  Your example of: 

> about:treestyletab-group?New%20Group

 will result in a new tab group with the label "Group" not "New Group".

**Actual redirected link:**  
moz-extension://599b265a-a2d6-43d3-9e62-6323b543c717/resources/group-tab.html?New%20Group

![2017-11-10_11-36-34](https://user-images.githubusercontent.com/979729/32668529-e1f55252-c60b-11e7-8e55-a523d2726238.png)

**Should be:**  
moz-extension://599b265a-a2d6-43d3-9e62-6323b543c717/resources/group-tab.html?title=New%20Group

![2017-11-10_11-37-08](https://user-images.githubusercontent.com/979729/32668528-e1e8f606-c60b-11e7-8309-e749eefad239.png)

**Comment by irvinm** [comment]
Oh, I see you added the feature to detect the title without the "title=" in 2.1.1.

Closing ...

**Comment by rubaboo** [comment]
Creating a group without specifying a name, and then renaming it leads to an error because the resulting URL is missing the `?` between `.html` and `title=`:
```
moz-extension://5ee6e8ba-3d3e-484b-8ec8-019246337601/resources/group-tab.htmltitle=Renamed_Group
```

**Comment by piroor** [comment]
The bug was already fixed on the master.
