### ISSUE TITLE
Multiple Windows with Version 2

### ISSUE THREAD

**Issue by adavier** [piroor/treestyletab#1355]
## Short description
When moving tabs between windows it causes TST in the window that it has been moved from to reload and the tab becomes a *ghost* tab in the destination window, able to be viewed but not closed through TST. These tabs do show correctly on the normal address bar at the top.

This can also cause the tabs on the origin window to loose the trees that they belong to, but this does not happen everytime.

Once the browser is restarted everything goes back to normal (except when sometimes the tree on window 2 is lost.

If tab is moved using the tabbar, the tab correctly changes window and causes no issues.
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a second window
 4. Open some tabs on the second window.
5. Use the sidebar to drag tabs from one window to the other

## Expected result
Tab moves and appears in appropriate tree.

## Actual result
Tab does move but the sidebar becomes out of sync with the rest of the browser. Sometimes trees are lost.

## Environment

 * Platform (OS):  Win 10 64bit
 * Version of Firefox: 57.0a1 (2017-09-08)
 * Version (or revision) of Tree Style Tab: v2.0a (2017-09-08)

**Comment by piroor** [comment]
Hmm, it is very odd. After I researched, a tab moved across windows seems have two different ids internally. For example, when I move a tab#8 from a window to another, the moved tab in the destination window becomes tab#24. However, when I click the moved tab#24 in the destination window, onActivated event is fired for tab#8. As the result TST cannot detect which tab is actually activated in the window...

**Comment by piroor** [comment]
Updated: The problem doesn't happen when TST is disabled - tabs moved accross windows keeps its id, as tab#8 in the destination window. So I think something TST's internal operation triggers to create new (invalid) id for the moved tab.

**Comment by piroor** [comment]
This problem seems to be triggered by a bug of Firefox itself. I've filed a bug: [1398272 - tabs.onUpdated listener triggers broken consistency of tabs.Tab.id, by a tab moved across multiple windows](https://bugzilla.mozilla.org/show_bug.cgi?id=1398272)

**Comment by adavier** [comment]
I would like to thank you, as your response has been amazing and your workarounds seem to have solved the issue. 

---
Working as of TST 2017-09-10
