### ISSUE TITLE
Dark theme (WE)

### ISSUE THREAD

**Issue by mathearts** [piroor/treestyletab#1356]
Any plans for a TST-WE theme that would look good with the dark theme from FF57?

Also, is it possible to hide the close buttons using custom .css?

Thank you!

**Comment by piroor** [comment]
Hmm, I can provide dark theme (actually there are some color definitions used in the legacy version) but it seems unnatural for Firefox's sidebar color scheme. Even if TST provides a dark theme, the header area and other sidebar panels will stay "light". (The header area is not controllable by WebExtensions Addons.)

![image](https://user-images.githubusercontent.com/70062/30254816-a63a1674-96d8-11e7-9eec-2d606180b394.png)
![image](https://user-images.githubusercontent.com/70062/30254826-c3a0762c-96d8-11e7-8999-59454c821501.png)

**Comment by post-temporal** [comment]
This intrigues me as I don't experience any dark theme related issues (aside from the tab background).
Which leaves me wondering what I'm doing differently....
FF 57 (9-9-17) 
TST WE Nightly (9-9-17)
![tst dark](https://user-images.githubusercontent.com/30803117/30258010-f5c796ec-96df-11e7-8526-f74b7cd42b7e.png)

**Comment by piroor** [comment]
@post-temporal  TST's ”Mixed” and some other themes use CSS's system color like "ThreeDFace". If you configure your OS to use a dark theme, Firefox and TST respect the color scheme by default. On the other hand, when you use a combination of OS's bright theme and Firefox's dark theme, only Firefox's toolbars become dark.

**Comment by gnite** [comment]
Just FYI, the bug with the color of the sidebar not changing with the dark theme is being tracked [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1385518), so once this gets fixed a dark theme for TST would be nice.

**Comment by post-temporal** [comment]
Many thanks @piroor for making my confusion vanish with the spot on explanation - Yep, my OS runs a dark theme.
Much gratitude and respect to you for your tireless work with TST.  For me, it really is that 'killer' FF addon that I would most hate to lose.

**Comment by piroor** [comment]
By recent commits, a new theme "Plain Dark" is added.
