### ISSUE TITLE
TST + "Open Tabs Next to Current" wrong new-tab tree display

### ISSUE THREAD

**Issue by famfop** [piroor/treestyletab#1357]
## Short description
I am using TST in combination with "Open Tabs Next to Current" By Sebastian Blask. Although this is another tabs-related addon I believe it sounds like an easy-to-resolve bug. It just looks like a special case was not considered/implemented...
(Having both installed:)
I have a tree of tabs (say two in total) and go to the upper tab. Now, when opening a new tab it appears in the "middle" of the tree. Behaviour-wise everything works fine.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install "Open Tabs Next to Current" By Sebastian Blask 
 4. Open two tabs (one as a child of the other)
 5. Open a new tab (ctrl+t) from the upper one.

## Expected result
New tabs appears at the end of the tree, as a "new", single tree.

## Actual result
Appears in the middle of the tree.

## Environment

 * Platform (OS): GNU/Linux, Ubuntu
 * Version of Firefox: 55
 * Version (or revision) of Tree Style Tab: 0.19.2017090601

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
