### ISSUE TITLE
Webextension not loading in private windows.

### ISSUE THREAD

**Issue by adavier** [piroor/treestyletab#1358]
## Short description
Sidebar not functioning on private windows
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open private window
 4. Open Sidebar

## Expected result
Functioning tab tree

## Actual result
The tab tree builds correctly and new tabs are added/removed, but the loading overlay is stuck on so the tree cannot be interacted with.

## Environment

 * Platform (OS): Win 10 64x
 * Version of Firefox: 57.0a1 (2017-09-12) (64-bit)
 * Version (or revision) of Tree Style Tab: V2.0a (2017-09-12)

However, this did work correctly on versions from about a week ago.

**Comment by piroor** [comment]
Fixed by 4d0ea74a6612dec83326bb403baac776b9b506a2. Thanks!
