### ISSUE TITLE
Choose side of scroll bar and close button separately

### ISSUE THREAD

**Issue by Keith94** [piroor/treestyletab#1362]
In the WebExtensions version, I'd like to have both the close buttons and scrollbar on the right. When choosing "Right side" in the options, it puts the tab close buttons on the left. Can I choose to put them both on the right or left side?

**Comment by piroor** [comment]
Put following style rule into the "extra style rules" field in the configuration, then inverted scrollbar will go away.

```css
:root.left #tabbar {
  direction: ltr;
}
```

**Comment by Keith94** [comment]
@piroor Thanks! That worked.

**Comment by piroor** [comment]
This is filed at the code snippets:
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules
