### ISSUE TITLE
[WE][Nightly] WhatsApp Web favicon does not show

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#1365]
## Short description
Tree Style Tab (WE) cannot show the favicon for https://web.whatsapp.com/, while TST Legacy can.

## Steps to reproduce

 1. Start Nightly with clean profile.
 2. Install TST WE.
 3. Go to https://web.whatsapp.com/
 4. Observe the favicon on TST tab bar and the original tab bar.

## Expected result
Favicon is shown in TST

## Actual result
Favicon is missing in TST but is shown on the original tab bar:
![tst_we](https://user-images.githubusercontent.com/771216/30752050-b6222bbc-9fed-11e7-9467-dc4b41217e46.PNG)

## Environment

 * Platform (OS): Win10 CU 64bit 
 * Version of Firefox: Nightly 2017-09-22
 * Version (or revision) of Tree Style Tab: Tree Style Tab (WE) 2.0a

**Comment by DIzFer** [comment]
I can confirm this is happening to me too, and has for a week or so, but 
I hadn't associated it to TST.

**Comment by DIzFer** [comment]
![shot](https://user-images.githubusercontent.com/8852888/30752619-236fc502-9fbd-11e7-9916-022f3bc93a28.png)
Second comment because github is dumb when it comes to email replies and doesn't attach pictures nor lets me edit the reply -.-

**Comment by piroor** [comment]
I don't know the reason but WebExtensions API reports an invalid URL `blob:https://web.whatsapp.com/7e3b071f-8daa-4a75-9ad4-49a3ea85dd91` as the value of `favIconUrl`. So same problem happens on any WebExtensions-based addons including Tree Tabs and Tab Center Redux.

**Comment by piroor** [comment]
I've filed: [1402393 - Wrong URL is reported via tabs.Tab.favIconUrl for whatsapp.com](https://bugzilla.mozilla.org/show_bug.cgi?id=1402393)

**Comment by piroor** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1402393#c2

> When I do watch events on that page I note that the icon changes multiple times from:
> 
> https://web.whatsapp.com/img/favicon/1x/favicon.png
> https://web.whatsapp.com/apple-touch-icon.png
> blob:https://web.whatsapp.com/5d7c2ea3-5045-0847-a176-8c71e46a72fe
> 
> If you look at the source, it looks like whatsapp changes it to a blob. So the tabs API is faithfully reporting it back.

**Comment by piroor** [comment]
After 30959bb, last effective favicon will be applied in such cases.The finally applied favicon is different from Firefox's tab, but I have no idea to maintain complete favicon database by self...

**Comment by Fanolian** [comment]
Thanks for the fix. But the favicon disappears again after a reload.

**Comment by Fanolian** [comment]
I believe the fix introduces a much worse issue now. The process responsible for WebExtensions has a constantly high CPU usage when using, or simply visiting, WhatsApp Web.

Steps to reproduce:
1. Install only TST 2.0 on a Nightly's new profile.
2. Open Task Manager, or any program that tracks CPU usages.
3. In Nightly, open https://web.whatsapp.com/. 
3a. Favicon should now be shown on TST side bar. CPU usage remains very low or none.
4. Reload the tab.

Actual result:
No favicons is shown on side bar. CPU usage for WebExtensions process skyrockets.

**Comment by Fanolian** [comment]
Is it possible to back out the fix while you are investigating the issue? No favicons is definitely preferable to constant high CPU usage. Thanks.

**Comment by piroor** [comment]
0ad9e1d should fix the infinite-loop problem.

**Comment by Fanolian** [comment]
Confirm fixed. Thanks
