### ISSUE TITLE
Quickly-opened new child tabs not placed correctly at the top of the tree

### ISSUE THREAD

**Issue by gonhidi** [piroor/treestyletab#1366]
## Short description

When TST is set to insert new child tabs at the top of the tree, if they are created in quick succession they might not get placed how they should.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Configure TST to “insert at the top of the tree, as the first child” for new child tabs.
 4. Open a page with at least one hyperlink.
 5. Slowly open a few child tabs by middle clicking. (Optional)
 6. Quickly open several child tabs by middle clicking.

## Expected result

Each new child tab opened in the last two steps should be positioned at the top of the tree respecting the order in which the clicking has occurred.

## Actual/observed result

The new tabs added in the last step open at the top of the tree but not in the expected order.

## Environment

 * Platform (OS): macOS 10.12.6
 * Version of Firefox: Nighty 58.0a1 (2017-09-22) (64-bit)
 * Version (or revision) of Tree Style Tab (WebExtensions version): Self-built from 0.19.2017090601-191-g2556529e (commit 2556529e5cf02108e24f73cc23b01cffeb80e813)

## Observations

A consequence of the observed result is that the insertion position and order of further child tabs may not be correct: sometimes, further slowly-opened child tabs are placed at the bottom of one of the unexpectedly-opened child tabs (undesired placement) and each one below the previous one (undesired order).

The situation previously described pertains to the WebExtensions variant of TST. However, a similar behaviour can be triggered in the non-WebExtensions variant (0.19.2017090601 with Firefox ESR 52.3.0 running on the same system). There are two differences:

 1. To easily trigger the unexpected behaviour by following the described procedure many (child tabs) must have been previously opened (in my case, more than twenty is a good start).
 2. The actual/observed behaviour is that some of the tabs are opened at the bottom of the tree instead of at the top.

If it is sensible to differentiate one situation from the other (e.g. for differences in the code, in the impact or in the lifetime expectancy of each TST variant) a separate issue can be opened to target the non-WebExtensions variant's behaviour.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
