### ISSUE TITLE
[Nightly] Bug 1366290 messes up tab focusing when closing last remaining child tab

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#1367]
## Short description
After [bug 1366290 - Bad event ordering in webextension tabs API](https://bugzilla.mozilla.org/show_bug.cgi?id=1366290), closing the last remaining child tab of a tree does not always focus its parent, but the next/right/below tab instead.

## Steps to reproduce

 1. Start Nighlty after 2017-09-14 build with clean profile.
 2. Install TST 2.0.
 3. Make 2 parent tabs, Tab A and Tab 1. Make a child tab Tab B under Tab A.
```
Tab A
└─Tab B
Tab 1
```

4. Switch to different tabs more than once. (This step seems to be necessary on a new profile.)
5. Focus on Tab B.
6. Close Tab B by middle-clicking or Ctrl-W. Just do not close the tab by clicking the close button on the tab.

## Expected result
Tab A should be now in focus.

## Actual result
Tab 1 is now focused instead. Mozregression points to bug 1366290.

## Notes
If I close the last child tab with the close button on the tab, it always focuses on the expected tab (previous sibling tab or parent tab).

## Environment

 * Platform (OS): Win10 CU
 * Version of Firefox: Nightly after 2017-09-14
 * Version (or revision) of Tree Style Tab: 2.0

**Comment by piroor** [comment]
Thanks, confirmed with Ctrl-W. Possibly recent commits solves this problem for middle-click case unexpectedly.

**Comment by piroor** [comment]
The commit 04f369d should fix this.

**Comment by Fanolian** [comment]
There are still some cases where Ctrl-W does not work as expected.

Steps to reproduce:
1. Open 2 parent tabs, Tab A and Tab B.
2. On Tab A, go to https://piro.sakura.ne.jp/xul/xpi/nightly/.
3. Middle click "Parent Directory" to open a child tab.
4. Switch to Tab B. Switch to child tab.
5. Press Ctrl-W to close the child tab.

Actual result:
Tab B is now active instead of Tab A.

What is working now:
If I drag and make a tab as a child tab manually, closing it always focus to its parent tab.

**Comment by piroor** [comment]
Thanks again. 9bfafd9 should fix the case.

**Comment by Fanolian** [comment]
I have not encountered more issues about tab focusing for a day. Thanks for the fix.
