### ISSUE TITLE
[Nightly] Tab is sometimes "highlighted"

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#1368]
## Short description
![tst_highlighted tab](https://user-images.githubusercontent.com/771216/30874775-eb477034-a323-11e7-9928-400c0aa2d59b.PNG)
First tab is the issue; it is highlighted. Second tab is the active tab.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. On a tab, quickly click-and-drag horizontally for a small distance. Quickly release the click.

## Expected result
No highlighting.

## Actual result
The tab is highlighted.
The issue does not affect any functions TST provides. Perhaps it is just a visual glitch.
To work around it, click-and-drag the affected tab again.

## Environment

 * Platform (OS): Win10 CU
 * Version of Firefox: Nightly 2017-09-26
 * Version (or revision) of Tree Style Tab: 2.0

**Comment by piroor** [comment]
Thanks. beb7113 should fix this.
