### ISSUE TITLE
Show advertising message for initial install (or updated) to show sidebar panel manually

### ISSUE THREAD

**Issue by staktrace** [piroor/treestyletab#1369]
## Short description

After upgrading to WebExtension version of TST, the sidebar doesn't automatically show. Filing this as a result of discussion on https://bugzilla.mozilla.org/show_bug.cgi?id=1403183

## Steps to reproduce

 1. Start Firefox (version < 57) with clean profile.
 2. Install TST (non-webextension version)
 3. Update Firefox to 57. This should also update TST to 2.0 which is the WebExtension version

## Expected result

When the WebExt version of TST is installed, the sidebar panel is made visible.

## Actual result

It is not made visible. This makes it feel like TST is broken.

I originally filed a bug against Mozilla for this, https://bugzilla.mozilla.org/show_bug.cgi?id=1403183 but it's not considered a bug by the add-ons team. Instead the suggested fix is that TST open a new tab advising the user to make the sidebar visible.

**Comment by piroor** [comment]
Because it is not allowed that WebExtensions addon opens the sidebar automatically without any user action, I think it is the last solution left for us: showing announcement message at initial startup of TST 2.0.

**Comment by piroor** [comment]
The API: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/OnInstalledReason

**Comment by piroor** [comment]
Oops, I wrongly mark the commit is related to this... It should be #1038

**Comment by piroor** [comment]
By recent commits, now a message tab is shown automatically when TST is updated from legacy to 2.0.

**Comment by staktrace** [comment]
Thanks!
