### ISSUE TITLE
Tabs are closed on middle click mousedown rather than mouseup.

### ISSUE THREAD

**Issue by mparkms** [piroor/treestyletab#1370]
## Short description
In the WE version, tabs are closed on middle click mousedown rather than mouseup. Previously, the tab would only close on mouseup on the same tab, but now it closes as soon as you click the middle mouse button. This is not ideal in cases of misclicks. I suspect that this is because it is listening to the "mousedown" event rather than the "auxclick" event. The same problem occurred in the Tab Center Redux add-on.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a new tab.
 4. Middle click on the new tab, but do not release the mouse button.

## Expected result
The tab should not close until the middle mouse button is released on the same tab it was pressed on.

## Actual result
The tab closes as soon as the middle mouse button is depressed.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: Dev Edition 57.0b3 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.0

**Comment by piroor** [comment]
Thanks. dccbab7 should fix this.
