### ISSUE TITLE
[Feature-request] [Improvemnet] Hide dummy parent tabs

### ISSUE THREAD

**Issue by hyiltiz** [piroor/treestyletab#1371]
## Short description
We should be able to hide or minimize (like Pinned tabs) dummy tabs, so they do not take over space.

## Longer description
There should be an option in the addon preferences page so that if the user chooses to replace closed parent tab with a dummy tab (excellent feature!), then the dummy tab is simply created internally as part of the data structure that `tabtree` manipulates, but the dummy tab itself should not be shown/opened/displayed visibly at all. Since we cannot write any text (title), or rename the dummy tab in any way (either in the tab bar or in the tabtree sidebar), displaying it is quite pointless. However, it preserves the tree structure so is a very useful feature. Considering how brainfuck the WebExtention API is, creating a record for the dummy tab in the data structure `tabtree` keeps *without* displaying the tab may not be something possible. In that case, is it possible to "Pin" it so it takes over less space in the tab menubar? Of course, without automatically moving the "Pinned" dummy tab all the way over to the far left, which again disrupts the tree structure by messing up the order.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. In TST Preferences, enable "Replace closed parent with a dummy tab ..."
 4. Open any page P0 with some link, and click on those link. Now, close the P0, creating a dummy page DP0 for it.
5. Right click to hide DP0, but there are no such option. Pin it, but it moves to the left.

## Expected result
An option to hide the dummy page is provided.

## Actual result
No such option is present.

## Environment

 * Platform (OS):  OSX 10.11.6
 * Version of Firefox: Firefox 57.0 Developer Version
 * Version (or revision) of Tree Style Tab: Tabtree 2.0 (Sept. 26, 2017)

**Comment by piroor** [comment]
I couldn't imagine how it should be rendered as. Could you describe again with any  edited screenshot?

**Comment by hyiltiz** [comment]
I wanted to make an illustrated screenshots for the idea, but even the basic dummy parent tab feature isn't working correctly for reasons unknown to me. I enabled only STS (version and setting details below).

The tree structure:
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/3246683/30984370-21abced0-a45b-11e7-8271-ca08a64ac779.png">

After closing the parent tab.
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/3246683/30984086-5858eebe-a45a-11e7-9cba-145b775df1a8.png">

As you can see, a dummy tab is created, but instead of replacing the closed parent, it just remained as a separate parent node, and the first child got promoted into a new parent. Once I get it working such that a closed parent node is simply replaced by a dummy tab, I'll try to illustrate what this issue was originally about. The option "Promote the first child tab as the new parent, if the closed parent has no parent" does not affect this behavior.

Settings:
<img width="726" alt="image" src="https://user-images.githubusercontent.com/3246683/30984202-ac794778-a45a-11e7-8184-fd740f15c710.png">

Firefox settings:
<img width="651" alt="image" src="https://user-images.githubusercontent.com/3246683/30984262-d4912870-a45a-11e7-98e7-0335c40b7040.png">

<img width="1746" alt="image" src="https://user-images.githubusercontent.com/3246683/30984294-e8b85fbc-a45a-11e7-9572-85e66061a82e.png">

**Comment by hyiltiz** [comment]
Oh, in trying to explain this, I think I found a bug. Now, that bug aside, here is what I meant.

**Comment by irvinm** [comment]
@piroor can you evaluate this?  Can we close this?

**Comment by piroor** [comment]
Sorry I forgot to follow back this.

I decided to not implement this with these reasons:

* If I implement such a tab as "a real tab but hidden in the native tab bar via the `tabs.hide()` WebExtensions API", it may introduce compatibility problems with other addons which control visibility of tabs.
* If I implement such a tree item as "a virtual tab and unexisting in the native tab bar", it may introduce chaos to TST's architecture. TST is strongly designed to work with tabs got via WebExtensions API. Virtual tabs may require changes around the core implementation of TST, for example shifting of tab indexes.

Anyway, such irregular items in TST's sidebar must increase difference between Firefox's native tab bar and TST's tabs. I think that such changes are mismatch to TST's basic design policy. Basically I won't implement unrelated features to TST by myself, instead I recommend users to use TST with other addons providing such features they require. To say that, I need to keep TST compatible with other tab related addons, and I need to minimize difference between TST's tabs and FIrefox's tabs. This is the reason why I'm negative to implement this feature.
