### ISSUE TITLE
Webextensions: Cannot make tab panel narrower

### ISSUE THREAD

**Issue by nh2** [piroor/treestyletab#1373]
## Short description

I noticed that with the 2.0 Webextensions (on Linux, FF nightly 57.0a1 2017-09-18) I can no longer make the tab bar narrower than ~1/6th of my 1366px width screen (that is, wider than ~200px).

Is this a limit in TST or a Webextensions panel restriction?

How can I make it narrower than the ~200px?

Thanks!

**Comment by piroor** [comment]
It is a limitation of Firefox tiself and WebExtensions-based addons cannot control it. However something userChrome.css rules will do that.

**Comment by Keith94** [comment]
Add the following code to [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css), it should do what you want.

```css
#sidebar {
  min-width: 100px !important;
}

**Comment by nh2** [comment]
> Add the following code to userChrome.css, it should do what you want.

@Keith94 Thanks, that worked!

**Comment by nh2** [comment]
> It is a limitation of Firefox tiself and WebExtensions-based addons cannot control it.

@piroor Do you know if there's already a Firefox bug for this?

Having some sendible `min-width` is OK but the way it is currently is too restrictive on low-resolution devices, even for non-TST contents like the bookmarks list.

(Let's close this issue once we've either filed one or found one.)

**Comment by piroor** [comment]
[1346490 - Allow setting min-width and max-width for sidebar](https://bugzilla.mozilla.org/show_bug.cgi?id=1346490 "1346490 - Allow setting min-width and max-width for sidebar") seems that, but it was closed as "WONTFiX".

**Comment by nh2** [comment]
> 1346490 - Allow setting min-width and max-width for sidebar seems that, but it was closed as "WONTFiX".

Hmm, looks like that issue was about controlling the width from an addon.

I think for our purposes where we should have an addon-unrelated bug that that simply asks FF to decrease the `min-width`, as it is too wide for low resolutions.

**Comment by piroor** [comment]
I couldn't find out any bug focusing to the point. (Sorry I won't file it because currently I'm not suffered from "too wide sidebar" - I believe that bugs should be filed by highly motivated parties.)

**Comment by naclander** [comment]
Along these lines, is the ability to remove the "Tree Style Tab" header at the top of the tree list something that's possible, or is this also a limitation of WebExtensions? ( I don't mean to hijack this issue, I can create a new one but this seems related ).

**Comment by Keith94** [comment]
@naclander It's only possible with userChrome.css, as far as I know.

```css
#sidebar-header {
  display: none;
}

**Comment by naclander** [comment]
@Keith94  Thanks, that fixed it for me. I'm guessing TST ( or other firefox addons ) can't manipulate `chrome/userChrome.css` for users?

**Comment by Keith94** [comment]
I don't think so, WebExtensions API doesn't provide any means to style the browser UI yet.

**Comment by Keith94** [comment]
However you can edit and save the file directly from Firefox's dev tools. See https://github.com/Timvde/UserChrome-Tweaks/issues/4

**Comment by piroor** [comment]
I close this because this is out of the range of WebExtensions-based extension.

**Comment by AgentOak** [comment]
Since Firefox 107.0 the size limitation is on the `#sidebar-box` instead of the `#sidebar` element, so the CSS needs to be updated:

```
#sidebar-box {
  min-width: 100px !important;
}
```
Should be updated on the wiki on these two entries: 
- https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#reduce-minimum-width-of-the-sidebar-1373
- https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#full-auto-showhide-theme

**Comment by fiskhest** [comment]
I was seeing issues with this on Firefox 107.0 on both linux and windows and can confirm @AgentOak's findings. I have updated the relevant wiki snippets.
