### ISSUE TITLE
Fade out tab label on overflow instead of ellipsis

### ISSUE THREAD

**Issue by Keith94** [piroor/treestyletab#1374]
Adding faded tab labels would look more consistent with the rest of Firefox UI. See https://bugzilla.mozilla.org/show_bug.cgi?id=658467

**Comment by piroor** [comment]
Firefox seems does it with very complicated technique, and it seems impossible to be done by simple CSS rules by 1 or 2 lines. I need PR to implement this.

**Comment by Keith94** [comment]
@piroor Maybe this implementation (CSS) would work also for TST? https://github.com/eoger/tabcenter-redux/commit/c17a99dc67193ddd2b3564ba46cb8e7eafe651da

**Comment by piroor** [comment]
Hmm, Tab Center Redux's way seems different from Firefox's one.

Firefox:

 * The fade-out effect is implemented with SVG mask.
 * The alpha of text is actually changed, so it is effective for various themes.

Tab Center Redux:

 * The fede-out is just a fake, and it is done by a gray gradation element covers tab label.
 * We need to define colored gradation element for various cases. (TST has 7 built-in themes!)

**Comment by piroor** [comment]
Anyway both ways require more effort. To be honest I think noth they are not attractive for me - the cost-performance seems not high. Until more easier way like `text-overflow: fade-out` is introduced, I won't implement this by myself. (Instead I'm still waiting PRs ;) )

**Comment by Keith94** [comment]
Thanks for the info! Hopefully there will be an easier way at some point.

**Comment by hyiltiz** [comment]
`text-overflow: fade-out` should really be implemented within CSS. w3 sucks...

**Comment by Keith94** [comment]
@piroor I found some simple code that achieves the fade out effect quite nicely. Can you try it?

```css
.tab .label {
  mask-image: linear-gradient(to left, transparent 0, black 2em);
}
```
![image](https://user-images.githubusercontent.com/5490615/38448296-daffd886-39f2-11e8-8b98-aa9fde1b7700.png)

**Comment by piroor** [comment]
@Keith94 Wow, this works on the released version of Firefox also!

**Comment by piroor** [comment]
I've added the rule as a built-in style of TST itself.

**Comment by Keith94** [comment]
Looks good to me. :)
