### ISSUE TITLE
Move to new window possibly broken

### ISSUE THREAD

**Issue by Keith94** [piroor/treestyletab#1377]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Right-click a tab and move to new window

## Expected result
Tab is moved to a new window

## Actual result
A new window is opened with only a blank tab in it

`TypeError: this.contextTab is null  sidebar.js:328:9`

## Environment

 * Platform (OS): Windows 8
 * Version of Firefox: 58.0a1
 * Version (or revision) of Tree Style Tab: 2.0

**Comment by piroor** [comment]
307982e should fix this. Thanks!
