### ISSUE TITLE
WebExtensions-version: Tab title and settings are using bold font

### ISSUE THREAD

**Issue by ppggff** [piroor/treestyletab#1379]
## Short description

After install and enable TST, I found the tab title in sidebar and
all settings about TST are all using bold font, as following screenshot:

* the tab title
![tab](https://user-images.githubusercontent.com/2892417/30897281-f63c13c8-a387-11e7-9567-d80b37ab13d6.png)

* the settings
![setting](https://user-images.githubusercontent.com/2892417/30897284-f895ecde-a387-11e7-97a2-dcc89976f121.png)

Is this a problem of TST? or FF?
Thanks

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.

## Environment

 * Platform (OS): Win7 64bit
 * Version of Firefox: 57.0b3 64bit
 * Version (or revision) of Tree Style Tab: 2.0

**Comment by piroor** [comment]
Hmm, it's not intentional. How about other addons, for example Tab Center Redux?

**Comment by ppggff** [comment]
I tried Tab Center Redux, the tab title is ok, but settings also using bold font.

* tab title
![tab_o](https://user-images.githubusercontent.com/2892417/30897895-4d73c6ba-a38b-11e7-90d2-96b0066598a1.png)

* settings (the checkbox is so big...)
![setting_o](https://user-images.githubusercontent.com/2892417/30897903-542bdec0-a38b-11e7-86e2-9453589f4a1b.png)

**Comment by piroor** [comment]
Then it is possibly caused by font scaling of Firefox itself. Do you configure Windows to show texts larger (or smaller) than 100%? (BTW I don't see this problem on my Windows 10 with 100% scaling.)

**Comment by ppggff** [comment]
Thanks.
I set the system text scale to 100% too. Maybe it's a problem about win7+firefox.
Can I custom the font weight of tab title in the settings of TST?

**Comment by piroor** [comment]
TST 2.0, Firefox Developer Edition 57, Windows 7 64bit (ja)
![image](https://user-images.githubusercontent.com/70062/30900641-b484809c-a39f-11e7-9988-7f773deb86dc.png)

**Comment by piroor** [comment]
I couldn't reproduce this problem in my testing environment...

**Comment by piroor** [comment]
In TST's options, there is a text field to input custom CSS rules. You can put `body { font-weight: normal !important: font-size: small !important; }`  or something, and those rules are applied to the sidebar.

**Comment by ppggff** [comment]
Thanks, I found the problem.

It seems firefox use the font setting of 'window title' as default for the setting page and sidebar.
After set font weight of 'window title' from bold to normal in control panel, every thing back
to normal.

**Comment by piroor** [comment]
Oh, thank you for sharing the details. Yes, "caption" system font is applied as the default font in addon contents.
https://dxr.mozilla.org/mozilla-central/source/browser/components/extensions/extension.css?q=file%3Aextension.css&redirect_type=single#13
