### ISSUE TITLE
Somewhat ugly triangle padding in the "sidebar" style

### ISSUE THREAD

**Issue by nh2** [piroor/treestyletab#1382]
The style called "sidebar" seems to have some disbalanced padding left of the triangle button:

![screenshot from 2017-09-27 13-34-27](https://user-images.githubusercontent.com/399535/30911510-313a3986-a389-11e7-98d2-5d2892d4072f.png)

Note how the arrow is somehow "stuck" to the favicon on the right, and on the left there's lots of unused space (highlighted with red arrow).

Other TST styles don't seem to have this problem, only the `sidebar` style.

I found that to be caused by [this left-padding of 10px](https://github.com/piroor/treestyletab/blob/593203832e14fd5597af74ab24f12a31bc34103d/webextensions/sidebar/styles/sidebar/sidebar.css#L89) in the code:

```css
.tab {
  padding: 0.075em 3px 0.075em 10px;
}
```

Changing to `2px` left-padding makes it well-balanced, like in other TST styles:

```css
.tab {
  padding: 0.075em 3px 0.075em 2px;
}
```

![screenshot from 2017-09-27 13-49-25](https://user-images.githubusercontent.com/399535/30911975-0f7cc690-a38b-11e7-8dee-d958f82f9282.png)

Should I send a PR for this?

**Comment by nh2** [comment]
> Should I send a PR for this?

Actually, for your convenience, here's the PR already: #1383

**Comment by piroor** [comment]
Because original code of the theme is not mine, I was not familiar to detailed reasons for each definitions. Now I've confirmed that the Library window has similar triangle in its sidebar and it doesn't have such a too large padding, so I totally agree this change. Thanks!
