### ISSUE TITLE
[Feature Request] Close tabs to bottom

### ISSUE THREAD

**Issue by ben-watt-es** [piroor/treestyletab#1389]
## Short description
The context menu option "close tabs to bottom" existing in prior versions of Tree Style Tab, but it doesn't seem to in the latest 2.0 releases.

**Comment by piroor** [comment]
There is "Close Tabs to Right", it works as you expected.

**Comment by piroor** [comment]
By the reason I wrote at another issue https://github.com/piroor/treestyletab/issues/1388#issuecomment-332764414 , I have very row motivation to make the fake context menu rich like as legacy version. All builtin items in the menu is designed just aliases of Firefox's tab context menu items, and the real purpose is: providing ability to use extra context menu items added by other addons in the sidebar. (See also https://github.com/piroor/treestyletab/wiki/API-for-other-addons#extra-context-menu-items-on-tabs )

**Comment by piroor** [comment]
I close this because outdated. Now there is a builtin context menu command "Close Tabs to Bottom".
