### ISSUE TITLE
view-source: tab’s title is "New Tab"

### ISSUE THREAD

**Issue by SimonSapin** [piroor/treestyletab#1391]
## Short description

Sometimes, the title of a "View Source" tab in TST seems to be left to the default `New Tab`. This is not reliable, there may be a race condition. It seems to happen more often when the amount of source code to show is small (when the view source tab loads quickly).

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Navigate to https://perf-html.io/
 4. Press CTRL+U
 5. Observe a new tab open and navigate to `view-source:https://perf-html.io/`, its title in Firefox’s "normal" tabs is `https://perf-html.io/`

## Expected result

The tab’s title in TST is also `https://perf-html.io/`

## Actual result

Sometimes, the tab’s title in TST is `New Tab`

## Environment

 * Platform (OS): Linux x64
 * Version of Firefox: 58.0a1 (2017-09-26) 
 * Version (or revision) of Tree Style Tab: 2.0

**Comment by piroor** [comment]
79d9d68 seems to fix this problem for me.

**Comment by SimonSapin** [comment]
This looks fixed in 2.0.1. Thanks!
