### ISSUE TITLE
After logging in to https://web.whatsapp.com/, Tree Style Tab pegs the CPU (logging Security errors to Browser Console for failure to load blob: URIs from whatsapp)

### ISSUE THREAD

**Issue by dholbert** [piroor/treestyletab#1394]
## Short description
If Tree Style Tab sidebar is open when I visit whatsapp web, I get zillions of copies of this warning (just spammed over and over to my error console, forever, as fast as it can):
> Security Error: Content at moz-extension://a676caf2-d944-4d70-af13-422f66ae4f5e/sidebar/sidebar.html may not load data from blob:https://web.whatsapp.com/...{some guid}...

It pegs the CPU trying to log so many copies of the warning.

## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install TST.
 3. Visit https://web.whatsapp.com/
 4. Log in by scanning the QR code with the WhatsApp app on your phone. (Open the already-logged-in WhatsApp app on your phone, and pick ":" menu at top right, and pick "WhatsApp Web", and then hit "+", and then scan the QR code that the web site is showing you)
 5. Watch your CPU usage, and (optional) open your browser console with Ctrl+Shift+J

## Expected result
Nothing special. If there's some security error that TST can't get around, it should fail once and stop trying, ideally.

## Actual result
Browser console shows "Security Error: Content at moz-extension://a676caf2-d944-4d70-af13-422f66ae4f5e/sidebar/sidebar.html may not load data from blob:https://web.whatsapp.com/...{some guid}..." being spammed over and over (with the red error-count just shooting up indefinitely).  And my CPU usage goes to 100%.

## Environment

 * Platform (OS): Ubuntu 17.10
 * Version of Firefox: 58.0a1 (2017-09-26) (64-bit)
 * Version (or revision) of Tree Style Tab: 2.0

**Comment by piroor** [comment]
Same to #1365?

**Comment by piroor** [comment]
I've installed WhatsApp messenger and created account, but I couldn't reproduce this problem with my blank firends-list...

**Comment by piroor** [comment]
Ah, OK, I've confirmed. When there is any message, the webpage changes the URL of favicon again and again infinitely and it triggers infinite loop on TST.

**Comment by piroor** [comment]
0ad9e1d should fix this problem. Thanks!

**Comment by dholbert** [comment]
Great, thanks!
