### ISSUE TITLE
[feature request] Add mode for full sized pinned tabs

### ISSUE THREAD

**Issue by Manishearth** [piroor/treestyletab#1395]
Tab Center Redux does this, with the pinned vertical tabs being the same size as the regular ones.

This means you can see their title contents, which is useful when a bunch of pinned tabs share the same favicon.

Would be nice to have an option that makes pinned tabs look like regular tabs (but with a pin icon, and outside of the scrolling area of the main tab list)

<img width="214" alt="image" src="https://user-images.githubusercontent.com/1617736/31028316-44921b3c-a502-11e7-9027-69350fe53d82.png">

**Comment by piroor** [comment]
It was internally possible but broken on TST 2.0 released version... By recent commits a new checkbox is added to the configuration and pinned tabs can be unfaviconized.

**Comment by Manishearth** [comment]
ooo thanks. approximately when will that be released?

(alternatively I guess I could just load from sources)

**Comment by piroor** [comment]
It ls already available on AMO.

**Comment by Manishearth** [comment]
This is great! Thanks.

Would you accept a pull request to have a little pin icon on these?

**Comment by Manishearth** [comment]
It seems like the "tab is active" highlight still applies to these, which looks kinda ugly

<img width="212" alt="image" src="https://user-images.githubusercontent.com/1617736/31051481-54531838-a61e-11e7-8def-38ec81f0951a.png">

**Comment by piroor** [comment]
By the commit 1edb8b4, now only faviconized tabs are highlighted.
