### ISSUE TITLE
tab close automatically when close another tab with the same domain

### ISSUE THREAD

**Issue by dupontjoy** [piroor/treestyletab#1396]
when we open two tabs with the same domain, it will show as parent-child style
then if I close the parent tab, the child tab is closed too
and this really causes some trouble
![5](https://user-images.githubusercontent.com/4965288/31043856-e6b944f0-a5f5-11e7-9033-380cae6352ab.jpg)

**Comment by piroor** [comment]
TST doesn't have such a domain-based feature, but it has a option: close all tabs of the tree always when the parent tab is closed. (By default, only the parent tab is closed when the tree is expanded.) Could you check TST's configuration?

**Comment by piroor** [comment]
I close this because outdated.
