### ISSUE TITLE
Font size is too big

### ISSUE THREAD

**Issue by Keith94** [piroor/treestyletab#1398]
The font size for tab labels and context menu items seems too big (i.e. not consistent with the rest of the UI).
For what it's worth I made the labels use `font: -moz-pull-down-menu;` and that fixed the issue.

**Comment by piroor** [comment]
For tab labels, is it same to #1379?

Anyway, 5d51ab2 applies `font: -moz-pull-down-menu` for the context menu.

**Comment by Keith94** [comment]
>For tab labels, is it same to #1379?

Nope, my system is using 100% font size so font looks normal in the horizontal tabs but is larger in TST

Default:

![2017-09-30_04-43-21](https://user-images.githubusercontent.com/5490615/31045498-207bc7dc-a59a-11e7-98aa-74dfd8e7f0b0.png)

`-moz-pull-down-menu`:

![firefox_2017-09-30_04-43-17](https://user-images.githubusercontent.com/5490615/31045507-40224778-a59a-11e7-936d-69159afacfeb.png)

**Comment by walkermalling** [comment]
Go to the add-on's preferences, and scroll down the the `Advanced` section, and set your font-size.  Example:
```
.tab .label {
  font-size: .75em;
}
```

**Comment by Keith94** [comment]
I know about that, but TST seems to use a default font size that's different from Firefox/system settings (see my screenshots) so I would say that it's a bug that should be fixed directly in TST.

With some themes the label even gets truncated at the bottom (for example the lowercase p here):
![image](https://user-images.githubusercontent.com/5490615/31207083-dc02c160-a930-11e7-82e0-c9f848a0bb30.png)

**Comment by piroor** [comment]
Because TST doesn't specify font size of tab labels by self, it seems to be defined by Firefox's default style sheet for addons.
https://dxr.mozilla.org/mozilla-central/source/browser/components/extensions/extension.css

Specifying small font size (smaller than `medium`) as the default value can have accessibility problem (it is possibly unreadable by people who have eye weakness), so `:root { font-size: medium; }` seems reasonable solution if it is effective for you. Could you try this? @Keith94

**Comment by Keith94** [comment]
Hmm, I didn't notice a difference between that code and default TST settings on my system. But, feel free to close this if it's not reproducible.

**Comment by piroor** [comment]
Oops, I meant that if `:root ...` is effective for you I'll add it to the next version of TST by default. It actually produces nothing on my environment, but if it reduces the font size on your environment, it will become the reason it should be done by TST.

**Comment by Keith94** [comment]
>if it reduces the font size on your environment

Doesn't seem to be effective. I added `:root { font-size: medium; }` to TST's style rules, but had no effect.

**Comment by piroor** [comment]
Hmm, then the font size of Firefox's tabs is possibly reduced by system setting. It is sized by `font: message-box` in all platforms. (I've confirmed this on Linux, with Browser Toolbox's inspector.)

https://dxr.mozilla.org/mozilla-central/source/toolkit/themes/linux/global/global.css#50
https://dxr.mozilla.org/mozilla-central/source/toolkit/themes/osx/global/global.css#37
https://dxr.mozilla.org/mozilla-central/source/toolkit/themes/windows/global/global.css#42

Could you try `:root { font: message-box; }`?

**Comment by Keith94** [comment]
>Could you try :root { font: message-box; }?

This had no effect for me in TST's style rules.
I changed it to `.tab .label { font: message-box; }` and then it worked for me.

**Comment by piroor** [comment]
I've found that extensions.css specifies the font size for `body` and it is under `:root` (`html`), so `:root ...` didn't work for you case. OK, anyway I specify `message-box` for default font size of TST. Thank you for researching!

**Comment by Keith94** [comment]
You're welcome, thank you for fixing it! :)
