### ISSUE TITLE
"Tabs on top" for tabgroups manager not working

### ISSUE THREAD

**Issue by pingomister** [piroor/treestyletab#140]
When using tree style tab together with tabgroups manager, is should be possible to place the tabgroups manager bar in the "tabs on top" position, next to the firefox button.

However, when tree style tab is placed on the left, it appears to disable "tabs on top" completely, and one is not able to place the tabgroups manager bar on top.

Is there any way around this?
Thank you

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
