### ISSUE TITLE
needing helo regards to the width adjustment

### ISSUE THREAD

**Issue by alphamales** [piroor/treestyletab#1400]
how do i adjust the width of tree style tab
i like the previous version because it allowed me tho customize the width on previous firefox
is there any solution to it?
see file for more clarification
![tst](https://user-images.githubusercontent.com/32416809/31046987-1817d6e4-a635-11e7-825e-41d818f7e284.jpg)

**Comment by nightpool** [comment]
click and drag the edge of the sidebar.

![width](https://user-images.githubusercontent.com/233815/31047788-ed4ad5ca-a5de-11e7-87ac-99f562f37d1a.gif)

**Comment by alphamales** [comment]
is there any way to fully minimize the width space? since in previous version in previous firefox,
you can minimize the width space by significant margin
although in web extension version, the width customization is limited

**Comment by Keith94** [comment]
Reduced width can be achieved with a workaround: https://github.com/piroor/treestyletab/issues/1373
