### ISSUE TITLE
Regression: tabs no longer work with bookmarks/history sidebar

### ISSUE THREAD

**Issue by ethus3h** [piroor/treestyletab#1402]
## Short description

In Firefox 57, because the tabs open in the sidebar, it is not possible to use bookmarks or history at the same time as tabs, or to have them on different sides of the window.

## Environment

 * Platform (OS): GNU/Linux
 * Version of Firefox: 57 developer edition
 * Version (or revision) of Tree Style Tab: 2.0.1

**Comment by piroor** [comment]
It is a limitation of Firefox's WebExtensions API itself. See also: [1328776 - Provide ability to show multiple sidebar contents parallelly](https://bugzilla.mozilla.org/show_bug.cgi?id=1328776 "1328776 - Provide ability to show multiple sidebar contents parallelly")

**Comment by perdolka** [comment]
TST Bookmarks Subpanel - awesome addon :)
