### ISSUE TITLE
[feature request/regression] Middle-click to open new tab

### ISSUE THREAD

**Issue by auscompgeek** [piroor/treestyletab#1403]
## Short description
Firefox allows for middle-clicking the tab bar (including legacy TST) to open a new tab.
WebExtensions TST does not allow for open new tabs in this fashion.

## Steps to reproduce
1. Start Firefox with clean profile.
2. Install TST.
3. Middle-click on empty space in TST sidebar.

## Expected result
A new tab is opened.

## Actual result
Nothing happens.

## Environment
* Platform (OS): Arch Linux
* Version of Firefox: 57.0b4 (Developer Edition)
* Version (or revision) of Tree Style Tab: 2.0.1

**Comment by piroor** [comment]
Done by b96f378. Thanks!
