### ISSUE TITLE
TST not using firefox's Tab warming feature

### ISSUE THREAD

**Issue by mustaqimM** [piroor/treestyletab#1405]
## Short description
It seems to me that TST isn't using [tab warming](https://bugzilla.mozilla.org/show_bug.cgi?id=1385453) to switch tabs quicker. Perhaps it's my imagination but switching tabs feel slightly slower from TST than using the tab bar.
I don't know if WebExtensions can access this feature or if it's being tracked for future use.
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Click on a tab to switch to it.
 4. 

## Expected result
Switch tabs faster with native firefox tab warming
## Actual result
Slower to switch when using TST

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 58 (Nightly)
 * Version (or revision) of Tree Style Tab: 2.0.1

**Comment by TheSweetLily** [comment]
It definitely doesn't. 
The old legacy TST version worked with warming, though.

**Comment by piroor** [comment]
Dup of #1337

**Comment by mustaqimM** [comment]
@piroor I don't think #1337 is related to tab war`m`ing. Warming is related to loading tab contents in the background when moused over. See [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1385453)

**Comment by piroor** [comment]
Oops, sorry...

**Comment by piroor** [comment]
TST updates its tabs based on the WebExtensions API `tabs.onActivated`. I think I can highlight a clicked tab immediately before the event is actually fired. (But you'll see a mismatched combination while you are trying to switch tabs - tabs are updated but the content area is not.)

**Comment by piroor** [comment]
Ah, I've realized what means this issue. Firefox now speculatively loads content of tabs on the memory as "warming-up" and show it immediately when the tab is actually activated. Sadly there is no way to notify Firefox to preload a tab speculatively via WebExtensions API for now, so we need a new API.

**Comment by piroor** [comment]
I've found a bug for it: [1402256 - WebExtension API to 'warm up' a tab](https://bugzilla.mozilla.org/show_bug.cgi?id=1402256 "1402256 - WebExtension API to 'warm up' a tab")

**Comment by mustaqimM** [comment]
[Tab warming has been enabled by default on Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1423220)

**Comment by irvinm** [comment]
@piroor is there more to do here?

**Comment by piroor** [comment]
TST 3.5.6 already contains a code to call the API, so this looks to be fixed.
