### ISSUE TITLE
Colour of highlighted tab in "Plain" and "Flat" styles hides the tab loading indicator

### ISSUE THREAD

**Issue by nnethercote** [piroor/treestyletab#1406]
In the "Plain" and "Flat" styles, the tab highlight color is a medium blue. This is the same, or almost the same colour as Firefox 57's bouncing tab loading indicator, which means you can't see the indicator.

The workaround is to use a different style. "Mixed" uses a much lighter shade of blue and so is better, but I was a bit confused during tab loading before I realized the problem and switched to it.

The obvious fix is to change the shade of blue used in "Plain" and "Flat".

Alternatively, the number of styles could be reduced. I honestly cannot see any difference between "Plain" and "Flat", and "Mixed" is also very similar, differing only in the tab highlight colour and a very subtle gradient effect on tabs. "Vertigo" and "Sidebar" are also similar, except they lack tab outlines and "Sidebar" is more compact and has a slightly different background colour. (In contrast, "Metal" and "Plain Dark" are very different.)

This is all on Firefox 58 on Mac with TST 2.0. On Linux it's a similar story but the tab highlight and tab loading indicator colour is orange instead of medium blue!

**Comment by piroor** [comment]
8ebb5db should fix this. Thanks!
