### ISSUE TITLE
TST doesn't inherit some settings in a second Firefox window

### ISSUE THREAD

**Issue by hyiltiz** [piroor/treestyletab#1407]
## Short description
Some custom options fall back to default in a second Firefox window.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST 2.0.1.
 3. Open Firefox Developer Edition. Use this settings for TST #1371.
 4. Now open a new Firefox window (Menu>Fire>New Window)
 5. In the new window, create a tree of tabs. Close the parent.

## Expected result
The parent is replaced by a dummy tab.

## Actual result
A dummy tab is created. However, the 1st child is promoted as the parent node, rather than the dummy tab being the parent.

## Environment

 * Platform (OS): OSX 10.11.6
 * Version of Firefox: Firefox 57.0 Developer Version
 * Version (or revision) of Tree Style Tab: Tabtree 2.0.1 (Sept. 29, 2017)

**Comment by piroor** [comment]
Thanks. The commit ca6bc97 should fix this.

**Comment by hyiltiz** [comment]
A single line of code! Nice. I'll test once I get the commit in this Firefox.
