### ISSUE TITLE
[WebExtensions] auto-group tabs potentially breaks tree controls.

### ISSUE THREAD

**Issue by MMeent** [piroor/treestyletab#1408]
## Short description
Spamming new tabs might result in broken trees when auto-group tabs is active

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Check the "auto-group tabs opened in [x] time" setting, ensure it is on.
 4. Spam-open a few tabs, each within [x] time from the last, but the last being later than the first + [x] time. 
5. After one or a few tries of spamming new tabs, there will be a tree which looks like the following:

    - New Tab [1]
        - \> New Tabs and more
            - New Tab
            - New Tab
    - \> New Tab and more [2]
        - New Tab

    Please note that "New Tab" [1] has no arrow when this happens, and that "New Tab and more" [2] also controls the opening/closing of the tree of "New Tab" [1].

## Expected result
New Tab[1] should have had controls for collapsing/opening of it's subtree, and the groups should've been top-level, not nested under a tab. 

## Environment

 * Platform (OS): Windows
 * Version of Firefox: 57.0b3
 * Version (or revision) of Tree Style Tab: 2.0.1

**Comment by piroor** [comment]
In this case, order of tabs seems broken. The "parent tab without twisty" is actually not a parent, instead the tab "New Tab and more [2]" is the real parent. All descendant tabs should be placed after the parent, but by some (unknown) reasons, they are placed before the parent - or the parent is unexpectedly placed after descendants.

**Comment by piroor** [comment]
7e48516 should fix this.
