### ISSUE TITLE
Out Of Order Tree

### ISSUE THREAD

**Issue by nightpool** [piroor/treestyletab#1411]
## Short description

Sometimes, in the WebExtension version, the ordering of tabs displayed by TreeStyleTabs can get "out of sync" with what TST considers the actual hierarchy to be. This can cause many confusing behaviors.

-----
<img width="300" alt="image" src="https://user-images.githubusercontent.com/233815/31095386-ae8b681e-a786-11e7-9b0c-b60e3785fd95.png">
This is after opening 1 of 2 collapsed trees. See how the 5 tabs look like they're under "Twitter", but are actually under Cybrespace?

-----
<img width="300" alt="image" src="https://user-images.githubusercontent.com/233815/31095422-c8d63672-a786-11e7-9da6-4dd45402c036.png">
This is what you see after clicking on the "twitter" tab.

-----
<img width="252" alt="image" src="https://user-images.githubusercontent.com/233815/31095376-a72894f2-a786-11e7-922b-cfb069a9927a.png">
This is what happens when you open a new tab 

after closing the new tab, you end up at the NEXT sibling down—a potentially large jump, depending on the size of the tree you're jumping over

## Steps to reproduce

1. Fresh Firefox Profile
1. Install TST
1. select "Open new blank tabs as a sibling of the current tabs"
1. select "Insertion position of new child tabs > No Control (respect the decision of firefox)" (this is to avoid the weird "jumping" behavior that happens when you click on links)

## Expected result

That TST opens new *sibling* tabs *below* the current tree, and furthermore that it maintains and displays it's internal state consistently even when the order changes (for example, if you're using both TST and the tab bar, like I do, it's trivial to use the tab bar to drag a child tab out of it's group, which *should* either remove it from the group or move it within the group, but instead causes this behavior. Trees should never be noncontinuous)

## Actual result

That the tree is "out of order", and children of earlier tabs come AFTER later parents, so for example, this tree

```
 - a
   - a1
   - a2
   - a3
 - b
 - c
   - c1
   - c2
```

should never be displayed as

```
 - a
   - a1
   - a2
 - b
 - c
   - c1
   - a3
   - c2
```

or 

```
 - a
   - a1
   - a2
   - a3
 - c
 - b
   - c1
   - c2
``` 

## Environment

 * Platform (OS): Mac OS
 * Version of Firefox: Firefox Nightly 58.0a1 `Build identifier: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:58.0) Gecko/20100101 Firefox/58.0`
 * Version (or revision) of Tree Style Tab: 2.0.1

**Comment by piroor** [comment]
Thanks. The commit 6e7d67d should fix this problem for the case when the current tab is a root tab (which has no parent).
