### ISSUE TITLE
"Loading" animations not synchronized

### ISSUE THREAD

**Issue by RalfJung** [piroor/treestyletab#1412]
## Short description

When there are multiple tabs loading, in the normal Firefox tabbar, the animation shown as tab icon is synchronized -- i.e., all these blue dots, as they move around, hot the left/right end of their movement at the same time.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open multiple tabs that load long enough such that you can see multiple "loading" animations.

## Expected result

The animations should all be synchronized.

## Actual result

They are not synchronized.

## Environment

 * Platform (OS): Linux (Debian testing amd64)
 * Version of Firefox: 57.0b4
 * Version (or revision) of Tree Style Tab: 2.0.1

**Comment by piroor** [comment]
How Firefox does that?

**Comment by piroor** [comment]
It is done here: https://dxr.mozilla.org/mozilla-central/rev/11fe0a2895aab26c57bcfe61b3041d7837e954cd/browser/base/content/tabbrowser.xml#620

**Comment by piroor** [comment]
Done by 9886c01. Thanks!
