### ISSUE TITLE
Not working with other extensions for opening tabs

### ISSUE THREAD

**Issue by ghmv** [piroor/treestyletab#1413]
## Short description

When a link is opened in a new tab by other extensions ([Right Click Opens Link New Tab](https://addons.mozilla.org/cs/firefox/addon/right-click-link-new-tab/), [Tap To Tab](https://addons.mozilla.org/cs/firefox/addon/tap-to-tab/)) instead of a standard way (middle click, context menu Open link in a new tab), it is not opened as a child tab of the originating tab but as an indipendent tab (or a sibling tab if the originating tab is already a child).

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install Right Click Opens Link New Tab / Tap To Tab.
 4. Click on any link by right click / double touch.

## Expected result

Tabs opened by other extensions should be child tabs.

## Actual result

They are indipendent or sibling tabs.

## Environment

 * Version of Firefox: 57.0b5
 * Version (or revision) of Tree Style Tab: 2.0.1
 * Version of Right Click Opens Link New Tab: 0.0.3
 * Version of Tap To Tab: 0.3.2

**Comment by piroor** [comment]
[Tabs opened with `openerTabId` option will become children of the current (or something) tab](https://github.com/piroor/treestyletab/wiki/API-for-other-addons#open-new-child-tab-from-a-specific-tab), so those addons need to be updated to use the option for Firefox 57 and later.

**Comment by piroor** [comment]
Because it is not a TST problem, I've marked this "invalid". Sorry.
