### ISSUE TITLE
[Feature request] Update the loading animation to the current spec (bug 1399111)?

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#1415]
## Short description
[Bug 1399111 - new tab burst animation in background tabs is too eye catch](https://bugzilla.mozilla.org/show_bug.cgi?id=1399111) introduces a new loading animation colour for background tabs. It has been uplifted to Firefox 57.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a background tab.
 4. Observe the loading animations in TST's side bar and Firefox's tab bar

## Expected result
The animations have the same colour.

## Actual result
They are not.

## Environment

 * Platform (OS): Win10 CU
 * Version of Firefox: Nightly 2017-10-03 build
 * Version (or revision) of Tree Style Tab: 2.0 latest nightly (2017-10-04 06:17)

**Comment by piroor** [comment]
Bursting animation effect is now implemented by b2e3d89 and 83f6ff8. Thank you for pointing!
