### ISSUE TITLE
Container tabs feature not working with the webextension

### ISSUE THREAD

**Issue by lgp171188** [piroor/treestyletab#1416]
## Short description
Container tabs feature not working with the webextension

## Steps to reproduce

 1. Start FirefoxDeveloperEdition (57.0b5) with clean profile.
 2. Install TST webextension from addons.mozilla.org or the latest webextension nightly.
 3. In the new tab button in the TST sidebar there is small dropdown at the right for selecting the container. Select a container and open a new tab.
 4. Open GitHub in the new tab and login.
5. Select a different container profile and open a new tab.
6. Open GitHub in the new tab.

## Expected result
The tab opened under step 5 will not know anything about the logged in session in the tab opened under step 3 as they are in different containers.

## Actual result
The logged in session in the tab opened under step 3 is recognized in the new tab opened under step 5.
This means that the container tab functionality is not working. Also, there are no color indicators on the tab to indicate any container profiles being used.

## Environment

 * Platform (OS): Mac OS X 10.12.6
 * Version of Firefox: Firefox Developer Edition 57.0b5
 * Version (or revision) of Tree Style Tab: 04/10/2017 Webextension Nightly and also the Webextension version from addons.mozilla.org

**Comment by piroor** [comment]
I couldn't reproduce this problem. My environment is:

 * Windows 10 (Creators Update)
 * Firefox Developer Edition 57.0b5
 * TST 2.0.2 (released version)
 * Clean profile

**Comment by lgp171188** [comment]
Thanks for the quick update. When I run Firefox in a clean profile things work fine as expected. But in permanent private mode ('Always use private browsing mode' option enabled), this doesn't work and the issue is reproducible. Since I am not sure if this is expected behaviour or not, I will leave it to you @piroor to take a call on that.

**Comment by lgp171188** [comment]
Closing this issue and opened a separate one as the issue happens only in permanent private browsing mode

**Comment by lgp171188** [comment]
https://github.com/piroor/treestyletab/issues/1458
