### ISSUE TITLE
Opening firefox from opening a local html file breaks the tab tree structure

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1419]
## Short description
Opening firefox from opening a local file (like a local html file) breaks the tab tree structure, usually flattening the tree.

## Steps to reproduce

 1. Start Firefox with clean profile
 2. Install TST
 3. Have a sample local html file ready, like a copy of thin.npr.org. Doesn't have to be an html file - OS just needs to be able to open the file with Firefox - but html is easiest way to replicate.
 3. about:config, browser.startup.page: 1 => 3 ("Show your windows and tabs from last time")
 4. Open up some tabs like:
```
a
\-- b
|   \-- c
|-- d
\-- e
```
 5. Close Firefox.
 6. Open sample local html file with Firefox (in Windows, typically double clicking the html file)

## Expected result
Tab tree structure is preserved, with the addition of the sample html file:
```
a
\-- b
|   \-- c
|-- d
\-- e
samplehtml
```

## Actual result
Tab tree structure breaks, usually flattening the whole tree (although occasionally I've seen some structure, but it's always messed up in some way):
```
a
b
c
d
e
samplehtml
```

## Environment

 * Platform (OS): Windows 10 Pro, Version 1709, Build 16299.0
 * Version of Firefox: Developer Edition 57.0b5
 * Version (or revision) of Tree Style Tab: 2.02

**Comment by lbmaian** [comment]
This is a serious enough issue that I know longer set Firefox as my default web browser app in Windows while this bug still stands. First discovered this when restarting Windows in Safe Mode for debugging a hardware issue, and upon startup, Windows opened a safe mode help page in the default browser, which was firefox for me, thus ruining my TST tab tree structure.

**Comment by piroor** [comment]
The commit 93de128b7cd9720a82b9cc86c37bb942589af8ff should fix this. For safety I didn't apply saved tree structure for tabs when the number of tabs are not same. Thanks!

**Comment by lbmaian** [comment]
Thanks, I've confirmed that the fix works!
