### ISSUE TITLE
Dragging local file to Tree Style Tab sidebar doesn't work

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1420]
## Short description
Dragging local file to Tree Style Tab sidebar doesn't work like it used to in the legacy version or like the vanilla tab bar:
- Dragging onto a tab doesn't replace it with the local file and its contents
- Dragging before/after/between tabs doesn't insert a new tab with the local file and its contents

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Have a sample local html file ready, like a copy of thin.npr.org. Doesn't have to be an html file - OS just needs to be able to open the file with Firefox - but html is easiest way to replicate.
 4. Drag local file to Tree Style Tab sidebar...
     1. Onto existing tab
     2. Before/after/between tabs

## Expected result
i. Replaces the tab with the local file and its contents.
ii. Inserts a new tab with the local file and its contents in the correct position.

## Actual result
i. Nothing happens.
ii. Nothing happens.

Note: This does still work as expected in the vanilla tab bar. Dragging a file onto the content window itself also still works as expected.

## Environment

 * Platform (OS): Windows 10 Pro, Version 1709, Build 16299.0
 * Version of Firefox: Developer Edition 57.0b5
 * Version (or revision) of Tree Style Tab: 2.02

**Comment by piroor** [comment]
Currently this is impossible due to limitations of WebExtensions. There is a bug about this: [1266960 - Extensions can not load file: URLs](https://bugzilla.mozilla.org/show_bug.cgi?id=1266960 "1266960 - Extensions can not load file: URLs")

**Comment by piroor** [comment]
I close this because it is not a problem of addon side.
