### ISSUE TITLE
Tab sound indicator does not update

### ISSUE THREAD

**Issue by mparkms** [piroor/treestyletab#1421]
## Short description
The icon that shows if a tab is playing audio doesn't update unless you close and reopen Tree Style Tab.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Go to YouTube and play any video with sound.
 4. Close TST and reopen it.
 5. Pause the video.

## Expected result
The icon should display as soon as the YouTube video starts playing. Pausing the video should cause the icon to go away.

## Actual result
The icon does not display when the video plays. The icon appears after closing and reopening TST, but does not go away when the video is paused until TST is closed and reopened again.

## Environment

 * Platform (OS): Windows 10 x64
 * Version of Firefox: 57.0b5 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.0.1

**Comment by piroor** [comment]
Thanks! This is a regression on 2.0.2 and the commit 65d2f90 should fix this.
