### ISSUE TITLE
Dummy tab created when Home page contains multiple tabs

### ISSUE THREAD

**Issue by Wagk** [piroor/treestyletab#1422]
## Short description
I currently have my home page string set to `https://calendar.google.com|https://inbox.google.com/|https://keep.google.com/`

Whenever I open a new window an additional tab with an address resembling `moz-extension://82b38832-a54a-466c-9902-64e936d0d5f6/resources/group-tab.html?title=afd9cd2c-f3c9-47bf-89fd-72c5f4f18378/confirm-page.html%3Furl%3Dhttps%253A%252F%252Fcalendar.google.com%252F%26cookieStoreId%3Dfirefox-container-1%20and%20more&temporary=true` would appear, and remain until I manually close it.

I could not find any documentation on whether this is intended. Is there a way to prevent this?

**Comment by piroor** [comment]
The commit e9c4a30 should fix this problem. Now new tabs opened while 500msec when a new window is opened are not grouped. (However, if your PC is slow, 500msec can be too short delay. I'll add a configuration UI to change this delay...)

**Comment by piroor** [comment]
Done by 94aecc8. Thanks!
