### ISSUE TITLE
TST-we does not scroll selected tab into view when reopen TST sidebar

### ISSUE THREAD

**Issue by alice0775** [piroor/treestyletab#1424]
## Short description
When reopen TST sidebar, TST-we toolbar does not scroll selected tab into view.
i.e. TST does always scroll to top.

## Steps to reproduce

 1. Start Nightly58.0a1 with clean profile.
 2. Install TST-we
 3. Open many tabs so that TST has vertical scrollbar
 4. Select a last tab(for ex.)
 5. Close TST sidebar and reopen TST sidebar 

## Expected result
The selected(current) tab should be visible in TST sidebar

## Actual result
TST does always scroll to top.
So, The selected(current) tab is invisible in TST sidebar. Manual scroll needs.

## Environment

 * Platform (OS):  Windows10 CU 64bit
 * Version of Firefox:  Nightly58.0a1
 * Version (or revision) of Tree Style Tab: 2.0.2

**Comment by alice0775** [comment]
Un-check "Enable animation effects" seems to fixe the problem.

**Comment by piroor** [comment]
Done by 208105e. (It is slow as #1425, but actually done.) Thanks!
