### ISSUE TITLE
TST-we is too slow to rebuild tree when reopen TST sidebar

### ISSUE THREAD

**Issue by alice0775** [piroor/treestyletab#1425]
## Short description
SSIA

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open may tabs(more than 30tabs)
 4. Toggle TST sidebar

## Expected result
The TST sidebar should appear as fast as bookmark sidebar

## Actual result
It takes too much time(1-3sec)

## Environment

 * Platform (OS):  Windows10 CU 64nit
 * Version of Firefox: Nightly58.0a1 Build ID 	20171005100211
 * Version (or revision) of Tree Style Tab:  2.0.2

**Comment by piroor** [comment]
Current result of `gMetricsData.toString()` on my environment:

startup (reload):

```
0: Loaded
150: earlyInit start
0: earlyInit end
32: init start
4: configs.$loaded
180: applyStyle
305: waitUntilBackgroundIsReady and retrieveAllContextualIdentities
60: treestyletab:pull-tab-id-tables
84: rebuildAll
408: inheritTreeStructure
343: treestyletab:request-registered-addons
110: treestyletab:request-scroll-lock-state
19: getting scroll-position
0: init end
```

reopen sidebar:

```
0: Loaded
98: earlyInit start
0: earlyInit end
17: init start
3: configs.$loaded
50: applyStyle
98: waitUntilBackgroundIsReady and retrieveAllContextualIdentities
4: treestyletab:pull-tab-id-tables
171: rebuildAll
482: inheritTreeStructure
315: treestyletab:request-registered-addons
61: treestyletab:request-scroll-lock-state
7: getting scroll-position
0: init end
```

`inheritTreeStructure()` and `treestyletab:request-registered-addons` take time a lot.

**Comment by piroor** [comment]
`treestyletab:request-registered-addons` simply does: `browser.runtime.sendMessage()` (in sidebar) => `Promise.resolve(gExternalListenerAddons)` (in background page) so I cannot believe that this takes much time. Hmm...

**Comment by seascape** [comment]
I have a browser with over 500 tabs. TST takes around 50-60 seconds to finish loading, give or take.

**Comment by kkot** [comment]
I have about 600 tabs an it takes 4 seconds to rebuild tree. It is not bad but of course faster is better especially after switching from History or Bookmarks back to Tree Style Tab.

**Comment by piroor** [comment]
On 2.2.0, more optimization has landed.

**Comment by gagarine** [comment]
V 2.3.0 seem faster but still to slow ;). Also the loading is kind of strange: first the tabs appear, then the tree is made until the end their is a loader on top of the UI. This cause certainly lot of unnecessary repaint.

I didn't look at the code, but can't we keep a tab tree in memory and update it when tabs are opens?

Say that I don't understand why making this tree take so long. With 10 tabs it should take 0.001ms.

But we shouldn't draw the UI before data are ready I think.

**Comment by piroor** [comment]
There are two cases of tree restorations.

 1. (relatively) quickly restored case
    * when you disable and enable TST
    * when you configure Firefox to restore last tabs and windows automatically on the startup
    * when you restart Firefox to apply updates
 2. very slowly restored case
    * when you choose "Restore Previous Session" from the hamburger menu
    * when you restore tabs after crash

The reason why case 1 is quick is: TST can assume that it is window restoration and can skip some operations. The restoted window have a session data stored by TST: the structure information of whole tabbar. On the other hand, there is no such hint to assume it is window restoration at case 2, so TST need to restore tree from relative relations of tabs step by step. WebExtensions doesn't have any event to notify Firefox is going to restore window at case 2. If we know that the restoration is started, we'll  make the case 2 more quickly...

**Comment by SXZ1** [comment]
Stupid question: will this bug help?

https://bugzilla.mozilla.org/show_bug.cgi?id=1413525

**Comment by piroor** [comment]
The bug 1413525 seems talking about APIs for addons like Session Manager. It won't help TST if no any new event is notified when a session is going to be restored, because TST won't include such session management system by self (it is quite out of the target range of this project).

**Comment by gagarine** [comment]
> There are two cases of tree restorations
But this bug is not about restorations, it's about the tree stye pane slow to build when opened.

![bkw2s2w8q7](https://user-images.githubusercontent.com/164074/33497075-e4d86ba4-d6cc-11e7-9f17-6708fa7dacc0.gif)

**Comment by piroor** [comment]
Oops, sorry, I misunderstood this to another issue about session restoration...

**Comment by piroor** [comment]
https://github.com/piroor/treestyletab/tree/reopen-tabbar-from-cache experimental branch to try caching built DOM tree. Still there are many problems around information not stored as attributes - Firefox stores some information to HTML elements just as a JS property and it won't be serialized and need to be restored manually.

Or, possibly I need to rewrite everything based on virtual DOM, but it is very hard work for me and it will be the the version 3.0.

**Comment by piroor** [comment]
Now the cache system is merged to master, but I think we need more doogfooding.

**Comment by piroor** [comment]
I close this because outdated.
