### ISSUE TITLE
"Close Other Tabs" on normal tab also closed pinned tabs

### ISSUE THREAD

**Issue by alice0775** [piroor/treestyletab#1426]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open few tabs
 4. Make pinned tab
 5. Perform "Close Other Tabs" on normal tab

## Expected result
Close other tabs, but not pinned tabs

## Actual result
Pinned tabs also be closed

## Environment

 * Platform (OS): Windows10 CU 64bit
 * Version of Firefox: Nightly58.0a1 Build ID 20171005100211
 * Version (or revision) of Tree Style Tab: 2.0.2

**Comment by piroor** [comment]
Done by bee48b8. Thanks!
