### ISSUE TITLE
Clicking "Tree Style Tab" menu in TST sidebar  reloads tab

### ISSUE THREAD

**Issue by alice0775** [piroor/treestyletab#1428]
## Short description
SSIA

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Narrow the width of the sidebar as much as the TST tab context menu width, if needed
 4. Right click on a tab in TST sidebar
 5. Click  "Tree Style Tab" menu 

## Expected result
Should not reload tab.
Stay open context menu and sub menu.

## Actual result
Tab reloads unexpectedly.
TST context menu also unexpectedly closed.

## Environment

 * Platform (OS):  Windows10
 * Version of Firefox: Nightly5.0a1 Build ID 	20171005100211
 * Version (or revision) of Tree Style Tab: 2.0.2

**Comment by alice0775** [comment]
The problem is that 1st submenu item overlap with  "Tree Style Tab" .
see screen shot https://imgur.com/H36effI .
And then mouse up triggers 1st submenu item command.

**Comment by piroor** [comment]
By recent commits, now TST ignores click event on these elements:

 * Menu item including submenu
 * Element without id
 * Element under half-transparent container (like animating submenu)

Thanks!
