### ISSUE TITLE
Tab loading animation does not synchronize

### ISSUE THREAD

**Issue by alice0775** [piroor/treestyletab#1430]
## Short description
#1412 doed not fix the promlem

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Right click on a bookmark folder which contains many bookmarks (20-30 bookmarks)
 4. Choose "Open All in Tabs"

## Expected result
Tab loading animation should synchronize

## Actual result
Despite having finished reading all the tabs, Tab loading indicator is animating forever.
see screenshot https://imgur.com/rZpiuXH

## Environment

 * Platform (OS): Windows10 CU 64bit
 * Version of Firefox: Nightly58.0a1 Build ID 	20171005100211
 * Version (or revision) of Tree Style Tab: 2.0.2

**Comment by alice0775** [comment]
And another str

  1.  Start Firefox with clean profile.
  2. Install TST.
  3. Open https://www.fxsitecompat.com/en-CA/versions/57/ in 1st tab
  4. Right click on the page and choose "View Page Source"
  5. If not reproduce, close the  "View Page Source" tab and repeat step4.

Expected result
Tab loading animation should synchronize

Actual result
Reproducible: 1 of 3
Despite having finished reading all the tabs, Tab loading indicator is animating forever.

**Comment by piroor** [comment]
Finally I've found that processing of tabs.onUpdated asynchronously caused the problem. d1fc1fd should fix this for me.
