### ISSUE TITLE
Creating new tree (new first child tab) sometimes doesn't collapse other expanded trees

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1431]
## Short description
Creating new tree (new first child tab) sometimes doesn't collapse other expanded trees

## Steps to reproduce
First off, this is potentially related to #1429, since while trying to produce edge cases there, I encountered this. The following isn't a complete follow-on of an edge case mentioned there, but it's close.

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Tree structure:
```
A
\- B (collapsed)
C (selected)
\- D
```
 4. Close tab D
 5. Select tab A to expand the A/B tree
 6. Select tab C
 7. Open child tab

## Expected result
The A/B tree is collapsed.

## Actual result
The A/B tree is NOT collapsed.

It also seems "stuck" in this state, where closing child tabs of A and C and opening new child tabs still leaves both trees open. To "unstick" this, a novel tree needs to be created, whether a new root tree, or creating a grandchild tab.

## Environment

 * Platform (OS): Windows 10 Pro, Version 1709, Build 16299.0
 * Version of Firefox: Developer Edition 57.0b5
 * Version (or revision) of Tree Style Tab: 2.02

**Comment by piroor** [comment]
This happens because the tab C is lost its "subtree-collapsed" state when the D is attached (*note that all new tabs have the state internally). Thus we need to set the state for existing parent tab when it loses all children.

**Comment by piroor** [comment]
Fixed by 65d2aa9. Thanks!
