### ISSUE TITLE
Open new blank tab as next sibling of last root tree inserts new tab in wrong position

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1432]
## Short description
Open new blank tab as next sibling of last root tree inserts new tab in wrong position

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set TST option for "Open new blank tab as" to "the next sibling of the current tab"
 4. Tree structure:
```
A (selected)
\- B
```
 4. Open new tab with new tab button (NOT Ctrl-T)

## Expected result
Tree structure:
```
A
\- B
new (selected)
```

## Actual result
Tree structure:
```
A
new (selected)
\- B
```

## Environment

 * Platform (OS): Windows 10 Pro, Version 1709, Build 16299.0
 * Version of Firefox: Developer Edition 57.0b5
 * Version (or revision) of Tree Style Tab: 2.02

**Comment by piroor** [comment]
Thanks, 2007fc1 should fix this.
