### ISSUE TITLE
Undo close tab on a closed root tab will insert the restored tab (and its children) as a child of the previous root tree

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1433]
## Short description
Undo close tab on a closed root tab will insert the restored tab (and its children) as a child of the previous root tree

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Tree structure:
```
A
\- B
C
\- D
...
```
 4. Close tab C
 5. Undo close tab

## Expected result
Tree structure:
```
A
\- B
C
\- D
...
```

## Actual result
Tree structure:
```
A
\- B
\- C
    \- D
...
````

## Environment

 * Platform (OS): Windows 10 Pro, Version 1709, Build 16299.15
 * Version of Firefox: Developer Edition 57.0b5
 * Version (or revision) of Tree Style Tab: 2.02

**Comment by piroor** [comment]
Thanks. 8bbcc35 should fix this.
