### ISSUE TITLE
Tabs would not sync between native and TST

### ISSUE THREAD

**Issue by alice0775** [piroor/treestyletab#1434]
## Short description
Maybe, this is rare case.
See screenshot https://imgur.com/gedGf6V

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open multiple New Tab (Ctrl+T)
 4. Close tabs quickly(middle mouse click on tab in native tabbar)

## Expected result
Ghost tabs(unable to select/close) appear in TST sidebar

## Actual result
Tabs should be synchronized
Toggle TST sidebar will fix the problem.

## Environment

 * Platform (OS):  Windows10 CU 64bit
 * Version of Firefox:  Nightly58.0a1 Build ID 	20171005100211
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
I couldn't reproduce this problem with manual operations. Moreover, I tried following two scripts in the browser console, but I got nothing problem:

```javascript
for (let i = 0, maxi = 20; i < maxi; i++) gBrowser.addTab('about:blank?'+i);
```

```javascript
for (let i = 0, maxi = 20; i < maxi; i++) gBrowser.removeTab(gBrowser.selectedTab);
```

**Comment by piroor** [comment]
I close this because outdated. Now TST has ability to synchronize order of tabs between the sidebar and the native tab bar.
