### ISSUE TITLE
Undo close tab on a closed root tab can expand previous root tree

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1435]
## Short description
Undo close tab on a closed root tab can expand previous root tree - follow-on bug of #1433 

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Tree structure:
```
A
\- B (collapsed)
C
\- D
```
 4. Close tab C
 5. Undo close tab

## Expected result
Tree structure:
```
A
\- B (collapsed)
C
\- D
```

## Actual result
Tree structure:
```
A
\- B
C
\- D
```

That is, A/B tree is expanded.

Oddly enough, if I repeat the process of closing tab C and undo close tab, then the A/B tree collapses again.

## Environment

 * Platform (OS): Windows 10 Pro, Version 1709, Build 16299.15
 * Version of Firefox: Developer Edition 57.0b5
 * Version (or revision) of Tree Style Tab: Latest nightly as of commit f65ea7b1a02ddcb5ead6eac7a2ef5d6f2dfd495c

**Comment by piroor** [comment]
feb10c7 should fix this. This change improves "auto fix tree structure" behavior more intelligently. Thanks!
