### ISSUE TITLE
Duplicate tab of tree can create child tab instead of sibling tab

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1437]
## Short description
Duplicate tab of tree can create child tab instead of sibling tab

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST with default settings (including leaving "Except focus moving caused by current tab closing" enabled)
 3. Tree structure:
```
A
\-B (collapsed)
C (selected)
\-D
```
 4. Duplicate tab A via menu item

#### Expected result
```
A
\- B
A-dup
C
\-D (collapsed)
```

#### Actual result
Sometimes:
```
A
|- A-dup (selected)
\-B
C
\-D (collapsed)
```

Sometimes:
```
A
|-B
\- A-dup (selected)
C
\-D (collapsed)
```

Sometimes the expected result. It almost seems non-deterministic, or at least very hard to narrow down a consistent test case.

Once it gets into this state, it can sometimes be repeated by duplicating via either middle-click of reload button or the duplicate tab menu item.

## Environment

 * Platform (OS): Windows 10 Pro, Version 1709, Build 16299.15
 * Version of Firefox: Developer Edition 57.0b5
 * Version (or revision) of Tree Style Tab: Latest nightly as of commit f65ea7b1a02ddcb5ead6eac7a2ef5d6f2dfd495c

**Comment by piroor** [comment]
I couldn't reproduce this problem for now. Recent changes may solve this problem. Could you try the latest development build?

**Comment by lbmaian** [comment]
It's still happening occasionally on the latest nightly on that test case, but it happens more rarely now.

Here's a better test case that reproduces more reliably:
1. Empty session (Firefox starts with only home page)
2. Tree structure:
```
A
\- B
C (selected)
```
3. Duplicate tab A via menu item (NOT middle-clicking reload button)

Expected:
```
A
\-B
A-dup
C
```

Actual:
```
A
|- A-dup
\- B
C
```

**Comment by piroor** [comment]
Firefox's native feature uses `duplicateTabIn()`:

https://dxr.mozilla.org/mozilla-central/rev/2d7b8b5dd174bd9db5894c6cb770e05f83e95ee3/browser/base/content/browser.xul#92
https://dxr.mozilla.org/mozilla-central/rev/2d7b8b5dd174bd9db5894c6cb770e05f83e95ee3/browser/base/content/browser.js#2179
https://dxr.mozilla.org/mozilla-central/rev/2d7b8b5dd174bd9db5894c6cb770e05f83e95ee3/browser/base/content/browser.js#8612

There is no operation to move tabs.

On the other hand, TST simply does `browser.tabs.duplicate(this.contextTab.id)` via WE API and the API implementation does something different from `duplicateTabIn()`.

https://dxr.mozilla.org/mozilla-central/source/browser/components/extensions/ext-tabs.js#640

So extra `gBrowser.moveTabTo(newTab, nativeTab._tPos + 1);` operation seems to be the trigger of this issue.

**Comment by piroor** [comment]
There are multiple problems there.

 * tabs.tabMoved is fired for unnecessary cases. This has been fixed by 588133091a8cf3352f95f04dda762e6ab5398294.
 * Sometimes TST fails to detect duplicated tabs - those tabs are treated as simple new tabs. Getting `browser.sessions.getTabValue(aTabId, kPERSISTENT_ID)` sometimes return null for duplicated tabs because session information is not copied to the tab yet. Currently I have no idea about this...

**Comment by piroor** [comment]
[1394376 - Add option to resolve promise before tabs are completely loaded, for browser.tabs.duplicate()](https://bugzilla.mozilla.org/show_bug.cgi?id=1394376 "1394376 - Add option to resolve promise before tabs are completely loaded, for browser.tabs.duplicate()") will help to fix the second problem.

**Comment by piroor** [comment]
Anyway, by recent commits now duplicated tabs are detected more certainly. If TST successfully detect that the tab is duplicated, then the tab is opened at expected position for me. Otherwise the tab becomes a child of the tab A based on its moved position.

**Comment by lbmaian** [comment]
Installed the latest nightly, and the test case in https://github.com/piroor/treestyletab/issues/1437#issuecomment-334922023 still consistently results in a child tab. It also reproduces in 2.02. Which come to think of it is actually bug #1438 

Since this bug and #1436 and #1438 are related, should they be merged? And since it seems this can't be completely fixed without Firefox fixes, should this be labeled as a Firefox bug?

**Comment by piroor** [comment]
By recent changes, now duplicated tab seems to be shown in expected place correctly about this case, for me. After I researched I realized that there were mistakes around "move tab" operations so it possibly caused such a problem in some cases. (On the other hand, now the operation be comes slow due to https://bugzilla.mozilla.org/show_bug.cgi?id=1394376 and the difference I told at https://github.com/piroor/treestyletab/issues/1437#issuecomment-334952194 - this is unavoidable for now.) Could you try the latest development build again?

**Comment by lbmaian** [comment]
Thanks, it does seem fixed. The duplicate tab from the TST context menu is indeed slower than middle-clicking reload button or Firefox's context menu, but that's a separate problem.

Now the only buggy thing at the moment I can find is that some expanding/collapsing around certain duplicating cases. I'll file a separate issue on that.
