### ISSUE TITLE
Middle-click mouse-up action should only apply on element that was mouse-downed

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1439]
## Short description

Middle-click mouse-up action should only apply on element that was mouse-downed. Holding down middle-click on a tab or the tab-bar, moving the mouse anywhere else, then releasing the middle-click, performs the action on the tab/tab-bar/etc. that mouse-up occurred on. This behavior differs from vanilla tabs/tab-bar.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST. 

### Case I

 3. Hold down middle mouse button (mousedown) on a TST tab or tab bar
 4. Move mouse over to another tab X
 5. Release middle mouse button (mouseup)

### Case II

 3. Hold down middle mouse button (mousedown) on a TST tab or tab bar
 4. Move mouse over anywhere that's not a tab (empty part of tab bar, content window, toolbar, title bar, outside the browser, etc.)
 5. Release middle mouse button (mouseup)

## Expected result

Nothing happens

## Actual result

Case I: Tab X is closed

Case II: New tab is created

## Environment

 * Platform (OS): Windows 10 Pro, Version 1709, Build 16299.15
 * Version of Firefox: Developer Edition 57.0b5
 * Version (or revision) of Tree Style Tab: 2.02

**Comment by piroor** [comment]
Fixed by 32590f0. Thanks!

**Comment by lbmaian** [comment]
This is only partially fixed for on the latest nightly.

Test cases:

FIXED:
1. Mousedown tab, move cursor to another tab, mouseup: nothing
2. Mousedown tab bar, move cursor to tab, mouseup: nothing

NOT FIXED - all should do nothing:
1. Mousedown tab, move cursor to tab bar, mouseup: new tab
3. Mousedown tab, move cursor to empty space left of indented tab, mouseup: new tab
3. Mousedown tab, move cursor to content window, mouseup: new tab
4. Mousedown tab bar, move cursor to content window, mouseup: new tab
5. Mousedown empty space left of indented tab, move cursor to content window, mouseup: new tab
6. Mousedown empty space left of indented tab, move cursor to tab, mouseup: CLOSE TAB

FINE AS-IS:
1. Mousedown tab bar, move cursor to empty space left of indented tab, mouseup: new tab
2. Mousedown empty space left of indented tab, move cursor to tab bar, mouseup: new tab

**Comment by piroor** [comment]
67f2818 should fix the "NOT FIXED" cases: 1, 2, 4, and 6. 3 and 5 still there.

"FINE AS-IS?" cases seem surely as-is. TST treats the left blank area same to bottom blank area, except the left-clicked on left blank area to select a tab.

**Comment by piroor** [comment]
And 3bdc563 should fix 3 and 5. Could you try the latest development build?

**Comment by lbmaian** [comment]
Verified fixed on my end.
