### ISSUE TITLE
browser.webProgress is undefined

### ISSUE THREAD

**Issue by titoBouzout** [piroor/treestyletab#144]
Hi Piro, 

Just to inform, for some reason sometimes I get this error:

Error: browser.webProgress is undefined
Source file: chrome://treestyletab/content/windowHelper.js
Line: 558

What I do is:
I have two or move trees collapsed and want to close these via "multiple tab handler" by selecting the "X"
Exactly as shown in this picture:
http://dl.dropbox.com/u/9303546/extensions/tst/1.jpg
Then, the error popups and only one tree is closed:
http://dl.dropbox.com/u/9303546/extensions/tst/2.jpg

The "X" keeps selected, I guess the error stop the execution.

Regards,

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
