### ISSUE TITLE
TST nightly build cannot be initialised (TypeError: aTreeStructure is undefined)

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#1443]
## Short description
Recent nightly build of TST does not start up for me. However the one on AMO (2.0.2) still works in Nightly.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST nightly 2.0.2.5314
 3. (Optional) Restart Nightly

## Expected result
TST is working.

## Actual result
TST cannot be initialised. I can only see the loading animation in the middle of the tab bar. No tabs are shown.
Browser console shows `TypeError: aTreeStructure is undefined  tree-operations.js:1256:3` when I disable and re-enable the extension.

## Environment

 * Platform (OS): Win10 CU
 * Version of Firefox: Nightly 2017-10-06 2nd build
 * Version (or revision) of Tree Style Tab: nightly 2.0.2.5314

**Comment by piroor** [comment]
Thanks. 3ebac86 fixes this.
