### ISSUE TITLE
Restoring session can lose child tab if it was created right before exit

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1445]
## Short description
Restoring session can lose a tab in certain cases. All the cases have in common:
1. The lost tab is the last opened child tab
2. The parent of the lost tab is selected
3. The very last action taken in TST before exiting Firefox was creating that tab (which should lead to conditions 1 and 2)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Ensure Firefox restores session upon startup (options => "Show your windows and tabs from last time")

### Case I
 4. Tree structure created in order of tab letters (A, B, ...):
```
A
\- B (collapsed)
C (selected)
\- D
```
 5. Restart Firefox

### Case II
 4. Tree structure created in order of tab letters (A, B, ...):
```
A (selected)
|- B
\- D
C
```
 5. Restart Firefox

### Case III
 4. Tree structure created in order of tab letters (A, B, ...):
```
A (selected)
\- D
B
\- C (collapsed)
```
 5. Restart Firefox

### Case IV
 4. Tree structure created in order of tab letters (A, B, ...):
```
A
\- B (selected)
    \- C
```
 5. Restart Firefox

## Expected result
Tree structure and tab selection is restored as-is.

## Actual result
The last created tab is not restored and thus lost.

Also note that the selected tab can change after session restore. In particular, if tab X was selected before exit, it seems the root tree tab of tab X is selected upon restoring the session. This happens regardless of whether a child tab is lost (and is probably a separate bug).

### Case I
```
A
\- B (collapsed)
C (selected)
```

### Case II
```
A (selected)
|- B
\- C
```

### Case III
```
A (selected)
\- B
   \- C
```

### Case IV
```
A (selected)
\- B
```

## Environment

 * Platform (OS): Windows 10 Pro, Version 1709, Build 16299.15
 * Version of Firefox: Developer Edition 57.0b6
 * Version (or revision) of Tree Style Tab: Latest nightly as of commit 1562e17661fb3947128a7c9722f2f8b19a6d3d33

**Comment by piroor** [comment]
Hmm... On the latest Nightly 58, this problem doesn't happen for me. Any error message in the debug console when you open the last child tab? You'll see the console by these steps: go to "about:debugging", find TST item in the list, click the "Debug" link, and choose the "Console" tab. If you check to "Debug mode" you'll see more logs.

**Comment by lbmaian** [comment]
Downloaded latest Firefox nightly (58.0a1 (2017-10-09)) AND TST nightly (812348e94d4fdfc673047a53305c48f07b77bcc6), and it still reproduces for me. Also confirmed that this still happens on latest Firefox dev edition (57.0b6).

After testing this more, it seems that the browser needs to be closed within a couple seconds after opening the last tab to reproduce this. If I wait about 4 or so seconds before closing, the last tab does get restored correctly.

When opening TST debugging console, the only error I see when opening tabs is the following: "TypeError: throbber.getAnimations is not a function[Learn More] sidebar.js:591:36"

**Comment by lbmaian** [comment]
As just noted in #1447, I managed to reproduce this without the parent tab being selected. It can still reproduce on the test case in that issue, if I close the browser fast enough.

**Comment by piroor** [comment]
Oops, the error told at your comment is not intentional and c6d7877 should suppress it.

**Comment by piroor** [comment]
> After testing this more, it seems that the browser needs to be closed within a couple seconds after opening the last tab to reproduce this. If I wait about 4 or so seconds before closing, the last tab does get restored correctly.

Hmm, it is very odd. I still couldn't reproduce this problem on my PC with the delay (4 or more seconds)...

**Comment by lbmaian** [comment]
I mean if the browser was closed within 4 seconds. Try closing the browser ASAP as soon as tab D is created  in case I.

1. Start new session
2. Root tab A
3. Create child tab B
4. New tab => root tab C
5. Create child tab D
6. Close Firefox ASAP
7. Reopen Firefox

**Comment by piroor** [comment]
Thanks, I successfully reproduce this problem. However it also happens without TST for me. The last opened tab (D) is not restored on plain Firefox. I think this problem is caused by the throttling of Firefox's session store itself.

**Comment by lbmaian** [comment]
Ah yeah, I just reproduced without TST enabled. The tree structure is a red herring. I could reproduce with just the following:
```
A
\- B
```
Restart Firefox ASAP, get:
```
A
```

So this is a Firefox bug.
