### ISSUE TITLE
Restored collapsed trees can show grandchildren and their descendants

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1446]
## Short description
Restored collapsed trees can show grandchildren and their descendants. I believe this is a regression since 2.02, since I can only reproduce on the latest nightly, and not in 2.02 itself.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Ensure Firefox restores session upon startup (options => "Show your windows and tabs from last time")

### Case I
 4. Tree structure:
```
A
\- B (collapsed)
   \- C (collapsed)
E (selected)
\- F
```
 5. Restart Firefox

#### Expected result
Tree structure and tab selection is restored as-is.

#### Actual result
```
A
\- B (collased)
   \- C
E (selected)
\- F
```

### Case II
 4. Tree structure:
```
A (selected)
\- B (collapsed manually from A)
   \- C (collapsed manually from A)
```
 5. Restart Firefox

#### Expected result
Tree structure and tab selection is restored as-is.

#### Actual result
```
A (selected)
\- B (collapsed)
   \- C
```

### Case III
 4. Tree structure:
```
A
\- B (collapsed)
   \- C (collapsed)
      \- D (collapsed)
E (selected)
\- F
```
 5. Firefox

#### Expected result
Tree structure and tab selection is restored as-is.

#### Actual result
```
A
\- B (collapsed)
   \- C
      \- D
E (selected)
\- F
```

## Environment

 * Platform (OS): Windows 10 Pro, Version 1709, Build 16299.15
 * Version of Firefox: Developer Edition 57.0b6
 * Version (or revision) of Tree Style Tab: Latest nightly as of commit 1562e17661fb3947128a7c9722f2f8b19a6d3d33

**Comment by piroor** [comment]
Thanks, 812348e should fix this.

**Comment by lbmaian** [comment]
Confirmed fixed on my end.
