### ISSUE TITLE
CSS Formatting \ Tab close button (FF57-TST2.0.2)

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#1448]
This might be an out of scope kind of question, but maybe there is a useful question in all of this. (I figured it doesdn't hurt to ask)

I am trying to modify the close button on the tabs to only be displayed "on hoover".  I found examples of CSS code but tried it both in userChrome.css and in TSTs "extra style rules" but neither had any effect.  (Obviously add-ons like "Tab Utilities" modified this behavior pre-FF57)

Here is the code I tried:

/* Show the close buttons only on hover and not on pinned tabs */ 
.tabbrowser-tabs[closebuttons="activetab"] .tabbrowser-tab:not([pinned="true"]):hover .tab-close-button:not([selected="true"]) {
  display: -moz-box !important;
  border: 1px solid #888 !important;
  border-radius: 3px !important;
}

**Comment by Keith94** [comment]
Try the following CSS in TST's style rules:

```css
.tab:not(:hover) .closebox {
  display: none;
}
```

**Comment by irvinm** [comment]
Perfect, thanks!

**Comment by Keith94** [comment]
P.S. I documented it here: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules

**Comment by kazerniel** [comment]
this doesn't seem to work any more

    /* "#tabbar" is required for TST 3.4.0 and later! */
    #tabbar tab-item:not(:hover) tab-closebox {
    display: none;
    }

Edit: ok the issue more seems to be that none of the snippets work for me D:

**Comment by piroor** [comment]
@kazerniel It works for me. Screenshot:
![image](https://user-images.githubusercontent.com/70062/124360743-4e197c00-dc66-11eb-893e-0f4b7441b7aa.png)

**Comment by kazerniel** [comment]
@piroor not for me:

![image](https://user-images.githubusercontent.com/5689996/124460179-f1fa4900-dd86-11eb-828b-69c11c907fef.png)

And none of the other snippets work either, not sure of the cause.

**Comment by piroor** [comment]
`userChrome.css` is wrong place to put those style rules. Please see: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#for-version-20-and-later

**Comment by kazerniel** [comment]
Aa thank you!
