### ISSUE TITLE
New tabs in completely full TST tab bar can result in focused tab not being in view

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1449]
## Short description
New tabs in completely full TST tab bar can result in focused tab not being in view

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Optional: Resize browser window to be smaller so less tabs need to be created

### Case I: New tabs that are selected/focused by default
 4. Create new tabs via new tab button, Ctrl-T, duplicate tab, middle-click item on bookmarks toolbar/menu (but NOT bookmarks or history sidebar to avoid clobbering TST sidebar) until they fill up the tab bar. By default, the last new tab should be selected/focused.
 5. Create one more such new tab (just in case).

### Case II: Undo close tab
 4. Repeat Case I steps (or follow on from it)
 5. Close last tab.
 6. Undo close tab. By default, the restored tab should be selected/focused.

### Case III: New tabs that are NOT selected/focused by default
 4. Create child tabs until currently focused tab is at the top of the TST tab bar (top of TST sidebar viewport).
 5. Create one more child tab.

## Expected result
Focused tab always remains in view

## Actual result
Case I and II: Focused tab is often at least partially hidden at bottom of the TST sidebar viewport.

Case III: Focused tab is often hidden by "Tree Style Tab" sidebar toggle.

## Environment

 * Platform (OS): Windows 10 Pro, Version 1709, Build 16299.15
 * Version of Firefox: Developer Edition 57.0b6
 * Version (or revision) of Tree Style Tab: Latest nightly as of commit 11437df2aeb51526d7a58875e69f5a6d271c3678

**Comment by piroor** [comment]
I think 3c6f4ab should fix the rest problem.

**Comment by lbmaian** [comment]
Thanks, it looks fixed except for one edge case:

When opening child tabs, the first time the tabs would overflow the tab bar, the focused tab (the parent tab) can be partially hidden. For ex:
<img width="378" alt="issue1449" src="https://user-images.githubusercontent.com/30856860/31366556-7ebe4eda-ad26-11e7-8e1e-4ae43df50cf3.PNG">

Subsequent new child tabs do bring the focused tab in to view.

**Comment by piroor** [comment]
Hmm, I couldn't reproduce the edge case. On my environment the parent active tab stays on the top of viewport and newly added tab (partially visible) is notified by blue gradient animation.

**Comment by lbmaian** [comment]
Hmm, let me try elaborating.

1. Start with a single tab on a very small browser window (bottom of image is where the browser window ends):
<img width="164" alt="issue1449-1" src="https://user-images.githubusercontent.com/30856860/31369175-71a274fe-ad37-11e7-90ad-b0aa55558c13.PNG">
2. Create child tab 1 - still fine:
<img width="164" alt="issue1449-2" src="https://user-images.githubusercontent.com/30856860/31369198-9f4b3670-ad37-11e7-9904-d3d1637e2aa9.PNG">
3. Create child tab 2 - now overflows, and focused parent tab is partially hidden:
<img width="164" alt="issue1449-3" src="https://user-images.githubusercontent.com/30856860/31369211-b10ab5ac-ad37-11e7-865b-36ec1b01c6df.PNG">
4. Create child tab 3 - now focused parent tab is shown again:
<img width="164" alt="issue1449-4" src="https://user-images.githubusercontent.com/30856860/31369217-bcdd5b14-ad37-11e7-8231-e6bc9e1d8e46.PNG">

**Comment by piroor** [comment]
Thanks, I've confirmed the problem on my environment and ca29eda should fix this. It is caused by my mistake.

**Comment by lbmaian** [comment]
Thanks, confirmed fixed for me.
