### ISSUE TITLE
Restoring session switches focus to root tab that is the ancestor of pre-exit focused tab

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1450]
## Short description
Restoring session switches focus to root tab that is the ancestor of pre-exit focused tab.

This behavior was noted in #1445, and I'm splitting it out into its own issue.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Ensure Firefox restores session upon startup (options => "Show your windows and tabs from last time")
 4. Tree structure:
```
A
\- B (selected)
```
 5. Restart Firefox

## Expected result
```
A
\- B (selected)
```

## Actual result
```
A (selected)
\- B
```

I can reproduce this on any tree structure I've tried so far.

## Environment

 * Platform (OS): Windows 10 Pro, Version 1709, Build 16299.15
 * Version of Firefox: Developer Edition 57.0b6
 * Version (or revision) of Tree Style Tab: Latest nightly as of commit 14e4a24c6299dc7c509f837e5365c6ee7ede2164

**Comment by piroor** [comment]
Thank you for separation. The commit 9351382 should fix this.

**Comment by lbmaian** [comment]
Verified fixed for me.
