### ISSUE TITLE
FF57-TST 2.0.2: Positioning of new tabs from different sources

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#1451]
## Short description
In general, I like to have all of my activities that generate new tabs create them either as siblings or children of the original tab.  Sources of new tabs include "Open link in new tab", new URL entered , new search executed, bookmark loaded, or other add-on related new tabs (generic).  [Open link in new tab - Works great!]

## New Content:  Existing tab or new tab
Firefox seems to default to "loading" any new content into the same tab, but can be manually changed by using the middle mouse button to force a new tab for the action.  This used to be handled by add-ons like "Tab Utilities" to change the default behavior. 

**Any desire, plans, or abilities (WE limits) to influence this default behavior via options?  [I know you do functionality based on your workflow, so this might not impact you]**

## Placement of new tabs:
Even using the middle click on some of these actions, the resulting new tab is placed at the end of the vertical tree can be fairly far from the original tab which doesn't make sense to me.  [Talking to you Firefox!]  Someone has even gone so far to create the add-on "Open Tabs Next to Current" which is a basic hack to allow Firefox to create the tab at the end and then it physically moves the tab back up.  It is definitely a creative solution, but a hack none-the-less with some edge-case issues.  

**Do you have any plans or desire to influence this behavior with TST?**

**Comment by piroor** [comment]
> Any desire, plans, or abilities (WE limits) to influence this default behavior via options? [I know you do functionality based on your workflow, so this might not impact you]

Did you mean "there is any plan to add an option like "open link in new tab by regular left click"? Then TST won't implement such an option because it is not related "tree". I believe that it should be done by another addon which is useful for people who don't want to use vertical/tree tabs. If the addon opens a new tab with the "openerTabId" option, those new tabs are automatically handled by TST as you configured.

> Do you have any plans or desire to influence this behavior with TST?

TST already has options to control new tab position for some cases. They don't work for your case?

**Comment by irvinm** [comment]
> >Any desire, plans, or abilities (WE limits) to influence this default behavior via options? [I know you do functionality based on your workflow, so this might not impact you]

> Did you mean "there is any plan to add an option like "open link in new tab by regular left click"? Then TST won't implement such an option because it is not related "tree". I believe that it should be done by another addon which is useful for people who don't want to use vertical/tree tabs. If the addon opens a new tab with the "openerTabId" option, those new tabs are automatically handled by TST as you configured.

I had done some investigating after I originally asked this question and came to the same conclusion as you have mentioned.  I have already started asking other add-ons to properly make use of the optional argument "openerTabID" and I think we should be good here.  Thank you for confirming this behavior.

Ex:  https://github.com/sienori/Tab-Session-Manager/issues/7
Ex:  https://www.reddit.com/r/imagus/comments/73nuq5/shortcuts_new_tab_order_default/

-----------------------------------

>> Do you have any plans or desire to influence this behavior with TST?

> TST already has options to control new tab position for some cases. They don't work for your case?

I looked at the options you already provide to see if they open tabs near the originator:

- Open new blank tab as --> Works!
- Middle click on "New Tab" button --> Works!
- Middle click on "Reload" button --> Works!
- Right-click "Open Link in New Tab" --> Works!

Other situations that aren't quite as clean or directly handled\applicable:

- New URL entered (enter) --> Simply replaces existing page
- New URL entered (alt-enter or middle-click) --> Creates new tab of URL but places at end of tab chain
- New Search (enter) --> Creates new tab of search results but at end of tab chain (browser.search.openintab modified to true)
- New Search (alt-enter or middle-click) --> Creates new tab of search results but at end of tab chain
- Load bookmark (left-click) --> Simply replaces existing page
- Load bookmark (ctrl-left-click) --> Opens bookmark in new tab at end of the tab chain
- Load bookmark (right-click -> open in new tab) --> Opens bookmark in new tab at end of the tab chain

It looks to me that there is no way to enter a new URL, search, or load bookmark in a new tab next to the current tab without creating a blank tab first.

For me personally, I prefer the default for "new URL", "new Search", and "Load Bookmark" to be a new tab close to the originator.  Right now, I think the "work around" is to use your middle-click options to open a new sibling\child tab THEN do the basic URL, Search, Load Bookmark into the blank tab.

**Comment by irvinm** [comment]
This is really out of scope for TST, so I am closing this out.  I have gotten around some of this by using a new about:config value (FF61+) browser.tabs.insertAfterCurrent to force creating new tabs next to the current tab.
