### ISSUE TITLE
Array of tabs returned by TST API provides inaccurate 'active' status.

### ISSUE THREAD

**Issue by joshuacant** [piroor/treestyletab#1453]
## Short description
Array of tabs returned by TST API provides inaccurate 'active' status.

## Steps to reproduce
Use the 'get-tree' command or any message that returns the '.tabs' array. Use 'console.log(tabs)' to view the array of tab objects. View the 'active' property across the tab objects.

## Expected result
One and only one tab is 'active: true'.

## Actual result
Many tabs 'active: true'.

## Screenshots
Screenshot showing multiple tabs with 'active:true'.
https://i.imgur.com/3kjVu6T.png

Screenshot showing same array of tabs with only a single 'active' class in the states arrays. Note: this one tab with an 'active' class **does** correspond to the correct active tab.
https://i.imgur.com/KQ5GONy.png 

## Environment

 * Platform (OS): Windows 10 x64
 * Version of Firefox: Nightly 58
 * Version (or revision) of Tree Style Tab: Nightly from http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by piroor** [comment]
I couldn't reproduce this. How did you call the API? Could you paste codes to reproduce from about:debugging debugger?

**Comment by piroor** [comment]
After research I found the cause, sorry. ac6fca6 should fix this problem.

**Comment by joshuacant** [comment]
Working well for me so far, thank you!
