### ISSUE TITLE
Undo close tab of duplicate tab can incorrectly restructure the tree

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1455]
## Short description
Undo close tab of duplicate tab can incorrectly restructure the tree, sometimes even hiding tabs.

Another follow-up on #1437 

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.

### Case I
 3. Tree structure:
```
A
\- B
```
 4. Duplicate tab A (using any method):
```
A
\- B
A_dup
```
 5. Close tab A_dup:
```
A
\- B
```
 6. Undo close tab

#### Expected result
```
A
\- B
A_dup
```

#### Actual result
```
A
A_dup
\- B
```

### Case II
 3. Tree structure:
```
A
|- B
\- C
```
 4. Duplicate tab A (using any method):
```
A
|- B
\- C
A_dup
```
 5. Close tab A_dup:
```
A
|- B
\- C
```
 6. Undo close tab

#### Expected result:
```
A
|- B
\- C
A_dup
```

#### Actual result:
```
A
\- C (actually child of A_dup)
A_dup
\- B
```

Toggle off & on TST sidebar (press F1 twice):
```
A
C
A_dup
\- B
```

### Case III
 3. Tree structure:
```
A
|- B
|- C
\- D
```
 4. Duplicate tab A (using any method):
```
A
|- B
|- C
\- D
A_dup
```
 5. Close tab A_dup:
```
A
|- B
|- C
\- D
```
 6. Undo close tab

#### Expected result:
```
A
|- B
|- C
\- D
A_dup
```

#### Actual result:
```
A
\- C (actually child of A_dup)
A_dup
\- B
(D is no longer shown but still exists)
```

Toggle off & on TST sidebar (press F1 twice):
```
A
C
D
A_dup
\- B
```

## Environment

 * Platform (OS): Windows 10 Pro, Version 1709, Build 16299.15
 * Version of Firefox: Developer Edition 57.0b6
 * Version (or revision) of Tree Style Tab: Latest nightly as of commit 14e4a24c6299dc7c509f837e5365c6ee7ede2164

**Comment by piroor** [comment]
Thanks! 8e1be8e should fix this problem.

**Comment by lbmaian** [comment]
Verified fixed for me.
