### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by weiznich** [piroor/treestyletab#1456]
## Short description

Using TreeStyleTabs in combination with Firefox the build in tracking protection will cause a abnormal high CPU usage (100% for the main process) 

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Enable the build in tracking protection and set it to strict blocking list
 3. Install TST.
 4. Perform a google query
 5. CPU usage is 100% because Firefox blocks loading the faviocon from google and TST tries it again and again 

## Expected result
TST loads the favicon

## Actual result
100% CPU used.

## Environment

 * Platform (OS): Ubuntu 17.04
 * Version of Firefox: 58.0a1 (2017-10-08) (64-Bit)
 * Version (or revision) of Tree Style Tab: 2.0.2

**Comment by piroor** [comment]
I cannot reproduce this problem on Ubuntu 16.04 with latest TST development build on Nightly 58.0a1. Any other information, for example result of profiling at "Performance" tab in addon debugger? ("about:debugging" => "Tree Style Tab" => "Debug" then you'll see the addon debugger.)

**Comment by weiznich** [comment]
After starting the dev tool I see a few thousand (rapidly increasing) log entries of the following form in the console:
```
The resource at “https://www.google.de/images/branding/product/ico/googleg_lodp.ico” was blocked because tracking protection is enabled.[Learn More] sidebar.html
```

A [attache](https://github.com/piroor/treestyletab/files/1370960/profile.zip) a profile created by the Profiler in the Performance tab.

As temporary workaround:
Disabling and re enabling the tracking protection fixes the issue till the next browser start.

**Comment by piroor** [comment]
Thank you for additional information! Hmm, actually your log says that TST infinitely retries loading of the favicon. However it still don't happen on my environment, because the error message appears only once...

**Comment by piroor** [comment]
TST 2.0.3 has some changes around handling of favicon. Could you try it on 2.0.3 also?

**Comment by weiznich** [comment]
2.0.3 seems to fix the issue 👍
