### ISSUE TITLE
TST context menu isn't closed when clicking outside of TST sidebar

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1457]
## Short description
TST context menu isn't closed when clicking outside of TST sidebar. This is an assortment of minor issues, following up on the fix for #1441.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.

### Case I

 3. Right-click anywhere on TST sidebar to open up the TST context menu (on either a tab or the tab bar).
 4. Then one of:
     1. Left-click on the title bar (enable via hamburger menu => Customize => check "Title Bar").
     2. Left-click on the current tab in the vanilla tab bar.
     3. Left-click OR right-click on empty parts of the vanilla tab bar. 
     4. Right-click buttons on any toolbar.
     5. Middle-click buttons that have no action for middle-click (e.g. excluding middle-clicking reload button).
     6. Click any mouse button (left, middle, right) on the menu bar.
     7. Click any mouse button (left, middle, right) on empty parts of any toolbar.
     8. Right-click on non-folder items of bookmark toolbar.
     9. Left-click OR right-click on folders of bookmark toolbar.

### Case II

This one might be specific to Windows, due to the context menu right-click mouseup behavior.

 3. Hold down right mouse button on content window.
 4. Move cursor to TST sidebar.
 5. Release right mouse down to open up the TST context menu (on either a tab or the tab bar).
 6. Then one of:
     0. Click any mouse button (left, middle, right) on the content window.
     1. Click any mouse button (left, middle, right) on the title bar (enable via hamburger menu => Customize => check "Title Bar").
     2. Left-click on the current tab in the vanilla tab bar.
     3. Left-click OR right-click on empty parts of the vanilla tab bar. 
     4. Right-click buttons on any toolbar.
     5. Middle-click buttons that have no action for middle-click (e.g. excluding middle-clicking reload button).
     6. Click any mouse button (left, middle, right) on the menu bar.
     7. Click any mouse button (left, middle, right) on empty parts of any toolbar.
     8. Click any mouse button (left, middle, right) on textboxes or menu-spawning buttons (e.g. library icon or hamburger menu icon) of any toolbar.
     9. Right-click on non-folder items of bookmark toolbar.
     10. Left-click OR right-click on folders of bookmark toolbar.

Note that 6.0, 6.1, 6.8 differ from Case I.

## Expected result

TST context menu is closed.

## Actual result

TST context menu remains open.

## Environment

 * Platform (OS): Windows 10 Pro, Version 1709, Build 16299.15
 * Version of Firefox: Developer Edition 57.0b6
 * Version (or revision) of Tree Style Tab: Latest nightly as of commit 11657b6fc4fde29cbf80e8721e97313fa1954735

**Comment by piroor** [comment]
I think this problem is fundamentally impossible to be fixed by addon. To emulate natural behavior of the real context menu, I have to do two things in a time: 1) handle click event outside of the sidebar and 2) send "click" event to the position (on Windows and Linux.) 1 is possible via [`Element.setCapture()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/setCapture) but the click event is processed as "fired inside the sidebar" and 2 is impossible from WebExtensions addons - they cannot access to outside of limited frames. Only new API to show the real context menu (like https://bugzilla.mozilla.org/show_bug.cgi?id=1396031 ) can fix this problem...

**Comment by irvinm** [comment]
@piroor I don't think this is a bug any more.  I think this can be closed.
