### ISSUE TITLE
Container tabs feature not working with the webextension in permanent private browsing mode

### ISSUE THREAD

**Issue by lgp171188** [piroor/treestyletab#1458]
## Short description
Container tabs feature not working with the webextension in permanent private browsing mode

## Steps to reproduce

1. Start FirefoxDeveloperEdition (57.0b5) with clean profile.
1. Configure FirefoxDeveloperEdition to always use private browsing mode and restart under that mode
1. Install TST webextension from addons.mozilla.org or the latest webextension nightly.
1. In the new tab button in the TST sidebar there is small dropdown at the right for selecting the container. Select a container and open a new tab.
1. Open GitHub in the new tab and login.
1. Select a different container profile and open a new tab.
1. Open GitHub in the new tab.

## Expected result
The tab opened under step 5 will not know anything about the logged in session in the tab opened under step 3 as they are in different containers.

## Actual result
The logged in session in the tab opened under step 3 is recognized in the new tab opened under step 5.
This means that the container tab functionality is not working. Also, there are no color indicators on the tab to indicate any container profiles being used.

## Environment

 * Platform (OS): Mac OS X 10.12.6
 * Version of Firefox: Firefox Developer Edition 57.0b6
 * Version (or revision) of Tree Style Tab: 04/10/2017 Webextension Nightly and also the Webextension version from addons.mozilla.org

**Comment by piroor** [comment]
Mozilla's official addon for containers https://testpilot.firefox.com/experiments/containers/ also cannot create container tabs, so it seems a limitation of WebExtensions API or Firefox itself.

**Comment by piroor** [comment]
I close this because it is not a problem of addon side.
