### ISSUE TITLE
Scrolling when viewing a PDF causes tab title to flicker as if the page was refreshed

### ISSUE THREAD

**Issue by mivok** [piroor/treestyletab#1459]
## Short description

When viewing PDF files in the browser, any scrolling causes a page refresh animation on the tab entry shown in the tree style tab sidebar.

## Steps to reproduce

 1. Start Firefox 57.0b7.
 1. Install TST 2.0.4.
 1. Load a page with a PDF, for example <http://www.pdf995.com/samples/pdf.pdf>
 1. Verify that the TST sidebar is open and you can see the tab for the page with the pdf.
 1. Scroll the PDF with the mouse wheel or pressing page down
 1. Look at the tab in the tree style tabs sidebar, it flickers (background gradient animation moving from left to right) as if reload was pressed.

## Expected result

No animation of the tab bar

## Actual result

Page reload animation shows.

## Environment

 * Platform (OS): MacOS High Sierra
 * Version of Firefox: 57.0b7
 * Version (or revision) of Tree Style Tab: 2.0.4

**Comment by piroor** [comment]
Thanks! I've confirmed on my PC and 2f62c07 fixes it for me.

**Comment by mivok** [comment]
Awesome, thank you!
