### ISSUE TITLE
How to Customize Toggle Sidebar Shortcut?

### ISSUE THREAD

**Issue by edouard-lopez** [piroor/treestyletab#1463]
Hi, 
Thanks for the work used it a long time ago and now I'm switching back to `TST` as it seems `Tab Groups` won't be supported in 57+ versions.

## Short description

I would like to be able to customize the shortcut to toggle the TST sidebar.

## Expected result

Have a key in `about:config` or a menu in the settings.

**Comment by piroor** [comment]
Currently it is impossible by WebExtensions-based addons. TST defines its own shortcut by the static manifest file and TST currently doesn't provide any ability to change such shortcuts dynamically. Thus you need to do: fork this project, modify the manifest file, pack it, and upload to AMO to sign to the file. See also: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands

Possible related bugs:

 * [1215061 - Better keyboard shortcut support](https://bugzilla.mozilla.org/show_bug.cgi?id=1215061 "1215061 - Better keyboard shortcut support")
 * [1303384 - UI for re-assigning command shortcuts](https://bugzilla.mozilla.org/show_bug.cgi?id=1303384 "1303384 - UI for re-assigning command shortcuts")
 * [1320332 - Support overriding existing keybinding through WebExtensions](https://bugzilla.mozilla.org/show_bug.cgi?id=1320332 "1320332 - Support overriding existing keybinding through WebExtensions")

**Comment by piroor** [comment]
It is already changeable.
