### ISSUE TITLE
Request: Allow to cancel TST's default behavior for tabbar-click API message.

### ISSUE THREAD

**Issue by joshuacant** [piroor/treestyletab#1465]
## Short description
tab-clicked supports:
```If any addon responds to the message with a boolean value true, TST's default behavior (activating the tab) will be canceled.```

tabbar-clicked does not support this and I would like it to.

It's not possible to override the default TST actions for tabbar clicks. For instance, I can catch middle mouse clicks on the tabbar and use that to do something else, but a new tab always opens too. I would like to cancel the new tab opening through the method above.

**Comment by joshuacant** [comment]
Wow. Fast! I'll grab the next nightly and test.

**Comment by piroor** [comment]
66001b8 should allow addons to cancel TST's behavior. Could you try that?

**Comment by joshuacant** [comment]
Are the nightly builds at http://piro.sakura.ne.jp/xul/xpi/nightly/ being updated? The timestamp changed but the XPI still shows as 2.0.4 not 2.0.5. I extracted the files and handlers.js doesn't show any of these changes.

**Comment by piroor** [comment]
Hmm, something wrong around my private automated build system... Anyway, now TST 2.0.5 is already released on AMO. You don't need to try unsigned development build :)

**Comment by joshuacant** [comment]
I've done a little bit of testing and it's working now. Thanks again!
