### ISSUE TITLE
[feature request] Multiple tab selection

### ISSUE THREAD

**Issue by MuxMelody** [piroor/treestyletab#1467]
I'm using the new TST 2.0.4. I appreciate the effort made to port this to WebExtensions. I have a feature request that has prevented it from being as useful as it used to: I would like to be able to select multiple tabs to better sort tabs when many tabs are to be moved and organized, just as I was able to do before in combination with Multiple Tab Handler. I found that the Tree Tabs addon does this in WE, but I'd prefer Tree Style Tabs because of how well it has worked for me in the past.

**Comment by piroor** [comment]
Now Multiple Tab Handler 2.0.x is available for TST 2.0.x. (The latest version on AMO is 2.0.2 - I've released it today.) I believe that combination of them produces experiences similar to legacy versions' one.

**Comment by MuxMelody** [comment]
Thanks!
