### ISSUE TITLE
Context Menu Entry "Send Tab to Device"

### ISSUE THREAD

**Issue by AlexEndris** [piroor/treestyletab#1469]
Since it doesn't make sense to have the tab bar open (I use userChome.css to collapse it) I currently lose the context menu option to send tabs to a synced device as this entry doesn't appear in treestyletab.

Can you please add that there as well?

**Comment by piroor** [comment]
It is impossible by an addon, due to lmitation of WebExtensions. There in no API to do around Sync for now.

**Comment by AlexEndris** [comment]
Yeah, I got curious myself before you responded. Didn't find anything. Hope it's on their agenda somewhere.

**Comment by gnite** [comment]
@AlexEndris But you do realize that option also exists in the context menu of the page itself? Having it on the tab might be convenient but is not necessary.

**Comment by AlexEndris** [comment]
@gnite No, actually I didn't realize that. Was looking for a "send tab..." and didn't even notice the "send page" entry.

I guess this can be closed then, seem like @piroor is hoping for Mozilla to enable native context menus on the tabs in sidebars anyhow. And that's probably the better option here.

**Comment by cipri-tom** [comment]
well spotted @AlexEndris ! Thank you !

**Comment by irvinm** [comment]
FYI, https://bugzilla.mozilla.org/show_bug.cgi?id=1417183 seems to be the issue being tracked.  Unfortunately, no progress yet.
