### ISSUE TITLE
Parent tab that is focused after closing child tab is sometimes not scrolled to

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1472]
## Short description
Parent tab that is focused after closing child tab is sometimes not scrolled to. For example, such cases in #1471.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Resize browser window to a small size.
 4. Start with a root tab A.
 5. Create child tab B.
 6. Select child tab B:
<img width="164" alt="1" src="https://user-images.githubusercontent.com/30856860/31572849-05b5ae34-b064-11e7-83be-42144b52f4a0.PNG">

 7. Select tab A again, so for new child tabs of A, if such a child tab is closed, the parent tab A is focused again (per #1471)
 8. Create at least two child tabs that at least partially overflow the tab bar:
<img width="164" alt="2" src="https://user-images.githubusercontent.com/30856860/31572875-7a010ce8-b064-11e7-86de-12e7a7457ed7.PNG">

 9. Select the last child tab (or a child tab that at least one tab beyond at least partially overflowing tab bar):
<img width="165" alt="3" src="https://user-images.githubusercontent.com/30856860/31572879-b8f7e2aa-b064-11e7-8a8c-9d804dfd8394.PNG">

 10. Close the selected tab.

## Expected result
The newly focused tab should be scrolled to.

## Actual result
The newly focused tab, which according to #1471 should be tab A is NOT scrolled to:
<img width="165" alt="4" src="https://user-images.githubusercontent.com/30856860/31572908-1dc3cb90-b065-11e7-9096-e8cb4a50f090.PNG">

## Environment

 * Platform (OS): Windows 10 Pro, Version 1709, Build 16299.15
 * Version of Firefox: Developer Edition 57.0b8
 * Version (or revision) of Tree Style Tab: 2.05

**Comment by piroor** [comment]
Confirmed.

**Comment by piroor** [comment]
a63f7e8 should fix this - it was a regression on recent versions. Thanks!

**Comment by lbmaian** [comment]
Confirmed fixed for me, thanks.
