### ISSUE TITLE
FF57-TST2.0.5:  openerTabId not being updated when tabs manually moved

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#1475]
Working with the developer of "Tab-Session-Manager", I asked them to add support for hierarchy of tabs by including openerTabId as part of the saved session information.  

https://github.com/sienori/Tab-Session-Manager/issues/7

He has added support and I have verified it works properly for tabs created naturally as children.  (Ex: Open link in new tab).  The children information is saved and restored properly.  However, if I create tabs all independently, but manually make some children of others it appears the openerTabId of the child is not being updated to be the parent and thus the relationship while working in TST does not restore properly when restoring the session.

**_Steps:_**

**What does work:**
- Install TST and Tab-Session-Manager
- Go to yahoo.com and right click on any number links and "open link in new tab"
- Result is 1 parent and rest as children
- Restart browser and restore session saved 
- Result is exactly the same as when browser was closed [good]

**What isn't working:**
- Install TST and Tab-Session-Manager
- Create 4 independent tabs
- Move 2nd tab to be child of 1st 
- Move 4th tab to be child of 3rd
- Now have 2 parents each with 1 child
- Restart browser and restore session saved 
- Result is now 4 tabs all at same level [non-ideal]

From the dev of Tab-Session-Manager:

https://github.com/sienori/Tab-Session-Manager/issues/7#issuecomment-336512327

> Supported in 1.3.1

> If you replaced the parent-child relationship of tabs, It is impossible to restore completely.
> This is because TST does not update the openerTabId when replacing tabs.

**Comment by piroor** [comment]
Hmm, I didn't know it is changeable property. After eebc95d now openerTabId is updated.

**Comment by irvinm** [comment]
Thank you piroor.  I will test it out in the next version.

**Comment by irvinm** [comment]
Thanks piroor.  Things look much better now.  I think there might still be an issue if entire trees are moved together, but I will investigate and report back if I can get a reproducible situation.  (An issue in that when moving the tree, then saving the session, then recovering the session that the tree is intact, but not where it originally was)

Even if this is the case, it is working much better as relationships are not being stored and recovered much better now between TST and the session manager.

**Comment by sienori** [comment]
Probably, it does not work as expected because of Firefox specification.
`browser.tabs.update(aTab.apiTab.id, { openerTabId: null });`

**Comment by irvinm** [comment]
@piroor, I have done some more investigation on the issue I was seeing and was able to at least come up with a scenario that isn't consistent between TST and TSM when restoring tabs.  Seeing as the primary functionality is on the session restore operation, I opened a bug first with tab session manager.

https://github.com/sienori/Tab-Session-Manager/issues/20

I could still be TST or FF related, but thought you should know.

**Comment by piroor** [comment]
Hmm, how can I clear the `openerTabId` for detached tree??

**Comment by piroor** [comment]
It seems impossible to clear `openerTabId` with any invalid value `null`, `0` or something like them, because `browser.tabs.update(id, { openerTabId: xxx })` requires any valid tab id as the value of `openerTabId`. So now TST sets the id of the tab itself instead of clearing it. I hope this change solves this problem...

**Comment by irvinm** [comment]
Looks like this was all related to the "Auto-group tabs opened within" option.  The random nature of how quickly the system could restore the tabs would cause TST to chang the grouping based on this parameter.

Disabling that feature and rerunning the test several times, I now get consistent results on a session restore.

Thank you @piroor for your continued excellence with this addon.

Sincerely,
Mike
