### ISSUE TITLE
[dev][Session restore] Active tab inside stack: Order of tabs and tree structure are not preserved after session restore

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1476]
Windows 8.1 x64 with latest updates, Nightly 16-10-17, TST2.0.5 (WE).

STR:
Create new profile, install TST2.0.5
Open new window, go to https://bugzilla.mozilla.org/ in the active tab and ctrl-click the following links: Home, New, Browse, Search, help (that's hyperlinks on the bugzilla web page)
Press Ctrl-T, go to github.com and ctrl-click Features, Business, Explore, Marketplace, Pricing
Press Ctrl-T, go to mozilla.org and ctrl-click Firefox, Pocket, Internet Health, Technology, About Us
Switch to the last tab, close Nightly using hamburger menu - Exit

Launch Nightly, hamburger menu - Restore session

ER: Order of tabs and tree structure are preserved
AR: Order of tabs is not preserved, tab trees are not preserved, some tabs are grouped though they shouldn't be (I guess that's because TST groups tabs opened within 100 msec by default, doesn't work well with session restore).

Will attach a screenshot in the next post.

**Comment by SXZ1** [comment]
Here is a comparison before restore/after restore:
![screenshot 6431](https://user-images.githubusercontent.com/26294581/31666503-2c0300a2-b355-11e7-9609-0b4ba11b0976.png)

**Comment by piroor** [comment]
After some experiments (you can see results at https://github.com/piroor/treestyletab/tree/aggressive-session-restore ) I've realized that this is impossible to fix with currently available WebExtensions APIs. There is no events around session restoration, so we cannot know when we should restore tree structure for tabs. (Of course TST stores permanent information for each tab as a part of its session data, but sessions.getTabValue just returns `undefined` as the value if I try to read the data from a restored tab immediately.) So we really need some fixes on Firefox itself.

**Comment by piroor** [comment]
Sorry, it's quite my mistake - I used wrong way to get session information for tabs. Now TST can detect restored tabs immediately and restores tree structure for this case.

**Comment by SXZ1** [comment]
Thank you very much! Unfortunately, the bug is not completely fixed, the last stack is still not restored correctly even with TST2.0.7. Here is before/after comparison. I used a bit different STR:
Launch profile, install TST2.0.7, close Nightly, launch Nightly, go to https://bugzilla.mozilla.org/ in the active tab
All other steps are the same.
![1](https://user-images.githubusercontent.com/26294581/31677019-20b9e1f8-b372-11e7-814f-0d81f0293630.png)

I'll post another comparison using STR from the first post below.

**Comment by SXZ1** [comment]
And here is before/after comparison using STR from the first post. As you can see, tree structure is restore but the order of tabs is wrong:
![2](https://user-images.githubusercontent.com/26294581/31677300-ff168b18-b372-11e7-805c-5dd03d177b01.png)

**Comment by SXZ1** [comment]
To sum up:
STR from the first post (two windows) - tree structure is saved, order of tabs is wrong
STR from https://github.com/piroor/treestyletab/issues/1476#issuecomment-337290047 (one window) - tree structure is lost, order of tabs is correct

**Comment by nnethercote** [comment]
FWIW, the tree structure and order is restoring just fine for me.

**Comment by SXZ1** [comment]
This bug is not reproduced in Tab Center Redux.

**Comment by SXZ1** [comment]
I've found two  more STR, TST from https://piro.sakura.ne.jp/xul/xpi/nightly/

1)Create new profile, install TST
Disable "Auto-group tabs opened within 100 msec" in TST Options
Close Nightly, launch Nightly, go to https://bugzilla.mozilla.org/
Ctrl-click New, Browse, Search
2)Press Ctrl-4
3)Close, Nightly, launch Nightly, restore session

ER: The last tab is part of the stack
AR: The last tab got removed from the stack. Same result with a bit different STR if you press Ctrl-3 in step 2) - the tab that was active before shutdown got removed from the stack.

STR2:
1)Create new profile, install TST
Disable "Auto-group tabs opened within 100 msec" in TST Options
Close Nightly, launch Nightly, go to https://bugzilla.mozilla.org/
Ctrl-click New, Browse, Search
2)Press Ctrl-2
3)Close, Nightly, launch Nightly, restore session

AR: See the screenshot below, tab order is messed up, one more stack is formed that can't be properly collapsed/expanded
![7](https://user-images.githubusercontent.com/26294581/31794189-0e38d7e6-b52a-11e7-8bfb-240a4f9ff539.png)

**Comment by SXZ1** [comment]
I've just retested all STR. Forget about all other STR in this thread that I don't mention in this comment. I think you should focus on STR from this comment first: https://github.com/piroor/treestyletab/issues/1476#issuecomment-338037518

Then try this STR:
1)Create new profile, install TST
Disable "Auto-group tabs opened within 100 msec" in TST Options
Close Nightly, launch Nightly, go to https://bugzilla.mozilla.org/
Ctrl-click New, Browse, Search
2)Press Ctrl-1
3)Close, Nightly, launch Nightly, restore session

ER: One stack, tab order is correct
AR: Tab order is correct, stack is gone. Screenshot before/after session restore:
![99](https://user-images.githubusercontent.com/26294581/31909815-fbc6f92c-b843-11e7-9e95-99de5d6c5960.png)
What else should I do to help you fix this bug, @piroor?

**Comment by SXZ1** [comment]
TST-related errors in the browser console:
![bc](https://user-images.githubusercontent.com/26294581/31931155-ecd4768a-b8aa-11e7-9d4a-449a521a85be.png)
![bc2](https://user-images.githubusercontent.com/26294581/31931156-ed1183b8-b8aa-11e7-8ea7-b54af8055767.png)

**Comment by SXZ1** [comment]
This bug is difficult to read, I'll close this bug and file a new one with latest info:
#1509
