### ISSUE TITLE
Duplicating tab can create child tabs even when configured not to

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1477]
## Short description
Duplicating tab can create child tabs even when configured not to under various cases:
1. Middle-click reload button or select Firefox tab context menu's duplicate tab, regardless of the TST duplicate tab settings
2. Select TST fake context menu's duplicate tab, with TST duplicate tab setting set to "an independent tab" (usually)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.

### Case I
 3. Set TST duplicate tab setting to any setting
 4. Tree structure:
```
A
```
 5. Duplicate tab A via middle-clicking reload button or selecting Firefox tab context menu's duplicate tab

### Case II
 3. Set TST duplicate tab setting to "an independent tab"
 4. Tree structure:
```
...
A
...
```
 5. Duplicate tab A via selecting TST fake context menu's duplicate tab

### Case III
 3. Set TST duplicate tab setting to any setting
 4. Tree structure:
```
A
\- B
```
 5. Duplicate tab A via middle-clicking reload button or selecting Firefox tab context menu's duplicate tab

## Expected result
Should only create a child tab when TST duplicate tab setting is set to "a child of the current tab". Should respect that setting's intended behavior.

### Case I
Creates a child tab:
```
...
A
\- A_dup
...
```

### Case II
Usually creates a child tab (very occasionally does create an independent tab correctly):
```
...
A
\- A_dup
...
```

### Case III
Creates a child tab of A, and makes B a child of this new child tab:
```
...
A
\- A_dup
    \- B
...
```

## Environment

 * Platform (OS): Windows 10 Pro, Version 1709, Build 16299.19
 * Version of Firefox: Nightly 58.0a1 (2017-10-18) (64-bit)
 * Version (or revision) of Tree Style Tab: 2.0.7

**Comment by piroor** [comment]
Thanks. By recent commits these three cases don't happen on my environment anymore.

**Comment by lbmaian** [comment]
Sorry, the latest changes haven't fixed the problem. In fact, it's probably worse now. Duplicating a tab, whether by TST context menu, Firefox context menu, or middle-clicking reload button, now seems to always create a child tab.

Furthermore there's a serious regression: attempting to create a child tab via middle-clicking a link now produces an "root" tab rather than a child tab. I put quotes around "root", because I've managed to create a tree structure like:
```
A
|- A_dup
A_dup_child?
\- A_dup2 (child of A)
```

**Comment by piroor** [comment]
Sorry for this regression, after that I did more changes. How about the latest build?

**Comment by lbmaian** [comment]
The child tab regression and all the above cases were fixed.

However, the following case is broken:
1. Set TST duplicate tabs setting to "an independent tab"
2. Tree structure:
```
A
B
```
3. Duplicate tab A via any method: TST context menu, Firefox context menu, or middle-clicking reload button

Expected result:
```
A
B
A_dup
```

Actual result:
```
A
B
\- A_dup (actually child of A)
```

**Comment by lbmaian** [comment]
Found two more cases with buggy behavior:

## Case V
### Steps to reproduce
1. Set TST duplicate tabs setting to "a child tab of the current tab"
2. Set TST child tab insertion position setting to "append to the end of the tree"
3. Tree structure:
```
A
\- B
```
4. Duplicate tab A via TST fake context menu (NOT middle-clicking reload button or Firefox tab context menu):
```
A
|- B
\- A_dup (selected)
```
5. Optional: close the duplicate tab
6. Select tab A
7. Duplicate tab A via middle-clicking reload button or Firefox tab context menu (NOT via TST fake context menu)

### Expected result
```
A
|- B
|- A_dup (if wasn't optionally closed)
\- A_dup2 (selected)
```

### Actual result
```
A
|- A_dup2 (selected)
|-B
\- A_dup (if wasn't optionally closed)
```

## Case VI
### Steps to reproduce
1. Set TST duplicate tabs setting to "a child tab of the current tab"
2. Ensure the vanilla Firefox tab bar is visible so that you can access the Firefox tab context menu (and its duplicate tab option)
3. Tree structure:
```
A
\- B
C
```
4. Duplicate tab A via TST fake context menu (NOT via middle-click reload button or Firefox tab context menu):
```
A
|- B
\- A_dup (selected)
C
```
5. Optional: close the duplicate tab
6. WITHOUT selecting tab A again, duplicate tab A via Firefox tab context menu (NOT via middle-click reload button or TST fake context menu)

### Expected result
```
A
|- B
|- A_dup (if wasn't optionally closed)
\- A_dup2 (selected)
```

### Actual result
```
A
|- B
\- A_dup (if wasn't optionally closed)
C
\- A_dup2 (actually child of A) (selected)
```

**Comment by piroor** [comment]
Thanks for these information. Extra cases also fixed for me by recent commits.

**Comment by lbmaian** [comment]
Thanks, all cases work fine for me now.
