### ISSUE TITLE
Feature request: Make "Open new tab" style of Tree Style Tab the default behaviour (alternatively: offer hotkey support)

### ISSUE THREAD

**Issue by Echtze1t** [piroor/treestyletab#1479]
1) Firefox 57+ default behaviour when clicking "Open new tab" button:

The tree scrolls to the end of all open tabs and a new tab is opened at that position. ALT: If a extensions is installed, the new tabs opens next to the current one, but the tree is still scrolled to the end of all open tabs.

2) Tree Style Tab configurable behaviour when clicking "Open new tab" button:

The tree doesn't scroll and a new tab is opened next (below) to the current one.
(Bug report: even after changing the option "For middle click on "New Tab" button" to "Independent tab", the new tab is still opened as a child of the current tab.)

****************

I would like to be 2) the default behaviour when I open a new tab (NO SCROLLING), preferably with a keyboard shortcut (can the default shortcut be overwritten?), alternatively with a button in the navigation bar or an option in the context menu (although less desirable).

**Comment by piroor** [comment]
Sorry I couldn't understand what is the problem. Which is the "new tab" button in the Firefox's horizontal tab bar or TST's sidebar? Could you describe the steps, the expected result, and the actual result with figures like #1478?

**Comment by piroor** [comment]
I close this because outdated.
