### ISSUE TITLE
Moving tab to new window should also move children

### ISSUE THREAD

**Issue by jryans** [piroor/treestyletab#1482]
## Short description

Moving a parent tab to a new window should also move its child tabs as well, like it used to do in the legacy TST add-on.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set up some parent tabs with one or more children tabs, as shown below.
 4. Right-click on one of the parent tabs (A), choose "Move to New Window".

```
A
|- B
\- C
D
\- E
```

## Expected result

I would expect the selected parent tab (A) and its children (B, C) to move together to the new window, and the tree structure should be preserved.

## Actual result

Currently only the tab you click is moved, so only A moves. The children remain in the original window.

## Environment

 * Platform (OS): macOS 10.12.6
 * Version of Firefox: Firefox Nightly 58.0a1 (2017-10-15) 
 * Version (or revision) of Tree Style Tab: 2.0.7

**Comment by piroor** [comment]
It is done correctly when the tree is detached from the window via drag and drop, but not implemented yet for menu command...

**Comment by piroor** [comment]
The commit 697d62c should implement this.

**Comment by jryans** [comment]
Thanks! This commit seems to mostly fix this problem, however I did notice that if one of the child tabs is in lazy / discarded mode (hasn't been focused since last restart of Firefox, so it's not loaded), then that child is left behind in the old window. Seems like a separate issue, so I will file a new issue.

**Comment by jryans** [comment]
Variant of this issue for lazy tabs filed as #1486.
