### ISSUE TITLE
tabs get shifted by one when starting browser and "open tabs next to current" is installed (recent regression)

### ISSUE THREAD

**Issue by kparal** [piroor/treestyletab#1483]
## Short description
When [Open Tabs Next to Current](https://addons.mozilla.org/en-US/firefox/addon/open-tabs-next-to-current/) is installed, every time I restart the browser (I have configured it to restore all by tabs on startup), all my trees get messed up. By experimenting, I found out all tabs get shifted by one position.

This is a recent regression, I believe (it used to work fine just a few days back).

I tested this with a completely clean F57 profile and default TST (no configuration adjustments).

## Steps to reproduce

 1. Start Firefox with clean profile. 
 2. Configure _When Firefox starts: Show your windows and tabs from last time_ in preferences.
 3. Install TST. No configuration needed.
 4. Install Open Tabs Next to Current.
 5. Create some tabs and trees.
 6. Close the browser and start it again, see that the tab positions are shifted by one.

For example, this is original state, after 1st restart, after 2nd restart and after 3rd restart:
![1](https://user-images.githubusercontent.com/755451/31813838-02651e1c-b588-11e7-8f0f-f07a0def83eb.png) ![2](https://user-images.githubusercontent.com/755451/31813839-043715e2-b588-11e7-88d4-079646ee006a.png) ![3](https://user-images.githubusercontent.com/755451/31813842-06053e1c-b588-11e7-81f8-69a399908b4e.png) ![4](https://user-images.githubusercontent.com/755451/31813844-07ce28a8-b588-11e7-954b-7aba653e2b75.png)

As you can see, each restart shifts the tabs by one.

## Expected result
Tabs are in the same state as when closing the browser.

## Actual result
Tab trees are messed up each time I close the browser.

## Environment

 * Platform (OS): Fedora 27
 * Version of Firefox: Firefox 57
 * Version (or revision) of Tree Style Tab: 2.0.7 from AMO

**Comment by piroor** [comment]
On my environment, Open Tabs Next to Current always breaks order of restored tabs on every startup, without TST. I've read [its source code](https://github.com/sblask/webextension-open-tabs-next-to-current/blob/master/background.js) and realized that there is no safe-guard mechanism for tabs restored in specific order at the startup. I think this should be solved by the addon itself, to introduce something mechanism to ignore multiple tabs opened in one time.

**Comment by kparal** [comment]
Not sure how I missed this, but you're correct, the problem seems to be entirely in Open Tabs Next to Current extension, and not in TST. Sorry for false alarm. I even found the bug report here:
https://github.com/sblask/webextension-open-tabs-next-to-current/issues/30
This ticket can be closed, I believe.
