### ISSUE TITLE
Bad font-size with dynamically changing high-DPI scaling

### ISSUE THREAD

**Issue by RalfJung** [piroor/treestyletab#1484]
## Short description

When the high-DPI scaling changes, the font-size in the sidebar does not adapt, making thefont way too small or big.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Start Firefox while an external, low-DPI screen is connected and the system is in low-DPI mode.
 4. Unplug the external screen, triggering the system to change to high-DPI mode.

## Expected result

The font size should adapt like it does in most of the rest of Firefox.

## Actual result

The font size stays the same (in pixels), making it unreadably small on the high-DPI screen.

## Environment

 * Platform (OS): Linux, Gnome
 * Version of Firefox:  	57.0b10
 * Version (or revision) of Tree Style Tab: 2.0.7

**Comment by piroor** [comment]
Does this happen on other sidebar addons, like Tab Center Redux? Or, TST specific?

**Comment by XCanG** [comment]
@RalfJung use this custom style in settings of addon:
```
.tab .label {
  font-size: 3.8vw !important;
}
```
where adjust size by changing 3.8 value, `vw` is relevant to width, you also may use `vh`. Documentation about relative values: https://developer.mozilla.org/en-US/docs/Web/CSS/length#Viewport-percentage_lengths

**Comment by RalfJung** [comment]
@piroor I briefly tried Tab Center Redux.  There was no issue going from low-DPI to high-DPI, but there was an issue going from high-DPI to low-DPI. I also found similar behavior in Firefox itself: <https://bugzilla.mozilla.org/show_bug.cgi?id=1410827>.

**Comment by RalfJung** [comment]
@XCanG uh that's really weird, it makes the fonz size change when I change the browser window size / the widht of the sidebar. I don't think I like that.

**Comment by XCanG** [comment]
Probably there is a global problem what you can't apply any lengh type relative to DPI of the screen. You have something like `1dpi` / `1in`, but it still static, you can read more about this problem in mentioned article here [#CSS_units_and_dots-per-inch](https://developer.mozilla.org/en-US/docs/Web/CSS/length#CSS_units_and_dots-per-inch)

**Comment by RalfJung** [comment]
For websites, Firefox rescales the content properly, changing the ration between a CSS pixel and a display pixel. But that doesn't seem to reliably work everywhere. Probably that's not a bug in this extension, but a bug in Firefox.

**Comment by XCanG** [comment]
I find another idea in internet, but don't sure how it will work for you. @RalfJung try use this style for font: ```
.tab .label {
  font: 100%/1.45 Arial, sans-serif;
}
```

**Comment by RalfJung** [comment]
Nope, no luck. The [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1410827) got moved to "Layout: Tables", so I guess the bug is on the browser side.

**Comment by piroor** [comment]
I close this because this is out of the range of WebExtensions-based extension.
