### ISSUE TITLE
[latest dev] Dragging a tab to the scroll bar breaks the tab stack

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1485]
Hello!
Win8.1, Nightly 22-10-17, TST2.0.7 or latest dev from https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi

STR:
Create new profile, install TST, open new window, go to [github.com](url) and ctrl-click on Features, Business, Explore (that's hyperlinks on github.com)
Start pressing ctrl-T until the scroll bar appears in the sidebar 
Left-click on "Github for Business" tab, release left mouse button
Left-click on "Github for Business" tab, hold the left mouse button, drag this tab to the scroll bar, release left mouse button

That's what happens, before/after/after+collapsing the stack/after+expanding the stack again:
![1](https://user-images.githubusercontent.com/26294581/31887404-e8a53536-b800-11e7-849a-ba30c94d6d54.png)
It would be great to be able to remove the tab from the stack by dragging it to the left.

**Comment by piroor** [comment]
Thanks, I missed this case. The commit 953c802 fixes this.
