### ISSUE TITLE
Lazy child tabs should also be moved to a new window

### ISSUE THREAD

**Issue by jryans** [piroor/treestyletab#1486]
## Short description

Moving a parent tab to a new window should also move its child tabs as well, including any lazy child tabs.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set up some parent tabs with one or more children tabs, as shown below.
 4. Select parent tab A.
 5. Restart Firefox so that the unselected tabs become lazy tabs.
 4. Right-click on one of the parent tabs (A), choose "Move to New Window".

```
A
|- B (lazy)
\- C (lazy)
D (lazy)
\- E (lazy)
```

## Expected result

I would expect the selected parent tab (A) and its children (B, C) to move together to the new window, and the tree structure should be preserved.

## Actual result

With commit 697d62cbe896ac97fbe8c8d19a41232ecec83bfb, the parent and any non-lazy / loaded child tabs move together to the new window, but lazy child tabs are left behind in the old window. They seem to move to somewhat random locations in the tab list, sometimes becoming a child of the first tab in the old window, for example.

## Environment

 * Platform (OS): macOS 10.12.6
 * Version of Firefox: Firefox Nightly 58.0a1 (2017-10-21) 
 * Version (or revision) of Tree Style Tab: 697d62cbe896ac97fbe8c8d19a41232ecec83bfb

**Comment by piroor** [comment]
More info: if I try to run "move to new window" from Firefox's native context menu on the tab bar for a discarded tab like D, it breaks everything...

**Comment by piroor** [comment]
The problem on "move to new window" for a discarded tab seems a bug of Firefox itself - it happens without any addon. See also [Bug 629232 - Move to New Window results in blank page and empty location bar for unloaded tab](https://bugzilla.mozilla.org/show_bug.cgi?id=629232). So I've decided that TST does nothing for this case.

On the other hand, browser.tabs.move() for a discarded tab works correctly for discarded tabs. I continue to research about the problem you reported.

**Comment by piroor** [comment]
By recent changes, most of this problem seems to be fixed. However there is one limitation: when you try to open the tab A, the tab B is always restored, because Firefox always focus to the next tab for "move to new window" command.

**Comment by jryans** [comment]
Great, this looks fixed to me as well. Thanks! 😁
