### ISSUE TITLE
[latest dev] Tabs are lost after session restore if Nightly is closed right after tabs finished loading

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1487]
Create new profile, install TST dev https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi , close Nightly, launch Nightly
Go to https://github.com/ in the active tab
Ctrl-click Features, Business, Explore (that's hyperlinks)
As soon as all tabs finish loading, close Nightly
Launch Nightly, restore session

ER: 4 tabs are restored 
AR: 2 tabs are restored, information loss

The key step is "As soon as all tabs finish loading, close Nightly". If I wait ~10 seconds before closing Nightly, bug is not reproduced

I'll now try to figure out if bug reported in this thread is also timing-related: https://github.com/piroor/treestyletab/issues/1476

**Comment by piroor** [comment]
Is this same to #1445?

**Comment by SXZ1** [comment]
Yes, I think so: I've just reproduced this bug without TST installed so I believe that's a Firefox bug. Thank you!
