### ISSUE TITLE
[dev][Session restore] Stack inside stack: tree structure and order of tabs are messed up after session restore

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1488]
Nightly 23-10-17, Win8.1
Create new profile, install TST from https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi, disable "Groups tabs opened within 100ms" in TST settings (I've reproduced the bug without modifying this pref, I just want to make sure it doesn't mess something)
Close Nightly, launch Nightly
Open new window
Go to github.com in the active tab, ctrl-click on "Features" and "Business" (that's hyperlinks on github.com)
Press Ctrl-2, ctrl-click on "Features", press Ctrl-4, ctrl-click on "Business"
Right click - TST - "Collapse all"
Open new tab, go to github.com, wait 10 sec in order to make sure Firefox session restore saves all data
Close Nightly, launch Nightly - restore session

ER: tab order and tree data are restored properly
AR: tab order and trees are messed up, before/after:
![newgen1](https://user-images.githubusercontent.com/26294581/31940442-db580a7c-b8c6-11e7-81ea-07dfc3841831.png)
 
I believe that's not a duplicate of https://github.com/piroor/treestyletab/issues/1476 because STR is different: this bug is caused by stack inside stack, bug 1476 is caused by the active tab inside the stack during shutdown.

**Comment by piroor** [comment]
Thanks. This problem is caused by asynchronous operations. By recent commits, tabs are rearranged synchronously if possible and the problem seems to be fixed on my environment.

**Comment by SXZ1** [comment]
I can no longer reproduce this bug in latest dev build, looks like this bug is fixed. Thank you very much! However, active tab inside the stack before shutdown still messes tab order and tree structure after session restore. STR:

Create new profile, install TST
Disable "Auto-group tabs opened within 100 msec" in TST Options
Close Nightly, launch Nightly, go to https://bugzilla.mozilla.org/
Ctrl-click New, Browse, Search
Press Ctrl-2, wait 10 sec in order to make sure Firefox session restore saves all data
Close, Nightly, launch Nightly, restore session

AR: See the screenshot below, tab order is messed up, tree structure is messed up, one more pseudo-stack is formed that can't be properly collapsed/expanded:
![image](https://user-images.githubusercontent.com/26294581/31964866-27d746d2-b90e-11e7-817c-99ea51ceb3e8.png)

**Comment by SXZ1** [comment]
I've just found one more STR when this bug is reproduced. Use STR from the first post but add the new step (marked in bold):
Close Nightly, launch Nightly
**Open new window**
...

Before/after:
![tst2710](https://user-images.githubusercontent.com/26294581/32106089-616ab51a-bb33-11e7-92a8-2a5bbd9f0dca.png)

**Comment by piroor** [comment]
I've introduced some more fixes around tree restoration. Could you try the latest development build?

**Comment by SXZ1** [comment]
I can no longer reproduce this bug with latest dev build (5552) so I assume this bug is fixed. Thank you very much, great job!
