### ISSUE TITLE
[dev][Session restore] Stack in stack in stack: tree structure and order of tabs are messed up after session restore

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1489]
Win8.1, Nightly 24-10-17.
Create new profile, install TST dev from https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi
Disable "Autogroup tabs opened within 100 msec" in TST settings, close and launch Nightly
**Open new window (bug is reproduced with or without this step with a bit different results. Look at before/after comparison at the the end of the post)**
Go to github.com, ctrl-click Marketplace, Pricing
Press Ctrl-3, ctrl-click Features, Business, Explore
Press Ctrl-2, ctrl-click Features, Business
Press Ctrl-4, ctrl-click Features, Business, Explore
Press Ctrl-3, ctrl-click Features, Business, Explore
Press Ctrl-T, go to github.com, wait 10 seconds, close Nightly, launch Nightly

ER: tab order and tree data are restored properly
AR: tab order and trees are messed up.

Before/after one window:
![str1 3](https://user-images.githubusercontent.com/26294581/31988357-746acd48-b977-11e7-9638-bf7c028a69a3.png)

Before/after two windows:
![str1 3 2](https://user-images.githubusercontent.com/26294581/31988363-770f8b92-b977-11e7-875b-c71a2ff21aa4.png)

I believe that's not a duplicate of #1476 or #1488 because STR is different: this bug is caused by stack inside stack inside stack, bug 1476 is caused by the active tab inside the stack during shutdown, bug 1488 is caused by stack inside stack.

**Comment by piroor** [comment]
I've introduced some more fixes around tree restoration. Could you try the latest development build?

**Comment by SXZ1** [comment]
I can no longer reproduce this bug with latest dev build (5552) using both STR so I assume this bug is fixed. Thank you very much, great job!
