### ISSUE TITLE
[feature request] clone / duplicate tab as sibling or child

### ISSUE THREAD

**Issue by stefan123t** [piroor/treestyletab#1490]
## Short description

I am using TreeStyleTabs for more than 10 years now. Actually it is the only thing keeping me from switching to any other Browsers as using it has become such a habit, I can not image a Internet Browser without it. Thanks for enhancing my online experience, this is a really great thing!
Besides that I only require ProxySelector, AdBlockPlus and notable BarTabHeavy Plugin to unload my outdated Tabs (usually around 500-800) and save me some memory.

I often come to the situation where I need another tab of the current open tab.
E.g. during a hunt for some search results, products, whatsoever on that page or another.
It would be nice to have the current search result form duplicated / cloned and sorted as next sibling (or optional as child) into the tab tree. This way I could simply clone and enter a new search term, which would be neatly sorted into my tabs.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open subtree of tabs
 4. Browse to e.g. a search page 
 5. Open a couple of results as child tabs
 6. If you want to add another search term result set in this tree, you would need to 
   a. copy the URL of the search page
   b. create a new tab, 
   c. enter the URL of the search page
   d. enter your search termn
   e. move the new tab with search results as a sibling (or child) into the previous tab tree.
 or
   A. right click on current tab
   B. select Clone tab as sibling (or child)
   C. update your search term
   D. No new tab reordering required =^)

```
A
\- B (collapsed)
C google
\- D other page search term ABC  (selected)
  \- E search result 1 for ABC
  \- F search result 2 for ABC
J other tabs
+ New tab button
```

## Expected result

```
A
\- B (collapsed)
C google
\- D other page search term ABC  (selected)
  \- E search result 1 for ABC
  \- F search result 2 for ABC
\- G same page search term DEF (cloned as result set for ABC)
  \- H search result 1 for DEF
  \- I search result 2 for DEF
J other tabs
+ New tab button
```

## Actual result

```
A
\- B (collapsed)
C google
\- D other page search term ABC  (selected)
  \- E search result 1 for ABC
  \- F search result 2 for ABC
\- G same page search term DEF (newly created as K, entered the URL copied from E and moved here)
  \- H search result 1 for DEF
  \- I search result 2 for DEF
J other tabs
[K New tab (copy URL of D here and search for DEF, then move to G)]
+ New tab button
```

## Environment

 * Platform (OS): 
Linux mint x86-64bit 18.2 Sonya
 * Version of Firefox: 
56.0
 * Version (or revision) of Tree Style Tab: 
0.19.2017090601

**Comment by sumyungguy** [comment]
Install addon "Multiple Tab Handler" also by Piro, it gives "duplicate tab" function. You can adjust with TST settings whether it opens as child etc.

In Firefox 56 or earlier, you can also use Dorando Keyconfig addon to make keyboard shortcuts to duplicate current tab as child, sibling, etc., for example:

Duplicate as child:
```
TreeStyleTabService.readyToOpenChildTab(gBrowser.selectedTab);
gBrowser.duplicateTab(gBrowser.mCurrentTab);
```
Duplicate as next sibling:
```
gBrowser.selectedTab = gBrowser.duplicateTab(gBrowser.mCurrentTab);
gBrowser.treeStyleTab.promoteCurrentTab();
```
Duplicate as independent:
```
gBrowser.selectedTab = gBrowser.duplicateTab(gBrowser.mCurrentTab);
setTimeout("gBrowser.moveTabTo(gBrowser.selectedTab);", 0);
```

**Comment by VladimirMarkelov** [comment]
In FF57 'duplicate tab' works different depending on where to call it. 
If I call it from top tab row(standard FF tab row) popup menu - it works great and a new tab appears in TreeView tree. 
If I call it from popup menu of tab in TreeView tree than TreeView turns gray(like inaccessible) for a while, new tab in top tab row appears, a dropdown icon on the tab inside TtreeView tree appears as well but the new duplicated tab does not appear in TreeView tree.

**Comment by piroor** [comment]
@VladimirMarkelov This issue is about TST 0.19. Could you file open new issue for TST 2.x? The command "duplicate tab" in TST's sidebar is not a native one but a reimplemented version based on WebExtensions APIs. Because WE API's `browser.tabs.duplicate()` doesn't work same as native one, I had to do more things to simulate the result of the native one.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
