### ISSUE TITLE
[dev 5552][MTH2.0.3] Order of tabs and tree structure are messed up after reopening the sidebar

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1493]
STR:
Create new profile, install TST dev https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi, install Multiple Tab Handler from AMO because I couldn't get MTH from .jp work with TST.

Press Ctrl-T 8 times, then follow the steps on this picture:
![tutorial mth](https://user-images.githubusercontent.com/26294581/32123927-be4d8150-bb6e-11e7-84fb-138025637c45.png)

I'll comment what's drown there: Form two stacks by drag n' drop, collapse them, select 3 tabs/stacks and drag them on top of the last tab. Then create a new tab and close/open the sidebar. Expand the stack.

Before/after comparison:
![mth before after](https://user-images.githubusercontent.com/26294581/32123951-cff6ab84-bb6e-11e7-8cf1-a5f06da2e65d.png)
Posting in TST since I am not sure this bug can't be reproduced without Multiple Tab Handler. However, I couldn't repro this bug without MTH so far.

**Comment by SXZ1** [comment]
I've just reproduced this bug with latest TST dev (5552) and MTH2.0.3 from AMO. I couldn't get latest MTH beta to work with TST 5552, unfortunately.

**Comment by piroor** [comment]
> Multiple Tab Handler from AMO because I couldn't get MTH from .jp work with TST.

Oops, sorry it was my mistake. Now it works with TST again.

**Comment by piroor** [comment]
In such case tabs were internally moved again and again. By recent commits, needless moving of tabs are reduced. I couldn't reproduce the problem with this steps to reproduce anymore.

**Comment by SXZ1** [comment]
I can no longer reproduce the bug in TST 5559 and latest MTH dev. Bug is fixed, thank you very much! Great job!
