### ISSUE TITLE
Intermittently cannot select, reload, close, move tabs, etc.

### ISSUE THREAD

**Issue by 53245342099** [piroor/treestyletab#1495]
## Short description

Intermittently cannot select, reload, close, move tabs, etc.

## Steps to reproduce

Intermittent problem...unsure what causes it to happen.

## Expected result

Expect it to work.

## Actual result

Doesn't work until restart.

## Environment

 * Platform (OS): Windows 10 1709 16299.19
 * Version of Firefox: 57.0b12 64 bit
 * Version (or revision) of Tree Style Tab: 2.07

**Comment by piroor** [comment]
I close this because outdated.
