### ISSUE TITLE
compability issue

### ISSUE THREAD

**Issue by RoninSavant** [piroor/treestyletab#1496]
## Short description
had to refresh FF after TLS decided to die, now can't install TST as it's reporting a compatability issue.

## Environment

 * Platform (OS): macOS 10.13 (17A405)
 * Version of Firefox: 56.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab:  2.0.7 

![screen shot 2017-10-28 at 5 37 11 pm](https://user-images.githubusercontent.com/33186680/32138753-b3cebd82-bc06-11e7-8c7a-420a2ae81ad5.png)

**Comment by RoninSavant** [comment]
I am running 57 BETA on MAC now, and it does work, so it seems to not like anything previous to 57 on Mac.

**Comment by gnite** [comment]
The 2.0.x versions only work in FF57 and newer. You need to click "View other versions" and scroll down all the way to before the 2.0.x releases to find the legacy version which installs in FF56.

**Comment by piroor** [comment]
I close this because outdated.
