### ISSUE TITLE
[dev][Session restore][Moving stack] Order of tabs and tree structure are messed up after moving stack and using session restore

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1500]
Nightly 30-10-17, TST dev 25-10-17
Create new profile, install TST dev https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi, disable Autogroup tabs opened within 100 msec (bug is likely reproduced without modifying this pref, I just want to make sure it doesn't break something), close-launch Nightly

**Open new window (optional step, bug is reproduced with or without it with a bit different results, see the comparison below)**
Go to https://github.com/marketplace in the active tab, open new tab, go to https://github.com/features , open new tab and go to https://github.com/business
Press Ctrl-1, ctrl-click Marketplace
Press Ctrl-3, ctrl-click Features
Press Ctrl-5, ctrl-click Business
Right click - TST - Collapse all, drag the last stack right below the first stack
Open new tab, wait 10 sec and close nightly
Launch Nightly - Restore session

AR: order of tabs and tree structure are messed up, before after:

One window
![1](https://user-images.githubusercontent.com/26294581/32214725-ddbf96da-be30-11e7-9022-5370670b9c98.png)

Two windows
![2](https://user-images.githubusercontent.com/26294581/32214730-e082061e-be30-11e7-9701-1cb9886bfee6.png)

**Comment by piroor** [comment]
When I reproduce this problem, it is caused by old insertion position information of each tab. By c67419f, now insertion position information of moved tab and around tabs are correctly updated and the problem seems fixed for me.

**Comment by SXZ1** [comment]
I can no longer reproduce this bug in latest dev build (5552) so I assume this bug is fixed. Great job! Thank you!
