### ISSUE TITLE
[dev][FIXED] "Insert position of new child tabs - No control (respect FF decision)" doesn't work as it should

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1501]
Win8.1, TST dev from https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi

STR:
Create new profile
Open new window, go to github.com, ctrl-click Features, press Ctrl-2, press Ctrl-1, ctrl-click Business
Note that Business tab is opened before the Features tab

Install TST https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi, disable animation in TST settings, set "Insert position of new child tabs - No control (respect FF decision)"
Open new window, go to github.com, ctrl-click Features, press Ctrl-2, press Ctrl-1, ctrl-click Business

ER: Business is initially opened before Features but then quickly gets moved after Features
AR: Business tab should be placed before Features tab just like when TST is not installed

Comparison without TST/with TST:
![default](https://user-images.githubusercontent.com/26294581/32274723-41d976e8-bf19-11e7-8035-729f51e16b6c.png)

**Comment by piroor** [comment]
I think 663e4fd should fix this. Could you try the latest development build?

**Comment by SXZ1** [comment]
I've just tried the latest dev build: I can no longer reproduce this bug so I assume it is fixed. Now the only bugs left that seem critical to me are the bugs about the loss of tree structure/order of tabs after session restore. Thank you very much!

**Comment by cole-h** [comment]
(@SXZ1 For future reference, you close an issue to mark it as fixed)
