### ISSUE TITLE
Close tabs to the right can close tabs in *other* windows

### ISSUE THREAD

**Issue by mlissner** [piroor/treestyletab#1502]
## Short description

If you right click on a tab and select "Close tabs Right" it can sometimes close tabs from other windows.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open several tabs across multiple windows
 4. Use close tabs to the right on each window. On one or the other it will close more than it should.

## Expected result

Only close tabs in the current window.

## Actual result

Sometimes tabs are closed in other windows. I've noticed a few times that entire windows got closed, but if the windows are in the background you might not even notice! 

## Environment

 * Platform (OS): Ubuntu
 * Version of Firefox: Nightly, 58.0a1
 * Version (or revision) of Tree Style Tab: 2.0.7

**Comment by SXZ1** [comment]
Might be related: https://github.com/piroor/treestyletab/issues/1498
Also, try to reproduce the bug using latest beta:
https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi

**Comment by piroor** [comment]
Thanks, this was my mistake and fixed by 87313e7.
