### ISSUE TITLE
Tabs duplicated in wrong positions, can cause Firefox to crash

### ISSUE THREAD

**Issue by sumyungguy** [piroor/treestyletab#1506]
## Short description
Duplicating tab with middle-click on reload button creates tabs in wrong or random positions, and can cause Firefox to become unresponsive.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open new tab with url github.com.
 4. Middle-click on Reload button.

Expected result: tab is duplicated as next sibling, which is default setting.
Actual result: tab is duplicated as child.

6. With newly-duplicated tab selected, middle-click again on Reload button.

Expected result: tab is duplicated as next sibling.
Actual result: tab is duplicated above, as first child of parent tab.

7. With original parent tab selected, middle-click again on Reload button.

Expected result: tab is duplicated as next sibling.
Actual result: A new duplicate tab shows in the native horizontal tab bar, but doesn't appear in the TST tab bar. The tab contents don't load. Firefox locks up and becomes unresponsive, using 100% CPU. Must be force-quit.

Reproducible every time.

## Environment

 * Platform (OS): macOS 10.12.6
 * Version of Firefox: 57.0b14
 * Version (or revision) of Tree Style Tab: 2.0.7

**Comment by SXZ1** [comment]
Try to reproduce this bug with latest beta:
https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi
It looks like it has already been fixed.

**Comment by sumyungguy** [comment]
Yes, seems to be fixed in the nightly. Sorry for the duplicate, I searched but didn't find an issue about it.
