### ISSUE TITLE
How to hide scrollbar in TST 2?

### ISSUE THREAD

**Issue by sumyungguy** [piroor/treestyletab#1507]
## Short description
Previous solution to hide scrollbar was found in #514, by adding code to userChrome.css, but this no longer works. I found one method, but maybe it can be improved?

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Add the following to "Extra style rules for sidebar contents"
```
:root.left #tabbar {
  overflow-y: scroll; /* always show scroll bar space */
  margin-left: -15px;
}
```
It works but the context menu gets cut off:

![screen shot 2017-11-04 at 2 39 22 pm](https://user-images.githubusercontent.com/5410893/32405880-37f268f4-c16e-11e7-8637-d97fc33b6216.png)

Is there a better method?

## Environment

 * Platform (OS): macOS 10.12.6
 * Version of Firefox: 57.0b14
 * Version (or revision) of Tree Style Tab: 2.0.7.5527

**Comment by irvinm** [comment]
I use just:  #tabbar.overflow { margin-left: -17px; }

However I am seeing the same thing as you if the width of the sidebar is too narrow.  Without this CSS, the right-click menu display logic works properly even with a narrow sidebar.

**Comment by sumyungguy** [comment]
The advantage to my example is that you don't get a glitch when transitioning from scrolling to not scrolling, where the scrollbar appears for a brief moment.

Ok, I did this, which seems to fix the menu cutoff:
```
:root.left #tabbar { 
  overflow-y: scroll;
}

:root.left #tabbar,
#tabContextMenu,
#tabContextMenu ul {
  margin-left: -15px;
}
```

That's only for the sidebar on the left. I don't really have much experience with CSS, just kind of poking around... anyway I'll add it to the code snippets in the wiki unless anyone has more suggestions.

**Comment by irvinm** [comment]
This definitely works well for me.  I would say add it to the wiki and close this out.

**Comment by sumyungguy** [comment]
Ok, I added it to the wiki...

**Comment by sumyungguy** [comment]
> To hide horizontal scroll in Firefox 57.0 on Mac OS X (10.11.6) I used

That doesn't make sense to me. There's no horizontal scroll bar in the TST tab bar. I've removed that snippet from the wiki.

**Comment by hethhhhh** [comment]
Do you have an idea how to make it show only on mouseover?
