### ISSUE TITLE
[dev][Session restore] All stacks are expanded after session restore (one window)

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1508]
Win 8.1, Nightly 06-11-17.
Looks like that's a fallout from one of these commits: 
https://github.com/piroor/treestyletab/commit/5d1b77c7666e8b1b8d502b7fce87d1b94b87816c
https://github.com/piroor/treestyletab/commit/0217021d4b694dff53c6c130b16dc63d3978121a
STR:
Create new profile, install TST from https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi
Close Nightly, launch Nightly
Go to github.com in the active tab, ctrl-click on "Features"
Open new tab, go to github.com
Right click - TST - "Collapse all", wait 10 sec in order to make sure Firefox session restore saves all data
Close Nightly, launch Nightly - restore session

ER: stack is collapsed
AR: stack is expanded. Also, note that collapse/expand indicator is in the wrong state, the number of child tabs shouldn't be displayed
![default](https://user-images.githubusercontent.com/26294581/32497604-1fbdad94-c3de-11e7-8cdf-e9f86dcff755.png)

**Comment by SXZ1** [comment]
Bug is gone after pressing F1 twice.

**Comment by piroor** [comment]
I've introduced some more fixes around tree restoration. Could you try the latest development build?

**Comment by SXZ1** [comment]
Thank you very much! Unfortunately, I can still repro this bug in latest dev build (5552).

**Comment by piroor** [comment]
Thanks. 37eedee should fix this.

**Comment by SXZ1** [comment]
I can no longer reproduce this bug in 5559, bug is fixed. Thank you very much, great job!
