### ISSUE TITLE
[dev][Session restore] Active tab inside stack: Order of tabs/tree structure are not preserved after restoring session

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1509]
That's a remake of bug #1476 with latest info because #1476 is difficult to read due to many comments.
Windows 8.1 x64 with latest updates, Nightly 07-11-17, latest dev from https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi (2017-11-07 21:13 | 513K |  at the time of writing).

STR:
Create new profile, install TST dev https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi
Disable "Auto-group tabs opened within 100 msec" in TST Options
Close Nightly, launch Nightly, go to https://bugzilla.mozilla.org/
Ctrl-click New, Browse, Search
2)Press Ctrl-1 or Ctrl-2 or Ctrl-4
3)Wait 10 seconds, close, Nightly, launch Nightly, restore session

ER: Order of tabs and tree structure are preserved
AR and before/after images: 
**When pressing Ctrl-1**: Order of tabs is correct, stack is gone
![image](https://user-images.githubusercontent.com/26294581/32507794-83fe1f6c-c3f9-11e7-8045-48bae176d99e.png)

**When pressing Ctrl-2**: both order of tabs and tree structure are messed up, one more stack is formed that can't be properly collapsed/expanded
![image](https://user-images.githubusercontent.com/26294581/32507815-9268c926-c3f9-11e7-91a9-227214738dee.png)
**When pressing Ctrl-4**: order of tabs is correct, last tab is removed from the stack
![default](https://user-images.githubusercontent.com/26294581/32507884-bcd52218-c3f9-11e7-9f44-4bd9bf570c21.png)

**Comment by piroor** [comment]
I've introduced some more fixes around tree restoration. Could you try the latest development build?

**Comment by SXZ1** [comment]
Thank you very much! Unfortunately, I can still repro this bug in latest dev build (5552) using all three STR (Ctrl-1,2,4).

**Comment by piroor** [comment]
Hmm, on this case TST failed to restore tab's persistent id (should be kept across sessions) for the active tab. Because the active tab is treated as a simple new tab, other tabs cannot find their parent...

**Comment by piroor** [comment]
By the commit 49bd615, now TST tries to detect such recycled tabs. Now I cannot reproduce this problem on my environment.

**Comment by SXZ1** [comment]
I can no longer reproduce this bug as well with latest dev. Thank you very much, bug is fixed!
