### ISSUE TITLE
Creating a new tree does not collapse other trees

### ISSUE THREAD

**Issue by gnite** [piroor/treestyletab#1515]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Check "When a new tree appears, collapse others automatically" in the options
 4. Create a tab structure something like:

A
\- B
\- C
\- D
E (selected)

 5. Open a child tab to E

## Expected result

Tree A collapses, that was the behavior in legacy TST.

## Actual result

Tree A remains expanded.

## Environment

 * Platform (OS): Win10
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.1.0

**Comment by piroor** [comment]
Thanks, I missed this...

**Comment by gnite** [comment]
This was fixed, but unfortunately either 2.2.0 or 2.2.1 broke it again.

**Comment by piroor** [comment]
Thanks. c23d2a9 should fix this.
