### ISSUE TITLE
What is the import format?

### ISSUE THREAD

**Issue by jtojnar** [piroor/treestyletab#1516]
## Short description
I am trying to convert my tab groups to tree style tabs. I followed the [description](https://github.com/piroor/treestyletab/blob/daa9859022b9a912a141c87d11b760605d783403/webextensions/background/migration.js#L133-L152) from the source code but only structure is imported, not the URL; though the groups seem to have `about:blank?about:treestyletab-group?bah` in the location bar.

[Conversion script](https://gist.github.com/jtojnar/cbe99e0c448b33554b93c48b2cf2e921)

<details>
<summary>Original JSON</summary>

```
{
    "version": [
        "tabGroups",
        1
    ],
    "session": {
        "lastUpdate": 1510271956292,
        "startTime": 1509930093887,
        "recentCrashes": 0
    },
    "windows": [
        {
            "tabs": [
                {
                    "entries": [
                        {
                            "url": "https://mail.google.com/mail/u/0/#inbox",
                            "title": "Inbox (11) - meh@gmail.com - Gmail",
                            "charset": "UTF-8",
                            "ID": 570,
                            "persist": true
                        }
                    ],
                    "lastAccessed": 1510271739406,
                    "hidden": false,
                    "attributes": {},
                    "extData": {
                        "tabview-tab": "null",
                        "treestyletab-id": "tab-<1506816470787-22331>",
                        "treestyletab-insert-before": "tab-<1506816470800-1179>"
                    },
                    "index": 1,
                    "pinned": true,
                    "image": "https://ssl.gstatic.com/ui/v1/icons/mail/images/favicon5.ico"
                },
                {
                    "entries": [
                        {
                            "url": "https://github.com/NixOS/nixpkgs/issues/10874",
                            "title": "Standardize all-packages.nix arguments and stdenv attributes · Issue #10874 · NixOS/nixpkgs",
                            "charset": "UTF-8",
                            "ID": 156,
                            "persist": true
                        }
                    ],
                    "lastAccessed": 1510260419938,
                    "hidden": false,
                    "attributes": {},
                    "extData": {
                        "tabview-tab": "{\"groupID\":1,\"active\":true}"
                    },
                    "index": 1,
                    "image": "https://assets-cdn.github.com/favicon.ico"
                },
                {
                    "entries": [
                        {
                            "url": "https://github.com/NixOS/nixpkgs/blob/bffdf2c0d8117bbed748be3c01262400ac3bc1dd/pkgs/servers/web-apps/selfoss/default.nix",
                            "title": "nixpkgs/default.nix at bffdf2c0d8117bbed748be3c01262400ac3bc1dd · NixOS/nixpkgs",
                            "charset": "UTF-8",
                            "ID": 2485736598,
                            "persist": true
                        }
                    ],
                    "lastAccessed": 1510229604730,
                    "hidden": false,
                    "attributes": {},
                    "extData": {
                        "tabview-tab": "{\"groupID\":3}"
                    },
                    "index": 1,
                    "image": "https://assets-cdn.github.com/favicon.ico"
                }
            ],
            "extData": {
                "tabview-group": "{\"1\":{\"bounds\":{\"left\":366.655236111111,\"top\":32.84375,\"width\":1099.344763888889,\"height\":545.15625},\"slot\":1,\"userSize\":null,\"stackTabs\":true,\"showThumbs\":true,\"showUrls\":true,\"tileIcons\":true,\"catchOnce\":true,\"catchRules\":\"\",\"title\":\"miscellaneous\",\"id\":1},\"3\":{\"bounds\":{\"left\":1750,\"top\":255,\"width\":120,\"height\":110},\"slot\":5,\"userSize\":null,\"stackTabs\":true,\"showThumbs\":true,\"showUrls\":true,\"tileIcons\":true,\"catchOnce\":true,\"catchRules\":\"\",\"title\":\"bah\",\"id\":3}}",
                "tabview-groups": "{\"nextID\":4,\"activeGroupId\":1,\"activeGroupName\":\"miscellaneous\",\"totalNumber\":2}"
            }
        }
    ]
}
```
</details>

<details>
<summary>Converted JSON</summary>

```
[
    [
        {
            "title": "Inbox (11) - meh@gmail.com - Gmail",
            "url": "https://mail.google.com/mail/u/0/#inbox",
            "pinned": true
        },
        {
            "title": "miscellaneous",
            "url": "about:treestyletab-group?miscellaneous",
            "pinned": false,
            "parent": -1,
            "collapsed": true
        },
        {
            "title": "Standardize all-packages.nix arguments and stdenv attributes · Issue #10874 · NixOS/nixpkgs",
            "url": "https://github.com/NixOS/nixpkgs/issues/10874",
            "pinned": false,
            "parent": 1,
            "collapsed": true
        },
        {
            "title": "bah",
            "url": "about:treestyletab-group?bah",
            "pinned": false,
            "parent": -1,
            "collapsed": true
        },
        {
            "title": "nixpkgs/default.nix at bffdf2c0d8117bbed748be3c01262400ac3bc1dd · NixOS/nixpkgs",
            "url": "https://github.com/NixOS/nixpkgs/blob/bffdf2c0d8117bbed748be3c01262400ac3bc1dd/pkgs/servers/web-apps/selfoss/default.nix",
            "pinned": false,
            "parent": 3,
            "collapsed": true
        }
    ]
]
```
</details>

How should the JSON be formatted?

## Steps to reproduce

1. Insert the converted JSON into preferences
2. Check “migrate trees”
3. Restart Firefox

## Expected result
![correct tree](https://user-images.githubusercontent.com/705123/32640566-8e39644c-c5c9-11e7-8cdc-064cefc19aa6.png)

## Actual result
![empty tree](https://user-images.githubusercontent.com/705123/32640592-b2224310-c5c9-11e7-8d45-c9172c76f85c.png)

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 58.0a1 (2017-11-09) (64-bit)
 * Version (or revision) of Tree Style Tab: 2.1.0

**Comment by piroor** [comment]
I'm very sorry, I missed to return the URI if it seems loadable...

**Comment by jtojnar** [comment]
Normal URLs seem to load, the `about:treestyletab-group?miscellaneous` still results in `about:blank?about:treestyletab-group?miscellaneous`, though.

Also the message “1 window(s) are restored only their tree structure.” appears. How can I import more information?

Last, I have around 2200 tabs in 25 groups, would it be possible to load them more gracefully? I waited for 30 minutes before I gave up.

**Comment by piroor** [comment]
Due to WebExtensions API's limitation, addons cannot open any special URI like "about:config", so TST opens a tab with "about:blank?" prefix as a workaround. This feature is basically designed with these expectation:

 * Tabs and session information are completely restored by Firefox itself.
 * Tree information is exported by old TST 0.19.x.
 * Migration is done by these steps:
   1. Export tree structure by TST 0.19.x.
   2. Upgrade to Firefox 57 - then Firefox restores all tabs without tree information.
   3. Upgrade to TST 2.x
   4. Paste your exported data to the input field for migration.
   5. Restart Firefox - then tabs are restored by Firefox itself and tree structure is applied by TST.

However I agree that these steps are too ugly. So I've released a utility command to migrate sessionstore.jsonlz4 directly: [treestyletab-sesssionstore-migrate](https://www.npmjs.com/package/treestyletab-sesssionstore-migrate). Could you try it?

**Comment by lorenzyannick** [comment]
I tried your command line treestyletab-sessionstore-migrate in different ways, no one seems to work.
I've the top bar with the current group and tabs, the side bar with tree style is empty and not working at all.

If I can help to debug please tell me !

**Comment by piroor** [comment]
Sorry, TST 2.2.4 was broken on Fx57. Now 2.2.5 is available.

**Comment by lorenzyannick** [comment]
Working well with 2.2.5 !!!!
On the other side, I'm still looking for a group tab feature as previusly on FF45
Thx a lot.

**Comment by piroor** [comment]
I close this because outdated.
