### ISSUE TITLE
[dev] Expand/collapse animation stutters, sidebar unresponsive when big number of tabs is open

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1517]
Win 8.1, Nightly 09-11-17, https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi
Create new profile, install TST, close Nightly, paste sessionstore.jsonlz4 from the archive to the root of the profile folder overriding existing file, launch Nightly, restore session
[sessionstore.zip](https://github.com/piroor/treestyletab/files/1460613/sessionstore.zip)
Now please look at the images, use arrow to the left of the favicon to expand/collapse stacks.
![2 2](https://user-images.githubusercontent.com/26294581/32650383-9d6284e0-c60e-11e7-9cbe-cc4312e90b4d.png)
![1 2 2](https://user-images.githubusercontent.com/26294581/32650386-a12c62d0-c60e-11e7-965b-41179f2093ef.png)
![1 2 2](https://user-images.githubusercontent.com/26294581/32650388-a57dfea2-c60e-11e7-809f-5a48fc0bacb1.png)

**Comment by SXZ1** [comment]
Bug is fixed in 5559. Great job, thank you very much!

**Comment by piroor** [comment]
It was caused by recalculation of style definitions. By recent commits I've changed the timing to recaculate indent levels so this unresponsive time doesn't appear while animation anymore.
