### ISSUE TITLE
[2.1.2] Expand/collapse animation stutters, sidebar unresponsive after opening or closing new tab

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1519]
Win 8.1, Nightly 11-11-17, TST2.1.2. STR:
Create new profile, install TST, close Nightly, paste sessionstore.jsonlz4 from the archive to the root of the profile folder overriding existing file, launch Nightly, restore session
[sessionstore.zip](https://github.com/piroor/treestyletab/files/1464780/sessionstore.zip)

Switch to the last tab, hover the mouse over the first tab and start moving the mouse down. Notice that when the mouse is hovered over the tab, that tab is highlighted with light blue color
Press Ctrl-W and keep moving the mouse down

ER: light blue color is always under the tab the mouse is pointing to
AR: after ~2 seconds after closing a tab light blue color stops for ~2 seconds and no longer follows the mouse movement. That means sidebar is unresponsive

Same problem when opening a new tab using ctrl-click (**bug is not reproduced when pressing Ctrl-T**!):
Switch to the last tab, ctrl-press Features, quickly hover the mouse over the sidebar and start moving it down.

ER: light blue color is always under the tab the mouse is pointing to
AR: after ~2 seconds after opening new a tab light blue color stops for ~2 seconds and no longer follows the mouse movement. That means sidebar is unresponsive

**Comment by SXZ1** [comment]
Bug is also reproduced when dragging any tab on top of any other tab to make a stack.

**Comment by piroor** [comment]
Sorry I couldn't understand what is the bug, with text-based descriptions... Could you upload any screencast?

**Comment by SXZ1** [comment]
This bug is basically identical to https://github.com/piroor/treestyletab/issues/1517
The only difference is that this bug is triggered by ctrl-clicking on a link or dragging tab on top of other tab to make a stack. I'll try to make a screencast.

**Comment by SXZ1** [comment]
![1](https://user-images.githubusercontent.com/26294581/32715169-3091288e-c862-11e7-8045-cbe08083b2b3.png)
![2](https://user-images.githubusercontent.com/26294581/32715171-339e0196-c862-11e7-9b12-801b031cabcc.png)
![3](https://user-images.githubusercontent.com/26294581/32715224-6b5409b4-c862-11e7-88ac-c1ff51b8887e.png)

**Comment by piroor** [comment]
Thanks. Hmm, in this case recalculation of indent levels seems to take CPU time...

**Comment by piroor** [comment]
After some optimization, collapse/expand animation and other layout recalculations become faster even if there are too many collapsed tabs. Could you try new development build?

**Comment by SXZ1** [comment]
Thank you very much! Unfortunately, I don't notice any improvement in 2.1.2.5638 (latest dev).

**Comment by piroor** [comment]
On 2.2.0, more optimization has landed. I hope that this problem is resolved by this change...

**Comment by SXZ1** [comment]
I couldn't reproduce this bug in 2.2.0 so far. I'll try again tomorrow to know for sure but I am confident this bug is fixed. You have done an excellent job, @piroor! I think everyone who is monitoring TST development is extremely impressed with your skills and passion. TST is truly a masterpiece. Thank you very much!

**Comment by SXZ1** [comment]
Bug is fixed! Thank you much! \o/
