### ISSUE TITLE
Strange tab opening and focus switching behavior

### ISSUE THREAD

**Issue by gnite** [piroor/treestyletab#1522]
## Short description

If you open tabs quickly they don't open in the proper order anymore, also sometimes focus switches not where you expect. See recording: https://streamable.com/y2bcf. This seems to be new in 2.2.0.

## Environment

 * Platform (OS): Win10
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.2.0

**Comment by gnite** [comment]
Looks like I was wrong, it does not matter how quickly the tabs are opened. Even when slowly clicking through links the same happens. I don't see any obvious reason that would make those tabs open in the wrong place.

**Comment by piroor** [comment]
On 2.2.1 some regressions are fixed. Could you try it?

**Comment by gnite** [comment]
Sorry, I just tried with 2.2.1 and both issues still exist.

**Comment by piroor** [comment]
Thanks, I've confirmed this with the setting.

**Comment by gnite** [comment]
Yes, the first problem with the opening requires that tabs are inserted at the top. For the one with the closing it makes no difference. These should probably have been two separate issues, sorry for that.

**Comment by piroor** [comment]
3ad12ac should fix this. Thanks!
