### ISSUE TITLE
[2.2.0] new window tab doesn't close as expected

### ISSUE THREAD

**Issue by MMeent** [piroor/treestyletab#1523]
## Short description
When you move a tab into a new window (pull the tree away from the sidebar, or 'move to new window' in the right-click menu), the tree of the new tab is broken, and you can't close the tabs you've moved.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a few tabs
 4. Move a root tree another window (pull away from sidebar, or click 'move to new window')

## Expected result
New window has tree structure of the selected (sub)tree

## Actual result
New window now has no tree structure, and unresponsive tab headers.

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 57.0
 * Version (or revision) of Tree Style Tab: 2.2.0

Sidenote: This happened using a github page. looking at the console outputs, I see some Content Security Policy error outputs: 
```js
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://assets-cdn.github.com”). Source: (function injected(eventName, injectedIn.... (treestyletab:1)
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://assets-cdn.github.com”). Source: ;(function installGlobalHook(window) { ....(treestyletab:1)
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://assets-cdn.github.com”). Source: !function(t){function __webpack_require_....(treestyletab:1)
```

**Comment by piroor** [comment]
Sorry, it was a regression. It should be fixed by recent commits.
