### ISSUE TITLE
Is it possible to remove the close button on the tabs?

### ISSUE THREAD

**Issue by erikw** [piroor/treestyletab#1524]
As it says, on the new webextension version of the plugin?

In the old extension it was possible to hide the close button on tabs using the hack described at https://github.com/djc/no-close-buttons but this does not affect the close button on this newer version of treestyletab.

Thanks,

**Comment by SXZ1** [comment]
It's possible to show close button on hover using this .css from wiki:
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#only-show-tab-close-button-on-hover-1448

**Comment by DaSourcerer** [comment]
I can confirm this works:
```css
.tab .closebox {
  display: none;
}
```

**Comment by erikw** [comment]
@DaSourcerer indeed, this works, thanks!

@SXZ1 @piroor can we get this workaround added to this wiki page too? I'm sure there will be other people looking for this too.

**Comment by piroor** [comment]
OK, I've added it. https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-tab-close-button-always-1524

**Comment by erikw** [comment]
Super, thanks!

**Comment by anjiro** [comment]
Using the Multiple Tab Handler extension, this CSS prevents highlighting the close button when dragging to close several tabs. Is there some extra CSS to allow the close buttons to be displayed when Multiple Tab Handler is ready to close the tabs?
