### ISSUE TITLE
Integrate with current theme

### ISSUE THREAD

**Issue by nt1m** [piroor/treestyletab#1526]
From 58 onwards, you can get the current theme properties: 

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/theme/getCurrent

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/theme/onUpdated

Why is this useful ?
Integrating with dynamic themes like [VivaldiFox](https://addons.mozilla.org/en-US/firefox/addon/vivaldifox/) or [Container Theme](https://addons.mozilla.org/en-US/firefox/addon/containers-theme/)

A lot of people have expressed their wish to see VivaldiFox work with their favourite sidebar tabs add-on.

**Comment by piroor** [comment]
Thanks, I've implemented the feature. However, due to limitations of WebExtensions APIs, builtin theme color won't be applied including themes installed from mozilla.addons.org. Only colros applied by addons are available.

**Comment by nt1m** [comment]
@piroor Thank you for implementing this! :)

I've tested this from the latest AMO release, and it's pretty awesome! One thing I found strange was the hover state on the selected tab:

<img width="218" alt="screen shot 2017-11-15 at 9 47 10 am" src="https://user-images.githubusercontent.com/1795135/32829443-085f9808-c9ea-11e7-9b4c-277237784083.png">

Other than that, great work :)

> However, due to limitations of WebExtensions APIs, builtin theme color won't be applied including themes installed from mozilla.addons.org. 

Technically built-in themes (Light/Dark) are quite different from WebExtension themes, which makes it quite difficult to implement. Another problem is that lightweight themes aren't supported by the API either. I was aware of those restrictions when implementing this API :)

**Comment by nt1m** [comment]
@piroor I noticed you don't use the `windowId` parameter provided by `getCurrent()` and `onUpdated`.  It would be nice if this was implemented, because multiple windows can have different themes.

**Comment by ELLIOTTCABLE** [comment]
I'm curious about VivaldiFox; but I can't visualize how this would look with TST.

Either of you mind posting a screenshot of your setup, with coloured tabs?

**Comment by polyzen** [comment]
[Theme permission will be unnecessary in Fx 62.](https://bugzilla.mozilla.org/show_bug.cgi?id=1469318)

Implementing this means changing the Firefox theme to dark will do the same for TST? This would save some trouble as I switch between light and dark themes based on ambient light (twice a day), and currently that means manually toggling themes in Fx, TST, and Stylus. Luckily in Fx 62 there are a few less clicks involved:

> Extensions with a toolbar button (browser action) can now be managed directly from the context menu of the button.

**Comment by piroor** [comment]
TST respects theme colors provided by other addons, only when one of Plain, Vertigo or Mixed is chosen as the skin. By recent changes, now TST applies more colors implemented in lately versions of Firefox. You can try the development build on Nightly and I'm waiting more feedback.: https://github.com/piroor/treestyletab/blob/master/README.md#development-builds

**Comment by piroor** [comment]
I close this because outdated.
