### ISSUE TITLE
Drag and dropping text on empty space in sidebar adds header to the text, overriding default setting.

### ISSUE THREAD

**Issue by akpkc** [piroor/treestyletab#1527]
## Short description
Drag and dropping text on empty space in sidebar adds header to the text, overriding default setting which is searching the said text.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Select any text (non-link) from any page
 4. Drag and drop over any empty space in sidebar.

## Expected result
It should search (or something else if overridden) the text that dropped over sidebar. It works without any issue when dropping over default tab bar of Firefox 57.

## Actual result
Example for "test12": moz-extension://30ffdb85-3182-4e3b-9444-5b236ba3a4f8/background/test12

## Environment

 * Platform (OS): Windows 10, Fall Creators Update
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.2.3

**Comment by piroor** [comment]
Due to limitations of WebExtensions APIs, it can't be implemented for now. We need more API to retrieve installed (default) search engine. See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1352598

**Comment by piroor** [comment]
After such an API is introduced, we need to retrieve search engines and convert non-URI value to a search URI at:
https://github.com/piroor/treestyletab/blob/c23d2a9050b99b781524f6c3435f12ce77b5cc3b/webextensions/sidebar/drag-and-drop.js#L380
https://github.com/piroor/treestyletab/blob/c23d2a9050b99b781524f6c3435f12ce77b5cc3b/webextensions/common/tree/base.js#L718

**Comment by oxysoft** [comment]
Hoping Mozilla can add the support for this very soon because this is very vital for my workflow. I can survive with `right click > search` for now but this is a major inconvenience for me as well!

**Comment by wai-fu** [comment]
Can we have a manual workaround for FF "regression" like what "ContextSearch web-ext" has implemented?
Since search engine is not meant to be changed so often (if not at all)

**Comment by tk-nguyen** [comment]
Mozilla is adding support for Search API in firefox 63 so I hope this issue will be implemented soon enough! Right-click and search is a pain to me.

**Comment by piroor** [comment]
Done by 15c301d.

**Comment by piroor** [comment]
2.6.1 including this feature is now available.
