### ISSUE TITLE
Drag and drop of text should open a search for that text

### ISSUE THREAD

**Issue by Creifelds** [piroor/treestyletab#1528]
**Sorry the exact same problem was posted while I was typing this: #1527 **

## Short description
Selecting an URL (plaintext) with your mouse and then putting it in the TST area will open a new tab with that URL. In previous versions doing the same with text that is not an URL, the text would open a new tab with a search (e.g. Google) for that text.

In the current version doing that will lead to a new tab opened to an URL like "moz-extension://f593caad-a509-4412-819e-e08798e0f1ff/background/some text I dragged and dropped on TST"

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3.  Mark random text.
 4.  Drag and drop the selected text on the TST area.

## Expected result
A search should open with that text as the search term.

## Actual result
A new tab with a mangled URL opens.

## Environment

 * Platform (OS): Windows 10 x64
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.2.2

**Comment by piroor** [comment]
I close this as a duplicated issue.
