### ISSUE TITLE
Sidebar is not automatically opened in Private Browsing mode

### ISSUE THREAD

**Issue by nneonneo** [piroor/treestyletab#1529]
## Short description
I run TST with the tab bar hidden (userChrome hack) in FF 57. When I open a private browsing window, TST is not visible, requiring me to press F1 to get it back. (However, because I don't have the function keys shown on my laptop, it actually requires clicking the TST icon).

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open TST in the sidebar.
 4. Open a new private window.

## Expected result
New private window contains TST sidebar.

## Actual result
New private window does not have any sidebar open.

## Environment

 * Platform (OS): macOS
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.2.0

## Notes

I believe this is caused by a Firefox bug, https://bugzilla.mozilla.org/show_bug.cgi?id=885054. Previously, I was using a different extension that was not a sidebar. I am wondering if TST will have some kind of option to open itself on new windows, as the usability of the browser is decreased in a window with no TST and no tab bar.

**Comment by Nono-m0le** [comment]
+1
The firefox issue is fixed isn't ?

**Comment by nneonneo** [comment]
I should have clarified - the fix to that issue caused the sidebars not to appear in Private Browsing mode.

**Comment by layus** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1268550, the follow-up of the above bug.

**Comment by piroor** [comment]
I close this because this is out of the range of WebExtensions-based extension.
