### ISSUE TITLE
Tree Style Tab is disabled in Firefox 57

### ISSUE THREAD

**Issue by jrysig** [piroor/treestyletab#1532]
1. Start Firefox with clean profile.
 2. Install TST.
 3. Open two tabs.
 4. TST is disabled, tabs are not displayed.

![image](https://user-images.githubusercontent.com/7038517/32824943-4f715288-c9e3-11e7-8961-5ddced2f1871.png)

 * Platform (OS): Windows 10 x64
 * Version of Firefox: 57 x64
 * Version (or revision) of Tree Style Tab: 2.2.4

**Comment by aussieade** [comment]
just updated firefox on mac, updated TST to v2.2.4 and seeing the same result

**Comment by nahouto** [comment]
same problem

**Comment by zzottel** [comment]
Same here. Worked perfectly in the beta all the time. After the new FF version was out, I now switched back to the stable channel.

TST worked there, too, but then it asked for new permission (seeing all my website data?), was updated, and afterwards this.

**Comment by piroor** [comment]
Sorry, I've disabled 2.2.4 on AMO. I think browser.theme can cause this problem...

**Comment by aussieade** [comment]
2.2.3 working fine, thanks for the great addon (couldn't live without it ;-)

**Comment by Indystef** [comment]
Same here. A fast fix would be appreciated ... TST has been a real productivity enhancer so far.

**Comment by piroor** [comment]
I've released 2.2.5 and it works on Fx57. I wrongly called unimplemented feature on Fx57... (it is available only on Fx58 and later)

**Comment by leeuwenrjj** [comment]
Thx, works now for me!

**Comment by Andy456** [comment]
Thank you very much. I works and I am happy :-)

**Comment by jrysig** [comment]
Thank you, it works now.
