### ISSUE TITLE
Does not work on a clean install 

### ISSUE THREAD

**Issue by psamim** [piroor/treestyletab#1533]
## Short description
I just updated to FF57 and installed treetabstyles as a repacement for tab groups. The sidebar is displayed but the tabs are not loaded into it.  have restarted several times and tried a clean profile. I am on ArchLinux.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 
 
## Expected result
To see the tabs in the sidebar.

## Actual result
 Loading animation is displayed but tabs are not loaded.

## Environment

 * Platform (OS): ArchLinux
 * Version of Firefox: 57.0
 * Version (or revision) of Tree Style Tab: 2.2.4

**Comment by dannoe** [comment]
I had the same problem after the normal update to FF57.
After reseting my firefox it worked, but only a short time. The addon asked for a new permission and after granting it, it was broken again. 

Im just seeing the "loading dot". The + button is also not working.

**Comment by Andy456** [comment]
Same, no Tabs. I dont know how the new version should work. What muß I do or is it ab bug. I see only the Firefoxtabs a the top of the window.
Please, please fixed that great extension.

**Comment by piroor** [comment]
Dup of #1532
