### ISSUE TITLE
Doesn't work with "Tab Groups" in 59.0a1

### ISSUE THREAD

**Issue by kevinptt0323** [piroor/treestyletab#1534]
## Short description

Doesn't work with "Tab Groups" in 59.0a1 with Legacy add-ons enabled.

It will show "all tabs" instead of tabs in current group.

// Sorry for the strange environment.

## Steps to reproduce

1. Start Firefox with clean profile.
2. set config `extensions.legacy.enabled` to `true`.
3. Install TST.
4. Install Tab Groups.
5. Create 2 tab groups with tabs.

## Expected result

Show tabs in current group only.

## Actual result

It will show "all tabs".

## Environment

 * Platform (OS): Mac OS X 10.11.6
 * Version of Firefox: 59.0a1
 * Version (or revision) of Tree Style Tab: 2.2.3

**Comment by piroor** [comment]
I think it can't be "fixed" by treestyletab, because there is no WebExtensions API to read metadata stored on the XUL layer. There is no way except waiting for https://bugzilla.mozilla.org/show_bug.cgi?id=1384515 and migration of Tab Groups to WebExtensions...

**Comment by kevinptt0323** [comment]
"Tab Groups" is deprecated.
