### ISSUE TITLE
TST does not focus the right child tab after rearranging the bottom child tab

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#1537]
## Short description
After rearranging the bottom child tab into another position in the same tree, closing the said tab will always focus the last tab in the tree instead of the next tab.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Create a tree with a few child tabs:
````
Parent
\- Tab A
\- Tab B
\- Tab C
\- Tab D
````
 4. Drag and move Tab D above Tab A or B, e.g.:
````
Parent
\- Tab D
\- Tab A
\- Tab B
\- Tab C
````
5. Focus Tab D, close Tab D.

## Expected result
After closing Tab D, the next tab, i.e. Tab A, should be focused.

## Actual result
Bottom tab (Tab C) is focused instead.

## NOTE
Rearranging other child tabs will not reproduce this issue.

## Environment

 * Platform (OS): Win 10
 * Version of Firefox: Nightly 2017-11-15
 * Version (or revision) of Tree Style Tab: 2.2.7

**Comment by piroor** [comment]
Thanks, this is a regression on recent optimization. d2975e4 should fix this.

**Comment by Fanolian** [comment]
Confirm fixed. Thanks.
