### ISSUE TITLE
New version "Requires access to ALL data from websites" Why?

### ISSUE THREAD

**Issue by bdbaddog** [piroor/treestyletab#1538]
## Short description
Can you explain why the need for new permissions?

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. It updates to newest version 2.2.7 and asks for new permissions "Requires access to ALL data from websites"

**Comment by infogulch** [comment]
See #1536:

> The message is shown due to the permission cookies.  It is required to know the container of each tab (Work, Private, etc.)  by TST. Without this permission, TST cannot colorize container tabs.

**Comment by paride** [comment]
But my container tabs were colored even with the previous version, before the permission was asked... Are you sure it is really needed?

**Comment by infogulch** [comment]
I would ask on the other issue.

**Comment by piroor** [comment]
I close this as a dup.
