### ISSUE TITLE
Close button too small on some tabs and not of the same size in some tabs

### ISSUE THREAD

**Issue by lgp171188** [piroor/treestyletab#1539]
## Short description
Close button too small on some tabs and not of the same size in some tabs
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Resize the TST bar to the minimum width possible
 4. Open multiple tabs under multiple trees

## Expected result
Close button is of the same shape and size in all the opened tabs

## Actual result
Screenshots 1 and 4 seem to have normal shaped and sized close buttons but screenshots 2, 3 have small button with different shapes.
![screenshot from 2017-11-15 23-43-26](https://user-images.githubusercontent.com/218870/32853129-4caf450a-ca60-11e7-8d49-f3eae2f97c82.png)
![screenshot from 2017-11-15 23-43-59](https://user-images.githubusercontent.com/218870/32853131-4ceed01c-ca60-11e7-9905-49c63ae51068.png)
![screenshot from 2017-11-15 23-44-07](https://user-images.githubusercontent.com/218870/32853132-4d2a796e-ca60-11e7-803f-17c3160212f4.png)
![screenshot from 2017-11-15 23-44-12](https://user-images.githubusercontent.com/218870/32853133-4d69c786-ca60-11e7-8a53-94646305543e.png)

## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: 57.0
 * Version (or revision) of Tree Style Tab: 2.2.7

**Comment by lgp171188** [comment]
Note that this happens only when using the "sidebar" theme

**Comment by piroor** [comment]
Thanks. This should be fixed by 388f3ff.

**Comment by lgp171188** [comment]
Installed the latest 2.2.9 version and the issue is gone. Thanks!
