### ISSUE TITLE
[feature request] Disable tree functionality (no branching, just a flat tabs list)

### ISSUE THREAD

**Issue by allixx** [piroor/treestyletab#1544]
## Short description

It would be nice to be able to completely disable tree functionality and have a simple flat tab list (max tree depth 0).

I realize it conflicts with originally intended addon purpose, but nonetheless I think this feature demand is non-zero, since similar popular addons I've previously seen had it.

**Comment by piroor** [comment]
After 49c953994843c458334b91a67c4fb1d904bbc4e1 (it will be included to the next release newer than 2.2.9) you can do it with secret configurations. Go to TST's configuration and turn on the Debug mode, then all internal configurations are listed. Then you should uncheck two checkboxes `autoAttach` and `syncParentTabAndOpenerTab`.

**Comment by piroor** [comment]
However, basically "Tree Style Tab" is designed to operate tabs as "Tree", such use case is quite irregular. Please note that these configs can be broken in future versions and there is no guarantee. I still recommend you to switch to any other vertical tab bar addon like Tab Center Redux.

**Comment by ikari-pl** [comment]
@piroor This is not irregular. For me, using it as a vertical tab list (because I have 200+ tabs open) is the primary purpose (alternative: switch browser to Vivaldi), and the fact of having them as a tree is just a nice to have. 

(kinda bug) Especially that once in a while 100+ tabs suddnely become children of a tab that never opened them (and when I close the parent, they don't get promoted to level 1, they become children of another tab). I came here looking for a single-shot option to flatten the list.

**Comment by piroor** [comment]
@ikari-pl Sadly TST's tree structure is sometimes broken. Disabling cache for optimization lets you to  clear such a broken information and TST will reconstruct tree of tabs, so please try that when you get such a problem on the next time.

**Comment by piroor** [comment]
I close this because outdated.

**Comment by miguno** [comment]
https://github.com/piroor/treestyletab/issues/1544#issuecomment-345129601

Still seems to work today to "flatten" the tab tree.

Instructions for Firefox 68: Go to Tools > Add-Ons > Find "Tree Style Tab" and click on the three dots "..." next to its entry to select "Preferences" > Scroll all the way down to an expandable menu named "All Configs" > Click on the small black triangle to expand the menu if it isn't already > Uncheck the checkboxes `autoAttach` and `syncParentTabAndOpenerTab`.

**Comment by keeganwitt** [comment]
Thanks for the workaround. This was one of the main reasons I was using Tab Center Redux / Tab Center Reborn (well that and the the window preview thing was kinda nice).

**Comment by gitvalds** [comment]
@miguno 
Wonderful :)
Thanks a lot.
Now that you told me about that (hidden) menu, I could set the variable "maxtreelevel" to 0 and have trees of a single level.

**Comment by Movisivi** [comment]
> [#1544 (comment)](https://github.com/piroor/treestyletab/issues/1544#issuecomment-345129601) still seems to work today to "flatten" the tab tree.
> 
> Instructions for Firefox 68: Go to Tools > Add-Ons > Find "Tree Style Tab" and click on the three dots "..." next to its entry to select "Preferences" > Scroll all the way down to an expandable menu named "All Configs" > Click on the small black triangle to expand the menu if it isn't already > Uncheck the checkboxes `autoAttach` and `syncParentTabAndOpenerTab`.

Still works over 2 years later. Good shit.

**Comment by opqriu** [comment]
> > [#1544 (comment)](https://github.com/piroor/treestyletab/issues/1544#issuecomment-345129601) still seems to work today to "flatten" the tab tree.
> > Instructions for Firefox 68: Go to Tools > Add-Ons > Find "Tree Style Tab" and click on the three dots "..." next to its entry to select "Preferences" > Scroll all the way down to an expandable menu named "All Configs" > Click on the small black triangle to expand the menu if it isn't already > Uncheck the checkboxes `autoAttach` and `syncParentTabAndOpenerTab`.
> 
> Still works over 2 years later. Good shit.

I tried it today (now), and it works very well. 
That's great. It was exactly what I needed, and Google did a great job of finding this page for me.

**Comment by JukkaSartinen** [comment]
> > > [#1544 (comment)](https://github.com/piroor/treestyletab/issues/1544#issuecomment-345129601) still seems to work today to "flatten" the tab tree.
> > > Instructions for Firefox 68: Go to Tools > Add-Ons > Find "Tree Style Tab" and click on the three dots "..." next to its entry to select "Preferences" > Scroll all the way down to an expandable menu named "All Configs" > Click on the small black triangle to expand the menu if it isn't already > Uncheck the checkboxes `autoAttach` and `syncParentTabAndOpenerTab`.
> > 
> > 
> > Still works over 2 years later. Good shit.
> 
> I tried it today (now), and it works very well. That's great. It was exactly what I needed, and Google did a great job of finding this page for me.

Can confirm, this works in current version 3.9.19 with Firefox 116.0.2. I realize the tree structure is what this extension does. But it would be nice, if there was a way to disable the tree structure with one option. But then again, I understand it's not what this extension was made for, and I respect that. Glad it was possible to tweak to my needs.
