### ISSUE TITLE
[feature request] Clicking on active tab switches to previously selected tab

### ISSUE THREAD

**Issue by allixx** [piroor/treestyletab#1545]
## Short description

It's quite useful to be able to switch to previously selected tab by clicking on currently opened tab.

Sometimes you need to quickly check something in another tab. You switch to that tab, and by clicking it again you get back to the tab you were before, without scanning through your multiple opened tabs or falling back to ctrl+tab shortcut.

**Comment by piroor** [comment]
Because this is not related to tree, I won't implement it as a built-in feature. Instead there is an API to help implementing such an addon working with TST.
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#when-a-tab-is-clicked

**Comment by ariasuni** [comment]
I wrote that today: [Tab flip for Tree Style Tab](https://addons.mozilla.org/en-US/android/addon/tab-flip-for-tree-style-tab/).

**Comment by piroor** [comment]
Thanks! I've updated the list of related addons: https://github.com/piroor/treestyletab/blob/master/README.md#addons-extend-tst

**Comment by piroor** [comment]
I close this because outdated.
