### ISSUE TITLE
Wrong tab is being selected

### ISSUE THREAD

**Issue by gnite** [piroor/treestyletab#1547]
## Short description

When a parent has **exactly** 2 children and there is another tab below, the wrong tab gets selected after closing the second child.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Create following tree structure:

A
\- B
\- C (selected)
D

 4. Close tab C

## Expected result

Tab B is selected.

## Actual result

Tab D is selected. I also made a quick screencast to demonstrate: https://streamable.com/cgolm

## Environment

 * Platform (OS): Win10 
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.2.9

**Comment by piroor** [comment]
Thanks, 37db856 should fix this.
