### ISSUE TITLE
TST Sidebar still showing when going full screen via F11 with FF57

### ISSUE THREAD

**Issue by wumpyr** [piroor/treestyletab#1548]
## Short description

The TST sidebar still shows on screen when entering full screen mode (F11) on Firefox 57.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Go full screen (F11).
 4.  Sidebar still showing.

## Expected result

TST sidebar should autohide.

## Actual result

TST sidebar stays visible.

## Environment

 * Platform (OS): Windows 10.
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.2.9

**Comment by piroor** [comment]
It is impossible by TST 2 because there is no WebExtensions API to do that. Basically WE disallows addon to show/hide its sidebar without user's action on its custom keyboard shortcut (F1 for TST) or clicking on the toolbar button.

**Comment by wdnz** [comment]
Would it be possible to have a configurable option to toggle fullscreen with the same button as TST visibility (F1)? Only one user interaction would be needed then.

**Comment by wdnz** [comment]
I found a userChrome.css workaround:

#main-window[inFullscreen] #sidebar-box {
   display:none !important;
   width: 0px !important;
}

**Comment by ivan** [comment]
I added wdnz's workaround to [the wiki](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#auto-hide-sidebar-when-fullscreen-1548) with an additional hiding of `#sidebar-splitter`.

**Comment by piroor** [comment]
I close this because this is out of the range of WebExtensions-based extension.
