### ISSUE TITLE
The sidebar stays on the left side even when the setting "Right side" is selected

### ISSUE THREAD

**Issue by ecanja** [piroor/treestyletab#1553]
## Short description

The settings "Appearance > Style of contents for the sidebar position > Right side" does not seem to work as expected, because the sidebar won't change to the right side of the window.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Go to the add-on settings and choose "Right side" under "Appearance > Style of contents for the sidebar position"

## Expected result

The sidebar with the tree-styled tabs should switch to the right.

## Actual result

The sidebar does not switch to the right. The only thing that changes is the alignment of the child tabs (from right-aligned to left-aligned).

## Environment

 * Platform (OS): Ubuntu Linux
 * Version of Firefox: 57.0
 * Version (or revision) of Tree Style Tab: 2.2.9

**Comment by piroor** [comment]
Because there is no API to change Sidebar's position from an addon, TST's configuration just changes appearance inside the sidebar. You need to click the switcher in the sidebar's header and choose "Move Sidebar to Right" manually.

**Comment by piroor** [comment]
Anyway I got same question from another user so I think I need to add something description to the config item.

**Comment by ecanja** [comment]
Ah cool! Yeah, maybe I should have explored the new add-on a bit more and have a look at the sidebar's header switcher. Would not be too much to ask, so sorry for the easy question...
And thanks for your really fast answer!

**Comment by piroor** [comment]
I close this because this is out of the range of WebExtensions-based extension.

**Comment by lukehud** [comment]
Any chance someone could post a screenshot of the "switcher in the sidebar's header"? I don't seem to have a header over my sidebar.

**Comment by irvinm** [comment]
![image](https://github.com/user-attachments/assets/3aed6531-d270-41a7-b09a-3973616c7b13)

**Comment by lukehud** [comment]
Crap, I can't figure out why mine doesn't have that...
![image](https://github.com/user-attachments/assets/55c6c7a6-9042-47a2-9e98-08ca5b941cee)

**Comment by lukehud** [comment]
Figured it out! I had added a css file in the past to hide the native tabs, past me must have not liked the TST header either because I hid the sidebar header. Thanks for that screenshot @irvinm !

**Comment by SHHSSH** [comment]
> Figured it out! I had added a css file in the past to hide the native tabs, past me must have not liked the TST header either because I hid the sidebar header. Thanks for that screenshot @irvinm !

It's crazy the amount of people support ticketing TST regarding the new Firefox UI changes, I was actively trying to find solutions to my malfunctional visual aesthetics too and ran into your issue somewhat -with the sidebar's title reappearing and me not wanting it/after dabbling in what Firefox was attempting to offer with their new sidebar gimmick. 
Although once I figure out how to customise it appropriately like I have enough for the current context menus and sidebars already I will potentially use it. I found the thing forced certain addons into there without customisation etc. which I found cumbersome along with many other things.

@lukehud Would you care to share your css if you don't mind? Here's mine below and a link to another fella's I found pretty good and pinched a bit of too.

I don't even know what some of it does, I just leave it in there until it breaks something else.

```
:root { zoom: 77%; }

#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] { 
  -moz-box-ordinal-group: 2 !important; 
}

/* Hide border on tab bar, force its state to 'scroll', adjust margin-left for width of scrollbar. */
#tabbar {
  border: 0;
  scrollbar-width: none;
  overflow: scroll !important;
  margin-top:  0 !important;
  direction: ltr;
}

/* Increase the favicon size by 33% */
:root.sidebar tab-item .favicon {
  transform: scale(1.11);
}


/* resolve extra space for scrollbar (scrollbar is hidden by this script) */
.on-scrollbar-area #tabbar {
  --shift-tabs-for-scrollbar-distance: 0px;
}

/* Include 'reveal' animation ... stagers by level */
#tabbar .tab {
  transition: 0.1s margin-top, 0.2s 0.1s visibility;
}
#tabbar tab-item-substance {
  transition: 0.2s 0.1s margin-left;
}


/* delay transitions on open */
#tabbar:not(:hover) tab-item-substance {
  transition-delay: var(--tst-sidepanel-hide-delay);
  margin-left: 0;
}



/* Style for unread tabs */
:root.sidebar tab-item.unread .label-content {
  color: #1092C9 !important;
  font-weight: bold !important;
  font-family: 'Aladin	', sans-serif;
  font-variant: titling-caps;
  font-size: 1.1em;
  text-shadow: 1px 1px 1px rgba(0,0,0,0);
}

/* Style for read tabs */
:root.sidebar tab-item:not(.unread) .label-content {
  color: #1092C9 !important;
  font-family: 'Aladin	', sans-serif;
  font-variant: titling-caps;
  font-size: 1.1em;
  font-weight: bold !important;
  opacity: 0.88;
}

/* Apply animated border to the active tab */
:root.sidebar tab-item.active tab-item-substance {
  height: 39px !important;
  border: 1.77px dashed #46C388 !important;
}

/* Styles for the active tab's background and label content */
:root.sidebar tab-item.active .background {
  background-color: rgba(0, 0, 0, 0) !important;
}

tab-item.active .label-content {
  font-weight: bold;
  font-size: 14px;
  color: #FFFFFF;
}

/* Animated border and style for hovered tabs */
tab-item tab-item-substance:hover {
  background: rgba(0, 0, 0, 0) !important;
  color: #FF0909 !important;
  font-family: 'Aladin	', sans-serif;
  font-variant: small-caps;
  text-shadow: 1px 1px 1px black;
  font-weight: bold !important;
  font-size: 1.33em;
  opacity: 1;
  border: 1px dashed #48ae90 !important;
}

/* Add private browsing indicator per tab */
:root.sidebar tab-item.private-browsing tab-label:before {
  content: "🕶";
}

/* Move close button to the right side of the tab */
:root.sidebar tab-item .closebox {
  order: 1;
  margin-left: auto;
  margin-right: 5px;
}

:root.sidebar tab-item .label {
  order: 2;
}

:root.sidebar tab-item {
  display: flex;
  flex-direction: row;
  align-items: center;
}`
```
and the other users' - https://github.com/piroor/treestyletab/discussions/3658
