### ISSUE TITLE
The tabs at the top of the browser window don't disappear when TST is activated

### ISSUE THREAD

**Issue by ecanja** [piroor/treestyletab#1554]
## Short description

When I activate the add-on TST, I do get the tree style sidebar (on the left), but the usual Firefox tab UI with the tabs at the top of the browser window does not disappear.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.

## Expected result

I only see the TST sidebar and no tabs at the top of the browser window anymore.

## Actual result

The usual Firefox tabs at the top of the browser window are still there.

## Environment

 * Platform (OS): Ubuntu Linux
 * Version of Firefox: 57.0
 * Version (or revision) of Tree Style Tab: 2.2.9

**Comment by gotyaoi** [comment]
https://github.com/piroor/treestyletab/issues/1511

**Comment by ecanja** [comment]
I had a look at the existing issues, but haven't found this. Thanks for pointing me to it and sorry for the duplicate!

**Comment by piroor** [comment]
I close this as a dup.
