### ISSUE TITLE
Move to New Window causes all tabs to reload

### ISSUE THREAD

**Issue by jtackaberry** [piroor/treestyletab#1555]
## Short description

When choosing Move to New Window from the tab context menu, all tabs in the window as well as the one moved to a new window are reloaded.  This doesn't happen when a tab is dragged from one window to another.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a bunch of tabs
 4. Right click a tab and select Move to New Window.
 5. Observe that all tabs get reloaded.

## Environment

 * Platform (OS): Windows 10 x64
 * Version of Firefox: 57 and 58b4
 * Version (or revision) of Tree Style Tab: 2.2.9

**Comment by piroor** [comment]
Thanks! d02d695 fixes this.
