### ISSUE TITLE
Pinning child tab results in the icon having left margin.

### ISSUE THREAD

**Issue by DeaD3R** [piroor/treestyletab#1557]
![image](https://user-images.githubusercontent.com/16120515/32949064-de466204-cbba-11e7-90da-df1379439e04.png)

Then unpinning this tab causes the same, tab has no parent but is offset from the left.
![image](https://user-images.githubusercontent.com/16120515/32949337-ebba6506-cbbb-11e7-925c-0bd7e3e5b44a.png)

Steps to reproduce: Open a page, open a link from that page as a child, pin child tab.

If you pin non-child tab after this the icons will overlap.

![image](https://user-images.githubusercontent.com/16120515/32949260-ac6f7616-cbbb-11e7-95ce-4fc6a53e2840.png)

First two imdb pages wrere children, third was not.

**Comment by piroor** [comment]
Recently I've fixed this problem. Which version do you use? Please fill the issue template.

**Comment by DeaD3R** [comment]
Ah sorry about that. I'm using 2.2.2, I didn't update cause of the new permision request.
