### ISSUE TITLE
[feature request] put TST context menu items into toplevel

### ISSUE THREAD

**Issue by elonderin** [piroor/treestyletab#1560]
## Description
TST's menu  items are now in a sub menu which requires an extra click to get to. Please move them up into the main menu how it was before FF 57.

You could also provide an option for this.

## Environment
 * Platform Win7
 * Version of Firefox 57 x64: 
 * Version (or revision) of Tree Style Tab: 2.2.9

**Comment by piroor** [comment]
It is impossible to place multiple top-level context menu items via WebExtensions APIs. See also: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/menus

**Comment by piroor** [comment]
I close this because outdated. Now this is possible.
