### ISSUE TITLE
[feature request] access keys for TST's context menu

### ISSUE THREAD

**Issue by elonderin** [piroor/treestyletab#1561]
## Description
the TST's menu  items dont have the access keys anymore. Please bring them back.

this goes with #1560 to increase productivity.

Before i just could right click and hit "s" or "e" (cant remember ) to close a single tab or tree.
This was awesome and was the main point of choosing TST over some other variant i had tried out.

## Environment
 * Platform Win7
 * Version of Firefox 57 x64: 
 * Version (or revision) of Tree Style Tab: 2.2.9

**Comment by piroor** [comment]
Currently it is impossible due to missing WebExtensions support. See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1320462

**Comment by elonderin** [comment]
hm, not being worked on....
is it possible to define a key shortcut for this? 
e.g. F4 closes the current tree ?

**Comment by elonderin** [comment]
hm, i just noticed that the context menu on the sidebar isnt the same as the standard context menu on the original FF tabs

1. it looks a little different
2. upon right click u cant use the arrow keys to navigate, u have to use the mouse, which hampers the use of AHK ....

**Comment by piroor** [comment]
As described at the [migration story of TST](http://piro.sakura.ne.jp/latest/blosxom/mozilla/extension/treestyletab/2017-10-03_migration-we-en.htm#topic2017-10-03_migration-we-en), current context menu in the sidebar is just a workaround, until any genuine WebExtensions feature to do that is landed. I don't want to pay time anymore to maintain it...

**Comment by piroor** [comment]
By recent commits accesskey and keyboard navigation for the fake context menu are now available.

**Comment by piroor** [comment]
This is already done.
