### ISSUE TITLE
[feature request] support drag and dropping url or search terms in plaintext onto the sidebar.

### ISSUE THREAD

**Issue by DeaD3R** [piroor/treestyletab#1563]
right now if you select this: 
`google.com `
or 
`www.google.com`
 and drag and drop it in the sidebar it opens 
> moz-extension://e1a16b2e-7a47-4b27-a524-51fa0d873c8b/background/google.com

only
`https://www.google.com`
opens correctly.

I think any text dropped in should be treated as url if it has contains "." and any other should go to search.

**Comment by DeaD3R** [comment]
Works great for urls, would be good if text without period went to default search engine.

**Comment by piroor** [comment]
There is another issue about that: #1527
