### ISSUE TITLE
[Suggestion] Include info on hiding vanilla tab bar in the new startup.html

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1565]
## Short description
Include info on hiding vanilla tab bar in the new startup.html (moz-extension://<extension id>/resources/startup.html).

It's one of the most commonly asked questions and filed "bug" about TST, so it would be wise to include to instructions informing users that it can't be done automatically due to insufficient Firefox WebExtension API capabilities, and what the [workaround](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-horizontal-tabs-at-the-top-of-the-window-1349) is.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. TST startup.html tab appears.

## Expected result
TST startup.html should include info on why the the vanilla tab bar is no longer hidden in TST 2.x and what the [workaround](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-horizontal-tabs-at-the-top-of-the-window-1349) is.

## Actual result
TST startup.html does not include such info.

## Environment

 * Platform (OS): Windows 10 Pro (64-bit), Version 1709, Build 16299.64
 * Version of Firefox: Developer Edition 58.0b4 x64
 * Version (or revision) of Tree Style Tab: 2.2.9.5777

**Comment by piroor** [comment]
I agree... I've added it by 939bcfe8eef6aca5cd740baac087bf6c8a9af8f4.

**Comment by lbmaian** [comment]
Thanks.

I tested it out, and I have to admit that it took me a while to find the new message on the startup page.

I'd suggest not doing the fancy hide-until-hovered-over thing, and just display it always.

Also, some spelling/grammar fixes:
"requireing" => "requiring"
"requires accessing" => "requires access"

**Comment by lbmaian** [comment]
Alright, that's fair.
