### ISSUE TITLE
middleclick to close tab causes parent tab to load a new URL

### ISSUE THREAD

**Issue by earthnative** [piroor/treestyletab#1568]
## Short description
I have 'middlemouse.contentLoadURL' enabled. When a URL is in the paste buffer, closing an unwatched tab by middle-clicking it in TST, causes the current tab to simultaneously load the URL from buffer. 

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Load URL A in Tab X
 4. Select URL (B) from a non-clickable location so it is in the linux paste buffer
 5. Middle-click a link from (X) causing a child URL (C) to load in tab Y
 6. Whilst on any other tab, middle-click tab Y in the TST sidebar to close tab Y

Behaviour does not occur in FF native tab bar
Behaviour does not occur if closing the current tab. 
Behaviour has been replicated both with all other extentions disables, and also in a clean profile. 

## Expected result
Tab Y closes, current watching tab remains unchanged. 

## Actual result
Tab Y closes, and simultanously current tab loads URL B. 

## Environment

 * Platform (OS): Linux Mint 17 Quina
 * Version of Firefox: 57.0
 * Version (or revision) of Tree Style Tab: observed in 2.2.9 and 2.2.10

**Comment by piroor** [comment]
Due to https://bugzilla.mozilla.org/show_bug.cgi?id=1341059 TST cannot cancel the behavior via regular way...

**Comment by piroor** [comment]
just for a memo: the feature is implemented here.

https://dxr.mozilla.org/mozilla-central/rev/a3f183201f7f183c263d554bfb15fbf0b0ed2ea4/browser/base/content/browser.js#5912
https://dxr.mozilla.org/mozilla-central/rev/a3f183201f7f183c263d554bfb15fbf0b0ed2ea4/browser/modules/ContentClick.jsm#39

**Comment by piroor** [comment]
I close this because it is not a problem of addon side.
