### ISSUE TITLE
[No STR][2.2.10] TST completely broken after restoring saved session

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1569]
Win 8.1, Nightly 17-11-17.
I upgraded to TST2.2.10 and tried to restore my saved session that I have been using for around a month. I installed TST around two weeks ago. After restoring session the problem is the following:
Sidebar completely blank even though I have lots of tabs open
Toolbar button doesn't work
F1 doesn't work
When I open new tab using Ctrl-T and try to go to google.com, the page doesn't load
All other tabs also don't load when I click on them using Firefox tab bar, just blank screen instead of the web page

TST seems to work fine if I don't restore session. Unfortunately, no STR because I don't have time right now (I'll try to find STR tomorrow) but there are TST-related errors in the browser console:
![image](https://user-images.githubusercontent.com/26294581/32978112-6ffbf6c8-cc4c-11e7-9061-b13c504f8987.png)
Empty TST sidebar after restoring session:
![sidebar](https://user-images.githubusercontent.com/26294581/32978102-3cb757c6-cc4c-11e7-9233-d2fcbbb7c443.png)

**Comment by piroor** [comment]
How did you "restore" the session?

**Comment by SXZ1** [comment]
I was using Hamburger menu - Restore saved session

**Comment by SXZ1** [comment]
STR:
Create new profile, install TST2.2.10, copy sessionstore.jsonlz4 from the archive to the root of the profile overwriting existing file
[sessionstore.zip](https://github.com/piroor/treestyletab/files/1484452/sessionstore.zip)

Launch Nightly, Hamburger menu - Restore session

AR: TST sidebar is blank, F1 doesn't work, TST toolbar button doesn't work.
![sidebar](https://user-images.githubusercontent.com/26294581/32978583-08a7eb26-cc56-11e7-8843-c72d20ae86e2.png)

**Comment by SXZ1** [comment]
I am not 100% sure but it looks like this bug is fixed in latest dev. I'll test everything in 12 hours, I got to go now.

**Comment by piroor** [comment]
Changes for #1569 may affect to this.

**Comment by SXZ1** [comment]
Bug is fixed in TST2.2.11 but there is another problem in TST2.2.11: it takes much longer time until all tabs and tree structures are restored in TST sidebar after using Hamburger Menu - Restore previous session compared to TST2.2.9.

But that's a separate problem, I'll file a new bug for that if I find STR. Thank you very much!
