### ISSUE TITLE
[2.2.10] Performance regression opening tabs with a large number of tabs in a window

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1570]
## Short description
There is a performance regression in 2.2.10 that didn't exist in 2.2.9, where having a large number of tabs in a window slows down the opening tabs (whether new tab, middle-clicking, duplicating, etc.) in any tree structure (even all flat). The more tabs you have in that window, the slower opening tabs gets.

This is especially noticeable for me at about 200 open tabs (and vast majority of them still in a discarded/unloaded state), where opening a new tab can take around a second. I think it gets exponentially worse (or at least, more than linearly worse) the more tabs you have in the window.

If I open a new window, tabs do open quickly in that window, until it fills up with a lot of tabs as well.

Again, this performance problem does NOT exist in TST 2.2.9.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a lot of tabs in any tree structure - 200 open tabs, even when most are discarded/unloaded was sufficient for me to reproduce.

## Expected result
Opening new tabs should be practically instantaneous.

## Actual result
Opening new tabs starts taking longer and longer the more tabs there are in the window. At around 200 tabs in a window, opening a new tab takes about a second for me.

## Environment

 * Platform (OS): Windows 10 Pro (64-bit), Version 1709, Build 16299.64
 * Version of Firefox: Developer Edition 58.0b4 x64 and Nightly 59.0a1 (2017-11-17) x64
 * Version (or revision) of Tree Style Tab: 2.2.10

**Comment by piroor** [comment]
I think https://github.com/piroor/treestyletab/blob/9439123fa86cfc45411bc92f9bf0666ea66a83d2/webextensions/common/tree/handlers.js#L211-L213 causes this. It is introduced to fix #1549 - the problem was caused by removed original tab desappearing before the reopened tab is completely tracked by TST. So I had to cache tree structure of tab when the tab is actually opened. Hmm...

**Comment by piroor** [comment]
After 1117320, the number of scanned tabs is reduced. Does this change affects this problem?

**Comment by lbmaian** [comment]
Assuming latest nightly version 2.2.10.5786 includes that commit: unfortunately, it doesn't seem to help. My current session still takes about a second to open a new tab with ~200 tabs, and when I created a new window and started populating it with new tabs, it also still started getting progressively worse (I stopped at around ~150 tabs).

**Comment by piroor** [comment]
Could you get profile by debugger? Go to about:debugging and click "Debug" under Tree Style Tab's item, then you'll see the developer tool:
https://developer.mozilla.org/en-US/docs/Tools/Performance

**Comment by lbmaian** [comment]
Good news! Downloaded the latest nightly version 2.2.10.5790, and opening new tabs no longer is slow, so it looks like its fixed.
