### ISSUE TITLE
Child tabs are placed in incorrect location

### ISSUE THREAD

**Issue by kparal** [piroor/treestyletab#1575]
## Short description
Child tabs appear in a completely different tree or location, but they are still handled by the correct tree (when collapsing etc). See these videos:
https://youtu.be/zwOW44_gMz0
https://youtu.be/4xIPNt44fVg

Closing a reopening the side bar (F1) doesn't resolve the issue. Restarting the browser sometimes affect the issue (the child tab is either placed correctly, or it's placed as a top level tab, or even all tabs get mixed up - probably a different issue) but sometimes not (the same behavior even after restart).

Started happening today or yesterday I believe.

## Steps to reproduce

I don't know. It seems it happens when drag&dropping tabs. I have Multiple Tab Handler installed, but I believe it happened even before it was installed, and when I'm dragging just a single tab. Doesn't happen always, but seems frequently enough.

## Environment

 * Platform (OS): Fedora 26
 * Version of Firefox: 57.0
 * Version (or revision) of Tree Style Tab: 2.2.11

**Comment by piroor** [comment]
I need exact steps to reproduce the problem...

**Comment by piroor** [comment]
If you see this problem again, could you capture tree information on your running Firefox?
https://github.com/piroor/treestyletab/issues/1717#issuecomment-358514010
Such information may help me to research what's happen.

**Comment by kparal** [comment]
Sorry, I'm not using TST at the moment. Probably close this.
