### ISSUE TITLE
Restart Browser to Last set of Pages

### ISSUE THREAD

**Issue by jerryyyyy** [piroor/treestyletab#1576]
## Short description

Restarting does not reload the prior set of tabs.  Have to start all over.  Do not find any option to allow this as in prior version. 

## Steps to reproduce

 1. Start Firefox with clean profile.... that will be the day and lose all my other settings and find out this does not work.
 2. Install TST.
 3. 
 4. 

## Environment

Windows 10

**Comment by gogoengie** [comment]
Tree Style Tab does not perform session management. Sessions are restored by the browser, or a session manager extension. If you want to restore tabs when you restart Firefox, open Firefox Preferences, choose the "General" tab, and under "When Firefox starts" select "Show your windows and tabs from last time"

![restore](https://user-images.githubusercontent.com/4132109/32984168-11a3d712-cc56-11e7-8272-5ed0b9eb854d.jpg)

**Comment by piroor** [comment]
I labeled this issue as invalid because it seems a topic about Firefox's built-in feature.

**Comment by jerryyyyy** [comment]
You guys are right.  I found the controls.  May I just speak as someone who is 68 years old and with now 40 (42)  years programming experience, it is a royal PITA to fix such silly roadblocks that show up every day in my workflow.  

Last week W10 decided that I could no longer mount folders in a Linux VM... duh.... try to fix that.  Do some basic reading in Hypervisor to START...

Time for retirement, but all you young folk will carry on quite well.  What could go wrong?  :)

PS  My complements on the Tabs... referred by Steve Gibson.

**Comment by piroor** [comment]
I close this because outdated.
