### ISSUE TITLE
The child tab not use the same context tab of his first parent

### ISSUE THREAD

**Issue by kadogo** [piroor/treestyletab#1579]
## Short description

Hello.
I was using context tab for my browsing and I wanting using 1 window for each context.
So I wanted create new child that directly using the tab context from his first parent.

I'm not sure it's an issue or not, but in case I prefer to ask.
Cheers.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST (dev version as temporary add on)
 3.  Open a tab with a context like personal
 4.  Go to preference for TST and change "open new tab as a child of the current tab"
 5.  Go on your personal tab and create a new tab
 6.  The new tab don't use the personal context

## Expected result

Create a new child that use the same context tab from his first parent

## Actual result

The new child don't use any context tab

## Environment

 * Platform (OS):  Debian Stretch
 * Version of Firefox:  57
 * Version (or revision) of Tree Style Tab: Dev version

**Comment by piroor** [comment]
Currently it is by design. New tab in non-default context won't be opened automatically. Instead you only can open new tab in specific context from the context chooser (see also #1571) on the new tab button.

**Comment by piroor** [comment]
Anyway I think your idea seems reasonable. I still think that current behavior of TST is natural for me, but the behavior you expected is also natural in different view point. So it should be an optional behavior. To introduce it, we need to do more changes:

 * Add new configuration checkbox like: "Inherit context (aka container, contextual identity) of the current tab, if a new tab is opened as a child of it."
 * Add a code to open new tab with the context of the current tab, based on the configuration.

Note: we need to give up for to do this behavior for new tabs opened by "new tab" command from outside of TST sidebar (the new tab button in the top tab bar, Ctrl-T shortcut, by other addons, etc.) because we cannot trap new tab's parameter before it is opened. WebExtensions API just allows us to receive events for already opened tabs, not before opened tabs. Because the new tab button in the sidebar is implemented by TST itself, we can do more things for new tabs opened from there.

**Comment by Lej77** [comment]
> we need to give up this behavior for new tabs opened by "new tab" command from outside of TST sidebar (the new tab button in the top tab bar, Ctrl-T shortcut, by other addons, etc.) because we cannot trap new tab's parameter before it is opened. 

Those new tabs could be closed and reopened with the correct context. It might be an option depending on performance and how often it would end up being used.

**Comment by Lej77** [comment]
@kadogo If you want new tabs to have the same context as the current tab then you might want to try the [Conex](https://addons.mozilla.org/sv-SE/firefox/addon/conex/) extension.

**Comment by kadogo** [comment]
@Lej77 
Thanks, I will try it.
It look like it do what I want for now. Having the possibility to make a default container fastly must be nice too but maybe I not find it yet. I will keep looking.

**Comment by Lej77** [comment]
@kadogo If you want to quickly access the default container with the [Conex](https://addons.mozilla.org/en-US/firefox/addon/conex/) extension enabled then you just need to open any bookmark not leading to the new tab page as a new tab. This can be done by middle clicking on a bookmark. To have bookmarks always visible and therefore easily accessible right click on the Firefox window toolbar and check the box for bookmark toolbar.

As an alternative solution you can use the [Containerise](https://addons.mozilla.org/sv-SE/firefox/addon/containerise/) extension and configure it to open a specific address in the default container.

For example:
 1. Create a bookmark for the address "http://localhost/" with a simple keyword such as "d".
 2. Press "Containerise"'s toolbar button.
 3. Press the arrow pointing to the left.
 4. Add the following text to the text box: `localhost , No Container` 
 5. Press save.

To use;
 1. Create new tab. (Press new tab button or use keyboard command ctrl+t)
 2. Address bar should get auto selected.
 3. Write the bookmarks keyword. In our case "d".
 4. Press enter.
 4. This should open the bookmarks address and trigger the "Containerise" extension to change the tabs container to the default container.

Note: The address doesn't need to be "http://localhost/" but if you use a website such as "google.com" then be aware that any tab that navigates to that website will be changed to the default container.

**Comment by kadogo** [comment]
@Lej77 
Thanks I will use it as workaround the time that TST implement this feature.
What could be nice is that we can create a tab with default context from the context menu too.

**Comment by Lej77** [comment]
@kadogo [New container tab by jkt](https://addons.mozilla.org/firefox/addon/new-container-tab/) is another extension that might be useful for creating a new tab with the same context as the current tab. It opens a new tab beside the current tab when the keyboard shortcut `alt+c` is pressed.

**Comment by piroor** [comment]
This behavior is implemented by recent commits. And, if the behavior is activated, an extra choice "Default" appears in the the container selector.

**Comment by kadogo** [comment]
@piroor 
Thanks, It's already rebuild for the FireFox extension or I need to install it in debugging mode ?

I was thinking too, but not sure it's related to TST.
It could be possible to choice in which container we open a new link ?
Example when I open a link from my IRC client it's always in default container.

I think it's more FireFox related than TST, but I prefer to ask just in case.

**Comment by piroor** [comment]
@kadogo This change has been included to 2.3.0.

>  It could be possible to choice in which container we open a new link ?

It is impossible for now due to two sides.

 * New tab just inherits the container from its parent and links from external application are always opened as independent tab on current TST.
 * WebExtensions addon cannot know where the requested URI is from. So we cannot do any decision like "this request is from external application, then open it in the private container." To do that we need to create a native messaging host (special local application module) to relay requests from other applications and need to register it as a default application for webpages.

**Comment by kadogo** [comment]
@piroor 

I was more thinking about a default option like I click on a link and I'm asked in which container I want open it.

**Comment by piroor** [comment]
I think it should be done by something addon designed to operate containers. In TST, container support is just limited and optional. Global controlling feature for container of newly opened tabs seems out of its purpose.

**Comment by kadogo** [comment]
@piroor 
Oki, yes I was not sure if it was really related.
If you see another addon that has this feature, don't hesitate to tell me ^^

I just upgrade to TST to 2.3 so I will testing the new features in the evening.

Thanks.

**Comment by kadogo** [comment]
@piroor 
I tested and i look working.
Just to be sure, it's normal that it work only with child tab and not with independant tab ?

**Comment by piroor** [comment]
>  Just to be sure, it's normal that it work only with child tab and not with independant tab ?

Yes, it is by design for now. If a new tab always inherits the container of the (old) current tab, it seems out of topic TST should control. TST just applies container from the parent to new child tabs.

**Comment by kadogo** [comment]
@piroor 

I forgot something really big.
It's that we always need to go back to the first parent tab if we want avoid having too much child tabs.
Maybe an option like "make a child tab under the main parent" will be a workaround.
Don't hesitate to close this bug if you think I try to go too far.

**Comment by piroor** [comment]
@kadogo Hmm, I think that Vivaldi or Tab Groups Manager seem to fit your needs...

**Comment by kadogo** [comment]
@piroor 
Thanks. Do you have a link for tab groups manager because I find only the oldest that's not compatible with FF57. For Vivaldifox it looks like a visual help that can help me for later (thanks).

**Comment by piroor** [comment]
@kadogo I misunderstood about Tab Groups Manager, sorry. It switches visible set of tabs so it is does not work as "tabs with grouping". sidebarTabs addon https://github.com/asamuzaK/sidebarTabs seems an alternative vertical tab bar addon which including one-level grouping feature.
