### ISSUE TITLE
scrollbar right side adds x-axis scrollbar

### ISSUE THREAD

**Issue by Djfe** [piroor/treestyletab#1581]
currently https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#show-scrollbar-in-the-tab-bar-rightside-1362 gives me a horizontal scrollbar as well.

My workaround for now is adding "overflow-x: hidden;"

Maybe a restart would have fixed it, I'm not sure.

**Comment by piroor** [comment]
Thanks! I've updated the wiki. And I've also added codes to control visibility of the scrollbar via a config UI so the code snippet will be out of date after the next release.
