### ISSUE TITLE
Bookmark All Tabs is broken

### ISSUE THREAD

**Issue by bricewge** [piroor/treestyletab#1582]
On Tree Style Tab 2.2.11 with Firefox 57 "Bookmarks All Tabs" seems broken, even after modifying the parameters to give TST the permissions; note that  "Bookmarks this Tree" work however. Here is the error message:
![error](https://user-images.githubusercontent.com/5525646/32993692-0dca7950-cd5c-11e7-9943-faccf7e66a58.png)

Downgrading to 2.2.9 work around the issue, bookmarking works flawlessly.

**Comment by MaximumBeans** [comment]
Same here. Check-box in Preferences produces a desktop notification about a Firefox bug preventing it from working, and then badges the toolbar button. Clicking the toolbar button gets you the Firefox prompt to enable the feature, which then checks the box in Preferences - but still can't bookmark all tabs.

**Comment by Lej77** [comment]
Have the same problem. Currently using keyboard shortcut `ctrl+shift+d` to bookmark all tabs as a workaround.

**Comment by SicariusNoctis** [comment]
A workaround for for Firefox on Linux: hit `Alt-B` > `Bookmark All Tabs`.

**Comment by WolfgangWeber** [comment]
I can confirm this bug. At the moment it is not possible to bookmark all tabs.

**Comment by piroor** [comment]
Thanks. The feature was broken and recent commits should fix it.

**Comment by bricewge** [comment]
I just tested the fix on Firefox Developer 57.0b13, and it works nicely. Thanks for the quick fix @piroor!
