### ISSUE TITLE
[dev 5803] "Don't expand collapsed tree when using Ctrl(-Shift)-Tab" pref UI doesn't work?

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1583]
Nightly 18-11-17, TST5803 (latest dev).
STR: Create new profile, install TST, note "Don't expand collapsed tree when using Ctrl(-Shift)-Tab" pref is disabled by default
Open new tab, go to github.com, ctrl-click on Features
Open new tab, go to github.com, ctrl-click on Business
Switch to the parent tab of the 1st stack, collapse both stacks and press ctrl-tab.
ER: Focus switches to the child tab in the 1st stack 
AR: Focus switches to the 2nd parent tab
![untitled](https://user-images.githubusercontent.com/26294581/32994872-b095475c-cd7d-11e7-9d0f-1d4762224dc0.png)

**Comment by piroor** [comment]
Sorry, its actual behavior is "Don't expand collapsed tree *and skip collapsed descendants* when using Ctrl-(Shift-)Tab". The label is wrong, it should be fixed in the next release.

**Comment by SXZ1** [comment]
Thank you! It looks like I am missing something because TST behavior still seems wrong to me.
"Don't expand collapsed tree and skip collapsed descendants when using Ctrl-(Shift-)Tab" is not checked by default. Expected behavior with this pref disabled is "Expand collapsed tree and don't skip collapsed descendants when using Ctrl-(Shift-)-Tab".

However, that's not what I am seeing because collapsed trees are not expanded and descendants are skipped even with this pref disabled.

**Comment by piroor** [comment]
Thanks, I maybe found what causes this problem. Currently, this behavior is enabled by default but doesn't work because content script is disabled by missing permission by default. However, same script is also loaded into the sidebar and if you press Ctrl key while the sidebar has focus, then the behavior is applied unexpectedly.

By recent changes, now internally the behavior is disabled and it is enabled only when the permission is granted.

**Comment by SXZ1** [comment]
Thank you very much! Bug is fixed in 5808!

**Comment by rubaboo** [comment]
I am seeing the opposite behavior now. I check "Don't expand collapsed tree..." option, click TST button and Allow permission. But the tree always gets expanded.

**Comment by ildar** [comment]
Please reopen.
It's also doesn't work on Ctrl+PgUp/PgDn.

**Comment by piroor** [comment]
@rubaboo @ildar Could you open new issue with your steps to reproduce? Even if yours is similar to this, it can be caused by different source.
