### ISSUE TITLE
Dark theme colors

### ISSUE THREAD

**Issue by dudelson** [piroor/treestyletab#1586]
I appreciate the fact that TST has a dark theme, but I think the colors could be tweaked a little bit to make it more aesthetically pleasing. For reference, here is what the dark theme currently looks like:

![tree-style-tab-dark](https://user-images.githubusercontent.com/3400780/32996444-ecc115f8-cd50-11e7-8615-e967e0f80955.png)

I added some css to the "Advanced" section of the TST settings and got it to look like this:

![tree-style-tab-dark-after](https://user-images.githubusercontent.com/3400780/32996455-133e89b8-cd51-11e7-8085-37f870c1338a.png)

Note how the background color of the tab bar and the tab color match that of the default firefox dark theme. This also improves the contrast between foreground and background. 

While I think a suggestion like this is more useful in the form of a pull request, I could not figure out where in the codebase these changes would be made, and I understand from #1356 that there are some areas of the browser window that cannot be themed by TST, leading to possibly incongruous themeing. I have added some of the userChrome.css suggestions from the TST wiki to my firefox profile in order to hide some parts of the window that can't be themed (like the sidebar header), so in the default case it's possible that these changes would look terrible and would be better off as a wiki suggestion. 

Additionally, I couldn't figure out how to change the color of the new tab button and of the blank space to the right of the pinned tabs, so hints on how to do those things would be appreciated.

 * Platform (OS):  Arch Linux
 * Version of Firefox: 57.0
 * Version (or revision) of Tree Style Tab: 2.2.11

**Comment by dudelson** [comment]
I consulted the TST wiki again and managed to solve both my issues. I never posted the themeing CSS, so here it is with both issues fixed:

    :root {
      --tabbar-bg: #222426;
      --tab-surface: #474749;
      --tab-text: #efefef;
    }

**Comment by piroor** [comment]
I agree that the current Plain Dark has too much contrast, so I've changed colors at 92876a8 and e4c78cd. Those colors are picked from Firefox's built-in Dark theme. How about that?

**Comment by Lej77** [comment]
@piroor The Tab Container Selector is white in the Dark Theme. I think it looks better black. Here is some CSS code to change that:

```CSS
.contextual-identities-selector {
  filter: invert(100%);
}
```

**Comment by piroor** [comment]
@Lej77 The color of the button depends on the color scheme of the platform, so fixed inversion can cause problem on some environment. Instead I think I should replace the current (quite uncontrollable) button with new custom UI (#1571).

**Comment by dudelson** [comment]
I like the changes! Thanks for fixing this, it makes a world of difference for me. I don't use containers so I'm not encountering the issue with the container selector color, but I'll leave the issue open nonetheless.

**Comment by piroor** [comment]
I close this because outdated. Now TST automatically applies theme color of Firefox itself.

**Comment by darkdragon-001** [comment]
This does not work with the latest version from today (3.0.10). I am using Firefox 66.0.3 on Ubuntu.
I chose The _Dark_ theme in Firefox and configured _Tree Style Tab_ to use _Plain_ theme with _Apply Browser Theme_ enabled. Tabs still appear gray...

**Comment by piroor** [comment]
Sorry I forgot to add a note. You need to use Nightly 68.0a1 to try the feature.

**Comment by sith-on-mars** [comment]
Sorry for digging up the ancient post. Could you maybe add an manual dark mode switch? I enabled `privacy.resistFingerprinting` in about:config, and `privacy.resistFingerprinting` basically just forces light mode for webpages and addons. I knew you could set dark theme in Firefox customisation, but I personally prefer to use default theme so that my Firefox theme looks consistent with the GTK theme on my Linux.

**Comment by piroor** [comment]
@sith-on-mars Sorry but there is no switch to activate the dark color without system dark color. Instead you can use the user style rules to override default colors with dark colors, citing from the color definition:

https://github.com/piroor/treestyletab/blob/9f2486a88fa4367bd47341aa3bb7762696101fa8/webextensions/resources/ui-color.css#L193-L226

**Comment by sith-on-mars** [comment]
> @sith-on-mars Sorry but there is no switch to activate the dark color without system dark color. Instead you can use the user style rules to override default colors with dark colors, citing from the color definition:
> 
> https://github.com/piroor/treestyletab/blob/9f2486a88fa4367bd47341aa3bb7762696101fa8/webextensions/resources/ui-color.css#L193-L226

Thank you for your reply! However, if I select Photon theme, using this style rules just didn't change anything. If  I select Proton theme, it looked like this: 
![image](https://user-images.githubusercontent.com/37974764/121373219-6bd91700-c92e-11eb-8d84-0257e7fb2f8c.png)

Before Firefox 89, I used [plain dark theme](https://github.com/piroor/treestyletab/wiki/Plain-Dark-theme-%28patch-for-the-theme-%22Plain%22%29) to fix the issue. However, plain dark theme is optimised for Photon and looks bit off for Proton. Would you consider to make another Proton dark theme?

**Comment by piroor** [comment]
I've updated the FAQ and Proton theme for Linux. Please see also: https://github.com/piroor/treestyletab/issues/2930#issuecomment-857956594
