### ISSUE TITLE
[dev 5829] Scrollbar doesn't appear, mouse wheel doesn't scroll the contents of the sidebar after expanding stack with animation disabled

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1587]
Nightly 19-11-17, TST dev 5808 (latest dev).
STR:
Create new profile, install TST, disable animation in settings, close Nightly, copy sessionstore.jsonlz4 from the archive to the root of the profile folder overwriting existing file
[sessionstore.zip](https://github.com/piroor/treestyletab/files/1486770/sessionstore.zip)

Launch Nightly, Hamburger menu - Restore Previous Session
Expand the lowest stack with 187 tabs

ER: Scrollbar appears after stack is expanded, mouse wheel scrolls the contents of the sidebar
AR: Scrollbar doesn't appear after stack is expanded, mouse wheel doesn't scroll the contents of the sidebar

**Comment by SXZ1** [comment]
Bug is reproduced in latest dev 2.2.11.5829

**Comment by piroor** [comment]
Thanks, d20812e should fix this.

**Comment by SXZ1** [comment]
Bug is fixed. Thank you very much!
