### ISSUE TITLE
I need a step-by-step instruction on how to remove the tabbed Firefox tab from the interface. I need only trees from Tree Style Tabs

### ISSUE THREAD

**Issue by IRainman** [piroor/treestyletab#1588]
* Version of Firefox: 57+

**Comment by SXZ1** [comment]
Type about:support in the adress bar, press enter, click on Profile folder - Open folder
Create new folder and call it chrome
Open this folder, right click - New - Text document
Press Ctrl-A and type userchrome.css, press Enter
Right click on userchrome.css - Edit
Paste following code:
`#TabsToolbar {
    visibility: collapse !important;
}`
Save file, close browser, launch browser

**Comment by lbmaian** [comment]
On the startup page that appears when Tree Style Tabs is installed, didn't you see the instructions that linked to https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#for-userchromecss?

**Comment by sandroden** [comment]
Thanks SXZ1, just a note: the correct name of the file is userChrome.css (capital C). At least on Linux it make the difference.
@lbmaian: I didn't had the opportunity to see the instruction on installation as I already had it installed... *;-)

**Comment by WolfgangWeber** [comment]
Thanks a lot, SXZ1!

I didn´t know that the file userChrome.css has to be put into the subfolder "chrome". It doesn´t work if it´s placed in the profile folder.
