### ISSUE TITLE
Feature request: tell the difference between new independent tabs, and new tabs opened by external applications

### ISSUE THREAD

**Issue by Jimi-James** [piroor/treestyletab#1589]
I'm not sure if this is possible with the current WE API, but if it is, I want to be able to hit the new tab button without it being a child and yet open a tab from a separate application's link and have it be a child, or at least open next to my current tab instead of at the end.

## Environment

 * Platform (OS): Arch Linux x64
 * Version of Firefox: 57.0
 * Version (or revision) of Tree Style Tab: 2.2.11

**Comment by piroor** [comment]
The difference cannot be detected via WebExtensions APIs. For example, these tabs are completely same for WE addons:

 * New tab opened from bookmark
 * New tab opened from history
 * New tab opened by other applications
 * New tab opened by other addons

**Comment by piroor** [comment]
Here is the list of available information for newly opened tabs:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab

If the tab is opened from the location bar, you can know more details:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webNavigation/onCommitted
However such information is not available for new tabs opened from outside of the location bar.

**Comment by irvinm** [comment]
@piroor please close this.
