### ISSUE TITLE
It dumps out all tabs when a new addon is updated

### ISSUE THREAD

**Issue by Justcause** [piroor/treestyletab#159]
Just like I said, I took my system down for a few windows updates that were required and when FF booted backup instead of getting the normal, can't find, want to reset questions, all the tabs were gone and Imacros had its own tab. Now since there are 3 seperate groups involved, I don't know who's lap it falls in. Is it yours because somehow you don't prevent being pre empted? If I go to the FF people are they going to say mae culpa? It happens when other add-ons load too. I thought since maybe you already have contacts with them, that you might be able to see what can be done, it was quite disheartening to have it come up and have like 25-35 of my tabs closed, wish there was a quick add-on that could restore all those tabs that were just lost instantly too. Is this a new issue?

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
