### ISSUE TITLE
Which .css is better to hide new tab button completely?

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1591]
I want to hide new tab button completely in both overflow mode (sidebar height is not enough to fit all tabs, scrollbar appears) and non-overflow mode (sidebar height is enough to fit all tabs, scrollbar is gone)
First code:

> #tabbar:not(.overflow) .after-tabs {
  display: none;
}
#tabbar.overflow ~ .after-tabs {
  display: none;
}

Second code:

> .newtab-button-box {
  display: none;
}

**Comment by irvinm** [comment]
I have also seen:

`#tabbar .after-tabs {
    display: none !important;
}`

At the end of the day, I am not sure there is much difference between each implementation. I would think your "Second code:" or this one are more simplistic and slightly better.

**Comment by wdnz** [comment]
I also use the second one without issues.

**Comment by piroor** [comment]
I think `.newtab-button-box { display: none; }` is good enough.

**Comment by SXZ1** [comment]
Thank you very much!
