### ISSUE TITLE
[feature request] Add a link to sidebar.html somewhere.

### ISSUE THREAD

**Issue by lewisaronmilne** [piroor/treestyletab#1592]
By that I mean moz-extension://{uid}/sidebar/sidebar.html

Preferably put it just above the extra css section.

It's difficult to find and almost necessary for customising the css rules. And on top of that you can't just post a link to it online since the uid is always different.

**Comment by piroor** [comment]
I think you should use the debugger for addon. Go to about:debugging and click the "Debug" link for TST, then you'll see a remote debugger for TST. You can change the target document from the "Select an iframe as the currently targetted document" button on the top right of the debugger.

**Comment by piroor** [comment]
I close this because outdated.
