### ISSUE TITLE
[Feature request] Activate last opened child tab when parent tab is closed

### ISSUE THREAD

**Issue by QBANIN** [piroor/treestyletab#1594]
Please add an option to activate last opened child tab when parent tab is closed and all child tab are promoted to higher level.

## Expected result
Activate last opened child tab (in most cases the last one in tree) when parent tab is closed

## Actual result
First child tab becomes active.

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.2.11

**Comment by cipri-tom** [comment]
To me, this seems unintuitive. I'm very interested to hear why you'd prefer it this way 😃

**Comment by QBANIN** [comment]
It's just a habit from old Tab Mix Plus extension :) After opening multiple tabs and closing parent tab I'd like to start browsing starting from the last opened tab.

**Comment by cipri-tom** [comment]
Very interesting ! I also have many remnants from TMP that I'd like to see in TST. Let's hope they'll get implemented, in time 😃

**Comment by piroor** [comment]
I think this should be implemented as an independent addon, instead of a part of Tree Style Tab. It seems possible to be implemented without any tree information, because now all tabs have their own `openerTabId` by default.

**Comment by cipri-tom** [comment]
@QBANIN I thing this could be achieved if you "Insert children at the top of the tree", since the top child will become active, thus the last opened one.

**Comment by irvinm** [comment]
@piroor please close this.
