### ISSUE TITLE
Dragging tabs between windows causes display issues/unresponsiveness

### ISSUE THREAD

**Issue by devonparsons** [piroor/treestyletab#1595]
## Short description

In Firefox Quantum, dragging a tab (or tab tree) from one WINDOW to another causes errant behavior (invisible tabs, frozen window)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a number of tabs in a tree in one window.
 4. Open a new window
 5. Drag a tab tree to the new window

## Expected result

The tabs I dragged to the new window appear in the Tree
The window I dragged the tabs FROM is responsive

## Actual result

The tabs I dragged to the new window are not visible. Because I hide the top bar using userChrome, the only way to access those tabs is to hit ctrl + pageup and ctrl + pagedn. The tabs are clearly attached to the window, but they are not displayed in the tree. No tab appears selected.

The window I dragged the tabs FROM is unresponsive. I seem to need to click around/minimize the program/alt tab a few times before it will respond.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: Quantum (57)
 * Version (or revision) of Tree Style Tab: Latest (All this was done on a brand new computer yesterday)

userChrome.css, in case it is interfering:

```
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
/*
  * TreeStyleTabs solutions to remove tabs
  *
  * Solution by: https://news.ycombinator.com/item?id=15343940 */
#TabsToolbar, #sidebar-header {
  visibility: collapse !important;
}

#TabsToolbar {
  margin-bottom: -21px !important;
}

```

**Comment by devonparsons** [comment]
Sorry, to clarify: The window remains responsive during that time, it's only TST that is unresponsive. And I just noticed a small dot that probably indicates that it's loading something. But the timeframe for loading is quite long (~ 7seconds)

**Comment by devonparsons** [comment]
![firefox_2017-11-20_10-45-29](https://user-images.githubusercontent.com/4528405/33023890-f3c90290-cddf-11e7-9f0a-f745714d8cab.png)

Screenshot: A window with apparently no tabs attached, but clearly pointed at github

**Comment by piroor** [comment]
Sorry, there is a regression around this operation. Recent commit should fix this...

**Comment by pkiersch** [comment]
The issue persists under Ubuntu MATE 17.10

**Comment by caudate-julie** [comment]
Same issue today, Windows 10
Though the source window tree is only irresponsible for about 10 seconds.
Also if I close the destination window and open ot again (from recent closed), all invisible tabs appear in the tree.
