### ISSUE TITLE
[BUG] NO Tabs Appear in the Sidebar

### ISSUE THREAD

**Issue by arandorion** [piroor/treestyletab#1599]
I installed the latest version (2.2.11). When I open the sidebar, it does not display any tabs. [You can see in this image](https://www.dropbox.com/s/lix9zgj90ccqbdc/tree-tab.jpg) that I have plenty of tabs open but none of them appear in the sidebar. I have tried disabling all other extensions, restarting the browser, opening different tabs, etc. It never displays any tabs.

After the sidebar is open for about thirty seconds, the CPU cranks up like it's trying to do something, but it never does anything.

Any idea how to get this working?

Thanks

Tree Style Tab 2.2.11
Firefox 57.0
macOS 10.12.6

**Comment by arandorion** [comment]
Nevermind. I disabled the extension for about an hour then re-enabled it and it started working. If anyone has the same problem I did, try that for a fix.

**Comment by piroor** [comment]
I think this issue has no reason to stay open for now, so I close this.
