### ISSUE TITLE
Allow mouse wheel to switch between tabs

### ISSUE THREAD

**Issue by doomeer** [piroor/treestyletab#1600]
## Short description

It would be nice to be able to use the mouse wheel to switch tabs.

Mouse wheel up could be configured to switch to the tab above or below depending on user preference, and vice-versa for scroll down.

Mouse wheel on the first or last tab could cycle to the last or first tab.

## Motivation

I used to have TST + Tab Wheel Scroll (TWS). Unfortunately TWS can no longer exist with WebExtensions. And I don't think it would work with the new TST anyway. In my opinion, tab wheel scrolling is a simple yet very useful feature, especially with TST as scrolling up and down is then even more natural than with horizontal tabs.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Put mouse cursor on TST (either on a tab or on the gray area).
 4. Scroll the mouse wheel.

## Expected result

Scrolling up switches to the tab above the current one, or to the last tab if the first tab is currently selected. Scrolling down switches to the tab below the current one, or to the first tab if the last tab is currently selected.

## Actual result

Nothing happens.

## Environment

 * Platform (OS): any
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.2.11

## Thanks

I've been using TST for years and it is awesome. Thank you for maintaining it as long as you have.

**Comment by Keith94** [comment]
Does this add-on work for you? https://addons.mozilla.org/addon/tree-style-tab-mouse-wheel/

**Comment by doomeer** [comment]
Awesome, thanks! I don't know why I did not find it, the name is rather obvious. Sorry for the noise.
