### ISSUE TITLE
[documentation] Expand "Code Snippets for Custom Style Rules" page

### ISSUE THREAD

**Issue by gitkato** [piroor/treestyletab#1602]
I made some additions to [Code Snippets for Custom Style Rules](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules) and organized it a bit. This is the page that is linked to from TST settings > Advanced > Extra style rules for sidebar contents.

Could this page maybe start out with a list of all css classes/selectors/etc. that can be styled? This might be faster for some people than trying to read through dozens of snippets. For example:

```css
:root {
  --tab-height;
  --tabbar-bg;
  --tab-surface;
  --tab-text;
  --tab-surface-hover;
  /* ... etc ... */
}

.tab
.tab.active
.tab.pinned
.tab.private-browsing
.tab.unread

/* sub elements */
.tab .closebox
.tab .counter
.tab .label
.tab .twisty,

.tab:hover
.tab:not(:hover)

```

I'm guessing there are quite a few others that I'm missing.

**Comment by piroor** [comment]
Thanks a lot for reorganizing! A list of available classes and major example selectors will make the page friendly for beginners. And I think there should be some links to major CSS documents like  https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors for beginners
