### ISSUE TITLE
TST without top tabs doesn't show complete list for Ctrl+Tab

### ISSUE THREAD

**Issue by cipri-tom** [piroor/treestyletab#1603]
## Short description
When you disable the top tabs by modifying the `userChrome.css`, you cannot switch to tabs beyond the first first six ones, which are shown in the overlay.

If the top tabs are shown, then the tab switching overlay displays thumbnails of the first six and "+ 60 others", which you can switch to if you keep pressing Ctrl+Tab.

## Steps to reproduce

 1. Start Firefox with clean profile. (I didn't do this, since I cannot start new FF in parralel: "Couldn't load XPCOM".
 2. Install TST.
 3. Disable display of top tabs like in #1588 
 4. Try to switch to the 7th tab (6 are shown in the overlay)

## Expected result
It should switch to the 7th tab

## Actual result
Switches to the same tab (cycles through the visible ones only)

## Environment

 * Platform (OS): MacOS High Sierra
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.0.4

**Comment by piroor** [comment]
It is a feature of Firefox it self, not of TST.

**Comment by cipri-tom** [comment]
Sorry, I don't understand. Can TST not populate the list of tabs of FF ?

**Comment by piroor** [comment]
Hmm, I misunderstood your description? I thought that you told about Firefox's built-in "Ctrl-Tab" feature with `browser.ctrlTab.previews`=`true`. (It is `false` by default and I thought you enabled it manually.) If it is wrong, could you describe more details and/or add any screenshot?

**Comment by cipri-tom** [comment]
Yes, you are right ! I have enabled it and forgot it was not on by default. I wanted to have the tabs in the "most recently used" order.

So, I believe that what I would like to have may be beyond the scope of TST.
But here is the example anyways.

STR:
0. Set `browser.ctrlTab.previews=true`
1. Show tab bar at the top (nothing in `userChrome.css`)
2. Open many tabs (some 10-20)
3. Pressing ctrl-tab brings up the following previews. Note there are 6 thumbnails and "60 other tabs".

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/2991890/33165676-fbe388c4-d037-11e7-89cb-87dce0bf33e0.png">

4. Disable top tab bar (via `userChrome.css`) (and restart)
5. Press ctrl-Tab. You now get the same previews, but no more the "60 other tabs" part.

The small bug of TST is that it doesn't let Firefox know there are 60 more tabs.

Ideally, what I would love to get is a feature from the extension that shall not be named here. It was showing tab previews as a list (no thumbnails) and only if ctrl+Tab was pressed for longer than X ms.

I understand if this if beyond the scope of TST.

**Comment by piroor** [comment]
This seems a breakage from hiding Firefox's built-in tab bar. I don't read the source of the feature yet, but hidden tabs seems to fail update its last focused time. Basically Firefox and its Ctrl-Tab feature is not designed to be used in such form, so hiding the tab bar may cause such troubles.
