### ISSUE TITLE
[feature request] New unstyled theme

### ISSUE THREAD

**Issue by jvzr** [piroor/treestyletab#1604]
This is a feature request

I've been trying to style the Dark theme to my liking (thanks to the Extra Style Rules and the Browser Toolbox) and I've achieved almost what I want:

<img width="281" alt="image" src="https://user-images.githubusercontent.com/445151/33137651-d02a7b5a-cfa8-11e7-9232-036499064355.png">

However I've hit limitations because of conflicts with the default CSS. You will notice that the twisties are all messed-up, and for the life of me I cannot find how to prevent the rotation of the collapsed twisty. I also noticed a lot of drop shadows that I have no use for since everything's black.

So I wondered if we could get a new unstyled theme: the HTML stays the same, but everything would have to be user-styled through Extra Style Rules. This would give power users the mean to get exactly what they want

In any case, thank you @piroor for this great extension!

**Comment by piroor** [comment]
After 8463f1f you can use "only very basic styles" theme as the fallback case. Go to TST's configurations and activate the debug mode, then you'll see all of internal configurations. Then set "style" to something unknown value like "-", then you'll get the sidebar without any visual decoration.

**Comment by piroor** [comment]
And I've added a new choice "No Decoration" by a366353.

**Comment by jvzr** [comment]
This is more that I was hoping for, thank you so much, @piroor

**Comment by SicariusNoctis** [comment]
Can you post your styling please?

**Comment by jvzr** [comment]
Thank you so much, @piroor: it's exactly what I wished for!

Here are a few screenshots:

<img width="218" alt="image" src="https://user-images.githubusercontent.com/445151/33435431-7161ef3c-d5e2-11e7-8d28-57b35128ea61.png">

<img width="284" alt="image" src="https://user-images.githubusercontent.com/445151/33435465-8ae64ff2-d5e2-11e7-857e-d9d71533f261.png">

<img width="251" alt="image" src="https://user-images.githubusercontent.com/445151/33435488-9da3a78e-d5e2-11e7-8c37-63d4d52be4cc.png">

Here's the gist with my custom theme: https://gist.github.com/jvzr/9015c395b2b49e1016692597d6583d25

It'll probably change a lot as I continue using it and I will not maintain the gist, fyi @SicariusNoctis

**Comment by badosu** [comment]
@jvzr Would you be able to share on how to apply your theme on a TST installation?
