### ISSUE TITLE
Request: Add API state for internal TST tabs

### ISSUE THREAD

**Issue by joshuacant** [piroor/treestyletab#1605]
Hi, I have had a user of my addon ask for a feature that would react to tabs created by TST itself, such as the "group-tab.html" page: https://github.com/joshuacant/tst-wheel_and_double/issues/4

Could you add a new class to the states list (https://github.com/piroor/treestyletab/wiki/API-for-other-addons#get-tree-information) for these tabs, called something like "internal"? Then addons such as mine would know which tabs were placeholders, like group-tab.html, and react to them according to our needs.

**Comment by piroor** [comment]
Undocumented but such dummy tabs already have a class `group-tab`. Moreover, all tabs have an attribute `data-current-uri` and you can use it for styling like `.tab[data-current-uri^="https://"] .label { color: blue !important; }`

**Comment by joshuacant** [comment]
Yep. group-tab is in there. Sneaky! Thanks!
