### ISSUE TITLE
TST side panel is closed when toggling any other side panel twice

### ISSUE THREAD

**Issue by JudeJohan** [piroor/treestyletab#1609]
## Short description
TST side panel is closed when toggling any other side panel twice. This might not be a bug in TST.

## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open TST side panel.
 4. Press Ctrl+B to open the bookmarks side panel.
 5. Press Ctrl+B to close the bookmarks side panel.

## Expected result
The TST side panel is showing.

## Actual result
The TST side panel is closed.

## Environment
 * Platform (OS): Windows 7, Windows 10
 * Version of Firefox: 57.0 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.2.11

## Comment
Since we (currently at least) cannot have both side panels open at the same time in FF57 (#1402), and not being able to change the short cut (#1463), having the possibility to quickly toggle the side panel instead would help with the work flow.

**Comment by tjakubo2** [comment]
Worth adding that TST has a default hotkey (F1) to toggle its sidebar, helps with this. Still sucks though.

**Comment by piroor** [comment]
I close this because this is out of the range of WebExtensions-based extension.
