### ISSUE TITLE
'Undo Close Tab' overwrites tree structure (incompat with 'Categorize')

### ISSUE THREAD

**Issue by slifox** [piroor/treestyletab#161]
When combining 'Categorize' with 'Tree Style Tab', the 'Undo Close Tab' feature will break & overwrite the tree structure (the tree structure will be lost).

The bug only occurs when a tree structure is created with multiple nested child tabs. When a new tab is created, closed, and the 'Undo Tab Close' feature activated, the tree structure is lost and all tabs become "parent" tabs on the 1st-level.

If you could track down this bug, I would be very grateful. I can't effectively use my browser without Tree Style Tab and Categorize, so worst case I will just continue not using the 'Undo Close Tab' feature. Thank you very much for making this extension!!

### Steps to reproduce
  1. Open a 1st-level new tab (ctrl+t) and go to a website
  2. Middle-click to open 2 child tabs (2nd-level) of the 1st-level original tab
  3. In each of the 2nd-level child tabs, middle-click to open a child tab
   * [at this point there are 5 tabs open; the 1st-level parent has two children, and each of the children has a child tab of its own]
  4. Open another 1st-level new tab (ctrl+t) and go to another website. Then close this tab
  5. Right click on tab bar and click 'Undo Close Tabs'
   * [at this point the whole tab tree structure will be lost, and all tabs will be on the 1st-level; no tabs are lost, but no tab has children anymore]

### Software Versions
* Firefox 3.6.23 (Linux, 64bit; latest v3.6 stable branch as of writing) with the following installed extensions:
   * Tree Style Tab 0.12.2011082901 (latest as of writing)
   * Categorize 0.9.7 (latest available for v3.6 as of writing)

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
