### ISSUE TITLE
WebExtensions nightly builds are incorrectly updated to the AMO releases

### ISSUE THREAD

**Issue by 3c0** [piroor/treestyletab#1610]
## Short description

WebExtensions nightly builds don't follow a nightly builds update channel.

## Steps to reproduce

 1. Start Firefox [Nightly](https://nightly.mozilla.org/) or [Developer Edition](https://www.mozilla.org/firefox/developer/) with clean profile.
 2. Set `xpinstall.signatures.required` to **`false`** in `about:config`.
 3. Install a TST WebExtensions nightly build from @piroor repo: https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi
 4. Wait for a new TST WebExtensions stable release on AMO.

## Expected result

Firefox should update TST to the newest nightly build.

## Actual result

Firefox updates the nightly build to a stable release from AMO (Nightly -> AMO Stable).

## Notes

TST WebExtensions **nightly** builds should contain an [`applications.gecko.update_url`](https://developer.mozilla.org/en-US/Add-ons/Updates#Enabling_updates_to_your_extension) pointing to an `updates.json` manifest in the nightly repo (https://piro.sakura.ne.jp/xul/xpi/nightly/updateinfo/treestyletab-we.updates.json ?).

In fact, the deprecated XUL edition was correctly pointing to a nightly update channel in [treestyletab.update.rdf](https://piro.sakura.ne.jp/xul/xpi/nightly/updateinfo/treestyletab.update.rdf).

Credits to @TheSweetLily for mentioning this behavior in #1572.

## Environment

 * Version of Firefox: Nightly or Developer Edition
 * Version (or revision) of Tree Style Tab: Nightly

**Comment by irvinm** [comment]
@piroor can you evaluate this?  Is this still applicable?

**Comment by piroor** [comment]
XUL version automated build is not updated anymore, because I removed all XUL-based codes from this repository. (Note: you still can chechkout them from old tags or branches.) I think this problem has been resolved.
