### ISSUE TITLE
Can't set TST's sidebar background to transparent when using a userChrome.css auto-hide tweak

### ISSUE THREAD

**Issue by Okamoi** [piroor/treestyletab#1614]
## Short description

It would be nice if people using this userChrome.css [tweak](https://github.com/Timvde/UserChrome-Tweaks/blob/master/sidebar/auto-hide-sidebar.css) to hide the side bar and have it displayed on hover, could set TST's dark grey background transparent. The part where there is no tab or button.

Currently, adding the following CSS in TST's advanced options only sets the background to white. Is there a way to make it transparent or semi-transparent like with legacy TST ?

```
:root  {
  background: transparent !important;
}
```

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Copy paste [this](https://raw.githubusercontent.com/Timvde/UserChrome-Tweaks/master/sidebar/auto-hide-sidebar.css) into the profile's userChrome.css and restart the browser
 4. Move the mouse towards the left side of the screen so that the side bar appears
 5. Notice how the dark grey background hides web page content
 6. Add the transparent background CSS rule above in TST's advanced options: web page content is still hidden beneath the opaque sidebar.

## Expected result

It should be possible to set the (by default) dark grey background through some TST option, TST CSS or userChrome.css (?) or userContent.css. If it is, I didn't figure out how, so maybe it's worth adding [here](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#for-version-2x) ?

## Environment

 * Platform (OS): Windows 7 64-bit
 * Version of Firefox: Firefox 57 64-bit
 * Version (or revision) of Tree Style Tab: 2.2.11

**Comment by piroor** [comment]
This is a limitation of Firefox (Gecko) itself.

**Comment by piroor** [comment]
I close this because this is out of the range of WebExtensions-based extension.
