### ISSUE TITLE
Reveal the sidebar only on events - Feature Request

### ISSUE THREAD

**Issue by davidsierradz** [piroor/treestyletab#1615]
Is there a way to reveal the sidebar only on events like cycling through tabs, opening or closing a tab, etc... like pre-webextension TST?

**Comment by piroor** [comment]
WebExtensions API doesn't allow to show/hide sidebar panel without explicit user actions. Only clicking on the toolbar button or static keyboard shortcut (F1 for now) can do that.

**Comment by piroor** [comment]
I close this because this is out of the range of WebExtensions-based extension.
