### ISSUE TITLE
Control+Click on TST's New Tab button isn't the same as middle click

### ISSUE THREAD

**Issue by mrjohnson22** [piroor/treestyletab#1618]
Middle-clicking TST's New Tab button opens a new tab as the child of the current tab, but control-clicking it does not.

It would be nice if these two click types behaved the same, since many native Firefox controls (including the native New Tab button) treat control-clicking as an alternative to middle-clicking. This is helpful for users without a middle-click button on their mouse or touchpad.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. View the TST sidebar.
 4. Hold the Ctrl key on the keyboard and left-click the TST's New Tab button.

## Expected result
The click should open a new tab as the child of the current tab, just like middle-clicking TST's New Tab button does.

A (tab that was selected when clicking the New Tab button)
\- B (child tab created by New Tab)
C
\- D
...

## Actual result
The click opens a new tab at the end of the tab strip, just like a regular left-click of TST's New Tab button does.

A (tab that was selected when clicking the New Tab button)
C
\- D
B (child tab created by New Tab)
...

## Environment

 * Platform (OS): Any
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.2.11

**Comment by piroor** [comment]
Thanks. Recent commits should fix this.
