### ISSUE TITLE
High network usage when opening sidebar with a lot of tabs

### ISSUE THREAD

**Issue by Remu-rin** [piroor/treestyletab#1620]
## Short description
TST sidebar generates a lot of network usage for unloaded tabs.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Change Firefox setting to restore previous session, then close Firefox.
 4. Grab big session (sessionstore.jsonlz4) from other profile (I use one with 1200 tabs), copy it into new profile.
5. Start Firefox with new profile.
6. For better observation you can close TST sidebar before closing Firefox at step 3, then in step 5 open Firefox, wait some time to the moment when Firefox is not using network at all (all connections are closed or at least not transferring any data), then open TST sidebar manually.

## Expected result
Sidebar should not use network at all, or at least should download only small favicons for the tabs.

## Actual result
Firefox (at start with open TST sidebar or when you open sidebar manually) creates 200-600 connections (simultaneously, then part of the old connections are closing and new are opening) and downloads 30-40 megabytes every time in my case. That takes 5 minutes with my slow internet and makes TST usage awful.

## Environment

 * Platform (OS): Win7
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.2.11

**Comment by piroor** [comment]
Maybe due to https://bugzilla.mozilla.org/show_bug.cgi?id=1315616

**Comment by Remu-rin** [comment]
In two attempts when I monitored firewall to the end, about half of the downloaded amount (23 out of 39 megabytes in the last attempt) were from one single connection to Google IP (173.194.44.71 and 173.194.113.166, probably Youtube). Can this be favicons alone?

**Comment by piroor** [comment]
Hmm, anyway I didn't design TST to read any data from the Web except favicons. Could you research which resources are actually loaded? Firefox can log all HTTP requests by low level logging mechanism:
https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/HTTP_logging

**Comment by Remu-rin** [comment]
Thanks for the tip. Apparently that's really related to favicons. Session, with which a reproduce this, doesn't have favicons on most of the tabs (maybe due to refreshing profile). I have 9 en.wikipedia tabs in it, among thousand of others, all of 9 going into log at first. Then I switched to one of those tabs, switched back to about:networking and restarted Firefox. Now that tab had normal favicon and new log only contains other 8 en.wikipedia tabs, without this one.
Now I'll try to create minimal session with few tabs so that I can share it or full log to you/firefox devs without leaking sensitive data.

**Comment by Remu-rin** [comment]
Here it is.
[log and small session without favicons.zip](https://github.com/piroor/treestyletab/files/1504194/log.and.small.session.without.favicons.zip)

**Comment by piroor** [comment]
I've noticed that there are some OCSP-related requests. To verify validity of TLS certificates, Firefox tries to fetch latest information via OCSP. If you have many secure tabs ("https://..."), such requests will be produced even if it is triggered by accessing to favicons.

**Comment by piroor** [comment]
I close this because outdated.
