### ISSUE TITLE
Performances issues when closing & reopening tabs

### ISSUE THREAD

**Issue by kit-ty-kate** [piroor/treestyletab#1621]
## Short description

Firefox takes between 40% and 60% of CPU time while doing nothing but take between 0% and 2% when Tree Style Tab is disabled.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a bunch of pages (20 or so)
 4. Close them
 5. Reopen them (Ctrl+Shift+T)
 6. Do 3), 4) and 5) at least 3 or 4 times
 7. Watch the CPU load taken by TST (it should high)
 8. Disable TST
 9. Watch CPU load again (it should be very low)
 10. Re-enable TST
 11. Watch CPU load again (it should be a bit higher than without TST, 2% to 4% on my computer)

## Expected result

Taking little CPU time.

## Actual result

Taking lots of CPU time.

## Environment

 * Platform (OS): Debian, GNU/Linux 4.13.13 x86_64
 * Version of Firefox: 57.0
 * Version (or revision) of Tree Style Tab: 2.2.11

**Comment by piroor** [comment]
Could you get profile? How to:

 * [Add-on Debugger - Mozilla | MDN](https://developer.mozilla.org/en-US/Add-ons/Add-on_Debugger "Add-on Debugger - Mozilla | MDN")
 * [How to - Firefox Developer Tools | MDN](https://developer.mozilla.org/en-US/docs/Tools/Performance/How_to "How to - Firefox Developer Tools | MDN")

**Comment by jpdeplaix** [comment]
@piroor is that sufficient ? https://framadrop.org/r/1KTdrUDZZU#jUGzYSUxWreZpKl6vER+HRZJVUhZOAyqqM/Xr6ePQrc=

I did every phases described above.
From 0ms to 6400ms: Phase 2)
From 6400ms to 83200ms: Phases 3), 4), 5) and 6)
From 83200ms to 87500ms: Phase 8)
From 87500ms to 103200ms: Waiting time with TST disabled
From 103200ms to the end: Phase 10)

**Comment by piroor** [comment]
Thanks a lot, but I couldn't download the file. The page just says "Asking for file part 1 of 6"...

Could you attach the file to this issue itself? Compress it as a zip file and drag-drop to this input form, then you'll successfully upload the file.

**Comment by piroor** [comment]
Sorry, it was my fault. After a while I successfully downloaded the file.

**Comment by jpdeplaix** [comment]
Sorry I didn't know it was possible to attach a file directly

**Comment by cipri-tom** [comment]
I also attached some logs:

[non-TST.json.txt](https://github.com/piroor/treestyletab/files/1504008/non-TST.json.txt) when TST side bar is hidden, for about 10s
[starting-TST.json.txt](https://github.com/piroor/treestyletab/files/1504009/starting-TST.json.txt) when showing the TST side bar
[with-TST.json.txt](https://github.com/piroor/treestyletab/files/1504010/with-TST.json.txt) with TST side bar open


Hope these help

**Comment by piroor** [comment]
Hmm, addon's performance profile seems invisible due to e10s. Could you upload profile.json again with the configuration `extensions.webextensions.remote`=`false` ?

**Comment by Remu-rin** [comment]
> Hmm, addon's performance profile seems invisible due to e10s.

Maybe https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler would be more useful than profiler in devtools.
I have noticed similar problems with https://github.com/violentmonkey/violentmonkey/issues/297 and Tree Tabs extensions, but they are using CPU on both main process and webext process (so firefox can even freeze a little), while TST was only using webext-process when I looked.

**Comment by jpdeplaix** [comment]
> Hmm, addon's performance profile seems invisible due to e10s. Could you upload profile.json again with the configuration extensions.webextensions.remote=false ?

It seems it was already ```false``` by default.

**Comment by piroor** [comment]
@jpdeplaix Hmm, could you try the Gecko Profiler? https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler It also has ability to download performance profile as a JSON file.

BTW, by recent commits implementation of throbber animation is completely replaced. I think it can affect to this problem. You can try the [development build](https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi) on Nightly or Aurora.

**Comment by jpdeplaix** [comment]
Here it is. Sorry for the delay: https://framadrop.org/r/mhTVgznceo#R1ruyZwoKzDxP7l/aPXQsxwjJqjYOZer5D5igfCKlaI=

The first big part is the phases 3, 4, 5 and 6, next there is a ~15 seconds of waiting with TST still enabled and then ~15 seconds of waiting with TST disabled.
You can see the difference on the graph.

**Comment by piroor** [comment]
Does this problem still happen on the latest development build?
https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi

**Comment by jpdeplaix** [comment]
Looks like it doesn't happen with the nightly. I'll confirm that in the long run. Thanks !

**Comment by piroor** [comment]
I close this because outdated.
