### ISSUE TITLE
Invisible tab when drag tab from 1 Firefox window to another Firefox window

### ISSUE THREAD

**Issue by nathanila** [piroor/treestyletab#1622]
## Short description

The tab is not displayed in the tree after dragging the tab from 1 Firefox window to another Firefox window.

## Steps to reproduce

 1. In the tab tree, right click a tab and click on "Move to New Window".  I always move a tab that is not part of any tree.
 2. In the new window, drag the tab back to the tab tree in the original window.

## Expected result

The tab should appear in the tab tree of the original window.

## Actual result

The tab is not displayed in the tab tree in the original window.  The new window disappears.  Ctrl+Tab can switch to the dragged tab.

## Environment

 * Platform (OS): Windows 7
 * Version of Firefox: 57.0
 * Version (or revision) of Tree Style Tab: 2.2.11

**Comment by piroor** [comment]
Does this happen on the latest development build http://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi on Firefox Nightly or Aurora?

**Comment by piroor** [comment]
I close this because outdated.
