### ISSUE TITLE
[feature request] When installed for the first time the tree should not be flat

### ISSUE THREAD

**Issue by gagarine** [piroor/treestyletab#1623]
## Short description
When installed for the first time the tree should not be flat but but be a tree based on my past navigation. This is cool for new user that have already a lot of tab open, one can directly see the usefulness of the add-on.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Navigate normally and open a bunch of tabs by opening links in new tabs
 3. Install TST.
 4. All tab on TST are on the same level

## Expected result
Tabs should have a hierarchy depending of my navigation. This can perhaps be build using the history of each tabs.

## Actual result
 All tab on TST are on the same level even the navigation was not flat...

## Environment

 * Platform (OS): MacOS
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.2.11

**Comment by piroor** [comment]
With the [latest development build](http://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi) (note that you need to use Nightly or Aurora to try this unsigned build), the expected result seems to appear for me.

Tree Style Tab now tries to build tree structure based on `openerTabId` information of each tab. If a tab is opened from a link in the current tab, the new tab will have the ID of the current tab as its `openerTabId`, even if TST is not installed (it's a built-in feature of Firefox itself). Actually I've confirmed that TST organizes tree of tabs automatically based on `openerTabId`, with these steps:

 1. Disable TST from about:config.
 2. Open a new window. There is only one new tab (about:newtab) with some thumbnails.
 3. Open a new tab by middle click on a thumbnail. Assume that it is `https://github.com/`.
 4. Switch to the tab opened at the step 3, and middle-click three links in the page. Assume that they are `https://github.com/features`,  `https://github.com/business`, and  `https://github.com/explore`.
 5. Go back to the about:newtab tab.
 6. Open a new tab by middle click on another thumbnail. Assume that it is `https://twitter.com/`.
 7. Switch to the tab opened at the step 3, and middle-click three links in the page. Assume that they are `https://about.twitter.com/`,  `https://support.twitter.com/`, and  `https://blog.twitter.com/`.
 8. Now there are 9 flat tabs:
    * `about:newtab`
    * `https://github.com/`
    * `https://github.com/features`
    * `https://github.com/business`
    * `https://github.com/explore`
    * `https://twitter.com/`
    * `https://about.twitter.com/`
    * `https://support.twitter.com/`
    * `https://blog.twitter.com/`.
 9. Enable TST. Then tree of tabs is constructed in the background automatically
 10. Open TST sidebar in the window, then tabs are shown as a tree like:
     * `about:newtab`
       * `https://github.com/`
         * `https://github.com/features`
         * `https://github.com/business`
         * `https://github.com/explore`
       * `https://twitter.com/`
         * `https://about.twitter.com/`
         * `https://support.twitter.com/`
         * `https://blog.twitter.com/`

**Comment by piroor** [comment]
In other words, if tabs have no `openerTabId` information, TST cannot build tree from them. If `openerTabId` information of your tabs were lost by some reason, tabs would be shown in flat when you installed TST.

And, sadly there is no effective hint to know relation of tabs except `openerTabId`, for WebExtensions addons. `document.referrer` won't help me because it just refers the URI of the opener webpage and easily become inaccessible after the opened page is transitioned.

**Comment by gagarine** [comment]
Thanks. So I guess we can close this issues as I tested on the stable version.
