### ISSUE TITLE
add error message when bookmarking without the permissions

### ISSUE THREAD

**Issue by bricewge** [piroor/treestyletab#1625]
When testing for #1582 I forgot to check `Allow to create bookmarks` (in the parameters), I was a bit confuse at first and thought the fix didn't work since no error message appear.

To avoid this for other user I see to way:

1. When a bookmarking action is performed without the permissions being granted a popup should notify the user and give a hint about the parameters.
2. Disabling by default the contexts menus related to bookmarking: `Bookmark this Tree`, `Bookmarks All Tabs`. So that user are forced to looks into the parameters and discover the check for to allow permissions to bookmark.

I personally prefer the first one.

**Comment by piroor** [comment]
Thanks, it was unexpected regression and f646c8a should fix.

**Comment by bricewge** [comment]
Thanks again! All is fine now.
