### ISSUE TITLE
Can't get permission to Bookmark All Tabs

### ISSUE THREAD

**Issue by hsantanna** [piroor/treestyletab#1626]
## Short description
Right click, Bookmark All Tabs, gives Permission Error.
The permission is already checked at configuration.
Tried to deactivate and activate the permission, but it didn't help.
Tried to reinstall the add-on, but it didn't help.

Have no other tabs addon installed, just uBlock, USI and NoScript.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Right click Tab Tree panel, Bookmark All Tabs
 4. Allow for permission needed
 5. Right click Tab Tree panel, Bookmark All Tabs
 6. Permission error

## Expected result

All tabs get bookmarked

## Actual result

Permission error, no tabs get bookmarked

## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: 57.0 (64 bits)
 * Version (or revision) of Tree Style Tab: 2.2.11

**Comment by SXZ1** [comment]
Try to reproduce the problem with the latest dev build:
https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi

**Comment by piroor** [comment]
Is this duplicated of #1625 ?

**Comment by hsantanna** [comment]
Tested again with updated addon and now it works.

**Comment by BlueRaja** [comment]
I'm seeing this exact issue in v2.4.24

**Comment by tzucker** [comment]
this link goes to non signed version of the add-in and firefox won't let me install it

**Comment by piroor** [comment]
@tzucker You may need to use Firefox Nightly to try development builds. See also: https://github.com/piroor/treestyletab/blob/master/README.md#development-builds
