### ISSUE TITLE
Wrong UI language

### ISSUE THREAD

**Issue by cmOti** [piroor/treestyletab#1627]
## Short description
The language of TST. is different from Firefox or my OS setting. Both Firefox and OS use traditional chinese (zh-TW locale), but TST. use simplified chinese (zh-CN locale).

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST. from [here](https://addons.mozilla.org/zh-TW/firefox/addon/tree-style-tab/)
 3. Right click on any tabs 

## Expected result
The language of context menu should be same as the Firefox or OS (zh-TW)

## Actual result
The language of context menu (and preference page) is zh-CN
![tst](https://user-images.githubusercontent.com/26322551/33376595-9c7a66ea-d551-11e7-9333-05033cc964da.png)

## Environment

 * Platform (OS): Windows7, macOS Sierra 
 * Version of Firefox: 57.0
 * Version (or revision) of Tree Style Tab: 2.2.11

**Comment by piroor** [comment]
TST's package includes both zh_CN and zh_TW (note that `_` instead of `-`, it is a rule of WebExtensions) and there is no more codes around localization, so correct locale should be selected by Firefox itself. Hmm...

**Comment by piroor** [comment]
Does this problem happens only on TST? Do you know any other addon which have both zh_TW and zh_CN locales and zh_TW is correctly selected?

**Comment by cmOti** [comment]
Yes, [Stylus](https://addons.mozilla.org/zh-TW/firefox/addon/styl-us) use zh_TW correctly.

**Comment by cmOti** [comment]
Maybe the case is related? mozilla/activity-stream#2452

**Comment by lycsjm** [comment]
@cmOti
I've already make zh_TW locale, and accepted by author. But you need to wait next version (or just use dev version).
I think the problem is firefox will use zh_CN rather than en if an addon don't have zh_TW locale.

**Comment by piroor** [comment]
Oh, sorry, I forgot that it was added after 2.2.11 was released...

**Comment by cmOti** [comment]
I installed the dev version and everything looks fine. Thank you!
