### ISSUE TITLE
Allow multiple selection of tab

### ISSUE THREAD

**Issue by gagarine** [piroor/treestyletab#1630]
You can't select more than on tab or tree.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Select on tab
 4. hold CMD on mac
 5. select another tab

## Expected result
Both tab are selected and I can move them around or launch an action on both tabs

## Actual result
The last tab is selected

## Environment

 * Platform (OS): MacOS
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 1.2.11

**Comment by piroor** [comment]
It is not a built-in feature of TST, now you need to install another addon Multiple Tab Handler. https://addons.mozilla.org/firefox/addon/multiple-tab-handler/ It is designed to work integratedly on TST's sidebar.

**Comment by piroor** [comment]
I close this because outdated. Now it is a builtin feature.
