### ISSUE TITLE
Text rendering on tab is worst than standard tab

### ISSUE THREAD

**Issue by gagarine** [piroor/treestyletab#1631]
Text rendering on TST is not has good as standard tab.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open TST

## Expected result
Same text rendering quality of standard tab.
Also for basic theme:  exact same typo and font weight and color.

## Actual result
Text is doesn't seem as sharp.

![screen shot 2017-11-29 at 20 54 31](https://user-images.githubusercontent.com/164074/33396009-8ccf30ea-d547-11e7-8ada-5a3093d666af.png)

Don't know if it's linked https://bugzilla.mozilla.org/show_bug.cgi?id=1387594

## Environment

 * Platform (OS): MacOS
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 1.2.11

**Comment by piroor** [comment]
I close this because outdated.
