### ISSUE TITLE
Group tab is closed when only child is closed or moved

### ISSUE THREAD

**Issue by kkot** [piroor/treestyletab#1632]
## Short description

Group tab is closed when only child is closed or moved to other place. It behaves differently than regular tabs and force me to recreate group tabs that takes time.

## Steps to reproduce

 1. Create a tab group for example: about:treestyletab-group?Recipes
 2. Add a child to the tab group.
 3. Make sure that tree is expanded so child tab is visible.
 4. Close the child or move it somewhere else.

## Expected result

Only child tab is closed.

## Actual result

Child tab and parent tab group is closed.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox:  57
 * Version (or revision) of Tree Style Tab: 2.2.11

**Comment by Lej77** [comment]
When multiple tabs are opened in quick succession they are auto grouped with a parent tab with the following URL:
[moz-extension://*/resources/group-tab.html?title=New%20tab%20and%20more&temporary=true](url)
where * is TST's extension id.

So it makes sense that you should be able to make permanent groups with the following URL:
[moz-extension://*/resources/group-tab.html?title=Group&temporary=false](url)
or simpler:
[about:treestyletab-group?title=Group&temporary=false](url)

But it doesn't seem to work correctly so I guess that is a bug.

**Comment by piroor** [comment]
The `temporary=true/false` option is not implemented (migrated) yet. Sorry.

**Comment by piroor** [comment]
I misunderstood, it was already there. I wrongly wrote two patterns to remove needless group tabs. e8d8c8b should fix it.

**Comment by kkot** [comment]
@piroor Thank you. I will check it as soon as it will be released. I tried to install Nightly now and use unsigned version from your website but I think it is not updated with every push to git repo.
This beta channel on addons.mozilla.org that someone mentioned would be useful because it would work with regular Firefox.

BTW. Tab Groups is nice feature but I guess very hard to discover for regular users.

**Comment by piroor** [comment]
@kkot I have not updated my website yet. But automated build is still available at https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi

**Comment by kkot** [comment]
Works, great thanks.
