### ISSUE TITLE
"New container tab" submenu is shown outside of the screen

### ISSUE THREAD

**Issue by BlackSmith** [piroor/treestyletab#1634]
## Short description
Submenu "New container tab" is show outside of the screen, if we have treeStyleTab on right side and maximized FF window.

## Steps to reproduce
 1. Start Firefox
 2. move treeStyleTab panel to right side
 3. click to button "v" for open submenu with containers

## Expected result
The submenu should be shown to left side from button.

## Actual result
The submenu is shown to right side from button. It is outside from screen, when is FireFox maximized.

## Environment

 * Platform (OS): Fedora25
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.3.0

![screenshot](https://user-images.githubusercontent.com/192467/33424862-607f40fe-d5bd-11e7-824c-1acb8bd0f095.png)

**Comment by piroor** [comment]
This should be fixed by #1571. We need to reimplement it totally but now I have very less motivation, so I'm waiting contribution from someone really need it.

**Comment by piroor** [comment]
I close this because outdated.
