### ISSUE TITLE
Wasted space on left side of tabs

### ISSUE THREAD

**Issue by zsau** [piroor/treestyletab#1636]
TST 2.3.0
FF 57.0.1
MacOS 10.13.1

There's a lot of empty space to the left of each tab (green square in the attached image). I believe it only appeared recently. I want to get rid of it, but can't find a CSS rule that does so. I've tried setting margin and padding to zero on various things, but no luck so far.

![tab](https://user-images.githubusercontent.com/6562419/33450294-302f5b5c-d5c0-11e7-9d2f-1ff2d2ce8883.png)

**Comment by zsau** [comment]
I just found that it's left-padding on the `li`s themselves, which I really should have realized before. I still think it's too much space by default, but at least I can get rid of it now.

**Comment by piroor** [comment]
By 2364626b460a1e8c8d4c8703f49aed26809bfe76 now the placeholder margin for overlay scrollbar is applied only when the tab bar is actually scrollable.

**Comment by zsau** [comment]
Thanks!
