### ISSUE TITLE
Sound playing/muted icon does not shown on some environment (character encoding issues)

### ISSUE THREAD

**Issue by shoutr** [piroor/treestyletab#1637]
Tabs with special characters (symbols, like hearts or speakers or anything related) display "OIF 508" in a square instead. Including the speaker icon when a tab is playing sound

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. open youtube or any sound producing website or any website with a special character in the title

![Image](https://i.imgur.com/QAORXcg.png)

## Environment

 * Platform (OS): linux mint 17 and 18.3 and windows 10 64
 * Version of Firefox: firefox 57
 * Version (or revision) of Tree Style Tab: 2.2.1

**Comment by piroor** [comment]
Hmm, it is very strange... Such emoji characters should be rendered by Firefox itself like images. For example, http://www.fileformat.info/info/unicode/char/1f508/index.htm this page includes raw Unicode characters and you should see graphical image at the `string.toUpperCase()` row. If you saw same square with number, I think it is environment specific issue.

**Comment by shoutr** [comment]
The thing is, this speaker character appear correctly on the default tab bar of firefox (I use the userChrome.css trick to hide this default tab bar). It worked before with TST and firefox < 57. And since the new version it's gone, but only in TST.
![Image](https://i.imgur.com/1I3T0eo.png)
and yet the fileformat page show me the unicode number instead of the symbol on the page, that confuse me a little...

**Comment by trevorhobson** [comment]
On Linux Mint I had to install fonts-symbola

I guess that is a restriction of Webextensions that prevents the use of the Firefox built-in icons?

**Comment by shoutr** [comment]
yup, this did the trick -I managed to get a white speaker by installing emojione fonts, now I have a black speaker with symbola-hint.ttf (installed in command line, installing it by opening it with the font  explorer didn't seem to work)

**Comment by piroor** [comment]
Anuway I think this emoji hack is just temporary and I should migrte to SVG icons.

**Comment by piroor** [comment]
By recent commits I've replace those emoji icons to SVG version. Now you don't need to install font for emoji anymore.
