### ISSUE TITLE
re-add suppot for latest ESR-Version 

### ISSUE THREAD

**Issue by youseeus** [piroor/treestyletab#1638]
## Short description

The ESR-Version (its like the Firefox LTE Version) is pre installed in many Companies and can't be changed. The latest version on this update channel is 52.5.0
The newest TST-Version is not compatible to this FF version. Please re-add support for this version

## Steps to reproduce

 1. Start Firefox-ESR with clean profile.
 2. Install TST. 

## Expected result

 2. Install TST. -> successsfull

## Actual result

 2. Install TST. -> not compatible

## Environment

 * Platform (OS): Windows 7
 * Version of Firefox: 52.5.0
 * Version (or revision) of Tree Style Tab: 2.2.11

**Comment by piroor** [comment]
Firefox 52 don't have enough API to implement Tree Style Tab 2, so you should keep TST 0.19.x on Fx52. After Fx59 become the new ESR, TST2 will work with it.

**Comment by sumyungguy** [comment]
This is a problem with the addons.mozilla.org website. It's difficult to find the compatible version, but it's there. If you visit the Tree Style Tab page with older Firefox, it will just tell you that it's not compatible. You have to scroll down to More Information, Version History, and click on "See all versions". Then scroll down and find the last Version 0.19.2017090601, that will have a green "Add to Firefox" button.

I think I read somewhere that Mozilla is working on fixing this problem, but I'm not sure.

**Comment by piroor** [comment]
I close this because outdated.
