### ISSUE TITLE
TST 2.3.0 stops respecting desktop colors in Linux

### ISSUE THREAD

**Issue by danielkza** [piroor/treestyletab#1641]
## Short description

TST 2.2 and earlier used to respect the system colors of my system Theme (Arc-Dark) on Fedora 27. Starting with TST 2.3.0, the Plain theme is always light colored instead:

https://i.imgur.com/n417Af9.png

## Steps to reproduce

Compare TST 2.2 and 2.3 in Linux with any dark GTK theme enabled.

## Expected result

Default theme respects theme colors.

## Actual result

Default theme does not respect theme colors.

## Environment

 * Platform (OS): Linux - Fedora 27
 * Version of Firefox: 57.0
 * Version (or revision) of Tree Style Tab: 2.3.0

**Comment by piroor** [comment]
Sorry I didn't know the system color is used on Linux. By recent commits I've introduced a configuration for color scheme and now "System Color" is the default on Linux.

**Comment by danielkza** [comment]
@piroor Thank you very much! I'll test the latest master and tell you the results.

**Comment by danielkza** [comment]
The latest dev build works perfectly. Awesome work, thank you!
