### ISSUE TITLE
Settings with combo box open at the wrong position

### ISSUE THREAD

**Issue by Tragen** [piroor/treestyletab#1642]
It doesn't matter which setting I want to change. When it is a combobox, it opens always
at the bottom of FF. Here I clicked on "Open new blank tab as"

![2017-12-01 17_50_26-settings](https://user-images.githubusercontent.com/1700241/33493424-45eb7d80-d6c0-11e7-99e3-e84ebed23130.png)

**Comment by Tragen** [comment]
I tried different addons and no one showed this behavior.

**Comment by piroor** [comment]
It is a bug of Firefox itself and fixed at Firefox 58. See also https://bugzilla.mozilla.org/show_bug.cgi?id=1390445

**Comment by Tragen** [comment]
Thanks for the info.
