### ISSUE TITLE
Plain theme no longer uses system colors in 2.3.0 for non-selected tabs

### ISSUE THREAD

**Issue by AndydeCleyre** [piroor/treestyletab#1643]
I'm using a custom dark GTK theme, and this extension, until yesterday, used sensible colors from that theme for all the tabs. But now only the selected tab uses colors from that theme, and the rest are an out of place bright-bg dark-fg.

I'm using Plasma on Arch Linux. I also tried setting the GTK 2/3 themes to Arc-Dark and the same problem was observed.

Firefox 57.0.1

**Comment by piroor** [comment]
This is duplicated issue of #1641.

**Comment by AndydeCleyre** [comment]
@piroor Thank you very much! Would you consider packaging a small release for this?
