### ISSUE TITLE
Dragging a tab to the bookmark toolbar splits the tab onto a new window

### ISSUE THREAD

**Issue by ceribik** [piroor/treestyletab#1646]
## Short description
Dragging a tab to the bookmark toolbar splits the tab onto anew window. 

Normally (pre web-ext), it just created the bookmark, but with the webext version, it also splits off the tab into a new window.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. enable bookmarks toolbar
 4. Browse to any site
 5. Drag tab from TST sidebar to bookmarks toolbar

## Expected result
Bookmark of tab is created on bookmarks toolbar

## Actual result
Bookmark of tab is created on bookmarks toolbar
AND
tab is split onto new window

## Environment

 * Platform (OS): Windows
 * Version of Firefox: 27
 * Version (or revision) of Tree Style Tab: 2.3.0

**Comment by kkot** [comment]
I have same problem. Strange thing is that sometimes it works. I can't figure out what I do different when it does and when it doesn't.

**Comment by piroor** [comment]
The commit 6991c64 seems to fix this issue on my environment. Could you try the latest development build? https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi

**Comment by ceribik** [comment]
I'm still getting the same issue with that dev version.

**Comment by kkot** [comment]
I checked it now on nightly and this issue still exists :(

**Comment by piroor** [comment]
Hmm, it sometimes success but sometimes fail...

**Comment by ceribik** [comment]
@piroor Same for me here. 

Not sure if this helps but when the issue does occur, I notice that the sidebar reloads as well (goes grey).

**Comment by piroor** [comment]
More verification:

 * Firefox 57.0.2 on Windwos 10 doesn't reproduce this problem.
 * Nightly 59.0a on Windows 10 doesn't reproduce this problem.
 * Nightly 59.0a on Linux (Ubuntu 16.04LTS) doesn't reproduce this problem.

**Comment by ceribik** [comment]
How many times did you try it on the windows machines? It doesn't happen every time for me, but when it does it's quite annoying.

**Comment by piroor** [comment]
I've tried 10 or more times, with these conditions:

 * Drop on a dropdown menu for a bookmark folder.
 * Drop on a folder itself, after its contents are shown as a dropdown menu.
 * Drop on a folder itself immediately, before its contents are shown.
 * Drop on a blank area of the bookmarks toolbar.

**Comment by piroor** [comment]
TST triggers its "move tab to new window" operation when the "dragend" event is notified its `dataTransfer.dropEffect` is `none`. In other words, if anyone processes the drag session and it changes `dataTrasfer.dropEffect` to `move` (or others), TST does nothing. Thus I think Firefox's drop handler for the bookmarks toolbar can have something unknown problem.

**Comment by ceribik** [comment]
So TST has ultimate control over that? In that case, could you add a option for disabling tab tearing? 

I rarely use the feature and could just use the right click menu cmd instead if needed.

**Comment by piroor** [comment]
OK, I've introduced new (secret) option to deactivate this behavior by the commit 6f7d055.
You can deactivate it by the checkbox "moveDroppedTabToNewWindowForUnhandledDragEvent" under "Debug mode".

**Comment by C4rter** [comment]
Nice. I've had that issue for quite some time now and that workaround fixes it. Great work.

**Comment by ceribik** [comment]
Thanks the workaround seems to work for now. Will reopen if it reoccurs.
