### ISSUE TITLE
Support close button closing the entire tree

### ISSUE THREAD

**Issue by somini** [piroor/treestyletab#1652]
This is a feature request.

## Short description
Since the middle mouse button already closes a tab, having the close button is redundant. However, closing an entire tree is a regular task that requires tree clicks.

Could it be possible to add an option for the close button to close the entire tree?

**Comment by piroor** [comment]
TST's configurations => "Tree Behavior" => "When a parent tab is closed with expanded tree" => "Close child tabs too" seems the option you find. Did it try it?

**Comment by somini** [comment]
I saw the similar option for closed trees, but missed that. Thanks for that, I'll try it.
