### ISSUE TITLE
New Tree Behavior: Stack by Domain

### ISSUE THREAD

**Issue by Riajyuu** [piroor/treestyletab#1660]
## Short description
 List all tabs under the same domain in a tree. Check tab stack in Vivaldi
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. open tabs as bellow

**BEFORE**

```
A github.com
\- B en.wikipedia.org
C github.com/issues
\- D en.wikipedia.org/wiki/github
E www.google.com
```

## Expected result

When this feature is enabled, tree should be classified by domains.

**AFTER**

```
A github.com
\- B github.com/issues
C en.wikipedia.org
\- D en.wikipedia.org/wiki/github
E www.google.com
```
This will override opening behaviors and other methods of course.

## Actual result

Tree are displayed as opening behaviors.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 58.0b10
 * Version (or revision) of Tree Style Tab: 2.4

**Comment by piroor** [comment]
I have no plan to implement the behavior as a built-in feature. Instead I think it should be done by something other addon developed for the purpose: manage relation of tabs based on their domain or origin. 

By the way, TST has some APIs to manage tree from other addons, and there are some secret options to deactivate auto-organizing of tree. These options will help you to use TST's sidebar as the base to implement such an addon. For more details:
https://github.com/piroor/treestyletab#i-dont-need-automatically-organized-tree-instead-i-just-want-to-organize-tree-by-myself
https://github.com/piroor/treestyletab/wiki/API-for-other-addons

**Comment by Keith94** [comment]
[Sidebar+](https://addons.mozilla.org/firefox/addon/sidebar_plus/) has an option to group tabs by domain btw.

**Comment by irvinm** [comment]
@piroor please close this.

**Comment by gerritholl** [comment]
Is there any addon that implements this behaviour?

**Comment by irvinm** [comment]
https://github.com/mnutt/group-tabs-by-domain
