### ISSUE TITLE
Disable tree functionality

### ISSUE THREAD

**Issue by panpiotrs** [piroor/treestyletab#1663]
Is it possible to completely disable tab stacking functionality? I like to have tabs on the side, it looks perfect right now, but I don't like when tabs are stacked when I open some link in new tab. I know that this is the main purpose of this extension, but maybe it can be done with some setting?

**Comment by trevorhobson** [comment]
Does changing Indent tabs until x level(s) setting to 0 give the result you desire?

**Comment by panpiotrs** [comment]
Nope, I would like to see every tab always as a main tab, with 0 it is still stackable, now with only one level, but still.

**Comment by KinRyuuXIV** [comment]
Sounds like you are looking for vertical tabs, not tree tabs
https://addons.mozilla.org/en-GB/firefox/addon/vertical-tabs-reloaded/

**Comment by panpiotrs** [comment]
I am and I tried VTR, but TST can be styled and now it looks for me like a native part of Firefox. Or maybe it's possible to style VTR tabs and buttons too with css, even when they didn't give an option for that?

**Comment by Lej77** [comment]
Seems to be a possible solution in [Issue 1544](https://github.com/piroor/treestyletab/issues/1544).

**Comment by panpiotrs** [comment]
Thank you @Lej77 , this is it!
