### ISSUE TITLE
Can't change color of group tab icons in the sidebar

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#1666]
## Short description
The group tab icons in the sidebar do not simulate svg context fill and will not change color with the theme. They do switch color if `svg.context-properties.content.enabled` is set to `true` and the TST Sidebar is closed and reopened.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Change TST Theme to "Plain Dark"
 4. Open a couple of new tabs quickly after each other. Or use the following URL: `about:treestyletab-group`.

## Expected result
The opened group tab should have a white icon in TST's sidebar.

## Actual result
The opened group tab have a black icon in TST's sidebar.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.4.0

**Comment by piroor** [comment]
Sorry, it has been fixed by recent commits.
