### ISSUE TITLE
Links opened by Fire Drag are opened as peers, not children

### ISSUE THREAD

**Issue by acertain** [piroor/treestyletab#1668]
## Short description
Links opened by Fire Drag are opened as peers, not children

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install Fire Drag
 4. Go to a web page
 5. Drag a link to open

## Expected result

A - original page
\- B - page opened with Fire Drag

## Actual result

A - original page
B - page opened with Fire Drag

Obviously, this could be a problem with how Fire Drag opens its tabs. But I would appreciate it if you could let me know if that's the case. Selecting the "Open Link in New Tab" from the right-click menu does what I would expect (opens it as a child).

## Environment

 * Platform (OS): Windows 10 Pro - Creator's Update
 * Version of Firefox: 57.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.4.0

**Comment by acertain** [comment]
More data. If the source page has a child, the dragged link will get opened as another child. E.g.

If you start with 

A - source page
\- B - already opened child

And drag a link in A, you end up with

A - source page
\- C - new dragged link from Fire Drag
\- B - already opened child

**Comment by piroor** [comment]
It need to be fixed by Fire Drag. I've reported a pull request for the addon: https://github.com/erictsangx/fire-drag/pull/37

**Comment by acertain** [comment]
Thanks for being so responsive!

**Comment by piroor** [comment]
I close this because outdated.
