### ISSUE TITLE
Delay before tab loading throbber starts

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#1669]
## Short description
When a tab is loading the loading throbber is not started immediately. If no other tabs are loading the animation starts after about 1 second. If there are other tabs loading then the tabs loading animation is started after the other tabs loading animations have completed an iteration.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Load a webpage.

## Expected result
The loading throbber should start its animation immediately.

## Actual result
There is a delay before the loading throbber's animation starts.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 57.0.2
 * Version (or revision) of Tree Style Tab: 2.4.0

**Comment by Lej77** [comment]
To easier observe the loading throbber's issues I used infinitely loading tabs. 

To get infinitely loading tabs I used the program ["iperf-2.0.9-win64"](https://iperf.fr/iperf-download.php) with the command `iperf.exe -s -p 8888` and then I opened tabs with the URL [localhost:8888](url).

**Comment by piroor** [comment]
Thanks. The commit 84dd436 should fix this problem.
