### ISSUE TITLE
Dummy Tabs disappearing on browser restart

### ISSUE THREAD

**Issue by milsanore** [piroor/treestyletab#1673]
## Short description

Firstly, thank you for the excellent plugin 👍 

Dummy tabs - used as a parent for a set of tabs - do not survive browser restart.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Configure TST - "When a parent tab is closed with expanded tree" => "Replace closed parent with a dummy tab and keep the tree"
 3. Open 3x tabs
 4. Add 2x tabs to the third tab as children (so 1x parent with 2x children). I hope this graph is correct:

\- A
  B
  C (selected)

 5. Close the parent. This will replace the parent with a dummy tab
 6. Restart the browser - the "dummy" parent tab will not exist

## Expected result

Dummy tab survives browser restart

## Actual result

Dummy tab does not survive browser restart

## Environment

 * Platform (OS): macos 10.13.1
 * Version of Firefox:  57.0.1 (64bit)
 * Version (or revision) of Tree Style Tab: 2.4.1

**Comment by piroor** [comment]
Is this same to #1670 ?

**Comment by milsanore** [comment]
I don't think so, regular group tabs are ok, only dummy tabs are not. Screenshot attached is after browser restart, it shows the group tab survived. But all dummy tabs are gone.
Thanks,

<img width="122" alt="tst" src="https://user-images.githubusercontent.com/8180435/33864351-66873c18-df40-11e7-8f5f-08f2d296f88f.png">

**Comment by piroor** [comment]
Thanks. TST tried to close such a dummy tab on window close, and the commit 00ad59b should prevent the behavior.

**Comment by piroor** [comment]
On #1670 I realized that current version's group tab is always lost on restored. Recent commits should fix this problem.

**Comment by milsanore** [comment]
Thanks @piroor, it looks like it works, dummy tabs survive browser restart with plugin v2.4.3 👍 

There is one small bug left, after browser restart, the dummy tab contents look funny:

before tab refresh:

<img width="1116" alt="before refresh" src="https://user-images.githubusercontent.com/8180435/33912386-c7089c54-dfe9-11e7-9f8c-06ae542869ad.png">

after tab refresh:

<img width="1103" alt="after refresh" src="https://user-images.githubusercontent.com/8180435/33912399-cf84388e-dfe9-11e7-8ad5-1f98a41a6a62.png">

In the tree, the dummy tab name is correct both before and after tab refresh:

<img width="114" alt="placeholder survives restart" src="https://user-images.githubusercontent.com/8180435/33912416-e76da534-dfe9-11e7-8235-914681551f5a.png">

I just wanted to add one more thing, I use the dummy tab as a parent for each tree - I don't like using a real tab as a "folder", if you see what I mean. So when this bug appeared I lost all of my trees (I now have 200 top-level tabs :p ). Maybe I'm the only person driving TST like this, I'm not sure. But for me the impact of the bug is quite large, so I would urge caution in the future.

Again, thanks for the awesome plugin 👍

**Comment by milsanore** [comment]
One last thing, this was only happening where the "Temporary Group" checkbox was unchecked. So "temporary" tabs did survive browser restart.
