### ISSUE TITLE
Sidebar suddenly turned gray

### ISSUE THREAD

**Issue by sim642** [piroor/treestyletab#1675]
## Short description
Simply one day I noticed TST sidebar being a different color, grayer than usual. I haven't changed any of the settings from default, not added custom CSS. It just suddenly became different color and I can't figure out why.

## Steps to reproduce
I wish I knew.

## Expected result
![screenshot_2017-12-12_20-29-24](https://user-images.githubusercontent.com/378740/33901878-d87978fa-df7b-11e7-9c5c-c95cd728b633.png)

## Actual result
![screenshot_2017-12-12_20-29-08](https://user-images.githubusercontent.com/378740/33901749-80e5410a-df7b-11e7-8acc-fa1e53f47166.png)

## Environment

 * Platform (OS): Xubuntu 16.04
 * Version of Firefox: 57.0.1
 * Version (or revision) of Tree Style Tab: 2.4.1

**Comment by piroor** [comment]
This is intentional change. On Linux, "Plain" and other similar theme use system color scheme instead of Photon color scheme by default. You can switch the color scheme by a secret configuration: TST config => `Development` => Check to `Debug mode` => `Color scheme` => Choose `Photon`.

**Comment by sim642** [comment]
Thanks for the explanation and instructions. I just found it very weird that the look would change for already existing users and now that the option to change it back actually exists but is kind of hidden away.

**Comment by piroor** [comment]
System color was used at TST 2.0-2.2.x (on all platform) and 2.4.0- (on Linux), in other words, Photon color is applied by default on Linux at only exact version 2.3.0. If you initially installed TST at 2.3.0 you thought it is a sudden change, but actually the Photon color was a bug on a specific version.

**Comment by piroor** [comment]
I close this because outdated.
