### ISSUE TITLE
Tabs from pinned tabs not grouped when appending to end

### ISSUE THREAD

**Issue by ben-foxmoore** [piroor/treestyletab#1679]
## Description

"Auto-group tabs opened from same pinned tab" doesn't group tabs when ""Append to the end of the tree" is checked. Likely related to #1677 - perhaps fixed by the same patch?

## Steps to reproduce

1. Start Firefox with clean profile.
2. Install TST.
3. Tick option "Append to the end of the tree" under "Insertion position of new tabs from pinned tab".
4. Check "Auto-group tabs opened from same pinned tab".
5. Pin a tab.
6. Open a link from the just pinned tab as a new tab.

## Expected result

The new tab is inside a dummy group positioned at the end of the tree. Not sure whether the new tab should be at the start or end of the dummy group.

## Actual result

The new tab's position is at the top of the tree, ungrouped.

## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: 58.0b10 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.4.3

**Comment by piroor** [comment]
> perhaps fixed by the same patch?

Yes, this doesn't happen anymore on the latest development build.
