### ISSUE TITLE
New child tab at end of list causes tab *next to* current tab to be highlighted

### ISSUE THREAD

**Issue by joshgold22** [piroor/treestyletab#1682]
## Short description

TST/Firefox can get into a state where the live/current tab is not the one highlighted in the tree.

## Steps to reproduce

1. Set preference so middle-click on New tab button opens a child tab
2. select the last tab.
3. cmd-click the new tab (+) button

(Notes: I have not tested with a clean profile.  My tabs are on the left.)

## Expected result
Exp-result 1 (preferred): child tab opens in the background, parent tab stays selected (blue) in the tree. parent tab's content shows in the main window.
Exp-result 2 (not preferred, but ok): child tab opens in foreground and is selected.  The child is what shows in the main window, and the child/last tab is blue

## Actual result
parent tab's content shows in the main window (and if you type a url in the url bar, it will load in the parent tab) but the child tab is blue.  

I think I'm interacting with the child tab because it's highlighted, but if I load a page, it loads in the parent tab

## Environment

 * Platform (OS): OSX 10.12.6
 * Version of Firefox: 57.0.1
 * Version (or revision) of Tree Style Tab: 2.4.3

**Comment by piroor** [comment]
This problem doesn't happen on my environment anymore. It is possibly fixed by other changes on the master branch.

**Comment by joshgold22** [comment]
I think I'm seeing it fixed too - still in 2.4.3, so I'm not sure what's changed.  Firefox itself is up to 57.0.4 if the change might be there.
Thank you for following up.

**Comment by piroor** [comment]
I close this because outdated.
