### ISSUE TITLE
How do I get rid of this and this ?

### ISSUE THREAD

**Issue by ng4ever** [piroor/treestyletab#1683]
https://i.imgur.com/SVHJUWf.jpg

Or at least hide it?

**Comment by piroor** [comment]
You'll find out the answer from code snippets:
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-the-new-tab-button-at-the-bottom-edge-of-the-tab-bar-1591
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-the-tree-style-tab-header-at-the-top-of-the-sidebar

**Comment by ng4ever** [comment]
Thank you!

**Comment by ng4ever** [comment]
For some reason I can't get the second one to work :( It doesn't hide the top header on the side bar.

**Comment by ng4ever** [comment]
Never mind I wasn't doing it in the userchrome. Got it! Thanks.
