### ISSUE TITLE
Feature request : create and rename Temporary Group

### ISSUE THREAD

**Issue by Adelscott** [piroor/treestyletab#1685]
Today I reloaded a session with Tab Session Manager and I saw that Temporary Groups appeared where before it was a real tab containing other tabs. That's kind of a bug, but well, at least I see that it is possible to have dummy tabs that contains real tabs... like in old Firefox. 

Would that be possible to create a Temporary Group on demand (and not by random issue from loading an old session) ? And would that be possible to rename this tab ? 

Thanks !

**Comment by Lej77** [comment]
Do you mean Tree Style Tab's group tabs? If so they can be created in a number of ways:
1. By rapidly opening several new tabs (for example by holding `ctrl+t` for a couple of seconds) if the "auto-group tabs opened within [number] msec" option is checked. 
2. Using the old TST group tab URL `about:treestyletab-group?title=Group&temporary=false`
3. Using the new TST group tab URL `moz-extension://%tst-extension-id%/resources/group-tab.html?title=Group&temporary=false` where %tst-extension-id% is a number specific to your TST installation.

To change name of a TST group tab you can navigate to the tab and click on the group title in the web area. Once clicked the title becomes a text field where you can write a new name. Press enter when you have written the new name to change the tabs name.

**Comment by Adelscott** [comment]
@Lej77 thanks !

#1 & 2 works, the #3 doesn't (or I couldn't find the right number). I'll use the #2, made a bookmark.

**Comment by Adelscott** [comment]
@Lej77 thanks, seen that. I'll stick with method 2, in case I reinstall TST, id might change

**Comment by mrwensveen** [comment]
Sorry for asking here, but what does the 'Temporary' checkbox actually do?

**Comment by Lej77** [comment]
@mrwensveen It makes it so that the group tab is closed automatically when its last child tab is closed.

**Comment by mrwensveen** [comment]
Thanks! Very useful.

**Comment by piroor** [comment]
I close this because outdated.
