### ISSUE TITLE
Cannot prevent it from making branches? 

### ISSUE THREAD

**Issue by LordStreetguru** [piroor/treestyletab#1686]
Hi, I've gone through all the options on an older version, whatever the last one that works in Waterfox 56 is, and I can't seem to find a way to stop it from making branches at all? Last update on mine was Dec 15th 2017

I just want the tabs on the side, don't need any other features past that. Any ideas? Thanks.

**Comment by piroor** [comment]
It is a FAQ.
https://github.com/piroor/treestyletab/blob/master/README.md#i-dont-need-automatically-organized-tree-instead-i-just-want-to-organize-tree-by-myself

**Comment by LordStreetguru** [comment]
I don't think I have a development section in this version, I can open up the file with Notepad++ but that's probably a lot of work to change.

https://i.imgur.com/51G1MA0.png

**Comment by piroor** [comment]
Oops, sorry I missed the term "Waterfox 56" in your description. You use a legacy version 0.19.x of TST, but the FAQ is written for current version 2.x of TST.

**Comment by LordStreetguru** [comment]
Ima guess there's no quick fix I can do for this? Cannot bring myself to use Firefox 57, like a good number of people it seems.

**Comment by sumyungguy** [comment]
@LordStreetguru , this was a "frequently rejected request" in the old version. From Piro's website:
https://piro.sakura.ne.jp/xul/_treestyletab.html.en

> Q: I want a simple vertical tab, without tree features.
>   A:  [Tab Center Redux](https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/), [Vertigo Tabs](https://addons.mozilla.org/en-US/firefox/addon/vertigo-tabs/) or [sidebarTabs](https://github.com/asamuzaK/sidebarTabs) can do it.

I guess it was for some reason an easy thing to add (well, remove) in the new Web Extensions version, but not in the old legacy one.

Also, you shouldn't expect any updates or improvements to the legacy version, unless there are very serious bugs found.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
