### ISSUE TITLE
Problem when loading session with "New Tab from Location Bar" enabled

### ISSUE THREAD

**Issue by Adelscott** [piroor/treestyletab#1689]
## Short description
The navigation doesn't occur in the tab from the session but it a new tab. Only occurs when "New Tab from Location Bar" enabled

## Steps to reproduce
 1. Load session with Tab Session Manager (compatibility with TST enabled)
 2. Click on a tab from the session (url is something like moz-addon:.....)

## Expected result
Page loading in the clicked tab

## Actual result
A new tab opens instead of loading the page in the clicked tab that keeps the url moz-addon ...

## Environment
 * Platform (OS):  Windows 10
 * Version of Firefox: 57.0.2
 * Version (or revision) of Tree Style Tab: 2.4.3

**Comment by piroor** [comment]
I close this because outdated. New Tab from Location Bar is not maintained anymore.
