### ISSUE TITLE
api event when tab is moved in tree

### ISSUE THREAD

**Issue by S2-** [piroor/treestyletab#1690]
## Short description

I wrote an extension that changes the color of the top tab toolbar to group tabs by it's ancestor.
https://addons.mozilla.org/firefox/addon/colortabgroup/

It would be nice to have an event triggered when a tab is moved inside tree style tab, so that I can recalculate the colors if a tab is moved from one tree to an other.

Something like

```
browser.runtime.onMessageExternal.addListener((aMessage, aSender) => {
  switch (aSender.id) {
    case kTST_ID:
      switch (aMessage.type) {
        ...
        case 'tab-moved':
          ...
        ...
      }
      break;
  }
});
```

**Comment by piroor** [comment]
I think this should be done by `tabs.onUpdated` for `openerTabId`. But it is not notified yet. See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1409262
As a workaround I think a new event for attached/detached tabs will help you. The name `tab-moved` you suggested seems very similar to `tabs.onMoved`, so I think I should use different name line `tree-modified`.

**Comment by S2-** [comment]
`tree-modified` sounds good to me. thanks @piroor

**Comment by irvinm** [comment]
@piroor please close this.

**Comment by piroor** [comment]
Sorry I forgot to implement this...

**Comment by piroor** [comment]
I've implemented `tree-attached` and `tree-detached`. Descriptions: https://github.com/piroor/treestyletab/wiki/API-for-other-addons#when-tree-structure-is-modified
