### ISSUE TITLE
Discussion on change to "Auto-hide sidebar" in Wiki page

### ISSUE THREAD

**Issue by InfernoZeus** [piroor/treestyletab#1691]
[This change](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules/_compare/e132aa55d408a81c80c8de22fbbeaf7835f05de5...1d00826e43cc3be8bfd16e6c3b938e1737f37e2d) was made to the Code Snippets wiki page a couple of days ago. It describes a new way to Auto-hide/show the side bar.

Personally, I think was a poor change. For one, it hardcodes the width of the side bar to exactly 260px. I would propose reverting it, but thought @piroor should probably make that choice.

**Comment by irvinm** [comment]
@piroor please close this.

**Comment by piroor** [comment]
I think that the wiki page should be maintained by people who really use custom user stylesheet, and I'm OK that snippets written by me are modified and updated.
