### ISSUE TITLE
[feature request] optionnally inline TST in contextual menu

### ISSUE THREAD

**Issue by jreybert** [piroor/treestyletab#1693]
## Short description

I would like the TST menu entries inlined in contextual menu instead of a submenu.
As this behavior may not be the prefered way for everyone, it should be enabled with an option.

**Comment by piroor** [comment]
This is a limitation of WebExtensions API. When a WE-based addon register multiple context menu items, they are always placed under a submenu. And TST's fake context menu respects this behavior of Firefox's native context menu. I have no plan to add  any extra behavior to the fake context menu, sorry.

**Comment by jreybert** [comment]
Too bad... I am far to understand all the benefits of WE. I am sure there are plenty. I hope these constraints are here for a good reason (security?) and not a bad initial design.

Anyway, thanks for the addon mate!

**Comment by piroor** [comment]
I close this because outdated. This is now available.
