### ISSUE TITLE
[REGRESSION] Drag-n-dropping a link produces new tab

### ISSUE THREAD

**Issue by ildar** [piroor/treestyletab#1694]
## Steps to reproduce
1. Drag a link anywhere
2. Drop on a tab

What happens is TST opening another tab. That's a regression as XUL-TST did open the link in the tab where it was dropped (in).
The bug is very annoying. Please fix.

**Comment by piroor** [comment]
Thanks. The feature didn't migrated yet from legacy TST. By recent commits I've introduced similar behavior with custom confirmation dialog.

**Comment by ildar** [comment]
Works fine, thanks a lot!
