### ISSUE TITLE
Tabs no longer showing in sidebar

### ISSUE THREAD

**Issue by mr-brunes** [piroor/treestyletab#1695]
Hi

Starting a few days ago I noticed that the tabs were not displaying correctly.
An example - FF showed this as the URL:

URL is:

 moz-extension://afd158a1-c5a5-40df-8510-7fbb0781c160/resources/group-tab.html?title=9e4c1944-7195-4a7d-a8fe-1bb1f0d71f11/replaced/replaced.html%3Fstate%3Dredirect%26title%3DNetgear%2520WNR2000%2520%255BOpenWrt%2520Wiki%255D%26url%3Dhttps%253A%252F%252Fwiki.openwrt.org%252Ftoh%252Fnetgear%252Fwnr2000%26favIconUrl%3Dhttps%253A%252F%252Fwiki.openwrt.org%252Flib%252Ftpl%252Fopenwrt%252Fimages%252Ffavicon.ico%20and%20more&temporary=true

and this as the page:

**9e4c1944-7195-4a7d-a8fe-1bb1f0d71f11/replaced/replaced.html?state=redirect&title=Netgear%20WNR2000%20%5BOpenWrt%20Wiki%5D&url=https%3A%2F%2Fwiki.openwrt.org%2Ftoh%2Fnetgear%2Fwnr2000&favIconUrl=https%3A%2F%2Fwiki.openwrt.org%2Flib%2Ftpl%2Fopenwrt%2Fimages%2Ffavicon.ico and more**

Temporary Group

However after some restarts it now does not show any tabs at all in the sidebar, despite enabling/disabling that function. The tabs display fine on the top bar.

This is with TST 2.4.3 and FF 57.0.2 (64 bit) on Win10.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by mr-brunes** [comment]
Uninstalled add-on and reinstalled and the sidebar tabs are now back.

However I'm still seeing some munged browser pages of the form:

moz-extension://9e4c1944-7195-4a7d-a8fe-1bb1f0d71f11/replaced/replaced.html [snip]

**Comment by mr-brunes** [comment]
This happened again today after a reboot. I found that disabling and enabling TST works to restore the sidebar tabs.

**Comment by JessXZ** [comment]
Sounds like a similar problem I am having. Every time I start FF v57, the TreeTab sidebar is all blank, I need to either restart FF a few times or the sure fire way to temporarily fix it is, goto the TreeTab addon settings page and hit the "SideBar not loading? Reset" button.

**Comment by mr-brunes** [comment]
I can't see that Reset button, even under the Debug settings. Where is it exactly?

**Comment by piroor** [comment]
@mr-brunes The problem you saw can be triggered by another addon, because the URL "moz-extension://9e4c1944-7195-4a7d-a8fe-1bb1f0d71f11/replaced/replaced.html" is not a part of Tree Style Tab addon. Do you use any other tab-related addon?

@JessXZ ["Tree Tabs"](https://addons.mozilla.org/firefox/addon/tree-tabs/) and ["Tree Style Tab"](https://addons.mozilla.org/ja/firefox/addon/tree-style-tab/) are different, this is an issue tracker for Tree Style Tab.

**Comment by JessXZ** [comment]
Thank you.  I have deleted my incorrectly posted comment.  Long time TST user!!!

**Comment by mr-brunes** [comment]
I was only using Tab Session Manager that was obvs related to tabs, but I've now disabled that and everything else (except for LastPass). I'll delete the corrupted tabs and see if the issue reappears. Thanks for listening.

**Comment by piroor** [comment]
I close this because outdated.
