### ISSUE TITLE
WebExtentions: GM.openInTab problem is back once again

### ISSUE THREAD

**Issue by TheCrap** [piroor/treestyletab#1700]
The new version of TST again doesn't open tabs which are opened with GM.openInTab(they renamed the function in the webextentions version) as a child but on the same layer as the parent. I think last time this has been fixed on TST site not on GM site

**Comment by piroor** [comment]
This cannot be "fixed" by Tree Style Tab. Now codes of WebExtensions-based addons are separated and isolated from others, so TST cannot apply patch to Greasemonkey anymore. Instead, Greasemonkey need to [specify `openerTabId` for opened tabs.](https://github.com/piroor/treestyletab/wiki/API-for-other-addons#open-new-child-tab-from-a-specific-tab)

Codes should be updated:
https://github.com/greasemonkey/greasemonkey/blob/master/src/bg/api-provider-source.js#L183
https://github.com/greasemonkey/greasemonkey/blob/master/src/bg/on-user-script-open-in-tab.js

**Comment by piroor** [comment]
The PR: https://github.com/greasemonkey/greasemonkey/pull/2799

**Comment by piroor** [comment]
The PR was merged.
