### ISSUE TITLE
Unable to select or close tabs with the mouse in FF57.0.3

### ISSUE THREAD

**Issue by dromer** [piroor/treestyletab#1701]
## Short description
I manually upgraded from 57.0.2 to 57.0.3
Now when I try to select a tab, or press the x to close, nothing happens.

Switching tabs with ctrl+pgup/pgdown and closing with ctrl+w works as expected.

## Expected result
Switch to tab, or close it.

## Actual result
Nothing.

## Environment
 * Platform (OS): Linux 64bit
 * Version of Firefox: 57.0.3
 * Version (or revision) of Tree Style Tab: 2.4.3

Reverting to 57.0.2 gives normal behaviour.

**Comment by piroor** [comment]
Does this still happen on Firefox 57.0.4 and Nightly?

**Comment by dromer** [comment]
So, it did happen to me once, then I restarted firefox and the problem was gone.

Seems that sometimes when the browser and then the plugin starts it gives this behavior. Have seen it for both .3 and .4 now

**Comment by piroor** [comment]
Oh, yesterday I saw this problem on my system. TST's sidebar didn't respond to any click events, so I think there are something problems around initialization...

**Comment by piroor** [comment]
On my environment reopening of the sidebar didn't solve the problem and finally I had to restart Firefox itself. I didn't tried any other sidebar panel (built-in Bookmarks sidebar and panels provided by other addons), but if the problem happened on all other sidebar panels, it could be a problem of Firefox itself. Could you confirm about other sidebar panels also, at the next time the problem happen on your environment?

**Comment by piroor** [comment]
I close this because outdated.
