### ISSUE TITLE
[Style Improvement] Allow context menu to expand outside the TST border

### ISSUE THREAD

**Issue by Hoeze** [piroor/treestyletab#1702]
The problem with the current situation is that it is hard to access the right sub-menu, since all sub-menus overlap the main context menu.

current situation:
![image](https://user-images.githubusercontent.com/1200058/34450679-3a452826-ed10-11e7-86ad-dfecb97b4541.png)
what it should look like:
![image](https://user-images.githubusercontent.com/1200058/34450691-d7f0ce40-ed10-11e7-9f0a-d6d6f429119a.png)

**Comment by piroor** [comment]
Please see #1333 and #1561. My comments on those issues:

> Currently it is impossible due to missing WebExtensions support. See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1320462

> As described at the [migration story of TST](http://piro.sakura.ne.jp/latest/blosxom/mozilla/extension/treestyletab/2017-10-03_migration-we-en.htm#topic2017-10-03_migration-we-en), current context menu in the sidebar is just a workaround, until any genuine WebExtensions feature to do that is landed. I don't want to pay time anymore to maintain it...

**Comment by piroor** [comment]
This is already done.
