### ISSUE TITLE
Feature request : Add : Notes function

### ISSUE THREAD

**Issue by boq74899** [piroor/treestyletab#1706]
Feature request : Add : Notes function

(I do not know English)

Add: Notes function
Note options: 1 to 10

ex：
Tree ....Tab﹀
[1] ICO GOOGLE A
　ICO GOOGLE B
[5] ICO GOOGLE C
　[10] ICO GOOGLE D　|　 　|
　　　　+　　　　　　 |　 　|
　　　　　　　　　　　|　 　|
　　　　　　　　　　　|T..S..T|
　　　　　　　　　　　　| Note：1 |
　　　　　　　　　　　　| Note：2 |
　　　　　　　　　　　　| Note：3 |

　　　　　　　　　　　　| Note：Sort |
　　　　　　　　　　　　| Note：search and highlight |

............
Advanced settings

.tab .note1 {
  color: #FFFFFF
}

.tab .note5 {
  color: #AAAAAA
}

.tab.discarded .note1 {
  color: #FFFFFF
}

------------------------------

or
Note options: User input

ex：
Tree ....Tab﹀
 [urgent] ICO GOOGLE A
　ICO GOOGLE B
　[Look later] ICO GOOGLE C
[operation] ICO GOOGLE D
　[99] ICO GOOGLE E 　|　 　|
　　　　+　　　　　　 |　 　|
　　　　　　　　　　　|　 　|
　　　　　　　　　　　|T..S..T|
　　　　　　　　　　　　| Note：Add |
　　　　　　　　　　　　| Note：delete |
　　　　　　　　　　　　| Note：change |
　　　　　　　　　　　　| Note：List |
　　　　　　　　　　　　| Note：Sort |
　　　　　　　　　　　　| Note：search and highlight |

「　Note Text Add or change：
　　　[　　　　　　]
　　　　　[OK]　[Cancel]　　　」

「　Note List：　　　　　[X]
　口1.urgent
　口2.temporarily
　　　　　　　　　　[ Use ]
　　　　　　　　　　[ Add ]
　　　　　　　　　　[ delete ]
　　( Drag to sort )
　　　　　　　　　　　　　　」

.........

Advanced settings

.tab .note {
  color: #FFFFFF
}

.tab.discarded .note {
  color: #FFFFFF
}

**Comment by piroor** [comment]
I think this should be done by another addon for this purpose. Because it is not related to "tree of tabs", I won't implement it to TST as a built-in feature. Sorry...

**Comment by piroor** [comment]
I close this because outdated.
