### ISSUE TITLE
Feature request：Return to the last opened label

### ISSUE THREAD

**Issue by boq74899** [piroor/treestyletab#1707]
Return to the last opened label

E.g：

Tree ....Tab﹀
**[ Return to the last opened label ]**
ICO1　ICO2　ICO3
ICO GOOGLE A
　ICO GOOGLE B
ICO GOOGLE C
　　　+

behavior
From A to C, Return button, from C to A.

---------

2.
E.g：

Tree ....Tab﹀
**[ ＜－ ]　[－＞]　[List]**
ICO1　ICO2　ICO3
ICO GOOGLE A
　ICO GOOGLE B
ICO GOOGLE C
　　　+

▼▼▼▼

Tree ....Tab﹀
**[ ＜－ ]　[－＞]　[List]**
ICO1　ICO2　ICO3　　┌　　　　   ┐
ICO Google A　　　　　| Google C   |
　ICO Google B　　　　| **Google A**   |
ICO Google C　　　　　| Google B   |
　　　+　　　　　　　└　　　　   ┘

**Comment by piroor** [comment]
I think this should be done by another addon for this purpose. Because it is not related to "tree of tabs", I won't implement it to TST as a built-in feature. Sorry...

**Comment by irvinm** [comment]
@piroor please close this.
