### ISSUE TITLE
Need help with advanced css rules

### ISSUE THREAD

**Issue by Tragen** [piroor/treestyletab#1713]
I wanted to have my tree like in the legacy TST version.
So I set

Show contentents for the sidebar position: left side

But to get the scrollbar to the right side I had to modify the CSS a bit.

> /* Show title of unread tabs with red and italic font */
> /*
> .tab.unread .label {
>   color: red !important;
>   font-style: italic !important;
> }
> */
> 
> /* Add private browsing indicator per tab */
> /*
> .tab.private-browsing .label:before {
>   content: "🕶";
> }
> */
> 
> /* scroll bar on right side */
> :root.left #tabbar {
>   direction: ltr;
> }
> 
> /* show closebox only on hover */
> .tab:not(:hover) .closebox {
>   display: none;
> }
> 
> /* center closebox vertical */
> .tab .closebox
> {
>     margin-top: 2px;
> }
> 
> /* change tab height and margin */
> :root
> {
>   --tab-height: 27px !important;
> }
> .tab {
>   height: var(--tab-height) !important;
>   margin-bottom: -3px;
>   xxxxmargin-left: 8px;
> }
> 
> /* no horizontal scroll bar */
> #tabbar { 
>   overflow-y: scroll;
>   overflow-x: hidden;
> }
> 
> /* small border between tree panel and websites */
> #tabbar
> {
>     border-right: 2px solid black;
> }
> 
> /* hide + button */
> .after-tabs
> {
>   display: none;
> }
> 
> /* height of tabbar panel */
> #tabbar
> {
>     height: 100%;
>     padding-left: 8px;
> }

Now everything looks like I want it.

![image](https://user-images.githubusercontent.com/1700241/34798109-0c89e4d6-f65b-11e7-9c34-7240356b1446.png)

But when I open a second window, there is something wrong.

![image](https://user-images.githubusercontent.com/1700241/34798131-1e4e6ef8-f65b-11e7-8f29-c969d543e218.png)

What do I need to change that both look like the first window?

**Comment by piroor** [comment]
Could you describe details about what is the wrong point? I thought that the second screenshot looks as:

 * There are two tabs
 * There is no child tab
 * "+" button is missing (is this the problem?)

**Comment by Tragen** [comment]
Sorry if I was unclear. The problem is the big margin on the left side of the tabs in window 2.
In window 1 it's perfect, the second window looks different. When I change it that the
second window is good, the first window tabs are too far left.

**Comment by piroor** [comment]
Thanks. Now I've realized that it is too hard for users to define custom CSS rules to change the position of the scrollbar, so I've decided to add new configuration to control it. By recent commits new configuration item is added under "Debug mode".

**Comment by Tragen** [comment]
Thank you very much.

**Comment by Tragen** [comment]
One more comment. The complete same css is working with FF 58 without any more problems.

**Comment by Tragen** [comment]
It was working only sometimes in FF58. Depending on where the tabs are and if tab trees were expandend or collapsed.
With TST 2.4.5 I was looking for the new option to position the scrollbar you added here:
https://github.com/piroor/treestyletab/commit/cc3a02f1f6ed4d40881a3bcd02b31c57a0787987
But I cannot find it on my option page. Where do I have to look for it?

**Comment by piroor** [comment]
The configuration UI is hidden by default. Check to "Debug mode", then it will appear.

**Comment by Tragen** [comment]
Thanks for the info. I found it with your help.
