### ISSUE TITLE
Firefox for Android 57

### ISSUE THREAD

**Issue by davidhedlund** [piroor/treestyletab#1716]
Your addon supports Firefox Quantum (Firefox 57), do you plan to add support for Firefox for Android 57 as well?

**Comment by piroor** [comment]
Currently Firefox for Android doesn't support sidebar, so TST doesn't work.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/sidebarAction
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/sidebar_action
I believe that the most important feature of TST is the "always visible tree", and sidebar API is quite necessary. Until sidebar API become available, TST will be incompatible to Firefox for Android.

**Comment by piroor** [comment]
Anyway, I'm using Firefox for Android and sidebar on horizontal layout will be useful on large size (10 inch or more) tablets, so I'm positive to port TST to Firefox for Android.

**Comment by davidhedlund** [comment]
Thank you, I'd love to use TST on Firefox for Android in the future.

**Comment by piroor** [comment]
Firefox for Android become obsolete and Firefox Preview will become the new main line on Android.
https://blog.mozilla.org/addons/2019/10/23/fx-preview-geckoview-add-ons-support/
Extension-support is announced as in-progress. We need to keep attention for a while more.

**Comment by davidhedlund** [comment]
> Firefox for Android become obsolete and Firefox Preview will become the new main line on Android.

I know, it's very fast.

> Extension-support is announced as in-progress. We need to keep attention for a while more.

Thanks.
