### ISSUE TITLE
Hidden/phantom/ghost tabs disappear from TST

### ISSUE THREAD

**Issue by madduck** [piroor/treestyletab#1717]
Sometimes (not very often), a tab disappears from display on TST. What I mean with this is that there might be two tabs displayed on TST, but when trying to navigate between them using `ctrl-pgup/-pgdown`, a "ghost tab" gets selected.

I've not been able to reliably reproduce this, but I did manage to capture the problem on video:

  http://scratch.madduck.net/__tmp__tst.mp4 size:1703438 hash:6301eea86d70c855855dba1955a80305b4223e7ffbe123fb863f0cb79ef3aabd

I am sorry for the bad quality, it was hard holding the phone and touching the keys ;)

The next time this happens, I shall investigate what Firefox's own tab bar thinks about it. Please let me know if there's anything else you need to know or would like me to test.

This is using the latest TST with FF 57.0.4 on Debian.

**Comment by piroor** [comment]
When you saw the problem again, could you capture the whole HTML of the background page and the sidebar? Steps:

 1. Enter to `about:debugging`.
 2. Check `Enable add-on debugging`.
 3. Find "Tree Style Tab" from the list and click the `Debug` link.
 4. Then a debugger window is opened and a confirmation dialog for remote debugging appears. Allow to connect.
 5. On the top-right corner of the debugger window, there are some buttons, so click the `Select an iframe as the currently targeted document ` button.
 6. Choose `/background/background.html` from the list.
 7. Choose the `Inspector` tab.
 8. Right-click on the node `<div id="all-tabs">` and choose `Copy` => `Outer HTML`.
 9. Click the `Select an iframe as the currently targeted document ` button again and choose `/sidebar/sidebar.html` from the list.
 10. Right-click on the node `<div id="tabbar" ...>` and choose `Copy` => `Outer HTML`.

Please post the result of the step 8 and 10. If there are some sensitive information, instead please e-mail it to `piro.outsider.reflex@gmail.com`.

**Comment by madduck** [comment]
Here you go (thanks for the great handholding):

    <div id="tabbar" class="vbox" style="margin-top: 28px;">
      <div id="all-tabs">
        <ul data-window-id="3" id="window-3" class="tabs"
            data-duplicating-tabs-count="0"
            data-trying-reforcus-for-closing-current-tab-count="0"
            data-internal-silently-focus-count="0"
            data-internal-focus-count="0"
            data-doing-intelligently-collapse-expand-count="0"
            data-sub-tree-children-moving-count="0"
            data-sub-tree-moving-count="0" data-already-moved-tabs-count="0"
            data-internal-closing-count="0" data-internal-moving-count="0"
            data-prevent-auto-group-new-tabs-until="1516265514644"
            data-opening-count="0" data-opened-new-tabs=""
            data-opened-new-tabs-openers=""
            data-to-be-opened-tabs-with-positions="0"
            data-to-be-opened-orphan-tabs="0" data-to-be-attached-tabs="0"
            data-to-be-detached-tabs="0">

          <li id="tab-3-51" data-tab-id="51" data-window-id="3"
                class="tab subtree-collapsed animation-ready
                contextual-identity-firefox-default complete" draggable="true"
                data-persistent-id="tab-feisty-quetzal-1516483668758-877"
                data-current-uri="https://www.geekzone.co.nz/forums.asp?forumid=158&amp;topicid=210440&amp;page_no=27#1944329"
                data-label="IPv6 beta for Bigpipe"
                data-label-with-descendants="* IPv6 beta for Bigpipe"
                title="IPv6 beta for Bigpipe">
            <span class="twisty" title="Expand tree"></span>
            <span class="favicon">
              <img class="favicon-image" src="https://cdn.geekzone.co.nz/images/favicon-32x32.png">
              <span class="favicon-default"></span>
              <span class="throbber"></span>
            </span>
            <span class="label">IPv6 beta for Bigpipe</span>
            <span class="counter"></span>
            <button class="sound-button" title=""></button>
            <span class="closebox" title="Close tab" draggable="true"></span>
            <span class="burster"></span>
            <span class="active-marker"></span>
            <span class="contextual-identity-marker"></span>
            <span class="extra-items-container behind"></span>
          </li>

          <li id="tab-3-1" data-tab-id="1" data-window-id="3"
                class="tab collapsed animation-ready
                contextual-identity-firefox-default complete" draggable="true"
                data-persistent-id="tab-vivid-heron-1516486656080-909"
                data-current-uri="https://github.com/piroor/treestyletab/issues/1717"
                data-label="Insecure Connection" data-label-with-descendants="*
                Insecure Connection" title="Insecure Connection">
            <span class="twisty" title="Collapse tree"></span>
            <span class="favicon">
              <img class="favicon-image" src="chrome://global/skin/icons/warning-16.png">
              <span class="favicon-default"></span>
              <span class="throbber"></span>
            </span>
            <span class="label">Insecure Connection</span>
            <span class="counter">0</span>
            <button class="sound-button" title=""></button>
            <span class="closebox" title="Close tab" draggable="true"></span>
            <span class="burster"></span>
            <span class="active-marker"></span>
            <span class="contextual-identity-marker"></span>
            <span class="extra-items-container behind"></span>
          </li>

          <li id="tab-3-57" data-tab-id="57" data-window-id="3"
                class="tab subtree-collapsed contextual-identity-firefox-default
                animation-ready complete" draggable="true"
                data-persistent-id="tab-zesty-narwhal-1516502353496-793"
                data-current-uri="moz-extension://eab6ead9-47df-4206-ba08-9ca030877e5b/static/newtab.html"
                data-label="Tridactyl Top Tips &amp; New Tab Page"
                data-label-with-descendants="* Tridactyl Top Tips &amp; New Tab
                Page" title="Tridactyl Top Tips &amp; New Tab Page">
            <span class="twisty" title="Expand tree"></span>
            <span class="favicon">
              <img class="favicon-image" src="moz-extension://eab6ead9-47df-4206-ba08-9ca030877e5b/static/logo/Tridactyl_64px.png">
              <span class="favicon-default"></span>
              <span class="throbber"></span>
            </span>
            <span class="label">Tridactyl Top Tips &amp; New Tab Page</span>
            <span class="counter"></span>
            <button class="sound-button" title=""></button>
            <span class="closebox" title="Close tab" draggable="true"></span>
            <span class="burster"></span>
            <span class="active-marker"></span>
            <span class="contextual-identity-marker"></span>
            <span class="extra-items-container behind"></span>
          </li>

        </ul>
      </div>

      <div class="newtab-button-box vbox">
        <button class="newtab-button" title="Open a new tab"></button>
        <select class="contextual-identities-selector" title="New Container Tab"><option value=""></option><option value="firefox-container-1" style="color: black; background-color: rgb(55, 173, 255);">Personal</option><option value="firefox-container-2" style="color: black; background-color: rgb(255, 159, 0);">Work</option><option value="firefox-container-3" style="color: black; background-color: rgb(81, 205, 0);">Banking</option><option value="firefox-container-4" style="color: black; background-color: rgb(255, 75, 218);">Shopping</option><option value="firefox-default">Default</option></select>
      </div>
      </div>
    </div>

    <div id="all-tabs">
      <ul data-window-id="3" id="window-3" class="tabs" data-duplicating-tabs-count="0" data-trying-reforcus-for-closing-current-tab-count="0" data-internal-silently-focus-count="0" data-internal-focus-count="0" data-doing-intelligently-collapse-expand-count="0" data-sub-tree-children-moving-count="0" data-sub-tree-moving-count="0" data-already-moved-tabs-count="0" data-internal-closing-count="0" data-internal-moving-count="0" data-prevent-auto-group-new-tabs-until="1516265514403" data-opening-count="0" data-opened-new-tabs="" data-opened-new-tabs-openers="" data-to-be-opened-tabs-with-positions="0" data-to-be-opened-orphan-tabs="0" data-to-be-attached-tabs="0" data-to-be-detached-tabs="0">
        <li id="tab-3-51" data-tab-id="51" data-window-id="3" class="tab subtree-collapsed contextual-identity-firefox-default complete" data-persistent-id="tab-feisty-quetzal-1516483668758-877" data-current-uri="https://www.geekzone.co.nz/forums.asp?forumid=158&amp;topicid=210440&amp;page_no=27#1944329" data-label="IPv6 beta for Bigpipe"><span class="label">IPv6 beta for Bigpipe</span></li>
        <li id="tab-3-1" data-tab-id="1" data-window-id="3" class="tab contextual-identity-firefox-default complete" data-persistent-id="tab-vivid-heron-1516486656080-909" data-current-uri="https://github.com/piroor/treestyletab/issues/1717" data-label="Insecure Connection"><span class="label">Insecure Connection</span></li>
        <li id="tab-3-57" data-tab-id="57" data-window-id="3" class="tab subtree-collapsed contextual-identity-firefox-default complete" data-persistent-id="tab-zesty-narwhal-1516502353496-793" data-current-uri="moz-extension://eab6ead9-47df-4206-ba08-9ca030877e5b/static/newtab.html" data-label="Tridactyl Top Tips &amp; New Tab Page"><span class="label">Tridactyl Top Tips &amp; New Tab Page</span></li>
      </ul>
    </div>

I did a quick check and the missing tab has class "collapsed", while the
others have "subtree-collapsed". If I modify that to "subtree-collapsed" in
sidebar.html, then the tab shows up.

Does that help?

**Comment by piroor** [comment]
Thanks! Hmm, I still don't know why this case happens, but actually an independent (orphan) tab is collapsed on your environment. By the commit a35c6f5 now TST tries to expand such invalidly collapsed tabs if they are focused.
