### ISSUE TITLE
Feature request: enhance context menu: keyboard and settings

### ISSUE THREAD

**Issue by mdollinger** [piroor/treestyletab#1724]
First i like to say, that i am still a big fan of TST (and addicted many other people meanwhile;) )

I just like to propose 2 little enhancements for the context menu:
- enable keyboard handling
After a right-click i'd like to use up and down arrow keys to select an option from context menu.
Currently (since FF Quantum) i have to use the mouse

- add an entry for the settings
(if this is technically possible)
Currently i have to click on Menu, then AddOns, then TST, and only then i can modify the options/settings.
This is unhandy, especially when you are new to TST where you try around with the settings a lot

My system data:
 * Platform (OS): Windows 7
 * Version of Firefox: 57.0.4 (64-Bit)
 * Version (or revision) of Tree Style Tab: 2.4.3

**Comment by piroor** [comment]
There is a FAQ about this topic.
https://github.com/piroor/treestyletab/blob/master/README.md#better-context-menu-on-tabs---full-featured-expanded-outside-of-the-sidebar-accesskeys-and-so-on

**Comment by piroor** [comment]
By recent commits accesskey and keyboard navigation for the fake context menu are now available.

**Comment by piroor** [comment]
I close this because outdated.
