### ISSUE TITLE
[feature request] seperate automatic expand/collapse on tab focus into two options

### ISSUE THREAD

**Issue by IGP** [piroor/treestyletab#1726]
## Short description
For the configuration options "When a tab gets focus, expand its tree and collapse others automatically", it would be nice if this was separated into two options. When a tab gets focus I want the tree it is in to expand but I do not want other trees to collapse automatically.

## Expected result
There are two configuration options for when a tab gets focus:
* When a tab gets focus, expand its tree automatically
* When a tab gets focus, collapse other trees automatically

## Actual result
There is one configuration option for when a tab gets focus:
* When a tab gets focus, expand its tree and collapse others automatically

## Environment
 * Platform (OS): Windows 10 Enterprise 1709 (x64)
 * Version of Firefox: Firefox 58.0 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.4.3

**Comment by piroor** [comment]
A secret configuration should help you. Go to TST's configurations and check the "Debug mode", then all internal configurations will appear, thus uncheck `autoExpandIntelligently`.

**Comment by irvinm** [comment]
@piroor please close this.
