### ISSUE TITLE
Dragging private tab to normal window causes desync.

### ISSUE THREAD

**Issue by adavier** [piroor/treestyletab#1730]
## Short description
Dragging tabs from private window to a normal window causes the sidebar to become out of sync.

Video [Here](https://gfycat.com/KindlyWindingIrishterrier)
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a private browsing window
 4. Open a new private browsing tab.
 5. Drag a tab from the private window to a normal window

## Expected result
Nothing should happen.

## Actual result
A new blank tab is created in the normal window.
The dragged tab remains in the private window, but cannot be selected by the toolbar. 
If closed on the private window, the blank tab on the normal window is closed.

## Environment

 * Platform (OS): Win 10 x64
 * Version of Firefox: 59.0b3
 * Version (or revision) of Tree Style Tab:  2.4.3.6303 & 2.4.3

**Comment by piroor** [comment]
Thanks, recent commits should fix this problem.

> Nothing should happen.

When I drag a tab from private browsing window to a tab bar of another regular window, the dragged tab is detached to a new private browsing window. So TST respects this behavior, instead simply ignore dragged tab.
