### ISSUE TITLE
No file named "*sessionstore*" found for using with treestyletab-sessionstore-migrate.

### ISSUE THREAD

**Issue by Inkbottle007** [piroor/treestyletab#1732]
## Short description
No file named "\*sessionstore*" found for using with treestyletab-sessionstore-migrate.
Bookmarks lost there tree structure.

## Steps to reproduce

First thing, I sort of establish, that on a debian/stable computer there is no file named
"\*sessionstore*". I've done the following manipulation on a borrowed computer.

1. Take a debian/stable computer
2. Install Firefox-esr 52.xx (https://packages.debian.org/stretch/firefox-esr)
3. Install treestyletab (0.18), via the debian package
(https://packages.debian.org/stretch/xul-ext-treestyletab)
4. Open firefox; build a tree of tabs; bookmark the tree of tabs;
verify in bookmarks window (Ctr-Shift-o) that tabs are associated with appropriate parent tab;
Clear history and everything; reopen FF; reopen the tree tab to verify everything is in place
5. Close FF
6. Search for a file named "\*sessionstore*"
sudo find ~/.mozilla /etc /usr -iname "\*sessionstore*"
No results returned.

Then what happened to me is that on a debian/sid computer,
with TST 0.19 (https://packages.debian.org/sid/xul-ext-treestyletab)
and FF-esr 52.xx (https://packages.debian.org/sid/firefox-esr)
I've migrated to
FF-57 (https://packages.debian.org/sid/firefox, it was 57 at the time I did it)
and TST from https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/
(file is tree_style_tab-2.4.3-an+fx-linux.xpi
md5sum is 07e5df13b8d83d645b466d604470985a)

After that my bookmarks lost there tree structure.
And I cannot find a file to provide to treestyletab-sessionstore-migrate.

I've done several backups of my .mozilla directory, dating from when I was still using
FF-esr 52.xx and TST 0.19; I cannot find a suitable file there either.

Nor can I find a file matching the name one another debian/sid computer of mine

QUESTION:
Would you have any idea of where the parent tab information is stored on a debian computer
using FF-esr 52.xx and TST 0.19?

I understand it might be distro specific, and I can open a bug on debian in case you
have no clue of what could have happened.

## Expected result
Have a file whose name is matching "\*sessionstore*" to give to the tool
treestyletab-sessionstore-migrate

Or find where are stored the parent tab information.

Alternative expected result: Find a way to have my trees of tabs back,
and not only flattened lists of bookmarks.

## Actual result
Can't find such a file, or where are stored the parent tab information;
Even though I can see the bookmarks are associated with appropriate
parent tab information

## Environment

 * Platform (OS): debian/sid
 * Version of Firefox: From FF-esr 52 to FF-57
 * Version (or revision) of Tree Style Tab: from 0.19 to 2.0

**Comment by Lej77** [comment]
The "sessionstore" file stores information about the current Firefox session. It stores the currently open windows and tabs and also recently closed windows and tabs. Bookmark data is stored in a separate file named `places.sqlite`. This information can be found [here on Firefox's support](https://support.mozilla.org/kb/profiles-where-firefox-stores-user-data#w_what-information-is-stored-in-my-profile).

Unfortunately this won't help you since the current version of TST doesn't support restoring tree structure from bookmarks (or saving it). You can read about this in [issue 1639](https://github.com/piroor/treestyletab/issues/1639).

If you want more information about "sessionstore" files I wrote some about it in [issue 1678](https://github.com/piroor/treestyletab/issues/1678#issuecomment-351411816).

**Comment by Inkbottle007** [comment]
It seems I've been mistaken and jumped to conclusion.

Let's consider Firefox-58 + TST-2.0.
*bookmark this tree = bookmark all tabs | (only on a sub-tree)*

Hierarchical information is **lost** through the process of bookmarking,
even though you selected "bookmark this tree".

So "bookmark this tree" could be safely rechristened *"bookmark this tree as a flat list"*.

This is very sad for users heavily relying on the persistence, of the tree structure and
associated metadata, through the "bookmark this tree" process.

So it seems that it is a **duplicate** of [Tree structure of tabs not restored
when opening "Bookmark all tabs/this tree" folder #1639](url), which is **fixed**
as **Bug of Firefox Itself**.

And that no matter what, I won't have my bookmarked trees restored anytime soon.

However, in older versions of TST (<= 0.19), tree structure metadata are/were stored in
the file `places.sqlite`, or in files like `firefox/xxxxx.default/bookmarkbackups/bookmarks-2018-01-05_65992_GuoOolzxa8uK9j2pTyY2mP\=\=.jsonlz4` as "json objects/data."

So, when/if, there will be a workaround, it will be possible to find the hierarchical
data in `places.sqlite` or in on of the `.jsonlz4` bookmarkbackups files. (Maybe
only for those who did backups of their Firefox's profiles).

Also if, a user want to extract the lost hierarchical data, he can find them in one
of the above files.

**Comment by irvinm** [comment]
@Inkbottle007 is this still an issue for you?  I believe a lot has changed since you reported this and hopefully this is a not a problem for you.  If not an issue, please close it.  Thx.

**Comment by Inkbottle007** [comment]
I agree this issue can be closed. Thx.
