### ISSUE TITLE
Can't change background color of side bar after update to 2.4.5.

### ISSUE THREAD

**Issue by chriscjs** [piroor/treestyletab#1733]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST 2.4.5
 3. put
:root { background: black; }
into the extra style rules box
 4. background color does not change from default gray
 5. downgrade to 2.4.3 from addons.mozilla.org
 6. background color changes to black as expected

## Expected result
Background should change to specified color.

## Actual result
Background color stays at default gray.

## Environment

 * Platform (OS): Linux
 * Version of Firefox: Developer Edition 59
 * Version (or revision) of Tree Style Tab: 2.4.5

**Comment by piroor** [comment]
After the commit 4eaf99095cef7bffd0a819ae54cf52738784aa68 now you need to specify background color for an element `div#background`, like https://github.com/piroor/treestyletab/blob/master/webextensions/sidebar/styles/square/plain-color.css#L18

**Comment by chriscjs** [comment]
Thanks.  This works
:root, #background {
  background: black;
}
