### ISSUE TITLE
Collapsed subtrees leave empty space

### ISSUE THREAD

**Issue by Phloog** [piroor/treestyletab#1734]
## Short description

When collapsing a subtree, TST leaves an empty space between the collapsed node and the next node; the empty space is smaller than the space taken by the expanded subtree, BUT its height is proportional to the height of the subtree (more collapsed siblings = larger empty space).

Closing and reopening the sidebar removes the empty space below collapsed subtrees.

See screenshots (red drawn arrow shows the empty space):

Before collapsing| After collapsing
------------ | -------------
![tst1](https://user-images.githubusercontent.com/2299409/35429828-049940e2-0276-11e8-806d-7ab264f83c28.png) | ![tst2](https://user-images.githubusercontent.com/2299409/35429831-079710bc-0276-11e8-864e-78dd1750490b.png)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. open several tabs and arrange them into multiple subtrees
 4. collapse one subtree

## Expected result

Entries immediately following collapsed subtrees should be adjacent to the collapsed entry

## Actual result

There's a bit of space between a newly-collapsed entry and the next visible one.

## Environment

 * Platform (OS): win 10 64bit
 * Version of Firefox: 57.0.4 (32-Bit)
 * Version (or revision) of Tree Style Tab: 2.4.5

**Comment by piroor** [comment]
This problem appears when actual height of each tab is different from the calculated height. Could you inspect details by the remote debugger? Steps:

 1. Start to inspect sidebar page according to the [instruction](https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs).
 2. Choose "Console" tab and type following codes into the prompt:
     `alert(gTabHeight + '\n\n' + gSizeDefinition.textContent)`
 3. Then a message dialog will appear. Select its contents, copy it, and paste to here.

**Comment by Phloog** [comment]
This is the requested content:

	26

:root {
    --favicon-size:         16px;
    --faviconized-tab-size: 28px;
  }:root {
    --tab-height: 26px;
    --scrollbar-size: 17px;
    --narrow-scrollbar-size: 8px;

    --tab-burst-duration: 375ms;
    --indent-duration:    200ms;
    --collapse-duration:  150ms;
    --out-of-view-tab-notify-duration: 750ms;
  }

**Comment by piroor** [comment]
Hmm, they seem to exact same. Is the user-defined style rules (in TST's configuration) blank or commented out?

**Comment by Phloog** [comment]
Hey, you're right, now I feel a bit stupid: The user-defined styles does in fact contain a line to make the tab entries smaller:

:root {
  --tab-height: 22px;
}

I wasn't aware of that anymore, nor the fact that this breaks the display of collapsed branches.

Now, with that being said, is it somehow possible to keep the smaller tab height while preventing the blank space when collapsing?

Thanks, Cheers

**Comment by piroor** [comment]
Here is a recommended method: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#change-tab-height-236

Note that you need to reopen the sidebar to apply this rule correctly. When the sidebar is shown, TST measures the actual height of tabs and store the result as a variable `--tab-height` to share the information for positioning, collapsing/expanding, and so on.

**Comment by Phloog** [comment]
Thanks, this does indeed work.
