### ISSUE TITLE
Consider renaming "Temporary group" to "Automatically close when the subtree becomes empty"

### ISSUE THREAD

**Issue by SimonSapin** [piroor/treestyletab#1736]
## Short description

… or something else that describes what that checkbox does. I *think* that’s what it does? After looking through the issue tracking. I had no idea at first and was very confused.

## Steps to reproduce

* In addon settings, make sure "Auto-group tabs opened for same pinned tab"
* In a pinned tab, middle-click on a link
* The link opens as a child tab on a tab called "Tabs from […]" that contains a checkbox with the label "Temporary Group"

## Expected result

* Ideally, UI should be self-explanatory.

## Actual result

* I’m not sure what a "group" is in this context, I haven’t seen this term used before in the context of TST (for example on its settings page, which uses "tree", "parent", "child")
* I have no idea what "temporary" means in this context.

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 58.0
 * Version (or revision) of Tree Style Tab: 2.4.5

**Comment by Peter92** [comment]
I'll second this, was initially a bit confused as to what "temporary" did. Maybe "close when empty" would be better than an actual sentence though.

**Comment by piroor** [comment]
Thanks, now the checkbox is renamed with more meaningful label by 4159745.

**Comment by SimonSapin** [comment]
Thanks.
