### ISSUE TITLE
Tree lost on container change

### ISSUE THREAD

**Issue by Naheulf** [piroor/treestyletab#1737]
## Short description
Lost tree structure if tab change container.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install Switch Container
 4. Create some tree
For example:
```
A One Tab
+- B Another Tab
   +- C Child tab
```
 5. With "Switch Container" add-on change container for one tab.

## Expected result
The tab tree remains unchanged.

## Actual result
The tab tree is lost for the tab that changed container.
In example below I change container for "B" tab but step to reproduce work for all tabs
```
A One Tab
+- C Child tab
B Another Tab (in new container)
```

## Environment

 * Platform (OS): Window 8.1
 * Version of Firefox: 58.0 (Also present in the previous version of Firefox )
 * Version (or revision) of Tree Style Tab: 2.4.6

**Comment by piroor** [comment]
This problem is impossible to be solved by Tree Style Tab, because the Switch Containers addon just opens new tab and close old one:
https://gitlab.com/mjanetmars/switch-container/blob/master/switch_container.js#L28
There is no hint to detect relation of tabs...

**Comment by Naheulf** [comment]
If a tab is opened with one url and another tab, with the SAME URL, is closed within 500ms, you can not consider it to be the "same" tab?

**Comment by mildred** [comment]
Could it be possible to improve the switch-containers addon to make the relationship visible and keep the tree?

**Comment by piroor** [comment]
@mildred Maybe. For example, if switch-containers addon opens a tab with `openerTabId`, TST can attach the reopened tab to the tree instead of the removed original tab.

**Comment by piroor** [comment]
I close this because outdated.
