### ISSUE TITLE
Old (not latest) versions of tree style tab on centos

### ISSUE THREAD

**Issue by bmilanov** [piroor/treestyletab#1739]
Hello,

Firefox that ships with centos is ~52.6 ESR and not supported by latest TST. Is it safe to run old versions of tree style tab from here:
> https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/versions/ ?

---
Thanks

**Comment by piroor** [comment]
Yes. Minor releases of Firefox ESR52 only includes changes around security issues, so most legacy addons including TST released when Firefox 52 (not ESR!) was the latest release should work on ESR52.

**Comment by bmilanov** [comment]
Confirming that it works, however I was wondering if non-latest versions of TST are somehow "unsafe" to use. My understanding is that TST does not interact with web resources, so in theory it cannot be deemed an attack surface. Is that correct?

**Comment by piroor** [comment]
I think legacy TST is mostly safe. However please note that there were some fingerprinting problems. I thought that known fingerprinting issues were fixed, but it may have some more unknown issues.

**Comment by bmilanov** [comment]
Got it. Thank you for the information!
