### ISSUE TITLE
When changing system theme, sidebar must be closed/reopened

### ISSUE THREAD

**Issue by maxxflow** [piroor/treestyletab#1740]
## Short description
When the system/GTK theme is changed, the new theme is not applied to TST until the sidebar is closed and reopened.

## Steps to reproduce
1. Use a TST theme that honors system theme colors, e.g. 'Plain'.
2. Change the system theme (I use gnome-tweak-tool) - preferably from a light to a dark theme or vice versa.

## Expected result
When the main Firefox UI changes to the new theme, TST should do the same.

## Actual result
TST keeps the old theme until the sidebar is closed and re-opened.

Editing anything in the extra CSS under TST's "Advanced" settings will also trigger an update that applies the new theme.

## Why is this important?
In my case, I have a keyboard shortcut on my laptop mapped to toggle between the light and dark versions of my system theme. This allows easy switching to something easier on the eyes when I happen to be in a dark surrounding. This mostly works great, but TST remains as a bright patch of light until I close/reopen it.

## Environment

 * Platform (OS): GNU/Linux (Ubuntu)
 * Version of Firefox: 58.0
 * Version (or revision) of Tree Style Tab: 2.4.6

**Comment by piroor** [comment]
It is impossible for now because there is no WebExtensions API to handle such events.

**Comment by maxxflow** [comment]
Fair enough.

For posterity, my workaround for now is the following crazy oneliner, executed by the same script that changes the system theme:

`PREV=$(xdotool getactivewindow) && for w in $(xwininfo -root -tree | grep '("Navigator" "Firefox")' | sed 's/ *\(0x[a-z0-9]*\).*/\1/'); do xdotool windowactivate $w && sleep 0.5 && xdotool key F1 && sleep 0.5&& xdotool key F1; done && xdotool windowactivate $PREV`

It finds any Firefox windows, activates them one by one and simulates two "F1" key presses in each window, to close and re-open the sidebar...

**Comment by piroor** [comment]
I close this because this is out of the range of WebExtensions-based extension.
