### ISSUE TITLE
Child tabs of pinned tabs open in temporary groups without a way to disable this behaviour

### ISSUE THREAD

**Issue by AlexCzar** [piroor/treestyletab#1746]
## Short description
After one of the latest updates new tabs opened from pinned tabs started opening in temporary groups. While I understand the logic behind it, I do not like it and would prefer older behaviour, where tab just opened at the end of the tree as a top level tab.
If this change was intentional, please provide a way to revert to the old behaviour.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. open any page which has links
 4. pin the tab you've just opened
 5. open any link from the page in a new tab

## Expected result
Child tab of a pinned tab opens as a top level tab at the end of tabs tree

## Actual result
Child tab opens in a temporary group

## Environment

 * Platform (OS): Linux (OpenSuSE), Windows 10, (I don't have others)
 * Version of Firefox: 58
 * Version (or revision) of Tree Style Tab: 2.4.6

**Comment by Lej77** [comment]
You can configure TST to behave in this way by disabling a checkbox named `Auto-group tabs opened from same pinned tab` under the header `New Tabs Behavior` in TST's settings page.

**Comment by AlexCzar** [comment]
Yes, this works, I somehow missed that checkbox. Thank you!
