### ISSUE TITLE
Bookmarks sidebar closes when Tree Style Tab sidebar is opened

### ISSUE THREAD

**Issue by armbck** [piroor/treestyletab#1750]
## Short description
Bookmarks sidebar and Tree Style Tab sidebar cannot be open simultaneously
## Steps to reproduce

 1. Open Bookmarks sidebar
 2. Open Tree Style Tab sidebar 

## Expected result
Bookmarks sidebar would stay open and TST sidebar would open new sidebar beside it.

## Actual result
Bookmarks sidebar is replaced by TST sidebar

## Environment

 * Platform (OS): Windows 7 Pro SP1
 * Version of Firefox:  58.0.1
 * Version (or revision) of Tree Style Tab: 2.4.7

**Comment by piroor** [comment]
Currently this is impossible due to limitation of WebExtensions APIs. See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1328776

**Comment by armbck** [comment]
Thank you @piroor for an excellent add-on, for your prompt answer and for pointing this out. I guessed this was the reason, but wanted to make sure. Let's wait for it to get fixed. If it gets... Feel free to close this issue, if you think it is not soon enough.

**Comment by vohzi** [comment]
I really hope there's gonna be a workaround for that. It was so practical.

**Comment by polyzen** [comment]
> Now I can't even drag & drop links from my tab bar to my bookmarks...

You can still do this with the bookmark toolbar item and the library (Show All Bookmarks) (and presumably the bookmark toolbar).

**Comment by piroor** [comment]
Recently I released a new addon ["Aggregate Tabs to Main Window"](https://addons.mozilla.org/en-US/firefox/addon/aggregate-tabs-to-main-window/). It may become a workaround for this issue.

 1. Install both addons: TST and Aggregate Tabs to Main Window.
 2. Go to `about:config` and set `browser.tabs.loadBookmarksInTabs` to `true`.
 3. Show "Tree Style Sidebar" sidebar in the main window.
    https://addons.mozilla.org/firefox/addon/tree-style-tab/
 4. Open a new window, and show "Bookmarks" sidebar in the window.
 5. Reduce width of the window for Bookmarks sidebar to enough width for the sidebar area.

Then, new tabs opened from the Bookmarks sidebar by clicking are automatically moved to the main window, thus it will work like multiple sidebar panels.

![tst-and-bookmarks](https://user-images.githubusercontent.com/70062/40523872-9bb5ff3e-6012-11e8-98e5-4cfb07666c3a.png)

**Comment by piroor** [comment]
I close this because this is out of the range of WebExtensions-based extension.
