### ISSUE TITLE
TST does not respect browser.tabs.warnOnCloseOtherTabs

### ISSUE THREAD

**Issue by paninaro95** [piroor/treestyletab#1752]
## Short description

TST does not respect browser.tabs.warnOnCloseOtherTabs, i.e. TST does not show the message box that Firefox shows when you select "close other tabs" from the context menu of a tab.

By default, browser.tabs.warnOnCloseOtherTabs is set to true, so Firefox does warn you whereas TST does not. I just lost about 150 tabs as there is no undo possibility either 👎

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open multiple tabs.
 4. Open the context menu of a tab inside the TST panel and select "close other tabs".
 5. All other tabs will be closed without a warning prompt.

## Expected result

A warning prompt should be shown.

## Actual result

No warning prompt is shown.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 58.0.1
 * Version (or revision) of Tree Style Tab: 2.4.8

**Comment by Lej77** [comment]
If you haven't restarted Firefox after losing your tabs it might be possible to restore your session to its state at last Firefox startup by closing Firefox and then moving and renaming:
`FirefoxProfileFolder\sessionstore-backups\previous.jsonlz4` 
to 
`FirefoxProfileFolder\sessionstore.jsonlz4` 
and then starting Firefox again. You might want to backup `previous.jsonlz4` before doing anything in case it goes wrong. 

Firefox profiles folders are located in:
`C:\Users\%UserName%\AppData\Roaming\Mozilla\Firefox\Profiles` 
and there should only be one folder in that directory if you haven't manually create new Firefox profiles.

I wrote about Firefox session management in [issue 1678](https://github.com/piroor/treestyletab/issues/1678#issuecomment-351411816) so you could read more there if your interested.

**Comment by paninaro95** [comment]
Thanks Lej77 for your hint -- I found that trick myself at [https://support.mozilla.org/de/questions/1119692](url) although it is not up to date with the latest Firefox where the jsonlz4 files are used instead of js. I was lucky that I took a backup of my profile after I lost all my tabs, but still before I closed Firefox. I will now create a backup of my profile on a daily basis 😁

**Comment by lycsjm** [comment]
@paninaro95 Maybe you can try something like [Tab Session [Manager](https://addons.mozilla.org/zh-TW/firefox/addon/tab-session-manager) for backup tabs. It can automatic backup periodically and works well with TST.

**Comment by piroor** [comment]
Implemented by recent commits.

**Comment by lycsjm** [comment]
I open 14 new tabs, auto grouping by TST(Firefox open warning dialog if I want to close window), and then collapse this tree then middle click to close tree, but no warning appear.

I am sure option in TST is clicked, so what did i miss?

**Comment by piroor** [comment]
@lycsjm  Hmm, middle-click on a collapsed tree in the sidebar shows warning for me...

**Comment by lycsjm** [comment]
@piroor I left only one window, close others, and then toggle the option again,  it works now.

**Comment by jonhermansen** [comment]
I'm not sure if this is related, but the "Close Other Tabs" context menu item doesn't always close all other tabs. It has been like this for a few weeks. Running 2.4.16

**Comment by piroor** [comment]
I close this because outdated.
