### ISSUE TITLE
How to open indepedent tabs when setting - open new tab as child is on

### ISSUE THREAD

**Issue by sushovannits** [piroor/treestyletab#1757]
## Short description
How to still open independent tabs when open new tab as child tabs is on in Mac
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Enable open new tab as child of current tab
 4. How to still open independent tabs

## Expected result
How to open independent tabs when the setting "Open new tab as child tabs" is on.

## Actual result
Open an independent tab

## Environment

 * Platform (OS): Mac
 * Version of Firefox: 57.0.4
 * Version (or revision) of Tree Style Tab: 2.4.8

**Comment by piroor** [comment]
You can set different behavior for simple left-click and middle-click (or ctrl-click) on the "New Tab" button. Did you try that?

**Comment by sushovannits** [comment]
@piroor I am not sure how to do that exactly. I tried doing it in the settings of TreeStyle Tab addon as shown in the snapshot attached. However this setting does not produce the desired behavior. 
<img width="1033" alt="screen shot 2018-02-12 at 9 56 09 am" src="https://user-images.githubusercontent.com/5388540/36083680-17344cf2-0fdb-11e8-927f-0b6632fe72d4.png">

**Comment by sushovannits** [comment]
When I long press the new tab button in TST pane, the sibling tab, etc works but open as independent tab does not

**Comment by piroor** [comment]
@sushovannits Thanks, it is a bug and the commit a59d978 should fix it.

**Comment by piroor** [comment]
I close this because outdated.
