### ISSUE TITLE
[FR] Send Tree to Device

### ISSUE THREAD

**Issue by efermi** [piroor/treestyletab#1760]
It would be great to have the ability to send and receive trees of tabs between devices using Firefox's tab sending mechanism.

**Comment by piroor** [comment]
Currently it is impossible to implement due to missing WebExtensions API for the feature. See also: [1417183 - Provide a way to send pages between devices](https://bugzilla.mozilla.org/show_bug.cgi?id=1417183)

**Comment by irvinm** [comment]
Firefox can send individual tabs (at a minimum) between devices using "Send Tab to device" built into Firefox, but I still don't think there is a way to do this via Web Extensions.  Given the easy way to do individual tabs directly in Firefox and that there hasn't been any progress on adding this functionality for addons, I think this should be closed.  @piroor

**Comment by piroor** [comment]
I'm positive to support this feature ASAP after the API is introduced (because I'm using it via Firefox's native tab bar now), so I want to keep this as open as a reminder.

**Comment by irvinm** [comment]
Sounds good.  Thanks for the update @piroor.

**Comment by piroor** [comment]
TST 3.6.0 and later now contains a simulated feature based on the sync storage. Its behavior is different from Firefox's native one - very limited data size, non-realtime transferring (you may need to run "sync" manually if you want to transfer tabs immediately), and impossible to send tabs to devices without TST (so Android Firefox cannot become a recipient).

**Comment by irvinm** [comment]
@piroor given they have marked this item as "WONTFIX", should we just close this item?  It is unfortunate.

**Comment by piroor** [comment]
OK, I close this because Firefox's bug is already closed as WONTFIX.
