### ISSUE TITLE
Accept group tabs from another session

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#1762]
## Short description
When a session file is restored in a different Firefox Profile then it was made with all the group tabs have the wrong address and while their title is loaded correctly they still show the default icon and their page doesn't load so you can't change their title or change their `temporary` status. This is a problem since it makes it harder to migrate sessions and to restore backup sessions. 

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a number of group tabs. Use the URL `about:treestyletab-group` or open new tabs quickly (hold `ctrl+t`).
 4. Close Firefox.
 5. Open the Firefox profile's directory and copy `sessionstore.jsonlz4`.
 6. Create a another new clean Firefox profile.
 7. Paste the `sessionstore.jsonlz4` file to the new profile's directory.
 8. Start Firefox with the new profile.
 9. Install TST.
 10. Restore the previous session using the hamburger menu.

## Expected result
The group tabs should load correctly in the new Firefox profile.

## Actual result
The group tabs that were migrated from a different Firefox profile doesn't have the same address as new group tabs and therefore don't load the correct page. They also don't show their icons correctly.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 58
 * Version (or revision) of Tree Style Tab: 2.4.8

**Comment by piroor** [comment]
This is caused by the UUID part in the URL which is generated for each installation. Currently it is impossible to provide custom `about:` URI by WebExtensions addons, so instead I need to use custom protocol like `treestyletab-internal://...`.
Possible related bug: [1271553 - Add ability to implement programmable custom protocol handler](https://bugzilla.mozilla.org/show_bug.cgi?id=1271553)

**Comment by Lej77** [comment]
@piroor Couldn't you redirect the page when they are loaded to the correct page by parsing their URL?

**Comment by piroor** [comment]
Does "parsing their URL" mean that conversion from an UUID-based URL (like `moz-extension://a93cdbe2-b549-401c-ad50-56572822cee3/resources/group-tab.html`) to another (like `moz-extension://3323cb07-bd1c-4a23-927f-1aee150aa5bf/resources/group-tab.html`) based on their common part `/resources/group-tab.html`? Then I think I should not do that because it can detect URL for another different addon wrongly. (Of course it is very low possibility, but I'm still worrying...)

**Comment by piroor** [comment]
Ah, now I have another idea. Detecting group tab based on session information stored by `browser.sessions.setTabValue()` instead of tab's actual URL will work for this case, because `sessionstore.jsonlz4` contains complete session information.

**Comment by Lej77** [comment]
@piroor That would be a good workaround. When tabs are copied using MTH could you change group-tab URLs to about:treestyletab-group URLs since they can be used by different sessions?

**Comment by Lej77** [comment]
@piroor Conversion from an UUID-based URL to another was what I had in mind to begin with. Your right that another extension could have the same address but it seems quite unlikely especially if there is the `?temporary=false&title=Group` info in the URL as well. Maybe use the confirmation box you made for closing multiple tabs to confirm that the tab is a group tab. Anyways this is probably not needed since you alternative solution should be good enough for most cases.

**Comment by piroor** [comment]
The idea https://github.com/piroor/treestyletab/issues/1762#issuecomment-363641750 has been implemented by f7b67af.

**Comment by piroor** [comment]
After some more fixes I've confirmed that group tabs are correctly migrated when sessionstore.jsonlz4 is imported.

**Comment by piroor** [comment]
And there are some more things I've realized:

 * If imported group tab is reloaded before migration, it becomes to `about:blank` tab and information stored in its URL is lost.
 * Custom protocol for TST does not help us. Currently impossible to use a [custom protocol](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/protocol_handlers) for a purpose like this. Protocol handler must be an website. ( https://bugzilla.mozilla.org/show_bug.cgi?id=1271553 )

**Comment by Lej77** [comment]
I test TST 2.4.9 and group tabs are now migrated when a sessionstore file is copied to a new Firefox profile folder. Thank you for fixing this!
