### ISSUE TITLE
Poor performance when using drag and drop for tabs

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#1763]
## Short description
When using drag and drop for tabs in windows with a couple of hundred tabs the Sidebar start to lag. It can make a task that should take a few seconds take half a minute because I have to wait for the Sidebar to catch up with my mouse. This is even more of a problem when I need to scroll the Sidebar while dragging the tab since it becomes easy to scroll too far. Any improvements to the drag and drop performance would be appreciated.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open about 400 tabs. (They can be in unloaded state. Close and reopen Firefox then restore last session to get unloaded tabs. You can also use an extension like [Tab Unloader (WebExtension) by Afnan Khan](https://addons.mozilla.org/firefox/addon/tab-unloader-we) though they don't seem to work very well on Firefox 58.)
 4. Click a tab and start dragging it around the sidebar.

## Expected result
The sidebar should be responsive and quickly show a marker for where the tab will end up when dropped.

## Actual result
The Sidebar starts to lag and the drop marker can take several seconds to catch up to the mouse.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 58
 * Version (or revision) of Tree Style Tab: 2.4.8

**Comment by piroor** [comment]
I've tested with 400 tabs prepared with a script:

```
for (let i = 0; i < 400; i++) gBrowser.addTab(`about:blank?index=${i}`);
```

but tab-dragging isn't lagged, and dragover-tabs are highlighted immediately for me. Tested environment is:

 * Windows 10
   * CPU: i3-7100 3.90GHz
   * RAM: 8GB
 * Nightly 60.0a1
 * TST latest development build

**Comment by Lej77** [comment]
@piroor It seems to be worst when hovering tabs in the end of the list so moving the mouse (while dragging a tab) over tabs with high indexes cause more lag. Also if you don't notice it with 400 tabs could you try with 800 and see if you notice it then?

**Comment by piroor** [comment]
The performance profile with 1200+ tabs says that `getNextVisibleTab()` is called 1455 times from `getDropActionInternal()` and takes 23.45% of the CPU time. Hmm...

**Comment by piroor** [comment]
```
function getNextVisibleTab(aTab) { // visible, not-collapsed
  if (!ensureLivingTab(aTab))
    return null;
  assertValidHint(aTab);
  return document.querySelector(`#${aTab.id} ~ ${kSELECTOR_VISIBLE_TAB}`);
}
```

I cannot imagine how optimize this function...

**Comment by Lej77** [comment]
@piroor Can't you minimize the amount of times the function is called? For example by using the last target tab as a reference point and the using `getNextVisibleTab` and another function to go in the opposite direction `getPreviousVisibleTab`.

**Comment by piroor** [comment]
I've found one needless method call, and b8a0538 reduces it. Here is the call tree on my another PC (16GB RAM, other conditions are same to previous):
![image](https://user-images.githubusercontent.com/70062/35975397-f2ab4ea2-0d1f-11e8-8ffd-ab4cb26f8d0c.png)
This says that 85% CPU time is used to invoke drag session and dispatch event. From the result I think that basically Firefox is not designed to operate such too many tabs...

**Comment by Lej77** [comment]
@piroor I think your monitored the performance of the wrong page. It show the frame rate as nearly 60fps and while this is true for the grayed out tab under the mouse its definitely not true for the sidebar page, that is to say the drop marker and any scrolling done by dragging the mouse close to the top or bottom of the Sidebar. I think i got more accurate results by performance monitoring using the `about:debugging#addons` page to open a debugger for TST and then selecting the `sidebar.html` page.

Here is the performance monitoring for background.html while dragging a tab:
![background page](https://user-images.githubusercontent.com/31554212/35989473-831accd4-0d01-11e8-9dc8-ba85276ad972.png)

Here is the performance monitoring for sidebar.html while dragging a tab:
![sidebar page](https://user-images.githubusercontent.com/31554212/35989476-848f2e84-0d01-11e8-9aec-0fce8d04e464.png)
Note the low FPS values.

Also it should be possible for the Sidebar to be responsive with this many tabs since the extension [Tab Center Redux by Edouard Oger](https://addons.mozilla.org/firefox/addon/tab-center-redux/) is very responsive even with a 1000 tabs. That is to say it will smoothly scroll when dragging a tab and the mouse gets close to the top or bottom. Of course this extensions is quite simple compared to TST but it shows that at least a simple Sidebar can handle this many tabs. Firefox's tab bar also seems to handle drag and drop with many tabs without any problems.

**Comment by piroor** [comment]
I couldn't reduce function call for `getNextVisibleTab()` but finally I realized that CSS3 `~` selector is too slow for this purpose. After some optimizations, the performance became better for me.

**Comment by Lej77** [comment]
@piroor I Tested TST 2.4.11 and the performance is definitely better! Still I had some more thoughts about possible performance improvements if you have the time.

-------------------------

### Tests with new clean profile (800 tabs)

Dragging tab in the beginning of the tab list:
![tst 2 4 11 - beginning of tab list](https://user-images.githubusercontent.com/31554212/36005799-a6f54908-0d39-11e8-8989-96083e10632d.png)

![tst 2 4 11 - beginning of tab list - waterfall](https://user-images.githubusercontent.com/31554212/36006024-e165e4b6-0d3a-11e8-8060-a1ed9816ffd1.png)


Dragging tab at the end of the tab list:
![tst 2 4 11 - end of tab list](https://user-images.githubusercontent.com/31554212/36005802-a90b9d46-0d39-11e8-8933-29fe2567eee5.png)

![tst 2 4 11 - end of tab list - waterfall](https://user-images.githubusercontent.com/31554212/36006027-e52c5ef4-0d3a-11e8-8453-1001836cdba5.png)

------------------------

### Tests with my current profile (400 tabs in testing window. 2400 tabs in total)

Dragging at the end of the tab list:
![tst 2 4 11 - my session 2](https://user-images.githubusercontent.com/31554212/36005848-edc08fe6-0d39-11e8-8c5d-442ef3f7dae0.png)

![tst 2 4 11 - my session 2 - waterfall](https://user-images.githubusercontent.com/31554212/36005857-ffb5865c-0d39-11e8-87ff-65e3931b5dc2.png)

-------------------

From this info it seems that in the cases with worst performance, that is to say when a tab is being dragged at the end of the list, then the worst java script functions are the `getTabById` and `clearDropPosition` functions. 

```JavaScript
function getTabById(aIdOrInfo) {
  if (!aIdOrInfo)
    return null;
  var selector;
  if (typeof aIdOrInfo == 'string')
    selector = `${kSELECTOR_LIVE_TAB}#${aIdOrInfo}`;
  else if (typeof aIdOrInfo == 'number')
    selector = `${kSELECTOR_LIVE_TAB}[${kAPI_TAB_ID}="${aIdOrInfo}"]`;
  else if (!aIdOrInfo.window)
    selector = `${kSELECTOR_LIVE_TAB}[${kAPI_TAB_ID}="${aIdOrInfo.tab}"]`;
  else
    selector = `${kSELECTOR_LIVE_TAB}#tab-${aIdOrInfo.window}-${aIdOrInfo.tab}`;
  const tab = document.querySelector(selector);
  if (tab)
    return tab;
  if (typeof aIdOrInfo == 'string')
    return getTabByUniqueId(aIdOrInfo);
  return null;
}
```
```JavaScript
function clearDropPosition() {
  for (let tab of document.querySelectorAll(`[${kDROP_POSITION}]`)) {
    tab.removeAttribute(kDROP_POSITION)
  }
}
```

Both these functions use the `document.querySelector` function so there might be some performance gains to be had by using some other method instead.

Except for those functions most of the CPU seems to be used for layout computations. By comparing my session to the clean profile it also seems like larger sessions will have more of its CPU usage in this area. Unfortunately I can't think of any easy way for further optimization in this area so it will probably have to remain as it is. 

Also I was wondering why the performance gets so much worse when the drop marker needs to move several tabs in one frame. If I move my mouse quickly up and down the Sidebar it can make the whole sidebar freeze for several seconds. During the time that the Sidebar is frozen the drop marker isn't updated at all which seems strange. I suppose this behavior is because the CPU usage is too high. If that is the case then it would be better to decrease the drop marker's CPU usage so that the Sidebar is still responsive. This would also be helpful for when the user is trying to scroll the sidebar while dragging a tab by moving the mouse close to the top or bottom of the Sidebar.

What I mean to say is why the update rate for the drop marker is slower when it is being moved quickly. If most of the performance issues comes from recalculating the layout then it doesn't make much sense that the number of calculated drop maker positions is lower when the mouse is moved quickly. If the layout could be calculated fast enough to draw 5 different drop maker positions per second while moving the mouse slowly why can't it draw 5 drop marker positions when the mouse is moved quickly?

It would also be good if the Sidebar could be kept more responsive for when the user is trying to scroll the sidebar while dragging a tab by moving the mouse close to the top or bottom of the Sidebar.

**Comment by piroor** [comment]
Thank you for the suggestion and investigation. I introduced some more optimization around `dragover` event listener. Function call for `document.querySelector()` and `clearDropPosition()` are little reduced.

**Comment by Lej77** [comment]
@piroor I was right! The sidebar can be very responsive with a simple fix. Firefox prioritizes java script computations over drawing the page so when the java script uses to much CPU Firefox will simply stop drawing the page and give all CPU power to the script. That is to say instead of drawing the page a java script function is called immediately when there is CPU time over. The javascript functions that are called by the page is the `onDragOver`, `onDragEnter` and `onDragLeave` functions. So to prevent these from using all the CPU time and allow the page to draw itself I wrote the following code:

```JavaScript
let isSleeping = false;
let workStartTime = null;
const maxSleepTime = 200;
const sleepComparedToWork = 0.5;

async function delay(timeInMilliseconds) {
  return await new Promise((resolve, reject) => setTimeout(resolve, timeInMilliseconds));
}
function getCurrentTime() {
  return performance.now ||
  performance.mozNow     ||        
  Date.now;  /*none found - fallback to browser default */
}
function checkIfSleeping() {
  if (isSleeping)
    return true;

  if (workStartTime || workStartTime === 0) {
    let workDuration = getCurrentTime() - workStartTime;
    let sleepDuration = workDuration * sleepComparedToWork;
    
    if (sleepDuration > maxSleepTime)
      sleepDuration = maxSleepTime;

    isSleeping = true;
    delay(sleepDuration).then(() => {
      isSleeping = false;
    });
  }
  workStartTime = getCurrentTime;
  return false;
}
```

Then I called the `checkIfSleeping` function before doing anything in the event listener function and if the function returned true then I simply returned the event listener without doing anything. Like this:

```JavaScript
function onDragEnter(aEvent) {
  if (checkIfSleeping())
    return;
  ...
```

```JavaScript
function onDragLeave(aEvent) {
  if (checkIfSleeping())
    return;
  ...
```

```JavaScript
function onDragOver(aEvent) {
  if (checkIfSleeping())
    return;
  ...
```

With this done I did some performance testing in the same clean Profile as last time, the one with 800 tabs. This was the result:

![tst 2 4 11 modified - end of tab list](https://user-images.githubusercontent.com/31554212/36022866-e528db62-0d8a-11e8-9c9e-a134dc2850eb.png)
Min FPS is now 11 instead of 1 and the sidebar feels very responsive!

**Comment by piroor** [comment]
Hmm, I think I should not throttle handling of dragenter and dragleave, because they are used to detect where the the cursor is: inside or outside of the sidebar. If I don't handle all of fired events, TST may misditect where the cursor is.

On the other hand, dragover is used to two purposes: 1) detection of three possible positions - before the tab, on the tab, or after the tab. 2) overriding dropEffect (link/copy/move/none). Because dragover is fired repeatedly while dragging, I can safely drop too many frames. My recent commits now dragover events are processed on every 50msec, but you can enlarge the minimum interval to 200msec or more via an internal configuration `minimumIntervalToProcessDragoverEvent`.

**Comment by Lej77** [comment]
I tested TST v2.4.11.6578 and it seems very smooth even with 1600 tabs open in one window so I think the performance is very good! I don't think it needs to be optimized any more really, it should be good enough for all reasonable scenarios. Thank you for all your work in fixing this issue!
