### ISSUE TITLE
Middle click on reload button ignores config and duplicates tab as child always

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#1764]
## Short description
When a tab is duplicated by middle clicking the reload button the new tab is supposed to follow the `For middle click on the "Reload" button, duplicate the tab as` option in TST settings' page. Instead the new tab is always opened as a child tab of the duplicated tab.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Middle click the "Reload" button.

## Expected result
The new duplicated tab should be positioned as the next sibling of the current tab with the default TST configuration. 

## Actual result
The new duplicated tab becomes a child tab of the selected tab. Also while the new tab is selected the it will be hidden if it was the first child tab of the selected tab.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 58
 * Version (or revision) of Tree Style Tab: 2.4.8 and 2.4.8.6511

**Comment by piroor** [comment]
I've realized that what's happen on this situation:

 * In the background page, the duplicated tab is a next sibling tab of the source.
   1. Attached to the source as a new tab. (This operation is broadcasted to the sidebar page.)
   2. Detached from the source as a duplicated tab. (This operation is broadcasted to the sidebar page.)
 * In the sidebar page, the duplicated tab is a child tab of the source.
   1. Observes the broadcasted "attach to source" operation, and start to wait until both the source and the duplicated tabs are tracked. (X)
   2. Observes the broadcasted "detach from source" operation, and start to wait until the duplicated tab is tracked. (Y)
   3. The pending operation Y is continued. The duplicated tab is detached from current parent, but it is not attached to any tab yet.
   4. The pending operation X is continued. The duplicated tab is attached to the source.

So I've introduced a mechanism to process these pending operations in correct order, by the commit e9862755ea689d3b3949c620453e2bd85083932d. I think it should solve this problem.

**Comment by Lej77** [comment]
@piroor I tested TST 2.4.8.6528 and this issue seems to be fixed. I tested all the positions for the duplicated tab and they were all positioned correctly. But when I duplicated the tab as an independent tab the Sidebar didn't scroll to the duplicated tab when it was opened even though this worked fine for all the other options.

**Comment by Lej77** [comment]
Tested TST 2.4.9 and the scrolling issue seems to be fixed as well!
