### ISSUE TITLE
Wrong tab selected after closing "print preview"

### ISSUE THREAD

**Issue by kkotenko** [piroor/treestyletab#1766]
## Short description
When using and closing the "print preview" feature of Firefox, the tab selected afterwards is the last child of the previously selected tab.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a tab A.
 4. As child of A, open a tab B 
5. As child of B, open a tab C.
6. As child of A, open a tab D.
7. Open tab E.

This creates the following structure:
A
\-B
\--C
\-D
E

8. Set tab A to active.
9. Press Alt on the keyboard.
10. Select File -> "Print preview" from the menu.
11. Close the print preview with the "close" button (or by pressing Esc key).

## Expected result
The previously selected tab A is selected.

## Actual result
Tab D is selected. 

It seems this is always the last direct child (not descendant) of the originally selected tab.

If you switch B and D
A
\-D
\-B
\--C
E

the erroneously selected tab is B. So it does not depend on the chronological order of opening the tabs.

## Environment

 * Platform (OS): Debian GNU/Linux 9.3 (stretch)
 * Version of Firefox: 52.6.0 (64-bit)
 * Version (or revision) of Tree Style Tab: 0.19.2017090601

**Comment by piroor** [comment]
This doesn't happen on TST 2.4.9 for me.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
