### ISSUE TITLE
v2.4.11 Breaks Additional Context Menu Items

### ISSUE THREAD

**Issue by cipri-tom** [piroor/treestyletab#1769]
## Short description
The additional Context Menu Items are not shown after update to version 2.4.11

## Steps to reproduce

 1. Start Firefox with clean profile. (btw, I suggest you update the issue template to give indication on how to start such Firefox: `firefox -new-instance -P "Another Profile"` from [here](https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options)
 2. Install TST.
 3. Open some tree of tabs
 4. Try to right-click on root and select 'Close tree'. 

## Expected result
With the default configuration, there is should be a Close Tree option

## Actual result
There seem to be some option, but without text

## Environment

 * Platform (OS): MacOS High Sierra
 * Version of Firefox: 58.0.1
 * Version (or revision) of Tree Style Tab: 2.4.11

**Comment by piroor** [comment]
Thanks, 75bcf48 should fix this.

**Comment by cipri-tom** [comment]
Thank you ! 

I don't use this too often, it just so happened that I needed it today, right after the update (well, it's Friday, time to cleanup the week haha). So, I'll wait till it makes it to the store version.

Thank you for fast response !
