### ISSUE TITLE
Changing tabs causes TST's scroll position to jump

### ISSUE THREAD

**Issue by cemerick** [piroor/treestyletab#1770]
## Short description

Each tab focus change (whether by clicking a tab or closing one) causes the scroll position of TST's tab tree to jump up such that the newly-focused tab is _always_ out of view.

Example:
![untitled project](https://user-images.githubusercontent.com/47489/36028586-9cc78070-0d6d-11e8-8cc3-fd5ee297218b.gif)

## Steps to reproduce

_Not_ reproduceable. Opening a large number of tabs in a new profile and clicking around yields expected (good) behaviour. I'm filing this entirely as a question:

**What in my profile could possibly cause this kind of bizarre scrolling behaviour?**  The rest of the browser is operating as expected.

(Thank you very much for all of your work on this project. 😄 )

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 58.0.2
 * Version (or revision) of Tree Style Tab: 2.4.12

**Comment by rickthepick** [comment]
I am experiencing something like this also.  I have two windows both with dozens of tabs.  One of them behaves normally.  The other behaves like this: whenever you click on a tab it scrolls all the way up to the first tab.  This is very annoying when you have lots of tabs.
MacOS, Tree Style Tab 2.4.17, FF 58.0.2

**Comment by Aymkdn** [comment]
Same problem here. It will eventually work properly after closing/reopening Firefox several times. Difficult to say what's going on and how to fix it....

**Comment by piroor** [comment]
This problem will happen when collapsed/expanded state of tabs are mis-detected. TST calculates the destination scroll position based on tabs detected as "expanded" (aka "visible"). However, by some reasons, collapsed state of tabs can be mismatched between the sidebar contents and the background (invisible) page.

**Comment by rickthepick** [comment]
Thanks very much @Aymkdn for sharing your workaround.  It seems to work!  I am now able to use TST without frustration :-)

**Comment by piroor** [comment]
Anyway, the commit ae03533 should reduce frequency of happening this problem.

**Comment by irvinm** [comment]
@cemerick are you still having issues?  If not, can you close this?

**Comment by cemerick** [comment]
No, this seems settled, closing.
