### ISSUE TITLE
No LICENSE or COPYING file at root of git repository

### ISSUE THREAD

**Issue by Nick-OpusVL** [piroor/treestyletab#1771]
I don't know what the license is for this addon.  I picked a file at random and it looks like it's MPL/GPL/LGPL

Could you please add a LICENSE or COPYING file at the root of the directory containing the full text of the correct license for the overall addon?

**Comment by Nick-OpusVL** [comment]
the COPYING file should really contain the full license text of the whole project's license.  So for example if the project is GPLv2 it should contain the full text of the GPLv2.

See https://www.gnu.org/licenses/gpl-howto.html

**Comment by irvinm** [comment]
@piroor I didn't look thru a lot of the files, but I think you have this requirement covered by the "COPYING.txt" and the license information in the files.  I think you can close this.

**Comment by piroor** [comment]
I've clearly select MPL1.1 for modules copied from the legacy version. Now all files are licensed under MPL1.1, MPL2.0, or other per-file non-copyleft licenses.
