### ISSUE TITLE
「以前のセッションを復元」しても、タブの階層構造がリセットされる

### ISSUE THREAD

**Issue by 888kk** [piroor/treestyletab#1772]
## Short description
ver58.0.2でツリー型タブ2.4.12を使用すると、
「以前のセッションを復元する」でタブを復元しても、
タブの階層構造が復元されず、全てのタブが親タブになってしまう。

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. いくつかタブを作成し、親タブ－子タブのツリー構造を作りfirefoxを終了。
 4.firefoxを立ち上げ、「以前のセッションを復元」からタブを復元させると、
ツリー構造にしたはずのタブが全て親タブになっている。 

## Expected result
ツリー構造も含め、終了時のタブの状態が正常に復元できるようになる。

## Actual result
ツリー構造が保存されておらず、全てのタブが親タブの状態で復元される。

## Environment

 * Platform (OS): windows7 ultimate x64
 * Version of Firefox: 58.0.2
 * Version (or revision) of Tree Style Tab: 2.4.12

**Comment by piroor** [comment]
ご指摘ありがとうございます。最適化の過程で引数の型を色々直したときの直し忘れのせいでした……早急に修正版を出そうと思います。
