### ISSUE TITLE
please update/have a newish theme for the website 

### ISSUE THREAD

**Issue by shirishag75** [piroor/treestyletab#1774]
http://piro.sakura.ne.jp/xul/_treestyletab.html is just too old. Please update the website with new info. and possible with somewhat of a better theme/styling. It is just **too boring**

**Comment by irvinm** [comment]
@piroor please close this.

**Comment by piroor** [comment]
I've updated the page a little. Sadly I cannot spent more time to maintain multiple mirrored contents, so I've decided to keep pages under my website as archived for old versions and added links to the latest information.
