### ISSUE TITLE
"Bookmark all Tabs" in TST context menu not working

### ISSUE THREAD

**Issue by HifeFish** [piroor/treestyletab#1775]
## Short description
Clicking "Bookmark all Tabs" in the Tree Style Tab context menu has no effect.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Choose "Bookmark all tabs" from the Tree Style Tab context menu.

## Expected result

A folder with bookmarks for all open tabs is created.

## Actual result

Nothing happens (as far as I can observe). The menu stays open until you select another option or click elsewhere. No bookmarks are created.

The option in the normal Tab context menu works normally.
Giving TST permissions to create bookmarks doesn't affect the issue.
The number or tree structure of open tabs doesn't affect the issue, as far as I have tested.
The position of the right-clicked on tab does not affect the issue.

## Personal remark

In my opinion this option belongs into Firefox's main bookmark menu, as it is not related to one specific tab. I don't know whether it is possible for an addon to do that or how to report this to mozilla. I have submitted it to https://qsurvey.mozilla.com/s3/FirefoxInput/ but I doubt that will have any effect.

## Environment

 * Platform (OS): Ubuntu 16.04 64bit
 * Version of Firefox: 58.0.1 (64-Bit)
 * Version (or revision) of Tree Style Tab: 2.4.14

**Comment by piroor** [comment]
Thanks, this is a regression in recent versions of TST itself.  The commit 191a3a7 should fix this.
