### ISSUE TITLE
Reload this tree

### ISSUE THREAD

**Issue by Tragen** [piroor/treestyletab#1776]
Please bring back the context menu entry to reload only a tree and not all tabs in a window.
I have hundred of tabs open but only want to reload the 50 in one subtree and it's not
possible.

Thanks.

**Comment by piroor** [comment]
There were missing menu labels for context menu item added by TST, at an old version. Could you update TST?

**Comment by Tragen** [comment]
Wow. Very fast. I updated the version and it's there now and working. 💯 👍
