### ISSUE TITLE
Tabs are pinned automatically

### ISSUE THREAD

**Issue by saipsa** [piroor/treestyletab#1779]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Pin any tab
 4. Open other tabs. While interacting, the tabs are pinned automatically

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
This doesn't happen on my environment. Any other condition to reproduce?

**Comment by piroor** [comment]
I close this because outdated.
