### ISSUE TITLE
このツリーを閉じる・このタブの配下のタブをすべて閉じるが動作しない

### ISSUE THREAD

**Issue by array** [piroor/treestyletab#1781]
## Short description
ツリー型タブ　2.4.15
このツリーを閉じる・このタブの配下のタブをすべて閉じるが動作しない
## Steps to reproduce
Firefox beta（59.0 b8）での実施
 1. Start Firefox with clean profile.
 2. Install TST.
 3. 新しくタブを開く
 4. リンクでタブを開き子ツリーができることは確認できる
 5.このツリーを閉じる・このタブの配下のタブをすべて閉じるが動作しない
 6.ツリーをすべてたたむ・展開するは動作する。

## Expected result
コンテキストメニューの「このツリーを閉じる」でツリーが閉じる
コンテキストメニューの「このタブの配下のタブをすべて閉じる」でタブが閉じる

## Actual result
どちらも動作しない。

## Environment

 * Platform (OS): Windows10 64bit
 * Version of Firefox: Firefox Beta 59.0 b8
 * Version (or revision) of Tree Style Tab: 
2.4.15

この前のバージョンでは動いていました。

**Comment by piroor** [comment]
ご指摘ありがとうございます、実装を移動したときの修正漏れでした……
