### ISSUE TITLE
[feature] Add right-click menu item to change selected tab to a different container

### ISSUE THREAD

**Issue by Jiehong** [piroor/treestyletab#1785]
Hello,

## Short description
When right-clicking on a tab, it would be nice to have a menu to change the container into which this tab belongs.

No reproduction steps, as this is a feature request.

**Comment by piroor** [comment]
Sorry but there is no plan to add the menu by TST itself. I don't want to add features unrelated to "tree of tabs". It should be provided by another addon which is developed to manage container tabs.

**Comment by Jiehong** [comment]
Sure, I understand. Thanks anyway for TST :)

**Comment by piroor** [comment]
Now there is a built-in (emulated) context menu item "Reopen in Container", and the context menu is now compatible with other addons which provides such a context menu commands.
