### ISSUE TITLE
Changes to storage.js not applied

### ISSUE THREAD

**Issue by chisui** [piroor/treestyletab#1787]
## Short description

I would like to be able to manage my custom styles and preferences in a file rather than a textarea on the preferences Tab.

There seems to exist a file that contains all relevant information at:

    /<profileDir>/browser-extension-data/treestyletab@piro.sakura.ne.jp/storage.js

Unfortunately changes to this file aren't reflected in the plugin itself. Is there a way to force TST to reload preferences from this file, am I looking at the wrong file or is this simply not possible?

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. close Firefox.
 4. change `storage.js` file.
 5. start Firefox.

## Expected result

Changes to preferences are applied.

## Actual result

Preferences did not change.

## Environment

 * Platform (OS): linux(NixOS)
 * Version of Firefox: 57.0.4 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.4.16

**Comment by piroor** [comment]
If you use the Firefox Sync, changes are possibly overwritten with last values loaded from the sync server. Values from the sync server are cached to the file `storage-sync.sqlite`, and it is used when Firefox couldn't connect to the sync server.

**Comment by piroor** [comment]
Anyway the file is not designed to be modified by your hand...

**Comment by chisui** [comment]
Is there another way of externalizing preferences that plays more nicely with firefox?

**Comment by piroor** [comment]
Sadly there is no such way. WebExtensions-based addons are isolated from Firefox's old preferences systems except [browserSettings API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserSettings).

**Comment by chisui** [comment]
Thank you anyway. I will try to hack something together nontheless.

**Comment by overdodactyl** [comment]
@chisui, I'm not sure if it helps, but you can use `@import` statements in the section you add your custom css.  For example if you host the file containing your css tweaks on a GitHub gist or something similar, you could use something to the effect of:

```css
@import url("https://rawgit.com/overdodactyl/ShadowFox/master/webextensions/treestyletabs.css");
```

**Comment by chisui** [comment]
@overdodactyl, I will experiment with that. although I would like the resource to be local.

**Comment by piroor** [comment]
I close this because outdated.
