### ISSUE TITLE
Arrange the configuration page by tabs

### ISSUE THREAD

**Issue by rabin-io** [piroor/treestyletab#1789]
Not a bug, just a small future request, can you please arrange/split the config page by tabs, so that there is less to scroll.

**Comment by irvinm** [comment]
@piroor I would vote to close this.  While I don't disagree with @rabin-io's rationale, I am not sure the work involved to make this change is something you would want to do.  (Else you would have already done it :)

**Comment by piroor** [comment]
I agree that TST's options page has too much options. So currently there are foldable sections. Both such foldable UI and switchables with tabs have each pros and cons. As a design decision I chose the current style, so switchable UI won't be implemented by me, sorry.
