### ISSUE TITLE
[Feature request] Mac/Windows CSS class for No Decoration theme

### ISSUE THREAD

**Issue by jvzr** [piroor/treestyletab#1792]
It appears that "Extra style rules for sidebar contents" is syncing across installs now (not sure when it started, but it's nice!)

<img width="105" alt="image" src="https://user-images.githubusercontent.com/445151/36195492-e8d0d4f4-116d-11e8-8a75-1fc764dce884.png">

However, this means that some rules that look good on Mac are looking wonky on Windows (mostly because of fonts' varying baseline and symbols size). In the example above, the X symbol looks completely different on Windows (way skinnier and larger) and the twisty is half a centimeter to the right. It's a simple font size fix but I cannot target Mac/Windows specifically.

Would it be possible for TST to add a simple ".mac" and ".windows" class to the sidebar when the "No Decoration" theme is selected?

I tried looking into Firefox's own classes at the browser level, but unless I target the two specific display resolutions of my two setups, I haven't found a way to target one over the other.

I'd be happy to give more details if need be. Thanks again for the amazing work! Love the extension to death, and it's practically the main reason that made me come back to Firefox!

**Comment by jvzr** [comment]
@piroor Awesome, thank you! Didn't know about those. I've made a change and added a -moz-os-version: windows-win10 media query to my styles. I'm on the Mac now but I'll test tonight and report. From my quick testing, it doesn't seem to be working but it might simply me not using them correctly. Again, will report!

**Comment by piroor** [comment]
Hmm, you are right. Those Gecko specific features seem not available on non-privileged contents including resources in addons. https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-moz-os-version says:

> Note: Since Firefox 58, this media feature is no longer available to web content — it is only available internally (e.g. to XUL / chrome code). See bug 1396066 for more details.

Thus, I've expose the value of `navigator.userAgent` as an attribute value of the root element by the commit 44b30ed. Examples:

```css
/* Windows 10 */
:root[data-user-agent*="Windows NT 10"] * {
  color: blue !important;
}

/* Linux */
:root[data-user-agent*="Linux"] * {
  color: red !important;
}
```

**Comment by jvzr** [comment]
@piroor absolutely brilliant! Will report back when the change hits my version

**Comment by jvzr** [comment]
Thank you @piroor, it's fixed!
