### ISSUE TITLE
[doc] events are not well-documented

### ISSUE THREAD

**Issue by ariasuni** [piroor/treestyletab#1793]
I used the API to create [Tab flip](https://addons.mozilla.org/android/addon/tab-flip-for-tree-style-tab/). However, I would like to be able to trigger my action only if I did a single click.

Right now, it’s triggered as soon as I click (the only moment I’m notified of a click), disrupting the user when re-ordering tabs for example.

I would like to be able to react on simple click, so that the user is still able to long-click and move their tabs.

Edit:

Some user pointed to https://framagit.org/ariasuni/tst-tabflip/issues/1#note_188708 so I guess that’s rather a lack of documentation than a feature request.

**Comment by irvinm** [comment]
@ariasuni can you review https://github.com/piroor/treestyletab/wiki/API-for-other-addons to see if this fits your needs?  If so, can you close out this issue?

**Comment by ariasuni** [comment]
I think it’s good, at least for me.
