### ISSUE TITLE
[feature request] Disable context menu

### ISSUE THREAD

**Issue by net** [piroor/treestyletab#1797]
Until native context menus are supported, an option to disable the existing context menu would be nice.

**Comment by net** [comment]
Perhaps an expand/close node action could optionally be taken on right click instead.

**Comment by piroor** [comment]
Hmm, I misunderstood that the point of this issue. I thought that it should be disabled for a future version of Firefox which provides ability to use native tab context menu on the sidebar, so I agree to add the option just for the future. On the other hand your point is providing different feature for right-click on the sidebar...

**Comment by net** [comment]
@piroor You're right. Just thought I'd toss in an alternative use for right click. :)

Thanks for the patch, that was fast!
