### ISSUE TITLE
ctrl+tab switches child tabs in incorrect order after I closed and reopened (ctrl+shift+t) root tab

### ISSUE THREAD

**Issue by fadimko** [piroor/treestyletab#1799]
## Short description
Child tabs are swithed in incorrect order with ctrl+tab after I closed and reopened (ctrl+shift+t) root tab

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a new tab.
 4. Make 4+ child tabs
```
root tab
\- 1st child
|- 2nd child
|- 3rd child
|- 4th child
...
```
5. Close and ctrl+shift+t root tab

## Actual result
Tabs are swithed in incorrect order with ctrl+tab:
4 tabs: root tab -> 1st child -> 3rd child -> 2nd child -> 4th child
5 tabs: root tab -> 1st child -> 4th child -> 3rd child -> 2nd child -> 5th child

## Environment

 * Platform (OS): Ubuntu 16.04.3 LTS
 * Version of Firefox: 58.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.4.16

**Comment by Tragen** [comment]
Perhaps it is the same bug I have?

1
|- 1.1
........|- 1.1.2
........|- 1.1.2
2

If you close 1.1 and you undo the close, my tree looks like

1
2
1.1
|- 1.1.2
|- 1.1.2

If I colapse 1
also 1.1 and the childs vanish.
Everything is at the wrong location.

**Comment by LookingForWayOut** [comment]
I have this same issue, as well as a few other bits I will mention.

Creating new tabs will sometimes become a child to another tab, or sometimes it will go to the very end of the tab list, or even becomes a child of another tab.

Moving tabs around do not always work. If I do create a tab and it is out of place, I can not move it to where i want it to go. Instead it picks its own place at the end of the list, or between other tabs. but not as a child of a parent, or even a new parent. It just goes somewhere else.

I do not know if related to the tabs being sometimes out of order with CTRL-TAB as well, but figured I mention it.

**Comment by piroor** [comment]
I close this because outdated.
