### ISSUE TITLE
basic auth entry dialog pops up immediately after restart for all restored tabs that use it

### ISSUE THREAD

**Issue by kilx** [piroor/treestyletab#1800]
## Short description

After restarting Firefox and restoring, tabs that were using basic authentication Firefox/TST asks for credentials immediately. Should ask only when I load that tab.

## Long description

Have lots of tabs open. Some of them required basic authentication which was provided but username and password were not saved in password manager. All good.

Now I restart Firefox due to update or or whatever reason. Firefox restores all tabs but does not load them until I actually choose one for viewing. This is good.

However it does ask for basic authentication on all tabs that required it before immediately after restarting without me opening any ofthe tabs that required basic auth. This is not good.

I want to provide authentication only when I actually open and load the tab, not before. Moreover, it doesn't make sense for me to provide my credentials to a basic authentication pop up without knowing what URL is asking for it.

However when I disabled TST and tested again Firefox did not ask for basic auth upon restart. It didn't even ask it during the content load (used cache). It asked for basic auth only when I clicked another link in the content of that tab that required fetching uncached content. Therefore this is caused by TST.

## Steps to reproduce
 0. Firefox 58 with TST 2.4.16.
 1. Open some tabs with any content.
 2. Open a tab and go to a URL requiring basic authentication. Login. Do NOT remember password using password manager.
 3. Open some more tabs or select some other tab that did not use basic auth.
 4. Close firefox.
 5. Open firefox.
 6. Firefox and TST restores all tabs. Loads only the currently selected tab and any pinned tabs.
 7. BUG: Firefox/TST also asks for credentials using deafult credentials entry pop up for all tabs that used basic authentication even though they are not even selected/loaded.

## Expected result

Credentials are not asked until actually required to load content as with default Firefox behavior.

## Actual result

Credentials are asked immediately.

## Environment

 * Platform (OS): Ubuntu 16.04
 * Version of Firefox: 58.0.2 ubuntu package
 * Version (or revision) of Tree Style Tab: 2.4.16

**Comment by piroor** [comment]
This is impossible to be fixed due to restrictions of WebExtensions APIs. We need any new API to embed favicons from cache. See also: [1315616 - Give extensions access to cached favicon URLs](https://bugzilla.mozilla.org/show_bug.cgi?id=1315616)

**Comment by kilx** [comment]
Huh, sucks. Will you keep this one open until the upstream fix gets implemented? I don't care either way.

**Comment by irvinm** [comment]
@kilx or @piroor ... I think we should close this item.  I believe that tabs are now started by default in a discarded state and therefore tabs that require authentication should not prompt for credentials until the tab is activated.

I might be missing a detail, so I thought I would ask.

**Comment by piroor** [comment]
On most cases WebExtensions API now returns data: URIs via favIconUrl, so I think this issue is already outdated. Thus I close this for now. If you still see this, please add a comment @kilx
