### ISSUE TITLE
TST autoscrolling

### ISSUE THREAD

**Issue by hethhhhh** [piroor/treestyletab#1801]
When more tabs are opened, TST autoscrolls to bottom when loading the current tab, which requires manual scrolling to go back to tab's position.

This happens when loading a tab, and when closing the active tab, even though the next tab is properly selected TST autoscrolls to bottom again.

Tabs are unloaded.

Edit:
Apparently it tries to allign with the current tab to be the first visible one, but it doesn't take in consideration that tabwidth might be different, resulting in hiding it (when wider tabs)

**Comment by piroor** [comment]
Does this still happen with the latest development build?
https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi

TST is designed to scroll the tab bar to the new active tab or a new tab opened in the background. If you see unexpected scrolling of the tab bar, then TST may misunderstand that some tabs are collapsed or expanded. By recent changes, TST calculates expected scroll position more correctly, so I hope you to try the latest development build.

**Comment by piroor** [comment]
I close this because outdated.
