### ISSUE TITLE
Sidebar submenu is still animated when animation are disabled

### ISSUE THREAD

**Issue by ariasuni** [piroor/treestyletab#1802]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Disable “Enable animation effects”
 4. Right-click on a sidebar tab

## Expected result

Submenu opening and closing aren’t animated (i.e. appear immediately).

## Actual result

Submenu opening and closing are still animated (fade in and out).

## Environment

 * Platform (OS): GNU/Linux
 * Version of Firefox: 59.0b11
 * Version (or revision) of Tree Style Tab: 2.4.16

## Comment

I can try to fix that myself but I don’t know Tree Style Tab source code, so any pointers or examples of how it’s done elsewhere could help.

**Comment by piroor** [comment]
Thanks, I forgot to apply the config for menu like UIs. After the commit 4bade00 animation of them are also deactivated.
