### ISSUE TITLE
Focus should change on mouseUp so that we can move tabs without loading them

### ISSUE THREAD

**Issue by ariasuni** [piroor/treestyletab#1803]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a few tabs 
 4. Check “Show your windows and tabs from last time” on Firefox settings page
 5. Restart Firefox
 6. Try to move unloaded tabs 

## Expected result

I can’t drag and drop tabs without the focus changing and Firefox loading them.

## Actual result

Tab is loaded as soon as I click on it, so I can’t move it without loading it.

## Environment

  * Platform (OS): GNU/Linux
  * Version of Firefox: 59.0b11
  * Version (or revision) of Tree Style Tab: 2.4.16

**Comment by piroor** [comment]
I don't think this is a "bug" of TST, because this is quite same behavior to Firefox's horizontal tab bar. I think TST should respect Firefox's behavior when it is possible - this is a design policy. Sorry.

**Comment by alreadydone** [comment]
So is this bug on Bugzilla now? If not we could provide this through an option of TST as @Lej77 already has a patch for it.

**Comment by piroor** [comment]
After the commit d460cea, now extensions like described at https://github.com/piroor/treestyletab/pull/1866 can work as expected. Thus it should become a workaround for this issue.

@alreadydone If you think dragged tabs should keep suspended on Firefox's horizontal tab bar, you should file a bug for it. If Firefox's behavior is changed in a future versions of Firefox, I will change TST's behavior to follow the new one of Firefox itself.

**Comment by Lej77** [comment]
I released an extension based on my example code on `addons.mozilla.org`. So that extension should work as soon as the next version of Tree Style Tab releases.

Here is a link: [Move unloaded tabs for Tree Style Tab by Lej77](https://addons.mozilla.org/firefox/addon/move-unloaded-tabs-for-tst/)

**Comment by QuixoticGitHub** [comment]
This needs to be resurrected. Loading onmousedown makes absolutely no sense. If it's a "design philosophy" then you need to reevaluate your axioms.

**Comment by ariasuni** [comment]
If you don’t like it, you can just use [Lej77’s addon](https://github.com/piroor/treestyletab/issues/1803#issuecomment-382371644).

Even if I don’t agree it’s the best behavior, sticking to Firefox’s default behavior has its advantages.

Furthermore, from the [README.md](https://github.com/piroor/treestyletab#faq--frequently-rejected-requestsproposals):

> To avoid users' confusion, TST respects Firefox's built-in behavior and features around the tab bar - tab context menu, gestures, and so on.

So this decision absolutely makes sense.
