### ISSUE TITLE
Dragging won't start if mouse is held still too long after pressing down the button

### ISSUE THREAD

**Issue by jwkangas** [piroor/treestyletab#1804]
## Short description

When I press down the left mouse button to drag a tab, it appears that I have to start moving the mouse within a certain short amount of time (less than one second). If I instead wait too long after pressing down the button, dragging won't initiate.

This isn't a huge problem as most of the time I don't pause for too long after pressing down the button, but it feels counter-intuitive and can be a bit annoying sometimes.

## Steps to reproduce

 1. (Start Firefox with clean profile.)
 2. (Install TST.)
 3. Open a few tabs.
 4. Move the mouse on any tab in the TST sidebar.
 5. Press and hold down the left mouse button, say, for one second, without moving the mouse (or moving it so little that dragging isn't detected).
 6. Still holding down the button, move the mouse to drag the tab.

## Expected result

The tab is dragged normally.

## Actual result

The tab is not dragged. Everything behaves as if the mouse button were not held down.

## Environment

Confirmed on the following:
 * Platform (OS): Ubuntu 16.04 LTS, Kubuntu 17.04
 * Version of Firefox: 57.0.4, 58.0.2
 * Version (or revision) of Tree Style Tab: 2.4.16

**Comment by piroor** [comment]
The behavior was reserved for other addons (especially Multiple Tab Handler) but it should be ignored if no external addon wants the behavior. By recent changes, the action long-press on a tab is available only when Multiple Tab Handler is installed.
