### ISSUE TITLE
In legacy TST, how to control position of tabs opened by Web Extensions?

### ISSUE THREAD

**Issue by sumyungguy** [piroor/treestyletab#1805]
I'm using legacy XUL TST in Waterfox. I think there is no preference in TST to control the position of tabs opened by other addons/extensions, is that right? They always open at the end of the tab bar?

I can modify XUL addons for example:
```js
if ('TreeStyleTabService' in window)
  TreeStyleTabService.readyToOpenChildTab(gBrowser.selectedTab);
gBrowser.addTab(TAB_URL);
```
But that doesn't work in a web extension. Is there some way to use the TreeStyleTabService from a web extension? Or is there a way to modify XUL TST to open all tabs from other addons as a child of the current tab?

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
