### ISSUE TITLE
add suport of auto-tab-discard

### ISSUE THREAD

**Issue by perdolka** [piroor/treestyletab#1808]
* Platform (OS): Win 10 (x64)
 * Version of Firefox: 59.0b12 (x64)
 * Version (or revision) of Tree Style Tab: 2.4.16

Problem:
TST doesn't detect unloading by [auto-tab-discard](https://github.com/rNeomy/auto-tab-discard) addon
therefore, [change-styling-of-pending-unloaded-tabs](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#change-styling-of-pending-unloaded-tabs-1363) code-snippets doesn't change tabs style.

**Comment by lbmaian** [comment]
That add-on does have some TST support: https://github.com/rNeomy/auto-tab-discard/issues/11

There are some problems with it re-registering itself on the fake TST menu when TST is updated or reinstalled at the moment. The workaround is to disable and enable Auto Tab Discard in about:addons.

**Comment by perdolka** [comment]
Solved
Looks like it's working.

**Comment by perdolka** [comment]
@lbmaian
I have the same problem.
I think you should create issue on the auto-tab-discard page.

**Comment by lbmaian** [comment]
The Auto Tab Discard dev did attempt to fix the problem in that linked issue, but it's still finicky. I think the problem may be on TST's side. Something about there not being a reliable way to ensure custom TST items remain registered through TST reinstalls and upgrades.
