### ISSUE TITLE
Keyboard shortcuts disabled

### ISSUE THREAD

**Issue by perdolka** [piroor/treestyletab#1813]
* Platform (OS): Windows 10 pro (x64)
 * Version of Firefox: 59.0b13 (x64)
 * Version (or revision) of Tree Style Tab: 2.4.16
<a href="http://piccy.info/view3/12122955/b99647e3bbdb889842aa47e58a1c6705/" target="_blank"><img src="http://i.piccy.info/i9/0dcfd8633f488971ef91d74a6691d861/1520240407/27561/1225975/key_min_500.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-03-05-09-00/i9-12122955/500x240-r" target="_blank"><img src="http://i.piccy.info/a3/2018-03-05-09-00/i9-12122955/500x240-r/i.gif" alt="" border="0" /></a>

**Comment by piroor** [comment]
A new API to change keyboard shortcuts is available only on Firefox 60 and later. On Fx 59 or older versions, you just see pre-defined shortcuts.
