### ISSUE TITLE
[enhancement] Add code highlight to Advanced window

### ISSUE THREAD

**Issue by perdolka** [piroor/treestyletab#1814]
<a href="http://piccy.info/view3/12123010/833554ae8e2ce63045a8fc825dce7cfa/orig/" target="_blank"><img src="http://i.piccy.info/i9/1727d909ff1a079dad19d7667af85c63/1520241486/54253/1225975/sample11_min_800.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-03-05-09-18/i9-12123010/582x733-r" target="_blank"><img src="http://i.piccy.info/a3/2018-03-05-09-18/i9-12123010/582x733-r/i.gif" alt="" border="0" /></a>

**Comment by piroor** [comment]
Sorry, I have no plan to make the feature rich... I recommend you to edit rules with something external text editor.
