### ISSUE TITLE
[feature request] display scrollbar on right

### ISSUE THREAD

**Issue by woj-tek** [piroor/treestyletab#1816]
## Short description
[feature request] Option to display TST scrollbar on the right

## Steps to reproduce
* Set the TST/sidebar to display on the right,
* Open more tabs than can fit on the screen (to force the scrollbar)

## Expected result
Scrollbar for the tabs should be displayed on the right side of the sidebar

## Actual result
The scrollbar is displayed on the left side of the sidebar (next to the page frame).
This is even more confusing if the page itself is long, which caused to have to scrollbars side-by-side.
https://www.dropbox.com/s/mz24tomh5jhgrt2/TST_scrollbar.png?dl=0

## Environment

 * Platform (OS): macOS High Sierra
 * Version of Firefox: 58.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.4.16

**Comment by Lej77** [comment]
In TST's setting page under the header `Appearance` their is an option called `Style of contents for the sidebar position`. Setting this option to `Right side` and then closing and reopening the TST sidebar should put the sidebar scrollbar on the right side. Note that the option will also restyle the rest of the Sidebar to fit better on the right side of the window.

If you don't want to restyle the whole TST sidebar and instead only move the scrollbar to the right side then there is a hidden setting to only move the scrollbar in TST's setting page. To activate it:
1. Check the `Debug mode` checkbox under the header `Development`.
2. Set the option `Position of the scrollbar` to `Right side`. (The option is located right above the `All Configs` header.)
3. Uncheck the `Debug mode` checkbox.

**Comment by woj-tek** [comment]
Actually I tried `Style of contents for the sidebar position` but wasn't so fond of the result but the `Position of the scrollbar` did the trick -- thank you! 👍

**Comment by piroor** [comment]
By recent commits I've moved the checkbox from "Debug" section to "Appearance".

**Comment by piroor** [comment]
I close this because outdated. Now it is an exposed option.

**Comment by the-a-man-006** [comment]
Where did the setting go? I can't find it; help!!!
