### ISSUE TITLE
[feature request]: add URL search

### ISSUE THREAD

**Issue by hrmillergithum** [piroor/treestyletab#1817]
Tab Groups provided a way to search with autofill for an existing tab which I used a lot, so it would be nice to be able to do the same thing with TST. I'm not a power user of TST so if this feature already exists, please provide a pointer to how to invoke it.  thank you!

**Comment by Lej77** [comment]
Unfortunately, I don't think TST has any search feature. As a workaround you can install another extension such as [All Tabs Helper by Kevin Jones](https://addons.mozilla.org/firefox/addon/all-tabs-helper/) or [Tab Finder by Chris Franson](https://addons.mozilla.org/firefox/addon/minimal-tab-finder/) to search for your tabs.

**Comment by lbmaian** [comment]
As a workaround, you can just use the URL bar: get to address bar (e.g. ctrl-L), type %, then <space>, then the tab title or keywords like a normal search. You don't even need to open a new tab for this - it'll just focus the searched-for tab.

**Comment by wsmwk** [comment]
[Tabhunter](https://addons.mozilla.org/en-US/firefox/addon/tabhunter/) is also good.

**Comment by hrmillergithum** [comment]
On 3/10/18 2:37 AM, wsmwk wrote:
> Tabhunter <https://addons.mozilla.org/en-US/firefox/addon/tabhunter/> is also good.
> 

Perfect! Thank you.

-- 
Rod Miller
Handcraftsman
===
Custom 2-rail O Scale Models: Drives,  |   O Scale West / S West
Repairs, Steam Loco Building, More     |   2018 Meet is May 24 - 26
http://www.rodmiller.com               |   http://www.oscalewest.com
