### ISSUE TITLE
The TST sidebar keeps reloading

### ISSUE THREAD

**Issue by ksze** [piroor/treestyletab#1818]
## Short description
The TST sidebar keeps reloading

## Steps to reproduce

 1. Update TST from 2.4.16 to 2.4.17

## Expected result

TST runs stably.

## Actual result

TST keeps reloading the sidebar.

## Environment

 * Platform (OS): macOS High Sierra 10.13.3
 * Version of Firefox: 58.0.2 64-bit
 * Version (or revision) of Tree Style Tab: 2.4.16

**Comment by azizLIGHT** [comment]
I think you might be talking about https://github.com/piroor/treestyletab/issues/1812

**Comment by ksze** [comment]
@azizLIGHT My symptoms are a bit different, I think. My sidebar does display, with the tabs; It's just that the sidebar keeps reloading after displaying the tabs, so it cycles from the animated blob, to showing tabs, to showing the animated blob again, and keeps repeating like that.

**Comment by azizLIGHT** [comment]
@ksze Oh yeah that is different. The issue I linked just reloads the sidebar forever without any glimpse of the tabs. Sorry!

**Comment by volas** [comment]
Same problem

**Comment by avh-on1** [comment]
I also started having this problem. I fixed it with the reverse solution that @mr-brunes used for #1812 

I had previously enabled debug mode and disabled `optimize tree restoration with cache` due to #1754 

Re-enabling `optimize tree restoration with cache` fixed this issue (#1818) for me. I'm not yet sure if this causes #1754 to come back.

I hope I don't have to choose between "TST only lets me interact with tabs 1 out of every 5 seconds" and "TST messes with the hierarchy of my tabs".

**Comment by jsams** [comment]
I am also seeing this over the past couple of days on 58.0.2 with tst 2.4.17. I had also been hit with #1754 and had disabled the tree cache optimization. Re-enabling it kills the infinite loop of reloading the tab tree. I've opened a few tabs and the tree hasn't been mismanaged yet. Here's to hoping it stays that way.

**Comment by avh-on1** [comment]
> I hope I don't have to choose between "TST only lets me interact with tabs 1 out of every 5 seconds" and "TST messes with the hierarchy of my tabs".

Unfortunately, enabling `optimize tree restoration with cache` *did* cause #1754 to come back for me. Turning it off caused TST to go into the reload loop, and turning it back on caused the loop to stop, and the tabs to be shown in a sane order. (This time, anyway.)

**Comment by ProCycleDev** [comment]
I was having this same problem. I managed to fix it (knock on wood) by turning off the cache, and then reordering the trees with the tabs that are broken while cache is enabled. That seems to have forced it to recalculate things and now it no longer reloads over and over

I've noticed that the laundry list of problems (out of order tabs, tabs you can't click on to switch to or close, disappearing tabs) all happen after I move tabs to another window and then back to the main window again

**Comment by Ryman** [comment]
> I've noticed that the laundry list of problems (out of order tabs, tabs you can't click on to switch to or close, disappearing tabs) all happen after I move tabs to another window and then back to the main window again

+1 on this, had the issues on a new install right after moving a tree to a new window, something weird happened which undid it and then doing it again.

**Comment by jsams** [comment]
-1 I don't believe mine had anything to do with a different window. I almost never open a second window.

**Comment by piroor** [comment]
Does this still happen with the latest development build?
https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi

**Comment by piroor** [comment]
I close this because outdated.
