### ISSUE TITLE
When opening all links from bookmark folder the first Tab drops out of resulting TST-Subtree

### ISSUE THREAD

**Issue by JTDE** [piroor/treestyletab#1819]
## Short description

When you open a complete bookmark folder as Tabs a new TST subtree with all these tabs is created.
The first of these tabs "jumps" out of this subtree.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Create two Bookmark-Folders with some links
 4. Right-Click on first Bookmark folder (A) to open them all in Tabs.
 5. Do the same with the second folder (B)

## Expected result

One would expect this structure:

[A]
\- A1
\- A2
\- A3
[B]
\- B1
\- B2
\- B3

## Actual result

I get this structure:

[A]
\- A1
\- A2
\- A3
B1    <-- seems to "jump" out of the tree during building [B]
[B]
\- B2
\- B3

## Environment

 * Platform (OS): Ubuntu Linux 17.10, Mate
 * Version of Firefox: 57.0 - 58.02
 * Version (or revision) of Tree Style Tab: 2.4.16...18

**Comment by JTDE** [comment]
The effect seems to happen mainly in slightly more complex scenarios (at least one pre-existing tab-subtree), so I extended the example a little bit.

**Comment by piroor** [comment]
The timeout setting seems too small for your case. Please increase the setting at TST's configurations => "New Tabs Behavior" => "Auto-group tabs opened within XXX msec", from its default value `100` to `200` or more. If there are too many tabs or the system is being slow, the secondary tab can be opened with too much delay.
