### ISSUE TITLE
Bad peformance when opening TST Sidebar in session with many tabs

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#1823]
## Short description
Opening the TST Sidebar seems to cause a lot higher CPU usage in TST 2.4.17 then it did in earlier versions. This becomes apparent in sessions with many tabs since the browser becomes unresponsive after opening a new window. When the TST sidebar is opened automatically in the new window it takes awhile before CPU usage goes down and the browser becomes responsive again. It also seems like it takes longer for Firefox to start if it is set to restore the previous session on startup. This is a new problem and it doesn't occur in TST 2.4.16 or earlier versions.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open 2000 tabs to simulate session with many tabs. 
    a. Close the TST Sidebar.
    b. Press `F12` to open development tools.
    c. Press the cogwheel in the upper right corner of the panel to access the settings page.
    d. Scroll to the bottom and activate `Enable browser chrome and add-on debugging toolboxes` under the `Advanced Settings` header.
    e. Open the browser console with `ctrl+shift+j` or from the hamburger menu.
    f. Paste the following script and press enter: 
      ``for (let i = 0; i < 2000; i++) gBrowser.addTab(`about:blank?index=${i}`);``
 4. Open a new window with 1 tab.
 5. Close and reopen the TST Sidebar in the new window (the window with 1 tab).
 6. Observe CPU usage.

## Expected result
In TST 2.4.16 and earlier versions the CPU usage was low and on my machine didn't go above about 20%. 

## Actual result
In TST 2.4.17 the CPU usage is really high, up to 80% on my machine. 

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 58 and 60
 * Version (or revision) of Tree Style Tab: 2.4.17

**Comment by Jiehong** [comment]
I can confirm this issue with FF 59 on Archlinux as well.

Disabling TST simply solves this issue.

In my case, it's already pretty noticeable at 300, mainly because I didn't clean much :D

**Comment by piroor** [comment]
Does ffab9b228af3bba0e88927646e9f010b7a2f1986 affect to this?

**Comment by Lej77** [comment]
Yes, this issue seems to be fixed now.
