### ISSUE TITLE
Child tabs open in the wrong place sometimes

### ISSUE THREAD

**Issue by wattb** [piroor/treestyletab#1824]
## Short description
Child tabs do not open at the bottom of the (sub)tree but instead open elsewhere

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set "insertion of new child tabs" to "append to the end of the tree"
 4. Open two tabs at the top level `a` and `b`
 5. In the first tab, open a child tab `a1`
 6. Open several more child tabs of `a`, they will appear above `a1`
 7. Open child tabs of `a1` and they appear below the first child of `a` (which is not `a1` for me)
 8. Doing the same with `b` works as normal - I think the last tab in the tree is unaffected

```
a
\-a2
   \-a1a
   \-a1b
\-a3
\-a1
b
\-b1
   \-b1a
\-b2
```

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 60.0a1 (2018-03-08) (64-bit) Nightly
 * Version (or revision) of Tree Style Tab: 2.4.17.6692.6692

**Comment by lbmaian** [comment]
This is happening to me as well on the latest TST version and latest Firefox Dev Edition version.

**Comment by ibrahima** [comment]
I've also noticed that keyboard shortcuts like ctrl+pagedown/pageup will navigate in the order that the tabs are supposed to be in, rather than the order that they're displayed, when this happens.

**Comment by piroor** [comment]
I think d9e1375ab9602864e15e7dc84aaa08ba549fa9ab should solve this problem on some cases.

**Comment by lbmaian** [comment]
I want to test this (as one of the users afflicted), but I'm getting the following error when trying to install the latest TST nightly:

"The add-on downloaded from this site could not be installed because it appears to be corrupt."

**Comment by piroor** [comment]
Sorry it was broken. I've re-uploaded installer: https://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by lbmaian** [comment]
Thanks, installed it successfully, and it looks like this bug is fixed!

**Comment by wattb** [comment]
It works for me now.
