### ISSUE TITLE
Import tree, tabs and structure, into quantum

### ISSUE THREAD

**Issue by zekeblue** [piroor/treestyletab#1826]
Is there a way to import my tree, with its structure, of 100+ tabs from Fx 52ESR to Fx Quantum?  I've succeeded in importing all of the tabs with a session restore extension, but with a flat structure.  Thank you.

edit:  found the treestyletab-sessionstore-migrate.exe utility.  However, instructions say to look for sessionstore.jsonlz4.  Mine is sessionstore.js and the utility won't run on that.  This is in the C:\Users\(username)> cd %AppData%\Mozilla\Firefox\Profiles\xxxxx.default folder.  And using the following commands in a cmd window:

C:...> rename sessionstore.jsonlz4 .\sessionstore.jsonlz4.bak
C:...> move C:\Users\(username)\Downloads\treestyletab-sessionstore-migrate.exe .\
C:...> treestyletab-sessionstore-migrate.exe sessionstore.jsonlz4.bak sessionstore.jsonlz4

**Comment by piroor** [comment]
Sorry I forgot to describe about preparation. You need to update Firefox ESR52 to Firefox 56 or newer versions, to migrate `sessionstore.js` to `sessionstore.jsolz4`. I've add the "before migration" section: https://github.com/piroor/treestyletab/wiki/How-to-convert-session-information-from-old-TST-0.19.x-to-new-TST-2.x#before-migration-from-firefox-esr52-or-some-versions-older-than-firefox-57

**Comment by zekeblue** [comment]
Thank you Piroor!  I will get on it.

**Comment by piroor** [comment]
I close this because outdated.
