### ISSUE TITLE
[2.4.17] Red dots on tabs after enabling debug mode

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1829]
Hello!
Nightly 61, TST2.4.17, Win8. STR:
Create new profile, launch it, go to TST options and enable debug mode.
![image](https://user-images.githubusercontent.com/26294581/37433439-0361f254-27ed-11e8-86cd-9c5539a27717.png)

Here is what TST sidebar will look like:
![default](https://user-images.githubusercontent.com/26294581/37433456-144c6202-27ed-11e8-9b8a-23f78ee71010.png)

AR: Each tab has red dots on it
ER: Tabs shouldn't have any red dots because enabling debug mode shouldn't change any TST settings and  cause graphical artifacts like this.

**Comment by piroor** [comment]
This is intentional. I need this for debugging about appearance.

**Comment by SXZ1** [comment]
Sorry, it looks like all changed prefs in "Debug mode" section are saved after you disable Debug mode so this bug is useless since you can just disable debug mode.
