### ISSUE TITLE
[2.4.17] Sidebar is constantly reloading after disabling cache

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1830]
Hello!
Nightly 61, TST2.4.17, Win8. STR:
Create new profile, launch it, go to TST options, enable debug mode, uncheck "Optimize tree restoration with cache":
![scr](https://user-images.githubusercontent.com/26294581/37433691-ec7484d4-27ed-11e8-966f-9f50bb493d19.png)

AR: Sidebar is constantly reloading - in other words, sidebar is constantly switching from state 1 to state 2 (both states shown on the screenshot):
![both](https://user-images.githubusercontent.com/26294581/37433743-28950e84-27ee-11e8-9325-5e430130966d.png)
ER: Sidebar shouldn't be reloading constantly

**Comment by SXZ1** [comment]
It looks like this bug is reproduced in 2.4.17 and not reproduced in 2.4.16. I think I'll try to find a faulty commit.

**Comment by SXZ1** [comment]
Surprisingly, faulty commit is https://github.com/piroor/treestyletab/commit/e8eb61166fa517bc1b924a260bead1a2666e8eaf
However, previous commit https://github.com/piroor/treestyletab/commit/eca4f88c533c603b7b5fcb6e8ba1d1e31bbaf26c is bugged as well because the sidebar is empty and doesn't work.

**Comment by gotyaoi** [comment]
Perhaps relating to this, when I updated firefox from 58.0.2 to 59.0.1 this morning, the sidebar was stuck in state 1. I turned off caching and restarted firefox, and saw this reloading behavior. I then re-enabled caching, restarted firefox and everything worked again.

**Comment by SXZ1** [comment]
Fixed in latest dev. Thank you very much!
