### ISSUE TITLE
I do not see any texts in tree style tabs.

### ISSUE THREAD

**Issue by skwaruch** [piroor/treestyletab#1833]
## Short description
I do not see the texts after the firefox upgrade to 59.
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
![image](https://user-images.githubusercontent.com/12412153/37553588-8586ce3c-29cb-11e8-80e2-8e8a13e68a0c.png)

 * Platform (OS): Windows 10 pro
 * Version of Firefox: 59.0.1
 * Version (or revision) of Tree Style Tab: 2.4.17

**Comment by skwaruch** [comment]
The solution: turn cleartype back on or disabling hardware acceleration in firefox

**Comment by Advanc3d** [comment]
Confirm the issue with Windows 7 as well

**Comment by piroor** [comment]
This problem doesn't happen on my environment, and I think this should be fixed by Firefox side because such an rendering problem can appear on regular webpages.

**Comment by piroor** [comment]
I close this because outdated.
