### ISSUE TITLE
Can I manually create a tab like this?

### ISSUE THREAD

**Issue by aminought** [piroor/treestyletab#1834]
![default](https://user-images.githubusercontent.com/8617665/37554650-bb10dbec-29fd-11e8-9f23-8b4fa564f757.png)

**Comment by Lej77** [comment]
If you mean Group Tabs like the currently selected tab in the screenshot then yes. 

1. You can make a bookmark to the page. You can also make the bookmark to the URL `about:treestyletab-group` or the more detailed `about:treestyletab-group?title=New%20group&temporary=false`.
2. You can install [Multiple Tab Handler by Piro (piro_or)](https://addons.mozilla.org/firefox/addon/multiple-tab-handler/) and in its options page activate the context menu option `Create New Group` which will appear when you select tabs in the Tree Style Tab sidebar with `ctrl+click`, `shift+click` or `long-press+drag` in the sub-menu `Selected Tabs` after having installed the extension. 
3. If the option `Auto-group tabs opened within` is cheked in Tree Style Tab's options page then you quickly open some new tabs to group them. For example by holding `ctrl+t`.

**Comment by JaneSmith** [comment]
I wanted this too. Thanks for the tips. It would be nice if there was a simple button to do this though - like a "new group" button next to the big "new tab" button.

**Comment by zekeblue** [comment]
Once multiple tab handler is installed, creating new groups is just as easy.

For the more advanced, I experimented and found the term to reference group tabs in TST's "extra style rules".  It is nice to have group tabs colored a bit differently to help show organization:

> /* --Change attributes of group tabs */
> .tab.group-tab {
>    background-color: #B5C1E3;
>    height: 23px;
>    }
> .tab.group-tab .label {
>    color: black;
>    font-weight: bold;
>    }

Example:

<a href="https://imgur.com/Numdhzo"><img src="https://i.imgur.com/Numdhzo.jpg?1" title="source: imgur.com" /></a>
