### ISSUE TITLE
[Feature Request] Lock/Protect tab

### ISSUE THREAD

**Issue by zekeblue** [piroor/treestyletab#1836]
This may be considered out of purpose.  Nevertheless, it is the most important function to me that remains to make quantum acceptably functional enough to replace pre quantum.  It was a feature of tabmixplus though other extensions may have offered it.  I cannot find a compatible extension that will do this.  It seems to me it would go well overall with TST functionality.

Lock/Protect tab (not sure of proper terminology) would protect a tab from closing.  Not just remove the close "x" on the tab, but keep it from closing unless unprotected (I use a mouse button to close a tab mimicking the keystroke that will do it.  Some use mouse gestures, etc.)

Part of this functionality was to make links open in a new tab, though there are extensions that do this as well.

Thanks for your consideration - or explanation if this is impossible to accomplish with the new limiations.

**Comment by overdodactyl** [comment]
This is a built-in feature in Firefox.  Rick click a tab and select "pin tab"

**Comment by zekeblue** [comment]
I wish it were that easy!  As far as I can tell, pin tab moves it out of the tree to the top of the sidebar as a favicon only.  I would like tabs to stay in their place and be locked.  

Wonderful if there is a setting to make pin tab do this, but I have not seen it if it exists.

**Comment by overdodactyl** [comment]
That's true, the big downside to pinned tabs is they can not be part of a tree structure.

See #1056

**Comment by ssokolow** [comment]
Also, one bug I'll have to double-check that I reported on Firefox is that "pin tab" doesn't override the about:config keys to force links to open in the same tab unless middle-clicked.

**Comment by irvinm** [comment]
I had used "Tab Utilities" pre-57 that provided a right-click option on a tab to "Lock" the tab which then replaced the "X" with a "Lock" which prevented you from closing the tab until you unlocked it.  I used it on my set of tabs I knew I would likely visit each day (or wanted to have available quickly) to ensure I didn't close by accident.

I had been thinking about this recently with TST and seeing as the tabs are not real tabs, I would imagine something like this could be possible without having to pin the tab if piroor was so inclined.  (This wouldn't impact the original tabs, but most who use TST hide the original tab bar)

I know you can remove the "X" via CSS for all tabs, but obviously the desire here would be to do this via a right-click option from TST to protect\un-protect individual tabs.

![2018-03-22_16-23-00](https://user-images.githubusercontent.com/979729/37796353-790c30fe-2ded-11e8-9d24-0b41563ec73b.png)

**Comment by zekeblue** [comment]
That add-on looks like it had it down.  I accomplished it with TabMixPlus.  

It does seem that creating this ability in an add-in, whether TST or a standalone one, would be achievable since the native function is there with pinned tabs.  It may not be as easy as it sounds though.  I'm not a programmer and don't see obstacles like I would if I was.

**Comment by piroor** [comment]
Because TST is designed just for operations of tabs in tree-view, I won't add features not related to tree. "Lock Tab" and "Protect Tab" feature should be done by a separate addon, and TST should become compatible with it. That will help people who don't use vertical and tree-style tab bar too.

**Comment by irvinm** [comment]
@zekeblue or @piroor please close this item.  @piroor already provided some information and example code to do this in https://github.com/piroor/treestyletab/issues/2104 which could be integrated into another addon.
