### ISSUE TITLE
Justification of TST tab context menu

### ISSUE THREAD

**Issue by Rybags** [piroor/treestyletab#1837]
I've noticed the right-click tab context menu seems to be left-justified in relation to the mouse pointer, opposite to normal behaviour (except when sufficiently close to the left of screen to force it the other way).

Is there a way to force "normal" behaviour or could an option be added?

(Firefox 58 and 59 for Windows)

**Comment by lbmaian** [comment]
I'm not the author, but I'm pretty sure this behavior is intentional. It's because the fake context menu must remain within the bounds of the sidebar.

**Comment by piroor** [comment]
I close this because outdated.
