### ISSUE TITLE
When closing a child tab, focus moves briefly to the tab below before returning to parent. 

### ISSUE THREAD

**Issue by zekeblue** [piroor/treestyletab#1838]
## Short description
When closing a child tab, focus moves briefly to the tab below before returning to parent.  Often this is waking up a suspended tab.

## Steps to reproduce
open link in tab so that it creates a child tab below that tab.  With focus on the child tab, close it.  

## Expected result
When child tab is closed, focus moves only to the parent tab that opened it.  

## Actual result
Focus moves to tab below very briefly, then returns to parent tab.  (Tab Open/Close Control is installed and influences which tab gets focus after closing active tab.  But same result occurs with that extension disabled.)

## Environment

 * Platform (OS): Win 10 Pro x64
 * Version of Firefox: 59
 * Version (or revision) of Tree Style Tab: 2.4.17

Thank you.

**Comment by piroor** [comment]
Currently I cannot fix this problem due to restrictions of WebExtensions APIs. See the comment at https://github.com/piroor/treestyletab/issues/1798#issuecomment-388572185

**Comment by kernc** [comment]
The brief focus onto the next tab is particularly painful when closing several tabs in succession by pressing <kbd>Ctrl</kbd>+<kbd>W</kbd> repeatedly as sometimes incorrect tabs are closed (and the fact only observed too late to recover).

If I understand the comment correctly, you say we can't switch tabs because we don't know whether `browser.tabs.selectOwnerOnClose` is set because [we can't read the preference](https://wiki.mozilla.org/WebExtensions/FAQ#Does_the_WebExtensions_API_provide_access_to_preferences.3F)?

Couldn't TST rely only on its own setting similar to "When the current tab is closed as a last child" and switch the tabs just _before_ the tab is closed?

**Comment by piroor** [comment]
> Couldn't TST rely only on its own setting similar to "When the current tab is closed as a last child" and switch the tabs just before the tab is closed?

It is technically possible, but it conflicts to my development policy. Basically I think that TST should do just few minimum interruptions for Firefox's native tab operations, to keep compatibility with behaviors of Firefox itself or other addons. I believe that the behavior introduced by `browser.tabs.selectOwnerOnClose` should be disabled by the preference `browser.tabs.selectOwnerOnClose` itself, not by addon. (In other words, I believe that TST is designed for non-novice people who can manage features of Firefox itself and addons by themselves.)

**Comment by piroor** [comment]
Sorry, I mispointed at the previous comment. I missed that you wrote not only about `browser.tabs.selectOwnerOnClose` but about "focusing to the next tab before previous sibling tab is focused" also. (I read this issue after a long interval, so I missed that what was the main topic...)

There are two cases when the current tab is going to be closed.

 1. The tab is closed by TST itself, by clicking the closebox of a tab in the sidebar, or choosing "close tab" command from the fake context menu in the sidebar.
 2. The tab is closed by Firefox itself or other addons, in other methods (Ctrl-W, clicking the closebox of a tab in the horizontal tab bar, etc.)

TST can focus to the previous tab before the current tab is closed, only at the 1st case. On the other hand, at the 2nd case only a "tabs.onRemoved" event is notified after the focus was moved by Firefox , so logically TST cannot prevent the "the next tab is unexpectedly focused" behavior.

About this point, Firefox 64 will have improvements.

 * [1419947 - Extend tabbrowser to track and use tab successors](https://bugzilla.mozilla.org/show_bug.cgi?id=1419947) (about basic implementation, already landed)
 * [1500479 - Enhance browser.tabs API to support assigning tab successors](https://bugzilla.mozilla.org/show_bug.cgi?id=1500479) (about WebExtensions API, in progress)

After the new API is land, I'll update TST to use that. After that you'll never see the "next tab is unexpectedly focused" behavior. But currently it is impossible, so please wait until Firefox 64 is released.

**Comment by kernc** [comment]
I understand clearly now. Thank you!

**Comment by hklene** [comment]
To my understanding the implementation and the API have landed in FF65, so the label "bug on FF itself" could be discarded, right?

**Comment by piroor** [comment]
This is already fixed.
