### ISSUE TITLE
Restarting Firefox unexpands all tabs

### ISSUE THREAD

**Issue by nh2** [piroor/treestyletab#1839]
When I restart Firefox, all my tree drop-downs restore in unexpanded mode, so I have to manually expand them again (e.g. by clicking the triangle).

It would be great if the tree could restore with the same expansion status as it was closed with when FF is restarted.

## Environment

 * Platform (OS): Ubuntu 16.04
 * Version of Firefox: 61 Nightly
 * Version (or revision) of Tree Style Tab:  2.4.17

**Comment by nh2** [comment]
Another question, slightly unrelated to the issue: Can I disable the "collapsing" feature completely? I would always like my tree to be expanded.

**Comment by zekeblue** [comment]
This help?

![2018-03-21_9-06-26](https://user-images.githubusercontent.com/720927/37725369-af1f856c-2ce7-11e8-97d5-68c3c64b6be9.jpg)

**Comment by nh2** [comment]
@zekeblue You are right, enabling that last setting, `Don't expand collapsed tree and skip collapsed descendants, while switching focus of the tabs via keyboard shortcuts`, seems to ensure that the foldings restore as before when restarting.

But I don't understand why -- that description doesn't sound relevant at all. Even more so because it says `don't expand`, while I _want_ it to expand.

**Comment by zekeblue** [comment]
Well, I can't explain, but glad it helps.  BTW, I didn't mean to suggest checking boxes as I displayed, only that there are those settings that affect tree operations.

**Comment by zekeblue** [comment]
I seem to have developed the issue.  Restart and all trees are expanded.  Can't find settings that will allow keeping the state of the previous tree.

**Comment by piroor** [comment]
I also see this problem sometimes, but I still couldn't find out what is the trigger...

**Comment by piroor** [comment]
The latest development build contains some fixes around this problem. If you use Aurora or Nightly you can try that: https://github.com/piroor/treestyletab/blob/master/README.md#development-builds

**Comment by piroor** [comment]
I close this because outdated.
