### ISSUE TITLE
Vertical scrollbar handle cannot be dragged where E10S (multiprocess windows) is enabled

### ISSUE THREAD

**Issue by kerframil** [piroor/treestyletab#1841]
## Short description

The vertical scrollbar does not function correctly in the legacy version of TST, where E10S is enabled. I understand that development is now focused on the WebExtension version, but this is a nuisance and a fix would be greatly appreciated.

## Steps to reproduce

 1. Start Firefox 56.0.2 or Waterfox 56.0.4.1 with a clean profile.
 2. Install TST.
 3. Ensure that "Multiprocess Windows" is shown as enabled via about:support.
 4. Configure TST to display the tabs on the right-hand side.
 5. Create enough new tabs that TST displays a scrollbar to handle the overflow.
 6. Attempt to grab the scrollbar handle and drag it to scroll up or down.
 7. Disable E10s via about:config, then restart Firefox/Waterfox.
 8. Repeat steps 5 and 6.

## Expected result

It should be possible to drag the scrollbar handle upwards or downwards to perform conventional vertical scrolling, irrespective of whether E10S is enabled.

## Actual result

The scrollbar handle remains stuck in its existing position upon trying to drag it upwards or downwards, provided that E10S is enabled. After disabling E10S, it functions as expected.

## Environment

 * Platform (OS): macOS High Sierra / Windows 10 (1709)
 * Version of Firefox: Firefox 56.0.2 / WaterFox 56.0.4.1
 * Version (or revision) of Tree Style Tab: 0.19.2017090601

**Comment by kerframil** [comment]
Additional information: where E10S is enabled, it is still possible to have TST scroll its overflowed content by clicking within the _empty_ space just above or below the scrollbar handle, if any. However, clicking the handle itself, then trying to drag, does not have any effect.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
