### ISSUE TITLE
Possibility to open "external" links in independent Tab?

### ISSUE THREAD

**Issue by PalminX** [piroor/treestyletab#1843]
## Short description
I would like to have TST open all "external" links (i.e. opened from another application) in a new independent tab instead of as child of the current tab.
I was searching for a configuration option, but did not find anything that relates to this behavior.

## Steps to reproduce

 1. Have Firefox configured as default browser
 2. Open a link from an external application

## Expected result
 * The link is opened in a new independent tab

## Actual result
 * The link is opened in a new child tab of the current tab

## Environment

 * Platform (OS): Windows 7 
 * Version of Firefox: 59.0.1 (64 Bit)
 * Version (or revision) of Tree Style Tab: 2.4.18

**Comment by piroor** [comment]
The behavior you described is the default behavior of TST for me. Do you use any other addon to open new tabs next to the current tab, or did you configure TST to open any new tab next to current tab?

**Comment by piroor** [comment]
I close this because outdated.
