### ISSUE TITLE
Feature Request: New Layout for Container Groups

### ISSUE THREAD

**Issue by tradewatcher** [piroor/treestyletab#1845]
I use TST since many years but after FF57 it cant fit my personal needs anymore. I'm affected of the Tab Groups chaos and its fine to see you trying to solve this problem. I have to use the Addon "Sea Containers" since FF57 without a tree feature und heavy performance issues since FF59 but the Firefox Developer Jonathan Kingston is busy with more important Firefox projects and ask for help from the community for this small addon.

Maybe you can take a look on the Addon and implement the same Layout with your already existing features.

This would fix the following problems or improve TST:
1.  https://github.com/piroor/treestyletab/issues/1836 (Lock / Protect Tabs).
2. Better overview, grouping of container tabs and the option to "collapse/expand" a full container.
3. We dont need an extra Addon for hiding Tabs and no dependence from Hide Tabs API. Container feature will fix this automatically.
4. User with 20-40 pinned Tabs dont loose the overview of important tabs. (TST pinned Tabs sucks heavily compared to Sea Containers)
5. Context Menu entries for Tabs are working automatically and well in Sea Containers but not in TST. I miss 5-8 entries.
6. Bind the Sea Containers Users to TST and offer a tab/tree sidebar solution for all without losing important TST features from the last years.
7.  New Layout
8. In FF58 Sea Containers have a much better "performance" when i switch between Sea Containers and TST but only realizeable in the first seconds after the switch. After initalizing there is no difference in FF58. But this doesnt matter.

I'm sure you can find more improvements with implementing such a layout.

Sea Containers doesnt support Tree structure, there are heavy performance issues since FF59 (nobody know why), (until now its not possible to expand more than 1 container menu at the same time) and no support from the developer since a year.

I wont update my Firefox 58 until i have a solution for my container overview / tab hiding / tab tree / tab grouping problem. It was heavy enough to find a solution which works for FF57+ but i lost the Tree feature. Sea Containers is not very popular and I'm sure the developer will have no problem cause he ask for help, maybe you can offer such a "Layout" in TST configuration.

https://github.com/jonathanKingston/sea-containers

I'm also ready to donate some ETH/BTC for your great work if you make it possible for me to use TST again for the next years. Such a Layout would fix all my problems with tabs/groups. I'm sure I'm not alone.

Thanks and greetings from Austria.

**Comment by tradewatcher** [comment]
![grafik](https://user-images.githubusercontent.com/32960881/38419295-359b63a8-39a0-11e8-9cef-e86fa5979cc0.png)

**Comment by piroor** [comment]
I think that the usecase is quite different from TST's expected one. TST is just designed t control tabs as tree, and not designed to manage tabs based on containers. And, it won't be included to TST as a switchable mode, because I cannot maintain too much codes about features I never use. Sorry...

(Of course, TST is licensed under MPL and you can fork this project to match your usecase.)

**Comment by irvinm** [comment]
@piroor please close this.
