### ISSUE TITLE
Tabs restored from tab session manager session : tab groups  not restored

### ISSUE THREAD

**Issue by Adelscott** [piroor/treestyletab#1846]
## Short description
When restoring a session with multiple levels (2 to be honest), tab groups aren't restored, they appear empty at level 0

## Steps to reproduce

 1. Restore session within Tab Session Manager

## Expected result
Tab group
    Tab 1
    Tab 2

## Actual result
Tab group
Tab 1
Tab 2

## Environment

 * Platform (OS): Windows 10 64
 * Version of Firefox: 59.0.2
 * Version (or revision) of Tree Style Tab: 2.4.18
 * Version (or revision) of Tab Session Manager: 3.0.1 (Restore tree state of Tree Style Tab : checked)

**Comment by cosmicdan** [comment]
FYI, this is an issue with Tab Session Manager. Tree Style Tab has done it's best to be compatible with other "session restoring" extensions.

If you want a more compatible addon, give Sync Tab Groups a go. The developers have been working together to try and make a solution for this. See the issue and discussion here - https://github.com/piroor/treestyletab/issues/1662

**Comment by Adelscott** [comment]
Thanks I'm trying Sync Tab Groups. Not a very intuitive addon though ...

**Comment by zekeblue** [comment]
I didn't try it.  Looks pretty cool if you want to depend on groups instead of trees.  I couldn't see how it would integrate with TST though (without trying it anyway).  I'm using Tab Session Manager (https://addons.mozilla.org/en-US/firefox/addon/tab-session-manager/) with mostly success.  It remembers and restores the tree perfectly except for restoring with all trees expanded instead of existing expand/collapse state.

**Comment by cosmicdan** [comment]
> I didn't try it. Looks pretty cool if you want to depend on groups instead of trees. I couldn't see how it would integrate with TST though (without trying it anyway). I'm using Tab Session Manager (https://addons.mozilla.org/en-US/firefox/addon/tab-session-manager/) with mostly success. It remembers and restores the tree perfectly except for restoring with all trees expanded instead of existing expand/collapse state.

Sync Tab Groups is the only thing that comes close to [SessionManager](https://addons.mozilla.org/en-US/firefox/addon/session-manager/). I remember trying Tab Session Manager, and found it too clumsy and buggy to be a viable replacement. It's 2.5 star review average shows that I'm not alone in that experience.

I'm not sure what you mean by "depend on groups instead of trees". I thought the goal of all of these is to depend on groups?

**Comment by zekeblue** [comment]
All I can say is it works for me (except for the expanded trees issue).  Dev released 10 days ago, perhaps will work better with TST now if he thought it was a major enough upgrade for a 2.x to 3.0 designation.

My understanding is groups is a Firefox function that morphed into container tabs in quantum.  TST uses group tabs - are they the same as groups in Sync Tab Groups?  If you create a group in STG, does it create a tree (or branch) in TST?  I guess I have to try it now!

**Comment by cosmicdan** [comment]
> My understanding is groups is a Firefox function that morphed into container tabs in quantum. TST uses group tabs - are they the same as groups in Sync Tab Groups? If you create a group in STG, does it create a tree (or branch) in TST? I guess I have to try it now!

I don't know anything about the built-in Firefox group function or container tabs, just that each "group" in STG is a collection of tabs - a session - and the sessions are easy to switch between automatically. Maybe it does use this Firefox function internally, I don't know, but it's just seamless tab session swapping.

Indeed, I will have to try out this Tab Session Manager too, maybe it's gotten better.

**Comment by atondwal** [comment]
Hmm, in the TSM settings it says

> Delay when tree restoration (millisecond)

> To restore the state of the tree, wait time is required to open the tab. Increase this value if the tree is not restored correctly.

But I can't find a value of it that actually works

**Comment by cosmicdan** [comment]
> But I can't find a value of it that actually works

Is that something in TSM settings or TST?

For Sync Tab Groups, you need to disable the "Auto-group tabs opened within x" option for it to work properly, otherwise it (un)groups tabs randomly when restoring a session.

**Comment by atondwal** [comment]
> Is that something in TSM settings or TST?

TSM settings, sorry.

> For Sync Tab Groups, you need to disable the "Auto-group tabs opened within x" option in TST for it to work properly, otherwise it (un)groups tabs randomly when restoring a session. Sounds like it might be related.

I've already disabled that

---

Okay, I just installed and re-installed TSM and now it works fine for who knows what reason. (after it suddenly stopped working for me a few days ago...)

**Comment by irvinm** [comment]
@piroor please close this.  TSM and TST are obviously fully compatible at this point.

**Comment by cosmicdan** [comment]
> TSM and TST are obviously fully compatible at this point.

If I may ask, why obviously? I've been staying on Waterfox for the moment until Firefox's webextensions become a bit more mature so am out of the loop.

**Comment by irvinm** [comment]
@cosmicdan what I meant is there has been a lot of discussion around TST and TSM working together from other issues over the past year or so and the working state between the 2 addons is very good at this point.  (Sorry, I didn't mean to say that is was "obvious" just from the information in this single issue)
