### ISSUE TITLE
[Feature request] Bookmarks dialog

### ISSUE THREAD

**Issue by vstepaniuk** [piroor/treestyletab#1847]
Sorry if I missed similar issues, but could you please show a Bookmarks dialog, where one can choose the folder name and its location? (as with the native Firefox "Bookmark All Tabs")

**Comment by piroor** [comment]
If you use TST 2.x, it is impossible due to restrictions of WebExtensions APIs. Sorry.

**Comment by piroor** [comment]
This feature is now available.

**Comment by vstepaniuk** [comment]
Yes! Thank you. )
