### ISSUE TITLE
[Feature] Full Auto-show/hide Theme tweaking of left-margins

### ISSUE THREAD

**Issue by cameronleger** [piroor/treestyletab#1849]
## Short description
The tweaks in the Wiki for having an auto-show/hide setup for this extension are awesome. Some work was done to line the favicons up for the minimized version, but I don't think it goes far enough. In my opinion, the hierarchy looks weird because the favicons begin to cut off.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. [Apply tweaks](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#full-auto-showhide-theme)
 4. Open tabs to create a hierarchy

## Expected result
A (subjectively) nicer display of the hierarchy.

## Actual result
Favicons deeper in the hierarchy are cut off, sometimes completely.

## Environment
Latest

## Solution
I have a mock-up solution that I created after looking at this extensions debugging window. It seems that CSS for `data-level`s are hardcoded up to level 7 (8 levels). With that in mind, I've added this to the "Extra Style Rules" and it's working very well with animations and all. Fully minimized, the tabs basically line up down the line. During the hover and maximization, they slide out to a nested appearance.
```
.tab[data-level][data-level="0"] {
  margin-left: 2% !important;
}
.tab[data-level][data-level="1"] {
  margin-left: 4% !important;
}
.tab[data-level][data-level="2"] {
  margin-left: 6% !important;
}
.tab[data-level][data-level="3"] {
  margin-left: 8% !important;
}
.tab[data-level][data-level="4"] {
  margin-left: 10% !important;
}
.tab[data-level][data-level="5"] {
  margin-left: 12% !important;
}
.tab[data-level][data-level="6"] {
  margin-left: 14% !important;
}
.tab[data-level][data-level="6"] {
  margin-left: 16% !important;
}
```

**Comment by stefnotch** [comment]
@cameronleger Oh, that's a great tweak! Please do [edit the existing full auto-show/hide theme on the wiki](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules/_edit).

Note: I'm the person who originally added that theme to the wiki. The theme has been taken from reddit and tweaked a fair bit.

**Comment by stefnotch** [comment]
Thank you for taking your time to edit the theme. 🎉  Feel free to close the issue now.

**Comment by cameronleger** [comment]
Cool, I didn't know I could edit the wiki otherwise I probably would've done that from the beginning!
