### ISSUE TITLE
Tree Style Tabs NOT reducing height of children tabs

### ISSUE THREAD

**Issue by Ceyarrecks** [piroor/treestyletab#1852]
## Short description
Tree Style Tabs NOT reducing height of children tabs
## Steps to reproduce
install Firefox 59 on Ubuntu 16, install Tree Style Tabs, attempt to Open Link in New Tab, notice tab SAME HEIGHT as parent.

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): Ubuntu 16
 * Version of Firefox: 59
 * Version (or revision) of Tree Style Tab: 2.4.18

**Comment by piroor** [comment]
Could you describe what is expected and what is actual? Screenshots will help me more.

**Comment by piroor** [comment]
I close this because outdated.
