### ISSUE TITLE
[Feature request] click to switch to previous tab

### ISSUE THREAD

**Issue by nikomatsakis** [piroor/treestyletab#1853]
## Short description

I often find myself ping-ponging between two tabs. It would be nice if clicking on the current tab would switch me back to the previous one (sort of like how Alt-Tab works when changing windows.

**Comment by zekeblue** [comment]
I think this will do what you want:
https://addons.mozilla.org/en-US/firefox/addon/most-recent-tab/?src=search

**Comment by polyzen** [comment]
https://github.com/piroor/treestyletab#addons-extend-tst
https://addons.mozilla.org/firefox/addon/tab-flip-for-tree-style-tab/

**Comment by nikomatsakis** [comment]
woohoo thanks!
