### ISSUE TITLE
Can't move tab to the top (first position) of TST when there is no pinned tab

### ISSUE THREAD

**Issue by pintassilgo** [piroor/treestyletab#1855]
## Short description

I can't move tab to first position by drag and drop. If I set first tab `margin-top: 2px;` then I can, or if I pin one tab, so it's a matter of lack of space above the first tab.

## Steps to reproduce

 1. No pinned tab.
 2. At least two tabs opened.
 3. Drag anyone except the first and try to move to the first position.

## Expected result

![](http://i.imgur.com/YEO0QMG.png)
then
![](http://i.imgur.com/sdGPjYv.png)

(I used `#tabbar .tab:not(.pinned):first-of-type { margin-top: 2px; }` to take screenshot of the expected result, without that it wouldn't work)

## Actual result
![](http://i.imgur.com/p40QkOH.png)
then
![](http://i.imgur.com/2uyd4Cq.png)

## Environment

 * Platform (OS): Windows 10 x64
 * Version of Firefox: tested on DevEd 60.0b10 and Nightly 61.0a1 (2018-04-06)
 * Version (or revision) of Tree Style Tab: 2.4.18

**Comment by piroor** [comment]
Thanks, this is a regression and fixed by a8c092b.
