### ISSUE TITLE
Feature Request -- Expanding from Auto-Hide hovers instead of slides.

### ISSUE THREAD

**Issue by dgtexan** [piroor/treestyletab#1856]
## Short description
Feature Request:
Using the code provided from https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#auto-showhide-sidebar-by-mouseover-hover, Auto-Hide/Expand functionality is added. The feature I am requesting is mouse-over would expand TST sidebar over website window (as if sideways drop down) instead of shrinking website window to fit expanded sidebar. 

--Pictures below are fabricated with Greenshot, not actual behavior I was able to jury rig. 

## Current Behavior
![image](https://user-images.githubusercontent.com/38168748/38461179-ecf0b594-3a86-11e8-917f-399f47963832.png)
![image](https://user-images.githubusercontent.com/38168748/38461185-fbfd106e-3a86-11e8-86ba-7deec76d5016.png)

## Requested Behavior
![image](https://user-images.githubusercontent.com/38168748/38461175-d6e8b4e0-3a86-11e8-9d0a-8623a50231f7.png)
![image](https://user-images.githubusercontent.com/38168748/38461178-e60aff96-3a86-11e8-98e2-a4e09bc8dd2b.png)

## Notes
I understand if API limitations make this impossible, but maybe it isn't? Hopefully, someone could come up with a solution because I do not have the knowledge as of right now. Maybe I will look into it when I have time away from my 70-hr work/school schedule and homework and service projects on top of that, but I wouldn't bet the farm on it. 

Please let me know if you need any clarification or further information. If there is a simple solution, I have not been able to find it. I like to think I'm fairly capable with my google-fu, but I've been proven wrong before and have no problem admitting my incompetence if so. Thank you for any future help you may provide in this endeavor. 

## Environment

 * Platform (OS): Win10 Pro Insider Preview 17074.1002 (I know I need to update)
 * Version of Firefox: 59.0.2
 * Version (or revision) of Tree Style Tab: 2.4.18

**Comment by dgtexan** [comment]
So, there's no css code that can do this? I know the add-on cannot change side bar width. That's why I added the code snippet for expand on hover. The code snippets are a part of this git, that's why I asked here. If I'm mistaken, my bad.

**Comment by Lej77** [comment]
This userChrome.css code seems to do it:
```CSS
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] {  
  position: sticky;
  border-right: none;
}
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"]:hover {
  margin-right: -220px;
}
```

The `margin-right` value should be equal to `calc(var(collapsed-width) - var(expanded-width))`

**Comment by marrak** [comment]
If you have sidebar on the right you need change margin-right to margin-left.
