### ISSUE TITLE
Tree Style Tab 2.4.18 graphical issues with Firefox 59.0.1

### ISSUE THREAD

**Issue by Shmoobly** [piroor/treestyletab#1857]
## Short description
Tree Style Tab 2.4.18 graphical issues with Firefox 59
## Steps to reproduce

 1. Start Firefox 59 with clean profile on Windows 10 x64 rev 1709.
 2. Install TST. Use F1 to open TST.
 3. Tabs on left do not show text, show favicons randomly, and right click menu has no text. (Note: right-clicking tabs in top bar does show tab menu correctly)
 

## Expected result
TST tab name text shows legible text on tab names and right click menu. Favicons display on left of tab name.

## Actual result
TST tab name text is missing, TST tabs right-click menu is missing text. Favicons display erratically.

## Environment

 * Platform (OS): Windows 10 x64 rev 1709
 * Version of Firefox: 59.0.1
 * Version (or revision) of Tree Style Tab: 2.4.18

**Comment by Shmoobly** [comment]
I noticed after updating to Firefox 59.0.2, the graphical anomalies w/ TST are gone, and TST is functioning normally.

**Comment by piroor** [comment]
Is this issue closable?

**Comment by piroor** [comment]
I close this because outdated.
