### ISSUE TITLE
The child of a parent can be move weirdly.

### ISSUE THREAD

**Issue by aloisdg** [piroor/treestyletab#1858]
## Short description

The child of a parent can be move weirdly. 

## Steps to reproduce

 0. I dont know how. I will look if I can.

## Expected result

Children should be under the parent. I am not sure it is a bug or if I miss the logic.

## Actual result

![bug_tree](https://user-images.githubusercontent.com/3449303/38527789-e9143cca-3c5c-11e8-8cb0-4a8c78ecd83e.gif)

![bug_tree2](https://user-images.githubusercontent.com/3449303/38527954-c829d532-3c5d-11e8-88fa-2eae1d1a7893.gif)

## Environment

 * Platform (OS): Windows 10 64 bits
 * Version of Firefox: FF DE 60.0b6 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.4.18

**Comment by piroor** [comment]
I also see this problem sometimes. I still need clear steps to reproduce...

**Comment by aloisdg** [comment]
@piroor is there a way to export a tree as test? something like:

    // with pretty print

    ├── The child of a parent can be move weirdly. · Issue #1858 · piroor/treestyletab | https://github.com/piroor/treestyletab/issues/1858
    ├── data |  https://data.com/
    │   ├──  dataImg |  https://data.com/img.png
    │   └──  Yo! |  https://data.com/yo/
    ├── images  |  https://images.com/yo/
    │   ├── icon  |  https://images.com/icon/
    │   └── logo |  https://images.com/logo/
    └── readme  |  https://data.com/readme.html

and another one as json/yaml/toml/whatever with the id of the parent or something

it could be useful, couldnt it?

**Comment by Sada-Mio** [comment]
I've been having this problem too. 

Sometimes moving a tab, nothing seems to actually move graphically, but if I reload the sidebar or browser the tab actually moved. 

Sometimes moving a nested tree screws up other tree structures or tabs. The parent tab can be lost or merged into another tree. Closing tabs sometimes screws the tree even more. 

Not sure how to reproduce but it happens one a week  to me and I have to rebuild my tabs from scratch.

**Comment by piroor** [comment]
@aloisdg I think that exported tree won't help debugging, because it is *already* broken. I need to know what is the trigger breaking the tree structure. (Currently I think that drag-and-drop action seems to trigger the problem, but the detailed condition is still not clear.)

**Comment by Sada-Mio** [comment]
Things are getting weirder the longer I use TreeStyleTabs. 

I have 3 windows each with about 75-100 tabs nested. Usually when my tabs start arranging weird or go missing I would just restart firefox and it fixes up.

But, now one of my window has all of it's tabs missing or hidden except for just one. Restart didn't fix anything. If I try closing that one tab, it is replaced with one of the missing/hidden tabs. 

Wonder if it is a conflict with another add-on.  Is there a limit to how many tabs firefox can handle? I have over 250+

**Comment by piroor** [comment]
@alith Thanks, but I couldn't reproduce odd behavior after the steps.

 * Actually B2 is restored as a first child of B1 instead of the next sibling, but it is a designed behavior of TST. In this case, B2 is actually restored as the next of B1, and after that B2 is attached to B1 as its first child because B2 appeared between B1 and its first child C1.
 * After that, all child tabs from B1, B2, and C1 are opened at correct position for me as configured.
 * I tried with only few tabs. If you see any problem only with 100 or more tabs, "too much number of tabs" itself seems one of conditions to reproduce the problem.

**Comment by Sada-Mio** [comment]
"optimize tree restoration with cache"

With this enabled, could it be that TST gets confused with old cache after a hibernate/suspend and insert/remove tabs in the wrong places giving us these weird behaviors? Just guessing, no clue how the cache system works.

**Comment by Sada-Mio** [comment]
For those also having issues. Noticed after resuming PC hibernation, suspend or just prolong usage weird things can happen such as:
- moving tabs doesn't appear to actually move at all visually, but it actually did.
- tabs opening in wrong location 
- tabs missing/hidden or all tabs missing 

A work around solution is to disable TST and re-enable. Sometimes that doesn't fix things and adv setting option  "optimize tree restoration with cache" needs to be also un-checked/re-checked. Sometimes it takes several attempts. I do this at least once a day. 

Moving tabs to a new window can sometimes hide all tabs. Workaround is to open a new tab and tree will appear & tabs unhidden.

**Comment by irvinm** [comment]
@aloisdg, is this still a problem for you?  Is anyone still seeing this issue?  Can we close it?

**Comment by aloisdg** [comment]
@irvinm Yes. I removed the extension.
