### ISSUE TITLE
Working on compatiblity issues between TST & FF theme Classic Compact

### ISSUE THREAD

**Issue by KenInME** [piroor/treestyletab#186]
I'm the developer of the Firefox theme Classic Compact (https://addons.mozilla.org/en-US/firefox/addon/classic-compact/) and its companion extension Classic Compact Options (https://addons.mozilla.org/en-US/firefox/addon/classic-compact-options/).

Users have reported some minor incompatibilities between my addons and Tree Style Tab, which I'd like to iron out, but I need the assistance of TST developers.

The issue is with pinned tabs when vertical tabs are used. The problem is that my extension allows users to change the height of tabs and toolbars.  Unfortunately, with pinned tabs in TST this only partially works.  What I'm running into trouble with is that the negative top margin of pinned tabs is set dynamically by TST using the style attribute and this negative value is different depending on how many rows of pinned tabs there are.  Also, the top margin of the rest of the tab stack changes depending on the number of pinned tab rows there are.

If there were only ever one row of pinned tabs I could easily override TST style rules to get things positioned correctly.  With multiple rows of pinned tabs, however, I suspect I'll need to work with TST developers to make accommodations in both my addons and in TST so that our addons work together seamlessly.

I'm sure our mutual users would be very appreciative of our efforts if we could iron out the issues between our addons.

Ken Barbalace

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
