### ISSUE TITLE
Firefox version 59.0.2 is not recognized when trying to (re)install TST

### ISSUE THREAD

**Issue by vrws** [piroor/treestyletab#1860]
## Short description
After a reboot Firefox (v.59.0.2 64-bit on W10) started with all previous windows (5) and their tabs. The TST bar was empty showing only the reload icon (horizontal moving dot). All tabs worked fine when selected on the tab bar. I disabled TST and removed it. After restart of Firefox, re-installation is not possible "This add-on requires a newer version of Firefox (at least version 57.0). You are using Firefox 52.0."
Please find attached screen shots 

## Starting Firefox with clean profile
Firefox version is accepted and TST is installable

## Environment
 * Platform (OS): Windows 10 Pro
 * Platform (Version):10.0.16299
 * Version of Firefox:  59.0.2
 * Version (or revision) of Tree Style Tab: newest
 * installed add-ons: Kaspersky Protection + Adobe Acrobat (both disabled)

## Screen shots
![firefox-v59_0_2-too-old](https://user-images.githubusercontent.com/13646641/38612875-90485574-3d77-11e8-8fac-d5af12d3ca75.png)
![firefox-v59_0_2-too-old-addons](https://user-images.githubusercontent.com/13646641/38612882-97fe4ed6-3d77-11e8-84b9-5ee7dc093e36.png)
![firefox-v59_0_2-too-old-config](https://user-images.githubusercontent.com/13646641/38612883-9b1f374c-3d77-11e8-9a11-63689040e59c.png)

**Comment by piroor** [comment]
Did you modify `general.useragent.override` or other related preferences?

**Comment by overdodactyl** [comment]
This happens as a result of setting `privacy.resistFingerprinting` to `true` via `about:config` (one of its many features is to spoof the UA to the latest ESR version).

You can still download/use the extension however.  As  workaround, you can do one of the following to download it:

* Temporarily turn of the setting

* Right click the `+ add to Firefox` button and select `open in new tab` (in my experience, this has only worked sometimes)

* Right click the `+ add to Firefox` button and download the file as an `xpi`.  You can then upload the `xpi` file via `about:addons` (from the gear/settings button).

Relevant bugzilla link:

https://bugzilla.mozilla.org/show_bug.cgi?id=1394448

**Comment by vrws** [comment]
Thank you very much, overdodactyl
for your valuable solution to my problem! I was missing TST very much already.
For me it worked to disable "privacy.resistFingerprinting", select TST for download and added it to FF.
Everything works fine.
Volker

Thanks again for your help
