### ISSUE TITLE
Where are the permissions?

### ISSUE THREAD

**Issue by colemickens** [piroor/treestyletab#1870]
I've been looking for 20 minutes and I can't find anything anywhere that describes how to allow permissions for this extension. I've seen it before after install, but never since then.

**Comment by Lej77** [comment]
The page you are describing that shows up at startup has the URL: `moz-extension://%Extension-id%/resources/startup.html` where `%Extension-id%` should be replaced with the extensions random id. You can find information on how to open such a page in #1725 (the second comment, the part after the divider line). 

You can also find all of these settings in Tree Style Tab's option page. There are two permission that can be allowed. The first is a context menu item to `Bookmark this Tree` and this can be found under the `Additional Context Menu Items` header. The second option with a permission is called `Don't expand collapsed tree and skip collapsed descendants, while switching focus of tabs via keyboard shortcuts (requires script injection to webpages for detection of keyboard operations.)` and can be found under the header `Tree Behavior`.

**Comment by colemickens** [comment]
Wow, what a detailed answer. Thanks very much!
