### ISSUE TITLE
How do I get rid of this tab from appearing when opening multiple tabs in tree style tab with snap link plus please? Thanks

### ISSUE THREAD

**Issue by ng4ever** [piroor/treestyletab#1871]
https://i.imgur.com/UB6oxe2.jpg

The tab in the yellow circle please. Thanks.

**Comment by Lej77** [comment]
Tree Style Tab is by default configured to group multiple new tabs that are created at the same time. This behavior can be disabled in Tree Style Tab's option page. The options affecting you is called `Auto-group tabs opened within` and is located under the header `New Tabs Behavior`.

Tree Style Tab also uses such tabs when it groups tabs opened from the same pinned tab. This behavior can be disabled with the option `Auto-group tabs opened from same pinned tab` and is also located under the header `New Tabs Behavior`.

**Comment by irvinm** [comment]
@piroor please close this.
