### ISSUE TITLE
Moving nested tab downwards (Ctrl-Shift-Pagedown) doesn't detach tab from tree

### ISSUE THREAD

**Issue by jimbo1qaz** [piroor/treestyletab#1874]
## Short description
When I move a nested tab (within a tree) downwards (Ctrl-Shift-Pagedown), it remains indented, even if I move it past the end of the tree (there are unindented tabs above the tab).

## Steps to reproduce

1. Start Firefox with clean profile.
2. Install TST.
3. Setup your tabs:
```
▼A
   B (selected)
 C
```
 4. Press Ctrl-Shift-PageDown.

## Expected result
```
 A
 C
 B (selected)
```
B could be above or below C, depending on how you want it to work.

## Actual result
```
▼A
 C
   B (selected)
```

## Environment

 * Platform (OS): Windows 10 x64
 * Version of Firefox: Dev 60.0b14 (64-bit)
 * Version (or revision) of Tree Style Tab: Latest dev

I noticed recurring shortcut-related issues with your extension, over the past few years (#998, etc). After enabling " Don't expand collapsed tree and skip collapsed descendants, while switching focus of tabs via keyboard shortcuts", why does it take close to a second when moving to a collapsed tree with `Ctrl-PageUp`, before it expands and the previous tree contracts? Do you not use keyboard shortcuts, and consequently not test that they work while developing your extension? (This is not the first time shortcuts have broken this extension)

Maybe most other users don't use shortcuts, or maybe many people are affected but none have reported the issues.

Should I file a separate bug for that?

**Comment by piroor** [comment]
Thanks, this was a regression and fixed by the commit 9afb336.
