### ISSUE TITLE
Firefox sends request twice

### ISSUE THREAD

**Issue by jazzl0ver** [piroor/treestyletab#1878]
Sorry for skipping the issue guidelines. It just looks simple and weird:
When I open an URL, for example, https://mydomain.com/path/spacer.gif, FF sends several requests - I see them on the server:
haproxy[6222]: a.b.c.165:43436 [27/Apr/2018:10:38:54.479] front~ front/Prod_155_SSL 21033/0/0/1/21034 200 1092 - - --VN 94/94/2/2/0 0/0 "GET /path/spacer.gif HTTP/1.1"
haproxy[6222]: a.b.c.165:44265 [27/Apr/2018:10:38:54.478] front~ front/Prod_155_SSL 45794/0/0/1/45795 200 1092 - - --VN 94/94/6/6/0 0/0 "GET /path/spacer.gif HTTP/1.1"

Sometimes, there might be 3 log entries for a single request.

When I disable TST extension, FF starts to send a single request as expected. 

Any ideas why this happens?

 * Platform (OS): Windows 7 x64
 * Version of Firefox: 59.0.2
 * Version (or revision) of Tree Style Tab: 2.4.18

**Comment by cipri-tom** [comment]
I think I've seen something similar and it is about the favicon: it needs a separate request to get the favicon of the website

**Comment by jazzl0ver** [comment]
Yeah, sometimes it asks for favicon, but this is not the case here. Check
the haproxy log entries I included - they shows FF requests the same URL
twice.

On Sat, Apr 28, 2018 at 12:31 AM, Ciprian Tomoiaga <notifications@github.com

**Comment by jazzl0ver** [comment]
After starting from scratch with an empty profile, the issue disappeared. Looks like there was something in my very old profile. Sorry for bothering.
