### ISSUE TITLE
native "add bookmark" dialogue missing when treestyletab is installed

### ISSUE THREAD

**Issue by br4nnigan** [piroor/treestyletab#1880]
## Short description
treestyletab bugs out firefoxs' add bookmark behavior

## Steps to reproduce

 1. Start Waterfox with clean profile.
 2. Install TST.

press ctrl + d

## Expected result
call "add bookmark" dialogue (where location and name can be chosen)

## Actual result
bookmark is immediately added to the bookmarks menu root

## Environment

 * Platform (OS): Windows 7 
 * Version of Firefox: Waterfox 56.1.0 (64-bit)
 * Version (or revision) of Tree Style Tab: **legacy**

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
