### ISSUE TITLE
[feature request] "Send to top" and "Send to bottom" operations on tabs

### ISSUE THREAD

**Issue by glaebhoerl** [piroor/treestyletab#1881]
# Summary

I would like a button (or menu item, or shortcut) to immediately move a tab to the top (beginning) or bottom (end) of the tab sidebar.

# Motivation

The tab bar essentially functions for me as a LIFO stack: I open Twitter, or google for something that interests me, open a bunch of interesting links in background tabs, read one of them, close it, read the tab which gets focused next, close it too, and so on, until none are left.

The problem is that "none are left" doesn't happen. Instead there is some tab that feels like too much effort to read right now, but I still want to get back to it later. So I can't just close it. So... maybe I should switch to the tab above it? Oh no, that is the *other* too-much-effort tab which I also left there, last time. And the same for the one above that. Restlessness sets in, I want to *do* something, not just sit there, so I... open Twitter again, open more interesting links in tabs, and the cycle repeats.

The result is that my tab bar is like an archaeological excavation, going upwards: at the bottom are the current tabs; as we move up, we see the merely recent tabs; now, this here is the layer of stale tabs; here you can see the old tabs; the very old tabs; the very, *very* old tabs; the antiquated tabs; the prehistoric tabs.

What would be helpful is an actual "I will get back to this later" button, that sends the tab to the back of the line without closing it, allowing me to immediately make a decision on every tab: read now, or send away for later, letting me efficiently skip through clumps of tabs which don't interest me right now to the ones behind them which do. Eventually, I might get "all the way around", until a tab I had sent to the back is now at the front again: then I can cycle through the remaining tabs to find the one I am most equipped to deal with right now, or, if I find that I've been sending a tab away too many times, I can decide that I'm never actually going to read this, and close it.

All in all I think this small feature would let me manage my tab situation much more productively and effectively.

(One might be tempted to say "why don't you just ...": drag-and-drop, or use a bookmarking service, or ...: I have of course tried many other solutions before this, and they don't work well for me. Or only work well in periods when I'm unusually effective and productive at dealing with things *in general*. That is, when I don't have the problem in the first place. In particular, drag-and-drop is way too cumbersome with a big tab bar, and bookmarking ends up being equivalent to "I will never look at this again".)

# Details

I would prefer to have this as a button on the active tab, or maybe as a keyboard shortcut, but if that's not possible, a context menu item would still be better than nothing.

Since the intent is "send this away, I want to deal with it later", focus should *not* stay with the tab: it should move to the next tab, as if I had closed it. This is very important.

If there are any tabs pinned to the top of the tab bar, "send to top" should of course *not* move the tab above those, only above the normal, un-pinned tabs.

Since we have not only tabs, but trees of tabs, there are multiple possible ways for the features to interact. The only one I really care about is being able to send a tab, or a top-level tree of tabs, to the top of the whole tab bar. If I can also do things like send a tab to the top of its subtree, that's fine, but I don't really need it.

I've been talking about "send to top" so far. The reverse, "send to bottom", would also be useful: if I scroll through my tab bar and see some particular tabs I would like to "increase the priority of", I can send them to the bottom so I will get to them sooner.

# Meta

I searched for several keywords and keyphrases in case this has been suggested before, and didn't find anything. If it's a duplicate, I'm sorry.

(I also tried searching addons and didn't find anything.)

This is as much a "request for information" as a "request for feature": would this feature fit in with TST? If yes but it's low priority, would a pull request be accepted? Could or should it be an [addon to extend TST](https://github.com/piroor/treestyletab#addons-extend-tst) instead? Or is there some other extension which already provides it? Is it even possible to implement this using the APIs provided by the browser?

(This ended up being long, sorry... I decided I'd rather risk being too thorough than not clear enough.)

**Comment by piroor** [comment]
I think it should be done by another addon created for the purpose. It will be possible to add extra context menu item for TST's fake context menu via API, and if needed I'll add more APIs required.

**Comment by glaebhoerl** [comment]
Wow, I just noticed that this feature seems to have been added after all! Thanks so much!

(I suppose this means the issue can be closed, so I will do that.)
