### ISSUE TITLE
Sometimes a tab doesn't appear in the sidebar

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#1884]
## Short description
When the extension [Conex by kesselborn](https://addons.mozilla.org/firefox/addon/conex/) is installed it will attempt to make new tabs in the same container as the current tab. To do this it closes and then reopens new tabs in the correct container. Sometimes when this is done the reopened tab doesn't appear in Tree Style Tab's sidebar. Closing and reopening the sidebar will show any of these "missed" tabs.

### Tree Style Tab Console log

Tab appears in TST Sidebar:
![success](https://user-images.githubusercontent.com/31554212/39970389-a7d15baa-56ea-11e8-8965-a390d242bc53.png)

Tab doesn't appear in TST Sidebar:
![failed](https://user-images.githubusercontent.com/31554212/39970394-baf17328-56ea-11e8-8213-2444a3b68f08.png)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install [Conex by kesselborn](https://addons.mozilla.org/firefox/addon/conex/).
 4. Open a container tab and make it the current tab.
 5. Open a new tab. (For example by pressing the new tab button or using the `ctrl+t` shortcut.)

## Expected result
The new tab will be closed and reopened with the same container as the last tab.

## Actual result
The new tab is closed and reopened with the same container as the last tab. But the new tab doesn't always appear in Tree Style Tab's sidebar. About 50% of the time it does but the rest of the times it doesn't.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 60.0
 * Version (or revision) of Tree Style Tab: 2.4.19

**Comment by piroor** [comment]
Thanks! This problem seems to be fixed by recent commits.
