### ISSUE TITLE
Keyboard shortcuts to scroll sidebar applies to all windows

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#1885]
## Short description
The shortcuts to scroll the sidebar such as `alt+shift+home` scrolls the sidebars in all windows. It would be better if it only scrolled the sidebar in the focused window.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Have several windows open.
 4. Open enough tabs in each window that the sidebars can scroll.
 5. Use a keyboard shortcut to scroll the sidebar. For example `alt+shift+home`.

## Expected result
Only the sidebar in the focused window should scroll.

## Actual result
All sidebars for all windows scroll.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 60.0
 * Version (or revision) of Tree Style Tab: 2.4.20

**Comment by piroor** [comment]
Thanks, the commit 249fa91 should fix this.
