### ISSUE TITLE
Group tabs always loaded on Firefox startup

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#1887]
## Short description
If Firefox is configured to restore the tabs from the last session on startup then any group tabs in the last session will be loaded at startup. If there are a lot of them this can cause slight performance issues so it would be nice if they could remain unloaded.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open some group tabs. (For example by holding `ctrl+t` for a second or by using the URL `about:treestyletab-group`.)
 4. Ensure that the active tab isn't a group tab.
 5. Configure Firefox to restore the last session on startup.
 6. Restart Firefox.

## Expected result
When the tabs from the last session is restored all but the active tabs should be unloaded.

## Actual result
When the tabs from the last session is restored all group tabs are loaded even if they aren't the current tab.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 60.0
 * Version (or revision) of Tree Style Tab: 2.4.20

**Comment by piroor** [comment]
I think the commit 2a4ce74 should fix this, but possibly still there are some unfixed cases.

**Comment by Lej77** [comment]
I tested TST 2.4.20.6831 and it seems this issue is fixed.
