### ISSUE TITLE
Context menu requires enter key to be pressed when using keyboard shortcuts

### ISSUE THREAD

**Issue by aaaddd4747** [piroor/treestyletab#1889]
## Short description
Context menu shortcut keys require the enter key to be pressed in order to execute now. It's highly annoying and unexpected.
This only applies when you right click on a tab in the tree, using the normal tabs results in the correct behavior
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Right click on any tab in your tree.
 4. Select any option using a keyboard shortcut (ex: "R" for reload tab).

## Expected result
The action is executed

## Actual result
The action is selected

## Environment

 * Platform (OS): Windows 7
 * Version of Firefox: 60.0 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.4.20

**Comment by piroor** [comment]
Thanks, it was a problem of the library itself. This will be fixed on the next release.
