### ISSUE TITLE
Fake context menu items not cleared for extensions that unregister.

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#1892]
## Short description
When the extension [UnloadTabs by NiklasG](https://addons.mozilla.org/firefox/addon/unload-tabs/) unregisters from Tree Style Tab its context menu items stay in the fake context menu. Also the title for the parent context menu item is set to an empty string which causes the fake context menu to show a scrollbar.

[UnloadTabs code that produces the problem](https://github.com/NiklasGollenstede/unload-tabs/blob/master/background/tst.js)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install [UnloadTabs by NiklasG](https://addons.mozilla.org/firefox/addon/unload-tabs/).
 4. Open UnloadTabs option page.
 5. Check and then uncheck `Dim unloaded Tabs and add context menu options.`

## Expected result
Fake context menu items for the UnloadTabs extension should be removed.

## Actual result
Fake context menu items for the UnloadTabs extension remains in the sidebar's fake context menu. Also the parent context menu item's title is set to an empty string which causes the sidebar to show a scrollbar.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 60.0
 * Version (or revision) of Tree Style Tab: 2.4.21

**Comment by piroor** [comment]
Thanks. The commit ce6171d should fix this problem.
