### ISSUE TITLE
TST does not focus next unread sibling tab after having switched to parent tab

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#1895]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. middle click [any link 1](https://github.com/piroor/treestyletab/blob/master/history.en.md) so it opens as a unread background child tab.
 4. Switch to first child tab. Switch back to parent tab.
 5. Middle click [any link 2](https://github.com/piroor/treestyletab/blob/master/history.en.md) and [any link 3](https://github.com/piroor/treestyletab/blob/master/history.en.md) (all 3 links provided are the same).

Now we have 
```
Parent
\- B, link1 (read)
\- C, link2 (unread)
\- D, link3 (unread)
```
 6. Switch to tab C. Close it by clicking the close button, middle clicking, or ctrl-w.

## Expected result
Tab D should now be focused.

## Actual result
Parent tab is focused instead.

## Environment

 * Platform (OS): Win10 1803
 * Version of Firefox: Current Nightly
 * Version (or revision) of Tree Style Tab: 2.4.21 (It is a long standing issue which I now find the exact STR)

## Note
1. If I open tab B,C,D in succession without switching to B then back to parent, keeping all as unread, the issue is not present.
2. If I switch to tab **_C and D in this order_** making them as read before closing C, the issue is not present.
3. HOWEVER, If I switch to tab **_D then C_** instead, closing C, the issue _is present_; closing D is ok though.
4. The issue also affects the option "When the current tab is closed as a last child".

There should be some more complicated cases involving other tress, or different orders of focusing and closing of tabs. But I guess it may be stemmed from the same problem.

Thanks you.

**Comment by Fanolian** [comment]
Looks like setting `browser.tabs.selectOwnerOnClose` to false fixes the problem. But it is not the default behaviour of Firefox

**Comment by piroor** [comment]
As you wrote, it is not a bug but a feature of Firefox itself.

TST is designed to be compatible with such focus control features (including other addons). When the opener tab is focused by Firefox, TST guesses that something special focus control mechanism worked and give up to do by self. In other words, TST controls focusing after the current tab is closed only when the next tab is focused (because it is the plain behavior with no extra focus control).

**Comment by irvinm** [comment]
@Fanolian can you close out this item?

**Comment by Fanolian** [comment]
As of 3.0.11, the workaround `browser.tabs.selectOwnerOnClose` is not needed.
