### ISSUE TITLE
Tree Style Tab causes pages to be loaded twice

### ISSUE THREAD

**Issue by pbarney** [piroor/treestyletab#1896]
## Short description

Tree Style Tab does two page requests every time a page is loaded or refreshed.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Go to a webpage on a server where you have access to Apache's access.log
 4. Load a page from that server.
 5. Notice two entries in the server log file.

## Expected result

I would expect that it would not need to load a page twice.

## Actual result

It loads a page twice. Here is the access.log after requesting a page with a brand new profile with only TST loaded:

```
127.0.0.1 - - [18/May/2018:17:25:25 -0400] "GET /index.html HTTP/1.1" 200 -
127.0.0.1 - - [18/May/2018:17:25:25 -0400] "GET /index.html HTTP/1.1" 200 -
```

## Environment

 * Platform (OS): Windows 7 SP1
 * Version of Firefox: 59.0.2 (64 bit)
 * Version (or revision) of Tree Style Tab: 2.4.21

**Comment by Lej77** [comment]
Might be related to #1878.

**Comment by piroor** [comment]
@pbarney This doesn't happen for me except requests for favicon.ico. Steps to confirm on Ubuntu:

 1. Start HTTP server: `sudo ruby -run -e httpd /tmp -p 80`
 2. Start Firefox and activate TST.
 3. Open new tab: `http://localhost/`

The log:

```
127.0.0.1 - - [21/May/2018:12:00:44 JST] "GET / HTTP/1.1" 200 8020
- -> /
[2018-05-21 12:00:44] ERROR `/favicon.ico' not found.
127.0.0.1 - - [21/May/2018:12:00:44 JST] "GET /favicon.ico HTTP/1.1" 404 279
- -> /favicon.ico
[2018-05-21 12:00:44] ERROR `/favicon.ico' not found.
127.0.0.1 - - [21/May/2018:12:00:44 JST] "GET /favicon.ico HTTP/1.1" 404 279
- -> /favicon.ico
```

The first is by Firefox self, the second is by TST. Currently TST accesses favicon.ico by self due to a restriction of WebExtensions API. (See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1315616 )

**Comment by piroor** [comment]
I close this because outdated.

**Comment by stefnotch** [comment]
Out of curiosity, what does "outdated" mean in this context? Does it mean that tree style tab now uses a different way to fetch the favicon?

**Comment by piroor** [comment]
Because Firefox now represents tabs with Data: URL favicons (sorry but I don't know when the spec was changed) thus TST won't fetch raw favicons directly anymore.
