### ISSUE TITLE
Desktop file (e.g. internet shortcut) drag'n'drop support

### ISSUE THREAD

**Issue by suiryc** [piroor/treestyletab#1897]
## Short description
TST (WebExtension version) does not handle drag'n'dropping desktop file in its sidebar, especially "Internet shortcut" files.
Legacy (not WebExtension) version, as well as FireFox when dropping the file in the top bar, handle this. So maybe it can also be done in the new TST WebExtension version ?

## Steps to reproduce
1. Create an internet shortcut file by drag'n'dropping a page (from the url bar - clickable left part where site information can be displayed) to the desktop.
2. Drag'n'drop the created shortcut file from the desktop inside the TST sidebar

## Expected result
The same that happens in legacy TST, or when dropping the file in the top bar:
If file is dropped on an existing tab, this tab loads the page pointed to by the internet shortcut file.
If file is dropped before first tab, between two tabs, or after last tab, a new tab is created at the specified location and loads the page.

## Actual result
Nothing happens in latest TST: page is not loaded (or tab not created when applicable).
There is only the visual hint of where the element would be dropped, and when staying over a tab long enough TST switches focus to this tab.

## Environment

 * Platform (OS): Windows 10 1803 x64
 * Version of Firefox: 60.0.1
 * Version (or revision) of Tree Style Tab: 2.4.21

**Comment by Keith94** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1266960

**Comment by Keith94** [comment]
@piroor It's a dupe also (#1420)

**Comment by piroor** [comment]
@Keith94 Thanks!
@suiryc This is quite same to #1420, so I close this. Please drr the old issue to track status of this problem.

**Comment by suiryc** [comment]
Sorry. Even though I searched through tickets, I really didn't spot this one ...
Thanks for the info. Will follow the original issue.
