### ISSUE TITLE
Context menu shortkeys doesn't affect submenu if a separator is hovered

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#1901]
## Short description
If a separators item is hovered in a sub-menu of the fake context menu then the keyboard shortcut affect the root menu instead of the sub menu.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Right click a tab.
 4. Go into the `Tree Style Tab` sub-menu.
 5. Move the mouse above one of the three separators.
 6. Use on of the shortkeys for the sub-menu. For example `r` to reload the tree.

## Expected result
The reload tree item should be selected and activated.

## Actual result
The reload tab item is selected and activated.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 60.0.1
 * Version (or revision) of Tree Style Tab: 2.4.21

**Comment by piroor** [comment]
Thanks, it was a bug of the library to implement menu-like UI.

**Comment by Lej77** [comment]
Great!
