### ISSUE TITLE
Unable to drag or move tab 

### ISSUE THREAD

**Issue by as3mbus** [piroor/treestyletab#1902]
## Short description
I am just trying to configure stuff based on the snippet in the wiki.
but suddenly after i restarted nightly for update. dragging tabs using TST arent workin anymore. 
i tried with empty profile results the same way as my default profile

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. try to move tab by dragging
 4. tab isn't moved anymore

## Expected result
Tab moveable using drag

## Actual result
it wont even move. it looks like when im dragging a component that runs back after i release the drag 

## Environment

 * Platform (OS): Arch Linux 
 * Version of Firefox: Nightly 62.0a1
 * Version (or revision) of Tree Style Tab: 2.4.21

**Comment by cg9999** [comment]
Same issue here, also on Arch, same versions as above

**Comment by as3mbus** [comment]
fixed at the following version (might be caused by mozilla) : 
62.0a1 (2018-05-25) (64-bit)
