### ISSUE TITLE
Add a way to close the child tabs

### ISSUE THREAD

**Issue by Nexen23** [piroor/treestyletab#1904]
There is no way close only child tabs for specific tab right now. 
It would be amazing to have this feature.

**Comment by piroor** [comment]
Sorry, this feature was removed from TST 2.x intentionally. Instead I recommend you to use TST with [Multiple Tab Handler](https://addons.mozilla.org/firefox/addon/multiple-tab-handler/). It provides ability to "select" multiple tabs and close them. Moreover, dragging on closeboxes of TST's sidebar also closes multiple tabs at a time.
