### ISSUE TITLE
Scroll bar jumps to the beggining or middle of list

### ISSUE THREAD

**Issue by jedwabny** [piroor/treestyletab#1905]
## Short description
If more pages are opened than can be hold on the vertical list of tree style tab (I have tens), so scroll bar appears, then each time the another tab is clicked the scroll bar jumps to the top (sometimes somewhere in the middle of list).
It's incredible uncomfortable to navigate through the opened tabs if these are somewhere at the end of list. Each time after action, it's needed to scroll down back to the bottom.
Sometimes it start working properly after a few hours, but after restart the browser it happens again.

## Steps to reproduce

 1. Start Firefox with a significant number of opened pages (tabs). The number of tabs has to be more than can be fit on the screen, so scroll bar appears.
 2. Scroll down to the bottom and click on one of the tabs there.
 3. Try to click on any other tab

## Expected result
The scroll bar should not move at all if the chosen page is placed within the range.

## Actual result
Scroll bar jumps to the top (sometimes somewhere in the middle of list) completely lost the position that contains the page.

## Environment

 * Platform (OS): Debian Linux
 * Version of Firefox: 64.0 (64bit)
 * Version (or revision) of Tree Style Tab: 2.4.21

**Comment by piroor** [comment]
Duplicated of #1770?

**Comment by mjd80** [comment]
Yes, indeed it looks the same.
Even workaround similar to described there, collapse and expand all the tabs, fixes the problem.
