### ISSUE TITLE
Integration bug with "open tabs next to current" extension

### ISSUE THREAD

**Issue by tgoodlet** [piroor/treestyletab#1906]
When using the [open tabs next to current](https://github.com/sblask/webextension-open-tabs-next-to-current) extension it seems `treestyletab` takes forever to startup after an upgrade - dancing dot in the tab pane; tabtree never displays. The only solution seems to be to uninstall the [open tabs next to current extension](https://github.com/sblask/webextension-open-tabs-next-to-current) and then reinstall it (potentially also re-installing `treestyletab`).

I can't seem to figure out exactly how to replicate unfortunately.
I will report back once I reproduce again.

## Steps to reproduce
Install both addons, wait for a `treestyletab` update, restart firefox.

## To Fix
Disable `open tabs next to current` and enable `treestyletab`.
Re-enable `open tabs next to current`

Also if there is some way to get the functionality from `open tabs next to current` and I just don't know about it I'd appreciate the tip :+1: 

## Environment

 * Platform (OS):  Archlinux
 * Version of Firefox: 60.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.4.21

**Comment by Keith94** [comment]
In a future version of Firefox, you can toggle `browser.tabs.insertAfterCurrent` in about:config to get the desired behavior, making the extension obsolete. See https://github.com/sblask/webextension-open-tabs-next-to-current/issues/58

**Comment by tgoodlet** [comment]
Oh that's just fantastic! Thanks for the tip!
