### ISSUE TITLE
Drag & Drop handling needs optimization

### ISSUE THREAD

**Issue by br4nnigan** [piroor/treestyletab#1908]
Someone will probably agree with me. It's really hard to find the exact drop area within trees. It's behaving unexpectedly and unreliably. In general it is a hassle, and imo TSTs biggest flaw.

**Comment by piroor** [comment]
Looks too less information, too wide range of targeted topics. I need exact steps to reproduce the problem you actually seen.

**Comment by piroor** [comment]
I close this because outdated.
