### ISSUE TITLE
Set "guess new tab" with "about:blank" will cause bookmark etc. to be controlled by new tab behavior

### ISSUE THREAD

**Issue by fireattack** [piroor/treestyletab#1910]
## Short description

When you set `guess a newly opened tab as opened by "new tab" action, when it is opened with the URL` to `about:blank`, it will consider other opened tab (from bookmark, location bar, etc.) as a "new tab". 

## Steps to reproduce

1. Start Firefox with clean profile.
2. Install TST.
1. In `behavior for new tab actions (other toolbar buttons, keyboard shortcuts, and others)`, choose "a child of the current tab" for `Open new blank tab as`. Then, change `guess a newly opened tab as opened by "new tab" action, when it is opened with the URL` to `about:blank`.  Like this: ![cej2d _ viw0ozf6jzx5woe](https://user-images.githubusercontent.com/4130991/40605700-d5f1db56-6228-11e8-91f2-f53e51bdb357.png)
1. Now, open any tab (like google.com).
1. Use either: bookmark bar middle click OR location bar + alt-click to open any website (do not use the same website, since it may be affected by another setting) in another tab.

## Expected result

The newly opened website/tab should be an independant tab. 

## Actual result

It opens as the child of the current tab, since for some reason it was considered as a "new tab" once you set that setting to `about:blank`, despite the fact that I didn't open a `about:blank` tab.

Note: I have to set it to `about:blank` for it to work on actual new tab, because I disabled about:newtab (Fx options->home->new tabs->Blank page).

## Environment

 * Platform (OS): Win 7
 * Version of Firefox:  Nightly (5/28)
 * Version (or revision) of Tree Style Tab: 2.4.21.6859 (dev)

**Comment by piroor** [comment]
Sadly it is impossible to detect actual new tab opened by Ctrl-T if it has no special URI.

 * Because there is no API to know what command opens the tab, guessing from URI is the last way to guess commands.
 * Tabs on Firefox are always opened with the initial URI `about:blank`. When you open new tab from bookmarks or links, those tabs are opened with `about:blank` at first, and started loading of actually expected URIs later.

Another approach: if Firefox allows for addons to override Firefox's builtin keyboard shortcuts like Ctrl-T, you'll be able to open new tabs as expected by setting Ctrl-T as the shortcut for a special command: "open new tab as child". Please see a bug of Firefox itself: https://bugzilla.mozilla.org/show_bug.cgi?id=1325692

**Comment by fireattack** [comment]
I know the first part, but didn't realise the second ( tabs are opened with about:blank at first). Thanks for the explanation. 

It's not really an issue for my usage, just something I noticed when playing with TST. So no big deal.

**Comment by irvinm** [comment]
@fireattack can you close out this issue or is there more to discuss?

**Comment by fireattack** [comment]
I think that's it, thanks.

**Comment by mzso** [comment]
For me opening as child tab doesn't work in any way. Made sure FF is set to use firefox homepage. Enabled guessing for about:newtab. But it always opens as next sibling.
Are there any other factors?

**Comment by piroor** [comment]
@mzso Does your case still happen? Could you investigate and describe how to reproduce the problem with a clean profile?

**Comment by mzso** [comment]
[**@piroor**](https://github.com/piroor) commented on [2021. ápr. 22. 16:48 CEST](https://github.com/piroor/treestyletab/issues/1910#issuecomment-824908646 "2021-04-22T14:48:36Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso) Does your case still happen? Could you investigate and describe how to reproduce the problem with a clean profile?

<del>Not sure, things are weird. Even when I set the FF homepage (even in a new profile) for new tabs I get blank tabs.</del> <del>I guess this is my doing via policies, yet:</del> Nope, not this either, anyway the Firefox homepage  doesn't open, even in a new profile:

 So I change it to empty page in TST, but it still opens up as a sibling tab, instead of a child.

**Comment by mzso** [comment]
Okay, so even though the keeping it at firefox homepage in a new profile a new tab will be empty for some reason, but also for some reason the setting for as child works, unlike with my main profile. So I have no ideas.

**Comment by piroor** [comment]
@mzso What operation do you use to open a new tab? I've tried following operations on Nightly 90.0a1:

* operations handled by Firefox
  * keyboard shortcut "Ctrl-T"
  * "+" in Firefox's native tab bar
  * middle click in a blank area of Firefox's native tab bar
  * "File" => "New Tab" in Firefox's menu bar
  * "New Tab" in Firefox's application menu
  * "New Tab" in Firefox's tab context menu
* Operations handled by TST
  * "+" button in TST's sidebar,
  * double click in a blank area of TST's sidebar
  * middle click in a blank area of TST's sidebar

**Comment by mzso** [comment]
[**@piroor**](https://github.com/piroor) commented on [2021. máj. 1. 17:28 CEST](https://github.com/piroor/treestyletab/issues/1910#issuecomment-830649974 "2021-05-01T15:28:16Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso) What operation do you use to open a new tab? I've tried following operations on Nightly 90.0a1:
> 
> *   operations handled by Firefox
>     *   keyboard shortcut "Ctrl-T"
>     *   "+" in Firefox's native tab bar
>     *   middle click in a blank area of Firefox's native tab bar
>     *   "File" => "New Tab" in Firefox's menu bar
>     *   "New Tab" in Firefox's application menu
>     *   "New Tab" in Firefox's tab context menu
> *   Operations handled by TST
>     *   "+" button in TST's sidebar,
>     *   double click in a blank area of TST's sidebar
>     *   middle click in a blank area of TST's sidebar

Ctrl+t, virtually always.

**Comment by piroor** [comment]
@mzso Thanks, hmm... As one more possibility I've tried with `browser.tabs.insertAfterCurrent`=`true`, but new tabs via Ctrl-T are controlled by TST as expected.

**Comment by mzso** [comment]
[**@piroor**](https://github.com/piroor) commented on [2021. máj. 1. 18:40 CEST](https://github.com/piroor/treestyletab/issues/1910#issuecomment-830659329 "2021-05-01T16:40:11Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso) Thanks, hmm... As one more possibility I've tried with `browser.tabs.insertAfterCurrent`\=`true`, but new tabs via Ctrl-T are controlled by TST as expected.

I tried exporting settings from the main profile, but it doesn't seem to make a difference in the test profile:
* With Firefox startpage in FF config and about:newtab in TST it works
* With empty page, and about:blank, it doesn't.

In my main profile it doesn't ever work.

**Comment by piroor** [comment]
@mzso 

> In my main profile it doesn't ever work.

If you use something other addon(s) or about:config preferences, they can cause the problem. For example, an addon forcing to reopen new tabs (to apply different container or doing other purposes) can conflict to TST's behavior.

Please remind that you need to report a new issue with the [issue template](https://github.com/piroor/treestyletab/blob/trunk/ISSUE_TEMPLATE.md), if you saw the problem with conditions different from the one described at the initial comment of this issue. Comments added to an existing issue are basically guessed as  same steps to reproduce, same Firefox version, same TST version, same configs and same other addons.

**Comment by mzso** [comment]
[**@piroor**](https://github.com/piroor) commented on [2021. máj. 1. 19:14 CEST](https://github.com/piroor/treestyletab/issues/1910#issuecomment-830664039 "2021-05-01T17:14:24Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso)
> 
> > In my main profile it doesn't ever work.
> 
> If you use something other addon(s) or about:config preferences, they can cause the problem. For example, an addon forcing to reopen new tabs (to apply different container or doing other purposes) can conflict to TST's behavior.
> 
> Please remind that you need to report a new issue with the [issue template](https://github.com/piroor/treestyletab/blob/trunk/ISSUE_TEMPLATE.md), if you saw the problem with conditions different from the one described at the initial comment of this issue. Comments added to an existing issue are basically guessed as same steps to reproduce, same Firefox version, same TST version, same configs and same other addons.

I can't think of anything to affect TST. On the other hand I saw no reason for an addon for unloading tabs to interfere TST's tab selection behavior, but it did.
Anyway, my enabled addons are these:
[addons.txt](https://github.com/piroor/treestyletab/files/6410211/addons.txt)

**Comment by piroor** [comment]
@mzso I've wrote [a guide to find out the true cause addon from a large number addons](https://github.com/piroor/treestyletab/wiki/How-to-minimize-conditions-to-reproduce-a-problem ). Could you try that?
