### ISSUE TITLE
How can the Tree Style Tabs session store be emptied completely?

### ISSUE THREAD

**Issue by vonHabsi** [piroor/treestyletab#1914]
After upgrading to Firefox 57 and above it seems that Tree Style Tab is reporting a wrong tab count.

One of my profiles is listing up to 800+ tabs although the visible tabs do not reach that number.

How can I clear the tabs or session store to reset it all to 0 and start again?

**Comment by piroor** [comment]
How about this workaround?:

 1. Install Multiple Tab Handler https://addons.mozilla.org/firefox/addon/multiple-tab-handler/
 2. Open new blank tab.
 3. Select all tabs on TST sidebar, except the blank tab opened at step 2.
 4. Right-click on TST sidebar and choose "Selected Tabs" => "Move to New Window"

Note that this can break your session information, so I recommend you to backup  `sessionstore.jsonlz4` and `sessionstore-backups` in your profile before doing that.
