### ISSUE TITLE
Possible to make new tabs opened from "children" to open as a "children" to the main "tree"?

### ISSUE THREAD

**Issue by xerance** [piroor/treestyletab#1915]
Hello, tried searching issues before posting, but guess I'm not looking for the right terms if its already answered; sorry if that's the case!

Is it possible to prevent new tabs to "branch" out at all and just act as another "child" to the "main tree"?
example
(T) = tree
(c1) = child 1
(c2) = child 2
(c3) = child 3

c2 opens a new link as a tab.
instead of making the new tab a children of c2, is it possible to change it to the next child of (t), aka (c4)?

master paint skillz illustration
![treepaint](https://user-images.githubusercontent.com/16266200/40678613-469e2e46-6381-11e8-8a48-fcb25fc23187.png)

Using fire fox quantum latest version(60.0.1 64bits).

bonus question:
Any chance we can rename the "main tree" so it persist even if we change the url?

**Comment by irvinm** [comment]
@piroor please close this.
