### ISSUE TITLE
Incompatibility with the Conex extension when opening external link

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#1917]
## Short description
There seems to be some incompatibility with the [Conex](https://addons.mozilla.org/firefox/addon/conex/) extension. When external links are opened Conex tries to open them in the same container as the current tab and to do this it closes the original tab and then re-opens it in a new tab. It does this even if the current tab is in the default container. The new tab it opens seems to be a child tab of the tab it closes. 

I think that Tree Style Tab considers the parent tab collapsed since the original tab is closed so quickly after opening the child tab. Therefore Tree Style Tab attempts to close the whole tree and a prompt appears asking if all tabs should be closed.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install [Conex by kesselborn](https://addons.mozilla.org/firefox/addon/conex/).
 4. Open an external link. For example by dragging a link from a web page to the Tree Style Tab Sidebar. (Can for example find links on the new tab page, just drag one of the top page's to the sidebar.)

## Expected result
The link should be opened in a new tab. 

## Actual result
The link is opened but immediately after a popup appears in the sidebar that says:

> You are about to close 2 tabs. Are you sure you want to continue?

If I press "Close tabs" then the new tab is closed and if I press "Cancel" then the new tab is duplicated and the prompt is re-opened.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 60.0.1
 * Version (or revision) of Tree Style Tab: 2.4.23

**Comment by piroor** [comment]
Thanks. The commit 8a02216 should fix this problem.
