### ISSUE TITLE
"Close tabs to the Right" doesn't work with TST animations disabled

### ISSUE THREAD

**Issue by nikola-kocic** [piroor/treestyletab#1919]
## Short description

"Close tabs to the Right" doesn't work with TST animations disabled.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open TST Preferences and disable "Enable animation effects".
 4. Restart Firefox.
 5. Open few new tabs.
 6. Right click one of first tabs in TST sidebar and choose "Close tabs to the Right".

## Expected result
You get dialog asking if you are sure you want to close tabs.

## Actual result
Nothing happens (no tabs are closed) and in Browser Console this error is printed:
```
TypeError: this.contextTab is null  sidebar.js:375:1
```

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 60.0.1
 * Version (or revision) of Tree Style Tab: 2.4.23

## Details
This works in version 2.4.21 (and is broken in 2.4.22).
To me it looks like this commit is the culprit: https://github.com/piroor/treestyletab/commit/cf69825a14950043271f8a23d255d0848ec0ec5c (Close fake context menu immediately when any item is clicked #1900).

**Comment by piroor** [comment]
Thanks! The commit 2d28a0a3925900b00bbd3e7acb02fb7b739d3f15 should fix this problem.

**Comment by nikola-kocic** [comment]
Confirming that it's fixed in version 2.4.24.
