### ISSUE TITLE
[2.4.24] All stacks are expanded after restoring session

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1920]
TST2.4.24, bug is not reproduced in TST2.4.23

Here is what a single tab and a stack look like after restoring session in 2.4.24:
![image](https://user-images.githubusercontent.com/26294581/40881166-f4baaf0a-66c8-11e8-97bd-d775ca651046.png)

AR: Stack is expanded even though the triangle to the left of the favicon says otherwise, child tab is visible
ER: Stack is collapsed, child tab is not visible

**Comment by SXZ1** [comment]
Do you need logs or commit number that caused a regression, @piroor ?

**Comment by piroor** [comment]
I think the commit fee0cd7 should fix this. Does it affect for your case?

**Comment by SXZ1** [comment]
Thank you very much! Bug is fixed in latest dev build!
