### ISSUE TITLE
Tree Style Tab somehow inherits color of Theme Texture from Firefox Color

### ISSUE THREAD

**Issue by aminought** [piroor/treestyletab#1924]
## Short description

Tree Style Tab somehow inherits color of Theme Texture from Firefox Color.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Go to https://color.firefox.com/?theme=XQAAAALsAAAAAAAAAABBqYhm849SCiazH1KEGccwS-xNVAVKEqArbLAENDFZcMwCbeRjUc7NRnqMESwYz6qkZzt2MS1ZaodKoWo4lTxErB9jrsd5qr4-wBgliD0TEz9dwSLUahFQM00LDexkSLXiCqEFgNxruSpKV1eZj8VQ_-JmapkWiOQziOi1aCUKemnQj1PyG9FAeSNoL3aPgPVvHQYsk0CNKGS9htxexSYqBVu4cUkhgUKMq9rffP-uT6AA

## Expected result

I think, Tree Style Tab shouldn't change it's theme.

## Actual result

See how your Tree Style Tab pane becomes ugly and unusable.

## Environment

 * Platform (OS): Windows
 * Version of Firefox: 60.0.1
 * Version (or revision) of Tree Style Tab: 2.4.24

**Comment by aminought** [comment]
Possibly, some checkbox for inheritance of firefox theme should be added in settings?

**Comment by piroor** [comment]
Sorry, but I have no plan to add extra option to deactivate the behavior. I this there is no reason to unapply theme colors for TST's fake tab bar  (except for strongly designed theme like "Metal") because I believe that it should basically imitate appearance and behavior of Firefox's tabs.

**Comment by piroor** [comment]
Now there  is the option.
