### ISSUE TITLE
[meta] Migrate to ES Module 

### ISSUE THREAD

**Issue by saneyuki** [piroor/treestyletab#1935]
This is proposal to migrate to ES Module.

## Motivation

* ES Module is a new standard way to organize a JS code.
* We can use it from Firefox 60.

### 0. Change the way loading scripts to `defer`

This is done by https://github.com/piroor/treestyletab/pull/1729

### 1. Allow to place ES Module and load them

This is done by https://github.com/piroor/treestyletab/pull/1928

### 2. Enable more ESLint rules to detect

* This is still progress and we can proceed next steps.
   * https://github.com/piroor/treestyletab/pull/1933
   * Add [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import).
   * and more....?
* In ES Module, we can make where all variables is defined statically in syntax. So we can detect unused variables or invalid importing by ESLint or other static analysis. It' easier to make our development.

### 3. Convert classic script source into ES Module.

* This is still progress
   * https://github.com/piroor/treestyletab/pull/1929
   * https://github.com/piroor/treestyletab/pull/1930
   * https://github.com/piroor/treestyletab/pull/1931

### 4. Flatten directories.

After complete step 3, then we would have only ES Modules!
We can erase `**/modules/` introduced by _step 1_ by flatten them.

**Comment by saneyuki** [comment]
@piroor 

This is my big picture. How about do you think?

**Comment by piroor** [comment]
Thank you for the plan. Experimentally I converted more independent modules to ES modules, and I've understood that more aggressive linting helps our development.

I think there are more detailed steps in the section "3. Convert classic script source into ES Module." (we are here):

 1. Convert base, get-tabs, tab-information, and tree-operations (possibly, more scripts) to ES modules.
 2. Restructure modules created at the step 1 to two ES modules: `Tabs` and `Tree`. `Tabs` should provide generic operations around tab elements in TST, `Tree` should provide methods to operate tree of tabs.
 3. Convert rest modules depending on `Tabs` and `Tree` to ES modules.
 4. Convert external libraries to ES modules. (This can be done at first.)

How do you think this detailed plan, especially the step 2? I think it is necessary to solve current too-complex and too-fragmented scripts, but it will take more time.

**Comment by piroor** [comment]
Another plan is: doing the step 2 after we completely migrate to ES modules. Because the step 2 will break everything easily, so aggressive linting introduced by completely-modulized codes will help that.

**Comment by piroor** [comment]
I've added some code to load external libraries as ES modules. (You need to run `make`.)

**Comment by piroor** [comment]
わかった。`import/namespace`で検出できるけど、import時のパスを絶対パスじゃなく相対パスで書かないと検出できないんですね……

**Comment by saneyuki** [comment]
@piroor

> How do you think this detailed plan, especially the step 2? I think it is necessary to solve current too-complex and too-fragmented scripts, but it will take more time.
> 
> Another plan is: doing the step 2 after we completely migrate to ES modules, because the step 2 will break everything easily.

I'm not sure about the current detail design of tree style tab, but I seem your proposed planning is nice. I support this another plan to do _step 2_ after we completely migrate to ES modules.

**Comment by saneyuki** [comment]
@piroor 

> わかった。import/namespaceで検出できるけど、import時のパスを絶対パスじゃなく相対パスで書かないと検出できないんですね……

I suspected we may get a nice Lint error by setting [resolver](https://github.com/benmosher/eslint-plugin-import#resolvers) option even if we use an absolute path.

But the tip of _master_ has been modified by you. I write a next patch based on using relative path.

**Comment by saneyuki** [comment]
BTW, I suspect that it might be useful to refactoring a code by introducing some type checker like ([Flowtype](https://flow.org/) or [Checking JSDoc by TypeScript Compiler](https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript).

The former is requires code transformation by [babel](https://babeljs.io/) or others on the compiling time. The later is that we can do like ESLint without any code transforming. But the later is sometimes hard to write a complex type.

How about do you think?

**Comment by piroor** [comment]
とりあえず、他のモジュールへの依存性が低い物からES moduleに移していってみます。
衝突が怖いので、作業は一旦止めて頂けると幸いです。

**Comment by saneyuki** [comment]
@piroor 

> とりあえず、他のモジュールへの依存性が低い物からES moduleに移していってみます。
> 衝突が怖いので、作業は一旦止めて頂けると幸いです。

Okay.

I'm working a pull request like https://github.com/piroor/treestyletab/pull/1937, which helps converting to ES Module and refactoring.
Should I suspend such works?

**Comment by piroor** [comment]
> I'm working a pull request like #1937, which helps converting to ES Module and refactoring.
> Should I suspend such works?

PRs like it are okay to continue. I'm happy just suspending actual converting PRs.

**Comment by saneyuki** [comment]
> PRs like it are okay to continue. I'm happy just suspending actual converting PRs.

Okay. Thank you.

**Comment by piroor** [comment]
I've done to migrate most modules to ES modules. Note that there are non-ES-module files under `resources/` because they are loaded as content scripts and content script doesn't support ES modules.

**Comment by piroor** [comment]
ES modules are now rejected by addons-linter, thus we need to wait releasing new version until https://github.com/mozilla/addons-linter/issues/1775 becomes fixed.

**Comment by saneyuki** [comment]
This add-on including a changing to  ES Module has been shipped as v2.5.0.
I think we can mark this tracking issue as RESOLVED FIXED.

**Comment by saneyuki** [comment]
@piroor 

Thank you, piro-san!
