### ISSUE TITLE
Switch to use absolute path to import an ES Module

### ISSUE THREAD

**Issue by saneyuki** [piroor/treestyletab#1942]
At now, we're using a relative path to do the title.
We would be able to change this rule into using an absolute path with setting eslint-plugin-import's resolver option.

## Related Issues

- https://github.com/piroor/treestyletab/pull/1940
- https://github.com/piroor/treestyletab/issues/1935

**Comment by piroor** [comment]
This is done by c26a48f1c01cc3b0da88330649760ab2eb9a854b and 1c3bd5ccdc2da5e0837661eb0660d3e44a6bf613.
