### ISSUE TITLE
[enhancement] add tab groups

### ISSUE THREAD

**Issue by perdolka** [piroor/treestyletab#1943]
Add "create a tab group" as optional context-menu item.

I know about "about:treestyletab-group?title=foobar"

**Comment by piroor** [comment]
My another addon [Multiple Tab Handler](https://addons.mozilla.org/firefox/addon/multiple-tab-handler/) provides the feature to create group from selected tabs.

If you need to open a new blank group tab, please create a bookmark for the URL `about:treestyletab-group`.

**Comment by piroor** [comment]
And, sorry, I have no plan to add any new command to open new blank group tab because I basically design TST to use with automatically-created tree from links.
