### ISSUE TITLE
Can't drug&drop pinned tabs to new window

### ISSUE THREAD

**Issue by kvaps** [piroor/treestyletab#1957]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Pin tab
 4. Open second window
 5. Try to drug&drop pinned tab from one to second window

## Expected result

The tab moved to new window

## Actual result

Tab isn't moved to new window

## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: 60.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.4.24

**Comment by piroor** [comment]
On my environment, there are two different results.

When I drag a pinned tab from TST's sidebar to another window's sidebar, it successes if I drop it before the first regular (unpinned) tab, but it fails if I drop it after regular tabs. Then I got an error:

```
Error: draggedTabs[0] is undefined tree.js
```

Environment:

 * Platform (OS): Ubuntu 16.04LTS
 * Version of Firefox: Nightly 62.0a1
 * Version (or revision) of Tree Style Tab: master

**Comment by piroor** [comment]
This problem looks fixed on my environment, by recent changes.

**Comment by piroor** [comment]
I close this because outdated.
