### ISSUE TITLE
The 'abstract' parent tab is always reloading when the 'real' parent tab changing its title

### ISSUE THREAD

**Issue by refeed** [piroor/treestyletab#1960]
## Short description

I got my "abstract" parent tab (sorry, I don't know what is the appropriate term for this) always reloading when the title of its real tab is changing.

Chat webapp like Telegram is always changing its title to tell the users that there's a message.
In my case, my Telegram tab is pinned. Thus, it creates an 'abstract' parent tab when I open a new link to a new tab from my Telegram tab. But when I got a message, the title of the Telegram tab is changing, and my "abstract" parent tab is always reloading when it happens. This is kinda annoying for me.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open Telegram or any website that its title is always changing.
 4. Pin the tab.
 5. Open a link in a new tab from the tab until the "abstract" parent tab appears.
 6. When the title of the tab that you created in the step-3 is changing, you'll see that the "abstract" parent tab is always reloading.

![tst_notification_always_reloading](https://user-images.githubusercontent.com/20320125/41671294-e42ee0fe-74e0-11e8-8c18-e9f790cc1e95.gif)

## Expected result
I'm not really sure what is the best solution for this. I just don't wanna see that tab always reloading like that.

## Actual result
The "abstract" tab is always reloading

## Environment

 * Platform (OS): Fedora 28 with Cinnamon DE
 * Version of Firefox: Mozilla Firefox 60.0.2
 * Version (or revision) of Tree Style Tab: 2.4.24

**Comment by piroor** [comment]
Thanks. After some recent commits, now TST tries to update only the title or the tree in group tabs, without reloading. Could you try the latest development build?

**Comment by refeed** [comment]
Ah yup! I like it now..

![tst_notification](https://user-images.githubusercontent.com/20320125/41718262-a4508130-7586-11e8-9de4-25a97acb19d0.gif)

So btw, when the next release will be released?

**Comment by piroor** [comment]
Currently TST is not releasable due to addon-linter problem: https://github.com/mozilla/addons-linter/issues/1775 I need to wait for the linter becomes to accept ES modules.

**Comment by refeed** [comment]
Alright! I'll wait for it
