### ISSUE TITLE
The last version available on piro.sakura.ne.jp is outdated (2.4.24.7145)

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1963]
The last version of TST available on github is 2.4.24.7314
The last version available on piro.sakura.ne.jp is 2.4.24.7145 (at least that's what the version number says in about:support)

ER: 2.4.24.7314 should be available on piro.sakura.ne.jp
AR: 2.4.24.7145 is available on piro.sakura.ne.jp

**Comment by piroor** [comment]
This problem has been fixed, so I close this issue.
