### ISSUE TITLE
Tab tree missing with Firefox 61.0 (workaround provided)

### ISSUE THREAD

**Issue by jbuttery** [piroor/treestyletab#1965]
Apologies for opening this bug with so little supporting information, but after I found a workaround I wanted to put this in a place where other semi-technical users like myself would be likely to find it, since suddenly losing the ability to have tabs is pretty devastating from a usability standpoint.  :)

My Firefox recently (last night) updated itself to version 61.0 and immediately the TST sidebar stopped working (the loading animation just continues forever).  It turns out you can get the tab tree back by removing this (or commenting it out) from `userChrome.css` (I know this file can have arbitrary contents, but this particular CSS rule is recommended for this purpose, so a lot of people are likely to have it):

```
/* Hide horizontal tab bar across the top */
#TabsToolbar { visibility: collapse !important; }
```

As you would expect, this also causes Firefox' normal horizontal tabs to be visible again; that's unfortunate, but having two sets of tabs is much better than having no tabs.

**Comment by MordecaiWalfish** [comment]
I have firefox 61.0 set up with this exact bit of code in userChrome.css, and did not encounter this issue. Possibly this is the result of other add-ons conflicting?

I was hoping that the css edit would no longer be necessary for this, with the following blurb in the firefox update notes for v61.0:
"More customization for tab management: added support to allow WebExtensions to hide tabs"

Hoping for an update to tree style tabs to support this. One concern is potential conflicts this may cause for people who have the additional css code for this already. Purely hypothetical at this point until a potential update comes.

**Comment by piroor** [comment]
@MordecaiWalfish The feature of Firefox 61 doesn't help TST, because it just allows addons to hide individual tabs but doesn't allow to hide the tab bar itself. I already tried to hide needless tabs in the horizontal tab bar with the API, but there are many restrictions and side effects because hidden tab is treated like as already closed tabs. (Thus finally I decided that hidden tabs are also hidden in TST's sidebar.)

**Comment by piroor** [comment]
@jbuttery Basically Firefox is not designed to work with hidden horizontal tab bar, so any userChrome.css rules to hide the tab bar can break everything. This it is impossible to guarantee complete behavior of an addon with hidden horizontal tab bar. For safety, I don't use any customization like that and I'm using TST with visible horizontal tab bar.

**Comment by jbuttery** [comment]
Given @MordecaiWalfish's comment, this seems like a non-issue and I'll go ahead and close it.  Thanks for the explanation; that's too bad but obviously whatever it is, is out of TST's hands.  :)
