### ISSUE TITLE
[feature request] Add empty group tab/folder.

### ISSUE THREAD

**Issue by emceekain** [piroor/treestyletab#1966]
## Short description
Children tabs opened from a pinned tab are created inside of a temporary group tab/folder.  It would be convenient to create such group tab/folder by themselves (possibly as an option "Open New Tab as..." menu.
## Current workaround

 1. With TST running, pin any tab with links to other pages.
 2. Open at least 2 of the pages in another tab.
 3. These tabs are automatically grouped in to a group tab/folder titled "Tabs from [origin_url]".  You can then rename this tab/folder, add/remove tabs, etc.
4. Additional group tab/folders can be created by copy/pasting the URL of the first one you created above (thanks to @madduck for pointing this out).

## Desired solution
The abilty to create an empty group tab/folder quickly and easily through either a keyboard shortcut or an option in the "New Tab" menu.

## Why is this necessary?
I'm aware of TST's ability create bookmarks, but my use case is more temporary.  I would like to be able to group together related pages (but not necessarily obtained from the same source URL), name the group accordingly, and be able to fluidly modify this group (as I can currently modify the children of an actual URL).  For example, if I did a bunch of research pertaining to the next phone I'm going to purchase, I might have tabs open from Amazon, Newegg, etc.  Having those tabs collected in one nice/neat folder while doing the research would be extremely useful.  I could collapse the folder if I need to work on another task, add/remove tabs as I need them, and once I've settled on a new phone, close the entire group.  

## Environment

* Platform (OS):  Windows 7
 * Version of Firefox:  61
 * Version (or revision) of Tree Style Tab:  2.4.24

**Comment by piroor** [comment]
This "command" won't be added by some reasons, but there is a workaround based on a bookmark. See also my old comments:

 * https://github.com/piroor/treestyletab/issues/1943#issuecomment-399141587
 * https://github.com/piroor/treestyletab/issues/1520#issuecomment-344035375
 * https://github.com/piroor/treestyletab/issues/1747#issuecomment-361530428

**Comment by piroor** [comment]
I close this because outdated.

BTW, now TST has a builtin context menu command "Create New Group from tabs" for multiselected tabs.

**Comment by hhyyrylainen** [comment]
Sorry to reply to such an old issue, but it took me a while to find out that this command has been moved to a separate addon: https://github.com/piroor/tst-more-tree-commands
In case someone else also finds this, and is confused by the option "Create New Group from tabs" not being anywhere, I thought I'd leave that link here.
