### ISSUE TITLE
Add keyboard shortcut for focusing children

### ISSUE THREAD

**Issue by j6s** [piroor/treestyletab#1967]
Currently the keyboard shortcuts only allow changing the tab on the current depth level (among siblings). It would be nice to have a shortcut to control the current depth ( to focus the children of the current tab or the parent of the current tab )

**Comment by piroor** [comment]
Recent commits including a9b298e add these commands. You can try them with the development build: https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi

**Comment by SXZ1** [comment]
@piroor I've just tried to install the latest dev build from https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi but for some reason TST2.4.24.7145 is installed where these commands are missing in TST Options. 

It looks like I don't understand something..

**Comment by SXZ1** [comment]
To clarify: TST2.4.24.7145 is an old build. According to commit counter on github, the latest build is 2.4.24.7325.

**Comment by piroor** [comment]
Sorry, the automated build system was broken... Now the file is built from master/HEAD correctly.

**Comment by j6s** [comment]
Did not see that commit. Thanks.
Closing issue.
