### ISSUE TITLE
Middle-clicking quickly enough opens new tab instead of closing tab

### ISSUE THREAD

**Issue by nh2** [piroor/treestyletab#1968]
## Short description

When I have many tabs open in the tree, put the mouse curser over the tree and middle-click very rapidly to close many tabs, sometimes a new tab opens if I click quickly enough.

(Because the new tab opens at the bottom, when I have many tabs open, the new tab's creation actually scrolls the tab bar up a bit, so that I sometimes accidentally close the wrong tab; this is very annoying.)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open many tabs
 4. Hover mouse over one of the earlier tabs, e.g. the 5th one
 5. Click middle click as quickly as you can

## Expected result

Tabs close.

## Actual result

Sometimes, a `New Tab` opens at the bottom.

## Environment

 * Platform (OS): Ubuntu 16.04
 * Version of Firefox: 62.0a1 (but have observed this with the last ~5 versions of FF)
 * Version (or revision) of Tree Style Tab: 2.4.24

**Comment by nh2** [comment]
Please let me know if you can reproduce it, otherwise I'll record a screenshare.

**Comment by piroor** [comment]
The commit dd9d36e should fix this problem.

**Comment by nh2** [comment]
Absolutely fantastic, indeed it does fix it!

**Comment by nh2** [comment]
@piroor Unfortunately this bug is back! Closing tabs quickly with middle-click occasionally opens a new tab.

I _suspect_ that it happens as part of the tab closing animation, that for a split second there's the background behind that tab, and if you middle-click that, a new tab is opened.

I'm on TST 3.5.1 on Firefox 75.

**Comment by nh2** [comment]
Is there a way I can disable the tab closing animation to check whether my suspicion is right?

`toolkit.cosmeticAnimations.enabled = false` does not disable it for me.

**Comment by piroor** [comment]
> Is there a way I can disable the tab closing animation to check whether my suspicion is right?

There is a checkbox to do that in TST's options => "Appearance".

**Comment by nh2** [comment]
> There is a checkbox to do that in TST's options => "Appearance".

Thanks, disabling the animations fixes that problem.

I have attached a video that shows the problem, and how disabling the animation fixes it:

[TST-closing.mp4.zip](https://github.com/piroor/treestyletab/files/4565396/TST-closing.mp4.zip)

**Comment by piroor** [comment]
I've introduced a safe guard mechanism for such cases with the commit 6044869. I hope it completely solves the problem @nh2 saw...

**Comment by nh2** [comment]
Thanks @piroor, it seems to be fixed, closing!
