### ISSUE TITLE
wrong bookmark folder date

### ISSUE THREAD

**Issue by perdolka** [piroor/treestyletab#1969]
I tested [Development build](https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi)
When I create a new bookmarks folder (add all tabs to bookmarks) it has wrong placeholder %DATE% value.
It's **30**, but it should be **29** in my time zone (EEST, UTC +3).

**FF** 61.0 (x64)
**TST** 2.4.24.7327
Used folder name settings: (%DATE%.%MONTH%.%YEAR%)

**Comment by perdolka** [comment]
Это не баг, это один старый фокус, делается на стороне постера.

**Comment by perdolka** [comment]
Это не баг, это один старый фокус, делается на стороне постера.

**Comment by piroor** [comment]
Oops, I wrongly incremented the date. 7e4f691 fixes this problem.
