### ISSUE TITLE
TST 0.0.2 will not run without TMP and a prefs insert in PM 28.0.0b2

### ISSUE THREAD

**Issue by thehandyman1957** [piroor/treestyletab#1973]
## Short description
Tree Style Tabs will not work at all without installing TMP (almost any version from 0.5.0.4 down.  
If I install TMP tabs only show on the left side of the browser.  If I choose the right side in settings, nothing changes until the browser is restarted and then all tab windows are greyed out.  At this point the profile has to be reset because you can't even see the add on page to uninstall or disable.  
So then if I install again in the same order, but don't change the right side in settings, close the browser and then open the "prefs" file in the profile and insert this line: "user_pref("browser.tabs.animate", false);" restart the browser and it will then work and you can change preferences at this point.  
## Steps to reproduce
1. New Profile, Install TST and restart.  Tabs still on top, settings won't change anything.  
2. Install TMP and upon restart, tabs will be on the left.  Changing the settings for tabs on the right will not change anything until a browser restart.  At this point the browser screen is grey and you can't see anything except the tabs. 
3. Delete profile to start over.  Install TST and restart.  Install TMP and restart.  Do not change any of the TST settings.  Close the browser.
4. Open the "prefs" file in the profile and insert this line: "user_pref("browser.tabs.animate", false);" and save and start browser.  Now all settings work and you can change the tabs to the right hand side.

## Expected result
Install TST and it works out of box.

## Actual result
As stated above, you must install TMP (version does not matter) and then change the prefs file.

## Environment

 * Platform (OS): Windows 7 Pro 64 bit
 * Version of Pale Moon:  Pale Moon 28.0.0b1 64bit
 * Version (or revision) of Tree Style Tab: 0.0.2

**Comment by piroor** [comment]
Do you use any forked version of TST? I've never released such a version (the initial version of TST is 0.1.2007102101). Moreover, currently TST doesn't support Pale Moon and it is designed only for Firefox 57 and later.

**Comment by thehandyman1957** [comment]
Yes, apparently so.  I'm sorry. Iwill continue to find the fork author.  
You can delete the issue then.
