### ISSUE TITLE
Image itself is shown for favicon when viewing image file

### ISSUE THREAD

**Issue by asamuzaK** [piroor/treestyletab#1982]
## Short description

When viewing image file in tab, favicon is wrong.
Image itself is shown as favicon.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open http://asamuzak.jp/test/sprite/triangle.svg

 Optional
 4. Press `F5`

## Expected result

Favicon (http://asamuzak.jp/favicon.svg) is shown as favicon in step 3.

## Actual result

http://asamuzak.jp/test/sprite/triangle.svg is shown as favicon in step 3.
See attached `image1.png`
![image1](https://user-images.githubusercontent.com/6790339/42894485-eccbe2e4-8af1-11e8-9413-0c49f49c4157.png)

When reloaded (step 4), expected favicon is shown.
See attached `image2.png`
![image2](https://user-images.githubusercontent.com/6790339/42894496-f078fcba-8af1-11e8-998b-cd5b7b17cf1e.png)

## Environment

 * Platform (OS): Win 10
 * Version of Firefox: Nightly
 * Version (or revision) of Tree Style Tab: 2.4.24

## Question and proposal

[webextensions-lib-tab-favicon-helper/TabFavIconHelper.js at master · piroor/webextensions-lib-tab-favicon-helper](https://github.com/piroor/webextensions-lib-tab-favicon-helper/blob/master/TabFavIconHelper.js#L76 "webextensions-lib-tab-favicon-helper/TabFavIconHelper.js at master · piroor/webextensions-lib-tab-favicon-helper")

This function is causing the issue.
For what purpose is this function needed?

In current Nightly, `favIconUrl` is set as data URL like `data:image/png;base64,foobar`, or `undefined` if there is no favicon, or `chrome://foobar` for `about:` URLs and a new tab.

My proposal is to look at `status` value at `onTabCreated`, and `onTabUpdated`, and especially at `getEffectiveURL`.
And I suppose you should not set previous favicon for the fallback.

For example:
```
getEffectiveURL(aTab) {
  const {status, favIconUrl} = aTab;
  let src;
  if (status === "complete") {
    if (favIconUrl) {
      const {protocol} = new URL(favIconUrl);
      if (protocol === "data:") {
        src = favIconUrl;
      } else {
        // protocol maybe `http(s):`, `file:`, `chrome:` etc.
        // fetch favicon from favIconUrl somehow and set src
      }
    } else {
      // set src as default fallback favicon
    }
  } else {
    // status === "loading"
    // set src as loading throbber
  }
  return src;
}

onTabCreated(aTab) {
  return this.getEffectiveURL(aTab);
}

onTabUpdated(aTabId, aChangeInfo, aTab) {
  return this.getEffectiveURL(aTab);
}
```

**Comment by piroor** [comment]
The method `maybeImageTab()` is used to simulate Firefox's behavior for images without `/favicon.ico`. For example: https://piro.sakura.ne.jp/pics/cartoon/firefox/fx-tb.jpg

And I think the library should concentrate to handling of favicons, instead of the throbber image.

Anyway, handling of favicons were too complex on 2.4.24 due to handling of internal icons, and I've moved those codes to the library itself. On my environment, the problem looks disappeared with the [latest development build](https://github.com/piroor/treestyletab/blob/master/README.md#development-builds).

**Comment by asamuzaK** [comment]
Confirmed fixed.
Thanks for quick fix.
