### ISSUE TITLE
Compatibility with color overriding

### ISSUE THREAD

**Issue by defanor** [piroor/treestyletab#1983]
## Short description
TST tab labels get illegible when color overriding is turned on in FF, particularly with light-on-dark colors.

There are related FF issues, and the only workaround I've found is to set the Metal theme, which provides legible dark-on-light labels; it would be nice to have something similar for light-on-dark.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Turn color overriding on (Preferences - General - Colours).
 4. Set colors to light-on-dark (e.g., white on black).

## Expected result
Legible labels.

## Actual result
![tree style tab](https://paste.uberspace.net/tree-style-tab.png)

## Environment

 * Platform (OS): CentOS 7.5.1804
 * Version of Firefox: 60.1.0esr
 * Version (or revision) of Tree Style Tab: 2.4.24

**Comment by piroor** [comment]
TST uses system color on Linux by default, so you may need to change more other system colors. Labels of tabs are shown with the system color `-moz-dialogtext`.

**Comment by defanor** [comment]
Apparently `-moz-dialogtext` is light grey here: when set in a Firefox instance with color overriding turned on, it's the same color as the default text (checked it with different colors, too), but in a Firefox instance without overriding, setting text color to `-moz-dialogtext` turns it very light grey.

**Comment by irvinm** [comment]
@defanor, does this problem still exist in current versions of Firefox?  (Can we close this?)

**Comment by defanor** [comment]
It does in FF 60.3.0esr with TST 2.8.5. Not an issue for me personally
anymore though, since I switched from built-in color overriding to a
global CSS.

Apparently the most recent FF version is 66.0.3 now, but I don't have it
at hand to test.
