### ISSUE TITLE
No way to restore hibernated group

### ISSUE THREAD

**Issue by daltinn** [piroor/treestyletab#1984]
In context menu on group after click on "Hibernate" tab group is gone, but no way to restore hibernated group.

## Steps to reproduce

 1. Hibernate group by context menu
 2. Hibernated group invisible, and no way to restore it

##Expected
Separate menu with hibernated group for restore it.

**Comment by piroor** [comment]
Which addon provides the "hibernate" feature? TST doesn't provide it by default.

**Comment by irvinm** [comment]
@daltinn can you reply to piroor or close this issue if it isn't applicable today?

**Comment by irvinm** [comment]
@piroor can you close this item?  No updates since July 2018.
