### ISSUE TITLE
Suggestions: settings tooltip (or a help page) [feature request]

### ISSUE THREAD

**Issue by brain8891** [piroor/treestyletab#1985]
My apologies for suggesting this here, I couldn't find any other alternative. 

I have been using TST for days now, I tried to check the settings, but there is no online documentation that describe what each setting does nor there is any tool tip when you hover over the 
settings. Some add-ons have this, if you don't know about it, I could search for some examples.

Again my apologies, I don't know the right channel for suggestion. 
 
I think this could be a [feature request]

**Comment by piroor** [comment]
It is possible to add tooltip for configs, but I cannot imagine how to describe them more easily for beginners.  And I believe that enough label won't need any extra tooltip. Could you point actual configuration items you couldn't understand their meaning? I'll try to update them more meaningfully.

**Comment by brain8891** [comment]
Pardon me for the late response; I wanted to reply to you when I go back at the settings, so my reply would be real. 

You have to think that a user using the settings might be completely unaware of Firefox terminologies, thus animated tool tips helps, for example: in the New Tabs behavior you have a section called ["New Tab" button] it would be intuitive to  see an animation of a mouse cursor moving over the plus sign. This makes new users less frustrated while on the settings. I know what new tab button is, but most users don't know everything and that why I gave this extreme example. I believe you should be extreme . it is a good idea to make the add-on user experience has no frustration at all when customizing it to fit the user needs.

Now about the issues that I had:
at New Tabs Behavior: 
1- For Middle click, open new black tab as (a sibling of the current tab, an independent, a child of the current tab, the next sibling of the current tab)  while the TST side bar is open I middle clicked while on each settings and it looks all the same there was a "child" tab opening. you see I don't know what a sibling or child  tab means  

2- Long-press on the "New Tab" Button to (choose container, etc.) it looks like it does nothing?

3- "Show selector button on the "New Tab" button, to specify where the new tab is opened in.  I disabled it and enabled it, but I can't see any difference in the new tab button, so what is the selector button?

4- Show container selector button on the "New Tab" button. again I disabled it and enabled it, but I am not sure what it does, so it should show a selector button on the "New Tab" button, but when I enable it, it doesn't do anything.

5- The reason I went to TST settings, I set [browser.tabs.insertAfterCurrent] to true when TST is disabled the New tab open next to the current but when it is Enabled it opens next to the current then moves to the far right. I am not sure if this a bug, but nothing in New tab behavior that fix this for me. 

suggestions:
1- add a (default) beside each default option in the lists and with check-marks add (by default un/selected) at the end of the sentence.

**Comment by piroor** [comment]
OK, I may see what you meant...

But, sorry, I have very less motivation to implement rich tutorials, because I am the prime user of this project. This project doesn't aims to provide rich introduction for very novice users (especially Firefox itself!) For a continuous increasing userbase Firefox needs such tutorials to invite people from other browsers. But TST doesn't. I'll maintain this project for the future even if there is only one user (myself). Too much codes for rich introduction will make TST too fat and hard to be maintained by my hand.

By the way, if you want to reset TST's settings completely, you just need to do: uninstall TST, restart Firefox, and reinstall TST. Then you'll see TST with completely default configurations.

**Comment by brain8891** [comment]
I must salute you for sharing this project. Thank you, and I agree with you, I just thought you might want to attract more users. 

The following  might be a  bug and might interest you, I uninstalled TST because my tabs were moving  to a random location on the tab-bar. I did my best to check the settings but it looked like everything was fine.

why I installed TST? it is nice to a see the history of your links jumps, specially when you dive into Wikipedia for a project. 

thanks for sharing your hard work.

**Comment by irvinm** [comment]
@brain8891 you may want to consider trying TST again.  There has been some great progress over the last 6 months and the addon is more stable than ever.

In any case, would you might closing this issue?  Thanks.

**Comment by irvinm** [comment]
@piroor, will you close this one?

**Comment by irvinm** [comment]
@piroor ... a friendly reminder.

**Comment by piroor** [comment]
Sorry I forgot to check this.

Anyway I'm still OK to merge any pull request adding such extra descriptions, but it won't be done by myself, because I'm the original author and descriptions written by me will be still less understandable for people.
