### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by fhoyos** [piroor/treestyletab#1987]
## Short description
Opciones no son visibles
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. options do not visible
 4. 

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab: 
![tst firefox extension bug](https://user-images.githubusercontent.com/595651/43161562-08bb62bc-8f4e-11e8-8751-de2ebd04a25a.png)

**Comment by piroor** [comment]
I close this because outdated.
