### ISSUE TITLE
non-free IEC61966-2.1 embedded color profiles

### ISSUE THREAD

**Issue by onlyjob** [piroor/treestyletab#1990]
The following images contain embedded non-free IEC61966-2.1 colour profile:

    webextensions/sidebar/styles/sidebar/closetab-white.png
    webextensions/sidebar/styles/sidebar/closetab.png

~~~~
$ exiftool {IMAGE.png}
Profile Copyright       : Copyright (c) 1998 Hewlett-Packard Company
Profile Description     : sRGB IEC61966-2.1
~~~~

This means that (propriatary?) graphics editor saved image(s) with embedded non-free IEC61966-2.1 colour profile.

IEC61966-2.1 prohibits modification, see ​http://www.color.org/srgbprofiles.xalter#v2

Non-free ICC profile can be removed using the following command

    exiftool -icc_profile"-<=" {IMAGE.png}

or using GIMP (Image --> Mode --> Convert to Color Profile).

**Comment by piroor** [comment]
Thanks! I didn't know they contain non-free information...

**Comment by onlyjob** [comment]
Thanks!
