### ISSUE TITLE
 fixing the old version of TST (overlay)

### ISSUE THREAD

**Issue by Ulf3000** [piroor/treestyletab#1991]
I want to fix the old version of TST (overlay addon)  for usage with waterfox ...

i mean it works , but it produces extreme memory leaks ...

If anybody knows which function in which .js is responsible for this please tell me .. im now browsing through the code , but its HUGE , so any help is appreciated 

thanx

**Comment by sumyungguy** [comment]
@Ulf3000 How do you know it's producing "extreme memory leaks"? I'm using it with Waterfox, with very few problems.

**Comment by Ulf3000** [comment]
i tested it extensively , you can see memory leaks in about:memory and task manager. for years ive been pissed off by firefox sluggish performance and after a while of browsing firefox/waterfox ramps up in memory well beyond the 3GB range and uses permanent cpu , everything becoming sluggisch. 

Seems when i disable my favourite addon of all time (tst) all problems are gone. re-enable , and problem comes back . tested it on real profile , on new profile .... problem is reproducable ... without tst you can surf for a weeek with x tabs open and memory will always stay low (even with many tabs , man youtube tabs etc), basically no restart needed ever and VERY fast and smooth experience. surfing a day with tst on , and memory fills up with ghost compartements (especially dead javascript ) and memory fills up to around 4GB+, by then the gc is already going wild and permanently maxing out a cpu thread .

**Comment by sumyungguy** [comment]
You might find the "Auto Unload Tab" addon helpful.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
