### ISSUE TITLE
Mask (fade-out) effect on tab title is sometime canceled

### ISSUE THREAD

**Issue by asamuzaK** [piroor/treestyletab#1994]
## Short description

I can not properly show the steps to reproduce, masking effect (fade-out) of the tab labels get canceled sometimes, like when the browser is updated, reloading the discarded tab, etc.
It seems that you are adding or removing 'overflow' class on nonstandard 'overflow' / 'underflow' event, I think you also need to calculate label width and tab width on other events too (eg when tab title is updated) and add / remove 'overflow' class?

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Expected result

Long label (tab title) is always masked.

## Actual result

The mask effect is not applied sometimes.

## Environment

 * Platform (OS):  Win 10
 * Version of Firefox:  Nightly
 * Version (or revision) of Tree Style Tab: 2.4.24.7422

**Comment by piroor** [comment]
Overflow/underflow events looks still effective on my environment. However, I also see the problem sometimes and I think that it can happen when those events are blocked or suppressed by some reasons. So I've introduced some changes to update the "overflow" state of tab labels. Now it is updated on following cases:

 * When a tree is expanded. Label of tabs turned to visible will be updated.
 * When the sidebar contents is restored from cache. Label of visible tabs are updated.

I hope these changes solve the problem.

**Comment by SXZ1** [comment]
>I've introduced some changes to update the "overflow" state of tab labels. Now it is updated on following cases:
>When a tree is expanded. Label of tabs turned to visible will be updated.
>When the sidebar contents is restored from cache. Label of visible tabs are updated.

I wonder if it is possible to revert these changes somehow because I am using TST with extremely big number of tabs and these commits have led to noticeable performance degradation (I am talking about time it takes to collapse or expand the stack). But as I said, I have extremely big number of tabs open so this problem will likely affect 0.001% of TST user base.

**Comment by SXZ1** [comment]
Just to clarify: I don't want to say your code is faulty or unoptimized, you don't need to fix anything! I am just wondering if it is possible to disable the code responsible for this particular implementation of fade-out effect. And the reason for that is the extremely big number of tabs that brings my PC to its knees, not TST code base.

**Comment by piroor** [comment]
I think that reimplementing based on virtual scrolling (like react virtualized https://github.com/bvaughn/react-virtualized) will improve performance with massive number of tabs. Before doing that I'll need to reimplement TST with virtual DOM...

Anyway, new option to deactivate the overflow style may become included to a future verison of TST.

**Comment by piroor** [comment]
I close this because outdated.
