### ISSUE TITLE
[feature request] Allow easier disabling of default keyboard shortcuts

### ISSUE THREAD

**Issue by ElDani82** [piroor/treestyletab#1997]
## Short description

I came here looking for a fix to #1995 initially, but my own attempts at fixing this problem have brought me to write this feature request. In my eyes it's half bug (because I hope the current functionality isn't intended this way) and half feature-request, but let me explain:

When I want to get rid of a particular keyboard shortcut in Tree Style Tab that I happen to trigger unintentionally, I cannot simply "empty" its field and remove the trigger entirely, because the key input field always reverts to the previously saved value if I leave it empty and the reset button brings back the default values. In some instances I could get it to show undefined which prompted the red warning label, but I'm not sure how to reproduce that.

This only leaves the option to set an existing but unused key combination as a shortcut. It works, but it's certainly not ideal when this has to be done for ten shortcuts I would never find myself using. There is always the possibility that these may be again triggered by mistake in the future.

Nice things to have in addition to a proper method of disabling these pre-existing shortcuts:

* A way to better distinguish between active and disabled shortcuts.
* A way to tell *why* a custom shortcut doesn't work. Give the user more information about the conflict, if that's possible.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 61.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.5.0

**Comment by damat** [comment]
+1 vote a checkbox to enable/disable specific shortcut
or at least an option to delete the key in the input box. Currently it's just impossible and drives me nuts since I can't even turn it off: 

![record_180818_022930](https://user-images.githubusercontent.com/914556/44292671-c17c3a80-a28e-11e8-89f8-7620528c0fad.gif)

**Comment by PeterJCLaw** [comment]
Not sure if it's quite what this request is about, but I'd be interested in a way to disable _all_ of Tree Style Tabs' keyboard shortcuts. I really value TST as an extension, but as a keyboard heavy user I already use almost all of the mappings it's defined for other things.

As I use Ctrl+Tab & Ctrl+Shift+Tab or Ctrl+PageUp & Ctrl+PageDown (depending on mood) to navigate tabs quite happily, I don't think I'm going to get much value out of adding more specific shortcuts (at least in the short term).

Like others, I already use most of the mappings that have been chosen for _other_ things (mostly selecting text by word), so the shortcuts as they stand are unfortunately a net negative for me.

**Comment by piroor** [comment]
This looks a problem of Firefox's WebExtensions API itself. It doesn't accept blank shortcut definition as the input of `browser.commands.update()`. See also:
https://dxr.mozilla.org/mozilla-central/rev/4e56a2f51ad739ca52046723448f3129a58f1666/toolkit/components/extensions/Schemas.jsm#987
This logic always throw an error for blank shortcut because it doesn't match to any valid shortcut pattern.

**Comment by piroor** [comment]
https://dxr.mozilla.org/mozilla-central/rev/4e56a2f51ad739ca52046723448f3129a58f1666/browser/components/extensions/parent/ext-commands.js#299
I think the commands API should provide `browser.commands.clear()` or something special feature to do that, or `browser.commands.update()` should accept blank input.

**Comment by piroor** [comment]
Sorry, I'm negative to introduce something mechanism like that - it will make things too complex and worse.

Another workaround idea is: remove all default keyboard shortcut definitions from the manifest.json and define default shortcuts on the initial startup of the addon itself. `browser.commands.reset()` correctly clears shortcut. However this workaround will avoid the "reset to default shortcut" feature, so I'm still negative.

**Comment by dubrowgn** [comment]
Can we please have a setting to disable *all* TST keyboard bindings?

**Comment by GollyJer** [comment]
> Can we please have a setting to disable all TST keyboard bindings? Or, having keybindings opt-in until this is all sorted out?

Came to say the same thing.  `ctrl + shft+ right/left` I use all the time to highlight text... now it changes tabs. 🙃

**Comment by bigbellyburger** [comment]
This extension now conflicts with default system wide shortcuts (ctrl+shift+right/left). Add a way to get rid of these useless shortcuts. You've made Firefox unusable.

**Comment by damat** [comment]
Workaround for now: remap those essential arrow hotkeys to something like Alt + Ctrl + E or any other letter. It's highly unlikely they are used somewhere else.

Stupid? Yes. But still works.

**Comment by piroor** [comment]
As a workaround, I've introduced a mechanism to provide deassignable default shortcut to the library. (For more details, see also https://github.com/piroor/webextensions-lib-shortcut-customize-ui/blob/master/README.md#basic-usage-initialization )

**Comment by ibrahima** [comment]
Thanks for that! For some reason, I'm still unable to disable one of the keyboard options (which is also used quite often for word navigation) - each time I clear it using <kbd>esc</kbd> and close the options screen, it comes back. Is there another way to clear that preference, eg. by editing a config file somewhere? I don't know why this one specific option keeps coming back.

![image](https://user-images.githubusercontent.com/47774/44429793-83f90500-a54d-11e8-96a4-1f16ec8814c8.png)

**Comment by piroor** [comment]
I close this because outdated.
