### ISSUE TITLE
Request: Folders

### ISSUE THREAD

**Issue by Ploppz** [piroor/treestyletab#2001]
I think it would be nice to have folders you can give useful names.
These should act as a node of the tree only for organizational purposes - cannot be focused like a normal tab, but can be renamed of course.

I saw that I could set up a hotkey for "New Container Tab". I tried to set its hotkey to `Ctrl + Shift + A`. However, nothing happened when I pressed this key combination, even after restarting Firefox.

## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: 61.0.1
 * Version (or revision) of Tree Style Tab: 2.5.1

**Comment by irvinm** [comment]
Try typing this on the URL bar:  about:treestyletab-group?New%20Group

**Comment by Ploppz** [comment]
Firefox shows:

> Hmm. That address doesn’t look right.
> Please check that the URL is correct and try again.

(also tried to substitute `%20` with space - same result)

**Comment by Ploppz** [comment]
That exact string also gives me the said error.
I have the latest updates I believe (Tree Style Tab & Firefox)

**Comment by Ploppz** [comment]
Hold on ... when I pasted it in the URL bar right after creating a new tab I got that error.
But when I pasted it in the URL bar where there was already `about:addons` it worked!

**Comment by irvinm** [comment]
That is interesting.  Thanks for reporting back.  I am wondering if it might be a Linux related item.  @piroor  will likely need to chime in on this one.  (Have you tried this on Windows as a test point?)

**Comment by ssokolow** [comment]
`about:treestyletab-group?New%20Group` works for me in a freshly-opened `about:blank` tab and in a tab that was opened to a different issue on this tracker and I'm on Kubuntu Linux 14.04 LTS with current Firefox Developer Edition (62.0b19).

That said, if you want to create a shortcut for it, you might prefer the approach I use. The [Multiple Tab Handler](https://addons.mozilla.org/en-US/firefox/addon/multiple-tab-handler/) addon will integrate with TST so you can click-hold on a tab, then drag to select a range of them, then let go and choose `Selected Tabs > Create New Group` from the resulting context menu.

**Comment by qwitwa** [comment]
@ssokolow  After installing that extension I don't see an option like that in the Selected Tabs submenu.

**Comment by qwitwa** [comment]
Turns out it is not enabled by default and must be turned on in the addon options. Now it works. 

I also have the problem that the "about:" URL has stopped working. I'm on mac Firefox Developer Edition 62.0b19 (64 bit).

**Comment by piroor** [comment]
I close this because outdated.

BTW, now TST has a builtin context menu command "Create New Group from tabs" for tabs multiselected via Ctrl/Shift-click.
