### ISSUE TITLE
Preferences page is weird

### ISSUE THREAD

**Issue by Ploppz** [piroor/treestyletab#2002]
I went into `about:addons` and pressed `Preferences` on Tree Style Tab. The settings now look like this... it was normal earlier.

![ss](https://i.imgur.com/YjkF644.png)

## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: 61.0.1
 * Version (or revision) of Tree Style Tab: 2.5.1

**Comment by piroor** [comment]
Any error in the browser console (Ctrl-Shift-J) or addon debugger? And, which language do you use?

**Comment by Ploppz** [comment]
Today it is fine again.... sorry.
Probably the reboot fixed it.
English btw.
