### ISSUE TITLE
[feature request] Outdenting top-level parent tab outdents all direct child tabs by 1

### ISSUE THREAD

**Issue by rieje** [piroor/treestyletab#2007]
Feature request: outdenting top-level parent tab outdents all direct child tabs by 1. Currently, outdneting a top-level parent tab does nothing since it cannot be outdented further. There also doesn't appear to be a way to outdent (and indent) all child tabs at the same level. 

Adding this feature would not interfere with current behaviors and there are many cases where it is desirable to outdent child tabs at the same level, *especially* when the parent tab is top-level. For example, I group tabs by "tasks I want to complete." If I want to complete a task, I focus the parent tab (then all other parent tabs at top-level become minimized), then I outdent all direct child tabs of this parent tab as tabs "I want to work on." Visually/contextually, tabs at top-level are tabs I want to prioritize dealing with.

A more general way to deal with indenting/outdenting tabs at the same level is also appreciated, but I'm sure that's been requested before and is more complicated while also potentially conflicting with existing behaviors.

**Comment by piroor** [comment]
Did you mean that you hope to make tabs:

 * [tabA, active]
   * [tabB]
   * [tabC]

to:

 * [tabA, active]
 * [tabB]
 * [tabC]

by single action to outdent the tabA?

By the way, my another addon Multiple Tab Handler https://addons.mozilla.org/firefox/addon/multiple-tab-handler/ provides ability to select tabs by Ctrl/Shift-click and you can drag selected tabs at a time. It will become a workaround for this case.

Moreover I'm planning to support Firefox 63's nantive multiselection of tabs by TST itself. Then you'll be able to do it without MTH.

**Comment by irvinm** [comment]
@piroor please close this.
