### ISSUE TITLE
Favicons for tabs discarded via extensions are lost when the sidebar is closed and reopened

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#2012]
## Short description
When tabs are discard via an extension they still have their favicons but after Tree Style Tab's Sidebar is closed and reopened they disappear. Sometimes the Sidebar needs to be closed and reopened several times before a tab loses its favicon.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install an extension that can unload tabs such as [Unload Tab by Js](https://addons.mozilla.org/firefox/addon/unload-tab).
 4. Unload a tab with a favicon.
 5. Close and then reopen TST's sidebar.

## Expected result
The unloaded tab should still have its favicon.

## Actual result
The unloaded tab have lost its favicon and the default favicon is used instead.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 61.0.2
 * Version (or revision) of Tree Style Tab: 2.5.2

**Comment by piroor** [comment]
It looks a bug of Firefox itself. `browser.tabs.query()` for such discarded tab doesn't have correct `favIconUrl' property, so TST cannot initialize the tab with valid favicon.

**Comment by piroor** [comment]
Hmm, OK, I've updated the library for such an edge case: https://github.com/piroor/webextensions-lib-tab-favicon-helper/commit/5a7f013e48e6729524ba3b5af53819bd289636d6
I hope this change won't reintroduce the unexpected recursion issue...

**Comment by Lej77** [comment]
@piroor Thanks! I tested the latest development build (v2.5.2.7507) and the favicons for discarded tabs are no longer lost when the sidebar is closed and reopened.
