### ISSUE TITLE
On nightly, clicking the new tab button in TST no longer moves focus to URLbar

### ISSUE THREAD

**Issue by ripdog** [piroor/treestyletab#2014]
## Short description
On stable firefox, clicking the + on TST will open a new tab and move the focus to the URLbar. On nightly, the focus no longer moves.
## Steps to reproduce

 1. Start Firefox nightly with clean profile.
 2. Install TST.
 3. Click + to open a new tab

## Expected result
Focus to move to URLbar.

## Actual result
Focus stays on TST.

## Environment

 * Platform (OS): Windows and Linux.
 * Version of Firefox: 63a1 20180829100131
 * Version (or revision) of Tree Style Tab: 2.5.2

**Comment by piroor** [comment]
I couldn't reproduce this on my environments:

 * TST 2.5.3 + Nightly 63.0a1 (Build ID 20180830010250) on Ubuntu 16.04LTS
 * TST 2.5.3 + Nightly 63.0a1 (Build ID 20180830010250) on Windows 10

Could you try TST 2.5.3?

**Comment by ripdog** [comment]
Hmm, you're right - on a fresh profile, this works fine. (2.5.3 did not change it on my profile).

It's worth noting that this IS a new profile, but I used Firefox Sync to copy my old settings across. The old profile had the issue, and it has transferred across to this new profile.

I have disabled all other addons now, and TST alone is still exhibiting the bug.

Is there a way I could send you the TST configuration for you to test?

**Comment by Fanolian** [comment]
It is [Bug 1485307 - Opening a new tab with an extension doesn't focus the address bar if the new tab is overwritten](https://bugzilla.mozilla.org/show_bug.cgi?id=1485307).
It works expectedly with about:newtab (the default) but not about:blank.

**Comment by ripdog** [comment]
Ah, fair enough! Thanks for the research. Closing this now.
