### ISSUE TITLE
Tree Style Tab needlessly triggers discarded tabs to be reloaded

### ISSUE THREAD

**Issue by ssokolow** [piroor/treestyletab#2015]
## Short description

When I'm attempting to drag freshly created tabs into groups to file them, Tree Style Tab sometimes triggers an un-discard of every tab in the group, which causes the TST sidebar to slow to a crawl.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST, Multiple Tab Handler, and [Auto Tab Discard](https://addons.mozilla.org/en-US/firefox/addon/auto-tab-discard/) (or some other means of discarding tabs)
 3. Create some groups full of discarded tabs for test purposes and then collapse them
 4. Create and drag tabs into the groups

## Expected result

The tabs in the groups should stay discarded, since I've never actually focused them.

## Actual result

Whatever TST does causes Firefox to think it needs to reload every tab in the group.

## Environment

 * Platform (OS): Kubuntu Linux 14.04.5 LTS
 * Version of Firefox: 63.0b1 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.5.3

**Comment by ssokolow** [comment]
I think I've figured out a more reliable reproduction.

1. Set things up as before
2. Expand a group full of suspended tabs.
3. Drag a tab into it
4. Without shifting focus away from the tab inside the group, collapse the group.
5. The group will spring open again and all its contents will be forced to un-discard.

(As you might guess, this makes it difficult to sort my tabs and gives me a strong urge to curse.)

**Comment by piroor** [comment]
Sadly I still cannot reproduce this. Could you attach any screencast to describe the problem?

**Comment by ssokolow** [comment]
I'll try to find some time to make one within the next few days.

**Comment by ssokolow** [comment]
This is still on my TODO list. The last couple of weeks have been unexpectedly messy.

**Comment by ssokolow** [comment]
Sorry for the wait. Once I did managed to find time, it took me several more days to confirm that the bug got fixed since I reported it.

Given that Firefox's behaviour surrounding multi-tab selection has also changed since I reported this, I have no idea what caused the fix.
