### ISSUE TITLE
Sidebar is unresponsive after expanding the stack with height bigger than the height of the sidebar

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#2017]
TST 2.5.3, Nightly 30-08-18.
Hello! I've just noticed one thing: if I have a big number of tabs open and try to expand the long stack whose height in expanded state is bigger than the height of the sidebar then the sidebar becomes unresponsive for a couple of seconds.

I've recorded performance profile of background.html and sidebar.html:
[logs.zip](https://github.com/piroor/treestyletab/files/2338203/logs.zip)

Here's the image (the number of tabs is much smaller here, I am just trying to illustrate what I am talking about):
![12345](https://user-images.githubusercontent.com/26294581/44883583-466c4880-acc0-11e8-8473-12e2dd4c4b9d.png)

I've just realized that this performance issue might have something to do with the scrollbar? But that's just a guess.

**Comment by piroor** [comment]
Hmm, this doesn’t happen for me. I've tried with 25-53 tabs but they are collapsed/expanded immediately.

If there is another window with large number of tabs, file I/O from `storage.local` may cause such a problem.

**Comment by piroor** [comment]
The performance profile still says that reflowing/updating layout takes 30% time, but I can't imagine that how only 28 tabs cause such a problem...

**Comment by SXZ1** [comment]
Sorry, I wasn't clear enough, I can't reproduce the bug in a window with 53 tabs either. This bug is reproduced only in a window with big number of tabs (4000). I realize that is a ridiculous number so I reported about this performance problem hoping there might be some low-hanging fruits that are easy to optimize. 

Since the source of the problem is unclear, I think it's not worth spending your time on this bug any further. In the meantime, I will try to find exact STR. Also, a workaround I found so far is quite simple: expand a bunch of stacks so that the whole height of the sidebar was filled with tabs. Thank you very much!

**Comment by SXZ1** [comment]
It looks like this performance regression might be caused by the new tab button in the TST sidebar. To be more precise, by recalculating of its position. Is there any way to disable all the code related to new tab button? I tried to hide it but it didn't help.

**Comment by piroor** [comment]
I close this because outdated.
