### ISSUE TITLE
Installing TMP ontop of TST & MTH hides "Reload Tab" item

### ISSUE THREAD

**Issue by LazyGenius88** [piroor/treestyletab#202]
**Problem:**
When right-clicking on a single tab, "Reload Tab" no longer appears on right-click context menu.
---> *See links to images at bottom*

**Reproducing the error:**
Install latest beta of Tree Style Tab (12-15-2011 version)
Install Multiple Tab Handler
Install latest beta of Tab Mix Plus (12-20-2011 version)

**Additional Information:**
The first time I installed TMP on top of TST + MTH, I I was given the new pop-up menu asking me what to do with future [default] Ctrl+Click actions. At first I chose to "use MTH's features, but then I re-installed TMP and then I chose the option to "use TMP's features" to see if I could get rid of MTH all together (rather than having two extensions installed that perform similar action). Unfortunately, TMP's feature for closing All Tabs to the Right/Left doesn't work as well as MTH's "Close All Tabs to the Top/Bottom." So I re-installed MTH but wasn't greeted with the new pop-up asking me about Ctrl+Click functioning. 

Anyways, the "Reload Tab" right-click context menu item doesn't appear when only a single tab is selected. However, "Reload Selected Tabs" DOES appear when multiple (2+) tabs are selected. I don't know if selecting a different option for the Ctrl+Click function will fix this as I do not know how to get the pop-up to show again, and could not figure out the respective about:config value to change for this.

**RIGHT-CLICK CONTEXT MENU SCREENSHOTS** *(how many tabs selected + which add-ons were installed at that time)*

**Single Tab  - Orphan**
TST: http://tinypic.com/r/9hkk91/5
TST + MTH: http://tinypic.com/r/es4whh/5
TST + MTH + TMP: http://tinypic.com/r/1z3ysm0/5

**Single Tab - Parent of a Tree**
TST: http://tinypic.com/r/33a6xp0/5
TST + MTH: http://tinypic.com/r/es4whh/5
TST + MTH + TMP: http://tinypic.com/r/29vl5yg/5
*Only setting changed for MTH: checked "Close other trees except this one"*
*Only setting changed for TMP: unchecked all Right-Click context menu items pertaining to Tabs*

**Multiple Tabs - Two Orphans**
TST + MTH: http://tinypic.com/r/v5fvwm/5
TST + MTH + TMP: http://tinypic.com/r/2z55aa0/5

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
