### ISSUE TITLE
Some tabs disappeared from TST

### ISSUE THREAD

**Issue by sim642** [piroor/treestyletab#2021]
## Short description
Today at one point it somehow happened that all the tabs I had open disappeared from TST but they're still open in Firefox. New tabs that I open show up in TST fine. Switching to the old tabs from the tab bar works too but they don't reappear in TST. Reloading TST extension nor restarting Firefox fixes the issue.

Is there a way to possibly fix this or do I have to close all the tabs and manually open every single one again?

## Actual result
![screenshot_2018-09-02_22-32-39](https://user-images.githubusercontent.com/378740/44960022-6be79500-af00-11e8-9a4e-d72fadd562b3.png)

## Environment

 * Platform (OS): Ubuntu 18.04
 * Version of Firefox: 61.0.1
 * Version (or revision) of Tree Style Tab: 2.5.3

**Comment by piroor** [comment]
I close this because outdated. On such cases TST 3.0.10 should reload itself automatically.
