### ISSUE TITLE
Cursor not active in address bar after creating new tab.

### ISSUE THREAD

**Issue by GollyJer** [piroor/treestyletab#2024]
- Firefox 63.0b2 (64-bit) on Windows 10.
- Tree Style Tab 2.5.3

I never realized how often I click the new tab button (or middle click an empty area of the tab bar) and start typing into the address bar until the functionality broke. 🙂

With the stated versions of the software the address bar is no longer active when creating a new tab.
However, when using the new tab button of the default firefox tab bar the address bar does get activated.

**Comment by Fanolian** [comment]
Dupe of #2014.
