### ISSUE TITLE
"Bookmark All Tabs…" only works on some windows, not on others

### ISSUE THREAD

**Issue by Steve-Zenfolio** [piroor/treestyletab#2025]
## Short description
"Bookmark All Tabs…" only works on some windows, not on others

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Make some windows with various tabs open
 4. Right-click in each one's TST blank area or "+" button, pick "Bookmark All Tabs…"

## Expected result

All windows will create a new folder inside Bookmarks → Other Bookmarks containing all the tabs' bookmarks

## Actual result

Some windows do that, others do nothing at all.

I can find no rhyme nor reason about which windows will be which.  The set of windows that don't work seems to stay the same regardless of restarts or closing some windows, though.

## Environment

 * Platform (OS):  Win10
 * Version of Firefox:  61.0.2 x64
 * Version (or revision) of Tree Style Tab: 2.5.3

**Comment by piroor** [comment]
Thanks! The commit 88b5703 should fix this.

**Comment by Steve-Zenfolio** [comment]
Thank you!
