### ISSUE TITLE
Can you make the border between the tabs and page wider?

### ISSUE THREAD

**Issue by Ligerx** [piroor/treestyletab#2026]
I was wondering if there was a styling I could do to make the border between the tabs and page wider.

Back before Web Extensions, there was a "click to collapse" thing on the right side of the tabs which served as a spacer, but that's gone now.

![image](https://user-images.githubusercontent.com/6577974/45194237-0862ad80-b207-11e8-9bfb-fe4d5406d4fe.png)

**Comment by mdollinger** [comment]
As it is now very easy to show/hide the area using F1-key, there is no more need to have any kind of collapse-icon or a bar.
But may be it would improve the usability, if the border-line (or at least the area where you can grab it by mouse) was 1px wider. Currently i often miss the line - when my hand stops, i am too far already and have to move back.

**Comment by piroor** [comment]
> Back before Web Extensions, there was a "click to collapse" thing on the right side of the tabs which served as a spacer, but that's gone now.

It is impossible on WebExtensions version because the separator between sidebar and contents area is a part of Firefox itself. WE-based TST only can control inside the sidebar area.
