### ISSUE TITLE
Unknown localized message errors logged

### ISSUE THREAD

**Issue by asamuzaK** [piroor/treestyletab#2027]
## Short description

Unknown localization message errors are logged in browser console.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open browser console (`Ctrl + Shift + J`)
 4. 

## Expected result

no error.

## Actual result

errors logged:
```
Unknown localization message context_collapsed_label context-menu.js:44
Unknown localization message context_pinnedtab_label context-menu.js:44
Unknown localization message context_unpinnedtab_label context-menu.js:44
```

## Environment

 * Platform (OS):  Win 10
 * Version of Firefox: Nightly
 * Version (or revision) of Tree Style Tab: 2.5.3

**Comment by piroor** [comment]
Thanks. It is suppressed by cc96a09.
