### ISSUE TITLE
Ctrl+Tab does not go through children in order

### ISSUE THREAD

**Issue by HighCommander4** [piroor/treestyletab#2031]
## Steps to reproduce

 1. On a page with several links, open multiple links in child tabs with Ctrl+click.
 2. Press Ctrl+Tab repeatedly to navigate through the child tabs.

## Expected result

The child tabs are navigated through in the order in which they appear in the tree (which is also the order in which they were opened).

## Actual result

The child tabs are navigated through in seemingly random order.

My recollection is that this used to work until recently.

## Environment

 * Platform (OS): Debian stable
 * Version of Firefox: recent Nightly
 * Version (or revision) of Tree Style Tab: 2.5.4

**Comment by HighCommander4** [comment]
I understand that Firefox Nightly recently changed Ctrl+Tab to have "most recently used" behaviour in new profiles, but please note that in the profile I'm using, "Ctrl+Tab cycles through tabs in recently used order" is **not** checked in about:preferences.

**Comment by piroor** [comment]
TST actually doesn't handle Ctrl-Tab/Ctrl-Shift-Tab shortcuts, they are handled by Firefox itself. If both Firefox's native tab bar and TST's sidebar are visible, you'll see focus of tabs in the horizontal tab is consistently move left to right (or opposite) by Ctrl-Tab/Ctrl-Shift-Tab. When TST successfully track Firefox's tabs, both order of tabs in the horizontal tab bar and TST's sidebar must be same. So the actual problem on your environment looks: tabs in the sidebar are shown with wrong order.

So I need to know why TST cannot track correct order of tabs on your environment. I cannot reproduce this problem on my environment, and I think that something configuration or other addons is preventing TST's tab tracking. Could you describe clear steps to reproduce the problem from scratch (with clean profile)?

**Comment by HighCommander4** [comment]
I cannot reproduce this any more either. It may have been a bug in Firefox nightly, which was fixed in a newer nightly.

Thanks for looking!
