### ISSUE TITLE
"next sibling" opens same as sibling (as last sibling)

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#2035]
## Steps to reproduce

1. Start Firefox with clean profile.
2. Install TST.
3. open two tabs (A, B) with distinct content (any url)
4. select A
5. using the new tab drop-down open new tab C as sibling
6. it opens after B as expected
7. select A
6. using the new tab drop-down open new tab D as next-sibling
7. it opens after C instead of before B

## Expected result
A
D
B
C

## Actual result
A
B
C
D

## Environment

 * Platform (OS): win7 sp1 x64
 * Version of Firefox: 62.0.0
 * Version (or revision) of Tree Style Tab: 2.5.4

**Comment by piroor** [comment]
Thanks! The commit 5a91d2e should fix this problem.

**Comment by piroor** [comment]
I close this because outdated.
