### ISSUE TITLE
I get Javascript errors on both mozilla firefox and torbrowser while using TST 

### ISSUE THREAD

**Issue by shirishag75** [piroor/treestyletab#2037]
I have been getting the following errors while using TST both on firefox-esr and torbrowser 

```
JavaScript error: moz-extension://5f07f600-dde3-482d-8a3b-55a0c2e2911a/background/background.js, line 124: Error: Could not establish connection. Receiving end does not exist.
JavaScript error: moz-extension://5f07f600-dde3-482d-8a3b-55a0c2e2911a/background/tab-context-menu.js, line 60: Error: Could not establish connection. Receiving end does not exist.
```

I had to use about:debugging#addons  in order to find out that 5f07f600-dde3-482d-8a3b-55a0c2e2911a is owned by TST. 

Interestingly enough, even though the version of the addon in torbrowser-launcher and firefox-esr are the same i.e. TST 2.5.4 I found that the internal UUID in both browsers is different. 

Please let me know if any more info. is needed. 

TST version - 2.5.4 
Firefox version - 60.2.1esr-1 
torbrowser - 8.0.1 (based on Mozilla Firefox 60.2.0esr) (64-bit)

**Comment by piroor** [comment]
I hope that the changes 475f39d49baa597fa9c3a965c4a3dbc86527a093 suppress those messages you saw.

**Comment by piroor** [comment]
I close this because outdated.
