### ISSUE TITLE
Expand tree on focus without collapsing others

### ISSUE THREAD

**Issue by fredrikdomeij** [piroor/treestyletab#2039]
## Short description
"When a tab gets focus, expand its tree and collapse others automatically" is nice, but can we split it so that one optionally can enable "When a tab gets focus, expand its tree" without "collapse others automatically"?

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Enable "When a tab gets focus, expand its tree and collapse others automatically" in Settings
 4. Have a tree selected, select a collapsed tree, watch the old selected tree collapse

```
A
\- B (collapsed)
C
\- D
E (selected)
```

## Expected result
```
A (selected)
\- B (not collapsed)
C
\- D
E (not collapsed)
```

## Actual result
```
A (selected)
\- B (not collapsed)
C
\- D
E (collapsed)
```

## Environment

 * Platform (OS): Linux Ubuntu 18.04
 * Version of Firefox: 62.0
 * Version (or revision) of Tree Style Tab: 2.5.4

**Comment by piroor** [comment]
This is possible by a secret config item of TST. Go to TST's options => Development => Debug mode => All Configs, and uncheck `autoExpandIntelligently`.
