### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by qazip** [piroor/treestyletab#2040]
Please check the following screenshot: http://i.imgur.com/pjsQOid.png

As can be seen, some icons are missing. When a tab is hovered with the mouse, there should also be an "X" to close tab. That is also missing and switches to a grey square.

Any idea what could be causing this?

**Comment by piroor** [comment]
Does this problem happen on other theme, for example "High Contrast" or "Metal"? Those icons are constructed from SVG images with hacky methods in CSS. Moreover, if you use TST on Linux, the color scheme of the desktop environment also affects.

Another viewpoint, does this problem happen on a clean profile of Firefox? You can try Firefox with a clean profile with command line options like: `firefox -profile /tmp/temporary-profile -no-remote` (on Windows, `firefox.exe -profile "%temp%\temporary-profile" -no-remote`

**Comment by qazip** [comment]
It happens in all themes. I will try to see if it happens with a vanilla firefox (mine is pretty costumized, shadowfox and whatnot)

**Comment by qazip** [comment]
It is ShadowFox that breaks it.
