### ISSUE TITLE
Collapsed tabs groups are not skipped on Ctrl+PgUp/Down (FF Nightly 60.2.0)

### ISSUE THREAD

**Issue by warej** [piroor/treestyletab#2042]
## Short description
It seems, that after last FF update `Ctrl+PgUp/Down` navigates through the tabs in the FF order instead of the TST order (with some trees collapsed).

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Configure TST to `[...]skip collapsed descendants[...]`
 4. Recreate following tree structure:
```
A
\- B (collapsed)
C (selected)
```
 5. Press `CTRL+PgUp`

## Expected result
```
A (selected)
\- B (collapsed)
C
```

## Actual result
```
A
\- B (collapsed, but selected)
C
```

## Environment

 * Platform (OS): Windwos 10
 * Version of Firefox: Nightly 60.2.0esr (32-bit)
 * Version (or revision) of Tree Style Tab: 2.5.4

**Comment by warej** [comment]
Okay, got it. Thanks for the quick answer!

**Comment by piroor** [comment]
I close this because outdated.
