### ISSUE TITLE
Unable to drag and drop tabs to bookmark bar

### ISSUE THREAD

**Issue by prog-rajkamal** [piroor/treestyletab#2045]
## Short description
Can't drag-n-drop tabs from TST tabs to bookmarks bar. 

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Try to drag current tab and drop to bookmarks bar
 4. Firefox shows that operation is invalid (via disabled icon) and will not do it.

## Expected result
 Bookmark should be added to bookmark bar (as it happens from firefox's actual tab bar)

## Actual result
Tab is opened in separate window.

## Environment

 * Platform (OS):  Win 10
 * Version of Firefox: 62
 * Version (or revision) of Tree Style Tab:  2.5.4 (latest at current time)

PS: I have verified that other adons are not interfering with this. And DragNDrop works for firefox's native tab bar.

**Comment by piroor** [comment]
See #2033 please. This is a restriction from Firefox's incompatible change about `mozSetData`.

**Comment by prog-rajkamal** [comment]
@piroor thanks. the fix mentioned in that issue fixed it
