### ISSUE TITLE
Can Tree Style Tab override the "Open Link In Foreground/Background" behaviour

### ISSUE THREAD

**Issue by vonHabsi** [piroor/treestyletab#2047]
## Short description
This not so much a bug as a question about additional functionality

The question involves an issue I described on reddit [Is "Open Link In New Tab" conceptually different from "Open Link In Foreground/Background Tab"? : firefox](https://old.reddit.com/r/firefox/comments/9mdqwu/is_open_link_in_new_tab_conceptually_different/).

I am trying a keyboard navigation addon called [Saka Key](https://key.saka.io/) and when I open a link in a foreground or background tab it is opened as the last tab, rather than under the current tab when done from the `Open Link In New Tab` menu, or the way Google result searches are opened under the current tab.

Is it possible for an addon to override the "Open Link In Foreground/Background Tab" to cause a new tab to be opened under the current tab and can Tree Style Tab do it?

Could it also be that the developers of Saka Key are overriding any settings that an addon may have applied?

**Comment by piroor** [comment]
> I am trying a keyboard navigation addon called Saka Key and when I open a link in a foreground or background tab it is opened as the last tab, 

It is a problem of the addon Saka Key itself. The API to open a new tab from an addon `browser.tabs.create()` accepts a parameter `openerTabId`, and TST manages tree of tabs based on the information. I Saka Key uses the parameter for newly opened tabs, those tabs will become children of the current tab automatically.
