### ISSUE TITLE
Support creating bookmark folders in the bookmark toolbar

### ISSUE THREAD

**Issue by waldyrious** [piroor/treestyletab#2048]
Currently the "Bookmark this tree" feature can be configured to use a custom title for the bookmark folder that gets created. It would be nice to also allow specifying the target location for the bookmark tree, either on-the-fly via a dialog, or in the extension settings in the same way that the title for the folder is specified. In particular, I'd like to set the Bookmarks Toolbar as the default destination for bookmark trees created this way.

An alternative solution (even more convenient, IMO) would be to allow dragging a tree to the bookmarks toolbar. While it's currently possible to drag a single tab to the bookmarks toolbar using shift+drag (although the behavior can be swapped to plain drag, as described in #2033), dragging a tree creates multiple independent bookmarks rather than a bookmark folder.

I do prefer the second solution, but either one would work for me, so I'm fine with whatever is easier to implement.

**Comment by piroor** [comment]
As the first step, I've added an configuration UI to choose a bookmark folder:
![screenshot](https://user-images.githubusercontent.com/70062/46942613-ae2bf680-d0a8-11e8-8361-7cefdf7b033a.png)

**Comment by piroor** [comment]
Fake bookmark dialog in the sidebar is now available.
![screenshot](https://user-images.githubusercontent.com/70062/46954360-505cd600-d0cb-11e8-98a4-600bbc12b6cd.png)

**Comment by waldyrious** [comment]
Thanks so much for the quick reaction and implementation! Are you planning to close this issue once these changes are deployed in a release?

**Comment by piroor** [comment]
Now 2.6.1 is available.
