### ISSUE TITLE
some wierd icons on bottom of tab bar

### ISSUE THREAD

**Issue by Johnwick14** [piroor/treestyletab#2050]
can someone help me in removing these . pls this is bugging me from some time.
![screenshot 11](https://user-images.githubusercontent.com/44187866/46994008-03f7b180-d130-11e8-874c-c2dee60cc263.png)

**Comment by piroor** [comment]
Too less information. Please describe how to reproduce the problem on other environment.

**Comment by Prem514** [comment]
im new to github. didnt understand what u said .

**Comment by Prem514** [comment]
im using vertigo theme and those things appear on the bottom of the side bar.

**Comment by Prem514** [comment]
![screenshot 10](https://user-images.githubusercontent.com/44187866/46995398-33a9b800-d136-11e8-9bc1-8ae86cac7129.png)
here is the full image

**Comment by piroor** [comment]
Thank you for the large screenshot. I've realized that the theme color is different from Firefox's default and the skin of TST itself is also different from its "vertigo" skinl. Moreover, there are some missing UI elements - horizontal tab bar, sidebar header, and so on. Could you attach following information?:

 * URLs of addons and themes you installed
 * the contents of userChrome.css

**Comment by Prem514** [comment]
its firefox color, and i disabled the sidebar header and i restarted firefox with addons disabled and also restarted the firefox without userchrome.css but still those things arent going away.

**Comment by Prem514** [comment]
its firefox color, and i disabled the sidebar header and i restarted firefox with addons disabled and also restarted the firefox without userchrome.css but still those things arent going away. 
![screenshot 15](https://user-images.githubusercontent.com/44187866/46996188-61dcc700-d139-11e8-97c9-297a7abb1e2a.png)

**Comment by piroor** [comment]
Thanks! I've reproduced this problem on my environment successfully.

**Comment by Prem514** [comment]
so is there any solution?

**Comment by piroor** [comment]
The commit 546e5d1ee637411a6d0dd91e4c9a4cbf3edf9c2f should solve this problem. A program-side change is required, so there is no effective workaround, sorry. After https://github.com/mozilla/addons-linter/issues/2242 become fixed I'll update TST.

**Comment by piroor** [comment]
2.6.1 is now available.
