### ISSUE TITLE
Drag tab to Bookmarks Toolbar

### ISSUE THREAD

**Issue by freetomik** [piroor/treestyletab#2051]
## Short description
Add tab to Bookmarks Toolbar by dragging it there.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Do right click in Overflow Menu (next to search text line) and click on item to show Bookmarks Toolbar
 4. Drag some tab to Bookmarks Toolbar

## Expected result
Tab is added to Bookmarks Toolbar.

## Actual result
New window is opened with dragged tab and tab is not added to Bookmarks Toolbar.

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 60.2.2esr (64-bit)
 * Version (or revision) of Tree Style Tab: 2.5.4

**Comment by piroor** [comment]
See #2033. The next release of TST will have a draggable hanle on tabs: https://github.com/piroor/treestyletab/issues/2033#issuecomment-429655835

**Comment by piroor** [comment]
I misunderstood Firefox's spec about unknown permission. Now 2.6.1 is available so I close this.

**Comment by freetomik** [comment]
Thank you for quick fix! It works nice now.
