### ISSUE TITLE
Migrate to SVG icons with "context-fill"

### ISSUE THREAD

**Issue by piroor** [piroor/treestyletab#2053]
"context-fill" for icons is availble only on Firefox 62 and later, and doesn't work on ESR60. After ESR60 is outdated and new ESR (66 or 67?) is released, we need to switch icons to context-fill versions.

**Comment by piroor** [comment]
Theme color is applied only when `svg.context-properties.content.enabled` is `true`. I've tried to bypass this restriction by:

```javascript
{
  const icons = browser.runtime.getManifest().variable_color_icons;
  Promise.all(
    [browser.runtime.getBrowserInfo()].concat(
      Object.keys(icons)
        .map(size => {
          return new Promise((resolve, _reject) => {
            const request = new XMLHttpRequest();
            request.open('GET', icons[size]);
            request.addEventListener('load', () => {
              resolve({ size, data: request.responseText });
            });
            request.send();
          });
        })
    )
  ).then(results => {
    const browserInfo = results.shift();
    if (parseInt(browserInfo.version.split('.')[0]) >= 62) {
      const icons = { path: {} };
      for (const icon of results) {
        icons.path[icon.size] = `data:image/svg+xml,${encodeURIComponent(icon.data)}`;
      }
      browser.browserAction.setIcon(icons);
      browser.sidebarAction.setIcon(icons);
    }
  });
}
```

but it doesn't solve the problem...

**Comment by irvinm** [comment]
@piroor is this still on your radar?  Looks like next ESR is FF68 and will come out July 9, 2019.

**Comment by irvinm** [comment]
@piroor friendly reminder.

**Comment by piroor** [comment]
Sadly `svg.context-properties.content.enabled` is still `false` by default on Firefox 68. As the comment https://bugzilla.mozilla.org/show_bug.cgi?id=1391980#c1 the pref no longer become `true` for this purpose, so I have to give up this idea. Instead I think I should remove dynamic codes for this workaround and close this issue, after https://bugzilla.mozilla.org/show_bug.cgi?id=1367042 become closed.

**Comment by irvinm** [comment]
@piroor is it time to close this one?

**Comment by piroor** [comment]
Thanks I forgot about this.
