### ISSUE TITLE
TST moves new tab to the right-most when I create new tab with `browser.tabs.insertAfterCurrent`

### ISSUE THREAD

**Issue by masayuki-nakano** [piroor/treestyletab#2054]
## Short description

When you (just) create new tab, the new tab is moved to right-most of the tabs even when `browser.tabs.insertAfterCurrent` is set to true.

## Steps to reproduce

 1. Toggle `browser.tabs.insertAfterCurrent` to true from about:config
 2. Open 2 or more tabs with any URL.
 3. Activate the left-most tab.
 4. Create new tab with clicking "+" button in the tabbar, Ctrl+T or from "File" menu.

## Expected result

Then, new tab should stay immediately right of current tab (i.e., as 2nd tab).

## Actual result

Immediately after new tab is created right of current tab, it's moved to right-most in the window.

## Environment

I tested Win10/Nightly and Firefox 62.0.4/TST2.5.4

Note that the setting is introduced by Firefox 61 ([bug 1344749](https://bugzilla.mozilla.org/show_bug.cgi?id=1344749)).

(Sorry, I've not tested with latest TST development version yet, but I couldn't find issues related to "insertAfterCurrent" from either open or closed ones.)

**Comment by piroor** [comment]
The commit 8f71bee should "fix" this. I've updated TST to respect `browser.tabs.insertAfterCurrent=true` configuration done by the user and TST now does nothing for new tabs opened next to the current by the config (so "new tab location" and other configs are now ignored for such tabs, for example opened by Ctrl-T).

**Comment by masayuki-nakano** [comment]
Thanks! I confirmed that this issue has been fixed in 2.6.2.
