### ISSUE TITLE
Bookmark Tabs save only active tab

### ISSUE THREAD

**Issue by zorro-ms** [piroor/treestyletab#2056]
## Short description
I can't bookmark all tabs. 
Last successfully "Bookmark all tabs" where in September.

## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a few tabs
 4. Right click under tabs (grey zone, I use sidebar), choose "Bookmark Tabs..."
 5. Bookmark Tabs... options bookmark only active tab

## Expected result
I expect that this options Bookmark all tabs like before.

## Actual result
Bookmark only active tab.

## Environment

 * Platform (OS):  Windows 7 SP1
 * Version of Firefox: 62.0.3 64-bit
 * Version (or revision) of Tree Style Tab: 2.6.2 last updated 2018/10/18

![obrazek](https://user-images.githubusercontent.com/44255382/47138748-857b4b00-d2ba-11e8-921d-423ba5157ef9.png)

![obrazek](https://user-images.githubusercontent.com/44255382/47138759-8c09c280-d2ba-11e8-953f-157d80b7231c.png)

**Comment by piroor** [comment]
Sorry, as a workaround you need to install my another addon "Multiple Tab Handler" to get the feature back, until Firefox 63. TST's context menu items are now renewed imitating the native context menu of Firefox 64. The "Bookmark All Tabs" menu is removed on Firefox 64 and current behavior of TST's "Bookmark Selected Tabs" is just same to the one on Firefox 64 - you need to select all tabs manually at first. Multiple Tab Handler introduces Firefox63-like tab multiselection feature to TST.

Now I'm planning to reintroduce "reload all tabs" and "bookmark all tabs" commands again, for Firefox 62 and older versions (including ESR60)...

**Comment by piroor** [comment]
OK, reintroducing is done by recent commits.
