### ISSUE TITLE
Dragging tabs to bookmark toolbar not working

### ISSUE THREAD

**Issue by HifeFish** [piroor/treestyletab#2059]
## Short description
Dragging a tab to bookmark toolbar moves the tab to a new window, but does not create a bookmark.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Activate bookmark toolbar
 4. Drag tab to bookmark toolbar.

## Expected result
A bookmark is created. The tab remains where it is.

## Actual result
Tab is moved to a new window.

## Environment

 * Platform (OS): Ubuntu 16.04
 * Version of Firefox: 62.0.3
 * Version (or revision) of Tree Style Tab: 2.6.4

**Comment by piroor** [comment]
This is a FAQ. See also: https://github.com/piroor/treestyletab/blob/master/README.md#i-cannot-drop-tabs-to-the-bookmarks-toolbar-to-create-bookmarks

**Comment by piroor** [comment]
Oh, OK I've updated scrolling messages. Thank you for the feedback!
