### ISSUE TITLE
cursor switches back when hovering link

### ISSUE THREAD

**Issue by GiftWolf** [piroor/treestyletab#206]
From time to time a problem occurs: When I move the mouse cursor over a link it turns into a hand but then immediately switches back to arrow although the cursor is still over the link. The current tab becomes highlighted (i.e. changes color) during that moment. This behaviour stays this way until I move the mouse over the (auto-shrinked) tab bar. That fixes it temporarily.  I don't know what triggers this problem so I can't tell how to reproduce it. It just comes back every couple of hours or minutes. I don't know if it has to do with treestyletab because I have many other extensions:

Application: Firefox 3.6.25 (20111212142243)
Operating System: WINNT (x86-msvc)

- Adblock Plus 2.0.1
- Add to Search Bar 2.0
- All-in-One Sidebar 0.7.13
- Auto Copy 1.0.1
- CacheViewer 0.6.3
- Clippings 3.1.7
- Cookie Monster 1.1.0
- CookieSafe 3.0.5 (Incompatible)
- Download Manager Tweak 0.9.5
- Download Statusbar 0.9.10
- dragdropupload 1.9.38
- Element Hiding Helper for Adblock Plus 1.1.4
- Extension List Dumper 1.15.2
- Find All 3.1
- FireGestures 1.6.5
- Flashblock 1.5.15.1
- FlashGot 1.3.6
- Go Parent Folder 2.5
- ImageHost Grabber 1.6.5.5
- keyconfig 20110522
- Lazarus: Form Recovery 2.3
- Linkification 1.3.9
- LinkVisitor 3.3
- Mozilla Archive Format 2.0.2
- Multiple Tab Handler 0.6.2011120101
- NewsFox 1.0.8.3
- NoScript 2.2.4
- NoSquint 2.1.2
- OperaView 0.7
- Organize Search Engines 1.7
- Paste and Go 3 1.0.5
- Places’ Tooltips 3.0.20110409
- Plain Text Links 1.0.1
- Redirect Remover 2.6.4
- Redirector 2.5.2
- RefControl 0.8.15
- Restart Firefox 0.5
- Saved Password Editor 2.2.6
- SearchWP 2.4.2
- Session Manager 0.7.8.1
- Show File Size2 1.1.0
- Show my Password 2.0
- Tab Mix Plus 0.3.8.7
- Tree Style Tab 0.13.2011121501
- Vacuum Places Improved 1.2
- Web Search Pro 3.0.1

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
