### ISSUE TITLE
Pressing Esc when dragging tab moves tab to new window

### ISSUE THREAD

**Issue by HifeFish** [piroor/treestyletab#2060]
## Short description
Dragging a tab outside the sidebar and then pressing Esc moves a tab to a new window. 

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Drag tab outside the sidebar.
 4. Press Esc.

## Expected result
The tab remains where it is.

## Actual result
Tab is moved to a new window.

## Environment

 * Platform (OS): Ubuntu 16.04
 * Version of Firefox: 62.0.3
 * Version (or revision) of Tree Style Tab: 2.6.4

**Comment by piroor** [comment]
The commit b17992e should fix this.
