### ISSUE TITLE
"Reopen in Container" only appears if there are 2 or more containers configured.

### ISSUE THREAD

**Issue by joshuacant** [piroor/treestyletab#2061]
## Short description
"Reopen in Container" context menu item only appears if there are 2 or more containers configured. However, even with a single configured container, there are still effectively 2. The baseline "default" state of "no container" and then the 1 container you created. The menu item does appear correctly when right clicking on a stock Firefox tab, so in this case TST is out of step with FF's native handling of that menu.

## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install TST.
 3. Remove preconfigured containers, create a single one.
 4. Right click on a tab in TST

## Expected result
The "Reopen in Container" context menu item should appear on tabs not inside this container already. 

## Actual result
The "Reopen in Container" context menu item does not appear.

## Environment
 * Platform (OS): Win10 1809 x64
 * Version of Firefox: 64 beta
 * Version (or revision) of Tree Style Tab: 2.6.4

**Comment by piroor** [comment]
Thanks! The commit 06f21cb should fix this.
