### ISSUE TITLE
Some cookies are not set if treestyletab is active

### ISSUE THREAD

**Issue by jjlee** [piroor/treestyletab#2064]
## Short description

With a new profile, with TST enabled, I get fewer cookies set than if I disable TST.  That prevents me from logging in to giffgaff.com.  This does seem quite a surprising bug, but I was quite careful in verifying it.

Note I wasn't able to install the latest TST build because firefox 63.0 reported that it "appears to be corrupt": https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab.xpi -- so I installed TST version 2.6.4 instead.

## Steps to reproduce

Between attempts I was careful to remove all cookies and other storage visible (under all domains) in the web developer tools.

These steps require an account at giffgaff.com: I wasn't able to reproduce at giffgaff.com without attempted login to an existing account.  I have not tried reproducing the issue on other sites because I don't yet have any guesses what causes the bug!  I believe it is possible to create an account with "My giffgaff" -> "Log in" -> "Register here".

 1. Start Firefox with clean profile.
 2. Install TST 2.6.4
 3. Visit https://giffgaff.com
 4. Attempt to log in: Hover over "My giffgaff" (top right) and then click on "Log in" (top right, but lower down and a bit further left).  Enter a username and password (the account must exist already) and submit the form by clicking the "Log in" button.

## Expected result

Expect: approximately 33 cookies shown in Storage tab in web developer tools.  Able to log in.

As compared with the Actual result (see below), the missing cookies include ones named (a few of these may be spurious differences since the precise set of cookies seems to vary for reasons that aren't obvious):

    lithiumSSO%3Anapa
    moneySSO
    napaId
    napaUser
    RateSetterSSO
    XSRF-TOKEN
    ggM
    ideaLabs
    GGUID
    esportsSSO
    __s_idk__
    _gaexp

## Actual result

Got: approximately 18 cookies shown in Storage tab in web developer tools.  Not able to log in.

## Environment

 * Platform (OS): Linux, Ubuntu 18.04
 * Version of Firefox: 63
 * Version (or revision) of Tree Style Tab: 2.6.4

**Comment by jjlee** [comment]
I notice in `about:preferences` in the `General` tab, I have this:

`An extension, Tree Style Tab, requires Container Tabs.`

There's a button next to that `Disable Extension`.  Underneath is `Enable Container Tabs`, which is checked (enabled, presumably), but greyed out.

Maybe related??

**Comment by piroor** [comment]
Hmm, it is very odd. TST is not designed to affect to web contents. Moreover, the "Container" feature looks unrelated because another addon [Container Plus](https://addons.mozilla.org/ja/firefox/addon/container-plus/) doesn't cause such a problem.

**Comment by piroor** [comment]
Sadly my IP is blocked by the service because I've been trying to login again and again for debugging...

**Comment by piroor** [comment]
Anyway it is an unexpected side effect and I cannot imagine how to fix that. I'm guessing that this may be a bug of Firefox itself - errors or regular operations around WebExtensions APIs causing unexpected side effects.

**Comment by jjlee** [comment]
@piroor is there something I can do to help?  I've written a simple web extension in the past, but don't know much -- and I know almost nothing about firefox itself.  And as I say, I don't have any guesses about the specifics beyond your suggestion that it may be a firefox bug...

**Comment by piroor** [comment]
Some hours later, I successfully accessed the website again, so I've tried more debugging. Here are some information I got:

 * Basic observations of tab events looked not related.
 * Not a initialization problem. The problem still happen even if I skip all initialization processes.
 * After I removed the `tabs` permission from the manifest file, the problem goes away.

**Comment by piroor** [comment]
After more researchi I've realozed that "browser.tabs.onUpdate" listener of TabFavIconHelper module https://github.com/piroor/webextensions-lib-tab-favicon-helper causes the problem.

**Comment by piroor** [comment]
OK, I've found the trigger of the problem. The TabFavIconHelper module included in TST tries to download favicon image parallelly when an webpage is loaded, and helps to embed the image into the sidebar. I don't know details but the loading from the sidebar area may send HTTP request with some missing headers - referrer or others, so I'm guessing that it may trigger Cookie breakage.

**Comment by piroor** [comment]
Current operation around favicon loading is the compilation of workarounds for previous issues, so changing its behavior will introduce new regressions. So I think I cannot "fix" this bug by TST.

On the other hand, there is a bug/proposal about new API to load favicons without real HTTP access: [1315616 - Give extensions access to cached favicon URLs](https://bugzilla.mozilla.org/show_bug.cgi?id=1315616). If the bug become fixed, there will be no reason to do such a workaround and TST will become compatible to the website.

**Comment by jjlee** [comment]
That sounds like the right fix.

For now, I wonder if you might add a setting to disable favicon fetching (hopefully in such a way that they come back reasonably quickly when the setting is toggled back to enable favicons again)?  Without that, because I hide the tab bar in userChrome.css, it's hard to know if a website might be misbehaving because of this bug, without losing all visual access to tabs entirely (which happens if I disable TST).

**Comment by jjlee** [comment]
@piroor cool, I'll try the fix soon if I can figure out how to install the nightly xpi.

And thanks for all your hard work on this awesome extension of yours, I'm grateful for it.

**Comment by piroor** [comment]
Oops, sorry this issue ishas been closed by the "fix XXX" commit message unexpectedly. Anyway the problem looks fixed on my environment after the change. The operation triggerint this problem was introduced to memorize effective favicon information while the sidebar is closed. After this change TST does the background operation at 5 seconds after, and delayed loading won't block setting of cookies by the website.

**Comment by jjlee** [comment]
Sorry for the long delay in testing this.  I just tried with firefox nightly and the latest build at https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi and I still see the issue when logging into giffgaff.com

Odd since I think you reproduced the bug yourself?  I wonder if we're doing subtly different things?

What I did just now:

0. cd firefox/
1. ./firefox -P --no-remote
2. create a new profile
3. Install the addon: go to about:config and disable addon signature requirement, open new tab, close about:config, Ctrl-O, open the xpi from URL above, accept the warnings, close the tab for tree style tab info 
4. Navigate to https://giffgaff.com/
5. Click firefox tracking shield button and "Turn off blocking for this site"
6. My giffgaff -> Login
7. Enter "member name" (i.e. username)
8. Enter password
9. Click "Log in" button

Got: red banner at the top that says "Oops, wrong member name/mobile number or password. Remember passwords are case-sensitive, so double check and give it another go."

With the addon disabled I can log in.

Clutching at straws a bit: I have a UK IP address.

**Comment by piroor** [comment]
Fetching of the favicon image without login information looks to cause the problem. Hmm...

**Comment by piroor** [comment]
By 8839daa (and https://github.com/piroor/webextensions-lib-tab-favicon-helper/commit/032ace1938f721d0fecec030c3c1f088164ca99d ) TST now never test effectivitiy of favicon URLs for recent 30 entries. I think this change should solve this issue fundamentally.

**Comment by jjlee** [comment]
I tested again (sorry again for slow feedback).

I found that with the steps I wrote above (i.e. starting from a clean profile, with current firefox nightly and latest tree style tab build) I reliably was not able to log in on the first attempt.  Trying to log in a second time then reliably logs me in.  Without TST installed, I can reliably log in on the first attempt.

So this seems partially fixed, but still something about TST is disturbing this website's cookie handling a little.

**Comment by piroor** [comment]
I've done some more changes to reduce needless requests to the website in the background. How about the latest new development build?

**Comment by piroor** [comment]
Thank you for confirmation. Then, is this issue closable as fixed?

**Comment by jjlee** [comment]
Yes, as far as I can tell this is fully fixed :-)
