### ISSUE TITLE
Empty TST's submenu items

### ISSUE THREAD

**Issue by KageShiron** [piroor/treestyletab#2067]
## Short description
__ツリー型タブ(Tree Style Tab)__'s submenu get empty when context menu config changed.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open TST's config page and edit Context Menu items. ( or Firefox sync )
 4. Menu items get empty until restart firefox.

## Expected result
The menu TreeStyleTab has checked menu items.

<img width="766" alt="image" src="https://user-images.githubusercontent.com/17571233/47654066-63909b00-dbcd-11e8-840f-cb383ad3558a.png">

## Actual result
The menu TreeStyleTab has no submenu item.

<img width="351" alt="image" src="https://user-images.githubusercontent.com/17571233/47654082-6d1a0300-dbcd-11e8-900f-35281ffe3066.png">

("**ツリー型タブ**" item has no ">").

## Environment
 * Platform (OS): Mac OS X (and  Windows 10)
 * Version of Firefox: 63.0
 * Version (or revision) of Tree Style Tab:  2.6.4 and 2.6.4.7741

As far as I remember, this problem started about 2 or 3 weeks ago.

## Memo
雑な英語で申し訳ないです・・・
Firefox Syncを有効にしていると、しばらくして設定の更新が走るようで、気がつくと毎回メニュー項目が消えています。

https://github.com/piroor/treestyletab/blob/61b396d8df61d94c106701d000c1d10913b4952a/webextensions/background/tab-context-menu.js#L797-L805

少し処理を追ってみたところ、上記のメニュー更新処理周辺で「ツリースタイルタブ」のサブメニューの中身を全て削除したりすると期待するサブメニューが表示されました。ただ、サブメニューを削除すると偶然うまく動くというだけで、ここが原因ではなさそうというところまでしかわからず・・・

**Comment by piroor** [comment]
ありがとうございます、Firefox 63で現象が再現しました。Nightlyでは再現しなかったので、何かタイミングの問題なのかもしれません。

**Comment by piroor** [comment]
原因が分かりました、TST固有のAPIの実装が適当だったのを忘れてFirefox 64対応のために行った変更のせいでメニュー項目の削除がきちんとできていませんでした。。。
206f2d2 で直ったと思います。ご指摘ありがとうございます。

**Comment by KageShiron** [comment]
ありがとうございます。複数バージョンの同時対応はなかなか大変ですね><
TSTのためにFirefoxに移ってきたので、今後とも楽しみにしています！
