### ISSUE TITLE
about:treestyletab-group - discarded tabs \ session restart \ favicons missing

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2068]
## Short description
tabs.discard() was introduced in FF58 (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/discard) but immediately had problems with favicons and session management [Discarded tabs would lose their favicons after the browser was restarted but would restore properly once the tab was activated].  Firefox has been trying to resolve these issues and made some progress in FF63, so I decided to revisit this funtionality.

This is working much cleaner in FF63 [tab favicons are maintained both active and discarded even after a restart], but I noticed that using about:treestyletab-group appears to have issues with tabs that are discarded after restarting the browser.

## Steps to reproduce

 1. Start Firefox with clean profile [I didn't do this, but can do it if nothing around favicons is clearly a potential issue]
 2. Load tab(s) regularly
 3. Discard tabs via tabs.discard()
 4. Restart the browser allowing FF to start with tabs from the previous session

Starting FF and just inspecting all tabs under about:treestyletab-group, you can see all the tabs are properly discarded (hence dimmed via CSS for TST) but that most of the favicons are defaulted.

![tst1](https://user-images.githubusercontent.com/979729/47664799-306eed00-db76-11e8-8593-6aee748679df.png)

Clicking on each tab, the tab loads properly and then about:treestyletab-group properly reflects the tabs being active and with their favicons updated.

![tst2](https://user-images.githubusercontent.com/979729/47664956-74fa8880-db76-11e8-9bea-49ac1bcfbfc0.png)

Then using the add-on "Auto Tab Discard" which just calls tabs.discard() the tabs are properly discarded (dimmed again) but now about:treestyletab-group still shows their favicons.  (Even after reloading the page to make sure)

![tst3](https://user-images.githubusercontent.com/979729/47665101-bee36e80-db76-11e8-9af1-7a44775713c6.png)

Finally, just restarting FF results in the first screenshot with everything properly discarded, but no (or few) favicons in about:treestyletab-group.

## Expected result
Ideally, favicons on about:treestyletab-group should be the same as what is being shown on the tabs regardless of state.

## Actual result
about:treestyletab-group favicons are not consistent with the tabs themselves.

## Environment

 * Platform (OS):  Windows 10 x64
 * Version of Firefox: FF63
 * Version (or revision) of Tree Style Tab:  Latest

**Comment by piroor** [comment]
I've confirmed but it looks a regression of Firefox itself. On old versions, tabs returned by `browser.tabs.query()` for discarded tabs had effective `favIconUrl`. However, on Firefox 63 `browser.tabs.query({ currentWindow: true }).then(console.log)` says that those tabs has no effective `favIconUrl` property.

On the other hand, on Nightly (Firefox 65) discarded tabs returned by the API has effective favIconUrl with "data:" URI and the problem doesn't happen.

**Comment by irvinm** [comment]
Thank you so much for spending time on this.  Maybe I can try this out in FF65 and see how it behaves.

**Comment by irvinm** [comment]
@piroor , let me simplify:

- New profile
- Install TST and "Auto Tab Discard" (for discarding)
- Create group tab:  about:treestyletab-group
- Load some children
- Discard the tabs
- Restart the browser

You should see my final screenshot after that using 65.0a1.

**Comment by piroor** [comment]
Thank you for detailed descriptions! By recent commits I've done changes to use last effective favicon information for favicons in group tabs.

**Comment by irvinm** [comment]
Looking good with the new 2.7.0.  Closing.
