### ISSUE TITLE
colored tabs...

### ISSUE THREAD

**Issue by mausalimi** [piroor/treestyletab#2069]
not an issue at all, but...

i'm still using firefox ESR 52.9 with old TST AND colorfultabs together, it works nicely together.

sooner or later i need to switch to something newer i suppose, so i checked firefox 65 with new TST and new colorfultabs. with  this combination we can only choose one of them in the sidebar at a time.
so we have either standard tabs with color, or tree tabs with no color.

it would be very very handy if TST could have a similar color mechanism built in.

anyway, thank you for TST.

**Comment by irvinm** [comment]
You probably want to read over:  https://github.com/piroor/treestyletab/issues/1645

**Comment by mausalimi** [comment]
uh, sorry.

looks promising, but unfortunately after all unmaintained.

so i'll use ESR 52.9 for another 6 months at least.
