### ISSUE TITLE
feature: option to elevate tab closing actions to the top of the sidebar context menu

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#2070]
I am using the context menu almost entirely for tab closing actions.  I suspect others are too, as there isn't much other useful stuff there.  But the tab closing actions are split across the top level and two sub-menus

- close tab
- Tree Style Tab
  - close tree
  - close descendants
  - close other than tree
- Close Tab Options
  - close tabs to the bottom
  - close tabs to the top (does not exist, but would be useful)
  - close other tabs

The proposed option would place all enabled close actions in one top-level section of the menu

**Comment by piroor** [comment]
"close tabs to the top (does not exist, but would be useful)" is out of scope of TST (but I'll introduce it to TST if it is added to Firefox itself), but others are done by recent commits.

**Comment by bughit** [comment]
@piroor 

The top-level close actions are not working.

- win7 sp1 x64
- fx 64.0 x64
- new profile
- tst 2.7.4
- enable all close actions in the options
- open several trees
- the top level close actions do nothing, whereas the corresponding ones in the Tree Style Tab sub-menu work fine
  - close this tree
  - close descendants
  - close other tabs except this tree

**Comment by piroor** [comment]
Thanks, a64694c should fix this.
