### ISSUE TITLE
Dragging tab to bookmark menu create bookmark and new window simultaneously

### ISSUE THREAD

**Issue by fpob** [piroor/treestyletab#2072]
## Short description

Dragging tab to bookmark menu creates bookmark and simultaneously moves tab to new window.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Add bookmark menu to toolbar
 4. Shift+Drag to bookmark menu

## Expected result

A bookmark is created and tab remains where it is.

## Actual result

A bookmark is created and tab is moved to new window.

## Environment

 * Platform (OS): Fedora 29
 * Version of Firefox: 63.0.1 
 * Version (or revision) of Tree Style Tab: 2.6.8

**Comment by piroor** [comment]
The commit 379a42d should fix this problem. Basically TST should detach the dropped tab only when there is no handler (outside of the window, or the content area) and should not do detaching tabs when the drag data is handled by someone. By this change, TST always skip operations detaching of tabs when the drag action was started for bookmarking.

**Comment by piroor** [comment]
I close this because outdated.
