### ISSUE TITLE
'Close Other Tabs' and 'Close Tabs to the Right/Bottom' were moved back to main tab context menu in bug 1502083

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#2073]
## Short description
Firefox Nightly/Beta have reverted the changes that buried these options in a sub-menu. TST's sidebar context menu should follow suit.
[Bug 1502083 - Close other tabs buried in a menu](https://bugzilla.mozilla.org/show_bug.cgi?id=1502083)
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST 2.6.8.
 3. Right click on TST's sidebar
 4. Compare the context menu to the one on Firefox's default tab bar.

## Expected result
Close Tabs to the Bottom, Close Other Tabs should not be displayed in a sub-menu anymore.

## Actual result
Firefox wasted your effort imitating the "Close Tab Options" sub-menu. 

## Environment

 * Platform (OS): Win10 1809
 * Version of Firefox:  Nightly 2019-11-15 build
 * Version (or revision) of Tree Style Tab: 2.6.8

**Comment by piroor** [comment]
Thanks! I've done this by 5be7282.
