### ISSUE TITLE
[Feature Request] disassemble all trees

### ISSUE THREAD

**Issue by perdolka** [piroor/treestyletab#2075]
Add (to context menu) option to 
**disassemble all trees into separate tabs**.

**Comment by piroor** [comment]
Sorry I have no plan to add the command to TST itself. Instead you can create another addon to add such a feature via TST's public API (see also https://github.com/piroor/treestyletab/wiki/API-for-other-addons#detach-existing-child-tab-from-its-parent ), for example:

```javascript
async function disassembleAll(windowId) {
  const tabs = await browser.tabs.query({ windowId });
  for (const tab of tabs) {
    browser.runtime.sendMessage('treestyletab@piro.sakura.ne.jp', {
      type: 'detach',
      tab:  tab.id
    });
  }
}
```

**Comment by irvinm** [comment]
@piroor please close this.
