### ISSUE TITLE
"Move Current Tree Down" hotkey fails

### ISSUE THREAD

**Issue by micimize** [piroor/treestyletab#2081]
## Short description
Setting a hotkey for "Move Current Tree Up" Works fine, but move down fails, sometimes with the following flickering:
![move tree down bug](https://user-images.githubusercontent.com/8343799/49107458-670a5700-f24b-11e8-9191-1c1b6fd64949.gif)

## Steps to reproduce
1. Set hotkeys like so:
<img width="690" alt="screen shot 2018-11-27 at 13 48 55" src="https://user-images.githubusercontent.com/8343799/49107612-c36d7680-f24b-11e8-8aab-e0e24a85b1c8.png">
2. Attempt to use with a tree with children (sometimes you should get the flickering)

## Environment

 * Platform (OS): macOS Mojave 10.14
 * Version of Firefox: dev edition 64.0b13 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.6.8

**Comment by piroor** [comment]
Thanks. Behaviors of the command was broken and fixed by the commit 7a0f07f (and more recent commits).

**Comment by piroor** [comment]
I close this because outdated.
