### ISSUE TITLE
Question: Can I set transparent background in Mac OS X?

### ISSUE THREAD

**Issue by janjur** [piroor/treestyletab#2085]
This is just a question. Is there a way to set a Mac OS X style transparent background? Firefox surely supports that.

![image](https://user-images.githubusercontent.com/20413685/49369406-a58f8e00-f6f1-11e8-8ad8-466a66f9622e.png)

**Comment by piroor** [comment]
It is hard by some reasons.

 * Basically TST uses a colored background to hide some elements. Simply making background transparent will expose such hidden elements unexpectedly.
 * Firefox looks giving 100% untransparent background for the sidebar frame for addons. You will need to cancel it by some userChrome.css hack manually, and any WebExtensions addon cannot control that.

Anyway, if you find out how to do that with userChrome.css, please add it to the code snippets for other people: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#for-userchromecss

**Comment by piroor** [comment]
I close this because it is not a problem of addon side.
