### ISSUE TITLE
Making new tab greys out all other tabs

### ISSUE THREAD

**Issue by nh2** [piroor/treestyletab#2088]
## Short description

This is a new behaviour that , I think, only appeared in the last couple weeks. It might be a change in TST or a change in Firefox Nightly.

Assume my tab tree looks like this

![screenshot from 2018-12-08 12-25-19](https://user-images.githubusercontent.com/399535/49685515-d0f4ed00-fae4-11e8-8940-32dd39d8512a.png)

Then if I Ctrl+T or press the `+`-new-tab-button, the new tab appears and all other existing tabs are greyed out:

![screenshot from 2018-12-08 12-25-24](https://user-images.githubusercontent.com/399535/49685526-e9fd9e00-fae4-11e8-8d90-efee4c0b7f31.png)

As soon as I switch to another tab via mouse or keybaord, teh greying-out disappears and everything is normal again.

Is this an intended TST feature, or a regression?

## Environment

 * Platform (OS): Ubuntu 16.04
 * Version of Firefox: 65.0a1 (2018-12-07) (64-bit)
 * Version (or revision) of Tree Style Tab: 2.8.6.7835

**Comment by piroor** [comment]
I close this because outdated.
