### ISSUE TITLE
Feature request: Bookmarks

### ISSUE THREAD

**Issue by bluefiberbread** [piroor/treestyletab#2093]
Please let us bookmark all tabs that's currently open

**Comment by irvinm** [comment]
https://www.ghacks.net/2018/12/14/how-to-bookmark-multiple-tabs-in-firefox-64/

You have two options to do so on FF64+:

- Right-click on any tab in the browser and activate "Select All Tabs" from the context menu. Right-click again afterward and select "Bookmark Tabs" from the context menu.
- Select the first tab in the tabbar, hold down the Shift-key, and left-click on the last tab; this selects all tabs. Right-click on the selection and use the Bookmark Tabs option to bookmark all open tabs at once.

Yes, I know a single click option would be easier, but it is really just 2 clicks with Firefox already.

**Comment by bluefiberbread** [comment]
ctrl + shift + d works too

**Comment by piroor** [comment]
To avoid users' confusion around changes of the tab bar, TST respects Firefox's built-in behavior if it is possible, including multiselection of tabs. On the other hand, "Bookmark All Tabs" command is not a builtin of Firefox anymore and it is also unrelated to "tree" feature. By these reasons I have no plan to reintroduce the command to TST itself for now.

**Comment by piroor** [comment]
I close this because outdated.
