### ISSUE TITLE
Close tab by double click

### ISSUE THREAD

**Issue by PhilipGGG** [piroor/treestyletab#2095]
Hello,
There is any way to close a tab by double click?
I am finally moved to FF Quantum, and this option was one of my useful further in the old version.
I am find a way a way to close tab by double click at the TAB bar, but not in the Tree style tab, i will be happy if this option is available. 

Many Thanks,

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
Did you try the "Tree Style Tab Mouse Wheel"?: https://addons.mozilla.org/ja/firefox/addon/tree-style-tab-mouse-wheel/

To avoid users' confusion around changes of the tab bar, TST respects Firefox's built-in behavior if it is possible. On the other hand, the behavior you told looks not a builtin of Firefox and it is also unrelated to "tree" feature. By these reasons I have no plan to reintroduce the command to TST itself for now. However, for people who want to extend behaviors around TST's sidebar, it provides some public APIs for other addons. Here is a list of known addons enpowering TST: https://github.com/piroor/treestyletab/blob/master/README.md#addons-extend-tst

**Comment by PhilipGGG** [comment]
Thanks, I will try,
This option is Firefox's built-in behavior (without any extenuation) 
browser.tabs.closeTabByDblclick
Far as i now, a lots of users use in the old version "Tab Mix Plus", this was one of the useful further, TMP not support the new version of FF.
Many thanks,

**Comment by piroor** [comment]
1435142 - Pref to enable close selected tab by dblclicking it
https://bugzilla.mozilla.org/show_bug.cgi?id=1435142

Oh, I didn't know that it was introduced at Firefox 61. OK, I'll add a builtin option to simulate that.

**Comment by piroor** [comment]
I've introduced the option by the commit cf3c0804418e318088067665fc9ac8f4b648e165.

**Comment by piroor** [comment]
I close this because outdated.
