### ISSUE TITLE
Multi-selecting tabs switches focus, and to wrong tabs, if not initiating at first(top) tab

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#2097]
## Short description
When I select multiple tabs by ctrl-clicking them, it may switch the active tab and often it is a wrong tab.
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open about 5 or more tabs.
 4. Switch to Tab 3.
 5. Ctrl-click Tab 1. Ctrl-click Tab 2.

## Expected result
Tab 3 is still the active tab.

## Actual result
Tab 2 is the last selected tab but Tab1 becomes the active one.
Video showing the issue: https://gfycat.com/UnawareUnfitDuckbillplatypus

## Notes
Other selection sequences may trigger the bug too. But 3 > 1 > 2 is almost always reproducible. It seems that selecting Tab 1 (top-most) early triggers the bug easier.
I cannot reproduce it if Tab 1 is selected before multi-selecting others.

## Environment

 * Platform (OS): Windows 10 1809
 * Version of Firefox:  Nightly 2018-12-21 (20181220215605)
 * Version (or revision) of Tree Style Tab: 2.7.3 and 2.7.3.7940

**Comment by piroor** [comment]
Thanks! The commit 24eb5db should fix this.

**Comment by Fanolian** [comment]
Confirm fixed in 2.7.4. Thanks!
