### ISSUE TITLE
New tab button stops working.

### ISSUE THREAD

**Issue by aesthicc** [piroor/treestyletab#2099]
## Short description
New tab button stops working in TST 2.7+

## Steps to reproduce
1. Start firefox
2. Click new tab (new tab opens)
3. click it again (button stops working)

Tested in several ff profiles.

 * Platform (OS): macOS
 * Version of Firefox: 64.0
 * Version (or revision) of Tree Style Tab: 2.7.2 (reverted to 2.6.8 for now, this is working fine)

**Comment by piroor** [comment]
I couldn't reproduce this problem on my environment: Windows 10 + Firefox 64 + TST 2.7.3+ with clean profile. If you see this problem on your daily environment, could you narrow down conditions with clean profile? You'll do that with commands like:

```bash
$ cd /Applications/Firefox.app/Contents/MacOS
$ ./firefox-bin -profile "/path/to/blank/directory" -no-remote
```

**Comment by aesthicc** [comment]
Sorry, I figured it out. New tab override seems to be conflicting with tree style tab. When I disable this everything is fine.
https://github.com/cadeyrn/newtaboverride/

**Comment by aesthicc** [comment]
Disabling the "Set focus to the web page instead of the address bar" in NTO works too.
Thanks for helping.
