### ISSUE TITLE
Option to disable successor tab handling

### ISSUE THREAD

**Issue by rhendric** [piroor/treestyletab#2100]
I'm glad to see that you're getting good use out of the new successor tabs API! I have my own extension managing tab successors, and I'd like to continue using it alongside TST, so I was hoping I could persuade you to add an option to TST to entirely leave successor tabs alone, for such cases. Thank you!

**Comment by piroor** [comment]
Sorry, I tried to design TST to keep successorTabId as is if it is unneccesary but it was incompleted. After the commit a53e94a TST don't touch to successorTabId if focus control is disabled from its options.
