### ISSUE TITLE
How do I get a new window when I drag a tab from sidebar?

### ISSUE THREAD

**Issue by paulri** [piroor/treestyletab#2101]
I have TST updated to 2.7.4
When I had normal FF tabs on the top, I could click on a single tab, drag it off the tab bar, and it would form a new window. I noticed tonight that I can't do this with TST. I didn't see any option that would allow this to happen. 

Is this a bug, or is this not normal expected behavior? Or is this just something that TST can't do at the moment? 

Windows 10, FF 65b6 (64 bit)

**Comment by paulri** [comment]
When I drag onto the taskbar in Windows 10, I get a circle with a line drawn through it--same as what would usually happen when I would drag the new tab over the browser window portion of my screen. But after reading your post, I was finally able to avoid the circle when I dragged the tab over the window of the browser--but even then, the new window was hard to move. 

I will see if this repeats in different profiles, thanks for the quick reply.

**Comment by 4rz0** [comment]
I can only drag it into a different window. 
Previously, one could drag it onto the desktop for it to automatically open a new Firefox window with the dragged tab.
not sure if that's how it's supposed to work.

**Comment by irvinm** [comment]
@paulri, can we close out this item or are you able to still reproduce this?

**Comment by paulri** [comment]
You can close this out. Thank you.
