### ISSUE TITLE
get-tree API always returning undefined

### ISSUE THREAD

**Issue by rootkit-ty** [piroor/treestyletab#2102]
## Short description
When trying to call the get-tree API the promise will always return undefined.
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Debug the TST plugin
 4. Paste the following code
```javascript
browser.runtime.sendMessage(kTST_ID, {
  type:   'get-tree',
  window: 1,
  tabs:   '*'
}).then(item => console.log(item));
```
## Expected result
The tab Tree

## Actual result
Returns undefined

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 63.0.3 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.7.4

I'm trying to integrate TST with Tridactyl but am stuck since I can't actually get the Tree.

**Comment by piroor** [comment]
TST's APIs are callable from other addons, not TST itself.
