### ISSUE TITLE
Questions about TST API & an idea for new addon (Locked tabs)

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2104]
@piroor,

In thinking about doing another addon using your TST API, I want to implement a way to implement a menu selection off of the TST tabs (doable) that allow you enable\disable a new state (seems doable via the APIs to set custom states for tabs) to "lock" a tab [prevent it from being accidentally closed by clicking on the close "x" -- keeping the right-click "close tab" option would still work], then if the state is considered "locked" to be able to either:

1. Just remove the drawing of the closing "x" from the individual TST tab or more ideally ...
2. Remove the closing "x" and replace it with a small "lock icon" in its place.

I know you can remove all of the closing "x"s via CSS\userchome, but it is possible to do this on a tab by tab basis from an external add-on outside of TST?

Also, by registering the new add-on with TST and registering the states ... does this mean TST will will store that state information when tracking the tabs?

Just an idea I had based off of the discussion from:  https://github.com/piroor/treestyletab/issues/1836

While I agree the locking mechanism would be better done to handle all tabs, I doubt there is a way to inject an icon graphic to over-ride the close "x" via WebExtensions, but modifying it on your tabs seems more reasonable to achieve.  (I am also betting people also hide the horizontal tab bar much of the time when using TST anyway)

![37796353-790c30fe-2ded-11e8-9d24-0b41563ec73b](https://user-images.githubusercontent.com/979729/50429226-2114d300-088b-11e9-857a-a651efa172cd.png)

I do use large sessions in Firefox and also having a visual indicator (the lock) to show important tabs is also another way for me to find those tabs faster as well.  (Obviously they are also more "protected" then from accidental closure by clicking on the "x")

Any thoughts and\or feedback would be appreciated.

Sincerely,
Mike

**Comment by piroor** [comment]
I've tried small example for "lock tab" feature. (This is a public domain code - you can reuse this.)

```javascript
const kTST_ID = 'treestyletab@piro.sakura.ne.jp';

browser.runtime.sendMessage(kTST_ID, {
  type: 'register-self',
  name: browser.i18n.getMessage('extensionName'),
  icons: browser.runtime.getManifest().icons,
  listeningTypes: ['tab-mousedown', 'tab-mouseup'],
  style: `
    .tab.locked .closebox {
      display: none;
    }
    .tab:not(.faviconized).locked::after {
      content: "🔒";
    }
  `
});

const lockedTabs = new Set();

browser.runtime.onMessageExternal.addListener((message, sender) => {
  const locked = message.tab && message.tab.states.includes('locked');
  switch (message.type) {
    case 'tab-mousedown':
      if (message.ctrlKey && message.shiftKey) {
        browser.runtime.sendMessage(kTST_ID, {
          type:  locked ? 'remove-tab-state' : 'add-tab-state',
          tab:   message.tab.id,
          state: 'locked'
        });
        if (locked)
          lockedTabs.delete(message.tab.id);
        else
          lockedTabs.add(message.tab.id);
        return;
      }
    case 'tab-mouseup':
      if (locked && message.button == 1) {
        return Promise.resolve(true);
      }
      break;
  }
});

browser.tabs.onRemoved.addListener(async (tabId, removeInfo = {}) => {
  if (removeInfo.isWindowClosing)
    return;
  if (!lockedTabs.has(tabId)) {
    lockedTabs.delete(tabId);
    return;
  }
  // wait until the tab is closed completely
  await new Promise(resolve => setTimeout(resolve, 100));
  // and undo close tab
  const sessions = await browser.sessions.getRecentlyClosed({ maxResults: 1 });
  if (sessions.length && sessions[0].tab)
    browser.sessions.restore(sessions[0].tab.sessionId);
});
```

"Close Tab" commands of keyboard shortcut and context menu are still available, so this example tries to restore closed tab immediately. 

> Also, by registering the new add-on with TST and registering the states ... does this mean TST will will store that state information when tracking the tabs?

TST's fast restoration cache will contain extra states added by other addons, but I recommend you to store tab's state viia `browser.sessions.setTabValue()` by yourself and reset all states on the startup, because the cache may be cleared.

**Comment by irvinm** [comment]
Thanks!  This is perfect.  I'll see what I can do.

**Comment by vonHabsi** [comment]
If I want to apply this example which file do I have to add it to?

**Comment by irvinm** [comment]
This code would need to be added to a new add-on that interacts with TST.  (Not as easy as just adding this code to a file exactly)

**Comment by piroor** [comment]
Does anyone release a public addon for that? No one yet? I think that it's easy with an example addon  https://github.com/mdn/webextensions-examples/tree/master/runtime-examples , you just need to paste the example above to its background.js.

**Comment by irvinm** [comment]
I don't think it has happen yet.  I was still planning on doing some learning first, but would still like to try.

**Comment by irvinm** [comment]
Why did you ask by the way?  (This item was closed for several months already)  Were you interested in some way?

**Comment by piroor** [comment]
Because I've received an email to ask how to implement such an addon based on the example above. I thought to introduce its URL, If anyone already did that.

**Comment by irvinm** [comment]
So I gave it a shot today and was able to build a development addon, load it, and get it to work to some degree.

![image](https://user-images.githubusercontent.com/979729/60773249-bf9eae00-a0d0-11e9-8cf1-5e0efc350b64.png)


The code successfully checks to see if the state is already locked and if not it updates the lock icon and displays it.  However, it does not look like the stored state of the tab is ever updated to include "locked" and therefore all subsequent checks still return "locked = false" and therefore never clears the lock icon. 

`const locked = message.tab && message.tab.states.includes('locked');` always returns false.

Inspecting the "states" field of the tab it doesn't have anything in it.

![image](https://user-images.githubusercontent.com/979729/60773228-777f8b80-a0d0-11e9-930a-355569ac4de2.png)

I'm sure it is something I am doing, so I will keep playing with it.

**Comment by piroor** [comment]
Oh, yes, due to security reasons only some builtin classes are exposed to the `states` array now. So you need to track tab's `locked` state with `browser.sessions.setTabValue()` and `browser.sessions.getTabValue()`.

**Comment by piroor** [comment]
Updated example code:


```javascript
const kTST_ID = 'treestyletab@piro.sakura.ne.jp';

function registerSelfToTST() {
  browser.runtime.sendMessage(kTST_ID, {
    type: 'register-self',
    name: browser.i18n.getMessage('extensionName'),
    icons: browser.runtime.getManifest().icons,
    listeningTypes: ['tab-mousedown', 'tab-mouseup'],
    style: `
      .tab.locked .closebox {
        pointer-events: none !important;
      }
      .tab:not(.faviconized).locked .closebox::after {
        background: none;
        content: "🔒";
        line-height: 1;
        mask: none;
      }
    `
  });
}
registerSelfToTST();

const lockedTabs = new Set();

browser.runtime.onMessageExternal.addListener((message, sender) => {
  const locked = message.tab && lockedTabs.has(message.tab.id);
  switch (message.type) {
    case 'tab-mousedown':
      if (message.button == 0 &&
          message.ctrlKey &&
          message.shiftKey) {
        browser.runtime.sendMessage(kTST_ID, {
          type:  locked ? 'remove-tab-state' : 'add-tab-state',
          tab:   message.tab.id,
          state: 'locked'
        });
        if (locked) {
          lockedTabs.delete(message.tab.id);
          browser.sessions.removeTabValue(message.tab.id, 'locked');
        }
        else {
          lockedTabs.add(message.tab.id);
          browser.sessions.setTabValue(message.tab.id, 'locked', true);
        }
        // Please remind that this cancels TST's default behavior for the action.
        return Promise.resolve(true);
      }
      break;

    case 'tab-mouseup':
      if (locked && message.button == 1) {
        // Prevent to close the tab by middle click
        return Promise.resolve(true);
      }
      break;

    case 'ready':
      registerSelfToTST();
      break;
  }
});

browser.tabs.onRemoved.addListener(async (tabId, removeInfo = {}) => {
  if (removeInfo.isWindowClosing)
    return;
  if (!lockedTabs.has(tabId)) {
    lockedTabs.delete(tabId);
    return;
  }
  // wait until the tab is closed completely
  await new Promise(resolve => setTimeout(resolve, 100));
  // and undo close tab
  const sessions = await browser.sessions.getRecentlyClosed({ maxResults: 1 });
  if (sessions.length && sessions[0].tab)
    browser.sessions.restore(sessions[0].tab.sessionId);
});

browser.tabs.query({}).then(tabs => {
  for (const tab of tabs) {
    browser.sessions.getTabValue(tab.id, 'locked').then(locked => {
      if (!locked)
        return;
      browser.runtime.sendMessage(kTST_ID, {
        type:  'add-tab-state',
        tab:   tab.id,
        state: 'locked'
      });
      lockedTabs.add(tab.id);
    });
  }
});
```

**Comment by irvinm** [comment]
@piroor when using this with the default key assignment of "ctrl + shift", I think there is a conflict with how Firefox deals with multi-tab selections.  Once the multi-tab selection is stopped, everything works as expected.

It is hard to see with the brief animated gif, but while holding down "ctrl + shift" and clicking on several tabs, you can actually see a white lock positioned in the upper-left of the tab.  Then when I click on an individual tab, the locks properly show up on all the appropriate tabs.

Everything works fine if I click on a single tab, then hold "ctrl + shift", then click on the tab again.

Obviously, I could just change the key assignment away from ctrl + shift as I would imagine that would solve it ... but wanted to get your thoughts.  (I was going to try to disable multi-select to test my theory, but they seem to have removed the functionality for toggling it via browser.tabs.multiselect)

Either way, it isn't a big deal and it works as intended.

![2020-06-13_22-53-45](https://user-images.githubusercontent.com/979729/84583835-7cae8580-adcb-11ea-9f14-57e940bdea0a.gif)

**Comment by piroor** [comment]
I've updated the example implementation at https://github.com/piroor/treestyletab/issues/2104#issuecomment-509071304 including more stable styling for the "locked" icon.

> when using this with the default key assignment of "ctrl + shift", I think there is a conflict with how Firefox deals with multi-tab selections. Once the multi-tab selection is stopped, everything works as expected.

You need to return `true` explicitly (as a promised value) if TST's default reaction for the operation should be canceled. The old example returns nothing for the case so TST recognized the response as "allowed to continue the default reaction".

**Comment by irvinm** [comment]
Thank you!  It works much better now.  (I promise I will keep learning ... I am always amazed at how much knowledge you have around the Firefox addons environment!)

**Comment by irvinm** [comment]
@piroor everything has been working as expected and I even created a signed addon to use on my main browser.  I setup the tabs I wanted to lock but when I restarted my machine this morning I see that none of the tabs with the new state were still locked.  I confirmed this quickly by just toggling a few tabs and restarting again.  It does not appear the states are being saved across browser restarts.

**Comment by piroor** [comment]
The example implementation is not tested well. I think it should be continuously maintained and debugged but I have less motivation to do that sorry...

**Comment by irvinm** [comment]
Just for record keeping, I did publish this addon for anyone to use:  https://addons.mozilla.org/en-US/firefox/addon/tst-lock

Any comments/defects can be submitted here:  https://github.com/irvinm/TST-Lock/issues

I do use it daily and works as intended.

**Comment by piroor** [comment]
Thanks! I've added it to the list: https://github.com/piroor/treestyletab/wiki/Helper-addons-extending-functionality-of-TST

**Comment by SHHSSH** [comment]
@irvinm Could this addon be extended to override all other parameters regarding opening of clicked links from within the locked tab?

I.e; currently if a user clicks on a link in the locked tab, it will still open in that tab instead of a separate tab, and not(imo) be locked in such a manner that I feel "more locked", that's not to undermine your effort and I am very thankful for this addon nonetheless, as of course the user can also just Ctrl+Click a link, but I thought perhaps it a useful function within this helper addon.

Thanks for the work.

**Comment by SHHSSH** [comment]
Also this addon doesn't actually work for hotkeying Ctrl+W

**Comment by irvinm** [comment]
@SHHSSH currently the addon is only designed to handle preventing a tab from being closed by clicking on the "X" of the tab by replacing it with the lock.  In addition, I never added the ability for a keyboard short-cut.  (Although this part isn't that hard to add)  

However, as for your ask about overriding the "click on a link" behavior:  
1. I would need to look at how that could be handled and how complex that might be.  I am not sure how robust the WebExtensions API is for addons to change the behavior of trying to keep a link within the same page vs. just creating a new tab.  (Especially in cases, where the website is trying to do the same ... either keep it on the same page or creating a new tab)
2. I would also need to find a way to keep the current lock mechanism while adding some options to handle the links.
3. In my case, I use locks for just "important" tabs I want to make sure I don't lose ... and this is a different use case than yours.  I see this as 2 separate use cases that would need ways to visually show which one(s) are active and how to enable/disable them separately.

I've created an item to track this idea ... https://github.com/irvinm/TST-Lock/issues/12

**Comment by piroor** [comment]
Disabling of the Ctrl-W shortcut will need userChrome.js hack, because overriding of Firefox's built-in shortcuts is not allowed to WebExtensions addons.
https://stackoverflow.com/questions/61081055/unable-to-disable-ctrl-w-in-firefox-with-userchrome-js
