### ISSUE TITLE
Tabs are reloaded when closing a firefox windows

### ISSUE THREAD

**Issue by tcflorea** [piroor/treestyletab#2106]
## Short description
Closing a window will reload the closed tabs in the remaining window(s)
## Steps to reproduce
[
 1. Start Firefox with clean profile.
 2. Install TST.
]
 3. Open new tabs 1.1, 1.2 1.3  (e.g. using Ctrl+T).
 4. Open a new window ( e.g. using Ctrl+N) and a new tabs 2.1 and 2.2
 5 Switch to first window and close a few tabs (1.2 and 1.3) previously opened.
 6. Close the second window (tabs 2.1 and 2.2) (confirm closing multiple tabs)
Expected result:
 Only the tab 1.1 remains opened
Actual result:
 Tab 1.2 and 1.3 previoulsy closed are reopened/recovered. ( as I would have clicked Ctrl+Shift+T) in the remaining window)

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 64.0 (64-bit) and Nightly 66.0a1 (2018-12-23) (64-bit) and Nightly 66.0a1 (2018-12-25) (64-bit)
 * Version (or revision) of Tree Style Tab: 2.7.6. Last Updated December 25, 2018

This is the only extension (and no add-on for the firefox used).
The behaviour is as expected when disabling Tree Style Tab extension.
The bug seems to be new introduced as I was a happy user of Tree Style tab for ages.

**Comment by tcflorea** [comment]
The issue is not present in the version 2.7.2 an is present in the versions 2.7.3 to 2.7.6

**Comment by oscarus** [comment]
I've been experiencing the same issue with private windows. This has been happening for about a week.

**Comment by tcflorea** [comment]
I confirm the issue is fixed now in 2.7.7. Thank you!

**Comment by piroor** [comment]
I close this because outdated.
