### ISSUE TITLE
Toolbar Bookmark Left Click does nothing (Legacy 0.18.2016111701)

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [piroor/treestyletab#2108]
Gomennasai Piro-san for asking a question about an old version of your work.  I understand that you are now working on TST V2, so I am not filing a bug report.

Domo arigato gozaimasu for TST in general, and though I'm not using it at the moment, for rewriting TST to make it work with WebExtensions.  I know you wrote the original version for yourself and then decided to share it, so I really appreciate your effort!

After trying FF65 for a couple months, I have decided to go back to a last pre-WebExtension/pre-Signing FireFox version, because I can no longer bear to go without all the addons I love.  Whilst I'm still trying to trick FireFox 56.0.2 into allowing me to use unsigned addons, I've also installed WaterFox.  WaterFox seems to be working almost perfect with my old Nightly 49 profile, but I haven't tested everything yet.

There are some small issues with TST that I would like to ask about, that will help me fix the problems I have found quicker.
1)  Left clicking on bookmarks in the Bookmark Toolbar or the Bookmarks menu (from the FireFox Titlebar menu) does nothing when I have TST (Legacy 0.18.2016111701) enabled. Whist I can use right-click on Bookmark Toolbar bookmarks, I cannot on those in the menu.
2)  The Quick Bookmark (Ctrl/Cmd - D) function is not working and automatically puts bookmarks into the Bookmarks Menu list.  So I cannot choose to put my new bookmarks directly into a folder.
3)  The vertical height of the tabs is a little too small for the title, which makes it hard to read.

When I disable TST, all these issues go away and WaterFox works correctly.

I would simply ask if you could help me find the problem more quickly by indicating what parts of the TST JavaScript/CSS I should look at to find the source of these problems.

Is there a more recent TST legacy version than the one I'm using: 0.18.2016111701?

Thank you,
Nap.

 * Platform (OS): 
MacOS Mojave 10.14.1
 * Version of Firefox:
WaterFox 56.2.6
 * TST Version:
TST 0.18.2016111701 (Legacy)

**Comment by Napoleon-BlownApart** [comment]
I installed https://github.com/JustOff/ca-archive and then version TST v0.19.2017090601 and it's fixed all the issues except #2 in my list above.  :)

**Comment by piroor** [comment]
Sorry I don't maintain legacy TST anymore, instead I recommend you to use other forked versions like: https://github.com/oinkin/treestyletab
