### ISSUE TITLE
Command by Ctrl (control key) and mouse click

### ISSUE THREAD

**Issue by PhilipGGG** [piroor/treestyletab#2109]
Hi,
Maybe you can implement at the "Keyboard shortcut" option to use Keyboard and mouse + all the option at right click on the tab (or some).
F.E, I like to duplicate the TAB with "ctrl" and "click", this option is very useful and was implemented at the old FF, but not anymore (far as I know).
This option will help all users are asked to do command from the TAB right-click in a faster way without click + selecting and ...
Unfortnly, there is no any option to use Ctrl + mouse click for any command.

Many thanks,

**Comment by piroor** [comment]
I believe that it can be implemented via the API:
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#when-a-tab-is-clicked

**Comment by PhilipGGG** [comment]
Thanks, !!!

I am not "code" friendly ...

I hope someone can help and explain to me what to do to implement this option.

Anyway, thanks for "close tab by double-click" implementation!!!

**Comment by irvinm** [comment]
@piroor please close this.
