### ISSUE TITLE
Feature Request: Filter tabs

### ISSUE THREAD

**Issue by ragnarookie** [piroor/treestyletab#2111]
Would it be possible to add a search field / filter that hides all non-mathing tabs? There was an addon for the xul-version of TreestyleTab, but it seems to be gone (and I doubt it would work with the new web-extension api).

**Comment by piroor** [comment]
See the FAQ: https://github.com/piroor/treestyletab/blob/master/README.md#faq--frequently-rejected-requestsproposals

TST should work addons together which provide ability to filter Firefox's tabs. In other words, if there is any compatibility issue with such addons, I'll make effort to improve TST for better compatibility.

**Comment by irvinm** [comment]
@piroor please close this.

**Comment by piroor** [comment]
Additional info: now TST has an option to keep tree structure when tabs are shown/hidden by other addons. It should provides compatibility to another addon which filters tabs with the `tabs.hide()` API.

**Comment by mzso** [comment]
[**@piroor**](https://github.com/piroor) commented on [2019. máj. 12. 17:19 CEST](https://github.com/piroor/treestyletab/issues/2111#issuecomment-491604580 "2019-05-12T15:19:04Z - Replied by Github Reply Comments"):
> Additional info: now TST has an option to keep tree structure when tabs are shown/hidden by other addons. It should provides compatibility to another addon which filters tabs with the `tabs.hide()` API.

What would be an example of an addon like this? Is there one? So far I only saw addons that work on their own and not together with TST.

**Comment by piroor** [comment]
> What would be an example of an addon like this?

To be honest I don't know such an addon for now. I've never search such an addon deeply, because I don't need it on my use case. I mentioned about just a possibility.
