### ISSUE TITLE
Regression 2.7.0 breaks Multiple Tab Handler on Firefox 60

### ISSUE THREAD

**Issue by ghtstpm** [piroor/treestyletab#2114]
## Steps to reproduce
 1. Start Firefox ESR 60.4.0 with clean profile.
 2. Install TST 2.6.8 and Multiple Tab Handler 2.2.5
 3. Try selecting multiple tabs with Shift+Click
 4. Tabs are selected
 5. Install TST 2.7.0 or 2.7.7 (same result)
 6. Repeat step 3
## Expected result
 Tabs are selected
## Actual result
 Tabs are not selected

**Comment by piroor** [comment]
I close this because outdated.
