### ISSUE TITLE
How to Tab Context Menu hide userChrome.css ?

### ISSUE THREAD

**Issue by aquapple** [piroor/treestyletab#2116]
## Short description
I will hidden tab context menu. using userChrome.css, Did you have any idea?

## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install TST.
 3. Select tab and right click button.
 4. default context menu appearance, i would like hidden it.

## Expected result
Using userChrome.css, like this class.
.fake-contextmenu { display:none !important; }

## Actual result
Do not work '.fake-contextmenu' class name.

## I hope action...
???  { display:none !important; }
fake menu context class name and display none, customize it.
In Japanese,
TST独自のコンテキストメニューを使用したいので、
初期設定状態で右クリックしたときに表示される項目を全て非表示にしたいです。
ソースコードをみるとfake-contextmenuなるクラス名が定義されているようですが、
.fake-contextmenu { display:none !important; }と指定しても非表示になりません。
デフォルトのメニュー項目を隠すためのクラス名が知りたいです。

## Environment 

 * Platform (OS): Windows 10 Home Build 17763.195
 * Version of Firefox: 64.0 release
 * Version (or revision) of Tree Style Tab: "2.7.7" instead of "latest"

**Comment by piroor** [comment]
「このツリーを閉じる」などのTSTが提供するメニュー項目だけを使用したくて、「タブを再読み込み」などの項目は表示したくない、ということでしょうか？

だとすると、これらの項目はFirefox 64の場合は https://searchfox.org/mozilla-central/rev/bcc0fe1081dc4f84fc5fdfebe0d2de8c075a4e2c/browser/components/extensions/parent/ext-menus.js#259 の部分で自動生成されていて、ここを見る限りは特別なクラスなどは設定されていないようです。
項目のIDはアドオンのIDとAPI経由で指定されたIDから https://searchfox.org/mozilla-central/rev/bcc0fe1081dc4f84fc5fdfebe0d2de8c075a4e2c/browser/components/extensions/parent/ext-menus.js#703 のロジックで生成されているため、userChrome.cssで属性セレクタを使って以下のように書くと、TSTが定義している「タブのコンテキストメニューと互換の項目」を隠す事はできます。

```css
*[id^="treestyletab_piro_sakura_ne_jp-menuitem-_context_"] {
  display: none;
}
```

ただし、この場合、各項目は「ツリー型タブ」サブメニューの配下に表示されるままとなります。
このサブメニューの内容に相当する項目すべてを最上位に表示させるという事は、userChrome.cssではできません。


そうではなく、「Firefox 64以降で使われるようになった、他のアドオンとの互換性が向上したコンテキストメニューを使いたくなくて、常にTSTが提供する偽のコンテキストメニューを使いたい」という事でしょうか？
だとすると、残念ながらそれはできません。
CtrlキーとShiftキーを両方とも押しながらツリーの上で右クリックすると、従来どおりの偽コンテキストメニューを一時的に開くという事はできます。この時は、アクティブなタブ以外ではCtrl-Shift-クリックによるタブの複数選択が同時に行われてしまう点に注意が必要です。

**Comment by piroor** [comment]
英語話者の人のために一応英語でも書いておきます。


Did you want to use only TST specific context menu items like "Close This Tree" and others, and hide other emulated items like "Reload Tab"?

Then, on Firefox 64 those items are generate by Firefox at https://searchfox.org/mozilla-central/rev/bcc0fe1081dc4f84fc5fdfebe0d2de8c075a4e2c/browser/components/extensions/parent/ext-menus.js#259 and those items have no special classnames. Instead, their IDs are autogenerated by https://searchfox.org/mozilla-central/rev/bcc0fe1081dc4f84fc5fdfebe0d2de8c075a4e2c/browser/components/extensions/parent/ext-menus.js#703 from the ID of the addon itself. So CSS codes in userChrome.css below will hide such emulated items in the menu:

```css
*[id^="treestyletab_piro_sakura_ne_jp-menuitem-_context_"] {
  display: none;
}
```

Please note that TST specific commands are still grouped under the "Tree Style Tab" submenu. You cannot move them to the top level of the menu by userChrome.css.


Did you want to deactivate new context menu on Firefox 64 and later and reactivate simulated fake context menu of TST itself?
Then, sorry but it is impossible.
Right-click on a tree with Ctrl AND Shift key will show old fake context menu, but it is just temporary. Moreover, please note that Ctrl-Shift-click on non-active tab will produce multiselection of tabs unexpectedly.

**Comment by aquapple** [comment]
@piroor 

Thankyou replay for your answer.
What I wanted to do is the first method.
```
> *[id^="treestyletab_piro_sakura_ne_jp-menuitem-_context_"] {
>   display: none;
>  }
```
I tried this code in userChrome.css, after Firefox relaunch, The default menu is hidden.

However, as @piroor suggested, it was not possible to display at the top level.

This is the specification of Firefox 64.0 or later?

Even just the solo harvest. Although the operation of the mouse increased one, the messy fake munu disappeared and it cleared up.

I would like to use it as it is.
Thank you very much for your response.

Best, Regards.
