### ISSUE TITLE
Order of tabs breaks when pinning a tab lower down

### ISSUE THREAD

**Issue by hkockerbeck** [piroor/treestyletab#2118]
## Short description

When I pin a tab that is not at the top of the list, left clicks on the tabs that were before it are shifted and not assigned to the correct tab. Right clicks seem to work correctly. I've noticed this problem since yesterday, so it has probably been introduced with version 2.7.8.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open, let's say, four tabs: A, B, C, D
 4. Pin another tab than the first in the list, let's say C
 5. Now the displayed order is
   C (pinned)
   A
   B
   D
 6. Left click on tab B to select it.
 7. Tab A gets selected instead of B.

## Expected result

Left clicks get assigned to the tab I clicked on.

## Actual result

For tabs that were, in unpinned order, before the pinned tab, left clicks are assigned to the wrong tab, probably to the tab that _were_ at this position if the tab(s) weren't pinned.

## Environment

 * Platform (OS): Ubuntu Linux 18.04.1
 * Version of Firefox: 64.0
 * Version (or revision) of Tree Style Tab: 2.7.8

**Comment by piroor** [comment]
Thanks. I've released 2.7.9 including a fix for this problem.

**Comment by piroor** [comment]
I close this because outdated.
