### ISSUE TITLE
New Tab Button does not create a new tab.

### ISSUE THREAD

**Issue by azazello4** [piroor/treestyletab#2121]
## Short description
Clicking on NewTab Button does not create a new tab.

## Steps to reproduce
I did not found the trigger for this issue yet. I can't pinpoint any particular setup to make it stop working.
I'm still able to use CTRL+T to open new tab. It seems to happen simultaneously with another issue: "_clicking on a tab focuses on another tab_" (I've seen a few issues opened here about that).
This is the log after clicking on the button:

```
tst<BG>: background/handle-misc:     new tabs requested:  
Object { parent: undefined, insertBefore: undefined, insertAfter: "tab-3-38", isOrphan: true, windowId: 3, inBackground: false, cookieStoreId: null, inRemote: false, type: "treestyletab:open-new-tabs", uris: (1) […], … }
common.js:323:5
tst<BG>: common/tabs-open:      openURIsInTabs:  
Object { uris: (1) […], options: {…} }
common.js:323:5
Error: tab is null
```

## Expected result

Clicking NewTab Button opens a new tab.

## Actual result

Clicking NewTab Button doesn't opena new tab.

## Environment

 * Platform (OS):  Windows 10 1809
 * Version of Firefox: 65.0b8 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.7.10

**Comment by azazello4** [comment]
* I'm still able to use CTRL+T to open new tab. It seems to happen simultaneously with another issue: "clicking on a tab focuses on another tab" (I've seen a few issues opened here about that).

**Comment by piroor** [comment]
Does this problem still happen with the latest development build?

**Comment by grantcarthew** [comment]
Still and issue here: FF 64.0.2 TST 2.7.11

**Comment by metronidazole** [comment]
Fixed with the latest dev build for me.

**Comment by azazello4** [comment]
After trying for these two days the latest dev build, it seems to be fixed.

**Comment by piroor** [comment]
Is this issue closable?

**Comment by azazello4** [comment]
It seems like so.
