### ISSUE TITLE
[Bug?][2.7.14] Left-click on tab doesn't work with browser.tabs.multiselect set to false

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#2123]
Latest Nightly, TST2.7.14. Bug is not reproduced in TST2.7.13. 

STR:
Set browser.tabs.multiselect to false and try to left-click on any non-active tab.

ER: Tab is selected
AR: Nothing happens

That might not be a bug at all, I just want to make sure everything works as expected. Thank you very much!

**Comment by piroor** [comment]
By the change https://github.com/piroor/treestyletab/commit/7ca96dbf5fc5ccf9a86db4236a91c00b122e5713#diff-67175a1ae7814f80dc52b6326afbcff4R22 , now TST depends on multiselection feature on Firefox 64 and later. It is impossible to detect Firefox's multiselection support is activated or not from addons, so I'll need to add a new checkbox to the options page like "Activate legacy tab focus method (*turn this on when you set `browser.tabs.multiselect` to `false`)".

**Comment by piroor** [comment]
I've introduced such a checkbox by c5738814888f0748e2e4d94f9537515cfe559231.

**Comment by SXZ1** [comment]
Awesome job, thank you!
