### ISSUE TITLE
Remove TST from tab  context

### ISSUE THREAD

**Issue by nollinvoyd** [piroor/treestyletab#2125]
* Platform (OS):  Windows 10 Pro
 * Version of Firefox: Firefox 64.02
 * Version (or revision) of Tree Style Tab: 2.7.16

How can I  remove TST from the tab context menu?

thanks

**Comment by piroor** [comment]
Did you reported about the "Tree Style Tab" submenu in the context menu on tabs? Then, please go to TST's options and deactivate items under the "context menu" section. Then the submenu will become hidden.

**Comment by nollinvoyd** [comment]
thanks
