### ISSUE TITLE
Bug 1489814 breaks compatibility of TST 2.7.8+ and extension "Tab flip for Tree Style Tab"

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#2127]
## Short description
In release 64.0.2 and current Nightly 2019-01-12, [Tab flip for Tree Style Tab](https://addons.mozilla.org/firefox/addon/tab-flip-for-tree-style-tab/)(TF) 1.1.0 does not switch active tabs with mouse clicks since TST 2.7.8. Keyboard shortcut for that extension still works.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST 2.7.8 or later.
 3. Install [Tab flip for Tree Style Tab](https://addons.mozilla.org/firefox/addon/tab-flip-for-tree-style-tab/) 1.1.0 (latest release)
 4. Open at least 2 tabs. Left click any non-active tab so it becomes active.
 5. Press Ctrl-F2 to confirm Tab Flip is working, i.e. active tab is switched.
 6. Left click on the now-active tab.

## Expected result
The previous tab should now be active.

## Actual result
The current tab (the tab you clicked) is still active. According to the tab indicator, active tab may have momentarily flipped on mouse-up but quickly switched back to current tab.

## Notes
A quick summary:

Tab Flip works? | TST 2.7.7 | TST 2.7.8+
---- | ---- | ----
prior bug 1489814 | ✓ | ✓
after bug 1489814 | ✓ | ✗

I tested some old Nightly builds and found that TF 1.1.0 with TST 2.7.8 to 2.7.16 actually worked until 2018-10-05 build. Mozregression points to [bug 1489814](https://bugzilla.mozilla.org/show_bug.cgi?id=1489814).

I don't know whether TST, TF, or Firefox should be responsible for this bug. Would you provide some insights so I can redirect this issue to them?

Thank you.

## Environment

 * Platform (OS): Win 10 1809
 * Version of Firefox:  Firefox 64.0.2.  Nightly 2019-01-12 (20190112094119)
 * Version (or revision) of Tree Style Tab:  2.7.8 or later.

**Comment by piroor** [comment]
I've realized that this should be fixed by tst-tabflip. It is tracked at: https://framagit.org/ariasuni/tst-tabflip/merge_requests/1

**Comment by polyzen** [comment]
@piroor, thank you, as usual.

Upstream report: https://framagit.org/ariasuni/tst-tabflip/issues/2

**Comment by ariasuni** [comment]
Sorry, I don’t know how I missed that issue and PR, this is now fixed.

**Comment by Fanolian** [comment]
> 
> 
> Sorry, I don’t know how I missed that issue and PR, this is now fixed.

Thank you!
