### ISSUE TITLE
What are drag handles?

### ISSUE THREAD

**Issue by nollinvoyd** [piroor/treestyletab#2129]
I have "SHOW DRAG HANDLES ON A EDGE OF EACH TAB" checked.  So what do these handles look like and where do I find them?

thanks  

Firefox 64.02
Windows 10 Pro
TST SHOW DRAG HANDLES ON A EDGE OF EACH TAB

**Comment by Lej77** [comment]
Hover over the left part of a tab for a second without moving the mouse. This will show some icons that you can drag and drop to perform different actions such as bookmarking the dragged tab or detaching it from the current window.

**Comment by piroor** [comment]
I've added more descriptions about drag and drop configs. I hope these changes help people from too less described configs...
![image](https://user-images.githubusercontent.com/70062/51223216-54c3b400-1984-11e9-85c4-2ded87e63269.png)

**Comment by nollinvoyd** [comment]
So this is what the tooltip should look like?

![tst2](https://user-images.githubusercontent.com/20844322/51495961-055df900-1d73-11e9-96a5-960053def8d7.png)

I'm using the custom css.  This is what the tooltip looks like for me.  It's that shadowy, barely perceptible figure on the left side.

![tst](https://user-images.githubusercontent.com/20844322/51496050-4e15b200-1d73-11e9-8d67-24a228c91c19.png)

**Comment by piroor** [comment]
> So this is what the tooltip should look like?

Yes.

I've tried the stylesheet posted at https://github.com/piroor/treestyletab/issues/2115#issuecomment-453781888 but the drag handle works as expected. If you use more CSS rules, it may break the feature.

**Comment by piroor** [comment]
I close this because outdated.
