### ISSUE TITLE
Cannot click tabs opened with Swift Selection Search add-on

### ISSUE THREAD

**Issue by LachlanStuart** [piroor/treestyletab#2131]
## Short description

TST throws an error when trying to change to tabs that were opened by the Swift Selection Search add-on. This only started happening for me in the last week.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST (v2.7.16 or 2019-01-15's nightly)
 3. Install [Swift Selection Search](https://addons.mozilla.org/en-US/firefox/addon/swift-selection-search/) (v3.29.2)
 4. Select some text and right-click it.
 5. At the bottom of the context menu expand Swift Selection Search's "Search for ..." sub-menu
 6. Click Google or any other search engine. This should open a new background tab.
 7. Click the new background tab in TST. 

## Expected result

It switches to the background tab.

## Actual result

Clicking does not change to the background tab.

In the browser console every click on the background tab in TST logs this message:
```
Error: No tab at index: 10000
```

Using the built-in Firefox tab bar works as expected. Sometimes after opening new tabs or dragging tabs in TST the broken tabs will start working again.

## Environment

 * Platform (OS): Mac OS
 * Version of Firefox: Firefox Quantum 64.0.2 (highly used profile) and Nightly 65.0b11 [from this revision](https://hg.mozilla.org/releases/mozilla-beta/rev/8574d2808aaa0afa131cc57be70b86dad3398ff0) (completely fresh profile, no settings changed from default)
 * Version (or revision) of Tree Style Tab: v2.7.16 and nightly for 2019-01-15

**Comment by piroor** [comment]
Thanks. This problem should be fixed by 44e62d0.

**Comment by LachlanStuart** [comment]
I can confirm the fix - I stopped having this issue with the latest TST nightly.

Thank you very much for such a fast response!

**Comment by piroor** [comment]
I close this because outdated.
