### ISSUE TITLE
how to remove active tab marker

### ISSUE THREAD

**Issue by aesthicc** [piroor/treestyletab#2132]
## Short description
Unable to remove the active tab marker that showed up since the latest update(s).
I'm using "no decoration" appearance.

.active-marker
{
    display: none;
}
?

## Environment

 * Platform (OS): 
 * Version of Firefox: 64.0.2
 * Version (or revision) of Tree Style Tab: 2.7.16

**Comment by Lej77** [comment]
try
```css
.highlighter
{
  display: none;
}
```

**Comment by aesthicc** [comment]
Thanks!
