### ISSUE TITLE
[feature request] Some way to report errors happening on an existing session

### ISSUE THREAD

**Issue by hmijail** [piroor/treestyletab#2133]
Sometimes an error appears in the middle of a big session, in a way that possibly would be easy to diagnose but hard to replicate. Looking at the state of TST at that point might be useful. Would it be possible to do so?

For example: Right now I have a big session (hundreds of tabs, multiple windows). I dragged a small tree (parent + 2 children, dragging by the parent) outside of their window to create a new window.
The new window broke the tree structure, and a new, unselectable, unopenable tab appeared in TST (but not in Firefox's tab bar): 
```
Parent
Children1
\-Children2
New tab
```
Furthermore, I tried again dragging another small tree to create a new window and TST stayed forever showing its "in progress" animation.
My assumption is that looking at the state of TST in those 2 windows would be useful, no matter the other hundred tabs and windows and add-ons around.

The times I have tried recreating this kind of problem with a clean profile it never worked; probably because I can't spend much time in such a clean profile so I can only test for a few minutes, but the bug being chased is some subtle problem that only appears when the session gets messy enough.

## Environment

 * Platform (OS): macOS 10.14.2 (18C54)
 * Version of Firefox: 65.0b11 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.7.16

**Comment by private-lock** [comment]
Did you see the [wiki](https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs)?

**Comment by hmijail** [comment]
I didn't. Thank you, will try following those instructions.
