### ISSUE TITLE
[incompatibility] group tabs not working after Firefox start in certain config

### ISSUE THREAD

**Issue by orthoceros** [piroor/treestyletab#2136]
Hi, I have a reproducible bug with group tabs in a Firefox (Developer v66.0b2) profile with browser.tabs.remote.autostart=false in about:config (to save RAM): 
After Firefox has started, I still can see the group tabs from my last session with my custom folder names. But once I click on one, not the usual list of its child/ancestor tabs is displayed; just an empty tab like about:blank is shown. The tab title that showed my folder name is replaced by "Group" and the location bar turns empty. 
If I set browser.tabs.remote.autostart=true again, it resumes working after a Firefox restart, but I would like to keep this option disabled on my tablet, as I need to save RAM... Maybe this can be fixed? Thanks.

**Comment by piroor** [comment]
Confirmed. Steps to reproduce:

 1. Start Nightly 66.0a1
 2. Go to about:config
 3. Find "autostart"
 4. Set found e10s configs to "false"
 5. Install TST
 6. Open Google's search result
 7. Pin the search result tab
 8. Middle-click search result links to open them in new tabs
 9. Wait until new tabs are grouped
 10. Open preferences of Firefox to set "restore previous session" on the next startup
 11. Restart Firefox
 12. Click the restored group tab

Expected result: the group tab is restored

Actual result: the group tab becomes blank tab

**Comment by piroor** [comment]
The commit 24d20ba should fix this. I'm still dogfooding...

**Comment by orthoceros** [comment]
I have tested it with your latest nightly treestyletab-we.xpi: While I had seen this problem again for one particular subfolder from my restored session initially (cache?), after further testing with several restarts and clicking on different (sub)folders, folder/group tabs seem to work reliably now with browser.tabs.remote.autostart=false. Thanks! :)
