### ISSUE TITLE
Drag and dropping a link or bookmark to create a new tab always creates a root tab

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#2137]
## Short description
When I drag and drop a link or bookmark between to existing tabs in the Tree Style Tab sidebar a new tab is created but the tab is always created as a root tab even in the middle of existing trees.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open some tabs in a tree
```
A
\- B
  \- C
  \- D
  \- E
```
4. Drag and drop a link or bookmark to create a new tab in the middle of the tree

## Expected result

The new tab should follow the same rules as drag and dropped tabs and be placed where the drop marker is indicating:
```
A
\- B
  \- C
  \- D
  \- F (Opened from drag and dropped link or bookmark)
  \- E
```

## Actual result

The new tab is always created as a root tab:
```
A
\- B
  \- C
  \- D
F (Opened from drag and dropped link or bookmark)
  \- E
```

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 64.0.2
 * Version (or revision) of Tree Style Tab:  2.7.16

**Comment by piroor** [comment]
Thanks, the commit c4617ab should fix this.
