### ISSUE TITLE
Tab selection after reload duplicating tab

### ISSUE THREAD

**Issue by hnougher** [piroor/treestyletab#2140]
Middle-click on reload button (duplicate tab functionality) of pinned tab messes up tab selection.

1. Start Firefox with clean profile.
2. Install TST.
3. Create 5 tabs.
4. Pin 3 of the tabs. All tabs can be selected as normal.
5. Select the first pinned tab and middle click its reload button creating a new (non-pinned) tab.
6. Clicking the new tab will select the 2nd pinned tab. Clicking the 2nd pinned tab selects the 3rd. And onwards until we reach the newly created tab.

Windows 10
Firefox 64.0.2 & 65.0
TST: 2.7.17

**Comment by piroor** [comment]
The commit 92e3c7d fixes this problem on my environment.
