### ISSUE TITLE
Deletes all tabs on crash

### ISSUE THREAD

**Issue by purpleidea** [piroor/treestyletab#2141]
If firefox crashes, when browser re-open this nukes the "restore session" page, thus deleting all your old open tabs!!

**Comment by irvinm** [comment]
I don't think this has anything to do with TST.  TST only shows the tabs managed by the browser.  If the tabs are not loaded after a crash, that is related to Firefox's session management.

**Comment by piroor** [comment]
TST just works after Firefox's sessions are restored by Firefox itself, and doesn't replace the "restore session" page itself. I also think that the previous (restored) session was lost by something other reasons.

**Comment by irvinm** [comment]
@piroor please close this.
