### ISSUE TITLE
[Feature request] Compatibility with Waterfox and older versions of Firefox (before 57)

### ISSUE THREAD

**Issue by vinturei** [piroor/treestyletab#2142]
## Description

Tree Style Tab requires Firefox version 60.0 or above.
Older versions of Firefox are used by many who dislike the big 57 update, including the Waterfox browser (a Firefox fork, based on version 56 I believe).
There is a version of TST compatible with older Firefox, but it is very outdated and difficult to use.

It would be great to have a version of the new Tree Style Tab available for Waterfox or earlier versions of Firefox.

## Steps to reproduce

 1. Install and start Waterfox or a version of Firefox under 57
    > [Waterfox](https://www.waterfoxproject.org/en-US/waterfox/new/)
    > [Firefox directory of older versions](https://ftp.mozilla.org/pub/firefox/releases/) - _note: list is in old-to-new order_
 2. Visit the [Firefox add-ons page and find Tree Style Tab](https://addons.mozilla.org/en-GB/firefox/addon/tree-style-tab/)
 3. A notification warns you that TST is incompatible with your browser.

## Environment

 * Version of Wirefox: 56.2.7

**Comment by piroor** [comment]
It is a FAQ.
https://github.com/piroor/treestyletab/blob/master/README.md#major-faq

**Comment by piroor** [comment]
I close this because outdated.
