### ISSUE TITLE
High memory and CPU usage when closing a browser window with lot of children tabs

### ISSUE THREAD

**Issue by szeder** [piroor/treestyletab#2143]
## Short description

With TST enabled, the ```WebExtensions``` process uses a lot of CPU and memory when closing a window with lots of children tabs: in case of 60 child tabs over 60secs of CPU time and almost 3GB of memory.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Optional: configure Firefox to show blank page in new tabs.
 4. Open a second browser window.
 5. Open a lot of empty child tabs for the current tab in that second window, e.g.:
```
Parent
\- Child 1
\- Child 2
[... other child tabs ...]
\- Child 59
\- Child 60
```
 6. Start some sort of memory and CPU usage monitoring.  On Linux ```top``` will do, if you only want to observe; for very simple logging I used ```while sleep 1 ; do ps axo pid,rss,time,comm= |grep WebExtensions ; done |tee log```.
 7. Close the window with the lot of child tabs, and watch the memory and CPU usage of the ```WebExtension``` process rise.

## Expected result

The window is closed quickly, without any fuss.

## Actual result

The browser struggles and becomes very sluggish.

This is the memory and CPU usage of the ```WebExtensions``` process after I opened 60 child tabs in a second window.
```
  PID   RSS     TIME 
30299 322192 00:00:35 WebExtensions
```
After clicking the 'x' of that window, it disappears immediately, but the ```WebExtensions``` process starts to work hard as it loads a CPU core to 100%, and its memory usage rises considerably.  This is the highest memory usage I recorded, i.e. almost 3GB:
```
30299 2955640 00:01:29 WebExtensions
```
After a while memory usage returns to normal; note that it took over a minute of CPU time:
```
30299 88076 00:01:43 WebExtensions
```
## Environment

 * Platform (OS): Linux Mint
 * Version of Firefox: 65.0
 * Version (or revision) of Tree Style Tab: 2.7.18

## Notes

- I saw this issue with the previous TST version in Firefox 65.0 as well.  I'm not sure about older TST and/or Firefox versions, as I noticed it while fooling around to test the new Firefox's apparently improved memory management.
- It is important to open a second window for this; creating a lot of tabs in the only Firefox window and then closing that window will simply and quickly exit Firefox.
- This issue doesn't arise when closing the tabs but not the window, either by using "Close this tree" from the TST context menu or by collapsing the tree and closing it with the 'x'.
- This issue doesn't arise when closing a window with a lot of top-level tabs without children.

**Comment by piroor** [comment]
Performance profile
[profile.zip](https://github.com/piroor/treestyletab/files/2859100/profile.zip)
![image](https://user-images.githubusercontent.com/70062/52691965-e3d4e380-2fa5-11e9-98a3-4bcfd9b4bd8a.png)

**Comment by piroor** [comment]
After the change b4316f5 this problem looks disappeared on my environment. Could you try the development build?: https://github.com/piroor/treestyletab/blob/master/README.md#development-builds

**Comment by szeder** [comment]
I tried the development build, and can confirm that my issue is gone.
