### ISSUE TITLE
Random tab is selected after closing active tab

### ISSUE THREAD

**Issue by vkovalcik** [piroor/treestyletab#2145]
## Short description
When closing a child tab, it occurs that sometimes a parent is newly selected and sometimes a sibling. 

This started to happen about a week ago. I have browser.tabs.selectOwnerOnClose = false and previously after closing child tab, its sibling was selected... this was great and worked very well for a few years. The behaviour seems to have changed recently.

The issue is similar to https://github.com/piroor/treestyletab/issues/1688 , but I have the recommended selectOwnerOnClose already on false.

## Steps to reproduce

It happens in so many variations, it is almost "random". But I found a reliable way hopefully demonstrates the issue:

 1. Start Firefox with clean profile. (I downloaded Firefox Portable)
 2. Install TST.
 3. Open any site, for example www.google.com/search?q=test
 4. Open two or more child pages by middle clicking
 5. Select the bottom one.

You should have this:

A
\- B
\- C (selected)

6. Now close C. The A becomes selected.
7. Ctrl + Shit + T to un-close the C, which becomes selected, so the same situation as in 5.
8. Now close C again. Surprise, now B becomes selected. (I wished this would be the result always)

## Environment

 * Platform (OS): Windows 64
 * Version of Firefox: 65.0
 * Version (or revision) of Tree Style Tab: 2.7.18

**Comment by piroor** [comment]
Due to a restriction of WebExtensions' new Tab Successor API, TST now simulates Firefox's default behavior with `browser.tabs.selectOwnerOnClose`=`true` by self on Firefox 65 and later. You may need to deactivate TST's corresponding option manually: Options => "Tree Behavior" => "When the current tab is closed as a last child" => "Move focus back to the opener tab if possible, when the current tab is closed". Did you try that?

**Comment by vkovalcik** [comment]
You are right, thanks! This seems to have fixed the issue for me.

The bug itself is probably still valid though - the behaviour with "Move focus back to the opener tab if possible, when the current tab is closed" is still random. But now as the workaround was found, I am happy, thanks again.

**Comment by piroor** [comment]
In this case, the restored tab looks treated just as an orphan tab instead of a tab opened from its "parent". The relation of tabs is easily lost on Firefox's "selectOwnerOnClose" behavior, and TST tries to simulate that for user experience compatibility.

**Comment by vkovalcik** [comment]
I see, thanks for the explanation!
