### ISSUE TITLE
[feature request] Add a css class "last-active" to last actived tab li.

### ISSUE THREAD

**Issue by davidsierradz** [piroor/treestyletab#2146]
## Short description

Hi! would be nice so we can visually track with some CSS the last active tab.

**Comment by davidsierradz** [comment]
I wrote a preliminary extension: [tst-add-last-active-class-to-tab](https://github.com/davidsierradz/tst-add-last-active-class-to-tab), any input is appreciated.

**Comment by piroor** [comment]
I think this is out of topics of the TST project, and the addon extending TST itself is a reasonable solution. I hope the addon is completely released for other people who have same demand.

**Comment by davidsierradz** [comment]
[Published Add-On](https://addons.mozilla.org/en-US/firefox/addon/add-last-active-class-to-tab/)
