### ISSUE TITLE
Minimize, Maximize, and Close buttons disappeared in FF65.0 with userChrome.css styling. Fix included

### ISSUE THREAD

**Issue by Ligerx** [piroor/treestyletab#2147]
## Short description
Yesterday, I noticed that the minimize, maximize, and close button on firefox disappeared.

![capture2](https://user-images.githubusercontent.com/6577974/52390450-3c0f6100-2a4d-11e9-9cae-b320842cea78.PNG)

I've been using the below userChrome.css tweak to hide the tab bar.

https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-horizontal-tabs-at-the-top-of-the-window-1349

#1349 

It seems like Firefox has moved the min/max/close buttons into the `#TabsToolbar` element, so the above CSS was hiding both.

![capture](https://user-images.githubusercontent.com/6577974/52390441-31ed6280-2a4d-11e9-8939-5edd2a860f80.PNG)

## Solution
I tweaked the css selector to fix it, so here's what I'm using now
```css
#main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #TabsToolbar > .toolbar-items {
  opacity: 0;
  pointer-events: none;
}
```

instead of the old
```css
#main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #TabsToolbar {
  opacity: 0;
  pointer-events: none;
}

#main-window:not([tabsintitlebar="true"]) #TabsToolbar {
    visibility: collapse !important;
}
```

## Request
My guess is other people are facing the same issue, so hopefully they can just copy over my fix. Could you update your docs to reflect this?
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-horizontal-tabs-at-the-top-of-the-window-1349

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 65.0
 * Version (or revision) of Tree Style Tab: 2.7.18

**Comment by piroor** [comment]
I'm inactive to update CSS code snippets in the wiki because I don't use them, so I hope that people who using the page maintain it by self. Could you feedback your knowledge?

**Comment by Ligerx** [comment]
I'd be happy to update the snippets page. I will wait a week or two first.

I want to make sure that other people are facing the same issue before updating the docs. So anyone reading, please give a thumbs up or a comment

**Comment by remmah** [comment]
I'm currently having success on macOS 10.14.3 / FIrefox 65.0 using an [older snippet](https://github.com/piroor/treestyletab/issues/1349#issuecomment-343718504):

```
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

#TabsToolbar {
    visibility: collapse !important;
}
```

I think this only works because I have the Title Bar checkbox selected in the Customize Firefox options.

**Comment by bl4ckout31** [comment]
@piroor I had the same problem with the same environment and your fix worked, thanks!

**Comment by BinarySplit** [comment]
I'm on MacOS 10.13.6 and was facing this issue. @Ligerx's fix works for me.

**Comment by Atticus-** [comment]
Works great, thanks so much! Is there a reason to keep the `:not([extradragspace="true"])` part around? Right now it looks like the Drag Space checkbox just toggles tabs' visibility in the title bar.

**Comment by Ligerx** [comment]
@Atticus- I'm also wondering the same thing about the `:not([extradragspace="true"])` part, which is why I wanted to keep this issue open. Hopefully someone who knows can chime in lol

**Comment by Dystopian** [comment]
@Ligerx you shouldn't remove `#main-window:not([tabsintitlebar="true"])` code part. It disables TabsToolbar when `Title Bar` checkbox is selected in the `Customize` settings. And that's what @remmah https://github.com/piroor/treestyletab/issues/2147#issuecomment-461710319 is talking about.

**Comment by Lej77** [comment]
@Atticus- I think that the `:not([extradragspace="true"])` selector was only there to allow showing the tabs in the title bar without having to modify `userChrome.css` and restarting the browser so it should be safe to remove.

**Comment by Ligerx** [comment]
Great, thanks for all the comments. @Lej77 I've kept the `:not([extradragspace="true"])` part and included a little explanation on how enabling drag space will show your tabs again.

The wiki has been updated in [this change](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules/889b55b720c4fef37a8dfbe8f65616541b4c8364), and then I fixed a navigation link I broke in [another change](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules/26b105a3a0d7f50e509561676526efd6e659241b)

**Comment by real-or-random** [comment]
> @Ligerx you shouldn't remove `#main-window:not([tabsintitlebar="true"])` code part. It disables TabsToolbar when `Title Bar` checkbox is selected in the `Customize` settings. And that's what @remmah [#2147 (comment)](https://github.com/piroor/treestyletab/issues/2147#issuecomment-461710319) is talking about.

I had to remove `#main-window:not([tabsintitlebar="true"])` after updating to Firefox 133 on Linux. Otherwise I see a grey bar when the "Title Bar" checkbox in "Customize Toolbar..." is *not* selected. (Asking here if others see the same before editing the wiki.)

**Comment by n1ghthavvk** [comment]
I had the same issue after updating to Firefox 133. My navbar exhibited an unnecessary _margin-top_-like phenomenon. Since I also use custom CSS to move my titlebar buttons (specifically the close button, such that it can be clicked just whishing the mouse into the absolute corner), and also hide the sidebar header for TreeStyleTab, I had to fix the former as well (while the latter continued working without issues).

Thank you for the initial fix of the first issue. Here's my current userChrome.css:
[userChrome.css.txt](https://github.com/user-attachments/files/17966859/userChrome.css.txt)
```/* https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-horizontal-tabs-at-the-top-of-the-window-1349-1672-2147 */
/* Hide tabs at the top of the window */
#main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #TabsToolbar > .toolbar-items {
	opacity: 0;
	pointer-events: none;
}
  
#TabsToolbar {
	visibility: collapse !important;
}

/* Keep titlebar buttons visible and adequately sized */
#toolbar-menubar {
	overflow: visible !important;
}
  
.titlebar-close, .titlebar-restore, .titlebar-min, .titlebar-max {
	height: 40px;
}

/* https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#for-only-tree-style-tab-sidebar-1397 */
/* Hide sidebar header for TreeStyleTab */
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar-header {
	display: none;
}

/* https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#move-minimizerestoreclose-window-buttons-to-the-right-of-hamburger-menu-after-hiding-horizontal-tabs */
/* Adding empty space for buttons */
#nav-bar {
	margin-right: 140px;
}

#titlebar {
	appearance: none !important;
	height: 0;
}

/* Fix for main menu calling by Alt button */
#titlebar > #toolbar-menubar {
	margin-top: 0;
}

/* Move minimize/restore/close buttons to empty space */
#TabsToolbar > .titlebar-buttonbox-container {
	display: block;
	position: absolute;
	top: 0;
	right: 0;
}
```
And here's how it looks now (tabnames and bookmarks blanked for privacy):
![image](https://github.com/user-attachments/assets/690a49e8-1875-47e7-9e19-92623de464f4)

It's back to working perfectly.

**Comment by real-or-random** [comment]
> ```
> /* Hide tabs at the top of the window */
> #main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #TabsToolbar > .toolbar-items {
> 	opacity: 0;
> 	pointer-events: none;
> }
> ```

Is there a specific reason why you changed it to `[tabsintitlebar="true"]` (removing the `not`)? Does it work for you also when removing the condition entirely?

**Comment by Ligerx** [comment]
Today I was upgraded to 135.0 and it broke my userChrome. I had to remove `[tabsintitlebar="true"]` to fix it

**Comment by Bert-Proesmans** [comment]
I think Firefox introduced a bug with version ~145 where the first window of the browser session not always (mostly not) draws a title bar.
The snippet below still works like expected, consistently from the second browser window of the session.

```css
#main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #TabsToolbar > .toolbar-items {
    opacity: 0;
    pointer-events: none;
}

#main-window:not([tabsintitlebar="true"]) #TabsToolbar {
    visibility: collapse !important;
}
```
