### ISSUE TITLE
Closing Tabs In Tree vs Closing Tabs From Window

### ISSUE THREAD

**Issue by DazzleDazzle** [piroor/treestyletab#2148]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
Too less information. Is this posted mistakenly?

**Comment by DazzleDazzle** [comment]
Hello

Not sure what happened to the text

I am trying to do TWO things with settings

+ closing PARENT in tree closes PARENT + CHILDREN
+ closing tab in the browser just closes that tab WITHOUT closing the children

How do I make this happen?

Many thanks

D

**Comment by piroor** [comment]
TST's options => "Tree Behavior" => "When a parent tab is moved or closed by someone from out side of the tree sidebar" => the third option, looks the setting you want.

**Comment by DazzleDazzle** [comment]
Thanks

And, I assume UNCHECK third option?

**Comment by piroor** [comment]
If you choose the tird option, TST won't close collapsed child tabs when the parent tab is closed via Firefox's native tab bar or the keyboard shortcut Ctrl(Command)-W.

**Comment by piroor** [comment]
I close this because outdated.
