### ISSUE TITLE
Make favicons more prominent in unloaded tabs

### ISSUE THREAD

**Issue by nollinvoyd** [piroor/treestyletab#2149]
Many favicons for unloaded tabs are almost imperceptable.  I understand that some users prefer these "faded" features to distinguish unloaded tabs from visited, etc., but that's what I use background colors for.

Regarding the background color, you can see that for some reason, I renadomly get tabs with white backgrounds (tab # 277).  They have too be reloaded to regain color.  

I would also like to know how to get more contrasting colors for unloaded and visited tabs [(tab 274 (visited) ans tab 275 (unloaded)]

 * Platform (OS): WINDOWS 10 PRO
 * Version of Firefox: 66.06b
 * Version (or revision) of Tree Style Tab: 2.7.18

![tree style tabs](https://user-images.githubusercontent.com/20844322/52669650-6d63b300-2ecb-11e9-80ce-b382e8664afd.png)

**Comment by piroor** [comment]
You can give custom appearance to unread and unloaded tabs, with CSS selectors like following:

```css
.tab.unread { ... }
.tab.unread .favicon { ... }
.tab.discarded { ... }
.tab.discarded .favicon { ... }
```
