### ISSUE TITLE
Tab order on drag unpinned tab into pinned tabs

### ISSUE THREAD

**Issue by ypconstante** [piroor/treestyletab#2151]
## Short description
When a unpinned tab is dragged into the pinned tabs, the dragged tab keeps unpinned, but selecting tabs or ctrl+tab doesn't work as expected.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Disable ctrl+tab in use order
 4. Open five sites A, B, C, D, E
 5. Pin sites A and B
 6. Drag site D into between sites A and B

## Expected result
Tabs shown in the order A, B, D, C, E (or maybe in the original order), and navigation using keyboard and mouse working as usual. 

## Actual result
Tabs are shown in the order A, B, D, C, E.
Ctrl+tab goes in the order A, B, C, D, E, which was the previous order, but not in the order shown in the tree.
Clicking on Tab B goes to tab C. clicking on tab C goes to tab D, clicking on tab D goes to tab B.

## Environment

 * Platform (OS): Linux MInt
 * Version of Firefox: 65.0 
 * Version (or revision) of Tree Style Tab: 2.7.18

**Comment by piroor** [comment]
Pinned tab should not be dropped after any unpinned tab, and unpinned tab should not be dropped before any pinned tab. By the commit 08846b0 such invalid drop operation is prevented, thus the problem told on this topic should disappear.

**Comment by ypconstante** [comment]
Thanks, it's working as expected.
