### ISSUE TITLE
Wrong grouping when moving tabs to new window

### ISSUE THREAD

**Issue by ypconstante** [piroor/treestyletab#2152]
## Short description
When a unpinned tab is dragged into the pinned tabs, the dragged tab keeps unpinned, but selecting tabs or ctrl+tab doesn't work as expected.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open for sites A, B, C, D
 4. Make sites B and C children of A
 5. Right click on site A and move it to a new window

## Expected result
Sites A, B and C on a new window, with sites B and C still children of A

## Actual result
Site C is child of site B, and site B is child of site A

## Environment

 * Platform (OS): Linux MInt
 * Version of Firefox: 65.0 
 * Version (or revision) of Tree Style Tab: 2.7.18

**Comment by piroor** [comment]
The commit 3c59083 should fix this.
