### ISSUE TITLE
Opening tab to new window causes remaining tabs clickable area to be off

### ISSUE THREAD

**Issue by kspearrin** [piroor/treestyletab#2153]
## Short description
_I did try searching for this problem, but I didn't find anything. My apologies is this is a duplicate. It is a bit hard to explain and search for._

If you have several tabs open and then open one of them to a new window, clicking on any tabs below where the one that was moved to a new window will not be off by one tab height.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open 5 tabs: A, B, C, D, and E.
 4. Right click Tab C and "Move tab to new window". In the original window, you now have A, B, D, and E remaining.

## Expected result

Tabs should all be directly clickable to select them.

## Actual result

Try clicking on Tab D. Tab E is selected instead. Tab E is not directly clickable. Tab D cannot be selected at all. Tab A and B are still clickable by selecting them directly, no issues with them.

Even though Tab C was removed from the tab list, it seems like its clickable space is still being accounted for.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 65.0.1
 * Version (or revision) of Tree Style Tab: 2.7.18

**Comment by piroor** [comment]
It looks fixed by the commit 853cda38a4d8123f3c88dd7b3e5aa574d221cd34.

**Comment by piroor** [comment]
I close this because outdated.
