### ISSUE TITLE
New tab opened as next sibling causes scrolling of TST panel

### ISSUE THREAD

**Issue by SkySkimmer** [piroor/treestyletab#2157]
## Short description

New tab opened as next sibling causes scrolling of TST panel

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. In TST settings "behavior for new tab actions" "open new blank tab as" set to "the next sibling of the current tab"
 4. open tabs until the TST panel has vertical scrolling
 5. select the first tab, then hit Ctrl+T (or File > new tab in menu bar, etc)
 6. observe the tree scrolling to the end as the new tab is placed there, then scrolling back as it's moved back

Expected: no scrolling, as when using the TST panel "+" button

## Environment

 * Platform (OS): linux (debian)
 * Version of Firefox: 65.0
 * Version (or revision) of Tree Style Tab: verified 2.7.20, 2.7.19; not present in 2.7.18

**Comment by piroor** [comment]
This looks a regression of 6003f9a82efd953efc5df68aabc2951e0f39fcd5.

**Comment by piroor** [comment]
The commit e12ebfa55b6d503246d6fc61a945a5c6794cc6b8 should fix this.

**Comment by SkySkimmer** [comment]
Confirm fix.

**Comment by SkySkimmer** [comment]
This is happening again (2.8.2)

**Comment by piroor** [comment]
I hope the change 5cdd799 fixes this problem fundamentally.

**Comment by SkySkimmer** [comment]
Seems OK
