### ISSUE TITLE
ver2.7.21においてタブのコンテキストメニューが動作しない

### ISSUE THREAD

**Issue by 888kk** [piroor/treestyletab#2160]
## Short description
2.7.21に更新後、
タブを右クリックし、コンテキストメニューから
「タブの再読み込み」「タブを閉じる」等を選択しても動作しなくなりました。

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 適当なURLや新規タブを開く
 4. タブを右クリックしてコンテキストメニューから任意の処理をクリック
5. 処理が行われない

## Expected result
タブのコンテキストメニューから「タブの再読み込み」「タブを閉じる」等を選択すると
その通りにタブが処理される。

## Actual result
タブのコンテキストメニューから「タブの再読み込み」「タブを閉じる」等を選択しても
何も起こらない

## Environment

 * Platform (OS): windows7 ultimate 64bit
 * Version of Firefox: 61.0.2(64bit)
 * Version (or revision) of Tree Style Tab: 2.7.21

**Comment by piroor** [comment]
一括置換でやらかしてました。 143fe35 で直ったと思います！

**Comment by 888kk** [comment]
ご対応ありがとうございます。
