### ISSUE TITLE
[feature request] Provide export/import to allow Firefox reset

### ISSUE THREAD

**Issue by gtimbo** [piroor/treestyletab#2161]
I've recently had an issue on both my home and work computers where Firefox starts getting confused about certain things (doesn't seem to retain login cookies across sessions, timezone seems to be incorrect), and it has turned out that the only way to fix it has been to completely wipe and reinstall Firefox. This was ok on my work computer, as I didn't have that many tabs open, but I've so far resisted doing the reset at home due to not wanting to lose all of my tabs and the tree structure.

I'm happy to use some other session backup/restore tool for the tabs themselves, but would it be possible for TST to provide an export/import of the tree structure? One of the session managers says that it supports TST, but when I tried it on my work computer it didn't correctly restore the tree structure.

Alternatively, if you can provide some other workaround for this issue, that would be just as good.

**Comment by irvinm** [comment]
@gtimbo, this can be done today using the addon "Tab Session Manager".  TSM already supports TST and will store both the tabs and the hierarchy for each session it stores.  (Make sure to enable TST support in the TSM options)  If this is sufficient, can you close this item?

I use TSM and it works really well with TST.

**Comment by gtimbo** [comment]
Tab Session Manager was the addon that I had previously tried on my work computer, which didn't correctly restore the tree. However, for my home computer I did end up using it but configured the "Delay when tree restoration" config parameter to a high value just to ensure that it properly restored the tree. For me, with a lot of tabs, TSM seems somewhat useless for restoring the previous session as it's just not fast enough.

Even though I still think this feature should be implemented rather than relying on some other addon, I'm willing to close it.

**Comment by irvinm** [comment]
@gtimbo if you use the [Use the "discarded" property for lazy loading] option I found that you can leave the "delay" low.  I just tried it just now with a 1016 tab session and I left the delay at the default of 150ms and it restored very quickly and maintained all the trees properly.  (FYI)
