### ISSUE TITLE
New Tab open and closes

### ISSUE THREAD

**Issue by rdewolff** [piroor/treestyletab#2162]
I have found an issue reported to Connex : https://github.com/kesselborn/conex/issues/303

But am not sure who is responsible for the bug. Just posting here to cross link if needed.

**Comment by rdewolff** [comment]
The issue has been updated on conex, and @piroor has commented the following : 

> After testing I've realized why this happens on a case.
https://github.com/kesselborn/conex/blob/master/conex-background.js#L467
Conex tries to open a new tab as a "child" of the original tab, and immediately closes the "parent" tab after the child is opened. On the other hand, TST automatically attaches the new "child" tab to the "parent", but its tree is internally still collapsed. Because the "parent" tab is closed before it becomes expanded, TST closes all children in the collapsed tree.

> I think this problem must be fixed by TST side.

Could any of the dev here have a look at this issue? Would be great!

**Comment by piroor** [comment]
The commit 2233374 should fix this.

**Comment by piroor** [comment]
I close this because outdated.
