### ISSUE TITLE
Allow extension configuraton to be exported

### ISSUE THREAD

**Issue by ypconstante** [piroor/treestyletab#2163]
The only way currently to migrate the extension configuration is to copy the JSON from the `browser-extension-data` in the profile directory, which isn't very practical and [it will not work starting with firefox 66](https://bugzilla.mozilla.org/show_bug.cgi?id=1406181).
It would be helpful to have import and export buttons in the extension config page when migrating the config from one profile/computer to another, or just to make a backup.

**Comment by piroor** [comment]
TST's most configuration items are synchronized via Firefox Sync. Did you try that?

Anyway, I've implemented the feature with the commit https://github.com/piroor/webextensions-lib-options/commit/34ffc832ce6d700689b147827856f8dba6f4f05e. You may see a text field with a caption "Import/Export" below the list of all configs under the "Development" section in the debug mode.
