### ISSUE TITLE
Random blank tabs

### ISSUE THREAD

**Issue by nollinvoyd** [piroor/treestyletab#2167]
## Short description
Numerous random blank tabs in the drop down menu

![tst](https://user-images.githubusercontent.com/20844322/53687294-d038b500-3ce7-11e9-92fb-4773defbe48f.png)

I must left click on the tabs for them to show the title

If I right click on the blank tab and select "Reload Tab", it shows no color

![tat2](https://user-images.githubusercontent.com/20844322/53687341-5a811900-3ce8-11e9-9d31-9332deec4ba4.png)

I must left click to get color
 
![tst5](https://user-images.githubusercontent.com/20844322/53687657-1263f580-3cec-11e9-9f21-977614f06b1b.png)

 * Platform (OS): Windows 10 pro
 * Version of Firefox: 66.0b11
 * Version (or revision) of Tree Style Tab: 2.7.23

**Comment by piroor** [comment]
Could you describe how to reproduce this problem from scratch, with filling the issue template?:https://github.com/piroor/treestyletab/blob/master/ISSUE_TEMPLATE.md

**Comment by nollinvoyd** [comment]
Perhaps the custom .css is the cause?

I made some alterations and will report back.

**Comment by irvinm** [comment]
@nollinvoyd are you still having issues?  If not, can you close this?

**Comment by irvinm** [comment]
@nollinvoyd any updates?

**Comment by nollinvoyd** [comment]
So far so good.  Not seeing blank tabs.
