### ISSUE TITLE
Mute icon on tab broken

### ISSUE THREAD

**Issue by jmarais** [piroor/treestyletab#2168]
## Short description
Muting tab isn't working:
Link to preview:
https://streamable.com/0m2du
(note. when the tab mutes/unmutes I used the right click context menu. Not sure why it is not in the recording)

## Steps to reproduce
( I did test it with your clean profile suggestion:
"C:\Program File\Mozilla Firefox\firefox.exe" -no-remote -profile "%Temp%\FirefoxTemporaryProfile" )
 1. Start Firefox with clean profile.
 2. Install TST.
 3.  open tab with music
 4.  click small speaker icon on tab
 5. tab doesn't mute

## Expected result
Tab should mute and unmute when clicking the small speaker.

## Actual result
Nothing happens

## Environment

 * Platform (OS): Windows 10: Version 10.0.17763 Build 17763
 * Version of Firefox: 65.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.8.0

## Logs from console
I get the following log in the console:
```
tst<BG>: background/handle-misc:     set muted state:  Object { type: "treestyletab:set-subtree-muted", windowId: 76, tabId: 49, muted: undefined } common.js:331:5
tst<BG>: background/handle-misc:     tab 49: playing=true, muted=false common.js:331:5
```

**Comment by piroor** [comment]
Thanks, the commit a97f441 should fix this.
