### ISSUE TITLE
TST 2.8.0: External links create tabs that are not placed in the current tree and destroy tree below new tab after restart

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2169]
## Short description
Clicking on a link in an external application (Ex: Outlook link) creates a tab in Firefox but creates the tab at the root indentation and not as a sibling or child of the current tab.  Tabs below the new tab are removed from the tree on restart as well. [2.7.x and older worked well]

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Create tab.
 4. Create child tab previous step.
 5. Go to external application and click on link.
 6. See that newly created tab is not indented properly.
 7. See that on restart that any tabs below the new tab lose their indenting as well.

**Example 1:**

Create a small tree within Firefox...

![2019-03-05_11-37-21](https://user-images.githubusercontent.com/979729/53821539-fd7da100-3f3b-11e9-854c-93839456582e.png)

Go to Outlook and click on a link and new tab is created at the root. (Pre 2.8.0 would create new tab within the tree and not outside of it)

![2019-03-05_11-37-54](https://user-images.githubusercontent.com/979729/53821574-0cfcea00-3f3c-11e9-98b7-06262ca435d4.png)

**Example 2:**

Start with same initial tree but leave "current tab" in the middle of the tree.

![2019-03-05_11-49-01](https://user-images.githubusercontent.com/979729/53822173-38340900-3f3d-11e9-941f-a60af1594789.png)

Go to Outlook and click on a link to create a new tab and see it is created below the current tab but outside the tree.

![2019-03-05_11-49-29](https://user-images.githubusercontent.com/979729/53822226-50a42380-3f3d-11e9-93bd-34d422d3e472.png)

Restart Firefox and see that any tab below the new tab has now also lost membership in the tree.

![2019-03-05_11-50-51](https://user-images.githubusercontent.com/979729/53822260-63b6f380-3f3d-11e9-8d49-c02e43c531c6.png)

## Environment

 * Platform (OS): Windows 10 (x64) [1809]
 * Version of Firefox: FF 65.0.2
 * Version (or revision) of Tree Style Tab: 2.8.0

**Comment by irvinm** [comment]
... adding this behavior is also seen when doing a search or direct URL in the URL bar [browser.search.openintab = 1] that now creates a new tab with the result outside of the tree.

**Comment by piroor** [comment]
This looks depending Firefox's secret option `browser.tabs.insertAfterCurrent`=`true`, and the commit ac8554f should fix this.

**Comment by irvinm** [comment]
Looks good now.  Thank you.
