### ISSUE TITLE
Ctrl+T doesn't respect new blank tab preference

### ISSUE THREAD

**Issue by SkySkimmer** [piroor/treestyletab#2170]
1. Start Firefox with clean profile.
 2. Install TST.
 3. set preference "open new blank tab as" to "next sibling of the current tab"
 4. Ctrl+T from a tab not at the end of the tree
 5. new tab is created at the end of the tree regardless of the preference

## Environment

 * Platform (OS): debian
 * Version of Firefox: 65.0.1
 * Version (or revision) of Tree Style Tab: 2.8.0

**Comment by piroor** [comment]
Thanks, the commit 0f598b3 should fix this.

**Comment by SkySkimmer** [comment]
Thanks!
