### ISSUE TITLE
2.8.0 regression: tooltip for a long tab label does not show reliably

### ISSUE THREAD

**Issue by Argolics** [piroor/treestyletab#2177]
## Short description
From TST 2.8.0 on (2.8.3 included) i noticed that sometimes tooltips for a long tab labels fail to show or did so unreliably. Possibly has something to do with the new option for long labels - Crop with ".."
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a few tab trees of sites with long titles
 4. Change settings for Too long label of tabs to 'Crop with ".." (Better Performance)'
 5. Restart Firefox (sometimes it stops working immediately)
 6. At least some (but usually all of them) long tab labels don't reliable show tooltips anymore, especially parent tabs

Changing this option to the old value (i.e. Fade Out) usually (temporarily?) fixes this, even when you chose the cropped one again (but it's still somewhat unreliable).

## Expected result
Tabs with long titles (when they are cut off by the sidebar) should always show a tooltip on tab hover.

## Actual result
It's quite unreliable, tooltips may randomly show for some trees/tabs but after every restart it usually stops working even if they did.

## Environment

 * Platform (OS): Linux
 * Version of Firefox: Tried with 65.0.2 & 66.0 b12
 * Version (or revision) of Tree Style Tab: Noticed it with 2.8.0, then it either got worse with 2.8.3 or i finally saw enough instances of this behaviour to recognize it as a bug.

**Comment by piroor** [comment]
Thanks, this should be fixed by a86ef16.

**Comment by Argolics** [comment]
It indeed seems to be fixed by 2.8.4, thanks.
