### ISSUE TITLE
Right clikc Context menu not working (60.5.1esr/ 

### ISSUE THREAD

**Issue by a4z** [piroor/treestyletab#2178]
## Short description
The context menu when clicking on tabs in the tree view does not do anything

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. open some tabs
 4. select one tab, choose open in new window, nothing happens

it could also be close all tabs below, nothing happens

## Expected result

expected, selected, context menu action happens

## Actual result

nothing happens at all

## Environment

 * Platform (OS): Redhat 7.6
 * Version of Firefox: 60.5.1esr
 * Version (or revision) of Tree Style Tab: 2.8.3

Tested on 2 installation with different desktop environments (Gnome and KDE) 

switching back to Version 2.7.23 and disabling automatic update fixes the problem, but this is maybe no an solution

**Comment by a4z** [comment]
same problem on openSUSE leap , Firefox 60.5.1esr (64-bit)

**Comment by piroor** [comment]
Thanks, the commit 018546a should fix this.

**Comment by piroor** [comment]
I close this because outdated.

**Comment by a4z** [comment]
well, you fixed it :-) 
sorry for not reporting this back more explicit than with thumbs up
