### ISSUE TITLE
2.8.0 regression: tab opened externally opens as child of current tab

### ISSUE THREAD

**Issue by DarthGandalf** [piroor/treestyletab#2179]
## Short description
Sometimes new tab is opened as child of current tab instead of in the end, when clicking a link outside of Firefox, which results in running e.g. `firefox http://example.com` while FF is already running, so that the existing process gets a new tab

## Steps to reproduce

I couldn't find a clean way to reproduce this yet. But it matters which tab is selected before opening the new tab. When I select some of my tabs, this triggers, but on other tabs, it does not.

 1. Start Firefox with clean profile.
 2. Install TST.
 3. ...
 4. Click a link outside of firefox. E.g. I'm clicking a github link from thunderbird

## Expected result
The new tab is opened at the end

## Actual result
The new tab is opened at the end, then immediately is moved to be child of the previously selected tab.

## Environment

 * Platform (OS): gentoo
 * Version of Firefox:  65.0
 * Version (or revision) of Tree Style Tab:  2.8.0 and 2.8.3; 2.7.23 works

**Comment by piroor** [comment]
It might be produced by the config: TST's options => New Tabs Behavior => When new tab with a website same to current tab is opened from the location bar (or others)  => Open as => a child of the current tab. Could you check the config?

**Comment by DarthGandalf** [comment]
Yes, looks like that's it, thanks. I didn't change my options though. Apparently, this option was broken in 2.7: I see it being there, but when it's selected as "a child of the current tab", it still opens independently. But I didn't find "fix it" record in changelog

**Comment by piroor** [comment]
Hmm, then I think old versions of TST had a problem about the config (and I missed that).
