### ISSUE TITLE
Clicking a tab opens different tab

### ISSUE THREAD

**Issue by imero** [piroor/treestyletab#2180]
## Short description

When clicking a tab then actually some other seemingly random tab is opened.

## Steps to reproduce

Cannot reproduce with clean profile but problem happens similarily in two different computers both with 1k - 2k tabs. Seems to be related to quickly opening multiple tabs as they still havent finished loading completely. Then clicking some of the recently opened tabs (now completely loaded), some specific tab permanently registers as totally different tab - I mean click to tab can open some tab maybe 700 tabs up that was first created more than a month ago but more often opens some nearer tab.

The wrong tab that is opened by tab click is then consistently same wrong one (the randomness does not change when clicking the misbehaving tab again). Poblem is temporarily fixed when restarting Firefox or disable/enable "Optimize tree restoration with cache".

## Environment

 * Platform (OS): W10
 * Version of Firefox: 65.0.2
 * Version (or revision) of Tree Style Tab: 2.8.3

**Comment by ropeladder** [comment]
I am getting the same or a very similar error, where clicking on a tab highlights the wrong tab. Only have ~25 tabs open.

Two examples:
I have a tree open with this structure:
```
- A
  - 1
    - a
    - b
    - c
    - d
```

Keeping the same structure, this is what I get when I click on them:
```
- A
  - 1
    - d
    - c
    - b
    - a
```
However, if I open two more tabs from the base tab I get the following:
```
- A
  - 2
    - 3
    - 1
    - d
    - c
  - b
  - a
```

Environment:
Linux Mint 19.1
Firefox 65.01
Version (or revision) of Tree Style Tab: 2.8.3

**Comment by piroor** [comment]
I'm trying to solve this mis-synchronizing of tab orders, and I think I need to complete #2139 to "fix" this fundamentally.

**Comment by as3mbus** [comment]
this also happen with me, but with some variation which is conflicting weirdly with simple tab group addon. clicking a tab in a tab group sends me to another tab in another tab group.

**Comment by imero** [comment]
Looks like TST 2.8.7 has fixed the tab click / wrong tab selected problem for me (was present in 2.8.6).

As of similar tab synchronization anomalies I could still generate weird tree structure when opening lots of tabs very quickly, like once every 200ms by Ctrl+clicking a bookmakr toolbar item 25 times. When the pages still loading, clicking some of them - tree with some subset of the 25 tabs appeared that should have been all only in root level. When opening similarily quickly but waiting and not clicking anyting while pages loaded then everything opened correctly into root level.

Second anomaly i noticed after messing around with fast click and tab clicks was that at one moment I noticed ~15 of my old trees had fully edpanded but I had not clicked those trees. Only had collapsed/expanded two other trees (while quickly opened tabs still loading).

Those last two are quite artificial tests that in reality quite seldomly appear, The main issue with wrong tab click was very frustruating and I'm pleased with the outcome and greatly appreciate your effort.

**Comment by as3mbus** [comment]
the problem with simple tab group addon still happen with TST 2.8.7. 
i wonder if i should make another issue or just stick with this one ?

**Comment by piroor** [comment]
Sorry but any verification on TST 2.8.7 is already out of date: I've done a migration of the core architecture of TST, so more testing with the [latest development build](https://github.com/piroor/treestyletab/blob/master/README.md#development-builds) is required.

**Comment by as3mbus** [comment]
still happen in version 3.0.1
i'm going to try with dev build soon as soon as i got some free time

**Comment by irvinm** [comment]
Can anyone on this thread comment if this still occurs with the latest version of TST?  (3.0.11)  

I had seen this in the past, but not recently and wondering if @imero can close out this issue or not.

**Comment by ropeladder** [comment]
I haven't had the problem in a while.

**Comment by FunkMonkey** [comment]
I am still experiencing this in FF 67 with TST 3.0.15...

**Comment by piroor** [comment]
> [edit] maybe I just got weird jumps to other tabs, when closing a tab. I'll investigate

Did you talk about the behavior produced with the [successor tab](https://piro.sakura.ne.jp/latest/blosxom/mozilla/xul/2018-12-03_successor-tabs-api-en.htm#topic2018-12-03_successor-tabs-api-en)? Then TST has some options to control successor tabs like Firefox does. Please see TST's options => Tree Behavior.
