### ISSUE TITLE
Drag and drop detaches siblings

### ISSUE THREAD

**Issue by nocotool** [piroor/treestyletab#2182]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. ...
 4. Drag and drop a Tab with siblings

When dragging and dropping a tab with siblings to another position in the tree, the siblings are not moved (they are detached from the "main tab")

## Expected result
The siblings maintain siblings of the "main tab" and are moved together with the main tab. 

## Actual result
the siblings are not moved (they are detached from the "main tab")

## Environment

 * Platform (OS): Win 10 x64
 * Version of Firefox: 65.0.2
 * Version (or revision) of Tree Style Tab: 2.8.3

**Comment by piroor** [comment]
Sibling tabs of a dragged tab won't be moved together. So, did you talk about descendant tabs? Then, I've tried with a case:

 * A
   * B
     * C
     * D
   * E
   * F

I've dragged the tab B below E, and all descendants of B have been moved as:

 * A
   * E
   * B
     * C
     * D
   * F

Another case, I've tried to drag tabs in the same level:

 * A
   * B
     * C [active, highlighted]
     * D [inactive, highlighted with ctrl-click]
   * E
   * F

I've moved C below E, then all highlighted siblings are moved as:

 * A
   * B
   * E
   * C [active, highlighted]
   * D [inactive, highlighted with ctrl-click]
   * F

Could you describe your case with figures like above?

**Comment by nocotool** [comment]
Thanks for your Answer and sorry for my bad English. Indeed i talked about descendant tabs. 

* A
* A
* A  
* B
  * C
* D

I've moved B below D and then had

* A
* A
* A  
* C
* D
* B

**Comment by piroor** [comment]
Did you choose the TST option?: options => "Drag and Drop" => "When a tree is dragged outside of the tab bar" => "Detach Individual Tab from the window (but impossible to create bookmark)". As a side effect, only the dragged individual tab is moved when you choose the option.

**Comment by nocotool** [comment]
Thank you, that was the solution!

**Comment by piroor** [comment]
I missed the side effect and I think TST should keep "drag and drop whole tree" behavior for dragging in TST's sidebar area.

**Comment by nocotool** [comment]
definitely! And to be honest, I misread the explanation and tought without the option set to "Detach Individual Tab from the window (but impossible to create bookmark)" I wouldn't be able to detach tabs from the window. But with the other option, everything is fine for me!

**Comment by piroor** [comment]
With recent commits, now TST moves the dragged parent tab with descendants except the tab is dropped outside of the sidebar.

> I wouldn't be able to detach tabs from the window. But with the other option, everything is fine for me!

I don't know why, but actually TST (and Firefox) sometimes fails to drop tabs outside of the sidebar area. Such an unstable behavior should be fixed, but currently I have no idea how to fix that...

**Comment by piroor** [comment]
I close this because outdated.
