### ISSUE TITLE
ver2.8.3に更新後、タブを閉じた時の挙動がこれまでと違うものになった。

### ISSUE THREAD

**Issue by 888kk** [piroor/treestyletab#2183]
## Short description
※前提としてツリー型タブの更新の前後で、
タブの挙動に関する設定、about:configの値等は一切変更していません。
ツリー型タブの更新によってタブを閉じた時のフォーカスの挙動が変わりました。

※タブに関する設定：
　　・browser.tabs.selectOwnerOnClose;false　
　　・ツリーの挙動
	　　現在のタブが最後の子タブだった時に、現在のタブを閉じた後は
	　　　●ツリー内の1つ前のタブにフォーカスを移す
	　　　○次のタブにフォーカスを移す

上記の設定のまま
2.7.22から2.8.3へ更新後、
親タブから子タブをいくつか開き、
子タブを閉じた時にフォーカスされるタブの位置がそれまでと違ったものになる。

追記：
親タブから子タブを開いた時の挙動もおかしくなっているようです。
親タブから新しいタブで開くようになっているリンクを叩くと、
まったく関係ないタブの子タブとして開かれてしまいます。

## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install TST.
 3. タブをいくつか開き、その中の適当のタブから子タブを開く。
 4. 現在のタブが最後の子タブの時に、現在のタブを閉じる。
5.一つ下の親タブにフォーカスしてしまう。

## Expected result
現在のタブが最後の子タブの場合、
現在のタブを閉じるとその親タブにフォーカスする。

子タブが複数あった場合は、現在の子タブを閉じると同階層の一つ上の子タブへフォーカスする。
子タブが複数あった場合に子タブの一番下のタブを閉じると同階層の一つ上の子タブへフォーカスする。

## Actual result
現在のタブが最後の子タブの場合、
最後の子タブを閉じると、その親タブではなく一つ下の親タブへフォーカスしてしまう。

子タブが複数あった場合は、現在の子タブを閉じると同階層の一つ下の子タブへフォーカスしてしまう。
子タブが複数あった場合に子タブの一番下のタブを閉じるとその下の親タブへフォーカスしてしまう。

## Environment

 * Platform (OS): windows7 ultimate 64bit
 * Version of Firefox: 61.0.2(64bit)
 * Version (or revision) of Tree Style Tab: 2.8.3

**Comment by piroor** [comment]
Firefox 64より古いバージョン固有の問題でした。 b652028 で直ったと思います。

**Comment by 888kk** [comment]
2.8.4への更新でタブを閉じた時の挙動が元に戻りました。
ご対応ありがとうございます。
