### ISSUE TITLE
Tab selection over-expanding trees and all descendants

### ISSUE THREAD

**Issue by vohzi** [piroor/treestyletab#2184]
## Short description

Tab selection over-expanding trees and all descendants

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Expected result

Upon tab selection : Auto expand the tree and the descendants ONLY IF those descendants were expanded previously.

## Actual result

Now auto expands ALL the descendants recursively upon tab selection (and not just those that were expanded before, like in previous versions) making a huge expanded tree. (looking very messy with big expanded desendants)

## Environment

    Platform (OS): Win 7 x64
    Version of Firefox: 65.0.2
    Version (or revision) of Tree Style Tab: 2.8.3

**Comment by piroor** [comment]
Sadly I couldn't understand what the problem is. Could you describe an exact example steps with details to reproduce the problem?

**Comment by vohzi** [comment]
Alright, I'll try to explain better.
When I used to select a non-expanded tree in the past, it used to auto-expand the first level of the tree only + the descendants that were expanded previously.

Before I had this bug it looked like this : 

https://i.postimg.cc/FKXvhnBv/before-bug.png

Now, it expands every children of the tree automatically, like this :

https://i.postimg.cc/BbkyMjW3/after-bug.png

**Comment by piroor** [comment]
Thank you for detailed explanation. Hmm, then I cannot reproduce the problem on my environment. TST is designed to expand tabs in a tree except descendants under tabs which have "subtree-collapsed" state.

Such a problem may happen when the status of tree is mismatched between actual tabs and tabs restored from cache. Could you try disabling the cache (under TST's options => Advanced) and re-enabling it?

**Comment by vohzi** [comment]
I tried disabling the cache and reenabling it but the problem still occurs. (I also played around with the right-click option "Collapse All" and the settings didn't stay upon restart.
Every tab I click still expands it's descendant fully.

**Comment by piroor** [comment]
Hmm, I've tried with a new profile but I still cannot reproduce the problem. Any other condition to reproduce the problem, for example other addons or configs of TST?

**Comment by vohzi** [comment]
I use quite a bit of add-ons but I don't recall having installed any add-ons in months and the problem started to occur very recently (after a FF update IIRC)
Also, this is now very strange, but now since I cleared the cache, sometimes it works like intended and sometimes it doesn't.
Yesterday it clearly wouldn't work even after a few restarts but today it worked correctly for the first try, 
Then I close FF and suddenly it's not working anymore.

I use quite a bit of customized settings for TST (I don't know if there's a way to list them all quickly)
I also use a custom script (for a very long time) that removes the "vanilla tabs" on the top of the browser, leaving only TST tabs positioned to the left site of the browser. 

I think my tree got corrupted (sometimes I drag & drop tabs to a new window by error, then try to drag & drop it back to the original window which my fail or create missing tabs)

But the weird behavior also showed with a new profile (the only other thing I installed there was Ublock origin), so I don't know what could be causing it. (an FF update or some sort of corruption due to unwanted drag and drops ?)

**Comment by piroor** [comment]
Which is the way you se to restore the session?: "Restore Previous Session" command in the humberger menu or Firefox's options => "General" => "Startup" => "Restore previosu session". Tree restoration for the first way is based on the implementation same to "Undo Close Tab" (Ctrl-Shift-T). You looked a problem on the "Undo Close Tab" command, then "Restore Previous Session" command may be fragile also.

**Comment by piroor** [comment]
I've seen this problem while testing with large number of tabs (over 100). This may happen only on such a situation.

**Comment by piroor** [comment]
I think this problem should be fixed by recent commits.

**Comment by vohzi** [comment]
I use about:preferences -> restore previous session.
I also use a very large amount of tabs (most likely above 300, I don't know if is there an easy way to count them)

**Comment by piroor** [comment]
I think this should be fixed with #2188.

**Comment by vohzi** [comment]
It looks like it is fixed indeed.
Thanks you :+1:
