### ISSUE TITLE
Tree Style Tab can't perform any actions on the Tabs

### ISSUE THREAD

**Issue by SomoneYouKnow** [piroor/treestyletab#2186]
## Short description

Every time I try to mute, pin or close tabs nothing happens.

The debugger is giving me the error "<div class="menu-ui-19133 menu-ui-blocking-screen"></div>" when I try to perform these functions.

This issue started after the recent update of the add-on

## Steps to reproduce

I have not seen a way to reproduce this.

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Uninstalled and reinstalled

## Expected result
Close, mute and pin tab do as expected.

## Actual result
Nothing happens to the tab and stays as is.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox:  60.5.2esr 
 * Version (or revision) of Tree Style Tab: 2.81

**Comment by piroor** [comment]
Is this same to #2178 ?

**Comment by SomoneYouKnow** [comment]
It appears to be the same issue. How do I apply the fix?

**Comment by piroor** [comment]
Please wait for the next release, or you can try a development build: https://github.com/piroor/treestyletab#development-builds

**Comment by SomoneYouKnow** [comment]
The developer build has worked. Thank you so much for the support.
