### ISSUE TITLE
Apply theme color to toolbar button doesn't work in TST 2.8.x

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#2189]
## Short description
The option to `Apply theme color to toolbar button` doesn't work in TST `2.8.0` and later. It still works with earlier versions like `2.7.23`. The toolbar icon becomes entirely transparent when the option is enabled. 

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Enable the `Apply theme color to toolbar button` option.
 4. Open `about:config` and enable the `svg.context-properties.content.enabled` option.

## Expected result
Toolbar icons should be theme colored.

## Actual result
Toolbar icons are transparent.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 65.0.2
 * Version (or revision) of Tree Style Tab: 2.8.6

**Comment by piroor** [comment]
This looks a regression of 3b4ff8cd773a3f0096ee1b0c7d5c99a879909156 and 6dc714c should fix it.
