### ISSUE TITLE
Integrate Bookmark list into TST Tab-Bar

### ISSUE THREAD

**Issue by Femtales** [piroor/treestyletab#2193]
First of all, THANK YOU very much for making this amazing tool.

I was wondering if something like this is possible.
For clarification: "Lesezeichen" is german for "Bookmarks" -> these are my current bookmarks that I would like to have easy access to, without needing to change the Tree.

![Tabbar](https://user-images.githubusercontent.com/48715293/54599133-4bb19a80-4a3a-11e9-9739-85707aa46690.PNG)

**Comment by saipsa** [comment]
Or, easier for dev would be two tabs in the bottom of screen. "tst" and "bookmark"

**Comment by piroor** [comment]
Providing bookmarks feature is out of scope of "Tree" Style Tab addon, so it may not be fixed by me.

On the other hand, I posted a feature request at bugzilla of Firefox: [1328776 - Provide ability to show multiple sidebar contents parallely](https://bugzilla.mozilla.org/show_bug.cgi?id=1328776)

**Comment by irvinm** [comment]
@piroor I think we can close this.  Until Firefox adds this as a feature enhancement, there is nothing you can do.
