### ISSUE TITLE
Strange sidebar since 2.8.7

### ISSUE THREAD

**Issue by Tragen** [piroor/treestyletab#2195]
Since 2.8.7, I get this view in some windows.
I doesn't happen when I start FF, but after some time.

![image](https://user-images.githubusercontent.com/1700241/54722862-fe324c00-4b65-11e9-9833-79c7efc71f1f.png)

**Comment by piroor** [comment]
Is this same to #2197?

Please fill the issue template. Missing information (platform and steps to reproduce) puts the issue off from solving.

**Comment by piroor** [comment]
I close this because outdated.
