### ISSUE TITLE
Have to click tabs several times to select them

### ISSUE THREAD

**Issue by jryans** [piroor/treestyletab#2196]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST version 2.8.7.
 3. Try to switch tabs by clicking on them in TST sidebar

## Expected result

The tab should switch on first click.

## Actual result

The first click seems to focus the TST sidebar but not actually switch the tab. You have to click a second time to actually switch.

The same is true for other actions like closing a tab. I have to click once to focus TST and then again to close.

## Environment

 * Platform (OS): macOS 10.14.3
 * Version of Firefox: 68.0a1 (2019-03-20)
 * Version (or revision) of Tree Style Tab: 2.8.7

**Comment by piroor** [comment]
1536730 - sidebar requires click to receive mouse events
https://bugzilla.mozilla.org/show_bug.cgi?id=1536730
Is this the bug?

**Comment by jryans** [comment]
Yes, that's it! 😁 Just came back here to say I verified it still happens in older TST as well (which I don't remember being true), so it must be some Firefox bug... and it seems you found it. I'll follow that bug, thanks!

**Comment by jryans** [comment]
I reverted back to a previous Firefox Nightly without the regression (introduced by https://bugzilla.mozilla.org/show_bug.cgi?id=1535541) and things are much better in TST now.

**Comment by rozniak** [comment]
FYI this is fixed as of a few hours ago lads :+1:

**Comment by PowerAccess** [comment]
See #2199.
It seems that the underlying cause might be related to other recent as well as long-standing issues, especially since the "Toggling Tab Caching" workaround seems to temporarily fix this (as well as other issues encountered often since v2.8.7, after nearly each extension update and in various other cases in the past).

**Comment by irvinm** [comment]
Is this still an issue or can we close this?  The referenced mozilla defect was marked resolved in FF68.

**Comment by piroor** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1536730 has been fixed on Firefox 68, so I close this.
