### ISSUE TITLE
Tree level change when reopen closed firefox window

### ISSUE THREAD

**Issue by AnatISR** [piroor/treestyletab#2201]
## Short description
Tree level change when reopen closed firefox window

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open new window.
 4. Open tabs as the trees in the example.
 5. Close the window with the example, using the X.
 6. Go to "library sign" - >"history" -> "last closed windows" -> and choose the last window.
 7. I expect it to be the same like the one I just closed, but it is not always.

### Example1:
The closed win - expected:
- A
- B
  - C
    - D
- E
  - F

Actual result:
- A
- B
    - C
        - D
- E
- F

### Example2:
The closed win - expected - also Actual result
- A
- B
    - C
       -  D
- E
    - F
- G

### Example3:
The closed win - expected - also Actual result
- A
- B
    - C
        - D
- E
    - F
- G
    - H

### Example 4
The closed win - expected
- A
    - B
        - C
- D
    - E

Actual result:
- A
- B
- C
- D
- E

## Environment

 * Platform (OS): 
 * Version of Firefox: 65.0.2 Quantum. reproduced also on 66.0.1
 * Version (or revision) of Tree Style Tab: 2.8.7

**Comment by AnatISR** [comment]
Just for recheck, I install **firefox 65.0.1** with clean new profile on special library.
I only add **TST 2.8.7**.
I try to close and restore from history the window again and again.
Please look at example 3. it return to tree after become flat.
there is something wierd there.....
please tell me if you manage to reproduce the problem.

### example1
expected
- A
  - B
     - C
- E
  - F
- G

result
- A
  - B
     - C
- E
  - F
  - G

### example2
expected
- A
  - B
     - C
- E
  - F
  - G

result - Flat

### example3
expected
- A
  - B
     - C
- E
- F

result1 - Flat
result2 - expected
resukt3 - expected
resukt4 - flat
resukt5 - flat
resukt6 - after closing the flat (result5) !!!
- A
  - B
- C
- E
- F
resukt7 - flat
resukt8 - after closing the flat (result7)  !!! - become as result6

**Comment by piroor** [comment]
I think c43fa6f should fix this for me. Before the commit TST did not save hint to restore tree structure for each tab until the tab is intentionally closed, because the information was expected to be used for Ctrl-Shift-T (Undo Close Tab).

**Comment by piroor** [comment]
I close this because outdated.
