### ISSUE TITLE
"bookmark this tree" not working

### ISSUE THREAD

**Issue by jakemkc** [piroor/treestyletab#2202]
## Short description
"bookmark this tree" function used to work: if you select it, it will prompt to have a window and allow you to select bookmark location to save the tree. Now nothing shown up after clicking "bookmark this tree"

It used to work but recent it is not -- I didn't change any settings of tree style tab. It is not working for unknown reason

## Steps to reproduce

 1. Disable TST
 2. Quit firefox
 3. Restart firefox, enable TST
 4. Restart firefox again
 5. Open a tab with sub tabs, then collapse the tree. 
 6. When righting clicking on a collapsed tree, select "tree style tab" ➙ "bookmark this tree..."
 7. Nothing shown up after clicking "bookmark this tree"

<img width="574" alt="Screen Shot" src="https://user-images.githubusercontent.com/18485734/54888537-d251f600-4ed8-11e9-8ed8-d496ad89a80d.png">

## Expected result
A prompt window appears and allow me to select bookmark location

## Actual result
nothing shown after clicking "bookmark this tree"

## Environment

 * Platform (OS):  Mac mojave 10.14.3
 * Version of Firefox:  firefox 66.0.1 
 * Version (or revision) of Tree Style Tab: 2.8.7

**Comment by rtkhklepsch** [comment]
I am having this issue as well.

    Platform (OS): Mac mojave 10.14.3
    Version of Firefox: firefox 65.0.1
    Version (or revision) of Tree Style Tab: 2.8.7

**Comment by piroor** [comment]
Thanks, this is a regression and fixed by 9ab0200.
