### ISSUE TITLE
closeWindowWithLastTab issue in 3.0

### ISSUE THREAD

**Issue by aesthicc** [piroor/treestyletab#2203]
## Short description

Unusual behavior with pref: browser.tabs.closeWindowWithLastTab;false

## Steps to reproduce

set browser.tabs.closeWindowWithLastTab to false
close last tab

## Expected result
show new created tab as usual

## Actual result
ff creates new tab, but tst no longer displays any tabs

## Environment

 * Platform (OS): macOS
 * Version of Firefox: 66.0.2
 * Version (or revision) of Tree Style Tab: 3.0

**Comment by andrisz** [comment]
I'm having the same issue. After closing last tab no tabs are displayed, but if you turn off and then back on the sidebars - the tab is there as expected.

**Comment by piroor** [comment]
Thanks, I missed this. The commit 8491929 should fix it.
