### ISSUE TITLE
Child tab opened in incorrect position with Panorama Tab Groups

### ISSUE THREAD

**Issue by kevinptt0323** [piroor/treestyletab#2204]
## Short description
Child tab opened in incorrect position with [Panorama Tab Groups](https://addons.mozilla.org/en-US/firefox/addon/panorama-tab-groups/) in some cases.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST and Panorama Tab Groups.
 3. Create 1 tab in group 0 and 2 tabs(A, B) in group 1
 4. Open a child tab in A

## Expected result

![Expected result](https://user-images.githubusercontent.com/5292982/55196579-c3c25200-51ea-11e9-8aee-c6fbaada049f.png)

## Actual result

![Actual result](https://user-images.githubusercontent.com/5292982/55196545-adb49180-51ea-11e9-8932-eca44c423045.png)

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 66.0.2
 * Version (or revision) of Tree Style Tab: 3.0
 * Version of Panorama Tab Groups: 0.8.8

**Comment by piroor** [comment]
Thanks! The commit f137b06 should fix this.

**Comment by kevinptt0323** [comment]
Fixed after upgrading to 3.0.3.
