### ISSUE TITLE
Ghost tab after detaching to new window

### ISSUE THREAD

**Issue by pintassilgo** [piroor/treestyletab#2205]
Since 3.0, after detaching a tab to new window the tab isn't removed from "parent" window, but I can't select it either, it's a ghost tab in TST. I need to refresh TST (like opening bookmarks sidebar then back to TST) so that the tab disappears.

DevEd 66, W10, TST 3.0.2 (but I'm experiencing the issue since yesterday with 3.0).

**Comment by piroor** [comment]
Thanks, this should be fixed with recent commits.
