### ISSUE TITLE
Wish: Option to disable drag and drop actions

### ISSUE THREAD

**Issue by f6fvy** [piroor/treestyletab#2206]
I often detach a tree or a tab by accident after clicking and moving my mouse (probably) too quickly. I understand I could use the bookmark feature instead, but I rather would like to totally disable this action, and keeping the Alt-drag and drop for detaching.

Would it be possible to add "Do nothing" options to the drag and drop and Alt-drag and drop actions please ?

Thanks !

**Comment by piroor** [comment]
Did you try the option?: TST Options => "Drag and Drop" => "When a tree is dragged outside of the tab bar" => "Create links or bookmarks from Whole Tree", then TST won't tear dragged tabs off from the window.

**Comment by f6fvy** [comment]
Thanks @piroor . It works well for children tabs, but it's a poor workaround when dealing with a tree root tab (a shortcut tab is created). Anyway, better than nothing. Thanks.

**Comment by piroor** [comment]
Hmm, OK, I've added a new choice "do nothing" to the list of actions with the commit af69c39.

**Comment by f6fvy** [comment]
Thanks @piroor
