### ISSUE TITLE
userChrome.css

### ISSUE THREAD

**Issue by stapuft** [piroor/treestyletab#2207]
my current userchrome.css looks like this
```
/* Replace this SAMPLE CONTENT with your own CSS */

/* Hide horizontal tabs at the top of the window */
#main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #TabsToolbar > .toolbar-items {
  opacity: 0;
  pointer-events: none;
}
#main-window:not([tabsintitlebar="true"]) #TabsToolbar {
    visibility: collapse !important;
}

/* Hide the "Tree Style Tab" header at the top of the sidebar */
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar-header {
  display: none;
}

/* Remove all tabs button. */
#alltabs-button {
display: none;
}
```
i want to be able to have the tabs hidden, but i still want to be able to use the space that the blank tab bar takes up, to hold all of my various buttons and stuff
could someone help me with what i need to do? i think it has something to do with pointer events, but i am not sure.
i found a small workaround using the menu bar as the bar to do this on, but i just personally dont like the looks.
thank you in advance for any help.

**Comment by piroor** [comment]
Firefox's toolbar customize allows you to show the title bar. Did you try that?
![image](https://user-images.githubusercontent.com/70062/55279378-ffc8f480-535b-11e9-8e12-7027a41d51ac.png)
(The bottom-left checkbox is it.)

**Comment by stapuft** [comment]
> 
> 
> Firefox's toolbar customize allows you to show the title bar. Did you try that?
> ![image](https://user-images.githubusercontent.com/70062/55279378-ffc8f480-535b-11e9-8e12-7027a41d51ac.png)
> (The bottom-left checkbox is it.)

yes i did, that option only shows the title bar, it doesnt allow you to place clickable items there.

**Comment by stapuft** [comment]
much better code to do this job. and if you place buttons in the tab bar, before you execute this code, the bar and buttons remain, but the tabs vanish.

```
/* Hide horizontal tabs at the top of the window */
#tabbrowser-tabs {
  visibility: collapse !important;
}
```

**Comment by irvinm** [comment]
@stapuft can you close out this issue or is there more to discuss? PS. I like your result.

**Comment by irvinm** [comment]
@stapuft any updates on if we can close this?

**Comment by irvinm** [comment]
@piroor I think we can close this one.  No updates since March.

**Comment by boardtc** [comment]
> much better code to do this job. and if you place buttons in the tab bar, before you execute this code, the bar and buttons remain, but the tabs vanish, unlike the code i had before that hid everything on that bar even the buttons placed there.
> 
> ```
> /* Hide horizontal tabs at the top of the window */
> #tabbrowser-tabs {
>   visibility: collapse !important;
> }
> ```

This works brilliantly, Should it not be part of the Tree Style Tabs installation to set this or the leats documentation?

**Comment by irvinm** [comment]
It is documented on the wiki already:  https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-horizontal-tabs-at-the-top-of-the-window-1349-1672-2147
