### ISSUE TITLE
Crash after restoring closed tab

### ISSUE THREAD

**Issue by Kebabpizza** [piroor/treestyletab#2208]
## Short description
Sometimes when restoring a recently closed tab, the entire tab panel goes gray.
It is happening with the latest nightly. No other addons are installed.
It doesn't always happen, but this seems to reproduce it 100%.

## Steps to reproduce

 1. Open a new window
 2. Open a new tab, browse somewhere (can't restore about:blank)
 3. Close the new tab (either with ctrl+w or the UI)
 4. Restore the tab without changing to another tab (ctrl+shift+t or the UI)

## Expected result
Restore the tab without crashing

## Actual result
```
TypeError: "container.parentNode is null"
    restoreTabsFromCacheInternal moz-extension://6d28ce66-5b53-4e80-a635-88094f07fdef/sidebar/sidebar-cache.js:280
    restoreTabsFromCache moz-extension://6d28ce66-5b53-4e80-a635-88094f07fdef/sidebar/sidebar-cache.js:215
    <anonymous> moz-extension://6d28ce66-5b53-4e80-a635-88094f07fdef/sidebar/sidebar.js:
```
![2019](https://user-images.githubusercontent.com/5185795/55280821-202c8b00-532b-11e9-8ed2-6cb20ae0db0b.gif)

## Environment

 * Platform (OS):  Windows 10
 * Version of Firefox: 66.0.2
 * Version (or revision) of Tree Style Tab: 3.0.2

&

 * Platform (OS):  Ubuntu 16.04.5
 * Version of Firefox: 65.0
 * Version (or revision) of Tree Style Tab: 3.0.2.8909

**Comment by piroor** [comment]
Thanks, this should be fixed with cdc0354 and some recent commits.
