### ISSUE TITLE
Expanding tree after restart only shows empty area

### ISSUE THREAD

**Issue by CreamyCookie** [piroor/treestyletab#2209]
## Steps to reproduce

1. Close Firefox with trees collapsed.
2. Restart Firefox.
3. Expand tree.

## Expected result
That the tree's children are visible.

## Actual result
They aren't. This is what it looks like:

![Screenshot_20190331_093017](https://user-images.githubusercontent.com/3063858/55286183-2e64c080-5398-11e9-84c2-a9a0c2043239.png)

Collapsing and re-expanding the tree makes them visible again.

## Environment

 * Platform (OS): Ubuntu 18.04
 * Version of Firefox: 66.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.0.2

**Comment by piroor** [comment]
I got similar two reports, and one case was triggered with unchecked "Enable animation effect" option. Did you change the option? Then, the problem looks fixed by the commit dc90c357df25f48a4fc64c86d403a8738bfede15.

**Comment by CreamyCookie** [comment]
Yes, animation effects are disabled. Great to hear!

And obligatory thanks for the add-on! :+1:
