### ISSUE TITLE
Wrong tab selected with pinned tabs and new tab as next sibling

### ISSUE THREAD

**Issue by Ashymad** [piroor/treestyletab#2212]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Select "Open new blank tab as the next sibling of the current tab"
![image](https://user-images.githubusercontent.com/15618637/55366065-70504c80-54e7-11e9-99c3-e818fed3c3ef.png)
 4. Open 2 new tabs and pin them
 5. Select the first pinned tab (the leftmost one)
 6. Open new tab
 7. Select the newly opened tab
## Expected result
The tab you clicked on (the one that is not pinned) is selected
## Actual result
The second pinned tab (the rightmost one) is selected
## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: 67.0b6
 * Version (or revision) of Tree Style Tab: 3.0.4

**Comment by stapuft** [comment]
i have had similar issues occur on my machine, though not in the same way.
but on multiple occasions, i have specificly clicked one tab, and a tab about 10 tabs above the tab i clicked, opens.

this also affects the CTRL+tab shortuct, you will see the tab you want to select for a split second, before it forcibly switches tabs to a different one.

**Comment by piroor** [comment]
@Ashymad Thanks a lot! I looked for the exact condition to reproduce this problem, for a long time. I've added a guard for this case (trying to open any unpinned tab before a pinned tab) with recent commits.

@stapuft If you find out the exact condition to reproduce the situation from scratch, please tell me that, like as the first comment of this issue. The problem looks triggered with some non-default configs or such a limited situation.

**Comment by stapuft** [comment]
okay i will try my best, its an intermittent error on my end, maybe if i ran in debug mode so i could grab the log when the error happens?

**Comment by piroor** [comment]
@stapuft Thanks. Detailed logs may help debugging, but it needs to be collected with suitable steps. If you collect logs *after* the problem has already happened, such logs may not contain helpful information. Instead, I need logs collected from "just before the problem starts" to "just after the problem actually happened". Thus, anyway you looks to need to narrow down the condition to reproduce the problem, before collecting logs, to avoid collecting too much logs like over 1MB. Sorry but too large log won't be analyzable for me.

**Comment by stapuft** [comment]
ok, so here is an idea @piroor , could you add a feature that timestamps the logs? if the logs had a timestamp on them i could just keep track of the time the error happened at, and search through the log (Ctrl+F) to find that time, and then copy the logs from, say, five minutes around the error?

**Comment by Ashymad** [comment]
@piroor thank you so much for fixing this! It works great. :tada:

**Comment by piroor** [comment]
@stapuft  OK, I've added timestamp to logs with the commit 10bf20eff54ec5f73293aeedfecc092cbee84c0a. It will be available with the next release.

**Comment by stapuft** [comment]
WHOAH! you are amazing! thank you for being so dedicated to this project of yours, it really is an amazing product you have created here, i have to say, i LOVE this extension
