### ISSUE TITLE
Tab not selectable

### ISSUE THREAD

**Issue by Tealk** [piroor/treestyletab#2214]
Hi,

I have installed some add-ons to shield my browser a bit. Among them [Temporary Containers](https://addons.mozilla.org/de/firefox/addon/temporary-containers) and [Firefox Multi-Account Containers](https://addons.mozilla.org/de/firefox/addon/multi-account-containers/).
I think it has to do with the first one because when I open a new tab it is always opened in a temporary container(the red one). In some cases I have the problem as shown in the gif.
![2019-04-03_11-04-12](https://user-images.githubusercontent.com/12276250/55467113-e399b180-5600-11e9-95c3-fe6a785dc0bb.gif)

**OS** Win10 1809 (17763.379)
**Firefox** 67.0b6
**TST** 3.0.5
**Temporary Containers** 0.94

**Comment by piroor** [comment]
Could you narrow down the conditions and clarify steps to reproduce [with a clean profile](https://github.com/piroor/treestyletab/wiki/How-to-run-Firefox-with-a-clean-profile), as described at the [issue template](https://raw.githubusercontent.com/piroor/treestyletab/master/ISSUE_TEMPLATE.md)?

**Comment by Tealk** [comment]
Thanks for the quick answer.
I will try to repoduce it in a clean profile. At the moment it seems to be totally random. I can open the same page 10 times and at some point this phenomenon occurs.

**Comment by piroor** [comment]
Thanks, I'm waiting for further comments.

This problem is quite similar to #2212. Such a "wrong focus" problem happens on various situations, and this is the largest reason why I reconstructed TST as 3.0 (#2139). This reconstruction aimed to reduce happening of problems like this, but still there. All cases have same status (invalid index of tabs) but they looks to be produced with different triggers. The case #2212 is quite rare case that complete steps to reproduce became clear.

**Comment by Tealk** [comment]
What I've noticed so far is it occurs whenever redirects occur.

When I open the tab it is a tracking URL this is in the container tmp1 then it goes to the web page this opens then in the container tmp2

**Comment by ciil** [comment]
I do sometimes have the same problem. However, I don't have Temporary Containers installed, but Containerise (and of course Firefox Multi-Account Containers). A colleague reports also using Temporary Containers and also stumbling over this problem. It's proven very hard to directly reproduce so far, but might've something to do with switching container contexts rapidly. If I find out more, I'll report back.

**Comment by piroor** [comment]
@Tealk On recent versions I've introduced some improvements about tracking of tab indexes. Could you confirm that the problem you saw is still there or not?

 @ciil This type problem may happen after very quick operations around tabs: for example reopening of a tab immediately after it is opened and closing the original. Container type addons sometimes do that to enforce specific containers by conditions. Another example case is moving a tab immediately just after it is opened. I hope these information help you to successfully find out the exact condition to reproduce the problem.

**Comment by Tealk** [comment]
Hallo @piroor and thanks for your work so far, I haven't had the problem anymore.

**Comment by irvinm** [comment]
@Tealk if this is resolved, can you close this item?  Thanks.

**Comment by ciil** [comment]
I've tried to reproduce with 3.0.11 and couldn't, even with very quick operations around creation, deletion and reopening of tabs in different containers. Seems fixed to me.

**Comment by irvinm** [comment]
> 
> 
> I've tried to reproduce with 3.0.11 and couldn't, even with very quick operations around creation, deletion and reopening of tabs in different containers. Seems fixed to me.

Great!  Please close this item then @ciil . :)
