### ISSUE TITLE
userChrome.css (autohide+hover) = can't drag and drop

### ISSUE THREAD

**Issue by 2mg** [piroor/treestyletab#2215]
As an old user of hovering and auto-showing/hiding sidebar, using the new userChrome.css doesn't allow the drag & drop of Tabs to TST sidebar because the sidebar won't pop-up when I move the cursor to the edge of the window while dragging a Tab.

Is this expected behavior with userChrome.css (and new webextensions)?

**Comment by piroor** [comment]
It looks a bug or designed behavior of Firefox itself. I've found a bug tracked on Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=122746 but it just says about dragging with no drag session (like text selection). When the drag session is invoked (like dragging of a link), both Firefox and Chromium don't activate `:hover` pseudo class for dragging over elements.

An old selector level 4 draft had a feature called `:drop()` pseudo class:

Drag-and-Drop | Level 4 Selectors : CSS4 Rocks
http://css4.rocks/drag-and-drop-pseudo-class.php

But it was already removed from the latest draft:

Selectors Level 4
https://www.w3.org/TR/selectors-4/#changes-2018-02
[selectors-4] drag and drop · Issue #2257 · w3c/csswg-drafts
https://github.com/w3c/csswg-drafts/issues/2257

Anyway, this request beyonds means of an just a Firefox addon. Such a request need to be discussed on tables of CSS spec and browser development. This is an issue tracker of the project TST, thus this issue looks not suitable to be tracked here.

**Comment by 2mg** [comment]
So working as intended, thank you.
