### ISSUE TITLE
Tabs not selectable when reopening NOT the most recently closed tab

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#2216]
## Short description
Similar to #2212 (huge thanks!) and #2214, here is another scenario where a tab becomes unselectable after reopening a tab that is not most recently closed.
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST 3.0.5 or 3.0.5.8960.
 3. Prepare 3 tabs that are not about:newtab. (some quick links to click: https://www.example.com, https://www.google.com, https://www.wikipedia.org/)
```
Tab1
Tab2
Tab3
```
5. Close Tab3 then Tab2, leaving
```
Tab1
```
6. Open _History_ > _Recently Closed Tabs_, either from menu bar or the `library` button on the toolbar.
7. Click on _Tab3_ (**second entry from the closed tabs list**)
8. Switch to _Tab1_.
9. Try to switch back to _Tab3_.

## Expected result
_Tab3_ should now be the active tab.

## Actual result
_Tab3_ is not selectable. _Tab1_ is still in focus.
When the bugged tab is clicked, Browser Console shows: `Error: No tab at index: 6` (or any number).

## Notes
It affects any closed tabs except the most recently closed one (either by Ctrl-Shift-T or from the closed tab list).
It affects extensions that provides undo closed tabs features, e.g. [Undo Closed Tabs Button (revived)](https://addons.mozilla.org/firefox/addon/undo-closed-tabs-revived/).

## Environment

 * Platform (OS): Win10 64bit
 * Version of Firefox: Nightly 2019-04-03 (20190403060632)
 * Version (or revision) of Tree Style Tab: 3.0.5 or 3.0.5.8960

**Comment by piroor** [comment]
Thanks a lot! Confirmed and looks to be fixed with the commit 5bff9e5.

**Comment by piroor** [comment]
This issue is triggered with WebExtensions API's odd behavior, so I've reported it to bugzilla.mozilla.org: [1541748 - New tab and restored tab notified via tabs.onCreated can have invalid (too large) index](https://bugzilla.mozilla.org/show_bug.cgi?id=1541748)

**Comment by Fanolian** [comment]
Confirmed fixed in 3.0.5.8963. I will close the issue when it's released.

**Comment by Fanolian** [comment]
Coincidentally, the bug is fixed in Nightly, even without commit 5bff9e5 (using TST 3.0.5), probably by [Bug 1504775 - Index is wrong for restored tabs](https://bugzilla.mozilla.org/show_bug.cgi?id=1504775).

**Comment by Fanolian** [comment]
The issue is fixed in 3.0.6 for Firefox 66.0.3, i.e. even without the fix from bug 1504775. Thank you.
