### ISSUE TITLE
Don't want "Group" tab when opening multiples

### ISSUE THREAD

**Issue by jimmydw666** [piroor/treestyletab#2217]
When I want to open all the tabs in a bookmark folder a "group" tab is made before the others.

It's the name of the first tab on my list and says "Close this tab when there are no more children."

What setting do I need to change to stop this annoying tab from being made.

**Comment by stapuft** [comment]
you can change its name by clicking on the text containing its name, those tabs are pretty useful for organization.
you could always try disabling the "auto-grouping of tabs" feature?

**Comment by jimmydw666** [comment]
@stapuft thanks for the response. i've spent hours and hours teaching myself how to do little adjustments with the settings but i couldn't get this one
THANKS AGAIN!

**Comment by stapuft** [comment]
@jimmydw666 no worries man ive been doing the same thing, trying to get it working and looking exactly the way i want it to.

i stream alot of tv shows so i love those group tabs, they let me keep the different genres of shows grouped together, and they are all grouped under another one just called videos, so that if i need to do real work i can compress that whole group and use the space for more productive things.

**Comment by piroor** [comment]
Actually there is a checkbox to deactivate the feature, but for more discoverability there should be something message to redirect people from group tabs to the options page.

**Comment by piroor** [comment]
I've implemented a hint to redirect people to the options page.
![image](https://user-images.githubusercontent.com/70062/55671754-44114300-58ce-11e9-8160-ca73880b270a.png)

**Comment by Ryonez** [comment]
Thank god, this was getting frustrating.

Used with Tab Session Manager, this was causing a absolute mess when loading in my sessions.

I'm going to suggest that this be off by default. It doesn't really make any sense why it's on, I'd imagine those opening groups of tabs would probably use a session manager pretty quickly.

**Comment by piroor** [comment]
> I'm going to suggest that this be off by default. It doesn't really make any sense why it's on, I'd imagine those opening groups of tabs would probably use a session manager pretty quickly.

Because I'm using "open in tabs" command on bookmark folders.

**Comment by piroor** [comment]
I hope to set the feature activated by default only for tabs from bookmarks, but sadly WebExtensions based addons cannot detect sources of new tabs: bookmarks or links...

**Comment by piroor** [comment]
I've added a confirmation before grouping.

**Comment by Ryonez** [comment]
> 
> 
> > I'm going to suggest that this be off by default. It doesn't really make any sense why it's on, I'd imagine those opening groups of tabs would probably use a session manager pretty quickly.
> 
> Because I'm using "open in tabs" command on bookmark folders.

Fair enough. I'd still probably recommend it'd be off by default, as it does change the user's experience from something they might expect. Most of my frustration was that I had no idea what was causing these random tabs to appear when I hadn't told anything to add them. If I wasn't able to resolve it while looking for solutions this time I was going to disable the extension as I was spending 5-10 minutes each time I started the browser cleaning it up. Making me start to avoid starting/restarting the browser. So a negative experience for me.

It's a good idea, just not something that belongs as on by default imo.

**Comment by Ryonez** [comment]
> 
> 
> > I'm going to suggest that this be off by default. It doesn't really make any sense why it's on, I'd imagine those opening groups of tabs would probably use a session manager pretty quickly.
> 
> Because I'm using "open in tabs" command on bookmark folders.

Fair enough. I'd still probably recommend it'd be off by default, as it does change the user's experience from something they might expect. Most of my frustration was that I had no idea what was causing these random tabs to appear when I hadn't told anything to add them. If I wasn't able to resolve it while looking for solutions this time I was going to disable the extension as I was spending 5-10 minutes each time I started the browser cleaning it up. Making me start to avoid starting/restarting the browser. So a negative experience for me.

It's a good idea, just not something that belongs as on by default imo.

**Comment by irvinm** [comment]
@jimmydw666 is there anything more to discuss on this topic?  If no, can you close this item?

**Comment by irvinm** [comment]
@jimmydw666 any updates?  Can we close this?

**Comment by versipellis** [comment]
@piroor I'm curious, is the existence of that group tab necessary to do any sort of groupings with TST? I still use the default horizontal tab bar that comes with FF, but the presence of multiple of those group tabs which take up a whole bunch of horizontal tab bar real estate is quite annoying :| I'd love if those group tabs only appear in the TST hierarchy, but my gut tells me that that isn't possible.

**Comment by piroor** [comment]
@versipellis The feature was originally introduced to organize tabs as a set when they are opened from a bookmark folder. As I commented at https://github.com/piroor/treestyletab/issues/2217#issuecomment-482020712 sadly there is no way to detect a tab is opened from a bookmark or other sources.

There are some ideas to show such "group tabs" only on the sidebar, but I gave up to do that because such hacks will introduce serious compatibility issue around other tab related addons. TST currently gives higher priority for stability and compatibility with other addons, than maximizing usability of TST itself with breaking others.

**Comment by piroor** [comment]
@versipellis And, as a workaround, you can hide those tabs in the horizontal tab bar with `userChrome.css` like:

```css
.tabbrowser-tab:not([image])[label$=" and more"] {
  visibility: collapse !important;
}
```

If the rule is unexpectedly applied for non-group tabs too frequently, you'll need to change title of group tabs with some prefix or suffix like "@hide" and update the selector of the rule like `.tabbrowser-tab:not([image])[label$="@hide"]`.

**Comment by irvinm** [comment]
@piroor I think this can be closed and mark "expired".
