### ISSUE TITLE
[feature request]: Tab search

### ISSUE THREAD

**Issue by stapuft** [piroor/treestyletab#2219]
a way to search between open tabs would be very useful, not necessarily search through the contents of the tabs, although that would be cool, but just searching through the titles and urls of your currently opened tabs, would be amazingly useful. as the awesome bar currently is you have to disable the ability to search through history, bookmarks, and the internet at large to be able to search for tabs easily and effectively. if there was a way to add a search function to TST it would be amazing.

**Comment by perdolka** [comment]
https://addons.mozilla.org/firefox/addon/tabhunter/

**Comment by stapuft** [comment]
wow thats cool! it seems to work really well, and it even searches the text in the tabs aswell, holy shit thats cool. thanks man!

**Comment by irvinm** [comment]
You don't really even need an add-on to do this.  Just do the search in the URL bar and prefix the search with "%".  This will only search your existing tabs and when you click on the result, it just takes you to that tab.

Ex:  "% github" would show you all your open github tabs.

**Comment by piroor** [comment]
As @irvinm mentioned, Firefox itself has a prefixed search feature for this purpose. So I think it may be a workaround for requests like this.

On the other hand, current TST has no availability to add such a feature inside its sidebar. This is one of receding points from legacy versions of TST and Firefox. I decided to keep TST concentrated to "tree" features, so I won't add such a feature natively. Instead I'm positive to add APIs required to add extendability, so I need well-designed API plan.

**Comment by stapuft** [comment]
> 
> 
> You don't really even need an add-on to do this. Just do the search in the URL bar and prefix the search with "%". This will only search your existing tabs and when you click on the result, it just takes you to that tab.
> 
> Ex: "% github" would show you all your open github tabs.

i have tried that from time to time but the order is all messed up and i have to type way more than i should to get it to find the tabs i want. while that feature does indeed work, it is kind of annoying in how it works (i have almost a hundred tabs open at the moment)

**Comment by irvinm** [comment]
@piroor given there is a workaround (albeit not perfect) ... if you do not want to add this functionality, we should close out this issue.

**Comment by piroor** [comment]
@stapuft The order of items in the location bar are calculated with their ["frecency"](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Places/Frecency_algorithm) and more other metadata.

I've tried [Tabs2List](https://addons.mozilla.org/firefox/addon/tabs-2-list/) and it provides a toolbar button to show the list of tabs with a search field. They are not indented but I think it should help you.

**Comment by piroor** [comment]
There are more other addons providing searchable tab list:

* [Tab Manager v2](https://addons.mozilla.org/firefox/addon/tab-manager-v2)
* [TabSearch](https://addons.mozilla.org/firefox/addon/tab_search/)
* [Tabby - Window & Tab Manager](https://addons.mozilla.org/firefox/addon/tabby-window-tab-manager/)
* [Tab Master 5000](https://addons.mozilla.org/firefox/addon/tab-master-5000/)
* [Power Tabs](https://addons.mozilla.org/firefox/addon/power-tabs/)

**Comment by piroor** [comment]
I've added a new section to the README: https://github.com/piroor/treestyletab/blob/master/README.md#listing-tabs-with-a-search-field If you know more helpful addons, please send a pull request me to add them.
