### ISSUE TITLE
scrollbar

### ISSUE THREAD

**Issue by stapuft** [piroor/treestyletab#2222]
since the 3.x releases my scrollbar has not disappeared even when set to auto hide.i don't know if this is a result of my css tinkering or more changes (like tab.burster being depreciated)

my TST Css
https://pastebin.com/DcT7BbZX

my userchrome.css
https://pastebin.com/rixEtWKB

**Comment by stapuft** [comment]
i just have found this post and code on a really old thread talking about a mac exclusive problem for an older version of TST,

> I use just:  #tabbar.overflow { margin-left: -17px; }
> 
> However I am seeing the same thing as you if the width of the sidebar is too narrow.  Without this CSS, the right-click menu display logic works properly even with a narrow sidebar.
> 
> _Originally posted by @irvinm in https://github.com/piroor/treestyletab/issues/1507#issuecomment-341899266_

and modified it to this
```
#tabbar.overflow { margin-right: -15px; }
#tabbar.overflow { margin-left: -8px; }
```
and while it works, and does more, (in that it also shrinks the indent on the other side of the tabs), i feel that the feature being broken in the first place is bad.

**Comment by piroor** [comment]
The scrollbar in the sidebar is now controlled with the [`scrollbar-width` property](https://developer.mozilla.org/ja/docs/Web/CSS/scrollbar-width). Code snippets about the scrollbar is already updated: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#auto-hide-scrollbar-1923 Did you try that?

**Comment by stapuft** [comment]
somehow.....this
```
/* please update sizes for your environment. */
:root {
  --scrollbar-size: 18px;
}
:root.narrow-scrollbar {
  --scrollbar-size: 18px;
}

:root.left-scrollbar #tabbar.overflow {
  margin-left: calc(0px - var(--scrollbar-size));
  transition: margin-left ease 0.25s 0.4s;
}
:root.right-scrollbar #tabbar.overflow {
  margin-right: calc(0px - var(--scrollbar-size));
  transition: margin-right ease 0.25s 0.4s;
}
```

which to me would make the scrollbar larger, actually made it disappear, even though the option in appearance is broken this did indeed work as that option used to work (make the scroll bar disappear and stay hidden permanently)

**Comment by irvinm** [comment]
@stapuft I grabbed the 3.0.5+ code snippet and it worked for me on Windows, FF 66.0.4, and TST 3.0.11.  (The scrollbar is hidden until my mouse hoovers over the tabs)  Can you try it with without any other TST or userchrome CSS just to test?

Here is the CSS I used:

```
/* please update sizes for your environment. */
:root {
  --scrollbar-size: 16px;
}
:root.narrow-scrollbar {
  --scrollbar-size: 8px;
}

:root.left-scrollbar #tabbar.overflow {
  margin-left: calc(0px - var(--scrollbar-size));
  transition: margin-left ease 0.25s 0.4s;
}
:root.right-scrollbar #tabbar.overflow {
  margin-right: calc(0px - var(--scrollbar-size));
  transition: margin-right ease 0.25s 0.4s;
}

:root.left-scrollbar #tabbar.overflow:hover {
  margin-left: 0;
}
:root.right-scrollbar #tabbar.overflow:hover {
  margin-right: 0;
}
```

**Comment by irvinm** [comment]
@piroor I think this could probably be closed.

**Comment by piroor** [comment]
Looks no progress or regression, so I close this for now.
