### ISSUE TITLE
TreeStyleTabs incompatibility with SnapLinks

### ISSUE THREAD

**Issue by GhostyGamesDotCom** [piroor/treestyletab#2223]
Hello,

Since last update there is some compatibility issue with SnapLinks and TreeStyleTabs. When I open multiple tabs, if I try to navigate them with the TreeStyleTabs it would snap to another tab than the one selected. I installed another Tree Tabs plugin for now but please update yours because the new one is not even half as nice as yours. Thank you.

Kind regards.

**Comment by GhostyGamesDotCom** [comment]
Disabling SnapLinks after the tabs were opened and a Firefox reboot fixes the issue but it's not a solution... Thank you.

**Comment by GhostyGamesDotCom** [comment]
Also using v2.8.7 is an alternative because that version does not have this issue.

**Comment by piroor** [comment]
Thanks! I think this should be fixed with the commit 568f775.

**Comment by GhostyGamesDotCom** [comment]
Thank you Piroor!

**Comment by piroor** [comment]
I close this because outdated.
