### ISSUE TITLE
Way to Disable "Close Other Tabs" and "Close Tabs to Bottom"

### ISSUE THREAD

**Issue by LD143** [piroor/treestyletab#2225]
I'll make this short - no need for the template on this one.

Hello there!

I've mis-clicked the "Undo close tab" too many times and I'm about to remove this entire add-on. Is there no way to remove the "Close xxx" options on the right-click popup menu on the vertical tabs? Because the tabs are closing (and not force exiting), the tabs aren't being saved upon relaunch of the browser (if I hit "close other tabs", all the tabs close one at a time then closes the browser).  I'm pretty sure there used to be a way to disable this (and some other right-click options) from the config but I'm not seeing them anymore (and haven't seen them in a while). 

Am I missing something or is there no way to remove certain options from that menu system? There aren't any extension add-ons that I can find anywhere (linked from here) and the only other support options aren't for this specific issue.

Please don't tell me I'm kinda screwed here. :(

**Comment by piroor** [comment]
You can hide them with the [userChrome.css](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Tutorial/Modifying_the_Default_Skin#Customize_with_userChrome.css), like:

```css
*|*[label="Close Other Tabs"],
*|*[label="Close Tabs to the Bottom"] {
  display: none;
}
```

See also #2116.

**Comment by LD143** [comment]
Yes!  Thank you so much, Piroor!  it took me some time to figure out the userChrome.css part - but I got there after a few websites. Thank you again so much for your help with this and, again, thank you for a great add-on!
