### ISSUE TITLE
Shift-Click does not select multiple tabs

### ISSUE THREAD

**Issue by aphirst** [piroor/treestyletab#2226]
## Short description
Shift-Click is supposed to let me select many tabs at once, instead of laboriously having to select them individually with CTRL+Click. However, it doesn't, it just selects the new tab like a normal click. Problem persists in a fresh profile.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open multiple tabs (either at the root of the tree, or as children of another tab)
 4. Click one tab
 5. Shift-Click on another

## Expected result
Multiple tabs get selected (between the initial click and the shift-click).

## Actual result
Currently selected tab changes, as if it were just a normal click.

## Environment

 * Platform (OS): Arch Linux x86_64
 * Version of Firefox: 66.0.3 
 * Version (or revision) of Tree Style Tab: 3.0.5

**Comment by piroor** [comment]
Thanks, the commit 4508add should fix this issue.

**Comment by aphirst** [comment]
どもありがとうございます！待ち望みます!

**Comment by piroor** [comment]
I close this because outdated.
