### ISSUE TITLE
Color previews for some color samples in extra style rules do not display correctly

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#2227]
## Short description
Some color previews introduced in commit e3e2a3247e757d448ed8ad2fd945496d5dfee9f8 appear in-between, instead of after, color codes.

## Steps to reproduce

 1. Use **_Nightly_ after 2019-03-31** build. The sample section does not show before it. [1]
 2. Install TST 3.0.6.
 3. Open _Nightly_'s `Customize` in hamburger menu.
 4. Change theme to `Dark`.
 5. Open TST's options.
 6. Expand `Advanced`. Check the section _Extra style rules for sidebar contents_.

[1]: "Regression" range is https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=9d74f5279e4f223d07fdfddbbe2340f39c6f7a53&tochange=58dd38390b0664680e5ad0307faec3923abf560d. Is it a bug or intended (that this section does not show in previous builds)?

## Expected result
All color previews show after color codes. For example, when `light theme` is selected:
![TST_lighttheme](https://user-images.githubusercontent.com/771216/56035956-2163ac00-5d5e-11e9-820d-173ec58cd4b7.png)
(`--theme-colors-frame` is missing the preview.)

## Actual result
Some previews show in-between the codes: (`dark theme` is selected)
![TST_darktheme](https://user-images.githubusercontent.com/771216/56035990-393b3000-5d5e-11e9-9d33-ef89943af354.png)

Copying an affected code adds a `\u200b` at where the preview is.

## Environment

 * Platform (OS): Win10 64bit
 * Version of Firefox: Nightly 2019-04-11 (20190411161115) 
 * Version (or revision) of Tree Style Tab: 3.0.6

**Comment by piroor** [comment]
Thanks! c0476ad should fix this.

**Comment by Fanolian** [comment]
Thanks for the quick fix.
