### ISSUE TITLE
so many bugs!

### ISSUE THREAD

**Issue by stapuft** [piroor/treestyletab#2228]
EVERY time i quit firefox, lately TST decides to hang or something, and it causes firefox to crash, upon opening, all of my tabs are out of order.
it takes way too long to reorganize them, as trying to use shift click or ctrl click to select multiple entries, take multiple attempts to actually work. and even then, tabs will attach themselves to each other for no reason, and some have even dissapeared entirely. the triangles that are supposed to expand the trees contents, just switch my to that tab, and than open the trees contents, instead of just opening the trees contents like it used to. but the worst part is how slow it acts i have to do almost everything multiple times to actually make it work.

**Comment by piroor** [comment]
Please fill the issue template. This is not a forum, but an issue tracker - a tool to track bugs and fix them.

**Comment by azizLIGHT** [comment]
@stapuft While I understand your frustration, its not exactly the right place for it. We're looking for actionable information. Something we can test, repeat, and fix. For that to happen, we need things like version information for Firefox, TST, etc, among other things described in the issue template. Only then can we help
