### ISSUE TITLE
back button middle click opens an unindented child tab

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#2231]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a page with links
 4. Open a link
 5. back button middle click
 6. a sibling tab opens, but the original tab behaves as if the sibling is its child
     ![image](https://user-images.githubusercontent.com/895588/56074461-3140b780-5d81-11e9-8eac-a6e91c8cfcdb.png)

## Expected result

the new tab should be either a sibling or a child, a pref may be needed to specify which

## Environment

 * Platform (OS): win7 sp1 x64
 * Version of Firefox: 66.0.3 x64
 * Version (or revision) of Tree Style Tab: 3.0.6

**Comment by piroor** [comment]
Thanks, 79038fe should fix this.

**Comment by piroor** [comment]
I close this because outdated.
