### ISSUE TITLE
New tab opens at very bottom of tree + can't be selected

### ISSUE THREAD

**Issue by Coldblackice** [piroor/treestyletab#2232]
This happens so randomly, I don't know how I could catch it even with a clean profile. When spawning a new tab, the tab doesn't appear in the current sub-tree, but instead all the way at the very bottom of the entire tab tree. Additionally, this tab cannot be clicked or chosen in any way, even by selecting a nearby tab and trying to ctrl-tab to it.

Further, as soon as this happens, "Session Manager" is no longer able to save a session: the save button is grayed out. Firefox's automatic backup sessions also stop getting generated, even if I continue browsing with the remaining tabs above (I'm also able to continue creating new tabs just fine). However, if I open a new browser window, "Session Manager" is able to save _just_ that window's session.

Other browser/addon functions also stop working when this happens, such as "Copy URIs of selected tabs". Nothing happens even when clicking it. It's as if something in the browser/tab backend breaks.

I only mention "Session Manager" because I think it stems from the same issue -- it's as if some backend browser engine gets stuck/stopped/broke, and can't be fixed while that browser window exists. If I don't want to lose all my tabs from that window, the only thing I can do is drag all of the tabs from that window into a new window. The only tab that remains (and can't be dragged or clicked) is that "dwarf" tab. As soon as I close that window, Session Manager is suddenly able to save a multi-window session again, and other browser functions and addons work, like "Copy URIs of selected tabs".

I know I need a better technical report here and I'm keen to do so, but I'm wondering if there are any suggestions on where I can check within the browser when this happens for debugging purposes? For example, perhaps something along the lines of an "about:memory", checking if X or Y window/resource is ghosted, or whatever (just an example). I figure that there has to be a way to check behind the curtain to see what part of the browser backend is hung/stuck, and then trace backwards to determine what is choking it.

**Comment by piroor** [comment]
On my environment, I've seen similar problem with Nightly 68.0a1, while debugging of TST. At the time I got grayed-out sidebar and all addons were completely dead. On my case the problem happend when I opened options pages of addons. I opened the debugger for TST before the problem happened, and after that the debugger said that there is no existing windows for TST (on the other hand, while TST is working correctly there are mulltiple pages like `background/background.html` and `sidebar/sidebar.html`).

Which version of Firefox do you use? Currently I saw the problem only on Nightly, and never seen on stable versions of Firefox. If you have also seen the problem on Nightly, it may be a bug (regression) of Firefox itself.

**Comment by irvinm** [comment]
@Coldblackice did you want to continue to try to resolve this issue?  If so, can you please respond to piroor?  If not, can you close this issue?

**Comment by irvinm** [comment]
@Coldblackice any updates?  Are you still experiencing the issue?

**Comment by Coldblackice** [comment]
@piroor @irvinm Apologies, I missed the notification emails on this thread and am only seeing it now. 

Yes, I still occasionally have the issue. I'll know right away that it's happened when there's a new tab that can't be closed/moved/anything. If I open the browser fresh and have a session restored, with all the tabs grayed out until selecting, sometimes I'll click on a tab and from that tab I'll open a new tab, the new tab will appear at the bottom of the list, and I'll know right away that it's happened, and Session Manager + developer console + addons will have stopped working for that window. It's only confined to that window, however. If I close the window, suddenly Session Manager is able to save a session again (it was already able to save a current-window-as-session, as long as it wasn't the ghost-tabbed window).

That's interesting what piroor says, as I believe it may have something to do with that, possibly having Firefox Options tab open at the tab and/or uBlock Origin settings (which opens as its own tab). I wonder if that's what's causing the trip up. The way I imagine it is that something happens that suddenly disconnects the front end (tabs) from the back end (data/storage). It's like the connection gets severed.

Can I access the TST debugger myself, or does that require a special build / source? I would love the ability to see actively what TST is seeing/doing for diagnostic purposes, if possible.

**Comment by piroor** [comment]
@Coldblackice You don't need special build for debugging, you just go to `about:debugging`. Please see also https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-start-debugger-for-tree-style-tab for more details.

**Comment by irvinm** [comment]
@Coldblackice any update on this?

**Comment by irvinm** [comment]
@piroor I think we should close this.  We can always continue the discussion if it closed if\when @Coldblackice has time.
