### ISSUE TITLE
How do you set tree behavior to inactive?

### ISSUE THREAD

**Issue by wdtglrn** [piroor/treestyletab#2235]
This is a great extension, but the trees are confusion. I find that tabs sometimes don't appear and I'm not sure how to work it. I'm using this as a replacement the above-the-url tab windows.

Can I set it so that all the tabs are on the same level without any hierarchies?

**Comment by Lej77** [comment]
The [readme has a section on how to disable automatically organized trees](https://github.com/piroor/treestyletab#i-dont-need-automatically-organized-tree-instead-i-just-want-to-organize-tree-by-myself). Note that after you can turn off `Debug mode` after you have changed the hidden settings.

**Comment by irvinm** [comment]
@wdtglrn is there anything more to discuss on this?  If no, can you close this item?

**Comment by irvinm** [comment]
@piroor I think this can be closed.

**Comment by piroor** [comment]
Looks no new background, so I close this.
