### ISSUE TITLE
Tree Style Tab "compact" theme

### ISSUE THREAD

**Issue by myBestSoftAndPref** [piroor/treestyletab#2236]
The theme is used with **1 level** tree level limit.

**How to**
1. Peek "mixed" or "plain" **Tree Style Tab** theme in **Tree Style Tab** _Preferences_
2. Peek "Compact" Firefox theme in Firefox `Customize...` menu
3. Take [this folder](https://github.com/myBestSoftAndPref/soft/tree/master/src/firefox/chrome) and put it to you Firefox profile, e.g `/home/user/.mozilla/firefox/XXXXXXX.default` Where `XXXXXXX` are any symbols. The result path should be like `/home/user/.mozilla/firefox/XXXXXXX.defaul/chrome`
4. Take [this code](https://github.com/myBestSoftAndPref/soft/blob/master/src/firefox/tree-style-tab.css) and put it to **Tree Style Tab** `Extra Style Rules` section
5. Restart Firefox

**Tested** with KDE (Kubuntu 18.04 LTS).

**Result is** (**Tab Bar** is hidden in `Compact` Firefox theme **and** `fullscreen` but you can choose **Normal** or **Touch** _Firefox theme_ to show **Tab Bar**)
<br>
![NrA0yBD](https://user-images.githubusercontent.com/18548391/56490799-168fe080-64ef-11e9-81af-b11318f4087b.png)

**Comment by piroor** [comment]
Is this not an issue report but a knowledge? I think you should add the information to the wiki: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules

**Comment by irvinm** [comment]
@myBestSoftAndPref can you add this to the wiki and close out this item?  Thanks.

**Comment by irvinm** [comment]
@piroor I think this can be closed.

**Comment by piroor** [comment]
OK, I close this as expired.
