### ISSUE TITLE
After some time of work I can't activate some tabs in tree - lower tab selected instead of clicked

### ISSUE THREAD

**Issue by MurzNN** [piroor/treestyletab#2241]
I can't always reproduce this problem on my side via short easy steps, so I describe the problem.

When I open Firefox and work some hours with many tabs - all works well. But after some time - something happens (nothing visible), and I can't select some tabs in tree (sometimes children, sometimes root): when I click on tab - in TST sidebar it shows as active at short time, but after less that second - next lower tab (at bottom of current tab) becomes active and Firefox switch to it. Via next clicks on needed tab - situation repeats, so I can't open needed tab.

If I click on tab, which is lower that needed, it selects normally without issues.

Closing TST sidebar and open again - sometimes help, sometimes not. So I can't describe right way how to reproduce this on your side :(

**Comment by piroor** [comment]
Thanks. There are some points possibly affect to this kind problems, so could you check them?:

* Which is the version of Firefox you use?
* Was the "unclickable" tab restored from the previous session? Or, does the problem happen without restarting of Firefox - does the problem appear just after the tab is newly opened?
* How did you open the tab? From links (with middle click / regular left click)? From an individual bookmark? From a bookmark folder? Ctrl-T? Clicking of the "+" button? Drag & drop of a link? Scripts in a webpage?
  * Which type is the tab opened from? A pinned tab? Or, a regular tab?
  * Was the tab opened together with others?
  * Where the tab was opened at? Middle of tabs? Top of sibling tabs (first child)? As a last child of a parent? Bottom of all tabs?
* How did you attach the tab to its parent? Automatically or manually (by drag and drop)?
* Did you change any option of TST? TST provides ability to export options via: Development => Debug mode => All Configs => Export (there is a button below the list of all options)

If you successfully narrow down the conditions and steps to reproduce the problem, please narrow down the list of other addons. The binary search method https://en.wikipedia.org/wiki/Binary_search_algorithm will be useful:

1. At first you disable all addons except TST and try to reproduce the problem.
   * If the problem is reproduced, there is no conflict and just TST's problem.
   * Otherwise, something other addons may conflict with TST.
2.  If TST conflicts with any other, activate only a half of addons.
   * If the problem happens, one or more criminals are in active addons.
   * Otherwise rest half of addons may contain the criminal.
3. Activate only addons TST and members of the group possibly contain the criminal, and disable a half of the group.
   * If the problem still happen, there is any criminal in the enabled addons.
   * Otherwise, there is any criminal in the disabled addons.
4. Repeat the step 3 until the criminal become clear.

**Comment by stapuft** [comment]
> 
> 
> I can't always reproduce this problem on my side via short easy steps, so I describe the problem.
> 
> When I open Firefox and work some hours with many tabs - all works well. But after some time - something happens (nothing visible), and I can't select some tabs in tree (sometimes children, sometimes root): when I click on tab - in TST sidebar it shows as active at short time, but after less that second - next lower tab (at bottom of current tab) becomes active and Firefox switch to it. Via next clicks on needed tab - situation repeats, so I can't open needed tab.
> 
> If I click on tab, which is lower that needed, it selects normally without issues.
> 
> Closing TST sidebar and open again - sometimes help, sometimes not. So I can't describe right way how to reproduce this on your side :(

this happens to me occasionally, if I hit ctrl+tab it allows you to switch to the tab you want to switch to, as for fixing the bug, I know of no way.

**Comment by MurzNN** [comment]
> * Which is the version of Firefox you use?

Strange question, most of users, that can provide bug report, use last version :) Firefox 66.0.3 64-bit on Ubuntu Linux. And `ctrl+tab` hotkey can switch to needed tab normally.

> * Was the "unclickable" tab restored from the previous session? Or, does the problem happen without restarting of Firefox - does the problem appear just after the tab is newly opened?

 "unclickable" tab opened in current session, but other tabs may be restored from previous session.

> * How did you open the tab? From links (with middle click / regular left click)?

From regular and middle clicks on page links.

>   * Which type is the tab opened from? A pinned tab? Or, a regular tab?

Regular tab.

>   * Was the tab opened together with others?

No, opened only single tab.

>   * Where the tab was opened at? Middle of tabs? Top of sibling tabs (first child)? As a last child of a parent? Bottom of all tabs?

Different: in middle, at bottom.

> * How did you attach the tab to its parent? Automatically or manually (by drag and drop)?

Automatically, no drag'n'drop.

> * Did you change any option of TST? TST provides ability to export options via: Development => Debug mode => All Configs => Export (there is a button below the list of all options)

Here is my settings:
[configs-treestyletab@piro.sakura.ne.jp.json.txt](https://github.com/piroor/treestyletab/files/3120259/configs-treestyletab%40piro.sakura.ne.jp.json.txt)

P.S. I can't find quick way to reproduce this problem every time, so it't too hard to test this on test environment ;(

**Comment by piroor** [comment]
@MurzNN Thank you for additional information. Some of them helps me to shrink the range of investigation. Summarized conditions are:

* Happens on Firefox 66.0.3 on Linux. So I can ignore all changes introduced at Firefox 67 and later.
* Visual order of tabs are correct, only internal index information is wrong.
* The problem happens on tabs opened from a link in a regular tab. It happens just with opening a child tab with middle click on a link (but there are some more unknown conditions.)
  * Tabs from links are attached to its opener as its last child automatically.
  * No option is modified about new tab position.
* Auto Tab Discard and TST Colored Tabs are installed, (but they looks unrelated to this problem.)

This means that I need to investigate codes to handle new tabs opened from links, and I just need to see a code path for default behaviors about new tab position.

**Comment by MurzNN** [comment]
I do more tests and can say, that this issue is reproducible often when I open child tab via middle click on page. And is disappeared when I close tab above problematic tab. Here is screencast with problem demonstration and disappearing: https://i.imgur.com/0Fndk16.mp4

**Comment by MurzNN** [comment]
Closing tab above problematic seems always solve the probem, and if I restore it via "Undo close tab" - all works without issue.

**Comment by piroor** [comment]
@MurzNN The screencast whiteouts between 00:10-00:15. Does this mean that you reopened(reloaded) the sidebar?

**Comment by MurzNN** [comment]
> @MurzNN The screencast whiteouts between 00:10-00:15. Does this mean that you reopened(reloaded) the sidebar?

No, I slowly :) type url in urlbar, and it shows white dropdown that overflow sidebar.

**Comment by piroor** [comment]
Do you use any other addon which controls positioning of new tabs? Or, did you changed secret options started with `browser.tabs.` via `about:config`?

**Comment by MurzNN** [comment]
Here is list of all my addons:
```
Auto Tab Discard
Containers On The Go
Containers Sync
Containers theme
Disable JavaScript
Display #Anchors
Download all Images
Firefox Multi-Account Containers
Form History Control (II)
Foxy Gestures
Hard Refresh Button
JSON Lite
Location Switcher
Make Google Images Great Again
Open bookmarks in new tab
Open image in a new tab
Plasma Integration
Popup window
RESTClient
Switch Container Plus
Table2Clipboard
TabSubmit Basic
Tree Style Tab
TST Colored Tabs
Url Shortener
User-Agent Switcher
```
So there are no addons, that operate with tabs. Also now I got the problem when can't switch to tab, that have no children (and not opened my middle click). Also seems the problem often happens on tab, that is previous to last bottom (when I open new tab at bottom, previous tab got the selection problem, and the problems stay with it, even if I open next tabs at bottom).

**Comment by piroor** [comment]
Thanks. I'm paying attention on some container related addons in the list, and if you set one of them to force open specific website in non-default container it may automatically reopen tabs opened from links (Firefox opens a new tab with the link URL in the same container, then the addon opens another tab with a specific container at the same position and removes the original tab automatically). For example Firefox Multi-Account Container (FMAC) actually has such a feature. However, I've tried it but I couldn't reproduce the problem. Did you change options of other addons? Or, any other addon does such operations?

**Comment by piroor** [comment]
Ah, hmm, but there is no "container" marker on the screencast you uploaded...

**Comment by pfheatwole** [comment]
I experience this bug maybe once a week. I usually fix the tree by tearing off the children and reattaching them to the parent. I can't reliably reproduce this bug, but here is how it happened yesterday:

I had a parent tab `A`, and middle clicked a link to open `B`:

```
A
 `B
```
Clicking the parent `A` would momentarily select that tab (including updating the forward/backward buttons), then almost instantly (~150ms?) the tab selection would change to the child `B`. Inside `B`, I middle clicked a link:

```
A
 `B
   `C
```

Clicking `A` would select `B`, clicking `B` would select `C`. I used Ctrl-PgUp to select `A`, then middle clicked a second link inside `A`, and the selection behavior was fixed for the entire tree. (If this bug happens again, I will see if opening a new child in the top-level parent reliably fixes the tree.)

I'm running Firefox 66.0.3 on Linux (Fedora 29). The problem does not require restarting Firefox and reloading tabs; it happens on newly opened tabs. I open new children with middle click. The parent tabs are normal tabs (not pinned). Selection is only broken in that specific tree; the rest of the tabs in the window can be selected normally. I don't use containers.

My addons:
```
Decentraleyes
Google search link fix
HTTPS Everywhere
Neat URL
PassFF
Tree Style Tab
uBlock Origin
uMatrix
```

My TST config: [configs-treestyletab@piro.sakura.ne.jp.txt](https://github.com/piroor/treestyletab/files/3132071/configs-treestyletab%40piro.sakura.ne.jp.txt)

Looks like both @MurzNN and I set `"autoCollapseExpandSubtreeOnAttach": false`.

**Comment by piroor** [comment]
On investigation at #2119 I've realized that tab's index can be overwritten unexpectedly with wrong values when multiple non-blank tabs are opened in a time (I've tried with tabs from 75 bookmarks in a folder). I cannot decide both problems are triggered with the same source, but the fix may affect to this. Could you try the latest development build?: https://github.com/piroor/treestyletab/blob/master/README.md#development-builds

**Comment by pfheatwole** [comment]
Sure, I can do that if it would help, but I see 3.0.10 has been released since your last message. Does 3.0.10 include the changes from the development build you were wanting me to test? If it does, I'll stick to the official releases and report if I experience this bug again. Thanks!

**Comment by MurzNN** [comment]
Thanks, after recent updates seems the problem is disappear! I don't do many tests at now, so maybe it will be reproduced in near future. Let's close issue now, I will reopen it if problem is reproduced again.
