### ISSUE TITLE
v3.0.8 Tree suddenly disappeared in just one window

### ISSUE THREAD

**Issue by cipri-tom** [piroor/treestyletab#2244]
## Short description

I have two windows, one with many tabs (205), one with some fewer ones (28). The tree suddenly disappeared in the window with many tabs. Everything became indented in level 0, no more markers for expanding (some were collapsed), nothing.

## Steps to reproduce

Not easy, since these tabs have been collected over a long period, most of them from the version 2.7 I think. I had problems before, but usually they happened after an update or after a restart of Firefox. This time, it happened as I was browsing. The TST side-bar just turned into the "loading" state, and then all the tree was flattened. However, there was no update at this point, the add-on was updated 2 days ago.

What is more interesting is that in the other window, the tree still works well. I tried toggling TST (F1 button), restarting Firefox, to no avail :(.

## Environment

 * Platform (OS): macOS 10.14.4
 * Version of Firefox: 66.0.3
 * Version (or revision) of Tree Style Tab: 3.0.8

## Feature req?

Is there an option to export and then later re-import trees of tabs? Just to minimise damage for the future.

Although, I have to say, I am very impressed by the v3 ! I see a lot of work has been put into it and I'm very happy it has finally happened. I am sure that once the small bugs are eliminated, the extension will be very robust!

**Comment by jingofett** [comment]
Also happening to me. It happened to both of my windows though. Opening a new tab seems to trigger it. It may have something to with the "Temporary Containers" add on

**Comment by rtoijala** [comment]
Same for me, when opening a new tab from a pinned tab. Reproducible.
I do not have the Temporary Containers add-on.
Linux x86-64, Firefox 66.0.3, Tree Style Tab 3.0.8

The browser console shows the following:

    Fatal error: native tabs are not same to the tabs tracked by the master process, for the window 3. Reloading all...   sidebar-tabs.js:428:5
    
    Promise resolved while context is inactive  unique-id.js:92
        request moz-extension://102e6a2d-cb35-4609-b462-ed200e48eaa4/common/unique-id.js:92
    
    TypeError: Argument 1 of StructuredCloneHolder.deserialize is not an object.  ExtensionChild.jsm:1016:24
    
    Error: WebExtension context not found!    ExtensionParent.jsm:1041:13
    
    TypeError: Argument 1 of StructuredCloneHolder.deserialize is not an object.  ExtensionChild.jsm:1016:24

**Comment by piroor** [comment]
I saw this problem on my environment just one time. Now I need (and I'm finding) constant steps to reproduce the problem...

**Comment by piroor** [comment]
I still cannot reproduce the situation, but I've found why tree structure is lost. After the commit ad72787 tree structure will be restored after all sidebars are reloaded.

**Comment by Sada-Mio** [comment]
Not exactly sure how to reproduce consistently, but noticed it flattening after opening a new tab link from a pinned tab. Minutes before that I had created a profile backup, restored, tried opening the same link again but couldn't reproduce the problem.

I make daily profile backup in fear of losing my hundreds of tab tree. Bug has been randomly flattening tabs starting from April-26. Might give a clue to find out what changes made since then results in this bug.

**Comment by cipri-tom** [comment]
@piroor I just got the update for `3.0.10` which includes that commit, but didn't get the tree back. I mean, not the one that was flattened. I restarted Firefox and all that. The indents that appeared since the flattening (in the same tree), are still there, so it's just the old tabs that kind of lost the tree information.

I can upload my list of tabs or anything that would help with debugging, if you can remind me how to get it (this is the work laptop, so no "interesting" personal stuff in there 😅 )

**Comment by piroor** [comment]
@cipri-tom Did you mean that flattened tree was not restored after updating of TST? Then, sadly TST may not possible to restore tree anymore on such cases and you may need to recreate tree structure by manual drag and drop. The change introduced at 3.0.10 means that structured tree will be kept as is after reloading triggered to fix misunsynchronizations of tabs.

**Comment by cipri-tom** [comment]
Yes, that's what I meant. 

No worries, it was probably about time I do a cleanup among those tabs collapsed in trees long time ago ^^. 

Thank you for introducing a fix!

**Comment by cipri-tom** [comment]
Hi,

This just happened again on 3.0.11 😞 .
I'm not sure how @rtoijala has managed to get browser console information. In the page that I was browsing there was nothing. Just the tree restarted all of a sudden, not even after opening a tab. 

Note that this is still the same old tree, so there is probably something broken in it. I should maybe scrap it and start anew. But how could I do this, while keeping all the tabs?

**Comment by rtoijala** [comment]
I have not had the problem since 3.0.11.
To get the browser console, use the hamburger menu -> Web Developer -> Browser Console, or use the keyboard shortcut, which for me is Ctrl+Shift+J.

**Comment by cipri-tom** [comment]
Thanks! 

This is the thing I found in the console which may be relevant:

```
Type error for parameter tabId (Integer -1 is too small (must be at least 0)) for tabs.get. background.js:182
Type error for parameter tabId (Integer -1 is too small (must be at least 0)) for tabs.get. background.js:377
    applyChanges resource://gre/modules/WebRequest.jsm:804
    throw self-hosted:1227
[Exception... "Component returned failure code: 0x805e0006 [nsIChannel.asyncOpen2]"  nsresult: "0x805e0006 (<unknown>)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: load :: line 147"  data: no]
    load resource:///modules/FaviconLoader.jsm:147
    load resource:///modules/FaviconLoader.jsm:463
    InterpretGeneratorResume self-hosted:1255
    next self-hosted:1210
    loadIcons resource:///modules/FaviconLoader.jsm:528
    onPageShow resource:///modules/FaviconLoader.jsm:560
    onPageShow resource:///actors/LinkHandlerChild.jsm:67
    handleEvent resource:///actors/LinkHandlerChild.jsm:156
    handleActorEvent resource://gre/modules/ActorManagerChild.jsm:134
    handleActorEvent self-hosted:1018
Content Security Policy: The page’s settings blocked the loading of a resource at https://avatars2.githubusercontent.com/favicon.ico (“default-src”).
Type error for parameter tabId (Integer -1 is too small (must be at least 0)) for tabs.get. background.js:182
    applyChanges resource://gre/modules/WebRequest.jsm:804
    throw self-hosted:1227
Type error for parameter tabId (Integer -1 is too small (must be at least 0)) for tabs.get. background.js:377
    applyChanges resource://gre/modules/WebRequest.jsm:804
    throw self-hosted:1227
```
