### ISSUE TITLE
Empty Sidebar after TSM loads session

### ISSUE THREAD

**Issue by donw146** [piroor/treestyletab#2247]
windows 10.
ff 66.0.3
tst3.0.9
Tab Session Manager (TSM) 4.5.2

My base window, which uses native Firefox session restore and TST opens fine. When I try to open an additional window session using TSM I can see the tabs being created but the sidebar ends up empty. If I switch the sidebar to History and then back to TST it quickly shows all my tabs.
I've attached one of my TSM session exports for testing.
[Cruise planning - Mediterranean - 2019-04-29 21-25-09.json.txt](https://github.com/piroor/treestyletab/files/3132494/Cruise.planning.-.Mediterranean.-.2019-04-29.21-25-09.json.txt)
I had to append .txt to the file name to upload it. Remove if necessary to import using TSM.

**Comment by piroor** [comment]
I've tried with the same condition but I couldn't reproduce the problem.

Did you activate TSM's option for the compatibility with TST? On my environment, TST's sidebar has been initialized correctly for me, and restored tabs have appeared in the sidebar step by step.

**Comment by donw146** [comment]
It looks like it was a timing issue. When I went to check my TSM settings
Supports Tree Style Tab was checked properly
However,
    Delay when tree restoration (millisecond) - was set to 350 ms - a setting I made a long time ago. I changed it to 750 ms and the sidebar opened correctly.
Sorry for the false alarm and thanks for all you efforts. TST is essential to my use of Firefox.

**Comment by piroor** [comment]
Is the option TST's or TMS's? Could you add a screenshot of the options page?

**Comment by donw146** [comment]
This option is TSM's. I've included a screen capture of my complete TSM settings. Most are defaults but I have made a few changes.
![2019-05-01_13-47-18](https://user-images.githubusercontent.com/8295285/57032318-1347d380-6c18-11e9-9c4c-f9fd1a5a4705.png)

**Comment by piroor** [comment]
Hmm, 750msec delay looks very large... On my environment 150msec (default value of TSM) is enough. However, the required minimum delay can be affected with the number of tabs, the system performance, and others.

**Comment by donw146** [comment]
750 ms was just an arbitrary guess that worked. It doesn't seem to introduce any appreciable delay in loading tabs. I frequently have several hundred tabs open in 2 or more windows so I plan to leave it at what appears to be a safe level for my usage.

**Comment by irvinm** [comment]
@donw146 is it ok to close this issue?  If so, can you close it?

**Comment by donw146** [comment]
It is OK to close. Doing so.
