### ISSUE TITLE
Drag-and-drop from one window to another is broken in Firefox ESR

### ISSUE THREAD

**Issue by HighCommander4** [piroor/treestyletab#2248]
## Steps to reproduce

 1. Open two Firefox windows, with the TST sidebar open in each
 2. Open a tab in one window
 3. Try to drag-and-drop it from the tree of one window into the tree of the other

## Expected result

The tab is moved to the other window.

## Actual result

I do see a drag image, and a drop indicator in the target window, but when I release the mouse, the tab stays in its original window.

## Environment

 * Platform (OS): Linux (Debian stable)
 * Version of Firefox: ESR 60.6.1
 * Version (or revision) of Tree Style Tab: 2.8.5

This is a recent regression, either from a Firefox update or a TST update, I'm not sure which. It used to work, in this same configuration (Firefox 60 ESR, but perhaps earlier than 60.6).

**Comment by piroor** [comment]
Sorry, TST's latest version is 3.0.9 and ESR60 is not supported by me anymore.

**Comment by HighCommander4** [comment]
I'm sorry to hear that. It will be another 5+ months before Debian stable ships ESR68.

**Comment by piroor** [comment]
Currently I have less resource to maintain TST, so old versions won't be maintained. Could you install an old version from https://addons.mozilla.org/firefox/addon/tree-style-tab/versions/ and disable auto update of TST until ESR68 become available?

**Comment by HighCommander4** [comment]
I can confirm that it works fine with version 2.7.23 - thanks!

I note that, while I had auto-updates enabled, I was only updated to 2.8.5, not 3.0.9, and the addons manager says 3.0.9 is not compatible with my current Firefox version. So, clearly, TST versions are already annotated with what Firefox versions they support. Should the annotations be adjusted so the boundary for ESR support is reduced from 2.8.5 to 2.7.23?

**Comment by piroor** [comment]
TST 2.8.5 is designed to work with Firefox ESR60, but buggy on some environments and usecases.

**Comment by irvinm** [comment]
@piroor we should probably close this one.
