### ISSUE TITLE
Warn on close multiple does not work when tabs are closed using the keyboard

### ISSUE THREAD

**Issue by BobVul** [piroor/treestyletab#2249]
## Short description
When the keyboard (Ctrl+W) is used to close a parent tab of a collapsed group, the warning for multiple tabs being closed does not appear. All the tabs in the group are immediately closed.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Create a tree with at least one child.
 4. Focus on the root (parent) of the tree.
 5. Collapse the tree.
 6. Press Ctrl+W to close the parent tab of the tree.

Observe that the entire tree is closed without warning.

GIF screen recording:

![KeyboardCloseNoWarning](https://user-images.githubusercontent.com/1674237/57006997-a7219b80-6c28-11e9-8b4e-5ec7b4aa0bcb.gif)

## Expected result
There should be a warning before closing multiple tabs, as per the default setting.

## Actual result
There is no warning. All tabs in the tree are closed.

## Environment

 * Platform (OS): Windows 10 v1803
 * Version of Firefox: 66.0.3
 * Version (or revision) of Tree Style Tab: 3.0.9

**Comment by BobVul** [comment]
Looks like there's a bit of confusion here:

https://github.com/piroor/treestyletab/blob/df9f4301188f59920910c1d865e10b24680c0931/webextensions/background/background.js#L443-L467

`tabIds` is the array of tabs to close, but the message sent to the confirm dialog uses `tabs` instead. `tabs` is the single currently active tab (used to display a message within the tab?).

I would suggest renaming `tabs` to `activeTab` and `tabIds` to `closingTabIds`. Then it's clearer that line 465 should instead be `tabIds: closingTabIds` https://github.com/piroor/treestyletab/blob/df9f4301188f59920910c1d865e10b24680c0931/webextensions/background/background.js#L465

**Comment by piroor** [comment]
Thanks, this also should be fixed with recent commits.

**Comment by BobVul** [comment]
Thanks for the quick response. Unfortunately this one does not seem to be completely fixed yet: the confirmation prompt now appears correctly, but the tabs are still removed from TST even if cancelled. The parent tab is completely removed (maybe okay, though a bit counterintuitive) and the children remain in the Firefox tab bar.

GIF recording:

![KeyboardCloseConfirmTest2](https://user-images.githubusercontent.com/1674237/57012814-a8b08b00-6c4b-11e9-8a44-e4597884f2d8.gif)

**Comment by BobVul** [comment]
Hold on - it's working now, after I tried debugging it. Interesting. I'll see if I can find a consistent way to reproduce.

**Comment by BobVul** [comment]
Looks like it's fine when testing with real websites. The scenario in the above recording only appears with blank (`about:newtab`) tabs, probably because of how Firefox's tab history/restore works with them (i.e. it ignores them completely). So this is probably fine in real-world use.

There is another quirk in that if a blank parent tab is closed, the reopened tab can be a previous one from the history. I'm not sure what can be done about this, unless `about:newtab` is special-cased and restored differently by TST. But that's probably not worth the effort.

Thanks for the fix!

**Comment by piroor** [comment]
Thank you for researching. As you know Firefox doesn't allow to us to restore closed blank tabs. On the other hand TST expected that closed tabs are always restorable.

* Basically, on an WebExtensions-based addon we cannot do anything *before* a tab is removed.
* So TST cannot show confirmation dialog *before* tabs are closed with Ctrl-W or other methods outside of TST.
* Instead, TST detects *already removed* tabs and show a confirmation regardless they are actually closed. And if the "Cancel" button is chosen TST restores closed tabs for rolling back.

So I've introduced one more change: TST now don't show any confirmation if all closed tabs are unrestorable. This is an unavoidable edge-case restriction of WebExtensions-based addon.

**Comment by BobVul** [comment]
Thanks, that looks like a good fix for the case of all-blank tabs :)
