### ISSUE TITLE
Subtabs not indented in relation to parent tabs

### ISSUE THREAD

**Issue by dotancohen** [piroor/treestyletab#225]
Firefox 8, Tree Style Tabs 0.14.2012012901, Kubuntu Linux 11.10

Subtabs are not indented in relation to their parent tabs. See screenshot attached.

Note that collapsing then reopening the tree causes it to display properly. The issue is intermittent and not determinate: often I can trigger it, sometimes I cannot. I started noticing the issue yesterday I think, and sure enough Tree Style Tabs was updated yesterday according to Firefox.

Thanks.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
