### ISSUE TITLE
Warn on close multiple does not work when treat as parent by operations inside the tree sidebar

### ISSUE THREAD

**Issue by BobVul** [piroor/treestyletab#2250]
## Short description
When the option "Treat as a parent by operations inside the tree sidebar. / Treat just as a solo tab, by operations outside the tree sidebar." is selected, closing a parent tab from inside the tree sidebar does not show the expected warning.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Change the setting under Tree Behavior => "When a parent tab is moved or closed by someone from outside of the tree sidebar" to (3rd option) "Treat as a parent by operations inside the tree sidebar. / Treat just as a solo tab, by operations outside the tree sidebar."
  
     ![2019-05-01 16_40_33-Add-ons Manager](https://user-images.githubusercontent.com/1674237/57008107-287d2c00-6c31-11e9-93b1-ecfeaf71118f.png)

 4. Create a tree with at least one child.
 5. Collapse the tree.
 6. Close the tree from the sidebar using the X button on the right side.

Observe that the entire tree is closed without warning.

GIF screen recording:

![CloseOutsideChangedExample](https://user-images.githubusercontent.com/1674237/57008125-3e8aec80-6c31-11e9-828e-fc9ee6167a94.gif)

## Expected result
There should be a warning before closing multiple tabs, as per the default setting.

## Actual result
There is no warning. All tabs in the tree are closed.

## Environment

 * Platform (OS): Windows 10 v1803
 * Version of Firefox: 66.0.3
 * Version (or revision) of Tree Style Tab: 3.0.9

**Comment by BobVul** [comment]
I took a brief look with the debugger and it looks like `byInternalOperation` is undefined in `shouldApplyTreeBehavior` when called from `getCloseParentBehaviorForTabWithSidebarOpenState`, so `tabsToBeClosed` only has one entry and the warning is not shown.

I would expect `byInternalOperation` to be set here, since the close is initiated by a mouse click on the X in the sidebar?

My first thought is maybe set `byInternalOperation: true` in the call on https://github.com/piroor/treestyletab/blob/df9f4301188f59920910c1d865e10b24680c0931/webextensions/common/tree-behavior.js#L68-L71

That would work for `getClosingTabsFromParent` called from the middle click and close box handlers in mouse-event-listener.js. But `getClosingTabsFromParent` is also called from handle-removed-tabs.js and I do not know how safe that is there.

The alternative is for `getClosingTabsFromParent` itself to take a `removeInfo` param, which has `byInternalOperation` set from the mouse event listeners calls only.

**Comment by piroor** [comment]
Thanks, this problem should be fixed with recent commits. You can try the latest development build: https://github.com/piroor/treestyletab/blob/master/README.md#development-builds

**Comment by BobVul** [comment]
Thanks for the quick response! This seems to work for me now with the dev build.
