### ISSUE TITLE
Internal tests not succesfull, but probably is ok

### ISSUE THREAD

**Issue by IRainman** [piroor/treestyletab#2255]
Firefox 66.0.3

 .EEEE.F........Done.

    testAutoFixupForHiddenTabs
    TypeError: browser.tabs.hide is not a function

    testAutoFixupForHiddenTabs/<@moz-extension://f00d935b-ba19-4f3a-8238-c6acb40f42fc/tests/test-hidden.js:89:7
    testAutoFixupForHiddenTabs@moz-extension://f00d935b-ba19-4f3a-8238-c6acb40f42fc/tests/test-hidden.js:79:11
    async*runAll@moz-extension://f00d935b-ba19-4f3a-8238-c6acb40f42fc/tests/runner.js:87:26
    async*run@moz-extension://f00d935b-ba19-4f3a-8238-c6acb40f42fc/tests/runner.js:32:9

    testCalculateNewTabPositionWithHiddenTabs
    TypeError: browser.tabs.hide is not a function

    testCalculateNewTabPositionWithHiddenTabs@moz-extension://f00d935b-ba19-4f3a-8238-c6acb40f42fc/tests/test-hidden.js:147:9
    async*runAll@moz-extension://f00d935b-ba19-4f3a-8238-c6acb40f42fc/tests/runner.js:87:26
    async*run@moz-extension://f00d935b-ba19-4f3a-8238-c6acb40f42fc/tests/runner.js:32:9

    testMoveAttachedTabBeforeHiddenTab
    TypeError: browser.tabs.hide is not a function

    testMoveAttachedTabBeforeHiddenTab@moz-extension://f00d935b-ba19-4f3a-8238-c6acb40f42fc/tests/test-hidden.js:218:9
    async*runAll@moz-extension://f00d935b-ba19-4f3a-8238-c6acb40f42fc/tests/runner.js:87:26
    async*run@moz-extension://f00d935b-ba19-4f3a-8238-c6acb40f42fc/tests/runner.js:32:9

    testNewTabBeforeHiddenTab
    TypeError: browser.tabs.hide is not a function

    testNewTabBeforeHiddenTab@moz-extension://f00d935b-ba19-4f3a-8238-c6acb40f42fc/tests/test-hidden.js:178:9
    async*runAll@moz-extension://f00d935b-ba19-4f3a-8238-c6acb40f42fc/tests/runner.js:87:26
    async*run@moz-extension://f00d935b-ba19-4f3a-8238-c6acb40f42fc/tests/runner.js:32:9

    testInheritContainerFromAutoAttachedParent
    AssertionError: a new tab implicitly attached to the active tab must inherit the contianer of the old active tab, and there must not be any needless group tab to group the original tab and the reopened tab.

    is@moz-extension://f00d935b-ba19-4f3a-8238-c6acb40f42fc/tests/assert.js:12:17
    testInheritContainerFromAutoAttachedParent@moz-extension://f00d935b-ba19-4f3a-8238-c6acb40f42fc/tests/test-new-tab.js:50:3
    async*runAll@moz-extension://f00d935b-ba19-4f3a-8238-c6acb40f42fc/tests/runner.js:87:26
    async*run@moz-extension://f00d935b-ba19-4f3a-8238-c6acb40f42fc/tests/runner.js:32:9

    Expected

    {
      "newTabsCount": 1,
      "newTabParent": 355,
      "newTabContainer": "firefox-container-1"
    }

    Actual

    {
      "newTabsCount": 1,
      "newTabParent": null,
      "newTabContainer": "firefox-default"
    }

    Difference

    {  "newTabsCount": 1,  "newTabParent": 355null,  "newTabContainer": "firefox-condefaulttainer-1"}

**Comment by piroor** [comment]
You need to give an extra permission to TST before running tests:
![image](https://user-images.githubusercontent.com/70062/57106252-da1e7900-6d67-11e9-86a8-a866fe71e6ef.png)

**Comment by IRainman** [comment]
` ...............Done.`

Thank you! It works.
