### ISSUE TITLE
unreliable prompting for tab grouping when opening a bookmark folder (open all in tabs)

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#2257]
## Short description

Please follow he repro directions exactly, a deviation in at least some steps will not repro.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. show the bookmark bar
 4. add "New Folder" to it
 5. add 2 bookmarks to "New Folder" without navigating to them
    1. name & location: http://example.org/?1
    2. name & location: http://example.org/?2
 6. close all but one homepage tab
 7. "bookmark bar" -> "New Folder" -> "open all in tabs"
 8. if it prompt to group, go to step 6
 9. for me it takes no more than two attempts to repro and 8/10 attempts manifested the bug

## Environment

 * Platform (OS): win7 x64 sp1
 * Version of Firefox: 66.0.3 x64
 * Version (or revision) of Tree Style Tab: 3.0.10

**Comment by piroor** [comment]
Thanks, I forgot to check the permission to run script in the content area on such cases. After the commit d77de64 the confirmation dialog will be shown in the sidebar when `<all_urls>` permission is not granted yet.

As a workaround, you can give the permission manually via: TST options => "Tree Behavior" => "Don't expand collapsed tree and skip collapsed descendants, while switching focus of tabs via keyboard shortcuts. (*You need to allow executing scripts on webpages.)"

**Comment by irvinm** [comment]
@bughit same thing with this one.  Looks like the check-in made 3.0.11.  Let's confirm if this is fixed or not.

**Comment by bughit** [comment]
fixed
