### ISSUE TITLE
Unexpected behaviour of tabs (after upgrading to ff 9.x)

### ISSUE THREAD

**Issue by lxandr** [piroor/treestyletab#226]
I'm not quite sure when it started, but it looks like after I've upgraded FF from 8.x version to 9.0.1.
Maybe it relates to new version of FF, or it's just a coincidence...
A have a lot of opened tabs (about 30-50) in each of 3 FF windows (1-2 hundred of tabs total).
Now I've got some 'magic':
- when I try to open new tab it can just disappear somewhere (it actually opens, but doesn't showed in treetabs view)
- when I click group of tabs sometimes it  doesn't auto-expand (or collapse). Also, tab isn't in focus after click. I click a tab, but I can get wrong tab opened (not that one I wanted to open)
- triangles from the left side of groups of tabs are not showing the correct state (is group expanded or not?).
- even Ctrl+PgUp/Down doesn't  really helps to walk through tabs. Focus is getting crazy and jumps through group of tabs (not tab one by one).

Here is screenshot:
http://rghost.ru/36369242.view
I have opened "about:config", but the tab of it is somewhere hidden between previous tab and "new tab" button.

P.S.: I'm using Ubuntu 11.04 amd64, FF 9.0.1+build1-0ubuntu0.11.04.1

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
