### ISSUE TITLE
Provide version for latest ESR

### ISSUE THREAD

**Issue by AlexTalker** [piroor/treestyletab#2260]
## Short description
I use this tab for couple years now.
And it were enabled all the time until recently Firefox decide to press on add-on signing.
And things went to hell so quick that I decided to switch on latest `60 ESR` release instead of using nightly or developer builds which allow to overcome the problem.
Unfortunately, your add-on can't be installed neither from market nor from a file.
Market says it requires version `65` and I can't find earlier releases without building things from sources.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Try to install from download page or market
 3. Being enable to install

I wanted to take a screenshot of market page but screenshots doesn't seem to work either(!!!).
So here's the link I see https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/

## Expected result

Add-on successfully works on latest ESR.

## Actual result

Add-on can't be installed.

## Environment

 * Platform (OS): Windows
 * Version of Firefox: `60.6.1esr`
 * Version (or revision) of Tree Style Tab: 3.0.11

**Comment by mordquist** [comment]
Tree Style Tab Version 2.7.23 is the latest version that support Firefox 60 ESR. You can get it from Mozilla here: https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/versions/

**Comment by AlexTalker** [comment]
@mordquist @piroor 
Well, thanks for the link, interface of the site did not suggest older version at least a bit explicitly. Now I finally see the link in the interface too. 😄 

However, I would like if you updated what supposed to be the same link on official site:
![image](https://user-images.githubusercontent.com/3531127/57191902-54e7bf80-6f33-11e9-987d-fa848d2744ea.png)
The link under `Old Versions` leads to `404`.

**Comment by AlexTalker** [comment]
Also I overheard that issue with signatures were caused by Mozilla's screwing up their certificate.
As screenshots began to work, can't decide if I want to go back on latest anymore :trollface:

**Comment by piroor** [comment]
Thanks, I forgot to update links on my website.

**Comment by piroor** [comment]
> interface of the site did not suggest older version at least a bit explicitly.

I believe that it is a problem of Mozilla Add-ons website itself and should be tracked at the issue tracker of the AMO website: https://github.com/mozilla/addons-server/issues

**Comment by mordquist** [comment]
> > interface of the site did not suggest older version at least a bit explicitly.
> 
> I believe that it is a problem of Mozilla Add-ons website itself and should be tracked at the issue tracker of the AMO website: https://github.com/mozilla/addons-server/issues

I agree that the issue lies with AMO, but given the following disclaimer I'm guessing it's intentional on Mozilla's part:
![Screenshot_20190505_235533](https://user-images.githubusercontent.com/16607572/57200917-f9442300-6f80-11e9-8c37-0e91e9aac0ba.png)

**Comment by AlexTalker** [comment]
@piroor @mordquist Yes, you're right, I just express why I've got confused: link were broken and interface of mozilla add-on website is just a mess(comparing to GitHub lets say, where you have `Release` tab at top of the page).
I'll file a report maybe but this issue is definitely closed.
