### ISSUE TITLE
Clarify supported versions in README

### ISSUE THREAD

**Issue by mordquist** [piroor/treestyletab#2261]
## Short description
The README states that Firefox 57 and above is supported. It also says that TST is designed for the latest Firefox and Firefox ESR. This is no longer accurate as of 6710423.

A clarification of actually supported versions is probably in order to avoid confusion.

## Steps to reproduce

 1. Start Firefox 60 ESR with clean profile.
 2. Install TST.
 3. Install fails because of `"strict_min_version": "65.0"`

## Expected result
Addon installs on all supported platforms as specified in the README.

## Actual result
Installation fails because of dropped support for Firefox ESR 60.

## Environment

 * Platform (OS): Fedora 30
 * Version of Firefox: ESR 60 
 * Version (or revision) of Tree Style Tab: 3.0.11

**Comment by piroor** [comment]
The README.md is just a sub document. You need to see webextensions/manifest.json or [notes of supported versions on each release](https://addons.mozilla.org/firefox/addon/tree-style-tab/versions/) to know exact supported version of Firefox.

**Comment by piroor** [comment]
I'm still negative to add version information to documents because I'll forget to update that. So, instead I've add a link to the install manifest to see the minimum supported version. Commit: 0726319fae1dc83a876b616a56a4af5275cc866f

**Comment by mordquist** [comment]
Looks good to me! Closing this as solved.

Thank you for your great work on an indispensable add-on!
