### ISSUE TITLE
TST has been disabled by FF after latest update. I trid to download the signed package, keeps failing, saying, 'download failed, check your connection.' Connection is fine. Help?

### ISSUE THREAD

**Issue by Gaia39** [piroor/treestyletab#2262]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by Fahrenh3it** [comment]
Same here. FF 66.0.3 says Tab Session Manager is unsigned and has deactivated it. Can't download it again as the download page says "download failed, check your connection" despite the connection being perfectly fine. Problem is, I had lots of useful tabs saved and never made a backup of those as I never expected the module to be deactivated, so it looks like I lost all of them... Any clue as to how to (1) reactivate TSM, and (2) recover my saved Tabs? Thx

**Comment by AlexTalker** [comment]
Mozilla screwed up signing a bit. Someday they'll fix that back.
Until then, unless you use latest or beta on windows, you can select a workaround: https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct#w_what-can-i-do-if-firefox-disables-an-installed-add-on

**Comment by IRainman** [comment]
That is not TST problem! Read this for detail https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

**Comment by piroor** [comment]
Duplicated of #2258.

**Comment by Gaia39** [comment]
TSt back functioning

**Comment by hhegedus** [comment]
If TST is working again then why am I still have this problem.  Tickets should not be closed before the problem is fixed and I don't consider running a beta version of FF a fix.

**Comment by justdave** [comment]
This was a problem in all versions of Firefox and TST, and the problem was with Firefox itself, not with TST. There is nothing the TST developer can do to fix this, which is why this ticket is closed. Follow the links above to the Firefox bug reports. There should be an update to Firefox (no matter which Firefox you're using) with a new signing key in it, you need to pick up that update for TST to start working again.
