### ISSUE TITLE
groups tab vs flat tabs

### ISSUE THREAD

**Issue by boistordu** [piroor/treestyletab#2264]
## Short description
Since the last update, I add this message to ask me if I wanted a group tabs or flat tabs and it didn't change anything. And I do'nt find it in the options of this addon .... so there is none or what was it? 

 * Platform (OS): windows 10 pro with latest ffirfox 66.0.0.4

**Comment by piroor** [comment]
Sorry but I couldn't understand what is the problem you are facing. Please fill the issue template https://raw.githubusercontent.com/piroor/treestyletab/master/ISSUE_TEMPLATE.md to describe how to reproduce the problem on my environment.

**Comment by boistordu** [comment]
I can't since 
1/ I didn't review your code
2/ =>so I can't say if it's normal behavior
3/ there is no expected behavior
4/ it's not a real issue but a lack of clarity and "maybe" a lack of feature in the options of your add-on

As I said, after the recent hotfix by firefox(if you have been following [the news](https://twitter.com/firefox/status/1125135184343396352?s=21))   which have been translated into an upgrade yesterday, I had a message from tree style tab, and I didn't pay enough attention to it since I was thinking there was a checkboxe about that in the options, about displaying the whole thing into flat tabs or group tabs. 
=> first I want to highlight that the user doesn't have enough information to make an informative choice about it,

And so I was thinking there was an option about it somewhere, easy to change and easy to understand the implication, but apparently I didn't find anywhere an option about that...
=> so is it one or not ? 

if there is a log about your add-on and you don't know the message/warning of your mod that I'm referencing too, we can certainly see it in the logs if there is any. I had this message on multiple hosts so I guess that everyone got it.

**Comment by piroor** [comment]
You don't need to know how the code is written. Instead, you should treat it just as a black box. Steps to reproduce, expected result, and actual result should be written with the viewpoint of a regular user. However, they should be described with details, for example:

 * Good: "press the keyboard shortcut Ctrl-T", bad: "open a new tab" (how did you do that?)
 * Good: "open a bookmark folder in the bookmarks toolbar, and click the 'open all in tabs' menu item", bad: "open tabs" (how did you that, and what tabs are opened?) 

I'm not well about English, so it is hard for me to understand what is the problem from naturally written paragraphs. Instead, descriptions written like the one for a machine may help my understanding.


Anyway, I guessed that you might reported about the confirmation dialog about grouping of multiple tabs opened in a time. When the checkbox TST options => "New Tabs Behavior" => "Auto-grouping of tabs" => "Confirm to group tabs" is ON, a dialog will appear on cases like opening of a bookmark folder in tabs.

**Comment by boistordu** [comment]
Well yeah no problem with considering it as a black box, but still, I had nothing to report into step to reproduce since it happened out of the blue, I had no action to pinpoint as the point of origin and I didn't know if it was the normal behavior or not and finally I had not a clue about something related into the option. 

Anyway, by chance I had another dialog popping up. Apparently I can't attach a png file so I can't show you but it seems related to what you are describing. It's to ask me if I want to group x number of tabs together.
Would you be kind enough to add a screen shot like you did for the theme part of the option, to help identify that this dialog is related to that option?

Thanks in advance
Best regards :) 
And again sorry for the misunderstanding
