### ISSUE TITLE
Unable to install TST for Firefox ESR

### ISSUE THREAD

**Issue by ploth** [piroor/treestyletab#2265]
## Short description

I'm unable to install TST for Firefox ESR. As stated in the FAQ it should be possible.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Not able to install TST (Firefox addon page states (This add-on requires a newer version of Firefox (at least version 65.0). You are using Firefox 60.0.)

## Expected result

Able to install TST with my firefox release (60.5.2esr or 60.6.1esr)

## Actual result

Not able to install TST.

## Environment

 * Platform (OS): Gentoo
 * Version of Firefox: 60.5.2esr, 60.6.1esr
 * Version (or revision) of Tree Style Tab: nothing

**Comment by piroor** [comment]
Recently I've updated the FAQ and added some information about how to check currently supported version: https://github.com/piroor/treestyletab/blob/master/README.md#release-builds Now ESR60 is not supported, and you need to use TST 2.7.x instead of recent versions. See also #2260.

**Comment by ploth** [comment]
Thank you.
Lazy: The addon for ESR can be found [here](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/versions/)
