### ISSUE TITLE
restoring tabs after crash (again)

### ISSUE THREAD

**Issue by stapuft** [piroor/treestyletab#2268]
## Short description
I leave my computer on pretty much all the time. while I slept Firefox crashed. I use the dialog box to send a report to mozilla, and restart/restore my session to be greeted by this
![image](https://user-images.githubusercontent.com/46431157/57395662-afcd2100-7196-11e9-9c31-06f51d1ba827.png)
my tab list is missing tabs (I had over 110 before I went to sleep) the order is messed to hell and back, and the pinned tabs at the top are all in the same exact place. also the "restoring" process happened one tab at a time and I saw it happen, it took about 5 minutes to restore to the point where I took a screenshot.

## Steps to reproduce

no fucking clue, I've tried many times now, as referenced by my other reports, but I cannot manage to recreate it it happens on its own when it wants to.
 66.0.4
 * Version (or revision) of Tree Style Tab:  3.0.11

I have no idea why this is only showing half of my report......i guess I fubared the editing of the post? I dont know?????

**Comment by stapuft** [comment]
## Short description
I leave my computer on pretty much all the time. while I slept Firefox crashed. I use the dialog box to send a report to mozilla, and restart/restore my session to be greeted by this
![image](https://user-images.githubusercontent.com/46431157/57395662-afcd2100-7196-11e9-9c31-06f51d1ba827.png)
my tab list is missing tabs (I had over 110 before I went to sleep) the order is messed to hell and back, and the pinned tabs at the top are all in the same exact place. also the "restoring" process happened one tab at a time and I saw it happen, it took about 5 minutes to restore to the point where I took a screenshot.

## Steps to reproduce


no fucking clue, I've tried many times now, as referenced by my other reports, but I cannot manage to recreate it it happens on its own when it wants to.


## Expected result
tree structure is restored normally (screenshot taken after I manually restored the trees order.)
![image](https://user-images.githubusercontent.com/46431157/57396148-ba3bea80-7197-11e9-985e-feeac5ac58a2.png)


## Actual result
tree structure is destroyed by bugs. (before I manually sorted the tree order.)
![image](https://user-images.githubusercontent.com/46431157/57396043-7ea12080-7197-11e9-9a15-834a728d6fa8.png)


## Environment

 * Platform (OS): windows 10  17763.45
 * Version of Firefox:  66.0.4
 * Version (or revision) of Tree Style Tab:  3.0.11

**Comment by irvinm** [comment]
@stapuft in the case where you see this, I have 2 suggestions:

1. When it occurs, click on one of the TST group tabs and see if that tab is showing the proper tabs under it ... even if those tabs are being displayed outside of the "collapsed" tree.  (I think they might be)
2. Expand and collapse each "group tab" to see if the tree corrects itself.  I have seen this situation in the past and I believe piroor has been working with someone with a related situation to be fixed in a future build.

**Comment by irvinm** [comment]
@stapuft any updates?

**Comment by irvinm** [comment]
@piroor maybe close and mark "expired"?  No updates since May.

**Comment by piroor** [comment]
Sorry but there are not enough information to debug. Moreover, too frequently crash of Firefox is clearly unexpected, and I cannot guarantee TST's stable behavior especially on such fragile environment...

**Comment by irvinm** [comment]
@piroor will you close this one?

**Comment by piroor** [comment]
I think there looks to be nothing can be done for this problem from addons-side... So I close this.
