### ISSUE TITLE
Code snippet "Show title of unread tabs in italic" stopped working

### ISSUE THREAD

**Issue by the-trooper0000** [piroor/treestyletab#2269]
## Short description

Up until recent Firefox update everything worked fine, yesterday I updated to 66.0.5 and code for unread tabs stopped working.

This is what I have entered:
/* Show title of unread tabs with red and italic font */
.tab.unread .label-content {
  color: red !important;
  font-style: italic !important;
}
*/

## Environment

 * Platform (OS): Win10
 * Version of Firefox:  66.0.5
 * Version (or revision) of Tree Style Tab: 3.0.11

EDIT: installed this extension which somehow fixed it, so... solved?
https://addons.mozilla.org/en-US/firefox/addon/tab-flag/

**Comment by irvinm** [comment]
I pasted this into my TST CSS and red italic unread tab titles. (Same environment as you)

> .tab.unread .label-content {
color: red !important;
font-style: italic !important;
}

**Comment by stapuft** [comment]
![image](https://user-images.githubusercontent.com/46431157/57484183-648a3f80-7276-11e9-917a-66b99101876a.png)
same environment, works for me

**Comment by piroor** [comment]
I've tried the snippet and it works as expected for me. There may be something more triggers of the problem.

**Comment by irvinm** [comment]
@the-trooper0000 it looks like the snippet is working.  Can you make sure to try the snippet without any other CSS as a test to see if it works for you?

**Comment by irvinm** [comment]
@the-trooper0000 any updates?

**Comment by irvinm** [comment]
@piroor I think we can close this one.

**Comment by piroor** [comment]
I close this for now because there is no further information.
