### ISSUE TITLE
whenever i restart firefox the tabs are messed up

### ISSUE THREAD

**Issue by mausalimi** [piroor/treestyletab#227]
hi,

as in the title mentioned. after closing/restarting firefox my tabs are usually not in the same order anymore.

sometimes theree is only one ore two wrongly placed, sometimes a lot more.

- windows 7
- firefox 12.0a2
- tst 0.14.2012012901

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
