### ISSUE TITLE
Erratic css display

### ISSUE THREAD

**Issue by nollinvoyd** [piroor/treestyletab#2271]
In the following image, the light tan background (loaded tab), dark tan background (unloaded tab) and yellow tab (active tab) display correctly, but the tabs with the grey background are unloaded tabs.  You can identify them by the blue font color.  They should have dark tan backgrounds.  Out of the several hundred tabs in this session, a good portion of them have grey backgrounds.

They must be individually reloaded to become the proper color, but if the browser is restarted the behavior can randomly repeat all over again.  There is no identifiable pattern of which particular tabs will become grey.  

![tst](https://user-images.githubusercontent.com/20844322/56868981-bc8b9100-69ae-11e9-8cf4-fd36eea3e092.png)

TST menu image from fresh profile:

![TST](https://user-images.githubusercontent.com/20844322/57475826-047da400-724a-11e9-915d-1a47f32cc6ca.png)

My css:

```
/* Add private browsing indicator per tab */
/*
.tab.private-browsing .label:before {
  content: "??";
}
*/

/* Less visible tab dividers. 
   A black border with a very low alpha slightly darkens any color. */
.tab {
  border: solid 1.0px #000000; 
}

/* As little space before the tab name as possible.
   The fold/unfold icon is not affected. */
.tab:not(.pinned) {
  padding-left: 0px !important; /* !important is required when there are enough tabs to cause a scrollbar */
}

/* Change styling of pending (unloaded) tabs */
.tab.discarded {
  opacity: 0.75;
}

.tab.discarded .label-content {
  color: blue;
}

/* Change tab height */
.tab {
  height: 25px;
}

/* Highlight active tab */
.tab.active {
  height: 39px !important;
  background-color: #ffff80;
}
.tab.active .label {
  font-weight: bold;
  font-size: 14px;
}
.tab.active .twisty,
.tab.active .label,
.tab.active .counter {
  color: red;
}

/* Hovered tab */
.tab:hover {
  background: #EBF10B !important;
  opacity: 1;
}

/* Background color or read tabs */
/* To change the background color of read tabs that are unfocused the following should work: */

.tab:not(.unread):not(.active) {
  background: #FFCC99;
}

/* Tab numbering and counting */
/* All of the options in this section need the raw count of tabs available. This is done using CSS counters: */

#tabbar {
  counter-reset: vtabs atabs tabs;
  /* vtabs tracks visible tabs, atabs tracks active tabs, tabs tracks all tabs */
}
.tab:not(.collapsed):not(.discarded) {
  counter-increment: vtabs atabs tabs;
}
.tab:not(.collapsed) {
  counter-increment: vtabs tabs;
}
.tab:not(.discarded) {
  counter-increment: atabs tabs;
}
.tab {
  counter-increment: tabs;
}

/* Numbering of tabs #1601 */
/* Note: this requires the counting CSS block listed here. */
/*This displays the number of each visible tab along side each tab. */

/* Numbereed Tabs */

.tab .extra-items-container {
  z-index: unset !important;
}
.tab .extra-items-container::after {
  background: Highlight;
  color: HighlightText;
  content: counter(vtabs);
  font-size: x-small;
  right: 0.2em;
  padding: 0.2em;
  pointer-events: none;
  position: absolute;
  bottom: 0.2em;

  z-index: 1000;
}

/* Put closebox left side, even if I choose "Left side" style */
:root.left .tab .twisty {
  order: 10000;
}
:root.left .tab .closebox {
  order: -1;
}

/* Change close button style */
.closebox::after { content: "U+2716";

  background: none;
  line-height: 1;
  mask: none;
  text-align: center;
  width: 1.25em;
}

.tab:not(:hover) .closebox {
  display: none;
}
```

Tab numbering and counting

All of the options in this section need the raw count of tabs available. This is done using CSS counters:

```
#tabbar {
  counter-reset: vtabs atabs tabs;
  /* vtabs tracks visible tabs, atabs tracks active tabs, tabs tracks all tabs */
}
.tab:not(.collapsed):not(.discarded) {
  counter-increment: vtabs atabs tabs;
}
.tab:not(.collapsed) {
  counter-increment: vtabs tabs;
}
.tab:not(.discarded) {
  counter-increment: atabs tabs;
}
.tab {
  counter-increment: tabs;
}

Numbering of tabs #1601, #2220

    Note: this requires the counting CSS block listed here.

This displays the number of each visible tab along side each tab.

.tab .extra-items-container {
  z-index: unset !important;
}
.tab .extra-items-container::after {
  background: Highlight;
  color: HighlightText;
  content: counter(vtabs);
  font-size: x-small;
  right: 0.2em;
  padding: 0.2em;
  pointer-events: none;
  position: absolute;
  bottom: 0.2em;

  z-index: 1000;
}
```

 * Platform (OS):  Windows to por
 * Version of Firefox:  670b18
 * Version (or revision) of Tree Style Tab: 3.0.11

**Comment by piroor** [comment]
Only following three sections look to affect to the color of tabs on this case:

```css
 .tab.discarded {
opacity: 0.75;
}

.tab.discarded .label-content {
color: blue;
}

.tab:not(.unread):not(.active) {
background: #FFCC99;
}
```

The tan color is applied only to "not active, already read"  tabs. Gray background and blue text tabs are detected as "not active, unread, discarded (unloaded)". TST tries to restore last "unread" status of tabs, but the status can be changed by reloadings or other triggers. I think this is the reason why background color of tabs are unstable on your environment.

**Comment by piroor** [comment]
So, the real topic of this issue looks: unstable "unread" status of tabs around restarting of Firefox and restoring/discarding of tabs. Is this summary correct?

**Comment by nollinvoyd** [comment]
I suppose the term "unstable" could be used.  The behavior is erratic.  All the tabs with the blue fonts are inactive and unread.  If I select a grey tab, it becomes the correct tan color.  

I don't know how the greying out is initiated, but I never know what's the affect restoring a previous session will do.  If I were to go and activate all the grey tabs, turn them tan, and then restore a previous session, I believe the problems would repeat.  

I'm going to test that a little closer to find out, but have you tested my css.  Are you saying you can't duplicate what's happening?  That profile I tested on was clean, so I can't think of anything that would interfere with it, unless it has something to do with the number  of tabs in a session, which is the only variable in the fresh profile.

**Comment by irvinm** [comment]
@nollinvoyd just a shot in the dark, but how are things with FF68 and TST3.1.5?

**Comment by piroor** [comment]
@nollinvoyd  On my environment "unread" state of tabs are correctly restored and "read" tabs never become to "unread" after session restoration. Thus I cannot research anymore why TST's "unread" state of tabs were lost on your environment...

**Comment by irvinm** [comment]
@piroor I think this might be considered "expired".  No updates since May.

**Comment by piroor** [comment]
OK, I close this because there looks to be no progress.
