### ISSUE TITLE
"open all in tabs" group root ends up a sibling of the last tab (instead of top-level)

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#2273]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3.  add a bookmark folder to the bookmark bar with 2 bookmarks: http://example.org/?(1-2)
 4. open 3 homepage tabs and arrange them like this:
     1. home1
        1. home2
           1. home3
 5. "open all in tabs" the bookmark folder

## Expected result

The bookmark folder group root to be top-level

## Actual result

The root is a sibling of home3

## Environment

 * Platform (OS): win7 x64 sp1
 * Version of Firefox: 66.0.5
 * Version (or revision) of Tree Style Tab: 3.0.11

**Comment by piroor** [comment]
Confirmed. This is triggered with TST's builtin behavior "fix tree structure after tabs are moved." On this case, the http://example.org?1 tab is detected as "opened at between a grandchild tab (home3) and a root tab (http://example.org?2), so TST automatically "fixes" the tree structure by attaching the first opened tab as the next sibling of the home3.

**Comment by piroor** [comment]
This should be fixed with the commit 8670645. Thanks!

**Comment by irvinm** [comment]
@bughit this will be in 3.0.12 when it lands.  Can you verify it works for you and close out the item?  (3.0.12 isn't out yet, fyi)

**Comment by irvinm** [comment]
@bughit can you confirm this is fixed and close if appropriate?
