### ISSUE TITLE
Firefox is VERY SLOW with multiple tabs opened, but suspended

### ISSUE THREAD

**Issue by UralZima** [piroor/treestyletab#2274]
I am using Firefox 62 on Ubuntu 18.04 and most of my tabs are always unloaded (auto suspender), loaded tabs usually not more than 10-20. Firefox is very very slow, very slow rendering new tab opening, very slow switching between them...
Disabing TST fixes the issue.

I have about 100-150 unloaded tabs. When there are 5 total tabs, it is working faster, but anyway rendering of animations is very slow.

XUL version was much faster!

We can reopen https://github.com/piroor/treestyletab/issues/1844 this issue and continue, because problem remains!

I am even thinking to switch back to Firefox 52 and use old xul extensions....

**Comment by piroor** [comment]
The latest version of TST doesn't support Firefox 62 anymore, and TST 2.7.x is the last version working with Firefox 62. Between TST 2.7 and TST 3.0 there are some performance improvements with a large restructuring of its internal design. The change is too large sadly I cannot backport it to TST 2.7. Thus I've decided to keep this closed for now.

**Comment by irvinm** [comment]
@UralZima can you retry with a newer version of Firefox to see if you get better performance?  (Maybe in a VM if you don't want to upgrade?)

Like I commented in https://github.com/piroor/treestyletab/issues/1844 I usually have around 1000 tabs and only 20-30 active tabs and have very good performance.  (My environment is different than yours)

Given that piroor isn't supporting your configuration at this point, let's either try it with a newer version of Firefox or close out this issue until you are able to try it.

**Comment by UralZima** [comment]
Really I am using torbrowser, which is based on firefox. And latest version is 60.6.1. (not 62, my mistake)
It seems I need to wait while they will bump to new version of firefox...

**Comment by UralZima** [comment]
My version of TST is 2.8.5 from March 19, 2019, not 2.7.x as you mentioned

**Comment by piroor** [comment]
Yes, Firefox ESR60 was dropped at TST 2.8.6. Currently the TST 2.8.7 is the only one public version of TST 2.8.x, and the last public version for ESR60 is TST 2.7.23.

**Comment by irvinm** [comment]
@piroor I think we need to close this one until tor browser is able to update to a new base version and @UralZima can then retest and reopen the issue if there is still a problem.

**Comment by tbruckmaier** [comment]
I am not sure if this fits here, but I have experienced the very same symptoms: a noticable slow down of firefox and a pretty high cpu usage, with many tabs open though most of them are unloaded. Closing the unloaded tabs seemed to fix the issue.

I think I have backtraced the problem to the favicons, when I hide them via a custom css rule, the problem disappears (at least for now). This is the rule I use:

```css
.tab .favicon .favicon-image {
  display: none;
}
```

I attach two performance profiles, one with favicons (without the css fix) and one without favicons (via the css fix). They both cover around 10 seconds, in this time I did not interact with Firefox at all and no site was loading.
[tst-profile-2274.zip](https://github.com/piroor/treestyletab/files/3192074/tst-profile-2274.zip)

**Comment by irvinm** [comment]
@piroor does the performance profiles help at all understanding if this is a problem or not?

**Comment by piroor** [comment]
@tbruckmaier Thanks, I forgot to see your performance profile. After I loaded them I've realized that CC (cycle collection) is triggered again and again on the case with favicon. It means that something operation around favicon eats RAM uselessly. Did such "unloaded" tabs have throbber animation? If animation effects of TST eat too much RAM on your PC, disabling animation effect may reduce such too frequent CC.

Otherwise, did you (or something addon around auto-unloading of tabs) applies extra appearance for "unloaded" tab's favicon, for example transparency? Such visual effect may also eat more RAM.

**Comment by tbruckmaier** [comment]
@piroor Thanks for your feedback. During the performance profiles, there was no throbber animation active. And i have not used any tab unloading addons. My TTS extra styles are just copied from the wiki, nothing fancy there (i'm attaching the styles at the bottom, including the now disabled favicon "fix"). There might have been an animated favicon though, I am not sure if that could have caused the CC events?

I am also no longer suspecting the favicons to be the reason for the performance issues, I have experienced more or less the same behaviour with my "fix". The performance drop also occurs more or less randomly, and I cannot really backtrace it properly. Normally at startup, firefox is very responsive, and after a while the performance drops. Switching tabs takes several seconds and the CPU usage goes up to 100%. Firefox's performance tab is no help though (if the CPU is at 100%, all tabs and addons are reported as low/medium usage).

To debug this further, I have disabled all addons and enabled them one by one over the time of several days, and I still *think* TTS is causing it. Afterwards, I have enabled all other addons again and used firefox for the last weeks without TTS, and the performance issues were mostly gone. Firefox still hangs sometimes, but mostly I could see another reason (like debugging a javascript intensive page, while the docker container on the same machine was running wild).

So for now, I have just installed the latest version of TTS (3.1.2), I have seen there were some performance-related fixes? So maybe this untrackable issue is gone :)

I will report back as soon as I have openend some tabs again (just 10 right now and firefox is running smoothly!!)

And this is my TTS styles:

```css
/*
.tab .favicon .favicon-image {
  display: none;
}
*/

/* Show title of unread tabs with red and italic font */
.tab.unread .label {
  color: red !important;
  font-style: italic !important;
}

/* Change styling of pending (unloaded) tabs #1363 */
.tab.discarded {
  opacity: 0.75;
}

/* Change tab height #236 */
:root {
  --tab-height: 28px !important;
}
.tab {
  height: var(--tab-height) !important;
}
```

**Comment by UralZima** [comment]
Hi. After I disabled animations, it became faster, but as @tbruckmaier said, just after starting the browser it works faster, than after some hours or days. I use 3-4 opened browsers with different profiles, and I just restart them all periodically, because they became very slow. Even the scroll is going with big delay. Right now I am typing this message and I see big delay between what I type and what I see.

**Comment by tbruckmaier** [comment]
So another follow-up, since I *really* would like to solve this. I have had firefox open now for 2+ hours, and when i was opening several links in new tabs, the lags started (maybe it has something to do with having multiple loading tabs at the same time?). At the time, I had only around 15 tabs open, and the lags stayed even when they were all fully loaded and there was no throbber animation. htop showed firefox using around 50% cpu. I went to the addons page, and disabled them all one by one, including TST. The laginess stayed though *with all addons disabled*. I dont know the firefox internals, but i assume disabling an addons means stopping/killing all of its processes right? Following this assumption, firefox *itself* causes the performance issues (because the lags are still there even with no addons at all).

But on the other hand, I have been using firefox in the past weeks with all other addons enabled except TST, and there were no lags at all. So somehow TST causes the erratic behaviour in firefox?

I have just installed the firefox profiler extension from https://profiler.firefox.com/ and will try to provide a performance profile the next time the lags start. Maybe that will help? Or anyone has other ideas? Maybe there is a bugzilla issue which could be related?

**Comment by piroor** [comment]
@tbruckmaier 

> I dont know the firefox internals, but i assume disabling an addons means stopping/killing all of its processes right? 

Maybe no. I don't know what is the trigger, but sometimes addon process can hang up and it couldn't be killed by disabling of the addon, instead I need to restart Firefox itself.

> I have just installed the firefox profiler extension from https://profiler.firefox.com/ and will try to provide a performance profile the next time the lags start. Maybe that will help? Or anyone has other ideas? Maybe there is a bugzilla issue which could be related?

Thanks, Gecko Profile can analyze deep performance profile inside Firefox itself so it will help more debugging.

**Comment by tbruckmaier** [comment]
@piroor so I managed to record a Firefox profile: https://perfht.ml/2xvUFI7
I hit "record" when Firefox showed the usual laggy behaviour (with only 20 Tabs open, none loading at the beginning). I have clicked on an (unloaded) tab in TST then.

I have included all threads in the performance profile, since I have no idea what we are looking for. Firefox was nearly freezing though, and CPU was at 100%, so I am not sure how useful this profile is. Maybe you can give me a hint which threads are important here?

![image](https://user-images.githubusercontent.com/4941331/60728548-e3cb8500-9f40-11e9-964e-a3b9a4adc1cc.png)

**Comment by tbruckmaier** [comment]
And another one: https://perfht.ml/2LE4ThU
This time with less threads, so I could actually switch some tabs. I have switched between some loaded tabs (including a blank page), then switched to the unloaded tab https://www.sueddeutsche.de/ and waited until it was fully loaded.

**Comment by piroor** [comment]
@tbruckmaier Thank you for uploading very detailed performance profiles. I still cannot understand full of them, but it looks that too frequently communication between the chrome process and the WebExtensions process looks take too much time. Hmm...

**Comment by piroor** [comment]
@tbruckmaier Could you try to copy your Firefox profile to something other platform (Windows or macOS) and run Firefox with the profile? If you don't see any slowing down, it is possibly a platform specific issue.

**Comment by irvinm** [comment]
@tbruckmaier can you also report back if you see the same performance issues with FF68?  I have personally seen a performance improvement with TST, but that could also just be in my head as it wasn't bad before that. If you aren't planning on going to FF68, just ignore this. :)

**Comment by tbruckmaier** [comment]
Hi, @piroor's comment  gave the the right hints: I went through all my settings again, and discovered that I had openGL enabled via `layers.acceleration.force-enabled` (as it was suggested in https://bugzilla.mozilla.org/show_bug.cgi?id=594876#c109 ). After I have disabled it again, the lags are gone. Hooray!

I have been using this setting for quite some time though, and I have not experienced these lags before. Probably some firefox update in the past months caused this? Anyway, I am back to software rendering, but at least without these 100%-CPU spikes, so I will keep it like this for now. Thanks for all your help!

@irvinm do you have the same setting enabled? I will install FF68 as soon as it is available, maybe TST and openGL are possible then at the same time ;)

**Comment by irvinm** [comment]
Interesting.  I just checked and I have `layers.acceleration.force-enabled` = false.  I would have thought that would be set to true.  I have `Use recommended performance settings` checked in my FF settings.

**Comment by irvinm** [comment]
@tbruckmaier doing a little research on the topic, I am guessing my setting isn't "abnormal" in that it just isn't "forced" in my situation.  In my about:config I can see that my `Compositing = WebRender` which is GPU based, but I think for only the 2D rendering.  I am not sure how to tell if it CPU or GPU video rendered when just choosing "Use recommended performance settings".

In either case, do you think you need anything more around TST on this topic or do you want to close it?

**Comment by tbruckmaier** [comment]
@irvinm I think it depends on the hardware. I am on `Compositing = Basic` now. At the bottom of the Graphics block `about:support` you can see the decision log. This is what it looks for me:

![image](https://user-images.githubusercontent.com/4941331/61075551-86d93e80-a41a-11e9-9e7a-d93866e3c65c.png)

Though I am still on FF67, I think in FF68 WebRender is enabled by default on more configurations.

My issue has been solved though, so this can be closed. Thanks again for all your suggestions!

**Comment by irvinm** [comment]
@UralZima do any of the recent comments help you?

**Comment by irvinm** [comment]
@piroor another one that might be considered "expired" ... nothing from the OP since June.

**Comment by piroor** [comment]
I close this because there looks to be no progress. Both Firefox and TST 3.1.8 contain performance improvements, so please open a new issue if you still see performance problems on new versions of TST and Firefox.
