### ISSUE TITLE
Cannot interact with TST sidebar while a tab is being duplicated

### ISSUE THREAD

**Issue by azizLIGHT** [piroor/treestyletab#2277]
## Short description
When a tab is duplicated using right click option, the entire TST sidebar becomes uninteractable until the new duplicated tab is loaded into TST

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open lots of tabs to show the effect (one method is to select "Open All in Tabs" right click option on a bookmark folder with many bookmarks) 
 4. Right click a tab in TST sidebar and select Duplicate Tab

## Expected result
TST sidebar remains interactable while duplicated tab is loaded into TST sidebar

## Actual result
TST sidebar shows throbbing animation and doesn't let user interact with sidebar until the duplicated tab is rendered/loaded into TST sidebar

## Environment

* Platform (OS): Windows 7
* Version of Firefox: Nightly 68.0a1 (2019-05-11) (64-bit)
* Version (or revision) of Tree Style Tab: 3.0.11.9109

## Extra details
* The effect is not noticable with very few tabs, but gets somewhat noticable with lots of tabs, and very noticeable when you have addons installed, depending on addons installed. The effect is also very noticeable if you load multiple tabs, with addons, and select all tabs and duplicate them all.
* TST sidebar is interactable if you duplicate the tab via Firefox tab strip instead.
* Placement of duplicated tab is different between 1) selecting duplicate tab right click option on a tab inside TST sidebar and 2) selecting duplicate tab right click option on a tab from Firefox tab strip. 1) creates new parent 2) creates a child tab

**Comment by irvinm** [comment]
I've never used it before, but I am seeing a similar behavior with only duplicating 1 tab.  (Windows 10, FF 66.0.5, TST 3.0.11)

In addition, it appears that the duplicate tab is not made a child or sibling relative to the original tab.

![9gsXn44q85](https://user-images.githubusercontent.com/979729/58033962-7def7f00-7af3-11e9-8600-581ff690f60a.gif)

**Comment by piroor** [comment]
Related bug of Firefox: [1394376 - Resolve browser.tabs.duplicate() promise right away (before tabs are completely loaded)](https://bugzilla.mozilla.org/show_bug.cgi?id=1394376)

**Comment by irvinm** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1394376 looks like it will land in Firefox 68!  (July 9, 2019)

**Comment by piroor** [comment]
Now the blocking screen effect for duplicating tabs is disabled on Firefox 68 and later, because duplicating of tabs became enough fast.

**Comment by azizLIGHT** [comment]
Looks fixed to me on FF 69.0a1 (2019-05-30) (64-bit) and TST 3.0.15 
![nightly-TST1-interactable-sidebar](https://user-images.githubusercontent.com/8013867/58638307-2d4f0180-82fd-11e9-9ce1-78b4a9d9a95a.gif)
However the duplicate tab's placement is inconsistent as @irvinm noticed. I will submit another issue soon
