### ISSUE TITLE
When on the parent tab of a collapsed tree, opening new tab (Ctrl-T) does not switch to new tab

### ISSUE THREAD

**Issue by iamLoi** [piroor/treestyletab#2280]
Latest FF and latest version of TST.

To reproduce this issue, create a tree of tabs, collapse the tree, then from the parent tab, click Control-T to open a new tab. The new tab is created, but the expected result is to be automatically switched to the new tab, but the observed behavior is that user remain within the original tab. This is a bug. 

If the tree is expanded first, then new tab will get switched automatically on creation, which is correct and expected.

**Comment by piroor** [comment]
I couldn't reproduce this. My environment:

* Windows 10
* Firefox 66.0.5 64bit (build ID: 20190507012018)
* TST 3.0.11
* clean profile, no other addon

Please fill the issue template https://raw.githubusercontent.com/piroor/treestyletab/master/ISSUE_TEMPLATE.md and describe complete steps to reproduce the problem with a clean profile.

**Comment by iamLoi** [comment]
Hmm, on closer look, I think it's one of my custom CSS that is the culprit but I haven't figured out which yet. Sorry, I will close this.
