### ISSUE TITLE
display is wrong after disabling treestyletab

### ISSUE THREAD

**Issue by rlramsey** [piroor/treestyletab#2283]
After I disable treestyletabs, FF returns to horizontal tabs, but as soon as there is more than 1 line of tabs, the tabs appear as if treestyle tabs is still in use.  

## Steps to reproduce

 1. Upgrade from FF 66 to 67.
 2. Close FF and restart.
 3. Add Treestyltab.
 4. Make some tabs.  TST works as advertised.
 5. Close FF and restart.
 6. Under Add-ons, disable TST.
 7. Close FF and restart.
 8. Open some tabs, enough so that there is more than 1 row of tabs. (ctrl + t and blank tabs or go to different sites)

## Expected result
I would expect disabling or removing TST to put things back the way they were.

## Actual result
The bottom row of tabs is not visible.  Only the current tab in the bottom row is visible.  Other tabs in the bottom row are hidden.

![image](https://user-images.githubusercontent.com/9300043/58107471-87d6b800-7baf-11e9-8260-72313259f89c.png)

There is a narrow space between the address bar and the tabs that are visible.  If you click in this narrow space FF will switch to that tab.  The narrow space is highlighted in red in this screenshot.  In reality it looks like part of the address bar.  I only discovered it was there by clicking around to find the other tabs.

![image](https://user-images.githubusercontent.com/9300043/58109014-6d520e00-7bb2-11e9-8d1a-88bb7550a5aa.png)

So it looks like the last line of tabs is there, just hidden behind the address bar.  And it is only the last line.  If FF thinks it should show 5 rows of tabs, you only see 4 rows and the 5th is hidden.  iff you keep hitting ctrl+t until there should be 10 rows showing, you can only see 9 and the 10th row is hidden.  I haven't looked in my userChrome, but it's almost like there's a css statement (made up class because I don't know it):

```
.horizontal-tab-row:nth-child(last) {
  z-order: -100;
}
```

## Environment

 * Platform (OS):  Windows 10, build 1809, Version 10.0.17763.503
 * Version of Firefox: 67.0 64 bit
 * Version (or revision) of Tree Style Tab: 3.0.11 May 19, 2019

**Comment by piroor** [comment]
Do you use any userChrome.css code? Then removing it may solve the problem.

**Comment by stapuft** [comment]
it sounds like you used the chrome.css code for multiple tab rows, as normally Firefox only has 1 row of tabs.
try looking in your userchrome.css file for code like this
https://superuser.com/questions/1351717/multi-row-tab-bar-in-firefox-quantum
or this
https://www.reddit.com/r/firefox/comments/alkqot/firefox_65_breaks_custom_multirow_tabs/

and remove said code, your firefox should then go back to only having one row of tabs, after you restart firefox.

**Comment by rlramsey** [comment]
Yes, I wiped out my userChrome.css and set FF back to the default.  It was just interesting that it was wrong only after installing and then removing/disabling TST.  And I could duplicate the problem by installing and then removing/disabling TST.  So even though TST doesn't change the css on the tabs, removing it changed the css.

**Comment by piroor** [comment]
Anyway current version TST is WebExtensions API based and enclosed inside the sidebar. It is impossible to affect outside of the sidebar area, especially the native tab bar. So I think that this is not a problem of TST itself.

**Comment by irvinm** [comment]
@piroor I think we can close this one.

**Comment by piroor** [comment]
I close this for now because there is no further information.
