### ISSUE TITLE
[feature request] Set a limit for the number of pinned tabs assigned to a row

### ISSUE THREAD

**Issue by bshafer** [piroor/treestyletab#2284]
## Short description

I am using a modification of "Full Auto-show/hide Theme" found on the "Code snippets for custom style rules" page. I have over 500 tabs, and 16 of them are pinned. I want the 16 pinned tabs to remain in their 4x4 square, even when the sidebar is expanded to avoid having all the tabs move up two rows every time I go to click on one. If there is a way to do that as another css snippet, that would be fine, I just can't figure it out. If I could set a limit (either by number of tabs or by pixel size) on how far over the pinned tabs can extend, that would solve my problem.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Move userChrome.txt (attached) into the chrome directory (create if needed) and change extension to .css
 4. Restart Firefox so that userChrome.css is loaded (alternatively, it might be possible to inject the css using debugging tools)
 4. Add code from "Tree Style Tabs Style.txt" (attached) to the "Extra style rules for sidebar contents" section of TST
 5. Load up a bunch of tabs, and pin 16 of them
 6. Try to select a tab

## Expected result

The tab that I want to click on (pinned or normal) should stay put as the sidebar expands.

## Actual result

The tab that I want to click on moves out from under my mouse as I click on it.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 67.0
 * Version (or revision) of Tree Style Tab: 3.0.11

[userChrome.txt](https://github.com/piroor/treestyletab/files/3208983/userChrome.txt)
[Tree Style Tabs Style.txt](https://github.com/piroor/treestyletab/files/3208984/Tree.Style.Tabs.Style.txt)

**Comment by piroor** [comment]
Done with the commit 036debb.
