### ISSUE TITLE
SSL_ERROR_HANDSHAKE_FAILURE_ALERT with TST on

### ISSUE THREAD

**Issue by ivoshm** [piroor/treestyletab#2285]
## Short description

On specific website secured by TLS (and user client certificate) Firefox returns SSL_ERROR_HANDSHAKE_FAILURE_ALERT error with TST turned on.

If I disable TST in browser than the site is normally accessible.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Try to connect to this specific site (unfortunately my is non-public, I try to find similar public one)
 
## Expected result

Connect to site (and think about security concerns of this situation :) ).

## Actual result

SSL_ERROR_HANDSHAKE_FAILURE_ALERT

## Environment

 * Platform (OS): Manjaro Linux
 * Version of Firefox: 67.0
 * Version (or revision) of Tree Style Tab: 3.0.11

Thanks for this great and addictive add-on and for solving this issue too.

**Comment by piroor** [comment]
Could you add the URL of the website? If it is not a public website, please email it to me.

**Comment by ivoshm** [comment]
Two messages (like in fairytail :smile: ):
- bad one - "my" site needs client certificate to simulate the problem and I have no way to provide it;
- good one - new version of TST (3.0.14) solved this problem.
