### ISSUE TITLE
TST information disclosure vulnerability

### ISSUE THREAD

**Issue by nollinvoyd** [piroor/treestyletab#2288]
Tree Style Tab 3.0.13, Windows 10 Pro, Firefox 67

Ive updated TST and multiple Tab Handler.  

I'd appreciate a more complete explanation of what we might or should be concerned about.  You message on the addon page about the issue was confusing.

**Comment by piroor** [comment]
# Range of leaked data

Both old TST (3.0.11 and older) and MTH (3.0.6 and older) violated the security model of WebExtensions API. They unintentionally exposed some sensitive tab data to other addons via their API even if the caller don't have permissions. Here is the list of possibly leaked data:

* `title`, `url`, and `favIconUrl` of `tabs.Tab` objects (in principle `tabs` or `activeTab` permission is required)
   - Especially, some web services may put session IDs or privacy data in the URL.
* `cookieStoreId`  of `tabs.Tab` objects (in principle `cookies` permission is required)
   - It looks not critical, but a fact that you are using the "container" feature was exposed.
* `tabs.Tab` objects from private windows (you need to allow to access them for each addon on Firefox 67 and later)

Firefox sometimes shows security alert, for example a list of required permissions when an addon is going to be installed, and a confirmation at the first time when a tab is hidden by an addon.

On the other hand, TST and MTH didn't implement such alerts, so those information might be leaked silently.

# Why the incident happened

I completely forgot the important point: API provider addons and client addons may have different permissions.

# Status of provision

Please update to TST 3.0.12 and MTH 3.0.7 (and newer versions). They don't expose them silently in API responses anymore.

**Comment by piroor** [comment]
# 概要

古いバージョンのTST（3.0.11以前）およびMTH（3.0.6以前）で、WebExtensions APIのセキュリティモデルに反した動作がありました。これらのバージョンでは、他のアドオン向けのAPIを通じて、本来であればそれらを取得する権限が無いはずのアドオンに対して、個人情報に関わりうるタブの情報が露出していました。

もし「攻撃者」となるアドオンをインストールしていた場合、それらのデータが読み出され、そのアドオンの権限で使用されていた可能性があります。現在の所、そのような「攻撃者」にあたるアドオンの存在は確認されていません。

# 漏洩したデータの範囲

* [`tabs.Tab`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab)オブジェクトの`title`, `url`, `favIconUrl` （本来であれば、取得には `tabs` または `activeTab` の権限が必要です）
   - URLの中にセッションIDやその他のプライバシー情報を含めているWebサービスがあり得ます。
* [`tabs.Tab`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab)オブジェクトの`cookieStoreId`（本来であれば、取得には `cookies` の権限が必要です）
   - それ自体は致命的な情報ではありませんが、Firefoxで「コンテナー」を使用しているという事実を検知できます。
* プライベートウィンドウ由来の[`tabs.Tab`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab)オブジェクト（Firefox 67以降のバージョンでは、本来であればユーザー自身が明示的に許可したアドオンのみが取得できる情報です）

Firefox自身はアドオンに関してセキュリティの警告を表示する場合があります。具体的には、インストール時に要求されている権限の一覧を表示したり、タブが初めて非表示に切り替えられようとしたりした場合などに警告と確認が行われます。

それに対し、TSTとMTHはそのような警告の仕組みを持っていなかったため、「攻撃者」のアドオンに対して全く無警告に情報が渡されていた可能性があります。

# この事象が発生した原因

APIを提供するアドオンとAPIを呼び出すアドオンの双方で許可されている権限に差がある場合があるという事を、完全に失念していました。

# 対応の状況

TST 3.0.12およびMTH 3.0.7以降のバージョンに更新してください。これらのバージョンでは、前述の情報が無警告に他のアドオンに渡される事はありません。

**Comment by nollinvoyd** [comment]
So this is a hypothetical based on the possible existence of yet unknown "attacker" addons?

This is a little over my head technically.  When you say a tab is hidden, please explain.  Is this the type of thing that is only relevant to private window security?

**Comment by piroor** [comment]
> So this is a hypothetical based on the possible existence/creation of yet unknown "attacker" addons?

Yes. I didn't receive any report about such an attacker addon yet.

> Is this the type of thing that is only relevant to private window security?

Not only on private windows.

* Tabs in non-private (regular) windows
  * Expected (and current) behavior: only safe information is disclosed to other addons.
  * Actual behavior on old versions: full information was disclosed regardless the attacker addon had no `tabs`, `activeTab`, and `cookies` permission.
* Tabs in private windows:
  * Expected (and current) behavior: tabs are completely inaccessible from other addons which is not allowed to access private windows. And, even if it is allowed, only safe information is disclosed to other addons.
  * Actual behavior on old versions: full information was disclosed regardless the attacker addon had no `tabs`, `activeTab`, and special permission for private windows.

**Comment by piroor** [comment]
I think I need to research all existing known WebExtensions addons registered on addons.mozilla.org at least, to make actual damage on regular usecase clear. But I don't know how to do that...

**Comment by irvinm** [comment]
@nollinvoyd is this sufficient?  If so, can you close this item?

**Comment by nollinvoyd** [comment]
I see that you addressed the data disclosure problem issue in the latest version.  I am not qualified to analyze the changes, but if you are satisfied with the current state of TST, so am I.  Thanks
