### ISSUE TITLE
addon bar disappears when customizing toolbars

### ISSUE THREAD

**Issue by zekeblue** [piroor/treestyletab#229]
Running Win 7 x64, Fx 10.0, TST 0.14.2012012901.  Right click toolbar => customize.  Addon bar (status bar) disappears - as does all-in-one sidebar.  Tabs now do something different when customizing.  They used to shift to the top.  They now fill the entire window (not a problem, just maybe part of symptom) - see screen shots.  

Disabling TST fixes problem.  Have tried with All-in-one toolbar disabled also with toobar buttons addon disabled.

When I exit customize, toolbars return.

Normal mode - note toolbar at bottom and right:
http://img832.imageshack.us/img832/9760/normall.png

Customize mode - toolbars disappear:
http://img838.imageshack.us/img838/3041/problembu.png

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
