### ISSUE TITLE
[Feature Request] Option to disable rendering tabs inside Group Tab

### ISSUE THREAD

**Issue by azizLIGHT** [piroor/treestyletab#2290]
## Short description
When tabs are auto-grouped together, the group tab page shows an overview of what tabs are grouped under it. I believe it should be optional because:
1) it is hard to understand/follow tree structure because of the horizontal scrolling nature of it. Vertical information is being displayed horizontally, and it is hard to keep track of which tab is under which parent if you span many columns.
2) people can just look at the TST sidebar to see the same information
3) people can use the mouseover tooltip to also gain the same information
3) performance could be improved by disabling this

By default, TST should show the overview page, but the option should be available to disable it for those who want it.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. enable option to auto-group tabs

## Expected result
To be clear, the auto-grouping tab overview page should exist, and be interact-able as before (change group tab name, and change options check boxes), just without the list of tabs under it. Example:
![image](https://user-images.githubusercontent.com/8013867/58372153-526cfa00-7f22-11e9-8d06-6105ee9b0306.png)

**Comment by piroor** [comment]
This option has been implemented with the commit e232979.
