### ISSUE TITLE
Right-click on sidebar outside of tabs doesn't open context menu

### ISSUE THREAD

**Issue by personalmountains** [piroor/treestyletab#2291]
This is on 3.0.14 and I noticed it first yesterday. Right clicking a tab shows the context menu, but right clicking on the empty space in the sidebar doesn't do anything. I'm also seeing `TypeError: message.tab is null` in the console, at `tab-context-menu.js:436:62` on right clicks.

**Comment by piroor** [comment]
Thanks. The commit 819ad9c should fix this.
