### ISSUE TITLE
firefox起動毎にツリー型タブのページが表示されて困ってます。

### ISSUE THREAD

**Issue by nirvana358888** [piroor/treestyletab#2292]
firefox67.0を利用しています。
そしてfirefoxを起動するたび下記の画面が表示されます。表示させなくさせることは可能ですか？

ツリー型タブ 3.0.14

ツリー型タブの縦型タブバーは切り替え可能なサイドバーパネルの一つになっています。もし表示されていない場合は、 「F1」キー を押すかツールバー上の「 ツリー型タブ 」ボタンをクリックして「ツリー型タブ」サイドバーパネルを表示して下さい。

​ TST自体を拡張する他のアドオン を組み合わせると、TSTのサイドバーにさらに機能を追加する事ができます。

⚠以下の機能には追加の権限が必要です。機能を使いたい場合のみ権限を付与して下さい。

コンテキストメニューの「このツリーをブックマーク」（ブックマークの操作の許可が必要）

キーボードショートカットでのタブ切り替え中は、折り畳まれた子孫タブにはフォーカスせず、折り畳まれたツリーも展開しない（キー操作の検出のためにWebページ内でのスクリプトの実行許可が必要）

**Comment by piroor** [comment]
通常、この画面は初回起動時や何か機能面で変更があった時にだけ表示するようになっています。具体的には、最後に表示した時の通知のバージョンを設定値として保持して、次回の読み込み時にその設定値と最新の通知のバージョンに違いがあったらタブを開くということをしています。
なので、「最後に表示した通知のバージョン」の情報を保存できなかったり、あるいは保存された設定値を読み出せなかったりすると、毎回初期設定に戻ってしまったのと同じ事になって、その都度通知が表示されるという事が起こります。
上記のプロセスのどこかに影響しそうなFirefoxのカスタマイズを行っていないか、何か心当たりはありませんか？
（例えば、今のアドオンの設定値はIndexedDBで保存されているので、IndexedDBが無効化されていると設定の永続的な保存が行われなくなってこういう現象が起こる気がします。）

**Comment by nirvana358888** [comment]
素早い返信ありがとうございます。
おっしゃる通りIndexedDBの無効化がおそらく原因だったようです。

about:profiles　より使用中のプロファイルのルートディレクトリを開き
Firefoxを終了し，storageフォルダを削除する。
この工程を行うことで問題解決しました。

**Comment by piroor** [comment]
解決して良かったです。
一旦closeします。
