### ISSUE TITLE
Active tab scrolls to the top when last opened background child tab is overflowing 

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#2293]
## Short description
I try to open a bunch of child tabs from a single page (e.g. a forum list) and read them later.
If the last opened background child tab causes an overflow, i.e. opens below the bottom visible tab, the active tab scroll upwards, tab by tab, until it reaches the top of the tab bar area.

I believe there are cases which this is useful. But is there an option, or a workaround, to prevent this scrolling completely? Thanks.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST 3.0.14 or 3.0.14.9228.
 3. Open a few root tabs. E.g.:
```
A
B
C (Selected; a page that has a link to click, e.g. https://www.example.com/)
D
E
```
![image](https://user-images.githubusercontent.com/771216/58470764-fb129800-8174-11e9-83f0-8769f3062299.png)

 4. At tab C, middle click a link so a background tab is opened as a child.
5. Repeat step 4 until child tabs are overflowing. E.g.:
```
A
B
C (selected)
├C1
├C2
├ ⋮
└Cn
---- (↓ out of visible area) ----
D
E
```

## Expected result
Visible tabs position does not alter, e.g. 
```
A
B
C (selected)
├C1 (all these child tabs unread)
├C2
├ ⋮
├Cn
---- (↓ out of visible area) ----
├Cn+1
└Cn+2
D
E
```
![image](https://user-images.githubusercontent.com/771216/58470675-c7d00900-8174-11e9-9b21-9486b126b894.png)

## Actual result
Tab C starts scrolling up. Eventually it reaches to the top and stops:
```
---- (↓ out of visible area) ----
A
B
---- (↑ out of visible area) -- (↓ visible tabs) ----
C (selected)
├C1 (all these child tabs unread)
├C2
├ ⋮
├Cm
---- (↓ out of visible area) ----
├Cm+1
└Cm+2
D
E
```
![image](https://user-images.githubusercontent.com/771216/58470636-ad962b00-8174-11e9-8420-91e4dbab4d31.png)

## Additional Notes
The issue happens no matter how deeply nested the currently selected parent tab is. It, rather than the root tab, scrolls to the top only when its own child tabs are overflowing.

## Environment

 * Platform (OS): Win10 1809
 * Version of Firefox: Nightly 2019-05-27 20190527215312
 * Version (or revision) of Tree Style Tab: 3.0.14 or 3.0.14.9228

**Comment by piroor** [comment]
This behavior respects  the one on the Firefox's native tab bar.
https://searchfox.org/mozilla-central/rev/ddb81c7a43ffada1f6cb4200c4f625e50e44dcf3/browser/base/content/tabbrowser.xml#927

I have a decision policy about triaging of behaviors on the tab bar: making compatible with the native tab bar if possible, including options. I personally won't deactivate the auto-scroll behavior, but if Firefox provides an option to do that I agree TST also should have it.

Then, Firefox looks to provide no option about this behavior. So, sorry but I won't make it configurable.

**Comment by Fanolian** [comment]
Thank you for the explanation.
