### ISSUE TITLE
Is it possible to show example thumbnail for currently hovered option?

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#2294]
## Short description
I would like to preview the available choices from the dropdown list before actually selecting them. Is it possible to do so? Thanks.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST 3.0.14 or 3.0.14.9228.
 3. Navigate to TST's *Options > New Tabs Behavior*
 4. Click a dropdown list that preview thumbnails are available. (Yellow arrows in the screenshot)
 5. Hover on an option.

![image](https://user-images.githubusercontent.com/771216/58473871-40869380-817c-11e9-810b-a1590691c941.png)

## Expected result
The thumbnail should show the preview of the currently hovered item. (Green arrow)

## Actual result
The thumbnail shows the already selected item until I confirm selection of a new one. (Red arrow)

## Environment

 * Platform (OS): Win10 1809
 * Version of Firefox: Nightly 2019-05-27 20190527215312 
 * Version (or revision) of Tree Style Tab: 3.0.14 or 3.0.14.9228

**Comment by piroor** [comment]
It looks a regression of Firefox itself. Now the event target of `mouseover` is always `select` instead of `option`...

**Comment by piroor** [comment]
I've reported this to bugzilla:

[1555018 - mouse events are not fired on `<option>` in `<select>` when e10s is enabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1555018)

**Comment by Fanolian** [comment]
Closing this issue for now as I don't think Firefox will ever fix it. Also it is only a nice-to-have feature for TST.
