### ISSUE TITLE
Allow TST keyboard shortcut to take precedence over page keyboard shortcut

### ISSUE THREAD

**Issue by theres-waldo** [piroor/treestyletab#2295]
I have configured "Ctrl + E" as a keyboard shortcut in TST to perform "Open in new child tab".

However, some pages react to "Ctrl + E" themselves. For example, bugzilla.mozilla.org uses "Ctrl + E" as a shortcut for "Edit Bug". In such cases, the page action takes preference, and the TST action is not performed.

I really don't care about page actions that happen to use "Ctrl + E" as a shortcut, and would prefer that it always does the TST action. It would be nice to have a way to specify that the TST action should always take precedence.

**Comment by piroor** [comment]
It looks a restriction of WebExtensions API. I've filed a bug: [1555620 - WebExtensions command don't work when the key combination is used by the webpage](https://bugzilla.mozilla.org/show_bug.cgi?id=1555620).
