### ISSUE TITLE
Expanding trees with large number of tabs scrolls the tab list

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2302]
## Short description
Expanding trees larger than the screen area, moves the root of the tree to the top of the tab area.  While I understand how that might be desirable, on large screens (4K screens with lots of area for tabs) moving the root of the tab far away from the point of expanding it isn't ideal.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Create some random smaller trees and verify that when trees are contracted and expanded, the root of the tree does not change locations.

![5FFA29E0-FDF5-4439-9F70-160C4413F5C0](https://user-images.githubusercontent.com/979729/58999783-8fb07200-87d5-11e9-8711-d70fe2961181.GIF)

 4. Create larger trees that have more tabs that may not all fit on the screen and repeat the experiment.  Notice how the root of the tree is moved to the top of the screen.

![023051DD-877D-4B65-BA9A-C0725AF739B4](https://user-images.githubusercontent.com/979729/58999817-b5d61200-87d5-11e9-916f-c5db4d3a660b.GIF)

## Expected result
I would prefer the behavior to be the same regardless of the size of the tree.  I would hope the root of the tree remains in the same location in each situation. (Or have an option to keep the current behavior or leave the tree "anchored" when expanded.)

## Actual result
Root of trees that are too large move when expanded.

## Environment

 * Platform (OS):  Windows 10 x64 (1903)
 * Version of Firefox:  FF 67.0.1
 * Version (or revision) of Tree Style Tab:  3.0.15

**Comment by piroor** [comment]
The current behavior is intentional and respects the behavior on the folder tree of Windows Explorer. Currently it there is no option to disable it, but I've realized that tree UI of Firefox itself (and Thunderbird's folder tree) doesn't work like that. So I've introduced a new secret option `scrollToExpandedTree`. It is `true` by default, and you can deactivate it via `All Configs` list.

**Comment by irvinm** [comment]
This is perfect.  Thank you!
