### ISSUE TITLE
Tab discarded state is not updating

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2304]
## Short description
TST no longer is catching (or storing) tab transitions between active and discarded states.  I believe this started with 3.0.16.  In my CSS I have:

/* --------------------------------------------------------------------- */
/* Change discarded tab opacity */
/* --------------------------------------------------------------------- */
.tab.discarded { opacity: 0.6; }

Tabs that are newly created always stay with opacity 1.0 regardless of active or discarded.  Tabs that were previously discarded, now stay with opacity 0.6 regardless of active or discarded.

## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install Auto Tab Discard.
 4. See new tabs = opacity 1.0 for active and discarded.
 5. See previously discarded tabs = opacity 0.6 for active and discarded.

Example:  Yahoo tab always shows as "active" for entire demo and 2 tabs below that show as "discarded" for the entire demo.
![92B2C664-96A3-48CC-9B2B-4318B8C32A20](https://user-images.githubusercontent.com/979729/59065615-1d926880-887b-11e9-9a6b-aff88e46e409.GIF)

## Expected result
CSS should apply to appropriate tab states. 

## Actual result
Tab opacity no longer changes state.

## Environment

 * Platform (OS):  Windows 10 x64 (1903)
 * Version of Firefox:  FF 67.0.1
 * Version (or revision) of Tree Style Tab:  3.0.16

**Comment by SimonSapin** [comment]
I am seeing something similar in TST 3.0.15: the `discarded` class is not applied to any tab (although many are in fact unloaded).

**Comment by Gotolei** [comment]
Also running into this, just triggered a manual update on an install that was still running 3.0.15 and it does look like whatever broke happened between .15 and .16.

Xubuntu 18.04, Fx 67.0.1

**Comment by suiryc** [comment]
It seems there may be an issue with both `unread` and `discarded` classes in TST 3.0.16.
If I switch to an unloaded or unread tab, the CSS styles applied remain as if the state did not change. Then if I switch to (e.g.) the Bookmarks in the sidebar then goes back to TST (which rebuilds its content) the tab now has the correct style. So maybe the changes in the tabs state are not properly taken into account for those classes ?

After downgrading to TST 3.0.15, there is no issue.

Windows 10 x64 (1903), FF 67.0.1

**Comment by xzn** [comment]
93c9bd80f698111161d64340cbcd7db35eb63442 seems to have fixed the issue for me,

although I'm use Unload Tabs instead Auto Tab Discard

**Comment by Fanolian** [comment]
Fixed for me in 3.0.17.

**Comment by irvinm** [comment]
Fixed for me as well in 3.0.17.  Closing.

**Comment by suiryc** [comment]
Fixed for me too.
