### ISSUE TITLE
Can't scroll tree with mouse wheel

### ISSUE THREAD

**Issue by cebas** [piroor/treestyletab#2310]
With the same setup as in #2309 

After changing to a new group with STG, I can't scroll the tree with mouse wheel.
If I un maximize FF and maximize it again, the scroll work fine again.

**Comment by piroor** [comment]
On your case, "before" and "after" are as below?:

* Before switching tab group:
  - Less tabs, no scrollbar
  - Maximized window
* After switching tab group:
  - Too many tabs, should be scrollable
  - Maximized window

**Comment by cebas** [comment]
This is my case:

I have two groups:
- A with enough tabs to create scroll
- B with some tabs (it doesn't matter how many)

I'm at group A with maximized window
- Scroll working fine

Go to group B
Come back to A

- Scroll not working

If I maximize and unmaximize window or if I collapse and uncollapse some trees on group A, scroll starts to work.

**Comment by irvinm** [comment]
@piroor do you need more information from @cebas?

**Comment by cebas** [comment]
with TST 3.1.5 & STG 4.0.0.1 & FF 68.0.1, I can't reproduce it anymore.
thanks to whom had fixed it!
