### ISSUE TITLE
[Regression] Can't middle-click to open a new tab; conflict with Multiple Tab Handler

### ISSUE THREAD

**Issue by protist** [piroor/treestyletab#2311]
## Short description
I can no longer middle-click in the "non-tab" area to open a new tab. This is caused by a conflict with the add-on "Multiple Tab Handler".

These two add-ons worked fine together before. The recent update to Tree Style Tab 3.1.0 (2019.6.13) caused this issue.

If I disable "Multiple Tab Handler", middle-click works fine again.

## Steps to reproduce
1. Start Firefox with clean profile.
1. Have both "Tree Style Tab" and "Multiple Tab Handler" installed.
2. Middle-click in the "non-tab" area.

## Expected result
A new tab should be created.

## Actual result
Nothing happens.

## Environment

 * Platform (OS): Linux (up-to-date Arch Linux)
 * Version of Firefox: 67.0.2
 * Version (or revision) of Tree Style Tab: 3.1.0 (2019.6.13)
 * Version of Multiple Tab Handler: 3.0.7

**Comment by piroor** [comment]
Thanks! This should be fixed on 3.1.1.

**Comment by protist** [comment]
Brilliant! Thank you for the quick fix and the brilliantness that is TST!
