### ISSUE TITLE
Unable to install add-on in Firefox 67.0.2

### ISSUE THREAD

**Issue by linusr** [piroor/treestyletab#2315]
## Short description
Unable to install add-on in Firefox 67.0.2

## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Go to add on site
 3. Try to install add-on 

## Expected result
Successfully install add on.

## Actual result
This add-on requires a newer version of Firefox (at least version 65.0). You are using Firefox 60.0.

## Environment
 * Platform (OS): OS X 10.14.5
 * Version of Firefox: 67.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: Latest.
<img width="913" alt="Screenshot 2019-06-15 at 9 05 43 PM" src="https://user-images.githubusercontent.com/761644/59551781-54990600-8f6e-11e9-8d38-e4687f90e32c.png">

**Comment by sbr61** [comment]
I have had a similar problem with a different addon. This seems to be a problem on the Mozilla side. Please try again after disabling `privacy.resistFingerprinting` in `about:config`. You should be able to re-enable the setting after installation of the plugin.

**Comment by piroor** [comment]
I couldn't reproduce this problem on my environment. Did you change the user agent string? Or, did you activate tracking protection or something globally?

**Comment by linusr** [comment]
Thanks @sbr61 @piroor , disabling privacy.resistFingerprinting resolved the issue.
