### ISSUE TITLE
Close other tabs leaves group tabs behind

### ISSUE THREAD

**Issue by SammysHP** [piroor/treestyletab#2317]
## Short description
Closing multiple tabs via "close other tabs" from the context menu leaves tab groups behind. 

## Steps to reproduce

- Enable preferences to replace closed parents with a group tab
- Enable preference to close group tab on last child
- Open many tabs with many branches
- Choose a leaf tab, open context menu and select "close other tabs" 

## Expected result
Only a single tab exists. Thus per definition there cannot be a group tab remaining. 

## Actual result
The tab might stay as a single tab in a group tab and there might be additional empty group tabs. 

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 67.0.3
 * Version (or revision) of Tree Style Tab: 3.1.1

**Comment by piroor** [comment]
Thanks. With the commit af085bb, now TST won't try to open group tabs when all children are going to be closed.

If you run something command like "Close Other Tabs"  outside of TST, such tabs still may be opened, but I've introduced a failsafe for such cases. TST will cleanup such needless group tabs when they already lose their children. So I hope that chances to see such tabs should be reduced.

**Comment by SammysHP** [comment]
Seems to work for my use cases. Thank you!
