### ISSUE TITLE
Disabling auto collapse/expand doesn't work sometimes

### ISSUE THREAD

**Issue by Infocatcher** [piroor/treestyletab#232]
Preferences:
extensions.treestyletab.focusMode = 0
(Focus to the next/previous tab even if it is invisible, by Control-Tab)

And <ins>not</ins> checked "When a tab gets focus, expand its tree and collapse others automatically".

Make following tabs structure:
<pre>
[ Parent tab - 1 ]
    [ Child tab - 1 ]
[ Parent tab - 2 ]
    [ Child tab - 2 ]
</pre>
And collapse both trees.
Then navigate through tabs via Ctrl+Tab/Ctrl+PageDown - only one tree will be in expanded state simultaneously.

Illustration ("+" = collapsed," -" = expanded, invisible tabs are hidden):
<pre>
+ [ Parent tab - 1 ] (focused)
+ [ Parent tab - 2 ]
</pre>
Press Ctrl+PageDown
<pre>
- [ Parent tab - 1 ]
      [ Child tab - 1 ] (focused)
+ [ Parent tab - 2 ]
</pre>
Ctrl+PageDown
<pre>
- [ Parent tab - 1 ]
      [ Child tab - 1 ]
+ [ Parent tab - 2 ] (focused)
</pre>
Ctrl+PageDown
<pre>
+ [ Parent tab - 1 ] &lt;- wrongly collapsed
- [ Parent tab - 2 ]
      [ Child tab - 2 ] (focused)
</pre>

P.S. I think, it's better to always show checkbox for extensions.treestyletab.focusMode preference.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
