### ISSUE TITLE
Tab tooltip is misplaced after entering a fullscreen video after bug 1062609

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#2320]
## Short description
After entering and exiting fullscreen of a video, the tooltip when hovering on a tab with a long tab title is no longer placed under the cursor.
The issue is much worse when the sidebar is put on the right side.

## Steps to reproduce

 1. Start Nightly 2019-05-07 build or onwards.
 2. Install TST.
 3. Open a tab containing a video and with a long tab title, e.g. https://www.youtube.com/watch?v=dQw4w9WgXcQ
 4. Hover on the tab on TST tabbar. Tooltip should appear under the cursor.
 5. Enter fullscreen through video control.
 6. Exit fullscreen.
 7. Hover on the tab on TST sidebar again.

## Expected result
Tooltip should appear under the cursor.

## Actual result
Tooltip appears afar from the cursor.
![image](https://user-images.githubusercontent.com/771216/60104831-cf46fa00-9794-11e9-9679-657a56822428.png)

If sidebar is placed on the right, the tooltip usually appears inside the content area.

According to Mozregression:
Last good Nightly: 2019-05-06
First bad Nightly: 2019-05-07
pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=3c70f36ad62c9c714db3199fc00e60800ee82bde&tochange=63bc837753d653ab13635e432400c1b6d31d12ca

Further bisection:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=70b7703b8c13dc87f02693338eef29ea36bb3689&tochange=c705a64ce83c3e320529baf9527e7060ff2c7bcd

This is regressed by [bug 1062609 - Mochitests Are Unable to Read Realtime Scroll Position with APZ enabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1062609).

## Note
1. A standalone video element also exhibits the issue. test link: https://interactive-examples.mdn.mozilla.net/media/examples/flower.webm (but you need another tab with a long enough tab title)
2. Entering a tab fullscreen (F11) does not exhibit the issue. Actually it fixes the problem (see point 3).
3. _**WORKAROUND:**_ Re-activating the TST tabbar, either by closing/re-opening sidebar, disabling/re-enabling TST, switching to another sidebar item and back, F11, etc., will fix the issue.
4. Tooltips from other Nightly's default sidebar items, e.g. Bookmarks, History, are not affected.

## Environment

 * Platform (OS): Win 10 1903 build 18362.175
 * Version of Firefox:  Nightly 2019-06-25 20190625094022
 * Version (or revision) of Tree Style Tab:  TST 3.1.2

**Comment by piroor** [comment]
The placement of the tooltip cannot be controlled by TST, because it is shown by Firefox itself based on element's `title` attribute. So I think it should be tracked at bugzilla.mozilla.org as a bug of Gecko itself.

**Comment by Fanolian** [comment]
I filed [Bug 1561570 - Tooltips for elements in WebExtensions sidebar are misplaced after entering a fullscreen video](https://bugzilla.mozilla.org/show_bug.cgi?id=1561570). Closing this issue as this is a Firefox bug that affects all WebExtension utilizing sidebar in general.

**Comment by piroor** [comment]
Thanks!
