### ISSUE TITLE
[Feature request] Implement the Picture-in-Picture indicator on tabs

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#2322]
## Short description
[Bug 1528459](https://bugzilla.mozilla.org/show_bug.cgi?id=1528459) introduces a Picture-in-Picture (PiP) indicator on tabs. [Bug 1554579](https://bugzilla.mozilla.org/show_bug.cgi?id=1554579) makes the PiP indicator an extra state of the existing audio indicator.
I think TST should implement it. This is a brand new feature. More polishings should be expected and Firefox's implementation may change. However it should not fly under the radar.

The feature is [coming to beta](https://bugzilla.mozilla.org/show_bug.cgi?id=1561298) soon.

## Steps to reproduce

 1. Start Nightly 2019-06-26 build 20190626093633 or later.
 2. Install TST.
 3. Open a video which [qualifies for a PiP toggle](https://searchfox.org/mozilla-central/rev/06bd14ced96f25ff1dbd5352cb985fc0fa12a64e/toolkit/content/widgets/videocontrols.js#94). E.g. https://www.youtube.com/watch?v=dQw4w9WgXcQ
 4. Hover on the video and click the PiP toggle.

## Expected result
Similar to Firefox's native tab bar, audio indicator changes to the PiP indicator. Clicking on it mutes/unmutes the video.

## Actual result
No PiP indicator is shown on the relevant tab.

## Environment

 * Platform (OS): Win10 1903
 * Version of Firefox:  Nightly 2019-06-26 build 20190626093633 
 * Version (or revision) of Tree Style Tab:  3.1.2

**Comment by piroor** [comment]
Is the information exposed to WebExtensions API?

**Comment by irvinm** [comment]
[https://www.ghacks.net/2019/02/18/mozilla-working-on-firefox-picture-in-picture-mode/](url)

"Mozilla won't implement the Picture in Picture WebAPI draft in Firefox at this point in time." (February 2019)

Not sure what this means towards the tab indicator or detection of this feature running.

**Comment by piroor** [comment]
1561809 - Expose picture-in-picture status to WebExtensions API
https://bugzilla.mozilla.org/show_bug.cgi?id=1561809

**Comment by irvinm** [comment]
As I do use PIP as well, my opinion is that while a separate indicator might be a nice to have, playing any video with the PIP feature will still show the "audio playing" icon on the tab.  So unless you have multiple tabs playing audio (unlikely?) then that indicator would make it pretty easy to find the tab that is the source of the PIP.

Again, just my opinion...

**Comment by Fanolian** [comment]
In Firefox's Proton redesign the sound indicator no longer has a PiP state. The state is instead shown as a secondary text in the tab for non-compact densities.
This issue is no longer valid.

**Comment by piroor** [comment]
Thanks, I didn't know that the indication method was changed.
![image](https://user-images.githubusercontent.com/70062/125612763-4d35e8aa-dc3c-4f50-9638-b8fc85c1178a.png)
![image](https://user-images.githubusercontent.com/70062/125612790-a5dac15f-dd02-4db5-937c-8eab4db63bdc.png)
![image](https://user-images.githubusercontent.com/70062/125612821-ee8a49e3-a991-4cb1-aba7-8d12345478cd.png)
Hmm, however it is still impossible to indicate the "picture-in-picture" status because it is not exposed to extensions in any way.
