### ISSUE TITLE
Incorrect new tab favicon

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#2323]
## Short description

The new tab favicon fails to load in the latest version of TST (v3.1.2) but it works as expected in TST v3.1.1.

The problem seems to be the `loader.crossOrigin = 'anonymous';` code on l[ine 291 in `TabFavIconHelper.js`](https://github.com/piroor/webextensions-lib-tab-favicon-helper/blob/master/TabFavIconHelper.js#L291). It causes a security error when loading the favicon url: `chrome://branding/content/icon32.png`.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a new tab (`about:newtab`).

## Expected result
The tab should have the Firefox logo as its icon.

## Actual result
The tab has the default favicon.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox:  67.0.4
 * Version (or revision) of Tree Style Tab: 3.1.2

**Comment by piroor** [comment]
Thanks, this should be fixed with recent commits.
