### ISSUE TITLE
3.1.3 pushed to AMO?

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2325]
It looks like you published 3.1.3 today via https://github.com/piroor/treestyletab/blob/master/history.en.md but it appears AMO still has 3.1.2.  Not sure if a problem or not, but you should be aware.

**Comment by piroor** [comment]
I already uploaded 3.1.3 to AMO and still waiting for review. I think that TST now requires not only automated review but a human review also because it became an officially recommended addon.

**Comment by irvinm** [comment]
Ah!  That makes sense.  Thanks.
