### ISSUE TITLE
privacy.resistFingerprinting causes issues with the high contrast theme

### ISSUE THREAD

**Issue by somasis** [piroor/treestyletab#2326]
## Short description

Tree Style Tab's high contrast theme has loses most of its color when `privacy.resistFingerprinting` is set to `true`. This does not happen when it is `false`, the default.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Apply the "High Contrast" theme.
 4. Set `privacy.resistFingerprinting` to `true`.
 5. Toggle the visibility of the sidebar, or change tabs, or anything to change the appearance of the tab tree.
 6. The appearance matches the actual screenshot.

## Expected result

![20190702_162445](https://user-images.githubusercontent.com/264788/60544102-0150e280-9ce6-11e9-8e7d-7972820219af.png)

## Actual result

![20190702_162454](https://user-images.githubusercontent.com/264788/60544110-057d0000-9ce6-11e9-9e5c-d113155bd628.png)

## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: 67.0.4
 * Version (or revision) of Tree Style Tab: 3.1.2

**Comment by piroor** [comment]
After the commit 44d9a64 tabs are shown with `ThreeDFace` color instead of `Background` (it is a color of the desktop itself). I hope this change make text readable.

**Comment by somasis** [comment]
Using the latest development build, the tabs look fine now, but there's still visual breakage on the background.

![20190703_152458](https://user-images.githubusercontent.com/264788/60619470-4b11f980-9dc8-11e9-9c0e-100abdfd664b.png)

**Comment by piroor** [comment]
After I re-browsed [system color names](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#System_Colors), I've realized that `AppWorkspace` is better than `Background` for the purpose.  How about that?

**Comment by jfdhuiz** [comment]
> Apply the "High Contrast" theme.

Not only the "High Contrast" theme. I can reproduce the behavior on the combination "Mixed" with "Apply browser theme" as well. The problem is with the tabs (the background seems fine).

**Comment by piroor** [comment]
@jfdhuiz Which theme are you using? The "Apply browser theme" option should do nothing for the default theme of Firefox itself.

**Comment by irvinm** [comment]
@somasis can you provide an update?  Is there more to do here or can we close?

**Comment by somasis** [comment]
Sorry for the quiet. Things still don't look exactly right. Firefox 68.0.1, Tree Style Tab 3.1.7.

![20190810_121928](https://user-images.githubusercontent.com/264788/62824249-2b10eb00-bb69-11e9-86bc-e735cd3acad3.png)
![20190810_121942](https://user-images.githubusercontent.com/264788/62824248-2b10eb00-bb69-11e9-8452-fe88fa1b4aff.png)

**Comment by irvinm** [comment]
@somasis or @piroor ... can we close this?

**Comment by somasis** [comment]
Yeah, sorry. It seems like it's fine now.
