### ISSUE TITLE
[feature request] Automatic different color for each tree

### ISSUE THREAD

**Issue by schmurtzm** [piroor/treestyletab#2329]
## **Short description :** 
Color tabs tree when a child tab is opened , I mean that each tree could be colored in a different color : it's very useful to find quickly the different sections of your navigation ! 

## **Expected result :**
(a click on a link opens a new tab in the same color of the current parent tab, the main parent tab is colored only when a child tab is opened).
### Example : 
![Example](https://gitlab.com/kroppy/TreeTabs/uploads/eae7723fea0e2becec70c8ea77956327/tabexample.JPG)
### Second idea/example :
![image](https://user-images.githubusercontent.com/7110113/60767335-f667ca80-a0b6-11e9-8cd5-a039296cabb6.png)

## **Actual result :** 
All tabs have the same color, not easy to distinguish the different sections.
![image](https://user-images.githubusercontent.com/7110113/60766654-1befd680-a0ad-11e9-8250-0791c123890c.png)

## **Environment :**
    Platform (OS): Windows 10
    Version of Firefox: 67.04
    Version (or revision) of Tree Style Tab: 3.1.2

**Comment by schmurtzm** [comment]
For information tst-colored-tabs is a Tree Style Tab extension that allow to color each tab based on current tab domain (but not allow to color each tree of tabs in a different color)
https://addons.mozilla.org/fr/firefox/addon/tst-colored-tabs/

**Comment by piroor** [comment]
Sorry but I have no plan to implement coloring feature of tabs, because it looks too far from basic tree management. Instead something another helper addon like TST Colored Tabs should implement that, via TST's API.

**Comment by schmurtzm** [comment]
Thanks for your answer, you're right so I've made a request on the TST Colored Tabs repo.
By the way thank for this great addon, it brings me back to Firefox :stuck_out_tongue:

**Comment by irvinm** [comment]
@schmurtzm can you close this item?  Thanks.

**Comment by irvinm** [comment]
@piroor I think you can close this one.

**Comment by irvinm** [comment]
@piroor friendly reminder.

**Comment by schmurtzm** [comment]
Issue submitted to tst colored tab (but seems to not find any interlocutor).

https://github.com/MurzNN/TST-Colored-tabs/issues/6

Anyway I close it here.
