### ISSUE TITLE
[Feature request] Option to Close Tabs to the Top

### ISSUE THREAD

**Issue by fncll** [piroor/treestyletab#2330]
I often find myself needing to close tabs to the top of the tree. Having that as an option would be a nice pairing for "Close tabs to the bottom" -- which I believe is a feature of TTT?

**Comment by piroor** [comment]
Close Tabs to the Left
https://addons.mozilla.org/firefox/addon/close-tabs-left/
This should work via the context menu on the sidebar.

Sorry but I'm negative to add top level menu commands to the simulated context menu except features natively provided in Firefox's tab context menu itself.

**Comment by fncll** [comment]
Thanks
