### ISSUE TITLE
[Nightly only] TST is affected by bug 1558914 (Disable Array generics in Nightly)

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#2332]
## Short description
[Bug 1558914 - Disable Array generics in Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1558914)
[Bug 1565832 - Some extensions don't work anymore after landing patches from bug #1558914
](https://bugzilla.mozilla.org/show_bug.cgi?id=1565832)
I don't know the technical details about bug 1558914 but it prohibits me from closing a tree by middle click.

## Steps to reproduce

 1. Start Nightly 2019-07-09 or onwards.
 2. Install TST.
 3. Open a tab as a root. Open another tab and make it a child of the first tab.
 ```
A
\- B
```
 4. Collapse the tree
```
A
\- B (collapsed)
```
 5. Try to close the whole tree by middle-clicking the tree (Tab A).

## Expected result
A prompt shows up and confirms the closing of tabs.

## Actual result
No prompt is shown. Browser Console shows:
```
TypeError: Array.slice is not a function        RichConfirm.js:43:20
```
which should point to

https://github.com/piroor/webextensions-lib-rich-confirm/blob/790fab8e9c1c7d6ba9b3908410c309a25060714e/RichConfirm.js#L42-L44

After this error, TST's context menu does not show but no error messages is given in Browser Console. At this point, switching to another sidebar panel (Bookmarks, History, etc.) reveals an error message:
```
 TypeError: this._resolve is not a function        RichConfirm.js:254:12
    dismiss moz-extension://[TST UUID]/extlib/RichConfirm.js:254
    onUnload moz-extension://[TST UUID]/extlib/RichConfirm.js:418
    onUnload self-hosted:1003
```
Switching back to TST panel and the context menu works again.

## Environment

 * Platform (OS): Windows 10 1903
 * Version of Firefox:  Nightly 2019-07-13 20190713175429
***(Do NOT test on a previous 2019-07-13 20190713095401 build. It has a [data loss bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1565836).)***
 * Version (or revision) of Tree Style Tab:  3.1.5

**Comment by piroor** [comment]
Thanks! I've done changes to remove codes based on Array generics methods on my addons.

**Comment by piroor** [comment]
I think I should close this issue after all affected addons are released.

**Comment by irvinm** [comment]
@piroor has everything been completed here?

**Comment by piroor** [comment]
I've released all related addons, so I close this now.
