### ISSUE TITLE
Close of parent tab preferences not respected with some plugin focus preferences

### ISSUE THREAD

**Issue by InsertUser** [piroor/treestyletab#2333]
## Short description
Using the "Treat as a parent by operations inside the tree sidebar./Treat just as a solo tab, by operations outside the tree sidebar." preference set, the "Replace closed parent with a dummy tab and keep the tree" preference is ignored.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. RMB on TST icon Manage Extension > Options 
 4. Under "When a parent tab is closed with expanded tree" set "Replace closed parent with a dummy tab and keep the tree"
 5. Under "When a parent tab is moved or closed by someone from outside the tree sidebar" select "Treat as a parent by operations inside the tree sidebar./Treat just as a solo tab, by operations outside the tree sidebar."
 6. Go to a link heavy site, open several links in new tabs.
 7. Close tab with CTRL+W
 
 
 

## Expected result

Closed tab should be replaced with placeholder tab.

## Actual result

Closed tab is replaced by first child.

## Environment

 * Platform (OS): Windows 10 1903 build: 18362.239
 * Version of Firefox: 68.0
 * Version (or revision) of Tree Style Tab: 3.1.5

**Comment by piroor** [comment]
This is exactly expected behavior of the option "Treat as a parent by operations inside the tree sidebar./Treat just as a solo tab, by operations outside the tree sidebar." The keyboard shortcut Ctrl-W is tracked by Firefox itself not by TST, so the operation is treated as "happened at outside the sidebar". Instead, if you click the closebox of the tree item in the sidebar, it will be treated as "happend at inside the sidebar".

**Comment by InsertUser** [comment]
I appreciate that a new dummy tab appearing might be counter-intuitive, but could you add an option to set the fallback for this action? To me, both the "promote all children to parent's level" and "liberate children from tree" options make much more sense for an externally closed tab than choosing a somewhat arbitrary successor for the top level.

**Comment by piroor** [comment]
Hmm, I've realized that the UI for these configurations should be redesigned totally...

**Comment by piroor** [comment]
I've implemented new option UI for these behaviors:

![image](https://user-images.githubusercontent.com/70062/61786983-c9067500-ae49-11e9-9c15-e9fdaeda3443.png)
![image](https://user-images.githubusercontent.com/70062/61787028-e2a7bc80-ae49-11e9-9111-a56dd6ac6323.png)
![image](https://user-images.githubusercontent.com/70062/61787064-f9e6aa00-ae49-11e9-81cd-f65bd3ac3311.png)

**Comment by irvinm** [comment]
@InsertUser can you review\comment\close as needed?

**Comment by InsertUser** [comment]
If the third dropdown is for a hidden TST sidebar then I think this covers everything. 

Thanks.

**Comment by piroor** [comment]
@InsertUser Yes, it covers hidden TST sidebar case.
