### ISSUE TITLE
middle click close

### ISSUE THREAD

**Issue by nnovikov** [piroor/treestyletab#2336]
Is it possible to disable closing tab by middle click? I can't find it in settings.

**Comment by piroor** [comment]
TST has no such option, but some helper addon may do that.
https://github.com/piroor/treestyletab#addons-that-extend-tst
TST provides an API to handle click events on sidebar items.
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#when-a-tab-is-clicked
If there is no existing helper addon providing features you want, you may need to create an addon for the purpose by yourself.

**Comment by nnovikov** [comment]
Ok, I do it
https://addons.mozilla.org/en-US/firefox/addon/tst-disablemiddleclick/
