### ISSUE TITLE
[Feature Request] Rename tab to prepend Container Name

### ISSUE THREAD

**Issue by sam-fakhreddine** [piroor/treestyletab#2338]
Would it be possible to get a feature that prepends the container name to the tab title so we can easily see which Container we are in / container we are switching to? 

Use Case: Working with a lot of different Amazon consoles for customers, would be nice if the tab was prepended with the container name 

See screenshot for mockup

<img width="283" alt="image" src="https://user-images.githubusercontent.com/6999657/61907623-138bfe00-aeeb-11e9-8875-b84bca39cf17.png">

**Comment by piroor** [comment]
It looks unrelated to the "tree" concept. I think this should be done with an addon created for the purpose.

**Comment by irvinm** [comment]
@piroor please close this.
