### ISSUE TITLE
Theme color not applying to top bar

### ISSUE THREAD

**Issue by ajmeese7** [piroor/treestyletab#2343]
##  Short description
For some reason the top level of the tree does not change colors with the change in theme. The rest of the levels will change for any theme change, but that level remains white.

I'm sure this isn't enough information to go about getting a fix, so just let me know what else I need to include.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Select the Plain Dark theme

## Expected result
![image](https://user-images.githubusercontent.com/17814535/62155154-cd111780-b2cd-11e9-9421-0271bf9244e5.png)

## Actual result
![image](https://user-images.githubusercontent.com/17814535/62154973-7572ac00-b2cd-11e9-9a68-a5675de068e1.png)

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 69.0b6 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.1.5

**Comment by irvinm** [comment]
Check out part of the wiki around possibly hiding it if you want:  https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-the-tree-style-tab-header-at-the-top-of-the-sidebar

If you wanted to apply CSS changes, you might be able to derive what you need from the above wiki entries as well.

Remember that the sidebar is shared with multiple functional areas for Firefox (TST, bookmarks, history, synced tabs, etc) and hence I believe Firefox manages that part of the display unless changed by user CSS.

**Comment by ajmeese7** [comment]
@irvinm the issue is the style is applying as it should on my desktop but it refuses to on my laptop. They both have the exact same synced Firefox with identical extensions and settings, so both should properly display the selected theme for that part of the sidebar, not just my desktop browser.

I understand that you are trying to offer a workaround, but that does not resolve the underlying issue. If I wanted to change themes, I would need to do the CSS for every single theme, rather than it applying automatically as it should.

**Comment by irvinm** [comment]
Ah!  Gotcha.  Thanks for the clarification.

**Comment by piroor** [comment]
@ajmeese7 Anyway the sidebar header is out of control of an add-on. The white background color of the sidebar header despite you choose the dark theme on Firefox itself is a problem of Firefox itself.

**Comment by ajmeese7** [comment]
@piroor I guess I'm just confused why the sidebar header remains black on my desktop and white on my laptop despite being synced up and having identical configurations

**Comment by piroor** [comment]
@ajmeese7 Firefox's "Default" theme respects the color scheme of the platform. 
https://www.tenforums.com/tutorials/24038-change-default-app-windows-mode-light-dark-theme-windows-10-a.html
I've confirmed that the sidebar header is rendered with a dark background color when I choose "Choose your default app mode" => "Dark". Did you try it on just one of your PCs?

**Comment by ajmeese7** [comment]
For some reason on my laptop I had to disable dark mode for the default app mode then re-enable it and the problem was solved. Thank you @piroor!

**Comment by irvinm** [comment]
@ajmeese7 can you close this item?  Glad to hear you found the difference.
