### ISSUE TITLE
Native + Vertical tab combination

### ISSUE THREAD

**Issue by michaelm2391** [piroor/treestyletab#2345]
I'd enjoy the ability to use the native (horizontal) tabs as 'master containers' for Tree Style Tabs groupings.

example: 
'Personal' container as horizontal tab 1 opens a list of TST groupings related to personal matters.
'Work' container as horizontal tab 2 opens a list of TST groupings related to work matters.

And so on. Obviously the selection of respective groupings would be at the user's discretion. 

Is this possible, or are there other add-ons that can help achieve this?

**Comment by piroor** [comment]
Currently tabs in the native (horizontal) tab bar and the TST sidebar (vertical tab bar) are just mirrored. Do you mean that only "grouping" tabs should be visible in the native tab bar and only tabs in the "active group" should be visible?

Then I think it can be done with a combination of the TST and another addon providing an ability to switch tab sets with groups, for example "Simple Tab Groups": https://addons.mozilla.org/firefox/addon/simple-tab-groups/ (Please note that there are possibly some compatibility issues - I'll try to improve TST to have better compatibility with other addons.)

**Comment by irvinm** [comment]
@piroor I think you can close this.  No feedback from OP since August 4.
