### ISSUE TITLE
Completed Russian translation

### ISSUE THREAD

**Issue by wvxwxvw** [piroor/treestyletab#2348]
Translated the missing lines and, quite a bit, fixed the old ones.
Based on the English language file.

[messagesRUS_190807_144641.zip](https://github.com/piroor/treestyletab/files/3476822/messagesRUS_190807_144641.zip)

**Comment by piroor** [comment]
Thanks! Could you send these changes as a pull request? You can do that with the link: https://github.com/piroor/treestyletab/edit/master/webextensions/_locales/ru/messages.json You just need to replace the contents to the completely translated version. After you commit the change you'll see a green button to create a pull request.
