### ISSUE TITLE
Feature Request:  Setting for tab height

### ISSUE THREAD

**Issue by zekeblue** [piroor/treestyletab#236]
Possible?  I run TST vertical on left and typically more tabs than are visible for the vertical space.  The tab size is plenty big to read and work with.  I would love to shrink the height by ~15-25%.  Perhaps proportional to a configurable font size?  Is there an About:xxxxx setting that could be used if it is not built into the settings UI?   extensions.treestyletab.tabbar.heightextensions.treestyletab.tabbar.height doesn't do it (maybe that's for horizontal tabbar)  Thanks.

screenshot may not indicate how big the tabs subjectively appear on my 20" 1600x900 monitor.
http://img685.imageshack.us/img685/14/tsttabsize.png

**Comment by infinity0** [comment]
+1 for this. Recent versions of firefox have made the tabs obnoxiously large, no doubt the personal preference of some designer. I OTOH prefer to increase my productivity, instead of wasting screen space simply because someone *else* thinks it's too cluttered. At the moment I am using this workaround in `userChrome.css`:

~~~~
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
/** Change the tab-bar height */
tab.tabbrowser-tab {
    height: 24px;
}
~~~~

However, this only works when tabs are on the left or right (i.e. vertical). I tried for a few minutes to make it work even in horizontal mode, but it's much more tricky, and you need to override a bunch of extra things. I gave up because I don't use horizontal mode.

It would be nice if TST made it easier for users to set the tab height, at least in vertical mode where the benefit is much greater (space is saved per-tab), and the cost of implementing it is much simpler (as I demonstrated above).

**Comment by piroor** [comment]
The cost to implement such a new "configuration feature" seems too large for its benefit.

**Comment by infinity0** [comment]
What about copying and adapting the code that already exists for the "tab width" configuration feature?

**Comment by piroor** [comment]
Currently the height of tabs can be controlled via userChrome.css by your hand completely. So, adding new configuration UI for it is just for lazy users who don't want to write userChrome.css by himself.

On the other hand, for technical reasons, the width of the tab bar is managed by the program itself, and it is hard to control it via userChrome.css. Moreover, TST sometimes wrongly set too large / too small width. The configuration UI is also required to fix such broken value, for emergency.

Note, any adding of new codes increases maintenance cost. I don't want to add needlessly rich configuration UIs which can be alternated with other major customization way except the "about:config".

**Comment by infinity0** [comment]
OK, I understand, thanks for the feedback. In case anyone is looking for this feature, I found [Thin Tabs](https://addons.mozilla.org/en-US/firefox/addon/thintabs/) in the meantime which works well for vertical tabs and almost-OK for horizontal tabs. The benefit is more than just to avoid writing userChrome.css - each user has to figure that out for themselves, which can take a long time, especially if you don't know the technical details of how the firefox chrome works.

**Comment by piroor** [comment]
To be honest, I think that most TST users have less motivation to customize height of tabs - detault height of tabs should satisfy most people. Otherwise I should change default height of tabs to thinner (or thicker) to fit to actual usecases.

**Comment by X-Raym** [comment]
Even if it closed, and even if it can be modified by creating a file a putting some CSS code in it, I think it would be a cool feature to have this in menu. Lots of people don't even think to search for a solution on google if it is not proposed in the UI.
Thanks for listening!

**Comment by seascape** [comment]
Can someone please provide working userChrome.css for changing (decreasing) tab height in the new webextension version? An hour of trying and I've failed. 

FWIW I agree it would be a natural setting to include in the options UI. Many people who use vertical tabs do so expressly to make the most of screen real estate. For this reason I prefer my vertical tabs as short in height as possible.

**Comment by piroor** [comment]
TST 2.0 has ability to define user-defined style rules. This is an example to shrink tab height:

```css
:root { --tab-height: 20px !important; }
.tab { height: 20px !important; }
```

**Comment by Keith94** [comment]
I think it needs an `!important;` rule after it.

**Comment by X-Raym** [comment]
@piroor
But where should we put this user style ? I get stuck on this few days ago. :S

**Comment by seascape** [comment]
@X-Raym There is a text entry box in the options screen, under Advanced: Extra style rules for sidebar contents. Paste code into there.

@Keith94 Thank you but that didn't make style-unread feature work, unfortunately. I wondered if the CSS was for a pre-WE version, perhaps.

**Comment by TheSweetLily** [comment]
"I wonder if unloaded tabs can currently be styled."
There is actually a code snippet for exactly that in the wiki. 

`.tab.discarded {
  opacity: 0.75;
}`

**Comment by seascape** [comment]
@TheSweetLily Oh, I was unaware of [the wiki page](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules). Thank you very much.

**Comment by X-Raym** [comment]
@seascape Here hat I see under the Advanced Panel:

[!Screenshot](https://i.imgur.com/f8kd14a.png)

I don't see any extra style rules for sidebar contents. Do I miss something obvious ?

(note I'm using the French version)

**Comment by piroor** [comment]
@X-Raym Your version is legacy TST 0.19 for Firefox 56- and this issue is about TST 2.0 for Firefox 57+.

**Comment by X-Raym** [comment]
@piroor Ok, then I'll wait until v57 is official. Thanks!

**Comment by magikmw** [comment]
> This is an example to shrink tab height

I've modified it a bit, so pinned tab icons don't get squashed:

```css
:root { --tab-height: 20px !important; }  
.tab:not(.pinned) { height: var(--tab-height) !important; }
```

Full tabs have no issues with favicons being smaller than 'normal' but pinned icons do, they get cut with margins.
Haven't found how to manipulate those icons with the custom styles, so any help is appreciated.

**Comment by kevinbeason** [comment]
These (especially the last one) worked perfectly in v57 for me. Much needed. Thank you!

**Comment by J-Griffin** [comment]
@magikmw 's solution works great!

**Comment by suiryc** [comment]
Thank @magikmw for sharing, and @piroor for making TST.

I see that the top bar tab height changes with the selected "Density" ("compact", "normal" or "touch") in the UI personalization. "compact" appears to be the closest to what I had in v56, which I can now achieve with a height of 27 pixels in the extra stye rules.
Would there be a way to link this top bar tab height to the TST one, and make the latter a bit more dynamic ?

**Comment by piroor** [comment]
>  Would there be a way to link this top bar tab height to the TST one, and make the latter a bit more dynamic ?

I think it is impossible, because there is no such WebExtensions API.

**Comment by dset0x** [comment]
@magikmw's solution is good for not having a gap between regular tabs and pinned tabs, but is there a way to have pinned tabs the same height without having a gap?

**Comment by magikmw** [comment]
I'm fairly sure that the gaps are still there due to how the pinned tab icons are placed, based on [these](https://github.com/piroor/treestyletab/blob/aac180b2a6c0901978a4901f720274b944fd000d/webextensions/sidebar/pinned-tabs.js#L76-L79) few lines.
If I'm reading this right, each pinned tab is placed 'statically' at a certain point. It seems we'd have to rewrite how this placement works, or provide a variable to the function, from options, I assume?

**Comment by tbertels** [comment]
> TST 2.0 has ability to define user-defined style rules. This is an example to shrink tab height:

You really should make it the default setting with 25px height. It seems to be the same as it was in the pre WebExtension versions.

**Comment by piroor** [comment]
@tbertels I think that the default height of tabs should match to Firefox 57's Photon design, instead of previous version of TST itself.

**Comment by tbertels** [comment]
Maybe an option with a checkbox could be added to restore the old design? CSS styling is too difficult for most users (finding the old design CSS rules + pasting them in the options).

**Comment by piroor** [comment]
Sorry, but it is different from TST's design policy. Basically I put configuration UIs only for limited cases:

 * Behaviors which can't be determined whether choice is "recommended" generally.
 * Behaviors which require some modifications of scripts.

Changing height of tabs seems relatively easier than other existing configs.

**Comment by kacf** [comment]
I'm not able to change the height of the tabs. I've tried all the methods I can find on this page as well as on [the snippets page](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#change-tab-height-236). I know that `userChrome.css` is working, because [hiding the sidebar header](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-the-tree-style-tab-header-at-the-top-of-the-sidebar) works. Is there any way to debug whether the `height` CSS property actually makes it to the tab, kind of like the F12 dev tools?

**Comment by gerg5c42g542g2c54g52c** [comment]
```
.tab {
  height: 16px;
}
```
doesn't work on firefox 61, are there other ways to do this?

**Comment by tbertels** [comment]
It has to go in the Tree Style Tab settings.

**Comment by lbmaian** [comment]
The current CSS snippet that links to here has:
```
.tab {
  height: 25px;
}
```

But as of right now, that alone doesn't work.

It apparently needs to have a --tab-height with the same value:
```
.tab {
  height: 25px;
  --tab-height: 25px;
}
```

**Comment by lbmaian** [comment]
Okay, I've done some testing here and there, and it looks like there's no need for a `--tab-height`, but changing `height` messed up the tree until its regenerated (like closing and reopening it).

**Comment by Makishima** [comment]
Could someone share a style that will be compatible with the new FF?
Groups is overlaping for now with `.tab {height: XXpx;}`
![изображение](https://user-images.githubusercontent.com/5548003/120475016-856be300-c3b1-11eb-9949-8c056383a96b.png)

**Comment by tbertels** [comment]
> Could someone share a style that will be compatible with the new FF?
> Groups is overlaping for now with `.tab {height: XXpx;}`

I'm using this, it still works fine with Firefox 89:
```/* Smaller tabs height */
:root {
  --tab-height: 25px !important;
}

.tab {
  height: var(--tab-height) !important;
}
```

**Comment by Makishima** [comment]
Thanks, I should restart FF to resolve overlapping
