### ISSUE TITLE
"Close descendents too" option doesn't respect different contexts

### ISSUE THREAD

**Issue by mruhlin** [piroor/treestyletab#2361]
## Short description
In preferences, there is an option to set "custom" close tab behavior and specify how to handle tabs closed in the sidebar, vs. tabs closed in the native tab bar.

In my case I want to close child tabs when a parent is closed in the sidebar, but promote the earliest child when closing from the top toolbar.

The "for operations inside the tree sidebar" setting doesn't seem to work, and the sidebar uses the same rules as the top bar.

## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install TST.
 3. Go to extension settings
 4. In the "when a parent tab is closed or moved just as a solo tab..."  - section, select "Custom"
 5. "For operations inside the tree sidebar" - choose "Close descendents too"
 6. "For operations on the native tab bar... while the tree is visible..." - select "Promote the first child always"
 7. "For operations on the native tab bar..." -   select "Promote the first child always"
 8. Open several tabs
 9. Open several children of one tab
 10. In the sidebar, close the parent tab
 
Expected: Parent and all descendents are closed.
Actual: First child is promoted to be new parent.

 11. Change "For operations in the tree sidebar..." to "promote the first child..."
 12. Change "For operations on the native tab bar... while the tree is visible..." to "Close descendents to"
 13. In the sidebar, close the parent tab

Expected: First child is promoted
Actual: All children are closed

## Environment

 * Platform (OS): Mac OS
 * Version of Firefox: 68.0.1
 * Version (or revision) of Tree Style Tab: 3.1.7

**Comment by mike-tn** [comment]
Confirm the same behavior.

##Environment

    Platform (OS): Windows 7 Pro 64bit (8gb)
    Version of Firefox: 68.0.1 Firefox Portable 64bit
    Version (or revision) of Tree Style Tab: 3.1.7

**Comment by irvinm** [comment]
@mruhlin can you verify if this is fixed and close it?  If not, let us know.

**Comment by mruhlin** [comment]
Thanks. I’m on vacation now with no device to test it on, but I’ll check when I get back next week.

**Comment by mruhlin** [comment]
Yeah this looks good.  Thanks!
