### ISSUE TITLE
Suspended children become parentless

### ISSUE THREAD

**Issue by Arthaey** [piroor/treestyletab#2362]
## Steps to reproduce

1. Install TST
1. Install Tab Unloader for Tree Style Tab (v5.15)
1. Set Preferences > Tree Behavior > When a parent tab is closed or moved just as a solo tab > **Promote the first child as the new parent always**
1. Create a tree
1. Suspend all the child tabs, but _not_ the parent
   
   ```
   AnotSuspended
   |- Bsuspended
   |- Csuspended
   \_ Dsuspended
   ```

1. Close the parent (ie, _AnotSuspended_)

## Expected result

The first child tab should be promoted to become the new parent, and it should remain suspended.

   ```
   Bsuspended
   |- Csuspended
   \_ Dsuspended
   ```

## Actual result

The children suddenly (appear to?) become parentless. They remain indented, and they do remain suspended.

   ```
   |- Bsuspended
   |- Csuspended
   \_ Dsuspended
   ```

## Environment

 * Platform (OS): Mac OS X (10.13.6)
 * Version of Firefox: 69.0b14 (64-bit) Developer Edition
 * Version (or revision) of Tree Style Tab: 3.1.7 (August 9, 2019)

**Comment by Sada-Mio** [comment]
https://addons.mozilla.org/en-US/firefox/addon/auto-tab-discard/

I use this addon and it works following your steps 1-6

**Comment by piroor** [comment]
Hmm, I couldn't reproduce the problem on my environment:

* Windows 10
* Firefox Nightly 71.0a1
* TST 3.1.7
* Tab Unloader for Tree Style Tab 5.15

I got the expected result you wrote. Do you have any other extra condition to reproduce? Is the problem reproduced with a clean profile? (You can start Firefox with a command line parameter `-profile` like: `/Applications/FirefoxNightly.app/Contents/MacOS/firefox -profile /tmp/fxprofile`)

**Comment by irvinm** [comment]
@Arthaey can you review the comments and provide more details or an update?

I also use Auto Tab Discard and run anywhere from 800-1000 tabs and don't have any problems with suspended tabs and parent-child relationships.

**Comment by irvinm** [comment]
@piroor I think we can close.  No updates since August.
