### ISSUE TITLE
Make dummy group "tabs" not be real tabs

### ISSUE THREAD

**Issue by Arthaey** [piroor/treestyletab#2365]
I like having the "dummy" group tabs, but I wish they weren't real _tabs_. I wish they were just a UI element that TST kept track of, but Firefox had no idea about. Is that feasible?

**Comment by mike-tn** [comment]
Remark: i'm afraid, it will be incompatible with many other add-ons and SessionRestore,   i.e. I think,  session managers will not restore such session correctly.

**Comment by piroor** [comment]
As @mike-tn described, this design is intentional for compatibility with other tab-related add-ons (and Firefox itself).

**Comment by irvinm** [comment]
@piroor or @Arthaey will someone close this?

**Comment by piroor** [comment]
OK, I close this based on a design decision.
