### ISSUE TITLE
Add link to Tab Center Reborn in README

### ISSUE THREAD

**Issue by ariasuni** [piroor/treestyletab#2369]
Current README links to [Tab Center Redux](https://addons.mozilla.org/firefox/addon/tab-center-redux/), however the development of this extension has been discontinued for more than 6 months now.

[Tab Center Reborn](https://addons.mozilla.org/firefox/addon/tabcenter-reborn/) is a regularly updated fork of Tab Center Redux which I’m developing.

Please include a link to it instead or besides Tab Center Redux so that users knows about the updated fork.

**Comment by piroor** [comment]
Thank you for the information. Could you create a pull request for the change at https://github.com/piroor/treestyletab/edit/master/README.md ?

**Comment by ariasuni** [comment]
Do I remove the mention to Tab Center Redux or do I put Tab Center Reborn before/after/on the same line?

**Comment by piroor** [comment]
I don't know Tab Center Redux is really dead or not, so I think that both addons should be listed. Anyway "Reborn" looks good to be listed before "Redux", because people may try addons from top.
