### ISSUE TITLE
Translated theme name don’t fit

### ISSUE THREAD

**Issue by ariasuni** [piroor/treestyletab#2375]
## Short description

Column size for themes isn’t enough and cause part of some translated theme names to go to the next line.

## Expected result

“Contraste élevé” (= High contrast, see screenshot below), which isn’t too long, should stay on the same line (or at least the second word could go just under)

## Actual result

![Screenshot_20190906_224729](https://user-images.githubusercontent.com/2446451/64460246-3a4c6f80-d0fa-11e9-90bd-21263bb05d86.png)

## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: 70.0b3
 * Version (or revision) of Tree Style Tab: 3.1.7

**Comment by piroor** [comment]
Thanks. Now style names become un-line-breakable with the commit b0678f6.

**Comment by irvinm** [comment]
@ariasuni will you confirm this is fixed and close this item?

**Comment by ariasuni** [comment]
Yes, it’s working!
