### ISSUE TITLE
Scroll bar sometimes disappears when I switch group with STG

### ISSUE THREAD

**Issue by dksher** [piroor/treestyletab#2376]
Scroll bar sometimes disappears when I switch group with Simple Tab Groups addon. It happens randomly. The only way to recover it is restarting Firefox.

Note that I'm using this [Show scrollbar with regular width](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#show-scrollbar-with-regular-width) snippet.

How to replicate the issue: Just switch group several times.

Firefox 69.0
TST 3.1.7
STG 4.0.1.2

**Comment by piroor** [comment]
Thanks, I missed to update visibility of the scrollbar when tabs are shown or hidden. The commit 7ee5fce should fix this.

**Comment by irvinm** [comment]
@dksher can you confirm if this is resolved and if so close this item?

**Comment by dksher** [comment]
It seems the issue has been fixed. Thanks.
