### ISSUE TITLE
Some superfluous spaces in the page of initial startup

### ISSUE THREAD

**Issue by ariasuni** [piroor/treestyletab#2377]
## Steps to reproduce

Open the «Initial Startup» page.

## Expected result

Text is displayed properly from translations files.

## Actual result

Some spaces are inserted.

I highlighted with small red lines where the superfluous spaces are:

![Screenshot_20190910_204509_edited](https://user-images.githubusercontent.com/2446451/64642447-b272a800-d40e-11e9-997e-c0256c6c07e5.png)

Extracts from `en/messages.json`:

```
  "message_startup_userChromeCss_description_link_label": { "message": "customization examples by userChrome.css" },
[…]
  "message_startup_userChromeCss_description_2": { "message": ". But " },
"message_startup_userChromeCss_description_note": { "message": "note that it is very low level customization, thus there is no guarantee and it can cause troubles on future versions of Firefox. Please try it at your own risk, only when you know what you are doing and if you are confident that you can resolve such troubles by yourself" },
  "message_startup_userChromeCss_description_3": { "message": "." },
```

```
"config_addons_description_link_label": { "message": "addons which extend TST itself" },
  "config_addons_description_after": { "message": ". Check them out if you need more features on TST's sidebar." },
```

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 70b4

**Comment by piroor** [comment]
Thanks! The commit 093541b should reduce those needless spaces.
