### ISSUE TITLE
[Feature Request] Add visually separated groups like in "Tree Tabs"

### ISSUE THREAD

**Issue by Sniperkillerut** [piroor/treestyletab#2383]
Hi, I'm a TST user for some years now, I really like it!!

Today after a pc format I was reinstalling and reconfiguring the Firefox addons and noticed that you have a section in wich you mention about other similar addons, so I checked them out.

Now I think TST is the best for my use case, but I would like to add just one feature from "Tree Tabs"

the ability to have tabs separated/organized in folders like in this image:

look at the left-side groups (social, games, youtube, study, ungruped)

I just created those to show the functionality, I like how it is an aditional layer to organize my tabs, can it be added to TST?
![imagen](https://user-images.githubusercontent.com/20777128/65004547-5dc5a600-d8c2-11e9-97ef-85a1db9a8ba3.png)

(ignore de current mess, while TST restored the tree structure Tree Tabs did not)

and those folders can be hidden, or could even be put above all in the other toolbar in icons like in"Sidebery"

**Comment by piroor** [comment]
It looks exceeding the concept of "Tree" Style Tabs. I'm negative to include features not related to "tree", instead I hope TST to be used together with another addon providing the feature. For example: Simple Tab Groups https://addons.mozilla.org/firefox/addon/simple-tab-groups/ provides ability to switch sets of tabs.

Please note that I cannot guarantee that TST is completely compatible with STG. They may conflict on some points, and I hope to solve them. If you see compatibility issues on the combination, please report issues to here.

**Comment by Sniperkillerut** [comment]
I installed STG and so far its working fine, tomorrow I will test it more.

but I believe this solution is not ideal as it is not integrated, as in they are two different functionalities that when used in this manner they dont look really connected or related, like bookmarks and TST (not really related), and more importantly not in the same UI/menu/place, it feels really disjointed to use it as two different functionalities instead of as an integrated solution.

I dont really care about "hidding" the tabs using the firefox functionality, I just want to better organize my different trees.

**Comment by piroor** [comment]
If you need an integreated feature just for grouping of tabs, then TST's dummy tabs may help you. You can open a dummy tab just for grouping with an URI `ext+treestyletab:group?(title)`. Typing it into the location bar or creating a new bookmark with the URI, to open the URI in a tab. But please note that such dummy tabs are shown as a regular tree node - only one difference is: their icon.

Sorry again but I won't integrate the feature you told even if you need the feature heavily. Adding unrelated features makes TST bloated and hard-to-be-maintained. Focusing to just "tree" feaatures is the largest policy of TST project over 10 years.

**Comment by Sniperkillerut** [comment]
Yeah, that would work, thanks.
Do the dummy tabs have a custom ID/class?

that way with the css in the settings I could experiment a little =P

**Comment by piroor** [comment]
Dummy tabs have a class `group-tab`, so you can apply custom styles to them wit h CSS like: `.tab.group-tab.active { ... }`

**Comment by irvinm** [comment]
@Sniperkillerut will you close this item?  Or is there more to discuss?
