### ISSUE TITLE
[Bug] Unable to close tab when leave page warning is ignore

### ISSUE THREAD

**Issue by jamiechoi1995** [piroor/treestyletab#2384]
##Short description
When you open a tab, edit an article, and want to close this tab, firefox will give the warning below:
![image](https://user-images.githubusercontent.com/13494034/65023731-07aa3e80-d966-11e9-9105-d7dd80b2b9ab.png)
if you ignore this warning and click other tab and back, this warning will disappear, however, you can not close this tab from treestyle now.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. open some website that can edit an article, for example: https://mp.csdn.net/
 3. start edit an article and close without saving
 4. firefox will show the leave page warning
 5. switch to another tab and back, the warning disappear
 6. try to close this tab by clicking the 'x' in treestyle tab, now you can not close it

**Comment by piroor** [comment]
I think it is a bug of Firefox itself. TST just changes focus of tabs with `browser.tabs.highlight()` and closes a tab with `browser.tabs.remove()` - both they are genuine way in WebExtensions API. These operations should not trigger such an odd behavior.

**Comment by mruhlin** [comment]
I'm seeing the same thing with slightly simpler repro steps, that don't rely on changing tab focus:
- Start writing something (in my case a comment on reddit)
- Click "close tab" button (either the one on TST or the Firefox tab bar)
- *Click "stay on page" in the modal*
- Finish writing your comment and submit it
- Click TST's "close tab" button
  - nothing happens
- Click Firefox's "close tab" button
  - tab closes as expected

**Comment by piroor** [comment]
I totally misunderstood. It is a bug of TST itself...

Now TST marks tabs as "to-be-closed" when you click the closebox of a tab, to accelerate operations of multiple tab close. However, even if you cancel the "tab close" operation by choosing "stay on page", the "to-be-closed" status of tabs are not cleared. As the result, when you try to close the tab again, TST detects the tab as "already processed as a closing tab" and never tries to close it again.

Thus, I need to do something like:

* Clear the "to-be-closed" status when tab close action is canceled.
* Give up to accelerate multiple tab close operations.

**Comment by piroor** [comment]
I've introduced a workaround for this problem with the commit 45dc6b1.

However there are still some more problems. When a parent tab of a collapsed tree is closed on TST's UI, TST tries to close all those tabs at a time for better performance. Canceled tab close with "beforeunload" are stopped but other requests are processed, thus only canceled tabs are left at this situation.

I think all tab close requests should be canceled in this case. But sadly WebExtensions API doesn't provide any mechanism to do it.

**Comment by piroor** [comment]
I've improved the workaround more. Now "to be closed" flags on canceled tabs are correctly and safely cleared.

(On the other hand, the problem "all tabs are closed even if you cancel some tab closes by a confirmation shown on `beforeunload` event" is still there.)

**Comment by irvinm** [comment]
@piroor do you see a need to leave this one open?

**Comment by piroor** [comment]
I changed my mind. Confirmation on each tab just should control closing of each tab, instead of all closing tabs. On this viewpoint this issue has been resolved.
