### ISSUE TITLE
Add FAQ entry about userChrome.css to hide tabstrip?

### ISSUE THREAD

**Issue by jjlee** [piroor/treestyletab#2387]
## Short description

I would like to configure firefox not to show the built-in horizontal tabstrip, but I am unable to find a FAQ entry about that, and docs online about the userChrome.css trick do not work for me any more.

## Steps to reproduce

This relates to this upstream bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=1332447

Using firefox 69.0.1 and TST 3.1.8 the userChrome.css I have used in the past to hide the default tabstrip no longer works for newly created firefox profiles (I have seen this problem for roughly a month or two, I think?  my memory may be inaccurate though).  Old profiles continue to not display the built in tabstrip for some reason.

Here is my userChrome.css:

```
#TabsToolbar {
 visibility: collapse !important;
}
#tabbrowser-tabs { visibility: collapse !important; }
```

I would be happy to raise a proper bug about that, but I may just be incorrectly configuring firefox?  So this issue is just about the FAQ.

## Expected result

There is an FAQ entry describing how to disable the built in horizontal firefox tabstrip.

## Actual result

I don't see an FAQ entry about that.

## Environment

 * Platform (OS): Ubuntu 18.04
 * Version of Firefox: 69.0.1
 * Version (or revision) of Tree Style Tab: 3.1.8

**Comment by irvinm** [comment]
Try this.  Is that what you want?

```
#tabbrowser-tabs {
  visibility: collapse !important;
}
```

**Comment by irvinm** [comment]
I also added this CSS to slide the min-max-close buttons down to get rid of the entire row.

```
#nav-bar{border-top:0px !important;margin-right:144px;margin-top: -32px;}
```
![2019-10-07_21-39-48](https://user-images.githubusercontent.com/979729/66360995-16738800-e94b-11e9-9e76-4b2631c1704b.jpg)

**Comment by irvinm** [comment]
Oh, and I just noticed you pretty much have my suggestion.  I wonder if it is Ubuntu related.  My solution works fine on Windows and TST 3.1.8.  Sorry about that.  (PS. Here is where I found out about the change in FF65a:  [Reddit](https://www.reddit.com/r/firefox/comments/9wd2d2/nightly_650a1_no_longer_able_to_hide_tab_bar/))

**Comment by Valentin-N** [comment]
Probably related to [toolkit.legacyUserProfileCustomizations.stylesheets](https://www.ghacks.net/2019/05/24/firefox-69-userchrome-css-and-usercontent-css-disabled-by-default/) which needs to be set to `true` for `userChrome.css` to take effect.

**Comment by matunos** [comment]
> Probably related to [toolkit.legacyUserProfileCustomizations.stylesheets](https://www.ghacks.net/2019/05/24/firefox-69-userchrome-css-and-usercontent-css-disabled-by-default/) which needs to be set to `true` for `userChrome.css` to take effect.

This was exactly it for me. Once I set the value to true and restarted Firefox, my previous userChrome.css settings were applied again.

**Comment by jjlee** [comment]
Thanks Valentin, that was it for me too!

How about a FAQ entry something like this (sorry not terribly polished for non-technical users, but better than nothing):

Q. Why do I see the regular horizontal tab strip along the top as well as the tree-style tabs on the left of the browser window?

A. This is because, since major changes in Firefox 57, there is no way for the extension itself to hide the built-in tab strip.  As a workaround, you can hide it yourself by creating a directory in your firefox profile directory, named `chrome`.  Inside the `chrome` directory, create a text file containing exactly the following text:

```
#tabbrowser-tabs { visibility: collapse !important; }
```

Then, visit the URL `about:config`, and set `toolkit.legacyUserProfileCustomizations.stylesheets` to true (search for that name, then double click the setting to toggle it from `false` to `true`).

**Comment by piroor** [comment]
I've added an entry to the list of most major FAQ.
https://github.com/piroor/treestyletab/blob/master/README.md#major-faq
I agree that it is not user friendly with less actual steps to do. People need to click the link and read another instruction to activate the `userChrome.css`. This is because I don't want people to try that without knowing about risks.

**Comment by irvinm** [comment]
@jjlee will you close this issue?  Thanks.

**Comment by jjlee** [comment]
Thanks!
