### ISSUE TITLE
Old way of resizing tab height is broken

### ISSUE THREAD

**Issue by Kern3l** [piroor/treestyletab#2389]
# The symptoms

When I apply this: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#change-tab-height-236 
```
.tab {
  height: 25px;
}
```
The latest Firefox on Linux.

## Expected result

Tabs should be set to the new height at all times.

## Actual result

It looks as expected until you collapse a tree - then the parent tab will shrink even more. The more nested the tree is, the more it will shrink.

I also tested some of user's custom styles with more compact tabs and all had the same problem.

# Proposed solution

Update the wiki with working CSS or make it work with the previous code.

**Comment by Lej77** [comment]
This seems to work:

```css
.tab {
  --tab-size: 100px !important;
  height: var(--tab-size);
}
```

**Comment by piroor** [comment]
Thanks, I've updated the code snippet: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#change-tab-height-236-2389

**Comment by Kern3l** [comment]
That's great, thanks! Just one thing left to update: the menu above the code snippets - currently the link's hash is pointing the previous title (so it doesn't scroll down).

**Comment by Gaffer13** [comment]
Doesn't seem to be working for me in Firefox 85. Don't know when it started - haven't tried it before. Other userchrome fixes appear to be working - the hidden horizontal tab bar and new location for window buttons. 

Is it still working for you?

**Comment by irvinm** [comment]
I just tried it and didn't have any problems.

**Comment by Lej77** [comment]
@Gaffer13 I don't think this CSS code should be added to your `userChrome.css` file. Instead it should be applied in the advanced section of Tree Style Tab's option page.

**Comment by Gaffer13** [comment]
@Lej77 Yes, that's it, thanks! :)
