### ISSUE TITLE
Latest upate 'Version 0.14.2012021001' causes tree to disappear in ff10

### ISSUE THREAD

**Issue by cnewtonne** [piroor/treestyletab#239]
When I started ff10 today, the entire tree disappeared. None of the following actions fixed it ...
- starting ff10 with a new profile with ONLY this extension enabled.
- Disabling all extensions.
- reinstalling this extension.

The only way I got to resolve is by installing Version 0.14.2012020901.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
