### ISSUE TITLE
Nested "group tab" does not display proper favicon

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2394]
## Short description
Nested "group tab" does not display its favicon properly when looking at the parent "group tab" page.

## Steps to reproduce
- Create a group tab.
- Create another child group tab in the original group.
- Inspect favicons\tabs in the first group tab and see that child group tab has default favicon.

![2019-10-17_13-08-46](https://user-images.githubusercontent.com/979729/67031984-adc1a380-f0e0-11e9-9f66-dc5f95e49873.jpg)

## Expected result
Favicon should be that of the default "group tab".

## Actual result
Favicon of the child "group tab" is displayed as the default favicon.

## Environment
 * Platform (OS): Windows 10 x64
 * Version of Firefox:  69.0.3 (64-bit)
 * Version (or revision) of Tree Style Tab:  3.1.8

**Comment by piroor** [comment]
Thanks, I missed it. The commit 2a1371e should fix this.
