### ISSUE TITLE
[Feature Request] TST functionality in default horizontal tab panel

### ISSUE THREAD

**Issue by Prucconi** [piroor/treestyletab#2395]
Would be great to implement TST functionality in default horizontal tab panel. Maybe it's even possible to replace default tab panel with TST.
The only restriction here is height of tabs, which limits number of child sub-tabs to be shown. But 4 levels of tabs (as shown on image) is enough for most purposes.
![изображение](https://user-images.githubusercontent.com/56964932/67487488-b41ec500-f676-11e9-9178-31583a44db4c.png)

**Comment by piroor** [comment]
Please see the FAQ: https://github.com/piroor/treestyletab/blob/master/README.md#major-faq
Sadly TST 2.0 and later never support the horizontal tab bar and it is impossible due to restrictions of WebExtensions API.
