### ISSUE TITLE
Improve narrow scrollbar appearance

### ISSUE THREAD

**Issue by Infocatcher** [piroor/treestyletab#240]
With default extensions.treestyletab.tabbar.narrowScrollbar.size = 10px scrollbar looks better for me with following CSS:
```css
				tabs.tabbrowser-tabs[treestyletab-mode="vertical"][treestyletab-narrow-scrollbar="true"]
				  .tabbrowser-arrowscrollbox
				  > scrollbox
				  > scrollbar[orient="vertical"]
				  > scrollbarbutton {
					margin-right: -2px;
					margin-left: -2px;
				}
```

But scrollbar width are configurable (OS preferences) and extensions.treestyletab.tabbar.narrowScrollbar.size are configurable too...
For example for 14px we should use -3px margins.
But I don't know easy way to detect scrollbar width (maybe scrollbar.boxObject.width or getComputedStyle(), but we should already have a scrollbar).

Before: <img src="http://img208.imageshack.us/img208/5194/fxtreestyletabnarrowscr.png" /> After: <img src="http://img821.imageshack.us/img821/5194/fxtreestyletabnarrowscr.png" />

**Comment by piroor** [comment]
I think that this approach is unrealistic for various platforms - Windows 10, Windows 8, Windows 7 with aero, Windows 7 without  aero, Linux with Gnome, Linux with KDE, Linux with other window managers, many versions of OS X... Moreover, TST supports officially supported versions of Firefox (currently 38 and 44). I cannot confirm all best margins for 10 or more environments...

**Comment by piroor** [comment]
Done by 6ca9f61 but it should be tested on other platforms.
