### ISSUE TITLE
Mouseover tooltips for long tab labels (mostly children) don't always show

### ISSUE THREAD

**Issue by Argolics** [piroor/treestyletab#2400]
## Short description
It's seemingly #2177 all over again, but i am not sure what has actually regressed expected behaviour this time around.
Basically while tooltips for parent/first level tabs with long titles are always shown, children tabs often don't show any tooltip/pop up on hover. It seems to depend on nesting level somewhat - some tabs in a tree will show the tooltip, while others (children/subchildren mostly) may not or not always. Which children tab will/won't show the tooltip seem to be pretty random, i couldn't find any reliable triggers for it.

There seem to be two conditions for this bug: **TST 3.2.1** and **FF 71.0**(noticed it in **b5**), could be a 3.2.0 regression, an FF bug or both. Settings for '_Too long label of tabs_' apparently don't really matter, both **Crop with ".." (Better Performance)** and **Fade Out (Better Visibility)** are giving the same random/unreliable results. Also can't reproduce this in FF 70.0 (tested with much smaller number of tabs though).

## Steps to reproduce
1. Install FF 71.0b5 & TST 3.2.1
2. Open a tree with lots of tabs, some with 2+ levels of nesting/child and subchild tabs
3. Some tabs with long labels don't reliable show tooltips on mouseover anymore, mostly children/subchildren tabs

## Expected result
Tooltips are always shown

## Actual result
Tooltips for children tabs show very unreliably

## Environment

 * Platform (OS): Linux
 * Version of Firefox:  71.0b5
 * Version (or revision) of Tree Style Tab:  3.2.1

**Comment by piroor** [comment]
Thanks. I've found some bugs around updating of tab label's overflow status, and I've introduced some small fixes. Could you try the development build of TST?: https://github.com/piroor/treestyletab/blob/master/README.md#development-builds If you see the problem again, please describe steps to reproduce with actual URLs and screenshots. It will help debuggings.

**Comment by piroor** [comment]
>  P.S. i don't think it was URL-specific at all, happened with almost any tree i had, but yeah a screenshot/screencast might have been better than my description.

Yes, it is not URL specific. I just hope to see the title of the page (short, or long enough to be overflowed) and operations to reproduce, to verify the problem.

**Comment by irvinm** [comment]
@piroor can you close this?
