### ISSUE TITLE
Suggested CSS to support option configuration when using "dark mode"

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2405]
There is a CSS tag to detect when using dark or light mode ([https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme](url)) which would allow better support of dark mode when configuring TST.

Currently when dark mode is enabled (Windows 10 -> Settings -> Personalization -> Colors -> Custom -> Choose your default app mode -> Dark), the TST configuration screen looks like:

![Snag_e82027f](https://user-images.githubusercontent.com/979729/68051701-734e2e00-fcbe-11e9-9577-a1b0f9462c7b.png)

When I add the CSS below to the TST options.html page dynamically in the broswer, I can get a better match with dark mode and it properly reverts back to the white version when in "light mode".

```
@media (prefers-color-scheme: dark) {
  html {
    --input-background: #474749;
    --link-color: var(--blue40);
    --link-color-hover: var(--blue50);
    --link-color-active: var(--blue60);

    color: white;
    background: black;
  }
  
  input,
  textarea,
  select {
    color: white;
    background: gray;
    border: solid 1px var(--grey50) !important;
  }
}
```

![Snag_e86b5ed](https://user-images.githubusercontent.com/979729/68052040-2a4aa980-fcbf-11e9-8e55-761b30771c4a.png)

I am not even sure if I got all of the CSS tags that need to be covered (or which colors your would want to use) but seems like this can be done fairly easy using the "prefers-color-scheme" CSS media feature.

If you don't want to do it, please feel free to close this item. :)

**Comment by piroor** [comment]
I think this should be fixed by Firefox itself, like https://bugzilla.mozilla.org/show_bug.cgi?id=1544212

**Comment by piroor** [comment]
I've filed: 1593355 - Options page in about:addons is still shown with bright color on Dark mode
https://bugzilla.mozilla.org/show_bug.cgi?id=1593355

**Comment by irvinm** [comment]
Thanks @piroor!  Let's see how this all plays out.

**Comment by jakobbbb** [comment]
Hey,

unfortunately, since 2.3.3, TST has stopped respecting the *Apply Browser Theme* option for me.

I use a dark GTK theme (I'm on Linux) and have set Firefox's theme to default so that it uses that GTK theme.  I also set `widget.content.allow-gtk-dark-theme` to true, as suggested in https://github.com/piroor/treestyletab/issues/2314#issuecomment-512810530.

I got the Plain theme to work again by disabling the newly added CSS with the `prefers-color-scheme` selector:

https://github.com/piroor/treestyletab/blob/0cf44267ff708de16f4420a82348c0dfb7ef0887/webextensions/sidebar/styles/square/plain-color.css#L62

I'm sure there is a way to prevent this bit of CSS overriding the theme if *Apply Browser Theme* is active?

**Comment by Nitrooo** [comment]
> unfortunately, since TST 3.2.3, TST has stopped respecting the _Apply Browser Theme_ option for me.

Same problem here on 3.2.3.

**Comment by piroor** [comment]
Sorry for the regression. With the commit 0b8dc5e TST now respects the system color even if it is detected as the "Dark" color scheme. Screenshots:

TST 3.2.3 + HighContrastInverse: tabs are shown with the built-in Dark color sheme
![image](https://user-images.githubusercontent.com/70062/68318492-3a6bea00-0100-11ea-8b22-5efafad6666e.png)

TST development build + HighContrastInverse: tabs are shown with colors specified by the HighContrastInverse theme
![image](https://user-images.githubusercontent.com/70062/68318497-3d66da80-0100-11ea-9a6b-37d6319760c7.png)

**Comment by piroor** [comment]
TST 3.2.3+ HighContrastInverse + "OldWood" Firefox theme: tabs are shown with the built-in Dark color sheme
![image](https://user-images.githubusercontent.com/70062/68319153-32607a00-0101-11ea-8506-484fd9d220ca.png)

TST development build + HighContrastInverse + "OldWood" Firefox theme: tabs are shown with colors specified by the HighContrastInverse theme, respecting "OldWood" Firefox theme
![image](https://user-images.githubusercontent.com/70062/68319302-7784ac00-0101-11ea-8caf-981a1f317fcb.png)

**Comment by jakobbbb** [comment]
Thank you very much, the styling works as expected in the latest development version:
![tstfixed](https://user-images.githubusercontent.com/26824491/68320710-c100d700-00c0-11ea-862b-416a352f3342.png)
3.2.3+Plain on the left, Dev Version+Plain on the right

**Comment by irvinm** [comment]
@piroor I am closing this issue as everything looks good now.
