### ISSUE TITLE
group-tab.html dark mode support

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2406]
Obviously this may be related to https://github.com/piroor/treestyletab/issues/2405, but wanted to see if these are related or different in some other way. (Questions at the bottom)

I see in group-tab.html the color is being set with the following code.

![Snag_18c4427](https://user-images.githubusercontent.com/979729/68076928-a3b2cc80-fd91-11e9-8f0b-a858777c2dcd.png)

The values of "background: -moz-dialog" and "color: -moz-dialogtext" create the same color pallet regardless of whether dark or light mode is active.

![Snag_18da31a](https://user-images.githubusercontent.com/979729/68076938-d957b580-fd91-11e9-89b5-b6aea001738e.png)

Changing the values to "background: gray" and "color: white" create a better experience in dark mode.

![Snag_18ecd43](https://user-images.githubusercontent.com/979729/68076954-073cfa00-fd92-11e9-919b-dbe00bbe8094.png)

So the questions:

1. Should we expect the values of -moz-dialog and -moz-dialogtext to change based on light\dark mode?
2. If not, is there a way to utilize the "prefers-color-scheme" CSS tag within the HTML to change the colors based on color scheme?
3. If not, is there a way I can change these colors manually?

It is not a big issue regardless of the answers.  We can close this item after any discussion.

**Comment by piroor** [comment]
Thank you for proposal! Color scheme of options in `about:addons` should be controlled by Firefox itself, on the other hand other tab contents provided by TST look to need to apply Dark theme by self. I hope that the commit 4c7d729 based on your code at #2405 does that.

**Comment by irvinm** [comment]
I pulled down the development build and played with this a little.

Both the group-tab.html and startup.html look great and dynamically change colors properly when the color mode is changed.  You may want to consider modifying the color of links (Example on startup.html) in dark mode as well.  White underlined links aren't too bad, but a version of blue might stand out better.

Ex:
    --link-color: var(--blue40);
    --link-color-hover: var(--blue50);
    --link-color-active: var(--blue60);

![Snag_64e401b](https://user-images.githubusercontent.com/979729/68090559-1b8cff80-fe43-11e9-950d-48a12ae87709.png)

![Snag_64e5e52](https://user-images.githubusercontent.com/979729/68090561-2051b380-fe43-11e9-8692-b07d465460ee.png)

![Snag_64e7d05](https://user-images.githubusercontent.com/979729/68090563-247dd100-fe43-11e9-8723-b45d55e6c77e.png)

![Snag_64e97d0](https://user-images.githubusercontent.com/979729/68090564-28a9ee80-fe43-11e9-8f9b-c2adb2d08b82.png)

I do see you made the same changes to options.css, but nothing changed when viewing the options either in-line or as a separate page.

When I inspect options.html, I can see CSS is properly applied.

![Snag_6604554](https://user-images.githubusercontent.com/979729/68090778-db7b4c00-fe45-11e9-8982-42e8337eea4a.png)

**Comment by piroor** [comment]
OK, with recent commits I've imported more color definitions including link colors from Firefox itself.

**Comment by irvinm** [comment]
The colors look great now.  Thanks.  We can track options.html in the other issue.

**Comment by irvinm** [comment]
@piroor when viewing options.html in its own page, the color changes look A LOT better.  Thank you.

In comparing the color pallet, I see 2 or 3 items which standout a little too much and just want to make sure it is what you intended.  (From: https://hg.mozilla.org/mozilla-central/raw-file/tip/browser/themes/addons/dark/manifest.json)

It looks like things like **text input areas** and **drop down lists** are white background with black text which can be pretty bright in the theme depending on the size of the element. [Red circled below]

![Snag_11a9d2ea](https://user-images.githubusercontent.com/979729/68256680-c39af800-fffe-11e9-90c7-a494bcbc7064.png)

Looking at another addon, it looks like the theme basically keeps the text in those areas as white, but just uses background color of #474749. (Which is basically just a color that is lighter than the background, but still dark)

![Snag_11b3c05b](https://user-images.githubusercontent.com/979729/68257153-47a1af80-0000-11ea-9078-f183645150d3.png)

**Comment by piroor** [comment]
Thanks, I forgot to define colors for input fields. After 77be0b8 and 513dc6a they are shown with dark background and light text color. The color scheme is based on Firefox's in-content fields.

**Comment by irvinm** [comment]
@piroor 3.2.4 just landed an everything looks great here as well.  Thanks again.
