### ISSUE TITLE
Feature request: session save

### ISSUE THREAD

**Issue by bijang** [piroor/treestyletab#2407]
Would it be possible to have a feature to 'summarize' an entire sessions tabs, in a link for later separate use (example scenario would be an academic search session), like what tab.bz offers (which I don't think is open source and has dodgy privacy policy)

**Comment by piroor** [comment]
Sorry but I won't add features not related to "tree of tabs" to TST. There is a document describing about this:
https://github.com/piroor/treestyletab/blob/master/README.md#faq--frequently-rejected-requestsproposals

**Comment by irvinm** [comment]
@bijang will you close this item?  Or is there more to discuss?
