### ISSUE TITLE
Feature request: syncronisation

### ISSUE THREAD

**Issue by bijang** [piroor/treestyletab#2408]
Would it be possible to syncronise tabs across browser by integrating with device to device sync like syncthing, or a cloud, self-hosted or otherwise; or by integrating with another opensource project like xbrowsersync (https://github.com/xbrowsersync).
[xbrowsersync syncs bookmarks (through self hosted or 3rd party cloud) but plans to add sync for tabs and history accross devices and browers through E2E encryption.] 
Thank you for your project and hard work
Is there a way to donate to this project?

**Comment by piroor** [comment]
I recommend you to use another addon developed for the feature: https://addons.mozilla.org/firefox/addon/tab-session-manager/

I won't add features not related to "tree of tabs" to TST. There are a document describing about this:
https://github.com/piroor/treestyletab/blob/master/README.md#faq--frequently-rejected-requestsproposals

And sorry but currently there is no donation way (described as the last FAQ).

**Comment by bijang** [comment]
Thank you for your reply and you work on this great project and for the recommendation for tab session manager, it is exactly what I am looking for!

**Comment by irvinm** [comment]
@bijang will you please close this issue?  Thanks.
