### ISSUE TITLE
group-tab.html favicon issues

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2413]
With FF 70.0.1 and TST 3.2.3 on the group-tab.html page, it looks like the favicon for children group-tab.html pages and regular web pages that don't provide their own favicon are missing.  (I originally thought it was dark mode related, but I switch the color scheme back to normal and still don't see them.)

**Chilredn group-tab.html:**
![2019-11-06_7-37-31](https://user-images.githubusercontent.com/979729/68299578-f75f3780-0069-11ea-8ed6-5fa1aeb47870.jpg)

**No favicon site: (Should be default globe favicon)**
![2019-11-06_7-36-03](https://user-images.githubusercontent.com/979729/68299190-39d44480-0069-11ea-8bcd-b5f08d03ad7b.jpg)

**Comment by piroor** [comment]
Thanks, this is a regression and fixed with a2b1ce8.
