### ISSUE TITLE
Tab Description Dialog Box created by hovering cursor over tab persists outside of the Tree Style Tab Area

### ISSUE THREAD

**Issue by mortar-and-pestle** [piroor/treestyletab#2414]
I am unsure if this is a bug. If confirmed to be a bug, I will go through the steps to reproduce it on a clean profile. I understand this may not be acceptable but I don't have the time right now to dig into it. 
![treestyle](https://user-images.githubusercontent.com/36805455/68365400-2de29400-00f6-11ea-8084-c162cfbf379e.png)

Here's the grievance. Frequently, when I put the cursor of the mouse onto a tab(cursor is not shown in picture due to printscreen capabilities), a white dialog box with the full name of the tab shows up near the tab. This applies to normal tabs in the default tab bar at the top of firefox as well as the tabs in Tree Style Tab. When I move the mouse away from the tab onto a web page(out of the treestyle tab area), the dialog box will persist. In the picture I have included, my cursor is way left of the page. It doesn't happen every time and the dialog box is shown through apps overlayed onto firefox. For example, switching to paint while the dialog box is showing in firefox also shows in paint. 

## Environment
 * Platform (OS): Windows 10 64 BIt
 * Version of Firefox: 70.0.1
 * Version (or revision) of Tree Style Tab: 3.2.3

**Comment by piroor** [comment]
There is a similar (but different) issue: #1423  It is a bug of Firefox itself, and it should be fixed by Firefox side.

Additional notes:

* You can deactivate tooltip for collapsed tree. TST Options => Development => All Configs => uncheck "showCollapsedDescendantsByTooltip".
* Sorry but there is no option to deactivate tooltip for tabs completely.

**Comment by mortar-and-pestle** [comment]
I see. Well it's not the worst thing. So its called a tooltip? Good to know. At least the option reduces the size of the tooltips that do show up for tabs with children.

Thanks for the reply and I love the add on. Been using it for years. Surfing the web is impossible without it.

**Comment by piroor** [comment]
> So its called a tooltip?

Yes, "dialog" means a message windows with buttons or input fields. Small floating windows like that - disappear after a while or mouseout - are called "tooltip".

By the way, I still don't know which bug is the exact same to this but here is a list of similar Firefox bugs:

* [636616 - Tooltip background remains when page scrolled with wheel](https://bugzilla.mozilla.org/show_bug.cgi?id=636616)
* [1286521 - ‘Show MDN Docs’ tooltip remains displayed after 'Visit MDN page' link was clicked](https://bugzilla.mozilla.org/show_bug.cgi?id=1286521)
* [1146490 - Switching tabs with the keyboard doesn't hide tooltips](https://bugzilla.mozilla.org/show_bug.cgi?id=1146490)
* [1194846 - Tooltip remains even after taking mouse off any icon while entering customize mode](https://bugzilla.mozilla.org/show_bug.cgi?id=1194846)

After some of them become fixed this issue may be fixed also.
