### ISSUE TITLE
Tab dragging: Landing line not visible in dark mode

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2415]
FF 70.0.1 with TST 3.2.3:

- Install fresh Firefox with new profile
- Create some tabs
- Drag tabs and notice the "landing line" is visible and easy to see in light mode
- Change color to dark mode
- Repeat tab dragging and notice black-on-black landing line makes judging where the tab will land very difficult

Desired result:
- Landing line should be white (or lighter) when in dark color mode.

![46003935-C9DA-4405-B750-15308C1DF263](https://user-images.githubusercontent.com/979729/68430645-6f1e8680-017e-11ea-8aab-bbaddda7edab.GIF)

**Comment by piroor** [comment]
Thanks. This should be fixed with the commit 2ad2d44.

**Comment by irvinm** [comment]
@piroor I will close this and validate when 3.2.5 comes out.  I see the check-in simply set the drop color via a variable.
