### ISSUE TITLE
Tab bar splitter improvements

### ISSUE THREAD

**Issue by Infocatcher** [piroor/treestyletab#242]
1. Reset tab bar size
We already have reset tab bar size functionality via double click:
<pre>
	resetTabbarSize : function TSTBrowser_resetTabbarSize() 
	{
		if (this.isVertical) {
			this.clearTreePref('tabbar.shrunkenWidth');
			this.clearTreePref('tabbar.width');
		}
		else {
			this.clearTreePref('tabbar.height');
			let tabContainerBox = this.getTabContainerBox(this.mTabBrowser);
			tabContainerBox.removeAttribute('height');
			this._tabStripPlaceHolder.height = tabContainerBox.boxObject.height;
		}
		this.updateFloatingTabbar(this.kTABBAR_UPDATE_BY_RESET);
	},
</pre>
Proposed improvements:
1) handle only left-clicks (not a "bug", but more intuitive)
2) make default values for "tabbar.shrunkenWidth" and "tabbar.width" configurable

2. We can do something good via middle-click:
1) collapse tab bar (clickable splitter area are small)
2) or toggle auto hide
3) or user defined action (one of the above) :)

**Comment by piroor** [comment]
Done by fc38c81.
