### ISSUE TITLE
group-tabs API throws 'cyclic object value'

### ISSUE THREAD

**Issue by mnutt** [piroor/treestyletab#2420]
## Short description

TST API throws `cyclic object value` when calling `group-tabs`

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Manually load the addon from https://github.com/mnutt/group-tabs-by-domain
 4. Open two or more tabs from the same domain. (example: github.com)
 5. Press the extension's "Group Tabs By Domain" button in the button actions bar.

I was interested in functionality similar to https://github.com/piroor/treestyletab/issues/1660 so I decided to build an extension that would group tabs by domain. I'm running into an issue when calling `group-tabs` with an array of tabs. (https://github.com/mnutt/group-tabs-by-domain/blob/master/background.js#L65)

## Expected result

Calling:

```
const result = await browser.runtime.sendMessage(TST_ID, {
  type: 'group-tabs',
  tabs: group.map(t => t.id)
});
```

returns a successful result.

## Actual result

The functionality seems to succeed but I receive an error asynchronously in the console:

```
Warning: Sending message that cannot be cloned. Are you trying to send an XPCOM object? [MessageChannel.jsm:1009:17]
Error: cyclic object value [MessageChannel.jsm:1009]
```

## Environment

 * Platform (OS): MacOS 10.14.6
 * Version of Firefox: Developer Edition 71.0b9, 70.0.1
 * Version (or revision) of Tree Style Tab: 3.2.4

**Comment by piroor** [comment]
Thanks! I missed that, and the commit f262f01 should fix this error.

**Comment by mnutt** [comment]
Thank you!

**Comment by mnutt** [comment]
I can confirm that f262f01 fixes the error. Thanks again!
