### ISSUE TITLE
border-left CSS property not consistent

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2421]
## Short description
Using FF 70.0.1 & TST 3.2.5, applying TST CSS towards "border-left" properties on a tab show different behaviors based on the indentation of the tab.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Apply:

```
.tab.active {
  background-color: #0b6ef8;
  border-top: 13px solid red;
  border-left: 13px solid red;
  border-right: 13px solid red;
  border-bottom: 13px solid red;
}
```

 4. Notice that the left border is only 13px when the tab is at the root level, else much smaller.  All other sides of the tab show consistent behavior.  (Obviously, I am using 13 just to demonstrate this behavior.)

## Expected result
I would expect 13px border for any position of the tab.

## Actual result
Root tabs:
![2019-11-15_21-58-29](https://user-images.githubusercontent.com/979729/68987043-b26a9c00-07f3-11ea-8fa1-da41f2839063.jpg)

Tabs inside trees:
![2019-11-15_21-58-51](https://user-images.githubusercontent.com/979729/68987049-c0202180-07f3-11ea-84e0-7fd6e76187a9.jpg)

**Comment by piroor** [comment]
It is produced with the declaration:

https://github.com/piroor/treestyletab/blob/4b81b82e00f4e79923736aa3933974116c6564ee/webextensions/sidebar/styles/square/border.css#L35-L37

Thus you need to write a selector with more higher specificity, like `:root.left .tab.active`.

**Comment by irvinm** [comment]
Thank you for the direction.  I was able to properly apply a custom border with the below CSS.  I deleted the original CSS block and just decided to it all here. [Both tabs with parents and tabs without parents]

I am including the CSS in case anyone else runs into a similar need.

```
:root.left .tab.active[data-parent-id],
:root.left .tab.active {
  background-color: #0b6ef8;
  border-top: 3px solid red;
  border-left: 3px solid red;
  border-right: 3px solid red;
  border-bottom: 3px solid red;
}
```
