### ISSUE TITLE
"Open all as tree" opened bookmarks in folders along with sub-folders

### ISSUE THREAD

**Issue by wvxwxvw** [piroor/treestyletab#2422]
"Open all as tree" opened bookmarks in folders along with sub-folders
This is wrong.
The possible options:
1. Do not let touch the folder,
2. Let sub-folders opens as a page with the links,
3. Let opens bookmarks in sub-folders as a tree branch.

Think for yourself, why do we need dozens of garbage tabs, which are formed in the case of opening folders with subfolders, this menu item?

**Comment by wvxwxvw** [comment]
Посмотрите этот аддон - https://github.com/psimonyi/openslowly
И мой комментарий к нему - https://github.com/psimonyi/openslowly/issues/4#issue-524291859

**Comment by irvinm** [comment]
@wvxwxvw I am not sure that "this is wrong" is right.  @piroor obviously implemented this with some design decisions that are obviously different that what you might expect.

Having said that, I think the way it was implemented is pretty slick where people can bookmark trees and restore them with the proper relationships.  If you check how it is done, you can see that each tab that is a child of something has any number of ">" in the stored text of the bookmark to store the relationships between with tabs when restoring them.  There are no folders stored.  I could just be missing your point.

@piroor, 2 things:
1. I did notice that restoring a tree creates everything properly, but that I would have thought the root tab being restored would have been a child or sibling of the active tab when the operation takes place.  (Yes, I am using browser.tabs.insertAfterCurrent;true)  I see without the about:config change how this works out well placing the new tree at the end of the tab list.
2. You may want to consider allowing an option to restore trees as discarded tabs [createProperties.discarded].  Especially for a tree with a large number of tabs, the resources will be pretty bad.  Creating them as discarded tabs will be quick and use little resources.  (But there is a FF defect where the favicon isn't set on a new tab created in the discarded state until that tab is loaded - https://bugzilla.mozilla.org/show_bug.cgi?id=1475240)

**Comment by wvxwxvw** [comment]
This is about opening a bookmark subfolder as an empty tab.

I beg you not to litter the branch. It is not related to the restoration of tabs and trees.

**Comment by irvinm** [comment]
Ok.  I will let @piroor comment.  Thanks.

**Comment by wvxwxvw** [comment]
![Video_2019-11-22_223731](https://user-images.githubusercontent.com/13194155/69457616-8369a280-0d7e-11ea-8009-11e3f52ba819.gif)

**Comment by irvinm** [comment]
Thanks for the animation ... that clears up a lot.  I did something similar on my system (to see if I could help) and I see a different behavior (albeit some similarities) than you.

I bookmarked a folder with 2 bookmarks and another folder ... in the 2nd folder was 2 other bookmarks.  You can see when I do a "Open all as a tree", I get a "blank new tab" (strange), the 2 bookmarks restored properly, then the folder restored as a "TST group-tab" but none of the bookmarks inside the folder were restored ... that might be by design.

Are you using the addon "Speed Dial"?  If so, can you disable it and retry your scenario just to see if the folders get created properly as group tabs?  Maybe there is a conflict between the 2 addons somehow.

It seems to me that either @piroor should not restore the sub-folders unless they are to be restored as TST group-tabs and then the sub-bookmarks restored as children of that group-tab.

![2019-11-22_15-45-03](https://user-images.githubusercontent.com/979729/69459514-e720ab00-0d3f-11ea-947a-c3f7ef7cf5a3.gif)

**Comment by wvxwxvw** [comment]
Like children, they can't. Read here -
https://github.com/piroor/treestyletab/issues/2230

The test I could do on an empty profile, but I do not see the point. And so it is clear that the mechanism should not touch subfolders at all. If he can't handle them.

**Comment by piroor** [comment]
> Think for yourself, why do we need dozens of garbage tabs, which are formed in the case of opening folders with subfolders, this menu item?

Oops, sorry I just forgot to handle nested folders. After the commit 1555ba4c5 only regular bookmarks are opened in tabs and TST doesn't retrieve subfolders for now.

**Comment by piroor** [comment]
I've added one more context menu command "Open All as a Tree including subfolders" (hidden by default) and a new option to control "discarded" state of opened tabs. These new behaviors are available via the API: https://github.com/piroor/treestyletab/wiki/API-for-other-addons#open-bookmarks-with-structure

**Comment by wvxwxvw** [comment]
@piroor 
If possible, make options to hide these menu items. As you can see, similar items can be added by other Addons and perhaps they will be preferable for the user. For me personally while it is preferable to use the addon https://github.com/psimonyi/openslowly . It would be nice if its author tweaked it for compatibility with TST. But he's not answering yet.

Or maybe you implement this in TST. Sequential opening of links in several pieces, not all at once. Otherwise, the browser hangs with the OS, when you open large folders.

I would like to get and grouping and opening sequence, but combinations of Addons will not allow this at the moment.

**Comment by wvxwxvw** [comment]
@piroor 
Only now saw. Also a good option. Thanks.
