### ISSUE TITLE
add-on consumes ridiculous amounts of RAM, CPU and freezes

### ISSUE THREAD

**Issue by LJMP** [piroor/treestyletab#2424]
## Short description
after some time of usage when trying to switch tabs  
add-on consumes 2-3GB RAM, 
10-20% CPU load 
and freezes dead :skull_and_crossbones: 

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. open Firefox with 4-5 windows, ~50 tabs each
usage RAM ~200MB, CPU <0-2%
after some hours of usage (open, close tabs, windows, etc.)
suddenly experience freezes of Firefox when trying to switch tabs
the treestyletab add-on WebExtension is using RAM  >2.4GB, CPU >10% (not Firefox total, just the add-on)
 4. ???

## Expected result
stable RAM and CPU consumption

## Actual result
unusable after freezing
need to kill the WebExtension subprocess or close Firefox :boom: 
giant memory leak? :man_shrugging: 

## Environment

 * Platform (OS): 4.15.0-70-generic 16.04.1-Ubuntu
 * Version of Firefox: 70.0.1 (64-bit) 
 * Version (or revision) of Tree Style Tab: 3.2.5

**Comment by irvinm** [comment]
@LJMP if you really think TST is the root of the performance issue you may want to collect a performance profile while you are seeing problems. (https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs ... see instructions at the bottom)

I think it is unlikely a TST issue as lots of people use many tabs with TST without any issues.  I personally (different environment) run 600-800 tabs every day without any problems.

**Comment by irvinm** [comment]
@piroor I think we might be able to close this one.

**Comment by superbeta** [comment]
Currently, my Firefox CPU usage jumps from <10% without the TST sidebar open to 30-80% **immediately** after opening it, and stays at _at least_ 30% for as long as it's open, then drops back down **immediately** if I close the sidebar. No need to disable the extension; CPU usage rises and falls instantly based solely on whether the sidebar is displayed. This happens with 100% consistency. Given the generous specs of this system, it's not enough to freeze anything, but enough that the effect on other programs (and my CPU temps) is noticeable and unacceptable.

**Comment by irvinm** [comment]
If you go to about:performance, what do you see as the high energy consumers when the sidebar is open?  Does your CPU still spike if TST is not in context in the sidebar?  (ex: showing bookmarks in the sidebar vs. TST)

**Comment by superbeta** [comment]
I find Firefox's task manager to be useless, as it doesn't show pids and _never_ shows _any_ process to be a high energy consumer, even when I expect and can clearly see the opposite to be true using other tools. 

The CPU usage drops immediately if I switch the sidebar from TST to bookmarks, history, or synced tabs, and jumps right back up when I switch it back to TST.

**Comment by hukka** [comment]
For what it's worth, I also see about 4× CPU use when idling with the sidebar in TST mode compared to sidebar closed or showing bookmarks. Interestingly enough, the CPU use is also as high when I am looking at the about:debugging page (having it open on background doesn't matter) no matter if the sidebar is open or closed.

Also profiling any extensions will just give mostly idle profile, with some CC graph reduction calls now and then. Very frustrating, can't seem to get a handle on this.

**Comment by piroor** [comment]
Anyway we need to do [performance profiling](https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-collect-a-performance-profile) instead of guessing without evidence.
I think we may need to collect performance profile on Firefox itself also, because some rendering parts are processed by the chrome process.

**Comment by superbeta** [comment]
For whatever it's worth, this issue went away completely for me after a recent Firefox update. Firefox's CPU usage is lower overall for me after updating, so issues in Firefox rendering seems likely.

**Comment by cab404** [comment]
Still there on Firefox 97, Wayland

**Comment by piroor** [comment]
Patches for optimization are always welcome.

**Comment by loegare** [comment]
I just started having this/similar issue,
Firefox 119
MacOS Sonoma 14.

Occasionally when my computer sleeps when I log back in I'll have warnings saying high memory use, which drops back to acceptable levels after it fully wakes up. the tree style tabs tab in the browser is also blank and needs to be opened/closed for the tabs to return. 

a few weeks ago this was happening while the computer wasn't sleeping, but since I've been looking to see the high usage while i was on the machine it hasn't happened. just this very high use while sleeping and the extension crashing

**Comment by nuclight** [comment]
Same issue with 3.9.20, I was forced to rollback to 3.9.19 which also eats memory, but 7 Gb instead of 19 Gb with 3.9.20.
