### ISSUE TITLE
Tabs toolbar visible again FF 72.0b1

### ISSUE THREAD

**Issue by XakepSDK** [piroor/treestyletab#2426]
## Short description
Tabs toolbar visible again in firefox 72.0b1
I'm using userChrome tweak from this page: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-horizontal-tabs-at-the-top-of-the-window-1349-1672-2147

## Steps to reproduce
1. Enable userChrome via about:config
2. Put tweak css in userChrome

## Expected result
Tweak works

## Actual result
Tweak does not work

## Environment
 * Platform (OS): Arch Linux
 * Version of Firefox: 72.0b1
 * Version (or revision) of Tree Style Tab: 3.2.5
 * userChrome.css: https://gist.github.com/XakepSDK/af4531e65bcbcf4ea846cedda78f70ce

**Comment by irvinm** [comment]
Try removing the namespace line in your CSS.  (https://www.reddit.com/r/FirefoxCSS/comments/dup4vf/firefox_72_breaks_my_tweaks/)

**Comment by XakepSDK** [comment]
It works, thanks.
