### ISSUE TITLE
I want to use SurfingKeys to interact with Tree Style Tabs

### ISSUE THREAD

**Issue by vonHabsi** [piroor/treestyletab#2430]
I use [brookhong/Surfingkeys](https://github.com/brookhong/Surfingkeys) for keyboard driven operation as much as possible and I want to customize it to operate some parts of Tree Style Tabs.

Is there some documentation and examples on how to call TST functions from another addon?

**Comment by irvinm** [comment]
https://github.com/piroor/treestyletab/wiki/API-for-other-addons

**Comment by vonHabsi** [comment]
> https://github.com/piroor/treestyletab/wiki/API-for-other-addons

I have seen that page and it looks complicated to me as I am not familiar with addon programming.

The first part speaks of the addon I'm using registering with Firefox but as it is not an addon I have written myself or ready to adapt that isn't what I have in mind.

I want to know it is possible to call TST functions directly from the keyboard handing code in Surfing Keys. eg the author of Surking Keys help me with this [issue](https://github.com/brookhong/Surfingkeys/issues/933#issuecomment-468683280) where I call the desired functionality directly from the keystroke definition.

Will it possible to cal TST functionality directly in that manner?

**Comment by irvinm** [comment]
The issue that you reference looks to me like it maps a keybind to some JavaScript code.  I don't see how that would work in this situation.  I believe there would need to be a tighter integration to make this happen, like the addon API in the wiki ... which, yes is more complicated.

I guess I will let @piroor comment more on this.

**Comment by piroor** [comment]
You don't need to register an addon. Registration is required only when the addon needs to receive events happening on TST's sidebar. Otherwise you just need to send [API messages](https://github.com/piroor/treestyletab/wiki/API-for-other-addons#manipulate-tree-of-tabs) to TST via `browser.runtime.sendMessage()`. For example:

```javascript
mapkey('<Ctrl-y>', 'Outdent current tab', () => {
    browser.runtime.sendMessage('treestyletab@piro.sakura.ne.jp', {
      type: 'outdent',
      tab: 'current',
      followChildren: true
    });
});
```

**Comment by vonHabsi** [comment]
Is there a list of all the TST API functions or messages?

**Comment by piroor** [comment]
I've created the index: https://github.com/piroor/treestyletab/wiki/API-for-other-addons#appendix-index-of-message-types

**Comment by vonHabsi** [comment]
Which file handles the keyboard shortcuts?

I would like to see how it works and see if I can use the same commands from my SurfingKeys customisations.

**Comment by vonHabsi** [comment]
> I've created the index: https://github.com/piroor/treestyletab/wiki/API-for-other-addons#appendix-index-of-message-types

Hi, I have managed to find out where the commands are defined in manifest.json.

What I need to know now is how the keyboard shortcuts are assigned to the commands at runtime when the user customises them in the Keyboard Shortcuts page.

Do you use your own code for that or is the same code used by Firefox's own Manage Extensions Shortcut page.

**Comment by vonHabsi** [comment]
I have learned enough to get going so I'm closing this issue. Thx to @piroor

**Comment by actionless** [comment]
@vonHabsi have you got any success with it? i've started with it, and managed to show hints on the tabs, but didn't found a nice way how to capture the user input (so at the moment the extension is only showing/hiding tab numbers when you hit the hotkey): https://github.com/actionless/firefox_tst_tabnavigation/blob/master/background.js

**Comment by dufferzafar** [comment]
@piroor I'm trying to achieve something similar. I want to bind a key to collapse ALL tabs of the tree (recursively.)

There doesn't seem to be an alias for "all" tabs. Also, do you know why I'm not able to see any console log / info lines in the Browser Console (Ctrl + Shift + J) or in the Devtools Box of the extension.

```js
mapkey('<Ctrl-y>', 'Collapse the entire tree', () => {
   
    // Neither does this!
    console.log("Now trying to collapse");
    
    let tabs = browser.runtime.sendMessage(TST_ID, {
      type:   'get-tree',
      window: 1
    });
    
    // This doesn't work!
    console.info(tabs);
   
    // Need to iterate on all tabs?
    browser.runtime.sendMessage(TST_ID, {
        type: 'toggle-tree-collapsed',
        tab:  'all',
        recursively: true
    });
});
```

**Comment by piroor** [comment]
@dufferzafar Sorry I'm not familiar to SurfingKeys...
