### ISSUE TITLE
TST Menu flashes and then disappears

### ISSUE THREAD

**Issue by AdventureDave82** [piroor/treestyletab#2432]
## Short description
I went to check my TST Option settings only to see the menu flash on the screen and disappear.  

## Steps to reproduce
Just open the FF Add-on page.  Click on Options for TST.  Both Firefox and the TST Add-on are updated.  I have read your instructions and tried opening a Firefox session without a profile and got the same results (I think I did this right but was confused when the Add-ons that I disabled were also disabled when I returned to my profile session).  I have removed and re-added the Add-on.  I have disabled all other Add-ons.  Sometimes the Options Menu flashes before it disappears and sometimes it's just blank.  Attachment No. 1 is a screenshot of this.  
![1 TST Options Menu Missing](https://user-images.githubusercontent.com/35151180/70946305-d2b49300-200b-11ea-8bfa-cb2fd2711af6.jpg)

Next I clicked on Debug this Add-on.  I got these results - see attachment no. 2
![2 Debug Add-on](https://user-images.githubusercontent.com/35151180/70946313-d7794700-200b-11ea-9f5b-1fa3330ab8cb.jpg)

Next I clicked on Inspect Results and got this - see attachment no. 3
![3 Inspect Results](https://user-images.githubusercontent.com/35151180/70946325-da743780-200b-11ea-814b-177a5ec2b8d8.jpg)

Manifest URL: moz-extension://e6242568-afba-48b5-818d-d24da870c6bb/manifest.json

Okay, hopefully this is a good report for you.  Let me know if you need anything else.

Dave

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Same behavior as before
 4. 

## Environment

 * Platform (OS): Windows 10 Home, Build 18362.535
 * Version of Firefox: 71.0 64-bit
 * Version (or revision) of Tree Style Tab: 3.2.5

**Comment by AdventureDave82** [comment]
I just finished setting up a dual monitor situation.  When I moved the Firefox window to my other display it did NOT have the problem I described above.  That seems like a huge clue.  Let me know what I might need to change on my original laptop settings to avoid this problem on that display.
Thanks,
Dave

**Comment by piroor** [comment]
Two workarounds:

* You can change most of options via the shorthand options menu, please right-click on the "Tree Style Tab" button in the navigation toolbar.
* You can open options page in a regular tab with the URI: `ext+treestyletab:options`.

Anyway, disappearing all options is quite odd result. The inspected result is about the hidden background page, not about the options page. You need to choose `options/options.html` from the list of loaded pages: ![image](https://user-images.githubusercontent.com/70062/70955481-66419e80-20b4-11ea-8bf3-480b96739d60.png) If you see a blank screen in the inspector pane, you may need to choose different page and switch back to the `options.html` to refresh the inspector. If you many elements in the DOM tree of the options page and you see red color boxes on the options page area with hovering on the DOM tree, the problem may be a rendering issue of Firefox itself. Could you try inspection again?

**Comment by AdventureDave82** [comment]
Fixed.  Thank you.
