### ISSUE TITLE
API notification message "scrolled" has deltaY: 0 when shiftKey: true

### ISSUE THREAD

**Issue by amandamana** [piroor/treestyletab#2433]
## Expected result
deltaY should be 1 or -1. A deltaY of zero would mean there was no scroll, but obviously there was as the message was sent.

Note that deltaY is correctly passed when the altKey or ctrlKey are held while using the mouse wheel.

## Environment

 * Platform (OS): macOS 10.11.6
 * Version of Firefox: 71.0
 * Version of Tree Style Tab: 3.2.5

**Comment by amandamana** [comment]
I suspect this is only a problem on platforms where holding shift usually results in a horizontal scroll, i.e., deltaX is changing. I'm not sure how best to address this problem so that add-ons can function properly cross-platform.

**Comment by piroor** [comment]
The property `deltaY` is just relayed from the raw [`wheel` event](https://developer.mozilla.org/en-US/docs/Web/API/Element/wheel_event) synthesized by Firefox itself, and TST doesn't touch that. I think that the listener addon (TST Wheel and Double) needs to handle such special cases.

But I've realized that currently TST doesn't relay `deltaX` and `deltaZ`. After the commit 103ace1 now listener addons can receive full information of the raw event.

**Comment by amandamana** [comment]
Great, thanks!
