### ISSUE TITLE
How can I hide the unmute icon on pinned tabs?

### ISSUE THREAD

**Issue by chinhodado** [piroor/treestyletab#2438]
## Short description

I want to hide the unmute icon on pinned tabs. I have tried many CSS rules but none of them worked.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open any tab with audio and pin it, then mute it
 4. Unmute icon shows up on the tab --> I want to hide this

![image](https://user-images.githubusercontent.com/1388219/71419891-ff862d00-263f-11ea-88e5-f1257fb2b841.png)

I have tried

	tab-item.tab-icon-overlay[muted] {
	    display: none !important;
	}

	.sound-button::before {
	    display: none !important;
	} 

	.tab-content > .tab-icon-overlay {
		display: none !important;
	}

## Environment

 * Platform (OS): Windows
 * Version of Firefox: 71.0
 * Version (or revision) of Tree Style Tab: 3.2.5

**Comment by chinhodado** [comment]
I figured it out, it's just

```
.sound-button {
    display: none !important;
}
```
I actually just disabled the pointer event so I can still see the muted icon
```

.sound-button {
    pointer-events: none !important;
}
```

**Comment by irvinm** [comment]
Thanks for the update @chinhodado.  Can you close this issue?
