### ISSUE TITLE
Open All as a Tree

### ISSUE THREAD

**Issue by wvxwxvw** [piroor/treestyletab#2441]
Point in the context menu of bookmarks "Open &All as a Tree" and "Open All as a Tree including subfolders" should only appear on folders, now they appear on individual bookmarks. And, if used on a separate bookmarks, open all the bookmarks in the folder, and, if this folder has subfolders, the item "Open All as a Tree including subfolders", opens them, too.

This will result in accidental opening of hundreds of tabs and absolutely unnecessary for us.

**Comment by piroor** [comment]
It was intentional but I agree that it is dangerous for a large number of bookmarks. With the commit 1b276ec now these extra context menus are shown only when the menu is opened on a folder.
