### ISSUE TITLE
How can I obtain the id of the current window?

### ISSUE THREAD

**Issue by vonHabsi** [piroor/treestyletab#2445]
I am using SurfingKeys commands to manipulate the tab tree, but some of the API commands need the window id and I am unable to determine it.

When I run this command to scroll down `window: 1` works for the window because I usually have only one window open. When I open more windows the command works only on the first window when I have change to the new window.

How can I get the window id for the current window when I have more than window?

```
mapkey("<Ctrl-]>", "scroll tab pane down", function () {
    console.log("scroll down\n");
 browser.runtime.sendMessage('treestyletab@piro.sakura.ne.jp', {
     type: 'scroll',
     window: 1,
     delta: 100,
     //followChildren: false,
 });
});
```

**Comment by piroor** [comment]
I don't know it is possible or not, but if you can call `browser.windows.getLastFocused()` from the script, it allows you to get the ID of the active browser window like:

```javascript
browser.windows.getLastFocused({}).then(window => {
  browser.runtime.sendMessage('treestyletab@piro.sakura.ne.jp', {
    type: 'scroll',
    window: window.id,
    delta: 100,
  });
});
```

I've introduced a new keyword `active`. It will be available on TST 3.2.7 and later:

```javascript
browser.runtime.sendMessage('treestyletab@piro.sakura.ne.jp', {
  type: 'scroll',
  window: 'active',
  delta: 100,
});
```

**Comment by vonHabsi** [comment]
I made other enquires about `browser.windows.getLastFocused` and wasn't sure about the Promises and async issues. I will give it a try and get back to you.

**Comment by vonHabsi** [comment]
I have tried it out in Nightly and the 'active' addition seems to be working correctly.

I also believe the customizations I'm making are working in the context of a content_script, moz-extension://426005c3-b59e-4e42-8780-6576a35502a7/content_scripts/content_scripts.js, which is why some of the browser functions are not working because they are not available in content scripts.

**Comment by piroor** [comment]
I close this because TST 3.3.4 is now published.
