### ISSUE TITLE
Grouped tabs being ungrouped after Firefox restart?

### ISSUE THREAD

**Issue by SHHSSH** [piroor/treestyletab#2447]
This is a common thing, I'm not sure why it happens. But it's very tedious to have to go through many suspended/grouped tabs just to regroup them when you restart.

Is there a fix for this by any chance? Firefox Dev edition Win 10x64.

**Comment by piroor** [comment]
There is too less information, please fill the issue template.

**Comment by SHHSSH** [comment]
I apologise, don't worry about it. Just delete the issue, it's likely an isolated issue with Developer edition, my other addons, e.g; tab suspender, or something else of the likes. Not a major problem for the majority, so just disregard it. I'll get over it and just group them manually.
