### ISSUE TITLE
Other addons should be able to send messages about tab switch

### ISSUE THREAD

**Issue by pintassilgo** [piroor/treestyletab#2448]
Currently, the only way TST detects tab switching (to define which tab should be selected) is by keyboard shortcuts (Ctrl+Tab, Ctrl+Shift+Tab and Ctrl+PageUp/Down).

Mouse gestures addons like Gesturefy should be able to send messages about tab switch event to TST so that TST can define which tab should be selected based on TST settings (skip collapsed tabs).

For instance, by default Gesturefy uses "hold rightclick then move down then move sideways" to switch to next/previous tab. But this doesn't honour "Don't expand collapsed tree and skip collapsed descendants", collapsed tab is aways selected and its tree expanded.

**Comment by pintassilgo** [comment]
Note: `autoExpandOnCollapsedChildActive = false` seems to solve this incompatibility if I'm switching to the previous tab (which is a collapsed group). But that setting creates a very inconvenient issue in reverse situation: if the selected tab is a collapsed tree and I want to switch to next tab (i.e. the next sibling tab, skipping collapsed tabs). In this case, I can't switch at all using Gesturefy (and my chrome-script), TST keeps switching back to the current tab (the root of the collapsed tree).

**Comment by piroor** [comment]
OK, I've added new aliases `nextVisible` and `previousVisible` (`prevVisible` to specify tabs based on their visibility. You just need to send a JSON message to TST like `{"type": "focus","tab": "nextVisible","silently": true}`. For more details:
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#focus-to-the-nextprevious-sibling-tab
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#basics-to-specify-tabs

**Comment by pintassilgo** [comment]
Thank you. Almost solved for me, there's only a little thing left: tab switching should be cyclical, but `nextVisible` and `prevVisible` are not.

If last tab is focused, `nextVisible` should be the first fisible. Similarly, if first tab is focused, `prevVisible` should be the last.

**Comment by piroor** [comment]
Oops, I missed the point. Now aliases with the suffix `Cyclic` are also available: https://github.com/piroor/treestyletab/wiki/API-for-other-addons#basics-to-specify-tabs
