### ISSUE TITLE
App Tabs are huge in Firefox 10.0 / 10.0.1 on Windows XP

### ISSUE THREAD

**Issue by stevenhaddox** [piroor/treestyletab#245]
I just upgraded to Firefox 10.0, and 10.0.1 this morning at work and upon reloading my app taps went from being the size of favicons (thanks a ton for this btw) to being the size of 9 favicons. It almost looks like it's using half-sized iPhone icons as shown below:

<img src="http://f.cl.ly/items/0O2e3y2R3q060L0Y0a3D/app_tab_growth_treestyle_tabs.jpg" alt="App tab growth image" />

Would love to see this returned back to a more manageable size if at all possible.

Thanks for the great extension. Still the reason I've never migrated to Chrome!

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
