### ISSUE TITLE
CSS is no longer working to hide tabs at the top of the screen

### ISSUE THREAD

**Issue by M-Walrus** [piroor/treestyletab#2450]
the new firefox update has made it so there is a redundant bar of tabs at the top of the screen. I remember when i first learned of the CSS workaround to remove the bar from the top, the feeling that it would only be a matter of time until this broke, and today is that day.

Is there any new method of removing the top bar of tabs from Firefox now, with this newest version 72.0.0?

**Comment by vonHabsi** [comment]
Are you sure haven't fallen afoul of this issue [PSA: Firefox v69 users will have to set a pref to enable userChrome.css and userContent.css](https://old.reddit.com/r/FirefoxCSS/comments/brmi8v/psa_firefox_v69_users_will_have_to_set_a_pref_to/)

I am on Firefox 73 beta and the top row of tabs are still hidden. Try this code in your userChrome.css.

    #TabsToolbar {
      visibility: collapse !important;
    }

**Comment by M-Walrus** [comment]
my about:config already has
toolkit.legacyUserProfileCustomizations.stylesheets | true

userchrome.css copied/pasted here:

@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
#main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #TabsToolbar {
  opacity: 0;
  pointer-events: none;
}
#main-window:not([tabsintitlebar="true"]) #TabsToolbar {
    visibility: collapse !important;
}
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar-header {
  display: none;
}

**Comment by vonHabsi** [comment]
TBH this is an area I'm not that expert in, only that it works for me and there may be some settings in yours which don't work in mine.

Have you considered removing the `#main-window:not([tabsintitlebar="true"])` to check?

**Comment by Trelor** [comment]
I had the exact same issue and I used to have
`
#main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #TabsToolbar > .toolbar-items {
    opacity: 0;
    pointer-events: none;
  }
`
which I had to change to 
`
#TabsToolbar > .toolbar-items {
    opacity: 0;
    pointer-events: none;
  }
`

after that change I stopped seeing the active tab across the top of the screen

**Comment by piroor** [comment]
It is not an issue of TST itself. Please remind that this is an issue tracker but not a forum. 

Code snippets for userChrome.css is not maintained well by me so I hope that it is updated by people who use userChrome.css.

**Comment by wvxwxvw** [comment]
@Trelor 
I have everything in one. Hides the tab bar and title bar. Buttons to control any window down in the navigation bar. Calling the menu bar by Alt, calls it on top of other panels (background transparency can be adjusted). You can use the menu bar to place buttons in it. You can use the space under the window control buttons to drag the window.
If you try my code, disable your associated styles for the tab bar, menu bar, title bar, and navigation bar. Depending on the OS and screen resolution, you may need to edit the code yourself, on Windows 7-8. 1, with Aero themes, with a screen resolution of 100% should work without unnecessary edits.
The code is made in the corresponding topic forum.mozilla-russia.org
`#main-menubar > menu {
    -moz-appearance: none !important;
}
#toolbar-menubar[autohide="true"]:not([customizing="true"]) {
    position: relative !important;
    z-index: 3 !important;
    background-color: var(--toolbar-bgcolor, -moz-dialog) !important;
    background-image: var(--toolbar-bgimage, none) !important;
    color: var(--toolbar-color, -moz-dialogtext) !important;
    -moz-box-align: start !important;
    padding-top: 0 !important;
    padding-bottom: 0 !important;
    border-top-width: 0 !important;
    border-bottom-width: 0 !important;
}

/* The height of the menu bar also affects the size of the added buttons */
#toolbar-menubar[autohide="true"]:not(:-moz-any([inactive="true"],[customizing="true"])) {
    height: 21px !important;
    margin-bottom: -21px !important;
}

*|*:root:not([inFullscreen])[tabsintitlebar] #navigator-toolbox > #titlebar {
    -moz-appearance: none !important;
}
*|*:root:not([inFullscreen])[tabsintitlebar][sizemode="maximized"] #navigator-toolbox {
    -moz-appearance: -moz-window-titlebar-maximized !important;
}
/* Indent on the right for navigation bar buttons to make room for window control buttons */
*|*:root:not([customizing="true"]) #nav-bar {
    padding-inline-end: 105px !important;
}
*|*:root:not([customizing="true"]):not([inFullscreen])[tabsintitlebar][sizemode="normal"] #nav-bar {
    padding-inline-start: 5px !important;
    padding-inline-end: 105px !important;
}
*|*:root:not([customizing="true"]) #TabsToolbar {
    height: var(--tab-min-height, 29px) !important;
    max-height: none !important;
    margin-bottom: calc(-1 * var(--tab-min-height, 29px)) !important;
    overflow: hidden !important;
    -moz-appearance: none !important;
    visibility: hidden !important;
    -moz-box-align: start !important;
    padding-top: 0 !important;
    padding-bottom: 0 !important;
    border-top-width: 0 !important;
    border-bottom-width: 0 !important;
}
#toolbar-menubar[autohide="true"][inactive="true"] + #TabsToolbar > .titlebar-buttonbox-container,
*|*:root[inFullscreen] #TabsToolbar > #window-controls {
    visibility: visible !important;
    position: relative !important;
    z-index: 3 !important;
}
*|*:root:not([customizing="true"]) #tabbrowser-tabs {
    visibility: visible !important;
    min-height: 0 !important;
    height: 0 !important;
    max-height: 0 !important;
    overflow: hidden !important;
}

/* Adjustments for Windows 7 - 8 */
@media (-moz-windows-compositor) {
    @media (-moz-os-version: windows-win7), (-moz-os-version: windows-win8) {
#toolbar-menubar[autohide="true"]:not(:-moz-any([inactive="true"],[customizing="true"])) {
    margin-top: 1px !important;
    margin-left: 1px !important;
    margin-right: 1px !important;
    }
/* Here you can set the margin from the top edge of the window */
*|*:root:not([inFullscreen])[tabsintitlebar][sizemode="normal"] #titlebar {
    min-height: 5px !important;
    }
/* Fix full screen mode */
*|*:root:not([inFullscreen])[tabsintitlebar][sizemode="maximized"] #titlebar {
    max-height: 0px !important;
    }
  }
}

/* Padding for buttons in menubar, if you add them */
#toolbar-menubar {
    --toolbarbutton-outer-padding: 4px !important;
    --toolbarbutton-inner-padding: 1px !important;
}
#toolbar-menubar .toolbarbutton-1 {
    padding-top: 2px !important;
    padding-bottom: 2px !important;
}
`

**Comment by wvxwxvw** [comment]
Here I found an animation that demonstrates the behavior of the style.
[https://b.radikal.ru/b41/1912/10/ca561fbd7102.gif](url)

**Comment by Dystopian** [comment]
@M-Walrus just remove the 1st line from your userChrome.css with `@namespace url`. Found it [there](https://bugzilla.mozilla.org/show_bug.cgi?id=1605208).

**Comment by M-Walrus** [comment]
thank you everyone who chimed in with advice and userchrome.css snippets here. 

closing this issue as it is now resolved.
