### ISSUE TITLE
Keyboard shortcuts to duplicate tab

### ISSUE THREAD

**Issue by ElhemEnohpi** [piroor/treestyletab#2452]
I use "duplicate tab" very often, but it is missing from the list of keyboard shortcuts. For example if I want to go to another page on the same website by doing a search instead of clicking a link, I can duplicate the tab and then search.

Ideally there could be four, "duplicate as:" (independent/child/sibling/next sibling). Thanks for considering this!

**Comment by piroor** [comment]
If you simply need a keyboard shortcut for a Firefox's builtin feature "duplicate tab", it looks out of TST's scope. Instead something other addons for the purpose may help you.

Duplicate Tab Shortcut
https://addons.mozilla.org/ja/firefox/addon/duplicate-tab-shortcut/
Duplicate Tab Hotkey
https://addons.mozilla.org/ja/firefox/addon/duplicate-tab-hotkey/

TST has an option to control how a duplicated tab should be treated. It should be effective for cases triggered by such addons.

**Comment by SHHSSH** [comment]
Realistically, it's actually pretty similar to most universal duplication hotkeys.

Many are Ctrl+D, Ctrl+J or something or the sorts, unfortunately this obviously conflicts with many of Firefox's other hotkeys.


So what you do (without any 3rd party addons) is simply Alt+D to select the URL bar KEEP Alt-down, then simply press enter again, this will create a new tab of the currently tab.

Obviously this doesn't work with the standard Ctrl+L URL hotkey, as you need to keep Alt held down.


1. Alt-D
2. Keep Alt-down
3. Alt-Enter
4. Duplicated tab

**Comment by ElhemEnohpi** [comment]
> If you simply need a keyboard shortcut for a Firefox's builtin feature "duplicate tab", it looks out of TST's scope.

In legacy TST (still using in Waterfox), I have separate keyboard shortcuts to duplicate a tab as a child, sibling, etc., and I find it very useful. I'm starting to switch back to latest Firefox, and I'd like to have it there too.

For example, "new tab" is also a built-in feature, but TST provides shortcuts for new tab as child, sibling, etc. Most of the other "Maniuplate Tree of Tabs" API is available as keyboard shortcuts, so I hoped this could be available too, thanks.

**Comment by piroor** [comment]
> For example, "new tab" is also a built-in feature, but TST provides shortcuts for new tab as child, sibling, etc. Most of the other "Maniuplate Tree of Tabs" API is available as keyboard shortcuts, so I hoped this could be available too, thanks.

I think that the "New Tab" command and "Duplicate Tab" have different level of context for each.

"New Tab" is a generic command, and there is no hint to determine how the tab should be opened as a child, a sibling, or an independent. You may open a new tab for various purposes, to start a new different context, or to start a sub task for the current tab.

On the other hand, "Duplicate Tab" has a hint to determine how it should be treated - the new tab is just a "duplicated" tab of an existing tab. This is the reason why TST doesn't provide various "duplicate tab as..." choices as commands directly-callable.

I must make decisions about all commands: "include" or "exclude". And I also try to provide APIs to implement such dropped options as helper addons. I think: if you seriously need those options it is the time to do that by your hand.

**Comment by ElhemEnohpi** [comment]
Ok, I understand. I hoped it would be simple and easy for you to add a few more commands to the list. Thanks anyway. Eventually I will try to make my own extension to add functions to TST, but I think it will take me a long time to learn how. In the meantime maybe I can find a utility for my computer to combine multiple shortcuts to get the same effect, like first "duplicate" then "outdent".

**Comment by piroor** [comment]
Don't worry, you may not need to create a new addon from scratch. I think you just need to find small addons which provide just one or more shortcuts, and modify its shortcut and its corresponding code. Then you just need to call TST's API via `browser.runtime.sendMessage()`. Documents:

* https://github.com/piroor/treestyletab/wiki/API-for-other-addons#abstract
* https://github.com/piroor/treestyletab/wiki/API-for-other-addons#duplicate-tab-as-childsibling-tab

**Comment by irvinm** [comment]
@ElhemEnohpi can you close this item?  (You can obviously continue to ask questions as needed even when it is closed)

**Comment by ElhemEnohpi** [comment]
Thanks for the info, I'll look into modifying another addon to provide the shortcut.

**Comment by ElhemEnohpi** [comment]
Thanks for the info, I'll look into modifying another addon to provide the shortcut.
