### ISSUE TITLE
When use dark theme and auto hide, i see light gray color splash when unhide tree tab bar

### ISSUE THREAD

**Issue by OmTatSat** [piroor/treestyletab#2454]
When use dark theme and auto hide, i see light gray color splash when unhide tree tab bar

I recorded video, how it is look like https://drive.google.com/open?id=12VZNM0x1msw0nvQFyEnocApg1zjxq72M

Would be great if set this splash to black color

win10x64 
cpu - xeon e5-1650v2, ram - 32gb, video - nvidia 1060 3gb.

**Comment by piroor** [comment]
userChrome.css issue is not a problem of TST itself but in the area of Firefox itself. Sadly TST cannot do anything about this.

**Comment by OmTatSat** [comment]
> 
> 
> userChrome.css issue is not a problem of TST itself but in the area of Firefox itself. Sadly TST cannot do anything about this.

Maybe you know what can i change in userChrome.css to fix this behavior?

**Comment by piroor** [comment]
I've not researched it yet but I think it looks hard to be fixed with simple userChrome.css hack.

Sorry but now I'm not a userChrome.css master anymore. I hope that userChrome.css code snippets are maintained by themselves who seriously requires that...

**Comment by irvinm** [comment]
@OmTatSat I would suggest posting something on Reddit under r/FirefoxCSS (https://www.reddit.com/r/FirefoxCSS/) as there are some very knowledgeable CSS people there and many have TST experience.

Can you also close this item?

**Comment by OmTatSat** [comment]
Thank you, i will try find solution there.

**Comment by OmTatSat** [comment]
Solution was found
`:root {
  --sidebar-hover-width: 90px;
  --sidebar-visible-width: 400px;
}

#sidebar-box {
  position: relative !important;
  overflow-x: hidden !important;
  margin-left: -9px !important;
  transition: all 1s!important;
  min-width: var(--sidebar-hover-width) !important;
  max-width: var(--sidebar-hover-width) !important;
  
}

#sidebar-box:hover {
  margin-left: calc(var(--sidebar-visible-width) * -1 + var(--sidebar-hover-width) - 9px) !important;
  right: 99px !important;
  transition: all 0s!important;
  min-width: var(--sidebar-visible-width) !important;
  max-width: var(--sidebar-visible-width) !important;
  opacity: 1 !important;
  
  
}

#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] {
  overflow: hidden;
  min-width: 90px;
  max-width: 90px;
  transition: all 0.2s ease;
  border-right: 1px solid #0c0c0d;
  z-index: 2;
}

/*Expand to 260px on hover*/
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"]:hover,
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar {
  min-width: 400px !important;
  max-width: 400px !important;
  z-index: 1;
}`
