### ISSUE TITLE
focus nextvisible (and similar) is skipping non-collapsed tabs after moving tab to another group

### ISSUE THREAD

**Issue by pintassilgo** [piroor/treestyletab#2455]
STR

**1.** Install TST 3.3.2;
**2.** TST Options > select `Fix up tree structure with visible tabs automatically (*Recommended if you use another addon to switch tab groups)`;
**3.** Install [Tiled Tab Groups 0.18.12](https://addons.mozilla.org/en-US/firefox/addon/tiled-tab-groups/) (also tested with Simple Tab Groups, but steps-to-reproduce are easier with TTG);
**4.** Structure your tabs like this:
- Tab 1 (expanded tree)
- - Tab 2
- Tab 3
- Tab 4

**5.** Make some tests with
```
    browser.runtime.sendMessage(kTST_ID, {
      type:     'focus',
      tab:      'nextvisiblecyclic',
      silently: true
    });
```
you'll see that as for now it's all right.

**6.** Focus on Tab 4, rightclick it, `Move Tab to group > Move Tab to New Group`. The view will change to this new group, with focus still on Tab 4.
**7.** Go back to the other group (click Tiled Tab Groups button, then Group 0);
**8.** Make new tests with `nextvisiblecyclic` (or any similar alias). Tab 2 will never be focused, despite being visible and member of an expanded tree.

This issue only happens with `Fix up tree structure with visible tabs automatically (*Recommended if you use another addon to switch tab groups);` selected, which is essential for anyone like me who uses a tab groups addon.

**Comment by SHHSSH** [comment]
Followed all prompts, I [was able to select Tab 2 no problem](https://imgur.com/JbWNk2r).

Maybe [this](https://imgur.com/CBKQHwi) is your problem, make sure it is NOT ticked.

**Comment by pintassilgo** [comment]
@SHHSSH this issue is not about Ctrl+Tab/Ctrl+Shift+Tab, it's about `focus` API using alias like `nextVisibleCyclic` and `prevVisibleCyclic`.

You can test it in DevEd or Nightly setting `xpinstall.signatures.required = false`, then installing [this test addon](https://filebin.net/9ozt7mppyxnfdfly/keyWebextHelper.xpi) and pressing Shift+Alt+F1 or Shift+Alt+F2.

**Comment by piroor** [comment]
Thanks! The commit b06a206 should fix this.
