### ISSUE TITLE
TST stops working after bug 1565170

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#2456]
## Short description
[Bug 1565170 - Disable toSource/uneval in non-chrome code](https://bugzilla.mozilla.org/show_bug.cgi?id=1565170)

TST sidebar cannot be initiated after updating to Nightly 2020-01-10 build (20200110220030). It is regressed by bug 1565170 according to Mozregression.

## Steps to reproduce

 1. Start Nightly 2020-01-10 with clean profile.
 2. Install TST.
 3. Observe the TST sidebar.

## Expected result
Sidebar shows the tabs.

## Actual result
Sidebar keeps loading.

## Environment

 * Platform (OS): Win 10 1909
 * Version of Firefox:  Nightly 2020-01-10 build (20200110220030)
 * Version (or revision) of Tree Style Tab:  `3.3.2` and `3.3.2.9933.9933`

**Comment by hbriese** [comment]
I'm having the same issue

## Environment
 * Platform (OS): Ubuntu 19.04 (5.3.0-26 kernel)
 * Version of Firefox: 74.0a1 (2020-01-10)
 * Version (or revision) of Tree Style Tab: 3.3.2

**Comment by myessail** [comment]
Same issue here,

### Environment
    Platform (OS): macOS Mojave 10.14.6
    Version of Firefox: 74.0a1 (2020-01-10) (20200110220030)
    Version (or revision) of Tree Style Tab: 3.3.2

**Comment by Fanolian** [comment]
Here are some error messages in *Browser Console* that are new after bug 1565170:
(You can only see them by enabling `Show Content Messages` from Browser Console's gear icon on top right)

```
ReferenceError: uneval is not defined                common.js:393:43
    log              moz-extension://8d6444a9-20be-4010-b9d3-f875215ff4e7/common/common.js:393
    reduce           self-hosted:303
    log              moz-extension://8d6444a9-20be-4010-b9d3-f875215ff4e7/common/common.js:392
    $log             moz-extension://8d6444a9-20be-4010-b9d3-f875215ff4e7/extlib/l10n.js:18
    updateSubtree    moz-extension://8d6444a9-20be-4010-b9d3-f875215ff4e7/extlib/l10n.js:45
    updateDocument   moz-extension://8d6444a9-20be-4010-b9d3-f875215ff4e7/extlib/l10n.js:51
    <anonymous>      moz-extension://8d6444a9-20be-4010-b9d3-f875215ff4e7/extlib/l10n.js:56
    (Async: EventListener.handleEvent)
    <anonymous>      moz-extension://8d6444a9-20be-4010-b9d3-f875215ff4e7/extlib/l10n.js:55
    InnerModuleEvaluation        self-hosted:1605
    InnerModuleEvaluation        self-hosted:1594
    evaluation       self-hosted:1559

```

```
TypeError: this.$TST is undefined             TabElement.js:158:13
    initializeContents      moz-extension://8d6444a9-20be-4010-b9d3-f875215ff4e7/sidebar/components/TabElement.js:158
    _onOverflow             moz-extension://8d6444a9-20be-4010-b9d3-f875215ff4e7/sidebar/components/TabLabelElement.js:135
    _onOverflow             self-hosted:876
    (Async: EventListener.handleEvent)
    _startListening         moz-extension://8d6444a9-20be-4010-b9d3-f875215ff4e7/sidebar/components/TabLabelElement.js:119
    connectedCallback       moz-extension://8d6444a9-20be-4010-b9d3-f875215ff4e7/sidebar/components/TabLabelElement.js:60
    define                  moz-extension://8d6444a9-20be-4010-b9d3-f875215ff4e7/sidebar/components/TabLabelElement.js:16
    init                    moz-extension://8d6444a9-20be-4010-b9d3-f875215ff4e7/sidebar/sidebar.js:122
    (Async: EventListener.handleEvent)
    <anonymous>             moz-extension://8d6444a9-20be-4010-b9d3-f875215ff4e7/sidebar/index.js:28
    InnerModuleEvaluation   self-hosted:1605
    evaluation              self-hosted:1559
```

**Comment by Etrit1** [comment]
I'm having the same issue.  It's actually be having problems with the last few Nightly builds but, has always worked... eventually.  Now, nadda.

I really don't understand why Mozilla keeps breaking addons.  Yes, I know there are tons of addons and that Mozilla isn't responsible for them.  But come on, there HAS to be a way to do adaptive code in addons OR for Mozilla to stop changing things that clearly were working fine and that those changes break addons.

**Comment by piroor** [comment]
Fixed by the commit f94995b.

**Comment by wsmwk** [comment]
> It's actually be having problems with the last few Nightly builds but, has always worked... eventually. Now, nadda.
> 
> I really don't understand why Mozilla keeps breaking addons

You were broken because you are nightly, and hopefully you understand how nightly works.  Nightly isn't a branch that gets testing - things break without warning. Also, sometimes the breakage is intentional - as in the present case documented at https://www.fxsitecompat.dev/en-CA/docs/2020/tosource-and-uneval-have-been-removed/   It's the nature of the beast.

**Comment by Etrit1** [comment]
Wait, nightly doesn't get any testing at all?
Wierd.

And thanks for the link to what changed.

I actually only was on Nightly because it ran better on my computer then
the standard build. Or at least used to. I hadn't used the standard in over
a year. I just switched back because of this problem though... Maybe the
issue I was having with standard was fixed by now.

**Comment by piroor** [comment]
Firefox Nightly is tested around itself based on automated tests, but complete addon compatibility is out of the scope. Addon authors including me may test their addons with Nightly and often update them until the version is released as a stable version.

"Nightly" was called "Minefield" officially in old days. Please remind that Nightly has higher risk than other channels.

**Comment by Movisivi** [comment]
Thank you for fixing this so quickly @piroor

**Comment by SicariusNoctis** [comment]
> Fixed by the commit [f94995b](https://github.com/piroor/treestyletab/commit/f94995bcdf18ba1d4eab08affc9a2ad96c504866).

Another Nightly user here. Manually applying this patch fixes things, though my tabs now load within 20 seconds rather than 5 seconds. The commit doesn't seem to contain anything that would cause this so it's probably unrelated.

**Comment by jnachtigall** [comment]
Temporarily workaround for Nightly until the fix with 3.3.3 release gets published on AMO:

1. Go to `about:config`
2. Search for `xpinstall.signatures.required` and set it to `false`
3. Go to https://github.com/piroor/treestyletab/releases and click on the 3.3.3 xpi 
4. Install

When the fix is available on AMO, do not forget to reset `xpinstall.signatures.required`

**Comment by timvisee** [comment]
Will it be kept up-to-date after this manual installation, or does this 
disable the updater?

**Comment by jnachtigall** [comment]
> Will it be kept up-to-date after this manual installation, or does this disable the updater?

I do not know. Anyway, I could not really work so i did it. I just overwrote the existing 3.3.2 so I'd think in worst case I'd have to reinstall from AMO that would again overwrite the manual installation.

**Comment by piroor** [comment]
Currently TST's unsigned builds has no update information. Then the auto-update feature of Firefox refers its default source (Mozilla Add-ons). If TST 3.3.4 or newer versions are published to AMO you'll get updated versions automatically.

**Comment by diox** [comment]
3.3.4 is now out on AMO.
