### ISSUE TITLE
Root tab unwantedly becomes child of the previous tree

### ISSUE THREAD

**Issue by pintassilgo** [piroor/treestyletab#2457]
I think we are approaching optimal compatibility with tab groups addons, thanks for all recent fixes.

---

STR

**1.** Install TST 3.3.3;
**2.** TST Options > select `Fix up tree structure with visible tabs automatically (*Recommended if you use another addon to switch tab groups)`;
**3.** Install [Tiled Tab Groups 0.18.12](https://addons.mozilla.org/en-US/firefox/addon/tiled-tab-groups/)
**4.** Create a second group (Group 1), then switch back to Group 0.
**5.** Prepare your tabs like this:

* Tab 1 (expanded)
  * Tab 2

**6.** Open a new tab (Tab 3). It will be a root placed in the last position.
**7.** Switch the view to Group 1.
**8.** Switch back to Group 0.

After a short delay, you will see Tab 3 automatically turning into the next sibling of Tab 2, inside the tree. This is unwanted, Tab 3 should remain a root.

**Comment by pintassilgo** [comment]
This is a regression. With TST 3.3.2 this issue is not reproducible.

**Comment by pintassilgo** [comment]
Regressed by b06a2061951203ee700e6414cbdeb3816f41d9a3.

**Comment by piroor** [comment]
Thanks! Basically there was such a risk and the commit a6ed557 should stabilize the result on the case.

**Comment by pintassilgo** [comment]
Thank you!

---

One thing I'm experiencing now with the latest build is that sometimes a new tab (Ctrl+T) is being created at the end of the bar even though I have all the settings to open it as the next sibling of the current tab.

Another thing that I noticed now: if the focus is on the root of a collapsed tree, I open a new tab (Ctrl+T), close it (Ctrl+W), the focus returns to the root of a collapsed tree, then if I press Ctrl+Tab nothing happens. I need to press it again to switch to next tab (skipping the collapsed tree). 

I need to leave now, if you can't understand these new issues, later I'll create new issues about these two things with STR.

**Comment by piroor** [comment]
> One thing I'm experiencing now with the latest build is that sometimes a new tab (Ctrl+T) is being created at the end of the bar even though I have all the settings to open it as the next sibling of the current tab.

What a URL do you use as the new tab page? TST guesses a tab is a new blank tab if the URL is same to the predefined option (it is "about:newtab" by default). If you customize it with other addons you need to set its new tab URL manually with the TST's options page. I hope that you successfully find out the condition to reproduce the problem and report it as a new issue in near future.

> Another thing that I noticed now:...

Thanks, it was a bug and fixed with the commit 9f645f5.

> I need to leave now, if you can't understand these new issues, later I'll create new issues about these two things with STR.

The first one needs to be posted as a new issue. The second one looks to be fixed for me, but if it still happens on your environment, please post a new issue for that. Separate issue for each problem make things easier to be tracked.

**Comment by pintassilgo** [comment]
> What a URL do you use as the new tab page?

`browser.startup.homepage = "about:blank"`
(but `browser.startup.page = 3` to recover previous session)
So, of course,
*✓ Guess a newly opened tab as opened by "New Blank Tab" action, when it is opened with the URL `about:blank`*
I don't use nothing else to handle these things.
I'm struggling to find a pattern on how to reproduce this, it seems to be quite random. As soon as I can (if I can) I'll create a new issue.

**Comment by irvinm** [comment]
@pintassilgo can you close this item and open a new one later if needed?
