### ISSUE TITLE
Tooltip persists over other windows while Firefox is in background

### ISSUE THREAD

**Issue by Vanav** [piroor/treestyletab#246]
In some cases Firefox tooltip persists over other windows while Firefox window is in background. The only way to hide tooltip is to move mouse to it or to move mouse to Firefox window.

In everyday work this bug appears after following actions:
1. Move mouse from Firefox window outside, to other window or task bar, and cross tab tree on its way,
2. When mouse is already outside Firefox window (or over other window), tooltip appears, as if mouse is still over tab tree. It looks like Firefox remembers old mouse coordinates.

This issue is a bit hard to reproduce, but always possible.
First way to reproduce, with simple tooltip:
1. Place Firefox window in the middle of desktop. Focus Firefox window.
2. Hover mouse over tab button for a bit (tooltip should not appear yet, but not too short), then move mouse to the left, outside of Firefox and click on desktop.
3. Tooltip will appear and will persist over other windows ([screenshot 1](http://screencast.com/t/VFYhlxs0rEqK), [screenshot 2](http://screencast.com/t/79CDGUKum1fB)).

Second way to reproduce, with rich TST tooltip:
1. Choose one tab button. Move any other window, so it partially overlaps half of this tab button.
2. Without focusing Firefox, move mouse over a tab. Wait for some seconds till the moment when tooltip should appear.
3. Without leaving the area of tab, move mouse over other active window. Tooltip will keep showing permanently on screen, until you move mouse over it, or mouse over Firefox window ([screenshot](http://screencast.com/t/EmfAKY4MmGp)).

My environment: Windows 7 x64, Firefox 10.0.2 (also tested with Nightly x64).

Notes:
- it doesn't matter if Firefox has focus or not (but more easy to reproduce with focus switch),
- mouse can leave Firefox window area, and tooltip will still appear after mouse has left,
- there may be no other window, just move mouse outside Firefox window will trigger the issue,
- this is an issue with any Firefox tooltips,
- if issue is triggered, you can see that color animation of tab freezes,
- I have “extensions.treestyletab.tooltip.mode = 0”, issue occurs less frequently, but tooltip still persists often during a day.

This looks like a Firefox bug. The most exact description of this issue is [bug 631462](https://bugzilla.mozilla.org/show_bug.cgi?id=631462). Some other similar issues: [bug 148624](https://bugzilla.mozilla.org/show_bug.cgi?id=148624), [bug 618733](https://bugzilla.mozilla.org/show_bug.cgi?id=618733) and [bug 131131](https://bugzilla.mozilla.org/show_bug.cgi?id=131131).

If it is hard to fix, can you please give an setting to disable tooltips for tab tree completely?

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.

**Comment by jarredou** [comment]
This is happening again.

**Comment by piroor** [comment]
@jarredou This legacy issue is for XUL-version TST. Today TST is reconstructured on WebExtensions API so this is out of context.
