### ISSUE TITLE
not working on FireFox74.0a1 (2020-01-14) (64 bit) windows

### ISSUE THREAD

**Issue by kyonmm** [piroor/treestyletab#2462]
## Short description
Firefox 76 Nightlyビルドで実行したところローディングでストップしてしまいました。

## Steps to reproduce
1. FireFox74.0a1 (2020-01-14) (64 bit) windows にアップデート
2. about:profilesにて新規プロファイル作成
3. 1のプロファイルでFirefoxを起動
4. https://addons.mozilla.org/ja/firefox/addon/tree-style-tab/ をひらいて Tree Style Tabを インストール
5. ローディングでとまってしまう

なお、既存プロファイル(いつもつかっているプロファイル)では、Firefoxを76に更新して再起動したときにローディングでとまってしまいました。

![2020-01-15_17h04_03](https://user-images.githubusercontent.com/839274/72416290-aed69f80-37b9-11ea-9c02-e9b71aa55419.png)

## Expected result
開いているタブが表示されていてほしい。この場合だと2つのタブがおなじインデント。

## Actual result
ローディングでとまる

## Environment

 * Platform (OS): Windows
 * Version of Firefox: 74.0a1 (2020-01-14) (64 bit) Nightly
 * Version (or revision) of Tree Style Tab: latest

**Comment by piroor** [comment]
#2456 と同じ話のように思われます。

**Comment by irvinm** [comment]
@piroor can you close this one?
