### ISSUE TITLE
Undo close tab

### ISSUE THREAD

**Issue by wvxwxvw** [piroor/treestyletab#2465]
Is it possible to make a submenu "Closed tabs" instead of this item "Undo close tab" or a plus to it?

**Comment by wvxwxvw** [comment]
Here is a script, but it adds a menu to the page menu. Just an example.
[https://github.com/alice0775/userChrome.js/blob/master/68/UndoListInTabmenuToo.uc.js](url)

**Comment by piroor** [comment]
"Undo Close Tab" addon provides a menu listing closed tabs in the context menu on tabs.
https://addons.mozilla.org/firefox/addon/undoclosetabbutton/
It is hidden by default and you need to activate it manually via its options page.

**Comment by wvxwxvw** [comment]
@piroor 
Yes, this is what need.
