### ISSUE TITLE
Dragging tab across trees sometimes automatically collapses originating tree

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2466]
## Steps to reproduce

@piroor I am still working on more concrete steps to reproduce, but the behavior is described below.  However, this behavior is not consistent but I am seeing it several times a day.

 1. Create tree "A" (OK)
 2. Create sibling tree "B" (OK)
 3. Drag any CHILD tab from tree "B" and drag on top of tree "A" (OK)
 4. Tree "A" will expand and insert the new tab in that tree. (OK)
 5. Tree "B" will now collapse although all options for "auto collapsing" trees are disabled. (BUG)

## Expected result
With the following options, I would expect the trees to not "automatically collapse".

![2020-01-15_15-04-59](https://user-images.githubusercontent.com/979729/72468432-281ac600-37ab-11ea-91f2-75de49ee92ea.jpg)

## Actual result
Tree "B" automatically collapses sometimes.  (I'm working to isolate and come up more concrete scenarios.)

## Environment

 * Platform (OS): Windows 10 (1909)
 * Version of Firefox:  72.0.1
 * Version (or revision) of Tree Style Tab:  Seen with 3.2.2 and 3.2.4.  (I have only seen this over the last few weeks at most ... feels like a possible regression.)

Could there be a situation when dropping a tab where the configuration option is not checked to see if a tree should be automatically collapsed?  (I see you have added some new features around locking trees, etc.)

**Comment by piroor** [comment]
I think this is triggered due to a combination of an option "Expand collapsed tree with hovering over XXX msec while dragging" and a hidden option `autoExpandIntelligently`. When the first option is checked and the second option is `true`, TST expands a long-dragover tree and collapse others automatically. At the next version I'll add an expert option UI for the hidden second option.

**Comment by piroor** [comment]
After the commit 306bfe1 you can change the second hidden option via a checkbox.

**Comment by irvinm** [comment]
Thanks @piroor, I will play around with that when it lands.
