### ISSUE TITLE
Ctrl+Shift+Tab does nothing under specific condition

### ISSUE THREAD

**Issue by pintassilgo** [piroor/treestyletab#2468]
STR in a new profile

**1.** TST Nightly;

**2.**
- `browser.ctrlTab.recentlyUsedOrder = false`
- `browser.startup.page = 3`

**3.** TST settings:
```
{
  "avoidDiscardedTabToBeActivatedIfPossible": true,
  "configsVersion": 8,
  "notifiedFeaturesVersion": 4,
  "optionsExpandedSections": [
    "section-debug"
  ],
  "skipCollapsedTabsForTabSwitchingShortcuts": true
}
```
P.S.: `skipCollapsedTabsForTabSwitchingShortcuts` must be manually set by clicking "Don't expand collapsed tree and skip collapsed descendants (...)" because you need to accept extra permission.

**4.** Prepare your tabs:
- Tab 1 (collapsed)
  - Tab 2
- Tab 3
- about:profiles

**5.** In about:profiles, click "Restart normally...".

**6.** Click on Tab 3.

**7.** Press Ctrl+Shift+Tab.

Tab 1 should be focused, but nothing happens.

**Comment by pintassilgo** [comment]
Extra issue: read Step 4's note above. When importing config that needs extra permission, no prompt asking for permission is displayed. So the pref that needs the permission is reset on Firefox restart without any warning to the user.

**Comment by piroor** [comment]
Thanks, the commit 5ecbe0b should fix this.
