### ISSUE TITLE
hide top row of tabs

### ISSUE THREAD

**Issue by manebule** [piroor/treestyletab#2470]
I just transitioned from Window 7 to a fork of Linux Mint. I used TST in W7 for years _without_ horizontal tabs or the bulky "Tree Style Tab" tab. I didn't have to do anything to achieve that...; that's how it ran out of the box. I just installed the TST (3.3.4) extension in Firefox (72.0.1 64-bit) and now I've got tabs both on top (ugh...) and treed on the side (yay!). I have no other extensions installed (this is the first extension I've installed [i.e., important!]), so I don't think this behaviour is the result of interaction with another extension. I searched through TST extension properties, but didn't find a toggle to change this behaviour. Any help appreciated!

**Comment by irvinm** [comment]
@manebule everything you need (I believe) is on the wiki.  https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules

TST doesn't change any of those things and you need to use CSS in userChrome.css to make the changes.

**Comment by cortic101** [comment]
And don't forget on Firefox 69+ go to about:config and set 
toolkit.legacyUserProfileCustomizations.stylesheets to true to use userChrome.css

**Comment by irvinm** [comment]
@manebule did this help?  Can you close this item if so?

**Comment by manebule** [comment]
Yes, the "code snippet" did what I needed. A bit of a kludge, but, hey, it _looks_ fine! ;-)
Just one further comment: you might add a little section at the top of the wiki about the potential need to actually create a userChrome.css file in a chrome folder (which might also need to be created) in one's Firefox profile, for people like me who don't do this every day... :-P
Thanks!
