### ISSUE TITLE
TST reloads (sometimes) when parent of auto-grouped tabs auto-closes

### ISSUE THREAD

**Issue by gonhidi** [piroor/treestyletab#2471]
## Short description

Quickly opened tabs can be grouped together under a temporary parent tab. By default, if that parent tab loses all its children it closes automatically. Sometimes this makes the TST sidebars reload.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open two new tabs (A, B) quickly so the grouping prompt shows (one can configure the time window for grouping in TST's options to make it easier to trigger this).
 4. Select the option to group the two tabs, which creates a (temporary) parent tab (C) for them.
 5. Drag the two tabs (A, B) off the parent tab (C).

```
C (auto-created by choosing to group A and B)
\- A (new tab)
|- B (new tab quickly created after A)
```

## Expected result

The parent tab (C) should close per its default settings (“Close this tab when there are no more children”). Nothing else should happen.

## Actual result

After the parent tab closes, the TST sidebar sometimes reloads.

## Observations

I have only seen the behaviour happen when the last child tab is dragged off (neither closing it by keyboard shortcut nor by middle-clicking on the tab seems to trigger it). Even then, the reloading of the sidebars does not always happen.

The trees of tabs seem to restore correctly, so the only obvious user-facing problem is the time it takes to reload. This depends on the number of tabs and windows (the behaviour affects all TST sidebars, not just the one of the current window).

## Environment

 * Platform (OS): macOS 10.14.6. Also seen on a Windows 10 virtual machine.
 * Version of Firefox:  72.0.1
 * Version (or revision) of Tree Style Tab:  3.3.4

**Comment by piroor** [comment]
This may be a timing issue. TST basically synchronize its tabs and Firefox's native tabs. Such a synchronization is triggered by tab move in the sidebar (like a drag-and-drop). If the number of internally tracked tabs is different to actual tab elements in the sidebar, TST guesses that something became wrong and tries to reload itself to re-initialize. It is the reloading you saw.

The synchronization of tabs and removing of obsolete group tab are processed in parallel. If the group tab is removed at a timing between a synchronization starts and finished, such a situation may happen. Currently I have no good idea to prevent such an unintentional mis-synchronization...

**Comment by irvinm** [comment]
@gonhidi is there more information or steps to help @piroor?  Could we close this item until there is more information to review?

**Comment by piroor** [comment]
I successfully reproduced this problem on my environment, with very large number tabs. Logs:

![image](https://user-images.githubusercontent.com/70062/75007321-10281780-54b8-11ea-9ada-87e01ae1291a.png)

Things happened on this case are:

1. Move all children tabs to anywhere.
2. (background) "tabs-move.js" tries to synchronize tabs order to the sidebar. There are 143 tabs.
3. (background) "tabs-group.js" cleanups needless group tab. There are 142 left tabs.
4. (sidebar) "sidebar-tabs.js" receives "synchronize tabs order" request. There are 143 tabs but the request contains only 142 tabs.
5. (sidebar) "sidebar-tabs.js" detects mismatched number of tabs, and tries to reload.

So between the step 3 and 4 we should remove a tab element from the sidebar, based on the operation at the step 3 - we need to process the request sent at the step 3 before another request sent at the step 2.

**Comment by piroor** [comment]
After the commit af6940d TST retries "synchronize tabs order" operation up to 10 times. This issue case should be handled like as:

1. Move all children tabs to anywhere.
2. (background) "tabs-move.js" tries to synchronize tabs order to the sidebar. There are 143 tabs.
3. (background) "tabs-group.js" cleanups needless group tab. There are 142 left tabs.
4. (sidebar) "sidebar-tabs.js" receives "synchronize tabs order" request. There are 143 tabs but the request contains only 142 tabs.
5. (sidebar) "sidebar-tabs.js" detects mismatched number of tabs, and reserves to do synchronization again.
6. (sidebar) The tab removed at the step 3 is removed from the sidebar.
7. (sidebar) "sidebar-tabs.js" retries "synchronize tabs order" operation. There are 142 tabs.

**Comment by irvinm** [comment]
@gonhidi can you try again with 3.3.6 and let us know if things are better?

**Comment by gonhidi** [comment]
I need to test it a little more thoroughly, but I have not been able to trigger the behaviour this time around. I will close this issue as it is seemingly fixed and report back if I find it not to be so. Thanks for looking into it, and sorry for the delay in getting back to you.
