### ISSUE TITLE
"bookmark this tree" not working 

### ISSUE THREAD

**Issue by prenaux** [piroor/treestyletab#2475]
Same as #2202 as far as I can tell, nothing happens when I click "bookmark this tree".

TreeStyleTab 3.3.4
Firefox 72

**Comment by piroor** [comment]
Did you give a permission to create bookmarks to TST? If you have not granted that, TST should show a desktop notification when you run the command from the context menu on a tab, and you'll go to TST's options page by clicking on the notification.

**Comment by polyzen** [comment]
Having this same issue, even with toggling bookmark permissions.

**Comment by piroor** [comment]
On my environment, I've successfully saved bookmarks with the command. Steps:

1. Start Firefox with a clean profile.
2. Install TST.
3. Prepare a tree of tabs.
4. Right-click on a parent tab in the sidebar.
5. Choose "Tree of tabs" => "Bookmark This Tree"
6. A desktop notification about missing permission appears. Then click it.
7. A new tab is opened with TST's options page. Then turn on the checkbox to give the permission to operate bookmarks.
8. Right-click on a parent tab in the sidebar.
9. Choose "Tree of tabs" => "Bookmark This Tree"
10. A dialog is shown in the sidebar. The name field is filled with the name of the parent tab. The folder is filled with "Other Bookmarks". Then click the "Save" button.
11. Press Ctrl-Shift-B to show all bookmarks in the browsing library.
12. Look at "All Bookmarks" => "Other Bookmarks".

Then there is a folder named with the name of the parent tab, and the folder contains bookmarks for tabs in the tree.

Confirmed environment:

* Firefox 72.0.2, TST 3.3.5

Could you describe detailed steps to confirm the problem you saw, like this?

**Comment by polyzen** [comment]
Looks like I just used this in an unintended manner. Bookmarking trees works fine. I was selecting all tabs in a window and trying `Bookmark this Tree`. I can accomplish this by using `Create New Group from tabs` and then `Bookmark this Tree` on the group.

**Comment by piroor** [comment]
> I was selecting all tabs in a window and trying Bookmark this Tree.

Oh, TST's "Bookmark this tree" command doesn't support multiselected tabs. It just affects to the single tab you right-clicked. (If it is a parent tab, TST creates bookmarks for tabs in the tree.) Because I couldn't make a decision: which behavior is most natural at the case:

* Bookmark only multiselected tabs?
* Bookmark all multiselected tabs and their descendants, even if some descendants are not multiselected?
* Bookmark only the specified single tree? (This is the current behavior)

**Comment by polyzen** [comment]
> Bookmark only multiselected tabs?

Perhaps if the command were `Bookmark as Tree`?

> Bookmark all multiselected tabs and their descendants, even if some descendants are not multiselected?

This seems safest.

**Comment by piroor** [comment]
The commit ba24ef0 introduces this behavior:

> Bookmark all multiselected tabs and their descendants, even if some descendants are not multiselected?
