### ISSUE TITLE
[Feature Request] Is there a way to disable automatic tree (as in child tabs when clicking a link)

### ISSUE THREAD

**Issue by zsection** [piroor/treestyletab#2476]
I've been hunting for option in preferences but can't see it.
Is there a way to disable a child tab being created when clicking a link on a site? And instead, having a sibling tab be created?

Thanks

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
See the section "I don't need automatically organized tree, instead I just want to organize tree by myself" at the FAQ.
https://github.com/piroor/treestyletab/blob/master/README.md#faq--frequently-rejected-requestsproposals

**Comment by irvinm** [comment]
@zsection anything else on this one?  If not, can you close this item?
