### ISSUE TITLE
{feature request} How to get rid of the scroll bar inside the treestyletab

### ISSUE THREAD

**Issue by LucKy-4U** [piroor/treestyletab#2480]
How do I get rid of the Scroll bar inside the treestyletab so that the space on the left side of the treestyletab isn't wasted. I can just use the mouse to scroll up and down the TSS so I don't need a separate bar for scrolling the tabs.
here is the amount of space that I could save by getting rid of it:
![image](https://user-images.githubusercontent.com/8860476/73623779-40705900-4664-11ea-93c9-7ab82970dafd.png)

Would really appreciate any help with this.
Thank You Very Much.

## Environment

 * Platform (OS): Ubuntu 16.4 LTS
 * Version of Firefox: 70
 * Version (or revision) of Tree Style Tab: 3.3.5

**Comment by piroor** [comment]
Here is a code snippet: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-scrollbar-1507

Please help yourself at first before posting new issues. This is an issue tracker for software development, but not a user forum.

**Comment by LucKy-4U** [comment]
> Here is a code snippet: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-scrollbar-1507
> 
> Please help yourself at first before posting new issues. This is an issue tracker for software development, but not a user forum.

My apologies, I didn't see it.
