### ISSUE TITLE
Tab labels for anonymised search engine are all the same generic name with no option to rename

### ISSUE THREAD

**Issue by blue535** [piroor/treestyletab#2482]
## Short description
When using an anonymised search engine, such as Startpage, all search tabs have the same name.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open the anonymous search engine https://www.startpage.com/
 4. Enter some search term in the search engine
 5. Check the name of the search results tab.  It is called "Startpage.com Search results"
 6. Click on one of the results in the search engine.  A new tab is opened and it has a useful name.
 7. Create a new parent tab and open the search engine again (https://www.startpage.com/)
 8. Enter some search term in the new search engine
 9. Check the name of the search results tab.  It is also called "Startpage.com Search results".  Both the parent search tabs are called the same name and cannot be distinguished when their tab trees are collapsed.

 

![image](https://user-images.githubusercontent.com/61006667/74437060-67e2d500-4e5f-11ea-9698-cc2868084f87.png)

## Expected result
It would be better if the label of the parent search tab would show the search terms instead of "Startpage.com Search results".  This  is what happens with other search engines e.g. Google.
If it is not possible or too hard to do this, could we have a new menu option "Rename Tab" to allow the user to manually rename the tab.

## Actual result
All anonymised search tabs have the same label: "Startpage.com Search results", therefore when the search result tree is collapsed, all the parent searches appear the same.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 73.0 (64 bit)
 * Version (or revision) of Tree Style Tab: 3.3.5

**Comment by irvinm** [comment]
@blue535, TST just displays the text that the website wants to display.  In your example, does the tabs on the top bar show the same as what TST shows?  (It should)  I believe this is more of a limitation of that website ... like you show in the screenshot, Google shows the search term. 

There are addons where you can rename the title of a page (Ex: https://addons.mozilla.org/en-US/firefox/addon/rename-tab-title/) but it still won't be customized to the search you executed.

**Comment by msrn** [comment]
As @irvinm said this is website specific feature. Tree style tab can't control this behaviour.
Redirect your request to said website.

**Comment by blue535** [comment]
Thanks for the replies.  TST displays the same tab label as the browser top bar, so it's not a fault in TST.  And the tab renaming feature is provided by another add-on.  So this issue can be closed.

If anyone reading this thread is interested in Startpage, there is a workaround setting in Startpage itself i.e. switch off the default 'Use POST vs GET' option that is meant to give additional privacy.  This allows the tab label to be set as you would expect, both in the browser and in TST.
Thanks!
