### ISSUE TITLE
Change color next to pinned tabs

### ISSUE THREAD

**Issue by Nardokor** [piroor/treestyletab#2483]
## Short description
Unable to set the root background color. Line of code from #1562 did not behave as expected.

## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set Firefox theme to "Light".
 4. Add the following code to "Extra style rules for sidebar content"
```
:root {
  --grey: #605e5c;
  --active: #444444;
  --hover: #0074c6;
  --tab-height: 25px;
  --font-size: 12px;  
}

:root { background: var(--grey); }

#tabbar{ 
  background-color:  var(--theme-colors-frame);
  bottom: 0 !important; /* Eliminate dead space on bottom */
}

.tab {
  background-color: var(--grey);
  height: var(--tab-height);
}

.tab .label {
  color: white;
}

.tab.active .label {
  font-weight: bold;
}

.tab.active {
color: white;
  background-color: var(--active);
}

.tab.active:hover {
  background-color: var(--active);
}

.tab:hover, .tab:not(.active):hover {
  background-color: var(--hover);
}

.newtab-button-box {
  display: none;
}
```

## Expected result
![image](https://user-images.githubusercontent.com/15717438/74503448-c5017980-4ea5-11ea-8ed5-15b365e38dd4.png)
Space to the right of pinned tabs is grey

## Actual result
![image](https://user-images.githubusercontent.com/15717438/74503426-b4510380-4ea5-11ea-80b9-337da4499094.png)
Space to the right of pinned tabs is light

## Environment
 * Platform (OS): Windows 10
 * Version of Firefox: 73.0
 * Version (or revision) of Tree Style Tab: 3.3.5

**Comment by piroor** [comment]
You should set background color to `#tabbar-container` also. It is the parent node of the `#tabbar`.

**Comment by Nardokor** [comment]
Thanks!
