### ISSUE TITLE
I keep selecting "Close Other Tabs" by accident :( plz add way to customize context menu or a way to disable this option.

### ISSUE THREAD

**Issue by manintan** [piroor/treestyletab#2487]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
You can customize visibility of context menu commands on the sidebar via userChrome.css. I've added a code snippet:

https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#for-userchromecss
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-context-menu-items-in-the-sidebar-2116

**Comment by piroor** [comment]
Sorry but I won't add explicit options for those context menu commands implemented as fake of Firefox's native commands. This is one of design decisions on TST: poor-customizabilities around features faking Firefox's one. On most cases TST doesn't provide options for a feature if Firefox doesn't provide options for the original feature, especially cases having workarounds like my previous comment.
