### ISSUE TITLE
The right-click menu of bookmarks in Firefox ESR

### ISSUE THREAD

**Issue by wvxwxvw** [piroor/treestyletab#2488]
## Short description
Firefox ESR 68.5 x64
The bookmarks context menu items with the "open unloaded" option unchecked do not work. Regardless of the grouping settings, the group page opens blank, and there are no child tabs.
At the same time, if you select the "open unloaded" option, everything will work as intended.

The problem was already in the previous version TST, I just didn't find time to report it earlier. And even earlier, I did not notice the problem, since I use the "open unloaded" option.

## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install TST.
 3. We configure only the options that interest us.
 4. Create, for example, a folder with bookmarks on the bookmarks bar.
 5. Try to open them using the TST context menu items.

 * Platform (OS): 
Windows 7 x64

**Comment by piroor** [comment]
I've tried with the latest development build (c23fbb0) but I couldn't reproduce the problem, on both Nightly and ESR68. Does the commit c23fbb0 affect to this?

**Comment by wvxwxvw** [comment]
Yes! This is it.

So, there were two problems:
1. Not loading tabs
2. Empty group page (no items, but the title is in place)

On the new profile, commit immediately solved all the problems.

On the old profile:
1. The first problem was solved immediately.
2. The second problem remained.
I tormented the profile for a long time, disabled Addons, deleted the cache, switched and deleted parameters in user.js and prefs.js. But everything was fixed, after the next recovery of the profile, by switching the parameter "config_requestPermissions_tabHide". Just switched it back and forth, the parameter value is not important.

Something like this.

**Comment by wvxwxvw** [comment]
You can close it.

**Comment by wvxwxvw** [comment]
Обновил пост выше.

**Comment by piroor** [comment]
I've tried but still couldn't reproduce the second problem. Do I understand your report correctly? Here are screenshots on my case:

Bookmarks options:
![image](https://user-images.githubusercontent.com/70062/75502233-92af5a80-5a15-11ea-9583-ca6cc6a666c0.png)
All configs and bookmarks (default items in a new profile for Nightly):
![image](https://user-images.githubusercontent.com/70062/75502270-b8d4fa80-5a15-11ea-9d69-28cbd81ed277.png)
Result:
![image](https://user-images.githubusercontent.com/70062/75502343-ede14d00-5a15-11ea-8404-8b63ee753180.png)

These screenshots are taken with Nightly but I got same result on ESR68.

**Comment by wvxwxvw** [comment]
I must have been vague.

1. [Commit](https://github.com/piroor/treestyletab/commit/c23fbb0fb3a2c439e70811db0de6be03ab1509be) fixed a problem with not opening tabs.
2. With the groups tab, everything is fine. I forgot to check the box.

In general, everything is fine, close issue.

**Comment by piroor** [comment]
Thank you confirmation!
