### ISSUE TITLE
Sidebar sometimes fails to load (animated throbber for a single tab) after restoration by Session Boss

### ISSUE THREAD

**Issue by grahamperrin** [piroor/treestyletab#2490]
Sometimes the sidebar presents as in two of these four windows: 

![2020-02-26 17:56:21](https://user-images.githubusercontent.com/192271/75373791-e78e8c00-58c2-11ea-9852-c03fac38e936.png)

Please: is the symptom above recognisable to anyone?

Screen recording available on request. Essentially: 

* the animation – suggesting that load is incomplete – continues long after load is complete
* a reliable and simple workaround seems to be, select anything other than Tree Style Tab (in the sidebar menu) then reselect Tree Style Tab. 

After applying the workaround to one of the two windows in the first screen shot: 

![image](https://user-images.githubusercontent.com/192271/75374110-929f4580-58c3-11ea-862a-a7153beaebcb.png)

Maybe an extensions conflict with Session Boss, https://addons.mozilla.org/addon/session-boss/ – if so I'm happy for this issue to be closed. 

Thanks

**Comment by piroor** [comment]
I've tested with Session Boss and I've realized that there are some errors on window initialization when windows are restored by Session Boss, due to some tabs removed before they are initialized. After some recent commits the problem looks go away on my environment. Could you try the latest development build?: https://github.com/piroor/treestyletab/blob/master/README.md#development-builds

**Comment by grahamperrin** [comment]
Thanks you. 

With `3.3.6.10041.10041` it seems that symptoms differ but the conflict is not entirely resolved.

After restoring a session (from around the time when I opened this incident) with sixty tabs across four windows: 

![image](https://user-images.githubusercontent.com/192271/75627874-f085a300-5bcb-11ea-891e-479e1e6720e4.png)

* if I'm not mistaken, there's no longer the animated throbber
* still, the sidebar does not load when expected.

**Comment by SHHSSH** [comment]
I have personally experienced similar/the same problems after reloading Firefox after a restart. I too use a "session" restorer/boss to a degree, not so dissimilar to yours. 

I use Tab Suspender, and I have certainly noticed odd conflicts at times with TST. However, thankfully, nothing major, e.g; tab/data loss.

I regularly have 100+ tabs stored in TST/suspended and upon restart of the browser it can be a little sluggish, running with only 16Gb of RAM and an old i7.

Realistically, I believe TST does load correctly 99% of the time, it's just a visual error, therefore a quick refresh of the sidebar with {F1} does the trick.

I hope nothing MAJOR comes of this and other addon conflicts in the future, as I feel it's somewhat rectified now with piroor looking at the initialization of tabs (hopefully he delayed them or something a little).

If you have any problems in the future and are worried about losing your tabs before closing the browser, I suggest you look into a few addons that offer the function of "Copy all tab URLs", just as an insurance method.

**Comment by piroor** [comment]
@grahamperrin I've seen same problem once, but I couldn't reproduce it anymore... (And, close/reopen the sidebar solved the problem for me.)

**Comment by grahamperrin** [comment]
This morning: 

![image](https://user-images.githubusercontent.com/192271/77028165-02b75d80-6990-11ea-8edf-70a31d3da6c9.png)

* four of six windows affected. 

I found this preference enabled, now disabled: 

> ☐ Optimize tree restoration with cache

**Comment by grahamperrin** [comment]
Further to yesterday morning's problem and experimental workaround (hidden comment above)

At the time of writing, I can no longer reproduce the issue. 

### Preferences and environment

* Vertigo theme (not what was preferred when yesterday's problem occurred)
* not applying browser theme
* ☑ Optimize tree restoration with cache (re-enabled after yesterday's experimental workaround). 

Previously using r357746 of FreeBSD-CURRENT, now using r359068. 

Previously using [graphics/drm-legacy-kmod](https://www.freshports.org/graphics/drm-legacy-kmod/) (not intended for the HP EliteBook 8570p that I use, but relatively stable) and [x11-drivers/xf86-video-ati-legacy](https://www.freshports.org/x11-drivers/xf86-video-ati-legacy/). 

Switched to [graphics/drm-current-kmod](https://www.freshports.org/graphics/drm-current-kmod/) (recommended but relatively unstable) then most recently [graphics/drm-devel-kmod](https://www.freshports.org/graphics/drm-devel-kmod/):  

* with [x11-drivers/xf86-video-ati](https://www.freshports.org/x11-drivers/xf86-video-ati/)

– I don't like using the kernel modules that are (for me) less stable, but `xf86-video-ati-legacy` recently can not be built/used. 

```text
root@momh167-gjp4-8570p:~ # date ; uname -v
Thu Mar 19 09:04:12 GMT 2020
FreeBSD 13.0-CURRENT #0 r359068: Wed Mar 18 21:14:12 GMT 2020     root@momh167-gjp4-8570p:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG 
root@momh167-gjp4-8570p:~ # beadm list
BE       Active Mountpoint  Space Created
r350684  -      -            8.2G 2019-08-07 19:01
r356618g -      -            1.2G 2020-02-10 19:02
r357746a -      -          450.4M 2020-02-11 17:16
r357746b -      -            1.1G 2020-02-14 23:58
r357746c -      -            2.4G 2020-02-21 11:34
r357746e -      -          369.1M 2020-03-10 18:24
r359068a NR     /          158.1G 2020-03-18 12:08
root@momh167-gjp4-8570p:~ # pkg query '%o %v %R' firefox drm-current-kmod drm-devel-kmod gpu-firmware-kmod xf86-video-ati 
www/firefox 74.0_5,1 FreeBSD
graphics/drm-devel-kmod 5.0.g20200221 poudriere
graphics/gpu-firmware-kmod g20200130 unknown-repository
x11-drivers/xf86-video-ati 19.1.0_2,1 FreeBSD
root@momh167-gjp4-8570p:~ # 
```

----

Also now using OpenGL 3.1, smooth (in lieu of XRender, crisp) for compositing, although this is probably irrelevant; IIRC I was getting good results i.e. sidebars loading properly *before* the switch away from XRender. 

HTH
