### ISSUE TITLE
Return Suspend Tab (action) to TST|Multiple Tab Handler?

### ISSUE THREAD

**Issue by CrashNBurn71** [piroor/treestyletab#2491]
The removal of "Suspend Tab" from MTH was especially bothersome to me, it was about the only usage I had for Multiple Tab Handler. And a year on now, there are still no extensions that allow you to manually suspend a Tab (or Tab Tree) nor retain the tab history. 

Both Tree Tabs (Firefox|Chromium) and Tabs Outliner (Chromium) allow for easily suspending a given tab | tab tree.

Could this please be returned to TST or MTH?

**Comment by piroor** [comment]
I believe that the feature should be provided by addons developed for the purpose - Auto Tab Discard, UnloadTabs, and more others. They often provide extra context menu commands for tabs, and TST/MTH should work them together seamlessly.

However I've realized that both Auto Tab Discard and UnloadTabs don't support multiselection of tabs, so I've created pull requests for that: https://github.com/NiklasGollenstede/unload-tabs/pull/34 and https://github.com/rNeomy/auto-tab-discard/pull/138. I hope they become merged...

**Comment by NiklasGollenstede** [comment]
Merged, somewhat tested, and available as [dev build](https://github.com/NiklasGollenstede/unload-tabs#development-builds----); release will follow.
Thanks piroor!

**Comment by piroor** [comment]
@NiklasGollenstede Thank you for the quick merging!

**Comment by irvinm** [comment]
@piroor can we close this now?
