### ISSUE TITLE
Unexpected appearance of trees after successfully enabling flatness

### ISSUE THREAD

**Issue by grahamperrin** [piroor/treestyletab#2494]
Re: https://github.com/piroor/treestyletab/issues/1544#issuecomment-522902490 around eight days ago I disabled two advanced preferences: 

* `autoAttach`
* `syncParentTabAndOpenerTab`

Success; no trees. 

Then disabled TST for a few days. 

Today after re-enabling the extension, unexpected trees began appearing, e.g.: 

![image](https://user-images.githubusercontent.com/192271/75626952-c9c36e80-5bc3-11ea-9174-038a3a76ef56.png)

I tried resetting (enabling) then again disabling the two preferences, no improvement. 

Please, might this be treated as a bug? 

Or re: https://github.com/piroor/treestyletab/issues/1544#issuecomment-345129601 (2017) will it be `wontfix`?

**Comment by grahamperrin** [comment]
… if it helps to diagnose this: immediately after re-enabling the extension, I noticed that my previously preferred theme was no longer preferred. 

Preference(s) corruption, maybe? (A wild guess. Not jumping to any conclusion.)

**Comment by grahamperrin** [comment]
I forgot to include environment information above, sorry. 

Extension: 

* `3.3.6 (2020.2.21)`
* https://addons.mozilla.org/addon/tree-style-tab/versions/3.3.6/updateinfo/

```text
grahamperrin@momh167-gjp4-8570p:~ % date ; uname -v
Sun  1 Mar 2020 14:13:43 GMT
FreeBSD 13.0-CURRENT #51 r357746: Tue Feb 11 03:54:19 GMT 2020     root@momh167-gjp4-8570p:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG 
grahamperrin@momh167-gjp4-8570p:~ % pkg query '%o %v %R' firefox
www/firefox 73.0.1,1 FreeBSD
grahamperrin@momh167-gjp4-8570p:~ % 
```

### Reproducibility

Not yet reproducible, touch wood :+1: 

I: 

1. reduced the number of content processes from `8` (the default here) to `1` 
2. saved a session (Session Boss)
3. quit
4. started (OT, probably negligible: _two_ content processes visible in `htop`)
5. observed Firefox automatically restore the session
6. manually flattened the tree
7. updated to development build `3.3.6.10041.10041`
8. <kbd>Control</kbd>-clicked links in a handful of tabs.

Result: 

* flatness 

![image](https://user-images.githubusercontent.com/192271/75627488-7dc6f880-5bc8-11ea-8a93-b673ca46ddc5.png)

I'll leave this issue open whilst testing `3.3.6.10041.10041` in relation to a separate issue …

**Comment by grahamperrin** [comment]
### Additional observations

I used <kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>T</kbd> to reopen the last tab that was (presumably) closed in the previous session. 

It was indented … I guess, because I did not manually flatten this particular tab before the quit of Firefox. 

After dealing with that one tab … at the time of writing, still no unexpected tree when opening links in new tabs.

**Comment by grahamperrin** [comment]
### Reproducibile

1. about:addons
2. seek an extension – _Find more add-ons_

Expected: 

* search results in a new tab, not indented.

Actual result: 

* search results in a new tab, indented.

**Comment by piroor** [comment]
I think the initial problem (unexpected tree restoration) can be a conflict with the Session Boss.

The second problem (search results tab is opened as a child) is currently "by design". But I agree that this behavior should be deactivated when you use `autoAttach`=`false` config.

(By the way, please post one topic per one issue for issue tracking. Multiple topics in one issue will prevent to close the issue for long time.)

**Comment by piroor** [comment]
The commit f7b6255 should fix the second problem.

By the way, basically TST is designed to use with tree structure, and flat tabs mode is not tested well. I still recommend you to use other vertical tab addons without tree structure. [Here is a list of alternatives I know.](https://github.com/piroor/treestyletab#similar-projects)

**Comment by grahamperrin** [comment]
Thanks, and apologies – 

> Multiple topics in one issue

– I imagined, wrongly, that the symptom involving about:addons might help to define this issue. 

Confirmed: with 3.4.7 I no longer find a problem with new tabs that originate from about:addons 👍

----

To the best of my recollection: recently, I have not found unexpected flatness in other situations, including restorations by Session Boss. 

Also, more recently: I have refrained from using Sidebery in combination with Tree Style Tab. https://github.com/mbnuqw/sidebery/issues/147#issuecomment-599105875 (posted after I temporarily disabled Sidebery) does mention an incompatibility. 

I might now (for a few days) disable Tree Style Tab, enable Sidebery. 

If you like, please close this issue. 

Thanks again.

**Comment by grahamperrin** [comment]
### Side note

For reference only: 

> … I might now (for a few days) disable Tree Style Tab, enable Sidebery. …

After finding a few compatibility issues with Sidebery e.g. https://github.com/erosman/support/issues/163 I chose to use Tree Style Tab with Simple Tab Groups (and other extensions) as outlined at https://github.com/Drive4ik/simple-tab-groups/issues/319#issuecomment-602148339

----

Closing; I assume that the flatness will remain good from now on. 

Thanks again 👍
