### ISSUE TITLE
[Feature Request] Add the item "open in private window" to the context menu of the tab

### ISSUE THREAD

**Issue by wvxwxvw** [piroor/treestyletab#2495]
Add the item "open in private window" to the context menu of the tab. For example, in the "tabContextMenu_moveTab_label" submenu.

**Comment by irvinm** [comment]
I was originally going to say that you could probably do this an addon, but the one I use and others seem to be broken as of one of the recent versions of Firefox.

In Firefox itself, there doesn't seem to be any support at the tab level (right-clicking on a tab to re-open it in a private tab or window).

What is there is support to right-click on a link on a page to "Open Link in New Private Window" *OR* to simply open a new private window via "FILE -> NEW PRIVATE WINDOW".

I am guessing that @piroor may not even be able to do this even if he wanted to.  (not tree related)

**Comment by wvxwxvw** [comment]
Yeah. Such a simple function a is made through one place.

The standard context menu item generates entities, i.e. opens new private window. Perhaps this is correct, but I absolutely do not need this behavior.

I had to temporarily install the addon "Open in Private Window", it uses an existing private window, and opens a new window only if another private window does not exist.

And you're probably talking about "open in private mode". I see that on AMO him cons put. :)

I will not close, let @piroor decide, what to do with this topic.

**Comment by irvinm** [comment]
I didn't ask you to close it and of course @piroor will chime in and make a decision on what to do. 

I was just merely stating what I saw as the state of handling private windows\modes in Firefox today.

**Comment by piroor** [comment]
I've searched "open in private" on addons.mozilla.org and I've found some addons, but no one currently available addon provide context menu commands on tabs. It's a mystery...

Here is a small example to implement such a command. I put this here under public license, so please use it as you like: 

```json
{
  "manifest_version": 2,
  "name": "Open Tab in Private Window",
  "version": "0.1",
  "permissions": [
    "menus",
    "tabs"
  ],
  "background": {
    "scripts": ["background.js"]
  }
}
```

```javascript
// background.js
browser.menus.create({
  id: 'open-in-private-window',
  contexts: ['tab'],
  title: 'Open in Private Window'
});

let lastWindowId;
let reuseWindow = true; // you should update this based on user option
browser.menus.onClicked.addListener(async (info, tab) => {
  if (info.menuItemId != 'open-in-private-window' || !tab)
    return;
  let window = reuseWindow && lastWindowId && await browser.windows.get(lastWindowId);
  if (window) {
    browser.tabs.create({ url: tab.url, windowId: window.id, active: true });
  }
  else {
    window = await browser.windows.create({ incognito: true, url: tab.url });
    lastWindowId = window.id;
  }
});
```

**Comment by piroor** [comment]
One note: you must activate the addon on private windows manually. Otherwise it will fail to create a private window or a tab in private windows.

Anyway, I think the feature should be distributed as an independent addon, not a part of TST. Such an addon will be available on TST's sidebar tabs. Thus I won't add the feature as a built-in command of TST, sorry.

**Comment by wvxwxvw** [comment]
Thanks!
