### ISSUE TITLE
PLain Dark Theme not rendered correctly in 3.4.1

### ISSUE THREAD

**Issue by marekbecica** [piroor/treestyletab#2499]
## Short description
Latest version doesn't render Plain Dark Theme properly
## Steps to reproduce

 1. Start Firefox with clean profile on system with dark theme
 2. Install latest TST 3.4.1.
 3. Select Plain Dark theme in TST settings

## Expected result
Tabs are displayed correctly in dark theme 
See screenshot from 3.3.6 (after clean install)
![screenshot_14](https://user-images.githubusercontent.com/1676265/76074880-55f6dc80-5f9c-11ea-83c6-bf8b5d9ea92e.png)

## Actual result
Tabs are not in dark theme
See screenshot from 3.4.1 (after clean install)
![screenshot_13](https://user-images.githubusercontent.com/1676265/76074921-61e29e80-5f9c-11ea-9155-b88d17a3ef7b.png)

## Environment

 * Platform (OS): Linux Mint 19.3 Cinnamon, Theme: Mint-Y-Dark
 * Version of Firefox: 73.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.4.1

**Comment by piroor** [comment]
This looks happen when the system color support is active. Could you try a workaround?: TST Options => For developers => Color scheme => Photon

**Comment by wallace11** [comment]
I'm also affected by this issue.
Workaround worked for me just fine.

**Comment by marekbecica** [comment]
Workaround worked for me too.

**Comment by piroor** [comment]
The commit f09654b2445ca484620f38e366ef60fab6bd9471 should fix this unstable coloring problem. After the commit, system's dark color mode is ignored, and you may need to choose the "Plain Dark" theme manually.

* The system color mode of TST is enabled by default only on Linux. Firefox's default theme on Linux uses system colors, so we also need to use system colors on addon. On this environment, CSS media query based "dark mode" is not supported.
* System color mode is disabled on Windows and macOS. Firefox's default theme on these environments are designed with Photon color scheme, and colors are switched to dark colors when the dark color mode is activated on the OS side. So, TST also does same thing - applies light colors by default, and applies dark colors on the dark color mode.

**Comment by piroor** [comment]
TST 3.4.6 is now available via addons.mozilla.org, so I close this.
