### ISSUE TITLE
Clicking on "close tab" does not close tab any longer

### ISSUE THREAD

**Issue by appletomato** [piroor/treestyletab#2501]
## Short description

Tabs cannot be closed by clicking the "close tab" icon any longer.

## Steps to reproduce

- Open a new tab
- Click on the "close tab" icon

## Expected result

- Tab gets closed

## Actual result

- Tab stays open

## Environment

 * Platform (OS): macOS
 * Version of Firefox: 73.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.4.1

I have downgraded Tree Style Tab to version 3.3.6 and there the problem does not exist.

**Comment by Gotolei** [comment]
Question, do you have any custom code that hides the close button except on hover? Because if so, I ran into the same thing when 3.4.1 came out.
For me the culprit is [this](https://github.com/piroor/treestyletab/blob/348d5a2864ae30042ffcb4d91092139fd96cfaec/webextensions/sidebar/styles/base.css#L331), on the .extra-items-container.front flexbox, because its right offset isn't updated on hover and it draws over the close button. Solved for now by setting a higher right on hover in custom css, but it looks like it should be fixed by ae95ed1 in 3.4.3.

**Comment by JonnyTsGitHub** [comment]
I am seeing this too.  I do have custom code to only show on hover.  After removing it (and restarting firefox) my close buttons work again.

What do you mean "setting a higher right on hover in custom css"?

**Comment by Gotolei** [comment]
```css
tab-item:hover .extra-items-container.front {
  right: 24px; /*give or take*/
}
```

**Comment by JonnyTsGitHub** [comment]
Thanks :)

**Comment by irvinm** [comment]
I thought I was losing my mind after upgrading to 3.4.1, but after playing around with my CSS and some other addons [thought maybe there was a conflict as I tried a clean profile and it worked fine] I was able to get everything working again.  (Although I didn't change any of my original CSS which hides the closebox unless hoovering and changes the closebox color and shape.)

So ... not sure how it is now working for me, but looks like 3.4.3 should be a permanent fix. :)

**Comment by piroor** [comment]
I got same problem report on Twitter and I've realized that a custom style rule "autohide closeboxes" https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#only-show-tab-close-button-on-hover-1448 produces the problem. Just a workaround, adding `#tabbar` prefix part (please note to the blank space between the prefix and `tab-item` or `.tab`) will solve the problem.

The commit ae95ed13b970854244237a5524cd10e2e82fc970 should fix this problem fundamentally, and I've already uploaded a new version 3.4.3 with the fix. It is now under editor's review...

**Comment by piroor** [comment]
Technical details:

TST 3.4.0 and later places "extra-items-container" span element covering over the tab label of each tab. The offset of the span element is calculated on the startup process of the sidebar panel, and it is based on actual coordinates of dummy tab elements shown behind the background screen. The "autohide closeboxes" style rules hides the closebox in the dummy tab element also, then the dummy tab label element is unexpectedly expanded to right edge of the dummy tab. On this situation the righthand offset becomes 0, so the span element is placed to cover the whole tab, and the closebox is unexpectedly covered under the span element. This is the reason why the closebox become unclickable.

The fix on TST 3.4.3 always gives a z-index higher than the span element, to tab closeboxes, twisties, and "sound playing" buttons. I think it should solve this issue and other similar problems triggered by custom user styles.

**Comment by gromain** [comment]
I had the same problem, and the @piroor solution worked perfectly for me!
Thanks for the quick fix!

**Comment by guraltsev** [comment]
I have implemented the suggested fix but it still has problems! The close button works in the first window, however if you open a second firefox window the close button doesn't work there. 

Thanks!

**Comment by piroor** [comment]
Hmm, there is another workaround:

```css
tab-closebox {
  z-index: 9001;
}
```

Until TST 3.4.5 becomes available on addons.mozilla.org, I hope it help you.

**Comment by piroor** [comment]
I close this because TST 3.4.6 is now available on addons.mozilla.org.
