### ISSUE TITLE
After 3.4.1 update, tabs are unselectable

### ISSUE THREAD

**Issue by tehyoshi** [piroor/treestyletab#2502]
TST automatically re-synced (turned gray and reloaded) and now I cannot click on any of the tabs. Everything else works, such as hovering, opening the right-click menu and interacting that way, move tabs, and even expanding/collapsing trees, but clicking on tabs do nothing.

I have tried removing all custom CSS and restarting Firefox, but to no avail.

At first, I thought this was related to issue #2501, but that also randomly resolved itself somehow, as I can close tabs normally.

**Comment by tehyoshi** [comment]
Just tried removing the extension and reinstalling it, and now everything works normally again.

**Comment by irvinm** [comment]
Ok, thanks.  Can you close this item?  Thanks.

**Comment by Patchumz** [comment]
I'm having this same issue, removing and reinstalling the extension did nothing for me. Only started happening some hours ago.

**Comment by klntsky** [comment]
I have just observed the same behavior. However, in my case reinstalling the extension did not help. Can we reopen this?

**Comment by piroor** [comment]
@klntsky Did you see #2504 ? If you use "Move unloaded tabs for Tree Style Tab" or something other helper addon, it may conflict with TST 3.4.1. I've uploaded a fixed version TST 3.4.4 to AMO and waiting for review.

**Comment by klntsky** [comment]
Thanks @piroor. I am using that addon indeed.

**Comment by Patchumz** [comment]
Manually updating to the latest version of TST fixed it for me, @klntsky. It was stuck on an older version (maybe even 3.4.1) when I tried reinstalling the add on before to fix it. So I had to go to the releases and manually upgrade.
