### ISSUE TITLE
Incompatible with Move unloaded tabs for Tree Style Tab: tabs can not be activated|switched via TST 3.4.1 (2020.3.6)

### ISSUE THREAD

**Issue by drsvp** [piroor/treestyletab#2504]
Following my update to TST 3.4.1 (2020.3.6) i can no longer activate|switch to tabs via TST; rather, i have to go to the default tabs bar in Ffox to activate|switch between tabs.  Prior to the TST update, it switched tabs when clicked on.

Steps to reproduce:
•  Place mouse cursor over tab to be switched to 
•  The color changes indicating focus
•  Clicking on the tab(s) does not switch to|activate them
   [note: clicking an X to close a tab via TST works normally]

i restarted Ffox once the issue started but it remains for me
i added no additional|new addons along with the TST update (i do still have 70+ other addons running, tho only a half dozen or so of those are tabs specific)

Ffox 73.0.1 (64bit)
TST 3.4.1 (2020.3.6); dark theme
Windows 7

Thanks!

**Comment by piroor** [comment]
This looks similar to #2503. Do you use any other addon extends TST?

**Comment by drsvp** [comment]
Indeed, i have Move Unloaded Tabs for TST installed; deactivating it corrected my issue; activating it again causes the issue to return for me.

jic, i had it installed prior to the TST update to 3.4.1 (2020.3.6) and did not have this issue.

?

**Comment by piroor** [comment]
Thanks, I've confirmed the problem with installed Move unloaded tabs for Tree Style Tab.

**Comment by piroor** [comment]
I forgot that TST's tab activation behavior was changed at a version between TST 3.0.17 and TST 3.1.8. Before 3.0.x, TST switches tab focus at the timing `onmousedown`. But 3.1.8 and later switch tab focus at the timing `onclick` - after `onmouseup`. "Move unloaded tabs for Tree Style Tab" was initially developed for TST 2.x but it actually (and unexpectedly) became unneeded for the purpose described at its name.

**Comment by piroor** [comment]
Hmm... I missed that the behavior was actually changed with the pull request https://github.com/piroor/treestyletab/pull/2306/files and I didn't mentioned that totally...

**Comment by piroor** [comment]
I've uploaded TST 3.4.4 to AMO with the fix. Please wait for editor's review...

**Comment by drsvp** [comment]
Just a quick confirmation that Mozilla has issued an update of TST to v 3.4.6, March 12, 2012
More after i've had the time to put it through some routines... including reactivating Move unloaded tabs for Tree Style Tab ...

**Comment by drsvp** [comment]
The issue with tabs in the TST sidebar being unswitchable with Move unloaded tabs for Tree Style Tab enabled seems to be resolved for me!  Working as expected.
Thanks!
