### ISSUE TITLE
Closing a collapsed tab may unexpectedly close other tabs when TST is hidden

### ISSUE THREAD

**Issue by pkrabbit** [piroor/treestyletab#2506]
## Short description
When the sidebar is hidden and a tab is closed, all child tabs are also closed after 20 seconds.

I understand this is intended behavior, but it was rather unexpected to me. The notification on the corner is easy to miss on a big screen.

When the TST sidebar is hidden, I think a saner default would be to simply close the tab (and not the group), since the user is not aware if a tab is collapsed or not.

## Steps to reproduce
1. Collapse a tab with multiple children in TST
2. Hide TST sidebar
3. Middle-click tab in Firefox to close it

## Expected result
4. Clicked tab is closed

## Actual result
4. The notification appears:
![Notification](https://user-images.githubusercontent.com/15457521/76182254-232b2f00-61bc-11ea-9767-4a9cbcbf2b21.png)
5. If no action is taken, clicked tab and all children are closed after 20 seconds

**Comment by piroor** [comment]
First, I recommend you to give a permission for TST to render confirmation dialogs inside the contents area as a workaround. Here is the scenario what happened on your case:

1. TST tries to show a dialog with a message "Yo uare about to close N tabs. Are you sure to continue?" on such cases if it is possible. First TST tries to show it inside the content area, it is available when both these conditions are true:
   - TST Options => Advanced => "Allow to show confirmation dialogs inside tab contents" is checked and the permission is granted.
   - The current tab activated after you closed the old active tab is a regular website (not addons.mozilla.org, about: pages, or other specials)
2. When TST couldn't show an in-content confirmation, TST tries to show the dialog inside the sidebar as a fallback.
3. When both the in-content dialog and in-sidebar dialog aren't available, TST shows the notification message you saw as the final option.

Anyway I've introduced a new expert option to treat current tab closing with invisible sidebar as a closing of a parent tab in an expanded tree, with the commit c8a2bbd. I hope it will help you.

**Comment by pkrabbit** [comment]
Oh, thank you for the very quick response! Should I close this issue?

I've just discovered this setting and it may also be what I'm looking for ("for operations while the tree sidebar is invisible"):

![Setting](https://user-images.githubusercontent.com/15457521/76264645-4e645b80-625a-11ea-9f46-059cb9f2e1f2.png)

Maybe this should be the default setting for new users?

**Comment by piroor** [comment]
It is already the default choice for new users. I think that the current choice on your environment might be produced by TST's auto migration. (Before these behavior-based options UI was introduced, there were some separate options. And I introduced such behavior-based choices, because they were hard to be understood by new people. If you used TST before this new UI was introduced, your options might be migrated.)

**Comment by pkrabbit** [comment]
I did have it before, but it seems the second radio button is the default, even on a fresh install of Firefox Portable 73.

**Comment by piroor** [comment]
Oh, you right! I missed that the migration mechanism I told unexpectedly overwrote the default config based on old options. With the commit 51f4428 now the default is changed to the first choice for fresh environments.

Hmm, I have to research the migration mechanism again and cleanup old options...

**Comment by piroor** [comment]
I close this because TST 3.4.6 is now available on addons.mozilla.org.

**Comment by pkrabbit** [comment]
Thank you!
