### ISSUE TITLE
[Feature Request] Expand\Collapse all in this tree

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2508]
In the context menu, there are options to:
- expand\collapse single trees ("Expand this Tree" \ "Collapse this Tree")
- expand\collapse all of the trees ("Expand All" \ "Collapse All") 

It seems it would be useful to be able to expand\collapse all trees and sub-trees starting at one tab.

**Example use case:**

- If the root of the tree is a research topic and there are several other related sub-trees, in an attempt to find a tab, it would be helpful to be able to expand all trees from the topic tab downward rather than having to expand all trees within the browser.

**Suggestions \ Options:**

- Option 1:  Re-use the existing "expand-collapse this tree" to be recursive for all sub-trees.  (People can obviously still expand-collapse a single tree via the graphical carat on the tab)
- Option 2:  Create a new set of options for this intermediate operation. (Ex:  "Expand all sub-trees" \ "Collapse all sub-trees")
- Option 3:  Close this issue and have a good day. :)

**Comment by piroor** [comment]
On old versions I got a request to invert context menu commands with middle click, but it was not supported on WebExtensions API. However, Firefox 64 and later supports `button` information for click events on context menu items.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/OnClickData
Thus I've added inverted reactions for some context menu commands. "Expand(Collapse) this Tree Recursively" are now available as inverted versions of their non-recursive versions, and they are also available as separate menu items.
