### ISSUE TITLE
Question: Why is the "expand/collapse" tree arrow so cramped?

### ISSUE THREAD

**Issue by janjur** [piroor/treestyletab#2509]
![image](https://user-images.githubusercontent.com/20413685/76326591-2839cc80-62e9-11ea-9a5b-2d89fa6b355e.png)

Extra style rules
```
/* Less visible tab dividers. 
   A black border with a very low alpha slightly darkens any color. */
.tab {
  border: solid 1px #00000012;
  padding-left: 13px; 
}
.tab.unread .label {
  font-style: italic;
}
.tab .twisty {
  margin-right: -1.5em;
  opacity: 0;
  position: relative;
  z-index: 10000;
}
.tab:not(:hover) .closebox {
  display: none;
}


:root.left-scrollbar #tabbar.overflow {
  margin-left: calc(0px - var(--scrollbar-size));
  transition: margin-left ease 0.25s 0.4s;
}
:root.right-scrollbar #tabbar.overflow {
  margin-right: calc(0px - var(--scrollbar-size));
  transition: margin-right ease 0.25s 0.4s;
}

:root.left-scrollbar #tabbar.overflow:hover {
  margin-left: 0;
}
:root.right-scrollbar #tabbar.overflow:hover {
  margin-right: 0;
}

:root.left-scrollbar.narrow-scrollbar #tabbar.overflow:hover {
  margin-left: calc(var(--narrow-scrollbar-size) - var(--scrollbar-size));
}
:root.right-scrollbar.narrow-scrollbar #tabbar.overflow:hover {
  margin-right: calc(var(--narrow-scrollbar-size) - var(--scrollbar-size));
}
```

chrome/userChrome.css
```
/* hides the native tabs */
#TabsToolbar {
  visibility: collapse;
}

#sidebar-header {
  visibility: collapse !important;
} 

#sidebar {
  min-width: 100px !important;
  max-width: 168px !important; /*six pinned icons*/
}
```

**Comment by irvinm** [comment]
@janjur I am not sure I understand your question.  It is your CSS that is causing the spacing issue.  If you comment out `margin-right: -1.5em;` and  `padding-left: 13px;` from the TST CSS, it looks normal to me.

**Comment by janjur** [comment]
Thank you! It worked. Can you help me with the next issue? The mouse cursor gets trouble aligning with the `x` sign on the tab. Here, take a look:

No highlight while on the `x` area:
![IMG_20200311_154758 (2)](https://user-images.githubusercontent.com/20413685/76430427-9eedcd00-63b0-11ea-9576-92878286ca12.jpg)

I got 1px width where I can close the tab:
![IMG_20200311_154806 (2)](https://user-images.githubusercontent.com/20413685/76430441-a1e8bd80-63b0-11ea-9983-099d62cf8717.jpg)

I move the mouse 1px right, I loose hoover-focus:
![IMG_20200311_154814 (2)](https://user-images.githubusercontent.com/20413685/76430451-a44b1780-63b0-11ea-9d7e-665f74dfbde9.jpg)

**Comment by piroor** [comment]
I think a higher z-index of tab-close-box may help you: https://github.com/piroor/treestyletab/issues/2501#issuecomment-597663177

**Comment by janjur** [comment]
It worked! Thank you!
