### ISSUE TITLE
[Feature Request] Open the settings page in a new tab

### ISSUE THREAD

**Issue by wvxwxvw** [piroor/treestyletab#2511]
Mozilla, for no reason, made the about:addons page narrow, and in addons, with a lot of descriptions in the settings, all the lines are lumped together and difficult to perceive. I'm talking about ordinary letter writing, not hieroglyphic. Moreover, the extension of the browser window will not affect the width of the settings page, the block with settings will remain the same narrow.

In the addon [CanvasBlocker](https://github.com/kkapsner/CanvasBlocker/) there is an interesting possibility to open the settings page in a new tab. To do this, go to the settings page and at the top there will be an option to open the settings page in a new tab, the entire width of the window.

So I thought, why not do the same in your add-on.

**Comment by irvinm** [comment]
It is there.  Go to TST options, expand the last section ("development"), and it is the first link there ("Tree Style Tab Options").

**Comment by wvxwxvw** [comment]
Yes exactly. ) I thought it was an external link, I never clicked it.

Need to duplicate it at the top, otherwise it turns out illogical, you need to expand the page, but for this you will have to scroll her to the bottom.

**Comment by piroor** [comment]
TST provides a special short URI `ext+treestyletab:options`. It is stable on cross-environments and automatically resolved to actual `moz-extension://` URL by TST itself. I recommend you to bookmark it.

As described above, you can use TST's options page in tabs via a bookmark, so I think special new menu command looks unnecessary.

**Comment by wvxwxvw** [comment]
Not everyone reads the instructions, and those who do not know English do not read at all. But it's your business.

**Comment by piroor** [comment]
Hmm, another idea, how about a link like "open this options page in more wide space" at the top of the options page itself (near the "Unlock expert options" checkbox)? Links under the "Development" section were made just for my debugging, so I agree that they are not friendly for regular users.

**Comment by irvinm** [comment]
@piroor I like that idea.  Especially considering the DPI scaling issue they still have as well, the number of people who may want to use it would benefit from it being more prominent.

**Comment by wvxwxvw** [comment]
> n the addon [CanvasBlocker](https://github.com/kkapsner/CanvasBlocker/) there is an interesting possibility to open the settings page in a new tab. To do this, go to the settings page and at the **top** there will be an option to open the settings page in a new tab, the entire width of the window.
> 
> So I thought, why not do **the same in your add-on**.

**Comment by piroor** [comment]
Oops I missed the section...

**Comment by piroor** [comment]
Sorry I misunderstood the context. I thought that this request was about a new menu item to open options page.
After the commit ab90dc2 now there is the link at top-right corner of the options page.
