### ISSUE TITLE
Cannot click a tab to switch to it

### ISSUE THREAD

**Issue by JakeStanger** [piroor/treestyletab#2512]
## Short description

I am unable to click on a tab within the tree to switch to it. All other functionality of the extension appears to be working.

Clicking a tab highlights it to show it is selected. This causes both the current tab and the clicked tab to show as highlighted.

![image](https://user-images.githubusercontent.com/5057870/76414604-8faa5780-638f-11ea-80e4-db8c069aaf32.png)

(while in new issue tab)

## Steps to reproduce

 1. Start Firefox with clean profile (including deleting all profiles, uninstalling firefox, deleting all Mozilla app data and rebooting).
 2. Install TST.
 3. Open more than one tab
 4. Attempt to switch tab by left clicking on it inside TST

## Expected result

The focused tab switches to the tab that is clicked on.

## Actual result

The tab is marked as selected but nothing happens.

## Environment

- Windows 10 Enterprise 1903
- Firefox 74.0 stable
- Tree Style Tab 3.4.1

I have TST at home with the same Firefox version on Linux, where the issue *does not* occur.

**Comment by piroor** [comment]
You really use TST 3.1.2? It is looks too old version.

**Comment by JakeStanger** [comment]
> 
> 
> You really use TST 3.1.2? It is looks too old version.

It looks like the page that opened on install showed the wrong version. I am actually on 3.4.1, updated main post.

**Comment by piroor** [comment]
I've seen your screenshot: it says you use Multiple Tab Handler 3.1.2 and TST together. I think you use TST 3.4.1, the latest available version on addons.mozilla.org.

There is a known incompatibility #2504 with an addon [Move unloaded tabs for Tree Style Tab](https://addons.mozilla.org/firefox/addon/move-unloaded-tabs-for-tst/). The incompatibility has been fixed ad latest development version, and a newer released version is still waiting editor's review...

**Comment by piroor** [comment]
If you don't use Move unloaded tabs for TST, this can be a different issue. But sadly I couldn't reproduce this with Nightly + new profile. There looks to be something more hidden triggers on your environment.

**Comment by JakeStanger** [comment]
> If you don't use Move unloaded tabs for TST

🤦‍♂ I do. Disabling it has solved the problem.

I did look through open issues a couple of times and completely missed the existing issue. Apologies for that and thank you.
