### ISSUE TITLE
Dragging link won't open on last parent tab.

### ISSUE THREAD

**Issue by edtng** [piroor/treestyletab#2514]
## Short description
When a link from a new window is dragged on the last parent tab, it won't open as a child tab.

## Steps to reproduce
1. TST 3.4.6 on Firefox 74.0 (64-bit) new profile on Win10
2. When dragging a link from a Chrome or Firefox window onto an existing Firefox window.
3. Dragging link on the last parent tab of the panel.

## Expected result
Dragging the link on the last parent tab should open as a new child tab.

## Actual result
Dragging the link on the last parent tab does nothing.

## Additional note
Dragging a link on any other parent tab (that is not the last one) will open said link as a new child tab.

## Environment

 * Platform (OS): Windows 10 Pro 64bit
 * Version of Firefox: Firefox 74.0 (64-bit)
 * Version (or revision) of Tree Style Tab: TST 3.4.6

**Comment by piroor** [comment]
Thanks, the commit 7281f71 should fix this.

**Comment by piroor** [comment]
I close this because TST 3.4.7 is now available.
