### ISSUE TITLE
Empty addon options

### ISSUE THREAD

**Issue by Nexen23** [piroor/treestyletab#2517]
## Short description
Empty addon options in about:addons

## Steps to reproduce
1. Open about:addons
2. Open TST options

## Expected result
TST options are displayed

## Actual result
![image](https://user-images.githubusercontent.com/8696123/76629657-37cb4680-6571-11ea-8010-dc44b3174dcb.png)

## Environment
 * Platform (OS): Windows 10 
 * Version of Firefox: 74.0 (64-bit) (just migrated from Firefox 65.0.2. There were no problem)
 * Version (or revision) of Tree Style Tab: 3.4.6

The only way I was actually able to open menu is via `ext+treestyletab:options `
Which I found here:
https://github.com/piroor/treestyletab/issues/2342#issuecomment-519526421
Also is there a way to reset TST settings? Tried to reinstall it, but it seems settings aren't removed by deinstallation.

**Comment by piroor** [comment]
Any error in the console?
https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-start-debugger-for-tree-style-tab

**Comment by Nexen23** [comment]
> 
> 
> Any error in the console?
> https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-start-debugger-for-tree-style-tab

Yes, a few
![image](https://user-images.githubusercontent.com/8696123/76632234-77942d00-6575-11ea-8593-14007f27abe2.png)

**Comment by Nexen23** [comment]
Oh, forgot this:
![image](https://user-images.githubusercontent.com/8696123/76632396-c0e47c80-6575-11ea-889a-b6ab2ff66b1c.png)

**Comment by piroor** [comment]
Thank! Hmm, but sadly I couldn't find any effective information from these screenshots...

* In the first screenshot many red lines (errors) are reported, but they look to be not from TST.
* Metrics in the second screenshot is about the background process, but options page doesn't provide such information.

Could you try with a clean profile? If you still see same problem, disabling hardware acceleration of Firefox itself possibly affect to this problem.
https://github.com/piroor/treestyletab/wiki/How-to-run-Firefox-with-a-clean-profile

> Also is there a way to reset TST settings?

Creating a text file with the content `{}` (a pair of braces) and import it from TST options => Development => All Configs => Import, then all options are cleared. Sadly it cannot be done manually - today options of addons are stored in indexedDB databases, and they are too complex to look by non-developer users.

**Comment by Nexen23** [comment]
> 
> 
> Thank! Hmm, but sadly I couldn't find any effective information from these screenshots...
> 
>     * In the first screenshot many red lines (errors) are reported, but they look to be not from TST.
> 
>     * Metrics in the second screenshot is about the background process, but options page doesn't provide such information.
> 
> 
> Could you try with a clean profile? If you still see same problem, disabling hardware acceleration of Firefox itself possibly affect to this problem.
> https://github.com/piroor/treestyletab/wiki/How-to-run-Firefox-with-a-clean-profile
> 
> > Also is there a way to reset TST settings?
> 
> Creating a text file with the content `{}` (a pair of braces) and import it from TST options => Development => All Configs => Import, then all options are cleared. Sadly it cannot be done manually - today options of addons are stored in indexedDB databases, and they are too complex to look by non-developer users.

With clean profile options work fine.
Also tried to import `{}`, but didn't help.
Also tried to export, but I also got empty page with nothing happend.

Is it too complicated to clear addon data from indexedDB? I am a developer, but can google a way to remove just extension data.
E.g. https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector tells nothing about extensions : (

**Comment by piroor** [comment]
You can inspect all data of TST via the debugger attached to TST (started from about:debugging). I've confirmed that you can clear all storage with the storage inspector in the debugger:
![image](https://user-images.githubusercontent.com/70062/76653864-fa84aa00-65ac-11ea-8ad8-2c04f40c8c8f.png)
Clearing all data in listed storage may affect to this problem, but I think that the trigger of the problem is in not only TST, for example Firefox's cache. I cannot answer what causes the problem, so I hope you find out it by your hand.

**Comment by Nexen23** [comment]
> 
> 
> You can inspect all data of TST via the debugger attached to TST (started from about:debugging). I've confirmed that you can clear all storage with the storage inspector in the debugger:
> ![image](https://user-images.githubusercontent.com/70062/76653864-fa84aa00-65ac-11ea-8ad8-2c04f40c8c8f.png)
> Clearing all data in listed storage may affect to this problem, but I think that the trigger of the problem is in not only TST, for example Firefox's cache. I cannot answer what causes the problem, so I hope you find out it by your hand.

I think it actually worked for a second (at least overlapping tabs cease to bug out), but after a few seconds, FF restored TST settings by itself and problem occurred again.

Seems the only way to fix this is to migrate to clean profile :( 
Anyway, thanks for helping out. Shame for Firefox to not allow clean addons cache : /
