### ISSUE TITLE
Support reverse-order of tabs (show newest at top of list)

### ISSUE THREAD

**Issue by notmgsk** [piroor/treestyletab#2521]
I searched through the config options to see if this was currently available. There were a couple options that mentioned where to insert child tabs, but this seems to not affect new-tab actions.

**Comment by piroor** [comment]
This looks to be a duplicated of #1882. In short: I believe that this feature is useful for non-Tree Style Tab users and it should be provided as a separate addon.

[I wrote a sample code to implement such an addon](https://github.com/piroor/treestyletab/issues/1882#issuecomment-438892656) but sadly no one looks to publish such a feature as an addon yet. (I think this may become a good first step to develop Firefox/Chrome addon for you.)

**Comment by notmgsk** [comment]
> This looks to be a duplicated of #1882. In short: I believe that this feature is useful for non-Tree Style Tab users and it should be provided as a separate addon.
> 
> [I wrote a sample code to implement such an addon](https://github.com/piroor/treestyletab/issues/1882#issuecomment-438892656) but sadly no one looks to publish such a feature as an addon yet. (I think this may become a good first step to develop Firefox/Chrome addon for you.)

Apologies for the duplicate, and thanks for the info.
