### ISSUE TITLE
Can't Drag entire trees anymore. 

### ISSUE THREAD

**Issue by tylandercasper** [piroor/treestyletab#2522]
## Short description
If I try to move a tree, it just moves the root, and than leaves all of the children in the original place as though I had just deleted it. 
## Steps to reproduce
Open Two Tabs (A and B) and put them so they're the same level. 
  Open a new tab (C) so that it's a child of the first tab. 
A
--C
B

Drag the First tab (A) into the second tab. 

## Expected result
B
--A
----C

## Actual result
C
B
--A

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: Firefox Developer 75.0b3 (64 bit)
 * Version (or revision) of Tree Style Tab: 3.4.6

**Comment by piroor** [comment]
This doesn't happen on my environment: TST 3.4.6 on Nightly 76.0a1. Any other condition to reproduce? If this doesn't happen [on a clean profile](https://github.com/piroor/treestyletab/wiki/How-to-run-Firefox-with-a-clean-profile) something [helper addon](https://github.com/piroor/treestyletab#addons-that-extend-tst) can affect to this.

**Comment by NightSharp** [comment]
Try to hold on shift before drag the page A

**Comment by tylandercasper** [comment]
> Try to hold on shift before drag the page A

Hey that works! Is there a way to make it so that I don't have to hold shift?

Thanks!

**Comment by piroor** [comment]
Could you check status of the "Drag and Drop" section in the TST Options? This is the expected default state:
![image](https://user-images.githubusercontent.com/70062/76086331-3e007680-5ff7-11ea-89e6-52948549f943.png)
If you choose "Detach Individual Tab from..." or "Create link or bookmark from Individual Tab..." for "Drag", this may happen, and choosing "Detach Whole Tree..." or "Create links or bookmarks from Whole Tree..." may solve it.

**Comment by tylandercasper** [comment]
Yep, that was it! 
Thanks so much.

**Comment by Mzyxptlk** [comment]
I ran into the same issue, the suggested configuration settings fixed it. Thanks!

There's one thing that confuses me about this: the configuration setting says "how tabs are treated when dropped **outside** of TST's sidebar", but the setting also affects drag-and-drop within the sidebar. It'd be nice if the description better matched the effect.

**Comment by piroor** [comment]
@Mzyxptlk The suggestion is reasonable. I've updated labels of those options with these commits:
https://github.com/piroor/treestyletab/commit/616106f668d785487bc2306d1a4125a2da74ccf7
https://github.com/piroor/tst-active-tab-in-collapsed-tree/commit/d555fdd7245de64e190e9c990829082e1f78cfc5

**Comment by piroor** [comment]
@NightSharp I'm sorry that I've modified some labels of drag and drop options. Could you update zh_CN translation again?

**Comment by Mzyxptlk** [comment]
Thanks. :)
