### ISSUE TITLE
Multi-Account Containers not handled

### ISSUE THREAD

**Issue by AlexKroeker** [piroor/treestyletab#2529]
## Short description
When using Firefox Multi-Account Containers TST is reopening the tabs as regular tabs on startup.

## Steps to reproduce

 1. Start Firefox with clean profile.
 1. Install TST.
 1. Open tab in new environment of the Firefox Containers
 1. Close Firefox with setting "Restore previous session" active
 1. Start Firefox 

## Expected result

The containered Tab is still in the specified container.

## Actual result

The containered tab is now a regular tab.

## Environment

 * Platform (OS): Windows 10 Build 1909
 * Version of Firefox: 74.0
 * Version (or revision) of Tree Style Tab: 3.4.7

**Comment by piroor** [comment]
Sadly I couldn't reproduce the problem you told. There is no description to install the Firefox Multi-Account Containers addon, so I think you looked to omit some required steps to reproduce. (Please remind that I just try the steps to reproduce you wrote as-is.)

By the way, another issue #2305 looks similar to this.

**Comment by Sada-Mio** [comment]
I have steps to recreate issue with TST & MAC 

1. New Firefox profile
2. Install TST & MAC
3. Visit Amazon.com, set MAC to "Always open in Shopping"
4. Visit Google.com, set MAC to "Always open in Work"
5. Visit Facebook.com, set MAC to "Always open in Personal"
6. Arrange tab tree as
Amazon.com (parent)
\> Google.com (child)
\>\> Facebook.com (child)
7. Right click Amazon.com (parent) tab, Tree of tabs, Bookmark this tree
8. Close all tabs
9. Open All as tree from previously created bookmark
10. Click Google.com (child of Amazon), tree hierarchy will break. Google looses child tab

Because bookmarked trees doesn't remember container information it is re-open as default container. If a parent tab is activated & "always open in" is remembered, MAC will close/re-open that tab in the correct container. However,  child tabs will lose a parent and be promoted.

**Comment by piroor** [comment]
I've introduced some changes to TST, it is not a solution of this issue but related.

After a research I realized that an addon [Container Bookmarks](https://addons.mozilla.org/firefox/addon/container-bookmarks/) provides ability to bundle a bookmark to a container, based on some behaviors of [Firefox Multi-Account Containers](https://addons.mozilla.org/firefox/addon/multi-account-containers/). It stores the container information as a fragment of the URL like `#container-personal`, so now TST saves container information of tabs to bookmarks with this format. And, when you try to open bookmarks via commands provided by TST, TST opens bookmarks with specific container tabs based on this information.

**Comment by piroor** [comment]
I think that lost container information of restored tabs is a problem of Firefox itself. See also:
https://github.com/piroor/treestyletab/issues/2181#issuecomment-472772365
I believe that the container of restored tabs should be reproduced by Firefox - I believe it is one of responsibilities of Firefox itself. Multi-Account Containers tries to do some workaround for the problem, but it looks should be solved fundamentally on Firefox side.


Anyway, I see that there still be a compatibility issue with TST and FMAC about reopening tab with a container immediately when tabs are opened. Currently I don't have any idea to solve this conflict...

**Comment by piroor** [comment]
I've removed codes to save container information to bookmarks, and instead I've done a PR to Bookmark Containers to improve compatibility with other addons: https://github.com/rafaelgssa/container-bookmarks/pull/5

**Comment by piroor** [comment]
I've found the reason why TST fails to keep the tree structure. In old versions FMAC opens a successor tab and closes the original tab more slowly, so the successor was attached to the original tab as its first child and removed after that. On the other hand, at the latest version of FMAC the original tab is closed before the successor tab is completely initialized on TST. With the commit 76bb154 now TST tries to detect the possibly successor tab and attach it into existing tree.

**Comment by piroor** [comment]
TST 3.5.4 is now available. If you don't see the problem anymore, could you close this? @AlexKroeker

**Comment by AlexKroeker** [comment]
Trank you very much @piroor for the fixes I will test it soon and thank you very much @Sada-Mio for your clarifications!

**Comment by AlexKroeker** [comment]
its fixed
