### ISSUE TITLE
First root tab are not shown after restoring it

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#2531]
## Short description
The first root tab may not display after closing and restoring.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Pin at least 1 tab.
 4. Open a normal tab. I think it is easier to reproduce if you open a blank tab then navigate to other page.
 5. Make sure the tab is the first root tab after the last pinned tab. 
 6. Quickly close the normal tab and restore it.

## Expected result
The restored tab is shown on TST sidebar.

## Actual result
The restored tab disappears in a flash.
Screencast: https://giant.gfycat.com/VigorousInferiorArcticwolf.webm

## Notes
1. It is not a recent regression.
2. It is not 100% but easier to reproduce if you restore the tab immediately after closing it.
3. It only occurs on the first root tab, and without any children, as far as I know.

## Workaround
Close and re-open TST sidebar.

## Environment

 * Platform (OS): Win10
 * Version of Firefox:  74.0 or Nightly 2020-03-24
 * Version (or revision) of Tree Style Tab:  3.4.7

**Comment by piroor** [comment]
I've seen similar result so I think that the problem has been reproduced on my environment successfully. And I've seen an unhandled error on the case, so I've introduced a change to guard such a case with the commit e67ea8b. I hope it solves the problem you saw also...

**Comment by Fanolian** [comment]
It should be fixed in 3.4.8. Thanks a lot!
