### ISSUE TITLE
I think this should be done by an user script (userChrome.js) or another addon which provides the feature "group new tabs by pre-defined conditions automatically". In other words, I have no plan to add such a feature to TST itself. For such needs, TST has some public APIs to control tree of tabs. See: http://piro.sakura.ne.jp/xul/_treestyletab.html.en#api

### ISSUE THREAD

**Issue by jrock4eva** [piroor/treestyletab#2537]
I think this should be done by an user script (userChrome.js) or another addon which provides the feature "group new tabs by pre-defined conditions automatically". In other words, I have no plan to add such a feature to TST itself. For such needs, TST has some public APIs to control tree of tabs. See: http://piro.sakura.ne.jp/xul/_treestyletab.html.en#api

Because I have very few time to maintain my addons and I cannot maintain too many various features which I never use, I decided to keep codes simple except some cases like locales (translations). I'll implement it or add new APIs for the requirement, if it is really cannot be implemented as an independent addon with existing public APIs. Sorry.

_Originally posted by @piroor in https://github.com/piroor/treestyletab/issues/509#issuecomment-17733013_

**Comment by piroor** [comment]
Is this posted mistakenly?

**Comment by piroor** [comment]
I close this for now because this looks to be posted mistakenly and there is no response.
