### ISSUE TITLE
Automatically open new tabs as independent tabs

### ISSUE THREAD

**Issue by chaoscreater** [piroor/treestyletab#2544]
The description for this addon says this:

> New tabs opened from the current tab are automatically organized as "children" of the current.

Is there a way to change this behaviour? In Firefox, if I'm doing a Google search, I'll tend to middle mouseclick on multiple links in the search results. These search results open up as child tabs of the Google search tab. I don't want this. I want them to open as independent tabs.

I mainly just want to use Tree Style Tab to manually organize the tabs into their own groups. I don't want it to automatically manage the tabs for me.

**Comment by piroor** [comment]
It is in the FAQ: https://github.com/piroor/treestyletab/blob/master/README.md#faq--frequently-rejected-requestsproposals

**Comment by irvinm** [comment]
@piroor I think we can close this one.
