### ISSUE TITLE
Opening new tab with empty page causes tab to be opened at end of the tree

### ISSUE THREAD

**Issue by Hoeze** [piroor/treestyletab#2545]
## Short description
TST ignores new tabs with empty page

## Steps to reproduce
- configure firefox to open new tabs with empty page
- configure TST to open new tabs as sub-tree
- press CTRL+T

## Expected result
Tab opens as sub-tree of current tab

## Actual result
Tab opens at end of tree, independent of TST config

## Environment

 * Platform (OS): 
arch linux
 * Version of Firefox: 74.0
 * Version (or revision) of Tree Style Tab: 3.4.8

-----------

This feature would be quite important to me, because if I configure new tabs to open with "about:newtab" TST will handle the new tab properly but it will take temporary containers up to 10 seconds to change the tab context. In the mean time, everything I type in the URL just disappears.
=> I have to wait up to 10s for a new tab to be opened.

With an empty window, temporary containers will only change the tab context AFTER I entered something in the URL bar.

**Comment by irvinm** [comment]
In about:config, set browser.tabs.insertAfterCurrent to true.  I think that is what you want.

**Comment by Hoeze** [comment]
@irvinm I tried this but this causes another problem:
Using this option causes the tab to stay in the default context and never be treated by temporary containers...

=> If TST would be able to correctly capture the newly created tab it would be sufficient to solve my problem.

**Comment by piroor** [comment]
This is a restriction of WebExtensions based addon. TST detects a newly opened tab is a "new blank tab" or not based on its URL, but new tabs opened by Firefox have its URL `about:blank` initially always, even if they are opened from bookmarks or others. So TST cannot detect the tab is really opened as a blank new tab.

Just a workaround, you can set a custom shortcut for "Open a new tab: Child Tab" and use it instead of "Ctrl-T", for example "Ctrl-Alt-T". Such custom shortcuts are processed by TST directly so TST can open a new blank tab as the child correctly.

**Comment by irvinm** [comment]
@Hoeze can you close this item?

**Comment by Hoeze** [comment]
I see this issue as non-resolved because of Firefox as it is missing necessary API.
I'm closing it for now, but maybe some "needs upstream fix" label could make more sense?

**Comment by pintassilgo** [comment]
Just posting my workaround, maybe it helps someone.

I set the desired command (for me is "Open new tab: Next Sibling Tab") to a weird shortcut, I used Ctrl+Shift+F3.

But I want Ctrl+T, so I installed [keyconfig](https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/extensions/keyconfig) (Developer Edition or Nightly only, as normal Firefox can't install legacy addons), disabled Firefox's default Ctrl+T, created a new key with the following code (it simulates pressing Ctrl+Shift+F3) and assigned Ctrl+T to it.

```
setTimeout(function (){
  let TIP = Cc['@mozilla.org/text-input-processor;1'].createInstance(Ci.nsITextInputProcessor);
  TIP.beginInputTransaction(window, {});

  TIP.keydown(new KeyboardEvent('', {key: 'Control' }), TIP.KEY_NON_PRINTABLE_KEY | TIP.KEY_DONT_DISPATCH_MODIFIER_KEY_EVENT);
  TIP.keydown(new KeyboardEvent('', {key: 'Shift' }), TIP.KEY_NON_PRINTABLE_KEY | TIP.KEY_DONT_DISPATCH_MODIFIER_KEY_EVENT);

  let keyEvent = new KeyboardEvent('', {keyCode: 114});
  TIP.keydown(keyEvent);
  TIP.keyup(keyEvent);

  TIP.keyup(new KeyboardEvent('', {key: 'Control'}), TIP.KEY_NON_PRINTABLE_KEY | TIP.KEY_DONT_DISPATCH_MODIFIER_KEY_EVENT);
  TIP.keyup(new KeyboardEvent('', {key: 'Shift'}), TIP.KEY_NON_PRINTABLE_KEY | TIP.KEY_DONT_DISPATCH_MODIFIER_KEY_EVENT);
}, 0)
```

Done, now new tabs opened by Ctrl+T become the next sibling tab as I wanted.

I use the same approach in my mouse gestures script to switch to next/previous tab without expanding collapsed trees.

**Comment by pintassilgo** [comment]
I use TST, but tested [Sidebery](https://github.com/mbnuqw/sidebery) (similar addon) and somehow it doesn't have this issue. So it seems that there is a way to fix this in TST.
