### ISSUE TITLE
on demand "restore previous session" regression

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#2547]
##  Short description

Don't think it was perfect to begin with, vague remember some discussion of it, but my impression is it has gotten worse. Tabs are not restored correctly and on top tree coherence is broken, expanding/collapsing/clicking on one node actually expands/collapses/clicks another.

## Steps to reproduce

don't have time now for a clean repro case, later

## Environment

 * Platform (OS): win7 sp1 x64
 * Version of Firefox: 74.0.1 & 75
 * Version (or revision) of Tree Style Tab: 3.4.8

**Comment by piroor** [comment]
I'm waiting for a further report with detailed steps to reproduce...

**Comment by irvinm** [comment]
@piroor I think we should close this for now.  If @bughit gets provides more information we can revisit.

**Comment by piroor** [comment]
I close this for now. @bughit  Please comment again if you find out a detailed steps to reproduce the problem on a clean environment.
