### ISSUE TITLE
middle click on tab doesn't close it

### ISSUE THREAD

**Issue by rrrafalsz** [piroor/treestyletab#2548]
## Short description

clicking on the current tab with the middle button doesn't close the tab as expected. instead, the tab gets greyed out (inactive?). a second click closes the tab. i believe this used to work previously. on the regular firefox tabbar, the middle click closes the tab correctly.

## Steps to reproduce

install TST, open a tab, click on it with the middle mouse button.

## Expected result

the tab should close.

## Actual result

the tab becomes inactive but doesn't close.

## Environment

 * Platform (OS): windows 10
 * Version of Firefox: 74.0.1
 * Version (or revision) of Tree Style Tab: 3.4.8

**Comment by piroor** [comment]
Did you install "Tab Unloader for Tree Style Tab"?
https://addons.mozilla.org/firefox/addon/tab-unload-for-tree-style-tab/
It looks provides the behavior.

**Comment by rrrafalsz** [comment]
that was it. thanks and sorry! i thought i had checked all add-ons but missed this one. thanks again!
