### ISSUE TITLE
Where to find keyboard shortcut config?

### ISSUE THREAD

**Issue by nevubm** [piroor/treestyletab#2549]
I noticed the keyboard shortcut section in the options is gone, with this commit "Remove shortcut customization UI, because Firefox ESR68 already has it" https://github.com/piroor/treestyletab/commit/9cb3801617634c90b9c8f7cd0246e4de1bf2517b

I don't understand what this means? Is there a native Firefox options page to configure add-on shortcuts that I can't find? Is custom shortcuts no longer supported, either by Firefox or TST?

Thanks,

**Comment by piroor** [comment]
Here is a screenshot:
https://github.com/piroor/treestyletab/issues/2473#issuecomment-599551546
