### ISSUE TITLE
Tab flicker/steals focus when selecting parent after closing child

### ISSUE THREAD

**Issue by PeterJCLaw** [piroor/treestyletab#2550]
## Short description

I'm getting a flicker (I think caused by rapidly switching between tabs) after closing a child tab and then selecting to change tab to its parent.

This doesn't always happen -- it seems to be timing related. I _can_ reproduce this with my mouse, even without trying too hard to move quickly.

## Steps to reproduce

Given:
```
A
  B
C
```

- Close tab B.
  - I then end up with tab C selected and now want to view tab A.
- Select tab A

## Expected result

Switches to desired tab cleanly.

## Actual result

Appears to switch to desired tab, then back to the one previously selected, then to the desired tab, creating a visual flicker.

## Environment

 * Platform (OS): Ubuntu 16.04 LTS
 * Version of Firefox: 75.0, though I think I had this in 74 too
 * Version (or revision) of Tree Style Tab: 3.4.8 (2020.3.27)

**Comment by piroor** [comment]
Sorry I couldn't understand what is the problem with these steps:

1. Start Firefox with a clean profile.
2. Install TST 3.4.8.
3. Prepare tabs as:
   
   ```
   * A
     * B (child of B)
   * C
   ```
4. Click the tab B to activate it.
5. Close the tab B with the keyboard shortcut Ctrl-W.
6. Then the tab A is activated, not C.

If you change TST's options or use other addons together, then they may cause such a problem.

**Comment by PeterJCLaw** [comment]
Apologies, I no longer seem able to reproduce this. I had thought I'd found a slightly different set of steps which showed this, but trying on one of my other profiles (what the same extensions and what I thought were the same settings) that doesn't do it either.

I'll keep an eye out for this happening and come back if I can reproduce it again.

**Comment by PeterJCLaw** [comment]
Ok I'm still not completely sure how to reproduce this, however it seems that it'll only happen if when closing the child tab (B), we end up on the next sibling after that tab's parent (i.e: C rather than A).
I can't actually work out how to reliably get _that_ to happen, however when it does I can reliably then reproduce the flicker by switching to the original parent (A) shortly after closing the child.
