### ISSUE TITLE
increase font-size of tab text

### ISSUE THREAD

**Issue by LwsBtlr** [piroor/treestyletab#2551]
## Short description
After adding "font-size: 125% !important;" to the styles, the font-size of the items in TST does not change.

## Steps to reproduce
Open preferences for TST and under advanced add

  font-size: 125% !important;

to the tab-item.unread .label-content block, or add a block

```css
* { font-size: 125% !important; }
```

## Expected result
Font-size increase

## Actual result
No cange

 * Platform (OS):  macOS 10.15.4
 * Version of Firefox: 75.0
 * Version (or revision) of Tree Style Tab: 3.4.8

**Comment by piroor** [comment]
`tab-label { font-size: 125% !important; }` and `tab-item.unread tab-label { font-size: 125% !important; }` works for me. Could you try this?

**Comment by irvinm** [comment]
@piroor can you close this one?
