### ISSUE TITLE
Move Tab addon appears to be included in TST already

### ISSUE THREAD

**Issue by FreeTheSmoke** [piroor/treestyletab#2552]
## Expected result
That the TST addons are required for features not/no-longer included in the main app.

## Actual result
Addon is already installed as part of TST

![tabControls png](https://user-images.githubusercontent.com/38685664/78839910-cfbb3380-7a3c-11ea-9597-a596818dfb7a.jpg)
Edit (wrong Image originally posted)

## Environment

 * Platform (OS): *Win10* 
 * Version of Firefox: *74.0.1 (64-bit)*
 * Version (or revision) of Tree Style Tab: *Tree Style Tab 3.4.8*

**Comment by piroor** [comment]
Sorry I couldn't understand what is the topic of your initial post.

* Did you mean that the "Add to Firefox" button in the page https://addons.mozilla.org/firefox/addon/tab-mover/ should be grayed out when the "Tab Mover" is already installed? It is a problem of the Mozilla Add-ons website itself. If you prevent fingerprinting by webpages completely, Mozilla website may fail to detect the addon's status.
* Did you mean that extra commands added by the "Tab Mover" should appear in the "Move Tab to" submenu of TST's tab context menu? It is impossible: "Tab Mover" addon just adds its context menu commands to Firefox's tab context menu and they are imported to TST's tab context menu as last extra commands. Firefox doesn't provide ability to import such extra commands to arbitrary submenu defined by TST.

**Comment by irvinm** [comment]
@FreeTheSmoke the menu item "Move Tab" is a standard Firefox menu item and isn't related to either TST or Tab Mover in this context.  If you install Firefox with no add-ons you will still see this menu item.

![image](https://user-images.githubusercontent.com/979729/78895208-6cc99c80-7a3c-11ea-86c9-f934b3107c6e.png)

**Comment by FreeTheSmoke** [comment]
> @FreeTheSmoke the menu item "Move Tab" is a standard Firefox menu item and isn't related to either TST or Tab Mover in this context. If you install Firefox with no add-ons you will still see this menu item.
> 
> ![image](https://user-images.githubusercontent.com/979729/78895208-6cc99c80-7a3c-11ea-86c9-f934b3107c6e.png)


Ok, thanks had never noticed it


> Sorry I couldn't understand what is the topic of your initial post.
> 
>     * Did you mean that the "Add to Firefox" button in the page https://addons.mozilla.org/firefox/addon/tab-mover/ should be grayed out when the "Tab Mover" is already installed? It is a problem of the Mozilla Add-ons website itself. If you prevent fingerprinting by webpages completely, Mozilla website may fail to detect the addon's status.
....

@piroor Your first paragraph correctly describes what I was expecting, and the likely cause you suggested seems correct too as I run some privacy extensions - I'll check later today but you can close this anyway, I just reported because I thought it was a bug.

Left some 5 star feedback on the extensions store, thanks for making this and sharing.

**Comment by irvinm** [comment]
@FreeTheSmoke you can close out this issue as well. :)
