### ISSUE TITLE
[Feature] Shift + Middle Mouse Click to Close Tree

### ISSUE THREAD

**Issue by H8to** [piroor/treestyletab#2553]
## Short description
Just an idea as browsing the property menu is quite complicated. 

When I have the tree tab on the left side open I'd like to be able to `Shift + Middle-Click` on a tab-title to close it and all child nodes.

Is this reasonable and possible to be implemented?

`Middle-Click` works as expected :) 

As I just read your addition to #570 I might give it a try myself.

Thanks for this great add-on. Really helps to remove my tab mess :rofl:

**Comment by piroor** [comment]
Sorry, but I have no plan to add the option to TST as a built-in. This is a design policy of TST: less options but more flexible via API. Here is an example implementation:

```javascript
// Please save this as "background.js" and load as a background script.
const TST_ID = 'treestyletab@piro.sakura.ne.jp';
async function registerToTST() {
  try {
  let result = await browser.runtime.sendMessage(TST_ID, {
    type: 'register-self',
    name: 'Your Addon Name',
    icons: browser.runtime.getManifest().icons,
    listeningTypes: ['tab-mousedown', 'tab-mouseup']
  });
  }
  catch(e) {
    // TST is not available
  }
}

browser.runtime.onMessageExternal.addListener((message, sender) => {
  switch (sender.id) {
    case TST_ID:
      switch (message.type) {
        case 'ready':
          registerToTST();
          break;

        case 'tab-mousedown':
        case 'tab-mouseup':
          if (message.button == 1 &&
              !message.altKey &&
              !message.ctrlKey &&
              !message.metaKey &&
              message.shiftKey) {
            if (message.type == 'tab-mousedown') {
              const ids = [];
              const collectIds = tab => {
                for (const child of tab.children.reverse()) {
                  collectIds(child);
                }
                ids.push(tab.id);
              };
              collectIds(message.tab);
              browser.tabs.remove(ids);
            }
            return Promise.resolve(true);
          }
          break;
      }
      break;
  }
});

registerToTST();
```

This example is under the public domain, so please use it freely. If you publish it as an addon and and maintain it, the addon may help people who have similar demand.

**Comment by SHHSSH** [comment]
@H8to Can't you just write a script for this?

Also @piroor have you removed hotkeys options?

**Comment by paninaro95** [comment]
> Sorry, but I have no plan to add the option to TST as a built-in. This is a design policy of TST: less options but more flexible via API. Here is an example implementation:

I'd love to have this feature as well. How do you invoke this script? I'm a plain TST user, not a webextension developer 😉

**Comment by piroor** [comment]
@SHHSSH I removed the UI to customize keyboard shortcuts. But you still can customize shortcuts via `about:addons` (please click the gear icon).

@paninaro95 It should be used as a background script: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background

**Comment by SHHSSH** [comment]
@paninaro95 I will come back to you in a few hours later today, I will write you a basic auto hotkey script that you can compile into an exe to autorun at startup, or manually if you recognise you're starting to use the function a lot.

@piroor Thanks, I knew it was still adjustable as some were still set as custom. Didn't really look too much into it. 

Sorry for hijacking this issue, I'll try and create a little 3rd party script as a work around for others, so TST doesn't become over cluttered with features. I'm not versed in background scripts of add-ons, so will temporarily make a quickfix independent script and look into a set background script for TST later on, as it doesn't look too complicated, just a bit of JS to run with the addon.

**Comment by irvinm** [comment]
@H8to \ @piroor can we close this item?

**Comment by H8to** [comment]
Sure!
