### ISSUE TITLE
Bad performance with TST Mouse Wheel addon

### ISSUE THREAD

**Issue by account-login** [piroor/treestyletab#2554]
## Short description
There is a significant lag when switching tab with mouse wheel, and cpu usage is high.

## Steps to reproduce

 1. Start Firefox with a clean profile.
 2. Install TST.
 3. Install TST Mouse Wheel addon (https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab-mouse-wheel/?src=search).
 4. Open 50~100 tabs.
 5. Scroll mouse wheel at the sidebar.

## Expected result
Switch to another tab instantly.

## Actual result
Tab switch works, but there is a significant lag.

## Environment
Firefox develop edition 76.0b3 64bit
win7

## Analysis
I have identified 2 problems after some debugging.
The first problem is that `browser.sessions.getTabValue` seems to be blame. Performance profiling (https://perfht.ml/34EPEwA) shows that lots of time is spent on `getLastEffectiveFavIconURL`, which calls `browser.sessions.getTabValue`.
This problem can be fixed by caching: https://github.com/account-login/webextensions-lib-tab-favicon-helper/commit/aa12a561031120f77283869c521499e1f50da920
After applying the patch above, tab switching by mouse wheel works instantly.
There is a cache inside `TreeItem` class which can be removed if we add caching in `getLastEffectiveFavIconURL`:
https://github.com/piroor/treestyletab/blob/2cb3c0c371b0e6521a6598e960772162a2860e99/webextensions/common/tst-api.js#L178

The second problem cache miss in `TreeItem.exportTab`.
`TreeItem.exportTab` is called on **every tab** when a mouse wheel event occurs:
https://github.com/piroor/treestyletab/blob/2cb3c0c371b0e6521a6598e960772162a2860e99/webextensions/common/tst-api.js#L1016-L1019

And `TreeItem.exportTab` is called recursively on **child tabs**:
https://github.com/piroor/treestyletab/blob/2cb3c0c371b0e6521a6598e960772162a2860e99/webextensions/common/tst-api.js#L204-L213

To prevent duplicated work, the result of 
`TreeItem.exportTab` is cached.
Unfortunately the cache does not work, because these tasks is launched **concurrently**.

This problem can be fixed by caching the Promise of the task instead of caching the result:
https://github.com/account-login/treestyletab/commit/e8f092a27952ed238faad891666cd6c8867e9cb0

## Proposed fix
- https://github.com/account-login/webextensions-lib-tab-favicon-helper/commit/aa12a561031120f77283869c521499e1f50da920
- https://github.com/account-login/treestyletab/commit/e8f092a27952ed238faad891666cd6c8867e9cb0

**Comment by piroor** [comment]
Thank you for very detailed investigation and pull requests! I've merged both PRs and updated the revision of `webextensions-lib-tab-favicon-helper`. Could you check the performance with the latest master?

**Comment by account-login** [comment]
I can confirm that the performance issue is fixed in master.

**Comment by piroor** [comment]
TST 3.4.9 has been released and now downloadable. Thanks a lot!
