### ISSUE TITLE
modifications on active tab seems to not work

### ISSUE THREAD

**Issue by Rorschasch** [piroor/treestyletab#2558]
Hi,
It sounds that modifications on active tabs by adding code in option is not working

For example, copying this is not working 

tab-item.active {
  height: 39px !important;
  background-color: #193B99;
}
tab-item.active .label-content {
  font-weight: bold;
  font-size: 14px;
}
tab-item.active tab-twisty,
tab-item.active .label-content,
tab-item.active tab-counter {
  color: #fff;
}

I'm on firefox 75.0 and windows 10, using dark theme in firefox (but tried with clear and with default).

It sounds to me that 'active' is not recognised but I'm probably wrong as I'm not use of programming 
( for example this is working 

tab-item.unread .label-content {
  color: red !important;
  font-style: italic !important;
}

But if i replace "unread" by "active", it's not working)

i would like to modify the background color and text color of the selected tab to have detect him more easily.

Thanks for this great tool.

PS : sounds that code for change depends on containers don't works too.

Rorschasch

**Comment by piroor** [comment]
It looks working as expected for me. Screenshot:
![image](https://user-images.githubusercontent.com/70062/79454891-f3770e80-8026-11ea-9cf6-e4a441145218.png)

> PS : sounds that code for change depends on containers don't works too.

Did you wrote about https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#container-colored-background-for-tab-1879 ? It also works for me:
![image](https://user-images.githubusercontent.com/70062/79455347-afd0d480-8027-11ea-9041-f2f5aeedb346.png)

Could you paste your screenshot?

**Comment by irvinm** [comment]
@Rorschasch Do you still want to work on this issue?

**Comment by irvinm** [comment]
@piroor I think this can be closed as inactive.
