### ISSUE TITLE
"Open all as a tree" doesn't restore page titles and favicons except for the first tab

### ISSUE THREAD

**Issue by ngirard** [piroor/treestyletab#2559]
Using TST 3.4.9 / Firefox 72.0.1 / Ubuntu 19.04.

Despite following this project closely, I'm just discovering now, that the contents of a bookmarks folder can be restored as a tree with the original indentation preserved.
Wow... this is a game changer for me, and I wish to express my gratitude and thank you once again for your work, @piroor !

This report may seem like nitpicking, but once a folder has been restored by right-clicking on the folder and choosing "Open all as a tree", only the first tab is properly titled.

The other tabs only display their url until you click on them and the page is loaded.

I'd expect all the tabs to be properly titled, since the page titles have been already saved to the bookmarks database.

**Comment by irvinm** [comment]
It looks like all of the tabs other than the first tab are being created as discarded tabs, so the favico isn't set and the tab isn't actually loaded.  Obviously, clicking on the tab will properly set the favico and the page title.  This is probably a good behavior if you are trying to restore a larger number of tabs.  I could see where different people might want different behaviors.

I also noticed that if you are in the middle of an existing tree and restore a tree, the restored tree is restored as if it was the root tree.  Additionally, if you then try to collapse the parent tree, the restored tree is not collapsed within that tree.  (It acts as a root tree that is visually displayed within another tree but does not interact with it)

![D906D3D0-B696-49FE-A379-2977B71EB096](https://user-images.githubusercontent.com/979729/79623036-21705780-80e8-11ea-917e-9bc61d3f4788.GIF)

**Comment by ngirard** [comment]
Thank you for your comments @irvinm.
Indeed, the favicons are also missing and I'd also expect them to be restored properly. I'll rename this issue consequently.
One thing I've noticed is that when you right-click the folder, the context menu only displays the "Open all as a tree" menu entry from TST, while mine also shows "restore tree":

![bkfd_ctx_menu](https://user-images.githubusercontent.com/98098/79629419-edc61980-8149-11ea-9b11-75bfcd49dd34.png)

Where does this "restore tree" entry come from ? Is it native, or does it come from TST ?
Why do I have it and @irvinm doesn't ?

Anyway, when I choose "restore tree", the contents of the bookmarks folder is restored as a flat list of tabs, which are also inactive as expected, but they are properly titled nevertheless.
This suggests to me, that TST should be able to restore at least titles, if not favicons, properly.

**Comment by piroor** [comment]
>  This suggests to me, that TST should be able to restore at least titles, if not favicons, properly.

Thank you for reporting! After a research I've realized that it is unexpected result from my mistake. With the commit 0eff2e2 non-first tabs are opened with correct title. (Icons are still not restored, it is a restriction of WebExtensions API.)

> Where does this "restore tree" entry come from ? Is it native, or does it come from TST ?

It may be provided by another addon like "Bookmark Tree for Tree Style Tab". On Firefox, an addon can add just one item at the top level of the context menu, and TST already adds the "Open All as a Tree" item.

**Comment by irvinm** [comment]
FYI, here is the  WebExtension defect if anyone wants to vote for it [allow setting favicon when creating discarded tabs](https://bugzilla.mozilla.org/show_bug.cgi?id=1475240).  It looks like I even commented on it 2 years ago!

@piroor is there anything you can do around how the restored bookmark tree interacts with the existing tree or will it always be an independent tree even if restored within an existing tree?

**Comment by piroor** [comment]
@irvinm Sorry I missed it. The commit 09f47ea should fix it.

**Comment by ngirard** [comment]
@piroor, thanks for your fix ! To me, this deserves a release on its own, but I'm biased ;-)

@irvinm, thanks for the link. Moz's bugzilla is no place for the fainthearted... there are so many bugs that are left unsolved for ~decades~ years... you could die in there if you're not cautious! I think I'll pass for tonight...

**Comment by piroor** [comment]
TST 3.4.10 is now available.

**Comment by ngirard** [comment]
Thanks you very much @piroor !
