### ISSUE TITLE
'Reopen in Container' should hide in private browsing

### ISSUE THREAD

**Issue by gomita** [piroor/treestyletab#2562]
## Short description
'Reopen in Container' in tab context menu should hide in private browsing mode,

## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install TST.
 3. Go to 'about:addons' -> Tree Style Tab -> Details.
 4. Set 'Run in Private Windows' to 'Allow'.
 5. Open new private window.
 6. Open TST sidebar.
 7. Right-click a tab.

## Expected result
'Reopen in Container' does not appear.

## Actual result
'Reopen in Container' appears.
I also noticed that if I select 'Reopen in Container' -> 'Work', I got an error in Browser Console.
 Error: Illegal to set non-private cookieStoreId in a private window

## Environment
Windows 10
Firefox 75.0
Tree Style Tab 3.4.9

**Comment by piroor** [comment]
Thanks! I didn't know the command is unavailable on a private window.
