### ISSUE TITLE
Make compatible with OneTab extension

### ISSUE THREAD

**Issue by quantitative-technologies** [piroor/treestyletab#2563]
I tried out the Firefox OneTab extension, and really want to use it.

However, when I restore a window, my TST organization is lost. OneTab also does not put the tabs back in their original containers.

Can someone suggest an alternative to OneTab that works with TST?

Sorry if this isn't the right place for my question.

**Comment by piroor** [comment]
I've tried the addon OneTab and confirmed its tabs restoration is not compatible with TST. Sadly there is nothing can do for compatibility on TST side, instead OneTab needs to do some more things to improve compatibility with TST.

If you just need a session restoration feature, [Tab Session Manager](https://addons.mozilla.org/firefox/addon/tab-session-manager/) looks compatible. It has an option to improve compatibility with TST but you need to activate the option manually.

**Comment by quantitative-technologies** [comment]
Thanks for the suggestion. However, I was looking for automatic suspend. 

I guess the idea is that I could save my session, manually close some windows, and then restore them?

**Comment by irvinm** [comment]
If you are looking for automatic suspending of tabs (discarding tabs), [Auto Tab Discard](https://addons.mozilla.org/en-US/firefox/addon/auto-tab-discard/) is certainly compatible with TST.  This discarding keeps the tabs in the session, but removes all of the resources used by the tab.

**Comment by irvinm** [comment]
I use TSM and ATD together and they work really well with TST.  Is there anything more we can do with this item?  Can we close this item?

**Comment by quantitative-technologies** [comment]
I assume you are saying that TSM will restore the tabs that have been auto-discarded?

Interesting idea, but may I ask if TSM is "100%" reliable?

I noticed that on one of my Ubuntu systems firefox seems to automatically suspend tabs, and a white dot appears on these suspended tabs. But my other system does not do this (both have Firefox v76).

Yes, of course feel free to close. Thanks.

**Comment by irvinm** [comment]
I (personally) think TSM is very good and very reliable.  It will absolutely be able to restore tabs that have been auto-discarded using the native Firefox discard like with "Auto Tab Discard".  I consider TST\ATD\TSM three of my core addons to keep my system running smoothly with a means to restore tabs at any point in time if something bad happens with the profile.  (Make sure to enable external file backup of your sessions on startup as a backup via TSM)

Firefox does have a mechanism internally to discard tabs automatically when it is close to running out of memory.  However, Auto Tab Discard has several options on how it handles when to discard tabs and whether to change the favico or not.

@quantitative-technologies you can close the item with the "Close" or "Comment and Close" buttons.

**Comment by piroor** [comment]
One note: An issue can be closed by the reporter or the project owner (me) but I think it is better that an issue is closed by its reporter not me, because issues closed by me cannot be reopened by the reporter. This is the reason why I don't close issues aggressively.

**Comment by quantitative-technologies** [comment]
@irvinm "Firefox does have a mechanism internally to discard tabs automatically" I think there may be confusion between "discarding" and "suspending" tabs? I believe discarding tabs means they are removed/deleted. I have never seen Firefox do that by itself (without a plugin).

**Comment by quantitative-technologies** [comment]
@piroor OK, I will close it then, because the conversation is getting off-topic.

**Comment by irvinm** [comment]
@quantitative-technologies here is an article on the feature to discard tabs automatically when resources are low:  https://www.ghacks.net/2019/03/01/firefox-67-automatically-unload-unused-tabs-to-improve-memory/  There were some issues with it when it was first released still discarding tabs when memory was still available.  I think they have since changed the algorithm to detect available memory.

"Tab discarding" according to MDN:  "Some browsers automatically "discard" tabs that they don't think are likely to be needed by the user soon. The tab stays visible in the tabstrip and the browser remembers its state, so if the user selects a tab that has been discarded, it is immediately restored."

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/discard
