### ISSUE TITLE
Unable to close collapsed tree in TST 3.5.0

### ISSUE THREAD

**Issue by echophantom** [piroor/treestyletab#2564]
## Short description
When I try to close a collapsed tree and all of its child tabs, the dialog box that pops up is completely blank and cannot be clicked.

## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a child tab of the current tab by clicking any link.
 4. Collapse the parent/root tab.

Your tab structure should look like this:
![Tab example](https://user-images.githubusercontent.com/10179983/80160330-39c9f180-8582-11ea-9966-5ba6d5f8db46.png)

 5. Close the collapsed parent/root tab to close the entire tree.

## Expected result
Tab tree is closed.

## Actual result
Popup window titled "about:blank Close Tabs?" is generated and takes focus, but is completely blank aside from the title. Can't do anything other than close the popup window, and tab tree isn't closed.

Rolling back to TST version 3.4.1 fixed this, so I believe the issue is due to the change to dialog boxes noted in the 3.5.0 version notes.

## Environment

 * Platform (OS): MacOS Mojave 10.14.6
 * Version of Firefox: 68.6.1esr
 * Version (or revision) of Tree Style Tab: 3.5.0

**Comment by piroor** [comment]
Hmm, something wrong on ESR68...

**Comment by piroor** [comment]
After some research I've realized that a small change is required on ESR68. The commit c59c9c0de should fix this.

**Comment by piroor** [comment]
I've released 3.5.1. It will be downloadable after an editor's review.

**Comment by wvxwxvw** [comment]
Probably in the subject. I can not bookmark the tree. See the screenshot, it shows:
1. Working instance,
2. Test clean instance (empty profile), specifically checked on it,
3. Hidden window, which can not be called, there is only a ghost in the preview of the taskbar.

[![](https://i.imgur.com/3ZvCo9d.png)](https://i.imgur.com/Wf0hn66.jpg)

Update 3.5.1 is still unsigned, so I have not checked the fix yet. I am writing just for information. Win7 x64, Firefox ESR 68.7 x64.

**Comment by wvxwxvw** [comment]
Could not resist. Installed unsigned. The problem has disappeared.

**Comment by piroor** [comment]
TST 3.5.4 is now available, so I close this.
