### ISSUE TITLE
Bookmarking tree of tabs: dialog box is too slow to appear

### ISSUE THREAD

**Issue by ngirard** [piroor/treestyletab#2566]
Using TST 3.5.0 then 3.5.1 on Firefox 72.0.1 / Ubuntu 19.04.

The "Show dialogs as semi-modal popup windows" addition to TST 3.5.0 is a disaster to my workflow.

When clicking "Bookmark these tabs" or "Bookmark selected tree", it now takes 13 seconds on my system for the dialog box to appear.
(As a side note, the dialog box was blank in version 3.5.0 ; this has seemingly been fixed in v3.5.1).

**Comment by piroor** [comment]
I've introduced some changes to the dialog implementation. Could you try the latest development build via `about:debugging`? https://github.com/piroor/treestyletab#development-builds

**Comment by ngirard** [comment]
Hey @piroor, thanks for your efforts and sorry for the late reply.

I can see the changes your developments brought to the dialog box, but I'm afraid the time for the box to appear stayed the same.

I'd be very glad to test any further changes, but I might not be available until tomorrow 8AM (now is past 9PM in the Paris area). Apologies in advance.
Cheers !

**Comment by piroor** [comment]
Hmm, I can't imagine why it takes 13 seconds... This is the list of what TST does:

1. Opens a blank window with 16x16 size.
2. Resizes the window same to the opener browser window, and move outside the desktop.
3. Wait until the tab load finishes. (Because dialog contents will be replaced with a blank page loaded by Firefox if TST draws it immediately.)
4. Build the dialog contents.
5. Shrink the window size and move to its final position.

Could you investigate which is the step that takes too long time?

----

I think this popup window based dialog is required to improve user experience around special pages (about: pages and some websites of Mozilla), because the old style in-page dialog is not available on such cases if the sidebar is hidden.

**Comment by ngirard** [comment]
Hi @piroor ,

The longest step is the first one, it takes 10 seconds for the blank window to appear.

I can also report that the situation is the same after upgrading my system to Ubuntu 20.04 / Firefox 75.

**Comment by piroor** [comment]
Thanks. Could you try following steps?:

1. Go to `about:debugging`.
2. Choose "This Firefox" from the left sidebar.
3. Click "Inspect" of "Tree Style Tab".
4. Then a debugger tab for TST is opened.
5. Choose the "Console" tab.
6. Copy following script and paste to the console input field:
   
   ```javascript
   (async () => {
     let start, win;
     const results = [];
     const conditions = {
       type: { type: 'popup' },
       url:  { url: '/resources/blank.html' },
       size: { width: 16, height: 16 }
     };
     for (const parameters of [
       [],
       [conditions.type],
       [conditions.url],
       [conditions.size],
       [conditions.type, conditions.url],
       [conditions.type, conditions.size],
       [conditions.url, conditions.size],
       [conditions.type, conditions.url, conditions.size]
     ]) {
       const params = parameters.reduce((condition, params) => {
         return Object.assign(params, condition);
       }, {})
       start = Date.now();
       win = await browser.windows.create(params);
       results.push(`${JSON.stringify(params)}: ${Date.now() - start}`);
       browser.windows.remove(win.id);
     }
     console.log(results.join('\n'));
   })();
   ```
7. Hit the Enter key. Then some windows are opened and closed.
8. After all you'll see an output in the console like:
   
   ```
   {}: 285
   {"type":"popup"}: 414
   {"url":"/resources/blank.html"}: 421
   {"width":16,"height":16}: 573
   {"url":"/resources/blank.html","type":"popup"}: 540
   {"width":16,"height":16,"type":"popup"}: 479
   {"width":16,"height":16,"type":"popup","url":"/resources/blank.html"}: 402
   {"width":16,"height":16,"type":"popup","url":"/resources/blank.html"}: 369
   ```
9. Copy the result and paste to here.

This research should make the condition which taks time clear.

**Comment by ngirard** [comment]
Hi and kudos for these very detailed instructions.
Here's the output of the execution:
```
{}: 748
{"type":"popup"}: 1183
{"url":"/resources/blank.html"}: 1208
{"width":16,"height":16}: 1366
{"url":"/resources/blank.html","type":"popup"}: 1290
{"width":16,"height":16,"type":"popup"}: 1487
{"width":16,"height":16,"type":"popup","url":"/resources/blank.html"}: 975
{"width":16,"height":16,"type":"popup","url":"/resources/blank.html"}: 1125
```

Is it to say that you're not experiencing the same delays yourself ? Which system are you using, it you don't mind me asking ?
Cheers

**Comment by RanHum** [comment]
Here is mine results as well:
```
{}: 515
{"type":"popup"}: 1109
{"url":"/resources/blank.html"}: 1174
{"width":16,"height":16}: 1150
{"url":"/resources/blank.html","type":"popup"}: 1147
{"width":16,"height":16,"type":"popup"}: 1172
{"width":16,"height":16,"type":"popup","url":"/resources/blank.html"}: 1014
{"width":16,"height":16,"type":"popup","url":"/resources/blank.html"}: 988
```
I run firefox 76.0b8 (64-bit) on Win 10 1909 (i5-2520M) with 2 windows and ~1300 tabs, customized ShadowFox userChrome.css and about 30 extensions... my total delay is about 3-4 seconds though

**Comment by piroor** [comment]
@ngirard  Thanks! Hmm, the result says that window open operation takes only about 1sec. There looks to be another bottleneck. Could you try again with this development build?: [treestyletab-we.zip](https://github.com/piroor/treestyletab/files/4535370/treestyletab-we.zip)

1. Go to `about:debugging`.
2. Choose "This Firefox" from the left sidebar.
3. Click the "Load Temporary Add-on..." button and choose the downloaded "treestyletab-we.zip".
4. Click "Inspect" of "Tree Style Tab".
5. A debugger tab for TST is opened, then choose the "Console" tab.
6. Do any operation produces a semi-modal popup. (for example: "Bookmark this Tree")

Then you'll see a result in the console, like following:

```
showInPopup:
get window: 2
open window: 284
move and resize window: 68
wait tab load: 168
ready to resize: 183

showInTab:
define RichConfirm in tab: 45
inject and execute: 1383
```

> Is it to say that you're not experiencing the same delays yourself ? Which system are you using, it you don't mind me asking ?

Luckily or unluckily, I didn't see such a very large delay. Examples in my comments are actual results on my environment: Firefox 75 on Windows 10, i3-7100 3.90GHz CPU, 16GB RAM. And here is a result on an Ubuntu 18.04LTS VM (VirtualBox) on the PC:

```
showInPopup:
get window: 4
open window: 357
move and resize window: 339
wait tab load: 230
ready to resize: 198

showInTab:
define RichConfirm in tab: 21
inject and execute: 3268
```

@RanHum You too see very large delay? Could you try the instructions above?

**Comment by piroor** [comment]
Ah, now I've realized that this problem can happen if you have very large number of bookmarks. While these operations TST tries to stringify the list of all bookmark folders and parse it, so it can take very long time.

**Comment by RanHum** [comment]
Here you go:
```
showInPopup:
get window: 4
open window: 355
move and resize window: 375
wait tab load: 270
ready to resize: 392

showInTab:
define RichConfirm in tab: 46
inject and execute: 6308
```

**Comment by piroor** [comment]
A new development build with a small optimization: [treestyletab-we.zip](https://github.com/piroor/treestyletab/files/4535483/treestyletab-we.zip)

**Comment by RanHum** [comment]
```
showInTab:
define RichConfirm in tab: 53
inject and execute: 2

showInPopup:
get window: 31
open window: 352
move and resize window: 358
wait tab load: 250
ready to resize: 232
```
Well, dialog window appears promptly and then folder list appears, but I think delay is even slightly bigger than before, certainly not faster... and somehow after first load and test for this dialog I managed to completely shut off mouse input on sidepanel, didn't check the logs, my bad...

**Comment by piroor** [comment]
@RanHum  On you case each step just took 200-300 msec. If you still see 10 sec or more delay, it happens on a point I didn't mentioned, but I can't imagine where is the bottleneck...

By the way, the "completely shut off mouse input on sidepanel" problem is a side effect of the semi-modal popup. You can reset the status with hiding and re-showing the sidebar.

**Comment by RanHum** [comment]
No, not 10+ sec, ~4-5 sec as in my first comment there, only it happens after dialog window shows up, not before. I tried to record profile for this moment, not sure if it helps: 
[profile.zip](https://github.com/piroor/treestyletab/files/4535832/profile.zip)

**Comment by ngirard** [comment]
@RanHum , thanks for your help in diagnosing !

@piroor , the [development build](https://github.com/piroor/treestyletab/files/4535370/treestyletab-we.zip) made a big difference: it takes now just ~3 seconds for the dialog box to appear.

Unfortunately, the dialog box is still impossible to use:

1. There's a new glitch with the combo box for the directory: the default entry is void, as shown in this screenshot:
![image](https://user-images.githubusercontent.com/98098/80315207-66863f00-87f6-11ea-9a53-4b45f455ff18.png)

If I leave the directory combo box as is and click ok, I cannot retrieve the newly created tabs folder -- at least I couldn't retrieve it after looking for it.

2. Whenever I click the directory combo box, it takes 50 seconds until the value is set to the previous default (in my case, "ref 1"):

![Screenshot_20200426_195515](https://user-images.githubusercontent.com/98098/80315722-b9152a80-87f9-11ea-8002-53d5522e393b.png)

This behavior is new ; in the past, when the dialog box appeared, it came with the default value for the directory combo box already set.

3. Now, the following is not new but I never reported it because I didn't want to bother you ; but if I want to change the destination directory to another one by clicking the directory combo box, it takes 1'13" for this menu to appear, showing the first-level entries:

![Screenshot_20200426_195726](https://user-images.githubusercontent.com/98098/80315728-be727500-87f9-11ea-8f5a-f1c0b184d450.png)

4. Then, when I click the "Autres marques-pages" menu entry ("other bookmarks" in French), it runs forever and at this point I cannot but cancel the operation. Here, I stopped the clock at 5 minutes and it was still stuck:

![Screenshot_20200426_200308](https://user-images.githubusercontent.com/98098/80315714-aa2e7800-87f9-11ea-9e8e-447e6975acb1.png)

Like I said, I never reported it and what I would do was to "file" the new tree of tabs to the default destination ("Ref 1" in my case), then I would manually cut and paste it to the desired destination.

I'm afraid it's not feasible any longer with the new behavior... sorry for reporting all these bad news !

**Comment by piroor** [comment]
@ngirard Thanks! The largest bottleneck is the operations to transfer bookmarks between processes on your case, and I agree that current implementation is designed just for small number bookmark folders. Now I'm planning to update the implementation to retrieve bookmarks tree incrementally.

@ngirard @RanHum Even if I successfully remove the largest bottleneck in a future, operations to open popup windows looks to take too much time (3-4 sec.) at your environment basically. To solve the delay I need to prepare a popup window before it is triggered and recycle on every cases. But I'm afraid that such a change will make things too complex...

**Comment by piroor** [comment]
I've introduced some more optimizations. I hope the new development build https://github.com/piroor/treestyletab/blob/master/README.md#development-builds becomes better...

**Comment by ngirard** [comment]
@piroor, thank you so much for your efforts. It's always a pain for me to see how much time and energy you need to invest in bypassing all those stupid limitations in Firefox's APIs.

The latest build is indeed a nice improvement:

* It seemingly takes as long (~3 seconds) for the dialog box to appear, but its appearance is much more visually acceptable ;
* Clicking the folder combo box changes its state from empty to the latest folder in 7 seconds, as opposed to 50 previously ;
* Clicking again the folder combo box popes up the context menu with the first-level entries quasi-immediately, as opposed to 1'13" previously.

So you're definitely on the right track !

That said, the folder combo box still cannot be used (at least on my system) to change the folder destination to another one ; and I'd it to be populated with the previously chosen folder in the first place, instead of having to click on it for the value to be set.

Cheers,
Nicolas

**Comment by RanHum** [comment]
I tested build from [commit eaee0be](https://github.com/piroor/treestyletab/actions/runs/88788920), it's certainly usable, only ~2s to show initial combo box after dialog appears and minor delay (<= 1 sec) to load subfolders' content (2nd level entries). And it doesn't happen to lock input in sidepanel so far, just for the record. With that build I'm only somewhat confused that full-fledged new firefox window opens like two times faster than this dialog window

**Comment by piroor** [comment]
I've introduced some more fixes to solve the blank combo box problem.

> That said, the folder combo box still cannot be used (at least on my system) to change the folder destination to another one ; and I'd expect it to be populated with the previously chosen folder in the first place, instead of having to click on it for the value to be set.

TST doesn't save the information about last chosen folder. The field is always initialized with the default parent folder configured in the TST's options page (under the "Context Menu" section). To improve experience about deeply nested folders, we need to implement a tree view UI. But it will make the dialog open more slowly...

**Comment by davidmbesonen** [comment]
When I was using TST 3.5.3 I had the same problem with the "Bookmark this Tree..." function wrecking my workflow because it took so long for the default folder to appear.  So I temporarily downgraded to TST 3.4.10 and the "Bookmark this Tree..." function went back to being super snappy.

Why is the old dialog box so much more responsive than the new one?

**Comment by piroor** [comment]
> Why is the old dialog box so much more responsive than the new one?

I think the question should be inverted: why a dynamically constructed popup window is too slow on this case? The dialog implementation is quite same both in the existing sidebar and in a newly opened popup window, except in-popup dialog is executed as a content script. I can't believe that the one difference critically make things very slow, so there may be something other differences I missed...

**Comment by davidmbesonen** [comment]
> 
> 
> > Why is the old dialog box so much more responsive than the new one?
> 
> I think the question should be inverted: why a dynamically constructed popup window is too slow on this case? The dialog implementation is quite same both in the existing sidebar and in a newly opened popup window, except in-popup dialog is executed as a content script. I can't believe that the one difference critically make things very slow, so there may be something other differences I missed...

I have quite a few bookmark folders.

Are you thinking there might be other possible causes besides what you mentioned earlier, "TST tries to stringify the list of all bookmark folders and parse it".

**Comment by irvinm** [comment]
@piroor is there anything more to do here?  It looks like it has been improved ...

**Comment by piroor** [comment]
After this issue the implementation of the dialog was more improved and a new option to show dialogs inside the sidebar instead of separate popup was added. I hope those improvements should help people who suffered from this slow down issue.

I close this for now to cleanup the list of unsolved issues, but it is welcome to add more comments here.
