### ISSUE TITLE
Conflict with Tab Mix Plus smooth scroll

### ISSUE THREAD

**Issue by her34** [piroor/treestyletab#257]
Firefox 10
Tab Mix Plus 0.4.0
Tree Style Tab 0.14.2012021101

Problem:
Tab Mix Plus 0.4.0 added feature smooth scoll which is just scrolling with inertia on tab bar. So you spin mouse wheel slowly then tab bar scrolls 1 tab, if you spin wheel fast then tab bar scrolls many tabs.

With Tree Style Tab in vertical tab mode, Tab Mix Plus 0.4.0 is still smooth scrolling on tab bar when there should be none. Even after disabling smooth scrolling in Tab Mix Plus first, the effect is still there in Tree Style Tab. Tab Mix Plus 0.3.8.7 does not cause the problem.

Tree Style Tab 0.14.2012021101 = no problem

Tab Mix Plus 0.3.8.7 + Tree Style Tab 0.14.2012021101 = no problem

Tab Mix Plus 0.4.0 + Tree Style Tab 0.14.2012021101 = problem

Even with toolkit.scrollbox.smoothScroll to false, Tab Mix Plus 0.4.0 smooth scrolling is not disabled. 

Tab Mix Plus author suggested this problem should be looked at by Tree Style Tab author

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
