### ISSUE TITLE
[Feature] Bookmark "Open All as tree" for child tree

### ISSUE THREAD

**Issue by Sada-Mio** [piroor/treestyletab#2570]
Ability to "Open All as tree" for child tree instead of the entire parent would be nice for large nested bookmarks.

**Comment by davidmbesonen** [comment]
This would be especially nice if the desired container could be specified.

**Comment by piroor** [comment]
@Sada-Mio Did you mean that you hope to open only some bookmarks in a folder, for example, when a folder contains 10 bookmarks created from a tree and only last 5 tabs need to be opened?

@davidmbesonen Container feature are not in purposes of TST except emulation of Firefox's native tab context menu commands, so I'm negative to add the feature. I think an addon created for bookmarks and containers (like  https://addons.mozilla.org/firefox/addon/open-bookmark-in-container-tab/ ) should provide the feature instead.

**Comment by Sada-Mio** [comment]
├── A1
│   ├── B1
│   │   ├── C1
│   │   ├── C2
│   │   ├── C3
│   ├── B2
│   ├── B4
│   │   ├── D1
│   │   ├── D2
│   └── B5

Currently, "Open All as a Tree" only works for A1, opens everything (A-D). 

Ability to select a child tree (B1) from bookmark to open (B-C)

**Comment by piroor** [comment]
@Sada-Mio Sorry I still cannot understand what is the point...

There are three trees on Firefox + TST:

1. Tree of tabs in the TST's sidebar, like:
   - A1
     - B1
       - C1
       - C2
       - C3
     - B2
2. Tree of bookmark folders, like:
   - [Folder X1]
     - [Folder Y1]
       - Bookmark Z1
       - Bookmark Z2
       - Bookmark Z3
     - [Folder Y2]
3. Tree structure of tabs stored to bookmarks in a folder
   - [Folder X2]
     - Bookmark from A1
     - \> Bookmark from B1
     - \>\> Bookmark from C1
     - \>\> Bookmark from C2
     - \>\> Bookmark from C3
     - \> Bookmark from B2

"Open All as a Tree" will appear on the context menu on [Folder X1], [Folder Y1], [Folder Y2], and [Folder X2]. In other words, the command won't appear on regular bookmarks: Z1, Z2, Z3, and all bookmarks under the [Folder X2] in this example. My previous comment meant that I thought that a new context menu command "Open as a Tree" should appear on the item "\> Bookmark from B1" and it should open "\> Bookmark from B1", "\>\> Bookmark from C1", "\>\> Bookmark from C2" and "\>\> Bookmark from C3" as a tree of four tabs. Is this my understanding correct? Or, did you mean any other different feature?

**Comment by Sada-Mio** [comment]
Sorry I wasn't clear. 

But, yes, context menu "Open as a Tree" for "**_> Bookmark from B1_**" is the feature desired. Right now I can only restore the entire [Folder X2] tree created by "Bookmark this Tree" which can be large.

**Comment by piroor** [comment]
OK, I've added the command experimentally with commits 38fff39 and 95f6052. But, this feature requires some description to understand how to use, so I think it should be extracted as a separate helper addon.

**Comment by piroor** [comment]
I've started a new project https://github.com/piroor/tst-open-bookmark-as-partial-tree and removed the new command from TST. It is a feature oriented addon about "bookmarks and tree", so I'm planning to add some more extra commands like "open as a tree in container".

**Comment by piroor** [comment]
I've uploaded it to AMO website: https://addons.mozilla.org/firefox/addon/tst-open-bookmarks-as-partial-/ It is waiting for a review, and will be available after accepted by AMO editors.

**Comment by piroor** [comment]
Because TST Open Bookmarks as Partial Tree is available, I close this.
