### ISSUE TITLE
group-tab.html wraps columns too quickly

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2573]
## Short description
group-tab.html wraps columns too quickly leaving empty space at the end of each column.

## Steps to reproduce
 1. Create new group-tab.html dummy tab.
 2. Create enough tabs under the dummy tab to create at least 2 columns.

## Expected result
![2020-05-02_13-00-01](https://user-images.githubusercontent.com/979729/80870681-13890d80-8c76-11ea-9167-ce8924efd636.jpg)

## Actual result
![2020-05-02_12-55-06](https://user-images.githubusercontent.com/979729/80870827-e7ba5780-8c76-11ea-99b7-4ae2034954b5.jpg)

## Environment
 * Platform (OS): Windows 10 (1909) x64
 * Version of Firefox:  75.0
 * Version (or revision) of Tree Style Tab: 3.5.3

## Notes
Using the developer tools and inspecting the column information, the "flex item of main" shows the content size = 502px, Flexibility (flex-grow: 1) = +55.83px, Final Size = 557.83px.  It looks like it is that +55.83px that becomes the empty space and is never consumed.  If I manually edit div id ="tabs" ... max-height:  557.83px and height:  557.83px, I get the expected outcome. 

![2020-05-02_12-55-23](https://user-images.githubusercontent.com/979729/80870933-8fd02080-8c77-11ea-9060-527fc03c48db.jpg)

**Comment by piroor** [comment]
The height of columns were calculated as 90% of the height of visible area because I didn't know how to calculate the best margin `1em` at the script. Now I know it can be done with CSS's `calc()`, so I've updated the calculation process. Thanks!

**Comment by irvinm** [comment]
Thank you @piroor .
