### ISSUE TITLE
Typo, "hitories" instead of "histories"

### ISSUE THREAD

**Issue by PantherX** [piroor/treestyletab#2574]
## Short description
A typo exists under the New Tabs Behavior section. The word "histories" is spelt incorrectly.
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Go to options
 4. Expand the New Tabs Behavior
5. Under Non-blank tabs, section option has the typo

## Expected result
The word "histories" is present.

## Actual result
The word "hitories" is present.
![image](https://user-images.githubusercontent.com/5349122/80898882-01ce6580-8d5d-11ea-8af0-d74d0d026c3a.png)

## Environment

 * Platform (OS): Windows 10 1909 64-bit
 * Version of Firefox: 75.0 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.5.3

**Comment by piroor** [comment]
Thanks! Fixed with 0b19874.
