### ISSUE TITLE
Focus on "Close tabs" button in the new "Close tabs?" dialog

### ISSUE THREAD

**Issue by szpak** [piroor/treestyletab#2576]
## Short description

The new "native" dialog to close multiple tabs could have the "Close tabs" button focused by default. It would be then required to just press the enter/space key to confirm instead or 2x TAB + ENTER/SPACE (for people preferring using keyboard for that)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST (ensure in "Advanced" displaying warning about closing multiple tabs is enabled) .
 3. Open some page.
 4. CTRL-T and open an another page.
 5. CTRL-click 2 links to open them in a sub-bookmarks.
 6. Collapse the group
 7. Click "x" to close the whole group.

```
A
B (selected) - try to close it
\- C (collapsed)
\- D (collapsed)
```

## Expected result

The "Close tabs?" dialog is displayed. It can be confirmed with the space/enter button.

## Actual result

There is no focus on the close button. It is required to press the TAB key twice to be able to close with ENTER/SPACE.

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 75.0
 * Version (or revision) of Tree Style Tab: 3.5.3

**Comment by piroor** [comment]
I've tested with TST 3.5.4 (approved today) + Firefox 75.0 + Ubuntu 18.04LTS and couldn't reproduced this. Could you try with updated TST? If you still see same problem, I think it can depends on the window manager of the system.

**Comment by szpak** [comment]
Thanks for checking. After updated to 3.5.4 it works as expected. Closing.
