### ISSUE TITLE
Web pages can not receive mouse events when the mouse cursor is over TST sidebar

### ISSUE THREAD

**Issue by lideming** [piroor/treestyletab#2577]
## Short description
When the user is selecting text or dragging items in web pages, web pages can not receive `mouseup` and `mousemove` events when the mouse cursor is over TST sidebar.

I am not sure whether this issue is caused by TST or Firefox itself.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open https://www.mozilla.org/.
 4. Start selecting text in the page by pressing left mouse button (don't release it until step 7).
 5. Move the mouse cursor into TST sidebar.
 6. Move the mouse cursor up and down, inside TST sidebar.
 7. (When the cursor is inside TST sidebar) release left mouse button.
 8. Move cursor back into the web page.

## Screen Recordings
[recordings.zip](https://github.com/piroor/treestyletab/files/4590537/recordings.zip) (662 KB) contains `tst.mp4` and `history.mp4`

(In the end of both recordings, I released left mouse button inside the sidebar, then moved the cursor back into the web page.)

## Expected result
The text selection should be done after step 6, like with the built-in History sidebar. (See `history.mp4`)

## Actual result
The text selection continues after step 6. (See `tst.mp4`)

The same thing may happen when dragging YouTube video progress bar.

## Environment

 * Platform (OS): Windows 10 x64 version 1909
 * Version of Firefox: 76.0
 * Version (or revision) of Tree Style Tab: 3.5.4

**Comment by piroor** [comment]
This looks to be a duplicated of #2339, and the root problem is a bug of Firefox itself: [1571946 - Text selection in the content area is not canceled after mouseup on a sidebar panel provided by an add-on](https://bugzilla.mozilla.org/show_bug.cgi?id=1571946)

**Comment by lideming** [comment]
Yes, it's the same problem...

And one interesting finding: it doesn't happen for `about:...` and `moz-extension://...` pages.

**Comment by piroor** [comment]
Yes, such a difference may be produced from boundaries of processes. At least three processes may be related to the problem: the UI process, the WebExtensions process, and the content process for the active tab. `about:` pages are processed by the UI process, `moz-extensions:` pages are processed by the WebExtensions process, so there are less boundaries between the active tab and TST's sidebar panel.

**Comment by irvinm** [comment]
@lideming can you close this item as it is a duplicate?

**Comment by lideming** [comment]
@irvinm of cource.
