### ISSUE TITLE
Tabs response very slow and laggy after update to new Firefox 76

### ISSUE THREAD

**Issue by huynhxloi** [piroor/treestyletab#2579]
## Short description
After updating to Firefox 76, switching tabs, creating new tabs, everything to do with tabs has a been jittery and lagging. Creating new tab, the browser takes a second to "think" about it before a new tab would appear. With switching tabs, the page itself would switch, but the tab highlight would take a moment before switching. Basically, just very slow and jittery.

## Steps to reproduce
Experience these issues switching and creating new tabs.

 * Platform (OS): 
 * Version of Firefox: 76.0.1
 * Version (or revision) of Tree Style Tab: 3.5.4 (2020.5.5)

**Comment by irvinm** [comment]
@huynhxloi can you try disabling TST to see if the problem persists?  The reason I ask is that I have seen at least one report of slow performance of Firefox after upgrading to FF76 on reddit.

**Comment by huynhxloi** [comment]
I create a new profile, reinstalled TST and it seems to be a lot better so I don't think its a TST issue. I think it may have been my userchrome not being as compatible with the new FF.

**Comment by billy1andy2** [comment]
hi, huynhxloi
Would you tell me how did you finally fix it ?
I encounter the same problem as you in 77.0.1

I had almost re-install and reset every thing...

**Comment by huynhxloi** [comment]
In my case I was using Temporary Containers with Automatic Mode turned on, which caused the delay. I turned that off and that was the fix for me.

https://github.com/stoically/temporary-containers/wiki/Automatic-Mode

**Comment by billy1andy2** [comment]
thank for your hint,
it seem to conflict with another add-on
: )
