### ISSUE TITLE
[Feature Request] Close button On/Off toggle

### ISSUE THREAD

**Issue by SHHSSH** [piroor/treestyletab#2580]
Working with the limitations of tab title displaying, I request the ability to Toggle On/Off the close button, as I for one have never closed a tab by the button in years. It will provide much more readability of the title from the beginning, and a cleaner look.

<a href="https://imgur.com/K2HSArJ"><img src="https://i.imgur.com/K2HSArJ.gif" title="source: imgur.com" /></a>

**Comment by irvinm** [comment]
You could already do this with custom TST CSS probably just as well as an option.

#tabbar tab-closebox {  display: none; }

**Comment by SHHSSH** [comment]
@irvinm Thank you.
