### ISSUE TITLE
Is it possible to list the names of pinned tabs?

### ISSUE THREAD

**Issue by informationeagle** [piroor/treestyletab#2584]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by informationeagle** [comment]
Is it?

**Comment by irvinm** [comment]
Have you tried unchecking this option?

![image](https://user-images.githubusercontent.com/979729/81879073-b0da2080-9557-11ea-95ce-8b8e9443338f.png)

**Comment by irvinm** [comment]
@informationeagle if this is sufficient, can you close this issue?
