### ISSUE TITLE
Wrong tab name after restoring from "Restore Session" dialog

### ISSUE THREAD

**Issue by thomasetter** [piroor/treestyletab#2587]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 1. Make sure to open two websites, e.g. https://piro.sakura.ne.jp/xul/xpi/nightly/ and https://github.com/piroor/treestyletab  (I could not reproduce it with only one page)
 3. kill Firefox by sending SIGTERM to the main process
 4. start again -> this should restore the tabs automatically & successfully
 1. select each of the tabs at least once to make sure they are loaded
 1. kill Firefox again by sending SIGTERM to the main process
 1. start again -> this should show the "Restore Session" dialog
 1. Push the "Restore Session" button

This will look like this:
![image](https://user-images.githubusercontent.com/422775/82328267-ecee0500-99df-11ea-8014-e5c0b11b2227.png)

## Expected result
Tab title displayed in tree updates to be the same as the one in the tab bar on top.

## Actual result
The tab title stays "Restore Session" even when navigating to a different page

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 77.0b7
 * Tree Style Tab 3.5.4.10477, 2020-05-12 12:08 | 647K from https://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by mikesbytes** [comment]
I can confirm the same behavior 76.0.1 on Linux. If the tab you left it on when closing is a pinned tab, it will also appear to be moved to the regular tab list in the tree, but retains the behavior of a pinned tab and shows as such in the regular tab bar.

**Comment by piroor** [comment]
I've confirmed, but it looks a bug of Firefox itself. Indeed same problem happens on other tab management addons (e.g. Tab Center Redux). Firefox should notify the new title of the tab to addons via `tabs.onUpdated` listeners but no change about `title` is notified about the recycled tab.

**Comment by piroor** [comment]
1640112 - Updated "title" is not notified via "tabs.onUpdated" listeners for a tab recycled by "about:sessionrestore"
https://bugzilla.mozilla.org/show_bug.cgi?id=1640112

I've filed a bug.

**Comment by p0lygun** [comment]
still happens

**Comment by piroor** [comment]
The problem is now tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1640112 instead of here, so I recommend you to watch it.
