### ISSUE TITLE
How to hide a right click Menu

### ISSUE THREAD

**Issue by Yurines201** [piroor/treestyletab#2588]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Right click at sidebar (サイドバーのタブが無いところを右クリック)
 
サイドバーのタブが無いところを右クリックしたときに、コンテキストメニューが現れます。
これを表示されないようにしたいのですが、可能でしょうか？

ドキュメントに書かれている、コンテキストメニューの消し方を試しました。(userChrome.css)
```
*[id^="treestyletab_piro_sakura_ne_jp-menuitem-_context_selectAllTabs"] {
  display: none;
}
```

すると、タブを右クリックした時に現れるコンテキストメニューの項目は非表示になりました。
context_selectAllTabs (すべてのタブを選択)

![image01](https://user-images.githubusercontent.com/65666463/82457432-6248fb00-9af0-11ea-840a-4b66c862c80e.png)

しかし、タブの領域ではなく、もう少し下の、タブが何も無い領域を右クリックした時に現れるコンテキストメニューの項目は、表示されたままでした。

![image02](https://user-images.githubusercontent.com/65666463/82458267-6e818800-9af1-11ea-9155-3a92016fa513.png)

このコンテキストメニューを出てこない様にできないでしょうか？
普段使っているときに、間違って右クリックしてしまった時に、出てくるのが邪魔なので。
よろしくお願いします。

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: Firefox 68.8.0 esr
 * Version (or revision) of Tree Style Tab: 3.5.4

**Comment by piroor** [comment]
空の領域で出てくる物はFirefoxのネイティブUIではなく、TSTのサイドバー内でHTMLとCSSを使って作られた偽コンテキストメニューです。なので、userChrome.cssではなく、TSTの設定画面のユーザースタイルシートの所でカスタマイズする必要があります。
具体的には以下のようになります。

```css
li[data-item-id="noContextTab:context_selectAllTabs"] {
  display: none;
}
```

about:debuggingからTST用のデバッガを開いて、sidebar/sidebar.htmlをインスペクタで調べると、ページの末尾の方に`ul#tabContextMenu`という要素があるのが見えると思いますが、これがこの偽コンテキストメニューの実体となっています。

**Comment by Yurines201** [comment]
ありがとうございます！ Thank you!

TSTの設定画面のユーザースタイルシートの所に、
以下の様に書くことで、コンテキストメニューを非表示にできました。

```
ul[id="tabContextMenu"] {
  display: none;
}
```

ありがとうございました！
