### ISSUE TITLE
How do I number my tabs for easy keyboard navigation?

### ISSUE THREAD

**Issue by faurehu** [piroor/treestyletab#2589]
Hi, I'm not sure if it is already implemented but it would be nice that tabs that are ordered from 0 to 9 have an indicator so that I can jump to them with ctrl+1-9.

There are solutions out there for tabs but not for TST.

**Comment by piroor** [comment]
Did you try this?:
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#tab-numbering-and-counting

**Comment by faurehu** [comment]
This does it! Any idea how to inspect the sidebar elements? The code is giving me duplicated numbers:
![image](https://user-images.githubusercontent.com/4634877/82685478-262aad00-9c4c-11ea-90ae-319e9bfb2d5c.png)

**Comment by Bone008** [comment]
I also faced duplicate numbers since some time. After long debugging it turns out there are now 2 elements `.extra-items-container` per tab. If you replace `.extra-items-container` with `.extra-items-container.behind`, it works.

**Comment by faurehu** [comment]
Perfect, thansk!
