### ISSUE TITLE
Multiple double-click options

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2591]
## Short description
There appears to be two separate, but very different, options on how to handle "double-clicking" on a tab which probably should be combined to reduce unwanted behaviors.  (Ex:  Expand\collapse, Delete, Do nothing)

## Steps to reproduce
1. Clean profile 
2. Set "Double-click on a tab" to "Collapse/expand tree"
3. Set Advanced "Close tab by double click"
4. Double clicking on a tab deletes tab or entire collapsed tree.

![2020-05-26_10-25-03](https://user-images.githubusercontent.com/979729/82941827-0c97a700-9f65-11ea-85fe-7c2cfeab1b06.jpg)
![2020-05-26_10-24-14](https://user-images.githubusercontent.com/979729/82941839-0f929780-9f65-11ea-8111-abad16ca7a22.jpg)

## Expected result
I was personally expecting for a tree to get expanded and ended up having the entire tree deleted. (Obviously screenshot was after I disabled the close tab option)

## Actual result
Tab\Tree will be deleted.

## Environment
 * Platform (OS): Windows 10 x64 (1909)
 * Version of Firefox: FF 76.0.1
 * Version (or revision) of Tree Style Tab: v3.5.4

**Comment by irvinm** [comment]
@piroor this situation got me thinking to how\why the "close tab by double click" was originally enabled for me when I would have not enabled it and I have some information and a suggestion.

It looks as if options.html when in its own tab treats the entire row of a checkmark box as a toggle for that item.  This means that even if I had clicked anywhere on "open space" to the right of the option, I really ran the risk of toggling that item without me even realizing it.  I think in general, the area from the checkbox till the end of the text description would be reasonable to toggle the value.  However, I think the empty space should just be that and when clicked have no effect on that option.

I tested this out by clicking empty space after the end of the text description and observed it toggling the value.

![2020-05-26_21-18-38](https://user-images.githubusercontent.com/979729/82965764-1a662000-9f97-11ea-9e28-3414dc4f4cab.jpg)

**Comment by piroor** [comment]
Thanks, I completely forgot handling for a case they both enabled. Now the "Close tab by double click" option became a choice for double-click action.

**Comment by irvinm** [comment]
Thanks @piroor, that will configuration change will definitely help.

Any thoughts about my 2nd comment regarding options.html?

I looked at options.html and options.css and I think if you just change "has-checkbox" CSS display type from "block" to "table" then each checkbox option ONLY toggles when the user clicks on the checkbox or the actual text ... but not any of the empty space on that row.  (https://www.w3schools.com/cssref/playit.asp?filename=playcss_display&preval=table)

![2020-05-27_9-04-20](https://user-images.githubusercontent.com/979729/83022763-01db2180-9ffa-11ea-99f9-9b85ae7d0530.jpg)

![2020-05-27_9-04-02](https://user-images.githubusercontent.com/979729/83022777-07d10280-9ffa-11ea-9696-e9091281f94c.jpg)

**Comment by piroor** [comment]
Sorry I missed the comment. The commit ed069f7 should shrink width of these items smartly.

**Comment by irvinm** [comment]
Thank you as always @piroor.
