### ISSUE TITLE
CTRL/CMD+Clicking the new tab button does not open in same container tab

### ISSUE THREAD

**Issue by Vash63** [piroor/treestyletab#2593]
##  Short description
When using Mozilla's official container tabs extension (or the Facebook Containers one), using Ctrl/CMD + Click on the "New Tab" button will open a new tab in the current container. This functionality does not work with the new tab button provided by TST.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install Mozilla's [Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/)
 4. Open up a tab in any of the four default containers
 5. Ctrl+Click the new tab button in the default Firefox tab bar and compare results to the same thing on the TST new tab button

## Expected result
New tab opens in the same container as current active tab

## Actual result
New tab opens outside of any containers

## Environment

 * Platform (OS): macos
 * Version of Firefox: Nightly 2020-05-27
 * Version (or revision) of Tree Style Tab: 3.5.4

**Comment by piroor** [comment]
Thanks, I didn't know those extra actions. After a research I've introduced simulated behavior for each action on the button:

* Ctrl-click: open a next sibling tab with inherited container
* Shift-click: open a new window
* Ctrl-Shift-click: open a next sibling tab with inherited container in the background

**Comment by Vash63** [comment]
That sounds perfect. Will test on next release probably, thanks.

**Comment by irvinm** [comment]
@Vash63 can you check with the new version?  If ok, please close out this item.  Thanks.

**Comment by Vash63** [comment]
Hi, it's working now with the keyboard hotkeys... I forgot one in my original note though that I only realized now that it's missing. Middle click should have the same behavior as ctrl+click.

**Comment by piroor** [comment]
OK, I've added a special option for the middle click with the commit 6c85bb6.

**Comment by Vash63** [comment]
Thanks again. I think this is probably safe to close now but since I'm too lazy to install the unsigned release temporarily for testing I'm just going to wait for the auto-update. Thanks for fixing this.

**Comment by Keppl** [comment]
Is there by chance an option to  re-enable original behavior.
I got used to ctrl-clicking to get a new child tab; 
If not, that fine, I will learn to middle click instead, eventually :D .

**Comment by piroor** [comment]
@Keppl OK, with the commit 7d7adb9 now you can configure the behavior of Ctrl/Command-click again in the expert mode.
