### ISSUE TITLE
Wrong name for the active tab after Restore Session

### ISSUE THREAD

**Issue by joshgold22** [piroor/treestyletab#2595]
## Short description

Sometimes after Restore Session, the tab that winds up active is mislabelled to look like the Restore Session (both the favicon and the name on the tab.)  The tab is correctly labelled in the main firefox tabbar (on the top of the window.)

In case it's relevant, I saw the popup that asks if I want to group the tabs or leave flat, and I clicked "leave flat".  This was using the button on the Restore Session page after a crash.  (Not the History menu.)

## Steps to reproduce
I have not tried to replicate, but I would try:
1. Crash Firefox with tabs open (I'm not sure if the bug may depend on a large number of tabs being open.  I had >200 being restored.)
Could probably simulate the crash with Force Quit.
2. Restart Firefox
3. Click Restore Session
4. When asked to group tabs or flat, click flat (may not matter)

## Expected result
The last tab open should be labelled normally.

## Actual result
The tab inherits the label and favicon from the Restore Session tab.  This persists if I close and reopen the TST sidebar.  Firefox's native tab looks correct.

## Environment

 * Platform (OS): OSX
 * Version of Firefox: 76.0.1
 * Version (or revision) of Tree Style Tab: 3.5.4 (2020.5.5)

**Comment by piroor** [comment]
Is this same to #2587 ?

**Comment by joshgold22** [comment]
Yes, this is a duplicate, thanks.

**Comment by irvinm** [comment]
@joshgold22 will you close this one then?  Thanks.

**Comment by joshgold22** [comment]
yes (wasn't sure of the etiquette)
