### ISSUE TITLE
Inability to disable "close other tabs"

### ISSUE THREAD

**Issue by LD143** [piroor/treestyletab#2597]
## Short description
On an ultra-wide monitor now and the tabs are small. Sometimes I'll accidentally right-click to 'UNDO' a tab I closed and instead hit 'CLOSE OTHER TABS' which does the exact opposite of what I want. What's worse, any tabs I had open to be viewed later are now gone (and not saved anywhere). There are no options within the addon itself to disable any of the 'close tabs' options. I want to manually control what's closed and what's not without accident mouse clicks removing 30+ tabs at once. 

## Steps to reproduce

 1. Start Firefox with a clean profile.
 2. Install TST.
 3. Right-click and accidentally press 'Close other tabs' or 'close tabs below this' instead of UNDO.
 4. Cry that tons of tabs are now gone.

## Environment

 * Platform (OS): Windows 10 Pro
 * Version of Firefox:  76.0.1
 * Version (or revision) of Tree Style Tab:  3.5.4

**Comment by irvinm** [comment]
It is a little bit of work, but you can accomplish this yourself via userChrome.css.  Check out https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-context-menu-items-in-the-sidebar-2116 on how to do it. 

I'm sure @piroor will let you know his thoughts on your request.

**Comment by LD143** [comment]
Thank you for your response, irvinm.  I'm not going to lie. I think I read that exact page (and another like it from an older Reddit post somewhere) and I have no clue what any of it means. I have absolutely zero knowledge of anything programming (though I can assemble any computer - sigh). I tried understanding what the CSS file is (or how to make one since I seem to be lacking one?) and i have no clue what anything means or .. well you get the idea. A lot of people talk about editing the CSS to make things more customizable but I have a feeling if I did anything, I'd end up deleting some basic functionality of Firefox - even if I backed it up. I'm just THAT awesome! :0(

It's not a "game-breaking" thing and I think we all know how incredible Piroor is for creating this insanely useful addon (and keeping it updated), but just wanted to throw my hat into the ring as it were since I lost a solid 70 tabs last night and was .. oooohhhh ... so unhappy from that misclick. :0(

**Comment by irvinm** [comment]
@LD143, no worries ... CSS isn't the easiest to work with at times.  Maybe I can help you.  I run with a large number of tabs so I understand your concern.  I figured I would disable "Close Tabs to End" and "Close Other Tabs" as well.  Here is how you do it.

1. Type "about:profiles" into the URL bar.
2. On that page, look at the row that says "Root Directory" and click on the button to the right labeled "Open Folder".  This will open the root folder of your Firefox profile.
3. If you do not see a folder named "chrome", go ahead and create a folder with that name.
4. Now open that new folder.
5. In that folder, create a file called "userChrome.css".
6. Edit userChrome.css with any text editor.
7. Simple copy the text from https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-context-menu-items-in-the-sidebar-2116 and paste into userChrome.css and save the file. (You don't need to change or customize any of it)

Finally we need to make sure Firefox will read\process your userChrome.css customization.

8. In Firefox, type "about:config" into the URL bar.
9. Type "toolkit.legacyUserProfileCustomizations.stylesheets" into the search bar on that page.
10. Assuming you don't have this value already created, it will show you "boolean", "number", "string" as choices of types to create this value.  Select "boolean" and then click on the "+".  It should show "true" after you do that.
11. Restart Firefox and enjoy.

This worked for me, so hopefully I wrote it up with all the details so it is understandable and complete.

**Comment by LD143** [comment]
@irvinm First of all, you rock. Second, thank you!  That was EXACTLY what my old non-programming @$$ needed. I must have spent over an hour the other night trying to understand what anyone was trying to say in multiple places but how you laid it out was what I needed - so again thank you for that.

The only question I have after this is that am I going to need to do this every TFT (or FF) update or will this stick for a while unless something breaks it down the line (like the change from old FF to "Quantum")? 

Again, thank you. You might have saved me from anxiety medication from tab loss in the future. :0)

**Comment by irvinm** [comment]
You should be good from now on.  You won't have to do anything else!

**Comment by piroor** [comment]
Thank you @irvinm !

@LD143 Sorry but I won't add option to control visibility of common context menu commands on tabs, because they aim to imitate Firefox's built-in commands in the native tab context menu and Firefox itself doesn't provide any option to hide those commands. Indeed Firefox itself also provides "Close Other Tabs" command in its native tab context menu and you still need to use `userChrome.css` to deactivate it. (Thus, if a future version of Firefox itself implement ability of context menu customization, TST will follow to that.) This is one of design policies on this project.

**Comment by LD143** [comment]
Understood and thank you for the explanation (and again for the work on the addon!)  :0)

**Comment by irvinm** [comment]
@LD143 would you mind closing this issue?  Thanks.
