### ISSUE TITLE
New tabs from external URLs are not made active if current selected tab is the parent of a collapsed tree.

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2598]
## Short description
When initiating a new tab via an external program, if the current tab is the parent of a collapsed tree, the tree with not auto-expand to be able to see the new tab.  (The tab is successfully created and properly setup as the child of the current tab)

## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set browser.tabs.insertAfterCurrent = true.
 4. Create a tree with some children, collapse the tree, select the parent tab.

A (selected)
\- B (collapsed)

5. From an external program, click on a link which should create a new tab in Firefox.

## Expected result
In previously versions of TST, the tree would expand, the new tab [C] would be created as a child of parent, and the child would then have focus.

Expected:
A
\- C [new tab] (selected)
\- B

## Actual result
The tree is not expanding, but I do see a brief animation of the tab being created.  The parent tab remains the selected tab and the tree remains collapsed.  Expanding the tree manually allows you to see the new tab [C] in TST.

A (selected)
\- C [new tab] (collapsed)
\- B (collapsed)

## Environment

 * Platform (OS):  Windows 10 x64 (1909)
 * Version of Firefox:  FF 76.0.1
 * Version (or revision) of Tree Style Tab: TST 3.5.4

**Comment by irvinm** [comment]
@piroor looking at the change log, I think this could be related to:

3.4.0 (2020.3.6)
- Rename an option autoExpandOnCollapsedChildActive to unfocusableCollapsedTab and make effective on cases tabs going to be collapsed by collapsing parent tree.

I loaded the version before this one (3.3.6 - 2020.2.21) and the tree properly expands when the tab is created.  However, there appears to be a different problem that TST thinks the new tab is the current tab but the Firefox tab strip shows the parent as the current tab.

Not sure if this help, but thought I would mention it.

![2020-05-30_11-36-54](https://user-images.githubusercontent.com/979729/83332603-1a517300-a26a-11ea-8b6d-918772cdeaf5.jpg)

**Comment by beverlyhillz** [comment]
I tried to duplicate this issue but couldn't. 
I was able to open a new tab from external link (the parent tab was collapsed initially) and the tree expanded and focus changed child element. 
Linux 18.04
Firefox 76.0.1
TST 3.5.4

**Comment by irvinm** [comment]
Thanks for giving it a go!  Maybe I should try in my Ubuntu VM to see if Firefox behaves any differently.

**Comment by irvinm** [comment]
Ok, I tried the same thing and saw the same behavior using Ubuntu 19.10 with same FF and TST versions.  I started with a clean profile before starting the screen capture.  (38 seconds from start to end! :)

https://i.imgur.com/eaOWNg1.gifv

**Comment by piroor** [comment]
The current result looks to be affected from recent refactoring. After a research I've realized that handling for this kind cases were originally missing but worked well unexpectedly. The change 66c0957 should reintroduce the expected behavior on this context. Thanks!

**Comment by irvinm** [comment]
Thank you ... I will retest in the next version.
