### ISSUE TITLE
Welcome screen is displayed every time firefox is started

### ISSUE THREAD

**Issue by dhowland** [piroor/treestyletab#2601]
##  Short description

The welcome screen is shown every time Firefox is started.  It should only be shown once and then not be shown again unless TST is reinstalled.

## Steps to reproduce

 1. Install TST.
 2. Restart Firefox. 
 3. Welcome screen is shown.
 4. Close welcome screen
 5. Restart Firefox.
 6. Welcome screen is shown again. 

## Expected result

Welcome screen should not be shown on subsequent restarts.

## Actual result

Welcome screen is shown on all subsequent restarts.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 76.0.1, but it has persisted for several versions
 * Version (or revision) of Tree Style Tab: 3.4.7

**Comment by piroor** [comment]
Is this same to #2324 ?

**Comment by dhowland** [comment]
> Is this same to #2324 ?

Not sure.  that issue discusses `dom.indexedDB.enabled=false`, which apparently isn't an option in Firefox anymore.

I do have `dom.indexedDB.storageOption.enabled` is that related?

**Comment by dhowland** [comment]
Okay I skipped that business and just cleaned out the storage area.  That seems to have worked.  In fact based on all the data files that have been created since cleaning it out, it seems that the entire thing was screwed up, not just for TST.  Lots of website data was in there but I very much doubt anything of value was lost.

**Comment by piroor** [comment]
FYI: The preference `dom.indexedDB.storageOption.enabled` doesn't deactivate the IndexedDB feature itself, instead it changes a behavior of its feature. Details: https://www.fxsitecompat.dev/en-CA/docs/2018/storage-option-for-indexeddb-open-has-been-deprecated/
