### ISSUE TITLE
[Feature Request] Optimistic tab close (and other simpler operations) for visual responsiveness (

### ISSUE THREAD

**Issue by juicetin** [piroor/treestyletab#2606]
**Background**:
At the moment there is a fair bit of visual lag when doing any operation, perhaps only when there is a moderate number of tabs (50+) - not sure if this is a precondition as I almost always have at least that many open as a minimum.

When temporarily re-enabling being able to see Firefox's native tab bar at the top though, I can see that operations like closing (e.g. holding the keyboard shortcut for closing tens of tabs at a time) are happening quickly, but it's likely FF's hook that is taking a while to notify Tree Style Tab.

**Feature request**:
As operations like close will almost never fail (at least I've never seen it fail), it would be great to have an opt-in option (and potentially have it be the default if the new functionality is found to be stable) to _optimistically_ perform these simpler operations, so that Tree Style Tab may feel much more responsive.

**Comment by piroor** [comment]
I already tried that and gave up. Actually `browser.tabs.remove()` API call sometimes fails - some webpages blocks tab closing when there is any in-editing input form. For example: Facebook.

I planned that an optimistic acceleration like: close TST's tabs anyway and restore unclosed tabs with a timeout. But what timeout is the best? The user can pend the confirmation "do you want this tab to be closed really?" for a long time, or forever. Until the timeout you cannot see the pended tab in TST's sidebar so it becomes inaccessible.

I also planned that an optimistic acceleration activated only when there is no tab which has such a blocked. But it is implemented based on a DOM event and the event can be canceled by various triggers, thus an addon cannot know which tab has any blocker or doesn't.

So finally I gave up any accelerated tab close. Now TST just calls `browser.tabs.remove()` and removes tabs from the sidebar after `browser.tabs.onRemoved` is notified.

**Comment by irvinm** [comment]
@piroor sounds like we should just close this one.  Not sure there is anything to do.  We can continue to discuss as needed.
