### ISSUE TITLE
group-tab improvements

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2607]
## Short description
@piroor I have 2 potential enhancements for group-tab.html:  (I can close if you don't want to do either)

1. Allow an option, hidden option, or CSS option to override the standard 20em column width on group-tab.html when more than one column of tabs.  (Most people have wide screen monitors and when there are only 2 columns, 20em columns are fairly narrow)
2. Support some type of color indicator to show a tab is in a container.  (The tabs themselves already support this and I accidentally found out you could style the tabs listed on group-tab.html, so this should be possible)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install [Firefox Multi-Account Containers](https://addons.mozilla.org/en-GB/firefox/addon/multi-account-containers/) by Mozilla Firefox.
 3. Create a group-tab.
 4. Create enough tabs under the group-tab to form at least 2 columns.
5. Place some tabs in different container.

## Expected result

In the case of containers, you can see some blue and green container indicators on the tabs in the sidebar.  I am wondering if it makes sense to have indicators as well on the group-tab page.  (Left color bar, right color bar, color ball under the fav icon, underline color ... open to ideas.)

![2020-06-11_18-47-17](https://user-images.githubusercontent.com/979729/84448777-9b6d1a80-ac19-11ea-9584-1cacd99e7ac5.jpg)

In terms of the column width, it looks like it is set in group-tab.js:373:

![2020-06-11_18-44-09](https://user-images.githubusercontent.com/979729/84448311-52689680-ac18-11ea-9ac7-bb5439ce11be.jpg)

If I manually change"calc(20em)" in the browser, I get the desired behavior.

![2020-06-11_18-43-38](https://user-images.githubusercontent.com/979729/84448329-5e545880-ac18-11ea-8a0b-73d2c500da18.jpg)

Any way to customize this would be helpful.

## Environment

 * Platform (OS):   Windows 10 x64 (1909)
 * Version of Firefox: 77.0.1
 * Version (or revision) of Tree Style Tab: 3.5.5

**Comment by piroor** [comment]
> Allow an option, hidden option, or CSS option to override the standard 20em column width on group-tab.html when more than one column of tabs.

OK, I've added a custom property `--column-width`. Now you can configure the column width with the user defined stylesheet (in TST's options) like as:

```css
:root.group-tab { --column-width: 30em; }
```

**Comment by irvinm** [comment]
> 
> 
> > Allow an option, hidden option, or CSS option to override the standard 20em column width on group-tab.html when more than one column of tabs.
> 
> OK, I've added a custom property `--column-width`. Now you can configure the column width with the user defined stylesheet (in TST's options) like as:
> 
> ```css
> :root.group-tab { --column-width: 30em; }
> ```

Thanks!  That CSS property is perfect.

Any thoughts on how to represent tabs in containers on group-tab.html?

`2. Support some type of color indicator to show a tab is in a container. (The tabs themselves already support this and I accidentally found out you could style the tabs listed on group-tab.html, so this should be possible)`

**Comment by piroor** [comment]
Yeah, container support is still in progress.

**Comment by piroor** [comment]
I've added more container support for group tabs.
![image](https://user-images.githubusercontent.com/70062/84598499-295d3580-aea6-11ea-8935-cb1e8e076c7b.png)
Because the column width is invisible by default, I decided to put the marker at leftside of a favicon.

**Comment by irvinm** [comment]
Love it!  That would have been my choice as well.
