### ISSUE TITLE
tab grouping is delayed until a tab failing to connect times out, and the failing tab is not grouped

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#2608]
## Short description

if one of the tabs is unable to connect and waiting in a loading state, grouping does not take place until it times out and stops loading. Then the successful tabs are grouped and the failing tab remains ungrouped.

I believe this is a recent regression.

## Steps to reproduce

 1. Start Firefox with clean profile.
 1. Install TST.
 1. activate tab grouping
 1. show the bookmark toolbar
 1. create a folder on it with 3 urls
    - https://example.org/?1
    - https://example.org/?2
    - https://example.org:444/
1. "open all in tabs"
1. while https://example.org:444/ is attempting to connect (~45s for me) the tabs remain ungrouped
    ![image](https://user-images.githubusercontent.com/895588/84471869-40a4e480-ac54-11ea-8c25-cb24fd46b767.png)
1. after it times out, the successful tabs are grouped, and the failing one is not
    ![image](https://user-images.githubusercontent.com/895588/84471995-7ba71800-ac54-11ea-8b6c-dc15429ff6a9.png)

## Expected result

grouping should be immediate, regardless of the loading state of any tab

## Actual result

grouping is delayed and ultimately fails

## Environment

 * Platform (OS): win7 x64 sp1
 * Version of Firefox: 77.0.1
 * Version (or revision) of Tree Style Tab: 3.5.5

**Comment by bughit** [comment]
also, if the failing tab is closed before it times out, no grouping takes place

**Comment by bughit** [comment]
when every tab loads successfully, the grouping is still unreasonably delayed, not till everything loads but enough to make this an unsettling regression compared to how it used to work.

**Comment by piroor** [comment]
I've realized that tabs opened from bookmarks have a part of bookmarked URL as its title. So I've modified codes to detect tabs opened from bookmarks more optimistically and quickly with the commit 7e7cf12. I think it should accelerate the auto-grouping behavior like older versions.

**Comment by bughit** [comment]
what is the expected wait for fix releases?

**Comment by irvinm** [comment]
@bughit you can always try out a development build (https://github.com/piroor/treestyletab#development-builds) while waiting for updated versions.

**Comment by irvinm** [comment]
@bughit have you been able to test this now?

**Comment by bughit** [comment]
fixed, @piroor I am curious, since the fix was done a month ago, why did you not release it sooner?

**Comment by piroor** [comment]
There are some reasons:

* For further dogfooding. Sometimes I can't believe quality of changes as "good to release".
* A sense of sin about releasing without response to lately reported new issues.
* Simply my laziness. I ordinarily use the latest revision of TST via about:debugging, so I sometimes forget that recent changes are not released...

**Comment by irvinm** [comment]
@bughit, can you close this item?
