### ISSUE TITLE
Incompatible with "How Many Times Can I Back?" addon since Version 0.14.2012012901

### ISSUE THREAD

**Issue by tsbartha** [piroor/treestyletab#261]
The newer versions of this addon (later than Version 0.14.2012012901, released January 29, 2012) seem to be incompatible with your _How Many Times Can I Back?_ addon (including current Version 0.2.2011012001). If I have the latter enabled, _Tree Style Tab_ loses its ability to organize tabs as a tree (they are simply vertical), and there is a thin white border at the edges of the tabs that should not be there. If I disable _How Many Times Can I Back?_, then _Tree Style Tab_ works perfect. Also Version 0.14.2012012901 of  _Tree Style Tab_ and older do not have this issue and can work together with _How Many Times Can I Back?_ without any problems.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
