### ISSUE TITLE
Zombie tabs accrue: Closing a tab doesn't remove it from the list

### ISSUE THREAD

**Issue by xobs** [piroor/treestyletab#2612]
## Short description

Tabs are not removed from the list when they are closed

## Steps to reproduce

I am unable to reproduce this in a fresh install, meaning there is something in my current profile that is causing this.

 1. Start Firefox
 2. Open a new tab
 3. Close the tab

## Expected result

Tabs that are closed should disappear

## Actual result

As an example, "New Issue" is actually located to the right of "unit_arg", and "Final Fantasy X|V Online" and "Got to a certain part" are both closed.

![image](https://user-images.githubusercontent.com/238325/84979333-c5ff2c00-b161-11ea-832a-2a821297fdca.png)

I can switch the sidebar from "Tree Style Tab" to e.g. "Bookmarks" and then switch it back, at which point zombie tabs disappear. However, zombie tabs will continue to build up once again.

Reordering tabs using the Firefox tab manager does cause them to be reordered, however closing tabs does not cause them to be removed.

Note that the right-click menu of a zombie tab is different from a normal tab:

![image](https://user-images.githubusercontent.com/238325/84979621-740ad600-b162-11ea-8666-3bf483365301.png)

## Environment

 * Platform (OS): Windows 10 1904
 * Version of Firefox: 77.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.5.5 (2020.6.6)

**Comment by piroor** [comment]
I need steps to reproduce the problem with 100% probability to debug it by myself. Otherwise I'm happy if you try debugging on your environment and creating a pull request to solve it.

**Comment by xobs** [comment]
I'm happy to try debugging it in my environment, except I have no idea how to debug Firefox extensions. I have multiple questions:

- Is there an error log somewhere?
- Is it possible to attach a debugger?
- Where is its state data stored?
- Do you have any idea of where I should start looking?

**Comment by piroor** [comment]
Here are some documents for developers:
https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs
https://github.com/piroor/treestyletab/wiki/Module-Design

TST does not depend on any build system like webpack, so you just need to clone this repository to your PC and load the file "webextensions/manifest.json" via "about:debugging" to run latest development version TST. Modify-and-reload will help you to understand what is the role of each module.

**Comment by irvinm** [comment]
@xobs have you tried to create a clean profile to see if this problem persists?  You should try just Firefox and TST and assuming things are working, add back in your other addons, etc.  Without more information about how to reproduce, this situation would make finding a solution hard and this doesn't appear to be a wide-spread problem or others would have reported it as well.

Maybe you could close this issue until you have more information you can share.  You can still ask questions even when the issue is closed.

**Comment by xobs** [comment]
Yes, I'll close this thread for now, and if I'm able to recreate it again I will reopen it. Sorry for the noise.
