### ISSUE TITLE
Setting CSS to affect add-on context menu items

### ISSUE THREAD

**Issue by dsl101** [piroor/treestyletab#2616]
I'm working on an add-on which will have a custom menu, and I'd like to apply styling to these menu items with CSS (for colours relating to the functionality of the add-on). I've tried creating CSS that matches the menu element ids and including it in the `styles` parameter passed in to TST via the `register-self` message.

These colours are generated dynamically, and if I get my add-on print the CSS to the console then manually copy it into `userChrome.css`, on the next browser load it works fine. But obviously that's not ideal, and if the generated colours change (via a parameter in the add-on options), I have to repeat the process.

Is it possible to set CSS for an add-on context menu via a message to TST, so that menu items would be affected in this way? Or is that just a limitation of the context menu system in FF?

The CSS in question looks like this kind of thing in `userChrome.css`:
```
#tst-tab-colours_pale-ed-menuitem-_Colour-1 {color: hsl(0, 100%, 75%) !important}
```

**Comment by piroor** [comment]
Native context menu is shown by Firefox itself and colors of items in such native menus are out of control by addons, except their icon (you need to use data URI and dynamically-generated favicon rendered with HTML canvas). This is one of restrictions of WebExtensions based addon and it cannot be fixed by TST.

**Comment by dsl101** [comment]
That’s what I thought. But I hadn’t realised the icon parameter could be a
data uri so thanks for that. I’ll investigate that option.

And thanks again for TST—it’s a fantastic framework :)
