### ISSUE TITLE
tabbar scroll doesn't work with firefox settings

### ISSUE THREAD

**Issue by her34** [piroor/treestyletab#262]
Firefox 11.0
New profile with just Tree Style Tab 0.14.2012021101.
Windows xp

By default firefox is set to scroll distance set by system. On my computer mouse wheel is set to scroll 1 page at a time, you can set by going to "control panel", then go to "mouse", then go to "wheel" tab, then set to "one screen at a time".

This works for firefox and on websites, the page will scroll 1 page.

The using Tree Style Tab in vertical mode, the tabbar does not scroll 1 page. Instead it scrolls a little bit or a lot depending on how fast you are scrolling mouse wheel.

It's like Tree Style Tab tabbar has its own settings when it should be matching firefox settings when scrolling websites.

The newest firefox version 13 has new smooth scrolling algorithm and this is bigger problem there. The reason is that scrolling on website feels very different than scrolling tabbar. It would be much better if scrolling behaved the same everywhere.

**Comment by Dook1** [comment]
I report this bug. Please confirm it - https://bugzilla.mozilla.org/show_bug.cgi?id=1272991

**Comment by arni2033** [comment]
@piroor 
This bug with <arrowscrollbox> was completely fixed in: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1263975 ->
https://bugzilla.mozilla.org/show_bug.cgi?id=1251987 .

However, all strangeness with DOMMouseScroll event is still present.
If you think it's a good idea, please leave one comment saying something like "2^15 is a very strange and unexpected value indeed. -TST developer." here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1257815
I'll really appreciate this.

**Comment by Dook1** [comment]
Fixed in 49

**Comment by piroor** [comment]
@arni2033 I've read discussions in https://bugzilla.mozilla.org/show_bug.cgi?id=1257815 My position is similar to Masayuki Nakano. Strange behavior of DOMMouseScroll is left there too long, and changing of it will produce another new "regression" report for the new behavior. Anyway, he clearly said like "we have no plan to change this behavior", so web developers don't have to wait for fixing of the bug by Firefox. Not only the problem, there are many other incompatibility around non-standard APIs. Web developers should not spend their time to fix such legacy incompatibility. Instead they should migrate their application to new standard APIs quickly...

**Comment by Dook1** [comment]
Have you checked 49 nightly? All arrowscrollbox are working fine.
