### ISSUE TITLE
Focus on a tab not next to the current tab

### ISSUE THREAD

**Issue by SuperGianchi** [piroor/treestyletab#2620]
## Short description
Is there a keyboard shortcut to focus a tab that is not next to the current tab *without* loading all the tabs in between?

## Steps to reproduce
1. Let's say I have 20 tabs opened but not loaded (eg, from a previous session).
2. I bring focus on tab 10.
3. Then, I want to focus on tab 15 _using the keyboard only_.
I can use Ctrl+PgDown 5 times but this will load all tabs from 11 to 15, slowing down the loading of tab 15. 

(Going from tab 10 to tab 15 without loading tabs 11, 12, 13, 14, can easily be done with the mouse, clicking on tab 10 then on tab 15)

## Expected result
Load tab 15 and do not load tabs 11, 12, 13, 14.

## Actual result
Load tabs 11, 12, 13, 14 and slow down Firefox.

## Environment
 * Platform (OS): elementary OS 0.4.1 Loki, Built on "Ubuntu 16.04.5 LTS, Linux 4.4.0-154-generic.
 * Version of Firefox: 68.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.5.5 (2020.6.6):

**Comment by SuperGianchi** [comment]
P.S.
I know about the shortcuts Alt+1...8 but it works only for the first 8 tabs.
Currently, I'm using the FF button "List all tabs" (top right corner) using 'Up' and 'Down' keys to select a webpage and 'Enter' to load the webpage.
This method has the disadvantages that 
* using, for example, the 'Down' keys, FF starts to select the first webpage, so it can be confusing to find the wanted webpage if there are many webpages opened. It would have been better if, opening "List all tabs" menu and pressing the 'Down' keys, FF selected the webpage that is next to the current one.
* there is no tree style in the "List all tabs" view

**Comment by piroor** [comment]
I think such a feature is out of purpose of this project. Instead it should be done by something other addon made for the purpose, then it will help all people even if they don't use TST. Of course such an addon should skip collapsed tree on TST intelligently, if it uses TST's API to know trees' collapsed/expanded state.

I don't know such an addon is really existing or not. If it doesn't exist, it need to be develiped newly. Sorry but I don't have enough motivation to do that by myself, and I hope it will be developed by someone who really want to use it...
