### ISSUE TITLE
Disable tree behavior

### ISSUE THREAD

**Issue by nollinvoyd** [piroor/treestyletab#2622]
I just want a simple menu with no Tree behavior. 

Some time ago you advised me how to do that.  Something about debug mode. Recently, I did a "reset all", and now i cant remember how to get back to the menu the way I want it.

**Comment by irvinm** [comment]
From the main page:

I don't need automatically organized tree, instead I just want to organize tree by myself

You can deactivate TST's automatic tree organizing behaviors, by some secret preferences:

    Go to TST's configuration.
    "Development" section.
    Turn on the checkbox "Debug mode". Then all internal configurations are listed.
    Turn off the checkbox "autoAttach".
    Turn off the checkbox "syncParentTabAndOpenerTab".

After that TST never attach new tabs to existing tree automatically.

**Comment by nollinvoyd** [comment]
Thank you.
