### ISSUE TITLE
TST - How to change color of pinned tabs?

### ISSUE THREAD

**Issue by mwoffenden** [piroor/treestyletab#2624]
## Short description

It's hard to see which tabs are pinned.  Is there a way to change the background color of all pinned tabs?

## Environment

 * Platform (OS): MACOS 10.15.5
 * Version of Firefox: 77.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.5.5

**Comment by irvinm** [comment]
`.tab.pinned {
  background: pink !important;
}
`

Customize to your liking ... :)

**Comment by mwoffenden** [comment]
That was easy!
