### ISSUE TITLE
[feature request] Number of open tabs label on extension icon

### ISSUE THREAD

**Issue by haydenseitz** [piroor/treestyletab#2626]
## Short description
Hello! It would be very helpful to have a label/indicator with the total number of open tabs in the current window (parent and child tabs) on the extension icon.

![image](https://user-images.githubusercontent.com/17074342/86402411-a20f1080-bc60-11ea-9863-bf7adb041a61.png)

The lastpass extension has something similar:

![image](https://user-images.githubusercontent.com/17074342/86402235-58bec100-bc60-11ea-9426-732db8a82cad.png)

**Comment by irvinm** [comment]
Not a direct solution, but one option is that you can display your tab situation via TST CSS on the new tab button however you want.  I never use the new tab button, but wanted to know how many tabs were loaded and the total number of tabs.  (Loaded tabs / total tabs)  Here is what mine ended up looking like.

![image](https://user-images.githubusercontent.com/979729/86403480-cc21fc00-bc7b-11ea-9a4a-6d1a8d5b1291.png)

@piroor will comment on your direct request.

**Comment by haydenseitz** [comment]
@irvinm I like that! What CSS styling did you use to get that?

**Comment by irvinm** [comment]
Actual counting:  https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#tab-numbering-and-counting
Displaying counts:  https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#tab-counts-in-new-tab-button-1661

Customize to your heart's desire!

**Comment by piroor** [comment]
The feature is out of TST's purpose, so I won't implement it natively, sorry. Workaround based on custom styles looks a good alternative.

**Comment by Fethbita** [comment]
@irvinm how did you remove the plus sign in the middle of the new tab button?
![image](https://user-images.githubusercontent.com/13559217/101127179-a374a880-3605-11eb-830e-a90a4d77171c.png)
![image](https://user-images.githubusercontent.com/13559217/101127191-ac657a00-3605-11eb-94a0-e70fd740e91c.png)

**Comment by irvinm** [comment]
Here you go.

```
/* 
   Hide "+" symbol from new tab button at bottom of tab strip
*/
.newtab-button::before { background: none !important; }
```
