### ISSUE TITLE
[Idea] Support for FF78 multiple tab "Undo Close Tab"

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2627]
## Short description
FF78 adds the ability to "Undo Close Tab" for multiple tabs if they are all closed with a single operation.  It might be a nice safety feature if TST were to be able to support this concept.

https://www.mozilla.org/en-US/firefox/78.0/releasenotes/

> The context menu (accessed by right clicking on a tab) lets you undo multiple tab closings with a single click and places Close Tabs to the Right and Close Other Tabs in a submenu.

## Steps to reproduce

 1. Install FF78 without TST
 2. Create multiple tabs
 3. Multi-select several tabs (Shift or Control click on a set of tabs)
 4. Close the tabs via the "X" or right-click "Close tab"
5. Right-click on a remaining tab and select "Undo Close Tab"
6. All closed tabs would be restored

## Expected result
Would like to see TST mimic this behavior especially as a way to possible restore a tree that was collapsed and accidentally closed.

## Actual result
I believe that you are probably just iterating over tabs to be closed when a tree is collapsed and closed and hence each tab would be a separate "tab close" and the "Undo Close Tab" would simply restore that last closed tab.

## Environment

 * Platform (OS):  Windows 10 x64 (1909)
 * Version of Firefox:  FF 78.0.1
 * Version (or revision) of Tree Style Tab:  TST 3.5.5

**Comment by piroor** [comment]
Firefox updates the menu label just after multiple tabs are closed via "Close Tabs to the Right" or "Close Other Tabs" commands.

https://searchfox.org/mozilla-central/rev/31d8600b73dc85b4cdbabf45ac3f1a9c11700d8e/browser/base/content/tabbrowser.js#3254

The command "Undo Close Tab*s*" gets the number of tabs to be restored via an internal API, and repeatedly restores tabs internally.

https://searchfox.org/mozilla-central/rev/31d8600b73dc85b4cdbabf45ac3f1a9c11700d8e/browser/base/content/browser.js#8030

On the other hand, WebExtensions API doesn't provide ability to know the number of tabs recently closed with a single action. I've tried to fetch sessions information via `sessions.getRecentlyClosed()` but there is no hint to know which is the set of items produced by a single action.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sessions/getRecentlyClosed
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sessions/restore

This means that we only can simulate the "Undo Close Tab*s*" behavior on TST's sidebar just privately, and it must have some restrictions like:

* If you use the "Close Tabs to the Right" on Firefox's native tab bar, TST won't activate the "Undo Close Tab*s*" command.
  * TST cannot handle tabs restored via the native "Undo Close Tab*s*" command. They are simply treated like as multiple calls of the Ctrl-Shift-T shortcut.
* The "Close Tabs to the Bottom" command on the TST's sidebar also won't activate the "Undo Close Tab*s*" command in Firefox's native tab context menu.

But TST's custom "Undo Close Tab*s*" command will provide better UX for people who don't use Firefox's native context menu commands. We can easily treat tabs restored via the command more smartly, so I think TST will restores the structure of the reopened tabs with more stability.

**Comment by piroor** [comment]
There is one concern: `sessions.getRecentlyClosed()` doesn't allows us to fetch very large number sessions. The maximum count of fetchable sessions is restricted to 25. It looks too small for TST's usage...

**Comment by irvinm** [comment]
Thanks for checking it out.  I actually thought about potential WebExtensions limitations after I posted the idea and figured there might be some.

My biggest concern was collapsed trees that were accidentally closed.  (Obviously this shouldn't happen often)  Up to this point, the workaround is to simply use a session manager and restore the session.  However, not everyone uses a session manager.

Thanks again for looking into this.  Ideally, it would be nice to see TST handle a single undo close tab transaction (regardless of the number of tabs) but the work to track that and undo\restore it probably isn't worth the effort.

**Comment by piroor** [comment]
I've experimentally implemented the "Undo Close Tab*s*" behavior. TST now tries to restore the set of tabs closed together, when one of them is restored. This behavior becomes active only after any operation to close multiple tabs at a time on TST - close tree, close tab with collapsed descendants and others.
