### ISSUE TITLE
New tab container list continously scrolled to the bottom of the list

### ISSUE THREAD

**Issue by Valentin-N** [piroor/treestyletab#2630]
## Short description

I'm unable to create a new tab in a container situated at the top of the containers list when a large number of containers are in use (in my case, one per tab). This is because the container list is continously scrolled to the bottom of the list.

## Steps to reproduce

1. Start Firefox with clean profile.
2. Install TST.
3. Create a large number of containers (e.g. 100)
4. Ensure the option "Show container selector button on the "New Tab" button, when the button is pointed" is enabled
5. Click on the container dropdown on the new tab button and try to select the 1st container

## Expected result

Can select the 1st container.

## Actual result

Container list is continuously scrolled to the bottom, never being able to scroll to the top to select the 1st container.

## Environment

 * Platform (OS): MacOS 10.14.6, Ubuntu 20.04 Gnome
 * Version of Firefox: 78.0.1 (has been a problem since at least 76?)
 * Version (or revision) of Tree Style Tab: Anything after 3.4.10 is affected

**Comment by piroor** [comment]
Thanks! It should be fixed with the commit https://github.com/piroor/webextensions-lib-menu-ui/commit/48a1b576a8580b378fb5d7306fabaa4fc27ebb7d

**Comment by Valentin-N** [comment]
Thanks for the quick turn-around.

I tried TST 3.5.9 and unfortunately I can still replicate the problem (at least on my profile). I'll try to find time later to replicate on a clean profile.

**Comment by piroor** [comment]
I've downloaded 3.5.9 from AMO and I've realized that the included file is unexpectedly unupdated... Sorry, I'll update it again.

**Comment by Valentin-N** [comment]
Re-tested with TST 3.5.12 and the problem is solved for me. Thank you!
