### ISSUE TITLE
Touch VPN slows/delays TST render opening/closing/activating tabs

### ISSUE THREAD

**Issue by Jmennius** [piroor/treestyletab#2632]
## Short description

When [Touch VPN](https://addons.mozilla.org/en-US/firefox/addon/touch-vpn/) is installed opening or closing tabs is very slow.
The action/animation in TST is delayed for a few seconds while the browser itself opens or closes immediately.

I do not actually know if the native FF tab bar behaves well (I have it hidden).

## Steps to reproduce

Installing Touch VPN and TST should reproduce it... but it doesn't (in a fresh profile).
It manifests itself in a Private window when I disable or enable Touch VPN just like it does in a normal session, however.

## Expected result

There is no delay when opening or closing tabs when Touch VPN is installed.

## Actual result

There is a delay before TST renders a change (closing or opening) when Touch VPN is installed.

## Environment

 * Platform (OS): Fedora 32 (Silverblue)
 * Version of Firefox: 78.0.1 (Flatpak)
 * Version (or revision) of Tree Style Tab: 3.5.7

**Comment by Jmennius** [comment]
I am totally OK with closing this as a 3rd-party issue (if it is), just want the info to be available.

**Comment by piroor** [comment]
I've tried the Touch VPN but I couldn't see any difference around TST between activated and inactivated...

Addons look to be executed in a special process for addons (separated from Firefox itself and tabs), so if the Touch VPN takes computer resources other addons including TST may be affected. Could you try with only TST and Touch VPN?

**Comment by Jmennius** [comment]
Yeah, I did.
I've tried it in a separate profile and couldn't reproduce the issue... It only affects my main profile :(

BTW, I didn't make it clear - you don't have to actually connect the VPN, only have it installed & enabled.

**Comment by irvinm** [comment]
@Jmennius do you think you could try disabling all of your other addons from your main profile just leaving TST and your VPN to see if you still see the performance problem?  I am wondering if there might be some other issue with another addon that might just manifest itself as a performance problem with TST.  Just an idea considering that you do not see the issue in a clean profile.

**Comment by irvinm** [comment]
@Jmennius, just a friendly reminder.

**Comment by Jmennius** [comment]
Tried disabling everything else (only kept Mozilla's Multi-Account containers - can't mess them up) - same behavior.
Basically, in this profile it is enought to have only TST and that VPN plugin.

**Comment by irvinm** [comment]
@Jmennius I loaded Fedora 32 in a VM with FF, TST, and Touch VPN and didn't see any problems opening or closing tabs.  Everything seems normal to me.  You also said you weren't able to reproduce the situation in a new profile.  There must be something else going on with your main profile and\or some profile corruption going on.  I think (honestly) the best thing to do is build up a new profile with everything you normally do and see if the problem persists.  I don't think there is likely anything @piroor will be able to do given that everything seems to work with a clean profile.

**Comment by Jmennius** [comment]
Yup, I totally agree. Thank you for your attention!

**Comment by irvinm** [comment]
@Jmennius will you close this item?  If there is more to discuss moving forward, we can still do that when it is closed.
