### ISSUE TITLE
Version 3.5.7 breaks TST Hoverswitch

### ISSUE THREAD

**Issue by cam29** [piroor/treestyletab#2634]
Just that. Version 3.5.7 breaks the all-important TST Hoverswitch…

 * Platform (OS): Windows 10 2004
 * Version of Firefox: 78.0.1

**Comment by irvinm** [comment]
Looks like this should be fixed after the next release of TST:  https://github.com/piroor/treestyletab/commit/366096495b2e4dc0835a19654da88e8700bb2083

**Comment by klemens** [comment]
Yes, we have already fixed this, just waiting on a new release. :slightly_smiling_face:

**Comment by irvinm** [comment]
@cam29 can you try with the latest and close this item if resolved?

**Comment by cam29** [comment]
Resolved.
