### ISSUE TITLE
Missing Tabs

### ISSUE THREAD

**Issue by viking2** [piroor/treestyletab#2635]
I have several tabs open but TST only shows the Tabs to the right of current Tab. To select a Tab to the left of the current tab, I need to use FF standard Tabs on top.
![](https://i.gyazo.com/a6682acf40e0956db3191e131c03e76b.png)

Firefox 78.0.1
TST 3.5.7
OS WIN7 (x64)

**Comment by piroor** [comment]
It is quite unexpected result. It looks that TST failed to track some tabs. Could you try disabling and re-enabling TST from the addons manager?

**Comment by viking2** [comment]
I don't know the steps that I took to end up with the missing tabs. I have not been able to reproduce it. I will report it again if it happens again.

**Comment by irvinm** [comment]
@viking2 could you close this item and reopen when you have more information on how to reproduce?

**Comment by piroor** [comment]
FYI: I  (the project owner) also can close issues, but issues closed by me cannot be reopened by their reporter. This is the reason why closing by the reporter is recommended.

**Comment by viking2** [comment]
I close this now and will reopen it if it occurs again.
