### ISSUE TITLE
tab labels now in bold

### ISSUE THREAD

**Issue by zeromus** [piroor/treestyletab#2636]
Hi there. Apologies for creating a not-quite-a-bug here. This seems to be a new problem and I wanted to create a bug for other people with the same problem to find, until the problem is fixed properly or otherwise triaged. I hope you don't mind.

Did you notice that your tab labels are all in BOLD suddenly? It's 2020 and stuff updates without our permission, so that must have happened. Here's how to fix it.

`Tools > addons > tree style tab > ... > options > advanced > extra style rules`

Add this OUTSIDE the comments, e.g., at the very bottom. 
`tab-label { font-weight: normal; }`

**Comment by irvinm** [comment]
I don't see any differences around tab labels being bold.  Can you reproduce this in a clean profile with just TST installed?

Can you list the steps to reproduce this?

**Comment by zeromus** [comment]
Mainly, I just noticed suddenly one day (recently) _two_ separate windows 7 systems with firefox 78.0.1 installed had the problem. 

I just created a new profile and added TST, and it was already bolded. I tested again in a windows 10 VM and they were _not_ bolded. But... it was on FF 77.0.1. I updated it and... still not bold? But I noticed it was 32bit for some reason. So I reinstalled it and made sure 64bit FF was installed... and it's still not bold.

It's possible they're only bolded on my windows 7 systems since I have done a number of things to mess around with how fonts work on my system and in my firefox. But... uhh... I might have done those on the win10 VM too? I wouldn't blame you for closing this as "user hacked his fonts" but I suggest there's a decent chance it may affect every win7 system. Wait and collect more info, I advise.

**Comment by irvinm** [comment]
I created a new Windows 7 VM, installed FF, installed TST ... I don't see any issues with the tab labels.

![image](https://user-images.githubusercontent.com/979729/87048450-bb1c4200-c1c9-11ea-8c47-8f6a65224711.png)

**Comment by piroor** [comment]
@zeromus Could you paste a screenshot? It possibly helps my understanding about what happens on your environment.

And, if you OK could you inspect the computed style of tab labels with the debugger? Here is steps to start inspection of the sidebar: https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-inspect-the-sidebar

**Comment by piroor** [comment]
Computed style on my environment:
![image](https://user-images.githubusercontent.com/70062/87050774-b1322780-c239-11ea-8e75-e6af48c6f2b9.png)
"Fonts" tab on my environment:
![image](https://user-images.githubusercontent.com/70062/87050674-88aa2d80-c239-11ea-9cf4-d80185893804.png)
On my case there is no style definition about "font-weight" for tab labels.

**Comment by zeromus** [comment]
mysterious:
![image](https://user-images.githubusercontent.com/102701/87072841-72c14c00-c1ea-11ea-8cfd-56bdefaa424d.png)

**Comment by piroor** [comment]
Hmm... TST doesn't have any code to apply such a style directly to the element, and it can't be done via TST's API. Do you use any user script?

**Comment by zeromus** [comment]
I disabled all other extensions and removed my userchrome.css (which contained only "to hide the sidebar header" and "to hide the native tabs" anyway) and the tabs were still bold. The tabs were NOT bold in the default firefox horizontal tabs (which I saw by disabling TST as the final extension)

**Comment by natenate19** [comment]
I noticed something similar starting in Tree Style Tab 3.5.7, except tab labels weren't bold, just a larger font-size than before 3.5.7.  Seems specific to Plain, Plain Dark, Vertigo, and Mixed themes.  Metal, Sidebar, and High Contrast themes don't exhibit the issue.  Since I prefer the Mixed theme, I hacked around it in much the same manner as @zeromus:

`tab-label { font-size: 11px; }`

Without doing this it seems like Plain, Plain Dark, Vertigo, and Mixed themes default to a font-size of 13px now, whereas Metal, Sidebar, and High Contrast themes still default to 11px.  For the record I'm using:

Firefox 78.0.1 / 78.0.2
MacBook Pro 13" 2020, highest resolution for built-in display
macOS 10.15.5

**Comment by piroor** [comment]
I've tried Firefox ESR78.0.1 on Windows 7 32bit with TST 3.5.9. Initially I couldn't reproduce the bold text problem, but after I switched the desktop theme from "Windows 7 Basic" to "Windows Classic" tab labels have became bold.

It is produced by the system font name "caption" defined at this line: https://github.com/piroor/treestyletab/blob/1207f34f9ee1acd164e2118a324118c0d040f5f1/webextensions/resources/ui-color.css#L257
And it is quoted from Firefox's built-in styles for addons:  https://searchfox.org/mozilla-central/rev/622dbd3409610ad3f71b56c9a6a92da905dab0aa/browser/components/extensions/extension.css#17
So the unexpected bold font problem appears not only on TST. Here is a screenshot of Firefox Multi-Account Containers, the caption and the "Manage Containers" are bold unexpectedly:
![image](https://user-images.githubusercontent.com/70062/87174491-325ced80-c312-11ea-8597-68c66ce2994f.png)

I've added a line to cancel the bold weight with the commit 4dbc72a, so it should fix the problem.

**Comment by piroor** [comment]
@natenate19 I think that the problem you saw is also produced by the system font name. If the window caption has large font size on your system, TST's tabs will be shown with the size same to them. I cannot determine the only one font size definition suitable for all platforms so I still hope to use the system font name for safety...

**Comment by zeromus** [comment]
I can confirm I'm using classic theme. Thanks for figuring this out.

The choice of "caption" for this font is weird. There is a little bit of sense for using caption for things that are like tabs, given that in your screenshot the tabs are invading the former caption area. But the extension.css you linked to seems to be setting it for every purpose, which is what's weird. A better choice would be something like "menu item" font.

**Comment by piroor** [comment]
> A better choice would be something like "menu item" font.

Thank you for a suggestion, but finally I've decided to use the system font "caption" for visual compatibility with other addons, and better accessibility.

**Comment by irvinm** [comment]
@zeromus can you try with the latest and close this item if resolved?

**Comment by zeromus** [comment]
I have july 14 version and the problem seems solved. Thank you very much.
