### ISSUE TITLE
Trivial question: How to I Promote(Demote) a child one level Up(Down)?

### ISSUE THREAD

**Issue by viking2** [piroor/treestyletab#2637]
Trivial question: How to I promote(Demote) a child one level up(Down)?
Dragging dropping with the mouse gives somewhat random results. Demoting seems to work better than promoting. 
There are no right-click menu commands for this? Are there any keyboard shortcuts?

**Comment by piroor** [comment]
TST has ability to do that via a keyboard shortcut but no key is bound by default. You need to set shortcuts manually via `about:addons` => Extensions => the gear button => Manage Extension Shortcuts => Tree Style Tab => Show ** More => Indent/Outdent Current Tab.

**Comment by viking2** [comment]
Thanks!
BTW, how would I "Outdent Current Tab" using the mouse? Dragging the tab to the left doesn't work.

**Comment by irvinm** [comment]
I tried a few situations, but it looks like it should work if it is the bottom tab in a tree.  

![2020-07-09_18-44-02](https://user-images.githubusercontent.com/979729/87098044-6e118d80-c214-11ea-9016-af8a63c1247b.gif)

If there is a child under the tab being moved, it doesn't work. (I thought this would work)

![2020-07-09_18-49-37](https://user-images.githubusercontent.com/979729/87098319-fbed7880-c214-11ea-80fc-a387994f6876.gif)

If there is a sibling under the tab being moved, it doesn't work. (I think this makes sense not to work)

![2020-07-09_18-51-32](https://user-images.githubusercontent.com/979729/87098431-440c9b00-c215-11ea-9208-95f04e83b5ab.gif)

@piroor what do you think?

**Comment by piroor** [comment]
@irvinm Thank you for research! The action must promote the dragged tab. The functionality was unexpectedly lost by changes in recent versions and dd367f9 should fix it.

@viking2 As @irvinm described with screencasts, dropping a child tab just after its present parent is a special action to promote the dragged tab on level. It was unexpectedly broken on recent versions but it should become available on TST 3.5.9 and later.

**Comment by irvinm** [comment]
@viking2 can you test with 3.5.12+ and close if this is resolved?

**Comment by irvinm** [comment]
@viking2, a a friendly reminder ...

**Comment by irvinm** [comment]
@piroor I think this can be closed.

**Comment by fghimis** [comment]
@piroor Can you still use a keybinding to Indent/Outdent current tab link [here](https://github.com/piroor/treestyletab/issues/2637#issuecomment-656125396)? I can't find it in **Manage Extension Shortcuts => Tree Style Tab**.

**Comment by piroor** [comment]
@fghimis Those features are not built-in commands now, and were moved to a helper addon TST More Tree Commands https://addons.mozilla.org/firefox/addon/tst-more-tree-commands/
