### ISSUE TITLE
Closing tab takes much longer time compared to 3.5.7

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#2639]
Hello!
Closing tab takes much longer time in 3.5.8 (or any newer version) compared to 3.5.7. By "longer time" I mean the amount of time before the closed tab disappears from the TST sidebar. 

STR:
1. Create new profile, install latest TST dev.build
2. Go to TST settings, disable animation
3. Press Ctrl-T, press Ctrl-T
4. Press Ctrl-W

ER: Closing tab is instantenious since there is a small amount of tabs open. That's what happens in TST3.5.7
AR: It takes around a second or two before the closed tab disappears from the TST sidebar

Commit that caused the regression: https://github.com/piroor/treestyletab/commit/60ce791b5851804e3a09976b338800c7c36d93fd

**Comment by piroor** [comment]
The change 60ce791 was introduced to reduce needless confirmation for "Close Tabs to the Right" and "Close Other Tabs" commands of Firefox itself. It is an unintentional side effect that slowing down of tab close.

I've introduced two more changes: 1307e09 to close tabs immediately and 722813c to show confimration dialog with more meaningful messages.

**Comment by SXZ1** [comment]
I can no longer reproduce this bug in 3.5.12. You've done an awesome job once again, thank you very much!
