### ISSUE TITLE
Is there some way to turn on/off the top Tab bar when using TST?

### ISSUE THREAD

**Issue by viking2** [piroor/treestyletab#2642]
I would like to be able to turn on/off  the top Tab bar w/o using userChrome.css (it is difficult to turn on/off with this option).

I tried https://addons.mozilla.org/en-US/firefox/addon/hide-tab/ but that didn't work at all (cant hide Tabs).
I also tried https://addons.mozilla.org/en-US/firefox/addon/panorama-view/, but that also hid TST.

Note the config option "extensions.webextensions.tabhide.enabled" is set to true.

**Comment by irvinm** [comment]
There is no way (to my knowledge) outside of userChrome.css until https://bugzilla.mozilla.org/show_bug.cgi?id=1332447 is implemented.

**Comment by piroor** [comment]
FYI: Tab hide API (in old days it need to be activated with `extensions.webextensions.tabhide.enabled`) just allows addons to hide *individual tabs*. TST also supports the API - TST never calls the API but TST hides tabs if they are hidden by other addons via the API, so it won't help you to help hiding the top tab bar itself.

**Comment by viking2** [comment]
What about the Stylish extension? Can that one, with proper CSS, be used to turn off the Tab bar (and then on by disabling the extension?

**Comment by piroor** [comment]
WebExtensions-based Stylish (it is the only one available edition on recent versions of Firefox) has no ability to apply stylesheets to Firefox itself, instead it just allows you to apply stylesheets to websites. Please remind that Firefox Quantum allows just limited ability of customization for addons, very high customizability on XUL addons (before Firefox 56) was already lost.

**Comment by irvinm** [comment]
@viking2 was there anything more to discuss here?  If not, would you please close this item?

**Comment by irvinm** [comment]
@viking2 a friendly reminder.

**Comment by viking2** [comment]
Sorry, forgot to close. Closed now.
