### ISSUE TITLE
Clicking the "TST does not have permission" dialog takes you to an unhelpful place

### ISSUE THREAD

**Issue by colemickens** [piroor/treestyletab#2643]
## Short description

I dread a new Firefox install because I can never, ever figure out how to get back into TST to allow it to bookmark a tree of tabs. When you do so, it does pop a notification, but clicking it just takes me to the settings page and I can *not* find this setting *anywhere* on this page. I'm sure it's on a different one, but I can't fire out how to get to it either.

Is there any way this can be made easier?

 * Platform (OS): Linux
 * Version of Firefox: 77.0.1
 * Version (or revision) of Tree Style Tab: 3.5.12

**Comment by irvinm** [comment]
@colemickens from the settings page, have you tried clicking on the "Page for Initial Startup"?  Is that what you are looking for?

![image](https://user-images.githubusercontent.com/979729/87536832-b93dfd00-c667-11ea-8c99-58d728292b85.png)

**Comment by piroor** [comment]
On my environment, clicking the popup shows this result:
![image](https://user-images.githubusercontent.com/70062/87567723-97905480-c6ff-11ea-9682-1884c2f84efd.png)
The checkbox "Allow to read and create bookmarks" should activate the permission. This is the expected, but did you see different result actually? Or, did you mean that the label of checkbox is not friendly?

**Comment by irvinm** [comment]
@colemickens can you reply to @piroor's questions?

**Comment by colemickens** [comment]
@piroor is right, I was looking for a different screen. I thought these "extra permission" check boxes used to be on a different page?

Either way, this can be closed.

**Comment by piroor** [comment]
@colemickens Do you mean `ext+treestyletab:startup` ? It is accessible under the section "Development", but I agree that there is too less hint...
