### ISSUE TITLE
Highlighting of selected tabs is broken by 3.5.12 (for certain tab themes)

### ISSUE THREAD

**Issue by lewallen** [piroor/treestyletab#2644]
Version 3.5.12 seems to break tab highlighting (upon tab selection) when using the "Metal" tab theme (with the "Plain" theme for example, tab highlighting seems unchanged). Specifically, in previous versions including 3.5.11, when I use the Metal skin and select one or more tabs, the unselected tabs become darker ("tab highlighting"), but this feature seems to be broken in 3.5.12. 

If this is a bug would love to see it fix, the highlighting is really useful. Thanks for all your work with this extension! Please let me know if additional info would be helpful.

**Comment by piroor** [comment]
Thanks! The commit e162a6c should fix this.

**Comment by lewallen** [comment]
It works! Thanks a lot. When do you think it might go out to the official add-on list?

**Comment by grahamperrin** [comment]
Thanks for reporting/fixing this! I sensed that something was wrong recently but I have many extensions so my initial assumption was a conflict. 

I tentatively worked around by removing `3.5.12` (oops, I forgot that removing extensions destroy preferences) then installing `3.4.10` … it was OK for a few hours but then something felt not quite right … can't quite put my finger on it … I'll review after the next release.

PS

> … (with the "Plain" theme for example, tab highlighting seems unchanged). …

For me, with `3.5.12`, _Plain_ **is** bugged. In the screenshot below, it appears as if three tabs are selected but the one tab that I'm viewing (the result of a normal click, not multi-select) is not highlighted: 

![image](https://user-images.githubusercontent.com/192271/87669766-7151cf80-c766-11ea-92f9-15323bf16d5d.png)

**Comment by piroor** [comment]
@grahamperrin I couldn't see the problem on my environment with the latest development build. Could you try it to confirm the change I did solves the problem or does not? https://github.com/piroor/treestyletab#development-builds

@lewallen It will take more time because I hope to include a fix for #2645 to the next release.

**Comment by irvinm** [comment]
@lewallen can you review if this is fixed and close this item if it is?
