### ISSUE TITLE
TST acting up last couple of days

### ISSUE THREAD

**Issue by mwoffenden** [piroor/treestyletab#2645]
## What happens

1. Overlapping tabs
2. Blank gray areas

See attached image.  It gets worse over time.  To reset things I have to disable/enable TST but then the problem comes back.

## Expected Result

Tabs would display correctly

## How to reproduce

Just use the browser.  Over time it gets worse.

## Environment

 * Platform (OS): MacOS
 * Version of Firefox: 78.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.5.12 (2020.7.12)

<img width="206" alt="screenshot_3798" src="https://user-images.githubusercontent.com/6774346/87724141-efbf6900-c788-11ea-98d5-b1821f6343d4.png">

**Comment by piroor** [comment]
Could you describe what happens on your environment - what is the expected result, and how to reproduce the problem?

**Comment by piroor** [comment]
I've not reproduced this on my environment yet, but the problem looks to appear from the origin same to #2652 and the commit ac23b65 can affect to this. Could you try the latest development build?: https://github.com/piroor/treestyletab#development-builds

**Comment by mwoffenden** [comment]
Yes, but how do I install the build?

**Comment by piroor** [comment]
You'll see detailed instructions under the summary "It is not signed, so you need to load it by non-regular way. (Please click this section to see instructions.)" after you click that.

**Comment by mwoffenden** [comment]
Ok, installed it and after over 1/2 hour of use, no issues, so looks like it's solved.  Typically the issue showed up within 10 mins of use before.  I'd give it another hour though.  Will report back.

**Comment by mwoffenden** [comment]
Still no issues after constant use for 2 hours, so we're all set here! 

When do we see the fixed version as a release?

**Comment by piroor** [comment]
It is already released on the addons.mozilla.org website, so you'll see it updated soon.

**Comment by mwoffenden** [comment]
Unfortunately the problem is back after restarting the machine.  The image below shows:

1. gray space opens up on its own
2. tabs overlap in the same location

<img width="110" alt="screenshot_3829" src="https://user-images.githubusercontent.com/6774346/88070312-8badf380-cb40-11ea-94a9-fc4043ce4b8c.png">

**Comment by mwoffenden** [comment]
False alarm, sorry
