### ISSUE TITLE
Feature Request: Better Integreations w/ Firefox Built-in Open-Tabs Search

### ISSUE THREAD

**Issue by SevenFactors** [piroor/treestyletab#2646]
## Short description 

Firefox Built-in Open-Tab Search is Very Poor. Is there anything you can do at your end to better its results, better yet, integrate such feature with TST.

## The Why

Firefox built-in tab search feature is unreliable.
By default, FF's Address-bar result include: browsing history, bookmarks, open tabs & top sites. Add to this, that the result presented on the address-bar are limited to 15 -give or take.
Setting address-bar to only show "Open Tabs" results, some tabs show on the results while other do not show.
Even when using Firefox address-bar search modifier "%" to only yield tab results, hardly ever find the desired tab(s).

## My Experience

I'm one of those how rides its Firefox on a sea of tabs. Even thought TST does a great job at organizing tabs in folders, including those synced from other devices, having all these tabs is as good as it is finding them. Reading up and down the Tree Style Tab list can be time consuming, specially when working on one too many things. Now, depending on Firefox built-in open-tabs search to find tabs can be completely frustrating.
 
I tried to make this better by increasing the amount of results presented by default on the address-bar from the default value to 25. Then I ended up reducing the type of results being shown to only "open-tabs" Even under these settings, tabs that I am looking at on the TST panel, do not show on the address-bar results.

Is there anything at your end that you can do so that Firefox can find all the available tabs on TST. It would be beautiful if this worked reliably out of the box.

Thank you.

## Environment

 * Platform (OS): WIN10
 * Version of Firefox: 78.0.2 64-bit stable. 
 * Version (or revision) of Tree Style Tab: 3.5.12 (2020.7.12)

**Comment by piroor** [comment]
Sorry, I won't add this feature to TST as a built-in because it is out of purpose of this project. Instead I recommend you to use another tab listing addon providing search field together with TST.
https://github.com/piroor/treestyletab#similar-projects
Under the collapsed item "Listing tabs with a search field" I listed some addons providing the feature.

**Comment by SevenFactors** [comment]
Hello piroor.

I am not referring to adding a search feature to TST itself but rather make it work with Firefox's own open-tabs search feature. 

Firefox allows user to search for open-tabs from within Firefox's address-bar. For some reason, some tabs show while other open-tabs do not. This is why I was asking to see if there is something at the TST level that can be better integrated with Firefox's own open-tab search so that it may see all tabs. Open-tabs search can be done by using "%" on the address bar.

I reached out to you knowing that a TST built-in feature is one you will not add but also knowing that you are willing to make TST work with other addons which offer a tab search feature. I was hoping that perhaps, Firefox's own built-in tab search would be the best candidate for such category given that the search feature is part of the browser itself.

With that said, Thank you for such great add-on.

**Comment by SevenFactors** [comment]
> 
> 
> Sorry, I won't add this feature to TST as a built-in because it is out of purpose of this project. Instead I recommend you to use another tab listing addon providing search field together with TST.
> https://github.com/piroor/treestyletab#similar-projects
> Under the collapsed item "Listing tabs with a search field" I listed some addons providing the feature.

Hello piroor.

I am not referring to adding a search feature to TST itself but rather make it work with Firefox's own open-tabs search feature.

Firefox allows user to search for open-tabs from within Firefox's address-bar. For some reason, some tabs show while other open-tabs do not. This is why I was asking to see if there is something at the TST level that can be better integrated with Firefox's own open-tab search so that it may see all tabs. Open-tabs search can be done by using "%" on the address bar.

I reached out to you knowing that a TST built-in feature is one you will not add but also knowing that you are willing to make TST work with other addons which offer a tab search feature. I was hoping that perhaps, Firefox's own built-in tab search would be the best candidate for such category given that the search feature is part of the browser itself.

With that said, Thank you for such great add-on.

**Comment by piroor** [comment]
> For some reason, some tabs show while other open-tabs do not. This is why I was asking to see if there is something at the TST level that can be better integrated with Firefox's own open-tab search so that it may see all tabs.

The algorithm to list search results in the address bar is based on ["frecency":](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Places/Frecency_algorithm). It is designed to list locations you frequently and recently visited. You can modify the bonus for each visit type via `about:config` - please search "frecency" to list related preferences - but it looks impossible to give higher bonus for open tabs. Indeed [the SQL query for the search result](https://searchfox.org/mozilla-central/rev/2f75c35b647a03e7afad0af906643ec50b5b4ede/toolkit/components/places/UnifiedComplete.jsm#72) is sorted only with with `frecency`, and the `open_count` corresponding to the [count of opened tabs](https://searchfox.org/mozilla-central/rev/2f75c35b647a03e7afad0af906643ec50b5b4ede/toolkit/components/places/UnifiedComplete.jsm#72) does not used for sorting.

And, sadly Firefox doesn't provide ability to touch the default search result from addons. The only one API around the address bar is the [omnibox API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/omnibox), and it just allows addons to provide custom search results for a custom trigger like `%`.

**Comment by piroor** [comment]
Just an idea (for another addon): we possibly can hack the address bar search results with auto-bookmarking of open tabs. It can increase frecency of open tabs and raise them in the search result. I think there is one possible side effect: If you use Firefox Sync, Firefox unexpectedly synchronizes such temporary bookmarks. When you use two devices at same time, temporarily added bookmarks corresponding to open tabs in a device will be listed in the search result on another device.

**Comment by irvinm** [comment]
@piroor any reason to leave this open in terms of TST now?

**Comment by piroor** [comment]
I won't do anything about this on TST. Customizing of default suggested results of the address bar is interesting but out of purpose of this project, thus I close this.
