### ISSUE TITLE
"Close Descendants Too" Preference not saved

### ISSUE THREAD

**Issue by nleskiw** [piroor/treestyletab#2649]
## Short description
Preference "Tab Behavior" > "When a parent tab is closed or moved just as a solo tab" > "Custom" > "For Operations inside the tree sidebar" is not saved.

## Steps to reproduce

1. Start with a clean profile (I removed directories and profile.ini from .mozilla/firefox/profiles from terminal) 
1. Install TST
1. Go to TST Preferences
1. Scroll to "Tab Behavior" > "When a parent tab is closed or moved just as a solo tab" 
1. Select "Custom" radio button
1. Change "For operations inside the tree sidebar:" to "Close Descendants Too" 
1. Close TST Preferences. 
1. Re-Open TST Preferences

## Expected result

"For operations inside the tree sidebar:" should read "Close Descendants too" 
Closing a parent tab of a tree should close all descendants. 

## Actual result
"For operations inside the tree sidebar:" reads "Promote the first child as the new parent always"
Closing the parent tab of a tree promotes the first child.

## Environment

 * Platform (OS): Ubuntu 20.04
 * Version of Firefox: 78.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.5.12

**Comment by piroor** [comment]
Thanks, this should be fixed with the commit c19c3937836af7b5afa9ff72d5d6b4e6c2fc0b0c.

**Comment by irvinm** [comment]
@nleskiw can you review if this is fixed and close this item if it is?

**Comment by irvinm** [comment]
@piroor I think you can close this one.
