### ISSUE TITLE
List tabs that will be closed in the "You are about to close <n> tabs" dialog

### ISSUE THREAD

**Issue by notmgsk** [piroor/treestyletab#2650]
# Short description

When closing a parent tab TST presents a dialog asking if you also want to close the child tabs. Often it is unclear what those child tabs are since either the affected tabs are too small to see their titles, or the tabs are collapsed in the TST sidebar. In the dialog it would be helpful if the titles of those tabs were listed so we could better appreciate which tabs will be affected.

## Steps to reproduce

1. Have many tabs open.
2. Under a particular tab, spawn a number of child tabs.
3. Collapse the tree for that particular parent tab.
4. Attempt to close the parent tab.
5. Prompted with the "You are about to close <n> tabs" dialog.

## Desired result

List the tabs that may be affected by the action of the dialog.

## Actual result

Dialog does not provide enough (or any) information about the affected children tabs.

## Environment

N/A.

**Comment by piroor** [comment]
This idea is interesting. How do you think cases with very large number of tabs? Should only some tabs are listed, or all tabs with a scrollbar?

First I thought that this improvement should be implemented by Firefox itself for its built-in "Close Tabs to the Right" and "Close Other Tabs", but now I think that this can be done by TST privately, because TST users may execute "close multiple tabs" operations more frequently. This will help TST users preventing accidental "close tabs" decision for wrong trees.

**Comment by piroor** [comment]
![image](https://user-images.githubusercontent.com/70062/87905440-85b20700-ca9b-11ea-8e67-3ceee129ccb6.png)
Experimental implementation. Currently the list is shown with 5 items and scrollable.

**Comment by piroor** [comment]
![image](https://user-images.githubusercontent.com/70062/87928386-b73cc980-cabf-11ea-8518-dbe250f5da49.png)
Updated.

**Comment by notmgsk** [comment]
> This idea is interesting. How do you think cases with very large number of tabs? Should only some tabs are listed, or all tabs with a scrollbar?
> 
> First I thought that this improvement should be implemented by Firefox itself for its built-in "Close Tabs to the Right" and "Close Other Tabs", but now I think that this can be done by TST privately, because TST users may execute "close multiple tabs" operations more frequently. This will help TST users preventing accidental "close tabs" decision for wrong trees.

My vote goes to the scrollbar.

**Comment by notmgsk** [comment]
> ![image](https://user-images.githubusercontent.com/70062/87928386-b73cc980-cabf-11ea-8518-dbe250f5da49.png)
> Updated.

Yeah, that looks great.

**Comment by piroor** [comment]
OK, this UI is now available as a part of TST 3.5.13.

**Comment by notmgsk** [comment]
Thanks and nice work @piroor
