### ISSUE TITLE
Custom user style for discarded tabs not applied

### ISSUE THREAD

**Issue by Altsinn** [piroor/treestyletab#2651]
## Short description
I wanted to use custom style rule for discarded tabs:

.tab.discarded
{
	filter: grayscale(70%);
    transition: filter 0.2s ease-in;
    opacity: 0.7;  
    font-style: italic !important;
}

After Firefox restart or after session restoration all tabs should have custom style applied. Currently TST applies it only for internal pages like about:addons, about:confg ect. Print-screen below shows how it looks after Firefox restart. When tab is discarded during session, custom style is applied correctly.  The rest of custom rules, not related to discarded tabs, are working ok. I tried to debug:

- disabled Auto Tab Discard add-on, 

- installed 3.4.10 version of TST to verify if it is a regression from recent version, 

No results. 

![obraz](https://user-images.githubusercontent.com/50676021/87870440-5a022480-c9a8-11ea-99ad-0ddc8ee39795.png)

## Steps to reproduce

 1. Apply custom user style for discarded tabs
 2. Restart Firefox

## Expected result
Custom user style is applied for all tabs

## Actual result
Custom user style is applied for internal pages only

## Environment

 * Platform (OS): Windows 7
 * Version of Firefox: 68 ESR
 * Version (or revision) of Tree Style Tab: 3.5.12 and 3.4.10

**Comment by piroor** [comment]
I've tried TST 3.5.12 on Firefox ESR68 on Windows 10 but I couldn't reproduce it. Steps I did:

1. Start Firefox ESR68 with a clean profile.
2. Go to the options page of Firefox, and activate restoration of last lession.
3. Install TST 3.5.12.
4. Open some tabs. I've tried with tabs with addons.mozilla.org.
5. Restart Firefox.

How do you restore the last session? Any other addon?

**Comment by Altsinn** [comment]
I use Firefox "Restore previous session" option. I have several other add-ons. Following your hint I disabled them one by one and I found the culprit - uBlock Origin 1.28.5b2. It's a developer version, not the regular one. When I switched to an earlier version 1.28.5b1 the problem disappeared. So it appears that the latest changes in uBlock Origin somehow interfere with TST.

https://github.com/gorhill/uBlock/compare/1.28.5b1...master

**Comment by piroor** [comment]
I've browsed the diff but I couldn't find out any possible trigger. I think that this problem is an unexpected side effect and the root problem is an edge case bug of Firefox itself.

**Comment by Altsinn** [comment]
@piroor, the issue was fixed on the uBO side so I closed this one.

**Comment by piroor** [comment]
Memorandum:

* https://github.com/uBlockOrigin/uBlock-issues/issues/1167#issuecomment-660661902 
* [1428956 - Nano Defender causes tabs to be un-lazified at startup](https://bugzilla.mozilla.org/show_bug.cgi?id=1428956)
