### ISSUE TITLE
Unpinning tab does not resize to original size

### ISSUE THREAD

**Issue by evening** [piroor/treestyletab#2652]
## Short description

Unpinning tab does not resize to original size.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open webpage.
 4. Pin webpage tab.
 5. Unpin tab.

Video here: https://www.dropbox.com/s/lacqyxorulv080z/G2tYPY9mcg.mp4

## Expected result

Tab should resize to full size.

## Actual result

Tab maintains "pinned" size, and offset by amount when tabbed.

## Environment

 * Platform (OS):  Windows 10
 * Version of Firefox:  78.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.5.12

**Comment by piroor** [comment]
Thanks! The commit ac23b65 should fix this.
