### ISSUE TITLE
3.5.13 regression: no confirmation for "close this tree" (multiple tabs)

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#2655]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. create a tree of two tabs (parent, child)
 4. "close this tree" on the parent

## Environment

 * Platform (OS): win7 sp1 x64
 * Version of Firefox: 78.0.2 x64
 * Version (or revision) of Tree Style Tab: 3.5.13

**Comment by piroor** [comment]
Thanks, this should be fixed with the commit 2ee5fa4.
