### ISSUE TITLE
Restoring closed tab - Incompatibility with Simple Tab Group addon

### ISSUE THREAD

**Issue by byblo** [piroor/treestyletab#2659]
Restoring child tabs on another STG group will show incorrect tree order on both groups.

To reproduce bug:
----------------------
- Install Simple Tab Group, Tree Style Tab addons (I tried on a fresh profile)

  - Create group 1
  - Create group 2

- On group 1, make a tree with 3 tabs:
  ```
  en.wikipedia.org/wiki/A
  > en.wikipedia.org/wiki/B
  >> en.wikipedia.org/wiki/C
  ```

- On group 2, make a tree with 3 tabs:
  ```
  en.wikipedia.org/wiki/X
  > en.wikipedia.org/wiki/Y
  >> en.wikipedia.org/wiki/Z
  ```

- Close tabs on group 1: 
  ```
  > en.wikipedia.org/wiki/B
  >> en.wikipedia.org/wiki/C
  ```

- Goto group 2, and Undo Close C and B tabs there.

- Now you can see 2 problems with STG addon:
  1. Undo tabs from group 1 are restored to the wrong and current selected STG group 2.
  2. The tree of A,B,C tabs is still valid, but now shared between 2 STG groups (hidden 1 and current 2)

Question: Can TST detect this problem somehow (by detecting that some tab are hidden? Like in this example, A tab is hidden while restoring C and B) and fix them by detaching tree from hidden A restored C and B, OR select STG group 1 first, then restore them there as before?

**Comment by piroor** [comment]
> Undo tabs from group 1 are restored to the wrong and current selected STG group 2.

It is a problem of STG side. Tabs B and C are restored in the Group 2 even if I disable TST.

> The tree of A,B,C tabs is still valid, but now shared between 2 STG groups (hidden 1 and current 2)

With these steps I've reproduced the result:

* A (in the Group 1, hidden)
  * B (restored, in the Group 2, shown)
    * C (restored, in the Group 2, shown)
* X (in the Group 2, shown)
  * Y (in the Group 2, shown)
    * Z (in the Group 2, shown)

Did you talk about this? Then I agree that this is unexpected result. TST has an option to prevent such a result: TST Options => "Tree Behavior" => "When visibility of tabs are changed by other addons" => "Fix up tree structure with visible tabs automatically" and if you choose this option TST should not attach the restored tab B and C to hidden tab A. I've introduced a fix with the commit e9ed1a0.

**Comment by byblo** [comment]
Yes this is the result i got. I switched now to your recommended option: "Fix up tree structure with visible tabs automatically"  and it seems working well. B,C are no more attached to hidden A.

**Comment by byblo** [comment]
Still having problems with STG (Could it be fixed with your commit? No idea how to try custom extensions on FF so I cant tell yet) Edit: Still giving problems also with new 3.5.15

Sometimes tabs are restored on some "random" places. Also in rare occasion, it even corrupt other trees on other groups that has nothing to do with the closed then restored tab. This seems to only happens while using the STG addon. If I disable STG then restart FF, all is working fine again. Closed tabs are restored properly on their trees.

Here is an example of problem that can happens when using STG + TST:
--------------------------------------------------------------------------------------------
(Note that I can reproduce this problem anytime, since I got saved the session. So I should be able to tell you if a commit works or not very easily)
![TST_restore_session_bug_step0](https://user-images.githubusercontent.com/5522524/88884947-e1b52200-d237-11ea-893c-4377b50bc767.png)
![TST_restore_session_bug_step1](https://user-images.githubusercontent.com/5522524/88884960-e5e13f80-d237-11ea-87fc-67a0c903b384.png)
![TST_restore_session_bug_step2](https://user-images.githubusercontent.com/5522524/88884969-e974c680-d237-11ea-9a4d-9c16d25e8573.png)

**Comment by piroor** [comment]
@byblo How to restore tabs on your case? Firefox's option "General" => " Startup" -> "Restore previous session", the application menu => "Restore Previous Session", or something other way?

And, is there any hidden tabs between existing tabs? You can show hidden tabs in the sidebar with following style declaration, so a screenshot with it will help me to understand what happens on your environment:

```css
tab-item.hidden {
  opacity: 0.35;
  position: relative;
  visibility: visible;
}
```

**Comment by piroor** [comment]
By the way, the latest development build (automated build) is available at https://github.com/piroor/treestyletab#development-builds

**Comment by byblo** [comment]
Yes I have the FF's setting "Restore previous session" enabled.

Actually, the change on version 3.5.15 fixed partially the problem it seems. But what i did was to close the tab on the previous example, then go to another group and close another tab, then come back to the first group and undo the first close, using Gesturefy addon with the function "Popup tabs closed recently", then returned to the second group and tried to restore the second tab. Only the first tab was restored correctly, while the second was again restored at the wrong position.

I will try tomorrow to bring you more details about this issue, and will tell you if there are hidden tabs between the tabs to undo.

**Comment by byblo** [comment]
I have tried with the hidden tabs visibles (tab-item.hidden ect...) and the lastest automated build version of TST.

There is no hidden tabs between the tabs closed then restored.

It seems the tabs just gets restored at some random position for some reason.

**Comment by byblo** [comment]
Here is a fresh FF profile where you can reproduce by yourself the problem: [FF_fresh_profile_for_STG_TST_Incompatibilty_bug.zip](https://github.com/piroor/treestyletab/files/5010260/FF_fresh_profile_for_STG_TST_Incompatibilty_bug.zip) (it has STG and TST extensions installed, without no change on settings, and some tabs from wikipedia)


Steps to reproduce the incompatibility bug:
- Select STG -> Group 2
- Close -> Wikipedia O tab
- Undo close tab


Note that I tried on current Firefox 78.0.2
With both TST official release and also tried with the lastest automated TST build. Results where almost the same.

Some preview pictures of what you should see with the provided profile:
![s1](https://user-images.githubusercontent.com/5522524/89100223-b7a95e80-d3f5-11ea-9929-652ed7081fd1.png)
![s2](https://user-images.githubusercontent.com/5522524/89100228-bc6e1280-d3f5-11ea-833a-5a1ca6e49031.png)
![s3](https://user-images.githubusercontent.com/5522524/89100230-c4c64d80-d3f5-11ea-84d0-7fc63fd6b5dd.png)
![s4](https://user-images.githubusercontent.com/5522524/89100234-c5f77a80-d3f5-11ea-8076-77d907bbea29.png)
![s5](https://user-images.githubusercontent.com/5522524/89100236-c6901100-d3f5-11ea-9316-7903caf35983.png)
![s6](https://user-images.githubusercontent.com/5522524/89100239-c7c13e00-d3f5-11ea-83ae-fa7d40ad72bc.png)
![s7](https://user-images.githubusercontent.com/5522524/89100240-c859d480-d3f5-11ea-8c8b-16669e673ecd.png)


Same preview with hidden tabs enabled:
![s3_hidden_tabs](https://user-images.githubusercontent.com/5522524/89100233-c55ee400-d3f5-11ea-8165-8f526ff450a2.png)
![s4_hidden_tabs](https://user-images.githubusercontent.com/5522524/89100235-c5f77a80-d3f5-11ea-9594-c9f811218a8a.png)
![s5_hidden_tabs](https://user-images.githubusercontent.com/5522524/89100238-c728a780-d3f5-11ea-898e-08702c608bc7.png)

**Comment by piroor** [comment]
Thank you for the testcase! It really helped my debugging!

After a research I've realized that restored hidden tabs can have wrong information about its position to be restored. I've introduced some changes with recent commits to fix that, so the problem should be fixed on the next release.

**Comment by byblo** [comment]
Unfortunately, there is still problems.

- On the debugging profile, the updated 3.5.17 fixed it.

- But on my real profile, I closed 2 tabs, on 2 different groups, and then undo them on their respective group. The result is the tabs are restored around the correct tab (sometimes before, sometimes after it), but curiously are not restored back into their respective tree. They are just restored as root tab and lost their tree attachement.

If you want to fix this problem at 100%, I recommend you use the debugging profile provided, install Gesturefy and use the popup with the recent closed tabs function, and then try to close some tabs, then restores them a bit randomly back on their own group. You should see there is still problems on positionning the restored tabs. Sometimes the tree still going crazy when you restore a lot of them.

edit: I did more tests on my main proffile. None of the restored tabs are returning to their tree. They are restored at the correct position but without any tree attachement. I tried to refresh the TST cache but without changes.

Anyway, the fix makes it much better already it seems. Thank you :)

edit2: Please ignore this post for now... After resetting ALL TST setting (Dev->Reset All) the fix seems working correctly again. I will try to find out which option from TST is failing the fix.

**Comment by byblo** [comment]
After checking, it seems the last fix (3.5.17) only works correctly when the TST's option 'Tree Behavior-->Keep Tree Structure including Hidden Tabs' is checked.

If using the other option: 'Fix up tree structure with visible tabs automatically', then the fix will not work correctly, as described in my previous post.

Is this expected?

**Comment by piroor** [comment]
Thanks, I've found a mistake on the latest version and the commit 50be5d3 should fix it.

However, confused tree after random restoration is still there. I've understood why the problem happens. Assume that there are 4 tabs:

* M
  * N
    * O
       * P

and you do following operations:

1. Close the tab O.
2. Close the tab N.
3. Restore the tab O.
4. Restore the tab N.

Initially the tab O has references information:

* next tab is P
* previous tab is N
* ancestor tabs are N and M
* child tab is P

Please remind that this information is stored to the session data.
At the step 1,  there are three remaining tabs:

* M
  * N
     * P

Now the tab N has references information:

* next tab is P
* previous tab is M
* parent tab is M
* child tab is P

Please remind that this information is stored to the session data.
At the step 2 there are two remaining tabs:

* M
   * P

At the step 3 the tab O is restored as;

* M
  * O
     * P

This restoration of O is based on the restored references information:

* next tab was P => P exists, so this can be a hint to place the restored tab.
* previous tab was N => N doesn't exist, this can't be a hint.
* ancestor tabs were N and M => only M exists, so O should be attached to M.
* child tab was P => P exists, so P should be attached to O.

At the step 4 the tab N is restored as;

* M
  * O
  * N
     * P

This restoration of N is based on the restored references information:

* next tab was P => P exists, so this can be a hint to place the restored tab.
* previous tab was M => M exists, so this can be a hint to place the restored tab.
* parent tab was M => M exists, so N should be attached to M.
* child tab was P => P exists, so P should be attached to N.

Now you need to pay attention to some points:

* The tab N should be placed after M, before P. Now both tabs exist but there is another tab O. Where should we place the tab N at? Currently TST respect the information "before P" prior to "after M", as the result the tab N is placed before P.
* The tab O was a child of the tab N, but now no one know the history - O was already restored as a child of M, and when N was closed O was not a child of N anymore. So there is no hint to restore the relation N => O => P.

To support such cases completely, we need to track and save all relation histories to each tab's session data - it will bloat the session database more so I think it is not a good idea.

On the other hand, if you restore tabs with Ctrl-Shift-T sequentially they will be restored as expected. I think this is a reasonable restriction balancing major usecases and robustness of the tree restoration.

**Comment by byblo** [comment]
I agree. There is no need to perfectly restore the tabs positions and trees on complex and multiples restorations. Usually we dont restore so many tabs, just one or two of the lastest closeds.

This said, I am still not sure which option i should use between: TST's option 'Tree Behavior-->Keep Tree Structure including Hidden Tabs' and 'Fix up tree structure with visible tabs automatically' with the STG addon.
I cannot really figure the differences.

But so far with the lastest official release TST 3.5.17, I could use the first one (Keep Tree Structure including Hidden Tabs) without any problem. Usually the lastest closed tabs are restored at the correct place, even after switching groups.

**Comment by byblo** [comment]
Still problems of restored tabs order with ''Tree Behavior-->Fix up tree structure with visible tabs automatically'.

But as said before, using the  'Tree Behavior-->Keep Tree Structure including Hidden Tabs' works correctly. I will keep using this setting from now.

**Comment by piroor** [comment]
@byblo After more testing I also saw tabs reopened in wrong position, and after a research I've understood that reference information of showing tabs were wrongly updated before showing of other tabs are completely done. The commit 7e2a17d should reduce such wrong updates.

**Comment by byblo** [comment]
Tested again this issue.

By closing some decent amount of tabs and restoring them in random order, it seems solved now for both 'Tree behavior' options.

Thank you again :)

**Comment by irvinm** [comment]
@byblo can you close this item?
