### ISSUE TITLE
Tab tree not readable for some Firefox themes

### ISSUE THREAD

**Issue by wagnerand** [piroor/treestyletab#2661]
## Short description

For some Firefox themes, the tab tree can become unreadable, if the theme background is not very solid.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install https://addons.mozilla.org/en-US/firefox/addon/firefox-alpenglow/
 4. Open a few more tabs.

## Expected result

The tree background is set to something that makes the tabs readable.

## Actual result

The tab tree is not very readable:

<img width="780" alt="theme" src="https://user-images.githubusercontent.com/873258/88810834-27c9a180-d1b6-11ea-98ec-40e2b5cb4b19.png">

## Environment

 * Platform (OS): macOS 10.15
 * Version of Firefox: 80.0b1 
 * Version (or revision) of Tree Style Tab: 3.5.14

**Comment by piroor** [comment]
I've introduced a fix for this, and you can apply the change with the user style sheet. Please see also: https://github.com/piroor/treestyletab/issues/2662#issuecomment-665728769

**Comment by wagnerand** [comment]
Thank you!

**Comment by irvinm** [comment]
@wagnerand can you close this item?
