### ISSUE TITLE
Background color of tabs has changed

### ISSUE THREAD

**Issue by HighCommander4** [piroor/treestyletab#2663]
The background color of all my tabs has just changed (become lighter), I think as a result of an update to 3.5.14.

Is this an intentional change?

**Comment by piroor** [comment]
Workaround stylesheet to deactivate browser theme colors:
https://github.com/piroor/treestyletab/issues/2662#issuecomment-665806899

Description of the background why I removed the option:
https://github.com/piroor/treestyletab/issues/2662#issuecomment-665815487

**Comment by irvinm** [comment]
@HighCommander4 can you close this item?

**Comment by HighCommander4** [comment]
I think the background color has reverted to the original in another update since I filed this issue.
