### ISSUE TITLE
Idea (SVG throbber CSS override) \ Github files missing?

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2664]
## Short description
I saw a post on reddit asking if it was possible to change the tab throbber and I thought it might be possible to simply override the throbber.svg via CSS (pointing the content to a public hosted location via url("public-location"\new.svg) in the 3 places mentioned in throbber.css.  I did have some challenges with this (I kind of expected that - maybe other CSS tied specifically to the Firefox throbber being used) and decided to try to load TST in FF developer edition (FF80) to try replacing the FILE throbber.svg directly to see if I could get that to work.

Problem:  When I tried to download the source from trunk or the archived source code ZIP of 3.5.15, there appears to be missing files which prevent loading the addon as a temporary addon.  Specifically, there are no files in the EXTLIB folder and the debug console for TST generates a long list of "Loading failed for the module ... /extlib/xxx.js".

Is this on purpose or am I doing something wrong?

If you have any initial thoughts on the throbber idea, that might be helpful else I will continue to play with that idea.  (Obviously I don't think this is something you would want to make a core feature)  I am just trying to get TST setup to debug properly for now.

Example free SVG throbber:  https://icons8.com/preloaders/en/circular/chasing-arrows/

**Comment by piroor** [comment]
> Problem: When I tried to download the source from trunk or the archived source code ZIP of 3.5.15, there appears to be missing files which prevent loading the addon as a temporary addon. Specifically, there are no files in the EXTLIB folder and the debug console for TST generates a long list of "Loading failed for the module ... /extlib/xxx.js".

The folder is blank by default and you need to run `make` to instantiate.
https://github.com/piroor/treestyletab/blob/trunk/README.md#development-builds
There are descriptions how to prepare a build environment under the folded section. Clicking on the line "It is not signed, so you need to load it by non-regular way. (Please click this section to see instructions.)" will expand them.

**Comment by piroor** [comment]
The most simple way to replace TST's throbber animation is: using a new SVG file created in the format same to https://github.com/piroor/treestyletab/blob/trunk/webextensions/sidebar/styles/throbber.svg as the mask.
This file has 60 cells for each animation frame, here is a rendered version with cell borders:
![throbber-01](https://user-images.githubusercontent.com/70062/88876443-3cfa0b00-d25e-11ea-900c-9b1fb8e12106.png)
If you need to use an SVG file in different format, you need to override declarations defined in the file https://github.com/piroor/treestyletab/blob/trunk/webextensions/sidebar/styles/throbber.css .

**Comment by irvinm** [comment]
Thank you for the guidance @piroor!
