### ISSUE TITLE
Dummy parent tabs immediately disappear and flatten the tree

### ISSUE THREAD

**Issue by hmijail** [piroor/treestyletab#2666]
## Short description
When a parent tab is closed and substituted by a dummy tab, the dummy disappears immediately and the children are promoted to the parent's level.

## Steps to reproduce

 1. Start Firefox 79b, 79 or 80b1 with clean profile.
 2. Install TST 3.5.14.
 3. Set TST's prefs: Tree Behavior - When a parent tab is closed or moved just as a solo tab - Recommended behavior for people who never use the native tab bar - Replace closed parent with a dummy tab and keep the tree
 4. Create 3 tabs in a window.
 5. Arrange the last 2 tabs as children of the first tab
```
A
\ - B
  - C
```
 6. Close the first tab

## Expected result
A is replaced by a dummy tab that keeps the tree structure

## Actual result
A is replaced by a dummy tab that seems to be out of place and immediately closed, resulting on B and C falling back to A's level.

![tst parent close](https://user-images.githubusercontent.com/4139546/88873952-3f119900-d261-11ea-8cd2-8d5ede2ce526.gif)

## Environment

 * Platform (OS): MacOS 10.15.6
 * Version of Firefox: 80.0b1 (also happens with 79 and 79b) 
 * Version (or revision) of Tree Style Tab: 3.5.14 (also happened with 3.5.13)

**Comment by piroor** [comment]
Thanks, the commit b10157e should fix this problem.

This looks to be a regression on a recent version, sorry...

**Comment by InsertUser** [comment]
I just came here to report this issue with:
TST version: 3.5.15
Firefox version: 79.0 (64-bit)
OS: Windows 10 (1909)

Is the commit mentioned above set to appear in version 3.5.16 ?

**Comment by irvinm** [comment]
@InsertUser, yes that change is in 3.5.16.

**Comment by irvinm** [comment]
@hmijail can you verify the fix and close this item?

**Comment by hmijail** [comment]
Fixed, thank you!
