### ISSUE TITLE
Tree style tab theme zoomed in

### ISSUE THREAD

**Issue by URRDURR** [piroor/treestyletab#2668]
## Short description

The background of the sidebar is an incredibly zoomed in version of the theme 

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install any theme

## Expected result

The theme appears as the sidebar background correctly proportioned

## Actual result

![image](https://user-images.githubusercontent.com/68181622/89001730-e3223100-d2af-11ea-8ca5-f2d88d36c40e.png)
![image](https://user-images.githubusercontent.com/68181622/89001750-f33a1080-d2af-11ea-91f5-891f7ff13a43.png)

Themes are disproportionate to the actual size

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 79.0
 * Version (or revision) of Tree Style Tab: 3.5.15

**Comment by piroor** [comment]
The change was intentionally introduced for a fix for #2662. Because there is less hint to determine how TST should repeat or zoom the background image, currently TST always zooms the background to cover the sidebar area.

Hmm, how should we treat both cases smartly?

**Comment by piroor** [comment]
There is a workaround, this style declaration will restore the old appearance:

```css:
:root,
#background {
  background-size: auto;
}
```

And I've introduced a change 8e867c4, it will prevent zooming of the background image if the aspect ratio of the image is 4:1 or more wider.

**Comment by piroor** [comment]
I've realized that some theme contains tiling information. After the commit 9d85e3f now TST respects "repeat", "repeat-y" and "no-repeat" tiling option given as a part of the theme.

**Comment by piroor** [comment]
I've found themes you tried:

https://addons.mozilla.org/firefox/addon/stripepaper/
https://addons.mozilla.org/firefox/addon/beach-stripe/

They sadly don't provide any tiling information, so even if you use the next release of TST the background image will be zoomed. But if the theme author add a tiling information to its manifest, it will be TST will respect it like as this screenshot:
![image](https://user-images.githubusercontent.com/70062/89046719-57300800-d388-11ea-9257-25ed26e88ec9.png)

This screenshot is based on a modified version of the theme, its manifest is:

```json
{
    "name": "Beach Stripe mod",
    "manifest_version": 2,
    "version": "1.0",
    "theme": {
        "images": {
            "theme_frame": "Beachstripe.png"
        },
        "colors": {
            "frame": "rgba(250, 216, 56, 1)",
            "tab_background_text": "rgba(82, 143, 208, 1)"
        },
        "properties": {
          "additional_backgrounds_tiling": ["repeat"]
        }
    }
}
```

The last section under `"properties"` is the added information.

**Comment by URRDURR** [comment]
How do i implement the workaround?

(and thank you for the help)

**Comment by piroor** [comment]
Steps I did:

1. Download the XPI package of the theme as a file.
2. Extract it as a zip archive. (Note: some archivers don't support the file, for example 7-zip. On Windows the standard "Compressed Folder" feature will be the best way.)
3. Add the `"properties"` section to the manifest.json.
4. Upload it to Mozilla Add-ons website to sign. You don't need to publish it on the website, instead you just choose to hide it on the website to make it just for yourself.

**Comment by irvinm** [comment]
Guys is there anything more to do with this item?  If not, can we close?

**Comment by irvinm** [comment]
@piroor I think this can be closed.  The topic can still be discussed if needed after it is closed.

**Comment by piroor** [comment]
OK, I close this.
