### ISSUE TITLE
[question] CSS

### ISSUE THREAD

**Issue by wvxwxvw** [piroor/treestyletab#2672]
Please tell me.
1. How can I remove (set my color) the edging of the "new tab" button.
2. Set the height of the additional elements of the "new tab" button. For example, "select a container".
3. Remove (set my color) the edging of the additional element. For example, "select a container".

I did not find it in the examples.

![2020 08 03_131029](https://user-images.githubusercontent.com/13194155/89172868-038e0c00-d58c-11ea-8254-0e94b5481f4e.png)

**Comment by piroor** [comment]
The inspector will help you to research available CSS selectors. You can research which CSS declaration produces the border with the inspector.
https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-inspect-the-sidebar
Screenshot: you'll see the declaration including `border-width` at the right pane.
![image](https://user-images.githubusercontent.com/70062/89185526-55a74f80-d5d5-11ea-8e2f-8c08986a4790.png)

For example:

```css
.after-tabs button {
  border: 0 none !important;
}
```

**Comment by wvxwxvw** [comment]
Awesomо!
![2020 08 03_174714](https://user-images.githubusercontent.com/13194155/89195519-89707e00-d5b1-11ea-9a88-ee2507312dd6.png)
Thanks.
