### ISSUE TITLE
Simple Tab Group Archiving and Backup function breaking TST trees

### ISSUE THREAD

**Issue by byblo** [piroor/treestyletab#2673]
Please note that I also opened a issue topic at the 'Simple Tab Groups' gitub, since I am not sure from which addon this can be fixed: https://github.com/Drive4ik/simple-tab-groups/issues/662

I am using both of addons: Simple Tab Groups & Tree Style Tab, which makes FF browser fantastic for who uses a lot of tabs everyday, without wasting time bookmarking everything all the time.

But I noticed that after restoring an archived group or restoring tabs from the backup json file, the trees that TST uses are all gone.

I guess remember it is the same with the STG bookmarks save, there is no tree structure using prefix characters like > and >> >>> ect...

Is there a compatiliby problem between those 2 addons or is it a bug?

If not bug, can TST (or STG) support those tree prefixes from STG to make both addons compatible on this topic, even by using some workaround?

**Comment by piroor** [comment]
I think this can't be done by TST side, because archive JSON files are generated by STG.  If STG saves "openerTabId" information to its archive and restores them, TST can restore tree structure for imported groups based on their "openerTabId".

**Comment by byblo** [comment]
A new version of STG addon was released, with this change:
STG 4.5.2, "Try to fix conflict with "Tree-style tab" add-on #601"

On this new STG version, when archiving a group, it seems to save the trees somehow, but once restoring the same group from his archive, the tabs order and the tree are totally incorrect. Not sure if this new problem is related to the STG or the TST addon.

**Comment by byblo** [comment]
A new version of STG addon was released, with this change:
STG 4.5.2, "Try to fix conflict with "Tree-style tab" add-on #601"

On this new STG version, when archiving a group, it seems to save the trees somehow, but once restoring the same group from his archive, the tabs order and the tree are totally incorrect. Not sure if this new problem is related to the STG or the TST addon.

**Comment by byblo** [comment]
Fixed with STG 4.5.5
