### ISSUE TITLE
Did v3.5.17 accidentally break the dark mode theming from 3.5.16?

### ISSUE THREAD

**Issue by shaneutt** [piroor/treestyletab#2674]
## Short description

It would appear that `v3.5.17` which was updated today August 3rd 2020 has broken dark mode theming at least on my system? I've lost the dark mode themes that use to be available in the add-on preferences in `v3.5.16`.

## Environment

 * Platform (OS): Linux x86_64
 * Version of Firefox: 79.0
 * Version (or revision) of Tree Style Tab: 3.5.17

**Comment by piroor** [comment]
Did you talk about the theme "Plain Dark" ? It was removed at 3.5.16 but you can restore it with use user stylesheet:
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#restore-old-built-in-themes

**Comment by shaneutt** [comment]
Understood, thanks for the link I'll follow those docs and work on getting mine back :+1:

**Comment by shaneutt** [comment]
Documentation was great, thank you I've got things restored. I appreciate your quick response here :+1: 

Please sign up for Github sponsorship, I would be happy to sponsor your work as I've used your addon for ages :vulcan_salute:
