### ISSUE TITLE
3.5.17 no longer works with dark mode on Linux

### ISSUE THREAD

**Issue by phoe** [piroor/treestyletab#2676]
## Short description

Tree Style tab no longer adheres to my dark Firefox/system theme after updating to 3.5.17.

## Environment

 * Platform (OS): debian sid
 * Version of Firefox: 76.0.1
 * Version (or revision) of Tree Style Tab: 3.5.17

![Zrzut ekranu z 2020-08-04 08-43-21](https://user-images.githubusercontent.com/15045546/89261568-9089a180-d62e-11ea-91f1-487d2e593ff1.png)

**Comment by taebox** [comment]
I mean, I don't like it, but there was a notice on the update notes.
https://github.com/piroor/treestyletab/wiki/Plain-Dark-theme-%28patch-for-the-theme-%22Plain%22%29

If that is not your issue, maybe you just need to switch to Plain theme to get what you want.

**Comment by phoe** [comment]
Switching to Plain was not enough, but with this user style, the dark mode is back. Thanks!
