### ISSUE TITLE
Never open an un-prompted tab on update

### ISSUE THREAD

**Issue by ssokolow** [piroor/treestyletab#2677]
I just received an update to Tree Style Tab 3.5.17 which switched me away from what I was working on to an unwanted `moz-extension://68847fa8-1e6e-4301-8c06-31791597e7d6/resources/startup.html`

Please never do this. It's bad enough that everything reflows when an un-prompted update causes the TST sidebar to temporarily go away.

(A few months ago, when HTTPS Everywhere and Cookie AutoDelete added such functionality within days of each other, I actually [submitted a request](https://github.com/mozilla/addons/issues/1182) to AMO to forbid this behaviour in their rules for extension developers. They said they'd consider it.)

If you must notify of new features or new optional permissions, please add a dismissable notification header/footer to the TST sidebar. (More generally, by adding some kind of indicator to the primary UI element, such as the browser action in an extension like uMatrix or DownloadStar or the page action in CanvasBlocker.)

**In the mean time,** please tell me how to forcibly disable that from happening again. You neglected to put a "never do this again" option in the unwanted tab and the TST preferences are so numerous that I just don't have time to search for it myself.

**Comment by piroor** [comment]
Just a workaround: Setting 
`notifiedFeaturesVersion` to 9999 or something large number via TST Options => "Development" => "All Configs" => "notifiedFeaturesVersion" will suppress the notification.

**Comment by ssokolow** [comment]
Thanks.

**Comment by piroor** [comment]
I've introduced a desktop notification as the startup message instead of tab. It doesn't steal tab focus until it is clicked. Is this acceptable by the policy?
![image](https://user-images.githubusercontent.com/70062/89321264-ae521780-d6bd-11ea-9786-3d38f5c9552b.png)

**Comment by ssokolow** [comment]
As long as it uses an `onClicked` or `onButtonClicked` rather than an `onClosed` handler, I'm perfectly happy with that.

From what I remember, the specification for the desktop notifications protocol that Firefox feeds those into on Linux says that applications must not assume that a notification host will reliably emit the system-level version of `onClosed`.

...and, even if that weren't an issue, some desktops, like KDE, move notifications into a "missed notifications" tray after a while, and I'm not sure how that would interact with `onClosed`. I wouldn't want the tab uncontrollably appearing after a delay **or** having a tab pop up unexpectedly when I click the "dismiss all" button on my missed notifications tray.

**Comment by piroor** [comment]
The notification never open any tab, on `notifications.onClosed`. I'll spread this change to other my addons.

**Comment by irvinm** [comment]
@ssokolow this has been in since 3.5.20.  Can you close out this issue?
