### ISSUE TITLE
Problems with shift-clicking after active tab was changed via keyboard

### ISSUE THREAD

**Issue by FichteFoll** [piroor/treestyletab#2684]
## Short description

Shift-clicking behaves erratically after the active tab has changed from outside of TST's control, e.g. through switching tabs with ctrl+tab or closing a tab with ctrl+w.

## Steps to reproduce

 1. Have TST and MTH.
 2. Open a couple tabs.
 3. Click on a tab.
 4. Close the tab with ctrl+w.
 5. Shift-click on a different tab.

*Case 2*

3) Click on a tab.
4) Click on a different tab.
5) Switch back to the previous tab with ctrl+tab or ctrl+pageup/down.
6) Shift-click on a different tab.

![2020-08-11_16-52-18](https://user-images.githubusercontent.com/931051/89913275-d37de300-dbf3-11ea-9498-591ca12773ee.gif) ![2020-08-11_16-52-47](https://user-images.githubusercontent.com/931051/89913281-d4af1000-dbf3-11ea-8b39-6b9b8d0a1fb4.gif)

## Expected result

Selects all tabs from the active to the clicked tab.

## Actual result

Seems to start the selection from the tab that was previously clicked on. If the previously clicked tab was closed, selects no tabs.

Can be recovered from by clicking on the already active tab and then trying to shift-click again.

## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: 79
 * Version (or revision) of Tree Style Tab:  

(I've experienced this problem for a long time, years probably, but haven't bothered to create an issue. Also note that the problem does not occcur with Multiple Tab Handler, but I don't need any of the features it provides over TST natively, outside of this bug.)

**Comment by piroor** [comment]
Thanks, this should be fixed with 9e68e1b.

**Comment by FichteFoll** [comment]
Confirmed, thanks
