### ISSUE TITLE
TST close box has different behavior than Firefox close box

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2685]
## Short description
Standard Firefox close box behavior is such that if I "down-click" on the close box, then move the mouse (even outside the close box), then as long as the mouse returns over the close box for the "up-click" then the tab is closed.

For TST, if I "down-click" then move my mouse at all, then the close tab action is cancelled.  [This basically means for any accidental mouse movement between the down and up click results in the action being cancelled by accident ... this reminds me of the older issue reported around accidentally dragging tabs by a small amount which would detach them from the current window.]

## Steps to reproduce

 1. Start Firefox with clean profile
 2. Install TST
 3. "Down-click" on a Firefox tab
 4. Move the mouse around or even outside the close box
5. Return to the close box and "Up-click"
6. Notice that the tab is closed
7. Repeat process with TST and see that the tab will not be closed

## Expected result
I would expect similar behaviors between the different close boxes.

## Actual result
Firefox closes the tabs if the requirements are met.  TST has a different behavior.

## Environment

 * Platform (OS): Windows 2004 (x64)
 * Version of Firefox: 79.0
 * Version (or revision) of Tree Style Tab: 3.5.21

**Comment by piroor** [comment]
Thanks, the commit 20dd7e1d81f457cb57f1eb4231636db3a6a7b1d2 should fix this. Now closebox should work same as the native one.

**Comment by irvinm** [comment]
@piroor I pulled down the development build and the behavior is not quite right.

Standard close box:

- Down & Up click on box:  Close tab
- Down click on box, Up click off box (but still on tab):  Tab remains
- Down click on box, Up click off box (and off tab):  Tab remains
- Down click on box, move mouse (on or off box), Up click on box:  Close tab

TST close box:

- Down & Up click on box:  Close tab
- Down click on box, Up click off box (but still on tab):  Close tab
- Down click on box, Up click off box (and off tab):  Tab remains
- Down click on box, move mouse (on or off box), Up click on box:  Close tab

The 2nd case is different.  TST should cancel the action if the "Up Click" is performed off of the close box.

**Comment by piroor** [comment]
Thank you for detailed feedback! The commit dc60c88 should fix the second case.

**Comment by irvinm** [comment]
The functional behavior is good now.  Everything functionally works as expected.  

I originally wrote up the text below as a question\bug, but after some investigation everything is working consistently.  The issue I saw was rooted in the difference of how TST changes the color of the "x" and background differently than Firefox on a "down click".  (TST goes "darker" whereas FF goes "lighter")

**QUESTION: Is there any way to override the formatting of the close box on a mouse down event via CSS?**  (I could not find the code that modifies the close box on a down click by reviewing drag-and-drop.js or mouse-event-listener.js)

------------------------------

**Standard close box:**

![1](https://user-images.githubusercontent.com/979729/90533849-0c174280-e147-11ea-9dfe-ef1d453532d0.jpg) Default
![2](https://user-images.githubusercontent.com/979729/90533848-0b7eac00-e147-11ea-8b9c-4d86f0b6b37f.jpg) Hovered over close box
![3](https://user-images.githubusercontent.com/979729/90533847-0b7eac00-e147-11ea-852b-bbc724a22bc3.jpg) Down click on close box

**General behavior:**

Default has no background to the close box.  Hover keeps white "X" and adds a background.  Down click keeps white "X" and makes background a little brighter.

**Click and mouse move behavior:**
- Starting with down click position (white "X" with brighter background)
- Move mouse outside of close box -> styling goes back to "Default" formatting (white "X" with no background)
- Move mouse back over close box -> styling goes back to down click formatting (white "X" with brighter background)

**TST close box:**

![4](https://user-images.githubusercontent.com/979729/90535344-cd828780-e148-11ea-92fc-cbd79e93d817.jpg) Default
![5](https://user-images.githubusercontent.com/979729/90535363-d1160e80-e148-11ea-94aa-62af5ed50ea5.jpg) Hovered over close box
![6](https://user-images.githubusercontent.com/979729/90535376-d410ff00-e148-11ea-95cd-1c5e6a6e2c43.jpg) Down click on close box

**General behavior:**

Default has no background to the close box.  Hover keeps white "X" and adds a background.  Down click keeps darkens the "X" and makes background a little darker.  (Last step a little different, but ok)

**Adding this little bit of CSS to help show the issue:**

```
/*
   Change color (hover) of closebox
   https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#colored-background-for-closebox-on-hover
*/
tab-item tab-closebox:hover::before {
  background: red !important;
  opacity: 1 !important; 
}
```

We now get:
![7](https://user-images.githubusercontent.com/979729/90538178-30c1e900-e14c-11ea-9c20-4e41407be932.jpg) Default
![8](https://user-images.githubusercontent.com/979729/90538188-33bcd980-e14c-11ea-8f4d-c2242ddd144b.jpg) Hover
![9](https://user-images.githubusercontent.com/979729/90538198-37e8f700-e14c-11ea-9ff5-e66cd2fcb3d7.jpg) Down click

**Problem**

... no problem.  I kept seeing the "down click" state when testing this issue and that is actually correct.  My brain kept telling me it should have been the "hover" state, but that isn't correct when down clicking and moving on and off the close box.

**Comment by irvinm** [comment]
@piroor just wanted to make sure you saw my last comment on this issue.  Obviously not an issue, but just a question.

**Comment by piroor** [comment]
Sorry I missed the difference. With the commit d98ec1c closeboxes will be shown similar to Firefox's native one.
