### ISSUE TITLE
Twisty and closebox contents are not visible with "No decoration" theme.

### ISSUE THREAD

**Issue by aqbot-kenw** [piroor/treestyletab#2688]
## Short description
Twisty and closebox contents are not visible with "No decoration" theme, despite specifying color, opacity, etc.  This broke with one of the last few updates.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Select "no decoration" theme
 4. Apply custom styles for everything, for example:

```

#background {
  background-size: auto;
  background: black;
  color: white !important;
}

.tab {
      height: 32px;
      border: solid 1px #88888855;
      background:  #482030ff !important;
      color: lightblue !important;
      font-size: 0.9em !important;
      opacity: 1 !important;

}

.tab.highlighted {
  background: #774488ff !important;
  color: #ffffff !important;
//  font-size: 1.2em !important;
  border-top: 3px solid #8888ff;
  border-bottom: 3px solid #8888ff;
}

.tab.discarded {
  background:  #282010ff !important;
  opacity: 0.9 !important;
}

tab-item tab-counter {
  color: #ffffff;
  font-size: 1.1em !important;
  padding-right: 4px;
}

tab-item tab-twisty {
  position: relative;
  border-bottom:2px solid white;
  margin: 2px;
  background: #884488;
  opacity: 100%;
  z-index: 100 !important;

}

tab-item tab-favicon {
  //border: 1px solid white !important;
  margin:3px;
}

.tab.unread .label {
  font-style: italic !important;
}

/* Add private browsing indicator per tab */
/**/
.tab.private-browsing .label:before {
  content: "\1f453\a0";
}

.closebox {
   display: none;
}
 
.tab:hover tab-closebox {
  display: block;
  content: "X";
  background: #ff000078;
  color: #ffffff !important;
  opacity: 1 !important;

}


.tab .label {
  padding-left: 3px;
}

.tab:hover {
  background: #7733aaff !important;
  opacity: 1;
}

/* hide scrollbar */
#tabbar { scrollbar-width: none; }

/* cancel spaces for macOS overlay scrollbar */
:root.platform-mac #tabbar:dir(rtl).overflow .tab:not(.pinned) {
  padding-left: 0;
}
:root.platform-mac #tabbar:dir(ltr).overflow .tab:not(.pinned) {
  padding-right: 0;
}

```
## Expected result

Twisty is white, X is closebox when hovering over tab is white

## Actual result

Boxes for twisty and closebox (when hovering only) appear, but contents do not.

## Environment

 * Platform (OS): Ubuntu 16.04 and Windows 10
 * Version of Firefox: 79.0 
 * Version (or revision) of Tree Style Tab: 3.5.22

**Comment by piroor** [comment]
This looks not a recent regression. I've tried old versions of TST and closebox had no color at least on TST 2.8.7.

**Comment by piroor** [comment]
With the commit be73393 now those UI elements have a default color. You can apply this change locally:

```css
:root {
  --tab-text-regular: ButtonText;
}
```

**Comment by aqbot-kenw** [comment]
Thank you.  Apologies for the incorrect info on previous versions working.  I think I might have previously been using one of the removed  themes as a base instead of "no decoration".

Just for the record in case someone else finds this in the future,  I ended up using `HighlightText` instead of `ButtonText` so the twisty and closebox 'X' would be light.
```
:root {
  --tab-text-regular: HighlightText;
}
```

**Comment by piroor** [comment]
I think that `HighlightText` looks not good for major environment, for example on my Windows 10 (non-Dark theme) it is shown with white color and buttons looks hard to be seen. How about `--tab-text-regular:  -moz-dialogtext` ? I hope it shows better color than `ButtonText` for you.

**Comment by aqbot-kenw** [comment]
I can barely even see twisty arrows (etc) with `-moz-dialogtext`, it's a very dark gray.

On my Ubuntu system at least, HighlightText is not crazy bright white and it fits in nicely with the rest of my styles.
Regardless, it would be ideal if you could set these things with `tab-item tab-twisty`.

**Comment by irvinm** [comment]
@aqbot-kenw is there anything more on this issue?  If not, can you close it out?

**Comment by aqbot-kenw** [comment]
Closing.
