### ISSUE TITLE
Closing the last tab switches to the one above it instead of a previously visited one

### ISSUE THREAD

**Issue by mustaqimM** [piroor/treestyletab#2690]
## Short description
When closing a tab, TST attempts to switch to the one below it, if there isn't one, it switches to the one above the one just closed. It should rather switch to the last tab actually used.
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Switch to a tab that is above the one you wish to close
 4. Now change to a tab that is last on the main tree; Close it.
 5. TST will switch to a tab above this closed tab.

## Expected result
Switch to the previous tab after closing the last tab. Don't open an unloaded/unrelated tab.

## Actual result
TST switches to to a tab above the closed one if there isn't a tab below it.
Please see the linked [video](https://streamable.com/va3zhl). The last visited tab is the `ListAdapter` one. I switch to the last tab in the main tree, which is the `Addons` page and close it. Instead of switching back to `ListAdapter`, it opens an unloaded one above it.

## Environment

 * Platform (OS): Linux
 * Version of Firefox:  `81.0a1 - Nightly`
 * Version (or revision) of Tree Style Tab:  `3.5.22`

**Comment by piroor** [comment]
Firefox itself doesn't have such a behavior except some special cases: when a tab is opened from a parent tab and closed the child tab immediately, if you never activate other tabs. TST tries to simulate the exception behavior, so, did you talk about any bug around it?

Or, did you talk about a request about a new feature not implemented in both TST and Firefox itself? There are some addons for the purpose, for example https://addons.mozilla.org/firefox/addon/select-after-closing-current/ , and if you see compatibility issue with a combination of such addons and TST, I'll try to solve the conflict.

**Comment by mustaqimM** [comment]
Thanks for linking to that addon, it does exactly what I wanted: To go to the last accessed tab after closing a tab

And thank you so much for your work on this great addon, please close this issue if you wish

**Comment by piroor** [comment]
OK I've closed this. Please open any new issue for compatibility problems freely.
