### ISSUE TITLE
[feature request] Keep scrolling position while closing tabs

### ISSUE THREAD

**Issue by dstd** [piroor/treestyletab#2691]
## Steps to reproduce
 1. Open multiple tabs so that they occupy the screen height * 2 (call it tabs #1...#100)
 2. Scroll to the middle of the tabs list, so that some tabs are above visible part of the list and some are below
 3. Try to close tabs sequentially, starting from the middle of the list (tab #50 and further), by clicking on [X] without moving a pointer
 4. While there are some tabs below the visible area all is fine, when a tab (#50, 51, 52, 53...) is closed the next one is moving on it place, so that I can continue without moving of the pointer.
 5. When the tail of the list becomes visible, a closing of a tab (e.g. tab #87) will result into moving up the scroll position. So on the next click on [X] instead of closing tab #65 I will close tab #49

## Expected result
Behave like Firefox's tab bar: while the pointer is over the tab bar the scrolling position is not changing, leaving empty space after the last tab, and adjusting itself when the pointer leaves the tab bar.

## Environment

 * Platform (OS): MacOS
 * Version of Firefox: 79.0
 * Version (or revision) of Tree Style Tab: 3.5.23

**Comment by piroor** [comment]
OK, I've implemented the behavior with the commit 666d658

**Comment by dstd** [comment]
Thank you. Now it's excellent
