### ISSUE TITLE
Can't hide tooltips using suggested code from wiki

### ISSUE THREAD

**Issue by sssceo** [piroor/treestyletab#2693]
## Short description
Tooltips are not hidden after adding the following to [profile folder]/chrome/userChrome.css

#aHTMLTooltip {
  display: none !important
}

## Steps to reproduce

 1. Started Firefox with clean profile.
 2. Installed TST.
 3. Created [profile folder]/chrome/userChrome.css with suggested code snippet from wiki. 
 4. Save
 5. Restart Firefox
 6. Tooltips still showing when hovering over a tab with a cut off title. 

## Expected result
No tooltips in TST sidebar. 

## Actual result
No change from normal tooltip behavior. 

## Environment

 * Platform (OS):                                                MacOS 10.15.6
 * Version of Firefox:                                          79.0, 80.0
 * Version (or revision) of Tree Style Tab:         3.5.23 (2020.8.26)

**Comment by irvinm** [comment]
Try it with a ";" at the end of the statement:

```
#aHTMLTooltip {
   display: none !important;
}
```

**Comment by piroor** [comment]
Did you activate `toolkit.legacyUserProfileCustomizations.stylesheets` to `true` via `about:config` ?

**Comment by piroor** [comment]
After investigation I've realized that the style declaration you tried won't work as expected on e10s enabled environment. Instead you need to apply "display:none" to the tooltip for remote processes:

```css
#remoteBrowserTooltip {
  display: none !important
}
```

Of course you need to activate userChrome.css at first with the config above.

**Comment by sssceo** [comment]
Wow, you are awesome for responding so quickly. Tooltips gone, thank you!

**Comment by sssceo** [comment]
Also, just to confirm, the solution was changing to #remoteBrowserTooltip as you said, and not the earlier suggestions. Thanks again.

**Comment by irvinm** [comment]
@sssceo can you close this issue?

**Comment by sssceo** [comment]
Thanks for closing this for me. I am a brand new github user and I will know to do it next time.
