### ISSUE TITLE
"Some changes may affect to your use case. Please click here to see explanations"

### ISSUE THREAD

**Issue by dequis** [piroor/treestyletab#2700]
## Short description

Just got an update to 3.5.24 and it said "Some changes may affect to your use case. Please click here to see explanations"

But when clicking that, I got resources/startup.html with the generic "first use" text.

The notification made it seem like there was something concrete that needed my attention, but sent me nowhere, and I don't know if there's anything that needs my attention or not.

## Steps to reproduce

 1. Update TST
 2. See message
 3. Click message

## Expected result

Explanations, as promised by the notification.

A generic page with a changelog / a link to the changelog would have been fine too, although I can't spot anything that obviously affects my use case in the last release

## Actual result

![The startup page](https://user-images.githubusercontent.com/94108/91633187-946ad280-e9e6-11ea-904d-82f877f3c7f9.png)

## Environment

 * Platform (OS): linux
 * Version of Firefox: 80.0
 * Version (or revision) of Tree Style Tab: 3.5.24

(btw - the git tag for that is "2.5.24", sounds like a typo?)

**Comment by dequis** [comment]
Oh so I see the context for this one is https://github.com/piroor/treestyletab/issues/2677

Honestly, the randomly opened startup.html was slightly annoying but not much. I didn't really care. It promised nothing and delivered nothing. I do agree that changing that to a notification was a move in the correct direction.

I think the main problem is the wording - the notification promises changes that need my attention, but is still shown for every update.

I'd suggest including the changelog (or a link to it) in startup.html and then either:

* Make the message more targeted, detect when users had settings that were deleted or skip the message for minor updates. This is harder, less reliable and https://xkcd.com/1172/ applies.
* Change the wording to something along the lines "Tree style tab has been updated. Click here to read the changelog"
* Don't show the notification at all (or until the next major release).

As a user who's been very happy with TST for years and never really had any problems because of updates, I'd be happiest with the last one. But I understand the desire to get people to be aware of changes - especially with such a large user base.

Maybe a checkbox in startup.html for "show notifications on updates" that can be toggled in settings too?

**Comment by piroor** [comment]
You right. Sorry I didn't maintain update guidance well... As a workaround I've changed the notification popup to open the version history page on AMO: https://addons.mozilla.org/firefox/addon/tree-style-tab/versions/

**Comment by dequis** [comment]
Sure, that works for me. Thanks!

**Comment by irvinm** [comment]
@dequis will you close this item?

**Comment by dequis** [comment]
I have no idea, am I supposed to? No idea what the workflow is like here or why @piroor labeled the issue instead of closing it.

**Comment by piroor** [comment]
I usually use labels because issues closed by me cannot be reopened by the reporter. I hope issues to be closed by the reporter if possible.

**Comment by dequis** [comment]
Oh, that makes sense. Sure then.
