### ISSUE TITLE
Revert tab closing behaviour to 3.5.23

### ISSUE THREAD

**Issue by pupkinvaska** [piroor/treestyletab#2703]
Don't like this recent update -
>  3.5.24 (2020.8.28): Simulate "lock scroll position of the tab bar while middle tabs are closed via mouse operations" behavior of Firefox's native tab bar.

Closing tabs in the middle of the tab bar became very slow and uncomfortable. Which option reverts the changes? Had to roll back to 3.5.23

 * Platform (OS): win 10 
 * Version of Firefox: 80.0 x64
 * Version (or revision) of Tree Style Tab: 3.5.24

**Comment by piroor** [comment]
You can deactivate this behavior with TST options => Development => All Configs => uncheck simulateLockTabSizing. Could you try it and report the result?

**Comment by pupkinvaska** [comment]
@piroor it worked for me, thanks

**Comment by piroor** [comment]
I've introduced some changes about the implementation of the spacer. Now it is implemented with the method same to Firefox's native tab bar for optimization. Could you try the development build?
https://github.com/piroor/treestyletab#development-builds

**Comment by pupkinvaska** [comment]
@piroor tested dev build on 68.12.0esr x64. Behaviour the same as on 3.5.24, but tab closing became a lot faster with 100-200 opened tabs.
Minor bug (only 68.12.0esr): when I close any tab while the tab bar is scrolled to the very bottom, the scroll bar jumps up a little

**Comment by piroor** [comment]
Thank you for testing!

> Behaviour the same as on 3.5.24, but tab closing became a lot faster with 100-200 opened tabs.

This is the expected result. I hope the change help people who suffered from same slowness.

> when I close any tab while the tab bar is scrolled to the very bottom, the scroll bar jumps up a little

I think this is the expected behavior. You'll see similar result on Firefox's native tab bar when there are too many tabs and scrolled the tab bar to the rightmost position.

**Comment by garymoon** [comment]
I completely understand why locked scroll position would be more desirable and performant, but I rely on the collapsing behavior to make it friction-less when closing a long backlog of top-level tabs. I was worried this wouldn't be optional and/or the option would be difficult to find (it was a bit, I was searching for a "scroll"-related preference, but this issue took care of that).

Thank you so much for making what's clearly a major improvement optional for those of us stuck in our ways, and thank you for the marvel that is Tree Style Tab :blue_heart: :blue_heart: :blue_heart:

**Comment by irvinm** [comment]
@pupkinvaska can you close this item unless there is more to discuss?
