### ISSUE TITLE
[Idea] TST CSS syntax coloring (CodeMirror)

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2704]
## Description
More recently, CSS usage in TST seems to be an more important for more people due to the change in built-in styles and the increased size of synchronized CSS data possible.

In thinking about working with CSS, I think about how working with CSS in [Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/) is easy to use due to the syntax highlighting, color patches which represent color values (like "rgba(255, 255, 255, 0.3)" or "#4B4B96") and easy ways to see when lines are commented out or not.

_**Stylus CSS Editor (Default theme):**_

![2020-08-31_9-37-54](https://user-images.githubusercontent.com/979729/91732521-58667780-eb76-11ea-9598-8f57ac19c17a.jpg)

**_Clip of my TST CSS inside of Stylus (Cobalt theme):_**

![2020-08-31_10-54-09](https://user-images.githubusercontent.com/979729/91734081-70d79180-eb78-11ea-8806-bdf3fd838bb1.jpg)

## Suggestion
It looks like Stylus had been using an open source library that provides syntax coloring (MIT License) called [CodeMirror](https://codemirror.net/) (Github:  https://github.com/codemirror/CodeMirror) ["CodeMirror is a versatile text editor implemented in JavaScript for the browser."]  It provides a variety of "modes" and one if obviously for CSS.

```
Basic Usage

The easiest way to use CodeMirror is to simply load the script and style sheet found under lib/ in the distribution, plus a mode script from one of the mode/ directories. For example:

<script src="lib/codemirror.js"></script>
<link rel="stylesheet" href="lib/codemirror.css">
<script src="mode/javascript/javascript.js"></script>
```
## Conclusion
CodeMirror might not be the best solution or the one you might want to do (if at all) but thought it might be worth a discussion.

If you don't want to entertain the idea, please feel free to close this item.

**Comment by piroor** [comment]
I've created a branch for an experiment. It looks working but there are some problems, so we need to do more things to use such a rich text editor...

**Comment by irvinm** [comment]
If it helps, here is the edit.html that Stylus uses:  https://github.com/openstyles/stylus/blob/master/edit.html

It obviously includes more than what is needed here (although things like themes, beautify, color pickers, and collapsible sections are all nice to have for CSS editors\highlighters).

I think syntax highlighting and color swatches by themselves would be the best improvements.

**Comment by silverwings15** [comment]
having this implemented would be lovely. on a similar note, would it be okay to have a thread dedicated to discussing CSS tweaks and customization?

**Comment by piroor** [comment]
I've merged changes activating CodeMirror for the user styles editor to the trunk. Now it is available by default, and I hope the development build to be tested more by people. https://github.com/piroor/treestyletab#development-builds

@mimecry I've activated the "Discussions" feature for this repository. I hope it to be used like a forum: https://github.com/piroor/treestyletab/discussions

**Comment by piroor** [comment]
I've also activated the color picker in the CodeMirror editor.

**Comment by silverwings15** [comment]
thank you very much for the Discussions tab

**Comment by irvinm** [comment]
@piroor I played around with the new editor and it looks great.  The lines numbers, syntax highlighting, color picker, and color swatches are all going to help people I think when editing their CSS.  I didn't see any problems with my limited testing.

My only comment might be around the theme and I could see people wanting to use different themes or to be able to tweak certain items by themselves.  Either way, the highlighting is still a hug improvement as it is.

OS Light mode:
![image](https://user-images.githubusercontent.com/979729/104815288-9b518080-57e1-11eb-85b0-92b4dfda00ef.png)

OS Dark mode:
![image](https://user-images.githubusercontent.com/979729/104815292-a4425200-57e1-11eb-8116-9932832f10ed.png)

Dark theme I use in Stylus: (Theme "blackboard")
![image](https://user-images.githubusercontent.com/979729/104815414-6bef4380-57e2-11eb-836b-b44542204250.png)

**Comment by piroor** [comment]
OK, I've added the theme chooser UI.

**Comment by irvinm** [comment]
@piroor the theme picker looks and works great!

By the way, I also really like how the text editor for the CSS now remembers the view port size that was last used between firefox sessions.

All great usability enhancements!
