### ISSUE TITLE
memory blow up with latest version

### ISSUE THREAD

**Issue by alreadydone** [piroor/treestyletab#2705]
## Short description
Today I restarted Firefox and recovered the session with 500+ tab in 3 windows. Without doing anything else, I found that Firefox ate up 4GB+ memory and still hadn't finished loading (high CPU usage) in a few minutes. (Normally, it takes a few dozen seconds for the tree to appear.) I suspected it was due to the Tree Style Tab addon and found that it was indeed updated 4 days ago; likely the update caused the problem. I then switched to Vertical Tabs Reloaded, and it only took 1.5GB to finish loading (very quickly). 

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 80.0
 * Version (or revision) of Tree Style Tab: 3.5.24

**Comment by piroor** [comment]
I saw another report #2703 similar to this started with 3.5.24. Could you try stop auto-update of TST and downgrade TST to 3.5.23?

**Comment by piroor** [comment]
3.5.23 is downloadable via https://addons.mozilla.org/firefox/addon/tree-style-tab/versions/

**Comment by piroor** [comment]
I've introduced some changes about the implementation of the spacer. Now it is implemented with the method same to Firefox's native tab bar for optimization. Could you try the development build?
https://github.com/piroor/treestyletab#development-builds

**Comment by alreadydone** [comment]
I installed the development build and memory usage is now moderate. Thank you! Feel free to close this.

**Comment by piroor** [comment]
I close this for now. Please add new comments or open new issue if you see the problem again.
