### ISSUE TITLE
Hourglass and white flashes when loading tabs and panels!

### ISSUE THREAD

**Issue by wvxwxvw** [piroor/treestyletab#2707]
Firefox 78 esr, TST 3.5.26

You should not go along with every unsuccessful idea of Firefox developers.
If I marked use animation in the TST settings, it means I want to use it.
I disabled animation in the browser for a completely different reason. In particular, to neutralize other unsuccessful decisions of developers, with an ugly address bar and increased resource consumption when loading multiple pages, and TST has nothing to do with this.
It's disgusting to look at it, I'll go back to the previous version until you come up with something.

The fact that a spinning point can trigger epilepsy worries them. And the fact that the ugly clock and flashing white flashes, with a dark browser theme, cause irritation even for non-epileptics, they do not worries? Am I the only one who sees this as progressive insanity?

**Comment by piroor** [comment]
> And the fact that the ugly clock and flashing white flashes, with a dark browser theme, cause irritation even for non-epileptics, they do not worries?

As an emergency response, I've deactivate 3.5.26 on AMO and re-activate 3.5.25 as the latest version. I apologize that the change is too premature for a public release: I just disabled CSS transitions and animations but I also had to reduce such annoying flashing more aggressively.

**Comment by piroor** [comment]
>  If I marked use animation in the TST settings, it means I want to use it.

I had not imagined a combination of configs: "animation effects reduced by the platform" and "activated animation effects on TST".

It looks that TST's "animation" config must have three states: force-on (activate animation effects even if they are reduced by the platform config), soft-on (current behavior of animation=true), and off (current behavior of animation=false). But radio buttons (or select box) for these states looks too complex...

**Comment by piroor** [comment]
I've added a new expert option: Enable animations regardless "reduce animations" platform settings. I hope it should help you...

**Comment by wvxwxvw** [comment]
OK, thank you. I'll wait for the signed version.

**Comment by wvxwxvw** [comment]
Installed unsigned. Yes, it helped me regarding tabs.

All the same, the panel blinks white when loading, this is much worse for epileptics than some dots there. On Firefox will be sued for such neglect for epileptics. )

**Comment by wvxwxvw** [comment]
del Wrong place.
