### ISSUE TITLE
TST keeps loading forever

### ISSUE THREAD

**Issue by kunaltyagi** [piroor/treestyletab#2710]
## Short description

TST can't finish loading

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST
 3. Open some tabs
 4. Open TST in sidebar
 5. Work normally. Sometimes, TST will auto-reload
 6. If you're unlucky, TST will keep loading forever

![tst-reloading](https://user-images.githubusercontent.com/2657068/92353778-01cfdf00-f11c-11ea-9a74-175b28d24fb1.png)

## Environment

 * Platform (OS): Ubuntu 20.04
 * Version of Firefox:  80.0.1
 * Version (or revision) of Tree Style Tab:  3.5.25

**Comment by piroor** [comment]
It looks to happen when TST is updated. Is this reproducible? Could you try to investigate reproducibility of it with an old version downloadable at https://addons.mozilla.org/firefox/addon/tree-style-tab/versions/ ?

**Comment by kunaltyagi** [comment]
When I disable and enable the plugin, the problem goes away. I've seen this issue (for sure) for a few weeks so this isn't a new problem. Beyond that, it'd be hard for me to replicate (no knowledge of JS or side-loading plugins in FF)

**Comment by piroor** [comment]
When the problem happens again, could you try close and reopen the sidebar instead of disabling and enabling? If TST works correctly, something happens around connection between the sidebar and the background process. If TST still doesn't work, the background process looks broken.

**Comment by kunaltyagi** [comment]
I tried closing the sidebar and opening it again when the issue appeared: there was no difference. I had to disable and re-enable the plugin.

**Comment by piroor** [comment]
Thanks! It means that something happens on TST's background page. Could you check the error console for TST when the problem happens? (You need to use the remote debugger: 
https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-collect-debug-logs-of-tst )
If you see no error in the console, please try with enabled "Debug mode" again. If the mode is enabled, more detailed logs will be reported in the console.

**Comment by kunaltyagi** [comment]
Got it. Will record logs when the issue pops up again.

BTW, the error console shows the following errors:
```js
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    sendContentTabId moz-extension://2839aa59-3fd2-404f-b91f-b010ebeb83d9/reloadmatic.js:463
reloadmatic.js:463:25
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 4 background.js:1930
    send moz-extension://e6e296df-895c-4147-8897-565785783a90/background.js:1930
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    restartAlarm moz-extension://2839aa59-3fd2-404f-b91f-b010ebeb83d9/reloadmatic.js:94
```

**Comment by irvinm** [comment]
@kunaltyagi any new updates?

**Comment by kunaltyagi** [comment]
None. I don't know if TST has been updated. If it has, then I've not seen this issue reproduced

**Comment by irvinm** [comment]
@kunaltyagi may I suggest closing this item for now then?  If it comes up again, you can re-open it.

**Comment by uncomfyhalomacro** [comment]
it happens again 
![image](https://github.com/piroor/treestyletab/assets/66054069/3f53bc9a-7977-447f-9308-c70bfd6d7d5b)

**LOGS**:

[console-export-2024-3-13_20-32-36.txt](https://github.com/piroor/treestyletab/files/14587681/console-export-2024-3-13_20-32-36.txt)
[console-export-2024-3-13_20-31-38.txt](https://github.com/piroor/treestyletab/files/14587683/console-export-2024-3-13_20-31-38.txt)

**Comment by piroor** [comment]
The error in the console looks no related to the initialization failure problem. Could you try disabling and re-enabling TST to reload it? @uncomfyhalomacro
