### ISSUE TITLE
group-tab.html doesn't always load from discarded state

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2711]
## Short description
When loading group-tab.html from a discarded state, it appears group-tab.js doesn't initialize\load properly a small percentage of the time and results in a blank page and the title of the tab either being the proper title or sometimes based on the UUID.  (Ex: moz-extension://5697a9ef-6dd3-4e85-a8ad-1cab77dad96e...)

- Reloading the tab manually works 100% of the time after initial failure (Can't reproduce it continuing to hit Ctrl+R over and over)
- Discarding the tab (Ex: Auto Tab Discard keyboard shortcut) then trying to active it can reproduce it
- The number of tabs under the group tab doesn't seem to matter.  (Have seen with 0, 10 or 100 children)

![2020-09-07_9-39-53](https://user-images.githubusercontent.com/979729/92393967-b521df00-f0ee-11ea-9350-7f01c8c54e4a.jpg)

## Steps to reproduce

 1. Start Firefox with clean profile
 2. Install TST
 3. Create group tab
 4. ~~Create children to group tab~~ - No children are needed.  I was able to reproduce with no children.
5. Discard group tab (or restart browser)
6. Click on group tab to bring out of discarded state
7. Notice that some % of loads results in a blank page
8. Reload page manually as work around

## Expected result
group-tab.html should always load or possibly try to "reload" if some initialization fails after a period of time.

## Actual result
A blank page is displayed a small percentage of time.

I have seen this issue for a while but just got around to writing it up, so I don't think it is related to recent changes.  I can reproduce it fairly easily and am happy to help debug with maybe a little guidance ... if that helps or if you can't produce.

Obviously this is not a critical issue.

## Environment

 * Platform (OS): Windows 10 (2004)
 * Version of Firefox: FF 80.0.1
 * Version (or revision) of Tree Style Tab: 3.5.26

**Comment by piroor** [comment]
I've realized that `tabs.executeScript()` sometimes fails for restoring discarded tabs, so I've added some error handling for the case with the commit 3b9e558. I hope it solve the problem...

**Comment by irvinm** [comment]
I tried 3.5.28 this morning and tried restoring about 60 group tabs (using auto tab discard to manually discard some of them and I also restarted FF as well) and I would say about 10 times the tab still did not load properly.  In each of the 10 cases, the tab loads fine after a manual reload.

**Comment by piroor** [comment]
I've introduced more changes about group tabs initialization with the commit 746559387d5f4529f9e671c7ba3af00239216489. Could you try the new development build?

**Comment by irvinm** [comment]
Thanks.  I loaded up FF82 in a sandbox and then tried to make sure I could reproduce it with the current version of TST and couldn't.  Before giving up (or trying something else with my current profile) I decided to bring over my TST CSS into the sandbox and I was able to reproduce it in just a few attempts.

I will try to narrow down what it might be in the CSS and provide an update.

**Comment by irvinm** [comment]
Update:  I've been playing with the CSS over the past hour and during that process, I ended up trying different CSS items but eventually was able to reproduce the issue (albeit with a low frequency rate) regardless of the CSS ... including no CSS.

The frequency of failure in the sandbox is much lower than my main profile.  (FF81 & ~500 tabs)

I did decide to still try out the development version and probably tried about 100 restore from discarded scenarios and they all loaded one way or the other.  I did have one group tab with some children to see if that behaved any differently and one thing I did notice was some "drawing" or "redrawing" issues but 98% of the time the result looked fine.  (It looked like maybe the tabs were been drawn and updated)  However, in 2 situations the page ended up looking like this:

![2020-09-30_20-58-49](https://user-images.githubusercontent.com/979729/94754814-5142ad00-0360-11eb-8447-61e542cd837f.jpg)

Versus the expected view:

![2020-09-30_20-59-11](https://user-images.githubusercontent.com/979729/94754827-5acc1500-0360-11eb-942a-9bed6b3b3d3a.jpg)

I think the real test will be in my main profile with a larger number of tabs.

**Comment by piroor** [comment]
Sorry I missed the duplicated tree contents problem. It is a regression of recent changes, and I've introduced some fixes about it. Could you try a newer development build?

**Comment by irvinm** [comment]
I have only seen the duplicated tree problem with that last development build ... never before that.  I'll try out the new dev build later today.

**Comment by irvinm** [comment]
The dev build looks good.  I wasn't able to reproduce any issues using it in a sandbox.  I will test it more in the next version in my main profile.

**Comment by irvinm** [comment]
Everything is looking good so far.  I will monitor and report back any additional issues.
