### ISSUE TITLE
Tab throbber color turns black even with a dark theme

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#2713]
## Short description
The tab loading animation turns black even if I am using a dark theme, making it hard to see.
It is a new regression since v3.5.27. v3.5.26 had some changes regarding the throbber but it didn't have this issue.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST v3.5.27. 
 3. No additional TST CSS is modified.
 4. Enable `Enable animation effects` in TST.
 5. Make sure Reduce Motion is **not** enabled, OS or Firefox.
 6. Set the theme colors as following:
   OS: dark (optional)
   Firefox: dark
 7. Load a slow page, e.g. https://www.reddit.com/, so you can see more loading animation cycles.

## Expected result
The throbber color should be easy to distinguish, just like v3.5.25.

## Actual result
Screencast: https://giant.gfycat.com/FearfulNastyAcouchi.webm
The throbber color turns black after 1 animation cycle.

## Affected theme combinations
OS: Light
Firefox: Dark, Firefox Alpenglow

OS: Dark
Firefox: Default, Dark, Firefox Alpenglow

** Firefox Alpenglow is a new built-in theme, currently Nightly only.

## Environment

 * Platform (OS): Windows 10 1909
 * Version of Firefox:  Firefox 80.0.1, Nightly 2020-09-08
 * Version (or revision) of Tree Style Tab:  3.5.27

**Comment by Fanolian** [comment]
Actually it looks like something is masking over the default throbber.

**Comment by piroor** [comment]
Thanks, I've realized that the black moving dot rendered from the background image unexpectedly covered the white background color. The commit fc6f3ce should fix this.

**Comment by Fanolian** [comment]
Thanks. Confirm fixed in 3.5.27.10854.
