### ISSUE TITLE
[request] bookmarkFolder_label

### ISSUE THREAD

**Issue by wvxwxvw** [piroor/treestyletab#2715]
Please add %YY% to the list of templates bookmarkFolder_label.

**Comment by piroor** [comment]
Does it mean the lower two digits of the year? (2019 => 19)

**Comment by wvxwxvw** [comment]
Yes.

**Comment by piroor** [comment]
OK, now `%SHORT_YEAR%` is available as a two digits with the commit 3104549.

**Comment by wvxwxvw** [comment]
Thanks!
