### ISSUE TITLE
Opening many children tabs in quick succession confuses later tab selection

### ISSUE THREAD

**Issue by farnoy** [piroor/treestyletab#2716]
## Short description

When I open multiple child tabs in quick succession, selection between them by clicking on the tree selects the wrong tab.

## Steps to reproduce

This isn't perfectly consistent (since it's probably a race condition), but my steps are:

1. Visit old.reddit.com
2. Open another tab as sibling to the previous one
3. Switch back to reddit
2. In quick succession, middle click (to open as children) on two separate `[l+c]` links on some thread
3. 4 children tabs are spawned
5. Select the sibling tab from step 2
6. TST selects one of the children tabs spawned from reddit.com

To visualize, after all these steps I end up with a tree like this
![image](https://user-images.githubusercontent.com/345808/92757956-8de93d00-f38e-11ea-9ed0-4254682951ed.png)

## Expected result

Selecting each tab in the resulting tree makes the appropriate tab active.

## Actual result

From the above screenshot, pressing on "about:memory" selects "Debugging - Setup" and vice versa. Tab positions and order looks fine to me, but the action of selecting a tab gets misattributed to a different tab. This **does not affect closing** of a tab, either through middle-mouse or the X button.

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 80.0.1 stable
 * Version (or revision) of Tree Style Tab: 3.5.27

**Comment by piroor** [comment]
I've realized that `[l+c]` links appear only when I installed [Reddit Enhancement Suite](https://addons.mozilla.org/firefox/addon/reddit-enhancement-suite/). Anyway I've successfully reproduced the problem. Hmm...

**Comment by piroor** [comment]
With the latest development build this problem doesn't appear. I think it was a regression triggered by the change a4da430, and fixed by a recent commit  1d7741cd1c4fd2c2cc7e164f249572a511727520 .

**Comment by farnoy** [comment]
Sorry about the `[l+c]` thing, I honestly thought that's just an old reddit feature. Can confirm it's fixed as of 3.5.28.
