### ISSUE TITLE
Scroll Bar

### ISSUE THREAD

**Issue by BlindSquirrelDog** [piroor/treestyletab#2718]
I typically have a LOT of tabs open.  Tree Style Tab makes it much easier to get around, but a scroll bar would sure speed things up.<!--

**Comment by irvinm** [comment]
@BlindSquirrelDog what do you mean a scroll bar would sure speed things up?  Of course TST has a scroll bar where there are more tabs than can be displayed.  

There are even a ton of CSS items on the wiki discussing different ways to change them or their behavior.

https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#scrollbar

**Comment by piroor** [comment]
TST sidebar has a vertical scrollbar as @irvinm mentioned. It may be invisible on macOS by default, and you need to change a setting of macOS itself to show scrollbars: https://osxdaily.com/2011/08/03/show-scroll-bars-mac-os-x-lion/

**Comment by irvinm** [comment]
@piroor I think this one can be closed.
