### ISSUE TITLE
[Nightly only] Unable to open about:processes after bug 1652785 is fixed

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#2719]
## Short description
*about:processes* (Process Manager) is a built-in tool currently available only in Nightly. Recently *about:processes* stops working when TST sidebar is shown.
Mozregression shows that [Bug 1652785 - Show websites loaded in process in about:processes (title, favicon)](https://bugzilla.mozilla.org/show_bug.cgi?id=1652785) is the culprit.

\* Not to be confused with *about:performance* (Task Manager) that is available in Firefox Stable.
\* A news piece about *about:processes*: https://www.ghacks.net/2020/05/11/this-is-firefoxs-upcoming-process-manager-aboutprocesses/
## Steps to reproduce

 1. Start Nightly 2020-09-07 or later with clean profile.
 2. Install TST.
 3. Make sure TST sidebar is shown.
 4. Navigate to *about:processes*.

## Expected result
After a short pause, *about:processes* should show CPU, memory, etc. information about various Nightly processes.

## Actual result
No information is shown. In *Browser Console* there is an error message after the short pause:

> Uncaught (in promise) 
> Exception { name: "NS_ERROR_FAILURE", message: "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIURI.host]", result: 2147500037, filename: "chrome://global/content/aboutProcesses.js", lineNumber: 208, columnNumber: 0, data: null, stack: "_getDOMWindows/windows<@chrome://global/content/aboutProcesses.js:208:1\n_getDOMWindows@chrome://global/content/aboutProcesses.js:204:35\n_getProcessDelta@chrome://global/content/aboutProcesses.js:280:21\ngetCounters@chrome://global/content/aboutProcesses.js:348:22\n_updateDisplay@chrome://global/content/aboutProcesses.js:904:26\nupdate@chrome://global/content/aboutProcesses.js:891:16\n", location: XPCWrappedNative_NoHelper }
>
> aboutProcesses.js:208

![image](https://user-images.githubusercontent.com/771216/93206190-9aed9e00-f78b-11ea-965d-461adb4129d4.png)

## Notes
1. The issues only occurs when TST sidebar is shown. Bookmark, History sidebars are not affected.
2. *about:processes* works when TST sidebar is hidden, even if TST is still enabled.
3. I tried some older versions of TST (3.3.6+) and they all have the same issue.

## Regression range
Last good Nightly: 2020-09-06
First bad Nightly: 2020-09-07
pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=5a77c0b857048d46fe4bced46b2234b49dcc84a2&tochange=ca131344e7fcf46f50e09bea63141d2578f18b7b

Further bisecting autoland builds:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=0a3de0138b450f7ed71d2ef371c2e8e602a2acaf&tochange=b8af21c6e6780dbca280115d97aa3ae91e7614f4

## Environment

 * Platform (OS): Windows 10 1909
 * Version of Firefox:  Nightly 2020-09-07 or later
 * Version (or revision) of Tree Style Tab: 3.5.27

**Comment by piroor** [comment]
Is this already reported to bugzilla.mozilla.org? I think it need to be fixed by Firefox side...

**Comment by Fanolian** [comment]
Not yet. I'll do it later.

**Comment by Fanolian** [comment]
Filed: [Bug 1665099 - Unable to open about:processes when Tree Style Tab sidebar is enabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1665099).

**Comment by piroor** [comment]
Thanks!

**Comment by Fanolian** [comment]
Fixed in 2020-09-19 Nightly.
