### ISSUE TITLE
Adjusting height of tab bar (tab strip)

### ISSUE THREAD

**Issue by ffuser34** [piroor/treestyletab#272]
Hello, I have lost the ability to adjust the height of the tab bar (tab strip) in the top position by moving the cursor over the border of the tab bar and dragging the border up or down. Not sure how this happened. I've tried reinstalling the newest version as well as installing older versions but that doesn't restore this functionality. 
How do I restore it? 
Thanks.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
