### ISSUE TITLE
Radio buttons not changed to default after resetting options

### ISSUE THREAD

**Issue by alexandra-martin** [piroor/treestyletab#2722]
## Short description
After changing settings and resetting them back to default, options with radio buttons will change back, but will be displayed like they weren't changed back.
## Steps to reproduce

 1. Start Firefox with a clean profile.
 2. Install TST.
 3. Go to TST's "Options"/"Preferences" from about:addons.
 4. Select or change an option that has a radio button.
 5. Click "Reset All" from "Development".

## Expected result
Options are changed back to original settings.

## Actual result
Options are changed, but radio buttons displays are not.

## Environment

 * Platform (OS): Windows 10 x64bit, MacOS 10.14
 * Version of Firefox:  Release 81.0, Beta 82.0b2, Nightly 83.0a1 (2020-09-22)
 * Version (or revision) of Tree Style Tab:  3.5.27
 
After a page refresh or browser restart radio buttons are displayed correctly.
Not reproduced with settings with checkboxes.

![1](https://user-images.githubusercontent.com/54401091/94008866-55912800-fdac-11ea-87ca-48b066275809.gif)

**Comment by piroor** [comment]
Thanks! The problem should be fixed with recent commits https://github.com/piroor/webextensions-lib-options/commit/1fcfb3b25026aedf2ae1891c44513c8ae9f9bbf9 and 534960d

**Comment by piroor** [comment]
I close this because TST 3.5.31 is already available. (If you still see this problem, add comments please.)
