### ISSUE TITLE
[Request] Setup GitHub sponsorship / donations

### ISSUE THREAD

**Issue by happy-dude** [piroor/treestyletab#2723]
Hey piroor, I have used this addon for ~10 years and I absolutely love it.
I would like the chance to donate and support your projects 👍 

More about GitHub sponsors:
* https://github.com/sponsors/
* https://docs.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/about-github-sponsors
* https://docs.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/sponsoring-an-open-source-contributor
* https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

It could be any other donation platform that works for you!

**Comment by happy-dude** [comment]
Ah, I spotted https://github.com/piroor/treestyletab/issues/761 and I respect your decision.

If that is the case, feel free to close and wish you the best regardless!

**Comment by piroor** [comment]
Thanks, I'm glad just with those feelings 😃 

Even if I got sponsored, this project will die when Firefox become dead (because TST depends on Firefox specific WebExtensions APIs), so please recommend Firefox to people around you! 👍
