### ISSUE TITLE
Closing parent tab messes with which tab to focus after closing current tab

### ISSUE THREAD

**Issue by pintassilgo** [piroor/treestyletab#2724]
## Setup:
Tree Behavior
- When the current tab is closed as last child
(×) Focus to the previous tab in the tree
[×] Move focus back (...)

- When a parent tab is closed or moved just as a solo tab
Custom 
Promote the first child as the new parent always (select this in all the three menulists).

## Steps
1. Load a webpage with links. Click to open some links in new tabs. These new tabs will be children of current tab.
2. Select next tab, ie. the first child of current tab.
3. Close it (I use Ctrl+W).
The next tab will be focused. It was the second child of the tree, now it's the first since the previous first was closed. You can repeat this while there's a child. When there's only one child, when you close it the parent will be focused because of what we defined in setup. That's right.

The bug is that if we close the parent tab in the middle of the process. Like:
1. Repeat the 3 steps above.
2. Close the parent tab. The first child will be promoted as parent.
3. Select the new first child and close it. The next child should be focused, but instead the parent tab gets focus. Parent tab should only gets focus if there is no children, but that's not the case.

TST 3.5.27.

**Comment by piroor** [comment]
Thanks! This should be fixed with the commit 229eedc.
