### ISSUE TITLE
[feature request] Snippet to resize pinned tabs

### ISSUE THREAD

**Issue by mkalinski** [piroor/treestyletab#2725]
## Short description

I find pinned tabs rendered in the sidebar way too small and hard to click. An ideal solution would be to be able to adjust the size with CSS.

There are instructions on the wiki about resizing regular tabs: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#change-tab-height-236-2389

They don't work for pinned tabs, though (`tab-item.pinned` doesn't seem to react to `height` or `--tab-size` changes). The only discussion of styling pinned tabs that I was able to find was #1704, but it's closed as outdated.

I would greatly appreciate if there were up to date information on how to style pinned tabs with CSS on the wiki.

## Steps to reproduce

1. Go to https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules

## Expected result

Information about how to change size of pinned tabs, similar to https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#change-tab-height-236-2389

## Actual result

No mention of resizing pinned tabs; snippet for regular tabs doesn't work in their case.

**Comment by piroor** [comment]
You can inspect the DOM tree of the sidebar with the debugger: https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-inspect-the-sidebar It will help you to try your custom CSS codes.

TST has an expert option to deactivate "faviconizeation" of pinned tabs: TST Options => Turn "Unlock Expert Options" checked => Turn "Show pinned tabs only with their icon" under the "Appearance" section unchecked, then pinned tabs will be shown with the full width of the sidebar. On the other hand, changing the aspect ratio of faviconized pinned tabs is impossible on current versions of TST. TST's faviconized pinned tabs are layed out based on a condition: their width and height are same. If you want to show they with double width, we need to modify calculation logic around their layout: https://github.com/piroor/treestyletab/blob/b7a91d9d8a8b27ee0f5ffb74096792121792bdb9/webextensions/sidebar/pinned-tabs.js#L54

**Comment by piroor** [comment]
If you hope to simply enlarge pinned tabs, it can be done with a secret option `faviconizedTabScale`. It is 1.75 by default, means "width = height = favicon-size * 1.75", so it will be 28px if favicons are shown with 16px width/height.

**Comment by mkalinski** [comment]
`faviconizedTabScale` is sufficient for my needs, thanks! Perhaps it would be worth it to mention it in the wiki by the tab resizing snippet?

I found one very minor issue with the "All Configs" section in the preferences page. When a decimal is put as a value for `faviconizedTabScale`, the input lights up in red as if its an error, even though it's not and even the default value is a decimal. It seems the input is programmed to only show integers as valid.

![Screenshot](https://user-images.githubusercontent.com/959502/94456239-c2912d00-01b3-11eb-8f6e-4a2c43ecd45c.png)

**Comment by piroor** [comment]
I've realized that decimal numeric value (like `1.01`) is detected as invalid value for a numeric input field by default, and we need to set `step` for such cases. With recent commits ,now such values won't be reported as invalid. Thank you for the report!

**Comment by piroor** [comment]
TST 3.5.31 is now available, so I close this.

**Comment by belonesox** [comment]
> `faviconizedTabScale` is sufficient for my needs, thanks! Perhaps it would be worth it to mention it in the wiki by the tab resizing snippet?
…
> ![Screenshot](https://user-images.githubusercontent.com/959502/94456239-c2912d00-01b3-11eb-8f6e-4a2c43ecd45c.png)

Sorry, how to change `faviconizedTabScale` in 2024 on TST 4.0.15? I did not see such options on the extension preferences page…

**Comment by piroor** [comment]
@belonesox TST options => Development => All Configs => expand the list, then you'll see the option.

**Comment by belonesox** [comment]
> @belonesox TST options => Development => All Configs => expand the list, then you'll see the option.

Thank you! But should it work?  I tried to change it up and down and see no difference… 

![image](https://github.com/piroor/treestyletab/assets/1609739/d89d7ea2-93a5-426b-885e-e4eeb0494dc1)

**Comment by piroor** [comment]
@belonesox TST does not apply the change dynamically, so you need to reopen the sidebar.
