### ISSUE TITLE
[feature request] How to change sidebar style and debug it 

### ISSUE THREAD

**Issue by zhanghb1994** [piroor/treestyletab#2726]
**Short description**

This is a very useful extension for me, and I don't like the sidebar style. I wanna change the style myself, but I don't know which file I should change. How do I know which file controls the sidebar style? Can we find it the same way we find page element styles?

**Comment by irvinm** [comment]
You might want to check out the wiki as it has a lot of CSS snippets to change TST.

https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules

**Comment by irvinm** [comment]
To inspect the sidebar itself, you can read how to do that here: https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-inspect-the-sidebar

**Comment by zhanghb1994** [comment]
Very very thanks
