### ISSUE TITLE
[feature request] TST sidebar/window title

### ISSUE THREAD

**Issue by mreppen** [piroor/treestyletab#2732]
#  Description
This feature request is in relation to https://github.com/Lej77/tree-style-tab-in-separate-window/issues/9

I try to summarize this post: https://github.com/Lej77/tree-style-tab-in-separate-window/issues/9#issuecomment-702959783

The linked extension breaks out the TST view into a separate window. Currently this window is titled "Mozilla Firefox" instead of something specific to TST (to distinguish it from a regular FF window). This can be set by `titlePreface`, but if set by multiple extensions, they conflict.

The author of that extension, @Lej77, suggested another solution: Let the sidebar title be changed by something like this: `ext+treestyletab:tabbar?windowId=3&title=Sidebar`. However, this would require TST support.

I quote the last paragraph of the [above linked post](https://github.com/Lej77/tree-style-tab-in-separate-window/issues/9#issuecomment-702959783
) for a more detailed description:

> Another approach would be to change the sidebar tab's title. I don't think it is possible to inject javascript into extension pages so this would probably require that a tiny bit of code is added to Tree Style Tab. This shouldn't be a problem however since code to support this extension has been added before. Currently this extension opens the Tree Style Tab's sidebar page by opening the URL ext+treestyletab:tabbar?windowId=3, I'm thinking that we could just open the URL ext+treestyletab:tabbar?windowId=3&title=Sidebar instead and then Tree Style Tab would read the URL and set the title. I can't think of any disadvantages for this second approach so it is the one I would prefer to implement.

**Comment by piroor** [comment]
OK, I've added a new URL parameter `title`. TST now respects it as the window title. @Lej77 Could you use the parameter?

**Comment by Lej77** [comment]
@piroor Thanks! I have released version `5.2` of my [Tree Style Tab in Separate Window](https://addons.mozilla.org/firefox/addon/tst-in-separate-window) extension with support for the new URL parameter. I tested it with a development build of Tree Style Tab and everything seems to work!

**Comment by mreppen** [comment]
@piroor @Lej77 Sorry for pinging you both, but: Thanks for making my everyday browsing life better!

This is working for me, so I close.
