### ISSUE TITLE
Tree Style Tab stopped working for Firefox v81.x

### ISSUE THREAD

**Issue by ldm1417** [piroor/treestyletab#2734]
Hello,

It seems the Tree Style Tab AddOn stopped working for Firefox v81.x. Is this true?

Here is how it looks (blank):

![1](https://user-images.githubusercontent.com/42472229/95246187-d1638980-081c-11eb-872f-5247fc1f2e6f.jpg)

How to fix it?

Thank you!

**Comment by irvinm** [comment]
No, it works. 😄 

Four things I would try:

1. Restart Firefox
2. Toggle the side bar off and on
3. Enable\disable TST itself
4. Uninstall\reinstall TST itself

**Comment by ldm1417** [comment]
I’ve re-installed the TST, closed and re-launched the Firefox, toggled the sidebar, disabled all the rest add ons, the result is the same – the sidebar under the TST is blank. What are the next steps?

**Comment by irvinm** [comment]
Can you create a new profile (it can be temporary) and just add TST to that profile to see if that works?  (about:profiles)

**Comment by ldm1417** [comment]
In the new profile, it works... so, what's the next step? 
In the old profile, I wiped the Firefox cache, but this did not help... 
I'd prefer to stay with the old profile because of the rest of the addons...

**Comment by irvinm** [comment]
@piroor might have some better suggestions, but my one last suggestion might be to:

- Uninstall TST
- Restart Firefox
- Reinstall TST

I believe if you remove and then reinstall in the same session it reuses what you already had.  It sounds like Firefox itself is fine as you can get another profile to work.  

It is also possible (I guess) that there is a conflict with another addon, but maybe something to look at next.  [You could try disabling (not uninstall) all of your other addons to see if things change]

Finally, you could also check the console to see if there are any clear errors being reported there around TST.

**Comment by ldm1417** [comment]
"Finally, you could also check the console to see if there are any clear errors being reported there around TST" - how can I do so?

**Comment by irvinm** [comment]
https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-inspect-the-background-page-master-process

**Comment by piroor** [comment]
@ldm1417  I'm using TST on Firefox 81.0.1 on Windows 10, and it works as expected for me. I think a debug log is required to research, collected via the method @irvinm linked to.

**Comment by irvinm** [comment]
@ldm1417 do you have any additional updates or could you close this item?

**Comment by irvinm** [comment]
@piroor I think this can be closed.  No response in over a month and TST is obviously working on FF81.

**Comment by piroor** [comment]
I close this for now as expired.
