### ISSUE TITLE
Keep getting warning of closing multiple tabs when I close parent tab

### ISSUE THREAD

**Issue by KDE5FAN** [piroor/treestyletab#2736]
I'm using the most current version of FF (81.0) & the addon (October 5, 2020).  When I try to close a parent tab with open children tabs, I get a warning that has a check box saying something like: "Warn me anymore if I close multiple tabs".  No matter how many times I uncheck that box, I still get the warning.  

I found a setting to turn this off deep in the settings and turning that off stops this from coming up when I close the tab.  

So it seems like the prompt/warning box isn't changing the settings when you de-select the box.

**Comment by irvinm** [comment]
https://github.com/piroor/treestyletab/issues/2735

**Comment by piroor** [comment]
TST 3.5.32 including this fix is now available, so I close this.
