### ISSUE TITLE
Tab Switch Gets Stuck in Click and Drag Mode

### ISSUE THREAD

**Issue by neostar63** [piroor/treestyletab#2738]
## Short description

When switching between tabs occasionally the tab selection will become stuck like I am clicking and dragging, yet I am not holding down the mouse button. This seems to be most easily repeatable when switching between a new empty tab and a tab that has been navigated to a site. This usually causes the tab to be opened in a new browser instance on accident. 

## Steps to reproduce

Steps to reproduce:
1. Open a tab and navigate to a site
2. Open another tab and leave it at the default new tab
3. Alternate between selecting the tabs.

## Expected result

Tabs switch cleaning

## Actual result

Tab is stuck as if in click and drag mode

## Environment

 * Platform (OS): Debian 10 using Gnome
 * Version of Firefox: 81.0.1
 * Version (or revision) of Tree Style Tab: 3.5.32

**Comment by neostar63** [comment]
I will also add that browser.tabs.allowTabDetach was set to true in about:config

I have set it to false. TST still lets me tear the tabs but I have not been able to recreate the issue since disabling it a few moments ago. I will leave it disabled and report back if I see any erroneous tab tearing.

**Comment by piroor** [comment]
TST Options => Drag and Drop => choose "Move Entire Tree / Do nothing" for the action "Drag", then tabs won't be detached from the window by dragging.

**Comment by neostar63** [comment]
This issue presents itself in a way where the mouse click event is locked as if I am still pressing the button down but I am not. When I click somewhere else outside of the TST area it results in a new browser window being spawned with that tab as its content. As you can imagine when moving at normal speed random browser windows popping up when switching tabs is an inconvenience.

I did see that option but I do occasionally to be able to drag and drop the entire tree. As of this moment disabling tab tearing in about:config has stopped the accidental tearing of tabs while allowing me to intentionally drag and drop with TST.

Thank you for attention to this issue and the great browser addon.

**Comment by piroor** [comment]
> This issue presents itself in a way where the mouse click event is locked as if I am still pressing the button down but I am not. 

It looks to be triggered by heavily/slowly processed mouse events for me. On my environment, similar problem sometimes happens when the PC becomes slow by something other heavy tasks. Moreover, there may be something un-noticed problems caused by zombie drag session happend around Firefox's IPC (Inter-Process Communication) mechanism.
