### ISSUE TITLE
Feature Request: Close Group Shortcut

### ISSUE THREAD

**Issue by rgvcorley** [piroor/treestyletab#274]
Apologies if this is not the place to submit a feature request!

I would like to be able to close a tab and all of it's children with a simple Ctrl + click (on x icon) or Shift or something.

At the moment it requires a right click

**Comment by piroor** [comment]
Firefox already have [very large number of keyboard shortcuts](https://support.mozilla.org/kb/keyboard-shortcuts-perform-firefox-tasks-quickly), and other addons also provide their own keyboard shortcuts, I cannot find out safe combinations for my features. So I gave up and decided to provide only [APIs for other addons](http://piro.sakura.ne.jp/xul/_treestyletab.html.en#api). Please use generic addons to customize keyboard shortcuts which can define custom actions based on scripts. Sorry.

**Comment by FichteFoll** [comment]
Actually, this wouldn't be a stand-alone key binding but a mouse event combined with a keyboard modifier key. You can control that, can't you?
