### ISSUE TITLE
Can't scroll through tabs with mouse wheel when dragging and dropping a tab

### ISSUE THREAD

**Issue by sbobbo** [piroor/treestyletab#2744]
## Short description

I would like to be scroll through the tree while dragging a tab to a new location. Currently, the mouse wheel does nothing when dragging a tab. The TST Mouse Wheel addon does not add this functionality as far as I can tell.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open enough tabs that the tab sidebar can scroll up and down
 4.  Select and hold onto a tab with left-mouse
 5. Use mouse wheel in attempt to scroll the tab sidebar

## Expected result

The tab sidebar scrolls per mouse wheel input

## Actual result

Nothing Happens

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox:  82.0
 * Version (or revision) of Tree Style Tab:  3.5.34

**Comment by piroor** [comment]
It is impossible due to a general restriction of the platform itself. While a drag session, wheel scroll events looks to be undelivered to applications. Indeed, on the Windows Explorer I couldn't scroll the folder tree while dragging a file.

**Comment by sbobbo** [comment]
That's disappointing. Is making the scrolling of the tab sidebar faster possible? Or configurable?

**Comment by piroor** [comment]
Shaking your mouse around edges of the scroll area while dragging, then it will trigger more scrolls. This technique is available on most auto-repeat scroll UI on Firefox.

**Comment by sbobbo** [comment]
Okay, thank you.
