### ISSUE TITLE
Thin red lines around tab names

### ISSUE THREAD

**Issue by petebrag** [piroor/treestyletab#2745]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
Too less information. Please fill the template to give some more hints for me to understand what happens on your environment, for example screenshots.

**Comment by petebrag** [comment]
Short description

I had asked you this week how to stop tabs from self-organizing. You told me to go to https://github.com/piroor/treestyletab/issues/2745 and do the items in the section  "I don't need automatically organized tree etc..”  I did them and now my tabs look like this:  https://user-images.githubusercontent.com/36479796/97085468-92537780-1615-11eb-9402-35a7be4ec7a4.png ( They have a red line around the tab names.) 
Steps to reproduce

1. In Firefox Developer Edition, 
2. Go to TST's configuration.
3.     "Development" section.
4.     Turn on the checkbox "Debug mode". Then all internal configurations are listed.
5.     Turn off the checkbox "autoAttach".
6.     Turn off the checkbox "syncParentTabAndOpenerTab".
7. Look at tab names, they should have a red line around them
Expected result

- the self organizing is turned off and works and the tab names should look the same as before.

Actual result

 the self organizing is turned off and works but there is a red line around the tab names. Like this:  https://user-images.githubusercontent.com/36479796/97085468-92537780-1615-11eb-9402-35a7be4ec7a4.png
Environment

* Platform (OS): 10.15.7 Mac Catalina
* Version of Firefox:  Firefox Developer Edition 83.0b3 (64 bit) 
* Version (or revision) of Tree Style Tab: 3.5.34

I hope this is enough detail. Thank you.

**Comment by piroor** [comment]
Thanks, I've realized that I forgot to write a step to deactivate the debug mode in the FAQ. The red line is shown when the debug mode is active (it indicates DOM structure of the sidebar contents.)

You can turn off the checkbox "debug mode" now, because it needed to be checked just to show all options.

**Comment by irvinm** [comment]
@petebrag is there anything more on this item or can you close it?

**Comment by petebrag** [comment]
You can close it thanks.
