### ISSUE TITLE
Feature request: copy URL/copy URL of all child tabs

### ISSUE THREAD

**Issue by cweagans** [piroor/treestyletab#2747]
I am easily distracted. When I find myself reading a distracting article, watching a video, or whatever, I create an empty tab and move the video/article/whatever to be a child of that tab and then collapse the tree. Out of sight out of mind.

Unfortunately, that means that I accumulate a ton of open tabs and that's not very good either. What I'd like to do is right click on the top level tab, click "Copy URLs of all child tabs", paste that list into a note somewhere, and then close that entire tree of tabs. For my specific use case, the top level tab only has immediate children (no grandchildren, great grandchildren, etc), so I'd be totally okay with a flat list of links, but maybe other people might want to preserve the hierarchy. The order is of interest to me, but if it's not preserved it's not that big of a deal.

Ideally, I could paste something like this in a note somewhere:

```
* [title of page loaded in tab](https://url.com/aasdfjk)
* [title of page loaded in tab](https://url.com/aasdfjk)
* [title of page loaded in tab](https://url.com/aasdfjk)
* [title of page loaded in tab](https://url.com/aasdfjk)
* [title of page loaded in tab](https://url.com/aasdfjk)
```

Definitely don't need the markdown formatting if it's easier to do something like this though:

```
https://url.com/asjhfdkjdsafksda
https://url.com/asjhfdkjdsafksda
https://url.com/asjhfdkjdsafksda
```

I've been doing this manually, but some automated way to do it would be really nice!

**Comment by irvinm** [comment]
This sounds like a good project for an helper addon for TST.  In lieu of that, there are already addons that can copy URLs to the clipboard (https://addons.mozilla.org/en-US/firefox/addon/copy-all-tab-urls-we/) but that isn't exactly what you want.  [This one can do URLs and Title & URL]

**Comment by piroor** [comment]
I think [Copy Selected Tabs to Clipboard](https://addons.mozilla.org/firefox/addon/copy-selected-tabs-to-clipboar/) ([repository](https://github.com/piroor/copy-selected-tabs-to-clipboard)) can help you. It provides ability to copy multiselected tabs so you currently need to multiselect tabs at first manually. I'm positive to add a new command "copy this tree" for environments both TST and CSTC are available.

**Comment by cweagans** [comment]
Oh, perfect! Thanks for the pointers! I followed piroor/copy-selected-tabs-to-clipboard#16 and installed that extension. Thanks again!
