### ISSUE TITLE
How do I change the size of the tabs?

### ISSUE THREAD

**Issue by waterjmwater** [piroor/treestyletab#2751]
Just got Tree Style Tab, how do I change the size of tabs and how do I delete some of the dead space above and below the text in the tab?

Thanks in advance.

**Comment by wvxwxvw** [comment]
Take a look at the settings. Section "Advanced".

**Comment by irvinm** [comment]
... and check out https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules for examples and ideas.

**Comment by waterjmwater** [comment]
> 
> 
> ... and check out https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules for examples and ideas.



> 
> 
> Take a look at the settings. Section "Advanced".

Thank you both so much for replying but I can only find how to change the padding width wise and I'm looking to delete some of the padding height wise.

**Comment by irvinm** [comment]
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#change-tab-height-236-2389

**Comment by irvinm** [comment]
@waterjmwater can you close this item?  If you still need some suggestions on what CSS you could change, I would suggest posting this over at https://www.reddit.com/r/FirefoxCSS/ where there are a lot of TST users who make CSS changes.

**Comment by irvinm** [comment]
@piroor I think you can close this one ... there isn't anything for you to do here.
