### ISSUE TITLE
Tab groups like in Kroppy's tree-style addon, or similar

### ISSUE THREAD

**Issue by akorn** [piroor/treestyletab#2753]
It would be great if the tab tree could be a tab forest.

Use case: I usually do several long-term things concurrently; all of these things involve dozens or even hundreds of open tabs. It would be useful to have a vertical bar of tab group names (with vertically rendered names) in the tree-style tab sidebar, one for each major project. Clicking one would hide the tabs related to the other groups, and show only the trees related to the selected group. It would be possible to move tabs (and entire trees) from one group to another.

Previously I used Opera with [Kroppy's tree-style tab addon](https://addons.opera.com/en/extensions/details/tree-tabs/) which had this feature, but a recent Opera upgrade broke it. The first screenshot on the linked page shows the vertical tab group bar, albeit with only a single group.

Another way that would work for me is to be able to have top-level tabs with no actual page open in them, just a custom title; these would then be my group roots and I could arrange the group-related tabs in subtrees. While grouping tabs already works, I can't rename the top-level tab the grouped tabs are made children of, which makes identifying the groups difficult.

**Comment by piroor** [comment]
Sorry I won't implement this feature to TST natively. I hope to keep TST concentrated about managing tree of tabs simply as possible as it can. A different level switcher UI is clearly out of the project scope.

Instead you can use [Simple Tab Gorups](https://addons.mozilla.org/firefox/addon/simple-tab-groups/) to switch forest of tabs. It works compatibly with TST.

> While grouping tabs already works, I can't rename the top-level tab the grouped tabs are made children of, which makes identifying the groups difficult.

The title of a group tab is changable. Did you try clicking on the title in the content area (not in the sidebar) or hitting the F2 key, while you see the group tab is active?

**Comment by akorn** [comment]
Hah, indeed the group leader can be renamed! Excellent, thanks!

The only thing still missing is a way to create a new 2nd-level tab under the current top-level tab with a hotkey.

I'll give the simple tab groups extension a try.

**Comment by piroor** [comment]
Firefox provides ability to customize shortcuts of addons, and TST provides commands for custom shortcuts. Please go to the addons manager tab and click the gear button, then you'll see a menu item to customize shortcuts. (But sadly you cannot reassign existing key-bindings used by Firefox itself. It is a known restriction.)

**Comment by akorn** [comment]
I know, and have in fact tried this; but TST doesn't have this function, so I can't assign a shortcut to it.

I already have a shortcut for "new next sibling tab" and am making do with that; but ideally it'd be possible to create a new tab just one level under the current group leader with a shortcut.

**Comment by piroor** [comment]
Do you mean that opening a fixed level tab in a tree regardless what level tab is active in the tree? Then I think TST More Tree Commands is good place to implement the command.
https://addons.mozilla.org/ja/firefox/addon/tst-more-tree-commands/
https://github.com/piroor/tst-more-tree-commands

**Comment by akorn** [comment]
Yes, that's exactly what I mean.

**Comment by piroor** [comment]
I've created an issue https://github.com/piroor/tst-more-tree-commands/issues/4 at the project. Please see the issue to track progress. This TST issue won't get any more progress, so I close this.
