### ISSUE TITLE
Blank dialog window to confirm closing tree of tabs

### ISSUE THREAD

**Issue by freetomik** [piroor/treestyletab#2754]
##  Short description
Dialog window to confirm closing tree of tabs is blank (white).

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open multiple tabs in one tree.
 4. Collapse the tree.
 5. Close the parent tab of the tree.

## Expected result
Dialog window shows up asking for confirmation with list of tabs, which are about to close.

## Actual result
Dialog window shows up, but it is blank (white). Hitting enter or escape does nothing.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 82.0.2
 * Version (or revision) of Tree Style Tab: 3.6.0

**Comment by piroor** [comment]
Thanks, this is a regression and fixed with updated external library.

**Comment by sodala33** [comment]
Sorry, I don't get it. How can I fix this for my TST?

**Comment by piroor** [comment]
I've uploaded 3.6.1 to Mozilla Add-ons, so please wait for a while until it become approved.

**Comment by spotcheckbilly** [comment]
> 
> 
> I've uploaded 3.6.1 to Mozilla Add-ons, so please wait for a while until it become approved.

It looks like the approval has been completed.  I was able to manually update a few minutes ago.  After I quit Firefox and restarted, the problem has gone away.  Thanks.

**Comment by irvinm** [comment]
@spotcheckbilly can you close this item?  Thanks.

**Comment by irvinm** [comment]
Sorry, my request should have been to ask @freetomik to close this item.

**Comment by freetomik** [comment]
Yes, I will close it. Works for me in version 3.6.1. Thanks for quick fix.
