### ISSUE TITLE
Clicking links always opens new tabs

### ISSUE THREAD

**Issue by mikeaustin** [piroor/treestyletab#2757]
## Short description

When clicking on links, for example results from Google, it opens every single link I click on in a new tab. This is definitely not regular behavior as I've been using TST for many years. It's becoming difficult to use jumping to and closing other tabs every time I click a link.

## Steps to reproduce

 1. Go to google.com and enter a search term
 2. Click a search results link

## Expected result

Clicking on a link stays within the current tab, replacing the current content.

## Actual result

A new tab is opened on every link click.

## Environment

 * Platform (OS): MacOS Catalina and Windows 10
 * Version of Firefox:  Firefox 82.0.3 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.6.1

**Comment by irvinm** [comment]
I don't think this is TST related.  (I could be wrong)  If you disable TST do you see the same behavior?

**Comment by piroor** [comment]
TST has no implementation to do this. Something like an addon or a user script for the Greasemonkey may cause such a result.

**Comment by mikeaustin** [comment]
You guys are right! It's the Google setting "Open each selected result in a new browser window". I've never heard of this or used it, and then it was enabled today and is so annoying. Google must have changed the default very recently.

Sorry for the spam. Why would you do that Google? It happens on my PC and my Mac. Btw, I love TST and have been using it for years :)
