### ISSUE TITLE
Typing in the TST CSS editor can move the cursor to the end of the editor

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2758]
## Short description
Typing in the TST CSS editor can move the cursor to the end of the editor.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Go to the end of the default TST CSS and enter something like:
Line 1 - 
Line 2 - 
Line 3 -
 4. Go to the end of "Line 1 - " and just start typing.  
 5. Eventually, the cursor gets moved to the end of the file.

I was worried I wouldn't be able to reproduce in a clean profile, but I had no problem doing so.  During my testing for this issue, I have seen it happen in as quickly as a couple of characters or as long as a few sentences.  I believe this is a regression within the later 3.5.x versions.

Another observation is that it appears that sometimes 1 character gets eaten by the editor when this occurs.

Ex:
Line 1 - Again this is a test to see how far I can type before things get all wonky.  This 
Line 2 - 
Line 3 - s the 

In this case I just typed:  "Again this is a test to see how far I can type before things get all wonky.  This is the"

## Expected result
Cursor should never get moved unless via keyboard.

## Actual result
Editing\typing in the TST CSS editor can cause easy mistakes.

## Environment

 * Platform (OS):  Windows 10 (x64 - 20H2)
 * Version of Firefox:  FF 82.0.3
 * Version (or revision) of Tree Style Tab:  3.6.1

**Comment by piroor** [comment]
Thanks, I forgot to fix this. The commit 4a869d8 should suppress it.

**Comment by irvinm** [comment]
@piroor I am still seeing this issue.  It isn't quite as bad, but I can definitely still reproduce it.  I am wondering if the timeout value from the check-in needs to be adjusted more.  I am on TST 3.6.2.

**Comment by piroor** [comment]
This problem can still appear if Firefox takes time over 250msec to save edited CSS to the storage and notifying the "changed" event to listeners. With the commit 7ac93d0 I've enlarge the timeout to 1000msec. I hope it should avoid the problem more certainly.

**Comment by irvinm** [comment]
Thanks @piroor.  I'm sure this will help and\or fix the situation.  My only other thought might be to expose this value in "all configs" just in case there might be people with a lot of CSS and maybe even slower machines.
