### ISSUE TITLE
[feature request] allow mouse scrollable switching of tabs with a modifier key

### ISSUE THREAD

**Issue by rieje** [piroor/treestyletab#2760]
Firefox has an about:config setting `toolkit.tabbox.switchByScrolling` which if set to `true`, mouse cursor over the tabs bar and mouse-wheel up/down will switch tab focus. This option has no affect on Tree Style Tabs and is expected, since mouse-wheel scrolling is the only way to scroll through the list of tabs.

However, `toolkit.tabbox.switchByScrolling` is very useful in scenarios where one wants to quickly seek/compare webpages (especially if webpages are similar) without having to click on each tab one-by-one which causes you to lose some context on the details of the tab. A workaround is to place tabs at the beginning of the tab bar then use the default Firefox hotkeys `ALT+{1-9)` to switch focus of the tabs. For example, to quickly compare 4 tabs, I move them to the beginning of the tab bar and then hold down ALT and press 1,2,3, and 4 in quick succession.

Anyway, it is possible to have `switchByScrolling` feature in TreeStyleTab by requiring the user to select a modifier like ALT so that regular mouse-wheel continues to behave by scrolling through the list of tabs and `ALT+mousewheelup` will scroll through tab focus either forwards or backwards depending on their preference.

**Comment by piroor** [comment]
There is a helper addon providing the feature: Tree Style Tab Mouse Wheel.
https://addons.mozilla.org/firefox/addon/tree-style-tab-mouse-wheel/

There is a project policy: emulate Firefox's native behaviors and options as possible as I can, so this feature looks to be good to become a built-in feature. But there is a workaround for now, so implementing the feature as a built-in has low priority...

**Comment by irvinm** [comment]
@piroor any reason to leave this open at this point?

**Comment by piroor** [comment]
@irvinm Thanks, I agree that I close this for now.
