### ISSUE TITLE
Disable Tree style behavior not possible anymore?

### ISSUE THREAD

**Issue by N3C2L** [piroor/treestyletab#2761]
From a previous thread I found this solution is not working anymore:
"
Go to TST's configuration.
"Development" section.
Turn on the checkbox "Debug mode". Then all internal configurations are listed.
Turn off the checkbox "autoAttach".
Turn off the checkbox "syncParentTabAndOpenerTab". "

I turn on debug mode, but autoAttach and syncParentTaAndOpenerTab are not visible.
I am on Windows 7 64 bit, latest firefox (normal, not nightly), latest TreeStyleTab.
When I turn on the debug mode nothing happens. No new options listed.

EDIT: Found a solution. The instruction above was not clear enough. It is not "debug mode" that
lists the options. Its "All Config" ("Alle Einstellungen" in german in my native language) at the bottom, click the triangle and then options expand.

**Comment by piroor** [comment]
Thanks, I've updated the description with the commit b326a92.
