### ISSUE TITLE
Wrong tab is activated when using Tree style tab in conjunction with panorama tab groups

### ISSUE THREAD

**Issue by animaone** [piroor/treestyletab#2762]
How to reproduce the bug:
Install tree style tab in firefox
Install panorama tab groups
create some groups in panorama tab groups and populate them
click on a website inside of the group, the wrong website will become active

**Comment by piroor** [comment]
I couldn't reproduce the problem on my environment. Could you describe more detailed steps? Here is my case:

1. Start Firefox (I used Nightly 84) with clean profile.
2. Install TST 3.6.1.
3. Install Panorama Tab Groups 0.8.12.
4. Prepare four tabs. My case:
   * A: https://addons.mozilla.org/ja/firefox/addon/tree-style-tab/
   * B: about:newtab
   * C: https://addons.mozilla.org/ja/firefox/addon/panorama-tab-groups/
   * D: about:addons
5. Click Panorama Tab Groups's toolbar button.
6. Accept keep tabs hidden. Assume that the existing group is X.
7. In Panorama Tab Group 's management page: Create a new group Y. 
8. In Panorama Tab Group 's management page: Drag the tab C from X to Y.
9. In Panorama Tab Group 's management page: Click the tab C to switch to the group Y.
10. Now there are only one visible tab C in the window.
11. Open three more tabs, E, F and G. Now there are tabs:
    * X
      * A: https://addons.mozilla.org/ja/firefox/addon/tree-style-tab/
      * B: about:newtab
      * D: about:addons
    * Y
      * C: https://addons.mozilla.org/ja/firefox/addon/panorama-tab-groups/
      * E: about:blank
      * F: about:blank
      * G: about:blank
12. Click Panorama Tab Groups's toolbar button.
13. In Panorama Tab Group 's management page: Click the tab D to switch to the group X.
14. Tabs in the group X become visible, and the active tab is D (as expected).
15. Click Panorama Tab Groups's toolbar button.
16. In Panorama Tab Group 's management page: Click the tab F to switch to the group Y.
17. Tabs in the group Y become visible, and the active tab is F (as expected).

**Comment by animaone** [comment]
I think this bug may be related to panorama tab groups, since sometimes two webpages are overlapped in the same place inside of a group.
Sorry about that. I will investigate this in the panorama tab groups source code.
