### ISSUE TITLE
'get-tree' only returns one tab

### ISSUE THREAD

**Issue by gonzaarcr** [piroor/treestyletab#2763]
### Short description

`'get-tree'` API return only the first tab when using window id.

### Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Make a new add-on and use the 'get-tree' API with a `window` id.
 4. Read results

### Expected result

It should return an Array with all the tabs as the [docs said](https://github.com/piroor/treestyletab/wiki/API-for-other-addons#get-tree-information-for-all-tabs-in-a-specific-window).

### Actual result

Returns only the first tab

### Environment

 * Version of Firefox: 85
 * Version of Tree Style Tab: 3.6.1

I think the error is [this if](https://github.com/piroor/treestyletab/blob/trunk/webextensions/common/tst-api.js#L1083)., There’s a ` Tab.getRootTabs` on the `else`.

**Comment by piroor** [comment]
Thanks! The root problem is in this function: https://github.com/piroor/treestyletab/blob/trunk/webextensions/common/tst-api.js#L1212 `formatTabResult()` currently requires something hint to format the result to an array but the case you mentioned has no hint. Hmm...

**Comment by piroor** [comment]
The commit 8439ec0 should fix this.

**Comment by irvinm** [comment]
@gonzaarcr can you try 3.6.2 and close this item if resolved?

**Comment by gonzaarcr** [comment]
Yes, it works!

Just another question, the program is working but on register I’m receiving the array `grantedPermissions` empty and I’m requesting `['tabs', 'activeTab']`. It does give me the permissions (because, as I said, the program works) but the array is empty. I don’t want to open an issue ’cause I don’t know if I’m doing something wrong.

**Comment by piroor** [comment]
> Just another question, the program is working but on register I’m receiving the array grantedPermissions empty and I’m requesting ['tabs', 'activeTab']. It does give me the permissions (because, as I said, the program works) but the array is empty. I don’t want to open an issue ’cause I don’t know if I’m doing something wrong.

TST returns the list of permissions actually granted on TST, not on Firefox. If you have not granted permissions for your addon yet at TST options => "Extra Features via Other Addons", it will become a blank array, and returned items of `get-tree` won't have `title`, `url` and some other properties. Do you mean that the array is blank but returned items of `get-tree` have such information? (Then it is a bug.)

**Comment by Binly42** [comment]
> Just another question, the program is working but on register I’m receiving the array `grantedPermissions` empty and I’m requesting `['tabs', 'activeTab']`. It does give me the permissions (because, as I said, the program works) but the array is empty. I don’t want to open an issue ’cause I don’t know if I’m doing something wrong.

> Do you mean that the array is blank but returned items of get-tree have such information? (Then it is a bug.)

might really a bug:

https://github.com/Binly42/Tab-Session-Manager/blob/54e807558cab050593fe44dafcfd582bd107654d/src/background/background.js#L298-L318

![image](https://github.com/piroor/treestyletab/assets/15514941/08d53d73-a76f-47e4-9a67-5a59590d4a66)
