### ISSUE TITLE
Closing Tab loads next tab automatically, which is often unwanted

### ISSUE THREAD

**Issue by blausand** [piroor/treestyletab#2766]
## Short description
Closing a tab triggers loading the adjacent tab, which isn't desired when "focus last selected tab (FLST)" policy/Add-On is active.

## Steps to reproduce
- Select some tab
- Close a tab that is not the very last one AND not the one before the selected one

## Expected result
- Focus stays on the active tab, nothing is loaded 

## Actual result
- Focus stays on the active tab, but tab next to the closed one is loaded

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 82.0.3
 * Version (or revision) of Tree Style Tab: 3.6.1

**Comment by piroor** [comment]
I think the choice will help you: TST Options => "Tree Behavior" => "When the current tab is closed as a last child" => "Never control focus". It suppresses any needless focus move by TST when the active tab is closed.

**Comment by blausand** [comment]
Am 25.11.2020 um 10:30 schrieb piroor:
>
> I think the choice will help you: TST Options => "Tree Behavior" => "When the
> current tab is closed as a last child" => "Never control focus". It suppresses
> any needless focus move by TST when the active tab is closed.
>
Perfekt, thanks!

Stunning amount of options here and stunning amount of brain processing needed
to parse the meaning of each :))

Anyway, your AddOn should be part of the core. At least it's highlighted in amo
by now.

Cheers and thanks for coding this again.
blausand

**Comment by piroor** [comment]
> Stunning amount of options here and stunning amount of brain processing needed to parse the meaning of each :))

I agree, I hope to reduce the number of options with more intelligent auto detection if possible...
