### ISSUE TITLE
Switch to last active tab

### ISSUE THREAD

**Issue by tbs** [piroor/treestyletab#2768]
Hi, I wish to have a way to switch to last tab on single clicking active tab. I miss a lot this feature in Tab Center Reborn extension.

Thank you!

**Comment by silverwings15** [comment]
https://addons.mozilla.org/en-US/firefox/addon/tab-flip-for-tree-style-tab/

**Comment by piroor** [comment]
I have no plan to implement this as a built in feature, from the project policy. Please use the helper addon.

I close this because this won't be implemented.
