### ISSUE TITLE
Indent/Outdent Current Tab Suddenly Lost (After v3.6.3 Update?)

### ISSUE THREAD

**Issue by viking2** [piroor/treestyletab#2776]
I had set key board shortcuts for Indent/Outdent Current Tab. Suddenly they stopped working and when I look for the keyboard shortcuts for this in TST, they are not there anymore!?

I believe that they may have disappeared in the 3.6.3 update?

p.s. I still find it very difficult to use the drag-drop for this, but I was perfectly happy with the previous shortcuts.

**Comment by irvinm** [comment]
They were moved into a separate extension.  https://addons.mozilla.org/en-US/firefox/addon/tst-more-tree-commands/

**Comment by viking2** [comment]
OK. Thanks. I must have missed the announcement about this...?

**Comment by irvinm** [comment]
It was in the release notes for 3.6.0, but unless you read about each update I can understand how it could be missed.

https://github.com/piroor/treestyletab/blob/trunk/history.en.md
