### ISSUE TITLE
Pinned tabs keep autohiding and becoming hard to see

### ISSUE THREAD

**Issue by spaceLem** [piroor/treestyletab#2778]
## Short description
Pinned tabs in TST keep autohiding, and becoming difficult to see (see screenshot).

![Screenshot from 2020-12-06 16-38-13](https://user-images.githubusercontent.com/6231990/101286455-86e19780-37e2-11eb-9524-55b19d6ae34c.png)

This behaviour only appeared a few days ago, and seems intentional as they reappear when the mouse is hovered over them. I can't find any option to turn this off and have the pinned tabs show normally at all times.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Add some pinned tabs.
 4. Wait.

## Expected result
Some option to turn off autohiding.

## Actual result
I can't find an option to turn off autohiding.

## Environment

 * Platform (OS): Linux (Manjaro)
 * Version of Firefox:  83.0
 * Version (or revision) of Tree Style Tab:  3.6.3

**Comment by piroor** [comment]
There is a hidden option `suppressGapFromShownOrHiddenToolbar` under TST options => Development => All Configs. Turning it off will deactivate the behavior, it looks to be a workaround for you.

Anyway, this is unexpected result and I cannot reproduce it on my testing environment: Windows 10 and Arch Linux. I think there are some more extra conditions to reproduce.

**Comment by spaceLem** [comment]
I've deactivated that option, and so far everything seems to be working normally again, so thank you!

**Comment by piroor** [comment]
The commit 749cd59 should fix the mis-shifted sidebar contents problem when the window is placed at coordinates like (*,0). It may help you if you saw the problem only at a problem placed at the top edge of the screen (ex. maximized).
