### ISSUE TITLE
Scroll bar position moved

### ISSUE THREAD

**Issue by acertain** [piroor/treestyletab#278]
Apologies if this is obvious, but I couldn't find it in the options or the release notes.  The scroll bar for the tabs used to be on the right of the tab block when the block was on the left (e.g. between the tabs and the main window).  When I upgraded from FF 3.X to 11.X, my TST add-on upgraded as well, and now the scroll bar is on the left.  Is this intentional?  Is there a way to flip it back?  Is this a TST issue or a FF issue?

Thanks.

Andrew

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
