### ISSUE TITLE
Option to disable tab pinning

### ISSUE THREAD

**Issue by rscircus** [piroor/treestyletab#2781]
## Short description
The keyboard shortcut `alt-p` collides with many other add-ons. For instance https://github.com/Cito/Pinboard-Pin

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install https://github.com/Cito/Pinboard-Pin
 4. Register your pinboard account with Pinboard-Pin
 5. Visit random site
 6. Hit `alt-p`
 7. Watch the tab being pinned instead of 'pinned to pinboard'.

## Expected result

The pinboard add-on to dominate over `alt-p`. An option to disable tab pinning in TST and/or move the keyboard shortcut.

## Actual result

A tab gets pinned per default, which can also not be disabled.

## Environment

 * Platform (OS): Ubuntu 20.04
 * Version of Firefox: 83.0 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.6.3

**Comment by irvinm** [comment]
@rscircus, I am sure @piroor will respond to this, but I don't see TST handling ALT+P to pin tabs.  Firefox also does not use ALT+P as well.  Are you sure you don't have another addon handling ALT+P?  (Like https://addons.mozilla.org/en-US/firefox/addon/toggle-pin-tab/)

If you go to about:addons, click on the gear, and select "Manage Extension Shortcuts" ... what is listed for ALT+P?

**Comment by piroor** [comment]
TST never use the shortcut Alt-P for any command by default. It looks a problem of another addon.

**Comment by rscircus** [comment]
OK, i'll check. Thanks for your help.

**Comment by irvinm** [comment]
@rscircus can you close this item?

**Comment by rscircus** [comment]
The solution was to be found in the 'Vimium C' extension. It sends the command. However, I wrongly assumed it was TST as this was the only visible reaction to the command sent.

**Comment by irvinm** [comment]
No worries.  Thanks for the update @rscircus.
