### ISSUE TITLE
No animation: allow sidebar scrolling as an exception

### ISSUE THREAD

**Issue by grahamperrin** [piroor/treestyletab#2782]
To move a tab up or down: 

* I nearly always use keyboard shortcuts i.e. <kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>⬆</kbd> and <kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>⬇</kbd>
* I rarely use a pointing device

– and I typically 'hold' the shortcut, for fastest possible movement of the tab to (or near) the top, or the bottom, of the sidebar. 

For performance, I prefer **no animation**. 

Sadly, wherever there's a scroll bar in the sidebar: 

* the tab becomes invisible. 

Example (a screen recording, with unnaturally slow movement for demonstration purposes): 

* [keyboard movement of a tab.zip](https://github.com/piroor/treestyletab/files/5686924/keyboard.movement.of.a.tab.zip)

In this context, I treat automated scrolling within the sidebar as essential. 

Please: is it possible to allow essential scrolling whilst generally _not_ allowing animation?

**Comment by piroor** [comment]
Ctrl-Shift-Up/Down expands the selection range in the current webpage by default. Thus I assume that you set these shortcuts for "Move Current Tab Up" and "Move Current Tab Down" for TST, then I think the commit b905346 should fix the problem.

**Comment by grahamperrin** [comment]
Sorry! I'm so accustomed to using the keys without looking at them, I thought simply 'up and down' when truly it's 'page up and page down' i.e. 

<kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>⇞</kbd> and <kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>⇟</kbd>

– respectively, _Move Tab Left_ and _Move Tab Right_ at https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_windows-tabs

**Comment by piroor** [comment]
Thank you for the follow-up. Ctrl-Shift-PageUp/PageDown cases are also covered by the change.

**Comment by grahamperrin** [comment]
Fix confirmed in version `3.6.4 (2020.12.21)`. 

Thank you!
