### ISSUE TITLE
Feature Request: Search within tabs

### ISSUE THREAD

**Issue by lamyergeier** [piroor/treestyletab#2783]
I have so many tabs open, I would like to search for the tab within the tree with a keyword.
Is it possible to add a search bar at the top of the treestyle tab. Regex support would be  a plus.

**Comment by irvinm** [comment]
I am sure @piroor will reply to this, but in general you can do some of this already with the existing URL bar.  Prefix "%" to your search term to search your tabs for that term.  ([link](https://support.mozilla.org/en-US/kb/address-bar-autocomplete-firefox?redirectslug=awesome-bar-search-firefox-bookmarks-history-tabs&redirectlocale=en-US#w_changing-results-on-the-fly_2))

There are also existing addons that focus on handling\searching tabs.  One that I use that can display tab thumbnails and allow your to search them is [Tab Manager Plus](https://addons.mozilla.org/en-US/firefox/addon/tab-manager-plus-for-firefox/).

**Comment by piroor** [comment]
Sorry it won't be added as an built-in feature because it is out of purpose of this project. Instead please use workarounds mentioned by @irvinm.

**Comment by irvinm** [comment]
@anishmittal2020 will you close this item?  Thanks.

**Comment by piroor** [comment]
FYI: there is a list of addons which provides "search tab" feature.
https://github.com/piroor/treestyletab#similar-projects => "Listing tabs with a search field"
