### ISSUE TITLE
First two tabs are hidden after full screen mode

### ISSUE THREAD

**Issue by nanto** [piroor/treestyletab#2786]
## Short description

When making a window in full screen and back from full screen mode, first two tabs are hidden.

## Steps to reproduce

 1. Open new window.
 2. Open three tabs in the window.
 3. Press F11 key and make the window in full screen.
 4. Press F11 key again and make the window not in full screen.

## Expected result

All three tabs are shown in sidebar.

## Actual result

The first and the second tabs are not shown. Only the third tab is shown in sidebar. 

![image](https://user-images.githubusercontent.com/82213/102630067-6bd23880-418f-11eb-9492-a531c66ca1a2.png)

Disabling CSS rule `#tabbar-container { top: var(--visual-gap-offset); }` makes all tabs shown. The value of `--visual-gap-offset` is `-75px` at the time.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 86.0a1 
 * Version (or revision) of Tree Style Tab: 3.6.3

**Comment by piroor** [comment]
This looks same to #2778 and #2779. Could you collect debug logs with steps described at https://github.com/piroor/treestyletab/issues/2779#issuecomment-747919000 ?

以下、なりふり構っていられないので日本語で失礼します。。。

https://twitter.com/piro_or/status/1339835626481307650 からのスレッドでも述べているのですが、再現条件が分からず調査が難航しております。過去報告はいずれもLinux環境の物だったので、Linux向けビルドのFirefoxに固有の現象なのか？とも思っていたのですが、Windows 10でも再現しているとのことなので、ますます困惑中です。

F11でのフルスクリーンモード切り替え時に発生しているとのことですが、ツールバーを自動的に隠す設定（フルスクリーンモード中にツールバー上で右クリックするとメニューにチェックボックスがある）はOFFでしょうか？

（……と書いていて、Nightly 86.0a1で以下の手順でサイドバーの内容がずれたままになる状況が発生することに気付きました。

1. F11でフルスクリーンモードにする
2. ツールバー上で右クリック→ツールバーを隠す のチェックを外す
3. F11でフルスクリーンモードから抜ける
4. 新しい空のタブを開く（このタイミングで、サイドバーの内容がブックマークツールバーの高さ分だけずれる）
5. F11でフルスクリーンモードに入る（サイドバーの内容はずれたまま：期待に反する、本来はサイドバーの内容はずらされないべき）
6. 空でない別のタブに切り替える（サイドバーの内容はずれたまま：期待に反する、本来はサイドバーの内容はずらされないべき）

ただ、このissueで報告されている現象はフルスクリーンモードでない状況で起こっているので、上記のケースとも異なっているようです。）

**Comment by nanto** [comment]
* ツールバーを自動的に隠す設定が有効 & ブックマークツールバーを常に表示 → 再現する
* ツールバーを自動的に隠す設定が有効 & ブックマークツールバーを表示しない → 再現する
* ツールバーを自動的に隠す設定が無効 & ブックマークツールバーを常に表示 → 再現する (隠れる領域の高さは小さくなる)
* ツールバーを自動的に隠す設定が無効 & ブックマークツールバーを表示しない → 再現しない

**Comment by nanto** [comment]
ツールバーを自動的に隠す設定が有効 & ブックマークツールバーを常に表示、という状態の下で、

1. 新しいウィンドウを開く
2. そのウィンドウで F11 キーを押してフルスクリーン表示に入る
   * デバッグコンソールに `tst<Sidebar-238>: 11:11:58.357 sidebar/gap-canceller:          should not suppress, but there is a visual gap common.js:602:13` と出力される。
3. そのウィンドウで再度 F11 キーを押してフルスクリーン表示をやめる
   * 問題が再現する (タブが見えなくなる)
   * デバッグコンソールに `tst<Sidebar-238>: 11:12:14.420 sidebar/gap-canceller:          should suppress visual gap: offset =  -103 common.js:602:13` と出力される。

となりました。

**Comment by nanto** [comment]
* 問題が再現した後、サイドバーの幅を変更すると問題が解消します。
* 問題が再現した後も F11 キーを押してフルスクリーンモードに入ったりやめたりを繰り返すと、フルスクリーンモードをやめたタイミングで問題が再現するときとしないときがあります。
  * フルスクリーンモードに入ったタイミングでは問題は再現しません。

**Comment by nanto** [comment]
今までの私の報告はすべて、新しいウィンドウを開いた際にウィンドウの際上端がディスプレイ表示領域の際上端に位置する (フルスクリーンモードでなくても `window.screenY === 0` である) 場合のものでした。

新しいウィンドウを開いた後にウィンドウを移動させて (`window.screenY !== 0` の状態にして) から F11 キーを連打した場合、問題は再現しません。

**Comment by nanto** [comment]
https://github.com/piroor/treestyletab/issues/2786#issuecomment-748404075 のステップ 3 で `should suppress visual gap` というログ出力が出ているのが気になります。この時点ではフルスクリーンモードをやめたはずですが、 https://github.com/piroor/treestyletab/blob/2226a9cfb86a76ab3b36e7f81d9bedd964a615d3/webextensions/sidebar/gap-canceller.js#L61-L64 の `shouldSuppressGap` が `true` になっている、~すなわち `document.documentElement.dataset.ownerWindowState` が `fullscreen` のままのようです~ (追記: `mDataset.activeTabUrl == configs.guessNewOrphanTabAsOpenedByNewTabCommandUrl` のほうが `true` になっている可能性もありますね)。

----

再追記 (2020-12-19 12:00+09:00): 私の環境ではホームページを `https://www.google.co.jp/` にしており、`configs.guessNewOrphanTabAsOpenedByNewTabCommandUrl` は `about:newtab` となっています。ということは再現手順において `mDataset.activeTabUrl == configs.guessNewOrphanTabAsOpenedByNewTabCommandUrl` は常に false のはずであり、やはりステップ 3 の時点で `document.documentElement.dataset.ownerWindowState` が `fullscreen` のままのようです

**Comment by piroor** [comment]
情報ありがとうございます！ Y=0の時に起こる問題については、「ウィンドウは移動もリサイズもされていないが、サイドバーの内容だけがずらされた」ことを検出する際にウィンドウのY座標だけを見ていたのが原因と言えそうです。 749cd59 でウィンドウのX,Y座標とサイズも比較するようにしたので、Y=0での誤爆はこれで減るのではないかと思われます。

> やはりステップ 3 の時点で document.documentElement.dataset.ownerWindowState が fullscreen のままのようです

ここは悩ましい所なのでした……
windowのfullscreen状態が変わったことを確実に検知する方法がなくて、今はwindowのresizeイベントが発火してから500ミリ秒間だけ何度も状態を問い合わせているため、fullscreen状態が変わる前の時点で検出処理が走ってしまうこと自体を避けられずにいるのでした。

**Comment by nanto** [comment]
Thank you for your fix! I think this issue is fully fixed.

By the way, I think current behavior of gap-canceller doesn't enhance user experience since it causes flicker.

----

ありがとうございます。私の報告した問題は解決したので、この issue は閉じてもよいのではないかと思います。

ところで、現在の gap-canceller の挙動はユーザー体験の向上につながらないように思います。`resize` イベントなどが非同期で発生する以上、現在の実装では一瞬タブの位置が上下するのを避けられません。この一瞬のちらつきはかえって視線をタブバーに注目させてしまいます (gap-canceller は本来、タブバーに注目させないための機能だと認識しています)。現在の挙動なら、gap-canceller がないほうがなめらかになる (ユーザーが操作していてストレスが少ない) と思います。

**Comment by piroor** [comment]
視覚的なちらつきに関しては確かに避けられないのですが、それとは別にこの現象がもたらす致命的な影響として、「タブの上でボタンを押し下げたときとボタンを放したときで座標が変わるせいで、それがドラッグ操作の開始と誤認されてしまう」問題があり、そちらをある程度軽減できることに期待して、この機能を入れたという部分もあります。そちらの効果はある程度あるはずと期待しているので、今の所は既定で機能をONにしておきたいと思っています。

ユーザー体験的には、ブックマークツールバーを常に表示するようユーザーが明示的に設定を変えるのが最善なので、どうにかしてそちらに誘導できればいいのですが……

**Comment by piroor** [comment]
よく見返したら、このissueはフルスクリーンモードでの動作についてのものでしたね。
先のコメントの懸念はフルスクリーンモードの方の場合だと起こり得ないものなので、フルスクリーンモード時の動作は既定でoffにしようと思います。
