### ISSUE TITLE
There is no "Bookmark all Tabs" in TST context menu

### ISSUE THREAD

**Issue by hsantanna** [piroor/treestyletab#2789]
## Short description
There nos no context menu for bookmarking all tabs from the current window.
No matter if right click over a tab or TST's sidebar empty space.

## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install TST.
 3. Do any web search and open multiple tabs to search results
 4. Right-click any tab on the tree or Right-click TST empty space

## Expected result
There to be an option to **"Bookmark all Tabs"** from the current window.

## Actual result
There is no option to "Bookmark all Tabs" from the current window.
The only way to create bookmarks for all tabs from the current windows is:
 1. Right-click any tab on the tree (or Right-click TST empty space), then select menu option **"Select All Tabs"**
 2. Right-click again and select **"Bookmark Selected Tabs..."**

Also, before realizing that, I was mistakenly using the option **"Bookmark this tree"** believing that all tabs from the current window would being bookmarked. That was because I was believing that the window was the root of the tree, and that every tree inside TST was a sub-tree. Which now I realize that was a wrong understanding and that I was confused. 

## Environment
 * Platform (OS): Arch Linux, KDE Plasma, KWin (X11)
 * Version of Firefox: Firefox Nightly 86.0a1 (2020-12-20) (64-bit)
 * Version (or revision) of Tree Style Tab: 3.6.4

**Comment by piroor** [comment]
Sorry but I have no plan to add the command, because there is a basic policy about TST's context menu: it just simulates Firefox's native one, to minimize confusion of existing Firefox users.

**Comment by piroor** [comment]
By the way, I hope to solve this misunderstanding for newcomers.

> That was because I was believing that the window was the root of the tree, and that every tree inside TST was a sub-tree. Which now I realize that was a wrong understanding and that I was confused.

Relabeling with the phrase "tree under this tab" looks better than current "this tree" labels? I'm afraid reduced usability with too long labels.

**Comment by irvinm** [comment]
@hsantanna Firefox does not support this directly any more as well.  The workaround that people use (with or without TST) is to select all of the tabs and bookmark them.  

Will you close out this item?  Thanks.

**Comment by irvinm** [comment]
@piroor I think this can be closed.

**Comment by SebiderSushi** [comment]
I always use `Ctrl+Shift+D`, it bookmarkts all your open tabs from the current window into a new folder and lets you name that and choose where it should be stored.
