### ISSUE TITLE
Ctrl Click

### ISSUE THREAD

**Issue by opqriu** [piroor/treestyletab#2791]
Good morning. I am using the Tree Style Tab add-on very well.
I have a question.
When I press Ctrl button and click Link, it opens in sub (tree) tab.
In this case, I can't find a setting to prevent opening with the Sub (tree) tab.
Can you help me?
Thank You.

**Comment by piroor** [comment]
There is a FAQ topic "I don't need automatically organized tree, instead I just want to organize tree by myself":
https://github.com/piroor/treestyletab#feature-requests

**Comment by irvinm** [comment]
@piroor I think this can be closed.
