### ISSUE TITLE
"For newcomer of Tree Style Tab" message triggered how?

### ISSUE THREAD

**Issue by rieje** [piroor/treestyletab#2793]
How is the message "For newcomer of Tree Style Tab some extra permissions are required for more natural user experiences. Please click the button to grant them." triggered? I get this message when I run a new profile with extension settings copied over from an older profile. All permissions are already granted on the new profile just like they were granted on the old profile. Context:

I'm on Linux and use [firejail](https://github.com/netblue30/firejail) to sandbox my Firefox profiles. I have a wrapper script for Firefox where it runs temporary sandboxed profiles--basically, it runs a one-time session of Firefox by quickly creating a profile, copying over some settings files from an existing and permanent profile, running the instance, then on close, deletes the profile. Settings copied to this temporary profile are inside the firefox profile folder: `extensions`, `browser-extension-data`, `extensions.json`, `extension-preferences.json`, and `extension-settings.json`.

For my use case, it is quite annoying to get this notification on startup every time I run new temporary profiles, which is often for my workflow. I understand my use case is not so common but I hope to learn more.

**Comment by piroor** [comment]
The notification appears when it is the initial startup or the saved "config version" information is older than the defined version. It is saved to the storage space for IndexedDB, the physical file is an SQLite DB under a folder like `storage\default\moz-extension+++...`. So, you'll see the notification on every startup if firejail does not write back updated IndexedDB data to the original one.

**Comment by piroor** [comment]
It means that a new option to deactivate the notification won't work as expected, because it won't be saved on your case.

**Comment by piroor** [comment]
I think it is a problem of the firejail, so I've marked this issue as an invalid.

**Comment by irvinm** [comment]
@piroor I think this can be closed.
