### ISSUE TITLE
Icon for Firefox's special `about` pages

### ISSUE THREAD

**Issue by ksze** [piroor/treestyletab#2794]
## Short description

TST can show special icons for some of the `about` pages, e.g. the "puzzel piece" icon for the `about:addons` page. I have checked through all of the `about` pages listed in `about:about`. For some reason, TST won't show the specific icons for the following special pages:
- `about:logins`
- `about:protections`
- `about:robots`
- `about:profiling`

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open the aforementioned `about` pages in tabs
 4. Open the TST sidebar

## Expected result

See special icons in the TST sidebar

## Actual result

See generic globe icons in the TST sidebar. See this screenshot:
![image](https://user-images.githubusercontent.com/381556/103723233-8ec46f80-500c-11eb-9523-6d557b3b3460.png)

The tabs in that screenshot are, in order:
- GitHub new issue
- `about:logins`
- `about:protections`
- `about:robots`
- `about:profiling`

You can see from the tab bar on top that those `about` pages are supposed to have special icons.

## Environment

 * Platform (OS): Kubuntu 20.04.1 x86-64
 * Version of Firefox: 84.0.1
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
Thanks! I've added more icons with the commit bd2714e.
