### ISSUE TITLE
Ctrl scroll zoom removed?

### ISSUE THREAD

**Issue by SHHSSH** [piroor/treestyletab#2795]
## Short description

 - - - - - - -
 
Prior to a few updates ago, we were able to Ctrl + Scroll Up/Down to zoom the TST sidebar, what has happened that has prevented us from doing so recently?

I have attempted to zoom in other freshly installed browsers, still doesn't work. Unfortunately I can't give you an example of how it used to work because I don't have access to older versions.

 - - - - - - -
 

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. TESTED

## Environment

 * Platform (OS): 

Windows 10. Multiple browser versions, Developer etc. Modern versions, not older ones.

Sorry for the lack of description of the problem, thought it was pretty basic to understand.

**Comment by piroor** [comment]
Turn on the checkbox: TST Options => Development => All Configs => zoomable, then you'll see zoomed sidebar contents.

The checkbox is unchecked by default and not changed for a long time. I think you were checked it manually ago, or something behavior was changed in Firefox side.

**Comment by SHHSSH** [comment]
Thanks, really did try to find it. Hidden all the way down there. Cheers @piroor
