### ISSUE TITLE
Moving multiple tabs in a New Window.

### ISSUE THREAD

**Issue by utkarshdubey** [piroor/treestyletab#2797]
[FEATURE REQUEST]
Is there any way I could hack the extension in a way I could add a keyboard shortcut for Moving multiple tabs to new window.

**Comment by piroor** [comment]
Did you try "Move to New Window" with multiselected tabs? You can highlight multiple tabs with Ctrl/Shift-click on tabs.

**Comment by utkarshdubey** [comment]
Hey!
Nvm I got it working. Had to create an add-on. Closing the issue.

Thanks
