### ISSUE TITLE
Pinned tabs hide blue light indicator?

### ISSUE THREAD

**Issue by ghost** [piroor/treestyletab#2799]
I'm trying to hide the blue light indicator on pinned tabs when there is new activity.

This code UserChrome.css code works for pinned tabs without the treestyletab addon:

```
.tabbrowser-tab > .tab-stack > .tab-content[pinned][titlechanged]:not([visuallyselected="true"]) {
  background-image: none !important;
}
```

The following code does not work in the treestyletabs addon:

```
tab-item.pinned {
  background-image: none !important;
}
```

**Comment by irvinm** [comment]
This worked for me:

```
tab-item.faviconized.unread tab-favicon::before {
  background-image: none !important;
}
```

**Comment by ghost** [comment]
Thank you!

**Comment by irvinm** [comment]
You are welcome.  Will you close this issue?
