### ISSUE TITLE
backup tabs?

### ISSUE THREAD

**Issue by aaaawwWWWwwwwWWW** [piroor/treestyletab#2800]
## Short description
If the users accidentally closes all tabs by using the Firefox "forget" functionality, they will lose their so much curated tabs like 1000 and will led them to sadness. Not  good. I'm sad.

## Steps to reproduce
1. Open 1000 tabs with very well curated content after in 1+ years.
2. Then stupidly hit the forget functionality without reading it first.

## Expected result
A backup.

## Actual result
No backup.

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 84.0.1
 * Version (or revision) of Tree Style Tab: 3.6.5

**Comment by irvinm** [comment]
There is already some undo functionality with TST, but nothing that would undo something like that.  I run a large number of tabs (500-600) and I use Tab Session Manager to backup my sessions as I go.  At the end of the day, I am at risk of only losing the last 15 minutes of changes using it.  It has bailed me out a few times after a Windows blue screen or a Firefox crash where it isn't able to start up properly or restore the last session.

**Comment by aaaawwWWWwwwwWWW** [comment]
Yeah, the undo functionally couldn't save them. There's so much extensions for TST that i didn't even know something like session management existed... It did never happen to me to search for it, because even after crashes Firefox could still restore everything like a miracle on my end. Still, thank you so much for your input! I've installed this extension and will be sure to use it properly. But damn, I'm very traumatized because I've put so much effort in organizing it and rely so much on them... I can only think how this will happen to other users in the future.

**Comment by irvinm** [comment]
You are welcome.  I also take things one step further and backup my Firefox profile once a day as well ... in case of some corruption or something like that.  I know it might be a little excessive, but between my tab sessions being backed up a few times an hour and my profile backed up once a day to the cloud, I know I can recreate Firefox on any machine at any point in time.

Given that TST is focused on trees, I don't think there is anything for TST here.  Would you mind closing this issue?

**Comment by aaaawwWWWwwwwWWW** [comment]
Oh, now that you talk about it... I have backup from last week of my home directory that I can use to recover the tabs. I totally forgot about this. I'll make sure now to do daily backups of my Firefox profiles following your input.

I understand TST is focused on tree tabs, and that this is out of scope already on the README. Still, I think it would be very useful to have a backup section on the README encouraging users to do daily backups of their Firefox profiles, and to use the Tabs Session Manager in advance.

**Comment by irvinm** [comment]
@piroor is there anything you want to do here or should it just be closed out?

**Comment by piroor** [comment]
Thank you for a reminder, this looks to be closable.
