### ISSUE TITLE
Container tabs selector should be disabled in private windows

### ISSUE THREAD

**Issue by andinus** [piroor/treestyletab#2802]
## Short description

Enabling this option:

![2021-01-24-200406_617x58_scrot](https://user-images.githubusercontent.com/62012039/105633608-844e0680-5e51-11eb-998c-2188c54093ec.png)

shows container selector option on new tab. 

It also shows it in private windows but container tabs don't work in private windows, so the button does nothing and fails silently.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Enable "container tab selector" option
 4. Open a new tab in private window

## Expected result

Either it should show an error stating that container tabs are not available for private windows or it should simply be disabled in private windows.

## Actual result

It fails silently when user chooses to open new container tab in private window.

## Environment

 * Platform (OS): OpenBSD 6.8
 * Version of Firefox: firefox-82.0.3 
 * Version (or revision) of Tree Style Tab: 3.6.5

**Comment by irvinm** [comment]
Interesting catch @andinus.  @piroor just wanted to make sure you saw this.

**Comment by piroor** [comment]
Sorry I missed this issue and I didn't know the container tab feature is disabled for private windows. With commits 980dd73 and 11b64fe, now TST deactivates the UI for private windows automatically.

**Comment by andinus** [comment]
Thank you!
