### ISSUE TITLE
Firefox85+TST3.6.5, First tab is covered by sidebar header when open New Tab

### ISSUE THREAD

**Issue by alice0775** [piroor/treestyletab#2804]
## Short description
First tab is covered by sidebar header when open New Tab

## Steps to reproduce
0. Start Firefox85.0 with clean profile.
1. Install TST3.6.5
2. Restart browser
  --- You can see first tab "New Tab" as expected
3. Load any web page(e,g wikipedia.org) in the tab
  --- You can see first tab "Wikipedia" as expected
4. Add a new tab(Ctrl+T or clock [+] button)
  --- First tab is covered by sidebar header --- BUG!
  --- You cannot see the first tab.

## Expected result
First tab should be visible

## Actual result
First tab is covered by sidebar header

## Environment

 * Platform (OS): Windows10
 * Version of Firefox: 85.0
 * Version (or revision) of Tree Style Tab: 3.6.5

## Additional information:
The problem is occurred when Alt > View > Bookmarks Toolbar > "Only Show on New Tab" is selected(default in Firefox85).

**Comment by alice0775** [comment]
TST 3.6.5.11204 is also affected.

**Comment by BlueRaja** [comment]
I'm seeing the same issue.  Here's an image of what it looks like

![tree bug](https://i.imgur.com/2jCIeir.png)

There are two tabs here, but only the bottom-few pixels of the first one are visible.

This only happens if the first tab is not selected. If I select the first tab, then it slides down to become visible.

**Comment by piroor** [comment]
Currently it is a designed behavior. Please see also:
https://github.com/piroor/treestyletab/issues/2779#issuecomment-760704688

There are two workarounds:

* Set the bookmarks toolbar to be shown always ( https://github.com/piroor/treestyletab/issues/2779#issuecomment-761833067 )
* TST Options => Turn "Unlock Expert Options" checked => Appearance => Suppress visual gap of the sidebar contents provided by temporarily shown/hidden toolbars on following cases => Turn "Blank new tabs on Firefox 85 and later" unchecked.

This behavior aims to avoid unexpectedly started drag-and-drop from shifted sidebar contents while switching of tabs via your mouse. Now I think that it will become better if it works only for tab switching triggered by mouse operations and doesn't work for tab switching from another addon or keyboard shortcuts.

**Comment by alice0775** [comment]
Thanks.
Both workarounds work for me.
I close this as WORKSFORME

**Comment by BlueRaja** [comment]
This should not be closed. It is not acceptable default behavior.

**Comment by piroor** [comment]
With commits 9080ec9 and c5dad40, now TST should suppress the visual gap only when it is triggered by a mouse operation as I planned at https://github.com/piroor/treestyletab/issues/2804#issuecomment-768883431
