### ISSUE TITLE
Where did keybind configs go?

### ISSUE THREAD

**Issue by ghost** [piroor/treestyletab#2805]
## Short description
I can't find the keybind config menu in the TST options anymore.. I'm trying to change the behavior of the default ctrl+t and I remember there was a way to change keybinds in the past but on latest version it appears to be gone.

## Expected result
https://github.com/piroor/treestyletab/issues/2473#issuecomment-577459864

## Actual result
![image](https://user-images.githubusercontent.com/63500907/106499802-586df900-64c1-11eb-83be-6e79261101f4.png)

## Environment

 * Platform (OS): Windows 10 x64 Pro Version	10.0.18363 Build 18363
 * Version of Firefox: Release 85.0 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.6.5

**Comment by Fanolian** [comment]
https://support.mozilla.org/kb/manage-extension-shortcuts-firefox

**Comment by Fanolian** [comment]
And I don't think you can change Firefox's native keyboard shortcuts.

**Comment by ghost** [comment]
Yep I just tried using ctrl+t with no luck. I'll have to make a habit of double clicking on the empty space to open new bars instead of using a keybind
