### ISSUE TITLE
Firefox 85 resets custom styling on losing focus

### ISSUE THREAD

**Issue by libfitz** [piroor/treestyletab#2806]
## Short description
When using Firefox 85, custom styling (applied via Advanced) is lost when Firefox window is not in focus.

## Steps to reproduce
1. Launch Firefox with TST installed.
2. Disable in-built themes (appearance => no decoration).
3. Apply custom CSS (advanced section). My custom styles are [here](https://gist.github.com/affectiosus/a7130d814815b8a67003867eae76fc16). I also have a `userChrome.css` with some tweaks, can provide it as well if necessary.
4. Switch to another window or make Firefox window not focused in any way.

## Expected result
TST stays themed with custom CSS.

## Actual result
Custom styling is lost, but brought back when Firefox is in focus again.
The behavior has been verified with a clean profile with only TST installed.

## Environment
 * Platform (OS): Linux (Ubuntu 18.04.5, Cinnamon 4.2.4-1, also tested on 18.04's Gnome; will verify on Windows a bit later; can reproduce on macOS also)
 * Version of Firefox: 85.0
 * Version (or revision) of Tree Style Tab: 3.6.5

I must add that using in-built themes works, and using "no decoration" option with empty custom CSS also works (i.e. the appearance of the tree is unchanged regardless of window being focused or not). Somehow my CSS seems broken, but it worked pretty much unchanged since Quantum was first released a few years back.

**Comment by SolidAlloy** [comment]
It is reproducible on Windows 10 too.

**Comment by piroor** [comment]
Your style sheet contains the [`:-moz-window-inactive` pseudo class](https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-window-inactive). It was disabled in any content provided by extensions but looks to be activated globally now.

**Comment by libfitz** [comment]
@piroor thank you for the tip. I got rid of those classes and it works as expected now.
