### ISSUE TITLE
New tab scrolls out of view

### ISSUE THREAD

**Issue by laktak** [piroor/treestyletab#2807]
## Short description

When I open a new tab, the tab is visible at the bottom but as soon as I click on a bookmark it scrolls out of view.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open new tabs (so you get to the bottom)
 4. Click on a bookmark (this will probably still be correct)
 5. Open another tab
 6. Click on a bookmark - the tab will scroll away

## Expected result

The tab should not move/scroll

## Actual result

https://user-images.githubusercontent.com/959858/107352471-2b76a300-6acc-11eb-896f-cb74a7440cc5.mov

## Environment

 * Platform (OS): linux and mac
 * Version of Firefox: 85.0.1
 * Version (or revision) of Tree Style Tab: 3.6.5

**Comment by laktak** [comment]
Also I tried to hide the new tab button but then it just scrolls below the screen.

**Comment by piroor** [comment]
It looks to be related to the "canceling visual gap" behavior for dynamically shown/hidden toolbars. TST 3.7.0 contains a change for the behavior (it is now suppressed except focus change triggered by mouse operations) so could you try the updated version?

**Comment by laktak** [comment]
Yes, 3.7.0 fixed it. Thank you!
