### ISSUE TITLE
New tab selector & Container tab drop-down should be placed consistently

### ISSUE THREAD

**Issue by andinus** [piroor/treestyletab#2808]
## Short description
Enabling this option:

![tst-option](https://user-images.githubusercontent.com/62012039/105633608-844e0680-5e51-11eb-998c-2188c54093ec.png)

shows container selector option on the right side & moves the new tab selector to the left.

1. After this fix: https://github.com/piroor/treestyletab/issues/2802, container tab selector was removed from Private windows. That causes New tab selector to move back to the right.

Here is the new tab selector in New window when the option specified above is enabled:

![2021-02-09-201558_184x225_scrot](https://user-images.githubusercontent.com/62012039/107380190-8ff22c00-6ae5-11eb-8be6-7c00c54a716a.png)

And here it is in Private window:

![2021-02-09-201142_197x189_scrot](https://user-images.githubusercontent.com/62012039/107380111-7c46c580-6ae5-11eb-9cd2-966d78cc22dc.png)

2. The container tab drop-down shows up on the left by long press on new tab button:

![2021-02-09-202052_249x217_scrot](https://user-images.githubusercontent.com/62012039/107381488-cd0aee00-6ae6-11eb-9b09-09ee6f4038e4.png)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Enable "container tab selector" option
 4. Open a new tab in private window & look at New tab selector
 5. Open a new tab & look at Container tab drop-down by long-press on new tab button

## Expected result

It should be placed consistently. 

## Actual result

The position of new tab selector shifts to right & the container tab drop-down shows up on the left when the new tab button is held but the selector is on the right.

## Environment

 * Platform (OS): OpenBSD 6.8
 * Version of Firefox: firefox-82.0.3 
 * Version (or revision) of Tree Style Tab: 3.7.0

**Comment by andinus** [comment]
If we just move the Container tab selector to the left then both issues are solved.

1. New tab selector stays on the right in all windows.
2. Container tab drop-down shows up on the left (when long-pressing new tab button) & that's okay because the selector is on the left now.

**Comment by piroor** [comment]
Thanks, changes introduced with commits 6a4fe13 and f9bf46d should improve the consistency.

**Comment by andinus** [comment]
Thanks!
