### ISSUE TITLE
Remove empty favicon placeholder when site icons and favicons are off. Help wanted.

### ISSUE THREAD

**Issue by barkoder** [piroor/treestyletab#2809]
## Short description
Hi!

I don't use favicons/site icons so I have them turned off in about:config. And they also [happen to be a privacy risk](https://www.cs.uic.edu/~polakis/papers/solomos-ndss21.pdf). So I always have them off.  
Regular tabs in Firefox give me back the space that's normally used for those but I can't seem to get back the space in TST. Please help.

Thanks :)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST 3.7.0 on your OS of choice.
 3. Visit **about:config**
 4. Set **browser.chrome.favicons** , **browser.shell.shortcutFavicons** , **alerts.showFavicons** and **browser.chrome.site_icons** to **False**
 5. Quit Firefox.
 6. Delete **favicons.sqlite** from your profile folder to fully remove favicons cache.
 7. Start Firefox Again.
 8. Visit https://en.wikipedia.org/wiki/Main_Page
 9. You'll get this empty circle.
![Remove favicon placeholder Circles (2) and get back this space for text](https://user-images.githubusercontent.com/70430094/107462086-3b859580-6b53-11eb-9990-17fc2a15f5d5.png)
10. How do you remove that circle altogether and get back the space instead for the text of the tab's name?

## Expected result
No more empty favicon circles. And that space should be used for the tab's name instead. Like here with regular tabs.
![Regular tabs give back the space](https://user-images.githubusercontent.com/70430094/107462576-4bea4000-6b54-11eb-9f28-3bafef3285ea.PNG)

## Actual result
Empty favicon circles.

## Environment

 * Platform (OS): Windows, Linux
 * 78.7.1 ESR Version of Firefox: 
 * TST 3.7.0

**Comment by piroor** [comment]
TST Options => Advanced => Extra style rules like following should do that:

```css
tab-item:not(.faviconized):not(.loading) tab-favicon {
  display: none;
}
```

**Comment by barkoder** [comment]
Thank you @piroor  :)

**Comment by barkoder** [comment]
![But is there some way to move the text further left](https://user-images.githubusercontent.com/70430094/107569214-f52a4800-6bdf-11eb-990f-d539c60eef5c.png)

But is there some way to move the text further towards the left edge?

**Comment by irvinm** [comment]
@barkoder you might want to check the instructions on how to inspect the CSS in the sidebar.  (https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs)  From there you can see all the effective CSS and find what works for you.

In your case, you can simply change the tab label margin to 0 to get back a little space.  You can go further left, but you have to remember there are twisties shown when there is a tree.  The CSS might be too generic for your solution, but might give you an idea.

```
tab-item tab-label {
    margin-left: 0;
}
```

**Comment by barkoder** [comment]
Thanks @irvinm that did move the text a little futher left. But is there some way to remove the twisties completely and move the text all the way over to the left? I always double click the tree's parent to expand and collapse anyway so I don't need the twisties.

**Comment by irvinm** [comment]
```
tab-item tab-twisty {
  display: none;
}
```

**Comment by barkoder** [comment]
Thanks @irvinm finally the text's all the way left.
