### ISSUE TITLE
organize tabs by domain, metadata, date, location, device

### ISSUE THREAD

**Issue by grexe** [piroor/treestyletab#2811]
## Short description

I constantly end up having 200+ tabs open and getting lost in them, despite serious attempts to keep them tidy.
When I found this extension, I was hoping to end this situation, but I am missing an important feature:

Re-organize by certain criteria to clean up the mess and trim down tabs by grouping similar ones under the same (sub)tree.
This could be done by reading metadata from web pages, like keywords (for semantic grouping by tag), or by domain, date, location information gathered from the web site, or device (when syncing).

Imagine a TST menu option "Group by -> Metadata, Domain, Location,…"
I could then end up with a tree that depends on the selected "mode of organization/grouping", like:

### Group by -> Metadata (from webpage "keywords" tag)

News
+--Politics
+--Gaming
+--Hardware
+--Tech
+--Culture

Culture
+--Arts
+--Movies

Business
+--LinkedIn
+--Wall Street Journal

Science
+--Curiosity.com
+--arxive.org

Reading
+--Medium
+--Brain pickings

### Group by Location

+--Local [taken from browser location + web site location info)
+--USA
+--Europe

### Group by Domain, Device

you get the idea,-)
There could also be advanced grouping options like "by frequency, last accessed, recommended,..."

**Comment by piroor** [comment]
TST has a project policy to concentrated to basic tree features. Other more useful commands need to be provided by helper addons, e.g. [TST More Tree Commands](https://addons.mozilla.org/firefox/addon/tst-more-tree-commands/) ([issue tracker](https://github.com/piroor/tst-more-tree-commands/issues)).
https://github.com/piroor/treestyletab/blob/trunk/README.md#feature-requests

**Comment by irvinm** [comment]
@piroor I think this one can be closed as well.
