### ISSUE TITLE
Show only pinned tabs

### ISSUE THREAD

**Issue by 3DRaven** [piroor/treestyletab#2813]
Hi! Cool addon :) How about option to show only pinned tabs in side panel? It can be help show many of pinned tabs in few columns. It is possible with this extension?

**Comment by 3DRaven** [comment]
Now, if I close all unpinned tabs, then I can't set width of side pannel less than 7 columns of pinned tabs. It is bad behavior for this functionality :) And I think best solution it show unpinned tabs in top (default for firefox) and show pinned tabs in side panel with what I need columns.

Tnx.

**Comment by 3DRaven** [comment]
Screenshot 

https://ibb.co/J7QJbTY

**Comment by 3DRaven** [comment]
And in this mode need to hide pinned tabs in default top panel of FF. This can be 

{code}
.tabbrowser-tab[pinned="true"] {
    display: none !important;
} 
{code}

**Comment by 3DRaven** [comment]
And need scroll of pinned tabs too.

**Comment by 3DRaven** [comment]
Now I used this css in userChrome.css

{code}
.tabbrowser-tab[pinned="true"] {
    display: none !important;
} 

#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar-header {
  display: none;
}

#sidebar {
  min-width: 10px !important;
}   
{code}

And get only pinned tabs panel without scroll. How to add scroll to the right side of side panel? And better is totaly hide unpinned tabs from this panel :)

**Comment by 3DRaven** [comment]
Screenshot

https://ibb.co/PYTj06M

**Comment by piroor** [comment]
I convert this to a discussion because this looks to be not an issue report.
