### ISSUE TITLE
Using Ctrl-T keybinding in about:addons -> Manage Extension Shortcuts

### ISSUE THREAD

**Issue by fghimis** [piroor/treestyletab#2817]
Hello! Is there way for Tree Style Tab to read the Accel key from Firefox's configuration (or to be set explicitly)? 
I use a different **ui.key.accelKey** (Alt, instead of Ctrl), but [here](https://github.com/piroor/treestyletab/blob/90b6d2232b68efbd4bcd692f4d6f9292c97af070/webextensions/common/handle-accel-key.js#L14) it seems it's hard-codded based on Mac/otherwise.

## Short description
I want to use Ctrl-T to toggle TST, but it says it is a Firefox shortcut. 
By modifying my accelKey to Alt now all my commands are like Alt-w (close tab), Alt-t (create new tab), Alt-c (copy) etc. Ctrl-T is no longer bind to any shortcut.

## Steps to reproduce
Go to **about:config**, change **ui.key.accelKey** to 18 (alt). Verify that Alt-t opens now a new tab and Ctrl-t doesn't do anything. Go to **about:addons**, try to bind Ctrl-t to some TST action. The following error appears: "Can't override a Firefox shortcut".

## Expected result
Allow to bind keys different than AccelKey-*

## Actual result
Not being on Mac it thinks my default shortcuts are of type Ctrl-Key instead of Accel-Key.

## Environment
 * Platform (OS): Linux 
 * Version of Firefox: 85.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.7.1-1

I don't know if this is a Firefox problem or a TST problem.

**Comment by fghimis** [comment]
I think it's a Firefox issue. If I bind Ctrl-1 to toggle TST and press Alt-1 it will toggle it.
This issue can be closed.

**Comment by piroor** [comment]
Hmm, I missed cases with customized `ui.key.accelKey`. I've introduced a new expert option to support changed accelerator key for tab switching shortcuts. I hope it help you.
