### ISSUE TITLE
"Replace closed parent with a dummy tab" option not working

### ISSUE THREAD

**Issue by 1zaman** [piroor/treestyletab#2818]
## Short description

The option for replacing closed parent with a dummy tab in the section "Recommended behavior for people who still use the native tab bar of Firefox itself also" does not seem to do anything, and retains the behaviour of promoting the first child, even when the sidebar is open.

The same option inside the section "Recommended behavior for people who never use the native tab bar of Firefox itself" does work as expected. Using different combinations of this setting in the "Custom" section also works as expected.

## Steps to reproduce

1. Start Firefox with clean profile.
2. Install Tree Style Tab.
3. Right-click the extension icon in the toolbar, and select "Manage Extension".
4. Expand the "Tree Behavior" section.
5. In the section "When a parent tab is closed or moved just as a solo tab", inside the already checked first option "Recommended behavior for people who still use the native tab bar of Firefox itself also", select the option "Replace closed parent with a dummy tab and keep the tree".
6. Keep the tree sidebar open and visible.
7. Open a new tab and go to a website.
8. Open two children from this tab.
9. Close the parent tab (either via keyboard shortcut or from the top bar or from the sidebar).

## Expected result

The parent tab is replaced with a dummy parent tab, and the tree structure remains the same.

## Actual result

There is no dummy parent tab created, and the first child tab is promoted as the new parent of the second child tab.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: Release 85.0.2
 * Version (or revision) of Tree Style Tab: 3.7.1

**Comment by piroor** [comment]
Thanks, after a research I've realized that there are some wrong codes which were produced with simple replacement of symbols. The commit 521da21 should fix this issue, and I've added a regression test also.

**Comment by irvinm** [comment]
@1zaman is this resolved for you?  If so, can you close this item?

**Comment by 1zaman** [comment]
Thanks, this is resolved for me in 3.7.2.
