### ISSUE TITLE
Clicking on tab bar of inactive window switch tab

### ISSUE THREAD

**Issue by jordanmorris** [piroor/treestyletab#282]
Default behavior for Firefox when clicking on an inactive tab in an inactive window:
-First click brings focus to window.
-Second click changes to tab.

Tree style tabs behavior:
-First click brings focus to window AND changes to tab.

I suspect this is not intended behavior. This is annoying, now that tabs-on-top is common, to have to be careful where you click in the titlebar/tabbar if you are just trying to bring focus back to your browser.

Thank you.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
