### ISSUE TITLE
Unexpected behaviour of "undo close tab" with keyboard shortcut

### ISSUE THREAD

**Issue by ElhemEnohpi** [piroor/treestyletab#2820]
## Short description
Using the "undo close tab" keyboard shortcut (shift-cmd-T on Mac) gives different and unexpected results than choosing the same thing from Firefox's History > Recently Closed Tabs, such as opening multiple copies, in a different place, and older closed tabs.

## Steps to reproduce

1. Start Firefox with clean profile.
2. Install TST.
1. Create five new tabs. Make the second one a child of the first tab. Close the fifth tab.
1. Collapse the first tree, and close it.
2. Select menu History > Recently Closed Tabs > first item in the list (marked with "shift-cmd-T"), or use TST context menu "Undo Closed Tabs". 
3. Note that the first two tabs are restored as expected. This can be repeated.
4. Collapse and close them again.
1. Press shift-cmd-T

## Expected result

The first two tabs will be restored again.

```
A
\- B (collapsed)
C
D
```

## Actual result

The first tab is restored with no children, the fifth tab is restored, with a copy of the first tab, and its child.

```
A
C
D
E
\ -A
   \- B
```

Also, if you uncheck "Restore the set of tabs most recently closed...", then shift-cmd-T restores the tree anyway (without extra copies), while choosing either menu item doesn't.

## Environment

 * Platform (OS): macOS 10.14.6
 * Version of Firefox: 85.0.2
 * Version (or revision) of Tree Style Tab: 3.7.1

**Comment by piroor** [comment]
I've confirmed this. It looks to be caused by duplicated restoration of multiple tabs closed at a time, by both Firefox and TST.

**Comment by piroor** [comment]
The commit 3e7dce5 should fix this, but I'm afraid that there can be some possible regressions...

**Comment by irvinm** [comment]
@ElhemEnohpi is this resolved for you?  If so, can you close this item?

**Comment by ElhemEnohpi** [comment]
It seems to be resolved, but I haven't tested it very much, so I don't know about the "possible regressions"... I guess I can close it and re-open if I find anything.

**Comment by irvinm** [comment]
Thanks @ElhemEnohpi ... definitely re-open if there any other issues.
