### ISSUE TITLE
API Question:  Events during TST upgrade

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2822]
## Short description
When TST is upgraded in Firefox, my helper addon does not receive any events that TST is going out of context or when it returns into context.  Disabling\re-enabling my addon or restarting Firefox re-establishes everything properly.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install older version of TST.
 3. Install helper addon.
 4. Upgrade TST with new version.

A few observations, when I do all of this in a clean VM with a clean profile with only a handful of tabs, I can't seem to reproduce the problem.  I don't receive any notifications that TST is ending, but I do receive a "ready" event when TST starts up again and my helper addon then re-applies the CSS changes.  

In my main profile, when I look at the sequence of events during a TST upgrade, I can see: 

- 10:24:03.112 TST-Lock is working fine
- 10:37:13.011 Looks like TST has started upgrading
- 10:44:42.142 I manually disable my helper addon in about:addons
- 10:44:43.293 I manually enable my helper addon in about:addons
- The regular startup process happens and things start working again.

![image](https://user-images.githubusercontent.com/979729/108529618-a5fcab00-72a2-11eb-9ab3-f5d822b66a2a.png)

Here is the code for registering to TST:

```
async function registerSelfToTST() {
  try {
    console.log("TST-Lock: Sending register-self message to TST");
    const result = await browser.runtime.sendMessage(kTST_ID, {
      type: "register-self",
      name: "TST-Lock",
      icons: browser.runtime.getManifest().icons,
      listeningTypes: ["tab-mousedown", "tab-mouseup", "wait-for-shutdown"],
      style: `
        .tab.locked .closebox {
          pointer-events: none !important;
        }
        .tab:not(.faviconized).locked .closebox::after {
          background: none;
          content: "🔒";          
          line-height: 1;
          mask: none;
        }
      `,
    });

  } catch (_error) {
    console.log(
      "TST-Lock: registerSelfToTST() -> Error: TST is not available yet (" +
        _error +
        ")"
    );
    console.log("TST-Lock: Retrying registerSelfToTST() in 250 ms");
    await sleep(250);
    registerSelfToTST();
  }
}
```

## Expected result
From an API perspective, how should a helper addon monitor for this situation?  If I can get this notification, I can enter into a state of trying to reach out to TST with delays in between until it is fully up and running.  My addon already has to do this as it is initialized much faster than TST and usually has to wait 4+ seconds until TST is ready.

I'm happy to share the code (just in a private Github repro), but maybe we could just start with what the proper way to handle this should be.  (It is based on https://github.com/piroor/treestyletab/issues/2104 which now works perfectly except for this use case)

## Actual result
TST will update properly, but the helper addon does not detect it and the changes it does are not reflected in TST until the helper addon or Firefox is restarted.

## Environment

 * Platform (OS): Windows 10 x64
 * Version of Firefox: 85.0.2 (I don't think it is related to the version of FF)
 * Version (or revision) of Tree Style Tab: 3.7.2
* Source background.js: https://gist.github.com/irvinm/1b094885957a89e09b98756b5073ba87

**Comment by irvinm** [comment]
Trying to figure this out a little more, I looked at the logs when disabling and enabling TST in my main profile and everything works fine in this scenario.

At point 1, everything is working fine.  TST is then disabled via about:addons and we can see the connections closed and the promise rejected.  At point 2, the helper addon sees the rejected promise and enters into uninitFeaturesForTST() which is proper.  After TST is re-enabled, it properly sends a "ready" event to the helper addon and it is able to continue working.

In the previous post about TST, neither 2 (uninit ...) or 3 ("ready" event) is done when TST does an upgrade.

![image](https://user-images.githubusercontent.com/979729/108579207-de78a500-72f3-11eb-8a6d-35aabde5d7da.png)

**Comment by piroor** [comment]
What happened on your environment maybe:

* A) TST failed to memorize the ID of your addon. TST won't send any notification to unknown addons. (TST's problem)
* B) TST memorized the ID of your addon, but didn't send a "ready" message to your addon. (TST's problem)
* C) TST memorized the ID of your addon and tried to send a "ready" message, but it was not delivered to your addon. (TST's problem or Firefox's problem)

Is your addon listed in TST Options => Development => All Configs => cachedExternalAddons ? If the value does not contains the ID of your addon, the case A happened on your environment.

And I've tried to check the log but realized that TST doesn't output expected log. The problem is fixed with the commit cb2965e7aeb00719a67745e8c73fed026db787df, so filtering logs of common/tst-api.js with the query `notifyAddons` should report the actual list of IDs TST tried to send a "ready" message to. If the ID of your addon doesn't appear in the log, the case B happened on the environment. Otherwise the case C.

Could you check these points with the next release (or the latest development build loaded via `about:debugging`) ? You'll need to open the debugger for TST before you update TST, to see logs reported while TST's startup process.

**Comment by irvinm** [comment]
Looking into cachedExternalAddons, it does not look like my addon is in there:


cachedExternalAddons:  ["{731bf636-c808-4c86-b02f-af462eccc963}","{7aa0a466-58f8-427b-8cd2-e94645c4edc2}"]

![image](https://user-images.githubusercontent.com/979729/109001226-b336e280-7672-11eb-86c3-6cdc977bc3dd.png)
![Snag_401759](https://user-images.githubusercontent.com/979729/109002426-3442a980-7674-11eb-935f-0e50d1a1dc7c.png)
![image](https://user-images.githubusercontent.com/979729/109002531-59371c80-7674-11eb-9c7c-52b8519065f8.png)

I do see that it is listed in the permissions section:

![image](https://user-images.githubusercontent.com/979729/109002629-74a22780-7674-11eb-8b9b-6a21ce7dbee1.png)

Any chance there might be an issue with me using an email-style formatting identifier for the "Extension ID"?  (TST-Lock@irvinm.addons.mozilla.org)

I'll check the logs with a development build in the next few days...

**Comment by irvinm** [comment]
So in a clean profile what I did which worked fine:

- Installed previous release of TST ... 3.7.1
- Installed my addon
- Verified that my addon is listed under cachedExternaladdons

![image](https://user-images.githubusercontent.com/979729/109239241-027c3080-77a3-11eb-9360-51ce2e3ed49b.png)

- Checked for addon updates and allowed TST to upgrade to 3.7.2.
- Verified that my addon is still listed under cachedExternaladdons
- Verified the debug logs on both the TST and helper addon side

**TST Side:**
- Point 1 is where the upgrade starts
- Point 2 shows a strange error about failing to send a "ready" message

![image](https://user-images.githubusercontent.com/979729/109239030-9699c800-77a2-11eb-995c-0bb105a998de.png)

**Helper addon side:**
- Point 1 is where the upgrade on the TST side starts
- Point 2 is where the "ready" event is received

![image](https://user-images.githubusercontent.com/979729/109239088-b03b0f80-77a2-11eb-8368-9da77af36365.png)

I went back to my main profile and tried to get the helper addon to properly show up in the cachedExternaladdons.

- I tried disabling and re-enabling the helper addon ... nothing changed in the cache.
- I went into TST and "reset" the cache field to clear it out.
- I then disabled and re-enabled each of the 3 helper addons and now all three show up in that field.
- ["TST-Lock@irvinm.addons.mozilla.org","{7aa0a466-58f8-427b-8cd2-e94645c4edc2}","{731bf636-c808-4c86-b02f-af462eccc963}"]

This tells me that the basic means to register with TST is working, but maybe at some time in the past somehow it got dropped from the cache.  I have a feeling it will work now.  I will disable automatic addon updates and before doing an update I will verify the cache field is properly set and then allow the upgrade to happen while letting the debug consoles run.  

Once a helper addon is registered, are there any situations that it is removed from the cache?

**Comment by piroor** [comment]
After reading your additional comments, I've realized that `cachedExternalAddons` and other related options are not listed in `localKeys`. This means that they were possibly replaced with blank value (from another device with no helper addon), if you use multiple devices and activate Firefox Sync. Does your case match to this description? Then I've added such keys to the list of not-synchronized options with the commit 372576d95, and it possibly solve this problem.

**Comment by irvinm** [comment]
@piroor that is definitely my use case.  I only use the helper addon on maybe 2 of my machines ... and the rest do not.  As I am not currently publishing the addon via AMO, I have to install it manually and hence it is not propagated to all of my profiles.

Your theory makes sense and I am guessing the commit will help.  I will monitor the situation, but I think we have a good plan moving forward.  Thanks.

I will reopen the issue if this doesn't solve the problem or if I get any additional information.

**Comment by irvinm** [comment]
Just an FYI, I checked the cached state this morning and my helper addon isn't there any more.  I think the Firefox Sync theory was a good idea.

["{7aa0a466-58f8-427b-8cd2-e94645c4edc2}","{731bf636-c808-4c86-b02f-af462eccc963}"]
