### ISSUE TITLE
Separation line between pinned and standard tabs have moved to up every time

### ISSUE THREAD

**Issue by 3DRaven** [piroor/treestyletab#2825]
## Short description
When we opened more and more tabs then line between pinned tabs and standard tabs moved to up, but never go down.
## Steps to reproduce
Just open lot of pinned tabs and start to open standard tabs
## Expected result
Need to make separation line between pinned tabs and standard tabs movable or set percent between this type of tabs adjustable in settings or css.

## Actual result
Can't move separation line and now this line separate 50% of tabs window

https://ibb.co/4282vjN
https://ibb.co/RBMFdvJ

##Environment
Firefox 85.0.1

**Comment by piroor** [comment]
TST already has the option: Appearance => Maximum height of the area for pinned tabs (please note that you need to activate expert options to show the input field)
![image](https://user-images.githubusercontent.com/70062/109153945-f1d2b700-77b0-11eb-853f-6cf8e8e2fd64.png)

**Comment by piroor** [comment]
Currently I have no plan to implement any draggable separator, because TST's sidebar is not designed to insert such a special element. Current behavior was introduced just as a workaround, sorry.

**Comment by 3DRaven** [comment]
It is strange, I set it to 100% and didn't have any effect. Any value of this option do not have any effect.

**Comment by 3DRaven** [comment]
A, it was my mistake :) This line placed on the end of pinned tabs and I haven't pinned tabs for place this line on 100% of height of window :)

All work fine, thank you!
