### ISSUE TITLE
Dragged tab obscures bookmarks toolbar

### ISSUE THREAD

**Issue by hotsphink** [piroor/treestyletab#2826]
## Short description

When I drag a tab to the bookmarks toolbar, the tab name covers up the folder I'm trying to drop it into, making it very hard to get to the right place (especially if attempting to file it into a nested folder.)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Reveal the bookmarks toolbar if you don't already have it (View / Toolbars / Bookmarks Toolbar / Always Show)
 4. Create a folder (right click on bookmarks toolbar, choose New Folder...)
 5. Try to drag a tab into the folder

## Expected result

The native Firefox tabs do not display the tab title when dragging, so do not have this issue. Possible ways I can think of to fix this would be to (1) use a small icon like Firefox does, (2) position the tab title when dragging a ways below the mouse cursor, or (3) display the tab title (but probably not the mouse cursor indicator) with partial opacity.

## Actual result

I have a tab titled "dragon prince zym at DuckDuckGo". I dragged it over to a bookmark folder named "Homeschool", with entries "The Courses -- The Animation Course" and "What's known about tutoring". This screenshot is after I painstakingly wiggled around a little until the folder menu opened up -- the main problem is before the menu opens up, when I'm trying to position the tab so that it goes into the right menu (and doesn't go into the top-level bookmarks toolbar.) At that time, I can't see *any* of the bookmark folder name (the screenshot shows the top part of it visible. That means I have already moved the mouse down a little, because while choosing a folder I have to completely cover up the folder names.)

![obscuring-tab](https://user-images.githubusercontent.com/78649/109327612-5f143580-780d-11eb-9f90-114896ad1443.jpg)

## Environment

 * Platform (OS): Fedora 33 Linux
 * Version of Firefox: nightly 87.0a1 (2021-02-03)
 * Version (or revision) of Tree Style Tab: 3.7.2

**Comment by piroor** [comment]
OK, I've changed the offset of the drag image. Now it is rendered at bottom-right of the cursor.
![image](https://user-images.githubusercontent.com/70062/109407034-1e5d1d80-79c1-11eb-93a5-44b59596a041.png)
Due to some restrictions TST cannot use a thumbnail as the drag image, thus I still use the tab element itself.

**Comment by hotsphink** [comment]
Perfect! I just got the updated version, and it resolves my issue completely. Thank you!

**Comment by natenate19** [comment]
Not a huge fan of this change, though I understand why this was done.  Moreover it seems buggy here, occasionally when dragging tabs, the tab drag image is nowhere near the cursor, and instead 400-500 pixels to the right of the cursor, out in the middle of the window.

I'm on macOS 11.2.2, Firefox 86, and TST 3.7.3 fwiw.  I seem to be able to reproduce the issue when moving a child / descendent tab of a parent, but only sometimes:

![Screen Shot 2021-03-05 at 10 11 32 PM](https://user-images.githubusercontent.com/279747/110193103-fe35c000-7dff-11eb-8024-70f0ddf94374.jpg)

Unfortunately you can't see my cursor there, but it's just above the highlighted tab in the tree, nowhere near the tab drag image, and was not near the tab drag image previously.  The tab drag image just appears 400-500 pixels to the right of the cursor, out in the middle of the window.  Again, only sometimes.

Is there any way you can reinstate the old behavior without the tab drag image offset, and put it behind a preference as an option?  Not asking you to revert these commits, just reinstate the old behavior as a non-default option behind a preference.

Thanks.

**Comment by piroor** [comment]
@natenate19 Do you use a retina display? The change I did can be buggy on a hi-dpi environment for now.

**Comment by natenate19** [comment]
Yes, this is a 13 inch retina MacBook Pro 2020 Intel.  Resolution is at max for the display, which is 3360x2100 (1680x1050@2x).
