### ISSUE TITLE
Tree not expanded when focus received after closing another tab.

### ISSUE THREAD

**Issue by danadam** [piroor/treestyletab#2827]
## Short description
With option "When a tab gets focus, expand its tree and collapse other automatically" ON (which is the default), after closing a tab, another, collapsed tree gets focus and stays collapsed.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open three tabs: A1, A2, B1 and B2.
 4. In TST move A2 as a child of A1 and B2 as a child of B1.
 5. Focus A1 (B1 gets collapsed)
 6. Close A1 (A2 becomes solo tab)
 7. Close A2 (B1 gets focus but is not expanded)

## Expected result
B1 gets expanded.

## Actual result
B1 stays collapsed.

## Environment

 * Platform (OS): Linux, Debian Testing
 * Version of Firefox: 86.0
 * Version (or revision) of Tree Style Tab: 3.7.2

Little recording:
https://user-images.githubusercontent.com/170743/109403630-aa8a2900-795e-11eb-8495-73297f912989.mp4

**Comment by piroor** [comment]
It looks not a bug but an intentional result. There is a hidden expert option "Except focus moving caused by closing of the current tab" and it is checked by default. Turning it off will produce the expected result for you, could you try that?
![image](https://user-images.githubusercontent.com/70062/109426940-61f06f80-7a33-11eb-9078-f87a172214dc.png)

**Comment by danadam** [comment]
Yep, that works.

Out of curiosity, is it some recent change? Because I remember it working as I expected not so long ago, without me needing to change this option.

**Comment by piroor** [comment]
The option was introduced at very early versions of TST while it was a XUL addon. If you use multiple devices with Firefox Sync, or if you reinstalled TST, the option may be restored to the default value even you didn't desired that.

**Comment by danadam** [comment]
Hm... I neither use Firefox Sync nor did I reinstall TST. Well, doesn't matter. Thanks for the help!
