### ISSUE TITLE
Sync volume check

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2833]
## Short description
Related to previous discussions around the amount of allowable sync data (https://github.com/piroor/treestyletab/issues/2623 and https://github.com/piroor/treestyletab/issues/2678) and reviewing your code comment:

https://github.com/piroor/treestyletab/blob/aa3710e3c16c2291b9c13f927448e144b46b9a4a/webextensions/common/constants.js#L357-L360

It appears the allowable amount to be synced should be at least 48k.

With my TST CSS currently at around 30k characters (including spaces) and the total sum of my chunkedUserStyleRules(0-5) at 36,635 characters, when I add one or two more lines to my TST CSS it triggers the editor's size check warning that the CSS is too long and needs to be reduced.

I can remove comments to get back under the quota, but just wanted to see if this is the behavior you would expect given the raw numbers.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Sync\Load 30k character CSS. (TST settings export: [configs-treestyletab@piro.sakura.ne.jp.zip](https://github.com/piroor/treestyletab/files/6110195/configs-treestyletab%40piro.sakura.ne.jp.zip))
 4. Copy and paste a block of CSS to increase the size.
 5. See warnings regarding CSS total size.

## Expected result
Given the total sync storage via Firefox and even with the "safety" reduced size of CSS sync storage I would have thought more than ~30k characters of CSS should be able to be synced.

## Actual result
CSS editor size warning to reduce CSS size will be triggered.  (I have not verified if the sync is blocked when this occurs and\or if the chunking stops until the editor size is reduced.)  I never see chunkedUserStyleRules6 and chunkedUserStyleRules7 being used at all.

![image](https://user-images.githubusercontent.com/979729/110511114-e85f1e00-80d1-11eb-8435-de088ff4b244.png)

## Environment

 * Platform (OS): Windows 10 x64 (20H2)
 * Version of Firefox:  86.0
 * Version (or revision) of Tree Style Tab:  3.7.3

**Comment by irvinm** [comment]
@piroor any initial thoughts on this?

**Comment by piroor** [comment]
Thanks, there was a mistake and TST didn't use full of allowed slots to save chunked data. With the commit 9f2486a now TST uses all 8 slots for both user styles and sent tabs.

* The old (wrong) maximum size of those chunked data: 6 * 1024 * 6 * 2 = 73728(bytes)
* The new (correct) maximum size of those chunked data: 6 * 1024 * 8 * 2 = 98304(bytes)
* The maximum size of all sync storage of an addon: 102400(bytes)
* The rest allowed data size for other options: 102400 - 98304 = 4096(bytes)
