### ISSUE TITLE
Possible bug on Firefox ESR

### ISSUE THREAD

**Issue by wvxwxvw** [piroor/treestyletab#2834]
Firefox ESR 78 x64
Sometimes tabs stop responding to mouse actions, while actions from the context menu work. 
Why this happens is not clear, for example, the last time it happened after adding all the tabs to bookmarks. But it happened that even after closing the first tab. Only restarting the browser helps, and then not always.
This has been happening for a long time, I did not write before, as I was hoping to describe the problem more accurately. I hope you can determine it yourself.

**Comment by irvinm** [comment]
Have you looked over either https://github.com/piroor/treestyletab/issues/2660 or maybe https://github.com/piroor/treestyletab/issues/2272?  I would suggest taking a look at those to see if you can contribute to information there ... or if they are different, I think it would be a great benefit if you could dig a little more into some scenarios that could reproduce this at all.

Unless @piroor has already seen this, I doubt he will be able to reproduce without more information.

On a side note, have you tried reproducing it one a clean profile with just TST installed?

**Comment by wvxwxvw** [comment]
@irvinm 
The problem is very rarely manifested, it happens three times a day, it happens once. How to catch it in a clean profile? I can't sit on an empty browser for all day. But I tried (so far to no avail) and even created a specially clean portable version, I will try to view on it.

**Comment by irvinm** [comment]
@wvxwxvw I totally understand.  Just as hard as it is for you to reproduce, I would imaging it would be that much harder for @piroor to reproduce it if he has never seen it before without any indicators of the trigger of the issue.

**Comment by wvxwxvw** [comment]
[Link_Properties_Plus_WE](https://github.com/Infocatcher/Link_Properties_Plus_WE)  fault. My brain almost boiled. )
[Created an iss](https://github.com/Infocatcher/Link_Properties_Plus_WE/issues/2), let's see what it responds to.

**Comment by piroor** [comment]
I've installed Link Properties Plus WE https://addons.mozilla.org/firefox/addon/link-properties-plus/ but I couldn't reproduce the problem. It looks there is something more trigger.

**Comment by wvxwxvw** [comment]
Yes, there is something else. Today, the tab bar froze immediately after opening the browser.

**Comment by wvxwxvw** [comment]
I could not determine exactly the cause. Disable addons - to no avail, remove external scripts - to no avail, delete prefs.js - bug disappeared.
I close the topic.
