### ISSUE TITLE
How do I reset tree style tab to original settings?

### ISSUE THREAD

**Issue by Evotron** [piroor/treestyletab#2836]
How do I reset tree style tab to original settings?

**Comment by irvinm** [comment]
If you are not using Firefox Sync, you could always just uninstall TST, restart Firefox, then reinstall TST.

If you are using Firefox Sync, I think that is a little harder.  I'd have to think about that more ...

**Comment by piroor** [comment]
@Evotron Did you try TST options => Development => All Configs => Reset All?

**Comment by Evotron** [comment]
I didn′t know about TST options => Development => All Configs => Reset All. Thank you very much!
