### ISSUE TITLE
Had tab grouping been removed?

### ISSUE THREAD

**Issue by xiraix** [piroor/treestyletab#2838]
Has tab grouping been removed? I used to use this addon several months ago and I remember being able to put tabs under a dummy tab. I cant find such an option under the context menu anymore.

Platform (OS): Windows 10
Version of Firefox: 86.0.1 (64-bit)
Version of Tree Style Tab: 3.7.3

**Comment by irvinm** [comment]
Check out:  https://github.com/piroor/treestyletab/issues/2428

I don't believe there is a context menu item for it.  Just do it manually or bookmark it to open a new one.

**Comment by piroor** [comment]
The command "Create New Group" for multiselected tabs was removed from TST itself, and moved to a helper addon "TST More Tree Commands". Please try it.
https://addons.mozilla.org/firefox/addon/tst-more-tree-commands/

**Comment by irvinm** [comment]
@piroor I think you can close this item.
