### ISSUE TITLE
tree is not restored when opening recently closed window

### ISSUE THREAD

**Issue by paravz** [piroor/treestyletab#2839]
## Short description
When i close a window with a tree and then restore it (via shortcut or history menu), the window restores with a flat list of tabs (the tree disappears). 

Toggling "Optimize tree restoration with cache" and enabling/disabling Tree Style Tab (by pressing F1) does not help.

This worked a few weeks ago and might be due to upgrade to Firefox 86.

## Steps to reproduce
- Create 2 windows in firefox
- Open a few tabs and arrange in a tree in each window
- Close one of 2 windows and then restore it (Ctrl+Shift+N or History > Recently closed windows)
- See that the window is restored with all tabs in flat list (the tree arrangement is gone)

## Expected result
- Tabs are restored with window's tree structure before closing

## Actual result
- Tree structure is not restored

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 86.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.7.3

**Comment by piroor** [comment]
I've tried with TST 3.7.3 Firefox 86.0 on Ubuntu 20.04LTS but I couldn't reproduce the problem. I think there is something more trigger.

**Comment by paravz** [comment]
I just tried on firefox 87.0 (newer than the report) and TST 3.7.3 and cannot reproduce it. Sorry for false alarm.
