### ISSUE TITLE
.discarded class for unloaded tabs is missing after updating to Firefox 87.0

### ISSUE THREAD

**Issue by mesvam** [piroor/treestyletab#2841]
styles like these no longer work
```
tab-item.discarded {
  opacity: 0.75;
}
```

**Comment by irvinm** [comment]
This is what I use and it still works.

`:root .tab.discarded { opacity: 0.60; filter: blur(0.6px); background: rgb(75, 75, 75, 0.4); } `

**Comment by irvinm** [comment]
Oh, on a side note, I tried your CSS and it worked fine.

**Comment by piroor** [comment]
It looks to be a problem of Firefox itself. TST just respects "discarded" status of tab objects got via WebExtensions API. I don't know why it happens but Firefox sometimes return wrong "discarded" status for restored tabs.

**Comment by silverwings15** [comment]
yep, works here as well

![image](https://user-images.githubusercontent.com/10742312/112357317-fe8bf180-8d01-11eb-91dd-4fcf91293634.png)

**Comment by mesvam** [comment]
> It looks to be a problem of Firefox itself. TST just respects "discarded" status of tab objects got via WebExtensions API. I don't know why it happens but Firefox sometimes return wrong "discarded" status for restored tabs.

This seems to be the case. Other add-ons like [this one](https://addons.mozilla.org/en-US/firefox/addon/loadtabonselect3/) failed to see discarded tabs as well, but they both worked on another machine with Windows 10 instead of 7. I've reported this to Mozilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1700708

**Comment by irvinm** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1700708 looks to be resolved in Firefox 90.

**Comment by piroor** [comment]
Wow, it's a good news!

**Comment by mesvam** [comment]
Ah forgot to close this. In summary, there was a weird bug where when the accessibility API was consumed by a third party application, Firefox would always think tabs were loaded, and reported discarded=false to addons
