### ISSUE TITLE
Redesign like Proton UI

### ISSUE THREAD

**Issue by xmha97** [piroor/treestyletab#2843]
A new look is coming to Mozilla Firefox.
Please redesign tabs style like proton UI.
Thanks.

**Comment by piroor** [comment]
Thanks, I didn't know that.

References:

Firefox/Proton - MozillaWiki
https://wiki.mozilla.org/Firefox/Proton

This is What Firefox's New 'Proton' Redesign Looks Like on Ubuntu - OMG! Ubuntu!
https://www.omgubuntu.co.uk/2021/02/try-firefox-proton-redesign-ubuntu

**Comment by piroor** [comment]
I've tried the Proton UI. The appearance of tabs looks quite similar to the vertical tabs on Microsoft Edge (Chromium-based version).

**Comment by piroor** [comment]
Background: Firefox Nightly + Proton UI
Foreground: Chromium Edge's vertical tabs
![image](https://user-images.githubusercontent.com/70062/112779527-e01b5280-9081-11eb-89bb-5ade24845ba2.png)

**Comment by xmha97** [comment]
> Background: Firefox Nightly + Proton UI
> Foreground: Chromium Edge's vertical tabs
> ![image](https://user-images.githubusercontent.com/70062/112779527-e01b5280-9081-11eb-89bb-5ade24845ba2.png)
> 

Nice.

**Comment by piroor** [comment]
Implemented experimentally with recent commits.
![image](https://user-images.githubusercontent.com/70062/113024810-237cda80-91c2-11eb-8b98-d9e60c67966c.png)

**Comment by xmha97** [comment]
Nice. 😍

**Comment by irvinm** [comment]
@xmha97 any reason to leave this open at this point?

**Comment by xmha97** [comment]
No
