### ISSUE TITLE
New feature request: Keyboard shortcut to access the context(righ-click) menu

### ISSUE THREAD

**Issue by rajeshmanivan** [piroor/treestyletab#2844]
After I right-click on the tab, I see keyboard-shortcuts to access functions in the context-menu-tree. but having to use the mouse to access context menu, disturbs the flow of keyboard usage.
I checked the keyboard-shortcut page for firefox addon, it didn't have this option listed there.

**Comment by rajeshmanivan** [comment]
It was stupid of me to ask this functionality from an addon developer, I realize this functionality should be developed by Mozilla.

**Comment by rajeshmanivan** [comment]
If this isn't possible, would you be able to add "Move tab to top" in firefox addon keyboard shortcuts menu. It currently only has option to move up.

![ff_move](https://user-images.githubusercontent.com/9722216/112743272-6a48b580-8fb3-11eb-955d-21b44f3c0dad.png)

**Comment by piroor** [comment]
Is it possible on the Firefox's native tab context menu? If not I think it is out of scope.

**Comment by jzedu** [comment]
Adding on to this thread, I was wondering if it is possible to remap the tree style tab toggle? Currently, my F1 key is bound to a system function and it would be very appreciate if I could bind it to another function key like F6. Thanks so much!

**Comment by piroor** [comment]
@Zhu-Justin It can be done with Firefox's built-in UI.

Manage extension shortcuts in Firefox | Firefox Help
https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

**Comment by irvinm** [comment]
@rajeshmanivan can you reply to piroor's comment from March 28th?

**Comment by irvinm** [comment]
@piroor I think this can be closed.  We can still discuss anything if needed after that.
