### ISSUE TITLE
Remap F1 Key

### ISSUE THREAD

**Issue by jzedu** [piroor/treestyletab#2846]
## Short description
My F1 key is mapped to a global hotkey, and I was wondering if there's any way to remap the tree-tab hotkey to any other function key like F6. Thank you so much! 

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
It can be done with Firefox's built-in UI.

Manage extension shortcuts in Firefox | Firefox Help
https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

**Comment by jzedu** [comment]
Thank you!
