### ISSUE TITLE
Do not open tab on drag and drop

### ISSUE THREAD

**Issue by ericschdt** [piroor/treestyletab#2850]
## Short description

I'd like to sort my tabs in the Tree Style Tab add-on, however, dragging a tab will load it, which is not desired.
I couldn't find an appropriate option for it within the context menu of the add-on to alter the behavior.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open multiple tabs
 4. Drag one tab to move it somewhere else in the tree structure

## Expected result
Tab is just moved

## Actual result
While dragging the tab opens

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 87.0
 * Version (or revision) of Tree Style Tab: 3.4.7

**Comment by ericschdt** [comment]
Sadly, looks like there's nothing much to do unfortunately: https://github.com/piroor/treestyletab/issues/2439

**Comment by irvinm** [comment]
https://addons.mozilla.org/en-US/firefox/addon/move-unloaded-tabs-for-tst/
