### ISSUE TITLE
Tab content jumps around when nearly full vertical height is used

### ISSUE THREAD

**Issue by MarkyC** [piroor/treestyletab#2852]
## Short description

When opening enough tabs to use nearly all the vertical height of the sidebar, the app gets stuck in a repaint loop, causing the `x` buttons to move around and high CPU usage. I'm fairly certain it's related to the height, since this issue doesn't occur when there are two tabs open (ie: it's not related to the site's I'm visiting changing the `<title>` tag or something like that)

Here's a video showcasing the problem: https://share.getcloudapp.com/GGuQovyb

## Steps to reproduce

1. Open enough tabs to almost use all vertical space
2. Open one more tab
3. Notice the `x` buttons dancing around and high CPU usage

## Expected result

no tab dancing

## Actual result

`x` buttons move around, high CPU usage: https://share.getcloudapp.com/GGuQovyb

## Environment

 * Platform (OS): Mac OS 11.2.3
 * Version of Firefox: 87.0
 * Version (or revision) of Tree Style Tab: 3.7.4

**Comment by irvinm** [comment]
Just a shot in the dark, but do you have any TST CSS?  Can you reproduce this behavior if you remove it all?

**Comment by MarkyC** [comment]
@irvinm I don't have any CSS, I'm using the _Photon_ theme in dark mode. I was able to reproduce it on the _High Contrast_ theme as well: https://share.getcloudapp.com/Z4uoq5bE

Maybe it has to do with the `border` used in these themes? Seems like it repaints because it's on the threshold of whether to show the scrollbar or not.

---

I dove a bit more into the source code and was able to prevent it for now by forcing the scrollbar to always show:

```
#tabbar {
    overflow-y: scroll; /* fixes jumping scrollbar */
} 
```

**Update**: the above mitigates it a bit, but it still happens occasionally.

**Comment by piroor** [comment]
Thanks, I missed that the guard mechanism for such infinite loop does not work for macOS specific hack. With the commit a3dd2ae TST won't trigger checking of overflow/underflow state of the tab bar except animation changes tab margins and tab size anymore.

By the way I've realized that the padding for overflow tab bar was applied to wrong side - it aimed to provide a draggable area for macOS scrollbar. It should be fixed with the commit 561776d.

**Comment by irvinm** [comment]
@MarkyC 3.8.0 has been released.  Can you verify if this has been fixed and close this item?

**Comment by MarkyC** [comment]
@irvinm Can confirm, 3.8.0 fixes this!

**Comment by sparkitus** [comment]
@piroor commit 561776d breaks TST for me. I get all the tabs jumping to the right when vertically shrinking a window past the point when they all fit on the screen, and they jump to the left when going back again. Backing out the code change or completely removing the workaround code fixes it for me.
