### ISSUE TITLE
Custom styles not applied for pinned discarded tabs on start

### ISSUE THREAD

**Issue by Heesz** [piroor/treestyletab#2853]
## Short description

Custom styles not applied for pinned discarded tabs on start.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Enable Restore previous session in General Startup Preferences.
 3. In about:config set `browser.sessionstore.restore_pinned_tabs_on_demand` as `true` for disable load pinned tabs on start browser.
 3. Install TST.
 4. Add custom style in TST for discarded tabs.
```css
tab-item.discarded {
	opacity: .3;
	background-color: orange !important;
}
```
 5. Open and pin few tabs.
 6. Relaunch browser.

https://user-images.githubusercontent.com/48418146/114284819-46797b00-9a5b-11eb-8ac4-aed6b206d016.mp4

## Expected result

Custom styles for discarded tabs applied for any discarded tabs.

## Actual result

Pinned discarded tabs showed without custom styles on start, but if click Discard Tab with Auto Tab Discard style is changed.

## Environment

 * Platform (OS): MacOS 10.15.7
 * Version of Firefox: Developer Edition 88.0b9
 * Version (or revision) of Tree Style Tab: 3.7.4

**Comment by piroor** [comment]
This looks to be caused with a reason same to #2841. Firefox has a bug around tabs opened with discarded state for now. The user style correctly applied if the tab is discarded manually via something addons like "Discard Tab".

**Comment by irvinm** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1700708 looks to be resolved in Firefox 90.
