### ISSUE TITLE
Open All as Tree including subfolder - order is reverse

### ISSUE THREAD

**Issue by Sada-Mio** [piroor/treestyletab#2863]
**## Short description**
bookmark subfolder opens in reverse order

**## Steps to reproduce**
Rightclick bookmark folder with subfolders in it
Tree Style Tab > Open All as Tree including subfolders

**## Expected result**
Folder A tree
   \- tabs...
Folder B tree
  \- tabs...
Folder C tree
  \- tabs...

TST 3.7.3 would create the tree in the order the subfolder was arranged in FF 

**## Actual result**
Folder C tree
   \- tabs...
Folder B tree
  \- tabs...
Folder A tree
  \- tabs...

TST 3.7.4 creates the tree in reverse order plus gets inserted oddly among existing tree. 

## Environment

 * Platform (OS): Windows 10 64bit
 * Version of Firefox: 87.0 64bit
 * Version (or revision) of Tree Style Tab: 3.7.4

**Comment by piroor** [comment]
Thanks, it looks a regression. The commit cc4b31f should fix it. When I changed behaviors of a utility method to open multiple tabs from parameters, I forgot to ignore bookmarks' "index" property as new tab positions.

**Comment by gilbertohasnofb** [comment]
@piroor Hi there, has this been regressed again? I'm on version 4.0.23, just tried migrating all tabs from another computer and they open in reverse order.

**Comment by piroor** [comment]
@gilbertohasnofb I've tried with TST 4.0.23 on Nightly 133.0a1 but I couldn't reproduce the problem reported at the initial comment. Screenshots:
![image](https://github.com/user-attachments/assets/a2074717-0f63-4b00-ae05-573d04c69bfe)
![image](https://github.com/user-attachments/assets/4f3c109a-0e14-4599-a2b3-b409e256cf20)
Could you describe steps to reproduce with details for your case?

**Comment by gilbertohasnofb** [comment]
Hi there @piroor, thanks for the reply! I ended up migrating to Tab Stash so I don't know if the issue was on my end or not. If you can't reproduce it, hopefully it is not present any more. But from memory, I simple tried opening all tabs from another define (with a few hundred tabs) and the order was reversed (new tabs in the beginning, i.e. left hand side of the browser).

**Comment by piroor** [comment]
Hmm, there are some possible triggers I imagine:

* `browser.tabs.insertAfterCurrent`=`true`
* other addons which control position of new tabs
