### ISSUE TITLE
New extension: TST Tab Search

### ISSUE THREAD

**Issue by NiklasGollenstede** [piroor/treestyletab#2865]
Hi piroor! This isn't a bug report or feature request, but more of a thanks and FYI:

I tend to have somewhere between hundreds and thousands of tabs "open" in Firefox, and TST already immensely helps managing that. One thing I was still missing was some way of searching through and/or filtering the tabs *in the tree*. Not everything can be organized in a tree (and by far not all my tabs are organized ^^).

Since I already knew about TST's extension API, I decided to have a look into what's possible in this case, and, lo and behold, there is a `subPanel` option!

So I went ahead and implemented [TST Tab Search](https://github.com/NiklasGollenstede/tst-search). It adds a search box at the bottom of TST's sidebar, allowing to search the titles of the tabs in the current window/sidebar, optionally case sensitive, as whole word, or by regular expression. Matching tabs will be highlighted in the tree, and/or non-matches will be suppressed.
There is certainly some more potential here, but as a first version it does the job.

Primarily I wanted to give you the feedback that your API is working very well, in particular also the `subPanel` (which I think isn't used much yet) works perfectly well (for this use case, at least).
I know how tricky the communication between extensions is, because either end can show up or disappear at any point without much warning. So I am actually (positively) surprised how stable your integration API is by now.

Apart from that, before I publish this on AMO, I wanted to ask whether you had any comments or concerns, e.g. regarding the name (which may imply association with TST itself).

**Comment by piroor** [comment]
Wow! You are the first challenger using the subpanel API except me! I didn't imagine it provides availability to implement this kind addon, and you done it so awesome - I'm so excited!

Now I'm inspired by your addon and planning to extend the subpanel API:

* Add ability to set fixed height for a specific addon (via API parameter)
* Add ability to memorize height of each subpanel (by TST itself)

Any other request around the API?

> Apart from that, before I publish this on AMO, I wanted to ask whether you had any comments or concerns, e.g. regarding the name (which may imply association with TST itself).

No problem, there are already some third-party helper addons including "TST" to their name :-) And, I'll post some feedbacks after I tried your addon more.

**Comment by piroor** [comment]
I've implemented new parameters for `subPanel`: `initialHeight` and `fixedHeight`. For more details please see the wiki: https://github.com/piroor/treestyletab/wiki/SubPanel-API#how-to-register-a-subpanel
And now TST saves/restores the height of the subpanel area for each provider addon.

**Comment by NiklasGollenstede** [comment]
Thank you for the nice reception!

Having the height of the sub-panel initially set and then remembered or (for something like this) fixed is indeed nice. I implemented the latter in TST Tab Search. I haven't tested it with an updated version of TST yet, though.

I'll probably publish TST Tab Search on AMO next week/-end, I want to test is in "production" for a while first. I'll keep you posted!

**Comment by kristofferR** [comment]
Awesome extension! My main wish would be to make it less tall though, the text is pretty useless.

It would be much better if it just added the search box.

**Comment by piroor** [comment]
@NiklasGollenstede FYI: you can try  the API improvements I told, with the latest development build: https://github.com/piroor/treestyletab#development-builds

**Comment by NiklasGollenstede** [comment]
@kristofferR You are probably referring to the text "TST Tab Search - DEV" above the search box? That is an UI element by TST itself, to let the user know that what is below is not part of TST itself, but provided by said extension. As such, it should generally remain there.
This case is somewhat extreme, as with such a small panel, the header almost doubles its overall size. I did add an option to hide that header via CSS, but with a big disclaimer:
> Hides the header above the search, that says something like "TST Tab Search - DEV".
> NOTE: That header is not part of this extension, but of TST itself, and from a UX perspective, should absolutely be there (by default). It may (in the future?) also be used to switch sub panels or do any number of other things. Please DO NOT raise issues about anything loke that with TST while this option is active!
> [x] I vow to have read the above and not to annoy TST's authors about it.

---

@piroor The new option mentioned above is somewhat invasive into TST, even with the disclaimer. Feel free to tell me to remove it.
Also, I am not sure how one currently would handle multiple `subPanel`s being registered at the same time.
And I did try the fixed panel height. It didn't quite work, see the PR.

I think once this is sorted out, I can publish TST Tab Search 🙏

**Comment by kristofferR** [comment]
> @kristofferR I did add an option to hide that header via CSS

Awesome, thanks! However, the text should clarify that Firefox needs to be restarted for it to work, though it wasn't functioning for a second.

A small black bar also appeared above when enabling the option, I'm not sure if that is an issue with the CSS code you added or something else?

<img width="320" alt="Skjermbilde 2021-04-26 kl  18 16 32" src="https://user-images.githubusercontent.com/481270/116116691-b9b9f880-a6bb-11eb-99c9-7ca88d372fac.png">

EDIT: Managed to get rid of it by re-enabling the header and positioning the search box perfectly before I disabled it again. Perhaps you should also clarify that in the text description.

**Comment by NiklasGollenstede** [comment]
It does say above:
> Advanced and/or experimental options, that may break and/or disappear at any time. These may also require a reload of TST, this extension or the sidebars to apply.
But I added another hint.

The size may have been off because this feature is expecting TST to support `subPanel.fixedHeight`, which the current main version doesn't yet.

**Comment by kristofferR** [comment]
Ah sorry, missed that, guess I only read the "Hide Header" text. Perhaps a paragraph space would make it easier to spot for dumb people like me. ;)

**Comment by piroor** [comment]
@kristofferR You can shrink the size of the subpanel header with custom user styles on TST, like:

```css
#subpanel-header,
#subpanel-header * {
  font-size: xx-small;
}
#subpanel-header {
  padding: 0;
}
```

Hiding its inner elements will shrink the header more. You can find hints from actual DOM tree with the debugger: https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-inspect-the-sidebar
Sorry but currently I have no plan to add a special option to do that, until it becomes required by large number users.  

----

@NiklasGollenstede 

Currently I have no policy about what should be allowed or disallowed for other addons via TST's API, except about security. Thus I don't blame what your addon does. Because I did similar things with my old addons.

However I have one knowledge about such a dangerous option: We sometimes expect people who use an options completely agree what will happen. But actually some people shot their own foot, for example when they saw a comment on Reddit, installed our addons, and activate the option without any understanding. I think we need to remind this is one of reasons why Mozilla killed XUL addons which could do everything on Firefox.

> Also, I am not sure how one currently would handle multiple subPanels being registered at the same time.

Currently the subpanel API expects just one subpanel per one provider addon. If you need to provide multiple different panels by one addon, you need to implement a switcher UI by yourself for now. (By the way I think different type subpanel should be provided by each provider addon for better user understandability.)

**Comment by NiklasGollenstede** [comment]
@piroor Cooli, will leave that option as is, then. (and yes, people can be very good at missing stuff ^^)

> Currently the subpanel API expects just one subpanel per one provider addon.

Sure, sure. That makes sense. Same as most other browser UI elements only allow one per type and addon.
What I actually meant though was what happens if you enable two (or more) extensions that have a subPanel _each_.
As far as I see it right now, TST will simply show the last one registered (but re-registration doesn't do anything).
I don't see an option for switching between them (hope I am not on on foot shooing business here :P).

**Comment by piroor** [comment]
>  What I actually meant though was what happens if you enable two (or more) extensions that have a subPanel each.

If the subpanel header does not work as a subpanel switcher, there is something untracked bug on TST itself. When there are multiple subpanel provider addons, TST should show a switcher popup for a click on the header area like as:
![image](https://user-images.githubusercontent.com/70062/116915120-93c9c080-ac86-11eb-8588-ea51820b37c1.png)

**Comment by piroor** [comment]
By the way currently there is no visual hint indicating it is a clickable UI, so I should do something more...

**Comment by NiklasGollenstede** [comment]
Ah. I do see it now. Given that there is no visual clue that it's there, I may indeed just have missed it in the past.
Some kind of button-ish appearance and `{ cursor: pointer; }` would be good :+1:.

While talking about that area: Can you tell me why TST Search doesn't get its icon there? I am passing the `icons` pretty much exactly the same way as [documented](https://github.com/piroor/treestyletab/wiki/SubPanel-API#how-to-register-a-subpanel), but the `<img>` there does not get a `src` attribute.

**Comment by piroor** [comment]
Oops, it is a problem of TST - it currently uses only the icon with exact 16px size. With the commit f323d04 now non 16px size icons will be shown.

**Comment by NiklasGollenstede** [comment]
Nice. The Icon now shows up, and the select button is now detectable as such.
The placement of the icon and button still seem a bit off. I added this as custom CSS:
```css
#subpanel-header * {
    line-height: 1.418; /* seems to be the default, but set it explicitly to know know the height to assign to the img */
}
#subpanel-header {
    padding: 0.2em 0.2em 0.2em;
}
#subpanel-selector-anchor {
    padding: 0;
}
#subpanel-selector-anchor span.icon > img,
#subpanel-selector span.icon > img {
    height: 1.418em;
    max-height: none;
    max-width: none;
    width: 1.418em;
    padding: .2em;
    display: inline-block;
    vertical-align: bottom;
}
#subpanel-selector span.icon {
    margin-right: 0;
}
```

**Comment by irvinm** [comment]
@NiklasGollenstede is there more to discuss on this item or can you close it?

**Comment by irvinm** [comment]
@NiklasGollenstede just a friendly reminder on this on.

**Comment by NiklasGollenstede** [comment]
Sorry. I still have a couple of suggestions for TST, and @piroor also [for the search](/NiklasGollenstede/tst-search/issues/10), but we should indeed discuss that seperately.

This week I also [finally got around](/NiklasGollenstede/tst-search/issues/8) to publishing [TST Tab Search on AMO](https://addons.mozilla.org/en-US/firefox/addon/tst-search/).
And as I see, @piroor also already added it to the README!

So indeed, all done here, thanks!

**Comment by garymoon** [comment]
Thanks so much to Niklas and piroor (and everyone else involved) for this! It's an amazing improvement for us unrelenting tab-whores! :blue_heart:
