### ISSUE TITLE
[minor] Tineye extension opens new pages as a sibling instead of child. Can I change this?

### ISSUE THREAD

**Issue by mzso** [piroor/treestyletab#2868]
Hi!

This is fairly annoying. It would make a lot mores sense for it to be a child. Can I do something to change this?

https://addons.mozilla.org/firefox/addon/tineye-reverse-image-search/

**Comment by piroor** [comment]
This cannot be solved by TST side, some changes need to be done by TinEye side. `content_script.js` should provide `openerTabId` for new tabs, like:

```diff
$ diff -uNr content_script.js.orig content_script.js
--- content_script.js.orig      2021-04-22 01:02:00.720573500 +0900
+++ content_script.js   2021-04-22 01:03:29.334081600 +0900
@@ -35,20 +35,21 @@

         // Get new tab index and open new tabs next to current one
         var new_tab_index = tabs[0].index + 1;
+        var openerTabId = tabs[0].id;

         // Check where the user wants the url to be open
         switch(tab_visibility) {
             case "background":
-                browser.tabs.create({url: url, active: false, index: new_tab_index});
+                browser.tabs.create({url: url, active: false, index: new_tab_index, openerTabId});
                 break;
             case "foreground":
-                browser.tabs.create({url: url, active: true, index: new_tab_index});
+                browser.tabs.create({url: url, active: true, index: new_tab_index, openerTabId});
                 break;
             case "current":
                 browser.tabs.update(tabs[0].id, {url: url});
                 break;
             default:
-                browser.tabs.create({url: url, active: false, index: new_tab_index});
+                browser.tabs.create({url: url, active: false, index: new_tab_index, openerTabId});
         }

     });
```

**Comment by piroor** [comment]
I've reported a feedback to the support e-mail address:

```
Hello,

I'm the developer of a Firefox addon Tree Style Tab.

https://addons.mozilla.org/firefox/addon/tree-style-tab/

Recently I've got a report from a user who using TinEye addon. The
reporter said that TinEye opens the search result tab as the next
sibling tab always, but it should become a "child" of the current tab.

https://github.com/piroor/treestyletab/issues/2868

After a research I've realized that TinEye doesn't set `openerTabId` for
new tabs. If TinEye provides the information, the compatibility with
other tab related addons and Firefox itself will be improved more:

* On Firefox's default config, a new tab opened with openerTabId will
  be opened next to the active tab automatically.
  Moreover, second and third tabs are placed next to the last opened
  "child" tab by Firefox itself. You don't need to calculate `index`
  for the search result tab.
* Other addons like my Tree Style Tab can detect search result tabs
  as children of the active tab automatically. There are some more
  tree-UI tab management addons, not only mine.

The attached diff describes how the `openerTabId` should be provided. I
hope the TinEye addon become improved more.

regards,
```

**Comment by mzso** [comment]
@piroor
Thanks for the info, and the report as well.

**Comment by mzso** [comment]
[**@piroor**](https://github.com/piroor) commented on [2021. ápr. 21. 18:05 CEST](https://github.com/piroor/treestyletab/issues/2868#issuecomment-824180157 "2021-04-21T16:05:57Z - Replied by Github Reply Comments"):
> This cannot be solved by TST side, some changes need to be done by TinEye side. `content_script.js` should provide `openerTabId` for new tabs, like:
> ...

Thanks, it works. I did it locally for the time being. Fortunately my profile is already set up to run unsigned extensions.

**Comment by irvinm** [comment]
@mzso can you close this item as there is nothing to do on the TST side?

**Comment by mzso** [comment]
[**@irvinm**](https://github.com/irvinm) commented on [2021. máj. 3. 12:59 CEST](https://github.com/piroor/treestyletab/issues/2868#issuecomment-831186456 "2021-05-03T10:59:17Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso) can you close this item as there is nothing to do on the TST side?

I can. Piroor, might have closed it if he wanted to, though.

**Comment by irvinm** [comment]
@mzso I know that based on previous discussions, if Piroor closes the item that you can not re-open it.  If you close it, then you can re-open it at a later point in time if needed.  Thanks for closing.

**Comment by jgould22** [comment]
My apologies for the wait however I was able to implement the changes above and provide the `openerTabId ` to the create call which should help solve this issue.

You will need to update your TinEye extension to 1.5.1
