### ISSUE TITLE
Scrollbar on top of collapse/expand arrows on MacOS

### ISSUE THREAD

**Issue by gpkc** [piroor/treestyletab#2869]
I'm running MacOS 11.2.3, FF 88.0 and TST 3.7.4. The problem is that there's a vertical scrollbar every time I start scrolling the tabs. If I want to expand/collapse one of the subtrees, the scrollbar is in front of the button. It disappears in a few seconds but that's still very annoying.

A possible solution would be to hide that scrollbar since I don't need it as I can just scroll.

**Comment by piroor** [comment]
I expected that an extra padding should avoid this problem, but codes for that have not worked as expected on recent versions. The commit 561776db7712fe8dd0197c567328017e0ae5776a should fix the problem.

**Comment by irvinm** [comment]
@gpkc can you confirm this is fixed and close this item?

**Comment by irvinm** [comment]
@gpkc 3.8.0 has been released.  Can you verify if this has been fixed and close this item?

**Comment by gpkc** [comment]
@irvinm It's working well now, thanks
