### ISSUE TITLE
Feature Request: Ability to close all child tabs but not the parent.

### ISSUE THREAD

**Issue by shelleybutterfly** [piroor/treestyletab#287]
Right now it's easy to close a whole tab tree either by collapsing the parent tab and clicking the 'x', or by right-clicking and choosing "Close this Tree". However, I am frequently finding myself browsing a bunch of sub tabs, wanting to return to the original and having to go through by hand closing each of the children to leave the tab I started with open.

A context menu item for "Close all children" or something similar would be great, or something like ctrl- or alt- clicking the 'x' or some other single-action shortcut would work even better for my browsing habits.   

(BTW, Sorry if I missed something in the other requests or in the existing functionality; I have gone through and searched the current issues and I haven't found anything about it, but there's a lot already there. :) Thank you for a great product, I switched to Firefox from Chrome specifically for this extension!)

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
