### ISSUE TITLE
Feature suggestion: save position of tabs when you close the browser. Sucks having to position them again every time I open it.

### ISSUE THREAD

**Issue by Airyleech** [piroor/treestyletab#2876]

**Comment by piroor** [comment]
Please fill the issue template to describe what's happen on your environment. I'm not a professional about your PC environment, so all required information to investigate things need to be described by yourself.

**Comment by harl** [comment]
I'm on FF 88.0 and TST 3.7.4 and I don't experience this behaviour.

I'm not sure what "positioning" means in this context, but as my tabs neither lose their position during a browser session (in any way that I would have noticed, including closing and reopening the sidebar), nor do they reposition themselves or get repositioned by TST when a new browser session is started, my prevalent assumption would be that there's another add-on involved.

Please try to evaluate this assumption on your side by disabling all add-ons except for TST, then closing all browser windows, starting FF again and testing whether your tabs behave the way you expect.
If they don't, disable TST as well and try again.  Then work your way backwards, enabling add-ons one by one to see which one is causing the issue you experienced.
Possibly check back here with the results.

**Comment by Airyleech** [comment]
> 
> 
> Please fill the issue template to describe what's happen on your environment. I'm not a professional about your PC environment, so all required information to investigate things need to be described by yourself.

My bad, forgot to close this issue. This only happens with the tabby tabs and window manager. When I close and open it it positions itself.
