### ISSUE TITLE
(Request/Help) Context menu access key customisation

### ISSUE THREAD

**Issue by SHHSSH** [piroor/treestyletab#2878]
## Short description

An unusual request, not so much an issue.

For years I have attempted to customise my FF context menu to varying degrees of success.
Some things are easily done through userChrome, some are not.

I am looking to change my access keys in the context menu for Collapse this tree & Expand this tree.

Currently I have such hotkeys set in TST's shortcut config, however, occasionally it's more efficient to just right click on the tab and select from the context menu (this helps in situations where the tab is discarded and I don't want to left click on it)

I have hotkeys set as;
Alt+J - Collapse current tree (Default access key in context menu "s")
Alt+K - Expand current tree (Default access key in context menu "a")

I have gone through so much documentation trying to customise this, as well as attempting to look deep into TST's extension config after decompiling.

https://www.reddit.com/r/firefox/comments/7dvtw0/guide_how_to_edit_your_context_menu/
^ This was the most informative to a degree, however still a nuisance as I was unable to actually customise any Hotkeys.

http://forums.mozillazine.org/viewtopic.php?f=38&t=2787563
http://forums.mozillazine.org/viewtopic.php?f=38&t=1630255
http://forums.mozillazine.org/viewtopic.php?f=7&t=415111

I seek your help guru @piroor, is there any was whatsoever I can set a custom context menu access key so it can be synergistic with the right side of the keyboard that I prioritise? I.e; Collapse current tree "j" & Expand current tree "k"

Also Collapse/Expand selected trees. <----- ***EDIT***

Thank you for any help you can offer.

**Comment by piroor** [comment]
Hmm, it is not so easy.

Here is the definition of the access key of the "Expand this tree" context menu item:
https://github.com/piroor/treestyletab/blob/b4f2ebf551fc7b67a9a937c1d708cde0e58fc146/webextensions/_locales/en/messages.json#L276

As you saw it is defined as a part of menu label: `"Exp&and this Tree"`, the character next to `&` is detected as the access key by Firefox itself. [This spec is described at the API document.](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/create#parameters) To change the access key we need to replace the label text itself dynamically. I think such a customizability looks beyond the scope of TST - it will increase codes of TST and make it more complicated. Sorry but I'm negative to reduce TST's maintainability for very limited usecases...

(I don't know any guide line about access key definitions published by Mozilla, so I refer the one written by Microsoft: https://docs.microsoft.com/en-us/windows/uwp/design/input/access-keys The document just describes how application author should define access keys, and there is no information about user-customizable access keys. I think that this fact means "access key is basically not expected to be customized by the user".)

----

By the way, a request like "TST should use more easy-to-use access keys" is reasonable, indeed current access keys are not satisfies the guide line I referred.

**Comment by SHHSSH** [comment]
Alright mate, I understand....

Even when you added the collapse tree features/helper add on all that time ago, it did messy TST up a little bit.
So I appreciate you even considering that back then.

Thanks for your clarification, I was merely hoping you knew of a potential way.
