### ISSUE TITLE
Duplication of (Tree Style Tab) tabs, after a link that is opened in a new discarded tab is automatically assigned to a (Firefox Multi-Account Containers) container, when the discarded tab is clicked

### ISSUE THREAD

**Issue by grahamperrin** [piroor/treestyletab#2880]
## Short description

Unexpected duplication of tabs. 

A conflict that can involve three or more extensions. 

As far as I can tell, the conflict is essentially between two: 

1. Multi-Account Containers
2. Tree Style Tab.  

## Steps to reproduce

 1. With a refreshed profile, add four extensions and do not allow them in private tabs
 2. Mozilla-recommended [Auto Tab Discard](https://addons.mozilla.org/addon/auto-tab-discard/) `0.4.7` by @rNeomy
 3. [Open link in new discarded tab](https://addons.mozilla.org/addon/open-link-in-new-discarded-tab/) `0.4` 
 4. Mozilla [Firefox Multi-Account Containers](https://addons.mozilla.org/addon/multi-account-containers/) `73.0`
 5. Mozilla-recommended [Tree Style Tab](https://addons.mozilla.org/addon/tree-style-tab/) `3.7.4`
 6. click the Multi-Account Containers toolbar button
 7. get started …
 8. decline the invitation to synchronise
 9. open https://github.com/piroor/treestyletab#user-content-feature-requests in a new tab
 10. use the address bar menu to **always** open `github.com` in the _Personal_ container
 11. open https://github.com/rNeomy/auto-tab-discard/issues/215 in a new tab
 12. the _always_ decision was not respected
 13. ☑ Remember my decision for this site
 14. Open in Personal Container 
 15. use the context menu for any `github.com` link to either **Open in New Discarded Tab** or **Open link in new discarded tab**
 16. click the new tab
 
## Expected result

17. load of content in the clicked tab

## Actual result

17. **duplication** of, and load of content in, the clicked tab.

## Environment

```text
% date ; uname -v
Thu 29 Apr 2021 01:30:20 BST
FreeBSD 14.0-CURRENT #93 main-n246330-5eb9c93a20d: Tue Apr 27 05:14:26 BST 2021     root@mowa219-gjp4-8570p:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG 
% pkg query '%o %v %R' firefox
www/firefox 88.0_2,2 FreeBSD
% 
```

## Thoughts

@piroor if you believe that this issue will require a fix in Mozilla code for Firefox, let me know, I can `@` someone who recently did great work with issues that involve the discarded state. 

In parallel, I'll attempt to find corresponding issues at https://github.com/mozilla/multi-account-containers/issues/

**Comment by Fanolian** [comment]
Similar to https://github.com/mozilla/multi-account-containers/issues/1617. You don't need TST for it.

**Comment by piroor** [comment]
@grahamperrin As @Fanolian told this problem does not depend on TST. I've confirmed duplicated tab problem without TST.
