### ISSUE TITLE
API: removed tabs states sporadically re-spawn in some sidebar instances

### ISSUE THREAD

**Issue by NiklasGollenstede** [piroor/treestyletab#2882]
## Short description

This is hard to describe, because it (so far) seems non-deterministic.
Best I can tell is that sometimes, when another extension uses `'add-tab-state'` and then `'remove-tab-state'`, and the user afterwards moves tabs in the tree (also e.g. as a consequence of closing other tabs), the moved tab appears _in a particular sidebar instance_ with some of the removed states.

Here is a really odd example, where the sidebar is open twice, once correctly without states, and once opened manually, where the first non-pinned tab has two re-spawned states (`tst-search:matching` and `tst-search:not-matching`, which logically also were never added at the same time). I verified with the inspector on the actual sidebar that the states indeed do not exist there:
![image](https://user-images.githubusercontent.com/10552031/116817827-9e8e3380-ab68-11eb-9b2f-2169316ae934.png)
There seems to be some mismatch here between TST's internal data model and what gets rendered in the sidebar(s)

This is probably causing https://github.com/NiklasGollenstede/tst-search/issues/5.

## Steps to reproduce

I am using trunk as of yesterday (3c93849b979f95b5b355b4dae558e2178a18c147) in a profile with only TST, and [TST Tab Search](https://github.com/NiklasGollenstede/tst-search/) to test this.

This took a while, but seems reproducible:

1. `Ctrl+N`
2. Middle click "New Tab"
3. Search for "new", press Enter: ![image](https://user-images.githubusercontent.com/10552031/116818125-0002d200-ab6a-11eb-9848-4297f53e1860.png)
4. Type `.` for "new.". The search fails, and the classes `tst-search:matching` (bold) and `tst-search:highlight` (red) are removed, `tst-search:not-matching` (compresss) is added: 
![image](https://user-images.githubusercontent.com/10552031/116818187-5d971e80-ab6a-11eb-8ec6-e6617c8127ae.png)
5. Drag the lower tab to the top of the list, promoting it to be the first top level tab. TST Tab search does not respond to that in any way, i.e. it did not send _any_ messages to TST, but `tst-search:matching` (bold) and `tst-search:highlight` (red) are both there again: 
![image](https://user-images.githubusercontent.com/10552031/116818240-a8b13180-ab6a-11eb-8491-d2f0eb64d071.png)

## Expected result

Removed states should remain removed.

## Actual result

Removed states reappear.

## Environment

 * Version of Firefox: 88.0 (64-bit) `apt` for Ubuntu 20.04.3
 * Version (or revision) of Tree Style Tab: trunk (3c93849b979f95b5b355b4dae558e2178a18c147)

**Comment by piroor** [comment]
Thanks! On the step 4 actually the tab has both `tst-search:macthing` and `tst-search:not-matching`. After investigation I've realized that tst-search sends a nested array instead of a simple string array. TST stores state values given via API directly and adds/removes it via `Set.prototype.add/delete`. These methods compares objects via the `===` operator, and they treat array values given via API as different always, because they always be new instances. Thus states given by tst-search via the API are never deleted.

I've introduced changes 9065286 and d3d2e56 to make those APIs more safe. Now TST accepts such non-string states and convert to strings automatically.

**Comment by NiklasGollenstede** [comment]
Ah, So to summarize: The Search was incorrectly passing an array of arrays of states when removing them (but did add them correctly). Removing states was handled differently by different parts of TST. Passing arrays to (I guess) `<classList>.toggle()` stringifies the arguments, and thus worked in removing the states, wile removing the class as array from the `Set` in the backend did not. Thus the states reappeared when the tabs got re-rendered.

Using `[].concat()` incorrectly was obviously silly of me, but at last now that inconsistent handling of states within TST is now fixed.

Thank you for looking into this!
