### ISSUE TITLE
[BUG] The content of TST keeps rocking from side to side

### ISSUE THREAD

**Issue by xialvjun** [piroor/treestyletab#2886]
## Short description
The content of TST keeps rocking from side to side.

https://files.catbox.moe/h2ivy8.mov

## Steps to reproduce
Hard to reproduce.

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): macOS Catalina 10.15.5 (19F101)
 * Version of Firefox:  90.0a1 (2021-05-05) (64 位)
 * Version (or revision) of Tree Style Tab:  3.8.0

**Comment by piroor** [comment]
Thanks, after I fixed the problem I did some refactoring and that reintroduced the problem... The commit 49c327b should fix this problem truly.
