### ISSUE TITLE
Ctrl-clicking the "+" button at the bottom of TST's panel doesn't respect the preferences

### ISSUE THREAD

**Issue by ngirard** [piroor/treestyletab#2889]
Using TST 3.8.1 on Firefox 88.0 and Ubuntu 21.04.

Ctrl-clicking the "+" button at the bottom of TST's panel creates a chils tab instead of an independant tab, as I used to configure it in the preferences.

This defect is the very reason I went to the preferences and discovered #2888 ; but perhaps #2888 itself could be the reason ?

**Comment by piroor** [comment]
I've tried TST 3.8.1 on Firefox 88.0 on Ubuntu 20.04LTS and they looks working as expected. Ctrl-click on the "+" button opens a new tab as a next sibling, according to the option I configured. Could you try with a clean profile?
https://github.com/piroor/treestyletab/wiki/How-to-run-Firefox-with-a-clean-profile

**Comment by ngirard** [comment]
I'm puzzled by this one too.
I'm a bit confused. Sorry for the low quality of my reporting, I'll report back later on.

**Comment by ngirard** [comment]
I can't reproduce it either.
Closing for now.
