### ISSUE TITLE
Child tab insertion position 2 is not settable on Waterfox Current after you switch it to 3 or 4, setting 1 after that sets 2 instead

### ISSUE THREAD

**Issue by ninep9up** [piroor/treestyletab#2890]
I don't know if it should work at all, but I struggle to get it work
Are there perhaps any hidden options

**Comment by piroor** [comment]
Please fill the issue template, and describe steps to reproduce incoluding exact option name you choose. Investigation based on misunderstanding from fuzzy information will never solve the problem.

**Comment by ninep9up** [comment]
Well, I try to press this or above, but it never stays here, instead it's just either on option 3 (as pictured) or 4, WF is the last to date Current

![Untitled](https://user-images.githubusercontent.com/24707777/117517041-75740580-afa3-11eb-8d2d-1dc61bfdf7c2.png)

Sorry, if you consider me too lazy

**Comment by irvinm** [comment]
Waterfox G3.2.1 and TST 3.8.1 in a clean profile I had no problems selecting any of the 4 options.  Please try a clean profile to reproduce the issue without all of your other addons.

![image](https://user-images.githubusercontent.com/979729/117547748-4ee3b800-afff-11eb-8901-f7a85d663855.png)

**Comment by ninep9up** [comment]
Strangely, it works now (with all the addons on). Maybe it's episodic. I'll dig into it.

**Comment by ninep9up** [comment]
Aha, I get it now. It doesn't switch after you set it to 3.

**Comment by ninep9up** [comment]
Moreover, after you set it to 1 after that, it stays on 2 somehow. My initial thought was wrong, I guess. It lets you switch, it's just not the option you want, so somehow I might've missed (?) that it was putting itself out of place? Super strange

**Comment by ninep9up** [comment]
Same with the next

**Comment by ninep9up** [comment]
I still find it weird that I've might set it to other than that (must've been 1 that switched to 2?) before this testing

**Comment by ninep9up** [comment]
Option 1 wasn't working and I feel that it been 3 after the clickings

**Comment by irvinm** [comment]
Can you also confirm if you see the same behavior with the configuration settings for TST @ about:addons?

![Snag_2305d2](https://user-images.githubusercontent.com/979729/117652963-d2b5b580-b161-11eb-88b4-bb83ebdcb934.png)

**Comment by ninep9up** [comment]
It works there, so I don't

**Comment by irvinm** [comment]
@piroor there is definitely a problem with Waterfox and using the TST right-click menu around the "insert position of new child tabs".  It looks to me that selecting the 3rd or 4th option works fine, but: 

- Selecting the 2nd item doesn't change the selection from the 3rd item
- Selecting the 1st item shows it updated on about:addons, but still shows selecting the 2nd item on the right-click menu

![image](https://user-images.githubusercontent.com/979729/120487491-03b19080-c384-11eb-9d73-729f54b6b465.png)

![image](https://user-images.githubusercontent.com/979729/120487002-9271dd80-c383-11eb-974c-5dd2752a9417.png)

**Comment by piroor** [comment]
Finally I've realized that there is a typo and only the right-click menu on the toolbar button is broken. Thanks!
