### ISSUE TITLE
Undoing via ctrl+t almost always restores branches erroneously.

### ISSUE THREAD

**Issue by mzso** [piroor/treestyletab#2892]
## Short description
When I press undo after closing branches the tabs of the branch are restored, but they get split and some are added as children to the following sibling's tab.

## Steps to reproduce

 1. Have several branches on top level
 2. close a full branch somewhere in the middle.
 3. undo via ctrl+shift+t
 4. observe restore branches

## Expected result
Restore branch as it was

## Actual result
Children are split off, and added elsewhere

Here's a screencast of the issue:
https://drive.google.com/file/d/1plX5DuuJkXtTKG7hv2pzV2DlLP44Si94/view?usp=sharing
The cursor is drawn to the wrong position for some reason, slightly confusing. (Never got this before...)

## Environment

 * Platform (OS): Win10
 * Version of Firefox: 87.0b9
 * Version (or revision) of Tree Style Tab: 3.8.1

**Comment by irvinm** [comment]
@mzso can you clarify the actions you are doing to "close the branch" and "undo the delete branch"?  

To close the branch, are you collapsing the branch and clicking the "X"?  
For restoring, ctrl+t is usually for creating a new tab ...

**Comment by irvinm** [comment]
@mzso any updates?

**Comment by mzso** [comment]
[**@irvinm**](https://github.com/irvinm) commented on [2021. jún. 12. 20:46 CEST](https://github.com/piroor/treestyletab/issues/2892#issuecomment-860093447 "2021-06-12T18:46:12Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso) any updates?

Still sucks. It doesn't seem to matter how I close them. X or hotkey. Sometimes I close multiple selected tab, somtimes a branch via X. Often it happens when the tabs closed have a lot of time between their closing, yet multiple of them are restored.
Sometimes the tree is visually messed up. Right now I had a tab that appeared to be a parent to many tabs. Yet when I collapsed it only two tabs got hidden. And when I moved it it got corrected, and was showing only two child tabs. Only happens via ctrl+shift+t. I never saw this when using the recently closed tabs menu.

Here are my settings:
[configs-treestyletab@piro.sakura.ne.jp-2020-06.zip](https://github.com/piroor/treestyletab/files/6642842/configs-treestyletab%40piro.sakura.ne.jp-2020-06.zip)

I don't think anything private's in them.

> For restoring, ctrl+t is usually for creating a new tab ...

Yeah. I made a mistake. It's ctr+shift+t.

**Comment by irvinm** [comment]
Just for kicks, I fired up Windows Sandbox, installed Firefox, loaded your settings ... and unfortunately didn't have any problems closing or restoring tabs.

I tried:

- Deleting a single tab and restoring with ctrl-shift-t
- Multi-selecting a parent and two children, closing them, then restoring with ctrl-shift-t
- Collapsing a tree, closing with the "X", then restoring them with ctrl-shift-t

You could probably try the same using Windows Sandbox or just trying a new profile.  Sorry I wasn't able to reproduce.

**Comment by piroor** [comment]
I don't know this is same to @mzso's case but I saw similar problem with these steps:

1. Start Firefox.
2. Install TST.
3. Install "TST Active Tab in Collapsed Tree".
4. Prepare tabs as:
   ```
   + A (index=0)
     + B (index=1)
       + C (index=2)
   + D (index=3)
   ```
5. Set B active.
6. Collapse tree A. (Then B is still active in the collapsed tree.)
7. Middle-click A to close the tree. (Confirm to close if necessary.)
8. Hit Ctrl-Shift-T.

Expected result:

```
+ A
  + B
    + C
+ D
```

Actual result:

```
+ A
+ D
  + B (child of A)
    + C
```

This is caused by the restoration order of tabs. Tabs are restored in the order: B, C and A. Then what happens is:

1. There are tabs:
   ```
   + D (index=0)
   ```
2. B is restored with its original index 1:
   ```
   + D (index=0)
   + B (index=1)
   ```
3. C is restored with its original index 2, and attached to B:
   ```
   + D (index=0)
   + B (index=1)
     + C (index=2)
   ```
4. A is restored with its original index 0, and attached to A:
   ```
   + A (index=0)
   + D (index=0 => 1)
     + B (index=1 => 2)
       + C (index=2 => 3)
   ```

**Comment by piroor** [comment]
The commit 0c59c9b should fix my case. @mzso Could you try the latest development build?: https://github.com/piroor/treestyletab#development-builds

**Comment by mzso** [comment]
[**@piroor**](https://github.com/piroor) commented on [2021. jún. 16. 17:14 CEST](https://github.com/piroor/treestyletab/issues/2892#issuecomment-862466375 "2021-06-16T15:14:22Z - Replied by Github Reply Comments"):
> The commit [0c59c9b](https://github.com/piroor/treestyletab/commit/0c59c9bc288ba4d05acbd07ad9d830eeb4cd8d2c) should fix my case. [@mzso](https://github.com/mzso) Could you try the latest development build?: [https://github.com/piroor/treestyletab#development-builds](https://github.com/piroor/treestyletab#development-builds)

I'll try it.

**Comment by mzso** [comment]
@piroor 
After some testing, I didn't notice the tabs getting actually restored to the wrong place. However once TST got visually broken. It's this weird thing where a tab is show some place but is actually somewhere else. I pressed the collapse arrow and the tab getting collapse were some distance away. I don't think I did anything special only closing and restoring tabs quickly.

What I definitely still get is more than the tab(s) restored via the last action. Close some tabs with separate action, with some second between them, then ctrl+shift+t to restore the last one and several other tabs are restored for some reason. As if TST or FF can't tell what how many tabs to restore.

**Comment by piroor** [comment]
I still want effective steps to reproduce the problem on my environment. If you successfully find out that, please tell me details in the format like of my report's. If it depends on platform performance of other addons, it looks impossible for me to fix it without any help...

FYI: just a workaround, you'll see fixed tree by drag and drop. For example, if you see a tree like:

```
+ A
+ B
  + B1 (child of B)
+ C
  + B2 (child of B)
```

then please move the tab B above A, then B and its all descendants will be moved together. As the result you'll see fixed trees like:

```
+ B
  + B1 (child of B)
  + B2 (child of B)
+ A
+ C
```

**Comment by mzso** [comment]
@piroor 

What decides which tabs to restore, FF or TST?

**Comment by piroor** [comment]
Keyboard shortcuts around closing and restoring tabs are handled by Firefox. And TST observes the event and may do something. On the other hand, mouse actions on the sidebar are always handled by TST. For example, actions to close tabs:

* When you press Ctrl-W, **Firefox** closes just the active tab. 
  * After that, when a closed tab has collapsed descendants, **TST** closes them also. (A)
* Middle-click on an expanded tree is handled by **TST**, TST will close just the clicked tab. (B)
* Middle-click on a collapsed tree is handled by **TST**, TST will close the tab and its all descendants at a time. (C)
* Left-click on the "x" button of an expanded tree is handled by **TST**, TST will close just the clicked tab. (D)
* Left-click on the "x" button of a collapsed tree is handled by **TST**, TST will close the tab and its all descendants at a time. (E)
* Context menu commands in the tab context menu on the sidebar are always handled by **TST**, TST will close just single tab or whole tree by the context. (F)

And, there are some actions to restore tabs:

* When you press Ctrl-Shift-T, **Firefox** tries to restore the last closed tab or tabs. (G)
* When you choose "Undo Close Tab" context menu command on the sidebar, **TST** tries to restore the last closed tab or tabs. (H)

There are some cases multiple tabs are closed via a single API call: cases C, E and F. If the last tab closed is one of these cases, Firefox tries to restore all of last closed tabs on both cases G and H.
