### ISSUE TITLE
Children tabs often disappear when parent is expanded

### ISSUE THREAD

**Issue by MayeulC** [piroor/treestyletab#2894]
## Short description
Sometimes, tabs become inaccessible. I can see they are open, but can't access them.

Collapsed:
![image](https://user-images.githubusercontent.com/3952726/117797773-b2185900-b250-11eb-9c96-0beca7b0cd72.png)

Expanded:
![image](https://user-images.githubusercontent.com/3952726/117797848-c6f4ec80-b250-11eb-9aa6-5d63cf6b33ee.png)

Closing collapsed:
![image](https://user-images.githubusercontent.com/3952726/117797923-dbd18000-b250-11eb-814d-fe0650621d65.png)

If I close an expanded tab, children just disappear (and I can get back to the previous step with Ctrl-Shift-T):
![image](https://user-images.githubusercontent.com/3952726/117798029-f7d52180-b250-11eb-828c-c7af61380591.png)

In any case, the only way to reach the tab is trough the address bar, with its "switch to tab" feature. If I do so, I can access the tab, but it will disappear again as soon as I move away from it:
![image](https://user-images.githubusercontent.com/3952726/117799464-6cf52680-b252-11eb-8585-3de602d8a3c2.png)

Unless it is a sibling, in which case I can temporarily make it appear again, but both will disappear as soon as I select the parent or another tab: 
![image](https://user-images.githubusercontent.com/3952726/117799725-b3e31c00-b252-11eb-8d8d-13c8f7ac0f70.png)

The only way to remediate the issue seems to be closing the tab, then opening back again with ctrl-shift-t. The tab then won't disappear again.

## Steps to reproduce

Unfortunately, I have trouble reproducing the issue in a reliable way. **It could be related to panorama tab groups**, plus having a large number of tabs (>600). I can reproduce it on two computers, but only sporadically.
I hope other people will chime in this thread to help reproduce the bug.

## Expected result
Children tabs should appear below the selected tab when expanded, as well as in the regular tab bar, and the tab list right to the "new tab" plus button.

## Actual result
The tab becomes unreachable unless you know its name.

## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: 88.0.1
 * Version (or revision) of Tree Style Tab: 3.8.1

**Comment by irvinm** [comment]
@MayeulC this certainly feels like it could be related to panorama's ability to hide tabs.  I am wondering if when you see this event again, if you just disabled panorama if the tabs would be displayed properly.  Also, it is unfortunate that it appears that project hasn't had any updates in over a year.  @piroor any thoughts?

**Comment by piroor** [comment]
@MayeulC As @irvinm commented, such a status may be produced by panorama, if you choose TST options => "Tree Behavior" => "When visibility of tabs are changed by other addons" => "Keep tree structure including hidden tabs". Is the tab invisible in TST's sidebar visible on Firefox's native tab bar? Then TST works correctly and the panorama addon looks to fail updating hidden/shown status of tabs. On the other hand, if a tab visible on Firefox's tab bar is invisible on TST sidebar, it is a fault of TST.

**Comment by MayeulC** [comment]
> @MayeulC As @irvinm commented, such a status may be produced by panorama, if you choose TST options => "Tree Behavior" => "When visibility of tabs are changed by other addons" => "Keep tree structure including hidden tabs".

Well, that was the default, so I left it at that. But it doesn't seem to affect the outcome if I toggele

> Is the tab invisible in TST's sidebar visible on Firefox's native tab bar?

No, nor it is visible on the drop-down near the tab bar. It is visible on "hidden tabs", though

> Then TST works correctly and the panorama addon looks to fail updating hidden/shown status of tabs.

Then if I got you right, TST works as intended?

> On the other hand, if a tab visible on Firefox's tab bar is invisible on TST sidebar, it is a fault of TST.

They are not visible in FF tab bar.

I've been wondering if TST conflicts with Panorama tab group's heuristics somehow, especially the fact that TST tends to insert new tabs in a different way than FF does.

**Comment by MayeulC** [comment]
> I am wondering if when you see this event again, if you just disabled panorama if the tabs would be displayed properly. 

I'll try to clean my tab list first, I don't want to lose my groups with a few hundred tabs in if I can avoid it :)

**Comment by piroor** [comment]
> Then if I got you right, TST works as intended?

Yes. Basically TST doesn't hide any tab via the API `browser.tabs.hide()`. The API hides tabs from both Firefox's tab bar and TST's sidebar, and tabs hidden via the API will be listed in the menu "hidden tabs". So, when a tab is listed in the "hidden tabs" menu, it looks to be hidden by someone not TST.

**Comment by irvinm** [comment]
@MayeulC is there anything more to discuss or can you close this item?

**Comment by MayeulC** [comment]
I think this can be closed. I disabled panorama tabs as it is a bit redundant with TST (although TST is a bit impractical for handling large groups of tabs).

I guess what I really want as a tab manager is a "mind map", sort of like pearltrees, with collapsible trees. TST will do, but it's a bit hard to reorganize the hierarchy sometimes.

**Comment by irvinm** [comment]
@MayeulC you could also try https://addons.mozilla.org/en-US/firefox/addon/tab-manager-plus-for-firefox/ and I haven't any problems with it at all ... although it is a little different than panorama tabs.

**Comment by MayeulC** [comment]
> @MayeulC you could also try https://addons.mozilla.org/en-US/firefox/addon/tab-manager-plus-for-firefox/ and I haven't any problems with it at all ... although it is a little different than panorama tabs.

Thanks for the suggestion, I'm trying it, and it looks quite good!
