### ISSUE TITLE
Allow the user to force TST to use its light or dark icons

### ISSUE THREAD

**Issue by Gitoffthelawn** [piroor/treestyletab#2896]
## Short description
It will be beneficial to have an option to allow the user to force TST to use its light or dark icons.  Why?  The TST icon can be completely invisible when using certain Firefox themes, including Firefox's native Alpenglow theme.

## Steps to reproduce

1. Create a fresh Firefox profile.
2. Install TST.
3. Right-click the TST icon and select 'Customize Toolbar'.
4. In the UI that appears, select the 'Firefox Alpenglow' theme.
5. Drag the TST icon to the upper-left of the Firefox window, to the LEFT OF THE LEFTMOST TAB (*ABOVE* the 'Back' button).
6. Click 'Done' in the 'Customize Toolbar' UI.
7. Maximize the Firefox window.
8. Notice that the TST icon is not visible.

## Expected result

TST icon visible

## Actual result

TST icon not visible

## Environment

 * Platform (OS): Windows
 * Version of Firefox: 88.0.1
 * Version (or revision) of Tree Style Tab: 3.8.1

**Comment by irvinm** [comment]
@piroor is this something you would want to support?  I could see people who might use a dark theme at the OS level, but a "lighter" accent color in the browser that render the icons hard to read.

Some addons I have seen basically have a configuration for icons that are:  (1) auto selected, (2) force dark icons, (3) force light icons.

**Comment by piroor** [comment]
Hmm... because this is an accessibility problem, I've reintroduced an option to choose icon color with the commit 38dfc08.

**Comment by piroor** [comment]
I think that by rights this should be solved on Firefox side...

**Comment by Gitoffthelawn** [comment]
> Hmm... because this is an accessibility problem, I've reintroduced an option to choose icon color with the commit [38dfc08](https://github.com/piroor/treestyletab/commit/38dfc080947dbe095c371f71a029d195cc63afcb).

Thanks.  Looking forward to the release.

**Comment by irvinm** [comment]
@Gitoffthelawn another one ... can you check and close if resolved?

**Comment by Gitoffthelawn** [comment]
Verified forcing the icon to white is working!  Thank you so much!  Closing now...
