### ISSUE TITLE
Bookmark This Tree window opens too small

### ISSUE THREAD

**Issue by Graemek1** [piroor/treestyletab#2897]
## Short description
When I use "Bookmark this tree", the save dialogue window opens too small - cannot see the "Save/Cancel" buttons.  Can I fix this or is this a bug?
## Steps to reproduce

![image](https://user-images.githubusercontent.com/49665714/118382435-d7360e80-b638-11eb-9bc3-832cf9f2d34f.png)

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Expected result
NA

## Environment
 * Platform (OS): Windows 10
 * Version of Firefox: 88.0.1 
 * Version (or revision) of Tree Style Tab: 3.8.1

**Comment by piroor** [comment]
Could you try Ctrl-0 (reset zoom level to 100%) ? This can happen when the zoom level is accidentally changed over 100%.

**Comment by NiklasGollenstede** [comment]
There is a chance that this is related to the `devicePixelRatio`. I remember issues with that and popup sizing on high(er) resolution screens.
Might be a Windows-only thing. I was using Windows then, but now on Ubuntu/KDE with `devicePixelRatio = 1.25` it works fine. But on my work PC (with Windows and DPR 1.25, but inacessible now) I also have (/recently saw) issues with the sizing of the "close multiple tabs?" popup.

**Comment by irvinm** [comment]
@piroor I don't normally use this feature, but I see the same thing.  I have the OS DPI scaling at 100%.  I have my default zoom level in Firefox set to 120%, but also tried resetting the specific page to 100% and always saw this:

![image](https://user-images.githubusercontent.com/979729/120475517-7405e500-c377-11eb-9a57-4fdf76757d9e.png)

I then tried your suggestion of resetting the zoom on that popup.  I make sure to dismiss the popup and bring it up again and the zoom remained and everything looked good.  @piroor while resetting the zoom to 100% fixes the sizing of the scrollbar and displaying of the buttons, in my case of using 120% as my default zoom level in Firefox, this display box at 100% seems small.

**Relative size:**
![image](https://user-images.githubusercontent.com/979729/120477148-710bf400-c379-11eb-83db-ad79761a730f.png)

**Standalone:**
![image](https://user-images.githubusercontent.com/979729/120476047-22118f00-c378-11eb-8ef7-4f53e1a64e2a.png)

**Comment by piroor** [comment]
Hmm... I didn't know that the default zoom level option affects to TST's custom dialog based on a popup window.

I've tried a combination of default zoom level 150% (on Firefox options) and 125% scaling (on Windows options), and I successfully saw a broken appearance as the first screenshot of @irvinm's comment. `devicePixelRatio` in such a stuation:

* `1.0` for the background page.
* `1.25` for the sidebar in the scaled display.
* `1.875` for the popup window contents.

I think the popup should be rendered with `1.25` devicePixelRatio same to the sidebar.

**Comment by piroor** [comment]
The commit be0db26 should solve the problem caused by changed default zoom level.

**Comment by irvinm** [comment]
@Graemek1 I tried this with TST 3.8.2 and with Windows @ 100% and Firefox @ 120%, I now see the popup at 100% scaling and everything fits and the buttons are visible.  (@piroor I think I would argue that the window scaling should really be at 120% in this scenario, but this works too)

If you are ok with things now, would you close out this item?

**Comment by irvinm** [comment]
@Graemek1 just a friendly reminder.

**Comment by irvinm** [comment]
@piroor I think this can be closed.
