### ISSUE TITLE
open group-tab for existing group

### ISSUE THREAD

**Issue by raphaelquast** [piroor/treestyletab#2902]
## Short description

this is not an issue but rather a feature-request...

in the development-settings there is an option **"page for group-tab"** that creates a group-page tab that displays a (full-page) list of all the tabs that are present in this group.

![image](https://user-images.githubusercontent.com/22773387/119257342-234afb00-bbc5-11eb-8039-8c6d2a7d7569.png)

you can't really edit anything on this page except the title of the group, but it provides a very nice overview of all pages that are present in a group

would it be possible to implement an option to open such a page that simply displays the currently selected group?
e.g. `right-click somewhere on the sidebar -> open group-tab`   or so
...this would be a very nice feature to search and navigate large groups with long tab-names etc. ...

for example:

![image](https://user-images.githubusercontent.com/22773387/119257574-1a0e5e00-bbc6-11eb-98a3-25d9f88aaa62.png)

alternatively it would be nice to be able to open such "group-tabs" via the new-tab context-menu...
e.g.: an option "Group-Tab" in here:
![image](https://user-images.githubusercontent.com/22773387/119257769-0adbe000-bbc7-11eb-9967-2d31aec7bec6.png)

**Comment by piroor** [comment]
I have no plan to add commands to open a group tab from the menu. Instead there are some alternatives:

* TST More Tree Commands https://addons.mozilla.org/firefox/addon/tst-more-tree-commands/ provides ability to group multiselected tabs. It automatically opens a new group tab.
* Creating a bookmark with an URL `ext+treestyletab:group`. When you open a new tab from the bookmark, it will become a group tab.

**Comment by irvinm** [comment]
@piroor I think you can close this one.
