### ISSUE TITLE
White flash when loading sidebar 2

### ISSUE THREAD

**Issue by wvxwxvw** [piroor/treestyletab#2903]
There's already a closed Issues, but I don't see it being solved.  
Although this is solved quite simply, through userContent.css:
```
@-moz-document regexp("moz-extension:\/\/.+\/sidebar\/sidebar\.html.*") {
:root, #background {
    background-color: rgba(40,42,48,1.0) !important;
}
}
```
Can't this be solved through the extension itself?
And in the [Code snippets for custom style rules](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#for-version-2x) about it there is nothing (like).  
  
Are you not afraid that epileptics will sue you? :)

**Comment by piroor** [comment]
>  Can't this be solved through the extension itself?

I think there is no universal solution. It looks easy that supporting only Firefox's default theme (with blight or dark color).

To suppress the white flash, we need to apply CSS declarations before Firefox initially renders the sidebar contents. The easiest way is: putting declarations in a static CSS file. However there is no chance to know the background color matching to the current theme at the timing. `browser.theme.getCurrent()` is asynchronous, so always we get the result including the expected color information, after the initial rendering is finished.

I've experimentally tried to apply better background color  with less delay, but I couldn't get expected result (you can try same build: https://github.com/piroor/treestyletab/actions/runs/898711920#artifacts ). `userContent.css` is loaded by Firefox before initial rendering of the sidebar, on the other hand WebExtensions API does not allow an addon to register any pre-loaded style sheet, so we always need to wait generated style sheets are applied for a while.

**Comment by piroor** [comment]
I don't know how to break through the restriction, and any idea is welcome.

**Comment by irvinm** [comment]
@wvxwxvw it is interesting that I tried your userContent.css code, but I still see a white flash before the color is loaded.  (I did verify the color is loaded eventually)

I had the same problem with web pages directly and I solved it by increasing the delay before a page starts getting displayed.  This allowed things like "Dark Reader" to override the color in enough time that the white flash is never shown.  I wonder if there is a similar option for the sidebar.

`user_pref("nglayout.initialpaint.delay", 400);`

**Comment by wvxwxvw** [comment]
@piroor  Just please add the instructions to the wiki.
@irvinm  And note that I left out the end parenthesis in my code.
I fix it now.

**Comment by piroor** [comment]
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#suppress-white-flash-on-showing-sidebar-in-dark-color-mode-2903

**Comment by piroor** [comment]
The change to apply background color to the sidebar panel unexpectedly introduced too frequent reloading of the sidebar on a case any addon changing browser theme frequently is installed. There is a report about a combination with VivaldiFox at #2936.

**Comment by piroor** [comment]
I've removed codes changing the sidebar panel too frequently with the commit 2f5a486. To reduce white flashing, we'll need to use userContent.css again...
