### ISSUE TITLE
TST steals mouse focus from the page, page freezes

### ISSUE THREAD

**Issue by bashtanov** [piroor/treestyletab#2904]
Unfortunately I've no idea how to reliably reproduce it, and whether I can do it in a clean profile etc.
It just happens a few times a day.

Basically under unknown circumstances the tree style tabs sidebar steals mouse focus from the page.
All the links and elements in the page appear frozen and not working.
If I scroll my mouse wheel above the page, tree style tabs switch tabs, but the page does not move.

The only way to recover from this situation is to switch between tabs using mouse clicks. Sometimes a tab reload is needed too.

_Maybe_ it only happens in private tabs.

Steps to reproduce: not sure
Actions: click on website links; scroll website page
Expected: website links drive me to another page; page is scrolled
Actual: nothing happens on click; tabs are switched in TST

Firefox 88.0.1 (64-bit) for Ubuntu
TST 3.8.1

Do you think it would make sense if I enable extensive logging and gather some logs about it?

**Comment by piroor** [comment]
Any error message reported in the debug console? (see also: https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-start-debugger-for-tree-style-tab ) TST captures mouse events on some cases, and it may forget to release mouse events if something error happens before the releasing.

**Comment by irvinm** [comment]
@bashtanov any updates on this?

**Comment by irvinm** [comment]
@bashtanov just a friendly reminder.

**Comment by bashtanov** [comment]
@irvinm @piroor sorry for the delay. I tried to follow the steps for debugging, but it differs from what is described in https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-start-debugger-for-tree-style-tab
When I navigate to `about:debugging` there is no `Enable add-on debugging` to toggle, but there is a link to "This Firefox". If I go there there is "Inspect" button for TST. And if I go there there is a console. I've seen some errors in the `/background/background.html` console, but when I switched to other iframes they were lost. Should I collect errors from `/background/background.html` iframe or from any other iframe?

**Comment by bashtanov** [comment]
UPD: there was the following error in `/background/background.html`:
`NS_ERROR_FILE_NOT_FOUND: Failed to open input source 'moz-extension://cea0b36a-4d15-430f-8254-bf5e13412b1f/extlib/codemirror-theme/default.css'`
Shortly after it the focus problem appeared.

**Comment by bashtanov** [comment]
Once again it reproduced, only the following messages were there near the time:
```
16:15:08.202 Uncaught (in promise) Error: Invalid tab ID: 447 undefined
16:15:08.205 Uncaught (in promise) Error: Invalid tab ID: 447 undefined
```

**Comment by piroor** [comment]
Thank you for researching, I've updated the wiki page for current Firefox. And I've fixed the `NS_ERROR_FILE_NOT_FOUND` error you saw. The `Invalid tab ID` is logged sometimes when asynchronous API call is processed after the tab is closed. Both errors look not related to this issue.

**Comment by piroor** [comment]
@bashtanov Is this OK to be closed as "stale"? (I recently introduced a bot to mark unresponded issues as "stale" and close such issues automatically, but initially I forgot to configure the bot to notify the issue was marked as "stale".)
