### ISSUE TITLE
Feature request: mouse-click "shortcuts", especially for Close Tree

### ISSUE THREAD

**Issue by joshgold22** [piroor/treestyletab#2905]
There are some actions, — but for me, especially Close Tree— that I'd like to be able to perform on a tab without selecting and loading the tab.  Right now that's possible via the context menu, but I wondered if TST could provide a way to specify actions such as single-/double-/triple- clicks on the tab with optional modifiers.  That would save the time of opening the context menu and finding the right option (especially since many have similar names.)

It would be nicest if this could do "anything" from the context menu (including entries from other extensions, like copying to the clipboard, AutoDiscard, TabMover , bookmarking, etc, though I would guess TST can't do that on its own.  That said, I'd be pretty happy myself with a just a quick tweak to allow "Close Tree" as one of the options for double-click, honestly.

(Perhaps this would subsume the double-click options to collapse or close if it's implemented more generally.)

## Environment

 * Platform (OS): OSX 10.15.7
 * Version of Firefox: 88.0.1
 * Version (or revision) of Tree Style Tab: 3.8.1 (2021.5.7)

**Comment by piroor** [comment]
Sorry I'm negative to increase too detailed options (it will increase costs for maintenance), thus the option won't implemented by TST itself. Instead it looks can be done via helper addons, like:

https://addons.mozilla.org/firefox/addon/tst-middleclick/
https://addons.mozilla.org/firefox/addon/tab-flip-for-tree-style-tab/

TST provides an API to override click action on tabs. If there is no existing addon satisfying your demand, you may need to create new addon by yourself.
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#when-a-tab-is-clicked

**Comment by joshgold22** [comment]
I'm very much in agreement with you.  Could you tell me, does the API ("when a tab is clicked") include only clicks on the TST sidebar tabs, or does it give the same event message for clicks on the firefox builtin tab bar?

**Comment by piroor** [comment]
It works only around TST's sidebar. Sadly there is no chance for addons to handle raw DOM event around Firefox's native tabs.

**Comment by irvinm** [comment]
@joshgold22 given there won't be changes for TST, would you close out this item?  You can always continue to ask questions about the API (if needed) even when it is closed.

**Comment by joshgold22** [comment]
Sure, and thanks for the feedback and suggestions.

**Comment by joshgold22** [comment]
Actually, I do just want to check about the smallest variant I'd mentioned — @piroor would you still consider adding "Close This Tree" to the set of options for double-click?  I wondered if that would have less of the maintenance concern (versus creating a whole scheme and UI for assigning custom mouse-events to TST actions.)  Could be a different ticket, to keep the wontfix explanation here.

**Comment by piroor** [comment]
At a different viewpoint, currently available choices have reasons from user experience compatibility.

* "Double-click to collapse/expand tree" is a generic operation on other situations: Firefox's bookmarks folder tree, Thunderbird's folder tree, Windows Explorer's folder tree, and more. 
* "Double-click to close individual tab" is available as an optional behavior (`browser.tabs.closeTabByDblclick`) of Firefox itself.
* "Nothing" is also a generic option compatible to other applications: Gimp, Adobe Illustrator, and more.

On the other hand, "double-click to close the whole tree" looks not a major behavior across multiple existing applications, for me (this is just my personal opinion, and anti-example is welcome). Compatibility is an important topic on this project. Even if it requires more codes, I sometimes implement a behavior compatible to other applications. And I sometimes negate adding new options incompatible to other applications, even if it can be implemented easily.

**Comment by joshgold22** [comment]
Ah, thanks, I do understand the principle you've explained and appreciate your explanation.  I do think it might be ambiguous how a user with double-click-to-close experience would expect it to behave when carried over to a tab that is the root of a group.  Not exactly a counter-example, because the question doesn't exist without the tree structure TST introduced.

**Comment by piroor** [comment]
Sorry but I have to put a boundary what should be a built-in and what is not. The criteria is considered based on various viewpoints: maintainability, compatibility, naturality, safety, un-implementability via API, and more. I can't find out a strong reason why it must be a built-in feature. Not only this, I hope to remove more not-critical built-in options from TST. Indeed a helper addon project TST More Tree Commands https://github.com/piroor/tst-more-tree-commands was started for the purpose, about menu commands and keyboard shortcuts.

**Comment by joshgold22** [comment]
No problem at all.  I was just sharing the thought exercise, and I agree it will be good to make the basic extension and configurations leaner.

**Comment by joshgold22** [comment]
**Found a workaround:**
I ran into a not bad (2-click) workaround that we didn't think of during this discussion earlier.

If I collapse the tree I want to close (click the twisty on the left), then a second click on the x on the right closes that sub-tree.
