### ISSUE TITLE
Open Child Tab dont work on certain insertion positions.

### ISSUE THREAD

**Issue by UPuXA** [piroor/treestyletab#2906]
## Short description
The "Open Child Tab" function don't work on certain insertion positions settings.
I experienced this for a long time on different Windows and Linux Systems.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set "Insertion position of new child tabs" to 1 (No control) or 2 (Next to the recently opened ...).
 4. Open a new Child Tab in the sidebar with Middle Click or selector button on the New Tab button.

## Expected result
A new Child Tab will appear in the configured position.

## Actual result
Nothing. No tab at all is opened.

### Test System:
 * Platform (OS): Xubuntu 20.04
 * Version of Firefox: 88.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.8.1

### My main System with the same symptoms:
* Platform (OS): Windows 10 (21H1)
 * Version of Firefox: 88.0.1 (64-Bit)
 * Version (or revision) of Tree Style Tab: 3.8.1

**Comment by piroor** [comment]
Thanks! I've confirmed that "No control" choice causes an error on the case and the commit 27119f8 should fix it.

However, I couldn't reproduce the problem with the choice "Next to the recently opened...". Could you confirm exact steps to reproduce the problem with the case?

**Comment by UPuXA** [comment]
Thank you for your time.

I am sorry but i forgot to mention that the Problem only appears if there is already a child tab under a parent.

Like this:
Tab
└ Child Tab

### Steps to reproduce
1. Start Firefox with clean profile.
2. Install TST.
3. Set "Insertion position of new child tabs" to 2 (Next to the recently opened ...)
4. Open a new Child Tab in the sidebar with Middle Click or selector button on the New Tab button.
5. Open a additional Child Tab under the same parent with Middle Click or selector button on the New Tab button.

I additional noticed that the "Insertion position of new child tabs" disappears after a Firefox restart in the extension icon context menu.
![grafik](https://user-images.githubusercontent.com/79371648/120468770-decc1600-c3a1-11eb-8961-2f619e8377b2.png)


And under Windows the setting jumps after a restart further to 1 (No control). But i think it is better i create a new issue for that.

### Test System:

- Platform (OS): Xubuntu 20.04
- Version of Firefox: 88.0.1 (64-bit)
- Version (or revision) of Tree Style Tab: 3.8.1

**Comment by piroor** [comment]
Oops, the menu on the toolbar button was broken. (See also #2890 please for more details.)

And thanks, I've successfully reproduced the problem and the commit 1b24c0b should fix it.

**Comment by irvinm** [comment]
@UPuXA can you check with the current build and close this item if resolved?

**Comment by irvinm** [comment]
@UPuXA just a friendly reminder.

**Comment by UPuXA** [comment]
I will try it this weekend.

**Comment by UPuXA** [comment]
It works like a charm. I will close this issue.
Have a nice day guys 🎉
