### ISSUE TITLE
Feature Request: Allow to configure that pinned tabs in the Firefox tab bar are not shown pinned in TST.

### ISSUE THREAD

**Issue by claudio-salvio** [piroor/treestyletab#2908]
## Feature Request

First of all, thanks for developing TST and sharing it with us.

I am contacting you to request you to allow to configure whether or not the pinned tabs in the Firefox tab bar are shown pinned or not pinned also in TST.

I would like to be able to see the tabs on one line each in TST even if they are pinned in the tab bar.

Best regards,
Claudio

**Comment by piroor** [comment]
Does the option help you?: TST Options => Check "Unlock Expert Options" => Appearance => Uncheck "Show pinned tabs only with their icon".

**Comment by irvinm** [comment]
@claudio-salvio anything more on this issue?  Can you close it?

**Comment by claudio-salvio** [comment]
Apologies for the delay in responding.
The option mentioned by piroor is the one I was needing.
Thank you very much for making this excellent addon available.
Regards
