### ISSUE TITLE
Tab selection not visible on Mac with Proton theme enabled

### ISSUE THREAD

**Issue by ivezakis** [piroor/treestyletab#2912]
## Short description

With the Proton theme selected, the currently active tab is no different than the rest.

## Steps to reproduce

 1. Start Firefox with clean profile on Mac OS.
 2. Install TST.
 3. Go to TST settings.
 4. Under "Appearance" change theme to "Proton". 

## Expected result

Tab selection appears as in the theme's screenshot.

## Actual result

Tab selection is not visible.

## Environment

 * Platform (OS): Mac
 * Version of Firefox: 89.0 64-bit
 * Version (or revision) of Tree Style Tab: 3.8.1

**Comment by piroor** [comment]
Thanks! The commit b2410a0 should fix this.

**Comment by irvinm** [comment]
@ivezakis can you check on the latest build and close this item if resolved?

**Comment by ivezakis** [comment]
@irvinm Sure, the selected tab is visible now.
