### ISSUE TITLE
CSS for render tab as they was before 89 version

### ISSUE THREAD

**Issue by Makishima** [piroor/treestyletab#2913]
Any chance that someone can write CSS to make the tabs looks like it was before 89 version?

**Comment by irvinm** [comment]
@Makishima are you talking about the native Firefox tabs or the tabs in the sidebar from TST?  You have total control of the tabs via CSS for TST, but if you are talking about the native Firefox tabs I would suggest visiting reddit's [r/FirefoxCSS](https://www.reddit.com/r/FirefoxCSS/) as I am sure there is plenty of discussion on that topic there.

**Comment by Makishima** [comment]
I mean TST tabs but I'm not sure that TST do no use native one
![изображение](https://user-images.githubusercontent.com/5548003/120529975-ab12df80-c3e5-11eb-93ba-de3effdeb56d.png)

**Comment by piroor** [comment]
@Makishima Did you try TST options => Appearance => Theme => Photon ?

**Comment by Makishima** [comment]
Oh, thanks! It's old 🧓 style
