### ISSUE TITLE
[feature request] One Tab extention integration with Tree Style Tab extention

### ISSUE THREAD

**Issue by JattMones** [piroor/treestyletab#2914]
## Short description
[feature request] OneTab & Tree Style Tab Integration
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install [OneTab](https://addons.mozilla.org/en-US/firefox/addon/onetab/) and Tree Style Tab
 3. Open tabs and organize them in a tree structure using tree style tab 
 4. Close/save the open tabs with the OneTab extension
 5. Open a new Firefox window and re-load the saved tabs using the OneTab extension 

## Expected result
Tabs are still stored in previous tree structure when loaded from OneTab.

## Actual result
(Most) Tabs are knocked out so they all resemble "root tabs" 

- Note: I've seen some inconsistent behavior with some tabs (Specifically a download tab opened after starting a download) sometimes stays as child tabs within Tree Style Tab.
- I noticed this once when downloading OBS from [this](https://obsproject.com/download/?utm_source=bmc) page, the "welcome to obs" tab which pops up afterward stays as a child tab when re-loading tabs from onetab. However, after re-testing I did not get the same behavior

## Environment

 * Platform (OS): Mac
 * Version of Firefox: 89

## 

I've also sent a message to the onetab support team, and made sure to include the link to this issue. I think it would make the most sense if OneTab stored Tree Style Tab information with it's saved tabs, although I'm not sure if this is possible. This info would then be sent to Tree Style Tab when the tabs are being loaded, so that Tree Style Tab knows how to organize them.
<img width="545" alt="onetab request" src="https://user-images.githubusercontent.com/22432176/120558534-9d516000-c3cd-11eb-8339-c287277c09ae.png">

All this being said, it's not really my concern HOW it works. Having OneTab supply data to Tree Style Tab seems like a long shot. If there is a better/easier way for you to integrate these two extensions together, please do it. Just thought I'd throw out a suggestion. Many thanks!

**Comment by piroor** [comment]
I think there is nothing TST side can do about this. If OneTab stores and restores `openerTabId` information of tabs like [TSM](https://addons.mozilla.org/firefox/addon/tab-session-manager/), TST can construct tree structure from the information. In other words, TST cannot reconstruct tree structure with no hint, until OneTab become providing that.

Tab's `openerTabId` is generic, and not TST specific. If OneTab starts to use the information, integration with OneTab will be improved more about other tree-view tab management addons also.

**Comment by irvinm** [comment]
@JattMones will you close this item?  There is nothing to do on the TST side.  Adding support for the openerTabId property is very simple and is the information that TST needs to be able to track relationships.

**Comment by irvinm** [comment]
@piroor I think this one can be closed.

**Comment by bjwest** [comment]
I'd rather see TST replace OneTab with it's own tab organizing system.  The method OneTab uses to import and export the database is atrocious.  OneTab has done a great job in hiding it's data so there's no way to extract it externally, and my tab "library" is larger than can be handled by the clipboard.

**Comment by piroor** [comment]
I've added a FAQ topic "Better compatibility with session manager extensions, or add high-power session management feature" based on this thread.
https://github.com/piroor/treestyletab/blob/trunk/README.md#feature-requests
