### ISSUE TITLE
Firefox Alpenglow dark theme not respected

### ISSUE THREAD

**Issue by auscompgeek** [piroor/treestyletab#2915]
## Short description

The standard Firefox chrome respects the OS color scheme (dark mode) when using the Firefox Alpenglow theme. TST will only show the Alpenglow light background regardless of active preferred color scheme.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Choose the Firefox Alpenglow theme.
 3. Ensure `(prefers-color-scheme: dark)` is set.
 4. Install TST.

## Expected result
TST shows the dark purple background like the native sidebars.

## Actual result
TST shows the light Alpenglow background.

## Environment

 * Platform (OS): macOS
 * Version of Firefox: 89.0
 * Version (or revision) of Tree Style Tab: 3.8.1

**Comment by piroor** [comment]
This looks to be cause by restrictions of WebExtensions API. `browser.theme.getCurrent()` always returns colors and image URLs for the bright mode for Firefox Alpenglow, and it is impossible to know which colors and images to be used on the dark mode.

**Comment by dmose** [comment]
Any chance you could file a Bugzilla bug filed about this?  (I implemented some of the Alpenglow pieces, and I'd love to see it be possible to use it more effectively).

**Comment by piroor** [comment]
This restriction looks to be tracked at the bug: [1542044 - browser.theme.getCurrent() & onUpdated should take in account `dark_theme` manifest field](https://bugzilla.mozilla.org/show_bug.cgi?id=1542044)

**Comment by dmose** [comment]
Great; thanks!

**Comment by auscompgeek** [comment]
no, bad bot

**Comment by auscompgeek** [comment]
*bonk*

**Comment by wagnerand** [comment]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1786564

**Comment by irvinm** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1786564 is listed as resolved in FF106.  Does this resolve this issue?

**Comment by auscompgeek** [comment]
Looking at that bug, it seems to refer to the gradient background having disappeared in Firefox 105 beta builds. This issue is about the background not responding to the system dark theme. It should match the colour of the toolbar. [Bug 1542044] is the correct bug to track.

[Bug 1542044]: https://bugzilla.mozilla.org/show_bug.cgi?id=1542044

**Comment by auscompgeek** [comment]
This is still relevant 😞

**Comment by piroor** [comment]
This issues tracker currently aims to track issues which can (and should) be fixed by TST. Firefox-side issues which can't be fixed by an addon (like WebExtensions API restriction) may be closed whether it still happens actually, otherwise this list of issues may be fullfilled with this kind issues...

**Comment by aaronliu0130** [comment]
i'm guessing nothing on TST would fix this?

**Comment by piroor** [comment]
There looks to be nothing we can do about this... you need to define dark colors for the Alpenglow theme with the user style sheet manually.
