### ISSUE TITLE
Sidebar stops responding to mouse clicks after quickly re-invoking tab-closing dialog

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#2917]
## Short description
After dismissing and quickly re-invoking the sidebar dialog for closing multiple tabs, TST sidebar no longer responds to any mouse interactions except middle clicks.
The sidebar still correctly displays tab changes.

## Steps to reproduce

 1. Start Nightly with clean profile.
 2. Install TST.
 3. Enable `Show dialogs in the sidebar if possible` in TST options > Appearance.
 4. Create a tree. Collapse the tree.
 5. Middle click the parent tab to invoke the tab-closing dialog.
 6. Dismiss the dialog either by clicking `Cancel` or pressing `Esc`.
 7. Quickly middle click the parent tab again to invoke the dialog.

## Actual result
1. 2 sets of dialog are shown before they disappeared abruptly.
![image](https://user-images.githubusercontent.com/771216/120810279-76d22700-c57d-11eb-9988-ceeeb5becd13.png)

2. TST sidebar does not respond to left/right clicks. 
3. Middle clicking a tab does not close it but instead creates a new tab, as if the dialog is still active.

## Notes
It seems that after the dialog disappears, it is still trying to listen to the inputs. Pressing `Esc` can actually "dismiss" the dialog and bring TST back to normal. Clicking the supposed area of `Cancel` button does not work however.
Another workaround is to hide and re-show TST sidebar.

## Environment

 * Platform (OS):  Win10 21H1
 * Version of Firefox:  Firefox 89 and Nightly 2021-06-04 (20210604102111)
 * Version (or revision) of Tree Style Tab:  3.8.1

**Comment by piroor** [comment]
Thanks, I've introduced some guard mechanisms for such a situation. With these changes, confirmation dialog UIs become expendable. They will be destroyed and the next dialog is shown in parallel.

However, I couldn't reproduce the problem you told on my environment - it looks difficult to reproduce. Changes I did should solve the problem, but I still cannot confirm it is actually solved. Please check the next release and close this issue when you confirm it is completely fixed.

**Comment by Fanolian** [comment]
It is fixed in 3.8.1.11501. Thanks.
