### ISSUE TITLE
Undefined object in settings after resetting all TST settings

### ISSUE THREAD

**Issue by Gitoffthelawn** [piroor/treestyletab#2922]
## Short description
In the *Context Menu* section of the options UI, an `undefined` object will appear in the `Active other devices` area after resetting all TST settings.  Pressing the `Delete` button will not delete the `undefined` object.

Manually importing a configuration without the `undefined` object also fails to work (the `undefined` object gets recreated).

TST not fully reset within the Firefox profile even after uninstalling TST.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open the TST settings UI, and press 'Reset All' to reset all TST settings (that option is in the `Development` section).
 4. Refresh the page.
 5. Notice the `undefined` object in the `Active other devices` area.
 6. Export the TST settings.
 7. Remove the `undefined` object from the exported TST settings JSON file.
 8. Reset all TST settings again.
 9. Import the settings from the JSON file.
10. Notice the `undefined` object in the `Active other devices` area again.
11. Reset all TST settings again.
12. Uninstall TST.
13. Close Firefox.
14. Open Firefox.
15. Install TST.
16. Notice the `undefined object` is present.

## Expected result
1. No undefined object.
2. Able to delete all objects.
3. Resetting settings should truly reset settings.
4. Uninstalling TST should remove all TST data from Firefox profile (steps 12-16 indicate an issue).

## Actual result
1. Undefined object.
2. Not able to delete all objects.
3. Resetting settings does not truly reset settings.
4. Uninstalling TST does not remove all TST data from Firefox profile (steps 12-16 indicate an issue).

## Environment

 * Platform (OS): Win7
 * Version of Firefox: 89.0.0
 * Version (or revision) of Tree Style Tab: 3.8.1

**Comment by piroor** [comment]
Thanks, I've done some changes to prevent this problem.

**Comment by Gitoffthelawn** [comment]
You're welcome, and thanks for the quick fixes!  Looking forward to the release on AMO.

**Comment by irvinm** [comment]
@Gitoffthelawn can you see if this is now resolved and close this item?  Thanks.

**Comment by Gitoffthelawn** [comment]
The appearance of those unwanted items in the UI is fixed for me.

Even though they no longer appear in the UI, they keep on multiplying in the internal settings database (even though they are no longer shown).  IIRC, during testing I could get this to happen quite a bit by importing settings files and performing actions to test all the various legal combinations of:

-  "syncAvailableNotified": true
-  "syncAvailableNotified": false
-  "syncOtherDevicesDetected": true
-  "syncOtherDevicesDetected": false
-  clicking on the sync popup when it appears
-  closing the sync popup when it appears

It's very possible that your recent commit https://github.com/piroor/treestyletab/commit/405dfdce0be6d50c62543970c28df804c6ed360a will solve this underlying issue, but you may want to test with all the possible combinations of the above to verify.

**Comment by piroor** [comment]
I've tried to reset all configs and reload TST, then TST just notifies a message for new users. The problem wrongly notified "sync available" message should go away, except imported configs contains sync information.

The sync feature is sadly very incompatible with import/export configs between synchronized devices. If you export all configs from a synced device and import it to another synced device, "device  id" information will be wrongly duplicated and TST cannot detect such a duplication. Thus something warning message looks to be required around import/export. (But I think I should not ignore some keys on import/export even if they are dangerous, because the feature can be used for backup.)

**Comment by irvinm** [comment]
@piroor is there anything more to do with this one or should we close it?

**Comment by Gitoffthelawn** [comment]
> Thus something warning message looks to be required around import/export.

Was a message like this added to the UI?

**Comment by piroor** [comment]
With the commit 64f1396 I've introduced a change to sanitize imported and exported data.

**Comment by Gitoffthelawn** [comment]
Wonderful!  I look forward to it.
