### ISSUE TITLE
Custom style rules area vertical size (userStyleRulesFieldHeight) not maintained during export/import round-trip

### ISSUE THREAD

**Issue by Gitoffthelawn** [piroor/treestyletab#2923]
## Short description
The `userStyleRulesFieldHeight` option in the TST settings export JSON file is not honoured.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open the TST settings UI and add a bunch of custom CSS in the custom style rules area (in the `Advanced` section).
 4. Expand the custom style rules area vertically.
 5. Export the TST settings.
 6. Make the custom style rules area as small as possible (vertically).
 7. Reset all TST settings.
 8. Import the settings from the JSON file.
 9. Notice the custom style rules area is not restored to the previously saved (exported) height.

## Expected result
All settings to be maintained during an export/import round-trip.

## Actual result
Height of custom style rules area not maintained during export/import round-trip.

## Environment

 * Platform (OS): Win7
 * Version of Firefox: 89.0.0
 * Version (or revision) of Tree Style Tab: 3.8.1

**Comment by piroor** [comment]
Thanks, the commit e4de8d8 should fix it.

**Comment by Gitoffthelawn** [comment]
You're welcome.  And thank *you* for the fix.  The next release on AMO should be fantastic!

**Comment by irvinm** [comment]
@Gitoffthelawn can you check with the latest build and close this if resolved?

**Comment by irvinm** [comment]
@Gitoffthelawn just a friendly reminder.

**Comment by irvinm** [comment]
@piroor I think this can be closed.
