### ISSUE TITLE
userChrome (for windows 10), as well as a request for userChrome documentation

### ISSUE THREAD

**Issue by zwarmapapa** [piroor/treestyletab#2925]
I worked on tweaking my userChrome file for a while, and this one works best (for windows 10). 

Maybe it's useful to share it somehow with other users, considering many want to hide the top bar (but not the minimize, maximize, and close window buttons). 

This is how it looks like:

![Untitled](https://user-images.githubusercontent.com/33539232/121003528-edde0a00-c78d-11eb-8f89-3ce7b2b44d2b.png)

File path:  %appdata%\Mozilla\Firefox\Profiles\xxxxxxx_this_is_randomly_generated_by_your_browser_xxxxxxx\chrome\userChrome.css  (create the "chrome" folder and the "userChrome.css" file if they don't exist yet). 

Content of userChrome.css:

```
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

#TabsToolbar .toolbar-items, #TabsToolbar .titlebar-spacer {
    visibility: hidden !important;
}

#sidebar-header {
    visibility: collapse !important;
}

#nav-bar {
    margin-top: -40px !important;
    margin-right: 150px !important;
    margin-bottom: 0px !important;
}
```

Maybe we could create a page in the documentation for userChome setups? Each with the intended platform as well as a screenshot included? That would have helped me out tremendously, and I'm sure it will be of a lot of use to other users as well.

**Comment by irvinm** [comment]
@zwarmapapa in general, a lot of people who really want to customize their experience had to do the same time you had to do.  I really like the idea of documenting some\all of it, but piroor is only one person and the community needs to be able to help out with that.  The wiki is the best place for things like this, but information also changes over time and even in your example CSS, it is really better to "explain" what each block does so people understand what they are potentially using. [Updated with comments below]

```
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

/* Hide Firefox native tab bar */
#TabsToolbar .toolbar-items, #TabsToolbar .titlebar-spacer {
    visibility: hidden !important;
}

/* Allow the sidebar to collapse */
#sidebar-header {
    visibility: collapse !important;
}

/* Move the minimize-restore-close buttons so they align with the URL bar */
#nav-bar {
    margin-top: -40px !important;
    margin-right: 150px !important;
    margin-bottom: 0px !important;
}
```

Another example is the namespace statement.  That is no longer needed ... I can't remember when that change happened.

Finally, it is usually best to link to other information\instructions for standard processes.  For example, to find the profile directory, it is actually better to:  Open about:profiles, find the section listed as "This is the profile in use and it cannot be deleted.", go to the row listed as "root directory", and click on the "Open directory" button.  [This should get you to the same directory that you described]  There are also the other steps to enable CSS processing for Firefox itself by going to about:config and setting toolkit.legacyUserProfileCustomizations.stylesheets = true.

I think we will all need to work together to help improve documenting this information as it is a fairly daunting task for people new to customizing Firefox.  I am sure that @piroor will chime in as well.

**Comment by zwarmapapa** [comment]
@irvinm Wow thanks, that's a lot of information I didn't yet know! 

Yes I agree, a wiki would definitely be best, as things will continue to change (for example, hiding the whole #TabsToolbar worked fine on windows 7, but on windows 10 it will also hide the windows min/max/close buttons as well, so hiding specific elements was needed instead). 

Maybe it's best to explain people how to inspect the browser (Menu -> More Tools -> Browser Toolbox) so that people are able to adjust or fix anything that's specific to their browser or their OS as well. 

However I think some default userChrome setups (for the most common OS today) will already be what >95% of the users of this plugin are looking for, a simple setup wiki for that would be great. 

A simple documentation page here will probably also work well enough for most users, since it doesn't happen often that the userChrome has to be changed (except when you switch OS, or when there is a major firefox overhaul like quantum was). For changes like that, a pull request is probably going to be fine, as it will rarely happen that there will be a newly released OS or a major firefox overhaul. The more specific information on how to customize things and how the CSS etc exactly works can be explained on a wiki.

**Comment by piroor** [comment]
You may add a new wiki page for the customization, it is welcome  all days, but I hope you (and wiki paeg authors) to put caution message about the risk of userChrome.css customization at the top of the page. Recently I commented about similar topic how to hide the horizontal tab bar, and I've added it to [the FAQ topic](https://github.com/piroor/treestyletab/blob/trunk/README.md#appearance).

**Comment by zwarmapapa** [comment]
@piroor Thanks, that's very useful to know!
