### ISSUE TITLE
[feature request] Multiple new tab buttons

### ISSUE THREAD

**Issue by TrianguloY** [piroor/treestyletab#2926]
I tried to search an existing issue or an addon with this new feature, but was unable to find anything. If there is one just point me to it, thanks.

## Short description

[feature request] Is it possible to have multiple new tab buttons depending on where you want to create a new tab (as a child, as a parent, etc, see screenshots below), either as a new feature or with a TST addon?

## Long description

I started using this addon recently and so far I really like it but creating new tabs is where I have most problems. Sometimes you want to create a new related tab of the current one, so you want a child, sometimes a new related one of the parent, so you create a sibling, others a completely independent tab, etc. With default settings you can click the little arrow in the new tab to choose, and you can also set shortcuts for different actions (control+click, shift+click, etc). The main issue with these methods is that they require you to remember how to do what you want, either the name (for non-english speakers I often mix the terms) or the shortcut.

So, my idea is to have different visual buttons for the different new tabs. I first though of having four '+', one for each method (independent, child, sibling, next sibling) but unless they have different icons it will be probably even more confusing (although that could be another feature request). What I think is very visual and hopefully intuitive at first glance:

![image](https://user-images.githubusercontent.com/10616202/121075921-0d992080-c7d6-11eb-85a1-a4514c71977a.png)
Left: current  ----------  right: suggestion.

Basically: each tab have a child '+' (after other childs). The bottom one can be considered the child tab of the browser itself. The position of each button matches the position of the new tab that will be created. Want a child of the current tab? press the '+' button under it. Want a sibling? the one below. An independent one? the one at the bottom. The only thing that can't be created with this is the 'next sibling' (which could be added but probably will be too much).

The downside is that you will need space for all those '+' buttons (exactly n+1 if you have n tabs, assuming none collapsed). For me it is no problem, I don't open a lot of tabs so I have plenty space, but if this is not wanted perhaps only the ones from the current tree could be shown, or reduce its size, or collapse those who are shown next to to each other...

I also don't mind needing a TST addon if this seems unrelated, even create it myself, but can it be made with the current API? (If so I'd appreciate some pointers to how to start implementing this).

Thanks for reading.

**Comment by piroor** [comment]
Very unique idea, but it looks hard to be implemented. Sadly TST's sidebar is not designed to mix tab and other type elements...

There are some possible workarounds;

* New Tab Here https://addons.mozilla.org/firefox/addon/new-tab-here/ provides a toolbar button and extra context menu item, and it allows you to open a new tab at any configured position.
* Put a new bookmark with a URL `about:newtab` to the bookmarks toolbar, then drag and drop it to any position in the sidebar, then it should be opened as a new tab there. (But this requires a commit 7401a816bbf53f78b04447a7ee6de01eb5a3346c - it will be included to the next release.)
* Shift-drag the new tab button: it will be treated as a new tab bookmark item. This behavior is implemented with recent commits, and available on the next release.
* Creating a new helper extension providing an extra context menu item. [It should call TST's API to open a new tab at arbitrary position](https://github.com/piroor/treestyletab/wiki/API-for-other-addons#open-new-tab-bypassing-tsts-tab-control-behavior).
* Creating a new helper extension [providing a small button in each tab](https://github.com/piroor/treestyletab/wiki/Extra-Tab-Contents-API). It should open a new tab below the owner tab.

**Comment by irvinm** [comment]
One additional idea:

- Creating a new help extension that monitored for double-clicks (or right-click menu addition) to open a new tab at the bottom of the tree that was clicked on.  [Monitor\respond, start at current tab, traverse to bottom of tree, create new tab via TST API]

**Comment by TrianguloY** [comment]
Thanks for the detailed answer, I understand the difference between tabs and other elements, I guess the new tab at the bottom is a special item then? Perhaps the suggestion of having different icons for the different new tab methods could work? I'll make a new issue to discuss it.

As for a current workaround, the ability to drag&drop the '+' button seems cool, thanks. And a helper extension that adds a '+' button near the 'x' one also seems interesting, I might try to implement it if I can (will report here).

I see you already marked this issue with the relevant tags. I'm not sure what is the expected step so I'll just keep it open, but feel free to close it if preferred.

Thanks again for your detailed answer. 👍

**Comment by piroor** [comment]
> I guess the new tab at the bottom is a special item then?

Yes. Only one last irregular item is easily supported, but irregular items mixed in middle of list is hard for me...

**Comment by TrianguloY** [comment]
I managed to create such extension without much issue (the API description is easy to follow, thanks!). However I needed to check another similar TST addon because I didn't knew you need to add all the code in a "background": {"scripts": [...]} file specified in the manifest. And I didn't find those instructions in the wiki. Maybe it is a good idea to add it in the [abstract](https://github.com/piroor/treestyletab/wiki/API-for-other-addons#abstract)? For an experienced extension developer it may be obvious, but not for a [newbie](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension) like me.

Anyway, [currently](https://github.com/TrianguloY/TST-new-child-tab-button) the extension works fine! 

![image](https://user-images.githubusercontent.com/10616202/121332562-46411300-c918-11eb-9107-6690f8b61a9b.png)



However I found three issues that I wasn't able to fix:
1) The icon is drawn above the text, so if you make it transparent to 'blend' into the background the text is visible and looks bad, but if you make it with an opaque color to hide the text it looks wrong with different colored tabs like the selected (and also the text don't fade and looks bad). Is it possible to somehow specify that the button needs to be outside the label like the 'x' button? [edit: and also if another icon is shown, like the speaker when the tab is playing a sound, it is drawn above it!]
1) When creating a new child tab, can you specify where to place it? It currently follows the user preferences (the 'insertion position of new child tabs'), but I wanted to have that setting as 'firefox default' and make my addon always add the child at the end, like when creating a child using TST. Is it possible?
1) The icon is currently passed as a base64 img data. Is it possible to specify an icon from a file in the extension? (or allow svg?) Not much problem, but I don't like it this way.

Note: I can create new issues for each of these points if preferred.

**Comment by piroor** [comment]
You can refer SVG icons. Here is an example:
https://github.com/piroor/tst-tab-drag-handle/blob/1d9d39d612bedeed05dcafdd8fb213454d052cf8/background/background.js#L99

This helper extension inserts some buttons, and they are placed at left to avoid conflicting with other existing UI. If you wish icons are placed at right, I recommend you to apply margin-right only when the "mute" icon is visible, like TST itself does: 
https://github.com/piroor/treestyletab/blob/5a8569c22feeaedeecde623a86832db7bc0419a2/webextensions/sidebar/styles/sound-button.css#L64-L69

A helper addon can apply arbitrary CSS rules to TST's UI . (It may break TST's functionality so you need to do it very carefully.) Adding margin-right for tab-label will solve the covered label problem.

**Comment by piroor** [comment]
> Maybe it is a good idea to add it in the abstract?

Thanks, I've added a note to the abstract section.

**Comment by irvinm** [comment]
@piroor I think we can close this one.  We can continue to have any discussions as needed with other questions.
