### ISSUE TITLE
Theming TST from an add-on?

### ISSUE THREAD

**Issue by altano** [piroor/treestyletab#2927]
I've created a Firefox theme and as a Tree Style Tabs user I went to the trouble of making sure the theme looked great with TST.

The problem is that the user has to [revert to native Firefox styles](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#apply-tab-colors-exactly-same-to-firefoxs-native-2780) for this to work the way I've done it now.

Is there a better way to do this? Can my Firefox add-on directly target the styles of TST so that there is no such step?

**Comment by piroor** [comment]
Do you mean about the method how to apply arbitrary style sheets to TST's sidebar? You can do that with the `register` type message: https://github.com/piroor/treestyletab/wiki/API-for-other-addons#basics

**Comment by irvinm** [comment]
@altano any feedback?  Anything more to do with this one or will you close it?

**Comment by altano** [comment]
@irvinm sorry I haven't had a chance to take a look at whether this API works or not. I'll close the issue for now on the assumption that it works and will report back if it doesn't. Thanks!
