### ISSUE TITLE
[Feature request] Separated new tab icons

### ISSUE THREAD

**Issue by TrianguloY** [piroor/treestyletab#2928]
Related to https://github.com/piroor/treestyletab/issues/2926

This suggestion is probably not desired to have on the main addon, but instead on a separate TST addon. Nonetheless I write this issue to have it recorded (also in case someone need related icons). Close as necessary.

## Short description

[Feature request] Have a different button for each new tab mode (independent, child, sibling and next sibling)

## Long description

Instead of having a unique '+' buton at the bottom, with an optional dropdown, place 4 different icons for each new tab mode:

![image](https://user-images.githubusercontent.com/10616202/121236319-1b15df80-c896-11eb-8793-8bf9a20b01a1.png)

Even though it should be easy to identify each icon, they are (left to right): new independent tab, new child tab, new sibling tab and new next sibling tab.

**Comment by piroor** [comment]
Anyway icons looks nice for better accessibility. I've added icons based on your idea:
![image](https://user-images.githubusercontent.com/70062/121334659-d1d89500-c954-11eb-9e3c-839f7c235e8b.png)

**Comment by piroor** [comment]
I've added new APIs to insert extra contents to the new tab button. I think your idea can be implemented as a helper extension for the next release of TST:
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#when-the-new-tab-button-is-clicked
https://github.com/piroor/treestyletab/wiki/Extra-Tab-Contents-API#extra-contents-in-the-new-tab-button

**Comment by piroor** [comment]
Thanks for giving a chance to extend TST's API. I mark this as "won't fix" because this can be done via API.

**Comment by irvinm** [comment]
@TrianguloY can you close this item?  I don't think there is more to do on the TST side.

**Comment by TrianguloY** [comment]
> Thanks for giving a chance to extend TST's API. I mark this as "won't fix" because this can be done via API.

And thanks to you for implementing it. I'm currently happy with my button-in-tab extension, but I'll try to play with that new api too.

> @TrianguloY can you close this item? I don't think there is more to do on the TST side.

Sure (I though you closed them when you considered, that's why I kept it open, sorry)
