### ISSUE TITLE
Better GTK theming on Proton when using "system theme" on Firefox

### ISSUE THREAD

**Issue by sith-on-mars** [piroor/treestyletab#2930]
I'm using Firefox 89 on OpenSUSE Tumbleweed. TST version: 3.8.1.

I followed "How to apply GTK+ theme color on Linux?" on Readme. It seems the fix for GTK theming doesn't work so well with the Proton UI when using "system theme". Here is an example:
![image](https://user-images.githubusercontent.com/37974764/121383495-d91a9580-c98a-11eb-9d41-77713758c5c6.png)

I think the unused tabs should not have "frames" and should blend in the background. This is the design principles of the Proton UI.

Interestingly, when I followed "How to apply colors customized via Firefox Color?" on Readme. Theming works better with Proton UI:
![image](https://user-images.githubusercontent.com/37974764/121384762-e71ce600-c98b-11eb-9ea4-d0ad3b655bf0.png)

I was using dark theme of Firefox. As you can see, unused tabs blend in the background.

**Comment by piroor** [comment]
Thanks, I forgot to update the information for Proton and include rules to use system colors to the Proton theme.

Sadly, due to restrictions of CSS system colors we cannot know the color of the headerbar in GNOME3. So I use inverted menu color on LInux instead.
https://github.com/piroor/treestyletab/blob/180b6fa502587a3528af7f2e4f4671aca58d244a/webextensions/sidebar/styles/proton/proton.css#L72-L113

**Comment by sith-on-mars** [comment]
Many thanks for the quick reply and fix. I’ll test it later today.

As for theming based on Firefox Color, I’m wondering does Proton and Photon use the same rules? The readme only mentions Photon, but the same rules seem work well enough on Proton, as you can see in the second screenshot.

**Comment by sith-on-mars** [comment]
I applied the new rules of GTK theming for Proton, and it doesn't look quite right. I'm using dark mode.
![image](https://user-images.githubusercontent.com/37974764/121465108-b85f3980-c9a4-11eb-82f7-eff6a5ced1c6.png)

**Comment by piroor** [comment]
It depends on recent changes. If you use TST 3.8.1, please try the latest development build: https://github.com/piroor/treestyletab#development-builds

**Comment by sith-on-mars** [comment]
> It depends on recent changes. If you use TST 3.8.1, please try the latest development build: https://github.com/piroor/treestyletab#development-builds

I'm now using TST 3.8.2 and I also tried the development build. I still get the same results for using Proton.

**Comment by piroor** [comment]
I've tried to reproduce the problem you described, but I couldn't get quite same result... Steps I did:

1. Install openSUSE Tumbleweed with KDE desktop.
2. Download Firefox 89 from official tar.bz2 and unpack it.
3. Start Firefox 89.
4. Right-click on Firefox's toolbar and choose "Dark" from the list of available themes.
5. Customize Firefox and TST with the description for GTK theme: https://github.com/piroor/treestyletab#appearance

Here is a screenshot I got. 
![image](https://user-images.githubusercontent.com/70062/121741721-dd38e580-cb39-11eb-8a07-599f037f58b5.png)
Is there any difference with actual steps you did?

**Comment by sith-on-mars** [comment]
> I applied the new rules of GTK theming for Proton, and it doesn't look quite right. I'm using dark mode.
> ![image](https://user-images.githubusercontent.com/37974764/121465108-b85f3980-c9a4-11eb-82f7-eff6a5ced1c6.png)

Sorry I was bit unclear. In my previous post I meant I used the global dark mode on my Tumbleweed, not on my Firefox. I actually used used "system theme" rather than "dark" in Firefox. So yes, my step 4 was bit different and GTK theming didn't work well when I used "system theme".

I'm also wondering does using the customisation for GTK theme intend to work with different Firefox customised themes other than "system theme"? To my knowledge, only "system theme" respects your GTK settings, and the customisation for GTK theme of TST is designed for "system theme".

Edited the title and the first comment for the better clarification.

**Comment by piroor** [comment]
OK, I've tried the combination of the "Breeze Dark" of KDE and the default theme of Firefox, and I've got bright background and dark tab like your screenshot. In short: it happens due to [rules for a bright theme](https://github.com/piroor/treestyletab/blob/180b6fa502587a3528af7f2e4f4671aca58d244a/webextensions/sidebar/styles/proton/proton.css#L98-L113). Paste only [basic style rules for both bright theme and dark theme](https://github.com/piroor/treestyletab/blob/180b6fa502587a3528af7f2e4f4671aca58d244a/webextensions/sidebar/styles/proton/proton.css#L72-L97) to the user styles, then I successfully got a naturally colored sidebar:
![image](https://user-images.githubusercontent.com/70062/121778856-d9f23800-cbd3-11eb-9f52-3a013ee99a04.png)

**Comment by sith-on-mars** [comment]
Nice, thanks! 

I kind of feels the background colour is bit too dark, almost black. I think the background should look brighter in your KDE and my Gnome environment. Now this is what it looks like:
![image](https://user-images.githubusercontent.com/37974764/121779601-e7152400-cbdf-11eb-912b-fa49b2001225.png)

This is the Photon theme does better with GTK theming and looks closer to the system GTK theme. As you can see, the background looks more dark-brownish:
![image](https://user-images.githubusercontent.com/37974764/121779640-0d3ac400-cbe0-11eb-8111-563204e9fa43.png)

**Comment by piroor** [comment]
Thanks, I didn't realized that colors of Firefox's "Dark" theme was changed for Proton. With the commit c162c02 you'll see more natural colors on the Dark mode.

**Comment by sith-on-mars** [comment]
Incidentally, I discovered that if you put ` --tabbar-bg: var(--browser-bg-darker, ThreeDShadow);` after the line of `--tab-dropmarker: var(--browser-fg, -moz-dialogtext);`, the background of the Proton theme looks the same as the background of the Photon theme. I saw ` --tabbar-bg: var(--browser-bg-darker, ThreeDShadow);` is in the Photon rules, but not in Proton rules and I just copied and pasted this line. I don't have any programming experience so feel free to correct me. Here is what is looks like:

![image](https://user-images.githubusercontent.com/37974764/121780033-d06fcc80-cbe1-11eb-8f17-9d3c02fd2002.png)

And here is the rule:
```
  :root[color-scheme="system-color"] {
    --tab-text-regular: var(--browser-fg, -moz-dialogtext);
    --tab-text-inverted: var(--browser-bg-more-lighter, -moz-dialog);
    --tab-text-active: -moz-dialogtext;
    --tab-text-active-inverted: -moz-dialog;
    --tab-border: var(--browser-border, var(--browser-bg-more-darker, ThreeDShadow));
    --tab-surface-hover-color: var(--browser-bg-hover-for-header-image-proton, ThreeDHighlight);
    --tab-surface-active: var(--browser-bg-active-for-header-image, var(--browser-selected-tab-bg, -moz-dialog));
    --tab-surface-active-hover: var(--browser-bg-active-for-header-image, var(--browser-selected-tab-bg, -moz-dialog));
    --tab-dropmarker: var(--browser-fg, -moz-dialogtext);
    --tabbar-bg: var(--browser-bg-darker, ThreeDShadow);
  }
  :root[color-scheme="system-color"] #background::after {
    background: var(--browser-bg-darker, AppWorkspace);
    opacity: 0.15;

    bottom: 0;
    content: "";
    left: 0;
    margin: 0;
    overflow: hidden;
    padding: 0;
    position: fixed;
    right: 0;
    top: 0;
    z-index: 20;
  }
```

**Comment by sith-on-mars** [comment]
Tried the latest development build. It looks like this with the [rules for Proton](https://github.com/piroor/treestyletab/blob/180b6fa502587a3528af7f2e4f4671aca58d244a/webextensions/sidebar/styles/proton/proton.css#L72-L97)

![image](https://user-images.githubusercontent.com/37974764/121780432-a0292d80-cbe3-11eb-9b93-43fc7d8f3fb8.png)

It seems to me that [c162c02](https://github.com/piroor/treestyletab/commit/c162c02e119d532e387f0ad7908ccc9e5935e090) changed the default background colour closer to Firefox "dark" theme, which is a nice thing to have and I appreciate your efforts. For those who (maybe most of the users) don't want to dig in the TST settings and change the TST theme in accordance with their GTK theme, it's certainly an improvement. But Firefox "Dark" theme doesn't follow GTK theme at all and only "System theme" follow the GTK theme. I think to improve GTK theming on the Proton UI, a change in the Proton rule is still needed.

**Comment by piroor** [comment]
After more trials I decided to refresh the Proton theme totally. After the commit 33d3ebe4bc56335567c7397c22cb8fff0d2e5b8c custom user style hack should be obsolete and you just need to change about:config options to apply GTK Dark colors. Could you try the latest development build?

**Comment by sith-on-mars** [comment]
![image](https://user-images.githubusercontent.com/37974764/121803265-0d8c9b00-cc84-11eb-8235-c19bdb47e597.png)

The new commit made the Proton theme works even better than the GTK hack before. The TST background colour now exactly matches the background colour of the tab bar.

**Comment by sith-on-mars** [comment]
Many thinks for the improvements!
