### ISSUE TITLE
slow, freeze pc and crash

### ISSUE THREAD

**Issue by floriangasc** [piroor/treestyletab#2931]
## Short description
(sorry in advance for my english)

In recent days, once Tree style tab is enabled,  within a few (2 ou 3) seconds, the pc will be very slow and one second after server X not respond. Sometime it's return to TTY with stacktrace, sometimes it's freeze, but always, the pc have to restart with the power button.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. all is ok.
 
but

1. Start firefox with existing profile all extension disable
2. enable Tst -> crash/freeze
3. restart pc with power button
4. start only firefox -> crash/freeze
 
## Environment

 * Platform (OS): archlinux (last update 9 june 2021)
 * Version of Firefox: 89.0 "release"
 * Version (or revision) of Tree Style Tab: 8.0 and 8.1. il seem's good for 3.7.4
 * cpu: i7, ram 16giga 
 

 **I use Tst for many years now, thank for your work.**

**Comment by irvinm** [comment]
Just a couple of thoughts to try:

- Have you tried disabling TST to see if the issue still persists?
- Have you tried looking at about:performance when the "slowness" is occurring to see if something else is going on? (Or the browser console)
- Have you tried creating a new profile with just TST to see if it happens there?

**Comment by floriangasc** [comment]
1. «Have you tried disabling TST to see if the issue still persists?» yes and the issue disappear.
2. «Have you tried looking at about:performance when the "slowness" is occurring to see if something else is going on» it's not possible because pc is to slow for open this (event terminal with top not updated).
3. «Have you tried creating a new profile with just TST to see if it happens there?» all seem's good.

another point:

1. With new profile, TST doesn't cause problem. 
2. The better clue for the source of the problem, is number of tab (i don't know if it's a number of tab by windows or total tab acroos window): this is the only difference between when it's work and when it's crash. 

In old historic profile, i have may be 20 windows with may be 40/50 tab evarage by window (some window can have 3 tab, other can have 100 or plus tab)

**Comment by irvinm** [comment]
I don't think it will be related to the number of overall tabs.  I currently run around 600 tabs, but have been as high as 1200 ... although not in a while.  Let's see what @piroor thinks the next steps around this might be.

**Comment by piroor** [comment]
@floriangasc I couldn't reproduce such a crash on my testing archlinux environment. Something stored information may trigger the problem. Could you try bisection to minimize conditions to reproduce the problem? How to do that: https://github.com/piroor/treestyletab/wiki/How-to-minimize-conditions-to-reproduce-a-problem

**Comment by melimelo45** [comment]
I follow tutorial and there is some new fact:

`rm -rf /tmp/fxprofile/ && mkdir -p /tmp/fxprofile`
then
`cp -r ~/.mozilla/firefox/my-old-profile/XXX /tmp/fxprofile`
then
`firefox -no-remote -profile /tmp/fxprofile`

Then i found it's seem's related to one/somes of this files:

`
xulstore.json

webappsstore.sqlite
webappsstore.sqlite-wal
storage 
storage.sqlite
storage-sync.sqlite

storage-sync-v2.sqlite
storage-sync-v2.sqlite-shm
storage-sync-v2.sqlite-wal 

`
Moreover i feeling that problem is not produce of the first run but at second run for a given profile:
1. start ff with new profile p0 with tst all is ok
2. quit ff (ctr-q)
3 start ff with new profile p0 -> crash.

The same behavior is observable with the old historic profile and new tmp profile for bisect: 
1. I copy all file except "related files listed above". 
2. run with the command `firefox -no-remote -profile /tmp/fxprofile` : all seem's ok
3. close ff
4.  re-run with the command `firefox -no-remote -profile /tmp/fxprofile` : crash

**Comment by floriangasc** [comment]
I follow tutorial and there is some new fact:

`rm -rf /tmp/fxprofile/ && mkdir -p /tmp/fxprofile`
then
`cp -r ~/.mozilla/firefox/my-old-profile/XXX /tmp/fxprofile`
then
`firefox -no-remote -profile /tmp/fxprofile`

Then i found it's seem's related to one/somes of this files:

```
xulstore.json

webappsstore.sqlite
webappsstore.sqlite-wal
storage 
storage.sqlite
storage-sync.sqlite

storage-sync-v2.sqlite
storage-sync-v2.sqlite-shm
storage-sync-v2.sqlite-wal 
```
Moreover i feeling that problem is not produce of the first run but at second run for a given profile:
1. start ff with new profile p0 with tst all is ok
2. quit ff (ctr-q)
3 start ff with new profile p0 -> crash.

The same behavior is observable with the old historic profile and new tmp profile for bisect: 
1. I copy all file except "related files listed above". 
2. run with the command `firefox -no-remote -profile /tmp/fxprofile` : all seem's ok
3. close ff
4.  re-run with the command `firefox -no-remote -profile /tmp/fxprofile` : crash


I hope this will help and what that was expected.


ps:  all file in profile that seem's cause not trouble

```
addons.json 
addonStartup.json.lz4 
AlternateServices.txt 
autofill-profiles.json 
blocklist-addons.json 
blocklist-gfx.json 
blocklist-plugins.json 
blocklist.xml 
bookmarkbackups 
broadcast-listeners.json 
browser-extension-data 
cert9.db 
ClientAuthRememberList.txt 
compatibility.ini 
containers.json 
content-prefs.sqlite 
cookies.sqlite 
cookies.sqlite-wal 
crashes 
datareporting 
dh-ldata.json 
enumerate_devices.txt 
extension-preferences.json 
extensions 
extension-settings.json 
extensions.json 
favicons.sqlite 
favicons.sqlite-wal 
features 
formhistory.sqlite 
gmp 
gmp-gmpopenh264 
gmp-widevinecdm 
handlers.json 
jetpack 
key3.db 
key4.db 
logins-backup.json 
logins.json 
mediacapabilities 
mimeTypes.rdf 
minidumps 
notificationstore.json 
permissions.sqlite 
persdict.dat 
pkcs11.txt 
places.sqlite 
places.sqlite-wal 
pluginreg.dat 
prefs.js 
protections.sqlite 
saved-telemetry-pings 
search.json.mozlz4 
secmod.db 
SecurityPreloadState.txt 
security_state 
serviceworker.txt 
sessionCheckpoints.json 
sessionstore-backups 
shield-preference-experiments.json 
signedInUser.json 
signons.sqlite 
SiteSecurityServiceState.txt 
times.json 
weave 
```

**Comment by piroor** [comment]
Thank you for a research! The result says that one of these data triggers the crash: toolbar customization state (including automatically inserted TST's toolbar button), sidebar state (open/close), window dimensions, or TST's saved configs (they are initialized and saved on the first startup). Hmm, but they look won't trigger any critical crash...

Does the problem happen on Nightly and Firefox ESR78 also? If you don't see the problem with other versions of Firefox, TST might hit something unknown bug of Firefox itself.

And I think that some changes on TST 3.8.0 possibly triggers such unknown Firefox bugs:

* Added accessibility information (ARIA-role) of sidebar contents. Indeed, on Windows there is a known trouble (maybe a bug of something other application) around accessibility feature of Firefox itself: https://support.mozilla.org/en-US/kb/accessibility-services
* Box-shadow, half-transparent colors, and citing of GTK theme colors. If there is unknown bugs around graphic drivers or graphic chipsets, TST's new theme may hit them.

If you never see the problem on another archlinux instance, it can be a platform specific issue, then it is very hard for me to debug that remotely...

**Comment by piroor** [comment]
One more testing, could you try these steps?:

1. Start Firefox with clean profile.
2. Install TST. (You told that this don't crash Firefox.)
3. Disable TST via about:addons.
4. Exit Firefox.
5. Start Firefox again.
6. Enable TST via about:addons.

If you don't see any crash with these steps, the problem looks to be a delicate timing issue: two or more operations done at the same time may conflict and hit something triggering the crash.

**Comment by floriangasc** [comment]
I retest tomorrow with your exact scenario, but, i test little variation (because i need my old profile for work):

1. start firefox with old profile (all extension enable and so on), 
2. disable TST between ff bootstraping (and before crash).
3. wait bootstrap completed: when all tab and windows seems stable, and when cpu  (command top in terminal) is  also stable.
4. enable TST all seems work.

ps:
1.  Same result if TST is disabled before ff bootstrap and re-enable after ff bootstrap complete.
2. «Box-shadow, half-transparent colors, and citing of GTK theme colors. If there is unknown bugs around graphic drivers or graphic chipsets, TST's new theme may hit them.» ===> i recently install a driver for my graphic card (before I use i7 embed graphic).
3. I use also firefox developer. It seems to have the same behavior as release, but I don't make a lot of testing on this for the bug. But I use ff developer every day, so if you need, I can make the same bisect test.
4. I have test intel graphic instead of nvidia, i am not sure if it's change something (maybe the way of crash, firefox display a pop up for send report and restart, not usable because pc is freeze).
5. I don't know if t's make sens, but if it can you help : the workaround (disable -> bootstrap complete enable), seems good for one firefox, but if two (or more) firefox run in same time (with 2 profiles, or release and developer like example), i got the same crash.
6. Thank you for a response \o/.

**Comment by floriangasc** [comment]
another information:

tree style tab 3.8.2 on firefox 88.0.1 "release" and firefox "developer" 90.0b4  on archlinux work prefectly (it's not same pc, but almost same hardware)

**Comment by floriangasc** [comment]
For now :

1. after reinstall msa + graphic card driver and use TST 3.8.3
2. create new profile with all file in bisect that cause not trouble (cf previous post)

all is ok \o/ : no lost any history, or tab hierarchy, all run very well. 

I think it's related to this: «Box-shadow, half-transparent colors, and citing of GTK theme colors. If there is unknown bugs around graphic drivers or graphic chipsets, TST's new theme may hit them.»  Firefox is main program gui my pc run/exec. 

I should have run other graphics software before posting the issue. I am confused that I wasted your time on a bug which is not your control. Please excuse me. Thank you very much for everything again (whether it's your time for help me on this bug or your time on this extension).
