### ISSUE TITLE
Regression in disable browser theme colors and images snippet in TST 3.8.2

### ISSUE THREAD

**Issue by gotyaoi** [piroor/treestyletab#2934]
## Short description
The commit https://github.com/piroor/treestyletab/commit/b81677d876333a278bbae94c58451c6295c52e4d caused a regression with the https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#disable-browser-theme-colors-and-images-2662 snippet. Workaround, added `--browser-bg-images: unset;` to the TST custom CSS for that snippet. Not sure if anything else needs to be added.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install a theme with custom colors or header
 3. Install TST.
 4. Apply the disable browser theme colors and images snippet in the TST options page.

## Expected result
Theme colors and header image do not appear in the TST sidebar.

## Actual result
Theme colors and header image do appear in the TST sidebar.

## Environment

 * Platform (OS): Win10
 * Version of Firefox: 89.0
 * Version (or revision) of Tree Style Tab: 3.8.2

**Comment by piroor** [comment]
User style rules for the purpose need to be updated for TST 3.8.2. I've updated the snippet: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#disable-browser-theme-colors-and-images-2662

**Comment by piroor** [comment]
This is a fault from un-updated user styles, and TST side won't "fix" this.

**Comment by irvinm** [comment]
@gotyaoi can you add your finding into that section on the wiki and close this item?  Just click the "edit" button, add that one line, and click "save page" at the bottom.  Thanks!

**Comment by gotyaoi** [comment]
Looks like @piroor already updated it, so I think we're all good.
