### ISSUE TITLE
new tab button dissappears under version 3.8.2

### ISSUE THREAD

**Issue by Orxenhorf** [piroor/treestyletab#2939]
## Short description

New tab button skinning disappears when version is updated to 3.82.  (Might just need to know what change between versions is applicable.)

## Steps to reproduce

 1. Download version 3.8.1 from addons.mozilla.com
 3. Select "No Decoration" style in Appearance preferences and install attached file under "Extra style rules for contents provided by Tree Style Tab" in Advanced section.  (It's the "Metal" theme replacement from the version 3.5.16 change notes.)
 2. New tab button appears as a bar.
 3. Update to version 3.8.2
 4. New tab button becomes only a "+" sign
 5. Reinstall 3.8.1 and it comes back

[TST_metal_style.txt](https://github.com/piroor/treestyletab/files/6643085/TST_metal_style.txt)

## Expected result
3.8.1 screenshot:
![tst_3-8-1](https://user-images.githubusercontent.com/85811153/121791713-d0a8a180-cbba-11eb-955f-49262724c4e8.jpeg)

## Actual result
3.8.2 screenshot:
![tst_3-8-2](https://user-images.githubusercontent.com/85811153/121791714-d8684600-cbba-11eb-8f7a-f11ed68a88ae.jpeg)

## Environment

 * Platform (OS): macOS 10.13.6
 * Version of Firefox: 89.0
 * Version (or revision) of Tree Style Tab: 3.8.2

**Comment by piroor** [comment]
User styles to restore old appearance need to be updated for TST 3.8.2 and later, because the "new tab" button is now `<div role="button">` instead of `<button>`.  I've updated the snippet https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#restore-old-built-in-themes , so could you try the latest one?

**Comment by piroor** [comment]
And I won't "fix" this on TST side because I think this is a problem of a user style.

**Comment by Orxenhorf** [comment]
Works well, and in the newer 3.8.3 as well.   Thank you.
