### ISSUE TITLE
Tree grabs unbranched tabs

### ISSUE THREAD

**Issue by ThomasMcA** [piroor/treestyletab#294]
I use FF11 in Linux with TST, BarTab Lite and TMP (among other add-ons). I have hundreds of tabs, and BarTab Lite keeps most of them inactive. One tree had about 8 branches, but after restarting FF it grabbed many unbranched tabs, and now has over 100.

1) This is a bug, obviously. :)
2) There is no "disconnect/unbranch tree" option. Because of that, fixing this requires dragging 90+ tabs out of the tree, or changing the "when parent tab is closed" option to "liberate," close the parent, put that setting back, then recreate the correct tree. And hope this doesn't happen again.

PS: If TST had options to control the Close buttons, I wouldn't need TMP. I only installed TMP because NONE of my tabs had close buttons after installing TST.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
