### ISSUE TITLE
regression: "close this tree" lag

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#2940]
## Short description

Either due to fx or tst update there's now a perceptible lag in the closing of a tree, triggered via the sidebar tab context menu. It's perhaps more evident with "show dialogs in the sidebar"

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. set "show dialogs in the sidebar" 
 4. create a parent->child tree, in addition to the default tab, so that fx does not close when the tree is closed
 5. invoke "close this tree" on the parent
 6. confirm closing in the dialog
 7. after the confirmation dialog closes, there's about a second delay before the tree starts closing, it's definitely noticeable and longer than it used to be. 

## Expected result

no lag

## Actual result

lag

## Environment

 * Platform (OS): win10 21H1 x64
 * Version of Firefox: 89.0 x64
 * Version (or revision) of Tree Style Tab: 3.8.2

**Comment by piroor** [comment]
Oops this accidentally become closed by the commit message of f3488a6... Anyway it should fix this regression.

**Comment by bughit** [comment]
There also seems to be a delay in the regular dialog, though not after closing, but between the click and the closing.

**Comment by piroor** [comment]
The change looks to solve the problem on regular dialogs.
