### ISSUE TITLE
The background of TST changes after updating to 3.8.2

### ISSUE THREAD

**Issue by mzso** [piroor/treestyletab#2941]
## Short description
I had a theme installed which adds a background image to the toolbar
After updating this vertically stretched became the background of TST. Which doesn't look that hot with the scaled image.

Also, the weird thing is I'm quite sure I overrode the background of TST:   `--browser-background: rgb(12, 12, 13);`

Not sure what to make of this, previously I couldn't make the background the same as the toolbar via CSS, even though I tried.
And even now it doesn't work for the built in white theme, but does with Alpenglow.

So what does this mean. Now it's possible to match the appearance of TST with the browser UI? But only via theme? Or CSS as well? Only via image background?

Is the background being overwritten even though me having set a background color a feature or a bug?

By the way: I have disabled all proton options via about:config.

## Environment

 * Platform (OS): Win10
 * Version of Firefox: 88.0b9 (dev edition)
 * Version (or revision) of Tree Style Tab: 3.8.2

**Comment by piroor** [comment]
I've reconstructed the Proton theme totally after TST 3.8.2. Could you try the latest development build https://github.com/piroor/treestyletab#development-builds ?

**Comment by mzso** [comment]
[**@piroor**](https://github.com/piroor) commented on [2021. jún. 13. 11:06 CEST](https://github.com/piroor/treestyletab/issues/2941#issuecomment-860178400 "2021-06-13T09:06:30Z - Replied by Github Reply Comments"):
> I've reconstructed the Proton theme totally after TST 3.8.2. Could you try the latest development build [https://github.com/piroor/treestyletab#development-builds](https://github.com/piroor/treestyletab#development-builds) ?

I guess. But right now I don't have proton enabled. So, regardless of proton something changed on FF side to make this possible?

**Comment by mzso** [comment]
[**@piroor**](https://github.com/piroor) commented on [2021. jún. 13. 11:06 CEST](https://github.com/piroor/treestyletab/issues/2941#issuecomment-860178400 "2021-06-13T09:06:30Z - Replied by Github Reply Comments"):
> I've reconstructed the Proton theme totally after TST 3.8.2. Could you try the latest development build [https://github.com/piroor/treestyletab#development-builds](https://github.com/piroor/treestyletab#development-builds) ?

Is anything supposed to look different? It looks rather identical to me.

**Comment by piroor** [comment]
Sorry I missed the last note about disabled Proton.

**Comment by piroor** [comment]
Please describe how to reproduce the problem you saw on my environment. I don't know what theme you are using.

**Comment by mzso** [comment]
[**@piroor**](https://github.com/piroor) commented on [2021. jún. 13. 11:25 CEST](https://github.com/piroor/treestyletab/issues/2941#issuecomment-860180736 "2021-06-13T09:25:29Z - Replied by Github Reply Comments"):
> Please describe how to reproduce the problem you saw on my environment. I don't know what theme you are using.

I'm not sure there's a problem, or that I just don't understand what happens and why.
The background being replaced despite being set by `--browser-background: rgb(12, 12, 13);`  in TST happens even with the FF built in alpenglow theme. I guess this could be a potential bug. (Otherwise I wouldn't even noticed that this is possible)

The bitmaps being scaled I guess are normal, since what the themes use are nowhere near as tall as the sidebar. These are some that I tried, where it's noticeable:
https://addons.mozilla.org/hu/firefox/addon/rustic-wood/
https://addons.mozilla.org/hu/firefox/addon/dark-wood/

**Comment by piroor** [comment]
Thanks, I've tried those two themes and maybe understood what you told about. In short, you need to clear `--browser-bg-images` with the custom user style, like following:

```css
#background {
  --browser-background: rgb(12, 12, 13);
  --browser-bg-images: none;
}
```

Background images are always rendered over the background color. From TST 3.8.2 style declarations for the background is separated to each property: `background-color`, `background-image`, `background-position`, `background-size` and `background-repeat`. The variable `--browser-background` affects only to `background-image`.

I think this is a problem of user style rules wrote for old versions TST. In general, user styles always need to be updated when TST is updated. This is the reason why the user styles editor is placed under the "Advanced" section: it is a feature for people who know CSS and how to inspect TST's sidebar itself. If you find something CSS snippet incompatible to the latest TST, the wiki page need to be updated.

**Comment by mzso** [comment]
@piroor 
Hmm. I see.
Though interesting if that I remove bg image and don't set a color I usually get very out of place colors (which appears to be the same as "--theme-colors-frame"). Including with the above mentioned themes. But weirdly even with the built in alpenglow theme I get some light grey instead of the one the built-in sidebars get (a shade of purple).

![kép](https://user-images.githubusercontent.com/4479090/121805821-229a0780-cc4d-11eb-9579-e32ab75c5e99.png)

vs. 

![kép](https://user-images.githubusercontent.com/4479090/121805836-3e9da900-cc4d-11eb-91a3-20d54e045d3f.png)

**Comment by piroor** [comment]
The difference is due to a restriction of WebExtensions API and it need to be solved by Firefox side. Alpenglow has two color schemes bright and dark, and the theme API only returns the bright colors to extensions. Please see also the bug: [1542044 - browser.theme.getCurrent() & onUpdated should take in account `dark_theme` manifest field](https://bugzilla.mozilla.org/show_bug.cgi?id=1542044)

**Comment by irvinm** [comment]
@piroor I think this one can be closed.
