### ISSUE TITLE
Container tab menu disappears when releasing long-press on new tab button

### ISSUE THREAD

**Issue by pnthach95** [piroor/treestyletab#2944]
## Short description

Before version 3.8.2, to open container tab menu, long-press on new tab button then choose an item.
From version 3.8.2 to 3.8.3, the menu shows but I have to hold and drag mouse to item to open container tab.

## Steps to reproduce

 1. Hold down mouse on new tab to show container tab menu.
 2. Release mouse, the menu disappears.
 3. Hold down mouse on new tab to show container tab menu.
 4. Drag mouse to container and release, new container tab is opened

## Expected result

After a long-press on new tab button, container tab menu should appear and stay there.

## Actual result

After a long-press on new tab button, container tab menu disappears. This behavior is changed but I don't see on change log.

## Environment

 * Platform (OS): Windows 10 Home
 * Version of Firefox: 89.0
 * Version (or revision) of Tree Style Tab: 3.8.3

**Comment by piroor** [comment]
Thanks, this is a regression of recent changes and fixed by commits 10f15a0 and https://github.com/piroor/webextensions-lib-menu-ui/commit/ae4ee9b3004b835ff1e0e514e8b7264193f0f01e

**Comment by irvinm** [comment]
@pnthach95 TST 3.8.4 has been released.  Can you verify and close this item if resolved?

**Comment by pnthach95** [comment]
Resolved
