### ISSUE TITLE
Close Multiple Tab Options Gone in v 3.8.3 

### ISSUE THREAD

**Issue by viking2** [piroor/treestyletab#2945]
The right click options to close multiple tabs (e.g. close other Tabs or Close tabs to the bottom) disappeared in TST v3.8.3 (& FF 89.0). The options are still there if I click on the regular top Firefox tabs.

**Comment by piroor** [comment]
I've found a bug affecting to the initial startup, and the commit d5b59a1 should fix it. I think your case is also covered by the fix.

**Comment by irvinm** [comment]
@viking2 TST 3.8.4 has been released.  Can you verify and close this item if resolved?

**Comment by viking2** [comment]
It is difficult to say if it has been fixed in v3.8.4 because with the previous v3.8.3, I sometimes saw the "Close Multiple Tab Options" and other times not. I will close this issue now and reopen it if it is missing again.
