### ISSUE TITLE
Clicking "Close Tab" button on the TST sidebar twice doesn't force close a tab with leave confirmation alert popup

### ISSUE THREAD

**Issue by NgoKimPhu** [piroor/treestyletab#2947]
## Short description
Clicking "Close tab" button again after close-tab confirmation dialog pops up doesn't force close the tab. This is the behavior for the traditional Tab bar.

## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install TST.
 3. Go to a page that implements Leave confirmation alert (e.g. https://cdpn.io/nvictorme/fullpage/OGpQbX)
 4. Click the "Close tab" button on the TST sidebar.
 5. A popup appears that says "This page is asking you to confirm that you want to leave — information you’ve entered may not be saved."
 6. Click the "Close tab" button on the TST sidebar.
 7. The tab doesn't get closed.
 8. Click the "Close tab" button on the traditional tab bar.
 9. The tab gets properly closed.

## Expected result
The tab gets closed.

## Actual result
The tab doesn't get closed.

## Environment

 * Platform (OS): Mac 11.3.1
 * Version of Firefox: Firefox Developer 90.0b3
 * Version (or revision) of Tree Style Tab: 3.8.3

**Comment by piroor** [comment]
Sadly this is impossible to "fix" by extension side, this is one of restrictions of WebExtensions API.

Firefox's built-in "close tab" action uses [a special option `skipPermitUnload`](https://searchfox.org/mozilla-central/search?q=skipPermitUnload&redirect=false). When the option is given, Firefox forcefully closes the tab. On the other hand, [the implementation of the `tabs.remove()` WebExtensions API calls the method to remove given tab without `skipPermitUnload` option](https://searchfox.org/mozilla-central/rev/b172dd415c475e8b2899560e6005b3a953bead2a/browser/components/extensions/parent/ext-tabs.js#813). As the result an extension never can close a tab containing confirmation dialog on "DOMWindowClose" event.

**Comment by NgoKimPhu** [comment]
thank you for the detailed explanation
