### ISSUE TITLE
Pinned tabs don't expose "close tab" in the TST context menu anymore

### ISSUE THREAD

**Issue by mfn** [piroor/treestyletab#2950]
## Short description
I'm 110% sure 😅 that a few weeks ago, I was able to right click on a pinned tab and chose "close tab" (like on a regular tab), but it's now gone. It's still exposed in the browsers native tab, but not within TST

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Pin a tab
 4. Right-click and try to locate "close tab"

## Expected result
Be able to locate and "close tab"

## Actual result
Not present

## Screenshots
Right click on regular pinned tab:
![image](https://user-images.githubusercontent.com/87493/122736718-9b6a1680-d280-11eb-8a79-41e44862adea.png)

Right click on TST pinned tab:
![image](https://user-images.githubusercontent.com/87493/122736769-a7ee6f00-d280-11eb-8926-ba832f790cb7.png)

## Environment

 * Platform (OS): OSX 17.15.7
 * Version of Firefox: 89.0.1
 * Version (or revision) of Tree Style Tab: 3.8.3

**Comment by piroor** [comment]
This looks to be same to #2945, and it should be fixed on the version 3.8.4 I've already uploaded.

**Comment by irvinm** [comment]
@mfn can you close this item?

**Comment by mfn** [comment]
The latest version was not yet available to me the last time I checked the issue.

But I just witnessed the future: I noticed TST was restarting a few minutes ago. I right clicked on a pinned tab and, 'lo and behold, the usual context items were back.

Quite a "wow" effect I experienced here.

Oh, and thank you for fixing it so quickly :)
