### ISSUE TITLE
Consider using GitHub action(s) for issue labels

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#2951]
## Short description
Consider using one or more GitHub actions to help automate transitioning issues more effectively.

## Steps to reproduce
Having a fairly large number of issues over time, having some automation based on labels (which only you can set\modify) would help transition some items that should be closed over time.

## Expected result
Looking at the current set of labels:

bug of Firefox itself
bug of platform itself
conflict with another addon
deadlocked
dependencies
duplicated
expired
fixed
help wanted
invalid
Legacy
maybe fixed
maybe invalid
out of purpose
partially fixed
platform specific
release blocker
WebExtensions
wontfix
workaround exists
works fo me 

**(Can you rename "works fo me" as "works for me"?)**

Using a Github action like:  https://github.com/marketplace/actions/close-issues-with-label (there are others as well)

I could see trying to set some interval where items such as:

- "duplicated", "expired", "wontfix", "out of purpose" or "invalid" should be closed fairly quickly (days?)
- "workaround exists", "maybe fixed", "fixed" should be closed after a little longer time (weeks?)
- Items not updated in a few months maybe get a "stale" label automatically then eventually closed out if not updated (might have to try to exclude items with "bug of Firefox itself" as those will be open much longer)

I always hate either bugging you or the OP for updates on a regular basis, but without it the backlog would get much longer.

This is just an idea and don't want to discourage discussion or doing the right thing, but I also think items that should clearly be closed shouldn't require additional effort.

**Comment by piroor** [comment]
Reminder: I must do this.

**Comment by piroor** [comment]
https://github.com/piroor/close-expired-issues-based-on-label

**Comment by piroor** [comment]
I've added a scheduled action with the commit bd3e29c experimentally. It will be executed at 5:00 AM.

**Comment by piroor** [comment]
Hmm... I added "exception labels" feature to keep some specific issues open, but only the environment variable to define exceptions is not visible in the script...

**Comment by irvinm** [comment]
Cool.  I saw the bot took some actions and I think adding exception labels is a good idea.

**Comment by irvinm** [comment]
One other idea or recommendation might be to augment the action to make a comment as to why the action was taken.  Example:  This item has a "won't fix" label and has been open for more than 7 days.

This might help people understand and not have to ask questions as to why the bot took the action.

**Comment by piroor** [comment]
I changed expiration days because I frequently become silent:

* Issues requireing something action by the reporter will expire after 7 days.
* Looks-to-be-closable issues will expire after 14 days.
