### ISSUE TITLE
Change F1 to any other button

### ISSUE THREAD

**Issue by KL13NT** [piroor/treestyletab#2953]
Is there a way to change the `F1` shortcut to something else? I can't find it in the options.

**Comment by irvinm** [comment]
https://github.com/piroor/treestyletab/issues/2846

**Comment by piroor** [comment]
I've added this to FAQ: https://github.com/piroor/treestyletab/blob/trunk/README.md#feature-requests

**Comment by sysadmjones** [comment]
I'd like to see this feature.  CTRL+B already opens the bookmark sidebar, and CTRL+H opens history.  So maybe there is a shortcut close to those two, to allow switching between these windows.
