### ISSUE TITLE
Formatting tabs in TST sidebar with userchrome

### ISSUE THREAD

**Issue by kazerniel** [piroor/treestyletab#2954]
## Short description
Trying to tweak TST's tab display, but can't pick out most elements from the sidebar tab list with Firefox's Browser Toolbox.

The tabs aren't visible in the HTML inspector either.

Tried to see what patterns the [code snippet list](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules) uses, but out of the 4-5 snippets I tried, none of them works in the Browser Toolbox's live preview.

## Steps to reproduce

 1. Start Firefox's Browser Toolbox
 2. With the inspector try to select elements such as the close box of individual tabs or the new tab button on the bottom of the list.
 3. See that it doesn't work. These elements don't show up in the HTML code inspector either.

## Expected result
To be able to pick out and manipulate other elements like it's possible with the #sidebar-header.

## Actual result
These elements don't show up in the HTML inspector. The closest I seem to get is a `<browser>` element with id="webext-panels-browser".

## Environment

 * Platform (OS): Win10
 * Version of Firefox: 89.0.2 x64
 * Version (or revision) of Tree Style Tab: 3.8.4

**Comment by piroor** [comment]
You need to use the debugger started from `about:debugging`.
https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs

**Comment by piroor** [comment]
I close this because this is not a problem of TST itself.
