### ISSUE TITLE
When theme is set to Proton, tab titles are invisible

### ISSUE THREAD

**Issue by the-trooper0000** [piroor/treestyletab#2955]
## Short description

When theme is set to Proton, tab titles become invisible.
https://i.imgur.com/vEbmKXq.jpg (first tab in the image)

 * Platform (OS):  Windows10 Version 2004 Build 19041.804
 * Version of Firefox: 89.0.2
 * Version (or revision) of Tree Style Tab: 3.8.4

**Comment by piroor** [comment]
This doesn't happen on my environment.

* Does the problem appear [with clean profile](https://github.com/piroor/treestyletab/wiki/How-to-run-Firefox-with-a-clean-profile)?
* Do you use any custom user styles?

**Comment by the-trooper0000** [comment]
>     * Does the problem appear [with clean profile](https://github.com/piroor/treestyletab/wiki/How-to-run-Firefox-with-a-clean-profile)?

No, everything's fine with a new profile. So, obviously the issue is on my end. Not sure what could cause it, i don't use any other tree like extension, any sidebar customization extension. Or any customization extension at all, for that matter.

>     * Do you use any custom user styles?

No, nothing.

**Comment by piroor** [comment]
Thank you for update. I have more questions:

* Which Firefox theme do you use? (System, Light, Dark, or others?)
* Which color scheme do you use for Windows 10 itself?
* Could you export TST's all configs (TST options => Development => All Configs => Export) and send to me?

**Comment by the-trooper0000** [comment]
>     * Which Firefox theme do you use? (System, Light, Dark, or others?)

System theme.

>     * Which color scheme do you use for Windows 10 itself?

Slightly customized default, nothing much, just some color through the options themselves (no regedit hacks or anything like that). Here's how it's set up:
https://i.imgur.com/QwN2ICd.jpg
 
>     * Could you export TST's all configs (TST options => Development => All Configs => Export) and send to me?

Sure, here they are:
https://we.tl/t-krXCpTcoCA

Note:
Updated to 90.0.1, on two different PCs, same thing! So it must be some combination of my extensions. Here's a list of what I'm using.
But, here's the thing, if I'm the only one affected by this don't waste your time on it! I like "high contrast" theme better anyway :)

Add-on List-o-matic 9000 1.5

Behind The Overlay 0.1.6
http://github.com/NicolaeNMV/BehindTheOverlay

Bitwarden - Free Password Manager 1.51.1
https://bitwarden.com

Bookmark Dial 2.0.4
https://github.com/sblask/webextension-bookmark-dial

Decentraleyes 2.0.15
https://decentraleyes.org

Downloads sidebar 1.0.1
https://github.com/aesqe/firefox-downloads-sidebar

Drag-Select Link Text 1.5.4
https://github.com/nkestrel/dragselectlinktext

DragLinks 1.10
https://github.com/Speedkore/draglinks

Enhancer for YouTube™ 2.0.104.13
https://www.mrfdev.com/enhancer-for-youtube

Everything Metric - Auto Unit Converter 3.4

Firefox Multi-Account Containers 7.3.0
https://github.com/mozilla/multi-account-containers#readme

Gesturefy 3.2.0
https://github.com/Robbendebiene/Gesturefy

HTTPS Everywhere 2021.7.13
https://www.eff.org/https-everywhere

Make Google Images Great Again 0.2.0
https://gitlab.com/donnieclapp-OS/make-google-images-great-again

Old Reddit Redirect 1.5.1
https://github.com/tom-james-watson/old-reddit-redirect

Reddit (Au) Comment Highlights 1.2.1
https://github.com/aesy/reddit-comment-highlights

Reddit Comment Collapser 5.1.1
https://github.com/tom-james-watson/reddit-comment-collapser

Reddit Enhancement Suite 5.22.5
https://redditenhancementsuite.com

Reddit Submission Finder 0.10.2

ScrollAnywhere 8.7
https://fastaddons.com/

Search by Image on Google 1.6
https://github.com/Sukigu/search-by-image-on-google

Select After Closing Current 5.2

Simple Translate 2.5.3
https://simple-translate.sienori.com

Sort Bookmarks 0.6
https://github.com/heftig/sort-bookmarks

Tab Flag 1.1

Tab Session Manager 6.8.3
https://tab-session-manager.sienori.com/

Tree Style Tab 3.8.8
http://piro.sakura.ne.jp/xul/_treestyletab.html.en

TST Mouse Wheel and Double Click 1.5
https://github.com/joshuacant/

uBlock Origin 1.36.2
https://github.com/gorhill/uBlock#ublock-origin

Undo Close Tab Button 1.7
https://codefisher.org/toolbar_button/

Video Speed Controller 0.6.3.3
https://github.com/codebicycle/videospeed

View Image Context Menu Item 3.2.1

Zoom Page WE 18.6

**Comment by piroor** [comment]
@the-trooper0000 I'm very sorry, I missed to download your JSON file until the link was expired... Could you upload it again?

**Comment by the-trooper0000** [comment]
> @the-trooper0000 I'm very sorry, I missed to download your JSON file until the link was expired... Could you upload it again?

Sorry for not replying sooner. Here it is:
https://filetransfer.io/data-package/XE6dzrCI#link

**Comment by piroor** [comment]
Thank you for re-uploading! I've imported it and realized you needed to change the background color of the rounded box placed in a tab, instead of the tab itself.

Before:

```css
.tab.active {
  height: 39px !important;
  background-color: #193B99;
}
```

After:

```css
.tab.active {
  height: 39px !important;
}
.tab.active .background {
  background-color: #193B99;
}
```

Screenshot:
![image](https://user-images.githubusercontent.com/70062/130258472-09c3c11c-beec-41d6-a9ed-ef7c1db47a48.png)

**Comment by piroor** [comment]
I ordinarily try to keep compatibility of custom user styles, but I couldn't avoid the breaking change at TST 3.8.5 due to some requirements. Thus user styles written for old TST need to be updated. Here is some hints to write CSS for TST 3.8.5 and later.
https://github.com/piroor/treestyletab/discussions/2960#discussioncomment-972745

**Comment by the-trooper0000** [comment]
Fixed!
I have no idea when and how I made that change :D Probably copied it from somewhere on Reddit.

Thank you!
