### ISSUE TITLE
Bookmarked tree not restored if about:newtab entries present

### ISSUE THREAD

**Issue by gonhidi** [piroor/treestyletab#2956]
## Short description

TST has options to bookmark a tree of tabs and then restore it from the bookmarks. If one of the bookmark entries is a tab with an `about:newtab` URL (which I will call from now on a newtab), the tree is not restored properly.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Give TST the “Read and modify bookmaks” permission (at a minimum).
 4. Create a tab tree containing at least one newtab.
 5. Use TST's “Tree of tabs” “Bookmark this tree...” option.
 6. Use TST's “Open All as a Tree” option on the newly created bookmark folder.

A couple of example trees, where X is a newtab:
* Tree A:
  ```
  X
  \-A
  ```
* Tree B:
  ```
  A
  \-X
  | \-B
  |-C
    \-D
  ```

## Expected result

The trees should be restored properly, exactly the same as the example trees.

## Actual result

The trees are not restored properly: the newtabs are not restored and all tabs end up at the same level.

* Tree A:
  ```
  A
  ```
* Tree B:
  ```
  A
  B
  C
  D
  ```

## Environment

 * Platform (OS): macOS Catalina 10.15.7
 * Version of Firefox:  89.0.2
 * Version (or revision) of Tree Style Tab:  3.8.4

## Workaround(ish)

If what one desires are blank-looking nodes/tabs, using `about:blank` instead of `about:newtab` (e.g. via an extension for new tabs; editing the bookmarks for already created trees) could be a compromise. (The looks of `about:home` are even closer / identical to a newtab on my system, but TST is restoring those pages as `about:blank?about:home` tabs.)

**Comment by piroor** [comment]
Thanks, the commit a1bbafd should fix this regression.

**Comment by gonhidi** [comment]
It does seem fixed. Thank you!
