### ISSUE TITLE
[Proposal] Add named groups (folders)

### ISSUE THREAD

**Issue by PubliqPhirm** [piroor/treestyletab#2957]
## Short description

Add the ability for end users to create named groups/folders of tabs to TST.  The extension [Tree Tabs](https://gitlab.com/kroppy/TreeTabs/) has this feature.  However, it has not been updated at all in two years, which is why I am asking for this functionality to be added to TST (since there is active development here).  A brief DDG search for "tree style tab named folders" did not yield any promising leads for cooperative extensions to add this to TST.

## Expected result

With the named folders, tabs can be grouped with a descriptive folder name, rather than the page title of the root tab.  They can also be nested into sub-folders.

Rather than have a tab list like

* Reddit
  * Facebook
  * Twitter
* GitHub
  * GitLab
  * BitBucket

The named folders could give a more descriptive hierarchy, like

* Social
  * Reddit
  * Facebook
  * Twitter
* Code Repos
  * GitHub
  * GitLab
  * BitBucket

## Environment

 * Platform (OS): Debian
 * Version of Firefox: 78.11.0esr
 * Version (or revision) of Tree Style Tab: 3.8.4

**Comment by irvinm** [comment]
Options -> Development -> Page for Group Tab

OR

In the URL bar, enter:  ext+treestyletab:Group

You can rename the title after the page is created to anything you want by clicking on the text "Group".

**Comment by piroor** [comment]
@PubliqPhirm As @irvinm mentioned you can open new group tab with the URL `ext+treestyletab:group`. It is recommended that creating a bookmark with the URL.

More useful commands to create such groups are beyond the scope of this project. It should be tracked on TST More Tree Commands https://addons.mozilla.org/firefox/addon/tst-more-tree-commands/ or other helper extensions.

**Comment by PubliqPhirm** [comment]
This solution works just fine for me, especially with More Tree Commands installed.  Thank you.
