### ISSUE TITLE
Missing "Duplicate Tab" as keybinding in TST and TST More Tree Commands extensions

### ISSUE THREAD

**Issue by rieje** [piroor/treestyletab#2959]
Missing "Duplicate Tab" as keybinding option in TST and TST More Tree Commands extensions.

**Comment by piroor** [comment]
It is a feature of Firefox itself, not related tree.

**Comment by piroor** [comment]
Instead of TST you should use Duplicate Tab Shortcut. https://addons.mozilla.org/firefox/addon/duplicate-tab-shortcut/
