### ISSUE TITLE
Photon theme does not work correctly with TST Colored Tabs

### ISSUE THREAD

**Issue by shr1k** [piroor/treestyletab#2962]
## Short description

When I change to the Photon theme in Tree Style Tab Preferences, the colours from the TST Colored Tabs extension only show up in the indent area of tabs, instead of colouring in the whole tab. All other theme options (Proton, Sidebar, High Contrast, No Decoration) colour the tab correctly.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install TST Colored Tabs
 4. Open a website, and a couple of pages under it (x3 for a nice representative sample)
 5. Toggle between Photon and non-Photon themes in TST Preferences under Appearance

## Expected result

The whole tab is coloured for the same domains, in the Photon theme

## Actual result

Only the indent portion in the TST sidebar is coloured

Screenshot of buggy behaviour under Photon:

![image](https://user-images.githubusercontent.com/927606/124751075-22c0b680-df1e-11eb-8391-44830a6f0de4.png)

Screenshot of correct/expected behaviour under Proton:

![image](https://user-images.githubusercontent.com/927606/124751177-3d932b00-df1e-11eb-961c-e67329e445e0.png)

## Environment

 * Platform (OS): Linux, Ubuntu 21.04, KDE Plasma 5.22.3
 * Version of Firefox: 90.0b12 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.8.6 (I started noticing this behaviour with 3.8.5 as well, but only got around to filing this issue now!)

**Comment by piroor** [comment]
TST Colored Tabs needs to be updated for TST 3.8.5 and later. I've created a pull request: https://github.com/MurzNN/TST-Colored-tabs/pull/24

**Comment by shr1k** [comment]
The issue is now fixed by updating to v0.7.1 of TST Colored Tabs -- thanks @piroor !
