### ISSUE TITLE
TST 3.8.6 tabs no longer completely transparent

### ISSUE THREAD

**Issue by chriscjs** [piroor/treestyletab#2963]
## Short description

After automatic update of TST from 3.8.4 to 3.8.6 tabs have a semi-transparent grayish background.  Reverting to 3.8.4 fixed it.  The version of Firefox (89.0.1) did not change and no other profile settings were changed.

**Comment by piroor** [comment]
Here is a hint: https://github.com/piroor/treestyletab/discussions/2960#discussioncomment-972745
And please comment your user styles to the discussion for further advice.

This kind problem need to be resolved with updated user styles instead of updating of TST itself, thus I close this.

**Comment by chriscjs** [comment]
Thanks.  I changed

     .tab {
       height: 16px;
       background: transparent !important;
       font-weight: bold;
     }

to

     tab-item tab-item-substance {
       height: 16px;
       background: transparent !important;
       font-weight: bold;
     }
and it worked.
