### ISSUE TITLE
Active Tab Height is no longer adjusable

### ISSUE THREAD

**Issue by Vindickator** [piroor/treestyletab#2965]
## Short description
Active Tab Height is no longer adjustable by code

## Steps to reproduce
I updated the TST today (10-Jul-21) and using the below snippet would no longer adjust the height of the tab,
the tab height is fixed to 30, anything more than that would just show the background
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#highlight-active-tab

## Expected result
https://imgur.com/a/A3m5kPL
![Expected](https://user-images.githubusercontent.com/87226625/125158793-feb8db80-e190-11eb-945b-bb543bdb7c37.png)

## Actual result
https://imgur.com/a/Gxypt6D
![Now](https://user-images.githubusercontent.com/87226625/125158800-07a9ad00-e191-11eb-982f-57a8b00ffd53.png)

## Environment
 * Platform (OS): Windows 10 
 * Version of Firefox: 89.0.2 
 * Version (or revision) of Tree Style Tab: 3.8.7

**Comment by irvinm** [comment]
```
tab-item.active tab-item-substance {
  height: 39px !important;
}
```

**Comment by Vindickator** [comment]
Thanks @irvinm,
This snippet works.
