### ISSUE TITLE
Slow site load

### ISSUE THREAD

**Issue by Alex-Mirov** [piroor/treestyletab#2966]
Hello

When using addon "Touch VPN" on "Firefox" the sites that i entered in "auto protected websites" 
are loading very slow.

It doesn't matter which country i selected it is the same issue.

I also have this issue on other computer.

**Comment by irvinm** [comment]
@Alex-Mirov just curious but why are you reporting this here?  You should report it to the "Touch VPN" addon.

**Comment by Alex-Mirov** [comment]
It is not the right place to report bug?

**Comment by piroor** [comment]
@Alex-Mirov If the problem strongly depends on Tree Style Tab, this issue tracker is the right place. If the problem strongly depends on Touch VPN, you should report to the provider of Touch VPN. Its website https://touchvpn.net/ looks don't have any issue tracker or user forum, so you may need to send an email directly. See the "Contact Us" link at the bottom of the page.

**Comment by piroor** [comment]
> If the problem strongly depends on Tree Style Tab, this issue tracker is the right place. If the problem strongly depends on Touch VPN, you should report to the provider of Touch VPN.

If you see the slow site load problem with enabled Tree Style Tab and disabled Touch VPN, it looks a problem of TST.
If you see the problem with disabled TST and enabled Touch VPN, it looks a problem of Touch VPN.
If you see the problem only withthe combination of both enabled TST and Touch VPN, it may be a conflict of two extensions - this may be hard to fix.
Which is your case?

**Comment by Alex-Mirov** [comment]
Hello

I'm only using the "Touch VPN" addon for firefox i dont have a "Tree Style Tab" addon installed.

**Comment by piroor** [comment]
OK, this issue should not be tracked at here. This is the issue tracker of Tree Style Tab project, not for other software.

Please report the problem to Touch VPN project. I'm not the author of Touch VPN so it I cannot debug and update it.
