### ISSUE TITLE
When closing a tab, wish TST to not avoid pending tabs in the same tree

### ISSUE THREAD

**Issue by SogaSuga** [piroor/treestyletab#2968]
## Short description
Feature request.
When option "Avoid pending tabs to be activated accidentally on current tab closes or tree collapsing" is enabled, wish to not avoid pending tabs in the same tree.

## Expected result
As said above, when that option is on, I would like TST to not avoid a pending tab if it's in the same tree of the tab I just closed.

For example, now with that option checked, when I close the "10.4L Oil Engine..." tab, I will be redirected to the New Tab, the "ANNOYING ..." tab is avoided because it's currently unloaded.
I would liket to have a more detailed option to not avoid that tab as long as they are in the same tree.
<img width="265" alt="截屏2021-07-15 上午4 27 12" src="https://user-images.githubusercontent.com/66196437/125765110-e12f8dcd-3139-454f-9a28-3a745acaa534.png">

## Environment

 * Platform (OS): MacOS Big Sur 11.4
 * Version of Firefox: 90.0
 * Version (or revision) of Tree Style Tab: 3.8.7

**Comment by piroor** [comment]
Such detailed focus control looks to be beyond the project focus. I think it should be done via a separate helper extension, and it looks to be a good place to move the existing option to.

**Comment by SogaSuga** [comment]
OK I see.

**Comment by irvinm** [comment]
Can we close this item?
