### ISSUE TITLE
External Tab in new window not displayed when using Temporary Containers add-on

### ISSUE THREAD

**Issue by bengb** [piroor/treestyletab#2970]
Referring to Issue #2858

It looks like this problem has come back in the latest versions of TST (currently running 3.8.8).

As before, when new tabs (in a new window) are opened from other apps, the page itself is shown, but the tab is hidden and just the "loading" bar is displayed in the sidebar.

![image](https://user-images.githubusercontent.com/2240252/126429435-0475bfbe-2642-4b96-9e6f-a8f9875e736e.png)

It seems to be related to Temporary Containers again, because when I turn this extension off, the problem disappears.

This has appeared on the recent versions of FIrefox (currently running 90.0.1).

Closing and re-opening the sidebar makes the tabs appear correctly.

(I opened a new issue because the last one was auto-closed when I tried to re-open it.)

_Originally posted by @bengb in https://github.com/piroor/treestyletab/issues/2858#issuecomment-883872367_

**Comment by piroor** [comment]
Sorry for inconvenience. I've introduced a change to the bot to keep reopened tabs open, thus I close this for now.
