### ISSUE TITLE
[Feature request] Option to stop creation of new child tabs if a certain depth has been achieved

### ISSUE THREAD

**Issue by id259** [piroor/treestyletab#2971]
It would be nice to have an option similar to "Indent tabs until *N* levels" that sets the limit beyond which new tabs will be created as a sibling of a current tab and not as a child.

For example, lets say the user set the limit at 2:

```
Site 1
- Site 2 (opened from site 1 as a child)
- - Site 3 (opened from site 2 as a child)              <- limit has been achieved
- - Site 4 (opened from site 3 as a sibling)            <- limit has been achieved
```

**Comment by irvinm** [comment]
Have you played around with "All Configs" -> "maxTreeLevel" parameter?

**Comment by id259** [comment]
> maxTreeLevel

That's just the "Indent tabs until N levels" option.
