### ISSUE TITLE
"Open link in new tab" from Firefox's right-click context menu always opens the new tab as a child of the current tab.

### ISSUE THREAD

**Issue by fourteen-1** [piroor/treestyletab#2972]
## Short description
"Open link in new tab" from Firefox's right-click context menu always opens the new tab as a child of the current tab.

## Steps to reproduce

- On Mozilla Firefox 90.0.2 (64-bit), go on any website that has links inside
- Right-click on any link/UI element that redirects to a link
- Select "Open Link in New Tab" from the context menu
- The new tab ALWAYS is opened as a child of the current tab.

## Expected result
"Open link in new tab" should open new tab as an independent tab.
or at least,
There should be an option in the settings of TST to choose how "Open link in new tab" should open a tab.

## Actual result
"Open link in new tab" ALWAYS opens new tab as a child of the current tab.

## Environment

 * Platform (OS): Windows 10 Pro 21H1
 * Version of Firefox: Mozilla Firefox 90.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.8.8

**Comment by irvinm** [comment]
I believe there are options to handle this, but I see the same behavior as you.  I could not change it from opening as a child.  (I even tried the reload via middle-click to duplicate the tab and it always opened as a child)  I'm sure @piroor will look into this or point us to some other things to do or try.

![image](https://user-images.githubusercontent.com/979729/127209366-cdea5d17-f475-4d2b-97a0-910918e3216c.png)

**Comment by fourteen-1** [comment]
>  (I even tried the reload via middle-click to duplicate the tab and it always opened as a child)

@irvinm There are a few issues with "Duplicate Tabs" as well that I intended to point out. I'll make a separate issue for that.

**Comment by mpela81** [comment]
Even with middle-click on new tab button, it's always created as a child of current tab, the setting does not seem to be applied, 
![image](https://user-images.githubusercontent.com/1140981/127305676-6a7bac15-ebe5-4951-bbc9-bc3f64ec7dd9.png)

**Comment by irvinm** [comment]
@piroor I just wanted to make sure you saw this item.

**Comment by piroor** [comment]
@fourteen-1  Did you see the FAQ topic "I don't need an automatically organized tree, I want to organize trees myself"?: https://github.com/piroor/treestyletab#feature-requests
