### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by ytingone** [piroor/treestyletab#2973]
## Short description
In about:performance, this plugin have about low(0.2) Energy Impact when do nothing, sometimes Medium(2.2) Energy Impact when changing tabs.

## Steps to reproduce
Just open multiple tabs and about:performance.

## Expected result
When not changing tabs, the Energy Impact should be zero(-).

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 78.12(esr)
 * Version (or revision) of Tree Style Tab: 3.8.8

**Comment by piroor** [comment]
I don't know how Firefox calculates the energy impact, but ~Firefox~ TST does some tasks periodically to improve its stability.

* Mechanism to check living status of sidebar UIs. TST sends messages between the background process and sidebar UI pages periodically, and TST tries to reload the sidebar if heartbeat message is stopped.
* Mechanism to check tabs sent from other devices. Firefox doesn't provide ability to send tabs via Sync from addons, so we need to implement "sync" behavior based on a periodical timer.
* Mechanism to check changing of the visibility of the bookmarks toolbar for "about:newtab". Firefox changes visibility of the toolbar automatically and I hope to reduce visual gap when it suddenly shown without the will of the user.

So I think TST cannot make the energy impact zero.

**Comment by ytingone** [comment]
Alright, but could we have configurations for this to minimize the energy impact?

**Comment by piroor** [comment]
After reading codes about sync feature, I remembered that a timer for the feature is processed only one time per a day. Thus it looks won't increase energy impact.

You can reduce energy impact of timers for other two feaetures. TST Options => Development => All Configs => set large values for `heartbeatInterval`, `connectionTimeoutDelay` and `suppressGapFromShownOrHiddenToolbarInterval` in milliseconds, like `86400000` (one day).
