### ISSUE TITLE
advice?

### ISSUE THREAD

**Issue by opqriu** [piroor/treestyletab#2974]
Hi.

I love using the [TST mouse wheel](https://addons.mozilla.org/firefox/addon/tree-style-tab-mouse-wheel/) when my browser has few tabs.
Of course I can't use it when i have a lot of tabs in my browser.
But the addon doesn't support on/off hotkey, so I'm looking for another way.

~$ sed -i 's/about:config:options:true/about:config:option:false/g' ~/.mozilla/firefox/default-release/prefs.js

As above, I can change the options of about:config in linux terminal in real time.

Similarly, I would like to change the enable/disable of the TST mouse wheel addon in the terminal.

Which part of which file? I have no idea. can someone give me some advice?

**Comment by piroor** [comment]
Sorry I'm not familiar to control addons from outside of Firefox safely and dynamically. Firefox provides a mechanism to control itself from commands like `web-ext`, so you may find out effective solution at https://github.com/mozilla/web-ext .

By the way I didn't provide ability to implement such an option on helper addon side, so I've introduced two changes: `overflow` property for `scrolled` notification and new notifications `tabbar-overflow`/`tabbar-underflow`. It should help helper addons to change their behavior based on overflow state of the tab bar.

https://github.com/piroor/treestyletab/wiki/API-for-other-addons#messages-notified-by-mouse-wheel-rotation
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#when-the-tab-bar-becomes-scrollable-or-unscrollable

**Comment by piroor** [comment]
Could you post a feature request to the addon's project, for an option based on changes I've done?: https://github.com/joshuacant/tst-wheel_and_double/issues

**Comment by irvinm** [comment]
@piroor I think this could be closed.

**Comment by piroor** [comment]
@irvinm Thanks, I forgot to mark this as expire-able by the bot.
