### ISSUE TITLE
Inconsistent placement of duplicating tabs

### ISSUE THREAD

**Issue by BrontoRed** [piroor/treestyletab#2976]
## Short description
Duplicating tab from native Firefox context menu acts according to option, defined for Non-blank new tabs.
But duplicating tab with any action from [Foxy Gestures](https://addons.mozilla.org/ru/firefox/addon/foxy-gestures/) add-on or middle-clicking on the "refresh" button next to the url address bar opens "a child of a current tab".

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set TST duplicate tab setting to any setting
 4. Install [Foxy Gestures](https://addons.mozilla.org/ru/firefox/addon/foxy-gestures/) add-on
 5. Duplicate tab with native Firefox context menu
 6. Duplicate tab with default gesture from Foxy Gestures
 7. Duplicate tab with middle-clicking on the "refresh" button

## Expected result
Steps 5-7 above should respect the TST duplicate tabs settings.

## Actual result
Only native Firefox context menu action duplicates tabs according to settings.
Gesture from Foxy Gestures and middle-clicking on the "refresh" button opens "a child of a current tab".

## Environment
 * Platform (OS): Windows 10 Pro (64-bit), Version 21H1, Build 19043.1110
 * Version of Firefox: 90.0.2 Release (64-bit)
 * Version (or revision) of Tree Style Tab: 3.8.8

**Comment by piroor** [comment]
This looks to be a duplicated of the issue #2845 and it depends on Firefox's bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1701900
As a workaround, TST options => Development => Delay to detect duplicated tabs => set suitable delay. On my environment `200` works as expected.

**Comment by piroor** [comment]
One note: there is some side effects, increased delay can prevent restoration of the tree structure on Firefox startup.

**Comment by BrontoRed** [comment]
Thanks!
Workaround solves the problem.

**Comment by piroor** [comment]
I've introduced a change 1f22694 to reduce the side effect I commented at https://github.com/piroor/treestyletab/issues/2976#issuecomment-894768600
