### ISSUE TITLE
No scrollbar when not enough tabs are loaded with Tab Unloader for TST

### ISSUE THREAD

**Issue by Tracerneo** [piroor/treestyletab#2977]
## Short description

With many tabs, there should be a scrollbar in the side panel.
When there are no at least two tabs loaded that would be far enough from each other to require scrolling, scrollbar is missing and unloaded tabs above and/or below tabs which are currently seen can't be accessed, as the sidebar area with tabs tree can't be scrolled.

How it can be reproduced:
Have TST and Tab Unloader for TST
Open many tabs, enough to have more tabs than height of the window (window can be resized to be smaller), requiring scrollbar
Unload tabs, having only one at the top loaded
The scrollbar disappears, along with the plus button at the bottom to open new tabs, as if the sidebar had enough space to render without scrollbars

The same issue can be triggered by resizing the window while having only some tabs loaded, e.g. one at the top, and one in the middle.
As long as both loaded tabs are in view without needing a scrollbar, the unloaded tabs will render off-screen and scrolling won't be possible. When the window is resized to be smaller, where it would require a scrollbar to reach the topmost and bottommost loaded tab, the scrollbar will appear, and the unloaded tabs below and above can be accessed with scrolling.

Pinned tabs seem to be ignored.

![issue](https://user-images.githubusercontent.com/660285/128435161-007f54e8-f999-48cf-ba93-d1a04760cea0.png) 
Here the top tab is loaded and out of view, the bottom tab is unloaded and out of view. Neither can be scrolled into view.
![no issue](https://user-images.githubusercontent.com/660285/128435409-95ebf2d4-b0ee-40cc-91f7-e3c397855ae6.png)
With more tabs loaded the scrollbar and plus button to open new tabs appears.

The issue appeared after an update to newer version.

## Environment

 * Platform (OS): Gentoo Linux
 * Version of Firefox: 84.0.2
 * Version (or revision) of Tree Style Tab: 3.8.8

**Comment by piroor** [comment]
> Open many tabs, enough to have more tabs than height of the window (window can be resized to be smaller), requiring scrollbar
> Unload tabs, having only one at the top loaded
> The scrollbar disappears, along with the plus button at the bottom to open new tabs, as if the sidebar had enough space to render without scrollbars

I couldn't reproduce the problem with these steps on Firefox 90 on Windows 10, so there looks to be something more requirements to reproduce. There are two differences: platform (Windows 10 vs Gentoo Linux) and Firefox version (90 vs 84). Could you try with Firefox 90?

**Comment by cdavie-weconnect** [comment]
I have the same problem. I tried unpinning all my pinned tabs & deleting all my custom CSS, but that made no difference.

- Platform (OS): Mac OS 11.3 (Big Sur)
- Version of Firefox: 92.0b6 (Developer Edition)
- Version of Tree Style Tab: 3.8.11

**Workaround:** What _does_ fix it, strangely, is opening the "Add-ons Manager" (Cmd-Shift-A)! If I leave it open _and_ no tabs pinned, the TST sidebar scrolls like normal. As soon as I close it or pin a tab, the sidebar is no longer able to scroll.

Very strange! Hopefully that helps narrow down the issue.

**Comment by piroor** [comment]
I've tried with a macOS environment but the problem still don't reproduce. Could you cooperate with debug logs?

* [Here is an introduction to collect debug logs of TST](https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-collect-debug-logs-of-tst)
* TST options => Development => check "Debug mode"
* TST options => Development => Detailed logging => Logs from sidebar modules => check only "sidebar/sidebar" (and uncheck all others)

Then you can collect logs about detection of overflow state. Here are examples of expected logs on my environment:

Logs when the sidebar becomes scrollable with too many visible tabs
![image](https://user-images.githubusercontent.com/70062/130648152-b157e152-8854-4ace-a3c7-2ed62e00c2f2.png)

Logs when the sidebar becomes unscrollable with less visible tabs
![image](https://user-images.githubusercontent.com/70062/130648092-c90e2082-8c51-4278-9435-d9898076f2db.png)

**Comment by Tracerneo** [comment]
It appears that `allTabsHeight` doesn't take unloaded tabs into account, it calculates the distance from the first loaded tab, to the last loaded tab.

Below is the debug log.

Many tabs open, most unloaded, scrollbar present, with the layout looking more or less like this:
```
3 pinned tabs unloaded
1 pinned tab loaded
first tab loaded
some more tabs loaded in the middle
two tabs loaded at the end
```
`allTabsHeight: 1215.3333740234375` from first to last tab(?)
Unloaded last tab, making the end of the list be `…, loaded, unloaded`
`allTabsHeight: 1185.6666259765625` 30 less from one unloaded tab
Unloaded another tab at the end, making the end of the list being a lot of unloaded tabs
`allTabsHeight: 533` scrollbar disappears ("underflow")

Unloading tabs is logged as `updateTabbarLayout reasons: tab close`

```
tst<Sidebar-1>: 13:51:00.107 sidebar/sidebar:                      updateTabbarLayout reasons: collapse,expand,animation end,tab open,tab close common.js:655:13
tst<Sidebar-1>: 13:51:00.110 sidebar/sidebar:                      height:  
Object { container: 750, allTabsHeight: 1215.3333740234375, newTabButtonSize: 18.666671752929688 }
common.js:655:13
tst<Sidebar-19>: 13:51:02.691 sidebar/sidebar:      mImportedTabs (19): onBackgroundIsReady  tab-mousedown undefined common.js:655:13
tst<Sidebar-21>: 13:51:02.692 sidebar/sidebar:      mImportedTabs (21): onBackgroundIsReady  tab-mousedown undefined common.js:655:13
tst<Sidebar-23>: 13:51:02.694 sidebar/sidebar:      mImportedTabs (23): onBackgroundIsReady  tab-mousedown undefined common.js:655:13
tst<Sidebar-25>: 13:51:02.695 sidebar/sidebar:      mImportedTabs (25): onBackgroundIsReady  tab-mousedown undefined common.js:655:13
tst<Sidebar-27>: 13:51:02.697 sidebar/sidebar:      mImportedTabs (27): onBackgroundIsReady  tab-mousedown undefined common.js:655:13
tst<Sidebar-29>: 13:51:02.699 sidebar/sidebar:      mImportedTabs (29): onBackgroundIsReady  tab-mousedown undefined common.js:655:13
tst<Sidebar-267>: 13:51:02.700 sidebar/sidebar:      mImportedTabs (267): onBackgroundIsReady  tab-mousedown undefined common.js:655:13
"issue start"
"issue start"
tst<Sidebar-1>: 13:51:18.229 sidebar/sidebar:      mImportedTabs (1): onBackgroundIsReady  treestyletab:contextMenu-updated undefined common.js:655:13
tst<Sidebar-19>: 13:51:18.231 sidebar/sidebar:      mImportedTabs (19): onBackgroundIsReady  treestyletab:contextMenu-updated undefined common.js:655:13
tst<Sidebar-21>: 13:51:18.233 sidebar/sidebar:      mImportedTabs (21): onBackgroundIsReady  treestyletab:contextMenu-updated undefined common.js:655:13
tst<Sidebar-23>: 13:51:18.234 sidebar/sidebar:      mImportedTabs (23): onBackgroundIsReady  treestyletab:contextMenu-updated undefined common.js:655:13
tst<Sidebar-25>: 13:51:18.235 sidebar/sidebar:      mImportedTabs (25): onBackgroundIsReady  treestyletab:contextMenu-updated undefined common.js:655:13
tst<Sidebar-27>: 13:51:18.236 sidebar/sidebar:      mImportedTabs (27): onBackgroundIsReady  treestyletab:contextMenu-updated undefined common.js:655:13
tst<Sidebar-29>: 13:51:18.237 sidebar/sidebar:      mImportedTabs (29): onBackgroundIsReady  treestyletab:contextMenu-updated undefined common.js:655:13
tst<Sidebar-267>: 13:51:18.238 sidebar/sidebar:      mImportedTabs (267): onBackgroundIsReady  treestyletab:contextMenu-updated undefined common.js:655:13
tst<Sidebar-1>: 13:51:21.793 sidebar/sidebar:             updateTabbarLayout reasons: tab close common.js:655:13
tst<Sidebar-1>: 13:51:21.794 sidebar/sidebar:             height:  
Object { container: 750, allTabsHeight: 1185.6666259765625, newTabButtonSize: 18.666671752929688 }
common.js:655:13
tst<Sidebar-1>: 13:51:28.385 sidebar/sidebar:      mImportedTabs (1): onBackgroundIsReady  treestyletab:contextMenu-updated undefined common.js:655:13
tst<Sidebar-19>: 13:51:28.388 sidebar/sidebar:      mImportedTabs (19): onBackgroundIsReady  treestyletab:contextMenu-updated undefined common.js:655:13
tst<Sidebar-21>: 13:51:28.389 sidebar/sidebar:      mImportedTabs (21): onBackgroundIsReady  treestyletab:contextMenu-updated undefined common.js:655:13
tst<Sidebar-23>: 13:51:28.390 sidebar/sidebar:      mImportedTabs (23): onBackgroundIsReady  treestyletab:contextMenu-updated undefined common.js:655:13
tst<Sidebar-25>: 13:51:28.392 sidebar/sidebar:      mImportedTabs (25): onBackgroundIsReady  treestyletab:contextMenu-updated undefined common.js:655:13
tst<Sidebar-27>: 13:51:28.393 sidebar/sidebar:      mImportedTabs (27): onBackgroundIsReady  treestyletab:contextMenu-updated undefined common.js:655:13
tst<Sidebar-29>: 13:51:28.394 sidebar/sidebar:      mImportedTabs (29): onBackgroundIsReady  treestyletab:contextMenu-updated undefined common.js:655:13
tst<Sidebar-267>: 13:51:28.395 sidebar/sidebar:      mImportedTabs (267): onBackgroundIsReady  treestyletab:contextMenu-updated undefined common.js:655:13
tst<Sidebar-1>: 13:51:31.271 sidebar/sidebar:             updateTabbarLayout reasons: tab close common.js:655:13
tst<Sidebar-1>: 13:51:31.271 sidebar/sidebar:             height:  
Object { container: 750, allTabsHeight: 533, newTabButtonSize: 18.666671752929688 }
common.js:655:13
tst<Sidebar-1>: 13:51:31.273 sidebar/sidebar:             underflow common.js:655:13
```

With the scrollbar missing, unloading some more tabs from the middle reduces `allTabsHeight: 414.33331298828125` further down.
```
tst<Sidebar-267>: 13:54:02.993 sidebar/sidebar:      mImportedTabs (267): onBackgroundIsReady  tab-mousedown undefined common.js:655:13
tst<Sidebar-1>: 13:54:03.315 sidebar/sidebar:                  updateTabbarLayout reasons: expand common.js:655:13
tst<Sidebar-1>: 13:54:03.317 sidebar/sidebar:                  height:  
Object { container: 750, allTabsHeight: 533, newTabButtonSize: 18.666671752929688 }
common.js:655:13
tst<Sidebar-1>: 13:54:03.317 sidebar/sidebar:                  underflow common.js:655:13
tst<Sidebar-1>: 13:54:03.509 sidebar/sidebar:                     updateTabbarLayout reasons: collapse,animation end common.js:655:13
tst<Sidebar-1>: 13:54:03.530 sidebar/sidebar:                     height:  
Object { container: 750.0000152587891, allTabsHeight: 533, newTabButtonSize: 18.666671752929688 }
common.js:655:13
tst<Sidebar-19>: 13:54:04.890 sidebar/sidebar:      mImportedTabs (19): onBackgroundIsReady  tab-mousedown undefined
…
tst<Sidebar-267>: 13:54:05.090 sidebar/sidebar:      mImportedTabs (267): onBackgroundIsReady  treestyletab:contextMenu-updated undefined common.js:655:13
tst<Sidebar-1>: 13:54:07.264 sidebar/sidebar:             updateTabbarLayout reasons: tab close common.js:655:13
tst<Sidebar-1>: 13:54:07.266 sidebar/sidebar:             height:  
Object { container: 750.0000152587891, allTabsHeight: 414.33331298828125, newTabButtonSize: 18.666671752929688 }
common.js:655:13
tst<Sidebar-1>: 13:54:07.298 sidebar/sidebar:             updateTabbarLayout reasons: tab close common.js:655:13
tst<Sidebar-1>: 13:54:07.299 sidebar/sidebar:             height:  
Object { container: 750.0000152587891, allTabsHeight: 414.33331298828125, newTabButtonSize: 18.666671752929688 }
common.js:655:13
tst<Sidebar-19>: 13:54:08.462 sidebar/sidebar:      mImportedTabs (19): onBackgroundIsReady  tab-mousedown undefined common.js:655:13
```

I have tested it also in a new window with only 5 tabs.
```
1st tab - unloading decreases allTabsHeight
2nd tab - loaded
3rd tab - unloading does nothing
4th tab - loaded
5th tab - unloading decreases allTabsHeight
```
After having 3 tabs unloaded, the distance of `allTabsHeight` was from 2nd to 4th tab.

**Comment by piroor** [comment]
OK, I've understood what happens on your environment. There were some missing steps required to reproduce the problem:

1. Instal "Tab Unloader for Tree Style Tab".
2. Go to the options page of Tab Unloader for TST and configure as:
   * "Tab Hiding" => "Hide unloaded tabs with the tab hiding API..." => turn it on.
   * "Tab Hiding" => "Show hidden tabs in Tree Style Tab's sidebar." => turn it on.
   * "Optional Permissions" => "tabHide" => "Request" => grant the permission.
3. Multiselect top or bottom unpinned tabs.

Currently TST is not designed for a case with "hidden via WebExtensions API but visible by CSS hack" tabs...

**Comment by Tracerneo** [comment]
I believe the issue would be here [sidebar.js#L682-L697](https://github.com/piroor/treestyletab/blob/3.8.11/webextensions/sidebar/sidebar.js#L682-L697)

The most likely case is that `Tab.getFirstNormalTab(mTargetWindow)` nor `Tab.getLastVisibleTab(mTargetWindow)` return unloaded and hidden tabs (the tabs are hidden in the top bar, but not in TST sidebar tree).

**Comment by piroor** [comment]
The commit a80625b should fix this.

**Comment by Tracerneo** [comment]
The latest version resolves the issue.
Thank you!
