### ISSUE TITLE
Auto-group tabs from external sources

### ISSUE THREAD

**Issue by himie** [piroor/treestyletab#2978]
I open a lot of tabs from outside Firefox and they tend to clutter up my tree and been looking for an option to group them all together automatically.

Recently found out about the "auto-grouping" feature from pinned tabs or bookmarks and would love to see this done for tabs opened outside Firefox as well. Have the option to create an auto-group from externally opened tabs that they all go to.

**Comment by piroor** [comment]
TST has the option but disabled by default. You can activate it via: TST Options => turn on "Unlock Expert Options" => Next Tabs Behavior => Auto-grouping of tabs => turn on "Auto-group tabs opened at a time from non-bookmark triggers also".

**Comment by himie** [comment]
That doesn't seem to be working for me. Every time I click on a link outside Firefox it still opens independently without a group.

From reading the description it sounds like this option is time-based? What I'm talking about is the option to group any tabs that are opened from outside Firefox, but not necessarily at the same time. Instead more of a global group of "all external tabs go in this group"

So if I'm in a chat program and I open a link from there, the tab goes into a group of other tabs that I've opened from outside Firefox. Be it today or tomorrow or anytime all links from outside Firefox would go there.

**Comment by piroor** [comment]
Hmm, then it looks beyond the scope of this project. TST's auto-grouping feature was originally designed as a virtual tree, to cover some special cases not covered by regular tree management.

* Basically TST is designed to attach new tabs opened from links to the opener tab, and child tabs need to be placed next to the parent. However, Firefox does not allow us to put unpinned tabs between pinned tabs. So TST opens a dummy tab for grouping as an alias of the opener pinned tab.
* Tabs opened from a bookmark folder at a time need to be organized as a tree, but there is no tab good to become their parent. So TST opens a dummy tab just as the parent of those opened tabs.
  * Initially TST didn't have ability to detect "tabs opened from a bookmark folder", thus I implemented the auto-grouping feature based on a simple time span. After I implemented bookmarked tabs detection, I added the option to disable general cases (I described at my first comment) and disabled it by default.
* One more case is: a group tab replacing a closed parent tab. It is opened just to keep the tree structure as-is after a parent tab is closed.

On the other hand, general auto-grouping for tabs opened by external applications looks not match to this strategy. If TST can know the opener external application of each tab, I agree to implement auto-grouping for each opener application. However, it is impossible for now. Thus we need to treat tabs from different external application just in a "from external" context. It looks not natural for me grouping of tabs generally opened from external multiple applications.

----

Anyway, auto-grouping based on various conditions looks good to be provided by a separate helper add-on designed for the purpose. On Windows and Linux, new tabs opened while no Firefox browser windows have focus mean "opened by external application", it does not depend on TST's internal information.

**Comment by piroor** [comment]
I've created a new project for the feature:
https://addons.mozilla.org/firefox/addon/tst-auto-group-tabs/
https://github.com/piroor/tst-auto-group-tabs

**Comment by piroor** [comment]
This won't fixed on TST side, so I close this.

**Comment by piroor** [comment]
And I'm finding successor developers of the "TST Auto Group Tabs" project. I'm ready to transfer the ownership of the project to successors.
I generally use TST without this kind features, so sorry but I have less motivation to develop and maintain the project.
I believe that it should be owned by someone who really want to use it (including you).

**Comment by irvinm** [comment]
@piroor, it looks like you are basically using the following logic to determine if the new tab is considered external or not:

https://github.com/piroor/tst-auto-group-tabs/blob/0f34c27c6b5183ea68fec3d599f5c34b5c612dc2/background/background.js#L196-L205

```
browser.tabs.onCreated.addListener(async tab => {
  try {
    trackTab(tab);
    if (mLastFocusedWindowId == browser.windows.WINDOW_ID_NONE)
      await handleNewTab(tab, 'byExternalApps');
  }
  catch(error) {
    console.log(error);
  }
});
```

Can you think of any information or method to identify if a tab has been created via Firefox Sync?  (I'm thinking this might be a workaround to https://github.com/piroor/treestyletab/issues/2419.)

**Comment by piroor** [comment]
@irvinm Hmm... sorry I cannot imagine how to detect a new tab is opened by Firefox Sync or don't. There looks to be no hint.
