### ISSUE TITLE
Subpanel resizing behaves in unexpected ways

### ISSUE THREAD

**Issue by SebiderSushi** [piroor/treestyletab#2979]
## Short description
When resizing the subpanel, it is only possible to go up to about 2/3rds of the sidebar height. Grabbing the resize action with the mouse and pulling up or using the keyboard shortcut to increase height don't cause any visible changes at this point. They seem to increase the internal value of the subpanel height without any useful limitation.

## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install official TST Bookmark Subpanel
 4. Drag the top of the subpanel to resize.
 5. When hitting the maximum height, continue dragging the resize bar until the mouse cursor hits the top of the screen
 6. Let go and move the mouse cursor back to the top bar of the subpanel
 7. Repeat dragging the subpanel top bar upwards a couple of times

## Expected result
I expected to be able to increase the height of the subpanel to at least 90% of the sidebar height. I expect the internal value representing the desired height to be limited to the visual limit.

## Actual result
The internal value representing the desired subpanel height seems to get incremented with every drag upwards or when pressing the keyboard shortcut to increase the subpanel height. It does not matter whether the subpanel on screen has already reached the visual limit. The internal value gets incremented while the visual representation of the subpanel no longer changes.

When going back to decrease the height of the subpanel, either by dragging or with the keyboard shortcut, it is necessary to undo all of the increases in height. After dragging 5 times past the maximum height it is necessary to drag 5 times downward until the subpanel actually starts to decrease in height. After keeping the keyboard shortcut for increasing the height pressed for 5 seconds after reaching the top limit, it is necessary to kepp the keyboard shortcut for decreasing the height pressed for 5 seconds as well before the subpanel starts to decrease in height.

## Environment

 * Platform (OS): Manjaro Linux
 * Version of Firefox: 90.0.2 (Manjaro - 1.0)
 * Version (or revision) of Tree Style Tab: 3.8.8

**Comment by piroor** [comment]
The maximum size of the subpanel area is currently fixed, and I've introduced a change 12b100b to make it configurable. At the next release you'll be able to change the value via TST options => Development => All Configs => `maxSubPanelSizeRatio`, it is a float number within 0-1.
