### ISSUE TITLE
Compatiblity with Tab Mix Plus: New Tabs silently overlay existing tabs

### ISSUE THREAD

**Issue by radi0active** [piroor/treestyletab#298]
Starting with Firefox 11 (and also on Firefox 12) when Tab Mix Plus is enabled, I see that  when opening new tabs, the rendered screen opens correctly, but the tab pane does not reflect the new tab.  The observed behavior is that the pre-existing tab becomes un-highligted  and the new tab does not show up at all. This behavior appears to be window dependent; I.E.: In one window it will work correctly by in the other 5 or 6 windows it exhibits the behavior described above. 

Many of those I know who previously used this valuable Add-On (Thank you!) have removed it altogether because of this bug.  Since it has been happening for months I am surprised to not see this already opened and am opening it here.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
