### ISSUE TITLE
privacy.resistFingerprinting breaks possibility to detach tabs to new windows via dropping outside of sidebar

### ISSUE THREAD

**Issue by rojnwa** [piroor/treestyletab#2980]
## Short description
As soon as this option is enabled in about:config, detaching tabs does no longer work.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set `privacy.resistFingerprinting` to true.
 4. Try to detach tab by drag and drop tab outside of sidebar.

## Expected result
The tab should detach from the current window and create a new window.

## Actual result
Nothing happens.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: Release 90.0.2 - Also tested with fresh/clean LibreWolf 90.0.2
 * Version (or revision) of Tree Style Tab: 3.8.8

**Comment by piroor** [comment]
This looks to be an unavoidable restriction. When the pref is set to `true`, Firefox disallows TST to access detailed window coordinates (`mozInnerScreenX` and `mozInnerScreenY`) so TST cannot detect the dropped coordinates is enough far from the sidebar.

**Comment by piroor** [comment]
After more research, not only detailed coordinates but regular coordinates `screenX` and `screenY` are unavailable with `privacy.resistFingerprinting`=`true`. Then it is completely impossible to get actual coordinates of the sidebar area.

**Comment by rojnwa** [comment]
I assume that TST can access the coordinates while the pointer is still inside the sidebar (otherwise moving tabs would not work).

According to this, wouldn't it be sufficient to check the rightmost/leftmost pixel of the sidebar and as soon as the pointer hits this pixel once and the tab is dropped, a new window is created?

This COULD possibly lead to undesirable behavior if someone drops a tab on just that particular pixel, but I would argue that this won't be a problem at all.

**Comment by piroor** [comment]
> According to this, wouldn't it be sufficient to check the rightmost/leftmost pixel of the sidebar and as soon as the pointer hits this pixel once and the tab is dropped, a new window is created?

Sadly your idea does not effective because event's `screenX` and `screenY` returns coordinates same to `clientX` and `clientY` with `privacy.resistFingerprinting`=`true`, but finally I've found another method to determine the cursor is outside or inside the sidebar. Thus I've introduced a change 55e9923 to deactivate the behavior "ignore tab drop near the sidebar for safety". With disabled the option you'll be able to detach dragged tab from the window with `privacy.resistFingerprinting`=`true`,

**Comment by rojnwa** [comment]
Works like a charm, thanks for your effort.
