### ISSUE TITLE
Tab Session Manager doesn't work well with TST, any alternative that might work better?

### ISSUE THREAD

**Issue by mzso** [piroor/treestyletab#2983]
Hi!

I've been using TSM, but always fails to restore the tree structure, and even the order of the tabs.
Perplexingly also the favicons are missing. So It sucks If one saves a window with a bunch of tabs, and only gets an unorganized and shuffled bulk of tabs. Some very few tabs might be restored as a branch but it's like two out of 50.

Is there any other session manager out there that support TST, that might work better?

**Comment by irvinm** [comment]
The favicons are missing as that is a Firefox limitation.  (Tabs that are created as discarded will not load their favicons until they are loaded)  I personally just wrote another extension to load a few tabs at a time then immediately discarded them again just to load their favicons.  Thankfully, I don't have to load sessions via TSM very often.

As for the tree structure, have you tried different delay values?  Maybe try a pretty large value to see if that works and if it does, lower it until you are satisfied.

**Comment by mzso** [comment]
[**@irvinm**](https://github.com/irvinm) commented on [2021. aug. 16. 13:25 CEST](https://github.com/piroor/treestyletab/issues/2983#issuecomment-899434670 "2021-08-16T11:25:32Z - Replied by Github Reply Comments"):
> As for the tree structure, have you tried different delay values? Maybe try a pretty large value to see if that works and if it does, lower it until you are satisfied.

Yes. It's at 650ms. I can see them being restored one-by-one... Without the proper tree structure of course.

But apparently it's restored the same way with multiple tries. So I guess the tree structure might not have been saved properly.

**Comment by piroor** [comment]
@mzso Did you saw the FAQ topic ["Better compatibility with session manager extensions, or add high-power session management feature"](https://github.com/piroor/treestyletab/blob/trunk/README.md#user-content-feature-requests-better-compatibility-with-session-manager-extensions-or-add-high-power-session-management-feature)?

**Comment by mzso** [comment]
[**@piroor**](https://github.com/piroor) commented on [2021. aug. 16. 15:45 CEST](https://github.com/piroor/treestyletab/issues/2983#issuecomment-899523724 "2021-08-16T13:45:26Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso) Did you saw the FAQ topic ["Better compatibility with session manager extensions, or add high-power session management feature"](https://github.com/piroor/treestyletab/blob/trunk/README.md#user-content-feature-requests-better-compatibility-with-session-manager-extensions-or-add-high-power-session-management-feature)?

Yes. But I was interested in actual alternatives for TSM if there are any.

**Comment by piroor** [comment]
Sorry but I don't know any other alternatives. If you need any alternatives with better stability, You may need to create it with these TST APIs:

* https://github.com/piroor/treestyletab/wiki/API-for-other-addons#take-a-tree-structure-snapshot-of-tabs
* https://github.com/piroor/treestyletab/wiki/API-for-other-addons#apply-a-tree-structure-to-tabs
* https://github.com/piroor/treestyletab/wiki/API-for-other-addons#open-new-tab-bypassing-tsts-tab-control-behavior

**Comment by irvinm** [comment]
> 
> 
> [**@irvinm**](https://github.com/irvinm) commented on [2021. aug. 16. 13:25 CEST](https://github.com/piroor/treestyletab/issues/2983#issuecomment-899434670):
> 
> > As for the tree structure, have you tried different delay values? Maybe try a pretty large value to see if that works and if it does, lower it until you are satisfied.
> 
> Yes. It's at 650ms. I can see them being restored one-by-one... Without the proper tree structure of course.
> 
> But apparently it's restored the same way with multiple tries. So I guess the tree structure might not have been saved properly.

@mzso, If you have the saved *.JSON file of a session you are trying to restore, you can simply edit the file in a text editor and look at the properties of each tab and look for the "openerTabId" property. If it is set properly you will see the tab number of the parent in that value.  [This would help verify if the session was at least stored properly]

If you just have the sessions in the browser, you can go into TSM options and export the sessions to inspect the values.

**Comment by OwenAR** [comment]
I've been using [Session Boss](https://addons.mozilla.org/en-US/firefox/addon/session-boss/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) for ages,
and as far as I've noticed, it always restores TST's tree structure and order perfectly.
(
I can't remember using any other session managers,
so I can't speak as someone with direct experience comparing.
)

It does *not* restore favicons
(
I've actually been vaguely thinking about asking the developer about that for a while,
but I just learned from above in this thread that that's apparently a firefox limitation anyway?
)

(
Also cuz of firefox limitations, Session Boss can't restore special URLs,
but it has an okay hacky workaround:
eg, a newtab is restored with a hacky url like:
`moz-extension://d3241f86-be33-4a8c-981a-612c1e3f3610/error.html?url=about%3Ablank&error=Cannot%20create%20a%20discarded%20new%20tab%20or%20%22about%22%20urls.&title=about%3Ablank`
with the content:
```
Session Boss
Browser content security policy prevents opening special url from extensions.
Error message: Cannot create a discarded new tab or "about" urls.
Copy and paste the url into the address bar to open it.
[about:blank]
```

And then all you have to do to restore it is:
- copy (text is already highlighted)
- ctrl-L (focus address bar)
- paste
- enter
)

If you try it, please do tell me if it works... and if you find anything *better*, please do tell me too. xD

**Comment by mzso** [comment]
@OwenAR 
> and as far as I've noticed, it always restores TST's tree structure and order perfectly.

My experience is that it virtually never does. Just saved a window and it was restored wrongfully. Branches appear completely in different positions and everything ended up as a sub branch of the first tab, which is also wrong.
Just for completeness sake I did it like this. Save only this window (I have multiple)> right click on the created session > open in new window.

**Comment by silverwings15** [comment]
seems you have to disable firefox's native 'restore previous tabs and windows on startup' because otherwise Session Boss opens one or even two extra windows of identical tabs. my experience with restored tree structure also mirrors that of mzso's, tabs are rearranged and moved all over the place

**Comment by OwenAR** [comment]
@mzso That's weird, it really does seem to be working perfectly for me,
with all tabs always loading back in the correct tree structure and order as expected.

And I just tested it a bunch
(
I was kinda expecting to rely on it working in the future,
so I got worried hearing it might actually be so broken...
)

I took a bunch of screenshots as I was doing it
(I've been meaning to work on streamlining my tools for that anyway),
so...

If you want to check if your setup looks the same,
here are all the screenshots:
https://www.dropbox.com/sh/j5r6h3ew8leamqy/AAAWj77mn39MVHeCbYiTQGIGa/screenshots?dl=0&lst=&subfolder_nav_tracking=1

To explain/group them a little:

> Checking preferences:
> > - 1.1 finding preferences
> > - 1.2 looking at preferences

> Saving the session:
> > - 2.1 "Capture the tabs of the current window as a new sesison[sic]"
> > - 3.1 "(click to edit)"
> > - 3.2 clicking "Save" [NOT hitting enter]
> > > (if you hit enter, it confusingly autorenames it back or something)

> Exporting the session:
> > - 4.1 "Export Session"
> > - 4.2 (saving json file)

> Deleting the original so can test importing:
> > - 5 "Delete Session"

> Importing:
> > - 6.1 "Import..."
> > - 6.2 "Browse..." for file to import
> > - 6.3 (opening json file)
> > - 6.4 "Merging Import All"

> Restoring first way (ie, whole session, in this case only one window):
> > - 7 "Restore session with new windows, keeping existing windows."

> Restoring second way (ie, only the one window by itself):
> > - 8 "Restore the window as a new browser window"

> Either way you restore, loading acts the same:
> It "wobbles" a bit as it fills up from the top down, and then finally the extraneous "new tab" at the beginning that wasn't part of the session disappears
> [(the little "konsole bell" notification in a couple of them was just my screenshotting script interfering with itself)]:
> > - L1 wobble 1
> > - L1 wobble 2
> > - L1 wobble 3
> > - L1 wobble 4
> > - L1 wobble 5
> > - L1 wobble 6
> > - L1 wobble 7
> > - L1 wobble 8 (flashing blue at the bottom)

> It takes... I guess maybe 20 seconds to finish loading (on my shitty old laptop):
> > - L2.1 fully loaded (top)
> > - L2.2 fully loaded (scrolled to bottom)

[ EDIT :... also just realized I forgot to note ["Tree Style" ("Toggle showing tree style tabs") should be checked](https://www.dropbox.com/sh/j5r6h3ew8leamqy/AAAWj77mn39MVHeCbYiTQGIGa/screenshots?dl=0&lst=&preview=x+%22Tree+Style%22+(%22Toggle+showing+tree+style+tabs%22).png&subfolder_nav_tracking=1).]

I created that session manually, doing a bunch of irregular stuff along the way
(randomly reordering and "child-ing"/"parent-ing" individual tabs, groups of tabs, and whole trees, closing and reopening tabs, etc etc)
and everything still reloads with exactly the same URLs in exactly the same order with exactly the same indentation.
[(Except for the special newtabs being converted into the "moz-extension" thing, of course.)]

I saved sessions on one computer and reloaded them on another
(hence why I showed testing the export/import stuff ; Sessions reload fine on a single computer without that too.)

(I did a lot more cycles of reopening/monkeying-with/saving/closing, of course, and yeah, all the changes kept loading correctly.)

But to keep things simple,
if you import this session:
https://www.dropbox.com/sh/j5r6h3ew8leamqy/AABAMq2LVVdLdR71TKfIB9rNa/sessions?dl=0&preview=Session+Boss+-+test1+User+Session+08-21+17.15.json&subfolder_nav_tracking=1
and restore from it...

Does that work like it does for me (ie, with the "wobble" and then fully loaded)?

---
@mimecry
> seems you have to disable firefox's native 'restore previous tabs and windows on startup'

No, I have that enabled (ie "Startup, [ ] Restore previous session" is checked in "about:preferences"),
and that's what I use for restoring the windows in my default persistent session whenever I restart
(not Session Boss, which has never interfered with that for me).

---
---
(
This all works the same on both my computers,
one with a perfectly normal FF version 91.0.1 on Ubuntu 20.04.3 LTS
and the other with an awkwardly mostly-frozen FF version 75.0 on an awkwardly mostly-frozen Gentoo 2.7 [(which I have to keep using indefinitely for complicated reasons)],
TST version 3.8.11 on both.
)

**Comment by mzso** [comment]
[**@mimecry**](https://github.com/mimecry) commented on [2021. aug. 21. 22:13 CEST](https://github.com/piroor/treestyletab/issues/2983#issuecomment-903171145 "2021-08-21T20:13:38Z - Replied by Github Reply Comments"):
> seems you have to disable firefox's native 'restore previous tabs and windows on startup' because otherwise Session Boss opens one or even two extra windows of identical tabs. 

I never used Session Boss' restore feature. At least Firefox can restore tabs tree structures as they were. (Although the order of the windows is usually messed up, an old bug...)

> my experience with restored tree structure also mirrors that of mzso's, tabs are rearranged and moved all over the place

I wonder why not everyone experiences this. Do you have many addons or other Firefox customizations?

**Comment by silverwings15** [comment]
@mjsn i do have a massive number of addons and customizations, so that might be it

**Comment by mzso** [comment]
[**@mimecry**](https://github.com/mimecry) commented on [2021. aug. 22. 15:19 CEST](https://github.com/piroor/treestyletab/issues/2983#issuecomment-903267956 "2021-08-22T13:19:10Z - Replied by Github Reply Comments"):
> [@mjsn](https://github.com/mjsn) i do have a massive number of addons and customizations, so that might be it

Hmmm. I as well. If you find some conflict please make note of it here.

Not sure who this "mjsn" who you responded to though. :)

**Comment by silverwings15** [comment]
what a brainfart, sorry about that!!!

**Comment by piroor** [comment]
Hmm, the bot looks to ignore the latest comment 2 days ago wrongly...

**Comment by zekeblue** [comment]
Similar problem for me with Tab Session Manager.  Ongoing for at least two years!  

Lost energy to try to figure it out.  Restoring with TSM has tabs in reverse order withing groups.  If I manually save the window with reversed order in TSM, then restore that window, everything is in the correct order again.  Workaround that is a pain, but enough to work with for now.

**Comment by irvinm** [comment]
@zekeblue I believe the issue of reverse tab restoring has to do with how TST inserts children ... whether at the top of the children list or the bottom of the list.  I remember having that problem, then I switched children insert mode and everything has worked well in terms of TSM for me.  (I also have browser.tabs.insertAfterCurrent = true which I think played a roll in my particular situation)

**Comment by zekeblue** [comment]
> 
> 
> @zekeblue I believe the issue of reverse tab restoring has to do with how TST inserts children ... whether at the top of the children list or the bottom of the list. I remember having that problem, then I switched children insert mode and everything has worked well in terms of TSM for me. (I also have browser.tabs.insertAfterCurrent = true which I think played a roll in my particular situation)

Thanks for that!  I just changed the setting from false.  Fingers crossed that it works for me as well.

**Comment by mzso** [comment]
[**@irvinm**](https://github.com/irvinm) commented on [2021. aug. 26. 23:32 CEST](https://github.com/piroor/treestyletab/issues/2983#issuecomment-906758129 "2021-08-26T21:32:46Z - Replied by Github Reply Comments"):
> [@zekeblue](https://github.com/zekeblue) I believe the issue of reverse tab restoring has to do with how TST inserts children ... whether at the top of the children list or the bottom of the list. I remember having that problem, then I switched children insert mode and everything has worked well in terms of TSM for me. (I also have browser.tabs.insertAfterCurrent = true which I think played a roll in my particular situation)

Hmm... That doesn't really explain my issues when the tree structure might be mostly missing or garbled.

**Comment by irvinm** [comment]
@mzso yes, I know that doesn't explain the structure challenge portion ... I was just talking about the reverse ordering.

I have had challenges with the indentation as well, and as for me, the best solution I have had is to make sure that the TST tab creation delay value in TSM is pretty large and that I also set TSM to create discarded tabs.  I would rather create the tree structure properly and take a few minutes (for 500+ tabs) than create all of those tabs and lose my structure.  [Looks like I use 500ms as the delay, so that basically only restores 2 tabs per second or 120 tabs per minute ... I'm guessing that number might have to change based on the performance of the machine as well.]

I don't have to restore sessions very frequently any more, so I can't really say the state of things between TST and TSM.

**Comment by mzso** [comment]
@irvinm
I already had it at 650ms, and even increasing it to 2000ms restores the tabs the same broken way. So it still seems it goes all wrong during saving.

**Comment by irvinm** [comment]
> 
> 
> @irvinm
> I already had it at 650ms, and even increasing it to 2000ms restores the tabs the same broken way. So it still seems it goes all wrong during saving.

*IF* you want to try sharing a saved session, I am happy to try on my machine to see if it is really the saved session or something in the configuration of either TST or TSM.  Just a thought ... If I can get it to work, then it isn't the saved session.  If I can't then maybe it is the saved session.  Up to you.
