### ISSUE TITLE
close buttons on left hand side

### ISSUE THREAD

**Issue by sirix123** [piroor/treestyletab#2984]
Hi,

Sorry not sure where to ask this I don't know if its a bug but I can't find a solution via google or the settings page but suddenly maybe I hit a hotkey? my tree is now backwards? if you see the picture the close buttons is on the left not the right and I can't really see the tree depth anymore.

![image](https://user-images.githubusercontent.com/21241272/129564920-35c98b66-1bc7-4324-9e36-6d7477b63a4a.png)

**Comment by piroor** [comment]
If you put the sidebar rightside, it is the expected appearance on TST 3.8.9 and later which is produced by TST options => "Appearance" => "Style of contents ..." => "Auto detect ...". You'll get back the old appearance with the choice "Left side".

**Comment by vandervecken** [comment]
I just had the same problem. Forcing it to select "Left side" works. This is new with the latest version. The Auto-detect behaviour doesn't respond correctly when TST is on the left side.

**Comment by durka** [comment]
Thanks @piroor. I also thought I did something wrong or somehow changed a setting in Firefox itself when this suddenly switched for me today. Definitely a very surprising UI update.

**Comment by durka** [comment]
By the way, if you use the "Photon" theme then the right edge of the tab is still visible in the "right side" tree, but with other themes it is invisible as @sirix123 said so the tree structure is hidden.

**Comment by sirix123** [comment]
Perfect thank you! (FYI it was on the right side) but "Appearance" => "Style of contents ..." => "Auto detect ...".  this fixed it

**Comment by piroor** [comment]
The detection logic is here: https://github.com/piroor/treestyletab/blob/54d08a43a577b3611c2e3bbaf3d10fd3be9d6c93/webextensions/sidebar/sidebar.js#L819-L826
It depends on some coordinates of the sidebar panel: `window.mozInnerScreenX` (left edge of the sidebar panel), `window.screenX` (left edge of the window), `window.outerWidth` (width of the window), and `window.innerWidth` (width of the sidebar panel). When `privacy.resistFingerprinting` is `true`, `window.mozInnerScreenX` returns a value same to `window.screenX`, `window.innerWidth` returns a value same to `window.outerWidth`, and `window.screenX` always return zero. As the result the sidebar panel position should be detected as "left side". However this issue and other some reports say that the position is mistakenly detected as "right side". I need to know why such unexpected result happens...

**Comment by durka** [comment]
Mine really is on the right side of the window. But I still like the "left
side" appearance better :)

**Comment by piroor** [comment]
Hmm, I expected that most people who put the sidebar at right side might choose "Right side" explicitly on old versions of TST. But actually the expectation might too much.

If you didn't any change about the appearance option of TST on old versions, sadly there is no hint to detect your previous decision "right side sidebar with left side appearance". It looks required to introduce some notification or migration message about the change.

**Comment by durka** [comment]
I'm sure it's a pain to do that when you already rolled out the update (and thank you for your tireless work on this extension for free!), but personally I would encourage it. I wasn't even sure where to look for the change, assumed maybe I had some incompatible userChrome.css or something.

**Comment by piroor** [comment]
I've implemented a confirmation to switch the appearance of the sidebar contents based on the sidebar position. TST 3.8.10 including the change is already uploaded and waiting the review.

**Comment by Kubuxu** [comment]
Thanks, awesome work.
My first reaction was "oh shit, userCrhome.css broke" as well, the confirmation will for sure avoid confusion for others.

**Comment by stampjp** [comment]
This discussion did not seem same as my problem, #2988, but now reading further it is. Note I found a weird (to  me) work-around by increasing sidebarPosition setting from 0 to 0.01. It is much more convenient for right handed people (IMO) to have close button on right, TST on right, indent and collapse arrow on left. I hope your fix doesn't mess this up again. FFnow at 91.0.1.

**Comment by piroor** [comment]
@stampjp  `sidebarPosition`'s possible values are just three cases: `0`=`auto detect`, `1`=`left side`, and `2`=`right side`.  Any other value is treated same as `1`.

**Comment by vandervecken** [comment]
Now on 3.8.11 I get a popup saying "TST has detected "right side". So now I know it's an error, because it's definitely left side.
This might be a multi-monitor issue.
On my right (main) monitor, auto-detect detects correctly that my tabs are on the left side.
On my left (secondary) monitor, it incorrectly detects that my tabs are on the right side.

**Comment by piroor** [comment]
OK I've confirmed a mis-detection with these conditions:

* Primary monitor
  * position: right
  * resolution: 1920x1200
  * zoom: 125%
* Secondary monitor
  * position: left
  * resolution: 1920x1080
  * zoom: 150%

On this environment, when I put a browser window with a sidebar half width of the window,  at the left edge of the left monitor:

* window.screenX = -1920
* window.mozInnerScreenX = -1274
* window.outerWidth = 461
* window.innerWidth = 216
* window.devicePixelRatio = 1.5

On the other hand, when I put the left edge of the window at the center of the left screen:

* window.screenX = -1363
* window.mozInnerScreenX = -688
* window.outerWidth = 461
* window.innerWidth = 216
* window.devicePixelRatio = 1.5

And  when I put the left edge of the window at 1/4 from the right edge of the left screen:

* window.screenX = -954
* window.mozInnerScreenX = -308
* window.outerWidth = 461
* window.innerWidth = 216
* window.devicePixelRatio = 1.5

window.screenX looks unstable. Currently I don't know which is correct: window.screenX and window.mozInnerScreenX, but they should be similar. This unexpected result breaks the auto detection feature...

**Comment by Frenzie** [comment]
> My first reaction was "oh shit, userCrhome.css broke" as well, the confirmation will for sure avoid confusion for others.

The confirmation dialog telling me the exact opposite of what was happening confused me plenty and I came here to report a bug, but it doesn't seem to be one? With "left side" everything's on the right side and vice versa.

**Comment by piroor** [comment]
Sorry for confusion. I've released TST 3.8.12, it contains a change: deactivating the auto detection if it cannot detect the sidebar position from coordinates due to a high-dpi screen placed lefter than the primary screen.

**Comment by vandervecken** [comment]
Nice. This is exactly what is happening to me. I have a Surface laptop on the left, and a regular monitor (3440x1440) on the right.

**Comment by piroor** [comment]
As I commented at https://github.com/piroor/treestyletab/issues/3739#issuecomment-2929756371 the fragility of window.screenX looks fixed on recent versions of Firefox. I've activate the logic to detect sidebar position again for any cases.
