### ISSUE TITLE
TST breaks after auto-update to the latest version

### ISSUE THREAD

**Issue by wagnerand** [piroor/treestyletab#2986]
## Short description

When TST auto-updates while it is open in the sidebar, the display breaks at the progress bar, and TST doesn't seem to be able to recover without a restart a Firefox.

The console shows the following output:

```
Uncaught (in promise) TypeError: tab.$TST is undefined sidebar.js:512:7
    rebuildAll moz-extension://<moz-uuid>/sidebar/sidebar.js:512
    addAsync moz-extension://<moz-uuid>/common/metrics-data.js:27
    rebuildAll moz-extension://<moz-uuid>/sidebar/sidebar.js:496
    init moz-extension://<moz-uuid>/sidebar/sidebar.js:221
    addAsync moz-extension://<moz-uuid>/common/metrics-data.js:27
    init moz-extension://<moz-uuid>/sidebar/sidebar.js:218
    async* moz-extension://<moz-uuid>/sidebar/index.js:28
    init moz-extension://<moz-uuid>/sidebar/sidebar.js:319
    AsyncFunctionThrow self-hosted:696
    <anonymous> moz-extension://<moz-uuid>/sidebar/index.js:28
    InnerModuleEvaluation self-hosted:2381
    evaluation self-hosted:2332
```

## Steps to reproduce

1. Install an old of TST.
2. Make sure the sidebar is open.
3. Wait some time for TST to auto-update.

## Expected result

Sidebar re-initializes successfully after update.

## Actual result

Broken sidebar after update

## Environment

 * Platform (OS): macOS 11
 * Version of Firefox: 92.0b4 (although I have been seeing this in earlier versions as well)
 * Version (or revision) of Tree Style Tab: 3.8.9 (as I said, happened with previous updates as well)

**Comment by irvinm** [comment]
@piroor any thoughts on this one?

**Comment by piroor** [comment]
@wagnerand I cannot reproduce the problem. Is it reproducible repeatedly with clean profile?

**Comment by wagnerand** [comment]
I couldn't reproduce this in a new profile when manually updating from 3.8.4 to 3.8.11, but then the automatic background update for those versions in my main profile didn't trigger the error this time either. I am also not sure if this only occurs for automatic background updates or also if you manually trigger the update.

All I know is that is happened several times in the past.

**Comment by piroor** [comment]
Hmm, I still cannot understand why this happen... After I researched related codes from your stack trace, the problem must not happen when TST is loaded from scratch. One possibility: it can happen there are mixed namespaces before and after update of TST.

I experimentally introduce a safe guard mechanism with the commit 78d577c. when the error situation you saw happens, TST now reloads the sidebar page. I hope it should become an effective workaround.
