### ISSUE TITLE
"Extra style rules for sidebar contents" is missing

### ISSUE THREAD

**Issue by ghost** [piroor/treestyletab#2987]
## Short description
After an auto-update (Aug 17, 2021 version) I am no longer seeing "Extra style rules for sidebar contents" in the Advanced section of the TST options.

## Steps to reproduce
I'm trying to follow the instructions at https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules but I can't find the "Extra style rules" option, has it been removed?  Is there a new way to specify custom CSS?

## Environment
 TST version 3.8.9
 Tested with Firefox 91.0 on Windows 10 and also Firefox 85.0 on Gentoo Linux - same result.

**Comment by irvinm** [comment]
It is in the "advanced" section of the options.  If you expand that section, do you see it?

**Comment by piroor** [comment]
Sorry I forgot to update the description.  "Extra style rules for sidebar contents" is for old versions, now it is "Extra style rules for contents provided by Tree Style Tab".

**Comment by ghost** [comment]
![shot-2021-08-18_08-36-38](https://user-images.githubusercontent.com/87669806/129907921-13903405-40b7-4d03-8e08-78e2d295b823.png)

This is what I'm seeing for the "Advanced" section.  I don't see anything there about style, and I'm not sure what you mean by "expand that section"  (I've already tried "Unlock Expert Options".   Sorry if I'm missing something obvious.

**Comment by irvinm** [comment]
Ah!  Go to about:addons -> Tree Style Tab -> Options -> Advanced (section) ... 

![image](https://user-images.githubusercontent.com/979729/129910362-00550a50-88cd-478b-92d9-418d0705f924.png)

**Comment by ghost** [comment]
Thanks!
