### ISSUE TITLE
Close tab x moved to left, tree indent to right 

### ISSUE THREAD

**Issue by stampjp** [piroor/treestyletab#2988]
## Short description
With TST on right, using High Contrast Theme, after update the close tab/tree x was moved from the right side to the left and the indent of the child tabs moved from the left to the right. 
## Steps to reproduce
Happened on two Windows computers with same configurations.

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): Windows 10 Home 64bit 21H1 build 19043.1165, Firefox 91.0 64bit
 * Version of Firefox: Firefox 91.0 64bit
 * Version (or revision) of Tree Style Tab: 3.8.9

**Comment by stampjp** [comment]
![image](https://user-images.githubusercontent.com/22268596/129834854-5ccf15fe-05af-4063-83d2-274c4350bf78.png)


![image](https://user-images.githubusercontent.com/22268596/129834830-bdff291b-5064-4553-ab61-b227c6642f9e.png)

**Comment by piroor** [comment]
This looks same to #2984.
