### ISSUE TITLE
tree not appearing after install

### ISSUE THREAD

**Issue by rowlandsm** [piroor/treestyletab#299]
the tab tree stopped working so I removed it and re-installed, its installs and is visible in extensions but just does not launch and  tree tab , when I click another tab FF just opens another tab as normal. 

Versions

Tree Style Tab 0.14.2012050301
Fire Fox 10.0.4 

I have also tried a the newer version of Tree Style tab but reverted to the original version as it did work at on point.

any help greatly appreciated.

thanks

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
