### ISSUE TITLE
Manual Grouping Only?

### ISSUE THREAD

**Issue by raywood1** [piroor/treestyletab#3001]
I am using TreeStyleTab in the current Firefox on Windows 10. I have gone through the settings several times; I can't seem to find what I'm looking for.

I'm looking to prevent automatic indenting or grouping. I love the tree structure; I just want to be able to control grouping manually. In other words, if I don't drag a tab to a sublevel, I want it to remain on the top level.

Is there a setting for that? TIA.

**Comment by irvinm** [comment]
I think what you probably want to do is to go under the "new tab behavior" section and basically make new tabs either siblings of the current tab or an independent tab.

**Comment by Lej77** [comment]
The ["I don't need an automatically organized tree, I want to organize trees myself"](https://github.com/piroor/treestyletab#feature-requests-i-dont-need-an-automatically-organized-tree-i-want-to-organize-trees-myself) question in the ["Feature requests"](https://github.com/piroor/treestyletab#feature-requests) section of Tree Style Tab's readme seems relevant. Maybe see if that helps?

**Comment by tigersof** [comment]
You might also find "TST More Tree Commands" extension, also by Piroor, helpful. It flexibly flattens/indents selected tabs, or the whole tree, via the context menu.

**Comment by piroor** [comment]
@raywood1 I think that @Lej77's suggestion will match to your case. Could you try that?
