### ISSUE TITLE
Editing container/groups

### ISSUE THREAD

**Issue by chrispikula** [piroor/treestyletab#3010]
## Short description
I'd like to make a set of custom container groups, say, 'News', 'Fiction', etc, etc.  I'd like to give them a custom color as well, but that's a nice to have, not a need.  The ability to remove Banking and Shopping would be nice as well.

I've spent 30 minutes at this, and am currently at a loss.  I'm pretty sure it's possible, but searching online, and inside this github has given me pretty much no clue as to how.  I've seen "about:treestyletab-group?BlahBlah", but that doesn't add it to the "Open in New Containers Tab" context menu.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox:  92.0
 * Version (or revision) of Tree Style Tab:  3.8.12

**Comment by irvinm** [comment]
about:preferences#containers
