### ISSUE TITLE
TST eliminates the close button in the find in page toolbar

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#3011]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. ctrl-f to open the find toolbar
     ![image](https://user-images.githubusercontent.com/895588/132972941-5b392a39-7d3e-4625-b9ef-7a6eeefd306d.png)
     the close button is present
 3. Install TST.
 4. restart Firefox
 5. ctrl-f to open the find toolbar
     ![image](https://user-images.githubusercontent.com/895588/132973005-65954b82-f89e-4d67-9b2a-95f2a66a38f8.png)
     the close button is missing

## Environment

 * Platform (OS):  win10 21H1 x64
 * Version of Firefox: 92.0 x64
 * Version (or revision) of Tree Style Tab: 3.8.12

**Comment by irvinm** [comment]
This looks like a bug with Firefox and the sidebar ... and nothing to do with TST.  Change the context of the sidebar to something like bookmarks and repeat it.  You should get the same result.  They are obviously not recalculating the position of the close button properly when the sidebar is opened and the find bar is already visible.

**Comment by piroor** [comment]
As @irvinm mentioned it is a problem of Firefox itself and any addon cannot solve it. I've find out a bug on bugzilla.mozilla.org: [1729958 - The find bar cannot be closed if the sidebar is open.](https://bugzilla.mozilla.org/show_bug.cgi?id=1729958) thus I recommend you to track it.
