### ISSUE TITLE
Takes time to load when I open it

### ISSUE THREAD

**Issue by deepanshu44** [piroor/treestyletab#3012]
It's slow to load all tabs when I open.
Using in firefox in Ubuntu 20.04  .
I also use Tab2List and its quick and no lag.
![buffering_1.gif](https://user-images.githubusercontent.com/62979448/132993324-00cb6a2c-6edc-46ad-a5b2-7d3ccfe06dd5.gif)

**Comment by irvinm** [comment]
- Is this a new behavior that you are experiencing?  (If so, what changed?  TST version, Firefox version, other?)
- Have you tried a clean profile with just TST to see if you see the same performance?
- You didn't mention anything more about your machine.  Is the machine fairly modern or is it really old with little memory available?
- Worst case, you might need to capture a performance profile so see where the time is being spent. (https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-collect-a-performance-profile)

**Comment by deepanshu44** [comment]
@irvinm I believe I found the problem. 
Actually i have multiple hidden tabs (SimpleTabGroup extension).

**Comment by irvinm** [comment]
I'm glad to hear that.  Will you close this item if there is nothing to do at this time?

**Comment by deepanshu44** [comment]
@irvinm can it be made faster? 
Can it ignore hidden tabs from Simple Tabs Groups extension

**Comment by irvinm** [comment]
@piroor will have to comment more as to if there are ways to improve performance, *BUT* I would guess that TST during initialization has to basically inventory *ALL* of the tabs establishing appropriate listeners to monitor for changes ... regardless of their hidden state via Simple Tab Groups.  [TST needs to monitor all of this so when Simple Tab Groups changes the visibility of the native tab(s) that TST properly shows\hides them in the TST sidebar]

This is where the TST performance profile might help @piroor determine if there is a problem or it is working as expected based on the number of tabs being processed at startup.

**Comment by deepanshu44** [comment]
@irvinm You can try yourself.

Open terminal, 
run "firefox -P newProfileName", enter profile name
-install both addons
-create 2 groups in STG
-open 2nd group and then press and hold Ctrl+T till you have 20+ tabs
-now open 1st group through STG
-open 5 tabs with random content
-now test TST by opening and  closing, you'll see the problem

**Comment by irvinm** [comment]
I did exactly your instructions and don't see any performance problems.

https://user-images.githubusercontent.com/979729/134429282-7ddd84ba-82a9-4a10-b783-5bd1c6927089.mp4

**Comment by deepanshu44** [comment]
@irvinm can you try again with 200 hidden tabs 
I am being lazy with tabs.


https://user-images.githubusercontent.com/62979448/134457625-2cb26ecb-0b9d-4b8a-b7bf-8727c9fac819.mp4

BTW, I am fine right now as I am using Tab2List and I sometimes open TST to close trees. And also I want to ask whether moving a tree to different group in STG possible as right now I had to open tree manually and select all tabs under the tree and then select move.

**Comment by irvinm** [comment]
I did 250 in one group and 10 in the other.  The performance seems reasonable for a total session size of 260 tabs running inside a VM.

https://user-images.githubusercontent.com/979729/134504691-12f5ef8a-92f2-4546-9c54-1cd3275797ae.mp4

In terms of moving trees to different groups in STG is a STG question.  They would need to really add support for TST by adding a menu option to TST via the TST API to move a tree (hierarchy of tabs) from one group to another.  If you do a search on the STG Github site, you will see a fair amount of discussion around TST.

**Comment by deepanshu44** [comment]
@irvinm 
Thanks for the comment, I'll ask there and reference your comment there.
I have intel i5 and performed the above operations in freshly booted m/c.

Hey, am I allowed to ask off topic questions related to addons, like I don't want the installed addons(or firefox as a whole) to have access to my whole computer directory.

 Is it possible to limit access to a single folder. Is there a button in firefox, or sandbox addon or firefox or something like that?
Thanks

**Comment by irvinm** [comment]
Best place for discussions is here:  https://github.com/piroor/treestyletab/discussions

**Comment by deepanshu44** [comment]
@irvinm last question,  what do you believe the source of problem is

**Comment by irvinm** [comment]
Sorry @deepanshu44 ... I have no idea.  I am just a user of TST just like you.  The performance might be as good as it is going to get for your hardware (CPU and\or memory) or there might be a problem that the performance profile might be able to help @piroor to see where TST is spending its time initializing the sidebar.

**Comment by piroor** [comment]
Sorry for my silence. There are many factors affecting to the performance of TST: CPU, RAM, OS, video driver, other addons, and more. Sorry but I cannot determine what is the bottle neck on your environment without any performance profile.

**Comment by deepanshu44** [comment]
@piroor @irvinm thanks for the reply, I believe its happening may be  because my laptop is slow as it takes >4 min. to bootup. And right now this extension became unusable as opening it crashes my whole system. I have many extensions installed btw.
 
I took  performance profile and tried to open the file generated and, it crashed my system. Its was 5 MB json file.

I am busy right now as I have to get a job. I am sufficing with Tab2list right now. May be tryout TST again if I get a high performance system later. Thanks
