### ISSUE TITLE
With TST, the "find in page" toolbar doesn't display completely

### ISSUE THREAD

**Issue by SogaSuga** [piroor/treestyletab#3013]
## Short description
On firefox 92.0(64-bit), windows 10 21H1(19043), TST 3.8.12 maybe causing trouble for "find in page" bar to display completely.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Ctrl + F to show Find in page toolbar. The "x" button doesn't show up.
![Snipaste_2021-09-12_23-49-27](https://user-images.githubusercontent.com/66196437/133026626-1bf7204b-5cec-4a57-a998-e62e88349603.jpg)

 4. Hit F1 to toggle TST, the "x" button shows up.
![Snipaste_2021-09-12_23-49-52](https://user-images.githubusercontent.com/66196437/133026692-2bca6401-ab94-4e8f-b1d1-2d1b53e1b228.jpg)

**Comment by piroor** [comment]
This looks to be a dup of #3011 and I recommend you to track the Firefox bug: [1729958 - The find bar cannot be closed if the sidebar is open.](https://bugzilla.mozilla.org/show_bug.cgi?id=1729958)
