### ISSUE TITLE
"X" button to close "Find in page" bar is missing on latest. 

### ISSUE THREAD

**Issue by Grenaid** [piroor/treestyletab#3019]
"X" button to close "Find in page" bar is missing on latest.  Can be restored by disabling TST.

![image](https://user-images.githubusercontent.com/441380/133959136-a77d6d74-9933-4d8e-b468-fbdaa488fbd4.png)

## Environment

 * Platform (OS): 21H1 Windows 10.
 * Version of Firefox: 92.0 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.8.12

**Comment by piroor** [comment]
This looks to be a dup of #3011 (, #3013) and I recommend you to track the Firefox bug: [1729958 - The find bar cannot be closed if the sidebar is open.](https://bugzilla.mozilla.org/show_bug.cgi?id=1729958)
