### ISSUE TITLE
Child tabs invisible after reopening parent tab

### ISSUE THREAD

**Issue by epjane** [piroor/treestyletab#3022]
## Short description
When reopening a tab that is collapsed and has multiple children, only the first child is visible and the rest are hidden, but can still be accessed with the "next/prev tab" keyboard shortcuts.

## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a couple links in a new tab, so they are sub-items in the tree.
 4. Switch to a different tab
 5. Collapse the parent tab of the links you opened
 6. Right click and select "Reopen closed tab"
 7. Only the 1st child tab is shown, whereas multiple should be there.

Here's a GIF showing the issue:

![tabs](https://user-images.githubusercontent.com/18060905/134289125-a0b99e8d-de0c-4834-9b82-2c755f8dc7a1.gif)

## Expected result
All child tabs should be shown after reopening a closed tab.

## Actual result
Only the first child tab is visible.

## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: 92.0
 * Version (or revision) of Tree Style Tab: 3.8.12

**Comment by piroor** [comment]
Thanks, the commit c49a6bf should fix this.

**Comment by epjane** [comment]
Tested the latest build on a fresh firefox profile and works for me, thanks!

**Comment by irvinm** [comment]
@johanvandegriff feel free to close this item or if you want to or wait until the official version is out ...
