### ISSUE TITLE
Changing to Photon Theme Deletes Session Restore

### ISSUE THREAD

**Issue by Tylast** [piroor/treestyletab#3025]
## Short description
I change from the default to the Photon Theme, when I relaunch FF, I lose my restored session...every time.  I have to restore from Time Machine to recover my 100+ tabs.  I changed to the Photon theme to gain use of the auto dark theme in sync with MacOS.

## Steps to reproduce
The description sums it up. 

## Environment
MacOS 11.6
FF 92.0.1
TST 3.8.12

**Comment by piroor** [comment]
Sadly I couldn't reproduce the problem. I've tried to switch the theme from Sidebar (default on macOS) to Photon via TST's options page, but all tree structure stayed there after relaunch Firefox. My environment:

* macOS Big Sur 11.5.2
* Firefox 92.0.1
* TST 3.8.12

**Comment by piroor** [comment]
I need more information to reproduce the problem on a clean environment. You can launch Firefox with new clean profile from `about:profiles`, so could you narrow down exact conditions to reproduce the problem?
