### ISSUE TITLE
Text is not readable on TST active tab in Colorways "Balanced" themes

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#3026]
## Short description
Currently available in Nightly and Beta, Colorways are new official monochromatic themes that may be released in Firefox 94.
Since the themes will be included in Firefox, TST may need to support them in addition to the existing light/dark/alpenglow theme.
I don't expect TST to support a not-yet announced feature. I am filing this issue now so you can keep an eye on it when it is officially announced.

Metabug for Colorways: [Bug 1725467 - [meta] Monochromatic themes](https://bugzilla.mozilla.org/show_bug.cgi?id=1725467)

The issue here is that the text color on the active tab in TST is not readable for "Balanced" type Colorways themes.

## Steps to reproduce

 1. Start Nightly 2021-10-05 build or later with clean profile.
 2. Install TST.
 3. Go to about:addons > Themes.
 4. Enable any "Balanced" type Colorways theme.
 5. Observe the active tab in TST.

## Expected result
I can read the text on the active tab.

## Actual result
Text is not readable as the text color is not inverted.
![image](https://user-images.githubusercontent.com/771216/136455326-6edd57a5-347b-4f1a-867c-0323d864f0b5.png)

The text in Firefox's own tab bar is readable.

I don't know how theme works, but here is the files for the Foto – Balanced theme:
https://searchfox.org/mozilla-central/source/browser/themes/addons/monochromatic/foto/balanced

"Soft" and "Bold" themes are not affected.

## Environment

 * Platform (OS): Windows 10 21H1
 * Version of Firefox:  Nightly 2021-10-07 build, Beta 94.0b2
 * Version (or revision) of Tree Style Tab:  3.8.13

**Comment by piroor** [comment]
Thanks. The commit 604ae86 should fix this

**Comment by Fanolian** [comment]
![image](https://user-images.githubusercontent.com/771216/136695301-74b62d4a-6146-447d-ac13-9f3ec03e10e6.png)

The issue on active tab text and toolbar icon are fixed in 3.8.13.11732. Thanks.
But now the TST icon on the sidebar header is barely visible until you hover on it. (Same for the TST icon inside the sidebar header menu.)

**Comment by piroor** [comment]
Thanks, with the commit 7e322a3 now TST respects given colors of popup text and sidebar header text.

**Comment by Fanolian** [comment]
All fixed in 3.8.13.11733. Thanks.
