### ISSUE TITLE
Suggested Feature: Ability to Highlight a Tab

### ISSUE THREAD

**Issue by AdventureDave82** [piroor/treestyletab#3028]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
Too less information. Please describe what should TST work as with the suggested feature, via descriptions or edited screenshots.
