### ISSUE TITLE
Option to avoid expanding the target tree of a drag-and-drop?

### ISSUE THREAD

**Issue by HighCommander4** [piroor/treestyletab#3029]
## Short description

When dragging-and-dropping a tab, the target tree is expanded. It would be nice to have an option to keep it collapsed.

The use case I have in mind is: I'm manually organizing some tabs by putting them into "folders" for later. If the folder has many tabs in it already, then expanding it may scroll the next tab I want to organize (that isn't in the folder) out of view.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Uncheck "When a tab gets focus, expand its tree and collapse others automatically".
 4. Open some tabs such that there is a at least one tree T, and a tab A outside T (e.g. at top level).
 5. Collapse T.
 6. Drag A and drop into onto (the root of) T.

## Actual result

T is expanded.

## Expected result

It would be nice to have an option to keep T collapsed.

I realize this means the addon would need to choose another tab to focus. I think choosing whichever tab would be focused if A was closed instead, would be fine.

I looked through existing options related to "expanding", but couldn't one find. Apologies if I overlooked one.

## Environment

 * Platform (OS): Debian 10
 * Version of Firefox: 78.14.0esr
 * Version (or revision) of Tree Style Tab: 3.8.14

**Comment by piroor** [comment]
It looks possible with the combination:

* TST options: "Drag and Drop" => uncheck "Expand collapsed tree with hovering over ... msec while dragging" (it is visible only when "Unlock Expert Options" is checked)
* Install [TST Lock Tree Collapsed](https://addons.mozilla.org/firefox/addon/tst-lock-tree-collapsed/) and double-click on a parent tab which should not be expanded automatically.
  * TST Lock Tree Collapsed options: "Don't expand tree automatically when" => check "a Child Tab is attached" and more others.

**Comment by HighCommander4** [comment]
Thanks for the suggestion. The effect is interesting -- after dragging, the locked tab is in a "partially collapsed" state where its previous children remain hidden, but the tab (or tree) that was dragged remains visible.

**Comment by piroor** [comment]
Oops, thanks it is a bug of TST itself.

**Comment by piroor** [comment]
The change 048e71a should fix the problem you saw. Thanks!

**Comment by I60R** [comment]
I hate this too.

But in my case the problem is that the currently active tab is always included in selection. That said, it isn't possible to just Ctrl+click on some tabs and drag them somewhere without also dragging the currently active tab.

I'd like to have an option to make the currently active tab lose selection on Ctrl+click on another tabs without losing focus. In the most of cases this would also resolve the problem with unexpected expanding of trees.
