### ISSUE TITLE
"Bookmark this Tree ..." doesn't add the container to the bookmark

### ISSUE THREAD

**Issue by jceb** [piroor/treestyletab#3030]
## Short description

I use containers for tabs and trees of tabs a lot. The addition of bookmarks in TST is really helpful for that, however I noticed that TST doesn't save the container of the tab in the bookmark. This is unfortunate, because when I restore the bookmark tree via "Open All as Tree", the tabs show up in the default container instead of the one that the tabs were in at the time the bookmark was created.

## Steps to reproduce

 1. Create a tree of tabs.
 2. Open one tab in the tree in a container.
 3. Bookmark the tree using TSTs "Bookmark this Tree..." from the menu.
 4. Restore the bookmark tree via "Open All as a Tree" from the menu.
 5. See that the tab that was in the container is outside the container.

## Expected result

The tab should be in the same container after restoring the tree from the bookmarks.

## Actual result

Tab is outside the container.

With the TST Open Bookmarks as Partial Tree I can restore the whole tree in one particular container. This is helpful but I'd prefer if the tab would always stay in the same container. This way I could mix tabs with different containers in one tree.

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 93.0
 * Version (or revision) of Tree Style Tab: 3.8.14

**Comment by piroor** [comment]
I think it is beyond TST's project scope. Instead it looks better that Container Bookmarks automatically detect its suitable container if a created bookmark is supposed corresponding to an existing container tab.
https://github.com/rafaelgomesxyz/container-bookmarks/issues

**Comment by piroor** [comment]
I've opened an issue on the Container Bookmarks project.

**Comment by jceb** [comment]
Thank you
