### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by SHHSSH** [piroor/treestyletab#3033]
Hi @piroor, just wondering if it all possible for a shortcut modifier of move current tree to top or bottom?

It can be extremely utilised in lengthy scrollable sidebars whilst brainstorming to allow a user to curate their positioning more promptly.

Instead of a user having to drag folders to the top with the mouse, I feel this could really be helpful.
As I already use these two below fairly often, but for anything else the mouse must be used.
https://ibb.co/yVS54j4

Thanks for your consideration.

**Comment by SHHSSH** [comment]
Anywhere I can donate?

**Comment by SHHSSH** [comment]
------- it's nothing major, but still usable, I had only just noticed you could hold it down, my mouse macro was malfunctioning.

**Comment by SHHSSH** [comment]
However, this could also be useful for singular tabs, not only groups.
Which with singular tabs having this functionality, I believe would be more useful to many more people.

**Comment by SHHSSH** [comment]
Like this standard Firefox context menu function
<a href="https://imgbb.com/"><img src="https://i.ibb.co/Ydhg0fN/kjtfjfcapture-030-02112021-164212-copy.png" alt="kjtfjfcapture-030-02112021-164212-copy" border="0"></a>
This is achievable with simply Right Click > V > S(Start)/E(End).
Therefore if this could be reproduced to function through TST as a singular command that'd be incredible.

Thanks as always.

**Comment by piroor** [comment]
> Hi @piroor, just wondering if it all possible for a shortcut modifier of move current tree to top or bottom?

It looks not related to the project scope: "tree management" so I won't implement it on TST. Instead if should be done by something other addon for the purpose, for example [TST More Tree Commands](https://addons.mozilla.org/firefox/addon/tst-more-tree-commands/). Please open an issue at [its issue tracker](https://github.com/piroor/tst-more-tree-commands/issues). (But sorry I have very few motivation to implement it by myself. It is welcome to merge any pull requests so I hope you try to implement it.)

**Comment by SHHSSH** [comment]
> 
> 
> > Hi @piroor, just wondering if it all possible for a shortcut modifier of move current tree to top or bottom?
> 
> It looks not related to the project scope: "tree management" so I won't implement it on TST. Instead if should be done by something other addon for the purpose, for example [TST More Tree Commands](https://addons.mozilla.org/firefox/addon/tst-more-tree-commands/). Please open an issue at [its issue tracker](https://github.com/piroor/tst-more-tree-commands/issues). (But sorry I have very few motivation to implement it by myself. It is welcome to merge any pull requests so I hope you try to implement it.)

Appreciate the thought.
I will figure out a way to macro the default FF Move Tab to start/end.
