### ISSUE TITLE
Respect text direction in title

### ISSUE THREAD

**Issue by NilsIrl** [piroor/treestyletab#3035]
## Short description

Normally browsers change the direction of the text depending on the language:

Firefox:

<img width="158" alt="image" src="https://user-images.githubusercontent.com/26231126/140612077-1fba4a44-edbe-4f44-8c81-7bdcef088a7e.png">

Chrome:

<img width="237" alt="image" src="https://user-images.githubusercontent.com/26231126/140612088-3b43709e-a3ec-4577-8667-acca8279e2ac.png">

However tree style tab will only respect its own text direction setting (defaults to left to right):

<img width="177" alt="image" src="https://user-images.githubusercontent.com/26231126/140612122-de755ded-ba34-4d2f-a3f9-7f8771a6c346.png">

with setting set to RTL:

<img width="174" alt="image" src="https://user-images.githubusercontent.com/26231126/140612135-1e7dd78b-849a-4b59-a7af-c132f2653306.png">

## Expected result

There should be a setting to leave the text direction to some default, so that it works similarly to how Firefox and Chrome do it by default.

## Environment

 * Version of Firefox: 94.0.1
 * Version (or revision) of Tree Style Tab: 3.8.15

**Comment by NilsIrl** [comment]
Ability to select text direction added in https://github.com/piroor/treestyletab/commit/4315f64902f28cf064a7a25130f8ee859994eeab

**Comment by piroor** [comment]
Thanks. We look to need importing Firefox's implementation:
https://searchfox.org/mozilla-central/rev/364aa1d41eb9b5ea583fa6cedc56fb5343e3514f/browser/base/content/tabbrowser.js#1615-1620
https://searchfox.org/mozilla-central/rev/364aa1d41eb9b5ea583fa6cedc56fb5343e3514f/dom/base/DirectionalityUtils.cpp#326

**Comment by piroor** [comment]
The commit 3947259 should fix this. I've tested with the page: https://www.alarabiya.net/?_gl=1*1g5wd8p*_ga*OTk4NTQ1NDY0LjE2MzYzNTU0Njk.*_ga_576H90FZVV*MTYzNjM1NTQ2OS4xLjEuMTYzNjM1NTQ3OS41MA..

**Comment by piroor** [comment]
@NilsIrl Could you try the latest development build?: https://github.com/piroor/treestyletab#development-builds

**Comment by NilsIrl** [comment]
Thanks a lot for this.

Unfortunately it fails to work using a [right-to-left mark](https://en.wikipedia.org/wiki/Right-to-left_mark), my website can be used to test that: https://www.nilsand.re/ctf/writeup/2021/02/06/trollcat21.html

**Comment by piroor** [comment]
Thanks, I've done one more change for the case with the commit c7f3617.
