### ISSUE TITLE
Children tabs counter should be at least as wide as its height (not narrower than a square)

### ISSUE THREAD

**Issue by ratijas** [piroor/treestyletab#3041]
## Short description

Tree Style Tab has a feature of displaying nested (children) tabs count as a badge on the opposite side to an expansion button (a little triangle). For small numbers, especially with a narrow glyph, like "1", the badge can be narrower than its height, resulting in a rectangular shape in album orientation.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set TST theme to "Sidebar".
 4. Open one nested tab.
 5. Collapse the tree.

```
A (collapsed) SomeTabTitle 1️⃣
\- B
E (selected)
```

## Expected result

Badges should be at least round or wider. That's how iOS & OS X does it, and Sidebar theme seems to mimic it.

## Actual result

Squeezed badges:

![Squeezed badges](https://user-images.githubusercontent.com/6737986/142744482-51d12be5-0b83-4486-b46d-3b503b899a91.png)

## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: 94.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.8.16

**Comment by irvinm** [comment]
I didn't look into the code and how the formatting is done, but it looks like it is basically just the number of digits with the rounding of the corners.  [Think of each item as a number in a box, then the corners rounded]  In the case below, you can see 1, 2, and 3 digit examples and this seems to be working as expected.

How would you expect this to change?

![image](https://user-images.githubusercontent.com/979729/142766251-d2c60692-297e-4a0c-9d0b-8d2391f32bc0.png)

**Comment by ratijas** [comment]
> How would you expect this to change?

I have no idea how to implement it in HTML, but I'll repeat in simple words:

width >= height

that's how it should be. I can see it looks good on your screenshot, but you can see as well that it doesn't work for me. Maybe different fonts or rendering backend or whatever.

**Comment by irvinm** [comment]
I checked the code and that is exactly how it is being done.

Here is the original CSS for the sidebar theme:

```
.counter {
  font-size: 85%;
  background-color: var(--badge-bg-color);
  border-radius: 8px;
  padding: 2px 4px;
  color: var(--tab-text-active);
  font-weight: bold;
  text-shadow: none;
}
```

If what you care about is having more width, just increase the value of the width padding.  Add this to your TST CSS and customize to what you like:

```
.counter {
  padding: 2px 6px;
}
```

**Comment by ratijas** [comment]
Increasing padding sounds artificial, and it doesn't account for a font size (at least in pixels). Is there any way in CSS to enforce minimum width that depends on a height?

**Comment by irvinm** [comment]
There might be some advanced CSS ways of doing that, but I do not know.

**Comment by ratijas** [comment]
It would've been such a trivial expression in QML/QtQuick, but it's some kind of dark magic in CSS no one's even aware of, lmao :D

**Comment by irvinm** [comment]
@piroor knows lots of dark magic ... he might know.

**Comment by piroor** [comment]
I've updated the CSS with the commit 03c5385
![image](https://user-images.githubusercontent.com/70062/143835221-cae4a06a-a583-471c-99af-03b5b87405ad.png)
How about this?

**Comment by piroor** [comment]
Updated: 
![image](https://user-images.githubusercontent.com/70062/143840218-52eb1983-fbdb-4ded-893a-d07c12a97301.png)

**Comment by ratijas** [comment]
> Updated:

> This issue has been closed due to no response within 14 days after labeled as "fixed", 7 days after last reopened, and 7 days after last commented.

OK, waiting for the next release! Thanks.
