### ISSUE TITLE
The 'bookmark this tree' feature not working when non-default profile is used

### ISSUE THREAD

**Issue by kiemlicz** [piroor/treestyletab#3044]
## Short description
Cannot "bookmark this tree" on non-default profile in Firefox.  
Works OK on primary profile  
Didn't check case when there are > 2 profiles

## Steps to reproduce
 1. Start Firefox: `/usr/lib/firefox-esr/firefox-esr --profile ~/.mozilla/firefox/'EDIT' %u`
 2. open multiple tabs under one root
 3. 'bookmark this tree' (root)
Nothing happens, whereas the popup should appear.

## Expected result
popup with bookmark folder selector

## Actual result
Nothing happens

## Environment

 * Platform (OS): Debian 11
 * Version of Firefox: `78.15.0esr-1~deb11u1` (Debian's default)
 * Version (or revision) of Tree Style Tab: `3.8.16`

**Comment by irvinm** [comment]
Just a guess, but it sounds like the permission isn't properly set for that profile.  Do you have "Allow to read and create bookmarks" under "Context Menu" in "Options"?

**Comment by kiemlicz** [comment]
They are set, I've done the typical restart/reinstall dance. It prompted for permissions, I've set them in options

**Comment by piroor** [comment]
This doesn't happen for me on Windows. It can be a platform specific issue.

**Comment by piroor** [comment]
Works as expected with ESR78.15.0 on Ubuntu 20.04LTS. It can be Debian specific issue.

**Comment by piroor** [comment]
Works as expected for me on Debian 11. What I got are:

1. Install Debian 11 with GNOME desktop.
2. Login to the desktop.
3. Start Firefox. It is ESR78.15.0.
4. Install TST 3.8.16 from AMO.
5. Prepare a tree.
6. Right-click on a parent tab.
7. Choose "Tree of Tabs" => "Bookmark this tree".
8. A desktop notification appears with a message about permission.
9. Click the notification.
10. A tab is opened with TST's options page.
11. Turn on the option about Bookmarks permission.
12. A permission popup opens for the requested permission.
13. Grant it.
14. Right-click on a parent tab.
15. Choose "Tree of Tabs" => "Bookmark this tree".
16. A small dialog window opens to choose the parent folder to save bookmarks. The default choice is "Bookmarks Toolbar".
17. Click "Save" with no change.
18. A new bookmark folder is created under the chosen folder at the step 16 and it contains bookmarks created from the tree.

Which step are different from your case? @kiemlicz

**Comment by kiemlicz** [comment]
thank you,
```
16. A small dialog window opens to choose the parent folder to save bookmarks. The default choice is "Bookmarks Toolbar"
```
is not appearing

I've removed the additional profile from firefox, and
- created fresh profile
- logged to firefox sync
- allowed TST to create bookmarks
- checked - **it works** (I can bookmark the tree)
- I've added the `./abqwjfnb.yet\ another\ profile/chrome/userChrome.css` with
```
/* hides the native tabs */
#TabsToolbar {
  visibility: collapse;
}
#titlebar {
  visibility: collapse;
}
```
- restarted the profile (the upper tab still exists), **bookmark functionality still works**
- I've added to the `about:config` the `toolkit.legacyUserProfileCustomizations.stylesheets=true`
- bookmark stops working

EDIT:
Trying aforementioned full-wipe method for the second time didn't result in the same outcome.  
The second time the 'bookmark this tree' didn't work right after installation of TST

**Comment by piroor** [comment]
Thank you for investigation!

Hmm, but it still don't happen on my Debian 11 environment (GNOME). I've seen Firefox windows without native tab bar but the small dialog still appear:
![image](https://user-images.githubusercontent.com/70062/144815690-40ba2bbd-9fae-4453-aab4-d7580a2394eb.png)
No error is reported in both the browser console and the remote debugger for TST...

It looks a bug of Firefox side (maybe from a combination of something application on your platform and Firefox). The userChrome.css affects only for Firefox itself and TST is not designed to change its behavior based on the file. I think the problem will happen with other extensions containing custom popup windows. Could you try something like https://addons.mozilla.org/firefox/addon/container-bookmarks/ ?

(And basically I don't recommend people to hide Firefox's native tabs for safety, so I still think the best workaround is disabling userChrome.css customizations.)

**Comment by matru** [comment]
@piroor @kiemlicz

I have the very same issue, but I do not think it is bound to the profiles, even though I have two and on the secondary one it works, while the first one does not.

Bookmark tabs... does not do anything.

Permissions are given, upon checking the configuration, under context menu > "Allow to read and create bookmarks" is checked.

However, nothing can be selected under "Create new bookmarks under". Three dots and nothing can be selected, the button is not interactive.

In the debugger:

![Screenshot from 2022-02-22 23-44-55](https://user-images.githubusercontent.com/526340/155233263-b341d3ae-84d1-4b31-9cfe-3add8c10de7a.png)

I tried resetting the default bookmarks, but that of course does not change anything.

**Comment by matru** [comment]
The issue does not persist if I reset my profile. So I fixed it by changing the defaultBookmarkParentId variable found in the config .json upon exporting it out through TST settings menu in Development section > All configs > Export.

To get this working I needed to get the correct defaultBookmarkParentId and to do so I exported my profile (for backup and restore), reset TST, export again with the fresh config, copy the new defaultBookmarkParentId to the old config and import the old config once again. This fixes the issue. If you can get the default and I presume the Bookmark Toolbar parent ID through other method, you can skip some of the steps above.

One thing I noticed is now, few days after (maybe it was changed upon importing), I don't even see the defaultBookmarkParentId in my current config, but it works

**Comment by piroor** [comment]
@matru Hmm, I can't imagine what triggers this problem. Anyway I hope my recent changes around the configuration library solves it. Please upload exported configs If you see the problem again.
