### ISSUE TITLE
Descendants are closed as in a collapsed tree when a promoted new parent is closed immediately after its parent was closed in a fully expanded tree

### ISSUE THREAD

**Issue by piroor** [piroor/treestyletab#3045]
### Discussed in https://github.com/piroor/treestyletab/discussions/3042

> Is there an option to fix a weird behavior caused by closing a tab recently made parent by having its parent tab closed?

<div type='discussions-op-text'>

<sup>Originally posted by **xVff12** November 24, 2021</sup>
https://gfycat.com/ThatNearAmericantoad
Gif of the issue I'm having. Essentially if I immediately close a tab that was just promoted a level by having its parent closed, all of the children of the promoted tabs are also closed. 
https://gfycat.com/IdolizedUncommonBarbet
Gif showing that the behavior does NOT occur if I close the two tabs slowly. In that case, the children tabs are preserved and this is my PREFERRED functionality.

In both cases I am only clicking the close button twice. The third tab closing seems to depend on how fast the parent tabs are closed. Is there an option somewhere to make tabs always behave like in the latter scenario, or is the former scenario a bug that needs to be reported?</div>

**Comment by piroor** [comment]
@xVff12 Could you collect a debug log? Steps:

1. Go to TST's options page.
2. Turn on "Development" => "Debug mode"
3. Click "Detailed logging" to expand the list.
4. Turn on only these checkboxes (and turn off others):
   * Log with timestamp
   * common/tree-behavior
   * background/handle-removed-tabs
   * sidebar/collapse-expand
   * sidebar/mouse-event-listener
5. Open the debugger for TST. https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-collect-debug-logs-of-tst
6. Choose the Console tab in the debugger.
7. Prepare a tree of tabs.
8. Click the dust box button in the console to clear old logs.
7. Try to close a parent tab and its first child clicking on the closebox twice.
8. If you see the problem, copy all messages reported in the console and paste them here. Otherwise, retry from the step 7.

**Comment by ErroneousDictation** [comment]
Alright, I closed the tabs so that the issue I'm encountering occurs as expected. Here's what the output looks like:
![image](https://user-images.githubusercontent.com/43498968/143969447-e9cbe9b9-61f6-4b51-bdf3-af3dd8c73512.png)

**Comment by piroor** [comment]
@xVff12 Hmm, something looks wrong... the console doesn't report any debug log. On my case, more and more logs are reported like as this screenshot:
![image](https://user-images.githubusercontent.com/70062/143970664-ef9e712b-5955-410a-bf5f-a1df329fdf6e.png)

If you use the Browser Console of Firefox itself (Ctrl-Shift-J), debug logs of TST won't appear there. You need to start the debugger for TST via about:debugging.

**Comment by irvinm** [comment]
It was harder to reproduce with debug on and the logging, but I was able to do it.  I turned on timestamps as well.

![image](https://user-images.githubusercontent.com/979729/144091202-0dec14b1-ce43-40e6-8932-50ef03a4b0ba.png)

**Comment by xVff12** [comment]
I get to the debug step where it says "accept connection" but I get no such prompt asking for me to accept any sort of connection. I am unable to start the debugger properly due to this, I assume.

**Comment by ErroneousDictation** [comment]
Alright, tried the steps again and got this. Hopefully this is the correct output.
![image](https://user-images.githubusercontent.com/43498968/144178017-d0de3ddb-a18b-4ee7-86f1-b9a2942e5d00.png)

**Comment by piroor** [comment]
Thanks! I got it. This problem happens because TST collapses the tree by double-click on the closebox (it is not the default behavior, so I think you changed the option manually.) With the commit 8b713b5 now TST ignores double-click on closeboxes in tabs.

**Comment by irvinm** [comment]
On my end, I do not have that option set.  (FYI)

![image](https://user-images.githubusercontent.com/979729/144232874-f3ac76ca-0d3d-4358-9d94-bfb02a2c2311.png)

**Comment by ErroneousDictation** [comment]
Oh yeah I manually enabled double click to collapse trees, and also the option to close trees that are collapsed. Never expected them to function together so that clicking the close button twice collapses the whole tree just in time for TST to go "oh, collapsed tree is being closed, close out everything" lmao. I honestly have no idea how to use the thing you linked to so I'll just disable the option to collapse trees by double clicking since I don't use it much. Thanks for solving this!
