### ISSUE TITLE
Unable to multi-select the first tab with ctrl/shift-click

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#3048]
## Short description
It is not possible to multi-select the first tab from TST tab bar, if I don't start the multi-selection at that tab.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST. Leave settings as default.
 3. Open 3+ tabs.
 4. On TST tab bar, left-click on the last tab, or any tab that is not the first, to bring it to focus.
 5. Ctrl- or Shift- click the first tab. If there are any pinned tabs, ctrl- or shift- click the first pinned tab instead.

## Expected result
**Ctrl-click**: The first (pinned) tab is also selected.
**Shift-click**: The first (pinned) tab until the last focused tab are all selected.

## Actual result
**Ctrl-click**: Nothing happens. The first (pinned) tab is not selected and not focused.
**Shift-click**: The 2nd tab till the focused tab are selected but not the first. It can be confirmed by Firefox's native tab bar.

I can ctrl/shift-click from the *native* tab bar to multi-select the first tab. It is also reflected on TST tab bar.
I can **deselect** the first tab with a ctrl/shift-click, but not (re-)multi-select it.

## Environment

 * Platform (OS): Win10 21H2
 * Version of Firefox: 94.0.2, Nightly 2021-12-01 (20211201050507), and a random old Nightly build (20200601214228)
 * Version (or revision) of Tree Style Tab:  3.8.16. This can also be reproduced at least on 3.5.34+ that are available at [AMO](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/versions/). I didn't test on older versions.

**Comment by piroor** [comment]
Thanks! This looked to be introduced at early versions of 3.x. The commit 3e4c6ac should fix this ancient bug.

**Comment by Fanolian** [comment]
Confirm fixed in 3.8.16.11772. Thanks a lot.
