### ISSUE TITLE
New tabs in folders are created at the level of the parent, instead of as a child of the folder

### ISSUE THREAD

**Issue by kilna** [piroor/treestyletab#3049]
## Short description

If I right-click on a folder tab and select "New Tab" I would expect the newly created tab to be under the folder tab. It's at the same level as the existing folder.

## Steps to reproduce

1. Go to URL about:treestyletab-group (which creates a new folder tab)
2. Right-click the newly created folder tab
3. Select "New Tab"

## Expected result

The newly created regular tab should be on the tree as a child of the folder tab on which the context menu "New Tab" was executed.

## Actual result

The newly created tab is on the tree at the same (sibling) level as the context-menu-selected folder tab, rather than as a child. This then requires dragging the newly created tab into the appropriate folder. It is easy to miss that the tab was created at an unexpected level. If a folder tab has a long list of sub-tabs it might require searching through a long list to find and reposition the new tab appropriately.

## Environment

I have reproduced on Windows and Mac

## Notes

Likewise I would expect any other means of creating a new tab if the current page being viewed was a folder tab, so if the current page is a folder called "Foo", then Option-T or File->New Tab would likewise create the tab as a child of the folder "Foo".

**If this is too hard to hook into the existing model for opening new tabs, another option would be a "New Child Tab" regular menu / context menu item.**

**Comment by piroor** [comment]
I'm negative to implement such a special behavior different from Firefox's natural behavior. The group tab feature was originally introduced just to keep tree structure for special cases (when a parent tab is closed, when tabs are opened from a bookmark folder, when tabs are opened from a pinned tab, etc.), so such a special top-level behavior may confuse people who just expect that the context menu item just works like as the one in Firefox's native tab context menu.

Instead I've added a secret behavior for the context menu item on the sidebar (3570a58): middle-click and accel-click on the menu item are treated like same actions on the "New Tab" button in the sidebar. Those actions are already customizable via TST's options, so you can open child tabs for a group tab easily (I agree it is not the best for you and just a workaround.)

And there is another possible solution: setting `browser.tabs.insertAfterCurrent` to `true` via `about:config`.
