### ISSUE TITLE
New Folder Tab option

### ISSUE THREAD

**Issue by kilna** [piroor/treestyletab#3050]
## Short description

I would expect that since folder tabs are now a core feature of TST, that I could create one. 

## Steps to reproduce

1. Look in the TST sidebar menu
2. Pull up a context menu under TST
3. Look under the menu bar

## Expected result

See some option for "New Folder Tab".  Preferably any or all of:

1. Under the TST sidebar menu
2. File menu alongside the "New Tab" option
2. Context menu alongside the "New Tab" option ( preferably positioning the new folder as a subfolder of the parent as per https://github.com/piroor/treestyletab/issues/3049 )

## Actual result

There is no visible way to create a folder tab

## Environment

I see this behavior on my Mac and Windows computers

## Notes

I know I can use the workaround found on Reddit: https://www.reddit.com/r/firefox/comments/9545v4/making_folder_tabs_for_tree_style_tabs_extension/

I know there is a workaround to create a new tab via the URL about:treestyletab-group

This request is to no longer need a workaround.

In a hierarchy-centric organization system I would hope that creating a folder wouldn't require digging into github issues or reddit threads.

**Comment by kilna** [comment]
Also, at the bottom or top of the actual display page for the folder tab, a "New Tab" and perhaps "New Folder Tab" option should be presented here.

**Comment by piroor** [comment]
The group tab feature was originally introduced just to keep tree structure without specific parent tab. So I have no plan to expose it as one of top-level features. I'm worrying that it will confuse the main concept of this project: "manage tabs with tree structure, not just grouping".

Instead I think the sub project "TST More Tree Commands" is a good place to implement such features. Here is an existing feature request waiting to be implemented: https://github.com/piroor/tst-more-tree-commands/issues/3

**Comment by piroor** [comment]
And currently there is a workaround: creating a bookmark with a URL `ext+treestyletab:group`.
