### ISSUE TITLE
set indent for sub tree

### ISSUE THREAD

**Issue by mike-boost** [piroor/treestyletab#3051]
## Short description
I want to add the size of indent, only for the sub-tabs.

![image](https://user-images.githubusercontent.com/69611731/144981475-860f90e3-28d3-4f10-9a7c-e7c97fd64113.png)

## Expected result
add configuration in preferences or workaround,  to set the indent size of the sub tab.

## Actual result
not found any solution

## Environment

 * Platform (OS):  Mac Big sur
 * Version of Firefox:94.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.8.16 (2021.11.11):

**Comment by piroor** [comment]
There is a hidden option to control it: TST Options => Development => All Configs => `baseIndent`.

**Comment by piroor** [comment]
Currently I have no plan to expose the option, to avoid confusing of users from too many options.
