### ISSUE TITLE
Using the sidebar page in a new window has issues when using drag and drop in the "create links or bookmarks" mode

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#3056]
## Short description
A user of my addon [`Tree Style Tab in Separate Window`](https://addons.mozilla.org/firefox/addon/tst-in-separate-window/) reported [an issue](https://github.com/Lej77/tree-style-tab-in-separate-window/issues/13) that they couldn't use drag and drop for tabs inside the opened window since that would always load the dropped tab's URL in that window and leaves the TST Sidebar page.

From my testing a page needs to have the following code in order to prevent such dropped links from being loaded in the dropped tab:
```javascript
window.addEventListener("dragover", function (e) {
    e = e || event;
    e.preventDefault();
}, false);
window.addEventListener("drop", function (e) {
    e = e || event;
    e.preventDefault();
}, false);
```

The code for Tree Style Tab's sidebar does call [`preventDefault` for the `"dragover"` event](https://github.com/piroor/treestyletab/blob/b6231a9d07db8112e9a1a836b9787ad1cf7d7ee4/webextensions/sidebar/drag-and-drop.js#L1037) but it never does so for [the `"drop"` event](https://github.com/piroor/treestyletab/blob/b6231a9d07db8112e9a1a836b9787ad1cf7d7ee4/webextensions/sidebar/drag-and-drop.js#L1246). 

So the question is if that code could be changed to call `event.preventDefault()` or if there is a reason it doesn't do that. If there is a reason then maybe we could open the sidebar page with some extra query parameter that specifies that
it should call `event.preventDefault()`.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open the `ext+treestyletab:tabbar` URL.
 4. Move the tab where you opened the URL to a new window.
    - This makes it easier to drag and drop tabs in the opened page since otherwise clicking on a tab would select it and remove focus from the tab we opened (which would interrupt the drag operation).
 5. Drag and drop a tab while holding the shift key.
     - Make sure to not drop the tab on itself since that usually cancels the drag operation.
     - Drop the tab inside the opened "sidebar" page.
     - The dragged tab must have a URL, so don't use a newtab page or some other Firefox internal page.
     - If you change the default drag and drop settings you might not need to hold the shift key, the important part is to use a drag and drop mode which allows creating bookmarks.

## Expected result
The tab should be moved to where it was dropped.

## Actual result
The URL of the page is changed to the dropped tab's URL. So the dropped tab's page is loaded inside the sidebar page's tab.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 65.0.2 
 * Version (or revision) of Tree Style Tab: 3.8.17

**Comment by piroor** [comment]
Thanks, I missed the case and the commit f90e17e should fix the problem.

**Comment by Lej77** [comment]
Thanks for the fast fix! Just tested the latest build and the issue seems to have been fixed!
