### ISSUE TITLE
Tree page turns into blanck when try to open uBlock Origin settings window from the toolbar

### ISSUE THREAD

**Issue by WhiredPlanck** [piroor/treestyletab#3058]
## Short description
Tree page turns into blanck when try to open uBlock Origin settings window from the toolbar

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install [`uBlock Origin`](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/).
 4. Open the sidebar to let TST show you the tree.
 5. Move cursor to the icon of uBlock Origin and click it to open its settings window.
 

## Expected result
Settings window of uBlock Origin could be opened normally, and nothing should be happened to TST.

## Actual result
Then TST's tree page truns into blanck and crash while uBlock Origin's settings window can not show too.

**P.S.** I have tried other simular addons such as [`Sidebery`](https://addons.mozilla.org/en-US/firefox/addon/sidebery) and experience the same problem.

## Environment

 * Platform (OS): Linux (AOSC OS)
 * Version of Firefox: 95.0 release (64 bit) 
 * Version (or revision) of Tree Style Tab: 3.8.17

**Comment by piroor** [comment]
I've tried with Firefox 95.0.1 (64bit) on Windows 10 + TST 3.8.17 + uBlock Origin 1.39.2 but couldn't reproduce the problem. Is there any difference between my case and yours?:

* On the step 4: I simply open the TST sidebar panel.
  ![image](https://user-images.githubusercontent.com/70062/147109933-9de4f527-55a5-4df2-b0a1-562c8080320a.png)
* On the step 5, I click the uBlock Origin toolbar button and click the gears icon.
  ![image](https://user-images.githubusercontent.com/70062/147110038-ce7aaff0-0dc4-41ea-96e7-52f127fca87d.png)
* I got the uBlock Origin's dashboard as a new tab.
  ![image](https://user-images.githubusercontent.com/70062/147110171-74d1d1ac-0324-4a48-b61b-e815bbe7e113.png)

All my configs of both addons are default.

**Comment by WhiredPlanck** [comment]
Hmm, weird. After I posted this issue, I found that opening uBlock Origin settings window from the tool bar will break tree page even thought I close the sidebar ... I may need a little more time to unearth some clues. But anyway, thank you for answering first ~.

**Comment by WhiredPlanck** [comment]
I have disabled TST and any other simular addons and still found that I cannot open uBlock Origin's settings window. This may be a quirk about uBlock Origin and not TST's or Sidebery's fault ...

**Comment by piroor** [comment]
Firefox works with multiple processes for each purpose. Such a situation can happen if opening uBlock Origin's options page causes crash of the process for addons (shared across multiple addons) on your environment - then I recommend you to try cleanup of uBlock Origin as a workaround: backup all settings of uBlock Origin, uninstall uBlock Origin, restart Firefox, re-install uBlock Origin, and restore settings of uBlock Origin from the backup.

**Comment by WhiredPlanck** [comment]
I refurbished my Firefox finally :joy: And this problem still occurs. I started up Firefox from terminal and found some error infomation: 

![Pic.png](https://mozilla.modular.im/_matrix/media/r0/download/mozilla.org/ab2fed86b82d4cad19506c4f50826afe84064446)

It seems that my Firefox's render processes (or threads I guess) are broken. This may be difficult for us to figure out the root cause ...

**Comment by WGH-** [comment]
FWIW, I have "cannot send/recv" errors all the time (Linux, Firefox 91.4.0esr), so I don't think these errors are meaningful.

**Comment by piroor** [comment]
@WhiredPlanck Hmm, anyway if you still see the problem not only with TST but with Sidebery (or other sidebar addons) also, this should be tracked at uBlockOrigin side.

**Comment by WhiredPlanck** [comment]
> @WhiredPlanck Hmm, anyway if you still see the problem now only with TST but with Sidebery (or other sidebar addons) also, this should be tracked at uBlockOrigin side.

OK, thanks very much!

**Comment by WhiredPlanck** [comment]
> @WhiredPlanck Hmm, anyway if you still see the problem not only with TST but with Sidebery (or other sidebar addons) also, this should be tracked at uBlockOrigin side.

Well, I think I find the cause. I didn't upgrade my Linux system properly and Firefox cannot link to correct libraries, which leads to addons were not working normally. So this is not the fault of any addon, just mine. Anyway, thank you very much again.

**Comment by irvinm** [comment]
@WhiredPlanck will you close this issue?  Thanks.
