### ISSUE TITLE
don't open folder tabs under a fictive folder

### ISSUE THREAD

**Issue by labrute57** [piroor/treestyletab#306]
Hi,

I'm under iceweasel 10.0.5 under debian 7.0 and I can't have to open a bookmark folder under a fictive folder tree.

Even when I ask to tell me what to do, it always open flattly the bookmark folder.

I hope I was enough clear

I'm using version Ver.0.14.2012050301

Bests regards
LALLEMENT Frederic

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
