### ISSUE TITLE
High Contrast appearance text turned white, unreadable [Dark Mode]

### ISSUE THREAD

**Issue by Ligerx** [piroor/treestyletab#3067]
## Short description
High Contrast appearance text turned white, unreadable

## Steps to reproduce
1. set windows to dark mode
2. change TST appearance setting to high contrast

This issue just started today, and I haven't changed any settings. It seems like TST hasn't been updated recently either. It appears to only effect dark mode on windows.

## Expected result
![image](https://user-images.githubusercontent.com/6577974/149044000-c36fd2b7-aaef-4638-88df-c091df92798e.png)

## Actual result
![image](https://user-images.githubusercontent.com/6577974/149043972-ef1a2043-aa35-4c4e-b57f-2f39578b151b.png)

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 96.0
 * Version (or revision) of Tree Style Tab: 3.8.18

**Comment by piroor** [comment]
Confirmed. This looks to be a problem due to something changes on Firefox 96.0.

**Comment by piroor** [comment]
The commit c00307e should fix this.

Very oddly the dark color scheme doesn't affect to the [system color](http://www.iangraham.org/books/xhtml1/appd/update-23feb2000.html) "ThreeDFace" on addon contents. It possibly a minor regression of Firefox itself, so I need to investigate more...

**Comment by Ligerx** [comment]
awesome, thanks for the super quick response.
TST is 100% of the reason why I use firefox, so thank you for continuing to support this awesome plugin

**Comment by piroor** [comment]
Here are screenshots of a HTML including demonstration of CSS system colors. (Left=Firefox 96.0, Right=Firefox 91.5.0ESR)

Colors on the Light mode:
![screenshot](https://user-images.githubusercontent.com/70062/149127301-bbe88a2e-e211-42e5-985e-9ba544e60e9d.png)

Colors on the Dark mode:
![screenshot](https://user-images.githubusercontent.com/70062/149127191-021246ef-3f49-483d-895a-fa0279cefe89.png)

Some [deprecated system colors](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#deprecated_system_color_keywords) especially `ThreeD*` look to be rendered with light colors even if the system color scheme is dark.

**Comment by Ligerx** [comment]
Trying High Contrast mode now, the white on white text is fixed. However it is now styled as dark mode (not sure if this was an intentional change or not). Is there any way to make TST visually in light mode even though my system and FF setting is in dark mode?

**Comment by piroor** [comment]
1750483 - "ThreeDFace" should have enough contrast for "ButtonText" on the dark color scheme mode
https://bugzilla.mozilla.org/show_bug.cgi?id=1750483
I've filed it, but it may become WONTFIX...

**Comment by piroor** [comment]
@Ligerx The "High Contrast" theme actually means "respect the system color scheme", and mainly designed to be combined with the "High Contrast" color scheme of the platform itself (for visually impaired people).  So you may need to redefine all colors manually with custom user styles. There are some possible hints:

https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#restore-old-built-in-themes
https://github.com/piroor/treestyletab/blob/7e9853fb96a01c81ee10edaefcdf775c6dd8d6ab/webextensions/sidebar/styles/photon/photon.css#L13-L32
https://github.com/piroor/treestyletab/blob/7e9853fb96a01c81ee10edaefcdf775c6dd8d6ab/webextensions/sidebar/styles/photon/highcontrast.css#L9-L20

**Comment by Ligerx** [comment]
I guess this is more of a feature request, but I'd like some way to specify if I want to follow the system theme or manually choose light or dark mode.

That said, this is not a huge deal. I like light mode better, but I can get used to dark mode.
