### ISSUE TITLE
[Firefox 98] New favicon for about:config is not applied to TST tab bar

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#3070]
## Short description
In Firefox 98 (current Nightly), new favicons are added to `about:config` and `about:about` by [Bug 1744366 - Add a favicon to about:config and about:about](https://bugzilla.mozilla.org/show_bug.cgi?id=1744366). TST does not automatically apply the new favicon for `about:config`.

## Steps to reproduce

 1. Start Nightly 2022-01-12 onwards with clean profile.
 2. Install TST.
 3. Go to `about:config` and `about:about`.
 4. Check their favicons on TST tab bar.

## Expected result
Similar to `about:about`, `about:config` should show the correct favicon.

## Actual result
![tst favicon](https://user-images.githubusercontent.com/771216/149621899-ae1a5400-3b17-41ab-9dde-02f687f4e8a8.png)

## Environment

 * Platform (OS): Windows 10 21H2
 * Version of Firefox:  Nightly 2022-01-14 (20220114220151) 
 * Version (or revision) of Tree Style Tab:  3.8.19

**Comment by piroor** [comment]
Thanks a lot! afa0c39 should fix this.
