### ISSUE TITLE
When a tab gets focus, expand it's tree and collapse others automatically works when unchecked

### ISSUE THREAD

**Issue by tinsoldat** [piroor/treestyletab#3072]
## Short description
When switching tabs with `Ctrl + Tab` from one tab to a tab that is a root to a collapsed tree, it's tree expands after a delay, even though "When a tab gets focus, expand it's tree and collapse others automatically" option is unchecked. It also collapses all other trees but it's inconsistent. Sometimes the same happens with mouse clicks too but I haven't figured out how to reproduce it.
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Uncheck "When a tab gets focus, expand it's tree and collapse others automatically" in Tree Behavior in addon options.
 4. Switch from one tab to another with `Ctrl + Tab`. If that tab is a root of a collapsed tree, it's tree expands.

## Expected result
Tabs gets selected, it's tree stays collapsed.

## Actual result
Tabs gets selected, it's tree expands, sometimes other trees get collapsed.

## Environment

 * Platform (OS): Windows.
 * Version of Firefox: 95.0.2 but older versions had it too.
 * 
 * Version (or revision) of Tree Style Tab:  3.8.19

**Comment by piroor** [comment]
You need to turn the another option "Don't expand collapsed tree and skip collapsed descendants, while switching focus of tabs via keyboard shortcuts." checked and give a permission. Did you try it?

**Comment by tinsoldat** [comment]
I've tried it too. It temporarily fixes mouse clicks but keyboard shortcuts switching is still the same. The option generally doesn't seem to do anything.

**Comment by piroor** [comment]
TST memorizes the "Ctrl key is pressed" state with a content script injected to and executed on the current tab. It fails on some special pages like `about:***` and privilege sites like `*.mozilla.org`, due to restrictions of Firefox's addon system. (This is the reason why mouse gesture addons are not available on such tabs.) Could you try to start/finish Ctrl-Tab operations on a general website tab like github.com?

**Comment by tinsoldat** [comment]
I've mostly tried on general websites, not special pages. Still same.

**Comment by piroor** [comment]
Hmm, did you mean about long-press of the Ctrl key? TST has a sub option "Expand active collapsed tree when the Tab key is pressed over 800 msec" and is is hidden by default. You can see it with checked "Unlock Expert Options".
![screenshot](https://user-images.githubusercontent.com/70062/149632821-f43e1084-8a81-4653-af39-6de6a5223e53.png)

**Comment by tinsoldat** [comment]
Thank you, turning it off helped. Thought the problem was with both short(<800ms) and long presses.

**Comment by piroor** [comment]
Thank you for confirmation!

Hmm, the sub option works even if the upper level "Don't expand..." option is unchecked but it looks to be confusable as this issue. I think TST should deactivate the long-press behavior on such cases...

**Comment by piroor** [comment]
With the commit 7e9853f, the auto-expand behavior for long-press of the ctrl key is now disabled when Ctrl-Tab handling is not granted.
