### ISSUE TITLE
Function to remove close button permanently

### ISSUE THREAD

**Issue by SHHSSH** [piroor/treestyletab#3075]
https://github.com/piroor/treestyletab/issues/1684

^
I don't believe this is working in 97.0b5 (64-bit) Dev Edition.

I think Firefox has implemented something new in regards to the close button, it sucks because I hadn't seen it for ages and now it's reappeared all of a sudden in the past few months.

Nothing in that issue is currently working.

**Comment by irvinm** [comment]
I don't have any problems with FF97.0b5 (Windows) using this CSS:


```
/* ------------------------------------------------------------ */

/* Works - Hide closebox unless hovering */
/*
   Remove tab closebox unless hovering over the tab
   "#tabbar" is required for TST 3.4.0 and later
   https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#only-show-tab-close-button-on-hover-1448 
*/
#tabbar tab-item:not(:hover) tab-closebox { display: none; }

/* ------------------------------------------------------------ */
```

**Comment by SHHSSH** [comment]
> I don't have any problems with FF97.0b5 (Windows) using this CSS:
> 
> ```
> /* ------------------------------------------------------------ */
> 
> /* Works - Hide closebox unless hovering */
> /*
>    Remove tab closebox unless hovering over the tab
>    "#tabbar" is required for TST 3.4.0 and later
>    https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#only-show-tab-close-button-on-hover-1448 
> */
> #tabbar tab-item:not(:hover) tab-closebox { display: none; }
> 
> /* ------------------------------------------------------------ */
> ```

Thanks, that worked fine, I wonder what went wrong in the past for me.
