### ISSUE TITLE
"Inherit container from current tab" for tabs from outside behaves strangely

### ISSUE THREAD

**Issue by Nadrieril** [piroor/treestyletab#3078]
## Short description

Opening a new tab from outside firefox with "inherit from current tab" option behaves weirdly.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set "New tab from outside firefox: Container: inherit from current tab"
 4. Open a new tab in the "Personal" container
 5. Open "twitter.com" from an external application. In my case, the terminal:
 ```
> firefox -P debug -url https://twitter.com
```

## Expected result

A new tab with "twitter.com" opens in the "Personal" container.

## Actual result

A new tab with "twitter.com" opens and is very quickly replaced with a new blank tab, instead of staying on twitter. This is very weird because it seems to depend on the website.

Works normally:

	  - https://google.com
	  - https://youtube.com
	  - https://en.wikipedia.org/wiki/Main_Page
	  - https://example.com
	  - http://example.com/
	  - http://localhost:5000 (where there is a web server listening for http but not https)

Opens a blank new tab:

	  - https://twitter.com
	  - http://twitter.com
	  - https://twitter.com/wonderb0lt/status/1486440858996117506
	  - http://slkdfjmlskdjf.com (nonexistent)
	  - https://localhost:5000 (where there is a web server listening for http but not https)

I hope you can reproduce because it's very bizarre. This is a clean profile with no other extensions. I deleted all files from the profile and started again just to be sure.

## Environment

 * Platform (OS): NixOS Linux
 * Version of Firefox: 95.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.8.19

**Comment by piroor** [comment]
Curiously this doesn't happen on my main environment Windows 10 but happens on a virtual Ubuntu environment. After a research I've found an odd behavior of the WebExtensions API itself around new tabs opened with URL, and introduced a workaround with the commit 6e9933e. After the change new tabs with URL are correctly reopened with the container and its original URL for me on Ubuntu.

**Comment by Nadrieril** [comment]
Oh phew glad it reproduced. Thanks for the quick fix!
I tested the nightly release and it works!

**Comment by pix0r** [comment]
I'm experiencing this issue in macOS 14.3.1, Firefox 123.0, TST 3.9.22.

Under TST preferences "New Tabs not from Existing Tabs" > "Basic control for New Blanks Tabs", if I set "Container" to either "Inherit from the current tab" (my desired behavior) or "Inherit from the parent tab on the tree", opening external links in Firefox does not work correctly if the frontmost window's active tab has a container. However if the frontmost window's active tab is the default container (or is that considered no container?), it works as expected.

Apologies for the incomplete bug report. I'm happy to follow the steps outlined in [CONTRIBUTING.md](https://github.com/piroor/treestyletab/blob/trunk/CONTRIBUTING.md) but it will take some time as this is my first time reporting an issue. I also wasn't sure if I should create a new issue or piggy-back on this existing issue which seems identical to what I'm seeing.

Thanks!

**Comment by piroor** [comment]
On macOS "tabs from outside (other applications)" detection does not work as expected due to a difference of window behaviors...

**Comment by pix0r** [comment]
> On macOS "tabs from outside (other applications)" detection does not work as expected due to a difference of window behaviors...

That's unfortunate. Are you aware of any possible solutions? Does the macOS tab detection problem already exist as a separate GitHub issue or would it be helpful to create a new one?

**Comment by piroor** [comment]
The root of this restriction is: WebExtesions API does not provide information of a new tab what the trigger is: bookmarks, histories, external apps, the address bar, and so on. Thus TST need to guess the trigger from other information, and currently TST uses "window focus state" to detect tabs from external apps. On Windows and Linux all Firefox windows are unfocused when other app has a focus, so TST can guess a tab is opened from other apps if no Firefox window has focus when a new tab is opened. But on macOS a Firefox window gets focused at first and a new tab is opened, when it is requested from other apps. I can't imagine how to bypass this restriction...
