### ISSUE TITLE
Folder name for <Bookmark this tree> breaks when dealing with quotes (")

### ISSUE THREAD

**Issue by m2habert** [piroor/treestyletab#3079]
## Short description

I want to use searches as tree parent (= bookmark folder name) most of, if not all, the time. 
Coincidentally, quoted terms happen to be used in searches all the time.

thus the bug : placeholder `%TITLE%` breaks when reaching the first `"` (quote)
 

## Steps to reproduce
I configured "folder name" as:
`%TITLE%,,[%SHORT_YEAR%%MONTH%.%DATE%]`

given the search : foo bar "qux barfoo" 
 
it will imply in web page titles like:
    foo bar "qux barfoo" - Google Search
or
    foo bar "qux barfoo" at DuckDuckGo

Whenever I try to "bookmark this tree" (through the shortcut) with such pages,
folder name returned in both cases is 

    foo bar \

## Expected result
...when expected result would be:

    foo bar "qux barfoo" at DuckDuckGo,,[2201.27]
or:

    foo bar "qux barfoo" - Google Search,,[2201.27]

## Environment

 * Platform (OS): macOS
 * Version of Firefox:
                    78.15.0
                    Firefox ESR
 * Version (or revision) of Tree Style Tab: 3.8.19

**Comment by piroor** [comment]
Thanks, I missed this. The commit b99072e should fix it.

**Comment by irvinm** [comment]
@m2habert can you confirm this issue is resolved and close this item?

**Comment by m2habert** [comment]
> @m2habert can you confirm this issue is resolved and close this item?

ooooooops, sorry, I've just saw your message.

Yes, issue is resolved.
