### ISSUE TITLE
All tabs removed when Firefox updates on Win10

### ISSUE THREAD

**Issue by pbhj** [piroor/treestyletab#3080]
## Short description
A few times now on Win10, after an update that Firefox has performed for itself, Firefox re-opens but without any of the tab tree that it had when it closed. Sync tabs from other devices are available, but the tab tree for the current session is empty. Currently, Firefox 96.0.3; I'm afraid I can't say what version it was on, nor what version this happened to in the past (I'm not really a Windows native, where are the logs for this?).

## Steps to reproduce
Leave Firefox to update to version 96.0.3 with TST 3.8.19 installed.

I'm afraid I can't create a situation where there is  an update of this type, I don't think.

## Expected result
TST normally after an update opens the same tab tree that was in use prior to the update.

## Actual result
TST's tab tree (and all regular tabs) is empty except for the newtab tab. I usually have at least 40+ tabs open, some tree branches were collapsed.

## Environment
 * Platform (OS): Win10 21H1 build 19043
 * Version of Firefox: 96.0.3
 * Version (or revision) of Tree Style Tab: 3.8.19

Apologies I can't give more detail.

I did have Tab Group Switch installed but not enabled for a long time.

Enabled extensions: Facebook Container, Firefox Multi-Account Containers, LanguageTool, HTTPS Everywhere, Tree Style Tab, uBlock Origin.

**Comment by irvinm** [comment]
@pbhj I don't think this is related to TST at all.  I'm assuming that when this event occurs, that your normal tabs are not present, right?  This looks like it is just a Firefox issue.  TST does not have anything to do with session management, but just displays the tabs in the browser.  (I bet you would see the same behavior if you uninstalled TST)

**Comment by piroor** [comment]
@pbhj As @irvinm mentioned, it looks not a problem of TST itself. I don't know why but sometimes Firefox fails to save/restore last session. If you lucky you may restore lost tabs with:

* The application menu => History => Restore previous session
* The application menu => History => Recently Closed Windows
