### ISSUE TITLE
tab indent level in extra style

### ISSUE THREAD

**Issue by liemlb** [piroor/treestyletab#3081]
## Short description
Is there any way to set indent levels in extra style?
I want to set indent level to 0 then when doing mouse hover set to -1

## Expected result
indent level is adjustable when mouse hover event occurred
## Environment

 * Platform (OS): Windows10
 * Version of Firefox: 96.0.3 
 * Version (or revision) of Tree Style Tab: 3.8.19

**Comment by irvinm** [comment]
If you look at the CSS code here ([link](https://github.com/piroor/treestyletab/discussions/2960#discussioncomment-974339)), that might be one way for you to handle this ... or at least a starting point.

**Comment by irvinm** [comment]
@liemlb is there anything more to discuss here?  Can you close this item?

**Comment by liemlb** [comment]
Ok, but recently I can not find time to try your suggestion yet. So maybe I will comeback later after doing some test
