### ISSUE TITLE
Tab switch becomes laggy after opened for a long time

### ISSUE THREAD

**Issue by gzqx** [piroor/treestyletab#3082]
## Short description
After the firefox window is opened for like 12 hours, switching tabs via Tree style sidebar becomes really laggy. However, switching by the origin tab bar of firefox is still responsive.
## Steps to reproduce

It reproduces on both my macbook and two fedora plasma 35 (also have the issue when in 34 version).

## Expected result
Responsive as origin tab bar.

## Actual result
Becomes laggy.

## Environment

 * Platform (OS):  Fedora Plasma 34,35 and mac OS X 15 Catalina
 * Version of Firefox: 96.0 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.8.19

**Comment by irvinm** [comment]
@gzqx you might want to try to capture 2 performance profiles for this issue.  ([link](https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-collect-a-performance-profile))  Do it once when you first start the browser and then again after you are seeing the degradation.  This will give information about where time is being spent.  ([Example](https://github.com/piroor/treestyletab/issues/3057#issuecomment-1025331366))

**Comment by piroor** [comment]
I ordinary run Firefox without restarting for a long time over some days, and I don't see this problem on my environment (Firefox 98.0.2 on Windows 10) for now...

@gzqx Do you use any other addon together? Firefox uses just one process for addons, so this problem can happen even if TST does not use CPU but other addons use CPU. Please try disabling all other addons and confirm to reproduce the problem.
