### ISSUE TITLE
New windows are created randomly when clicking items on TST

### ISSUE THREAD

**Issue by mzso** [piroor/treestyletab#3087]
## Short description
Ever since upgrading FF to 97 and TST to 3.8.19 I get unwanted new windows opened.
## Steps to reproduce

Apparently mere clicking is enough, if my finger slips a few pixels. But this was not enough to tear away tabs and create new windows previously. But now it happened multiple times.
I can only reproduce it after several tries, by clicking the same item and moving the cursor up a few pixels at the same time, and in around 10-20 tries it happens.

## Expected result
Tab merely selected

## Actual result
New Window with the tab.

## Environment

 * Platform (OS): Win 10
 * Version of Firefox: 97.0 devedition
 * Version (or revision) of Tree Style Tab: 3.8.19

**Comment by piroor** [comment]
I've confirmed this problem on Nightly 99.0a1 on Windows 10, and I've realized that this is triggered by a bug of Firefox itself. TST is designed to detach tabs with "dragend" events based on their coordinates but Firefox wrongly reports 0,0 as the coordinates. As the result TST detects such a dragend event as happened enough far from the dragstart position. This is the reason why TST detaches tabs unexpectedly. Hmm...

**Comment by piroor** [comment]
After more investigation I've realized what is the root problem.
Due to [something security fix](https://bugzilla.mozilla.org/show_bug.cgi?id=1317873) (I couldn't see the details - it is flagged as a security bug), [Firefox now disallows to set any drag data with type prefixed with "x-moz-"](https://searchfox.org/mozilla-central/rev/2a0b0ababd4541ecffb74cbe0820a9d0a25da636/dom/events/DataTransfer.cpp#571). The change was introduced at 2021-12-15. TST uses a custom data type `application/x-moz-drag-data` so the operation is blocked and it breaks dragstart handling.

I've introduced some changes: c1a540f9b5c4460c818d535b29393250a5fb4f05 and 05c6ff28cc2217ff75ee57682ab74312c28d50ce. They should fix this issue.

**Comment by mzso** [comment]
> After more investigation I've realized what is the root problem. Due to [something security fix](https://bugzilla.mozilla.org/show_bug.cgi?id=1317873) (I couldn't see the details - it is flagged as a security bug), [Firefox now disallows to set any drag data with type prefixed with "x-moz-"](https://searchfox.org/mozilla-central/rev/2a0b0ababd4541ecffb74cbe0820a9d0a25da636/dom/events/DataTransfer.cpp#571). The change was introduced at 2021-12-15. TST uses a custom data type `application/x-moz-drag-data` so the operation is blocked and it breaks dragstart handling.
> 
> I've introduced some changes: [c1a540f](https://github.com/piroor/treestyletab/commit/c1a540f9b5c4460c818d535b29393250a5fb4f05) and [05c6ff2](https://github.com/piroor/treestyletab/commit/05c6ff28cc2217ff75ee57682ab74312c28d50ce). They should fix this issue.

Great!
Can you make a (beta?) release, so I can try it? It's pretty frustrating sometimes.

**Comment by piroor** [comment]
I've released 3.8.20 and it is now waiting for reviewed.

**Comment by mzso** [comment]
[**@piroor**](https://github.com/piroor) commented on [2022. febr. 8. 16:06 CET](https://github.com/piroor/treestyletab/issues/3087#issuecomment-1032709638 "2022-02-08T15:06:08Z - Replied by Github Reply Comments"):
> I've released 3.8.20 and it is now waiting for reviewed.

Out of curiosity: how come you stopped providing builds on github?

**Comment by piroor** [comment]
It is still available, for example: https://github.com/piroor/treestyletab/actions/runs/1812639133#artifacts ([You need to be a logged-in user on GitHub to download artifacts.](https://github.community/t/public-read-access-to-actions-artifacts/17363/11))

**Comment by mzso** [comment]
@piroor 
Thanks. Never would have found it.  I don't even know what that part of Github is about.

**Comment by mzso** [comment]
It seems to work fine now.

**Comment by Elaborendum** [comment]
I'm on FF 101.0.1 using TST 3.8.24, and I still experience this issue from time to time.

**Comment by piroor** [comment]
@Elaborendum Please see #3138.

**Comment by mzso** [comment]
For a long time for me it wasn't an issue. But recently I upgraded to FF109 and latest TST. And it came back.  (I actually upgraded straight from FF97)
