### ISSUE TITLE
[feature request] Expand all tree by default

### ISSUE THREAD

**Issue by huipengcheng** [piroor/treestyletab#3088]
For me, I don't want to expand or collapse trees by clicking. So how to set to expand all trees by default?

**Comment by irvinm** [comment]
I think you just need to disable the options under tree management for automatically collapsing trees in certain circumstances.  I manage all my tree states myself.  (You use the right-click "expand all" command to get to your starting point)

![image](https://user-images.githubusercontent.com/979729/153428606-59023bfe-d9c1-47ff-9b98-0e82104523f3.png)

**Comment by huipengcheng** [comment]
I got it, thank you so much.
