### ISSUE TITLE
How do you change the indentation/margin of child tabs?

### ISSUE THREAD

**Issue by georgeabr** [piroor/treestyletab#3090]
I am using TST on linux, but cannot find the setting (css or know in addon settings) to change the pixels taken by child tabs.

**Comment by irvinm** [comment]
https://github.com/piroor/treestyletab/issues/3081

**Comment by georgeabr** [comment]
Thanks for your help, @irvinm.
For each level of indent of child tabs, manually add a _tab-item_ entry.
```
tab-item[data-level][data-level="1"] tab-item-substance {
  margin-left: 0px !important;
}
tab-item[data-level][data-level="2"] tab-item-substance {
  margin-left: 6px !important;
}
tab-item[data-level][data-level="3"] tab-item-substance {
  margin-left: 10px !important;
}
```

**Comment by irvinm** [comment]
You are welcome.  If this works for you, can you close this item?  Thanks.
