### ISSUE TITLE
[feature request] Copy tab urls

### ISSUE THREAD

**Issue by CodedNil** [piroor/treestyletab#3093]
## Short description
Would it be possible to implement a feature where in the right click context menu for tabs/multiple selected, it lists an option to copy selected tab urls to clipboard.

**Comment by irvinm** [comment]
@CodedNil just as an FYI, selecting multiple tabs is pretty much standard in Firefox now and @piroor has already implemented this feature in a helper addon here:  https://addons.mozilla.org/en-US/firefox/addon/copy-selected-tabs-to-clipboar/

**Comment by CodedNil** [comment]
> @CodedNil just as an FYI, selecting multiple tabs is pretty much standard in Firefox now and @piroor has already implemented this feature in a helper addon here: https://addons.mozilla.org/en-US/firefox/addon/copy-selected-tabs-to-clipboar/

Brilliant, thank you.
