### ISSUE TITLE
Send tab to another device does not work

### ISSUE THREAD

**Issue by DoS007** [piroor/treestyletab#3095]
**Describe the bug**
Firefox allows to send tabs to other devices that shrae the same firefox sync account. This does not work in treestyletab.

**To Reproduce**
1. Login into your firefox account on the desktop browser and another desktop or mobile firefox browser.
2. On desktop browser using treestyletab right click on a tab in treestyletab and try sending. (this does not work)

![grafik](https://user-images.githubusercontent.com/11618958/157241972-b059e336-0cf8-4927-a624-b5f2944af3d4.png)

**Browser and Vimium version**

If you're using Chrome, include the Chrome and OSS version found at chrome://version. Also include the Vimium version found at chrome://extensions.

Name 	Firefox
Version 	97.0.2
Build-ID 	20220304162637

(should be normal "release")

Vimium 3.8.21

(If you're using Firefox, report the Firefox and OS version found at about:support. Also include the Vimium version found at about:addons.)

**Important to say / or what i should see** 
Sending using the tabs in treestyletab! Not the native actuals tabs in tabbar (which i don't see anyway because i configured userChrome.css because i use treestyletab as my main tab manager). I tested with native tabs (deleted my userChrome.css temporarly) and there i said what i should see:
![grafik](https://user-images.githubusercontent.com/11618958/157243573-7d553663-bbaf-4986-92f5-0213ae4a5615.png)

**Comment by piroor** [comment]
It is a known and unsolvable problem due to Firefox's restriction. See the FAQ topic ""Send Tab/Tree to Device" does not work" under the section "Troubles, unexpected behaviors": https://github.com/piroor/treestyletab/blob/trunk/README.md#troubles-unexpected-behaviors

**Comment by DoS007** [comment]
@piroor thanks, for your response 😃
