### ISSUE TITLE
Scale height of "Close tabs?" dialog with number of listed tabs

### ISSUE THREAD

**Issue by jmbreuer** [piroor/treestyletab#3100]
## Short description

Enhancement Request: The height of the "Close tabs?" confirmation dialog should scale (within reason) to allow at-a-glance overview of both the number and the specific list of tabs to be closed.

In LibreWolf, the width of the confirmation dialog could also be chosen more optimally; but that is quite probably due to their anti-fingerprinting technology and thus a completely different issue.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Turn on TST preferences "Warn me when I attempt to close multiple tabs", "List closing tabs in the confirmation dialog"
 4. Open a number of tabs, say, something like ten to forty
 5. Use any "Close Multiple Tabs" function, e.g. "Close Tabs to the Bottom", "Close Other Tabs" or (when the corresponding preference is also enabled) clicking on the close icon of a tab; in a way that closes a larger number (say, again, on the order of ten to forty) tabs at once

A confirmation dialog listing the tabs to be closed shows up.

## Expected result

The dialog height should scale with the number of tabs being closed, allowing at-a-glance overview as well as an intuitive grasp of "what and how much am I about to close?". Overflow scrolling should only be required when a reasonable portion of vertical screen space - and/or limited by the height of the current browser window perhaps - is exhausted.

## Actual result

The dialog is scaled to show about five lines of list content. To see the whole list one has to either resize the dialog or scroll through the list in what feels like a keyhole:

![Extension: (Tree Style Tab) - Close tabs? — Mozilla Firefox_001](https://user-images.githubusercontent.com/1792037/159942085-21b81b39-a366-44fb-a01b-dbef12cdfc0e.png)

## Environment

 * Platform (OS): Linux
 * Version of Firefox: Firefox 91.6.1, also affects LibreWolf 97.0.2-1 
 * Version (or revision) of Tree Style Tab: 3.8.21

**Comment by piroor** [comment]
Inspired by your request, I've introduced more codes to resize and reposition the dialog more intelligently: maximized but smaller than the owner window, and always visible inside the active screen. Thanks!

![image](https://user-images.githubusercontent.com/70062/160855207-03b2305d-121c-43c0-93ae-22e6bcbfacf3.png)
