### ISSUE TITLE
Detaching a tab creates a window in wrong position

### ISSUE THREAD

**Issue by ATechnocratis** [piroor/treestyletab#3103]
## Short description
Dragging a tab to create a new window moves it further to the right when sidebar is on the right side.
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Move sidebar to the right side.
 4. Drag any tab to detach

## Expected result

A new window is created on screen, with the top left corner on the position (x , y) where you dragged the tab.

## Actual result

A new window is created on the position where you dragged  the tab plus an offset in x axis (probably the firefox window width) .

Detaching a tab from a maximized window, creates a window off-screen which you can't see and have to maximize from taskbar to bring into view.

## Environment

 * Platform (OS): Windows 10 64bit
 * Version of Firefox:  99.0.1
 * Version (or revision) of Tree Style Tab: 3.8.21

**Comment by ATechnocratis** [comment]
Testing on Firefox version 98 everything is working fine so it only happens in 99. 

Seems like having the sidebar on the left and detaching a tab is also bugged.

**Comment by ATechnocratis** [comment]
Seems like inner width of the window ( window width - sidebar width) is added to the x position.

Replacing` event.screenX ` and `event.screenY` with `event.clientX `and  `event.clientY` at `BackgroundConnection.sendMessage` in  `function onDragEnd(event) ` at the  `sidebar\drag-and-drop.js`  is a possibly fix.

**Comment by piroor** [comment]
It looks due to a bug of Firefox itself. TST tries to open a new browser window based on `screenX` and `screenY` of the `dragend` event. When I drop a tab at top-left edge the coordinates should be "0,0". However when the sidebar is placed at right side, a `dragend` event for top-left edge of the screen has an unexpected coordinates like "843,23" - it still should be "0,0" regardless of whether which position the sidebar is placed at.

**Comment by piroor** [comment]
I may fixup the wrong coordinates only when you use a right side sidebar, but sadly it is impossible that an addon knows which side the sidebar is really placed at. TST tries to detect it but the detection is not stable...

**Comment by ATechnocratis** [comment]
Another consequence of this, is that the option to disable tab detaching when dropping near the sidebar, is not working. As a result clicking on a tab and accidentally dragging it a little will detach it.

**Comment by piroor** [comment]
I've understood that this happens globally on Firefox 99 and later. The bug report I've filed: [1767165 - Wrong coordinates of dragend event in a subframe](https://bugzilla.mozilla.org/show_bug.cgi?id=1767165)

The workaround d1d65c9a1cdf35c9c88123f29b23748b0151153e should solve this problem. I think I'll have to deactivate this hack on a future version of Firefox which contains a fix of the bug.

**Comment by irvinm** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1767165 is marked as resolved in FF102.
