### ISSUE TITLE
[feature request] Sort tree by order of last used 

### ISSUE THREAD

**Issue by bnichs** [piroor/treestyletab#3106]
When trying to use an extension like https://addons.mozilla.org/en-US/firefox/addon/sort-tabs-advanced/ to accomplish this, the tree is collapsed in the sort. I doubt their addon knows how to deal with trees of tabs but I figure it shouldn't be that bad on the TST side of things given that similar logic is used in https://addons.mozilla.org/en-US/firefox/addon/tst-fade-old-tabs/. Would just need the recent time needs to be included in the sort order. 

Thanks! 

## Environment

 * Platform (OS): Linux version 5.11.0-49-generic (buildd@lcy02-amd64-054) (gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0, GNU ld (GNU Binutils for Ubuntu) 2.36.1) #55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022
 * Version of Firefox: 96.0 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.8.21

**Comment by piroor** [comment]
The feature is out of scope of this TST project, instead it should be done by a helper addon like [TST More Tree Commands](https://github.com/piroor/tst-more-tree-commands) or something new addon for it.

**Comment by piroor** [comment]
Or, suggesting to improve compatibility with TST to https://addons.mozilla.org/en-US/firefox/addon/sort-tabs-advanced/ also looks to be a good alternative approach.
