### ISSUE TITLE
High CPU usage and freeze when mouse over tab

### ISSUE THREAD

**Issue by steelywing** [piroor/treestyletab#3111]
## Short description

High CPU usage and freeze when mouse over tab

**Only happen when**
- Sidebar on right side
- The tab title too long, and tooltip of title appear

Note
- Not only in unloaded tab
- TST left/right option does not affect
- Also happen on [Sidebery add-on](https://addons.mozilla.org/en-US/firefox/addon/sidebery/)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a tab with [long title](https://www.mozilla.org/en-US/firefox/)
 4. Open Windows Task Manager
 5. Move sidebar to right side
 6. Mouse over the tab and stop moving mouse (wait the title tooltip)
 7. The CPU will be very high and sometimes Firefox freeze
 8. Move mouse to outside of TST will resume normal

## Environment

Windows 10, Firefox after 99

I can reproduce on 2 PC, so I think this is not display driver issue

~May be relate to #2931 #2904~ (Confirmed only trigger on Firefox version >=99)

**Comment by steelywing** [comment]
And weird, I also have "Auto Tab Discard" add-on, when mouse over the tab that is unloaded by "Auto Tab Discard" , it will not use high CPU.

**Comment by steelywing** [comment]
I think this is Firefox issue, does anyone can help to reproduce this issue for report to mozilla?

## Update

I created a [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1765713) to Firefox

**Comment by Qwerty-Space** [comment]
I am also having this issue, except sometimes it won't unfreeze.

**Comment by irvinm** [comment]
Looks like they have said this will be resolved in Firefox 101.  Can someone try this in nightly to see if it works now?

**Comment by reinerblock** [comment]
I'm using Waterfox and since version 3.8.22 the WF/FF hangs and the private bytes of the memory is in the clouds. I just had to terminate the process because the memory was at about 43 GB (!).

Now I'm back to version 3.8.21, and it's working just fine again.

Another hint that something is buggy: The startup of WF/FF took with v3.8.22 significantly longer.

**Comment by steelywing** [comment]
Firefox v100 has fixed this issue
