### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by singhke** [piroor/treestyletab#3117]
Need to make this app compatible for Firefox mobile Android app

#1716

**Comment by irvinm** [comment]
@singhke, nothing has changed to date on this.  Sidebar is still not supported on Android, so there is nothing that can be done at this point.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sidebarAction

**Comment by irvinm** [comment]
@piroor can we close this one?  Maybe add an entry to the FAQ about mobile support but that it isn't possible until Firefox adds support for the sidebar ... maybe reference the URL above for people to check?

**Comment by piroor** [comment]
@irvinm Thanks, I've add a FAQ topic about this.

@singhke As described at the FAQ https://github.com/piroor/treestyletab/blob/trunk/README.md#other-browsers-support TST won't support Firefox Android. I leave this for now because I may reconsider to support Firefox Mobile if those blockers go away.
