### ISSUE TITLE
tab-mouseover event no longer delivered to other add-on after re-opening sidebar

### ISSUE THREAD

**Issue by klemens** [piroor/treestyletab#3118]
## Short description

After re-opening the TST sidebar, my extension [TST Hoverswitch](https://github.com/klemens/ff-tst-hoverswitch) stops working. This is because the `tab-mouseover` event is no longer delivered.

I am not quite sure since when this happens. Some users reported this problem quite some time ago, but I could never reproduce it. Since a few weeks (?) I am experiencing this issue myself and can now reproduce it 100% of the time. It might be timing-related, see below.

## Steps to reproduce

1. Start Firefox with a clean profile
2. Install TST (3.8.23)
3. Install the debug extension provided below
4. Open console for the debug extension and check that you receive `tab-mouseover` and `tab-mouseout` events
5. Close the TST sidebar and reopen it (e.g. with F1)
6. Check again the console of the debug extension

See also this short screen recording: https://user-images.githubusercontent.com/813206/167317176-74467c82-2aea-42f2-9883-16e2046c0eda.mp4

## Expected result

We still see the `tab-mouseover` and `tab-mouseout` events (and maybe a `ready`-event?).

## Actual result

We only see `tab-mouseout` events and we also do not see any ready event.

## Further observations

* When opening the debugger for TST and setting a breakpoint to https://github.com/piroor/treestyletab/blob/d5b312793cc2295c12ca04ebce001d3b0fa568f2/webextensions/sidebar/mouse-event-listener.js#L104 and then just continuing when it is hit after re-opening the TST sidebar, it works as expected (I see both mouse events again). So maybe this is timing-sensitive?
* I never see any `ready` events, not sure if this is expected.

## Environment

 * Platform (OS): Arch Linux (as of 2022-05-08)
 * Version of Firefox: 100.0, but could also reproduce this with 98
 * Version (or revision) of Tree Style Tab: 3.8.23

## Debug extension

```json
{
    "manifest_version": 2,
    "name": "TST Debug extension",
    "version": "0.1.0",

    "developer": {
        "name": "Klemens Schölhorn",
        "url": "https://klemens.schoelhorn.eu/"
    },

    "description": "Debug TST",

    "applications": {
        "gecko": {
            "id": "tst-debug@klemens.io"
        }
    },

    "background": {
        "scripts": [
            "background.js"
        ]
    }
}
```

```javascript
"use strict";

const TST_ID = "treestyletab@piro.sakura.ne.jp";

async function registerToTST() {
    try {
        let result = await browser.runtime.sendMessage(TST_ID, {
            type: "register-self",
            name: browser.i18n.getMessage('extensionName'),
            listeningTypes: ["ready", "wait-for-shutdown", "tab-mouseover", "tab-mouseout"]
        });
        console.log("Registered:", result);
    } catch(e) {
        // Could not register
        console.log("Could not register to TST:", e);
        return false;
    }

    return true;
}

async function handleTSTMessage(message, sender) {
    console.log(sender.id, message.type);

    if(sender.id == TST_ID) {
        switch (message.type) {
            case "ready":
                registerToTST();
                break;
    
            case 'wait-for-shutdown':
                return new Promise(() => {});
        }    
    }
}

browser.runtime.onMessageExternal.addListener(handleTSTMessage);
registerToTST();
```

**Comment by piroor** [comment]
I couldn't reproduce this on Firefox 101 on Windows 10 but successfully reproduced on Firefox 100 on Ubuntu 21.04. It may be a platform specific issue.

**Comment by piroor** [comment]
After some research I've realized that helper addons are detected after the sidebar page is initialized on Linux. The commit 3f16290 fixes this. Thank you for detailed, helpful report!

**Comment by klemens** [comment]
I can confirm that 3f162903fdbca30cc030c1dc5b1226e1d8fe2054 fixes the issue for me, thank you very much for looking into this!
