### ISSUE TITLE
is there a way to save custom values for each tab  when saving a session ? 

### ISSUE THREAD

**Issue by Ulf3000** [piroor/treestyletab#3119]
what the title says. 

i need to save two custom values(a base64 image and a hex color value)  for each tab together with the session and of course reload them when a session is restored.

**Comment by irvinm** [comment]
Any addon can use browser.sessions.getTabValue() and browser.sessions.setTabValue() to store information for a tab and then Firefox would manage the session aspects of it.  TST has nothing to do with session management and what you want to do is probably best done as a separate addon.  You could, of course, store this information in a lot of different ways.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sessions/getTabValue

**Comment by piroor** [comment]
I close this because this looks to be a general question about usage of WebExtensions APIs. (This is the tracker of issues about TST.)
