### ISSUE TITLE
TST performance

### ISSUE THREAD

**Issue by wsmwk** [piroor/treestyletab#3121]
Energy Impact, as reported by about:performance, is high for TST

Just normal FIrefox usage.  TST energy impact has been high for me for years.  Although I do have a couple thousand tabs. I think it happens even for low number of tabs. 

Profile https://share.firefox.dev/3yrII6V.  This is with several settings  set to 86400000 - heartbeatInterval, connectionTimeoutDelay and suppressGapFromShownOrHiddenToolbarInterval according to issue #2973 

Is there a way for me to better measure the impact of TST? 

## Environment

 * Platform (OS): macOS 12.1
 * Version of Firefox: 100.0b3 
 * Version (or revision) of Tree Style Tab: 3.8.23
 
<img width="970" alt="image" src="https://user-images.githubusercontent.com/216903/167914714-25bc5528-cc74-4f4d-b5f4-15166058df8d.png">

**Comment by wsmwk** [comment]
So far, AFTER restarting Firefox after setting the three values above, TST is no longer at the top of about:performance.  

I am surprised not more users report at problem, like issue #2973

**Comment by irvinm** [comment]
@wsmwk I don't think "thousands of tabs" is a common means of using Firefox.  However, having said that, I do run around 500 tabs (with lots of other addons) and don't see the energy impact of TST even as high as what you are showing and I am using the standard values for those 3 options.  I am also using a fairly old machine (i7-4790k) with a good amount of ram (32GB).  I couldn't get the energy impact any higher than like (5) but it was usually between (1-3) while doing anything.

@piroor is there anything more you wanted to add to this one or anything jump out at you from the profile report?  Can you label this item?

**Comment by piroor** [comment]
I couldn't reproduce this on my environment.

@wsmwk Please inspect the minimum conditions to reproduce the problem on other environments (or other new profiles) also,  when you see this problem again. I leave this open for now until the bot closes this as expired.
