### ISSUE TITLE
Spaces in folder and sub-folder tabs displayed as '+' after moving tab

### ISSUE THREAD

**Issue by manyfew** [piroor/treestyletab#3127]
## Short description

As per the title, folder and sub-folder tabs whose names contain spaces get corrupted after dragging the folder to a different position in the tree. Here is a short video screen capture:

![TST group dragging problem](https://user-images.githubusercontent.com/11704566/168437293-09bc08e5-a8e4-46a8-aac1-83f719e51cb1.gif)

## Steps to reproduce

1. Open any website to ensure there is at least one tab open (e.g. "google.com").
2. Open a new empty tab.
3. Type "ext+treestyletab:group" in the address bar and hit Enter to create a new folder tab. The new folder tab should appear underneath the tab opened at step 1 (this may vary depending on your preferences but in this example we assume the group tab is created under the previously active tab).
4. Rename the folder tab to "My new folder tab", the key thing being that there should be at least one space in the name.
5. Use the mouse to drag the folder tab from below the "google.com" tab to above the "google.com" tab.

**Observed result:** The folder tab name changes to "My+new+folder+tab", that is, all spaces have automatically been replaced with '+', but only in the side bar.
**Expected result:** Folder tab name should not change.

6. Rename the folder tab to "My new folder ta" (just delete the last character)

**Observed result:** After changing the folder tab name, the '+' characters change back to spaces.
**Expected result:** No expectation because the starting state was already incorrect.

7. Rename the folder tab to "My new folder tab" again.

**Observed and expected result:** Space characters don't change to '+'.

8. Drag folder tab again as we did at step 5. 

**Observed result:** Spaces are, again, replaced with '+'.
**Expected result:** Folder tab name should not change.

**NOTE:** Spaces in sub-folder names also change to '+' when the parent folder is moved.

## Environment

 * Platform (OS): Windows 10 Professional 64-bit Windows 10 Pro 64-bit v20H2 Build 19042.1586
 * Firefox version: 91.0 (64-bit)
 * Tree Style Tab version: 3.8.23 (May 2, 2022)

May I add, this is my favorite and most useful Firefox add-on. Thank you.

**Comment by irvinm** [comment]
Interesting ... I tried and see the same thing.

There does seem to be a quick workaround ... just reload the tab and the "+" go back to spaces.  In addition, once the spaces return, you can move the tab around without any problem.  It just seems to be right after changing the title and moving the tab.

**Comment by manyfew** [comment]
> Interesting ... I tried and see the same thing.
> 
> There does seem to be a quick workaround ... just reload the tab and the "+" go back to spaces. In addition, once the spaces return, you can move the tab around without any problem. It just seems to be right after changing the title and moving the tab.

Yep, I noticed after posting this that reloading the tab got rid of the "+", but I hadn't noticed the tab was completely immune to this bug after reloading it, so thanks for that! Hopefully this gets fixed anyway.

**Comment by piroor** [comment]
Thanks I missed this. The commit fa9a98c should fix it.
