### ISSUE TITLE
Empty preferences and empty list of tabs in FF100 Fedora 36

### ISSUE THREAD

**Issue by Yenya** [piroor/treestyletab#3128]
## Short description

Hello, after upgrade to Fedora 36, the list of tabs in my session is empty, even though the original (horizontal) list of tabs(*) contains the tabs. Also the Preferences page of TST is empty.

(*) I usually hide the horizontal list of tabs in userChrome.css, but I commented out this settings, so the original list of tabs is visible.

## Steps to reproduce

Firstly, I cannot reproduce it on all of my machines - it works on my laptop (also FF100, Fedora 36, TST 3.8.23) as expected. On the desktop workstation where it does not work, I tried also a clean new FF profile and even different Linux users, and I can reproduce it there reliably.

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open some more tabs. 
 4. Open about:addons, select Extensions -> TST -> Preferences

## Expected result

There should be some preferences to modify in the about:addons tab, and there should be a vertical list of tabs in the sidebar.

## Actual result

The sidebar is empty, and the preferences area is also empty.

## Environment

 * Platform (OS): Fedora Linux 36, x86_64
 * Version of Firefox: 100.0 (64bit)
 * Version (or revision) of Tree Style Tab: 3.8.23

Here is the screenshot of the TST preferences, with empty sidebar and Help->About Firefox window:

![tst](https://user-images.githubusercontent.com/1055951/168526324-28165f9c-3f22-47b3-8858-f4df6edf8298.png)

The problem appeared immediately after upgrade from Fedora 35 to Fedora 36. However, I have upgraded all of my machines the same way, and on my laptop, for example, I cannot see this problem.

**Comment by irvinm** [comment]
@Yenya you might want to read this over:  https://github.com/piroor/treestyletab/issues/2888

**Comment by Yenya** [comment]
@irvinm - OK, thanks. Should we close this issue and reopen #2888?

**Comment by irvinm** [comment]
@Yenya I would leave this one open and let's see what @piroor wants to do.

**Comment by Allda** [comment]
Hey all, I also updated to Fedora 36 with Firefox 100 recently and I am facing the same issue. I tried to run the extension with a clean profile but the issue still persist.

After I lost access to the sidebar with all tabs I realized how important the extension is for me. Do you think there is any short term workaround that I could apply to fix this issue.

Thank you everyone for any help!

**Comment by irvinm** [comment]
@Yenya \ @Allda are you guys still seeing this?  I see there were some code changes after your comments to try to avoid this.

**Comment by piroor** [comment]
I've tried TST 3.8.24 on Firefox 100 on Fedora 36, but I couldn't reproduce this problem. Something errors may be reported in the debugger, thus please copy and paste that here.
https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs

**Comment by Yenya** [comment]
Hello,

Firefox 102.0 on Fedora 36 on a system which previously been affected by this issue, now works.

**Comment by Walker-00** [comment]
For Me it's happen by the `FoxFilter` addon after I disabled, everything work fine.

**Comment by piroor** [comment]
Thanks! I've confirmed [FoxFilter](https://addons.mozilla.org/firefox/addon/foxfilter/) triggers this problem. I don't think all reporters used this addon, but it need to be confirmed if similar problem happens.
