### ISSUE TITLE
Missing plain theme

### ISSUE THREAD

**Issue by haoadoreorange** [piroor/treestyletab#3129]
Hi, so I've been toying a bit with themes and I noticed that there some old themes that based on a theme called "Plain", switching to it requires changing the theme to "Plain" and apply custom CSS.

But I don't have "Plain" theme at all, and I don't remember that's ever been an option. Was it removed or something is wrong with mine setup ?

**Comment by piroor** [comment]
Sorry I forgot to update documents. The theme "Plain" was renamed to "Photon".
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#restore-old-built-in-themes

**Comment by haoadoreorange** [comment]
thank you (: it's THE best extension (:
