### ISSUE TITLE
Make behaviour more like Vivaldi Tab Stacks

### ISSUE THREAD

**Issue by bobf32** [piroor/treestyletab#3132]
There is an option in TST to expand a tree node and collapse the others on a mouse click. I think it would be good if there was an option to achieve the same results via the mouse hover event instead of needing to click. This would ensure that any tab could be selected with just one tab click instead of two, as in the Vivaldi tab stacks feature.

**Comment by piroor** [comment]
I have no plan to implement it as a built-in option, sorry. Instead it may be provided by a helper addon using [TST's API](https://github.com/piroor/treestyletab/wiki/API-for-other-addons). I think the TST Hoverswitch addon https://addons.mozilla.org/firefox/addon/tst-hoverswitch/ will help you to understand how to implement "hoverexpand" feature.
