### ISSUE TITLE
Collapse and Close buttons Missing In the Tree Style Side Bar

### ISSUE THREAD

**Issue by Vindickator** [piroor/treestyletab#3134]
## Short description
The buttons for collapse and close went missing on the side bar, even opening the side bar as a page doesn't have the icons, so it is hard for me to see which is a tab with multiple tabs and close.

## Steps to reproduce
I updated to Firefox v100 recently and from that point only I am facing this issue.
1. Open Firefox, 
2. Start TST with hotkey or sidebar launch
3. Wait for tabs to load
4. Open wikipedia
5. Rapid press any number of links to open child tabs

## Expected result
**Expand button present**
![image](https://user-images.githubusercontent.com/87226625/170818604-4459cc8e-414f-4b42-abec-d910d3fc969c.png)
**Close button present**
![image](https://user-images.githubusercontent.com/87226625/170818622-ffa24033-dd71-4dcb-94cf-1788935fb223.png)

## Actual result
**Expand button missing**
![image](https://user-images.githubusercontent.com/87226625/170818715-f2fd981f-e55f-439f-a32a-9c9672a783b2.png)
**Close button missing**
![image](https://user-images.githubusercontent.com/87226625/170818718-2a20afac-829d-4885-9204-6f9c47a74119.png)

## Environment
 * Platform (OS): Windows 10
 * Version of Firefox: v100
 * Version of TST: v3.8.23

**Comment by Skiri-ki** [comment]
I have the same issue.
Windows 10 and 11
TST: v3.8.23
Firefox:  v100.0.2 
Reopening FF doesn't always solve it, restarting the machine usually does. Very annoying though.

**Comment by milroneth** [comment]
Same here. The new tab + icon on the bottom of the tab list is also invisible.

Windows 10
Firefox 100.0.2
TST 3.8.23

Also, I want to mention that I have an AMD RX480 and I upgraded my GPU Drivers+Adrenalin software from 22.3.2 to 22.5.2 at the same time as I upgraded Firefox. Probably irrelevant, but I can't rule it out until someone else confirms they don't have AMD GPU or that software version.

**Comment by piroor** [comment]
I've seen this problem on Nightly 102.0a1 after updating from 101.0a1. After reloading of TST itself the problem has gone away.

I think this is a bug of Firefox itself around image rendering. Sadly I have no idea to fix this on addon side.

**Comment by Vindickator** [comment]
@piroor Noted, thanks for the information, we'll await and see on the next major FF update.

**Comment by piroor** [comment]
Icons of those invisible buttons are rendered with a CSS property `mask`. Regular favicons are still shown as expected, so this looks to be `mask` specific issue. It may be missed by Firefox developers, so I think we should file this case as a bug at bugzilla.mozilla.org.

**Comment by milroneth** [comment]
Couldn't make the icons appear by disabling and reenabling the plugin multiple times, nor restarting FF. Until it updated to 3.8.24 yesterday (I saw the sidebar disappear and reload) so I know exactly when FF auto-updated it. It loaded fine with the icons and they have not disappeared since.

Also, Firefox is now v101.0.0, ~~though I'm not sure when that happened due to a power outage. I believe I was still on 100.0.2 when this got fixed by itself, but not 100% sure.~~ I am sure, it was still 100.0.2 yesterday while icons were working, so the FF update seems irrelevant.

**Comment by Vindickator** [comment]
I guess I found a workaround for this FF bug

Those who are still in the 100th version may try this out, 
(I have planned upgrade for my FF to the newer v101 next week only, to test and see if bug still exists)

So,
If I close my last FF session on a child tab of a New Tab that is also a New Tab, I seem to get the collapse and close icons fine on the next relaunch;
(like this ↧)
![image](https://user-images.githubusercontent.com/87226625/172010486-d584d139-b5be-4c15-bad9-3342a720e6fa.png)

**Comment by Vindickator** [comment]
Hello, 
As @milroneth indicated, I have updated to FF v101, and I confirm that the issue is gone now.

Thanks.

**Comment by piroor** [comment]
There is a progress at another issue: https://github.com/piroor/treestyletab/issues/3142#issuecomment-1173976231

**Comment by aeonstone** [comment]
I am on Firefox 106.0.3 and have been having this issue for over a month. Very annoying and still very much an issue.
