### ISSUE TITLE
Can pinch to zoom on trackpad on mac

### ISSUE THREAD

**Issue by Dqu1J** [piroor/treestyletab#3143]
## Short description
On Mac, you can pinch to zoom the TST sidebar on a trackpad

## Steps to reproduce
1. Use mac
2. Install TST
3. Put your mouse over TST sidebar
4. Try pinch zooming on a trackpad

## Expected result
I won't be able to zoom

## Actual result
It zooms in, see video below

https://user-images.githubusercontent.com/27054231/173565773-9adb2048-a8b7-409c-b8b9-856bfabb7e3f.mov

## Environment

 * Platform (OS): macos monterey
 * Version of Firefox: 101
 * Version (or revision) of Tree Style Tab: 3.8.24

**Comment by piroor** [comment]
My Windows PC's trackpad supports multi-touch and pinch-in/out works as zoom-in/out on the content area, but it doesn't change zoom level of the TST sidebar. Is this macOS specific?

**Comment by piroor** [comment]
I've tried the pinch-in/out action on Nightly + TST on macOS and confirmed it. It looks a platform specific problem.

**Comment by piroor** [comment]
* `* { touch-action: none !important; }` doesn't affect for me.
  https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action
* `touchmove` event is not reported for pinch-in/out.

The pinch-in/out zoom on macOS is processed by the lower layer (C++ and Objective-C).
https://searchfox.org/mozilla-central/source/widget/cocoa/nsChildView.mm#2494
https://searchfox.org/mozilla-central/source/widget/cocoa/nsChildView.mm#1858
https://searchfox.org/mozilla-central/source/widget/nsBaseWidget.cpp#873
I couldn't find out any method to prevent it for now.

**Comment by piroor** [comment]
Just a workaround you can deactivate pinch-in/out zooming on Firefox globally with disabling `apz.allow_zooming`.
https://www.reddit.com/r/firefox/comments/rzxwu4/how_do_i_disable_the_pinchzoom_feature_on/
But it deactivate zooming on the content area also.

**Comment by piroor** [comment]
I've filed a bug: [1777199 - Pinch-in/out zooming on macOS should be disabled on an extension's sidebar panel](https://bugzilla.mozilla.org/show_bug.cgi?id=1777199)

**Comment by piroor** [comment]
I missed that [pinch-in/out zooming is actually cancelable via `event.preventDefault()` of synthesized `wheel` event](https://bugzilla.mozilla.org/show_bug.cgi?id=1777199#c5). This problem was produced because I misunderstood that I had to cancel Command-WhellScroll on macOS instead of Ctrl-WheelScroll on other platforms. The commit 736c38a should fix this.
