### ISSUE TITLE
Child tab (collapse) arrow buttons and other icons disappeared.

### ISSUE THREAD

**Issue by jeongwhanchoi** [piroor/treestyletab#3144]
The arrow icon and close Tab icon disappeared like the below image:
![image](https://user-images.githubusercontent.com/29731173/174223494-7d5b028b-38f1-4706-9ade-5083438c26e3.png)

When I use the default theme and Firefox version 101.0.1 (64-bit) on Windows 11, the icons are gone for me.
What I expected is the below:
![image](https://user-images.githubusercontent.com/29731173/174223907-3e2bc669-966c-4e9e-a856-482610f79915.png)

**Comment by piroor** [comment]
Is this same to #3134 ?

**Comment by jeongwhanchoi** [comment]
Oops, that's right. It's the same duplicate issue.

**Comment by piroor** [comment]
OK I close this as a duplicated.
