### ISSUE TITLE
Is there any chance of the sidebar becoming an actual tree, in the HTML?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [piroor/treestyletab#3145]
## Short description
I'm attempting to solve [the new-tabs-at-the-top problem](https://github.com/piroor/treestyletab/discussions/3009#discussioncomment-1660540) to my satisfaction, as I re-try about once a year, heh.

In attempting a CSS solution to this (which, honestly, makes more sense — it's a _visual_ change, after all), I'd previously come up with the following:

```css
/* Invert order of entire tab-tree.
 * Note: *Also reverses sub-trees*. */
#tabbar #all-tabs > ul.tabs {
  display: flex;
  flex-direction: column-reverse;
}
```

Unfortunately, that inverts the _entire_ tree, not just "puts new root-level tabs at the top."

Currently, I'm frustrated by the fact that the tree looks like this:

```html
<ul class="tabs">
   <tab-item id="tab-99" data-level="0" />
   <tab-item id="tab-100" data-level="1" />
   <tab-item id="tab-84" data-level="0" />
   <tab-item id="tab-85" data-level="1" />
   <tab-item id="tab-86" data-level="1" />
   <tab-item id="tab-87" data-level="1" />
   <tab-item id="tab-83" data-level="0" />
</ul>
```

… that is, although there's a 'tree' structure exposed through `data-level`, the actual HTML is flat. This means I can't address a subtree with CSS and change the `flex-direction`.

Is it possible you'd consider adding actual tree-structure to the source? Something like,

```html
<ul class="tabs">
   <tab-item id="tab-99" data-level="0" />
   <tab-item id="tab-84" data-level="0">
      <tab-item id="tab-100" data-level="1" />
   </tab-item>
   <tab-item id="tab-83" data-level="0">
      <tab-item id="tab-85" data-level="1" />
      <tab-item id="tab-86" data-level="1" />
      <tab-item id="tab-87" data-level="1" />
   </tab-item>
</ul>
```

## Environment

 * Platform (OS): macOS Monterey **12.4** (21F79)
 * Version of Firefox: **101.0.1**
 * Version (or revision) of Tree Style Tab: **3.8.24**

**Comment by piroor** [comment]
It is impossible via customization with CSS. Recently a new helper extension is developed based on a new API added on recent TST. Please try it: [TST New Tabs First](https://addons.mozilla.org/firefox/addon/tst-new-tabs-first/)

**Comment by ELLIOTTCABLE** [comment]
That extension is what inspired me to go poking around, today, actually!

Unfortunately, it has the same failing as all my initial attempts: it _actually reorders_ the tree, meaning "tab number 1" changes every time you open a new, root-level tab:

<img width="381" alt="Screen Shot 2022-06-19 at 12 41 42 PM" src="https://user-images.githubusercontent.com/200/174493802-525f72f6-d5a3-4e59-82d1-57d1f22a8253.png">

(It's probably not relevant, but — absolute-numbering matters to me due to using a lot of [Tridactyl](https://github.com/tridactyl/tridactyl#highlighted-features)'s `:tab 𝑛` to refer to tabs I'm using a lot during a given session. If, for example, I used `:tab 4` to switch to the "I opened this second" tree in that screenshot, as soon as I opened a new tab, that muscle-memory will now direct me to a different, unrelated tab.)

Anyway — if simply for consistency's sake — I'm still hunting for a good, solid solution that doesn't require fallible JS APIs with race-conditions; just simple CSS. /=

**Comment by piroor** [comment]
Sorry I responded without reading your full request deeply...

> Is it possible you'd consider adding actual tree-structure to the source? Something like,

In short it is beyond TST's design.

DOM structure of TST's tabs (they are flat and indented just visually) are synchronized to Firefox's native tabs (they are completely flat) including their physical order. It is intentional to keep compatibility with other tab addons. In other words, introducing nested DOM structure will make TST's tabs far from Firefox's tabs and it will become hard to collaborate with other addons. Something other similar addons providing tab management feature with tree structure may satisfy your demand, so I recommend you to try them.

If you still want to satisfy your will with TST, I think you need to use (possibly create) a new helper extension providing expected behavior. It is welcome to introduce new API to TST if such an extension can't be implemented with existing APIs.

**Comment by ELLIOTTCABLE** [comment]
Hmmmm. Any solution I can think of to those constraints is … super-janky.

I suppose TST (or an addon) could continuously maintain a second, duplicated copy of the DOM in tree-structure … and only display one … ugh, but that's so gross, and invites many bugs. Meh.

Thanks for your time! Maybe someone will come by with a better idea than any of mine.

**Comment by piroor** [comment]
I label this issue as "won't fix" for the main topic: changing DOM structure, and "help wanted" for the new tab behavior topic.
