### ISSUE TITLE
Github Actions \ Cycle Weekly Close Job \ No Label Items

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#3146]
## Short description
The Github actions job to automatically transition issues is working really well in most situations.  One change, I might suggest is to add one additional label with some actions.

1. If an item is older than "X" days (Say "3" ... or even "0") and has no label, add the label "Needs triage" to indicate that you have not likely reviewed that item.
2. Every "X" days, maybe add a comment to the item which will bump the item to the top of the list when sorted by "date updated".  (Maybe this step is optional if you would rather just search on the "Needs triage" label vs. just sorting by "Recently updated".)
3. Once a new label is applied, the original process takes over.

Currently 8 out of 20 open items don't have labels and a few can likely closed are are "older".

![image](https://user-images.githubusercontent.com/979729/174605133-1d5d7efc-af06-4662-a028-63b07509581f.png)

**Comment by irvinm** [comment]
@piroor it looks like you can just update ISSUE_TEMPLATE.md to include some YAML front matter to assign a default label to new issues.

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

It looks like only `name:` and `about:` are required, but you can add `labels: Needs Triage` to create a default label ...

![image](https://user-images.githubusercontent.com/979729/175842077-6d4db55f-a196-461a-9da6-94f96f2d614f.png)

Also, if this isn't a change you want to make to your label workflow please close this item.

**Comment by piroor** [comment]
Thank you for suggestions, I've added issue templates for each type issues. Still need update the automated task to add comments for untriaged issues...

**Comment by irvinm** [comment]
@piroor is there anything more you wanted to do with this one?  I think the process has been working out pretty well.  

I think the only other thing to consider was adding a comment (reoccurring?) for untriaged issues after a certain number of days.  However, this would really just be more of a reminder for you and that doesn't seem to be a problem. :)  [There is only 1 right now]
