### ISSUE TITLE
[Bug] Tab counts in new tab button - dont work

### ISSUE THREAD

**Issue by wvxwxvw** [piroor/treestyletab#3155]
1. Start Firefox with clean profile.
 2. Install TST.
 3. Add css in "Extra style rules for contents provided by Tree Style Tab"
```
#tabbar {
  counter-reset: vtabs atabs tabs;
}
tab-item:not(.collapsed):not(.discarded) {
  counter-increment: vtabs atabs tabs;
}
tab-item:not(.collapsed) {
  counter-increment: vtabs tabs;
}
tab-item:not(.discarded) {
  counter-increment: atabs tabs;
}
tab-item {
  counter-increment: tabs;
}
.newtab-button::after {
  content: var(--tab-count-text);
  pointer-events: none;
  position: absolute;
  right: 2.5em;
  color: rgb(111,111,111);
  background: transparent !important;
  mask: none !important;
}
.newtab-button {
  --tab-count-text: counter(tabs);
}
```
 5. Restart Firefox

## Expected result
Tab counts in new tab button

## Actual result
Unknown shit, instead of a counter

## Environment
Win 7 x64 + all update
Firefox ESR 91.11 and ESR 102
TST 3.8.25

**Comment by irvinm** [comment]
https://github.com/piroor/treestyletab/issues/3153

**Comment by wvxwxvw** [comment]
Okay, issue resolved for me. Can be closed.

**Comment by irvinm** [comment]
@wvxwxvw can you go ahead and close this item?  Just click "close issue" at the bottom of the comment box.  Thanks.
