### ISSUE TITLE
[Bug] (Wrong child tab indentation when parent tab is moved)

### ISSUE THREAD

**Issue by Sangeppato** [piroor/treestyletab#3162]
## Abstract

When a parent tab is moved to another window, the first child is promoted but its indentation is not updated

## Steps to reproduce

 1. Start Firefox with clean profile
 2. Install TST
 3. Create a parent and a child tab
 4. Move the parent tab to a new window, so that the child one is "promoted" to the previous parent's level

## Expected result

The child tab's indentation is adjusted to the left accordingly

## Actual result

The child tab's indentation remains unchanged

## Environment

 * Platform (OS): macOS 12.5
 * Version of Firefox: 103.0
 * Version (or revision) of Tree Style Tab: 3.8.26

### Before parent's movement

<img width="219" alt="Screen Shot 2022-07-27 at 16 18 37" src="https://user-images.githubusercontent.com/37263823/181274409-aa2156fe-6cdd-4ddd-8c83-59245a418fac.png">

### After parent's movement

<img width="215" alt="Screen Shot 2022-07-27 at 16 18 59" src="https://user-images.githubusercontent.com/37263823/181274583-a62dc474-77ae-4d7d-af9f-ee8e781fffcd.png">

You can see how the Wikipedia tab retained its previous indentation despite being effectively "promoted"

**Comment by piroor** [comment]
Confirmed with detaching of a parent tab via drag and drop of an individual tab in the horizontal tab bar.

**Comment by piroor** [comment]
The commit 0bc82f9 should fix this problem.
