### ISSUE TITLE
[Enhancement] Is it possible to hide all pinned tabs from tab bar?

### ISSUE THREAD

**Issue by minshifu** [piroor/treestyletab#3164]
Thank you for your great addon which is very useful. It is good to have some pinned tabs on standby.But they are taking up much space and can be cumbersome. So is it possible to hide pinned tabs completely from tab bar and move them either to sidebar or an independent drop-down list?  Best regards!

**Comment by irvinm** [comment]
@minshifu TST doesn't interact or change the main tab bar at all.  Many people hide the main tab bar and just use TST, but is sounds like you want kind of a hybrid approach.  I saw your post on r/FirefoxCSS and that is probably the right place to find out if is possible to hide pinned tabs from the main tab bar.

Pinned tabs are obviously already shown in the sidebar with TST.

**Comment by minshifu** [comment]
> @minshifu TST doesn't interact or change the main tab bar at all. Many people hide the main tab bar and just use TST, but is sounds like you want kind of a hybrid approach. I saw your post on r/FirefoxCSS and that is probably the right place to find out if is possible to hide pinned tabs from the main tab bar.
> 
> Pinned tabs are obviously already shown in the sidebar with TST.

OK, thank you for your kind reply.

**Comment by piroor** [comment]
This is out of scope of this project, moreover we cannot do this due to restrictions of WebExtensions. Firefox allows hiding of individual tabs by addons but pinned tabs are excepted - we cannot hide pinned tabs via WebExtensions API.
