### ISSUE TITLE
[Enhancement] Adding a subpanel at top of the sidebar (instead of bottom)

### ISSUE THREAD

**Issue by tjakubo** [piroor/treestyletab#3165]
## Abstract
Current [SubPanel API](https://github.com/piroor/treestyletab/wiki/SubPanel-API) seems to always put it on the bottom of tab bar, as shown here:
![image](https://user-images.githubusercontent.com/12734857/183311264-da2bd145-906f-4088-8fe2-4325568c7973.png)

That's great for expansive subpanels with a lot of content, but for something designed to be easily accessible like quick actions buttons, it'd be amazing to put it *above* tab content instead.  
So far I haven't found a satisfactory CSS solution to do that, while I can just override `#subpanel-container` style with e.g. `top: 0px`, it breaks a lot of other components: pinned tabs, TST still leaving "space" at the bottom for the force-moved subpanel etc.  
This also means subpanels designed for that use are a nightmare to share, may be breaking with other users having different tab height etc.

## Steps to see the situation
 1. Follow the SubPanel API tutorial to add any subpanel - it appears at the bottom.

## Expected result
Being able to specify some parameter that natively anchors subpanel above tab content instead of below.

## Example application
What I am working on (that would benefit greatly from this) is a simple shortcut buttons panel, with buttons to reopen last closed tab, expand/collapse all trees, bookmark-and-close all (like saving a session) etc.  
Using some very dirty CSS it looks like below. At the moment, it breaks pinned tabs because of that hacky CSS solution:
![image](https://user-images.githubusercontent.com/12734857/183311664-d0b580a1-67be-4cb5-bddf-7c119fc8c040.png)

## Environment
N/A

## Disclaimer
The idea (and my need for it) comes from a different addon - [TreeTabs by kroppy](https://gitlab.com/kroppy/TreeTabs), that has this awesome customizable buttons bar:
![image](https://user-images.githubusercontent.com/12734857/183311777-f59af8bf-de3d-4843-a1a9-e2a95bb9053e.png)
unfortunately, its development was abandoned with some infuriating bugs still prevalent, so I decide to migrate and use TST customizability to match its functionality (and look to some degree).

**Comment by piroor** [comment]
Moving the position of the subpanel area is hard. Instead I think such fixed-height buttons can be provided with the new `set-extra-contents` API with `place:"tabbar-top"` (see #3171 for more details).

**Comment by tjakubo** [comment]
> Moving the position of the subpanel area is hard. Instead I think such fixed-height buttons can be provided with the new `set-extra-contents` API with `place:"tabbar-top"` (see #3171 for more details).

That looks great, and I can't wait to see it integrated in a public release! Thank you very much piroor.
