### ISSUE TITLE
Tab sidebar loads forever. Uncaught (in promise) TypeError: Range.setEndAfter: Argument 1 is not an object

### ISSUE THREAD

**Issue by pfgithub** [piroor/treestyletab#3166]
## Steps to reproduce

I don't know how to reproduce this. It has happened to me twice

- The first time, it didn't like some tab I opened. After closing the tab, it started working again
- The most recent time, I closed the tab sidebar and then it wouldn't reopen until restarting the browser.

## Expected result

The tab sidebar shows

## Actual result

The tab sidebar loads forever and displays an error in the console:

```
FATAL ERROR: Imported tab is not untracked yet. Reload the sidebar to retry initialization. See also: https://github.com/piroor/treestyletab/issues/2986 [sidebar.js:580:17](moz-extension://2839a011-f286-4a90-a194-7538bc7418f3/sidebar/sidebar.js)
Uncaught (in promise) TypeError: Range.setEndAfter: Argument 1 is not an object.
    updateTabbarLayout moz-extension://2839a011-f286-4a90-a194-7538bc7418f3/sidebar/sidebar.js:765
    init moz-extension://2839a011-f286-4a90-a194-7538bc7418f3/sidebar/sidebar.js:282
    addAsync moz-extension://2839a011-f286-4a90-a194-7538bc7418f3/common/metrics-data.js:27
    init moz-extension://2839a011-f286-4a90-a194-7538bc7418f3/sidebar/sidebar.js:275
    async* moz-extension://2839a011-f286-4a90-a194-7538bc7418f3/sidebar/index.js:28
```

It references issue #2986 but the extension was last updated a month ago, so it's not the same problem

## Environment

 * Platform (OS): Linux x86_64 5.18.10-arch1-1
 * Version of Firefox: 102.0.1
 * Version (or revision) of Tree Style Tab: 3.8.26

**Comment by Vindickator** [comment]
I too have this exact issue after updating the TST to 3.8.26; 

The TST loads forever, I get and alert and check processes and I see firefox is continuing to eat entire RAM rapidly (the entire 32GB).
I killed the firefox, restarted the browser, quickly disabled TST and everything is fine again..

Enabling TST again manually causes rapid RAM spike and Firefox to become irresponsive.

Update: I managed to downgrade TST back to 3.8.25 and was able to resolve this issue for me (at least for the time-being)

**Comment by Vindickator** [comment]
@pfgithub do you by any chance have the colour addon installed along with TST? (TST Colored Tabs);
I had to disable this too along with the newer version to stop the issues...

**Comment by piroor** [comment]
I cannot reproduce this on my environment. I've introduced the commit 1752e7a to suppress the error @pfgithub reported, but I'm not sure it fixes the problem completely. Could you try the development version? https://github.com/piroor/treestyletab#development-builds (You need to use Nightly to try it from startup.)

**Comment by pfgithub** [comment]
Thanks for looking at this - it's hard since I have no clue how to reproduce it. I haven't had it happen again since reporting this issue, even with hundreds of tabs open. It's possible it's some problem with my system or a bug fixed in a newer version of Firefox

**Comment by pfgithub** [comment]
It seems I had some bad memory in my computer and there's a chance Firefox put some tab data there or something that broke the extension, closing this
