### ISSUE TITLE
[Enhancement] Firefox Translations (possible other) vertical space causing displayed TST tabs to fall out from visible area

### ISSUE THREAD

**Issue by maricn** [piroor/treestyletab#3168]
## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install official Firefox Translations addon https://addons.mozilla.org/en-US/firefox/addon/firefox-translations/.
 4. Open enough tabs to fill out vertical space in TST, scroll to the bottom.
 5. Navigate to a page where Firefox Translations top bar activates.

## Expected result
As the Firefox Translation bar takes vertical space, it eats away part of TST space. I'd expect that if TST is scrolled to the bottom of the list, it stays scrolled down.

## Actual (present) result
When Firefox Translation notification bar pops up, TST tabs are pushed down. That in turn pushes out the last opened tab from what's visible in the TST sidebar.

![screencast-2022-08-10T19:34:22](https://user-images.githubusercontent.com/3995223/183979360-fda86ed8-7258-4451-b0e1-6b7aedef5010.gif)

The current behavior is confusing as when working with many tabs, the last opened ones are often where our attention is. Losing them out of sight is breaking the flow and introducing cognitive load to keep up with the state while that should be machine's job :robot: .

## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: 103.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.8.26

**Comment by piroor** [comment]
Sadly it is out of control of TST. Firefox Translations is implemented with an experimental API specially allowed for Mozilla official addons - the toolbar is inserted above the sidebar area via a special power. On the other hand, TST just uses existing public WebExtensions API and its UI is implemented just as a sidebar panel. It needs to be done by Firefox Translations to change the insertion position of the toolbar.
