### ISSUE TITLE
[Enhancement] Copy tree URLs

### ISSUE THREAD

**Issue by dotancohen** [piroor/treestyletab#3169]
A useful enhancement to TST would be to copy a newline-separated list of open URLs in a Tree. This would help once I've completed a research project, but would like to store the open URLS in my Project Notes file in the event that I need to return to this project.

## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Search your favorite search engine for "The Beatles".
 4. Open four links in a new tab (Ctrl-Click, or Right Click).
 5. Try to copy all the URLs to a text file.

## Expected result

Right click a Parent Tab, among the options presented would be "Copy Tree URLs".

I would not expect the sub-Tree structure to be preserved, just a list of URLs including the Parent Tab URL.

## Actual (present) result

No such right-click menu item.

**Comment by irvinm** [comment]
There are ways to do this already with other addons.  I personally use the addon "Copy Selected Tabs to Clipboard" (integrated with TST) and all you need to do is multi-select whichever tabs you want to get or use the built in options:

![image](https://user-images.githubusercontent.com/979729/184876114-d1196111-b8c9-496a-a1c9-6d438481de5f.png)

**Comment by piroor** [comment]
As @irvinm suggested the combination with Copy Selected Tabs to Clipboard is the solution.
https://addons.mozilla.org/firefox/addon/copy-selected-tabs-to-clipboar/
I have no plan to add the feature to TST as a built-in.
