### ISSUE TITLE
Opening bookmark folder as tree opens local file bookmarks as inoperative "about:blank?file:///[path]" tabs.

### ISSUE THREAD

**Issue by ncsuDuncan** [piroor/treestyletab#3173]
## Abstract
Opening bookmark folder as tree opens local file bookmarks as inoperative "about:blank?file:///[path]" tabs.

## Steps to reproduce

1. Create a bookmark folder containing bookmarks pointing to local HTML files (example: C:/Users/Exampleuser/examplefile.html)
2. Open that bookmark folder as a tree, using "Open All as a Tree" in the context menu.

## Expected result

Normally you would expect the bookmarks pointing to local files to load like any other tab. (Which is what happens when you open the individual bookmark, or open the bookmark folder as normal instead of "as a Tree".)

## Actual result

When opening "as a Tree" the local HTML files will not be opened, instead in their place you will get an empty tab with the URL "about:blank?file:///" followed by the file path. 

For example using the example file mentioned further above, the blank tab points to: "about:blank?file:///C:/Users/Exampleuser/examplefile.html"

Reloading the blank tabs will not load the relevant file. You have to manually edit the URL to prune out the "about:blank?" part.

This issue has no impact on the tree structure itself, the tabs are all positioned where they should be. Web URLs (e.g. non-local HTML) open just fine in their expected places.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 103.0.2
 * Version (or revision) of Tree Style Tab: 3.8.26

**Comment by piroor** [comment]
It is due to a restriction of WebExtensions API based addons for Firefox. Related issues:

* [1266960 - Extensions can not load file: URLs](https://bugzilla.mozilla.org/show_bug.cgi?id=1266960)
* [1269456 - [meta] Add permission to allow extensions to load semi-privileged URLs](https://bugzilla.mozilla.org/show_bug.cgi?id=1269456)

**Comment by ncsuDuncan** [comment]
Gotcha. Thanks for the quick response!

I thought I was being smart by creating some local HTML files (just title and favicon) to use as labels for trees I regularly create. Looks like I'll just have to host those somewhere non-local. :)
