### ISSUE TITLE
[Bug] Send tab to Android (Fennec)

### ISSUE THREAD

**Issue by dflvunoooooo** [piroor/treestyletab#3174]
## Abstract
It is not possible to send a tab to fennec on android. 

## Steps to reproduce

 1. Start Firefox.
 2. Install TST.
 3. Start Fennec nightly.
 4. install TST from collection.
 5. Right click on a Tab in Firefox.
 6. Select "Send tab to device".

## Expected result
I expected my fennec instance to appear to select as a target to send tabs to. 

## Actual result
No device is listed.

## Environment

 * Platform (OS): Arch Linux and Android 12.
 * Version of Firefox: 104 
 * Version (or revision) of Tree Style Tab: 3.8.26 

I know that fennec is not supported. But sending tabs is the most important feature of Firefox for me. 

I have TST installed in fennec with the collection "trick", but I can not even open the settings of TST to give this device a name. Would it work if this would be possibel?

Is there something I can do?

**Comment by irvinm** [comment]
@piroor will certainly comment, but I do not think this will be possible.  Even if you are able to install TST in Fennec, it won't be able to run there as there is no sidebar support.  If it doesn't run, it won't be able to use Firefox Sync to pass tabs between instances.

![image](https://user-images.githubusercontent.com/979729/186522332-d6d1ab99-8857-452f-a5fd-a2262d00a825.png)

**Comment by dflvunoooooo** [comment]
Thanks for the fast answer. I see, makes sense not to loose the tree hierarchy. And there is no way to get the standard Firefox send to device option too? Than, one could send the tab the "old way", without tree structure via Firefox Sync and with the TST send to device with tree structure.

**Comment by irvinm** [comment]
As I recall, the WebExt API (addon API) does not have access to be able to interact with the native Firefox "Send Tab to Device" functionality.  I believe TST has a workaround for this by populating the information in the Firefox Sync mechanism and hence why this only works when TST is installed on both ends.

If you really need to be able to send a tab to Fennec, I think the only way to do that is via the native tab option of "Send Tab to Device" but obviously that does not pass across the "Parent ID" and hence they are all sent as just individual tabs without tree information being maintained.

I know there is a feature request in bugzilla to allow addons access to that functionality.

**Comment by piroor** [comment]
There is a FAQ topic about this: https://github.com/piroor/treestyletab/blob/trunk/README.md#user-content-feature-requests-send-tab-tree-to-device-does-not-work

**Comment by piroor** [comment]
Oops, sorry I missed this section:

> I know that fennec is not supported. But sending tabs is the most important feature of Firefox for me.
> 
> I have TST installed in fennec with the collection "trick", but I can not even open the settings of TST to give this device a name. Would it work if this would be possibel?
> 
> Is there something I can do?

A special URL `ext+treestyletab:options` should be available if TST's protocol handler works. Could you try it?

**Comment by dflvunoooooo** [comment]
@piroor No problem. I would love to, but I do not really understand what I am supposed to do. Would you please be so to explain that?

**Comment by dflvunoooooo** [comment]
@irvinm 
> […] and hence they are all sent as just individual tabs without tree information being maintained.

I don't mind that. Since TST isn't really working on Fennec, the hierarchy of my tabs must not be preserved, but I extensively use the "send tab to device" function.

**Comment by irvinm** [comment]
> @piroor No problem. I would love to, but I do not really understand what I am supposed to do. Would you please be so to explain that?

I think he is asking you to type that into the URL bar in Fennec and see if it loads the TST options page.  If it does, then it means that TST is actually running although there is no sidebar support.  If it doesn't then it isn't running at all.

**Comment by dflvunoooooo** [comment]
Ah, I tried that, but fennec uses the search engine and can not open it otherwise.

**Comment by piroor** [comment]
Hmm, does the command "Manage Devices..." under "Send Tab to Device" work? If it is missing in the menu you looks to use Firefox's native tab context menu instead of the menu on TST's sidebar. I've experimentally expose the menu for Fennec's native context menu (it is not tested by me) with the commit 3f26df4 and it should open TST's options page to manage the device name.

**Comment by dflvunoooooo** [comment]
There is no option "Manage Devices …". In Fennec one can only share a tab, and if you are logged in to firefox-sync than there are all other firefox-sync devices listed. In firefox on my desktop, I get to the settings page of TTS.

**Comment by piroor** [comment]
You cannot see "Manage Devices …" in tab context menu: it means that TST cannot provide any special menu command for Fennec. Thus we looks to do something for Fennec specially, but currently TST does not support Fennec officially and I have very limited motivation to research for TST on Fennec which does not provide effective place to show tree of tabs...

 It is not promised but if you create a pull request of TST to support Fennec and it is reasonable I can merge it. Could you try that?
