### ISSUE TITLE
[Issue] Sidebar scroll bar uses other colors than other scrollbars in the Firefox UI

### ISSUE THREAD

**Issue by allo-** [piroor/treestyletab#3175]
## Abstract

It would be nice to have an optional scroll bar for scrolling through long lists of tabs.

## Steps to see the situation

 1. Open Firefox with a lot of tabs
 2. try to go to the start or end of the list
 3. You have to use the scroll wheel a lot

The current tree structure where I am missing the scroll bar is a flat list.

## Expected result

There should be an (optional) scroll bar.

## Actual (present) result

There is none.  
I am not sure if it is a missing feature or a bug / possibly a regression after Firefox upgrade.

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 104.0
 * Version (or revision) of Tree Style Tab: 3.8.26

**Comment by piroor** [comment]
If depends on the behavior of sidebar on web pages, inherited from GTK's behavior. Go to `about:config` and set `widget.gtk.overlay-scrollbars.enabled` to `false` (or options page of Firefox => General => Navigation => Always show scrollbars => turn on) then you'll see the scrollbar always when the sidebar is scrollable. 

And for Windows 11 users: you'll need to change an accessibility option of Windows itself.
https://connect.mozilla.org/t5/discussions/scrollbars-disappear-in-firefox-100/td-p/5433

These changes affect globally on Firefox. Sorry but there looks to be no way to apply the change only for TST's sidebar.

**Comment by allo-** [comment]
I already disabled overlay scrollbars. I now noticed (and maybe that changed with the upgrade to FF 104?) that there is indeed some kind scrollbar at the left side of the sidebar. It looks different than the gtk-style scrollbar and does not have a handle and seems to stop working once one reached the end of the list (so you need to click again to scroll in the opposite direction), but you can scroll. I wonder if this is a TST feature or a Firefox Feature.

The Bookmarks, History, etc. Sidebars have a usual gtk-style (which is since a few releases a native-ui from Firefox) scrollbar at the *right* (Sidebar at the right side of Firefox). I wonder if you disabled the right-side scrollbar on purpose because that's there the close-buttons of the tabs are (proton style sidebar). I don't actually care about the side, but having a handle that indicates the approximate position in the list would be useful.

**Comment by allo-** [comment]
Oh, I've got it. It's theme dependent. The default dark theme has a scrollbar at the left side of the sidebar that has way too little contrast, some other darkthemes seem to use the same colors both for the handle and the background.

I am not sure if I should close here. It may be just a theme bug, but on the other hand the scrollbars in the bookmarks and history list work fine on these themes, being lighter than the scrollbar drawn by TST.

**Comment by allo-** [comment]
Theme: Firefox Dark

History Sidebar: Scrollbar to the right, enough contrast
![History-Tab-Scrollbar-Darkmode](https://user-images.githubusercontent.com/1482341/186617824-939b528e-7862-44f2-a127-4d8fb4fb1047.png)

TST Sidebar: Scrollbar to the left, very little contrast, on some thirdparty themes no contrast at all
![TST-Tab-Scrollbar-Darkmode](https://user-images.githubusercontent.com/1482341/186617839-f44e41ae-bd78-4c92-948a-b78a5bea3e4d.png)

Maybe you're using other colors from the theme for the scrollbar than the scrollbars used for the other sidebars?

**Comment by piroor** [comment]
With the commit b2f4076 the auto-hide scrollbar in the TST's sidebar should be rendered with default colors.

**Comment by allo-** [comment]
In which release is the fix included? 3.9.5 seems to still have the scrollbar that is invisible in some dark themes.

**Comment by piroor** [comment]
@allo- Could you describe more details about the environment? I can create a VM on VirtualBox and install Linux distribution if it is available, so I hope that you describe the name of the Linux distribution, required packages and configurations to see the problem on my environment.

**Comment by allo-** [comment]
- Use a fresh Firefox profile
- Activate the default dark theme (System theme auto could work, but use the explicit one)
- Install TST
- Set `widget.gtk.overlay-scrollbars.enabled = false`
- (Everything looks fine)
- Switch TST from Proton to High Contrast (looks fine)
- Switch back to Proton (Now the scrollbar is black)

This seems to fix it temporarily:
- Set `widget.gtk.overlay-scrollbars.enabled = true`
- Switch to High Contrast and then back to Proton
- Set `widget.gtk.overlay-scrollbars.enabled = false` again
- DO NOT switch TST themes

The problem happens here both with the Debian (testing) Firefox and the unpacked tar from ftp.mozilla.org.

I think Firefox tries to get colors from the Gtk colorscheme what may affect things. I am not sure if colors should change when overlay scrollbars are disabled. I very much prefered native scrollbars, but they probably won't return in Firefox.

**Comment by allo-** [comment]
The problem seems to be disabling overlay scrollbars. After applying the temporary fix, TST just does not seem to change scrollbars at all and still has overlay scrollbars enabled. When you close and open the sidebar again the problem is back.

Switching themes is probably just triggering a reload and then the new scrollbar style is applied.

**Comment by piroor** [comment]
Thanks! I've tried with Debian unstable and Firefox 105.

Case 1:

* System theme; Dark
* Firefox theme: System
* Firefox config: `widget.gtk.overlay-scrollbars.enabled` = `false`
* TST theme: Proton

![image](https://user-images.githubusercontent.com/70062/191525925-710f831c-5444-4c28-b25d-89c9ccd5830d.png)

Case 2:

* System theme: Dark
* Firefox theme: Dark
* Firefox config: `widget.gtk.overlay-scrollbars.enabled` = `false`
* TST theme: Proton

![image](https://user-images.githubusercontent.com/70062/191526340-460b81a9-3acf-4345-bf4e-704b95bf119a.png)

Case 3:

* System theme: Dark
* Firefox theme: Dark
* Firefox config: `widget.gtk.overlay-scrollbars.enabled` = `true`
* TST theme: Proton

![image](https://user-images.githubusercontent.com/70062/191526756-d5ce127e-bd86-4cf7-85c3-2704d830283e.png)

**Comment by allo-** [comment]
Yes, case 2 is what I am seeing. And when you use a theme that has different (dark) colors than the Firefox dark theme, you may end up with an invisible scrollbar.

**Comment by piroor** [comment]
On the case 2, TST applies `scrollbar-color: var(--theme-colors-toolbar_bottom_separator) var(--theme-colors-toolbar);`. The first color is the thumb of the scrollbar, the second color is the background of the scroll bar.
On this case:
`--theme-colors-toolbar_bottom_separator` is `hsl(240, 5%, 5%)`, and 
`--theme-colors-toolbar` is `rgb(43,42,51)`.
Those colors are from the "Dark" theme of Firefox itself. Hmm...

**Comment by piroor** [comment]
Recent commits ca6e36944af9cfbeed6d7950cced5e160d3ddd23 and e6fb8c6c267b8947ff3b3fb64e5156385c7a314a should change the thumb color more visible on this case, if the toolbar text color is parsable. I hope it solve this hard-to-see color combination problem...

**Comment by allo-** [comment]
Works for me.
