### ISSUE TITLE
[Enhancement] Auto tree expand / collapse on mouse over

### ISSUE THREAD

**Issue by bobf32** [piroor/treestyletab#3176]
I use the Vivaldi browser as well as Firefox. The former has a wonderful feature called tab stacking, which is similar in spirit to TST. The main difference is that hovering the mouse over a top level node in the stack (tree equivalent) causes a thumbnail grid of all pages included in the stack to be displayed, and any new tab can then be navigated to. 

I think it would be great if TST had an option to emulate this feature, as it only takes one mouse click to open any tab. 

One way it could work would be to have an option for navigation by mouse hover, and maybe another for the duration before the hover event takes place. Once this duration has passed, TST would then fully expand the TST node hovered over. Perhaps also collapse all the other top level tab trees too.

Any appetite?

**Comment by irvinm** [comment]
https://addons.mozilla.org/firefox/addon/tst-hoverswitch/

Also, see https://github.com/piroor/treestyletab/issues/3132.

**Comment by bobf32** [comment]
Thanks @irvinm, that's great.

**Comment by piroor** [comment]
Sorry I won't implement those behavior as built-in features.
https://github.com/piroor/treestyletab#user-content-feature-requests-add-more-minor-trivial-options
