### ISSUE TITLE
[Bug] Dragging Multiple Trees

### ISSUE THREAD

**Issue by aFineBoi** [piroor/treestyletab#3178]
## Abstraction
If only one tree is selected by holding down shift key, it behaves normally when drag the tree to open a new window. But if you make it two trees it won't work.
## Steps to reproduce
1. Open Firefox with TST
2. Open tabs in a tree style manner
3. Select **two trees** of tabs by holding down _shift_ key
4. Drag them with your mouse to an empty area to open a new window
## Expected result
All selected tabs are move and sorted as what it was
## Actual result
One of the trees of tabs won't be moved
## Environment
Windows 11
Firefox 104
TST 3.8.26

**Comment by irvinm** [comment]
@piroor I tried this and it worked the first time I did it (steps below), but I put the tree back together again and repeated the process and the 2nd time only 1 tree was moved.  There does seem to be a problem here.

Starting point with several trees:

![image](https://user-images.githubusercontent.com/979729/187428278-2a5744bd-80a6-4953-bba3-1bac69ecfb45.png)

Selecting 2 trees by clicking on first tab then shift+last-tab:

![image](https://user-images.githubusercontent.com/979729/187428322-ec643093-fcbf-4a37-b171-5c7f65f5ab32.png)

After dragging those trees outside:

![image](https://user-images.githubusercontent.com/979729/187428400-a6584b80-b626-417e-a336-b8ed9f5391ba.png)

**Comment by piroor** [comment]
Thanks @aFineBoi and @irvinm , finally I've realized that TST failed to update its internal "highlighted tabs" information after they are moved across windows. The commit c81e3db should fix it.
