### ISSUE TITLE
"Last related tab" is not cleared unexpectedly

### ISSUE THREAD

**Issue by piroor** [piroor/treestyletab#3180]
### Discussed in https://github.com/piroor/treestyletab/discussions/3179

<div type='discussions-op-text'>

<sup>Originally posted by **DreamC** August 31, 2022</sup>
Since I installed TST a few months ago I noticed some strange behavior with opened tabs. TST is set to open new child tabs next to recent tab (imitate Firefox behavior). Sometimes new tabs keep on creating after some sort of "old recent" tab even if focus them. Also focusing a tab while it is still loading does nothing - new child tab will be opened after recent tab instead of current.
I tried a fresh profile, but the problem is still there.
Is this the intended behavior or not? And should it be different from the "Firefox controls opened tabs"?

Video that will help to visualize it: https://youtu.be/bm_Aaz3N2nk</div>

**Comment by piroor** [comment]
This may be triggered due to failure of updating `lastRelatedTab` around the code:

https://github.com/piroor/treestyletab/blob/d6c455bd31a295f89abdc4d0f37966a3be659333/webextensions/background/successor-tab.js#L184-L220

@DreamC Could you try inspecting opened tabs when the problem happens? Please run the following code with the [debugger console](https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-start-debugger-for-tree-style-tab) for TST's "background.html" , while the problematic parent tab is active:

```
Tab.getActiveTabs().map(activeTab => [activeTab, ...activeTab.$TST.descendants].map(tab => `${tab.id}(${tab.$TST.ancestors.length}): opener=${tab.openerTabId}, lastRelated=${tab.$TST.lastRelatedTabId} / successor=${tab.successorTabId} / lastSuccessr=${tab.$TST.lastSuccessorTabId||-1} / lastSucessorByOwner=${tab.$TST.lastSuccessorTabIdByOwner||-1}`).join('\n')).join('\n\n')
```

This will dump details of a tree under the active tab.

**Comment by DreamC** [comment]
First of all, when I close tabs this unhandled exception is printed. Just when closing tabs (not always though). Didn't notice any dependence on the order.
```
Uncaught (in promise) Error: Invalid tab ID: 16 2 undefined
    timer moz-extension://ff9370d1-de26-46b0-a81f-b70b3c1d5901/extlib/TabFavIconHelper.js:417
    AsyncFunctionThrow self-hosted:811
    (Асинхронный: async)
    onTabUpdated moz-extension://ff9370d1-de26-46b0-a81f-b70b3c1d5901/extlib/TabFavIconHelper.js:404
    onTabUpdated self-hosted:1356
    apply self-hosted:2736
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:622
    fire resource://gre/modules/ExtensionChild.jsm:829
    recvRunListener resource://gre/modules/ExtensionChild.jsm:833
    recvRunListener self-hosted:1356
    _recv resource://gre/modules/ConduitsChild.jsm:82
    receiveMessage resource://gre/modules/ConduitsChild.jsm:188
```

And this is the dump you asked for:
```
"13(0): opener=13, lastRelated=52 / successor=12 / lastSuccessr=51 / lastSucessorByOwner=-1
51(1): opener=13, lastRelated=0 / successor=13 / lastSuccessr=-1 / lastSucessorByOwner=-1
52(1): opener=13, lastRelated=0 / successor=13 / lastSuccessr=13 / lastSucessorByOwner=true

47(1): opener=12, lastRelated=0 / successor=12 / lastSuccessr=12 / lastSucessorByOwner=true" 
```

**Comment by piroor** [comment]
＠DreamC Thanks! The dump message says that there are two windows and there is a tree with two children in a window, like as:

* Parent (id=13)
  * Child1 (id=51)
  * Child2 (id=52)

On the other hand, there is a tree with more children in the screencast https://youtu.be/bm_Aaz3N2nk when the odd behavior appeared. Do you actually see more children when you got the dump, like as following?

* Parent (id=13)
  * Child1 (id=51)
  * Child2 (id=52)
  * Child3 (id=?) (new child tabs from the parent are inserted above this tab)
  * Child4 (id=?)

Then it means that internal tree structure is broken - third and fourth child tabs are internally orphaned, so we may need to fix a bug producing such a broken tree.

**Comment by DreamC** [comment]
@piroor Yes, I just opened the debugger in a separate window. Didn't have any experience with that.
Video has more children, yes. I did not replicate it one-to-one according to video - just till the point when this bug happens.
I can record a separate video with debugger.

Regarding the dump: it had three tabs only including the parent one.

**Comment by DreamC** [comment]
Recorded the whole thing again.
Video:
https://youtu.be/SHlE0wAN1zw
Debug output:
`"3(0): opener=3, lastRelated=0 / successor=2 / lastSuccessr=4 / lastSucessorByOwner=-1" `

**Comment by piroor** [comment]
Sorry the code to dump always report information from the active tab and the last dump you got is for the debugger tab. Could you try with new script which report information for all tabs?:

```
Tab.getRootTabs().map(root => [root, ...root.$TST.descendants].map(tab => `${tab.windowId}-${tab.id}(${tab.$TST.ancestors.length}${tab.active && ', active' || ''}): opener=${tab.openerTabId}, lastRelated=${tab.$TST.lastRelatedTabId} / successor=${tab.successorTabId} / lastSuccessr=${tab.$TST.lastSuccessorTabId||-1} / lastSucessorByOwner=${tab.$TST.lastSuccessorTabIdByOwner||-1}`).join('\n')).join('\n\n')
```

**Comment by DreamC** [comment]
I see. Here's a new one.

Video:
https://youtu.be/BFMhXosvSNQ
Output:
`"1-2(0, active): opener=2, lastRelated=0 / successor=1 / lastSuccessr=3 / lastSucessorByOwner=-1

1-3(0): opener=undefined, lastRelated=0 / successor=-1 / lastSuccessr=-1 / lastSucessorByOwner=-1
1-7(1): opener=3, lastRelated=0 / successor=3 / lastSuccessr=-1 / lastSucessorByOwner=-1
1-8(1): opener=3, lastRelated=0 / successor=3 / lastSuccessr=3 / lastSucessorByOwner=-1

1-7(1): opener=3, lastRelated=0 / successor=3 / lastSuccessr=-1 / lastSucessorByOwner=-1

1-8(1): opener=3, lastRelated=0 / successor=3 / lastSuccessr=3 / lastSucessorByOwner=-1" `

**Comment by piroor** [comment]
OK I got it. The behavior is produced from the difference of Firefox's built-in behavior and TST's simulated behavior.

**Comment by piroor** [comment]
I've introduced some changes to make simulated behavior more similar to Firefox's one. Coukd you try the development build?: https://github.com/piroor/treestyletab#development-builds

**Comment by DreamC** [comment]
Tried in Dev Edition. Seems to work for now (well, at least tried repeating the same thing I showed).
