### ISSUE TITLE
[Enhancement] Moving Tabs without Loading the Tabs

### ISSUE THREAD

**Issue by aFineBoi** [piroor/treestyletab#3183]
## Abstract

Inactive tabs will be loaded if you select multiple tabs and drag them **to open a new window** (won't happen if you just move them inside one window). This will cause issues like unnecessary bandwidth and high RAM usage.

## Steps to see the situation

1. Open lots of tabs
2. Close and re-open Firefox to get lots of inactive tabs
3. Select and drag multiple inactive tabs around to open a new window and all of them will be loaded

## Feature request

An option to drag inactive tabs around without loading them

## Environment

 * Platform (OS): Windows 11
 * Version of Firefox: 104
 * Version (or revision) of Tree Style Tab: 3.8.26

**Comment by aFineBoi** [comment]
Firefox will crash if too much tabs are loaded. Also websites like Youtube are apparently not happy about loading tabs over and over again, asking me if I'm a robot 😢

**Comment by irvinm** [comment]
https://addons.mozilla.org/en-US/firefox/addon/move-unloaded-tabs-for-tst/

**Comment by aFineBoi** [comment]
> https://addons.mozilla.org/en-US/firefox/addon/move-unloaded-tabs-for-tst/

[Comment by Lej77](https://github.com/Lej77/move-unloaded-tabs-for-tree-style-tab/issues/4):
> As mentioned in the other issue this will be fixed in Tree Style Tab v3.4.4. Anyways this extension isn't really needed on later versions of Tree Style Tab since it has changed its default behavior to not select/active/load tabs when they are moved and therefore you should probably just uninstall this extension.

Not sure if this is intended, but that extension is helpful anyway

**Comment by irvinm** [comment]
@aFineBoi, thanks for the info.  I did try disabling the helper addon and TST doesn't seem to support moving unloaded tabs without loading them first.  Maybe there is a configuration option I need to explore.

**Comment by piroor** [comment]
I've realized that this happens because Firefox moves multiple tabs across windows step-by-step and activates each tab before moved (it triggers restoring of the tab) unexpectedly. With the commit 117d292 TST should move focus to one of tabs left in the source window before tabs are moved and it should prevent unexpected activation of to-be-moved tabs.
