### ISSUE TITLE
[Bug]  can't send the tabs thru the Tree Style Tab on the left regardless if it's per tabs or per tree. When I select the tabs, I need to send the tabs through the tab menu at the top (ergo by right clicking the tabs at the top not the tabs on the tree style)

### ISSUE THREAD

**Issue by jnlawrence** [piroor/treestyletab#3190]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Select the tabs thru the Tree Style Tab
 4. Right Click and choose either to send Tabs to device or Send Selected Trees to Device
 5. No device shows up even if devices are synced

## Expected result

Tabs or tree should be sent to device 

## Actual result

No device shows up when mouse is hovered on the send tabs to device

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
Is this covered with the FAQ topic?
https://github.com/piroor/treestyletab#user-content-feature-requests-send-tab-tree-to-device-does-not-work
