### ISSUE TITLE
[Bug] Cross-Extension Embedding Security Error in Firefox 105

### ISSUE THREAD

**Issue by NiklasGollenstede** [piroor/treestyletab#3191]
I tried Firefox 105(.0b9) today, and in TST's sidebar the subpanel area is blank and instead of TST-Search's icon above it, there is the broken-image placeholder:

![image](https://user-images.githubusercontent.com/10552031/189549714-b66d8a08-fe9d-4d19-af91-360335d9303e.png)

The debugging Toolbox of TST shows:

> Security Error: Content at moz-extension://df6c3756-.../sidebar/sidebar.html?style=photon&reloadMaskImage=true may not load or link to moz-extension://0ffe6b18-.../src/content/embed.html?windowId=1

(and the same for the icon)

I assume Mozilla changed something cross-origin related. I am not sure whether this can be adjusted for by TST (or the embedded extension).
Maybe there are some cross settings on the iframe or the embedded extension needs to declare some of its content as cross-embeddable.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST + TST Tab search.

## Expected result

The search subpanel should be visible and its icon should show up in the subpanel selector.

## Actual result

(see screenshot)

## Environment

 * Platform (OS): Linux x64
 * Version of Firefox: 105.0b9
 * Version (or revision) of Tree Style Tab: 3.8.26

**Comment by piroor** [comment]
Is this https://github.com/NiklasGollenstede/tst-search/issues/25 ?

**Comment by NiklasGollenstede** [comment]
I believe so, yes!
(My last days were rather eventful, I completely missed you filing that issue, sorry.)
I guess the only takeaway from my filing here is that this already occurs in FF 105 and that (if you haven't already) the new requirement to make any embedded content (including the registered icons) `web_accessible_resources`  should be documented.
