### ISSUE TITLE
[Bug] Updating TST with extra style rules causes visual bug on New Tab button

### ISSUE THREAD

**Issue by 30103db** [piroor/treestyletab#3196]
## Abstract
If extra style rules which affect the New Tab button are added, updating to a newer version of TST causes the New Tab button to display incorrectly. Apart from the visual bug, the button still functions properly and the 3 context menus (container tabs, new tab position, new/reload/bookmark/select) still work as expected. Besides the September 12 (3.8.26 to 3.9.0) update, it has also occurred during past updates.

Removing the extra style rules and putting them back, i.e., ctrl-x, ctrl-v, temporarily fixes the bug.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install non-latest version of TST.
 3. Add extra style rules which affect the New Tab button. Here are the rules I used:
```/* Tab numbering and counting */
#tabbar {
  counter-reset: vtabs atabs tabs;
  /* vtabs tracks visible tabs, atabs tracks active tabs, tabs tracks all tabs */
}
tab-item:not(.collapsed):not(.discarded) {
  counter-increment: vtabs atabs tabs;
}
tab-item:not(.collapsed) {
  counter-increment: vtabs tabs;
}
tab-item:not(.discarded) {
  counter-increment: atabs tabs;
}
tab-item {
  counter-increment: tabs;
}

/* Position some text in the New Tab button */
.newtab-button::after {
  content: var(--tab-count-text);
  pointer-events: none;
    
  width: 100%;

  /* TST 2.4.0 - Fix for Issue #1664 */
  background: transparent !important;
  mask: none !important;
}

/* Show combined active and total tab count */
.newtab-button {
  --tab-count-text: counter(atabs) "/" counter(tabs) " tabs";
}
```
 4. Update TST
 5. Repeated "+" symbols are displayed on the New Tab button
 

## Expected result
![Screenshot 2022-09-13 232343](https://user-images.githubusercontent.com/45131961/190052478-aeb3f95a-faf7-467f-a158-18e47925fc14.png)

## Actual result
![Screenshot 2022-09-13 232248](https://user-images.githubusercontent.com/45131961/190052532-267a0915-4c5a-4403-97af-799ff563ad39.png)

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox:  104.0.2
 * Version (or revision) of Tree Style Tab:  3.8.26 and 3.9.0

**Comment by 30103db** [comment]
Apparently this also happens if you disable then re-enable TST from the Add-ons Manager

**Comment by piroor** [comment]
Thanks, the commit 71eac58 should fix this.
