### ISSUE TITLE
[Bug] New tab wrongly reattached since 3.9.x

### ISSUE THREAD

**Issue by Tragen** [piroor/treestyletab#3200]
## Steps to reproduce

Inside a tree click on a tab.
Press CTRL+T to open a new tab at the far end of the list.
Enter the same domain as the previously clicked tab and the tab will get moved to this tab as a child tab.

```
A.1
\A.2
  \A.3 (selected)
B
```

Pressing CTRL+T gives me
```
A.1
\A.2
  \A.3
B
A.4 - New tab  (selected)
```

then when I enter the same domain I get

```
A.1
\A.2
  \A.3
    \A.4 - New tab  (selected)
B
```

## Expected result
New tab stays at the end

## Actual result
New tab gets a child of the previous selected tab

## Environment

 * Platform (OS): Windows 11 22H1
 * Version of Firefox: 104.0.2
 * Version (or revision) of Tree Style Tab: 3.9.2

**Comment by piroor** [comment]
I couldn't reproduce the problem with TST 3.9.2 on Nightly 106.0a1 on Windows 10. Steps I did:

1. Start Nightly 106.0a1 with clean profile.
2. Go to https://addons.mozilla.org/firefox/addon/tree-style-tab/ and install TST 3.9.2. (the tab A.1)
3. Stay on the addon page and middle-click on a link in the page to open a child tab. (the tab A.2)
4. Ctrl-T to open a new blank tab. (the tab B)
5. Click the tab A.2.
6. Go to the address bar, modify the URL to something same origin URL, and press Alt-Enter to open a new child tab. (A.3)
7. A.3 is opened at the end of the tab bar and immediately attached to A.2 by TST.
8. Ctrl-T to open new tab. (A.4)
9. A.4 is opened at the end of the tab bar and stays there.

It looks there is something more conditions required to reproduce the problem you saw.

**Comment by Tragen** [comment]
It's strange, now I cannot reproduce it anymore reliably.
But it happens again and again.
