### ISSUE TITLE
[Bug] "open all in tabs" auto-grouping is not working in Fx 105.0rc2 and TST 3.9.2

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#3203]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. "open all in tabs" on a bookmark folder

## Expected result

grouped

## Actual result

ungrouped

## Environment

 * Platform (OS): win10 21h2
 * Version of Firefox: [105.0 RC2](https://archive.mozilla.org/pub/firefox/candidates/105.0-candidates/build2/win64/en-US/Firefox%20Setup%20105.0.exe)
 * Version (or revision) of Tree Style Tab: 3.9.2

**Comment by piroor** [comment]
I've realized that [`bookmarks.search()`](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/search) with moz-extension: URL even if it is a valid URL. The commit ab10725 should solve the problem.

**Comment by piroor** [comment]
https://searchfox.org/mozilla-central/rev/249ef0d85120097b6f34fceb0bea501bfe900b6c/browser/components/extensions/parent/ext-bookmarks.js#344
https://searchfox.org/mozilla-central/rev/249ef0d85120097b6f34fceb0bea501bfe900b6c/toolkit/components/places/PlacesUtils.sys.mjs#17
https://searchfox.org/mozilla-central/rev/249ef0d85120097b6f34fceb0bea501bfe900b6c/toolkit/components/places/Bookmarks.sys.mjs#1845

~~`URL.isInstance('moz-extension://********-****-****-****-************/options/options.html')` return `false` unexpectedly...~~ `URL.isInstance` return false for strings, it is my mistake.

**Comment by piroor** [comment]
OK I got it.
https://searchfox.org/mozilla-central/rev/249ef0d85120097b6f34fceb0bea501bfe900b6c/toolkit/components/extensions/Schemas.jsm#1058

* Now Firefox checks the access right for the URL given as `url`, even if it is just searched.
* TST doesn't have access right to other extensions' internal URL.
* TST tries to search bookmarks from URLs assumed from tab's `url` and `title` to detect it is opened from a bookmark or not. This process is done in parallel for multiple possible cases like `http://example.com`, `https://example.com`, `moz-extension://example.com`, and so on. The last case `moz-extension://` prefixed URL raises an error due to it violates the access right described above.

**Comment by piroor** [comment]
I've filed: [1791313 - bookmarks.search() with "url" always raises error if the given URL is inaccessible by the addon](https://bugzilla.mozilla.org/show_bug.cgi?id=1791313)

**Comment by bughit** [comment]
> TST tries to search bookmarks from URLs assumed from tab's url

Why do you have to search multiple versions? Do you not know the exact URL that started the navigation to a given tab? From your commit it seems the scheme is missing from this.tab.$possibleInitialUrl. Why does Fx give you urls without a scheme?

> The last case moz-extension:// prefixed URL raises an error due to it violates the access right described above.

My understanding moz-extension: is for extension internal pages. Don't those follow a well defined pattern (moz-extension://extension_guid)

**Comment by piroor** [comment]
Because new tabs don't have the loading URL information.

* New tab's `url` is `about:blank` until it is loaded.
* On some cases (especially opened from a bookmark) a new tab's `title` becomes the loading URL without its original scheme part. For example, a bookmark with `https://example.com/` will become a tab `{ title: "example.com/", url: "about:newtab" }`.
* There is no way to fixup the correct scheme, so TST searches multiple queries with different scheme in parallel.

**Comment by piroor** [comment]
Oops I misread your comment.

> Why does Fx give you urls without a scheme?

I don't know the exact reason - I just know that what actually happens on Firefox.

> Don't those follow a well defined pattern (moz-extension://extension_guid)

You are right. We possibly should skip searching for non-GUID cases. My implementation is sometimes rough and not smart.

**Comment by bughit** [comment]
@piroor

This regressed in Fx 106.0.5 and TST 3.9.8.

I determined that the optional perms were reset (confirmed in two profiles):

![image](https://user-images.githubusercontent.com/895588/200137905-86089a15-a4f1-4b11-8010-7a980819221d.png)

And the options UI was not prompting for them when clicked:

![image](https://user-images.githubusercontent.com/895588/200138042-d2aab2fc-9033-4f26-a8c3-c8b2852b5445.png)

It had to be regranted via the permissions tab.

Also please link to or explain the optional perms. They may all have been reset and I'd like to know what they're for to decide if I should regrant the others.

**Comment by piroor** [comment]
@bughit  Thanks, I've confirmed that and introduced some changes to fix the ability to request bookmarks permission at the situation.

**Comment by bughit** [comment]
@piroor 

> please link to or explain the optional perms. They may all have been reset and I'd like to know what they're for to decide if I should regrant the others.

**Comment by piroor** [comment]
I added a checkbox at the section to request bookmarks permission. It is synchronized with others in the options page.

**Comment by bughit** [comment]
We're miscommunicating. I'll try to restate.

![image](https://user-images.githubusercontent.com/895588/200179331-53e62b4d-b442-4643-ac11-05bdfa124dfd.png)
The optional perms should be documented (what functionality do they enable). I know what the bookmark one is for, not the others. Do you already have a page for them? If not please add one.

**Comment by piroor** [comment]
OK I  got it. Sorry for my misunderstanding. Currently it is described only at the startup page which is accessible via the startup notification at the initial install. You can access it with the URL: `ext+treestyletab:startup`

On old versions the startup page was opened at a tab automatically but today it is hidden behind the notification. It was claimed as violating addon policy on the AMO website: recommended addon should not open needless startup page.

**Comment by piroor** [comment]
There is an exception: "Hide and show browser tabs" is not required for regular use and TST has no description about it. It is required only for automated tests.

I think Firefox should provide ability to add metadata to describe purpose of permissions via common UI across addons...
