### ISSUE TITLE
[Enhancement] Use group-tab titles when bookmarking tree

### ISSUE THREAD

**Issue by HifeFish** [piroor/treestyletab#3205]
## Abstract

When a tree starts with a group-tab and is bookmarked, the folder should be named after the group-tab instead of the next tab in the tree. The group-tab title is usually more relevant as a description of the whole group than the title of the next tab, which might also be excessively long and hide the relevant information at the very end. In my case it is either the name of a bookmark folder that was loaded as a tree or a manually created and named group. I don't know of another situation where group-tabs would show up and not have the more relevant title.

## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Create a folder named EXAMPLE with some bookmarks
 4. Load that folder as a tree (a top-level group-tab titled EXAMPLE is created)
 5. Bookmark that Tree

## Expected result

The suggested name for the bookmark folder is EXAMPLE (CURRENT DATE).

## Actual (present) result

The suggested name is "FIRST TAB TITLE and more (CURRENT DATE)."

## Environment

 * Platform (OS): Ubuntu 20.04, Gnome 3.36.8, X11
 * Version of Firefox: 104.0 (64-Bit)
 * Version (or revision) of Tree Style Tab: 3.9.2

**Comment by piroor** [comment]
OK, done with recent commits.

**Comment by HifeFish** [comment]
Thanks, that was fast. 
One more thing I would like is to also append the current date to the folder name, but this is already great.

**Comment by piroor** [comment]
I've introduced new placeholders `%ANY()%` (filled with the first effective value) and `%GROUP%` (filled with the title of the first group tab).

>  One more thing I would like is to also append the current date to the folder name

You can do that with these placeholders, like: `%ANY("%GROUP%", "%TITLE% and more")%  (%YEAR%.%MONTH%.%DATE%)`

**Comment by SHHSSH** [comment]
The %MILLISECONDS% had me laughing, thanks for all you do piroor.

%ANY("%GROUP%", "%TITLE% (+more)")% %SHORT_YEAR%/%MONTH%/%DATE% %HOURS%:%MINUTES%
Works perfect!

I'll close my request.
