### ISSUE TITLE
[Feature Request] (Date & or Time to Bookmarked Tree Title)

### ISSUE THREAD

**Issue by SHHSSH** [piroor/treestyletab#3209]
Hello again @piroor, hope all is well in your neck of the woods.

3.9.3 (2022.9.19):

    Use the name of the parent "group tab" as the default folder name for the "Bookmark This Tree" command, if possible.

I was wondering if at all possible you could create a function where the current date & or time is embedded into the bookmarked tree's title.
This would be an incredible productivity boost for someone like me who often saves categorised, foldered trees whilst _manually_ adding the date to each folder.

This may seem redundant for many, as sure, Firefox offers bookmark sorting via date modified/added etc. however, this does not allow one to search with string queries, it merely sorts huge amounts of bookmarks via the relevant date. This becomes painfully tedious when backtracking brainstormed projects/ideas.

Thank you for all you do and the consideration.

**Comment by piroor** [comment]
With recent commits 856c37c126dd3d0d57f776758a22fb2faf6c84e5 and bf08965f4454e9a1cc3d2d5628be16af3b1188e5 now TST accepts `%ANY()%` and `%GROUP%`. `%ANY(%GROUP%, "%TITLE% and more")% (%YEAR%.%MONTH%.%DATE%)` will work for both group tab and regular tab. Moreover, I've added more placeholders `%HOURS%`, `%MINUTES%`, `%SECONDS%` and `%MILLISECONDS%`. I think they can work as you described.
