### ISSUE TITLE
dragging from tab to bookmarks not working in FF 17

### ISSUE THREAD

**Issue by mausalimi** [piroor/treestyletab#321]
as the title says. try to drag a tab to the bookmarks, not much happens.

using the newest TST and FF17, on a clean profile.

BUT workes fine up to FF16

not funny anymore... why do those people @mozilla change things like this all the time?? i will switch to the ESR version, once v17 ESR comes out.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
