### ISSUE TITLE
[Bug] Resizing side pane horizontally no longer works

### ISSUE THREAD

**Issue by DimitryAndric** [piroor/treestyletab#3211]
## Abstract

As of recently, resizing the side pane with Tree Style Tab does not seem to work anymore. I have no idea whether this is due to a recent Tree Style Tab update, or due to a recent Firefox Nightly update. I only noticed this today when attempting to made the Tree Style Tab pane wider.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Show TST in side pane
 4. Attempt to make side pane wider by dragging divider
 5. An empty 'gray' area is shown, but the tabs themselves do not resize

Before:

<img width="483" alt="resize-before" src="https://user-images.githubusercontent.com/9060368/192496064-f3c3ee6c-16e3-4e8a-b174-5c948e413b04.png">

After:

<img width="570" alt="resize-after" src="https://user-images.githubusercontent.com/9060368/192496100-15ee8656-3362-463f-94b4-d0876ff65b08.png">

## Expected result

Tabs show resize with the divider

## Actual result

Tabs ignore any resizing

## Environment

 * Platform (OS): macOS 12.6
 * Version of Firefox: 107.0a1 (2022-09-26) (64-bit)
 * Version (or revision) of Tree Style Tab: 3.9.5

**Comment by DimitryAndric** [comment]
FWIW, with TST 3.9.5 on Firefox 105.0.1 (64-bit) resizing does work correctly, so it must be some regression in Firefox Nightly. I'll see if I can find where it broke.

**Comment by piroor** [comment]
Confirmed on Windows 10, Nightly 107.0a1.

**Comment by DimitryAndric** [comment]
Working: https://ftp.mozilla.org/pub/firefox/nightly/2022/09/2022-09-22-09-56-47-mozilla-central/
Failing: https://ftp.mozilla.org/pub/firefox/nightly/2022/09/2022-09-22-21-44-29-mozilla-central/

**Comment by piroor** [comment]
I've tried bisection with mozregression-gui. It says:

```
2022-09-27T19:27:58.368000: DEBUG : Found commit message:
Bug 1789168 - Use modern flexbox emulation in the main browser area. r=Gijs

Now that DevTools splitters work this should be doable.

Differential Revision: https://phabricator.services.mozilla.com/D156385
```

**Comment by piroor** [comment]
Oh, it is already tracked:

1792277 - Sidebar doesn't correctly reflow when resized
https://bugzilla.mozilla.org/show_bug.cgi?id=1792277

**Comment by DimitryAndric** [comment]
OK, so there's really not much more that can be done from the TST side, and maybe we should close this ticket? Or otherwise keep it open for others to find more easily.

**Comment by piroor** [comment]
I hope to keep this open until the related Firefox bug become closed.

**Comment by DimitryAndric** [comment]
﻿﻿Fixed in https://hg.mozilla.org/mozilla-central/rev/97e0c3328eee, problem no longer occurs in Firefox Nightly 107.0a1 (2022-09-28) here.

**Comment by MonkAlex** [comment]
Have this problem on 107 released firefox (x64) version and 3.9.10 tst version.
Windows11.

**Comment by piroor** [comment]
@MonkAlex If you use a userChrome.css hack, here is a workaround: https://github.com/piroor/treestyletab/issues/1373#issuecomment-1317546292

**Comment by MonkAlex** [comment]
@piroor sorry, but i am not understand.
Workaround just set minimal width, but close button unvisible when width lower then 200:
![lower](https://user-images.githubusercontent.com/6784764/202807959-57f5b13e-009e-4ed4-83f5-6fa2bd83c7c5.png)![full](https://user-images.githubusercontent.com/6784764/202807994-5ae6f49a-d310-4ecb-b40a-ab1f0f25937f.png)

**Comment by stevleibelt** [comment]
Same issue on arch linux (6.0.10-arch2-1) with firefox 107.0 (64 bit) and tst 3.9.10.

![image](https://user-images.githubusercontent.com/2287220/204370529-ca70b813-995b-4cd8-aa6f-712bcd9eee24.png)

**Comment by piroor** [comment]
Please try clearing `xulstore.json` in your profile. I saw a case solved with the method. The file stores UI sizes in Firefox, and Firefox may store/restore old information unexpectedly. The problem can happen when a width value is wrongly applied to a UI element which  is not resizable anymore.

**Comment by stevleibelt** [comment]
@piroor fixed the issue on my environment too (arch linux 6.0.11, firefox 107.0.1).

**Comment by irvinm** [comment]
Just some info from Mozilla on the topic:  (I didn't know about xulstore.json, so I looked into it)

https://support.mozilla.org/en-US/kb/firefox-support-troubleshooting-guide#w_reset-the-xulstore-json-file

![image](https://user-images.githubusercontent.com/979729/206705231-a48b8b1c-c6d6-4b24-be58-7b7d93bc0468.png)

**Comment by SHHSSH** [comment]
Dunno if any of you guys have custom css settings set for your sidebar,

Though post FF 107 versions the css title for sidebar has been changed to #sidebar-box

/* remove maximum/minimum width restriction of sidebar */
#sidebar-box {
max-width: none !important;
min-width: 0px !important;
}

Trying adding this to your userchrome.css to see if it helps at all, along with maybe a fresh TST install.
