### ISSUE TITLE
[Enhancement] Open new tab as independent tab but insert after current root

### ISSUE THREAD

**Issue by kenkuo** [piroor/treestyletab#3217]
## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set "New Tabs not from Existing Tabs" setting to "an independent tab"
 4. Create a tree with a child and select the child tab
 5. CTRL+T

I would like a new option to insert the new tab as an independent tab but not have it go to the end of the tree. Instead it would insert as the next sibling? of the current root/independent tab. Essentially mimicking `browser.tabs.insertAfterCurrent = true` setting but as an independent tab.

## Expected result
![image](https://user-images.githubusercontent.com/5104436/193627232-759df9eb-345a-498f-998b-12678c02e09e.png)

## Actual (present) result
![image](https://user-images.githubusercontent.com/5104436/193627424-d72c29eb-98b4-44e2-8c2c-977982ed1c8b.png)

**Comment by piroor** [comment]
We don't need to introduce a new option.

* TST Options => "New Tabs not from Existing Tabs" => "Basic control for New Blank Tabs" => "Open new blank tab as" => "(no control)"
* about:config => set `browser.tabs.insertAfterCurrent` to `true`

This combination should work as you described. However I've fond a bug on this usecase: when a new tab is opened at middle of an existing tree by clicking on the new tab button in the sidebar, TST doesn't attach the new tab to the tree based on its inserted position. The commit a2730d5 should fix it.

**Comment by kenkuo** [comment]
Hi, thanks for the quick reply. I'm now using the build from here: https://github.com/piroor/treestyletab/actions/runs/3176608394
and also using "no control" setting for new tabs with `browser.tabs.insertAfterCurrent` = `true`

I believe what the current behavior is with these settings is that the new tab (red arrow) will match its depth with the depth of the tab below the current tab (highlighted yellow). I'm intending to have a new tab always be at root level. Let me know if I am missing a setting to get this behavior.

### Case 1
Before new tab:
![image](https://user-images.githubusercontent.com/5104436/193695238-0a18dd46-546d-4c44-a4b0-5271bcd83ef5.png)

Actual:
![image](https://user-images.githubusercontent.com/5104436/193694551-56862bf3-73e6-43ae-91f8-f69e60000878.png)

Expected:
![image](https://user-images.githubusercontent.com/5104436/193694607-c6fa61c2-0af4-40fd-b75e-833162ee9b0d.png)


### Case 2
Before new tab:
![image](https://user-images.githubusercontent.com/5104436/193695437-bbaf1454-da86-41d2-8276-b0c65c4ab3f4.png)

Actual:
![image](https://user-images.githubusercontent.com/5104436/193694738-cd28dc02-827d-4985-ac79-ccb5a73732c0.png)

Expected:
![image](https://user-images.githubusercontent.com/5104436/193694771-2acc5084-a2fe-4602-8841-c2337db25bd6.png)


### Case 3
Before new tab
![image](https://user-images.githubusercontent.com/5104436/193695693-74a04991-ef8c-4ef9-9af5-492a6867cf17.png)

Expected == Actual:
![image](https://user-images.githubusercontent.com/5104436/193694921-928082c9-f2e5-4e8c-8666-bf2586c72e9e.png)

**Comment by piroor** [comment]
The combination of "no control" and `browser.tabs.insertAfterCurrent`=`true` just provides ability to open a new tab next to the active tab. TST just attaches the opened tab to existing tree to prevent breakage of tree structure. The behavior you described at the previous comment need to be implemented specially, but sorry I have no plan to implement it as a built-in option because it looks too hard to describe as a choice of existing option.

I've implemented a new notification type API `try-handle-newtab`.
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#suppress-handling-of-new-tabs-by-tst
When a helper addon listens it and returns `true`, TST will abort its new tab handling, so the helper addon can place the new tab as you want. If you seriously want the behavior you can create a helper addon overriding TST's behavior.

**Comment by meedstrom** [comment]
I also desire this behavior.  For how to describe the option, "insert after current tree" seems pretty straightforward.

@kenkuo did you manage to create some helper addon?

**Comment by kenkuo** [comment]
Yes, I did. https://addons.mozilla.org/en-US/firefox/addon/tst-insert-as-next-sibling/

**Comment by kenkuo** [comment]
> I also desire this behavior. For how to describe the option, "insert after current tree" seems pretty straightforward.
> 
> [@kenkuo](https://github.com/kenkuo) did you manage to create some helper addon?

Yes, I did:
https://addons.mozilla.org/en-US/firefox/addon/tst-insert-as-next-sibling/
