### ISSUE TITLE
Pinned tab switching by Alt+<number>

### ISSUE THREAD

**Issue by fargred** [piroor/treestyletab#322]
When tree-style-tab is activated Alt+1 switches to first non-pinned tab Alt+2 — second non-pinned and so on. But I’d like to use it for pinned tabs, as I pinned them to switch fast. Is it wrong behavior of this add-on or can it be fixed by option somewhere inside of the browser configuration?

**Comment by piroor** [comment]
Anyway TST doesn't touch to codes around keyboard shortcuts to focus to each tab via Ctrl-(numbers). I believe that this is caused by another addon or something...
