### ISSUE TITLE
[Bug] "Default" selection in "New container tab" menu opens wrong container

### ISSUE THREAD

**Issue by keegan-lillo** [piroor/treestyletab#3229]
## Abstract

When choosing the "Default" option in the "New container tab" menu, and the user also has the "Inherit from current tab" container setting for the "Basic control for new blank tabs" section, the tab will still open in the existing tab.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set the "Inherit from current tab" container setting for the "Basic control for new blank tabs" in the TST add-on settings
 ![image](https://user-images.githubusercontent.com/3537963/195764172-b34a6ea6-5f28-441c-9e2d-33a25e6b8850.png)
 4. Create a new tab container
 5. Open a tab in the container
 6. Click the "Default" option in the "New container tab" menu
![Screen Shot 2022-10-14 at 3 34 02 pm](https://user-images.githubusercontent.com/3537963/195765078-16d51d27-7009-4073-a38e-7871ea5936e8.png)

## Expected result

New tab is opened with no container

## Actual result

New tab is opened with the current tab's container 

## Environment

 * Platform (OS): MacOS 12.6 (21G115)
 * Version of Firefox: 106.0b9 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.9.6

**Comment by piroor** [comment]
Thanks, the commit 9198644 should fix this.
