### ISSUE TITLE
[Enhancement] mouse gesture to "Close this tree"

### ISSUE THREAD

**Issue by joshgold22** [piroor/treestyletab#3230]
Could we add a one-step mouse gesture to "Close this Tree" without selecting/loading the tab or using the context menu?  
For example: option-click on the "X" close button of the tab.

## Environment

 * Platform (OS): OSX 12.6
 * Version of Firefox: 106.0.3
 * Version (or revision) of Tree Style Tab: 3.9.6

**Comment by irvinm** [comment]
I think the better ask here is for an addon like Gesturefy (https://addons.mozilla.org/en-US/firefox/addon/gesturefy/) to add support for TST.  Adding gestures to TST doesn't feel like part of the goals of this project.  @piroor I am sure will weigh in on this.

**Comment by joshgold22** [comment]
@irvinm hoo, I myself would find that to be too much and probably wouldn't install something like it.  I see some users may want a lot of gestures to control access a lot of actions, but I was just noticing that Close this Tree is special in that it's hard to access (e.g., by shortcut) without loading the tab, and might benefit from a modifier click in the sidebar.  

(I'll grant you, exploring just now, that there are others that could be similar, for instance I just tested it and saw that expand-all/collapse-all aren't supported with the typical option-click on the twistie, so perhaps this is more of a pandora's box than I'm understanding.)

Ok, and actually I apologize I didn't find it earlier: we 3 have had this conversation in the past, I'm sorry about that.
See: #2905

**Comment by joshgold22** [comment]
And just to clarify @irvinm are you saying that gesturefly can do this now in conjunction wth TST or that something like it could be implemented.  (And, would TST-more-tree-commands be a place to consider it?  Is that project a place for ways to access commands, or just including more commands?)

**Comment by irvinm** [comment]
> And just to clarify @irvinm are you saying that gesturefly can do this now in conjunction wth TST or that something like it could be implemented. (And, would TST-more-tree-commands be a place to consider it? Is that project a place for ways to access commands, or just including more commands?)

I'm pretty sure that they would not work in conjunction at this point in time.  The concept of "close this tree" is much more TST centric (or really any sidebar addon that supports trees of tabs).

The basic "need" is to track mouse movements and map them to TST actions (TST native, TST-more-tree-commands, or something the helper addon does manually).  Given Gesturefy already tracks mouse movement and can map them to items, it would just need to integrate with one of the TST addons ... or TST would need to add mouse tracking which I don't believe is in-line with the goal of the project.

Either way, there is clearly some work to be done ...

**Comment by irvinm** [comment]
... and just as I wrote that, I do see that Gesturefy DOES support sending messages to other addons as one of the options that can be tied to a mouse movement.  

If you look over https://github.com/Robbendebiene/Gesturefy/wiki/Send-message-to-other-addon there are some examples of what can be done with TST already.  (See https://github.com/piroor/treestyletab/wiki/API-for-other-addons for TST commands)

![image](https://user-images.githubusercontent.com/979729/195922550-78a427dd-374e-40e0-bd61-cf3f3e82099f.png)

**Comment by joshgold22** [comment]
> The basic "need" is to track mouse movements and map them to TST actions

Is that definitely the case?  Do we need to track mouse movements to get/use clicks with modifiers?
Having the whole apparatus for tracking movements seems like it could be very cpu-heavy as well.

**Comment by joshgold22** [comment]
(Also not clear that gesturefly could detect clicks on twisties or close-x's.  Could it even map an action to a specific *tab* in the sidebar where the mouse is hovering, or is it more global, i.e., draw a J to trigger a global command like close-current-tab, versus close-this-tab-here)

I'm still curious about the gesturefly integration, since it seems a nice addition to the global keyboard shortcuts given the two APIs are there and could talk, but I'm not sure it solves what I'm looking for (and it's not my style of interaction, personally)

**Comment by irvinm** [comment]
I don't think Gesturefy can do anything directly in the sidebar.  All of its actions (I believe) are on the main page itself.  Therefore if you were on a tab in TST that had children and it was expanded, you would draw a gesture on the main page while holding down the right mouse button, Gesturefy would capture that action, map it to a "Send message to other addon" message and send it to TST to ... Ex: "collapse that tree".  

Gesturefy would not have any knowledge if that was appropriate and\or possible, but let TST handle the request.

If you wanted to do gestures in the sidebar when TST was loaded, that would have to be implemented directly from TST and @piroor would have to add that functionality.

**Comment by joshgold22** [comment]
Ok, I appreciate that — in that case I think Gesturefly is not on the mark for what I'm looking for, which is (for instance) to be able to scroll through the sidebar tab-list without changing the active tab and close the trees I'm no longer interested in.

**Comment by piroor** [comment]
FYI: [TSTのタブを閉じるボタンの挙動を変更 (tst-change-close-tab-button-be)](https://addons.mozilla.org/firefox/addon/tst-change-close-tab-button-be/) allows you to close the parent and its all descendants with a middle click on the closebox of a parent tab, whether the tree is expanded or collapsed. I think it is very similar to the feature you initially described.

**Comment by piroor** [comment]
Anyway I won't add this as a built-in option. Basically I'm negative to add rich options to TST.

**Comment by joshgold22** [comment]
That extension sounds close to perfect, but unfortunately it doesn't seem to work for me.  With or without the extension enabled, middle-clicking anywhere on the sidebar tab brings up the standard context menu, including on the close button.

That's information for others reading this, though (perhaps someone can confirm if they can get it to work.  I would file an issue, but can't because of the language.)   
I respect your decision!

**Comment by irvinm** [comment]
@joshgold22, you have to middle-click on the close "x" to close the tree.  It worked for me.

**Comment by joshgold22** [comment]
Ah, sorry, I just realized middle click is different from "secondary click"/control-click.  I'm on a mac, and it appears you need to run extra software to generate a middle click (e.g., bettertouchtool, or more specialized apps that just enable middle-clicking specifically.)  Thanks for checking that it worked @irvinm

**Comment by piroor** [comment]
I think that supporting Ctrl-click is good option for the helper addon, and requesting the feature to the addon author looks reasonable. Here is the issue tracker of the addon:
 https://github.com/rinsuki/tst-change-close-tab-button-behavior/issues

**Comment by joshgold22** [comment]
@piroor Do you think it would be fine for me to post the request in English?

**Comment by piroor** [comment]
@joshgold22  I've looked at activities of the author and there are some conversations in English, so I think they will accept English comments.

**Comment by piroor** [comment]
BTW the addon looks hard to find out for people who don't use  Japanese language because it has only descriptions in Japanese, thus I've created a pull request to localize it.
https://github.com/rinsuki/tst-change-close-tab-button-behavior/pull/1

**Comment by joshgold22** [comment]
That's great (localization) thanks for doing that.

**Comment by joshgold22** [comment]
I noted a workaround here:
https://github.com/piroor/treestyletab/issues/2905#issuecomment-1589870099
