### ISSUE TITLE
[Bug] Visual jank when the mouse moves into the tree "gutter"

### ISSUE THREAD

**Issue by jaydub** [piroor/treestyletab#3231]
## Abstract
When enough tabs are open to cause the sidebar to need to install a scroll bar, moving the mouse into the "gutter" between tab entries and the edge of the sidebar where the scroll bar lives causes the whole tree to "jank" about a 1ex to the right.

## Steps to reproduce

 1. Start Firefox with clean profile
 2. Install TST.
 3. Open enough tabs to cause the sidebar to need to add a scroll bar (and/or shorten the height of the browser window to achieve the same)
 4. From the browser pane, move the mouse pointer horizontally onto some tab in the tab tree
 5. Continue moving the mouse pointer horizontally past the favicon and the edge of the tab
 6. The tab should have change background colour indicating it's element size; before reaching the left most edge the whole tree displaces to the right by approximately a character width
 7. Continuing to move the mouse pointer horizontally to the left will eventually cause the sidebar scroll bar to appear, but this pops out from the left as an overlay and doesn't further displace any elements
 8. Once the mouse pointer continues left and passes over the scroll bar to either the window border or outside the window, the tabs snap back to their previous position.
 
 All built in themes have the same behaviour except the "No decoration" theme.

## Expected result

No right displacement; the tabs stay put, even when the scroll bar is reached.

## Actual result

Jank :-(

I'm more sensitive to this that the typical user as I have my sidebar to the left, so I'm always passing through the "jank" zone. 

## Environment

 * Platform (OS): Kubuntu 20.04 (focal) , Debian 11 (bullseye)
 * Version of Firefox: 104.0, 102.3.0esr
 * Version (or revision) of Tree Style Tab: 3.9.6 (on each; but it likely started happening about 3.9.0)

**Comment by rebeccaj** [comment]
Thank you, jaydub, for explaining it so thoroughly. Developers, please fix this - it is annoying, irritating, and distracting.

**Comment by piroor** [comment]
There are expert options to control the behavior (TST Options => turn on the checkbox "Unlock Expert Options" to show them). "Appearance" => "Shift tabs aside 0.5em (by default) to keep in-tab buttons touchable avoiding covered with the auto-shown scrollbar" and "Shift tabs only when the mouse cursor is near the scrollbar"

**Comment by jaydub** [comment]
Perfect. That's the setting to fix the problem. Hopefully other folks affected by it will find this issue.
