### ISSUE TITLE
[Performance regression after eb9f748] Sidebar takes longer time to react to left mouse button click

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#3232]
Hello!
Commit eb9f748b223531ff18e7656be903a6a686af4dca introduced the performance regression: the sidebar takes longer time (1-1.5 sec) to react to left mouse button click on any tab with big number of tabs open.

STR (windows 10, Nightly 16-10-22, i5 8400 desktop CPU):
Create new profile, install TST from last good commit 54150d4f53112418600cf4765d5d1bea60c90dec, 2500 tabs open, left click on any tab
Tab gets selected instanteniously just as expected

Create new profile, install TST from first bad commit eb9f748b223531ff18e7656be903a6a686af4dca, 2500 tabs open, left click on any tab
Tab gets selected with 1-2 second delay, not expected

Things get more inconvenient if you click on a collapsed stack as it takes longer time to expand as well. The lowest number of tabs performance regression starts to get difficult to recognise is in a region of 1500-2000 tabs on a i5 8400 CPU so it definetely won't affect the majority of the user base.

Last commit when bug is not reproduced: 54150d4f53112418600cf4765d5d1bea60c90dec
First commit when bug is reproduced: eb9f748b223531ff18e7656be903a6a686af4dca 
Bug is also reproduced with TST built from the latest available commit, that is 9198644bf7390e078d583020ee5c7ca95a8e01cf

**Comment by piroor** [comment]
Thanks, this was triggered by my mistake. The commit 3b265b5 should fix this.

**Comment by SXZ1** [comment]
Just updated to 3.9.7, sidebar definitely reacts faster so I think it is safe to say this bug is fixed. That was a very quick fix, thank you very much!
