### ISSUE TITLE
[Feature Request] Keep tree structure of opened bookmarks

### ISSUE THREAD

**Issue by SHHSSH** [piroor/treestyletab#3235]
Hi @piroor ,

Just wondering if there was any setting I could utilise to open bookmarked trees with their original tree structure?

Below is how the tree is structured prior to bookmarking.
<a href="https://imgbb.com/"><img src="https://i.ibb.co/wJ7dgf2/capture-009-20102022-142419.jpg" alt="capture-009-20102022-142419" border="0"></a>

Then the parameters ammended to the bookmarks' titles.
<a href="https://imgbb.com/"><img src="https://i.ibb.co/Phs1znd/capture-008-20102022-142411.jpg" alt="capture-008-20102022-142411" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>

However, when opening the bookmarked tree it flattens to a singluar hiearchy.
<a href="https://imgbb.com/"><img src="https://i.ibb.co/09gCwd0/capture-010-20102022-142953.jpg" alt="capture-010-20102022-142953" border="0"></a>

This is such a pain for research when you want to be able to restructure your brainstorm as it doesn't include sub-iteming.

Anyway, as per usual, thanks for everything you do and any help you may offer.

**Comment by piroor** [comment]
Try right-click on a bookmark folder and choose "Open All as a Tree" please. It will appear at the bottom of the context menu.

**Comment by SHHSSH** [comment]
> Try right-click on a bookmark folder and choose "Open All as a Tree" please. It will appear at the bottom of the context menu.

As always, prompt response, with little tricks I didn't even know were there.

Perfect! Thanks!

**Comment by SHHSSH** [comment]
Hi @piroor,

Sorry to disturb you again but is there anyway I could add the "Close" Cross button to the right side SPECIFICALLY in TST's Helper Addon "TST In New Window"

I do a kind of a mirroring of the window and overlay it whilst enabling click-through functions, however the cross being on the left side isn't practical as I have on the bottom left of my browser, so the right side is much easier.

I believe this is relevant to a setting that TST already has, the helper add-on just doesn't.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/C7Ggy5C/capture-011-20102022-144749.jpg" alt="capture-011-20102022-144749" border="0"></a>

I'll close this if you'd like and move it to the helper add-on's repo.

**Comment by piroor** [comment]
FYI: I've introduced some changes to restore tree structure even if tabs are opened with middle-click on a bookmark folder (if possible).

**Comment by piroor** [comment]
@SHHSSH Please don't recycle an issue to different purpose, because it will become hard to identify issues with their subject.

> Sorry to disturb you again but is there anyway I could add the "Close" Cross button to the right side SPECIFICALLY in TST's Helper Addon "TST In New Window"

Did you mean [Tree Style Tab in Separate Window](https://addons.mozilla.org/firefox/addon/tst-in-separate-window/)? You cannot do this because there is no hint to switch CSS rues for in-sidebar and in-window cases. You need to choose TST Options => "Appearance" => "Style of contents for the sidebar position" => "Left side" as the global setting.

**Comment by SHHSSH** [comment]
> @SHHSSH Please don't recycle an issue to different purpose, because it will become hard to identify issues with their subject.
> 
> > Sorry to disturb you again but is there anyway I could add the "Close" Cross button to the right side SPECIFICALLY in TST's Helper Addon "TST In New Window"
> 
> Did you mean [Tree Style Tab in Separate Window](https://addons.mozilla.org/firefox/addon/tst-in-separate-window/)? You cannot do this because there is no hint to switch CSS rues for in-sidebar and in-window cases. You need to choose TST Options => "Appearance" => "Style of contents for the sidebar position" => "Left side" as the global setting.

Thanks, dunno why it was applying to the TST and not the other, that worked.
