### ISSUE TITLE
Links opened in FVD Speed Dial don't adhere to "Tree Style Tab" add-on settings

### ISSUE THREAD

**Issue by petermac-** [piroor/treestyletab#324]
I have Tree Style Tab setup so that when I middle click on any link the new tab is nested under the source tab forming a new tree. When I middle click on a link on the FVD Speed Dial page the new tab doesn't get nested and it opens at the bottom of my Tree Style Tab list regardless of where the source tab is located.

Here is a link to the FVD Speed Dial add-on:  https://addons.mozilla.org/en-US/firefox/addon/fvd-speed-dial/?src=search

I notified the creators of FVD Speed Dial about this issue but they said they couldn't fix the problem and recommended that I post the issue here.  Here is a link to the thread I created on FVD Speed Dial's getsatisfaction page:  https://getsatisfaction.com/fvd_suite/topics/links_opened_in_fvd_speed_dial_dont_adhere_to_tree_style_tab_add_on_settings?rfm=1

**Comment by piroor** [comment]
Now TST opens new tabs from addons as children of the current tab in most cases.
