### ISSUE TITLE
[Bug] [Nightly] 2nd+ pinned tabs are shifted down and unclickable

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#3240]
## Abstract
Though this is a Nightly bug, I file this issue here just for the record and let tst users find the report easier.

On Nightly 2022-10-27 (20221027095047) build, 2nd+ pinned tabs are shifted down and unclickable. This is regressed by [Bug 1797011 - Make nsFrameList and AbsoluteFrameList be move-only](https://bugzilla.mozilla.org/show_bug.cgi?id=1797011).
There is already a regression bug filed so I did not file a separate bug for TST issue in BMO:
[Bug 1797703 - fixed positioned elements are broken on several websites](https://bugzilla.mozilla.org/show_bug.cgi?id=1797703).

## Steps to reproduce

 1. Start Nightly 2022-10-27 with clean profile.
 2. Install TST.
 3. Pin 2 or more tabs.
 4. Press F1 to close and reopen TST tabbar.

## Expected result
Pinned tabs align correctly.

## Actual result
![image](https://user-images.githubusercontent.com/771216/198322679-ebc96cc5-96a7-406f-b7ad-093f8ddc7275.png)

2nd+ pinned tabs are shifted down and I cannot select them in TST tab bar.
Sometimes the bugged pinned tabs may shift back to their intended position after some time. I cannot figure out how though.

## Environment

 * Platform (OS): Win10
 * Version of Firefox:  Nightly 2022-10-27 (20221027095047) build
 * Version (or revision) of Tree Style Tab:  3.9.7

**Comment by happy-dude** [comment]
This problem is also manifesting on macOS, albeit in a different manner.

The pinned tabs show up in the Firefox standard tab bar, but TST shows only the first pinned tab. There is no "overflow" on my system.

<img width="416" alt="Screen Shot 2022-10-27 at 11 08 03 AM" src="https://user-images.githubusercontent.com/1098725/198343704-0cdc61e9-c58e-47da-885b-a164aecf1700.png">

Firefox nightly details copy-pasted from `about:support`
```
Name 	Firefox
Version 	108.0a1
Build ID 	20221027095047
Update Channel 	nightly
User Agent 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:108.0) Gecko/20100101 Firefox/108.0
OS 	Darwin 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000
```

**Comment by happy-dude** [comment]
This looks like it has been fixed in the latest nightly:

```
Name: Firefox
Version: 108.0a1
Build ID: 20221028212211
Distribution ID:
Update Channel: nightly
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:108.0) Gecko/20100101 Firefox/108.0
```

**Comment by Fanolian** [comment]
Yes.
