### ISSUE TITLE
After Uninstalling this Addon, opening links from other apps sometimes results in extra tabs with an error message

### ISSUE THREAD

**Issue by Zillatamer** [piroor/treestyletab#3243]
The text is always something like:

ext+treestyletab:group?title=Tabs%20from%20External%20Apps&temporary=true

![image](https://user-images.githubusercontent.com/95879646/199333061-4ce35107-8786-4811-8cd4-397f36760470.png)

I'm assuming there's still some component of the addon that wasn't uninstalled, but I don't know how to fix this on my own. Any help here would be apprecated.

**Comment by Fanolian** [comment]
Do you have any other extensions that explicitly supports tst's extra features? You may have to disable those preferences.

**Comment by Zillatamer** [comment]
Thanks! I think you solved it. There were 3 TST extensions I didn't realize were installed, suppose that's the first thing I should have checked for, haha.
