### ISSUE TITLE
I had 30 or more Tabs . works very well. Until I started firefox this morning. ALL TABS have disappeared? If I set this all up again is there a way to Save the entire structure so that I don't have to waste another day rebuilding.

### ISSUE THREAD

**Issue by RJG2022** [piroor/treestyletab#3248]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
Please fill the issue template.

* TST has ability to create bookmarks from opened tabs with tree structure information. It will be an easy way to save/restore tree. Please remind that you need to call this feature manually
* TST does not provide session management features like autosave: it is beyond the project scope. You should use other session management addon compatible to TST together.

**Comment by RJG2022** [comment]
That you very much
