### ISSUE TITLE
[Bug] Excessive paint events

### ISSUE THREAD

**Issue by nirvdrum** [piroor/treestyletab#3250]
## Abstract

My Firefox instance constantly keeps the CPU going when running TST. I've narrowed down and fixed several issues already. But, I keep seeing loads of sidebar paint events. This happens even when I don't interact with the browser.  I suspect paints are being triggered when they don't need to be and they're computationally expensive.

I'm willing to help investigate, but the code base is quite large and I couldn't find a way to track down where the paint events are coming from. 

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Disable the workaround for bug 1388193 and 1421329 to rule out its CPU usage.
 4. Open a bunch of tabs in several windows.
 5. (Optionally) Put tabs to sleep.
 6. Watch Firefox's CPU usage.
 7. Record a profile with native events recorded.

## Expected result

I'd expect an idle browser to have a fairly low CPU usage. I'd expect sidebar paint events to only trigger when the sidebar needs to be repainted, which shouldn't happen too frequently with an idle browser.

## Actual result

I'm seeing at least 50% of one core running at all and using Firefox Profiler I can match up the paint events with periods of high power consumption.

## Environment

 * Platform (OS): macOS 12.6 on Apple M1
 * Version of Firefox: Firefox Developer Edition 107.0b9
 * Version (or revision) of Tree Style Tab: 70890743b465719791b2c03f90a2a1b1749e3522 (3.9.8 + dev changes)

**Comment by wsmwk** [comment]
Please post your profile link

**Comment by irvinm** [comment]
https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-collect-a-performance-profile

**Comment by nirvdrum** [comment]
I'm unable to activate the "performance" tool in the addon debugger. It's enabled, but Firefox says "Not supported for current toolbox targets". Thus, I've been using the [Firefox Profiler](https://profiler.firefox.com/docs/#/). That said, I don't want to share a profile of my entire browsing session. I've measured with an new browser profile, but staging all of the data is a large undertaking (many tabs, several windows) so as a matter of practicality, I'm running Firefox Developer edition with my primary browser profile at the moment.

I'm willing to investigate the performance on my own, but was looking for assistance in identifying which parts of TST cause the sidebar to repaint. Since the paint event is native and divorced from a method call, it doesn't show up in a JS profile.

**Comment by piroor** [comment]
The disabled "performance" tab in the debugger for addons is critical blocker on investigation. I seriously want it become enabled again...

If you still see the performance problem with old versions Firefox like ESR91 which can collect performance profile of addons, profiling with old Firefox may help us.

**Comment by irvinm** [comment]
Looks like the severity of this item just got pushed down recently.

https://bugzilla.mozilla.org/show_bug.cgi?id=1766271
