### ISSUE TITLE
[Bug] TST width adjustment no longer working

### ISSUE THREAD

**Issue by mulsambe** [piroor/treestyletab#3252]
## Abstract
It seems that since Firefox was updated to 107.0, the width of the TST pannel is no longer adjustable.

## Steps to reproduce
I have removed all other add-ons.
My TST pannel sits on the left of the screen.
When I want to adjust the width, the main window moves over TST panel and the TST tabs stay the same.

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Same result

Attached screenshot shows TST overlapped by main window instead of being adjusted.

## Environment

 * Platform: Windows 10 Professional 21H2 build 19044.2130
 * Version of Firefox: 107.0 (64 bits)
 * Version (or revision) of Tree Style Tab: 3.9.10 (2022.11.10) 
![2022-11-18_09-33-51](https://user-images.githubusercontent.com/43172360/202657463-4816b589-e405-4c48-9691-d7b5ff0af427.jpg)

**Comment by mliudev** [comment]
Looks like Firefox renamed the id of the sidebar: https://support.mozilla.org/en-US/questions/1396856

I fixed this by renaming `#sidebar` css selector to `#sidebar-box` in my `userChrome.css`:

```css
#sidebar-box {
  max-width: none !important;
  min-width: 0px !important;
}
```

**Comment by piroor** [comment]
This is invalid as an TST issue, because it is a topic about general userChrome.css customization.
