### ISSUE TITLE
[Bug] (please put summary here)

### ISSUE THREAD

**Issue by HaddadJoe** [piroor/treestyletab#3253]
## Abstract
Auto upgrade were enabled for my extension. After the upgrade, the extension stopped working displaying a blank page as show in the image below
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/13067123/202925007-e50ae9d8-deb6-4979-bb5d-79394a8d2c02.png">

## Steps to reproduce

 1. Start Firefox
 2. fresh installation of TST will show the error

## Expected result
working app

## Actual result
broken app with error 
```
XML Parsing Error: no root element found
Location: chrome://browser/content/webext-panels.xhtml
Line Number 1, Column 1:

^
```

## Environment

 * Platform (OS): MacOS
 * Firefox: 107.0 (64-bit)
 * Treestyletab: Last Updated: November 20, 2022 version 3.9.10

**Comment by irvinm** [comment]
Can you try this?

1. Open an about:support tab
2. Click the "Clear startup cache..." button and restart

**Comment by HaddadJoe** [comment]
yep that resolves the issue, thanks for the prompt reply.
