### ISSUE TITLE
Export tree tabs' structure

### ISSUE THREAD

**Issue by ravirathore** [piroor/treestyletab#3256]
Hi,

Is it possible to add this functionality:

1. Save tabs along with their tree structure and their colors(using TST-Colored-tabs https://github.com/MurzNN/TST-Colored-tabs), just like what 'tab session manager' (https://addons.mozilla.org/en-US/firefox/addon/tab-session-manager/)  add-on do.

If it cannot be included into your work pipeline, please let know which API can be used to export the tree tabs and their colors. Will try to build it.

thanks,

**Comment by irvinm** [comment]
@ravirathore, TSM already supports TST and hence stores the tab relationships.  I took a quick look at the source code for TST-Colored-tabs and it looks like it just traverses the tabs and adds the color when it finds a match based on domains specified.  Therefore, it looks to me that if you use TSM to backup and restore a "session" that you should get your tree structure restored along with your tab colors.

I am not sure why you would "need" to export all of this information from the TST side.  I might be missing something.

**Comment by ravirathore** [comment]
Hi,
Thanks for the reply. 
I wanted to store the sessions offline and look at them later.
Really sorry for the confusion.
I guess,  I need to find out tab's parent id and color it.

Can you pls let know which api can be used to fetch this details.


thanks,

**Comment by irvinm** [comment]
@ravirathore, you can get the parent tab ID by just looking at the tab's property:  `openerTabId`

So using the Firefox API [tabs.get()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/get) and looking at the returned data [tabs.Tab](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab).

In terms of the color, it looks like TST-Colored-tabs just sends CSS to TST when it finds a domain that needs to be changed.
```
     let css = `
tab-item.active tab-item-substance {filter: saturate(` + ColoredTabs.settings.activeSaturate + `%) brightness(` + ColoredTabs.settings.activeBrightness + `%);}
tab-item tab-item-substance:hover {filter: saturate(` + ColoredTabs.settings.hoverSaturate + `%) brightness(` + ColoredTabs.settings.hoverBrightness + `%);}`;

    if(ColoredTabs.settings.activeBold == true) {
      css += 'tab-item.active .label{font-weight:bold}';
    }

    for(let i = 0; i < 360; i += (360 / ColoredTabs.settings.colors)) {
      let hue = Math.round(i);
      css += `tab-item.coloredTabsHue` + hue + ` tab-item-substance {background-color: hsl(` + hue + `,` + ColoredTabs.settings.saturation + `%,` + ColoredTabs.settings.lightness + `%);}`;
    }

    if(ColoredTabs.state.hostsMatchColor !== undefined) {
      ColoredTabs.state.hostsMatchColor.forEach((element, index) => css += `tab-item.coloredTabsHostMatch` + index + ` tab-item-substance {background-color: ` + element + `;}`);
    }
    if(ColoredTabs.state.hostsRegexpColor !== undefined) {
      ColoredTabs.state.hostsRegexpColor.forEach((element, index) => css += `tab-item.coloredTabsHostRegexp` + index + ` tab-item-substance {background-color: ` + element + `;}`);
    }
    // console.log(css);

    browser.runtime.sendMessage(TST_ID, {
        type: "register-self",
        style: css,
    });
```

You would need to be able to retrieve this information from TST.  You might want to check out the information around the API.  (https://github.com/piroor/treestyletab/wiki/API-for-other-addons)  I've only passed CSS to TST, but never asked to retrieve CSS from TST.

**Comment by piroor** [comment]
FYI: here is the section about gettintg tree information of multiple tabs.
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#apis-to-get-tree-information

**Comment by ravirathore** [comment]
@piroor 
thanks
