### ISSUE TITLE
[Enhancement] Feature Request: Notes sub-panel

### ISSUE THREAD

**Issue by EdwardDrapkin** [piroor/treestyletab#3257]
Hey there,

Just wanna say that this is the best extension and the reason I've stuck with Firefox for all the years.  Now that there's a subpanel feature, is there any way we can get a simple notepad added to it?  Just an empty text field to write stuff down in, nothing special about it.  Something like [this](https://addons.mozilla.org/en-US/firefox/addon/sidebar-note/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search)?

Thanks!  And again, love this piece of software!

**Comment by piroor** [comment]
You can implement such a helper extension using TST's API.
https://github.com/piroor/treestyletab/wiki/SubPanel-API

Sorry but I have no plan to implement the notepad feature as a built-in of TST.
