### ISSUE TITLE
[Bug] Auto-Grouping from External Program no longer Auto-Grouping

### ISSUE THREAD

**Issue by LordJair** [piroor/treestyletab#3258]
## Abstract
In the past couple months, I've noticed that auto-grouping is no longer occurring when opening multiple tabs from an external program all at one time. 

## Steps to reproduce

1. In options, under New Tabs not from Existing Tabs, enable "Auto-group tabs opened at a time from non-bookmark triggers also."
2. Open multiple links at the same time from an external program.

## Expected result
A group tab is automatically inserted and all links opened from external program should become child tabs underneath this parent tab.

## Actual result
All tabs are opened flat with no automatically inserted/generated group tab.

## Environment

 * Platform (OS): Windows 10 22H2
 * Version of Firefox: 107.0 
 * Version (or revision) of Tree Style Tab: 3.9.10

**Comment by piroor** [comment]
Thanks, the commit 8a0396b should fix it.
