### ISSUE TITLE
[Enhancement] Update info in wiki

### ISSUE THREAD

**Issue by adamsonich** [piroor/treestyletab#3260]
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#slightly-betterworse-option-for-hiding-tabs-depending-on-what-you-want
Code:
`
#tabbrowser-tabs {
  visibility: collapse !important;
}
`

It can be updated/upgraded to version:
`
#tabbrowser-tabs {
  visibility: collapse !important;
  min-height: 0 !important;
}

tab{
  display:none!important;
}
`
History: 
Updating to version with "Firefox View" broke tabs visibility, showing tab (tabbrowser-tabs) with "recently closed" button only

**Comment by piroor** [comment]
The wiki is public and I hope it is maintained by users. You don't worry about permission.

**Comment by adamsonich** [comment]
I updated wiki.
Thanks
