### ISSUE TITLE
Resize Tab Titles

### ISSUE THREAD

**Issue by zsection** [piroor/treestyletab#3266]
Hi, is there a way to resize the tab titles? They're really small for me and I can't see a setting to change them. Thanks

**Comment by zsection** [comment]
completely missed the settings... :P

**Comment by piroor** [comment]
TST has no such option but you can configure the appearance via CSS.
TST Options => Advanced => extra style rules:

```css
.label-content {
  font-size: large;
}
```

![image](https://user-images.githubusercontent.com/70062/208830178-1aad0258-fb90-4593-a945-4d99eb43ebc0.png)

**Comment by piroor** [comment]
I won't add a built-in option to change font size of tabs: there is a project policy that providing options only hard to be done with CSS.

**Comment by zsection** [comment]
Great, that works! Thanks very much.
