### ISSUE TITLE
[Enhancement] (Multiple options for New Blank Tabs)

### ISSUE THREAD

**Issue by wtbutler** [piroor/treestyletab#3270]
## Abstract

Given that Firefox uses different pages for normal and private browsing (`about:newtab` and `about:privatebrowsing` respectively), I feel like it would make sense if the "Guess a newly opened tab with URL" option should have a way to input more than one URL. As it is, opening a tab and searching a term in it repeatedly will cause them to open as siblings in normal browsing, but as children of each previous in private browsing. I've tried using comma separation, semicolon separation, and spaces, but as-is it doesn't seem to have a way to use more than one URL. If it does already have a way to do so, it would vastly help if it were made clearer.

**Comment by piroor** [comment]
This should be fixed with commits 12f1742 and 0bd0e51. Thanks!
