### ISSUE TITLE
Open child tab opens independent tab[Bug]

### ISSUE THREAD

**Issue by rcrx** [piroor/treestyletab#3284]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
Too less information to reproduce the problem on my environment, or guess what happens on your environment. Please try to fill the template - it aims to assist narrowing down conditions the problem happens with.
