### ISSUE TITLE
[Tree style tab as a usr link](open tree style tab from url link)

### ISSUE THREAD

**Issue by AminSdiri** [piroor/treestyletab#3286]
Is it possible to open a tree from an URL link? it would be really helpful to save current sessions for later use as a URL link. I'm using a to-do manager that accepts text and links as reference material. It would be great if I can reference a Treestyletab of my last progress and continue from there.

## Expected result
 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open some tabs
 4. save the tree as url
 5. open the tree from the url
 6. a tree style tab from 4. opens in firefox

**Comment by irvinm** [comment]
@AminSdiri you can already save all of your tabs (including tree) by using the "bookmark this tree" feature.  However, this doesn't do exactly what you want in terms of a "single URL".

In general, TST is not a "session manager" and something like this might be better as a feature request to an addon like "Tab Session Manager" which already support exporting\saving tab sessions as JSON text files.  

A custom URL would need to be basically a "payload" of information and would need to be handled by the addon to create all of the tabs described in the payload.  In addition, there are limitations to the length of a URL and that would factor into this solution.

Given there is already a JSON export solution (amongst other ways of exporting tab information), I don't think this is likely to happen.

https://github.com/sienori/Tab-Session-Manager/milestone/6
https://github.com/sienori/Tab-Session-Manager/issues/700
https://github.com/sienori/Tab-Session-Manager/issues/678

**Comment by piroor** [comment]
@AminSdiri As @irvinm described you can use bookmarks created from a tree for the purpose. Could you try that?

In general I have no plan to implement a custom URL format to open a tree, because it looks beyond the project scope.
