### ISSUE TITLE
[Bug] New tabs opened by dropping a url on the sidebar does not follow Firefox's setting.

### ISSUE THREAD

**Issue by Kenqr** [piroor/treestyletab#3288]
## Abstract

New tabs opened by dropping a url on the sidebar are always focused, not following Firefox's `When you open a link, image or media in a new tab, switch to it immediately` setting.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Drop a url on TST sidebar.
![TST](https://user-images.githubusercontent.com/7265185/216754525-b440952f-f5da-4260-9db3-53b3a5cd9f80.gif)

## Expected result

New tab opened in background when the option `When you open a link, image or media in a new tab, switch to it immediately` is unchecked.

## Actual result

New tab opened in foreground.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 109.0.1
 * Version (or revision) of Tree Style Tab: 3.9.12

**Comment by irvinm** [comment]
Just an FYI, but I see the same behavior as you and agree it is different than Firefox itself.  @piroor will have to comment if this is due to a limitation or just a defect that needs to be addressed.

**Comment by piroor** [comment]
TST cannot know how Firefox is configured as, so I've added a new option to simulate it.
![image](https://user-images.githubusercontent.com/70062/224510747-b20cbaae-47b9-4c90-8baa-e7fe323a2295.png)
(the bottom item in the screeshot)

**Comment by Kenqr** [comment]
Works perfectly, thank you.
