### ISSUE TITLE
[Enhancement] (any way to export as csv?)

### ISSUE THREAD

**Issue by tiddu** [piroor/treestyletab#3289]

**Comment by irvinm** [comment]
Export what?

**Comment by tiddu** [comment]
> Export what?

the structure or list

**Comment by irvinm** [comment]
You can save\restore everything (include tree structure) with the addon "Tab Session Manager" ... but it won't be CSV.  You can also bookmark your tabs (including indentation) and you can restore them via TST.  In addition, there are other addons that allow you to export tab information, but I don't think most will export the parent ID which is needed to maintain the tree structure.

**Comment by piroor** [comment]
TST won't provide ability to manage session information because it is out of the project scope.
https://github.com/piroor/treestyletab#user-content-feature-requests-better-compatibility-with-session-manager-extensions-or-add-high-power-session-management-feature
