### ISSUE TITLE
[Enhancement] Provide CSS example for removing notification dot from pinned tabs

### ISSUE THREAD

**Issue by dekatzenel** [piroor/treestyletab#3290]
## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Pin a tab that gets updates that Firefox provides a background update notification dot for, such as Gmail
 4. Wait with any other tab open until update happens on website and dot appears below pinned icon

## Expected result
Add examples to https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules to remove this dot, both for all pinned tabs and for specific pinned tabs, similar to how the various answers in https://support.mozilla.org/en-US/questions/1181537 do for Firefox's built in pinned tabs

## Actual (present) result
No entry describing this change in https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules

## Environment

 * Platform (OS): macOS Ventura 13.2
 * Version of Firefox: 109.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.9.12

**Comment by irvinm** [comment]
You can do this yourself by simply inspecting the tree information to find the element you want to change.  I did that and this seems to do what you want.

```
tab-item.faviconized.unread:not(.active) tab-item-substance:not(:hover) tab-favicon::before {
	background-image: none;
}
```

Next time, you can try yourself:  https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-inspect-the-sidebar

**Comment by piroor** [comment]
@dekatzenel  The wiki is editable for everyone. I hope it is maintained by people who use it.
