### ISSUE TITLE
[Enhancement] (export part of it?)

### ISSUE THREAD

**Issue by tiddu** [piroor/treestyletab#3292]
like can we export some folders to a file and can later import? not the whole tree bcoz that can be done with that jsonlz4 file but sometimes the tree gets big. in a merging style.

**Comment by irvinm** [comment]
Again, you can bookmark a tree from TST and then restore it later whenever you want.  (TST:  "Bookmark this Tree" and then right-clicking on the folder and choosing TST:  "Open all as a Tree".)

**Comment by piroor** [comment]
It looks a FAQ topic:
https://github.com/piroor/treestyletab#user-content-feature-requests-better-compatibility-with-session-manager-extensions-or-add-high-power-session-management-feature
