### ISSUE TITLE
[Enhancement] Extend addon API 'group-tab' to optionally allow passing in the desired tab group title

### ISSUE THREAD

**Issue by frederikb** [piroor/treestyletab#3294]
### Feature Request
Extend the addon API 'group-tab' to optionally allow passing in the desired tab group title.

### Current State

When using the API as follow:
```javascript
let parentTab= await browser.runtime.sendMessage(TST_ID, {
    type: "group-tabs",
    tabs: [ 1, 2, 3]
});
```
A new tab group is created with a title based on the title of the first child tab of the newly formed group.

### Desired State

I can specify the desired tab group title when calling the API, e.g.

```javascript
let parentTab= await browser.runtime.sendMessage(TST_ID, {
    type: "group-tabs",
    title: 'My new tab group',
    tabs: [ 1, 2, 3]
});
```
### Reason

I'm building an addon (thanks by the way for making that possible!) to reorganize tabs grouped by domain and would like to make those new tab groups have the respective domain as their title.

### Impact

The change should be backwards compatible because existing addons shouldn't have been passing in additional properties to the messages send to the TST API which would have been ignored anyway.

Depending how you would (if you approve this feature request) implement it the change could be restricted to only `handle-misc.js` because `TabGroup.groupTabs` already implicitly supports overriding the automatically generated tab group title through the passed in options object.

Let me know if you need any further information or if I can help out in any other way. Thanks!

**Comment by piroor** [comment]
I've introduced the new option "title" as described with the commit 6be81b2.

**Comment by frederikb** [comment]
Works exactly as needed. Thanks a lot for the update. :)
