### ISSUE TITLE
[Enhancement] (Feature Request - Expand all disregards Locked as collapsed Trees)

### ISSUE THREAD

**Issue by SHHSSH** [piroor/treestyletab#3298]
Hi @piroor,

There has been some discussion on [Lock as collapsed](https://github.com/piroor/tst-lock-tree-collapsed) in recent years, I am happy to have suggested this feature. I hope others has utilised it to some degree.

I am looking to request for the functionality of TST to be able to recognise whether a tree is Locked as collapsed(LAC) and therefore, not expand when I use the macro for "Expand all", currently, the locked trees still expand.

Everything has been working brilliantly in recent years, ESPECIALLY, the functionality of TST skipping LAC trees with Ctrl+Tab/Shift+Tab.

I am endlessly appreciative of your tireless efforts mate, just that if this function was implemented it would save me time having to manually collapse all the groups again, other than say the ones that weren't LAC that I could optimise accordingly to be the only ones expanding when I expand all.

Thanks for your consideration.

**Comment by SHHSSH** [comment]
Expand/Collapse all is one of the most used macros of mine, it's on my mouse even.

I often wonder if the "Recursively" suffix was some form of a solution to this, though I could never get it to work, or really determine its true use-case.

**Comment by piroor** [comment]
OK, I've introduced new notification types `try-expand-tree-from-expand-command` and `try-expand-tree-from-expand-command`:
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#suppress-unintentional-expansion-of-collapsed-tree-by-tst

I've also updated TST Lock Tree Collapsed to use the new API. Introduced new features are:

* Allow blocking of expansion of locked tree by TST's built-in "Expand this Tree recursively" and "Expand All". (default=off)
* New context menu commands "Expand this Tree Except Locked" and "Expand All Except Locked". (default=off)

**Comment by SHHSSH** [comment]
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#suppress-unintentional-expansion-of-collapsed-tree-by-tst

What is the expected result? And what am I meant to do to introduce those commands?

Basically, just as clarification so we're on the same wave length, is what you're linking relevant to "Expand all" affecting LAC trees? Essentially what I am confused about is if there's the function to keep collapsed LAC trees, as collapsed, even with "Expand all" ?

Sorry for any confusion, I am unfamiliar with what to do with those commands.

**Comment by piroor** [comment]
Sorry I pended releasing of updated TST Lock Tree Collapsed, because its new blocking for TST's built-in "Expand this Tree recursively" and "Expand All" is depending on TST 3.9.14 which is under review. Its extra commands "Expand this Tree Except Locked" and "Expand All Except Locked" commands are available on older TST, so I've released TST Lock Tree Collapsed 1.2.0.
