### ISSUE TITLE
[Enhancement] Conditionally show/hide TST for windows that are taller than they are wide

### ISSUE THREAD

**Issue by dhorkin** [piroor/treestyletab#3300]
## Abstract

I have two monitors; one is oriented vertically, the other landscape (like most people).

TST is great when I'm on my normal 16:9 monitor. But when I'm on my 9:16 monitor, vertical tabs take up critical screen real estate.

There's an addon I use called [Paxmod ](https://github.com/numirias/paxmod)that allows you to have multiple tab rows at the top of your screen.

I created a request over there to add ability to conditionally switch behavior. https://github.com/numirias/paxmod/issues/108

I'm not sure whether some of this functionality would be better suited for implementation in TST as opposed to Paxmod, so I'm creating a semi-duplicate issue here of the one there.

## Steps to see the situation

 1. Start Firefox Developer edition (required for Paxmod)
 2. Install Paxmod
 3. Install TST
 4. note that when both are enabled, a huge amount of space is wasted

## Expected result (Desired behavior)
When I'm on my Portrait monitor / a window that is significantly taller than it is wide:
- automatically close `TST` if open (but leave other sidebars open)
- normal Paxmod behavior (titlebar disabled, multiple tab rows)

When I'm on my Landscape monitor / :
- I would like to automatically open `TST` sidebar
- replace Paxmod's tab rows the default Firefox titlebar (i.e. window title plus minimize/maximize/close buttons). Likely would need to be implemented on Paxmod side.

## Actual (present) result
![image](https://user-images.githubusercontent.com/59899746/223305206-3dc4114d-7059-4fac-9830-3b401b770c24.png)

## Environment

 * Platform (OS): 
 * Version of Firefox: 111 (Developer version)
 * Version (or revision) of Tree Style Tab: 3.19.12

**Comment by piroor** [comment]
This feature never be included into TST, sorry.

We need to implement a custom WebExtensions API with experiments to toggle visibility of the sidebar aggressively, but it is out of scope of TST: it is a pure  WebExtensions add-on project. I'm negative to introduce dependency to specific version of Firefox.
