### ISSUE TITLE
[Enhancement] There still horizontal space after hide horizontal tabs at the top of windows

### ISSUE THREAD

**Issue by eldon922** [piroor/treestyletab#3301]
## Abstract
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-horizontal-tabs-at-the-top-of-the-window-1349-1672-2147. 

can we remove the horizontal space?

## Steps to see the situation

 1. hide the horizontal tabs like in the link that i mention above
 2. run firefox

![image](https://user-images.githubusercontent.com/19554521/224292302-8fc1aa64-8488-4fa3-8b96-0bbd621f0c2b.png)

## Expected result
there is no any space

## Actual (present) result
there are still horizontal space

**Comment by irvinm** [comment]
Which of the solutions have you tried?  There are several in that section of the wiki you reference.  I see there is one that is for FF106 (recently updated) ...

**Comment by irvinm** [comment]
Also, given this is not TST specific, you could also check https://www.reddit.com/r/FirefoxCSS/ for newer\different solutions.  (If there really is something wrong in the wiki, please feel free to edit with updated\newer information)

**Comment by eldon922** [comment]
okay thank you. i have already try to tweak the css from that and i got the solution by changing the height in this code to 0
```/* 15px for dragging whole window by mouse*/
#titlebar {
	appearance: none !important;
	height: 0px;
}
```
and add this code if we want to change the height of close button to make it same as the address bar
```
  .titlebar-close {
    height: 40px;
  }
```
