### ISSUE TITLE
[Enhancement] Auto hide collapsed tree tabs in "native tabs bar"

### ISSUE THREAD

**Issue by QORTEC** [piroor/treestyletab#3303]
## Abstract
Auto hide collapsed tree tabs in "native tabs bar"

## Steps to see the situation
 1. Start Firefox with clean profile.
 2. Install TST.
 3. create a tree
 4. collapse the tree

## Actual (present) result
Tabs in the "native tabs bar" are unchanged.

## Expected result
Collapsed tabs are hidden in the "native tabs bar" (default tabs bar at the top of Firefox)

## Additional Interactions for proposed enhancement
- Auto expand tree on tab focus (native tabs bar)
  - option always true, false, none
  - option "next level" or "full tree" 
- Auto collapse tree on tab focus loss (native tabs bar)
  - option always true, false, none
  - option auto collapse only on auto expand

## Environment
 * Platform (OS): Solus OS (Linux)
 * Version of Firefox: 108.0.2
 * Version (or revision) of Tree Style Tab: 3.9.12

**Comment by piroor** [comment]
Here is my comment why I don't introduce this behavior: https://github.com/piroor/treestyletab/issues/2696#issuecomment-682653947

> There are some my past comments describing risks when TST hides tabs in Firefox's native tab bar:
> 
> [#1831 (comment)](https://github.com/piroor/treestyletab/issues/1831#issuecomment-373618534) [#1371 (comment)](https://github.com/piroor/treestyletab/issues/1371#issuecomment-491575613)
> 
> In short: Tabs hidden when they are just collapsed will introduce compatibility issues with other tab addons and Firefox's native behavior (because hidden tabs are treated as unexisting by Firefox itself.) Thus I decided that I don't introduce this change.

**Comment by QORTEC** [comment]
Thank you for the quick response, I agree 100% that introducing incompatibility is something TST should avoided. 
Are there any architectural issues that would prevent implementing this feature in a TST addon extension?

> Firefox's native behavior (because hidden tabs are treated as unexisting by Firefox itself.)

If you could point me towards more information on this behaviour i would like learn about it in my spare time.

**Comment by piroor** [comment]
> If you could point me towards more information on this behaviour i would like learn about it in my spare time.

The implementation of "gBrowser.visibleTabs" in Firefox:
https://searchfox.org/mozilla-central/rev/2ede53e39955988f98db4369f7ce09614b22104a/browser/base/content/tabbrowser.js#295
https://searchfox.org/mozilla-central/rev/2ede53e39955988f98db4369f7ce09614b22104a/browser/base/content/tabbrowser-tabs.js#1048

Callers:
https://searchfox.org/mozilla-central/search?q=symbol:%23visibleTabs&redirect=false
https://searchfox.org/mozilla-central/search?q=symbol:%23_getVisibleTabs&redirect=false
There are 50 codes referring visible tabs.

**Comment by QORTEC** [comment]
Thanks, closing this issue since its marked as _wontfix_.
