### ISSUE TITLE
[Enhancement] Is there a way to increase twisty size?

### ISSUE THREAD

**Issue by eldon922** [piroor/treestyletab#3304]
it's too small, hard to click it

**Comment by irvinm** [comment]
```
tab-item tab-twisty {
  scale: 1.25;
}
```

Or check out original CSS and modify as you like:  https://github.com/piroor/treestyletab/blob/d4654ad52b09590b3a47a0676c7b34ee6cce6ac1/webextensions/sidebar/styles/twisty.css

**Comment by eldon922** [comment]
> ```
> tab-item tab-twisty {
>   scale: 1.25;
> }
> ```
> 
> Or check out original CSS and modify as you like: https://github.com/piroor/treestyletab/blob/d4654ad52b09590b3a47a0676c7b34ee6cce6ac1/webextensions/sidebar/styles/twisty.css

thank you so much!
