### ISSUE TITLE
[Enhancement] How to vertical centered new tab icon?

### ISSUE THREAD

**Issue by eldon922** [piroor/treestyletab#3305]
I increase the height of new tab button using below css but the icon placed at the top of the box. how to get it vertical centered? also for the "open new tab as.." button which located at the right of the box, how to make it bigger and vertical centered too?
```
.newtab-button {
 height: 43px;
}
```

**Comment by irvinm** [comment]
Alignment:

```
.after-tabs button, .after-tabs [role="button"] {
	--tab-like-button-padding: 10px;
}
```

Scale:
```
.newtab-action-selector-anchor::after {
	scale: 1.5;
}
```

**Comment by eldon922** [comment]
> 

Thanks! but the Scale part only make the icon bigger, not the clickable area. it's too small, hard to click it. i try to add padding, but it doesn't work

**Comment by irvinm** [comment]
```
.after-tabs .newtab-action-selector-anchor {
	max-width: 32px;
	padding-left: 10px;
	padding-right: 10px;
}
```

**Comment by eldon922** [comment]
> ```
> .after-tabs .newtab-action-selector-anchor {
> 	max-width: 32px;
> 	padding-left: 10px;
> 	padding-right: 10px;
> }
> ```

Thanks!
