### ISSUE TITLE
Tooltip persists over other windows while Firefox is in background

### ISSUE THREAD

**Issue by jarredou** [piroor/treestyletab#3306]
Sometimes, TST tooltips persists over other windows while firefox is in background.
The only way to get them  dissapear is to focus back on Firefox windows, move the mouse, and go back the others windows.
This is really annoying. It is only happening when TST's sidebar is active.

It's the same as previously already reported but never fixed similar bugs, even if it's not the same TST version.

![TST bug tooltips 2](https://user-images.githubusercontent.com/6044199/225007578-6f6340a1-5f50-41b2-b05a-35cf5cb8a089.png)
![TST bug tooltips](https://user-images.githubusercontent.com/6044199/225007646-a22c8e69-3059-403a-af5b-71cd2e06e5fc.png)

**Comment by irvinm** [comment]
Given the original issue you commented on was 11 years old, are you saying this has been happening to you for 11 years?  If not, when did this start happening for you recently?  What are versions are you running?  (OS, Firefox, TST)  How do you reproduce this?

**Comment by piroor** [comment]
As irvinm mentioned, too less information. Please fill the issue template especially versions of the platform (OS), Firefox and TST.

And this looks a duplicated of #2022 which is an issue of Firefox itself - maybe unfixable by TST side.

**Comment by jarredou** [comment]
Firefox Developer Edition 112.0b2 (64 bits) / Windows (7 and 10, it happens with both) / Last TST version.

And yeah, I think this is happening since I've started using TST, so since years.

I haven't found a way to reproduce it "on demand". But once it's happening with one tooltip, it will happen with tooltips displayed later... until a TST/Firefox restart. But since the recent huge memory problem during each sidebar loading with TST-lock-tree-collapsed (https://github.com/piroor/tst-lock-tree-collapsed/issues/14), it's really not a solution.

**Comment by piroor** [comment]
> But once it's happening with one tooltip, it will happen with tooltips displayed later... until a TST/Firefox restart. 

Did you mean that the problem appears with these steps?

1. You put the cursor on a collapsed tree A.
2. Wait for a while.
3. You move the cursor onto another collapsed tree B.
4. A large tooltip provided by TST appears for the tree A.
5. Wait for a while.
6. A large tooltip provided by TST apepars for the tree B.
7. You move the cursor another place.
8. The tooltip shown at the step 6 (or 4?) remains there.

----

By the way please write the exact version. The term "last" is unclear to track issues. Recently I've released 3.9.14 and some people may not download it yet, so the term can match to two versions both 3.9.14 and 3.9.12. (Of course I agree that your case may happen with any version of TST.)

**Comment by jarredou** [comment]
My TST was autoupdated on 15 march, so I'm using 3.9.14 since then.

The problem seems more related to the moment when you have a tooltip displayed (collapsed tree or only from a unique tab) while changing the focused window, and once the firefox window is in background with the tooltip, it stays in foreground and doesn't disappear. But as I told before, it's little oscure how this happens. I'll try to be more carefull next time it happens (no time to try to provoke the bug to investigate further at the moment).

**Comment by jarredou** [comment]
I can confirm this is not a TST issue, as this is also happening with other sidebar addons.

**Comment by fanzhuyifan** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1852191
