### ISSUE TITLE
[Bug] Moving tabs via Firefox Shortcuts produces bad behavior

### ISSUE THREAD

**Issue by RemoteSalad** [piroor/treestyletab#3307]
## Abstract
I enjoy how much TST helps me organize my workspace. However, I encountered an issue where the tree structure & tab focus behaves unexpectedly when trying to use keyboard shortcuts to move tabs. 
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Create a basic tab tree of any size with top level tabs on either side
 4. Try to move top level tab using keyboard shortcuts (`ctrl + shift + pg up` or `ctrl + shift + pg dn`) while the tab tree is collapsed.

Example starting below collapsed tree:
```
A
B
\- C (collapsed)
D (selected)
```
`ctrl + shift + pg up`

```
A
B (selected)
\- C (collapsed)
\- D (collapsed)
```

Example starting above collapsed tree:
```
A (selected)
B
\- C (collapsed)
D
```
`ctrl + shift + pg dn`
```
B (selected)
\- A (collapsed)
\- C (collapsed)
D
```
## Expected result
Focus stays on the initially selected tab. Architecture of trees does not change and focused tab can move freely into or out of sub-trees.

## Actual result
Focus shifts to the top level tab of the collapsed tree. Formerly focused tab becomes an unselected member of that tree. The formerly selected tab is inconsistently placed within the tree. 

Appears to work as intended if the tab tree is expanded.

## Environment

 * Platform (OS): Windows 10 Pro; Version 22H2
 * Version of Firefox: 110.0
 * Version (or revision) of Tree Style Tab: 3.9.12
* User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0

**Comment by piroor** [comment]
Thanks, I missed to handle the shortcut for Ctrl-PageUp/PageDown. The commit c29d1f4 should fix it.

**Comment by RemoteSalad** [comment]
I just did a quick test and it seems to be totally functional!

I'm guilty of rearranging my tab mess without moving my hand to the mouse so this is a great for me.

Thank you very much :)
