### ISSUE TITLE
[Bug] Flashes when opening TST

### ISSUE THREAD

**Issue by hotsno** [piroor/treestyletab#3308]
I've seen several other issues reporting similar behavior, and I did follow [these instructions](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#suppress-white-flash-on-showing-sidebar-in-dark-color-mode-2903) in the wiki, but I'm still getting flashes.

https://user-images.githubusercontent.com/71658949/226138523-ba796488-4cce-4a49-b0b6-692593c7f8e2.mp4

<br>
<details>
  <summary>Here is how each new frame is drawn (in order)</summary>

  Frame 1 (no tabs yet, light gray)
  ![image](https://user-images.githubusercontent.com/71658949/226138652-86d3d0c1-8fbd-43d8-a381-5e447de6dd30.png)

  Frame 2 (no tabs yet, darkest gray, horizontal scrollbar at the bottom)
  ![image](https://user-images.githubusercontent.com/71658949/226138693-2a08dfdc-d858-4dc7-bf8c-75fd6c34b770.png)

  Frame 3 (no tabs yet, darkest gray, white square in the middle)
  ![image](https://user-images.githubusercontent.com/71658949/226138934-23cf4193-4b79-45b4-b050-ed6e925f81c7.png)

  Frame 4 (tabs show up, less dark gray)
  ![image](https://user-images.githubusercontent.com/71658949/226139003-ab70ed06-c3c9-46e6-be03-d6d70046b169.png)

</details>

I think if it's possible to eliminate the colors changing, the horizontal scroll bar, and the white square, this would make things look a lot more smoother. Ideally the tabs load instantly but that's a lot less likely to be an simple solution.

I know this is pretty nitpicky, but I just wanted to put it out there in case it is fixable and it's worth it to fix. I personally open and close TST a lot and it would really benefit from looking nicer :)

**Comment by piroor** [comment]
It is uncontrollable from addons like TST and you need to apply something bg color for blank sidebar by userContent.css.
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#suppress-white-flash-on-showing-sidebar-in-dark-color-mode-2903
