### ISSUE TITLE
[Bug] Native tab menu favicon entry not updated in dark mode

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#3309]
## Abstract
When turning on dark mode, the sidebar, addon bar, and TST tab menu favicons change from black to white when enabling dark mode.  When right-clicking on the native tabs, the TST menu item favicon still remains black and is not updated.  (Is this a FF limitation?)

**Sidebar and Addon button:**

![image](https://user-images.githubusercontent.com/979729/226184296-e848eb57-2714-4605-bc59-370fdf060a13.png)

**TST tab menu:**

![image](https://user-images.githubusercontent.com/979729/226184489-b6e98ce6-95c3-4d28-b850-48aee57e8ffa.png)

**Native tab menu:**

![image](https://user-images.githubusercontent.com/979729/226184312-3f08b701-74f2-46d2-bf7a-99834c087723.png)

## Steps to reproduce

1. Fresh Firefox install
2. Install TST
3. Switch Firefox to the dark theme

## Expected result
Native bar menu item favicon should be updated to white.

## Actual result
Native bar menu item favicon remains black.

## Environment

 * Platform (OS): Windows 10 Pro x64 (22H2)
 * Version of Firefox:  FF 111.0
 * Version (or revision) of Tree Style Tab:  3.19.14

**Comment by piroor** [comment]
I think this is a bug of Firefox itself. Both menu icons for native tab context menu and TST's simulated tab context menu are already updated with same method, to Firefox should apply the updated icons for the native context menu...

**Comment by irvinm** [comment]
Not an important issue ... closing.
