### ISSUE TITLE
[Bug] New tab inheriting container from current tab switches focus

### ISSUE THREAD

**Issue by farnoy** [piroor/treestyletab#3310]
## Abstract

When using the option to inherit container from current tab when creating a New independent blank tab, the new tab is created correctly, in the right position, with the right container, but the focus switches back to the original tab.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Configure as follows: 
![image](https://user-images.githubusercontent.com/345808/226324869-f3d3bb8b-db0d-4455-8cdd-a18fed330774.png)
 4. Open a new container tab
 5. Use `CTRL/CMD-T` to create an independent tab
 6. New tab is created properly, but focus switches back to the originating tab

## Expected result

Focus switches to the new tab and stays there

## Actual result

Focus switches to the new tab for a split second, then goes back to the originating tab.

## Note

The problem does not occur when `CTRL-T`-ing from a non-container tab. It also doesn't occur when creating the tab as a sibling/child with a TST shortcut. Finally, it doesn't occur when using the Plus button in TST. It only seems happen with the exact interaction of `CTRL-T` from a container tab.

## Environment

 * Platform (OS): Windows 11
 * Version of Firefox:  112.0b3
 * Version (or revision) of Tree Style Tab:  3.9.14

**Comment by dirtymoustache** [comment]
Also occurs on MacOS 13.2.1 and Firefox 112.0b3

This appears to be related to the fix for #3296 that was released with 3.9.13 (2023.3.12). 

Reverting to [3.9.12](https://addons.mozilla.org/firefox/downloads/file/4053198/tree_style_tab-3.9.12.xpi) serves as a temporary fix for now.

Edit: Looks like 3.9.12 has been removed from the downloads list at this time.

**Comment by ralish** [comment]
Also seeing this. The impact is pretty severe to the user experience. Happy to provide any details to assist!

**Comment by piroor** [comment]
Thanks, the commit f8d9d3d should fix this.
