### ISSUE TITLE
[Bug] Tree Style Tab sidebar starts cycling reload after popping out a tab to a new popup window 

### ISSUE THREAD

**Issue by MurzNN** [piroor/treestyletab#3311]
## Abstract
After a recent update, the Tree Style Tab sidebar starts cycling reload after popping out a tab to a new popup window, using the https://github.com/ettoolong/PopupWindow extension.

Previously all worked well without any issues, and the problem started several days ago only, seems after the 3.9.14 release?

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install the https://github.com/ettoolong/PopupWindow extension.
 4. Open many tabs.
 5. Pop out some tab in the middle of the list to the new window, using https://github.com/ettoolong/PopupWindow extension.
 6. See that the TST sidebar starts reloading every several seconds.

It's reproducible always on my work profile, but not always - on a clean profile, still trying to find a strict way to reproduce it on a clean profile.

## Environment

 * Platform (OS): Ubuntu Linux
 * Version of Firefox: 111.0 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.9.14

**Comment by MurzNN** [comment]
I've caught this error in the browser console, maybe it's related:
```
FrameData missing for treestyletab@piro.sakura.ne.jp page moz-extension://96a99982-aafe-4dd7-a7de-ab0cf918794a/sidebar/sidebar.html?style=photon&reloadMaskImage=true [ExtensionPageChild.jsm:466](resource://gre/modules/ExtensionPageChild.jsm)
    initExtensionContext resource://gre/modules/ExtensionPageChild.jsm:466
    initExtensionDocument resource://gre/modules/ExtensionProcessScript.jsm:376
```

**Comment by piroor** [comment]
I cannot reproduce this on my Windows 10 and Windows 11 environment. Is this Linux specific?

**Comment by MurzNN** [comment]
Yes, I'm using Linux, but still no strict steps to reproduce it - it happens sometimes. But seems I've caught the real error when this is happening:
```
Error: Fatal error: native tabs are not same to the tabs tracked by the background process, for the window 2722. Reloading all...
    syncTabsOrder moz-extension://96a99982-aafe-4dd7-a7de-ab0cf918794a/sidebar/sidebar-tabs.js:171
```
Can I give you more debug info to investigate the issue?

**Comment by MurzNN** [comment]
Also, after returning a tab from "Popup" status to the normal one - the reloady cycle stops, but I can't see the returned tab in the list of TST tabs, but still can switch to it using "Ctrl+Tab", so it becomes hidden.

**Comment by MurzNN** [comment]
And seems it's happening when I use "popup" feature for a child tab inside a tree, with a root tab it works well.

**Comment by MurzNN** [comment]
Here is a video with reproducing the issue in a fresh Firefox profile:
https://user-images.githubusercontent.com/336662/227422917-a9d7936a-03da-4308-a091-f4b32d3f3384.mp4

**Comment by piroor** [comment]
Thanks, I've successfully reproduced the problem on my Ubuntu environment and introduced some commits to fix this.
