### ISSUE TITLE
[Enhancement] Highlight container tabs

### ISSUE THREAD

**Issue by ravirathore** [piroor/treestyletab#3315]
@piroor 
Hi,

In a window, if some tabs are open in a 'container' called 'x1', is it possible to:

1.    Highlight them someway (in TST tree)
2.    Or, append a string titled 'x1' to their page title (in TST tree)?

## Expected result
1.    Highlight container tabs someway (in TST tree)
2.    Or, append a string titled 'x1' to their page title (in TST tree)?

## Actual (present) result

Only shows the title of the page.

Please advise.

Thanks,

**Comment by ravirathore** [comment]
@piroor 

## Expected result

3. Or, attach any string 'xyz' to their title.

thanks,

**Comment by irvinm** [comment]
@ravirathore maybe I am missing something here, but TST already gives you a visual indicator when you open a tab into a container.

![image](https://user-images.githubusercontent.com/979729/229378970-ee6503d1-515d-4364-8b44-7c84c3cdf8ed.png)

**Comment by irvinm** [comment]
Now if you wanted to do something specific (different), there is "data-contextual-identity-name" that you could probably work into some CSS to make specific changes.

![image](https://user-images.githubusercontent.com/979729/229379263-17351548-91a7-4a90-8ac8-331bc2d5c796.png)

**Comment by irvinm** [comment]
Example:

![image](https://user-images.githubusercontent.com/979729/229379574-49d4a185-e06c-4abf-b927-9191385ddd8c.png)

**Comment by irvinm** [comment]
If you still wanted to do the text, it looks like you could do something like this:

![image](https://user-images.githubusercontent.com/979729/229380114-d8e530cd-7221-4ad0-82ea-afdbd98f700b.png)

I am not sure why that element doesn't not align vertically, but you could adjust that if you want to.

**Comment by ravirathore** [comment]
@piroor 

Thanks a lot for the help!

regards,

**Comment by ravirathore** [comment]
@irvinm 

Thanks a lot!

regards,
