### ISSUE TITLE
[Bug] "tab session manager" session restore loses tree structure

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#3316]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. enable photon theme, autogrouping
 4. install TSM
 5. create the following tree
    - https://example.org/?1
      - https://example.org/?1_1
      - https://example.org/?1_2
 6. also add all three urls to a bookmark folder and open it grouped, now you have two trees
 7. save it as a named TSM session
 8. restart firefox
 9. restore the session
 10. it opens flat, both trees are lost
     ![image](https://user-images.githubusercontent.com/895588/229561606-ba736099-ad74-46d2-b50b-ed0fc5bf2979.png)

## Environment

 * Platform (OS): win11 22h2
 * Version of Firefox: 111.0.1
 * Version (or revision) of Tree Style Tab: 3.9.15
 * TSM: 6.12.1

**Comment by bughit** [comment]
according to the [readme](https://github.com/piroor/treestyletab/blob/trunk/README.md#user-content-feature-requests-better-compatibility-with-session-manager-extensions-or-add-high-power-session-management-feature), this is expected to work:

> TST should work well with any other session manager extension together, if it respects [openerTabId of tabs.Tab](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab). [Tab Session Manager (aka TSM)](https://addons.mozilla.org/firefox/addon/tab-session-manager/) is one of examples.

**Comment by irvinm** [comment]
Did you enable support for TST in TSM?

![image](https://user-images.githubusercontent.com/979729/229571722-969e6413-f589-4e79-9d93-3617eae761ee.png)

**Comment by bughit** [comment]
No. Seems to be working with that.
