### ISSUE TITLE
[Enhancement] Add right click options

### ISSUE THREAD

**Issue by Clozent** [piroor/treestyletab#3317]
## Abstract
It's kind of a bummer, not being able to set different actions when right clicking on different things.
This way, for example, I could decide that I want the "new tab" button to open a certain context menu, or decide that right clicking an empty area will add a tab, etc.
## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open TST,
 4. Right click on the "new tab" button.

## Expected result
The menu where you choose where to open the new tab appears.

## Actual (present) result
The same menu opened by right-clicking any empty area appears.

## Environment

 * Platform (OS): Windows
 * Version of Firefox:  111.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab:  3.9.15

**Comment by piroor** [comment]
Thanks, I missed that recent Firefox provides special context menu on the new tab button. With the commit a451dbc, TST also shows container selection menu as the right-click menu on the new tab button in its sidebar.
