### ISSUE TITLE
Overlapping Tabs

### ISSUE THREAD

**Issue by Shuro** [piroor/treestyletab#332]
Hi piro,

have a problem with your addon, but for me it's hard to discribe.
My tabs are assigned on the left side in tree layout, but after the last update to version 0.14.2012080901 it happens after some time that new tabs begin to overlay.

Example: I'm on google.com, click right on picture search and say "to new tab", normally it would subattached to my actual tab, but I see it just flashing up on the active tab and disapear. that happens with every new tab I open until i restart firefox.

Happens under windows 7 and linux (opensuse 11.4).

Hope someone can help me here.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
