### ISSUE TITLE
[Enhancement] Add tab numbers for tabs 1-9

### ISSUE THREAD

**Issue by j-steinbach** [piroor/treestyletab#3320]
## Abstract

In [Firefox](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly?redirectslug=Keyboard+shortcuts&redirectlocale=en-US) one can jump to tabs 1-8 and 9 (always the latest tab) with `alt` + `1-9`. But on a glance it is difficult to see which tab has which number. I propose to add small icons/numbers to the first eight and the last tab so that users can quickly jump.

## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open twenty random tabs
 4. Try to jump to tab 7 based on counting/guessing which is the 7th tab.
 5. You will probably jump to the wrong tab because you counted wrong...

E: Removed bad screenshots. See the CSS solution below.

## Expected result

Add tab numbers (as option/choice)

## Actual (present) result

Not possible to only show tab numbers 1-8 .

E: possible to do it with CSS. See below.

## Environment

 * Platform (OS): NixOS
 * Version of Firefox: 111.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.9.15

**Comment by piroor** [comment]
Here are some hints: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#tab-numbering-and-counting

**Comment by irvinm** [comment]
```
#tabbar {
  counter-reset: vtabs atabs tabs;
  /* vtabs tracks visible tabs, atabs tracks active tabs, tabs tracks all tabs */
}

/* Increment counters for visible, active, and all tabs */
tab-item:not(.collapsed):not(.discarded) {
  counter-increment: vtabs atabs tabs;
}
tab-item:not(.collapsed) {
  counter-increment: vtabs tabs;
}
tab-item:not(.discarded) {
  counter-increment: atabs tabs;
}
tab-item {
  counter-increment: tabs;
}

/* Display vtabs counter only for the first 9 tabs */
tab-item:nth-child(-n+9) .extra-items-container.behind::after {
  background: Highlight;
  color: HighlightText;
  content: counter(vtabs);
  font-size: x-small;
  right: 0.2em;
  padding: 0.2em;
  pointer-events: none;
  position: absolute;
  bottom: 0.2em;
  z-index: 1000;
}

/* Set z-index of extra-items-container.behind to unset */
tab-item .extra-items-container.behind {
  z-index: unset !important;
}
```

![image](https://user-images.githubusercontent.com/979729/230738544-db2bc300-5aed-4fc8-a562-d2c4ffec2c8f.png)

**Comment by j-steinbach** [comment]
Wow, awesome, ty!. Almost perfect, just the `9` should be the last tab (`Debugging - Runtime`). 

But perhaps I will find a way to do that myself. Maybe it with `:last-child`?

E: Maybe just doing 1-8 is enough, as 9 is always the last tab. No need to specifically mark it. Thanks again!

**Comment by irvinm** [comment]
```
#tabbar {
  counter-reset: vtabs atabs tabs;
  /* vtabs tracks visible tabs, atabs tracks active tabs, tabs tracks all tabs */
}

/* Increment counters for visible, active, and all tabs */
tab-item:not(.collapsed):not(.discarded) {
  counter-increment: vtabs atabs tabs;
}
tab-item:not(.collapsed) {
  counter-increment: vtabs tabs;
}
tab-item:not(.discarded) {
  counter-increment: atabs tabs;
}
tab-item {
  counter-increment: tabs;
}

/* Display vtabs counter only for the first 8 tabs */
tab-item:nth-child(-n+8) .extra-items-container.behind::after {
  background: Highlight;
  color: HighlightText;
  content: counter(vtabs);
  font-size: x-small;
  right: 0.2em;
  padding: 0.2em;
  pointer-events: none;
  position: absolute;
  bottom: 0.2em;
  z-index: 1000;
}

/* Display "9" counter info on the last tab */
tab-item:last-of-type .extra-items-container.behind::after {
  background: Highlight;
  color: HighlightText;
  content: "9";
  font-size: x-small;
  right: 0.2em;
  padding: 0.2em;
  pointer-events: none;
  position: absolute;
  bottom: 0.2em;
  z-index: 1000;
}

/* Set z-index of extra-items-container.behind to unset */
tab-item .extra-items-container.behind {
  z-index: unset !important;
}
```

![image](https://user-images.githubusercontent.com/979729/230739187-aa907eb0-273a-4352-ae95-010aeac20b62.png)

**Comment by j-steinbach** [comment]
Perfect.

As this can be done with CSS (thank you again!), from my side the issue is solved and can be closed, but I don't know how you handle these cases.
