### ISSUE TITLE
Right click/context menu does not match theme colours or css customisations 

### ISSUE THREAD

**Issue by Zabooby** [piroor/treestyletab#3322]
## Overview

I'm very new to TST so I'm not sure if I'm missing something, but when right clicking on tabs the menu seems to ignore any themes installed or css customisations in userChrome.css.  In my case, I have [this ](https://addons.mozilla.org/en-GB/firefox/addon/perfect-darkness/)theme installed and the following css for right click menus:

```
html#main-window menupopup:not(.in-menulist) {
  --menu-border-color: black !important;
  --panel-border-color: var(--menu-border-color) !important;
}

html#main-window menupopup:not(.in-menulist) menuseparator {
 --menu-border-color: black !important;
 border-top: 1px solid var(--menu-border-color) !important;
}
```

Here is how right click menus should look:
![image](https://user-images.githubusercontent.com/78969986/232876793-f08a3337-8c8c-4505-a95e-1ef34f4fa114.png)

Here is how they look in TST: 
![image](https://user-images.githubusercontent.com/78969986/232875772-4200f314-5c38-48f5-bbd4-030101eb8765.png)

## Steps to reproduce

I currently have the [Firefox-UI-Fix](https://github.com/black7375/Firefox-UI-Fix) installed, but the issue persists without it anyway. 

[Full userChrome.css](https://pastebin.com/Hu67HymA)
[TST css settings ](https://pastebin.com/8SZHCid3)

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install a random theme 
 4. Right click on tabs in TST 

## Environment

 * Platform (OS): Windows 11
 * Version of Firefox: 112.0.1
 * Version (or revision) of Tree Style Tab: 3.9.15

**Comment by Zabooby** [comment]
@andreasgrafen also found that this option: 

``` 
/*** Hide fake context menu, when right clicking empty area***/
ul[id="tabContextMenu"] {
  display: none;
}
```
seems to have some unintended side effects that break the usability of the integration, as it still opens the context menu – it's just not visible. Resulting in a non-hovered yet hovered state. Shoul I open another issue for this? 

https://user-images.githubusercontent.com/35840154/233112215-7e28e5b7-f0b0-451a-b501-2342c0e0a11a.mov

**Comment by irvinm** [comment]
I spent a little time on this (not too much) and it looks like the scope you are specifying is only for the main window.  ex: "html#main-window menupopup:not(.in-menulist) menuseparator {"  

I was able to change the separator and the border-radius.

![image](https://user-images.githubusercontent.com/979729/233163269-19aa51fc-eded-4848-80e0-2c277c35fe7a.png)

**Comment by Zabooby** [comment]
Thanks I removed `html#main-window` and the menu in TST changes too. This is my code now:
```
menupopup:not(.in-menulist){
  --menu-border-color: black !important;
  --panel-border-color: var(--menu-border-color) !important;
  --panel-background: #1E2021 !important;
}

menupopup:not(.in-menulist) menuseparator {
 --menu-border-color: black !important;
 border-top: 1px solid var(--menu-border-color) !important;
}

menupopup:not(.in-menulist){
  --menu-border-color: black !important;
  --panel-border-color: var(--menu-border-color) !important;
}
```
