### ISSUE TITLE
[Enhancement] Ability to cycle between the tab group only

### ISSUE THREAD

**Issue by sathishmanohar** [piroor/treestyletab#3324]
With tree style tabs I have tabs like

```
- Topic 1
    - Related 1
        - Deep Link 1
    - Related 2
    - Related 3
- Topic 2
    - Related 1
        - Deep Link 1
    - Related 2
    - Related 3
```
Here tabs within Topic 1 and Topic 2 are related to each other. So cycling between only those topics will be great for the workflow and to keep web browsing in context.

For this feature to work. There can be a customization option to 
* cycle with `ctrl+tab` and `ctrl+shift+tab` only within a root parent.
* jump to next/previous parent node with `ctrl+shift+n` and `ctrl+shfit+p`

**Comment by piroor** [comment]
Do you mean following?:

Tabs:

* A: Topic 1
  * B: Related 1
    * C: Deep Link 1
  * D: Related 2
  * E: Related 3
* F: Topic 2
  * G: Related 1
    * H: Deep Link 1
  * I: Related 2
  * J: Related 3

Cycling as B => C => D => E => B => C => ... when the topic 1 is focused.
Cycling as G => H => I => J => G => H => ... when the topic 2 is focused.

**Comment by irvinm** [comment]
I was thinking it would be more like:  (OP might have another view)

Going down might be:  <anything in topic 1> => F => K (assuming K was Topic 3)
Going up might be:  K => F => A ... or J => F => A

I actually wrote an addon today as it seemed fairly interesting.  (Waiting on AMO approval - https://github.com/irvinm/Parent-Tab-Switcher)

It works well with normal tabs, but am seeing some strangeness with TST Group Tabs and how it is assigned its openerTabID and if it gets updated or not when the tab is moved.  (Everything looks fine with the tab properties with TST, but this addon shouldn't need to rely on anything from TST but only the openerTabID)  

Example:

Starting point with some random tabs, you can see there are 5 tabs at the root and only 5 tabs that have undefined openerTabID ... good.

![image](https://user-images.githubusercontent.com/979729/233806803-89bd5958-667c-4b0c-ba17-392d82fd065a.png)

Now I duplicated (Shift+Reload tab) "Group 3" to "NEW" and then dragged it to the root.  In this case everything is the same except for the new tab but as it is still assigned a openerTabID, and thus it won't be selected to be switched to and it gets skipped over.

![image](https://user-images.githubusercontent.com/979729/233806898-e4f4c74b-d845-4dcc-9478-241999129ae3.png)

Here is what it looks like live just going from bottom to top and back:

https://user-images.githubusercontent.com/979729/233807121-44ad83e9-3694-40ed-83c8-f2171b95ada5.mp4

I will say this issue goes away after restarting the browser, so it might be an issue with Firefox and\or the current Developer's Edition version.  After the AMO approves it, I will experiment more with the current version of FF.

**Comment by irvinm** [comment]
@piroor ... nevermind.  This issue also happens with normal tabs and Firefox special tabs.  It is not TST specific.  I'll dig into it more.  Strange that it resolves itself after a browser restart.

**Comment by irvinm** [comment]
Ok, irony at its best ... this looks related to a bug you opened 6 six years ago.  (https://bugzilla.mozilla.org/show_bug.cgi?id=1409262)  Maybe even more ironic that someone said they were going to be working on that issue and were assigned 4 months ago.  (However, this does mean that this new addon would require TST to be installed to ensure that openerTabID gets updated as needed ... and that the defect would need to be resolved in order to work real-time)

**Comment by sathishmanohar** [comment]
@piroor Yes. I meant something like this. Or it can also include the parent tab of the current tab during cycling. So for Topic 1. Cycling as A => B => C => D => E => A => B => C => 

> 
> Cycling as B => C => D => E => B => C => ... when the topic 1 is focused. Cycling as G => H => I => J => G => H => ... when the topic 2 is focused.
>

when cyclic like this there will be a need to jump to another topic. This was my second point about

> * jump to next/previous parent node with `ctrl+shift+n` and `ctrl+shfit+p`

This is the part @irvinm is working on. It looks cool.

Essentially, The feature I am looking for is scoping the tab cycling within the current topic and jump to topics all using keyboard shortcuts.

**Comment by piroor** [comment]
Thank you for more descriptions.

It does not match to your idea but I've realized that "focus previous sibling" and "focus next sibling" commands do not cycle focus, so I've fix the restriction with the commit cfb4227. Now you can cycle focus between tabs as: B => D => E => B ... This change should help you to move focus at your use case.

**Comment by sathishmanohar** [comment]
Awesome! I already have key bindings for next-sibling and prev-sibling so this going to come in handy.

In this regard, I am looking for two ways of cycling.

"focus next parent", "focus previous parent"

When advancing within a parent through sibling and children while at the last tab for the parent (top level tab). Jump to parent or first child. Basically cycle within the parent.

**Comment by sathishmanohar** [comment]
Implementation wise this feature can be  called as "focus mode" or something. This can be like pinning. When focus mode is enabled tabbing cycles within the parent and when it is turned off tabbing continues to next parent like usual.

**Comment by polysquirrel** [comment]
I am not exactly sure what the consensus is on the potential solution, but I'd like to see keystrokes for 'next sibling'/'previous sibling' and 'parent tab' ('child tab' is already handled by `ctrl+tab`.

**Comment by irvinm** [comment]
@piroor I think we can probably close this one.

I had published the work I had done for being able to traverse parent tabs if anyone wants it.

- https://addons.mozilla.org/en-US/firefox/addon/parent-tab-switcher/
- https://github.com/irvinm/Parent-Tab-Switcher

**Comment by piroor** [comment]
@irvinm Wow! Thanks, I've added it to the list of known helper addons.
https://github.com/piroor/treestyletab/wiki/Helper-addons-extending-functionality-of-TST
