### ISSUE TITLE
[Enhancement] Apply theme to group tabs

### ISSUE THREAD

**Issue by polyzen** [piroor/treestyletab#3327]
## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Create group tab
 4. Change theme
 5. Group tab theme remains the same

## Expected result

Group tab reflects current theme

## Actual (present) result

Group tab theme remains the same

## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: 112.0.2
 * Version (or revision) of Tree Style Tab: 1.23.0

**Comment by piroor** [comment]
This is impossible due to Firefox's restriction.

* Gtk's theme color not fully exposed to CSS system colors.
* The `browser.theme.getCurrent()` WebExtensions API does not return effective color information based on gtk's theme.

Thus you need to set theme colors manually as custom CSS.

**Comment by polyzen** [comment]
That's a shame, thanks for explaining!
