### ISSUE TITLE
[Enhancement] Don't open a child from specified open sites 

### ISSUE THREAD

**Issue by Zabooby** [piroor/treestyletab#3331]
For example, I have a startpage (both my homepage and new tab page) with my most visited sites and I regularly ctrl click multiple links from it, would it be possible to not make these children of the startpage, so I don't have to constantly rearrange the tabs?

**Comment by piroor** [comment]
This looks to be beyond the project scope and should be a helper addon.

But I thought about how to implement it. When you open a new tab from your homepage, it is opened as a child tab next to the homepage tab by Firefox not TST - the tab has the ID of the homepage tab as its `openerTabId`. TST just respect the information and attaches the tab to the opener tab as a tree child. So, we need to handle opened tabs and move them to desired position intentionally, if you hope new tabs from the homepage tab to be opened as independent (top level) tabs.

**Comment by piroor** [comment]
Anyway I'm negative to add this to TST as an integrated feature, sorry.

**Comment by Zabooby** [comment]
No problem, it is only a minor annoyance and I am still adjusting to vertical tabs maybe I'll get used to it or there might be some settings that I missed that could help. 

Thanks for the response!
