### ISSUE TITLE
[Enhancement] Showing all tabs of a specified domain (or search-term)

### ISSUE THREAD

**Issue by mYnDstrEAm** [piroor/treestyletab#3332]
## Abstract

It would be very useful if you could make the TST panel show all tabs of one specific domain (and/or search term) without altering the tree structure.

For example, showing all Github tabs so you see and can **go through all of them at once** even when they are dispersed across your tab trees, but then afterwards (or even in parallel) still have the tree view of tabs with the previous structure in TST.

It would be most useful if it was possible to add that view to the current tree view in a **subpanel** so you can see the tab twice:
* once in the search results / list of tabs for a specific domain
* and once in its tree context in case the placement / surrounding tabs matter
It could display in the lower region of the TST panel just like it's possible with the "TST Bookmarks Subpanel" addon.

You could also use this to make a new tab tree that contains all/many of these tabs (domain-tabs-trees).

## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open many tabs
 4. Try to close your tabs in an organized way

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
Did you try TST Tab Search? https://addons.mozilla.org/firefox/addon/tst-search/

**Comment by piroor** [comment]
By the way I won't implement this kind feature as a built-in feature of TST because it is beyond the project scope, sorry.

**Comment by mYnDstrEAm** [comment]
Thanks, that's a great workaround - it basically solves the problem.

However, it keeps the tab trees un/collapsed as is and still shows other tabs instead of only the search results. I later found it can hide all tabs not in the search results by Result  Highlighting->Other/Misses->Hide Completely. Maybe that should be the default or the user get prompted about after installation / at first usage.

However, it can't show the search results only in a separate subpanel so you can see their context in one panel and the search results tabs on the subpanel. I guess these would be proposals for that addon. If it won't be implemented here, the issue can be closed.

It would just be great if you built in a way users of TST could discover such highly useful addons (without making/finding an issue here or browsing through all the addons with "tree style tab" at Mozilla). **See #3339**
