### ISSUE TITLE
[Enhancement] Integrate "Tab Unloader for Tree Style Tab"

### ISSUE THREAD

**Issue by mYnDstrEAm** [piroor/treestyletab#3333]
## Abstract

Please integrate "[Tab Unloader for Tree Style Tab"](https://github.com/Lej77/tab-unloader-for-tree-style-tab) or its unloading functionality into TST. It's very useful and it's not good to have such useful in separate addons, for example because most users will never learn that these exist or that functionality could exist or be useful.

Please make this addon a subcomponent of TST, it could still be developed in a separate repo but be part of TST. As far more users would then use this software, devs of that addon probably would be glad if it was integrated in TST itself, making their work much more useful.

## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open many tabs
 4. Try unloading tabs to speed up performance, improve privacy, free memory, and so on

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
Integration of various features not related to basic tree management is beyond the project scope.
https://github.com/piroor/treestyletab#requests-proposals-or-unexpected-trouble-from-bugs

Moreover, unmaintained components will introduce security risk or blocker of future development even if they are sub components and just bundled.

**Comment by mYnDstrEAm** [comment]
Makes sense. I'd still support if it was integrated if that's ever possible (for example if there are more TST devs who make sure the subcomponent is well-maintained). If it won't get integrated (at least in the foreseeable future), the issue can be closed. Discussion could continue at #3339
