### ISSUE TITLE
[Enhancement] Sort Tree By MRU (Most Recently Used)

### ISSUE THREAD

**Issue by the-a-man-006** [piroor/treestyletab#3335]
Sort tabs by last accessed too. TabSlider (sorts tabs by MRU) doesn't interact well with Sidebery and TsT. Quick Tabs Ported doesn't present the MRU list as an always visible side panel and has to be clicked instead. Plus there's the risk that multiple views of the same thing (tabs) might be disorienting. Ignoring the disorientation, and ignoring the fact that you still can't have two sidebars (one at left, another at right) concurrently in Firefox), the only good alternative is All Tabs Helper (which truly is a masterpiece, but the person who made it is a 66-year-old, and the UI colors totally reflect that, lol; not complaining, in fact, imma stick to using it in parallel until TsT or Sidebery integrates MRU tree-sorting...).

An MRU implementation in TsT:
When user switches to any tab, drag the tab and its whole subtree up at the top. Children of the same parent stay sorted in the MRU order; the upper the more recently used one. A parent's own ranking/last-accessed-time is that of its most recently accessed child, or itself (whichever is more recent). Thus, clicking a child tab of a very old parent should drag the whole parent up at the top too. Life would be bliss.

Note that if an option could be had whereby dragging a tab drags the whole chain (it's own subtree, and its parent, and the parent's parent, and so on), then TabSlider would work perfectly with TsT with that option turned on, and native MRU sorting wouldn't be necessary.

**Comment by piroor** [comment]
Such a feature is beyond the scope of TST project. TST concentrates to provide basic tree management features and just provides APIs to control its tree from other helper addons which extends TST's tree for various purpose.

**Comment by the-a-man-006** [comment]
Too bad; Sidebery has chosen to implement it:
https://github.com/mbnuqw/sidebery/issues/643#issuecomment-1975215661
Guess competition is always good, lol.

**Comment by piroor** [comment]
That's true. Because there are competitors who choose ways I didn't choose, I can choose my way without concern.
