### ISSUE TITLE
[Bug] (When opening link in a new tab with ctl + left click (on link) wont open tab as child)

### ISSUE THREAD

**Issue by haShinui** [piroor/treestyletab#3337]
## Abstract
Hello so I am setting up my treesyle tab and I am running into an issue of opening child tabs. I tried to reinstall firefox and deinstall all extension besides tst and nothing worked. I am not sure if its a bug, probrely not but I can't solve the problem my self.
## Steps to reproduce
So I deinastalled firefox, all extension, besides treestyletab.
I just set every setting that make something a child tab to that, even that caution one. I can also send my config file, cant do it over gituhub, it doesnt support format

## Expected result

So when I am on a site like this github page and I click on a old issue link or anything, without ctrl, it will open/load the link in current tab, but I want to open it in a new tab, so ctrl + left click, and it should open that link/page as a child of the original.

So link on website are made to be automatically open in new tab, those link will open as a  child tab. Example, fastest I can find for me, if I press on track button on my aliexpress order, it opens that new window as a child

## Actual result
When click (without ctrl) a link, that link will open in current tab. With crtl + right click, It open that tab as a sibling(not sure) or something else just not a child

## Environment

 * Platform (OS):  Arch, Hyprland. Also tried it on windows, same result.
 * Version of Firefox: 112.0. 1 
 * Version (or revision) of Tree Style Tab: 3.9.15

**Comment by piroor** [comment]
Hmm, it is very unexpected. Ctrl-click is handled by Firefox itself and a new tab should be opened with `openerTabId` information, then TST handles it and attaches to the opener tab. So your case looks one of followings:

* Firefox unexpectedly omits `openerTabId` for the opened tab.
* TST unexpectedly ignores `openerTabId` of the opened tab.

Could you try collect logs with these steps?:

1. Go to TST's options page and turn on checkboxes:
   * Development => ✔Debug mode
   * Development => Detailed logging => Logs from background modules => ✔background/handle-new-tabs
2. Start debugger for TST: https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-start-debugger-for-tree-style-tab
3. Switch the debugger to the "Console" tab.
4. Click the trash box icon to clear old logs.
5. Go to a GitHub tab and Ctrl-click a link.
6. Go back to the debugger, copy logs and paste it to here.

**Comment by haShinui** [comment]
Ok so I played around a bit and if I ctrl + right click on link it opens it as a sibling. Also the last example of file opening is when I press the track order button on aliexpress where it open the tab as a child, but that was yesterday, now it opens as a sibling?? Wierd

The debug log coppied
`tst<BG>: 18:46:32.280 background/handle-new-tabs:         Tabs.onCreating  #96(tracked) 69 
Object { bypassTabControl: false, positionedBySelf: false, openedWithCookieStoreId: false, mayBeReplacedWithContainer: false, maybeOrphan: false, restored: undefined, duplicated: false, duplicatedInternally: false, activeTab: {…}, fromExternal: false }
common.js:680:13
tst<BG>: 18:46:32.281 background/handle-new-tabs:         opener: #69(tracked), positionedBySelf = false common.js:680:13
tst<BG>: 18:46:43.072 background/handle-new-tabs:         Tabs.onCreating  #97(tracked) 4 
Object { bypassTabControl: false, positionedBySelf: false, openedWithCookieStoreId: false, mayBeReplacedWithContainer: false, maybeOrphan: false, restored: undefined, duplicated: false, duplicatedInternally: false, activeTab: {…}, fromExternal: false }
common.js:680:13
tst<BG>: 18:46:43.073 background/handle-new-tabs:         opener: #4(tracked), positionedBySelf = false common.js:680:13
tst<BG>: 18:48:21.621 background/handle-new-tabs:         Tabs.onCreating  #98(tracked) 96 
Object { bypassTabControl: false, positionedBySelf: false, openedWithCookieStoreId: false, mayBeReplacedWithContainer: false, maybeOrphan: false, restored: undefined, duplicated: false, duplicatedInternally: false, activeTab: {…}, fromExternal: false }
common.js:680:13
tst<BG>: 18:48:21.622 background/handle-new-tabs:         opener: #96(tracked), positionedBySelf = false common.js:680:13
tst<BG>: 18:48:57.646 background/handle-new-tabs:         Tabs.onCreating  #99(tracked) 67 
Object { bypassTabControl: false, positionedBySelf: false, openedWithCookieStoreId: false, mayBeReplacedWithContainer: false, maybeOrphan: false, restored: undefined, duplicated: false, duplicatedInternally: false, activeTab: {…}, fromExternal: false }
common.js:680:13
tst<BG>: 18:48:57.648 background/handle-new-tabs:         opener: #67(tracked), positionedBySelf = false common.js:680:13
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features! options.html
tst<BG>: 18:50:53.753 background/handle-new-tabs:         Tabs.onCreating  #100(tracked) 69 
Object { bypassTabControl: false, positionedBySelf: false, openedWithCookieStoreId: false, mayBeReplacedWithContainer: false, maybeOrphan: false, restored: undefined, duplicated: false, duplicatedInternally: false, activeTab: {…}, fromExternal: false }
common.js:680:13
tst<BG>: 18:50:53.755 background/handle-new-tabs:         opener: #69(tracked), positionedBySelf = false common.js:680:13
tst<BG>: 18:51:46.699 background/handle-new-tabs:         Tabs.onCreating  #101(tracked) 69 
Object { bypassTabControl: false, positionedBySelf: false, openedWithCookieStoreId: false, mayBeReplacedWithContainer: false, maybeOrphan: false, restored: undefined, duplicated: false, duplicatedInternally: false, activeTab: {…}, fromExternal: false }
common.js:680:13
tst<BG>: 18:51:46.701 background/handle-new-tabs:         opener: #69(tracked), positionedBySelf = false common.js:680:13
Uncaught (in promise) Error: Invalid tab ID: 101 4 undefined
    timer moz-extension://00560efe-efd5-48a3-9d93-3c3ad0ad9768/extlib/TabFavIconHelper.js:418
    AsyncFunctionThrow self-hosted:814
    (Async: async)
    onTabUpdated moz-extension://00560efe-efd5-48a3-9d93-3c3ad0ad9768/extlib/TabFavIconHelper.js:404
    apply self-hosted:2324
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:649
    fire resource://gre/modules/ExtensionChild.jsm:832
    recvRunListener resource://gre/modules/ExtensionChild.jsm:836
    _recv resource://gre/modules/ConduitsChild.jsm:84
    receiveMessage resource://gre/modules/ConduitsChild.jsm:196
tst<BG>: 18:52:58.297 background/handle-new-tabs:         Tabs.onCreating  #102(tracked) 14 
Object { bypassTabControl: false, positionedBySelf: false, openedWithCookieStoreId: false, mayBeReplacedWithContainer: false, maybeOrphan: false, restored: undefined, duplicated: false, duplicatedInternally: false, activeTab: {…}, fromExternal: false }
common.js:680:13
tst<BG>: 18:52:58.301 background/handle-new-tabs:         opener: #14(tracked), positionedBySelf = false common.js:680:13
tst<BG>: 18:54:12.932 background/handle-new-tabs:         Tabs.onCreating  #103(tracked) 102 
Object { bypassTabControl: false, positionedBySelf: false, openedWithCookieStoreId: false, mayBeReplacedWithContainer: false, maybeOrphan: false, restored: undefined, duplicated: false, duplicatedInternally: false, activeTab: {…}, fromExternal: false }
common.js:680:13
tst<BG>: 18:54:12.933 background/handle-new-tabs:         opener: #102(tracked), positionedBySelf = false common.js:680:13
tst<BG>: 18:55:02.486 background/handle-new-tabs:         Tabs.onCreating  #104(tracked) 102 
Object { bypassTabControl: false, positionedBySelf: false, openedWithCookieStoreId: false, mayBeReplacedWithContainer: false, maybeOrphan: false, restored: undefined, duplicated: false, duplicatedInternally: false, activeTab: {…}, fromExternal: false }
common.js:680:13
tst<BG>: 18:55:02.487 background/handle-new-tabs:         opener: #102(tracked), positionedBySelf = false common.js:680:13
`

Edit: I did some more testing. What i did was first I click a link that should open in a new tab and it opend as a sibling. Then I ctrl + right clicked it and it gave me that error that you may see. The last tab I opened was from a reddit, when I click on the link to some dot files, it opens that link in a new tab and it is a child. I did it with and without ctrl and it still opened as a child.
Here are the logs:
`tst<BG>: 19:03:16.357 background/handle-new-tabs:         Tabs.onCreating  #111(tracked) 58 
Object { bypassTabControl: false, positionedBySelf: false, openedWithCookieStoreId: false, mayBeReplacedWithContainer: false, maybeOrphan: false, restored: undefined, duplicated: false, duplicatedInternally: false, activeTab: {…}, fromExternal: false }
common.js:680:13
tst<BG>: 19:03:16.358 background/handle-new-tabs:         opener: #58(tracked), positionedBySelf = false common.js:680:13
tst<BG>: 19:03:19.472 background/handle-new-tabs:         Tabs.onCreating  #112(tracked) 58 
Object { bypassTabControl: false, positionedBySelf: false, openedWithCookieStoreId: false, mayBeReplacedWithContainer: false, maybeOrphan: false, restored: undefined, duplicated: false, duplicatedInternally: false, activeTab: {…}, fromExternal: false }
common.js:680:13
tst<BG>: 19:03:19.472 background/handle-new-tabs:         opener: #58(tracked), positionedBySelf = false common.js:680:13
Uncaught (in promise) Error: Invalid tab ID: 111 3 undefined
    timer moz-extension://00560efe-efd5-48a3-9d93-3c3ad0ad9768/extlib/TabFavIconHelper.js:418
    AsyncFunctionThrow self-hosted:814
    (Async: async)
    onTabUpdated moz-extension://00560efe-efd5-48a3-9d93-3c3ad0ad9768/extlib/TabFavIconHelper.js:404
    apply self-hosted:2324
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:649
    fire resource://gre/modules/ExtensionChild.jsm:832
    recvRunListener resource://gre/modules/ExtensionChild.jsm:836
    _recv resource://gre/modules/ConduitsChild.jsm:84
    receiveMessage resource://gre/modules/ConduitsChild.jsm:196
tst<BG>: 19:03:59.960 background/handle-new-tabs:         Tabs.onCreating  #113(tracked) 1 
Object { bypassTabControl: false, positionedBySelf: false, openedWithCookieStoreId: false, mayBeReplacedWithContainer: false, maybeOrphan: false, restored: undefined, duplicated: false, duplicatedInternally: false, activeTab: {…}, fromExternal: false }
common.js:680:13
tst<BG>: 19:03:59.961 background/handle-new-tabs:         opener: #1(tracked), positionedBySelf = false common.js:680:13
`

**Comment by haShinui** [comment]
Hello
So I did a reinstall and reset my config and reset the tree style tab to default.
After that it worked for some reason??? I dont know why, I used this firefox chrome config file from this[ git repo](https://github.com/AmadeusWM/dotfiles-hyprland)(liked it a lot). 
I think this repo config messed some things up, because after setting it to default the expected behaviors and settings worked.  Will figure it out how to work with the configs

Also quick question, I know there is a page for that, but first I wanted to ask you directly.
Do you need a english to german translation. I like TST a lot and I am ricing up my Arch right now and trying to contribute on github a bit. My main langue is german, grew up with it. If yes just answer and I will go through these steps as shown [here](https://github.com/piroor/treestyletab/blob/trunk/webextensions/_locales/README.md).
I am working on ricing up my arch but as a side project I can translate it and thanks a lot for making this plugin.
Have a great day
