### ISSUE TITLE
[Enhancement] Ways for users to discover, learn about and find helpful TST extensions

### ISSUE THREAD

**Issue by mYnDstrEAm** [piroor/treestyletab#3339]
## Abstract
There are extremely useful extensions to TST but most users will never know about them.

From #3332 and #3333 it seems like some of the most useful of these will
* neither be integrated as subcomponents of the addon (separate repo but bundled with the extension)
* nor their functionality be added into the TST addon itself (repo merging or copying the code or similar)

----

I found these TST extensions the most useful:
* [TST Bookmarks Subpanel](https://addons.mozilla.org/en-US/firefox/addon/tst-bookmarks-subpanel/) (a subpanel beneath your tabs in the TST panel showing your bookmarks so you can easily drag tabs to your bookmarks folders)
* [TST Tab Search](https://addons.mozilla.org/en-US/firefox/addon/tst-search/) (a subpanel beneath your tabs in the TST panel where you can enter search terms and of all your tabs the search result tabs are shown in tabs above - this way you can not only quickly find a set of tabs but show all tabs of specific domain/website so you can close them or reorder them based on that)
* [Tab Session Manager](https://addons.mozilla.org/en-US/firefox/addon/tab-session-manager/) (not losing your tabs and tab trees should be priority#1 and this is the only or best addon which has support for TST so the tab trees can be restored if there ever is a problem with your session so you can't restore it otherwise or you'd like to start a new session without losing the current)
* [Tab Unloader for Tree Style Tab](https://addons.mozilla.org/en-US/firefox/addon/tab-unload-for-tree-style-tab/) (allows you to quickly unload _all other than selected_ or _all selected_ tabs which can speed up performance a lot and free up RAM - extremely useful if you have many open tabs)

[Many closed issues have been created here where users asked about functionality such/these addons already provide](https://github.com/piroor/treestyletab/issues?q=label%3A%22out+of+scope%22+is%3Aclosed).

Despite of all of that, only very few users have the above TST extensions installed. I don't think that's because these aren't useful but because they don't know about them, even I didn't know about them despite being tech-savvy and very interested in TST and having many tabs. (I think it would be reasonable if something on the order of half of TST users have at least one of these installed and TST users grow by a factor of ca 100 - seeing how few open issues there are it would probably be best to prioritize working on the latter now.) Increasing the use of the extensions would also support TST extension development, why would devs work on extending it if so few people use their extensions, this would build up a TST ecosystem or make it more stable and so on.

## Steps to see the situation

 1. Install TST.
 2. Not being aware of how useful for example tab unloading could be and/or thinking a bookmarks subpanel certainly doesn't exist and/or looking for a way to show all tabs of a specific domain but not knowing about the existing TST extension and even if looking for it (unlikely) probably not finding it.
 3. No "Did you know?" type of helpful info or anything similar is ever displayed by TST and very few users know about TST extensions.

## Expected result

**I think it could be very useful if this addon added things to enable users to discover these addons and to find the addons when they need them when they try to use or find some specific functionality** (the latter shouldn't be required because often users don't know which functions could be useful and actively look for them).

For example, there could be context menu entries for things like "Unload tabs (x)" but instead of unloading the tabs it opens the website of the Tab Unloader extension. Burying info about these addons somewhere in the addon preferences is not a good idea. Listing these addons in this repo's readme is good but most won't read that either, especially because it's a long list (I'd recommend making the listed or the best-voted/used addons bold and moving them to the top of the list). If you have other additional ideas please comment.

I think the best thing would be to **show a popup/did-you-know tip** after an update (directly after installation is too soon to add further features) with some info about the addons or a wizard/multiselect-combobox where you can select which additional features you'd like to have and then it opens the websites of the relevant extensions afterwards. It could also show depending on time for example, it doesn't have to be after an update.

Some other recommendations could show depending on some conditions such as the Tab Session Manager being recommended the first time (or whenever) your number of tabs grows above a certain number (a small tip that you can easily close saying "_You have many tabs open. If you want to make sure you don't lose your tabs and the tree structure the extension Tab Session Manager is recommended (link)_". Or there could be biweekly tips on TST functions/options and TST extensions which you can deactivate in the settings and easily close but otherwise sometimes show helpful info somewhere.

## Actual (present) result
None of these options or anything similar.

## Environment

 * Platform (OS): Debian
 * Version of Firefox: 102.10.0esr
 * Version (or revision) of Tree Style Tab: 3.9.15

**Comment by piroor** [comment]
TST cannot show any startup page automatically - it is a restriction of  an officially recommended addon. TST just shows a notification popup and clicking it opens a startup tab `ext+treestyletab:startup` based on the guideline. So I think it is only one available choice: adding links to helper addons into the page.

**Comment by mYnDstrEAm** [comment]
Would be great if you added some there. However, I think it was best if this was a separate page from `resources/startup.html` so that this startup page only links to it.

It could for example be a list of brief addon descriptions (with button to expand for long description) each with a checkbox. You could then check the addon(s) you'd like to install and then click on the install button which opens all the addon pages in new tabs so you can manually install the addons (except if there is a secure way to directly install them).

Another thing to consider is that this isn't useful for many people who just newly install the addon, that's another reason to keep it on a separate page which is only linked to from the startup page (people usually want to install things quickly and worry about missing functions later). The main thing could be showing a notification popup of a type of "Tip of the day" (not shown every day of course but much less frequently or depending on conditions like many tabs being open) that when clicked opens this `resources/extensions.html` page.

**Comment by irvinm** [comment]
@piroor you still have the "needs-triage" label on this one.  Next steps?

**Comment by piroor** [comment]
Sorry for my long silence.

I'm basically negative to recommend too much helper addons on the startup of TST. Recommended features may be useful for some people but most people will simply be confused because they don' know themselves: what they should use and they really need. Installing too much addons with less-knowing definitely introduce troubles. Instead I believe that people need to realize what is their actual issue and find solutions by themselves.

I agree that we should maintain and promote the list of helper addons to provide more easy-to-find information, but I also believe it should be kept separated from TST's codebase. Currently TST contains a link to https://github.com/piroor/treestyletab/blob/trunk/README.md#extensions-that-extend-tst in its startup page and I think it can be replaced with more rich list maintained by users - it may be a [wiki](https://github.com/piroor/treestyletab/wiki) page.

**Comment by piroor** [comment]
I've created a wiki page: https://github.com/piroor/treestyletab/wiki/Helper-addons-extending-functionality-of-TST
Currently it just contains the list of helper addons moved from the README.md. It's OK that you and people update the list more aggressively.
