### ISSUE TITLE
[Bug] Tab Session Manager creates odd tree problem when restoring

### ISSUE THREAD

**Issue by k-h** [piroor/treestyletab#3341]
## Abstract
I am using MacOS 10.14.6 but the latest release of TST 3.9.15 I normally have between 30 and 80 tabs.  I use Tab Mix - links 0.1.0 and Tab Session Manager 6.12.1 among others.  
If firefox restarts there is no issue.  All the tabs exist (unopened) as expected and open as expected.
If I close Firefox and open it and attempt to restore the tabs with Tab Session Manager, all the tabs and trees are created (unopened).  Tabs within a tree open as expected.  But when I open a top level tab it moves to the bottom of the tab list, leaving its tree behind and I have to move it back to the top by hand.  The tree left over still seems to be say at the top where the toplevel tab was but does not have a toplevel tab above it any more.  I can open the tree from the top level tab, even though it is at the bottom of the tree list.  This is difficult to reproduce in another environment because of the number of tabs and tree structure.  And I am not set up for that, I'm sorry. 

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

 I tried reproducing with a new plain profile but I can't get enough complexity to get this behaviour. I still think it is worthwhile flagging this but am not expecting it to be fixed in a hurry.

## Environment

 * Platform (OS): MacOS 10.14.6
 * Version of Firefox: 113.0.1 (64-bit) 
 * Version (or revision) of Tree Style Tab: 3.9.15

**Comment by piroor** [comment]
TST, [Tab Mix - Links](https://addons.mozilla.org/firefox/addon/tab-mix-plus-webextension/) and [Tab Session Manager](https://addons.mozilla.org/firefox/addon/tab-session-manager/) have many options and I'm not well about TML and TSM. Could you describe how to configure them to reproduce the problem?

**Comment by k-h** [comment]
Hi,
Sorry I've been busy but have been thinking about how to duplicate this.
k-h

**Comment by k-h** [comment]
I tried exporting a session with TabSessionManager and opening with a new profile with just TSM TreeStyleTabs.  But everything worked as I would have expected.
