### ISSUE TITLE
[Enhancement] The drag and drop options seciton is confusing, and incredibly hard to read in dark mode. It should be modified.

### ISSUE THREAD

**Issue by echo-lalia** [piroor/treestyletab#3345]
## Abstract
Options menu is difficult to make sense of. The table has dark lines that aren't compatible with dark mode, and the format is unusual, such that it is difficult to interpret what the intended meaning is. 

## Steps to see the situation

 1. Start Firefox in dark mode.
 2. Install TST.
 3. open the options menu
 4. scroll to the drag and drop section

## Expected result
Anything else. Perhaps a dropdown like what is used elsewhere in the options. 

## Actual (present) result
![image](https://github.com/piroor/treestyletab/assets/108598670/3b032c1c-beeb-41d3-bc4e-16c8eb43c44b)

## Environment

 * Platform (OS):  Windows 10
 * Version of Firefox: 113.0.2 (64 bit)
 * Version (or revision) of Tree Style Tab: 3.9.15
 
 
 This is a great extension, just needs some tweaks. Thank you all for what you do.

**Comment by piroor** [comment]
Thanks, I missed it. The commit 2d8b61c should fix it.
