### ISSUE TITLE
[Bug] randomly switching of tabs

### ISSUE THREAD

**Issue by sedrubal** [piroor/treestyletab#3349]
## Abstract

TST randomly activates tabs. I can not really explain what triggers the switching of tabs, but I assume it happens when Firefox gets the focus after focusing another window. I'm using <kbd>Alt</kbd>+<kbd>Tab</kbd> to switch between windows in my window manager but I don't think this should be relevant.

## Steps to reproduce

1. Run Firefox in wayland (not sure if this is relevant)
1. Start Firefox with clean profile.
2. Add css style to chrome to hide Firefox's default tab bar and the "Tree Style Tab" title in the sidebar (not sure if this is relevant)
3. Install TST.
4. open some tabs 
5. work with firefox and other programs. Switch between windows many times.

Then sometimes it happens that suddenly a tab is marked with a white box like this:

![Screenshot_20230606_233557-1](https://github.com/piroor/treestyletab/assets/5571650/19facad3-39f6-496c-a10e-d8badf46578c)

When I switch between windows again or try to type text on a website or do whatever you do when you work on you PC, it happens that this tab, that was previously focused gets activated. When you just continue to work with other windows and continue switching windows, sometimes it happens that the next tab gets also highlighted and then activated.

This happens on two of my laptops which are very similarly configured.

## Environment

 * Platform (OS): ArchLinux with Plasma Desktop and Wayland
 * Version of Firefox: 113.0.2
 * Version (or revision) of Tree Style Tab: 3.9.15

**Comment by piroor** [comment]
Could you try without this step?:

> Add css style to chrome to hide Firefox's default tab bar and the "Tree Style Tab" title in the sidebar (not sure if this is relevant)

**Comment by sedrubal** [comment]
I'm currently evaluating if the issue is caused by the style. Until now, it didn't happen again. But it's a very sporadic issue. Sometimes it doesn't happen for days and then it happens all the time. I'll report back if it happens again.

**Comment by sedrubal** [comment]
After ~1 week it happens again. It happens, when the window of firefox gets focused or a keyboard shortcut like <kbd>Ctrl</kbd>+<kbd>Tab</kbd> gets pressed.

**Comment by sedrubal** [comment]
It is still a very annoying issue. I'm very sorry that I can't provide more information.

Can you maybe explain what are these white boxes around tabs that randomly appear before the random tab switching behind?

**Comment by SXZ1** [comment]
> Can you maybe explain what are these white boxes around tabs that randomly appear before the random tab switching behind?

Hold Ctrl and left-click on any tab that is not active (active = current = the tab that currently has focus):  will the same white box appear around it too?

**Comment by sedrubal** [comment]
No, if I left-click on the currently active tab holding <kbd>Ctrl</kbd>, it looks like this:

![Screenshot_20230723_132839](https://github.com/piroor/treestyletab/assets/5571650/7296f2bc-518e-4abc-bf9d-2bd20b1b99d9)

If I first click the current tab and then another one holding <kbd>Ctrl</kbd>, it looks like this:
![Screenshot_20230723_132913](https://github.com/piroor/treestyletab/assets/5571650/21c30d12-4883-47c5-8c67-a4d299b2e113)

**Comment by sedrubal** [comment]
Ah but If I move a tab onto another one (to make it a child of the other one), this box appears:

![Screenshot_20230723_133152](https://github.com/piroor/treestyletab/assets/5571650/d41ef8f5-6aeb-4d1f-bbf9-18084a0f561d)

And If I drop the tab again on its original position and switch the window afterwards and come back to firefox, then the white box appears *sometimes* around the tab I started to move before.

**Comment by nyz93** [comment]
I was able to reproduce it on a clean profile with the default TST settings simply by dragging tabs over each other and switching windows with the mouse.
Unfortunately I think this is an upstream Wayland bug in KDE or Firefox, not TST specific, it's just easiest to reproduce it with this addon. Even regular websites sometimes think there is a drag event happening. The behavior TST is displaying here is actually the same as you'd see when a **file** is being dragged over a tab, which is to show the rectangle and then switch to the tab after a short delay.

**Comment by nyz93** [comment]
Further testing shows that this is actually a GTK/KDE bug and most likely these: https://gitlab.gnome.org/GNOME/gtk/-/issues/5519 https://bugs.kde.org/show_bug.cgi?id=464196

**Comment by sedrubal** [comment]
You're awesome, thanks for figuring this out.
