### ISSUE TITLE
Add command to copy URLs from subtree [feature request]

### ISSUE THREAD

**Issue by ivan-danilov** [piroor/treestyletab#3352]
Maybe I'm missing something obvious but I haven't found a way to just copy locations of a subtree tabs. There's a feature to bookmark the tree, but I tend to use bookmarking rarely, and it is useless if you want to share the list with someone, e.g. using a chat.

I'm not sure if the functionality belongs to TST itself or to one of the add-ons, but I wasn't been able to locate existing issue with the request.

The proposal is to add a context menu "Copy URLs" to each tab that copies to clipboard all URLs of a subtree with root at the clicked tab, one URL per line, regardless of collapsed/expanded state, and currently selected tab.

For example, if there's a tree like this:
```
A
\- B (collapsed)
   |- B1
   |- B2
   \- B3
C
\- D
E (selected)
```
The user right-clicks A and selects "Copy URLs", the following text should be copied to the clipboard (where `URL(X)` should be replaced with the actual URL or the specific tab):
```
URL(A)
URL(B)
URL(B1)
URL(B2)
URL(B3)
```

As an alternative, I can imagine taking tab title also useful after space. If deemed useful, the two can be distinguished with names "Copy URLs only" and "Copy URLs with titles". In the example above, executing "Copy URLs with titles" should bring the following text to the clipboard:
```
URL(A) A
URL(B) B
URL(B1) B1
URL(B2) B2
URL(B3) B3
```

**Comment by SXZ1** [comment]
I'll offer a workarond in the meanwhile: right-click on tree -> bookmark this tree, go to bookmarks->open folder with bookmarked tabs - Select All - Copy
That will copy all urls. OP should be aware of this, posting for people who don't know.

**Comment by piroor** [comment]
I ordinarily use [Copy Selected Tabs to Clipboard](https://addons.mozilla.org/en-US/firefox/addon/copy-selected-tabs-to-clipboar/) for the purpose. Shift-click or Ctrl-click tabs to highlight and choose the format from the right-click menu, then you'll get copied data in arbitrary format.

The addon does not provide any command like "copy subtree of TST" but it looks the good place to provide such a feature. Pull requests to add the command is welcome.
https://github.com/piroor/copy-selected-tabs-to-clipboard

**Comment by ivan-danilov** [comment]
@piroor cool, thanks, this addon solves my needs :)
