### ISSUE TITLE
[Enhancement] Add sorting to Tab list

### ISSUE THREAD

**Issue by jthomasser** [piroor/treestyletab#3353]
## Abstract

It would be a great feature addition to have some mechanism to sort the list of tabs. This especially useful when you have 10's of tabs (which i often do) and i keep them open almost all the time. sometimes i have duplicates. allowing for a sort will allow to remove unnecessary tabs, or maybe a "dedupe" feature. the latter may be more difficult.  

## Steps to see the situation

N/A this is an enhancement request.

## Environment

 * Platform (OS): MacOS
 * Version of Firefox:  102.12
 * Version (or revision) of Tree Style Tab: 3.9.15

**Comment by piroor** [comment]
There are similar requests: #3106, #94 and more. They (including this) are beyond the project scope and I won't add the feature as a built-in. Instead I believe it should be done an addon specific for the sorting purpose (I don't know whether available addon exists or not so you may need to develop it newly), and I'm positive to improve compatibility of TST with such a sorter addon.

**Comment by jthomasser** [comment]
found this, works great with your tool. https://addons.mozilla.org/en-US/firefox/addon/sort-tabs-advanced/ . thanks
