### ISSUE TITLE
[Bug] group-tab.html property not being used

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#3357]
## Abstract
vertical-align is misspelled and not used in group-tab.html

## Steps to reproduce

Check source code:

https://github.com/piroor/treestyletab/blob/053755304239d8c54cc3b926bf109bf69c409bcc/webextensions/resources/group-tab.html#L187-L194

I ran across this trying to customize some CSS and noticed this value was disabled because it was misspelled.

## Expected result
I guess check your expected desire from using this and update as appropriate.  I'm trying to fix some overlapping elements on this page when there are many tabs.  Not sure if this is related or not.  I will continue to investigate.

![image](https://github.com/piroor/treestyletab/assets/979729/a2fb8724-98cc-4ed1-b771-f085e75b209f)

## Actual result
Value is not being used.

## Environment

 * Platform (OS): Windows 10 (latest)
 * Version of Firefox: 114.0.2
 * Version (or revision) of Tree Style Tab: 3.9.15

**Comment by piroor** [comment]
Thanks! The commit fa43603 should fix this.
