### ISSUE TITLE
[Enhancement] Prevent drag-and-drop creating tree structure

### ISSUE THREAD

**Issue by sith-on-mars** [piroor/treestyletab#3358]
## Abstract

I would like to completely disable tree functionality. https://github.com/piroor/treestyletab/issues/1544 already provides a workaround. However,  you're still allowed to create tree by using drag-and-drop. Would it be possible to prevent it so that we won't accidentally create tree structure?

Here is a short video about the issue I was talking about:

[Screencast from 2023-07-07 16-10-07.webm](https://github.com/piroor/treestyletab/assets/37974764/a17eb821-5b41-480c-964a-10624ab7f08a)

I'm aware of other vertical tab addons that offer no tree structure, however, non of them really works as good as TST. Feel free to close this if it's outside the scope of TST.

## Environment

 * Platform (OS):  Fedoral Silverblue
 * Version of Firefox:  latest
 * Version (or revision) of Tree Style Tab:

**Comment by irvinm** [comment]
I know this doesn't solve exactly what you are looking for, BUT if you just wanted the tree to be "flattened" (although they are still trees) you can simply remove the indentation with some simple TST CSS.  However, they are still trees and dragging and dropping would still be the same in terms of grabbing parents and their children.

```
:root .tab:not(.pinned)[data-level] {
	--tab-indent: 0px;
}
```

![image](https://github.com/piroor/treestyletab/assets/979729/1c07f05f-e157-4dfd-b328-278b117b1d24)

**Comment by piroor** [comment]
This is beyond the scope of this project. TST is strongly designed to manage tree of tabs. I recommend you to choose another extension aims to provide flat tabs: https://github.com/piroor/treestyletab#similar-projects
