### ISSUE TITLE
Slight gap at bottom of tab list in photon theme on upgrading from 3.9.15 to 3.9.16

### ISSUE THREAD

**Issue by ellisonmarks** [piroor/treestyletab#3364]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Select the photon theme in the addon preferences.
 4. Open enough tabs that the scrollbar becomes visible.
 5. Scroll to the very bottom of the tab list.

## Expected result

The bottom of the last tab should be flush with the top of the new tab button.

## Actual result

There is a slight gap between the bottom of the last tab and the top of the new tab button. It's only a few pixels normally, but I also use 0px top and bottom padding, which seems to increase the gap.

## Environment

 * Platform (OS): Tested on Windows 11 x86_64 build 22621 and Mac M1 13.4.1 (c)
 * Version of Firefox: 115.0.2
 * Version (or revision) of Tree Style Tab: 3.9.16

**Comment by piroor** [comment]
I've confirmed that this problem was there on old versions and the gap is increased at 3.9.16.
(The gap is from box-shadow of tabs. I've introduced some changes around the definition of the box-shadow at 3.9.16.)

**Comment by piroor** [comment]
> this problem was there on old versions

Sorry I misunderstood this point. It is not a gap, but a regular border. The gap was canceled by `overflow:hidden` in old versions and not it is not canceled anymore. I've introduced the commit d27ae19 to cancel the gap again.
