### ISSUE TITLE
[Bug] Copy tab but not visible in TST

### ISSUE THREAD

**Issue by 707wk** [piroor/treestyletab#3367]
![GIF](https://github.com/piroor/treestyletab/assets/11644507/8a78e432-9d8e-429a-95b4-5043f0ae5a58)
Copy with the mouse after pressing the ctrl key, or use the copy tab command in the right-click menu

## Environment

 * Platform (OS): Windows 11
 * Version of Firefox: 115.0.3
 * Version (or revision) of Tree Style Tab: 3.9.16

**Comment by 707wk** [comment]
found the reason, i set the value is -1
![图片](https://github.com/piroor/treestyletab/assets/11644507/fa2c6e6c-91be-4ee8-9671-d56d0ae275ce)

**Comment by piroor** [comment]
(For non zh_CN users: the option is "Abort tab duplication when it takes N milliseconds or more." under "Development".)
