### ISSUE TITLE
[Bug] Closing crosses misalign

### ISSUE THREAD

**Issue by Mike6547** [piroor/treestyletab#3368]
Hi, I'm having a problem with TreeStyleTab, the closing crosses indent randomly when using TST.

![Sélection_160](https://github.com/piroor/treestyletab/assets/139588469/37bbbd3f-b8f1-42b0-a9dc-f3b2140bd501)

I've tested several versions of TST, even completely removed the extension and reinstalled from the latest GitHub version, but the problem continues to appear randomly when using the browser!

How can I solve this problem?

**Comment by Mike6547** [comment]
I just found out what the problem was. It's because of the "TST Tab Search https://github.com/NiklasGollenstede/tst-search#readme" extension that the closing crosses become randomly misaligned when using the browser. Deactivating the extension corrects the problem immediately.

I find this extension rather useful, is there any way of correcting this problem?

**Comment by piroor** [comment]
Fixed by TST Tab Search v0.0.7.
