### ISSUE TITLE
New Tab doesn't work

### ISSUE THREAD

**Issue by Joe-Green** [piroor/treestyletab#337]
Like veggiesama recently (and more than a few others out there, I think), I find that suddenly I can't create a new tab. This holds true for middle-button, File -> New Tab, and any other way I can think of trying to create one. I can produce the same interesting-looking stuff in the error console as veggiesama did. The sudden break doesn't seem to have corresponded with any explicit software upgrade. I've completely wiped every trace of Firefox on disc and in the registry, then re-installed and done nothing but add TST but to avail. The only way I can get new tabs is in safe mode. I'm tearing my hair out over this one. Now I understand that it's not the fault of TST but it would be really really useful if someone could provide pointers on to how to debug this, like how to find out what might be hidden.

XP Pro SP3, FF 14.0.1 FWIW.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
