### ISSUE TITLE
Open TST Folder Expand Collapse does not work

### ISSUE THREAD

**Issue by w00kee** [piroor/treestyletab#3380]
## Abstract
The TST Addon Open TST Folder Expand Collapse does not work.
The click on a FolderTab is processd by TST as well as the Addon.
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Make Firfox reopen tabs on Restart
 4. Install TST Addon Open TST Folder Expand Collapse and activate
 5. Create Folder tab on root Level with some Tabs contained
 6. Restart Firefox/Pc
 7. Click on Folder Tab

## Expected result
eR1: Folder Opens

## Actual result
aR1: Folder Opens (Tst) does this)
aR2: Folder Tab is Selected (Tst does this)
aR3: Folder Closes (Tst Addon does this by toggleing)

## Environment

 * Platform (OS):  Windows 10
 * Version of Firefox: 116.0.3
 * Version (or revision) of Tree Style Tab: 3.9.16 (2023.7.21)
 * TST Config:
 {
  "__ConfigsMigration__userValeusSameToDefaultAreCleared": true,
  "autoAttachOnAnyOtherTrigger": 0,
  "autoAttachOnDuplicated": 2,
  "autoAttachOnNewTabCommand": 0,
  "autoGroupNewTabsFromOthers": true,
  "avoidDiscardedTabToBeActivatedIfPossible": true,
  "cachedExternalAddons": [
    "tst-folder-expand-collapse@pale-ed"
  ],
  "chunkedUserStyleRules0": "OnJvb3QsICNiYWNrZ3JvdW5kIHsKYmFja2dyb3VuZDogCiAgIzIwMjAyMAp9Ci8qb3RoZXIgY29sb3JzICMxMjEyMTI7Ki8KLyogU2hvdyB0aXRsZSBvZiB1bnJlYWQgdGFicyB3aXRoIHJlZCBhbmQgaXRhbGljIGZvbnQgKi8KLyoKOnJvb3Quc2lkZWJhciB0YWItaXRlbS51bnJlYWQgLmxhYmVsLWNvbnRlbnQgewogIGNvbG9yOiByZWQgIWltcG9ydGFudDsKICBmb250LXN0eWxlOiBpdGFsaWMgIWltcG9ydGFudDsKfQoqLwoKLyogQWRkIHByaXZhdGUgYnJvd3NpbmcgaW5kaWNhdG9yIHBlciB0YWIgKi8KLyoKOnJvb3Quc2lkZWJhciB0YWItaXRlbS5wcml2YXRlLWJyb3dzaW5nIHRhYi1sYWJlbDpiZWZvcmUgewogIGNvbnRlbnQ6ICLwn5W2IjsKfQoqLw==",
  "colorScheme": "system-color",
  "configsVersion": 28,
  "context_bookmarkTree": false,
  "context_collapseAll": false,
  "context_collapseTreeRecursively": false,
  "context_expandTreeRecursively": false,
  "context_topLevel_bookmarkTree": true,
  "context_topLevel_collapseAll": true,
  "context_topLevel_collapseTreeRecursively": true,
  "context_topLevel_expandTreeRecursively": true,
  "context_topLevel_sendTreeToDevice": false,
  "dropLinksOnTabBehavior": 2,
  "enableWindowsBehaviors": true,
  "grantedExternalAddonPermissions": {
    "tst-folder-expand-collapse@pale-ed": [
      "tabs"
    ]
  },
  "incognitoAllowedExternalAddons": [
    "tst-folder-expand-collapse@pale-ed"
  ],
  "inheritContextualIdentityToSameSiteOrphanMode": 1,
  "insertNewTabFromPinnedTabAt": 0,
  "notifiedFeaturesVersion": 9,
  "optionsExpandedSections": [
    "section-debug"
  ],
  "showExpertOptions": true,
  "syncDevices": {
    "device-1670846607295-24142": {
      "id": "device-1670846607295-24142",
      "name": "Firefox on Windows",
      "icon": "device-desktop",
      "timestamp": 1693811611036
    }
  },
  "treeDoubleClickBehavior": 1,
  "userStyleRules": "",
  "userStyleRulesFieldHeight": "120px",
  "warnOnCloseTabs": false,
  "warnOnCloseTabsByClosebox": false
}

**Comment by irvinm** [comment]
In TST, do you have this enabled for the addon?  If not, enable it and restart the browser.

![image](https://github.com/piroor/treestyletab/assets/979729/4dd6032e-d4e8-4733-bc7a-0771f0f5e910)

**Comment by w00kee** [comment]
Yes the option is set.

**Comment by irvinm** [comment]
Only other things I could suggest (The functionality works for me in a clean profile, and I looked at the code and it is only like 60 lines of code and half of it is just registering with TST) is to:

- Verify that the additional addon has the proper permissions as well.

![image](https://github.com/piroor/treestyletab/assets/979729/e66952ed-9635-4438-a582-86acce072f8c)

- Try a new profile (just for testing) with just TST and this additional addon to see if it works for you.  (Maybe another addon conflict in some way?)

**Comment by piroor** [comment]
It looks a bug of [TST Folder Expand Collapse](https://addons.mozilla.org/firefox/addon/tst-folder-expand-collapse/). It should listen and cancel `tab-mousedown` because TST moves focus to the clicked tab before the mouse button is released, but it actually listens `tab-clicked` which is notified after the mouse button is released.
