### ISSUE TITLE
[Enhancement] Bigger pinned tabs icons

### ISSUE THREAD

**Issue by perroboc** [piroor/treestyletab#3381]
## Abstract
I would like to be able to change the size of pinned tabs

## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Pin some tabs
 4. Pinned tabs might appear too small at the top

![image](https://github.com/piroor/treestyletab/assets/2722773/b0c45960-5c15-4670-907b-8be920758682)

## Expected result
I wish there was an option to set the size of pinned tab icons, maybe even options like 1x, 2x, 4x, etc. I read the code a bit and found `--pinned-tabs-area-size` might be changed, but I didn't find how in the plugin options, or through customs styling.

## Actual (present) result
The pinned tabs area has the same height as the tabs icons

## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: 117.0 
 * Version (or revision) of Tree Style Tab: 3.9.16

**Comment by irvinm** [comment]
Some simple TST CSS should help:

```
tab-item.pinned tab-favicon {
  transform: scale(150%);
}
```

![image](https://github.com/piroor/treestyletab/assets/979729/1e2655d2-ebc2-4147-9e70-aa1b3013491d)

**Comment by perroboc** [comment]
Awesome! Thank you!
