### ISSUE TITLE
 List all tabs button not visible

### ISSUE THREAD

**Issue by boardtc** [piroor/treestyletab#3385]
The List all tabs button, i.e. toolbarbutton#alltabs-buttonis not showing on the tabs toolbar for me when using Tree Style tab.

Another user confirmed [in the Mozillazine forum](https://forums.mozillazine.org/viewtopic.php?p=14963275#p14963275) that it was not visible and suggested opening a ticket here.

**Comment by piroor** [comment]
Please fill the [issue template](https://github.com/piroor/treestyletab/blob/trunk/.github/ISSUE_TEMPLATE/bug_report.md) to help debugging. Screenshots may help my debugging more.

**Comment by irvinm** [comment]
@boardtc, I do not believe this is TST related at all, but more of a userChrome.css customization issue.  This should likely be moved over to the Discussions.  Either way, piroor is right that the issue template needs to be filled out to understand the steps to reproduce.  I believe you will still have this issue even if you uninstalled TST.

**Comment by boardtc** [comment]
Haven't figured out how to move it, any advice is appreciated. Or maybe it's an old-school "move", close and reopen?

**Comment by irvinm** [comment]
@boardtc you still haven't explained how to reproduce this using the [issue template](https://github.com/piroor/treestyletab/blob/trunk/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by boardtc** [comment]
This was a misunderstanding on my part, apologies.
