### ISSUE TITLE
[Meta] No new releases on GitHub

### ISSUE THREAD

**Issue by Clozent** [piroor/treestyletab#3386]
I couldn't help but notice the fact that the latest version released on GitHub is 3.8.2 from July of 2021, despite the fact the extention has recived numerous new versions since. Why is that? Not uploading new releases to the repo makes it more difficult to track issues, as well as making it unclear that there have been newer releases since 3.8.2.

**Comment by irvinm** [comment]
While @piroor is not keeping copies here on Github, you can download older versions (not all) by going to:  https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/versions/

You can also grab XPI files in Github under the "actions" menu. (https://github.com/piroor/treestyletab/actions)  Although I believe generated XPIs do get deleted after a certain period of time.  [I am not sure these are signed either]

I believe you have to manually take extra steps to record "releases" (https://github.com/piroor/treestyletab/releases) on Github and obviously that would be up to Piroor if he wants to do that.

**Comment by piroor** [comment]
Sorry for my laziness... I've mirrored XPIs of recent releases to this repository.
