### ISSUE TITLE
[Bug] in private windows TST partly stops working (the tree itself is fine, the interaction isn't)

### ISSUE THREAD

**Issue by LupinIII** [piroor/treestyletab#3387]
Recently (unfortunately I can't tell after which FF/TST update), TST stopped working properly in private windows.
The tree itself is fine. I can move tabs around, indentation is correct, collapsing/expanding trees works, new tabs get opened in the right position.
But for some reason I can not switch to some of the tabs by clicking them. I can't even close these tabs by clicking on the respective tab's "X". TST extensions like "TST Hoverswitch" do not switch to these tabs either, and the extension "TST Mouse Wheel" does not work at all (it doesn't switch even between those tabs where clicking and hovering works).
I have not yet found a pattern to which tabs this will happen. Firefox's own hotkeys still work as normal on these tabs (like Ctrl-PgUp/PgDown to switch to the tab or Ctrl-W to close the tab). 

I don't think this ever happened in a non-private FF window. Although there is one small odd behavior (just mentioning it in case it is somehow a hint). "TST Hoverswitch" does not switch to the hovered tab if the mouse moved off a tab that shows an "about:" page (like "about:preferences", "about:addons" or "about:config").

[EDIT]
I just found the simplest test case. A blank tab in a private window triggers what I've described above. For testing I've used wikipedia to get a decently large tab tree in a private window. Everything (including TST extensions) worked as expected. But as soon as I opened a blank tab (Ctrl-T), TST Mouse Wheel stopped working completely, Hoverswitch would not switch to the blank tab (but it would switch away to one of the wikipedia tabs), clicking the tab does not switch to it either and the tab's X does not work. If I Ctrl-PgUp to the blank tab and close it with Ctrl-W, or enter an URL into the tab's address bar, everything is back to normal. For some reason some tabs even with an URL entered still trigger the bug.

Windows 10
Firefox 117.0
TST 3.9.17

**Comment by Lej77** [comment]
This bug seems to be introduced in version `3.9.16` since version `3.9.15` works without issues. The issue seems to be when a helper addon is listening to Tree Style Tab mouse events in a private window. This means that the helper addon must be allowed in TST option page so that it `Notify Messages from Private Windows`. Clicking on a tab that uses an inbult favicon (such as a new tab or the `about:addons` tab) will cause TST to encounter an error and no message will be sent to the helper addon. The clicked tab will also not be selected (same as if the addon returned `Promise.resolve(true)` even though that isn't what happened).

The error that is logged in TST is:

```text
Uncaught (in promise) Error: Failed to open database
    onerror moz-extension://a96451a8-a49a-446e-8618-196a10143caa/extlib/TabFavIconHelper.js:154
    _openDB moz-extension://a96451a8-a49a-446e-8618-196a10143caa/extlib/TabFavIconHelper.js:153
    _openDB moz-extension://a96451a8-a49a-446e-8618-196a10143caa/extlib/TabFavIconHelper.js:150
    _getAssociatedFavIconUrlFromTabUrl moz-extension://a96451a8-a49a-446e-8618-196a10143caa/extlib/TabFavIconHelper.js:228
    _getAssociatedFavIconUrlFromTabUrl moz-extension://a96451a8-a49a-446e-8618-196a10143caa/extlib/TabFavIconHelper.js:227
    _getEffectiveFavIconURL moz-extension://a96451a8-a49a-446e-8618-196a10143caa/extlib/TabFavIconHelper.js:522
    _getEffectiveFavIconURL moz-extension://a96451a8-a49a-446e-8618-196a10143caa/extlib/TabFavIconHelper.js:470
    loadToImage moz-extension://a96451a8-a49a-446e-8618-196a10143caa/extlib/TabFavIconHelper.js:398
    processOneTask moz-extension://a96451a8-a49a-446e-8618-196a10143caa/extlib/TabFavIconHelper.js:387
    _run moz-extension://a96451a8-a49a-446e-8618-196a10143caa/extlib/TabFavIconHelper.js:392
    _addTask moz-extension://a96451a8-a49a-446e-8618-196a10143caa/extlib/TabFavIconHelper.js:373
    loadToImage moz-extension://a96451a8-a49a-446e-8618-196a10143caa/extlib/TabFavIconHelper.js:397
    set favIconUrl moz-extension://a96451a8-a49a-446e-8618-196a10143caa/sidebar/components/TabElement.js:613
    _updateTabProperties moz-extension://a96451a8-a49a-446e-8618-196a10143caa/sidebar/components/TabElement.js:529
    update moz-extension://a96451a8-a49a-446e-8618-196a10143caa/sidebar/components/TabElement.js:324
    connectedCallback moz-extension://a96451a8-a49a-446e-8618-196a10143caa/sidebar/components/TabElement.js:164
    <anonymous> moz-extension://a96451a8-a49a-446e-8618-196a10143caa/sidebar/sidebar-tabs.js:284
    dispatchWithDetails moz-extension://a96451a8-a49a-446e-8618-196a10143caa/extlib/EventListenerManager.js:64
    dispatch moz-extension://a96451a8-a49a-446e-8618-196a10143caa/extlib/EventListenerManager.js:43
    init moz-extension://a96451a8-a49a-446e-8618-196a10143caa/common/Tab.js:1726
    <anonymous> moz-extension://a96451a8-a49a-446e-8618-196a10143caa/sidebar/sidebar-tabs.js:542
    dispatchWithDetails moz-extension://a96451a8-a49a-446e-8618-196a10143caa/extlib/EventListenerManager.js:64
    dispatch moz-extension://a96451a8-a49a-446e-8618-196a10143caa/extlib/EventListenerManager.js:43
    onConnectionMessage moz-extension://a96451a8-a49a-446e-8618-196a10143caa/sidebar/background-connection.js:127
    onConnectionMessage moz-extension://a96451a8-a49a-446e-8618-196a10143caa/sidebar/background-connection.js:113
TabFavIconHelper.js:154:16
```

Below is the helper addon I used to test this issue:

<details>
  <summary>Example TST helper addon</summary>

## `manifest.json`
```json
{
  "manifest_version": 2,
  "name": "Log TST Mouse Events",
  "version": "1.0",
  "permissions": [],
  "background": {
    "scripts": [
      "background.js"
    ]
  }
}
```

## `background.js`
```javascript
function getFormattedTime() {
  let time = Date.now();
  return '' +
    Math.trunc(time / (1000 * 60 * 60 * 24)) +
    ' days ' +
    Math.trunc(time / (1000 * 60 * 60) % 24).toString().padStart(2, '0') +
    ':' +
    Math.trunc(time / (1000 * 60) % 60).toString().padStart(2, '0') +
    ':' +
    Math.trunc(time / (1000) % 60).toString().padStart(2, '0') +
    ',' +
    Math.trunc(time % 1000).toString().padStart(3, '0');
}

const TST_ID = 'treestyletab@piro.sakura.ne.jp';

async function registerToTST() {
  try {
    await browser.runtime.sendMessage(TST_ID, {
      type: 'register-self',
      // The name of your addon (string, optional)
      name: browser.runtime.getManifest().name,
      // The list of listening message types (array of string)
      listeningTypes: ['tab-clicked', 'tab-dblclicked', 'tab-mousedown', 'tab-mouseup'],
      permissions: []
    });
  }
  catch (e) {
    // TST is not available
  }
}

async function start() {
  browser.runtime.onMessageExternal.addListener((message, sender) => {
    switch (sender.id) {
      case TST_ID:
        console.log(
          `TST Event "${message.type}"!\n`,
          message,
          "\nTime: " + getFormattedTime(),
        );
        switch (message.type) {
          case 'tab-clicked':
            return Promise.resolve(false);
        }
        break;
    }
  });
  registerToTST();
};
start();
  ```
  
</details>

**Comment by LupinIII** [comment]
Thanks for the detailed analysis! Due to that I now also found what's common to the tabs that break TST: it's those that do not have a favicon.

To test: in a private window search for anything on google and on the result page open any image in a new tab (by right clicking -> "show image in new tab"). It doesn't have to be an image search, the "favicons" that google shows in front of every result work as well. This should create a tab without a favicon and break TST. (on google the images seem to be either inline base64 encoded "data:" images or are served by gstatic.com, which does not have a favicon).

Maybe related as well, now that I think of it: even in a non-private window TST extensions like "hoverswitch" and "mouse wheel" aren't responsive, if you just opened a few tabs to different sites (e. g. by middle clicking a list of links in search results). While some of those tabs are still loading hoverswitch and mouse wheel don't work for a short time (a second or two). It is hard to test for me, but could the "lag" happen while those tabs are still trying to load the favicon? The difference to a private window being that a missing favicon does not "perma-break" TST.

**Comment by irvinm** [comment]
@piroor, I just wanted to make sure you saw this one.  Still has the "needs-triage" tag.

**Comment by joshuacant** [comment]
Hi, I'm the TST Mouse Wheel dev. I started noticing this in my own use, but didn't have time to look into it until this week. I got about 30 minutes into trying to figure it out when I had the bright idea to search the issues here and see if anyone else had run into the problem, since no issues were filed in my repo. 

Thank you both for saving me a lot of time trying to chase this down. I'm sure @piroor will fix this one when he gets a chance. 😄

**Comment by piroor** [comment]
Sorry for my silence. I missed that the IndexedDB API is unavailable on private windows. I've introduced some changes to bypass IndexedDB-dependent operations on private windows. The error @Lej77 investigated won't raised anymore so I hope the change solve problems around helper addons and private windows successfully.
