### ISSUE TITLE
Enhancement: calculate sub tabs margin based only on expanded tabs

### ISSUE THREAD

**Issue by Infocatcher** [piroor/treestyletab#339]
<pre>[ Parent tab ]
&lt;- margin -&gt;[ Child tab ]</pre>

Small margin really needed only for deep trees.<br/>
And isn't necessary if these trees are collapsed.<br/>
<br/>
Visualization:
<pre>
[ Tab ]       | &lt;- end of tab bar
 [ Tab ]      |
  [ Tab ]     |
   [ Tab ]    |
    [ Tab ]   |
     [ Tab ]  |
      [ Tab ] |
       [ Tab ]|
[ Tab ]       |
 [ Tab ]      |
</pre>
Collapse tree:
<pre>
[ Tab ]       |
  [ Tab ]     |
    [ Tab (5)]|
[ Tab ]       |
  [ Tab ]     |
</pre>

But we should wait while mouse is over tabs (like new close tabs behavior). Or while mouse aren't moved after click on the twisty.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
