### ISSUE TITLE
[Enhancement] Add a copy tree links option

### ISSUE THREAD

**Issue by HumanG33k** [piroor/treestyletab#3391]
Add a :

right clic -> tree of tabs -> copy that tree links 
(add links one by line to clipboard)

**Comment by piroor** [comment]
[Copy Selected Tabs to Clipboard](https://addons.mozilla.org/firefox/addon/copy-selected-tabs-to-clipboar/) provides the feature. Please try it.

**Comment by piroor** [comment]
Anyway I won't add the feature as a built-in of TST due to its project policy, sorry.
https://github.com/piroor/treestyletab#user-content-feature-requests-add-more-minor-trivial-options
