### ISSUE TITLE
[Enhancement] Improve background CPU usage

### ISSUE THREAD

**Issue by jmbreuer** [piroor/treestyletab#3397]
## Abstract

TreeStyleTabs seems to busy-wait/busy-poll stuff all the time.

## Steps to see the situation

 1. Have a browsing session with, in my case, 644 tabs over 35 windows; otherwise completely idle (most of those tabs are 'discarded', see [AutoTabDiscard](https://webextension.org/listing/tab-discard.html))
 2. In `about:processes`, see "Extensions" taking up nearly 100% of one core (i7-6700HQ)
 3. Click on the conveniently located "Profile all threads of this process for 5 seconds" button of the Extensions process
 4. In the profile result, see `updateTimeoutTimer` in `moz-extension://6efa3d93-bed2-4dff-a92a-064725d94b45/common/sidebar-connection.js:165:31` as the 'culprit'

## Expected result

Idle CPU usage of below 30% ideally.

## Actual (present) result

Idle CPU usage of 70% - 115% pretty much all the time.

## Additional remarks

I'd be happy to know about a tunable where I could trade off this CPU usage against how quickly TST reacts to new tabs or such (which, by the way, already is noticeably slow for me - but if that is 'because' or 'despite' of this issue, I cannot say).

## Environment

 * Platform (OS): Gentoo amd64 
 * Version of Firefox: LibreWolf 118.0.1-1
 * Version (or revision) of Tree Style Tab: 3.9.17

**Comment by piroor** [comment]
Could you try larger value for `heartbeatInterval`, for example 10000 ? The insternaloption is configurable via TST otpsions => Development => All Configs.

**Comment by piroor** [comment]
I've increased the default heartbeat interval to 5000msec (5sec) to reduce CPU usage.
