### ISSUE TITLE
[Enhancement] Option to go to the last active tab when closing the current tab.

### ISSUE THREAD

**Issue by Clozent** [piroor/treestyletab#3398]
## Abstract
My idea (which I could have sworn was already in TST) is for the extention to save a history of active tabs, and would have an option to switch to the last active tab from the saved history upon closing the current one, or in other words: Every time a tab is closed, the user is taken one step back in the "active tab" history.

## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open some tabs (in this example, five).
 4. Go to the second tab.
 5. Without clicking any other tab, go to the fourth tab.
 6. Close the fourth tab.

## Expected result
You should be sent to the second (the last active) tab.

## Actual (present) result
You are sent to the fifth (now fourth) tab.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 118.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.9.17

**Comment by irvinm** [comment]
You could try this addon to see if it fits your needs:  https://addons.mozilla.org/en-US/firefox/addon/select-after-closing-current/

You can basically specify what tab to select after closing a tab.  There is an option in there for "last accessed" as one of the options.  I use this addon and it works well.

I prefer to try to keep my selected tab inside the current tree when closing a tab, but if it is the last tab from a tree, I select the "last accessed" tab.

![image](https://github.com/piroor/treestyletab/assets/979729/dcca8470-b110-4cc1-b138-8a6601f5a65c)

**Comment by piroor** [comment]
This project has a policy: TST should concentrate to provide features compatible to Firefox's built-in features and tree related features. Unrelated features should be separated from TST so I won't add the feature as a built-in of TST. Instead I'm positive to improve compatibility of TST with other feature-oriented addons. Please comment again if you see any compatibility issue with the "Select After Closing Current" addon.
