### ISSUE TITLE
Tab height/padding ignores GTK theme on Linux

### ISSUE THREAD

**Issue by yump** [piroor/treestyletab#340]
Steps to reproduce:

1. Install and select the [Clearlooks Compact](http://gnome-look.org/content/show.php/Clearlooks+Compact?content=69357) GTK2 theme.

2. Create a clean Firefox (16.0a2 and possibly others) profile.

3. Install Tree Style Tab.

Expected behavior: Tabs have little padding around the text, and are narrow.

Observed behavior: Tabs have the usual excessive padding around the text, and are wide.

A git bisect suggests the problem is introduced by 2c2050b61e75e8d919945d83b923cc1c29432b19.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
