### ISSUE TITLE
[Bug] Use prefers-color-scheme for icons, and remove the manual setting.

### ISSUE THREAD

**Issue by emilio** [piroor/treestyletab#3401]
Sometimes the icon doesn't appear in the right color-scheme, like in the context menu, unless you manually toggle the setting in the extension settings.

Instead, prefers-color-scheme can be used, see https://github.com/mozilla/multi-account-containers/pull/2584 for an example, https://bugzilla.mozilla.org/show_bug.cgi?id=1779457.

That would make this setting obsolete and simplify the code presumably.

**Comment by piroor** [comment]
Thanks! I've done this with the commit 00645f5.

**Comment by emilio** [comment]
Sweet! Fwiw, I think you can removemost of the icons if you remove the width / height attributes and just leave the viewBox
