### ISSUE TITLE
[Enhancement] [Minor] Include TST Folder tab URL schema in the Documentation

### ISSUE THREAD

**Issue by fabiorzfreitas** [piroor/treestyletab#3409]
## Abstract

This is a very minor suggestion, no more than just a small addiction to the docs for `ext+treestyletab:group?title=<TITLE>`, `ext+treestyletab:group?title=<TITLE>&temporary=true` and `ext+treestyletab:group?title=<TITLE>&temporaryAggressive=true`.

## Steps to see the situation

On my Bookmarks bar, I have a fix link to `ext+treestyletab:group?title=<TITLE>`. I find it useful when I know I'm going to need some kind of a workspace for my next tabs.

## Expected result

I found the 3 URL schemas (meaning what comes after `?`) by clicking the buttons and checking the URL change, easy enough.

## Actual (present) result

I didn't recall immediately that I could use this simple method, so I started by searching this repo (issues, wiki, code etc.). I think it would be nice to have those described somewhere.

## Environment

 * Platform (OS): Windows 11
 * Version of Firefox: Firefox Developer 120.0b7 (64-bits)
 * Version (or revision) of Tree Style Tab: 3.9.7

## Edit

PS: I don't know if there are any other "arguments" to be used like this, a useful one would be something like `Expanded=true` for other behaviors for a folder, it would be useful to know them!

**Comment by piroor** [comment]
OK, I've added a FAQ topic for that: https://github.com/piroor/treestyletab/#user-content-feature-requests-how-to-open-new-group-folder-tab-intentionally
