### ISSUE TITLE
Tab focus/scrolling issue / interaction with SearchMenu

### ISSUE THREAD

**Issue by zebulon2** [piroor/treestyletab#341]
Hi,

Since version 0.14.2012081101, if I scroll on my tree tab list, and the current/active tab goes out of view, then automatically the tree list "jumps" so that the active tab goes back in the view, making scrolling the tab tree cumbersome. I have to click on a tab that would not disappear from view to be able to scroll up or down. This did not happen with previous version.

Thanks.

UPDATE: see below, this is an interaction with SearchMenu.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
