### ISSUE TITLE
[Bug] Memory issue with TST when some animated themes are installed

### ISSUE THREAD

**Issue by Taron-art** [piroor/treestyletab#3413]
## Abstract
While using the TST, sometimes Firefox eats all available memory in the system and it becomes unusable. The issue usually happens when the Firefox is minimized. Using the Performance Monitor and about:processes I identified that the problem is in the extensions process, disabling extensions one by one showed that closing TST frees the memory. Also, most of the time opening about:memory in Firefox helps (some GC happening?). This happens for me in two synced profiles on different machines. I'm not sure what can I do to help find the root cause, so please advise. Since the issue is not happening all the time, I haven't tried a clean profile for it.

## Steps to reproduce

 1. Start Firefox with a new profile;
 2. Install TST;
 3. Install animated themes. Not all of them are affected, but here are the examples:
    [ANIMATED KITTY CAT](https://addons.mozilla.org/en-US/firefox/addon/a-n-i-m-a-t-e-d-kitty-cat/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser)
    [Dark space - The best dynamic theme](https://addons.mozilla.org/en-US/firefox/addon/nicothin-space/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser)
 4. Open about:processes and find the PID of the Extension process; //process1
 5. Open any tab;
 6. Open Task Manager -> Details;
 7. Add a Working Set column;
 8. Minimize Firefox and do something else and wait.
 9. Find the process1 in the Task Manager and observe.

## Expected result
The Working Set remains the same;

## Actual result
The Working Set is increasing 5\10 MB per second;

## Environment

 * Platform (OS): Windows 11
 * Version of Firefox: 120 (happened before this version too).
 * Version (or revision) of Tree Style Tab: 3.9.19 (happened before this version too).

**Comment by piroor** [comment]
Could you collect memory measurement with `about:memory` ? Clicking the "Measure and Save..." button will download a json.gz file containing detailed information helping to investigate what happens when you see largely eaten RAM. Please note that it contains very sensitive data like URL of opened tabs, so I recommend you to send it via email (piro.outsider.reflex@gmail.com) instead of posting it to this issue tracker.

**Comment by Taron-art** [comment]
Thanks for the answer, I will try. But most interactions with the browser tabs "frees" the memory. I will try to work around this.

**Comment by Taron-art** [comment]
@piroor, I've send you an email with the memory measurement. The interesting part of the problem that I've discovered, is that even if I hover a mouse cursor over the TST, the memory gets cleaned. So I used a separate Firefox window that was just waiting for a problem to collect the data.
Edit: attached the screenshot.
![зображення](https://github.com/piroor/treestyletab/assets/12997554/2323aa73-94cd-4ad0-8743-6fc013cb37db)

**Comment by Taron-art** [comment]
@piroor I've reproduced the problem on the clean environment and updated the initial post alongside the header. Please let me know if you need any more help.

**Comment by piroor** [comment]
Sorry to my silence. I've seen the dump you sent me.

The dump says that your Firefox uses RAM as:

* 325MB for the main process
* 242MB for the extensions process
* 352MB + 302MB for youtube.com
* 102MB for reddit.com
* 306MB for GPU
* And some other processes using RAM fewer than 60MB for each.

Details of the extensions process at this time are:

* TST uses 19.17MB and more
  * 11MB + 3.27MB for sidebars
  * 4.26MB for the background part
* a session manager addon
* a popup blocker uses 18.07MB
* a dictionary addon uses 17.92MB
* A N I M A T E D KITTY CAT uses 27.49MB and more
* And more other addons

Before I seen this dump I thought that there are some clear bottlenecks like memory eaters with TST's internal URLs. But actually I didn't see any such a stupid memory eater...

Next I'll try the theme with animation.
https://addons.mozilla.org/firefox/addon/a-n-i-m-a-t-e-d-kitty-cat/

**Comment by piroor** [comment]
When the theme is active, TST applies the background image (with animation) to the sidebar panel (yes, you cannot see any animation, but it the image is actually aligned to top-left and the animated cat at top-right is placed out of the viewport). The background image is scaled to cover the sidebar panel, so such a rendering may increase RAM usage.

So I've tried to deactivate the background image with a user style (TST options => Advanced):

```css
:root {
  --browser-bg-images: none !important;
  --theme-images-theme_frame: none !important;
}
```

It looks to reduce the RAM usage for me. Could you try it? @Taron-art

**Comment by Taron-art** [comment]
@piroor,
Yes, this style change fixes the problem for me. Just a small note, I've updated the bug with exact steps to reproduce the problem with animated themes (want to make sure you noticed that).

**Comment by piroor** [comment]
Thanks! I've confirmed that the number of the working set column gets increased immediately after I minimize the window and the increasing is stopped after I restore the window. And the user style I posted at https://github.com/piroor/treestyletab/issues/3413#issuecomment-1895364691 prevents the increasing of the working set size. Hmm....

**Comment by piroor** [comment]
On my environment, a minimized window is actually resized to 160x20 and placed at (-32000, -32000).
I've tried resizing and repositioning separately, and finally I've figured out what is the trigger: positioning to out of screen. I've tried `window.moveTo(10000, 10000)` also and it successfully triggers the increasing RAM problem.

**Comment by piroor** [comment]
With the commit cfbde1a I've introduced a mechanism to apply the workaround I commented, when a browser window is minimized. The mechanism is based on a timer so CPU usage will be increased a little, but I think the RAM usage is more important. Thanks again!

**Comment by piroor** [comment]
I've filed: [1875100 - RAM usage grows too much on minimized browser window with sidebar panel containing APNG background](https://bugzilla.mozilla.org/show_bug.cgi?id=1875100)

**Comment by Taron-art** [comment]
Thank you! Looking forward to a release with the fix.

**Comment by piroor** [comment]
The bug 1875100 is now fixed and landed at Firefox 124!
