### ISSUE TITLE
Also an issue about big memory usage with TST (such as #3413), but mostly by user fault.

### ISSUE THREAD

**Issue by fabiorzfreitas** [piroor/treestyletab#3415]
## Abstract

First of all, this issue is entirely my own fault. I have over 300 tabs (organized in collapsed folders) and that's why my Firefox eats way more memory than I can handle. I've already bookmarked and closed lots of these groups, but now my bookmarks are now a whole other mess I have to clean beforehand.

That said, I tried to use `about:memory` to try to find something else I could chop. My addons' usage sometimes go up to 2GB. TST alone can get close to 700MB.

There's absolutely no way I'll stop using TST, and my other extensions are all small stuff adding up. I was really hoping that Auto Tab Discard + collapsing trees would be good enough, but it's not, so I need to find ways to reduce usage:

1. Is ATD + TST a good combo, or is there a better one?
2. Are there any settings on TST (or any other helper addon you'd suggest) I could tweak to get better results?
3. Are there any Firefox (i.e. `about:config`) settings I can try changing? I'm perfectly willing to "discard tabs harder" and have a bigger reload time by storing less info per tab if it improves performance!

---

PS: I know I'm stepping a fair amount out of TST's scope, but in my scenario, all of this falls back to TST, I'm not interested in anything that won't work alongside it. I can't even stand its absence when I need to use Google Chrome for something quick!

Thank you :)

## Environment

 * Platform (OS): Windows 11 23H2 build 22631.2715
 * Version of Firefox: Firefox Developer 121.0b2 x64. Update channel: aurora
 * Version (or revision) of Tree Style Tab: 3.9.19
 
Also relevant:

* Auto Tab Discard 0.6.7
* Bookmark Tree for Tree Style Tab 4.3
* Multiple Tab Handler 3.1.11
* Tab Session Manager 6.12.2

**Comment by irvinm** [comment]
> ## Abstract
> 
> First of all, this issue is entirely my own fault. I have over 300 tabs (organized in collapsed folders) and that's why my Firefox eats way more memory than I can handle. I've already bookmarked and closed lots of these groups, but now my bookmarks are now a whole other mess I have to clean beforehand.
> 

While running 300 tabs might not be the normal for all of Firefox, many people who use TST have "hundreds" (or more) of tabs.  I run TST with 600-800 usually, but as you already know you have to discard tabs to keep things under control.

> That said, I tried to use `about:memory` to try to find something else I could chop. My addons' usage sometimes go up to 2GB. TST alone can get close to 700MB.
> 

This does seem a little high.  I just checked my addons and the total was 800MB with TST only taking up about 100MB.  (And I have a lot of addons personally)

>     1. Is ATD + TST a good combo, or is there a better one?
> 

I have always found this to be a good combination.  I don't think you "need" to change anything here.

>     2. Are there any settings on TST (or any other helper addon you'd suggest) I could tweak to get better results?
> 

The only thing I might suggest is turning off the tab cache.  That might reduce your memory usage, but not sure ... I haven't had that enabled for a long time.  (I am sure @piroor can comment better on suggestions and next steps, I think he just missed this one and my comment will bring it back to the top)

![image](https://github.com/piroor/treestyletab/assets/979729/900dea64-49f5-4a6f-b3a7-c950120cc5e5)

**Comment by MurzNN** [comment]
I faced a similar high memory usage problem with the Tree Style Tab extension (with all TST-related extension turned off), seems the HTML code for tabs starts growing in time, here are some `about:memory` reports:
First:
![image](https://github.com/piroor/treestyletab/assets/336662/b31e4140-e253-4d25-b9a8-30662329c84a)
And after a couple of minutes (with no new tabs created):
![image](https://github.com/piroor/treestyletab/assets/336662/78f782a2-ee85-4fcb-a02a-fb1351f356ae)
And after ~20 minutes with around 5 new tabs created:
![image](https://github.com/piroor/treestyletab/assets/336662/96eae81a-1ad0-4954-b3b4-80fdcbec8acc)

**Comment by MurzNN** [comment]
Seems related to the "Optimize tree restoration with cache" feature, cuz if I disable it - the memory usage becomes pretty normal:
![image](https://github.com/piroor/treestyletab/assets/336662/74061941-3424-4d2f-9efe-acc998b04c08)
And after enabling it back - 3+ gigabytes again:
![image](https://github.com/piroor/treestyletab/assets/336662/42430f69-fb24-4dc7-ac17-243e69272e1e)

**Comment by piroor** [comment]
@MurzNN Very large strings like `<ul ...>` in your screenshot indicates that your case is same to #3434.

**Comment by Secret-Code** [comment]
I had an issue that seemed identical to this, with version 3.9.20. Reverted to 3.9.19, which was stable. Now updated to 3.9.22, and so far I am not experiencing it. 

Firefox 122.0 on Kubuntu Linux 20.04.6

I have "Optimize tree restoration with cache" checked and "Persist tree cache" is checked
