### ISSUE TITLE
[Bug] TST breaks subpixel aa (cleartype) in the url and bookmark bars 

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#3416]
## Abstract

Installing and activating the TST sidebar breaks subpixel aa (cleartype) in the url and bookmark bars.

If this turns out to be a Fx bug, please report it, you're in a better position to explain what triggers it.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. show bookmark bar (add a folder to it)
 3. open any url (https://www.mozilla.org/en-US/privacy/firefox/)
 4. observe subpixel aa (cleartype) in the url and bookmark bars
 5. install TST 3.9.19
 6. no subpixel aa in the url and bookmark bars

## Expected result

view the images full size to better see the aa

before TST:
![image](https://github.com/piroor/treestyletab/assets/895588/6e3fee62-a29a-41d8-8b0a-b1ba0044549b)

## Actual result
![image](https://github.com/piroor/treestyletab/assets/895588/4bd9659e-1176-4013-9482-b1e7a7424ca7)

## Environment

 * Platform (OS): win10 22h2 x64
 * Version of Firefox: 120.0.0 x64
 * Version (or revision) of Tree Style Tab: 3.9.19

**Comment by piroor** [comment]
This looks to be not a TST specific issue. I've tried another sidebar addon "Sidebery" and this problem happens when it is installed.

**Comment by piroor** [comment]
I've filed: [1874903 - ClearType is partially disabled when any sidebar panel provided by addons is shown](https://bugzilla.mozilla.org/show_bug.cgi?id=1874903)

**Comment by ValdikSS** [comment]
More general bug is https://bugzilla.mozilla.org/show_bug.cgi?id=1724057

**Comment by irvinm** [comment]
@piroor seeing this is not TST related, I think we should close it.  Interested parties can follow the filed bugs.

**Comment by piroor** [comment]
Thanks. I close this because there is nothing left to do in TST side.
