### ISSUE TITLE
[Enhancement] Option to group tabs based on its domain

### ISSUE THREAD

**Issue by Zeioth** [piroor/treestyletab#3418]
## Description
It would be great to have a option to group tabs based on its root domain (while still allowing manual re-ordering).

Alternatively to the current default behavior of ordering them based on what page opened the current tab.

## Extra comments
That would allow me for example, closing all my reddit pages at the same time. Or all my youtube pages. Or all my github pages. Without having to manually re-ordering them first, necessarily.

Sounds like a big change so IDK if this would be actually possible.

**Comment by Zeioth** [comment]
ok, it seems someone is currently working on this: https://github.com/stanah/tst-group-tabs-by-domain

**Comment by piroor** [comment]
The functionality is out of the project scope. Please see also:
https://github.com/piroor/treestyletab#user-content-feature-requests-high-power-management-of-tree-like-sorting-child-tabs-auto-modification-of-tree-renaming-tabs-and-so-on
