### ISSUE TITLE
[Enhancement] Better handling of new tabs with regards to containers

### ISSUE THREAD

**Issue by sevmonster** [piroor/treestyletab#3422]
## Abstract

In TST, opening a tab is straightforward and the provided options are useful. But for ctrl-clicking or middle-clicking, functionality is less defined, and in some cases unwanted—especially when it comes to containers.

Specifically: TST will always use the container inheritance selected in the new tab section, unless one of the dropdown options overrides it to use the same container. However, there is no way to *not* inherit containers, and the capability to inherit container is limited to only specific situations.

For example, the ctrl-click new tab button dropdown has an option for "next sibling, same container" but no option for "child, same container" which is something I want. 

It would be best to copy the new tab settings for each individual key combination, instead of adding partially-complete dropdown options.

## Example one

1. Enable container inheritance on new tab
2. Set middle click to open independent tab
3. Opening new tab with middle click will still inherit container, and there is no option to override this.

## Example two

1. Enable container inheritance on new tab
2. Enable long-press to open container selection menu
3. Ctrl-long click the new tab button and select a container (while still holding ctrl)
4. The tab will still be opened with the inherited container

## My solution

1. Leave "New Blank Tabs" section as it is.
2. Add a separate "Container" dropdown under the middle click dropdown
    * Currently, the only way to change container inheritance when middle clicking is by making it behave the same as a ctrl-click and using the "next sibling, same container" option for ctrl-click.
3. Add a separate "Container" dropdown under the ctrl-click option
4. Remove the "next sibling, same container" option from the ctrl-click dropdown

## Environment

 * Platform (OS): Windows, Linux
 * Version of Firefox: LibreWolf 120.0.1-1
 * Version (or revision) of Tree Style Tab: 3.9.19

**Comment by piroor** [comment]
> ## Example one
> 
>     1. Enable container inheritance on new tab
> 
>     2. Set middle click to open independent tab
> 
>     3. Opening new tab with middle click will still inherit container, and there is no option to override this.

I could not reproduce this with:

* Nightly 123.0a1 on Windows 11
* TST Options
  * New Tabs not from Existing Tabs
    * Basic control for New Blank Tabs
      * Container: Inherit from the parent tab on the tree (not "Inherit from the current tab")
    * Special actions on the "New Tab" button
      * For middle click, open new blank tab as: an independent tab

With this configuration, middle-click on the "New Tab" button with active "Personal" container tab opens a new blank tab with the "default" container for me.


> ## Example two
> 
>     1. Enable container inheritance on new tab
> 
>     2. Enable long-press to open container selection menu
> 
>     3. Ctrl-long click the new tab button and select a container (while still holding ctrl)
> 
>     4. The tab will still be opened with the inherited container

I could not reproduce this also. Whether "Inherit from the parent tab on the tree" or "Inherit from the current tab" is chosen at TST Options => New Tabs not from Existing Tabs => Basic control for New Blank Tabs => Container, the operation opens a new blank tab with the chosen container on my environment.

Any other condition? Or is this Linux specific?

**Comment by sevmonster** [comment]
On first look I can also not reproduce this on Windows. It seems that perhaps what I was seeing under Linux was tabs inheriting based on the current tab and not the location of the newly opened tab, regardless of other settings. It works more as I would expect it to work under Windows. I will try again later today on Linux to see if I can still reproduce there.

**Comment by sevmonster** [comment]
I can no longer reproduce this on Linux either. Guess it was a glitch in the Matrix.
