### ISSUE TITLE
[Enhancement] Enable Share menu for right-clicking on a tab in TST Sidebar (macOS)

### ISSUE THREAD

**Issue by ideologysec** [piroor/treestyletab#3423]
## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Right click on the standard tab bar at the top of Firefox's window
 4. Observe "Share" option in right-click menu that connects to macOS system services (AirDrop, Messages, etc)
 5. Right click on tab in TST sidebar
 6. Observe missing "Share" item
 7. edit userChrome.css to remove top tab bar and maximize vertical real estate
 9. be sad that you can't airdrop or iMessage a tab to someone except by using the "File -> Share" menu bar item in Firefox

<img width="382" alt="2023-12-22-20 41 27" src="https://github.com/piroor/treestyletab/assets/790061/d8feb325-e3c8-4c96-a9c8-9c80d110b5a7">
<img width="306" alt="2023-12-22-20 41 04" src="https://github.com/piroor/treestyletab/assets/790061/e80f8a3f-6b75-4378-8fda-8d7c5781ac85">

## Expected result
Context menu on a tab in TST has "Share" option

## Actual (present) result
"Share" item in context/right-click menu does not exist.

I realize this is a "quality of life" issue since I can work around it with the File menu, but it's much faster to use a right-click on a single tab to share, especially with a mouse.

## Environment

 * Platform (OS): macOS 14.2.1 Sonoma
 * Version of Firefox: 121.0 arm64
 * Version (or revision) of Tree Style Tab: 3.9.19

**Comment by piroor** [comment]
Sadly it is impossible because Firefox does not expose features to call the native "Share" command via WebExtensions API.

**Comment by ideologysec** [comment]
Is this a bug I could file with Upstream? where would be the best place to do that?

**Comment by piroor** [comment]
There is an already filed bug: [1706675 - Add an API to call the "Share" command of Firefox itself (on Windows 10 and macOS)](https://bugzilla.mozilla.org/show_bug.cgi?id=1706675) and sadly it is resolved as "WONTFIX".

**Comment by irvinm** [comment]
@piroor we should close this item as this won't be resolved upstream and there is nothing more you can do on this end.

**Comment by piroor** [comment]
Thanks. I hope to keep this issues tracker as the place to track unresolved problems possible resolved, so I close this for now.

FYI: The extended version TST built-in to Waterfox has the "Share" context menu command based on Experiments API which is restricted on the release version of Firefox.
https://www.waterfox.net/
