### ISSUE TITLE
[Bug] TST addon causes behaviour reported in Mozilla bug 1485683

### ISSUE THREAD

**Issue by amthog** [piroor/treestyletab#3428]
## Abstract
Mozilla bug 1485683 reports incorrect behaviour when opening new tabs and failure to open new tabs next to the current tab despite config settings that mean this should happen.
https://bugzilla.mozilla.org/show_bug.cgi?id=1485683

In particular when opening a link in the current page in a new tab via middle click or right click Open Link in New tab,
In these cases the new link does not open in a tab after the current tab, but instead opens at the end of the set of tabs that have been recently opened from the current tab where the context used to decide "recently" is unclear and confusing.  Basically opening several tabs 1, 2 ,3 from current tab end up in order 1,2,3 next to current tab rather than expected order 3, 2, 1 i.e. the most recently opened tab e.g. 3, does not open _next_ to current tab, but instead opens at the end of the set of tabs opened from the current tab. Please see Mozilla bug report for full details including how this can be very confusing/disruptive trying to "spot" the newly opened tab. 

Several contributors to the thread identified the Tree Style Tab extension as the cause of this behavior in their case:
https://bugzilla.mozilla.org/show_bug.cgi?id=1485683#:~:text=2%20years%20ago-,For%20me%20it%20turned%20out%20that%20a%20browser%20extension%20was%20causing,the%20extension%20Firefox%20tab%20insertion%20behaved%20perfectly%20again%20respecting%20about%3Aconfig.,-I%20do%20apologise

This proved to be the case for me as well. 

It is clear from the Mozilla bug report that Firefox itself has had bugs in this area for over 4 years. So I suspect this is probably the case of TST getting unfortunately "entangled" in this and needing to avoid or compensate for certain Firefox behaviours/issues. It seems likely that there is more than one root cause for all the behaviours being reported against bug 1485683.  But all that is just speculation on my part. I have chosen to report here as it is clear that for myself and several other contributors in the bug 1485683 that TST is directly correlated to the unexpected behaviour in our cases. 

It is also clear that there are several combinations of config settings that could be relevant. I have only tested under the specific combination documented below and confirmed that addition/removal of TST is directly correlated to the unexpected behaviour. 
I have not had time to test under all possible combinations (sorry) 

## Steps to reproduce

 1. Start Firefox.
 2. Ensure TST not installed or is disabled.
 3. Confirm tab insert config settings are at their _default_ values:
 
![image](https://github.com/piroor/treestyletab/assets/65935719/84078051-f9b4-4266-99f6-a819b29d1dd5)

 4. Browse to a page with several links 
 5. Confirm expected tab opening behaviour. Middle click or right click Open in New tab several links (1, 2, 3) on current page
 6. Tabs should open next to current tab in order 3, 2, 1 i.e. each tab opening immediately next to the current tab.
 7. Install or enable TST.
 8.  Repeat link opening steps above.
 9. Newly opened links end up next to current tab in order 1, 2, 3 i.e. each tab is opened at the end of the recently opened tabs rather than immediately next to the current tab. Visually you can see the new tab open next to the current tab and remain there briefly before _moving_ to a position at the end of recently opened.   
 11. Disable or uninstall TST.
 12. Repeat link opening steps and confirm expected behaviour has returned.
 

## Expected result

Newly opened tabs via middle click or right click Open Link in New Tab should end up next to current tab in 3, 2, 1 order

## Actual result

Newly opened tabs via middle click or right click Open Link in New Tab should end up next to current tab in 1, 2, 3 order

## Environment

 * Platform (OS): Windows
 * Version of Firefox: 121.0 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.9.19

**Comment by piroor** [comment]
I couldn't reproduce this:

> ## Steps to reproduce
> 
>     1. Start Firefox.
> 
>     2. Ensure TST not installed or is disabled.
> 
>     3. Confirm tab insert config settings are at their _default_ values:
> 
> 
> ![image](https://private-user-images.githubusercontent.com/65935719/294728250-84078051-f9b4-4266-99f6-a819b29d1dd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODg1OTUsIm5iZiI6MTcwNTM4ODI5NSwicGF0aCI6Ii82NTkzNTcxOS8yOTQ3MjgyNTAtODQwNzgwNTEtZjliNC00MjY2LTk5ZjYtYTgxOWIyOWQxZGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA2NTgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZTVkYjBhNmUyMzYzMDVmOWIyZmU1M2M1OTVjMzdhMDVjYzA2YTBlZDdlNDY0MTI3YjIzZTZhY2JhY2VjN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Du52qWLrdNDGk4P4jkiGz5uFT6SfAY07pN90gMCqfNQ)
> 
>     4. Browse to a page with several links
> 
>     5. Confirm expected tab opening behaviour. Middle click or right click Open in New tab several links (1, 2, 3) on current page
> 
>     6. Tabs should open next to current tab in order 3, 2, 1 i.e. each tab opening immediately next to the current tab.

You mean tabs should be opened as following?:

* Current Tab
* 3rd tab opened from a link with the context menu command "Open Link in New Tab"
* 2nd tab opened from a link with the context menu command "Open Link in New Tab"
* 1st tab opened from a link with the context menu command "Open Link in New Tab"

On my environment, Nightly 123.0ai with clean profile (without TST of course) puts opened tabs with the order:

* Current Tab
* 1st tab opened from a link with the context menu command "Open Link in New Tab"
* 2nd tab opened from a link with the context menu command "Open Link in New Tab"
* 3rd tab opened from a link with the context menu command "Open Link in New Tab"

To get results like yours, I had to set `browser.tabs.loadInBackground`=`false` also. Otherwise I had to switch to tabs opened from the current tab on each step, to clear internal "related current tabs" information. Is this a missing steps to reproduce you reported?

**Comment by piroor** [comment]
If you need to put new tabs from links to the top of existing children always, you should configure TST as:

* TST 3.9.19
  * TST Options => Unlock Expert Options => checked
  * TST Options => Tabs opened from Existing Tabs => When a tab is opened from existing tab, open it as => a child of the parent tab (Recommended)
  * TST Options => Tree Behavior => Insertion position of new child tabs => The top of the tree (next to the parent)
* TST 3.9.20 or later
  * TST Options => Unlock Expert Options => checked
  * TST Options => Tabs opened from Existing Tabs => When a tab is opened from existing tab, open it as => First Child of the parent tab
