### ISSUE TITLE
[Bug] Proton theme does not fully respect light theme when using System theme - auto

### ISSUE THREAD

**Issue by sith-on-mars** [piroor/treestyletab#3429]
## Abstract

I set System theme - auto in Firefox themes setting and set the system to light. The TST theme I use it's Proton. However, other than the selected tab, TST still uses dark theme when switching to light theme in the System.

![image](https://github.com/piroor/treestyletab/assets/37974764/97bb70d0-ef34-4382-909a-fe2dac6d288a)

It seems that other TST themes don't have the same problem.

![image](https://github.com/piroor/treestyletab/assets/37974764/03564fe6-7d2b-4700-a076-e83beb6dd603)

![image](https://github.com/piroor/treestyletab/assets/37974764/f5f9df88-b800-43b2-a386-17411c20d281)

Using dark theme in the system works fine. TST with the Proton theme respects the dark theme.

![image](https://github.com/piroor/treestyletab/assets/37974764/814d5320-9ed0-47ed-a1a3-935f4e629e4a)

## Environment

 * Platform (OS): Fedora Silverblue 39 Gnome
 * Version of Firefox: 121.0
 * Version (or revision) of Tree Style Tab: 3.9.19

**Comment by piroor** [comment]
Did you mean that the blank area of the sidebar should be rendered with the color same to the titlebar in this screenshot?:
![image](https://github.com/piroor/treestyletab/assets/70062/3411dbb0-2835-42da-85b5-2ed99c269bde)
Actually the color of the titlebar is not exposed to addons: it is defined as "transparent" in Firefox and the actual color is painted by GNOME itself. TST cannot refer the color not defined in system color names, thus you need to define similar colors manually. For example:

```css
:root {
  --browser-fg: -moz-dialogtext;
}
#background {
  background-color: #dfdcd9;
}
```

![image](https://github.com/piroor/treestyletab/assets/70062/d93d0004-d1b6-4666-8147-da590f4415a2)

**Comment by sith-on-mars** [comment]
Thanks for the reply. Yes that's what I meant.

It seems this bug only happened exclusively on the Proton theme, not on others. For example, the Photon theme looks fine in the system light mode:

![image](https://github.com/piroor/treestyletab/assets/37974764/ec311234-4db9-4a51-8833-480e5b1d9f94)
