### ISSUE TITLE
[Bug] (Tabs opened from existing tabs get moved to the end of a tree regardless of chosen option.)

### ISSUE THREAD

**Issue by Bluetinity** [piroor/treestyletab#3431]
1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a tab, let's call it tab 1
 4. Open a new tab (tab 2) from the first tab (tab 1)
 5. Visit (tab 2) and go back to first tab (tab 1)
 6. Open another tab (tab 3) from the first tab (tab 1)
 7. (tab 3) opens next to (tab 1), but then gets moved to the end of the tree
 8. Changing the "Tabs opened from Existing Tabs" preference in TST options doesn't effect this behavior in any way

## Expected result:
Opened tabs to have normal behavior and respect chosen options

## Actual result:
Tabs opened from existing tabs get moved to the end of a tree regardless of chosen option

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 121.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.9.19

**Comment by piroor** [comment]
The option you saw is for tabs *opened from pinned tabs*. You should see another option for your purpose: TST options => "Tree Behavior" => "Insertion position of new child tabs". It affects to general cases including "tabs are opened from a non-pinned tabs" and "tabs are drag-and-dropped onto a tab".

BTW I agree the categorization is user-unfriendly. Hmm, is it the time to add one more option to the "tabs opened from Existing Tabs" section...

**Comment by piroor** [comment]
Ah, I missed an existing option. With activated "expert options", you'll see an option "Tabs opened from Existing Tabs" => "When a tab is opened from existing tab, open it as". It is "a child of the parent tab" by default and you can choose "a child of the parent tab, next to the recently opened child" to change the insertion position of new child tabs.

However it does not allow you to insert new child tab at the top of children - you need to configure "Tree Behavior" => "Insertion position of new child tabs". In other words, currently there are two separate options but they are partially overlapped.

**Comment by piroor** [comment]
I've restructure options with the commit e08d8df.
Now TST has choices "open new tab as first or last child" explicitly for each "open tab as..." options. Your case is now covered with an expert option "Tabs opened from Existing Tabs" => "When a tab is opened from existing tab, open it as" and you don't need to configure more other options.

**Comment by piroor** [comment]
I've seen some unexpected results with edge cases: tabs from a pinned parent are unexpectedly attached as first child of the alias group-tab tree. Configs:

* New tabs from existing tab = opened as last child
* New tabs from pinned parent = near last related tab or near the parent

It looks that I have to do more.

**Comment by Bluetinity** [comment]
Well thanks for the info, it fixes the problem I had. I guess i just didn't understand what all the options did. You can close the issue now or later if you want to address those edge cases first.
