### ISSUE TITLE
[Enhancement] Copy links from multiple tabs

### ISSUE THREAD

**Issue by sherwood333** [piroor/treestyletab#3436]
## Abstract
Often I am in the situation where I open a lot of tabs to research, and wish to save them in a spreadsheet. Or archive them in a text file for later. 
My preffered solution would be an option to copy the selected URLs to the clipboard, via a right click option on the tabs. 

## Steps to see the situation
 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open 2-5 new websites as seperate tabs
 4. Select tabs (using shift or ctrl+click)
 5. Right click on one of the selected tabs

## Expected result
Copy URL's to clipboard option is available to choose

## Actual (present) result
No such option exists

## Environment
 * Platform (OS): N/A. Tested on Win10
 * Version of Firefox: 121.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.9.20

**Comment by piroor** [comment]
Please try [Copy Selected Tabs to Clipboard](https://addons.mozilla.org/firefox/addon/copy-selected-tabs-to-clipboar/). It should work together with TST.

Sorry I have no plan to add the feature as a built-in of TST, to concentrate TST project to its scope.

**Comment by sherwood333** [comment]
Thank you so much for the link, this was exactly what I was looking for!
