### ISSUE TITLE
[Enhancement] Auto-Sort Tabs within a tree by Name, URL, or other criteria

### ISSUE THREAD

**Issue by Isuress** [piroor/treestyletab#3437]
## Introduction
Hello Piroor; I have used TreeStyleTab for FireFox for almost 7+ years now?
I love the addon; it is immensely useful. I have a tab addiction and have way too many tabs.
Your addon allows me to actually see the title of these tabs properly without having the description of the tab cut off.
One issue I have is that I will have LOT of tabs within a tree, and there might be duplicates that I am unaware of.
Being able to sort tabs would help with eliminating unneeded tabs; also with general tab cleanup.

There are other addons that do this within FireFox but I doubt their compatibility with TreeStyleTabs.
I would also prefer to just use your addon for everything.

## Suggestion
Right-click functionality on a ROOT of a tree to "auto-sort" all tabs within a tree by URL Domain, URL Link, Tab Name, or other criteria _(alphabetical, numerical, etc)_.

## Steps for functionality - Type 1

 1. Have a Tree of 3+ tabs.
 2. Right-click ROOT of the tree.
 3. Hover over "sort by" context menu.
 4. Choose appropriate sorting application.
 5. Tabs within the tree are the sorted by selected function.
 6. ???
 7. Profit

## Steps for functionality - Type 2

 1. Shift+Left-Click a range of tabs _(3, 5, 10, etc)_.
 2. Right-click any tab.
 3. Hover over "sort by" context menu.
 4. Choose appropriate sorting application.
 5. Tabs within the tree are the sorted by selected function.
 6. ???
 7. Profit

## Alt
Ctrl+Left-Clicked tabs, or any selected tabs.

## Expected result
All tabs within the Tree are sorted.

**Comment by piroor** [comment]
There is a FAQ topic for this.
https://github.com/piroor/treestyletab/blob/trunk/README.md#user-content-feature-requests-high-power-management-of-tree-like-sorting-child-tabs-auto-modification-of-tree-renaming-tabs-and-so-on
In short, the feature is beyond the project scope. I'll make effort to make TST compatible to any other addon providing the sorting feature, but I won't add the feature as a built-in.
