### ISSUE TITLE
Extension version 3.9.21 won't start in Firefox 122.0

### ISSUE THREAD

**Issue by bsimpson** [piroor/treestyletab#3441]
## Steps to reproduce

 0. Download the Mozilla Firefox Debian package. This should be 122.0 (64-bit)
 1. Start Firefox with clean profile (`firefox -P` and created new profile).
 2. Install TST extension version 3.9.21

## Expected result

The sidebar opens and tree style tab extension shows the tabs

## Actual result

It shows the sidebar with a loading indicator and no further progress. Tree style tab never initializes

![image](https://github.com/piroor/treestyletab/assets/3703/ef6ca0b4-f6a0-4802-a3a0-54e5b5a1bb0d)

## Environment

 * Platform (OS): 
 * Version of Firefox: 1.22
 * Version (or revision) of Tree Style Tab: 3.9.21

**Comment by hpvd** [comment]
Possibly duplicates: https://github.com/piroor/treestyletab/issues/3440

**Comment by bsimpson** [comment]
Closing as duplicate of https://github.com/piroor/treestyletab/issues/3440
