### ISSUE TITLE
[Bug] Dragging multiple tabs from one window to another breaks order

### ISSUE THREAD

**Issue by Nitero** [piroor/treestyletab#3454]
## Abstract

With the default settings dragging multiple tabs from one window to another one messes up the order of tabs in the tree style tab view and also sends you to wrong tabs when selecting some of them. Reordering one tab by drag and drop in the tree style seems to fix it.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open two tabs in one window (named 1/2)
 4. Open two tabs in another window (named 3/4)
 5. Select both tabs in the second window (3/4) and drag them to the first window (1/2), but insert them at the start
 6. The actual tab order is 3/4/1/2 but the tree style shows 3/1/4/2
 7. Selecting some of the tabs sends you to wrong ones

## Expected result
Tabs should be ordered like they were in the other window and clicking on them should send you to the right one

![image](https://github.com/piroor/treestyletab/assets/11302557/04b63773-a781-4cbe-8a92-059da195a1d7)

## Actual result
Tabs are ordered differently than in the other window and clicking on them sends you to different ones (not sure whats the rule here)

![image](https://github.com/piroor/treestyletab/assets/11302557/107e0260-80b8-4956-81e5-2ed87e13dfbf)

## Environment

 * Platform (OS):  Windows 11 Pro
 * Version of Firefox: 122.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.9.22

**Comment by piroor** [comment]
I've tried this with TST 3.9.22 but couldn't reproduced. Is there any required step to reproduce? I've tried with:

1. Install TST 3.9.22.
2. Open a browser window and prepare two tabs "1" and "2".
3. Open another browser window and prepare two tabs "3" and "4".
4. Activate the tab "4".
5. Ctrl-click on the tab "3" in the sidebar. Then both "3" and "4" are become mulltiselected.
6. Drag the tab "3" from the sidebar and drop it at the position before the tab "1" in the sidebar.
7. I've got tabs "3", "4", "1" and "2" in both sidebar and the horizontal tab bar.
