### ISSUE TITLE
[Enhancement] Allow easy copy/pasting of (complex) tab trees

### ISSUE THREAD

**Issue by Bjeaurn** [piroor/treestyletab#3455]
## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Browse as usual, do some research perhaps.
 4. Select the tabs that may be interesting to persist in some other database/text form.
 5. Copy, try to paste. The result is only the primary tab's URL is pasted.

## Expected result
It would be nice if you could paste a list of URLs in a similar fashion, or perhaps a combination of "Title - URL", maybe even have modes to switch. Easiest result would be to not just copy/paste the primary selected tab's URL, but all of the selected tabs.

## Actual (present) result
Only primary selected tab's URL is copy/pasted.

## Environment

 * Platform (OS): MacOS
 * Version of Firefox: 122.0 (64bit)
 * Version (or revision) of Tree Style Tab: 3.9.22

**Comment by irvinm** [comment]
This might be what you want:  https://addons.mozilla.org/en-US/firefox/addon/copy-selected-tabs-to-clipboar/

**Comment by piroor** [comment]
The feature looks to be covered by the addon Copy Selected Tabs to Clipboard as irvinm commented. 

Basically I won't add new built-in features to TST if it is covered by other addons, to keep the project scope, sorry.

**Comment by Bjeaurn** [comment]
Fair enough and totally understandable, thanks for taking a look and for the great tip!
