### ISSUE TITLE
[Bug] Default for Tabs opened from Existent tabs keeps kicking out to First child instead of (no control)? (Something to do with pinned tabs maybe?)

### ISSUE THREAD

**Issue by ninep9up** [piroor/treestyletab#3457]
This is only last couple of days, I'm on the last Waterfox

**Comment by ninep9up** [comment]
Okay, I've also pinned a tab so to add some time before this, so that might have to do something with this

**Comment by ninep9up** [comment]
I also have Auto Tab Discard installed, though if it has to do something with this it's only on behalf of these two, because I have it installed for a long time. It just pushes your tabs out of memory with keeping a tab to load

**Comment by irvinm** [comment]
TST hasn't been updated for a little over 2 weeks ... it must be something with your settings\profile.

Can you reproduce this in a clean profile?  You should also fill out the bug template with the configuration and steps to reproduce.

**Comment by piroor** [comment]
@ninep9up Please fill the issue template to describe what is the problem clearly. I still cannot understand what is the exact problem you saw.

```markdown
## Abstract

## Steps to reproduce

<!--
Please investigate complete steps required to reproduce the problem from scratch,
on a clean environment with a new profile. See also:
https://github.com/piroor/treestyletab/wiki/How-to-minimize-conditions-to-reproduce-a-problem
-->

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

<!--
Please describe how to reproduce your problem on my (developer/author/other peoples') environment.
If your issue is related to tree structure, figures or screenshots will help me a lot, like:

```
A
\- B (collapsed)
C
\- D
E (selected)
```
-->

## Expected result


## Actual result


## Environment

 * Platform (OS): 
 * Version of Firefox: <!-- put exact version like "63.0" instead of "latest", because there are multiple  "latest" versions for each "release", "beta" and "nightly" edition. -->
 * Version (or revision) of Tree Style Tab: <!-- put exact version like "2.6.6" instead of "latest", because the "latest" version will change day by day. -->
```
