### ISSUE TITLE
[Bug] No longer grouping, correctly, no indents, 'x' to close is on the left

### ISSUE THREAD

**Issue by meorime** [piroor/treestyletab#3458]
## Environment

 * Windows 11
 * Version of Firefox: Version 122.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.9.22

![image](https://github.com/piroor/treestyletab/assets/160343598/94873164-fb6e-479c-9b18-51042e6b7916)

**Comment by irvinm** [comment]
Did you change this value?

![image](https://github.com/piroor/treestyletab/assets/979729/7930cdcd-ea1c-4492-a8d9-410cba185941)

**Comment by piroor** [comment]
@meorime Please fill the issue template to describe what is the problem clearly. I still cannot understand what is the exact problem you saw.

```markdown
## Abstract

## Steps to reproduce

<!--
Please investigate complete steps required to reproduce the problem from scratch,
on a clean environment with a new profile. See also:
https://github.com/piroor/treestyletab/wiki/How-to-minimize-conditions-to-reproduce-a-problem
-->

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

<!--
Please describe how to reproduce your problem on my (developer/author/other peoples') environment.
If your issue is related to tree structure, figures or screenshots will help me a lot, like:

```
A
\- B (collapsed)
C
\- D
E (selected)
```
-->

## Expected result


## Actual result


## Environment

 * Platform (OS): 
 * Version of Firefox: <!-- put exact version like "63.0" instead of "latest", because there are multiple  "latest" versions for each "release", "beta" and "nightly" edition. -->
 * Version (or revision) of Tree Style Tab: <!-- put exact version like "2.6.6" instead of "latest", because the "latest" version will change day by day. -->
```

**Comment by meorime** [comment]
Apologies, I was out of town and didn't have my laptop. The issue is as you see in my initial screenshot. The theme for the tabs isn't applying. Instead the tabs look like in the image I uploaded in the initial bug report. I didn't change anything in the settings, it just flipped to what you see there. I use the Photon theme by default.

There are no steps to reproduce. It was working, then it wasn't :(

**Comment by meorime** [comment]
Figured out the problem. Options were set to auto-detect right or left column - mine is in the right. Auto and right column options now display as if the tabs are on the left. Now I have it set as if the tabs are on the left and it's formatted correctly for the right side. In other words, it seems as if the two settings have been reversed.

**Comment by piroor** [comment]
>  In other words, it seems as if the two settings have been reversed.

Hmm, it is very odd. The initial screenshot was certainly taken with the option?: TST options => "Appearance" => "Style of contents for the sidebar position" => "Left side"
I cannot reproduce this and I can't imagine why it happens...

If you choose "Auto detect", it may fail to detect and cause such a problem. The auto detection is based on screen coordinates and some more information, and the logic may not work correctly on some environments - multiple screens, high DPI screens, and so on.
