### ISSUE TITLE
[Enhancement] Open all bookmarks as a tree **in containers**

### ISSUE THREAD

**Issue by michaelCTS** [piroor/treestyletab#3462]
## Abstract

Greetings!  

At the moment, when a bookmark tree is opened, all the tabs are not in containers. So, this is a straight-forward feature request to enable opening bookmarks in a selected container.

## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Create a tree of tabs
 4. Save the tree as bookmarks
 5. Right-click on the bookmarked folder

## Expected result

"Open All as a Tree" is available **with** a dropdown list of containers to open in.

## Actual (present) result

"Open All as a Tree" is available

![afbeelding](https://github.com/piroor/treestyletab/assets/132582212/1a75df7a-fd12-45f1-8a95-d8a00a22b158)

## Environment

 * Platform (OS): Debian Bookworm (12)
 * Version of Firefox: 115.7.0esr

**Comment by piroor** [comment]
A helper addon "TST Open Bookmarks as Partial Tree" includes the feature.
https://addons.mozilla.org/firefox/addon/tst-open-bookmarks-as-partial-/

Currently Firefox provides ability to open a bookmark with specified container but does not for a bookmark folder, so I think it looks natural enough that TST does not provide ability to open bookmarks from a folder with container. Sorry for inconvenience but decision like this is required to keep the range of this development project clear.

**Comment by michaelCTS** [comment]
I wasn't aware of the extension! It implements exactly what I'm looking for. Thanks
