### ISSUE TITLE
[Enhancement] option to show full url in tab tooltip instead of page title

### ISSUE THREAD

**Issue by br4nnigan** [piroor/treestyletab#3463]
that would be nice

**Comment by piroor** [comment]
It won't be a built-in option because Firefox does not provide such an option, so I've added a new API for helper addons to override tab tooltip text. I hope you or someone develops a new helper adodn.
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#set-custom-tooltip-text-to-tabs

**Comment by mzso** [comment]
Hi!
Did any addon of the sort materialize?

**Comment by irvinm** [comment]
Maybe check here:  https://github.com/piroor/treestyletab/wiki/Helper-addons-extending-functionality-of-TST

**Comment by mzso** [comment]
[**@irvinm**](https://github.com/irvinm) commented on [Sep 3, 2024, 6:36 PM GMT+2](https://github.com/piroor/treestyletab/issues/3463#issuecomment-2326968915 "2024-09-03T16:36:23Z - Replied by Github Reply Comments"):
> Maybe check here:  https://github.com/piroor/treestyletab/wiki/Helper-addons-extending-functionality-of-TST
> 
> _Originally posted by @irvinm in https://github.com/piroor/treestyletab/issues/3463#issuecomment-2326968915_

I did. Only the drag handle addon mentions tooltip.
