### ISSUE TITLE
[Enhancement] Configurable minimum drag / option to disable for pinned tabs

### ISSUE THREAD

**Issue by dsl101** [piroor/treestyletab#3466]
## Abstract
When rushing, I often find I am accidentally still moving the mouse slightly when clicking to activate a tab. I drag tabs rarely, and the default behaviour of creating a new window for the tab is unintuitive in this situation.

## Steps to see the situation

 1. Move the mouse slowly whilst quickly clicking on a tab
 2. The tab is not dropped back where it was, but opened in a new window

## Expected result
The tab would stay where it was. I would also love the option to prevent dragging of pinned tabs completely.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 123.0 
 * Version (or revision) of Tree Style Tab: 3.9.22

**Comment by irvinm** [comment]
You may want to read this: https://github.com/piroor/treestyletab/discussions/3461

**Comment by dsl101** [comment]
Thank you. I'm happy to move to shift-drag :).

**Comment by dsl101** [comment]
![image](https://github.com/piroor/treestyletab/assets/900542/bde6e650-cdee-44d6-8e8d-364c0e81d6f7)

In fact, this setting still allows regular dragging within the tree, but requires shift for detaching, so best of both worlds.
