### ISSUE TITLE
[Bug] Sidebar doesn't adapt to dark version of theme

### ISSUE THREAD

**Issue by aaronliu0130** [piroor/treestyletab#3468]
## Abstract
I use a theme, Alpenglow (aka. Firefox Radiance), which has a different background image under dark mode using the undocumented object "dark_theme" in its manifest.json. TST still uses the light mode background image under dark mode for its background.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install [Alpenglow](https://addons.mozilla.org/en-US/firefox/addon/firefox-alpenglow) or any theme with a different dark mode background image as specified in the abstract.
 4. Under "Dynamic Themes" of <about:prefs>, click "Force Dark Mode".

## Expected result
The TST sidebar uses the background for dark mode, which, in Alpenglow's case, is purple.

## Actual result
![The sidebar is the light mode's orange-to-pink gradient.](https://github.com/piroor/treestyletab/assets/11874211/1899461d-8fe2-4b19-baa4-4ac8b35cedbc)

## Environment

 * Platform (OS): Win11
 * Version of Firefox: 115.8.0
 * Version (or revision) of Tree Style Tab: 3.9.22

**Comment by aaronliu0130** [comment]
Actually, I don't think any dark mode style is respected except for the color of the selected tab, maybe. TST's tab text doesn't change in dark mode either.

**Comment by irvinm** [comment]
Known Firefox limitation discussed here:  https://github.com/piroor/treestyletab/issues/2915

**Comment by aaronliu0130** [comment]
oh wow

**Comment by aaronliu0130** [comment]
is there some way i could inspect the treestyletab sidebar to know what classes I should select to clone the alpenglow dark theme into it?

**Comment by irvinm** [comment]
Yes ... follow these instructions: https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-inspect-the-sidebar
