### ISSUE TITLE
Treestyle tab causes startup crash after FF 15 update

### ISSUE THREAD

**Issue by bengb** [piroor/treestyletab#347]
Treestyle Tab no longer works now that my browser has updated to version 15.0.  

When I enable the TST add-on, Firefox every time it starts up and sends a report to Mozilla.  The only way to get back into FF, is to start in safe mode and disable the TST add-on.

This is on a Mac running OSX 10.8.1.

Thanks for any help!

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
