### ISSUE TITLE
[Bug] New tab button jittering around on Photon and High Contrast theme after updating to 4.0/4.0.1

### ISSUE THREAD

**Issue by cheatreal321** [piroor/treestyletab#3471]
## Abstract
Immediately after updating to version 4.0/4.0.1 the Photon and High Contrast themes cause the new tab button to have a gap from the lowest tab and jitter around when opening new tabs. The Proton and Sidebar themes do not seem to have this bug.
This seems to be related to the number of tabs, as the button moves away further from the position it's supposed to be in and jitters more strongly the more tabs are open. 

## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install TST.
 3. Select the Photon or High Contrast theme.
 4. Open a lot of tabs.
 5. See (very long) gif:
![12 03 24_3875_firefox](https://github.com/piroor/treestyletab/assets/150494288/4571dded-c9d8-4cc2-81f3-69aba92d0a41)

## Expected result
New tab button stays directly under the last tab without a gap, and does not jitter around.

## Actual result
See gif above. New tab button has an increasing gap under the last tab and jitters around at almost any interaction.

## Environment
 * Platform (OS): Windows 10 IoT Enterprise LTSC
 * Version of Firefox: 123.0.1
 * Version (or revision) of Tree Style Tab: 4.0.1

**Comment by pengupengupengu** [comment]
First time caller here, it might have something to do with `--virtual-scroll-container-size` having the wrong value? It just set it to 0 in the addon settings:

```
* {
  --virtual-scroll-container-size: 0px;
}
```

**Comment by kevinptt0323** [comment]
+1. Attach image instead of looooooong gif instead.
![image](https://github.com/piroor/treestyletab/assets/5292982/dc853b3d-b339-4720-907b-80c0c098843d)

**Comment by piroor** [comment]
Thanks, this should be fixed with recent commits.

**Comment by DimitryAndric** [comment]
I think I see almost the same, however for me there is only a gap that gets bigger all the time, it doesn't really "jitter" around. However, if I close tabs, the gap seems to reset most of the time. I will wait for 4.0.2! :)

**Comment by Qwerty-Space** [comment]
See https://github.com/piroor/treestyletab/issues/3470#issuecomment-1994068629

> If you're still on the stable release, the following fixes the issue, seemingly without other drawbacks:
> 
> ```css
> .virtual-scroll-container {
>     min-height: 0px;
> }
> ```
