### ISSUE TITLE
[Bug] 4.0.1 - Close multiple tabs warning dialog is empty

### ISSUE THREAD

**Issue by Sada-Mio** [piroor/treestyletab#3474]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open multiple tabs
 4. Select multiple tabs from sidebar to close

## Expected result

- Warning dialog popup with list of tabs

## Actual result

- Warning dialog popup is empty
- No close tab or cancel button

## Environment

 * Platform (OS): Win10
 * Version of Firefox: 123.0.1
 * Version (or revision) of Tree Style Tab: 4.0.1

**Comment by noc0lour** [comment]
I can confirm this behaviour on MacOS with Firefox 123.0.1 and Tree Style Tab 4.0.1

**Comment by markocelan** [comment]
Confirming this bug on Fedora Linux with Firefox 123.0.1 and Tree Style Tab 4.0.1

**Comment by piroor** [comment]
Any error message in the error console opened by Ctrl-Shift-J, or the debugger for TST (see also https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-start-debugger-for-tree-style-tab )?

**Comment by NelsLucid** [comment]
I am also experiencing this bug on Ubuntu with Firefox 123.0.1 and Tree Style Tab 4.0.1. These are the errors I see in the debugger when I hit the "x" button on a tab and then see a blank dialog.

```
Uncaught (in promise) Error: Missing host permission for the tab undefined
managed storage is not provided [Configs.js:310:27](moz-extension://955503bc-0931-4434-9d54-130a06a6d978/extlib/Configs.js)
Uncaught TypeError: renderableTabs[firstRenderableIndex] is undefined
    renderVirtualScrollViewport moz-extension://955503bc-0931-4434-9d54-130a06a6d978/sidebar/scroll.js:251
    scrollTo moz-extension://955503bc-0931-4434-9d54-130a06a6d978/sidebar/scroll.js:508
    scrollStep moz-extension://955503bc-0931-4434-9d54-130a06a6d978/sidebar/scroll.js:638
    scrollStep moz-extension://955503bc-0931-4434-9d54-130a06a6d978/sidebar/scroll.js:643
    scrollStep moz-extension://955503bc-0931-4434-9d54-130a06a6d978/sidebar/scroll.js:643
    scrollStep moz-extension://955503bc-0931-4434-9d54-130a06a6d978/sidebar/scroll.js:643
    scrollStep moz-extension://955503bc-0931-4434-9d54-130a06a6d978/sidebar/scroll.js:643
    smoothScrollTo moz-extension://955503bc-0931-4434-9d54-130a06a6d978/sidebar/scroll.js:645
    smoothScrollTo moz-extension://955503bc-0931-4434-9d54-130a06a6d978/sidebar/scroll.js:614
    scrollTo moz-extension://955503bc-0931-4434-9d54-130a06a6d978/sidebar/scroll.js:492
    scrollToTab moz-extension://955503bc-0931-4434-9d54-130a06a6d978/sidebar/scroll.js:772
    async* moz-extension://955503bc-0931-4434-9d54-130a06a6d978/sidebar/sidebar.js:822
    FrameRequestCallback* moz-extension://955503bc-0931-4434-9d54-130a06a6d978/sidebar/sidebar.js:815
    EventListener.handleEvent* moz-extension://955503bc-0931-4434-9d54-130a06a6d978/sidebar/sidebar.js:803
2 [scroll.js:251:5](moz-extension://955503bc-0931-4434-9d54-130a06a6d978/sidebar/scroll.js)
```

**Comment by piroor** [comment]
Could you try again with granted "Access your data for all websites" permission? It may be a workaround.
![image](https://github.com/piroor/treestyletab/assets/70062/6d296165-8f09-4656-817a-60baa6ffeaaf)

Hmm, to avoid this problem, we need to introduce another problem again: Ctrl-Shift-T to restore close tabs will "restores" a blank window corresponding to the dialog.

**Comment by NelsLucid** [comment]
Yes, that seems to work. Thank you for the workaround.

**Comment by piroor** [comment]
I've released 4.0.2 with a fix for this. Please wait until it is published.

**Comment by ocolluphid** [comment]
thanks, this also worked for me! should we revert to old settings when 4.0.2 is released?

**Comment by piroor** [comment]
The permission is also required if you hope the keyboard shortcut Ctrl-Tab/Ctrl-Shift-Tab to switch tabs skipping collapsed tabs. Otherwise you can remove the permission.

**Comment by markocelan** [comment]
After the upgrade to 4.0.2(without updating any permissions) it started to work as expected. Thank you!
