### ISSUE TITLE
[Bug] Private window bricked after 4.0.0/4.0.1 upgrade

### ISSUE THREAD

**Issue by psofiterol** [piroor/treestyletab#3475]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Make sure version is 4.0.1
 4. Open a private widow and start opening tabs

## Expected result (normal window)
![image](https://github.com/piroor/treestyletab/assets/25620559/1364b6d1-e3bc-46b2-b2dd-88de7423d7e1)

## Actual result (private window)
![image](https://github.com/piroor/treestyletab/assets/25620559/05b06eb3-9a78-4db1-914d-b1c3405431e9)

## Environment

 * Platform (OS):  Ubuntu 22.04.4 LTS
 * Version of Firefox:  123.0 (64-bit)
 * Version (or revision) of Tree Style Tab:  4.0.1

**Comment by psofiterol** [comment]
Downgraded to 3.9.22 to temporarily fix this - worked as expected.

**Comment by piroor** [comment]
I cannot reproduce this, so there looks to be something missing steps to reproduce. Could you share exported configs of TST with me?

**Comment by psofiterol** [comment]
Hey :wave:

Full version (skipped the lines about it being a snap, sry)
![image](https://github.com/piroor/treestyletab/assets/25620559/0893feab-0b14-4a2d-bba9-bb80ba1ec303)

And the configs:
[configs-treestyletab@piro.sakura.ne.jp.json](https://github.com/piroor/treestyletab/files/14570798/configs-treestyletab%40piro.sakura.ne.jp.json)

**Comment by SimonPilkington** [comment]
I encountered this after first updating from 3.9.22 to 4.0.1 but after restarting the browser it was fixed.

**Comment by ElhemEnohpi** [comment]
I got the same thing, starting today, with the 4.0.1 release, on Mac Firefox 123.0.1. My browser was open during the update to 4.0.1 overnight, and in the morning a private window I had open had the appearance similar to the "actual result" screenshot above. It was also not possible to scroll the tab sidebar. It seems to be resolved by restarting Firefox. Other non-private windows were not affected.

I was able to save the private window first, using Tab Session Manager. At first, restoring it also gave the broken appearance, but after restarting Firefox, I could restore it successfully.

**Comment by psofiterol** [comment]
right, thanks a lot @SimonPilkington & @ElhemEnohpi, I can confirm that restarting Firefox (after upgrading back to 4.0.1) has indeed fixed this issue!

@piroor not sure if I should just mark the issue as closed given the nature of the fix, leaving it up to you :pray: (maybe good to leave it up for other ppl who might encounter this?)

**Comment by piroor** [comment]
Sadly I still cannot reproduce the problem after importing the config file https://github.com/piroor/treestyletab/issues/3475#issuecomment-1991299512 . I've seen user style sheet in the config but I couldn't find out any possible triggers. Hmm...

Anyway restarting may be a workaround as some people reported, if something data cached by Firefox triggers problems.

**Comment by afontenot** [comment]
I also saw this and it went away after a restart.

Actually before restarting I downgraded and upgraded several times between the last 3.X and 4.01, and reproduced the issue multiple times whenever I returned to 4.01.

I also have a user style sheet (very small, just reduces the height of the tab bars), but removing it didn't fix the issue, even with a new private window.

**Comment by afontenot** [comment]
So, this is interesting. Now that I've restarted the browser, I see the reverse. When I force a downgrade to 3.9.22, the bug resurfaces! It then goes away again when I upgrade to 4.X.

Was able to reproduce on both photon and proton (the only two I tested).

**Comment by psofiterol** [comment]
Closing this - the issue goes away after a Firefox restart.
