### ISSUE TITLE
[Bug] Some profiles don't work properly at reduced heights

### ISSUE THREAD

**Issue by clockwinder** [piroor/treestyletab#3478]
## Abstract

When using the Photon profile at small tab heights, you can't drag tabs ontop of one another to create a tree.
![TST error](https://github.com/piroor/treestyletab/assets/54368516/4b08ecc7-2883-4306-982f-1932dab1a067)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. reduce tab height in user styles
```
.tab {
  height:20px; /*Originally 25px*/
}
```
 4. Switch to `Photon` Theme
 5. open enough tabs until the scroll bar appears ~50
 6. Attempt to drag tab ontop of another to create tree

## Expected result
I should be able to drag tabs to make a tree regardless of theme or tab height.

## Actual result
I can't drag tabs into a tree

## Environment

 * Platform (OS): Windows
 * Version of Firefox: 123.0.1 (64)
 * Version (or revision) of Tree Style Tab: 4.0.1

**Comment by piroor** [comment]
I've released 4.0.2 with a fix about calculation of tab dimensions on the Photon theme. I think it solves this issue also. Please wait until it is published.

**Comment by piroor** [comment]
Sorry it was not fixed yet. The commit 3882d8c should does.

**Comment by clockwinder** [comment]
@piroor 

I'm not sure this issue is fully resolved.  After updating to 4.0.3 and following the same steps I put in my original post, but setting the tab height to `14px`; you can see that the bounding box for selecting tabs with the mouse isn't correct.  The selecting area is ~5 pixels below the cursor. 

![TST theme issue](https://github.com/piroor/treestyletab/assets/54368516/ddfb533f-1ab7-439b-ae4e-6413ed95b9a7)

**Comment by piroor** [comment]
On this case tabs are actually expanded to top due to their wider contents.
![image](https://github.com/piroor/treestyletab/assets/70062/a2ff2ccf-efce-438e-b176-397f2bff8ae0)
You need to shrink tab contents also, for example:
```css
.tab,
.caption {
  height:14px;
}
```
TST's tab structure was changed a little at TST 4.0 so you may need to inspect tabs and update your user style sheet.
https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-inspect-the-sidebar

**Comment by piroor** [comment]
For convenience I've introduced a change 388953b to limit height of tab contents even if tabs are customized as thinner. After a new release you won't need to set height for `.caption` also anymore.

**Comment by Mzyxptlk** [comment]
The `.caption` fix resolves the last v4 issue for me, thanks!
