### ISSUE TITLE
[Bug] Pinned tabs can get hidden

### ISSUE THREAD

**Issue by MMeent** [piroor/treestyletab#3479]
## Abstract

When the width of the sidebar is precisely configured, pinned tab icon elements can overflow without the height of the pinned tabs container element increasing, thus hiding the last _N-lines_ elements of the pinned tabs

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Use Photon
 4. Pin 7 tabs. You'll have something like this: ![image](https://github.com/piroor/treestyletab/assets/2960313/8bcce8a9-e173-40fb-a8da-82c289973ece)
 5. Reduce the width of the sidebbar to around the width of those 7 tabs. You'll go from the above, to the following in succession:
   - ![image](https://github.com/piroor/treestyletab/assets/2960313/f2815db4-87bd-443a-91d2-00286dc4680f)
   - ![image](https://github.com/piroor/treestyletab/assets/2960313/a3458185-6a3c-4fb7-85e5-24523feb466d)

(note the temporary disappearance of the selected `about:addons` pinned tab)

## Expected result

All pinned tabs show up

## Actual result

One pinned tab is hidden from view (or multiple tabs, if more than one line was in use).

## Environment

 * Platform (OS): Windows
 * Version of Firefox: Beta 124.0b5 
 * Version (or revision) of Tree Style Tab: 4.0.1 (2024.3.8) with no updates available.

**Comment by piroor** [comment]
Thanks, the commit 1de646f should fix this.
