### ISSUE TITLE
[Bug] Cannot hide scrollbar

### ISSUE THREAD

**Issue by azhongzl** [piroor/treestyletab#3481]
## Abstract
Cannot hide scrollbar.
<img width="200" alt="SCR-20240312-jyrx" src="https://github.com/piroor/treestyletab/assets/22796369/6e6e7ac5-9bb6-4839-a2fb-9ad5cd2d7084">

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Hide scroll bar in user styles
```
/* Hide scrollbar */
#tabbar { scrollbar-width: none; }
```
 5. Open many tabs to trigger scrollbar
 6. We can see scrollbar even we hide it.

## Expected result
Scrollbar should be hidden if we set it to be.

## Actual result
Scrollbar is not hidden even we set it to be.

## Environment

 * Platform (OS): MacOS
 * Version of Firefox: 123.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab: 4.0.1

**Comment by subjut** [comment]
It seems, the CSS code has changed. This works for me: `#normal-tabs-container { scrollbar-width: none; }`.
The [Wiki](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-scrollbar-1507) needs to be updated.

**Comment by azhongzl** [comment]
Updated the [wiki](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-scrollbar-1507)
