### ISSUE TITLE
New release breaks drag and drop within sidebar when changing tree structure

### ISSUE THREAD

**Issue by sgjohnson1981** [piroor/treestyletab#3483]
## Steps to reproduce

I'm not sure what's going on, but I can't reproduce in a new profile. On my current profile the drag and drop has stopped working insofar as dropping a tab on another tab to create a sub-tab. No matter where I try to drop, only a single line to change positions within the current structure is possible, i.e. the outline of an entire tab that appears before dropping to create a sub-tab never appears no matter where I drag it. I haven't changed any settings so I'm guessing the new update broke something.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 123.0.1
 * Version (or revision) of Tree Style Tab: 4.0.1 is causing the issue. Reverting back to last version prior downloadable from Firefox store, 3.9.22, works fine.

**Comment by piroor** [comment]
This looks to be a duplication of #3478 (and the source is same to #3470 and #3471 ). Fixed with 4.0.3, so please wait until it is published.

**Comment by sgjohnson1981** [comment]
> This looks to be a duplication of #3478 (and the source is same to #3470 and #3471 ). Fixed with 4.0.3, so please wait until it is published.

Like some of those I'm also using High Contrast theme.

**Comment by NefariousFerris** [comment]
Same here, just started happening this morning, not sure what changed

**Comment by sgjohnson1981** [comment]
New update to 4.0.3 seems to have fixed it.
