### ISSUE TITLE
[Bug] Children and even Parent Tabs Disappear upon unopening the Tabs

### ISSUE THREAD

**Issue by Mahim2000** [piroor/treestyletab#3484]
## Short Description
1) Tabs look Hidden when a New Tab is opened. No amount of scrolling brings me toward my tabs
2) If a Parent Tab with a Child Tab in it is unopened, Opening it again doesnt show the Child Tab(s). Opening and Unopening the Parent tab shows the Child Tab(s) for half a second, meaning the tabs are still there, It's just the bug is hiding it.
3) If all the Parent Tabs are closed, the Tab simple Disappears/Gets Hidden.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open up Tabs with Multiple Children Tabs.
 4. Unopen the Parent Tabs
 5. Watch them Disappear and Not show despite scrolling

https://github.com/piroor/treestyletab/assets/114470045/523cea7f-636c-484e-98af-3740b9dad2dc

## Expected result

Parent Tabs open and reopen as expected

## Actual result

Children Tabs, even Parent Tabs get disappeared

## Environment

 * Platform (OS):  Linux Mint v21.3 (Kernel 6.5.0-25 Generic)
 * Version of Firefox: 123.0.1
 * Version (or revision) of Tree Style Tab: 4.0.1

**Comment by piroor** [comment]
I couldn't reproduce the problem for now. You looks to use something user style sheets (userChrome.css and TST's advanced options) so they may affect to the problem. Could you confirm those style sheets affects to the problem or not? If it is fixed after you unload user style sheets, please share those style sheets to me to inspect.

**Comment by Mahim2000** [comment]
> I couldn't reproduce the problem for now. You looks to use something user style sheets (userChrome.css and TST's advanced options) so they may affect to the problem. Could you confirm those style sheets affects to the problem or not? If it is fixed after you unload user style sheets, please share those style sheets to me to inspect.

Hey there!
As you said, I did disable the Style CSS, and even All of the CSS for that matter, and nothing worked.
Here,

![Screenshot from 2024-03-13 19-49-13](https://github.com/piroor/treestyletab/assets/114470045/a64edbf4-99b0-4740-9dcf-d707a932210e)

The TST Tabs dont scroll past the limit, even after more tabs being opened beyond that.
As you can see, in the TST sidebar, The Last tab is a New Tab, whereas in the Default Top Tab bar, after that New Tab, there's another New Tab, A Youtube Tab and a Google Search Tab opened, which I cant scroll towards in TST.
I guess that means the CSS aint the issue here. The TST Config File is attached below:

[configs-treestyletab@piro.sakura.ne.jp.json](https://github.com/piroor/treestyletab/files/14588731/configs-treestyletab%40piro.sakura.ne.jp.json)

Also, while writing the comment, TST suddenly reloaded and now I have a big Footer in TST.

![Screenshot from 2024-03-13 20-02-27](https://github.com/piroor/treestyletab/assets/114470045/27529372-66f5-4c9e-9ed6-55d4c77f0eac)

**Comment by piroor** [comment]
Thanks! TST 4.0.3 has a fix about similar problem, but I've realized that your user style sheet has both top and bottom margins for each tab and the fix in TST 4.0.3 is incomplete for such cases. I've pushed a change 75b83a3 and the "big footer" problem should go away.

**Comment by piroor** [comment]
This is a workaround until 4.0.4:

```css
tab-item {
  margin: var(--tab-margin);
  margin-top: 0; /* added */
}
```

**Comment by piroor** [comment]
And the commit should affects to the problem: last tab is placed beyond the scrollable area. Could you try the development build?
https://github.com/piroor/treestyletab?tab=readme-ov-file#development-builds

**Comment by Mahim2000** [comment]
> This is a workaround until 4.0.4:
> 
> ```css
> tab-item {
>   margin: var(--tab-margin);
>   margin-top: 0; /* added */
> }
> ```

This Fixed the Big Footer Problem, for the most part.
Closing the bottom-most tabs creates that empty big footer, but it goes away once a new tab is opened.
Thanks for the Fix, man! <3

But surprisingly enough, the Disappearing Tab Issue have been fixed as well. Although I dont wanna call this a confirmation, since I wanna keep on using it for a while to see if the issue gets reproduced at any point again. But overall, thank you so much for the fast response and fixes!

**Comment by Mzyxptlk** [comment]
I ran into this issue for a while too: after collapsing a large tab tree, subsequent tabs (ie. those previously off-screen) would not be shown, even when they should've scrolled back into view. As a workaround, changing the width of the sidebar (click and drag) brought them back.

I don't think I've seen it since v4.0.3, though. Photon theme.

**Comment by FelixBrakel** [comment]
I am experiencing an issue like this as well.

I have firefox reopen all the tabs from the previous session. before version 4.0.1 this was working fine. Now the tree only shows the tabs that were loaded before the firefox restart.

If I restore the previous session using the Tab Session Manager extension it restores the tree correctly, but after a while the unloaded tabs disappear again.

**Comment by piroor** [comment]
> If I restore the previous session using the Tab Session Manager extension it restores the tree correctly, but after a while the unloaded tabs disappear again.

This looks need to be tracked as a new issue. Could you create it with detailed steps to reproduce?
