### ISSUE TITLE
[Bug] Pop-up windows cannot display any content

### ISSUE THREAD

**Issue by cemeteryparty** [piroor/treestyletab#3487]
## Abstract
The pop-up alert window, confirm window will open, but it will not display any content.

## Test Cases

 - Close a collapsed trees
 - Add selected trees to bookmarks

![](https://github.com/piroor/treestyletab/assets/42334422/fb7ebdd0-301f-461b-a5e9-8920bd37a463)

## Environment
 - Platform (OS): Windows
 - Version of Firefox: 123.0.1
 - Version (or revision) of Tree Style Tab: 4.0.1 (2024.3.12) with no updates available.

**Comment by piroor** [comment]
This is dup of #3474 and has been fixed at 4.0.3.
