### ISSUE TITLE
[Enhancement] Middle-click on "+" to open the clipboard URL in new tab

### ISSUE THREAD

**Issue by kengruven** [piroor/treestyletab#3489]
## Abstract

In the normal (top) Firefox tab bar, middle-clicking the "+" (new tab button) will create a new tab and automatically open the contents of the clipboard as a URL.  Or if it's not a URL, it'll search for that term with the default search engine.

TST has a new tab button "+" in its sidebar, and middle-clicking it opens a new tab, but this doesn't use the clipboard contents at all.

I propose that middle-click on the TST "+" should work the same as the ordinary tab "+" button.

Rationale:
 - It's more consistent with the existing Firefox interface
 - It requires no new configuration or settings options
 - No functionality would be lost: you can still left-click to get a plain tab

Note that middle-clicking in the empty space next to tabs creates a new default tab, in both tab areas, so that behavior is already consistent with Firefox and should not change.

## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Copy a URL to the clipboard
 4. In the TST sidebar, middle-click on the "+" at the bottom

## Expected result

A new tab is opened at that URL (same as would occur if you middle-clicked on the "+" at the normal tab bar).

## Actual (present) result

A new tab is opened, but it ignores the clipboard and makes a default tab.

## Environment

 * Platform (OS): Debian (stable)
 * Version of Firefox: 115.0esr
 * Version (or revision) of Tree Style Tab: 4.0.3

**Comment by piroor** [comment]
Thank you for detailed explanation! I've implemented it with recent commits a629d00 , 6aaeb3f and 989e28a .

**Comment by kengruven** [comment]
Hello!  I've been using this feature for a few weeks now, and it's very nice -- thank you!

One small note: I've noticed that the Firefox tab bar uses the selected text (X11 "PRIMARY"?), while the TST tab column uses the clipboard text (X11 "CLIPBOARD"?).  This isn't a huge deal, and I'm not even sure if it's possible for extensions to read the other one.  I looked around a little and found [this Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1418462) which looks like the original browser feature patch, if that's any use.

And if it's difficult or impossible to make these work exactly the same, that's totally fine with me.  I'm just pointing it out.  Thanks again!

**Comment by piroor** [comment]
@kengruven Sadly it is impossible to access to the selection clipboard on Linux with WebExtensions API or Web standard APIs. Thus I've added a mechanism to register an external provider 652c6c9. I also pushed added a change to register a provider based on special power APIs on Waterfox's experimental tabs sidebar feature based on TST, so you can get contents of the selection clipboard if you use Waterfox's tabs sidebar on future versions.
