### ISSUE TITLE
[Bug] Tabs' scrollbar became very big after v4

### ISSUE THREAD

**Issue by MagicalDrizzle** [piroor/treestyletab#3491]
## Abstract
Scrollbar grew giant on v4.0.0
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open enough tabs to make the scrollbar appear.

## Expected result
Scrollbar stays small (v3.9.22)
![old](https://github.com/piroor/treestyletab/assets/49761211/389fafa6-cff0-4774-9f7b-379a28becdea)

## Actual result
Scrollbar grew very large (v4.0.0)
![new](https://github.com/piroor/treestyletab/assets/49761211/cec9143a-7dec-4774-80c8-48bbc2265cc1)

## Environment

 * Platform (OS): Windows
 * Version of Firefox: 123.0.1, 124.0b9 
 * Version (or revision) of Tree Style Tab: 4.0.0

**Comment by piroor** [comment]
Thanks, the commit dc64e2a should fix this.

**Comment by MagicalDrizzle** [comment]
The scrollbar is fixed, however it seems its color is now broken.
v3.9.22: white scrollbar normally, gray on hover
![Screenshot (28)](https://github.com/piroor/treestyletab/assets/49761211/68158195-2759-49ad-9538-29525275e6d0)
latest commit: black scrollbar normally (visibility issues), and completely invisible on hover.
![Screenshot (29)](https://github.com/piroor/treestyletab/assets/49761211/c0a7d8f9-d699-40ce-86f7-76b63aac4772)
I am using photon theme.

**Comment by piroor** [comment]
Thanks, 82359fb should fix the color.

**Comment by MagicalDrizzle** [comment]
Thanks! Seems everything is working fine now!
