### ISSUE TITLE
[Bug] Placing the "new tab" button at the top results in incorrect shadow line

### ISSUE THREAD

**Issue by gtimbo** [piroor/treestyletab#3492]
Note, this issue has been raised following on from [this comment](https://github.com/piroor/treestyletab/issues/3477#issuecomment-1997792339), which it turns out is unrelated.

## Abstract
Using [this CSS](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#put-new-tab-button-at-the-top-of-the-tab-bar-1376) to place the "new tab" button at the top of the tab bar results in the shadow line for the "new tab" button still being displayed at the bottom.

## Steps to reproduce
Add the CSS to the User Style Sheet in the Advanced configuration section. With enough tabs in the tree to fill the tab bar, scroll upwards and the shadow line will appear at the bottom. Scroll to the bottom and the shadow line will disappear.

Note that I haven't tested what happens when there aren't enough tabs to fill the tab bar.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 123.0.1 64-bit
 * Version (or revision) of Tree Style Tab: 4.0.3

**Comment by piroor** [comment]
I've updated the snippet:
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#put-new-tab-button-at-the-top-of-the-tab-bar-1376

**Comment by gtimbo** [comment]
That seems to work fine. Thanks @piroor.
