### ISSUE TITLE
[Bug] When opening a new tab via the context menu, TST scrolls all the way to the top

### ISSUE THREAD

**Issue by Ennea** [piroor/treestyletab#3493]
## Abstract

When opening the context menu of any tab and selecting the "New Tab" option, if the list of tabs is longer than the viewport (needs scrolling), TST first scrolls to the very top and immediately back down to the newly created tab.

## Steps to reproduce

 1. Have a long list of tabs that requires scrolling.
 2. Right-click a tab near the bottom.
 3. Select "New Tab".

## Expected result

New tab is created and nothing else happens.

## Actual result

New tab is created, the view scrolls to the top and back down.

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 124.0.b9
 * Version (or revision) of Tree Style Tab: 4.0.3

**Comment by piroor** [comment]
Thanks, the commit ddce4a3 should fix this.
