### ISSUE TITLE
[Bug] close box too close to or overlapping panel boundary (close box half hidden)

### ISSUE THREAD

**Issue by rokdun** [piroor/treestyletab#3494]
## Abstract

Hello, on Firefox last version (123.0.1) with last TST available (4.0.3, I've seen 4.0.7 exists but Firefox doesn't know about it apparently), on Windows 11.

About a week ago, my close boxes are not aligned anymore. If tab title is small, it's OK, if tab title is too large, the close box goes too far to the right and is partially hidden (truncated). So it's more difficult to click on it, even though it still works.

## Steps to reproduce

I don't know bow to reproduce, it juste happened without me doing anything special. I have hundreds of tabs, and it works perfectly except for this alignment (or rather, tab label size) issue.

By the way, I've been using TST for years and it's wonderful. Thank you so much!

<img width="297" alt="TST_close_boxes_issue" src="https://github.com/piroor/treestyletab/assets/26318935/23f02cca-261c-4bc3-8ed4-436384d3f5d6">

**Comment by irvinm** [comment]
If you clear out your TST CSS, does everything work properly?  (I'm going to guess "yes")

I had a different issue with my CSS and had to do some minor tweaks to get it to my desired state.

**Comment by rokdun** [comment]
It worked! I had this in the CSS in the Advanced Options :
/* Hide .twisty and adjust margins so favicons have 7px on left. */
.tab .twisty {
    margin-left: +15px;
}

I don't know where it comes from, a looong time ago there was some suggestion about modifying the CSS for TST, something like hide some stuff, maybe it came from that time.
Anyway, great suggestion, thanks!
