### ISSUE TITLE
[Enhancement] Return ability to show hidden tabs

### ISSUE THREAD

**Issue by lucasama** [piroor/treestyletab#3495]
## Abstract

It used to be possible to hide unloaded tabs on Firefox's horizontal tab bar, while keep showing them on the Tree Style Tab's sidebar.
This was very useful to me to be able to quickly jump to different active tabs by clicking the horizontal tab bar, rather than scrolling on the TST sidebar.
I was using the Tab Unloader extension for this behavior, and created the same issue in their Github repo:
https://github.com/Lej77/tab-unloader-for-tree-style-tab/issues/45

## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install the Tab Unloader extension: https://github.com/Lej77/tab-unloader-for-tree-style-tab
 4. In the options for the Tab Unloader extension, in the Tab Hiding section, check the "Hide unloaded tabs..." checkbox, and the "Show hidden tabs in TST's sidebar" checkbox. This behavior is no longer supported, since it's no longer possible to keep showing unloaded tabs on TST's sidebar.

## Expected result
Unloaded tabs can be hidden in the horizontal tab bar, while keep showing them in TST's sidebar.

## Actual (present) result
Unloaded tabs cannot be hidden in the horizontal tab bar while keep showing them in TST's sidebar.

## Environment

 * Platform (OS): Windows
 * Version of Firefox: 123.0.1
 * Version (or revision) of Tree Style Tab: 4.0.3

**Comment by piroor** [comment]
Hmm... TST 4 does not generate DOM nodes for hidden tabs, and the condition is hard coded. It looks very hard to return ability to generate DOM nodes for tabs currently rejected to be rendered.

**Comment by lucasama** [comment]
I see...
I'm sad to hear, since given the way I work, I loved this feature.
I usually keep a small number of loaded tabs, but a big number of unloaded tabs.
Therefore, the horizontal tab bar was my way to navigate to the tabs I was currently using, even if they were far apart on TST (needing scrolling)
For me it was similar functionality to the TST Sticky Tabs addon.

**Comment by piroor** [comment]
I have another concern: if I introduce options to build DOM nodes for collapsed and hidden tabs, they may make things more worse about performance. Currently TST's virtual scrolling expects all tabs have same height and hidden/collapsed tabs are invisible = zero height, so operations to extract list of to-be-rendered tabs is easily calculated. If we allow "collapsed/hidden tabs with zero height by default and easily changeable its visibility via user style sheet", we need to scan tabs state to measure actual height...

So it is the only one effective solution: introducing options to expose hidden and collapsed tabs completely.

**Comment by piroor** [comment]
I've added a new option `renderHiddenTabs` with the commit 7c000b0. Hidden tabs are now become visible by turning it to `true`.

And I dropped the plan to add another option to expose collapsed tabs, because "visible collapsed tabs" will have height different to regular tabs and it is meaningless if only full height "visible collapsed tabs" became available.

**Comment by lucasama** [comment]
I was able to test this today...
Amazing, thank you very much!!
