### ISSUE TITLE
[Bug] Middle-click on "+" stopped working

### ISSUE THREAD

**Issue by CompileNix** [piroor/treestyletab#3499]
## Abstract

Middle click on the "+" stopped working.

The issue was introduced in version 4.0.8.

The most recent version, where this issue is not present, is: 4.0.3.

I suspect that the issue is related to #3489

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Middle-click on the "+" of TST

Note: Middle-click on the "+" of the Firefox tab bar, at the top of the window, works as expected.

## Expected result

A new blank Tab opens, as last child of the current tab (as per default TST settings).

## Actual result

Nothing happens.

## Environment

 * Platform (OS): Fedora Workstation 39
 * Version of Firefox: 123.0.1
 * Version (or revision) of Tree Style Tab: 4.0.8
 * All Firefox- and TST-Settings are at their default values.

**Comment by piroor** [comment]
Is the "Get data from the clipboard" permission granted at about:addons => "Extensions" => "Tree Style Tab" => "Permissions" tab? If it is unchecked please try it after check it.

**Comment by piroor** [comment]
I've realized that current implementation may raise an error when `dom.events.asyncCLipboard.clipboardItem` is `false`. Turning it to `true` via about:config is a workaround.

And I've pushed some changes to avoid the error just skipping operations to read the clipboard if the feature is not available.

**Comment by CompileNix** [comment]
> Is the "Get data from the clipboard" permission granted at about:addons => "Extensions" => "Tree Style Tab" => "Permissions" tab? If it is unchecked please try it after check it.

No, it is not. But granting the permission, and restarting the browser, did not change the described behavior for me.


> I've realized that current implementation may raise an error when `dom.events.asyncCLipboard.clipboardItem` is `false`. Turning it to true via about:config is a workaround.

Thanks, I can try that out tomorrow and will report back.

**Comment by CompileNix** [comment]
I can confirm that the following workaround works for version 4.0.8:

1. navigate to `about:config`
2. click on "Accept the Risk and Continue"
3. enter `dom.events.asyncCLipboard.clipboardItem` into the search
4. change the value from `false` to `true`
5. navigate to `about:addons`
6. navigate to the extension "Tree Style Tab"
7. go to "Permissions" and enable the optional permission `Get data from the clipboard`

After that Middle-click on "+" of TST is working again.

**Comment by testeddoughnut** [comment]
Ran into this today and found that you can restore the original behavior by just:

1. going into the extension preferences in `about:config`
2. check `Unlock Expert Options` at the top
3. under `New Tabs not from Existing Tabs` uncheck `Open new tab with URL in the clipboard`.
 
No need to change any about:config options or grant new permissions.

(Unrelated to this issue, @piroor  I do want to extend a thanks for the time and work you've put into this project. I have been a user of this add-on for well over a decade and it is usually one of the first things I install with a fresh Firefox profile.)
