### ISSUE TITLE
[solved] (tab structure got flattened/corrupted)

### ISSUE THREAD

**Issue by tiddu** [piroor/treestyletab#3501]
i tried to restore session using backup copy of sessionstore file and it is still flattened. please help.

**Comment by jindalpratik** [comment]
Facing the same issue, the tabs have also started moving around on their own after a recent update.

**Comment by piroor** [comment]
Too less information. Please add more detailed steps to reproduce for further debugging.

Anyway, sadly you cannot take old tree structure back after it was completely lost. After you successfully reconstruct tree by drag-and-drop of tabs manually, I recommend you to save the browsing session with the tree structure by other addons like Tab Session Manager, or saving tabs to a bookmark folder with tree structure information (you need to grant a permission to access bookmarks, then right-click on a tab => select all => bookmark selected tabs will do that.)

This issue tracker aims to fix bugs of TST, so the focus of this issue should be "what triggers such a tree structure lost, and how to prevent it by the program." User-side trouble shooting topics should be posted as discussions https://github.com/piroor/treestyletab/discussions .

**Comment by THElegend5** [comment]
> Too less information. Please add more detailed steps to reproduce for further debugging.
> 
The moving of tabs happened mostly between opening and closing of browser window. But I also saw it happen right in front of me as I selected the tab.

I do use Tab Session Manager with option to restore tree style tabs enabled with successfully restoring multiple times but doing so now leads to a flat tree structure.
I can do further testing on a session I know definitely works if you would like.

> Anyway, sadly you cannot take old tree structure back after it was completely lost. After you successfully reconstruct tree by drag-and-drop of tabs manually, I recommend you to save the browsing session with the tree structure by other addons like Tab Session Manager, or saving tabs to a bookmark folder with tree structure information (you need to grant a permission to access bookmarks, then right-click on a tab => select all => bookmark selected tabs will do that.)
> 
> This issue tracker aims to fix bugs of TST, so the focus of this issue should be "what triggers such a tree structure lost, and how to prevent it by the program." User-side trouble shooting topics should be posted as discussions https://github.com/piroor/treestyletab/discussions .
>

**Comment by jindalpratik** [comment]
> Too less information. Please add more detailed steps to reproduce for further debugging.
> 

The moving of tabs happened mostly between opening and closing of browser window. But I also saw it happen right in front of me as I selected the tab.

I do use Tab Session Manager with option to restore tree style tabs enabled with successfully restoring multiple times but doing so now leads to a flat tree structure.
I can do further testing on a session I know definitely works if you would like.

> Anyway, sadly you cannot take old tree structure back after it was completely lost. After you successfully reconstruct tree by drag-and-drop of tabs manually, I recommend you to save the browsing session with the tree structure by other addons like Tab Session Manager, or saving tabs to a bookmark folder with tree structure information (you need to grant a permission to access bookmarks, then right-click on a tab => select all => bookmark selected tabs will do that.)
> 
> This issue tracker aims to fix bugs of TST, so the focus of this issue should be "what triggers such a tree structure lost, and how to prevent it by the program." User-side trouble shooting topics should be posted as discussions https://github.com/piroor/treestyletab/discussions .

**Comment by jindalpratik** [comment]
I use 126.0a1 (2024-03-19) (64-bit) but afaik this issue started with 4.0.0 but never bothered to report is I just restored my tabs via Tab Session Manager but can no longer do so.

**Comment by piroor** [comment]
Sorry for my less description. I meant about that steps to reproduce like:

1. Start Firefox with clean profile.
2. Install TST.
3. Prepare tree of tabs like as: ...
4. Do something action...
5. Exit Firefox.
6. Start Firefox, then tree structure is lost.

In other words, narrowing down of conditions is required for further debugging. Of course it is not an easy way, thus I need more help by contributors about this kind information.

**Comment by tiddu** [comment]
i solved this. had an old sessionstore file that i recovered that had most of the structure and rest of the new tabs via tab session manager and beyond compare.

**Comment by JustMyGithub** [comment]
> or saving tabs to a bookmark folder with tree structure information (you need to grant a permission to access bookmarks, then right-click on a tab => select all => bookmark selected tabs will do that.)

I just tested this way and it did not work. when I reopened all bookmarks from the bookmark folder it had a flat structure.
