### ISSUE TITLE
[Bug] Insertion Position of Duplication is not right

### ISSUE THREAD

**Issue by NightSharp** [piroor/treestyletab#3502]
## Abstract

 The Insertion Position of Duplication in settings doesn't match the actual behavior

## Steps to reproduce

1. Set the duplicating position to "Sibling Next to the Current".
2. Set "browser.tabs.insertAfterCurrent"="true"
3. Duplicat a tab

## Expected result
The duplication appear as "Sibling Next to the Current"

## Actual result
It appears as "First Child of the Current"
though set it to "false" works, but it will break my other actions about tabs

## Environment

 * Platform (OS): Windows 10 22H2 Professional (19045.4170)
 * Version of Firefox: 123.0.1
 * Version (or revision) of Tree Style Tab: 4.0.8

**Comment by piroor** [comment]
I couldn't reproduce this problem with the steps described above on a clean profile. There seems to be something more required steps reproduce, e,g, other options, how the tab is duplicated, and the URL of the duplicating tab. Could you narrow down that?

**Comment by NightSharp** [comment]
> I couldn't reproduce this problem with the steps described above on a clean profile. There seems to be something more required steps reproduce, e,g, other options, how the tab is duplicated, and the URL of the duplicating tab. Could you narrow down that?

Here is my config json file
[current.json](https://github.com/piroor/treestyletab/files/14680759/current.json)
as for URL, almost all, just like this issue page.
but not everytime it appears.
I use "Middle-Click Refresh Button" to duplicate tabs.
just duplicate and close the duplication, repeat several times.

some time it works correct
![图片](https://github.com/piroor/treestyletab/assets/9748063/10ba7a3a-135e-4a77-9183-c23c45efb671)

some time it works wrong
![图片](https://github.com/piroor/treestyletab/assets/9748063/da934705-bf21-4fb4-992b-765b94a38c24)

**Comment by piroor** [comment]
Thanks! This is a known problem and TST has an option for that: TST options => "Development" => "Delay to detect duplicated tabs" (expert option). On my case it need to be `100` to detect tabs duplicated by middle click of the refresh button or "Duplicate Tab" command on the context menu on Firefox's horizontal tabs. Here is a helper featutr to calculate delay: click the "Auto detect" button.

**Comment by NightSharp** [comment]
> Thanks! This is a known problem and TST has an option for that: TST options => "Development" => "Delay to detect duplicated tabs" (expert option). On my case it need to be `100` to detect tabs duplicated by middle click of the refresh button or "Duplicate Tab" command on the context menu on Firefox's horizontal tabs. Here is a helper featutr to calculate delay: click the "Auto detect" button.

Well, I always ignored these part before. Let me try it.
