### ISSUE TITLE
[Bug] Can't get "Close Descendants" to appear in Sub Menu anymore

### ISSUE THREAD

**Issue by Atario** [piroor/treestyletab#3503]
## Abstract

I used to have "Close Descendants" in the Sub Menu, but a recent update (not sure which) made this impossible.  Not sure if other selections are affected.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Enable "Close Descendants" checkbox for Sub Menu

## Expected result

"Close Descendants" appears in Sub Menu

## Actual result

"Close Descendants" does not appear in Sub Menu

## Environment

 * Platform (OS):  Win 7
 * Version of Firefox:  115.9.0esr (64-bit)
 * Version (or revision) of Tree Style Tab:  4.0.8

**Comment by piroor** [comment]
Thanks, the commit 06ad894 should fix this.
