### ISSUE TITLE
[Bug] Tree Style Tabs not loading

### ISSUE THREAD

**Issue by Yoposoc** [piroor/treestyletab#3507]
## Abstract

For some reason, Tree Style Tab has stopped working properly for me. None of the tabs show up in the sidebar. 
![image](https://github.com/piroor/treestyletab/assets/2718371/b7e279db-6401-4e39-93e9-a29f32a6b37b)
I tried to debug this by bisecting my profile. I made a new fresh debug profile, installed TST, and to start, brought over my `prefs.js` file from my default profile. Luckily I already found out it's the source of my problem. Below is a screenshot from my debug profile.
![image](https://github.com/piroor/treestyletab/assets/2718371/8d28ba07-f14b-4d77-8af8-77f1e9c5bfc6)
Interestingly, even the "options" menu for the debug profile is blank. It is not blank on my default profile.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Bring over my prefs.js file.
 4. TST does not work.

## Expected result

TST works normally. 

## Actual result

TST does not work properly -- not showing up in sidebar.

## Environment

 * Platform (OS): Win 10 Professional Edition.
 * Version of Firefox: 124.0 (64-bit) 
 * Version (or revision) of Tree Style Tab: 4.0.8

**Comment by Yoposoc** [comment]
Here is my prefs.js: https://shrib.com/?v=co#Luke546WAPa

**Comment by piroor** [comment]
This looks to be a dup of #3496. You look to use Tab Session Manager with TST, it can trigger the problem.

**Comment by Yoposoc** [comment]
@piroor thank you, I do indeed use Tab Session Manager. 
Interestingly, I went ahead to try to fix it. But actually now, the tabs are showing in TST! Not sure what changed. I'll reopen again if I still have issues.
