### ISSUE TITLE
[Bug] The default state of Auto-group tab don't follow my config

### ISSUE THREAD

**Issue by NightSharp** [piroor/treestyletab#3509]
## Abstract
I set every default state of the related auto-group tab from "close when 1 children left or less" (State A) to "close when no more children" (State B), but the actual auto-group tab is still in State A

## Steps to reproduce

 1. Set every default state of the related auto-group tab to State B
 2. Open a Bookmark dir
 3. See the default state of the auto-group tab

## Expected result
the tab is in State B

## Actual result
still in State A

## Environment

 * Platform (OS): Windows 10 22H2 Professional (19045.4170)
 * Version of Firefox: 124.0 x64
 * Version (or revision) of Tree Style Tab: 4.0.10

**Comment by piroor** [comment]
Thanks, the commit 00eba8c should fix this.

**Comment by NightSharp** [comment]
@piroor 
There is a similar issue for a TST add-on here
https://github.com/piroor/tst-open-bookmarks-as-partial-tree/issues/14
