### ISSUE TITLE
[Bug] Typo

### ISSUE THREAD

**Issue by abcdenis** [piroor/treestyletab#3511]
Hi,

there is "isnert" and it makes reading decompressed session JSON difficult.

https://github.com/piroor/treestyletab/blob/a6c74f765481e83b61b6c22a4c4656f6bf9df729/webextensions/common/constants.js#L138

**Comment by piroor** [comment]
Thanks! The commit 3d2ca09 should fix this but we still need to keep the typo-ed name for more while for backward compatibility...
