### ISSUE TITLE
[Bug] Previously visited website's favicon is reused unexpectedly

### ISSUE THREAD

**Issue by kenhys** [piroor/treestyletab#3515]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open new tab and access website which use favicon.ico
    e.g. https://addons.mozilla.org/ja/firefox/addon/tree-style-tab/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search
 4. Access other website which doesn't use favicon.ico in same tab which is opened in step 3.
    e.g. https://mentors.debian.net/

## Expected result

When website doesn't provide favicon.ico, default favicon is shown on active tab.

## Actual result

Previously accessed website's favicon.ico is reused. It is annoying.

## Environment

 * Platform (OS):  Linux
 * Version of Firefox: 125.0b6
 * Version (or revision) of Tree Style Tab: 4.0.10

**Comment by kenhys** [comment]
![image](https://github.com/piroor/treestyletab/assets/225841/3b37f01b-9281-4f03-976e-a8342320e004)


1. addons.mozilla.org (favicon.ico is shown expectedlly)
2. mentors.debian.net (newly opened tab and favicon.ico is not used.  default icon is shown)
3. access addons.mozilla.org => mentors.debian.net (unexpectedly favicon is reused)

**Comment by piroor** [comment]
Thanks! The commit 2b31f51 should fix this.
