### ISSUE TITLE
[Bug] "High Contrast" Theme renders without tab button borders in 4.0.10

### ISSUE THREAD

**Issue by jmbreuer** [piroor/treestyletab#3517]
## Abstract

Updated version 4.0.10 changes "High Contrast" Tab rendering, omitting borders, resulting in a rendering I'm less capable to grasp at a glance. 

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open TST preferences
 4. Choose "High Contrast" Theme under Appearance

## Expected result

A Tab Tree rendering resembling what's shown in the preview graphic, and/or as it used to be before 4.0.10. This seems to be a change/regression related to that release.

## Actual result

The Tab Tree renders without borders around the individual Tabs, depending on background color it makes the tree very hard to understand at a glance and does not meet "High Contrast" requirements/expectations.

In Firefox:
![Firefox Tree snippet](https://github.com/piroor/treestyletab/assets/1792037/192366f5-6146-4bae-b106-3de4a78401ec)

In LibreWolf:
![LibreWolf Tree snippet](https://github.com/piroor/treestyletab/assets/1792037/ff6edc67-017d-4f9b-9dad-7a8c3bbed875)

## Environment

 * Platform (OS): Gentoo x86_64 23.0 (Desktop, Plasma, systemd)
 * Version of Firefox: 124.0.1, also LibreWolf 124.0.1-1
 * Version (or revision) of Tree Style Tab: 4.0.10

## Additional Information

The Photon theme in 4.0.10 looks quite like what I'm looking for, but would need a higher-contrast color scheme (especially: strong color for active tab which will probably make inverted text appropriate).
I've had a brief look at the advanced style options, but don't really know which of those to touch to get where I'd want. (I.e. I'm missing a cheat sheet correlating the style names to what tree elements they relate to.) For a workaround, I'd be happy about some direction in that regard.

**Comment by piroor** [comment]
Thanks, I've realized that CSS system color `ButtonShadow` is now same to `ButtonFace` on Firefox 124 on Windows 11. It is possibly a bug of Firefox itself - it should be different from `ButtonFace`, anyway I've pushed a change to set border-color more visible: `ButtonText`.

**Comment by piroor** [comment]
Here is a workaround until the change is released, please set user style sheet in TST options as:

```css
:root {
  --tab-border: ButtonText;
}
```

**Comment by piroor** [comment]
There is a new report about too high contrast of the new border color: #3526 
@jmbreuer Could you try the visibility of another color? I'll apply it for the next release if it is acceptable.

```css
:root {
  --tab-border: GrayText;
}
```
