### ISSUE TITLE
TST doesn't remember tabs created by extensions like Stylish

### ISSUE THREAD

**Issue by WillPittenger** [piroor/treestyletab#3518]
## Abstract

I have a profile with TST.  I have a tab I want to keep an associated Stylish tab open for it.  The style for the original tab should be a child of the original.  But TST doesn't remember such tabs.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install Stylish.
 4. Visit Google.com.
 5. Write a style for Google.com in Stylish.
 6. Make the style's page in the Stylish editor a child tab of the the tab for Google.com.
 7. Restart FF.
 8. Is the Stylish page there?

## Expected result
Presumably, a restart should preserve all tabs regardless of position or URL type.

## Actual result
Stylish tabs aren't restored after a restart.

## Environment

 * Platform (OS): Windows 11 Pro 23H2 22631.3296 Windows Feature Experience Pack 1000.22687.1000.0
 * Version of Firefox: 124.0.2 
 * Version (or revision) of Tree Style Tab: 4.0.10

**Comment by piroor** [comment]
It looks not depending on TST. The "Edit" tab is gone even if TST is disabled for me.
