### ISSUE TITLE
[Bug]new tabs that inherit a container load then get blanked immediately

### ISSUE THREAD

**Issue by kephas** [piroor/treestyletab#3520]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Go to TST Settings
     1. Unlock Expert Options
     2. Change `New Tabs not from Existing Tabs`/`Basic control for New Blank Tabs`/`Container` to `Inherit from the current tab`
 4. Open tab in `Personal` container and switch to that tab
 5. From terminal, do `firefox  --new-tab --url "https://mozilla.org/" `

## Expected result

New tab opens in `Personal` container and page is shown.

## Actual result

New tab opens in `Personal` container, URL is empty and page is blank. Sometimes, URL and page can be seen for less than a second and disappear.

## Environment

 * Platform (OS): Debian
 * Version of Firefox: 115.8.0esr
 * Version (or revision) of Tree Style Tab: 4.0.11

## Additional details

This bug happens in any combination where the new tab inherits a container, like:

- Open as independant + Inherit from current
- Open as child in the tree + Inherit from parent

**Comment by piroor** [comment]
I couldn't reproduce this on Windows 11, so this can be a Linux environment specific issue.

**Comment by piroor** [comment]
Confirmed on Ubuntu 22.04.

**Comment by piroor** [comment]
The commit ff12753 should fix this.
