### ISSUE TITLE
[Bug] Drag and drop parent-child / subtree broken on 4.0.11

### ISSUE THREAD

**Issue by natenate19** [piroor/treestyletab#3521]
## Abstract
Drag and drop of a tab onto an existing tab outside of an existing parent-child relation is broken.
## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a bunch of tabs
 4. Try to drag the last tab, or any tab, onto an existing tab to create a parent-child tab relation / subtree.
## Expected result
Drag and dropping a tab onto another should create a new subtree / parent-child relation.
## Actual result
It is impossible to drop one tab onto another.  It is possible to place the dragged tab above or below an existing tab, but not to create a new subtree by dropping onto the tab.  If there is an existing parent-child subtree, it is possible to drag and drop a tab into that subtree however.

![Screenshot 2024-04-04 at 10 31 43 PM](https://github.com/piroor/treestyletab/assets/279747/2d800aaf-b831-4807-b99e-1016c2ebeab2)
![Screenshot 2024-04-04 at 10 42 20 PM](https://github.com/piroor/treestyletab/assets/279747/927abe9b-557f-414d-be74-21603ab8bdb3)

The behavior is also very inconsistent, sometimes it behaves as expected, usually not though as tab list grows in size.  Sometimes reloading TST in the sidebar will resolve the issue for a short while, but then it will appear again.

This is similar to https://github.com/piroor/treestyletab/issues/3519, but not the same I don't think, as there is no custom tab-size component.
## Environment

 * Platform (OS): macOS 14.4.1
 * Version of Firefox: 124.0.2
 * Version (or revision) of Tree Style Tab: 4.0.11

**Comment by piroor** [comment]
Thanks, the commit 1bf9182 should fix this.

**Comment by natenate19** [comment]
Thanks, working fine on 4.0.12 now.
