### ISSUE TITLE
[Bug] Recent update shows booksmark manager, not tabs

### ISSUE THREAD

**Issue by BHare1985** [piroor/treestyletab#3522]
## Abstract

The update from April 4/4 causes the tab menu to disappear, I had to reinstall to the 4/5 version.

## Steps to reproduce

 1. Start Firefox/Librewolf
 2. Notice bookmars bar in place of tabs.
 3. Disable and enable extension to no avail
 4.  Notice the updated 4/4
 5. Uninstall and reinstall
 6.  It works, but now updated 4/5.

## Expected result
To work 

## Actual result
Did not load, had to reinstall

## Environment

 * Platform (OS):  Windows 10
 * Version of Firefox:  Latest Librewolf.
 * Extention: The one from April 4th

**Comment by piroor** [comment]
What means "tab menu" ? The context menu on tabs in the TST sidebar, or the TST sidebar panel itself?

And what means "bookmars bar" also? If you meant the bookmarks toolbar of Firefox itself, it is fully controlled by Firefox and TST does not touch to it. Or, did you mean the "TST Bookmarks Subpanel" ?

**Comment by thebluesnevrdie** [comment]
I have experienced the same behavior, but it was the Firefox history dialog and it was after I used Ctrl+H. The TST panel is replaced by history. I use CTRL+H again, and the vertical tabs panel disappears completely. I can also use CTRL+B and bookmarks manager shows up where TST panel used to be.

**Comment by piroor** [comment]
@thebluesnevrdie Please remind that Firefox has a UI "Sidebar" which provides switchable panels: Bookmarks, History, and Synced Tabs by default. TST provides just an extra panel to the list of switchable panels. TST's default shortcut "F1" is actually "switch sidebar panel to TST". Sidebar panels are generally switched via the dropdown list above the sidebar panel, so you may need to restore it if you hide it with userChrome.css or something way.

**Comment by thebluesnevrdie** [comment]
Thanks for the guidance. For whatever reason, as soon as I added the TST icon to the toolbar, it immediately fixed the sidebar.
