### ISSUE TITLE
[Bug] photon sidebar backround is too light on linux

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#3525]
## Abstract

On Ubuntu 20.04 the sidebar background with the Photon theme is much lighter than on windows. There's not enough contrast. 

## Steps to reproduce

 1. Start Firefox with clean profile on (win10 or win11) and Ubuntu 20.04 
 2. Install TST.
 3. enable photon
 4. observe the sidebar background

## Expected result
as on windows
![image](https://github.com/piroor/treestyletab/assets/895588/894a9345-778e-4f15-90d2-67a0f46b185f)

## Actual result

on ubuntu 20.04

![image](https://github.com/piroor/treestyletab/assets/895588/09c684bf-ff83-417c-a4ca-8804d70bbeac)

## Environment

 * Platform (OS): Ubuntu 20.04
 * Version of Firefox: 124.0.2 (archive downloaded from Mozilla)
 * Version (or revision) of Tree Style Tab: 4.0.12

**Comment by piroor** [comment]
In short: Choosing the option will apply the BG color same to Windows: TST Options => "Development" => "Color scheme" => "Photon".

The color choice is intentional. There are various desktop themes on Linux distributions, and it is major on Linux community to change color scheme of the desktop environment - there is no "standard", so "Photon" color scheme may become unnatural on some environments easily. So I decided preferring system color on Linux. The BG color referes "ThreeDShadow" on the system color, it is "darkgray" on the "Photon" color scheme. It will become more darker color if you configure color definitions of your desktop environment system more darker. Or a user style sheet (under TST Options => Advanced) to override the color is also available, like:

```css
:root { --tabbar-bg: darkgray; }
```

**Comment by bughit** [comment]
> it is major on Linux community to change color scheme of the desktop environment

I'm fairly sure that Firefox chrome (whatever is under its control, within the window chrome which may be os specific) is intended to be the same (or as close as possible) across OSes.

![image](https://github.com/piroor/treestyletab/assets/895588/eed9872f-4f8a-4659-8111-1dc82ab7536c)

This intent is pretty clear from the above win/linux comparison. You are violating this convention by choosing to style parts of TST differently on linux. Your different background sticks out as an unwelcome exception to this rule. By default there should not be a difference. If you believe anyone actually wants this, which is doubtful, it should be optional.

**Comment by bughit** [comment]
There is somewhat of a general color difference between linux and win, but I'm referring more to preserving the contrast difference between the foreground and the background, than the exact color values.

**Comment by piroor** [comment]
> I'm fairly sure that Firefox chrome (whatever is under its control, within the window chrome which may be os specific) is intended to be the same (or as close as possible) across OSes.

Here is an anti-example: Firefox 124 on ArchLinux with the "Adapta" theme.
![image](https://github.com/piroor/treestyletab/assets/70062/49b7c907-d8bc-4e2d-9f62-744a13658d37)
The dark background color of the tab bar is referred with the special system color name `-moz-headerbar` (or `-moz-headerbarinactive`, both special colors cannot be used from addon's resources) so Firefox just uses the color defined in the GNOME theme. As the result the contrast around tab face and tab background is quite different from Windows.

**Comment by piroor** [comment]
I think we cannot choose colors providing same contrast on all platforms, so I chose second-best: system colors which are expected to have enough contrast.

Anyway I agree that "ThreeDShadow" the current choice is little pale on this case so there is any other possible choice. I'm not negative to change the color I use for the background, but the new choice need to have contrast enough on various environments (e.g. ArchLinux + Adapta).
