### ISSUE TITLE
"Open new blank tab as" setting is ignored

### ISSUE THREAD

**Issue by Mzyxptlk** [piroor/treestyletab#3527]
## Abstract
New blank tabs become root tabs, ignoring the "Open new blank tabs as" setting. The "Tabs from any other trigger" appears to be used instead.

## Steps to reproduce

1. Fresh Firefox profile.
2. Install TST.
3. Tick "Unlock Expert Options".
4. Set "Open new blank tab as" to "Last Child of the current tab".
5. Tick "Guess a newly opened tab as opened by the 'New Blank Tab' action", with titles "New Tab|New Private Tab" and URLs "about:blank|about:privatebrowsing|about:newtab".
6. Open two tabs, like so:
   Parent
   \- Child
7. Select the Parent tab.
8. Press Ctrl+T.

## Expected result

New tab becomes the last child of tab A:
Parent
\- Child
\- New

## Actual result

New tab becomes a new root tab:
Parent
\- Child
New

As far as I can tell this is due to the new blank tab no longer getting recognized as a new blank tab, which causes TST to apply the setting for "Tabs from any other trigger" instead. When I change that setting to "Open as last child of current tab", I get the expected result shown above.

I'm confident this bug didn't occur 24 hours ago, so this is probably a regression in v4.0.12.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 124.0.2
 * Version (or revision) of Tree Style Tab: 4.0.12

**Comment by hyperpac** [comment]
I can confirm the bug for Firefox 124.0.2 with Treestyle Tab 4.0.12 on Windows 10 64-bit.

**Comment by piroor** [comment]
Sorry it is my fault... the commit ebc9bb5 should fix it.

**Comment by Mzyxptlk** [comment]
Updated to v4.0.13 a couple of days ago, restored my old settings (as best as I could remember them): looks good. Thanks!
