### ISSUE TITLE
[Bug] TST Tab Search extension no longer works correctly with TST

### ISSUE THREAD

**Issue by miltuss** [piroor/treestyletab#3531]
Hello, TST Tab Search no longer works correctly with the latest TST and Firefox updates. the tabs are not fully displayed, leaving a large gap at the bottom of the browser when searching. The bottom tabs disappear after scrolling. Would it be possible to correct this bug?

**Comment by piroor** [comment]
Please give more information filling the issue template. Screenshots may help more researching.

**Comment by miltuss** [comment]
My list of tabs is long as indicated by the scroll bar on the left, but when I search with the TST Tab Search extension, the tabs appear at the very top, and if I scroll up the tabs on the bottom disappear into the void.

![image](https://github.com/piroor/treestyletab/assets/152040152/51786864-b2f6-49d4-a4ea-9132c9d8cf53)

The extension no longer appears to have the bottom TST boundary marker.  It worked very well before but for a month I have had this problem under all my LibreWolf 124.0.1-1 and Firefox 124.0.2 browsers.  I tested version 4.0.13 of TST (from the Firefox store) and version 4.0.8 downloaded from the github repository.  I also tested version 0.0.7 of TST Tab Search (from the Firefox store) and also the development version 0.0.7b41 from the github.  But the problem remains the same

I tested this with several Librewolf and Firefox instances under Linux-Mint 21.3

**Comment by miltuss** [comment]
@piroor Hello, I have not received a response from you, do you plan to correct this bug please?

**Comment by piroor** [comment]
Sadly there is no fundamental solution on TST side, because TST 4.0 and later won't render tabs out of the viewport and tabs under collapsed trees. TST Tab Search needs to be updated to work correctly:

* Expand all trees while searching.
* Hide all unmached tabs while searching. In other words, "shrink unmatched tabs" mode needs to be dropped.

**Comment by piroor** [comment]
Sorry I missed that "Expand all trees while searching" is already done. TST Tab Search just need to hide unmached tabs via `browser.tabs.hide()` instead of CSS hack.

**Comment by piroor** [comment]
See also: https://github.com/NiklasGollenstede/tst-search/issues/34
