### ISSUE TITLE
[Enhancement] toggle expand/collapse function

### ISSUE THREAD

**Issue by pedro-vale** [piroor/treestyletab#3535]
## Abstract

The idea is having the possibility of toggling expand/collapse behaviour letting the same to be set to a single keybind.
Currently you need to assign keybinds for two actions.

## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. create a tree
 4. create tabs under this tree
 5. use <keybind_1> to collapse
 6. use <keybind_2> to expand

Having two keybinds leads to two separate keybinds leaving the need of possible remaps and so on.

It can also make it less ergonomic in terms of usage.

 1. Start Firefox with clean profile.
 2. Install TST.
 3. create a tree
 4. create tabs under this tree
 5. use <keybind_1> to toggle collapse
 6. use <keybind_1> to toggle expand

Using a single keybind for such feels more ergonomic.

## Expected result

Being able to assigne toggle expand/collapse in order to use a single keybind to use such behaviour.

## Actual (present) result

<img width="671" alt="image" src="https://github.com/piroor/treestyletab/assets/19675607/864223d5-f96f-4d26-a5c8-6e958403d9ba">

## Environment

 * Platform (OS): MacOS
 * Version of Firefox: 125.0.2
 * Version (or revision) of Tree Style Tab: 4.0.14

**Comment by piroor** [comment]
Implemented by the commit d2c09b9. Thanks!
