### ISSUE TITLE
[Enhancement] Drag parent onto child

### ISSUE THREAD

**Issue by UnePierre** [piroor/treestyletab#3538]
## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open several tabs in a small tree
 4. Try to drag&drop the parent (`A`) of a tree onto one of its offspring.

```
A (selected)
\- B
|\- B1 (drag here)
\- C
```

## Expected result

```
B
\- B1
|\- A
\- C
```

5. The selected parent (`A`) should move and become a child of the offspring it was dragged onto (`B1`).
6. Another node becomes the parent; possibly the one that would get this position, when the parent was to be closed (`B` in the example).

This would also exchange the two nodes in a mini-tree (single-mom with only child) in a single action, which was my motivating example.

## Actual (present) result

5. Nothing happens.

## Environment

 * Platform (OS): Windows10 x64
 * Version of Firefox: 125.0.2 (32-Bit)
 * Version (or revision) of Tree Style Tab: 3.9.19

**Comment by piroor** [comment]
I've implemented this behavior experimentally. I'll decide to activate it by default or not after more dogfooding.
