### ISSUE TITLE
TST tab list blank when moving firefox window to different monitor (Error location found)

### ISSUE THREAD

**Issue by goransque** [piroor/treestyletab#3539]
## Abstract
When I move the firefox window from one monitor to another the tabs are no longer shown.
This issue appears to have been caused by my xulstore.json file as after deleting it I have not been able to repro the issue.
Making this bug report to make you aware of the potential issue and in case anyone else has this problem.

## Steps to reproduce
UPDATE: I have not been able to repro with my xulstore file alone, I must have missed some other file that is necessary to cause the issue. Will update with a proper repro path if I can figure it out.

~~1. Start Firefox with clean profile.~~
 ~~2. Install TST.~~
 ~~3. Replace default xulstore file with provided file below~~
 ~~4. Have firefox on primary monitor (windows display monitor 1)~~
 ~~5. Move firefox to secondary monitor dragging to top of screen to maximize (windows display monitor 2)~~

Note: issue only occurred when dragging from Monitor 1 to Monitor 2.
Note 2: While the tab list was blank adding a new tab would cause the missing tabs to reappear.
note 3: I doubt this is relevant but for full clarity of my setup, monitor 1 was 4k and monitor 2 was 1920x1080

[xulstore.json](https://github.com/piroor/treestyletab/files/15206320/xulstore.json)

## Expected result
Tabs are still visible after moving firefox window to secondary monitor

## Actual result
Tabs in list are no longer visible
![firefox_rRugR7MV7U](https://github.com/piroor/treestyletab/assets/11338672/7954d210-9450-4d7d-86a2-dc6a768f4acb)

## Environment

 * Platform (OS): windows 10
 * Version of Firefox: version 125.0.3 (64 bit)
 * Version (or revision) of Tree Style Tab: 4.0.14
 
 ## Additional information
I also was encountering an issue where the tabs would not update after making changes to the order or nesting.
However adding a new tab would cause a refresh and update the tab list to show them in the positions they should have been in.

For example if I were to un-nest a child tab it would still show as being nested until I added a new tab at which point the list would refresh and the tab would be properly unested.

Unfortunately I was unable to find a reliable repro for this issue and have not been able to determine if this issue was also caused by the xulstore file. At minimum I have not encountered it since I deleted my xulstore file.
If I run into the issue again I will make a separate bug report on it.

**Comment by piroor** [comment]
Does this happen only with TST? It may be a bug of Firefox itself if this happens with other sidebar addons also like Sidebery.

**Comment by piroor** [comment]
>  note 3: I doubt this is relevant but for full clarity of my setup, monitor 1 was 4k and monitor 2 was 1920x1080

Do these monitors have different DPIs? Does the problem still happen when you configure them with same DPI?
