### ISSUE TITLE
Collapsed tabs at the top are sometimes too wide

### ISSUE THREAD

**Issue by Sathors** [piroor/treestyletab#354]
I'm using treestyletab on FF 14 on windows XP, and there is an annoying bug.
I've always had the same problem, on different versions of FF and different flavors of linux too.

Sometimes tab groups are not collapsing like they should, and instead of having them all stacked neatly, some groups are stacked with more width, so it ends up by taking too much horizontal space.

Here is a screenshot of the problem : http://img191.imageshack.us/img191/6681/treestyletabs.jpg

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
