### ISSUE TITLE
[Enhancement] Drag N' Drop, maintain folded state

### ISSUE THREAD

**Issue by jiewangjs** [piroor/treestyletab#3542]
![image](https://github.com/piroor/treestyletab/assets/11204422/4cabf3d0-bb30-4794-bf96-474698098657)
When the drag and drop operation finished,how to recover folded state, or make the folded entry not expand at all?

**Comment by piroor** [comment]
TST has no built-in option for that, but there is a helper addon to control detailed behavior on such situation: [TST Lock Tree Collapsed](https://addons.mozilla.org/en-US/firefox/addon/tst-lock-tree-collapsed/).

**Comment by piroor** [comment]
The helper addon TST Lock Tree Collapsed was originally made to extract features about this topic to a separate addon. It won't be merged as a built-in feature, so this issue is marked as "wontfix".
