### ISSUE TITLE
[Enhancement] Auto show and hide TST when needed

### ISSUE THREAD

**Issue by LMauricius** [piroor/treestyletab#3543]
## Abstract

I'd like to propose a QoL improvement for saving space and tab management. Would be possible to implement (an option of) 
automatically showing TST whenever we move from having one tab open to two or more, along with hiding the sidebar when we close all tabs except one? This would save valuable screen space when I for example drag a tab to separate window to focus, and would automatically open TST when it is truly needed.

## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open TST if it is closed
 4. Close all tabs except one
 5. TST is still open despite not being needed

## Expected result

TST opens and closes when needed.

## Actual (present) result

TST needs to be manually opened and closed.

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 125.0.2
 * Version (or revision) of Tree Style Tab: 4.0.14

**Comment by piroor** [comment]
There is a FAQ: https://github.com/piroor/treestyletab#user-content-feature-requests-automatically-hide-the-sidebar

> Due to limitations of the WebExtensions API, this is impossible. There exists [a workaround with userChrome.css](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#auto-showhide-sidebar-by-mouseover-hover).
> 
> The WebExtensions API allows us to toggle visibility of the sidebar with [keyboard shortcuts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Key_combinations) and the toolbar button. Other arbitrary timings are disallowed, including mouseover and long-press of a key.
