### ISSUE TITLE
Feature request: Add option to unload tabs

### ISSUE THREAD

**Issue by bossanovaorca** [piroor/treestyletab#3546]
## Abstract

Allow [tab unloading](https://firefox-source-docs.mozilla.org/browser/tabunloader/) from Tree Style Tab, like in [Sidebery](https://github.com/mbnuqw/sidebery/blob/aa476a47f3663230ee5722d1a3cebffe4faf3192/src/services/tabs.fg.actions.ts#L1121)

## Expected result

I would like to be able to manually unload tabs from the sidebar

## Actual (present) result

There is currently no option to unload tabs from TST

## Environment

 * Platform (OS):  macOS, Windows 10, Windows 11
 * Version of Firefox: 127.0a1
 * Version (or revision) of Tree Style Tab: 4.0.141

**Comment by piroor** [comment]
The feature won't be added as a built-in due to TST's project policy.
https://github.com/piroor/treestyletab?tab=readme-ov-file#basic-project-policy

Please see also some FAQ topics:
https://github.com/piroor/treestyletab#user-content-feature-requests-high-power-management-of-tree-like-sorting-child-tabs-auto-modification-of-tree-renaming-tabs-and-so-on
https://github.com/piroor/treestyletab#user-content-feature-requests-add-more-minor-trivial-options

**Comment by irvinm** [comment]
@bossanovaorca there are several addons that have different discarding methods that integrate directly into the TST right-click menu.  I personally use 2 of them:  "Auto Tab Discard" and "Tab Unloader".  Most also have some keyboard shortcuts as well.

![image](https://github.com/piroor/treestyletab/assets/979729/a3a6a1c0-e45b-4c43-836f-397c5fcc3a6a)

**Comment by lemeurherve** [comment]
@irvinm I'm curious, what's the added value of "Tab Unloader" when "Auto Tab Discard" is already installed?

**Comment by irvinm** [comment]
Great question ... the answer is in the history of Auto Tab Discard. For a short time, they had broken integration with TST and dropped support of discarding a tree ... both of which is working today.  This is where Tab Unloader filled the gap for me during that time.  

In addition, ATD also supports discarding loaded tabs over time and some other advanced options.  However, as of today, they both work well and is probably more of a preference of what you want.  (They both seem to support:  Discarding tab, Discarding trees, Keyboard shortcuts.  I think the only requirement difference for me is the "auto" portion of ATD which I do use).

**Comment by bossanovaorca** [comment]
ok @piroor I understand, and thank you for the suggestions @irvinm !

**Comment by Chealer** [comment]
Please specify the first version which implements the new feature.
