### ISSUE TITLE
[Bug] tab appearance in incognito tabs seems broken

### ISSUE THREAD

**Issue by shadoxxhd** [piroor/treestyletab#3547]
## Abstract
In incognito windows, many tabs take up multiple "lines" in the vertical view:
![image](https://github.com/piroor/treestyletab/assets/6153557/c0917095-73e0-42dc-9d8f-565b92aca2e5)
Also, the order icon/title/X is effectively reversed for the "single line" entries.

In normal windows, the tab list looks like it should (normal proton style without customizations)

## Steps to reproduce

I updated the extension, and suddenly the formatting was broken.
Disabling and re-enabling the extension and giving the TST addons access to private windows (or revoking it) didn't change the issue.
I don't have any environments to recreate the issue right now.

## Expected result
Private window tabs look like normal tabs.

## Actual result
They don't (see screenshot above).

## Environment

 * Platform (OS): Win10
 * Version of Firefox: 120.0
 * Version (or revision) of Tree Style Tab: 4.0.14

**Comment by shadoxxhd** [comment]
Other themes have similar issues.

**Comment by piroor** [comment]
Could you post "expected" case screenshot too? TST's appearance is affected from various reasons - language, platform color scheme, and so on, so I don't know what is exact expected case on your environment.

**Comment by shadoxxhd** [comment]
![image](https://github.com/piroor/treestyletab/assets/6153557/4a7ea970-f40e-49ae-9432-4fb73437570b)
"expected" demonstration (different sites, but same configuration, apart from column width).

Interestingly, after I killed the GPU process for RAM recovery reasons, the problem fixed itself - private tabs look like normal for me now. Since this might have been a random, transient, inherently unreplicable issue (flipped bit in memory perhaps?), I'll close the issue for now.

**Comment by maltfield** [comment]
Hi, was this bug actually fixed? I don't see any comments indicating that it was. All I see is that, after the user submitted clarification, this got closed.

I also am experiencing this issue after upgrading to:

 * Firefox ESR 115.15.0esr
 * Tree Style Tab 4.0.23

**Comment by maltfield** [comment]
Update: I upgraded Firefox again (this time to `Firefox ESR 128.3esr`), and the issue went away.
