### ISSUE TITLE
[Enhancement] Review terminology used in locales

### ISSUE THREAD

**Issue by vadcx** [piroor/treestyletab#3550]
The title is grandiose, the only thing on my radar after #3549 is to only change **"Addon" -> "Extension"** in wording everywhere. Maybe more words will come up after a thorough review.

If this is OK with you, piroor, I could do it some time later for English. I think to have mostly finished this myself for Russian, and German was using the word for "extension" too already.

**Comment by vadcx** [comment]
Forgot to add this:

config_bookmarkTreeFolderName_description -> DATE, two digits: The German translation described this as "Day, two digits" rather than "date". What is it actually?

**Comment by piroor** [comment]
Sorry I missed this issue. I've replace the term "addon" to "extension" except some special cases with the commit 49c8afe.
