### ISSUE TITLE
[Bug] Cannot scroll the sidebar with latest nightlies

### ISSUE THREAD

**Issue by cg9999** [piroor/treestyletab#3554]
Using the latest nightlies of FF, it is impossible to scroll the sidebar with mouse wheel.
I used mozregression to find the cause:

https://bugzilla.mozilla.org/show_bug.cgi?id=1888737

```
Bug 1888737 - Disable overflow/underflow events in early beta r=smaug,emilio

Differential Revision: https://phabricator.services.mozilla.com/D206175

2024-05-18T09:51:44.935000: DEBUG : Did not find a branch, checking all integration branches
2024-05-18T09:51:44.937000: INFO : The bisection is done.
2024-05-18T09:51:44.938000: INFO : Stopped
```

Is this a TST or FF issue?

FF 128.0a1 (2024-05-17) (64-bit) running on Arch Linux/KDE
tree_style_tab-4.0.14

update:
seems to be an issue of TST relying on an api that's being removed
https://bugzilla.mozilla.org/show_bug.cgi?id=1688022

Separate FF bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1897595

**Comment by piroor** [comment]
I really need something method to run callback functions when the overflow state of a element (or the document) is changed. Is there any alternative way in the Web standard technologies?

**Comment by piroor** [comment]
Workaround: setting `layout.overflow-underflow.content.enabled` to `true` via `about:config`.

**Comment by piroor** [comment]
OK, I've found the way. With the commit 58f7f7c TST should work without overflow/underflow events.

**Comment by cg9999** [comment]
Thanks for quick fix!

**Comment by diox** [comment]
FYI 4.0.15 is now live on [AMO](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/) with that fix.

**Comment by piroor** [comment]
There are some performance regressions like #3557 but currently I have no fundamental solution...
