### ISSUE TITLE
[Enhancement]  Prevent Automatic Collapse/Expand to keep all tab depths/tab titles in view 

### ISSUE THREAD

**Issue by gituser823** [piroor/treestyletab#3555]
## Abstract

I want to be able to only manually collapse trees, not have it done automatically.
The same as issue #1142 

## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Click on another collapsed tree. The current expanded tree will be collapsed
 4. 

```
A
\- B (collapsed)
C
\- D
\- E (selected)
```

## Expected result

only collapse on manual collapsing

## Actual (present) result

```
A
\- B (selected)
\- B-1
C (collapsed)
```

## Environment

 * Platform (OS): Linux Mint
 * Version of Firefox: 126.0
 * Version (or revision) of Tree Style Tab: 4.0.14

**Comment by irvinm** [comment]
![image](https://github.com/piroor/treestyletab/assets/979729/8fc2a906-c7cc-415b-8ec8-b6e5c241a79a)

**Comment by gituser823** [comment]
That option doesnt exist in my version:

![Selection_024](https://github.com/piroor/treestyletab/assets/32219087/8752c542-1f5e-4d48-97b9-54b999e64814)

**Comment by irvinm** [comment]
Ah ... enable expert options:

![image](https://github.com/piroor/treestyletab/assets/979729/22a0041e-b6c8-4bfe-ae61-a08586738b0d)

**Comment by gituser823** [comment]
Now it works, thanks!

But one more question:
When I now click on a collapsed tree it does not automatically expand.
Can I set up that it does, but just does not automatically collapse trees?

**Comment by piroor** [comment]
Sadly there is no such exact option, so you need to create a new helper addon.

The default auto-collapsing/expansion behavior respects expanded state of trees if they are expanded manually via clicking on the twisty (chevron). Manually expanded trees won't be collapsed automatically when you click a collapsed another parent.
