### ISSUE TITLE
[Bug] Tab titles don't resize with sidebar after nightly 2024-05-28 22:22:16.612000

### ISSUE THREAD

**Issue by DimitryAndric** [piroor/treestyletab#3562]
## Abstract

After Nightly 2024-05-28 22:22:16.612000 (on Windows, might also be other platforms), and with TST 4.0.15, the TST tabs in the side bar no longer 'resize' with the side bar. The tabs are always the same length now, and the 'x' button gets cut off on the right side.

Before: 
![tst-before](https://github.com/piroor/treestyletab/assets/9060368/0b0be510-69a2-492a-aa62-061939393f1e)

After:
![tst-after](https://github.com/piroor/treestyletab/assets/9060368/5caba8a2-4f98-453b-a468-ce88bb6189a5)

Using mozregression shows that this regressed due to https://bugzilla.mozilla.org/show_bug.cgi?id=1898705, with https://hg.mozilla.org/mozilla-central/rev/ebf68f67ccc8

## Steps to reproduce

* Install nightly build after 2024-05-28 22:22:16
* Make fresh profile
* Install TST
* Observe cut-off tabs in side bar
* Resize side bar to see TST tabs not resizing

## Expected result

As in ![tst-before]

## Actual result

As in ![tst-after]

## Environment

 * Platform (OS): Windows 10 x64, but I assume other OSes will also be impacted.
 * Version of Firefox: Nightly build 2024-05-28 22:22:16.612000
 * Version (or revision) of Tree Style Tab: 4.0.15

**Comment by DimitryAndric** [comment]
Related bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1899561 ("webextension's sidebar has viewport width that is widely than the sidebar width"), which mentions TST, so maybe this will get fixed by Mozilla upstream?

**Comment by piroor** [comment]
It looks to be fixed soon by Firefox side. I do nothing at TST side.

**Comment by TheWoodsy** [comment]
Fixed in new windows nightly 

> 128.0a1 (2024-05-30) (64-bit)
