### ISSUE TITLE
[Enhancement] Don't load unloaded tabs on drag drop of tree

### ISSUE THREAD

**Issue by Tragen** [piroor/treestyletab#3565]
## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Create a tree with 2+ tabs
 4. Restart FF
 5. Drag the root tab of the tree to a new window

## Expected result

The root tab gets activated and loaded and the tree is moved as is to the new window.

## Actual (present) result

All tabs get loaded.
I have some websites which uses rate limiting. Moving such a tree causes the site to not load anymore.
E.g. Wordpress has a ninjafirewall plugin.

## Environment

 * Platform (OS):  Windows 11
 * Version of Firefox: 126.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab: 4.0.15

**Comment by irvinm** [comment]
https://addons.mozilla.org/en-US/firefox/addon/move-unloaded-tabs-for-tst/

**Comment by Tragen** [comment]
This addon doesn't work properly.
I've moved a tree from one window to the other. Perfect.
But moving it back loaded all tabs like without the addon.

**Comment by piroor** [comment]
After detailed investigation I've realized that `browser.tabs.move()` unexpectedly restores moved discarded tabs on certain cases. I've introduced a change to avoid such unexpected restoration: 720666d

**Comment by Tragen** [comment]
Wow, thank you! 👍😁😊

**Comment by Tragen** [comment]
One question, does this fix mean I don't need https://addons.mozilla.org/en-US/firefox/addon/move-unloaded-tabs-for-tst/ anymore or is this addon still needed?

**Comment by piroor** [comment]
You still need the addon https://addons.mozilla.org/en-US/firefox/addon/move-unloaded-tabs-for-tst/ if you don't want an unloaded tab become loaded when you *start dragging on it*. My fix just affects only for tabs moved across windows.

* When you press *down* your mouse button on an unloaded tab, TST activates it and the tab become loaded, *before you release the button*.
  * This causes unexpected loading of a pending tab even if you just move the tab by drag and drop.
    * https://addons.mozilla.org/en-US/firefox/addon/move-unloaded-tabs-for-tst/ blocks loading of this situation.
    * The reason why I don't apply this behavior by default is: this "fix" affects to cases you just want to activate a clicked tab also. In other words, if I introduce this fix as a built-in, you'll see delayed response for tab activation actions: "the clicked tab is activated *before* you release the mouse button" will become "the clicked tab is activated *after* you release the mouse button".
* When you select multiple tabs (by Ctrl-click or Shift-click) and drag-and-drop them to outside of the source window, TST opens a new window and move all dragged tabs to the new window, and it also loaded those tabs unexpectedly in old versions.
  * My fix affects to this case. TST 4.0.16 and later won't load dragged tabs except the active tab, on this case.

**Comment by Tragen** [comment]
So I don't need this addon if I don't care about the tree "root" I want to drag and drop to become active.
As long as the rest of the tree is still unloaded, that's okay for me. I have trees with 30 to 80 tabs and one less addon is okay for me if only one tab gets loaded.
Thanks for TST and your fixes.
