### ISSUE TITLE
Please add a true tree functionality sorted by domain

### ISSUE THREAD

**Issue by lastmetroid** [piroor/treestyletab#3568]
Honestly I dont understand how this addon works or whats the logic behind the sorting. I was looking for a tree tab functionality, but this addon seems to randomly sort or actually sort nothing at all.

Can you please implement a true tree function, which sorts by domain name.

**Comment by piroor** [comment]
It won't be implemented as a built-in feature. Here is a FAQ topic about it:
https://github.com/piroor/treestyletab#user-content-feature-requests-high-power-management-of-tree-like-sorting-child-tabs-auto-modification-of-tree-renaming-tabs-and-so-on

**Comment by lastmetroid** [comment]
So where is that """3rd party helper""" addon providing this simple sorting I dont see it. Without a proper sorting this """tree""" is useless.

**Comment by piroor** [comment]
Sorry I'm not familiar about addons to sort tabs because I don't use such kind addons for now. You may need to implement it by yourself if no such existing addon.

**Comment by lastmetroid** [comment]
You dont think, a sorted tab functionality is the most important aspect of an addon like this? If you have for example 100 tabs, or even just 50, you want to easil have them be sorted into a tree, where the tree is sorted by each domain and you can open it for example for amazon.com show all tabs for this domain, and with one click, close all tabs with amazon.com domain.

**Comment by piroor** [comment]
I think: sorting of tabs should not be limited to cases only with tree. Instead purpose-oriented addon providing ability to sort tabs should do that. I'm welcome to make TST compatible to such an addon, but I'm still negative to bloat TST with various features not strongly depending on tree of tabs. This is important policy of this project to keep it long-live.
https://github.com/piroor/treestyletab/blob/trunk/README.md#basic-project-policy
