### ISSUE TITLE
[Bug] "Allow to open a new tab with the URL in the clipboard, by middle click on the "New Tab" button" not working

### ISSUE THREAD

**Issue by karasuhebi** [piroor/treestyletab#3569]
## Abstract
The option "Allow to open a new tab with the URL in the clipboard, by middle click on the "New Tab" button" is not working.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Give TST the permission to read your clipboard
 4. Enable dom.events.asyncClipboard.clipboardItem 
 5. Copy a URL into your clipboard
 6. Middle click the + button at the bottom of TST
 7. Nothing happens.

## Expected result

The URL in my clipboard should open.

## Actual result

Nothing happens

## Environment

 * Platform (OS): Windows 10 Version 22H2
 * Version of Firefox: 126.0.1
 * Version (or revision) of Tree Style Tab: 4.0.15

**Comment by piroor** [comment]
Did you turn these checkboxes on?
![image](https://github.com/piroor/treestyletab/assets/70062/fc0d9836-e5d9-4b06-b30f-4efef61f513f)
"Open new tab with URL in the clipboard" is checked by default only on Linux (because "browser.tabs.searchclopboard.middleclick" is also active by default only on Linux) and you need to activate it manually on other platforms.

**Comment by karasuhebi** [comment]
I did, yeah. Still doesn't work. :(

**Comment by piroor** [comment]
I got what happened. The checkbox become checked even if its internal option is still disabled, when you grant the clipboard permission by the "Permissions" tab provided by Firefox. You need to uncheck the "Open new tab with URL in the clipboard" checkbox and check it again for now, to activate the internal option.

I've pushed a change 3d9d79b to fix this "mismatched checkbox state" bug.

**Comment by karasuhebi** [comment]
That worked! Thanks!
