### ISSUE TITLE
Incorrect placement of the TreeTab by the restoration of the session

### ISSUE THREAD

**Issue by dlnsk** [piroor/treestyletab#357]
My default placement of the TreeTab on right
When I start browser with saved tabs (I have SessionManager extention), on right side I see gray empty place, but Tabs are on the left above the surface of the page.
Picture: http://vfl.ru/fotos/2425c21a909655.html

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
