### ISSUE TITLE
[Bug] New tab from application opens with "forbidden-url" URL

### ISSUE THREAD

**Issue by kephas** [piroor/treestyletab#3571]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Go the TST preferences
 4. In Non-blank new tabs/New tab from Other Application/Container, select `Inherit from the current tab`
 5. Open a new tab with some container
 6. Create an HTML file `/foo/bar`
 7. From the command-line, do `xdg-open /foo/bar`

## Expected result

A new tab opens, with the same container as the last focused tab, with URL `file:///foo/bar`

(you get this result if in step 4, you select `(no control)`

## Actual result

A new tab opens, with the same container as the last focused tab, with URL `about:blank?forbidden-url=file:///foo/bar`

## Environment

 * Platform (OS): Linux Debian
 * Version of Firefox: 115.11.0esr
 * Version (or revision) of Tree Style Tab: 4.0.15

**Comment by piroor** [comment]
It is due to a restriction of WebExtensions API - we cannot reopen tab with specific container if it has special URL.

**Comment by piroor** [comment]
Did you turn the checkbox "Reopen tab with inherited container anyway, even if it has a URL unable to open by addon's permission" on? It is off by default and recommended to prevent opening such `about:blank?forbidden-url=` tabs from cases like this.

**Comment by kephas** [comment]
It was checked on my setup and this removes this behaviour, thanks!
