### ISSUE TITLE
[Bug] (Unloaded tabs unable to be accessed via Hotkey navigation)

### ISSUE THREAD

**Issue by SHHSSH** [piroor/treestyletab#3573]
Unloaded, Locked as Collapsed Trees that are unloaded via Tab Unloader for Tree Style Tab by [Lej77](https://addons.mozilla.org/en-US/firefox/user/13464160/?utm_source=firefox-browser&utm_medium=firefox-browser&utm_content=addons-manager-user-profile-link) are unable to be accessed via Hotkey/Macro navigation as they are ignored when collapsed.

Locked as Collapsed Tab Trees are able to be accessed/navigated to via Ctrl+Shift+Tab when they are Locked as Collapsed.
However, when they are unloaded you cannot navigate via Macros/Hotkeys to them.
This is inconvenient as it forces the user to manually move the mouse over the tab for focus/navigation to.

@piroor is there a solution for this I am missing? Perhaps it's apart of a setting, though the setting - Don't expand collapsed tree and skip collapsed descendants is not modifying the behaviour unfortunately.

Additional clarification and explanation of the issue;
I would like to be able to Ctrl+Shift+Tab to an Unloaded, Locked as Collapsed Tree in TST.
The functionality works if the parent tab **_is not_** discarded/unloaded.
If the parent tab **_is_** discarded/unloaded it does _not_ allow the navigation.

Thank you for any help you may provide.

**Comment by SHHSSH** [comment]
I found a work around for this, to disable the unloading capability of a "Folder" in my TST Tree as the parent and that allows for the navigation to its tree. This allows for a minimal RAM usage as they're only folders and not active internet tabs.

I don't want to burden you with more issues @piroor 
Thank you for all you do.

**Comment by piroor** [comment]
Did you activated the option?: TST options => (Unlock Expert Options) => "Tree Behavior" => "Avoid pending (unloaded) tabs to be activated accidentally on current tab closes or tree collapsing" Such a skipping may happen with the option checked.

**Comment by SHHSSH** [comment]
> Did you activated the option?: TST options => (Unlock Expert Options) => "Tree Behavior" => "Avoid pending (unloaded) tabs to be activated accidentally on current tab closes or tree collapsing" Such a skipping may happen with the option checked.

Yep, that is and was ticked.
Don't worry mate, I guess a "Folder" as the Parent tab is suitable anyway.
![capture_068_11062024_221500](https://github.com/piroor/treestyletab/assets/21285581/029c810e-b91e-4a7a-91b0-9bf000c37a86)
