### ISSUE TITLE
[Bug] set-extra-contents to new-tab-button doesn't seem to respect window parameter

### ISSUE THREAD

**Issue by rixx** [piroor/treestyletab#3578]
## Abstract

I'm trying to put the number of tabs in the current window into the "new tab" button. However, all windows end up displaying the number of tabs in the last given window.

## Steps to reproduce

You can see my code [here](https://github.com/rixx/tst-tab-count/blob/e90b645d11a9d59b8d3b0f64d57b4ffa34f27847/tabCount.js#L72). I'm sending a message like this:

```json
{
    "messages": [
        {
            "type": "set-extra-contents",
            "place": "new-tab-button",
            "contents": "85 tabs",
            "windowId": 1
        },
        {
            "type": "set-extra-contents",
            "place": "new-tab-button",
            "contents": "4 tabs",
            "windowId": 10202
        }
    ]
}
```

However, both "new tab" buttons end up showing the latter message. I've verified that this happens if I send the messages individually instead of in an array, aswell.

Is this a limitation of Firefox or a bug in TST? It looks to me like [setExtraNewTabButtonContents](https://github.com/piroor/treestyletab/blob/4d3e1994904501a650de07df26cb008aaa6a02e9/webextensions/sidebar/tst-api-frontend.js#L633) isn't attempting to read the passed `windowID`. I understood the [documentation](https://github.com/piroor/treestyletab/wiki/Extra-Tab-Contents-API#how-to-insert-extra-contents) to say that passing a `windowID` is allowed, is this not correct?

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 127.0a1
 * Version (or revision) of Tree Style Tab: 4.0.17

**Comment by piroor** [comment]
Did you try this?:

```javascript
{
    "messages": [
        {
            "type": "set-extra-contents",
            "place": "new-tab-button",
            "contents": "85 tabs",
            "windowId": 1  // <== windowI*d*, not windowI*D*
        },
        {
            "type": "set-extra-contents",
            "place": "new-tab-button",
            "contents": "4 tabs",
            "windowId": 10202  // <== windowI*d*, not windowI*D*
        }
    ]
}
```

**Comment by rixx** [comment]
@piroor  Oh, yeah, sorry, I'll edit my original post – I tried both spellings and forgot to update that. 

You can try this for yourself by running:

```js
browser.runtime.sendMessage('treestyletab@piro.sakura.ne.jp', {type: 'set-extra-contents', place: 'new-tab-button', contents: 'appearing on all button instances', windowId: 1})
```

**Comment by piroor** [comment]
Thanks, I forgot to check the target window ID...
