### ISSUE TITLE
[Bug] Option to deactivate "Tabs from..." tab is not linked to properly

### ISSUE THREAD

**Issue by cclypeatus** [piroor/treestyletab#3582]
## Abstract

When multiple tabs are opened via a pinned tab's links and a "Tabs from..." tab opens, the `There is an option to deactivate opening of this type tab.` button given doesn't link to the option to deactivate opening said tab.

## Steps to reproduce

1. Make sure TST is active, and the `Auto-group tabs opened from same pinned tab` option should be toggled on
2. Open tab with one or more links
3. Pin said tab
4. Open link to a new tab, at least twice
5. Switch to "Tabs from..." tab when it appears
6. Click `There is an option to deactivate opening of this type tab.` on the top right

## Expected result

The options page is opened to the option that would deactivate opening of "Tabs from..." tabs. Simplest fix is to point to `#autoGroupNewTabsFromPinned` instead of `#autoGroupNewTabsSection`. Ideally open this in the same tab, not a new one; anyone doing step 6 probably means to deactivate it. 

## Actual result

The options page is opened on a new tab, with a box shadow on a fieldset that doesn't control deactivating the "Tabs from..." tab. You have to scroll up to see the correct fieldset; the section containing this fieldset is (thankfully) already open.

(This is not how I figured out how to toggle it off though. Instead, I right-clicked the toolbar button and noticed `Tabs opened from Existing Tabs` > `Auto-group tabs opened from the same pinned tab` was toggled on.)

## Environment

 * Platform (OS): Ubuntu
 * Version of Firefox: 126.0.1
 * Version (or revision) of Tree Style Tab: 4.0.18

## Addendum

It may be helpful to give a proper name to a "Tabs from..." tab and have that be in the title of said tab so it is obvious. e.g. the tab can be titled `Summary of Tabs from <tab title>` and the option can say `Open a Summary tab grouping tabs opened from the same pinned tab`.

If possible, it would be better to also provide the deactivate option on the "Tabs from..." tab directly.

**Comment by piroor** [comment]
Thanks, I forgot to do that when I separate sections for each cases.
