### ISSUE TITLE
[Bug] Tabs not going to folder dragged into

### ISSUE THREAD

**Issue by NefariousFerris** [piroor/treestyletab#3585]
Hello, thank you for your help last time with the folder/groups and tabs hierarchy getting broken when dragging occasionally.

Now there is a new issue where I am having weird issues when trying to drag tabs into groups .

1) Sometimes if I drag tabs to a group that is collapsed, sometimes the tabs that were already in that folder end up in the group below that group .
2) Sometimes when When dragging tabs to the group it does not end up in the group and goes elsewhere (video attached) 

https://github.com/piroor/treestyletab/assets/73053278/ee4b16dc-45aa-4896-a64a-ee17c2d1151d

**Comment by NefariousFerris** [comment]
I think it works better if I drag to under the folder/group tab, but then the tabs end up out of order and not in the order I dragged it in 
![image](https://github.com/piroor/treestyletab/assets/73053278/217eea9a-48b0-49be-9d62-4ce49521b400)

**Comment by piroor** [comment]
Please don't remove the issue template and fill that with details: steps to reproduce from scratch (including settings of TST). Issues on this tracker need to have full information for each, because I frequently forget its context if it is created from related another issue.
