### ISSUE TITLE
[Bug] TST is causing all panels of the Firefox Sidebar to have accessible name of "Tree Style Tab"

### ISSUE THREAD

**Issue by anna-yeddi** [piroor/treestyletab#3586]
## Abstract
TST is causing all panels of the Firefox Sidebar to have accessible name of "Tree Style Tab" - it looks like the extension is overwriting the [label of the sidebar's toolbarbutton](https://searchfox.org/mozilla-central/rev/3d173a6ad865eb778eb7a85de900e92774559ed6/browser/base/content/browser-box.inc.xhtml#16) and it is not allowing any further changes to happen when other views of the sidebar are opened.

This is a high severity accessibility issue because it would prevent users of assistive technologies from identifying currently opened sidebar view, unless they review the content (they'd need to guess, especially, if a screen reader user has cognitive disability and rely on a screen reader to understand the content). Also, users of speech-to-text software like Voice Control would have to use a workaround to activate the view toggle, because calling its on-screen name would not work.

## Steps to reproduce

1. Start Firefox with clean profile.
1. Install TST.
1. Have a Fx sidebar opened, i.e. with `ctrl/cmd+B` open a Bookmarks sidebar and change to `Tree Style Tabs` 
1. In the sidebar, select the `History` view (or any other)
1. Confirm the sidebar view is updated and its visual title is changed to `History`
1. Using a screen reader, navigate to and observe the announcement of the `History` control at the top of the sidebar.
    1. Alternatively, open a browser developer tools > Accessibility > and select the sidebar's title button via the `Pick accessible object from the page`

## Expected result

1. The on-screen name of the sidebar is serving as an accessible name of the button and is announced as `History` (which would be the `name` field value in the A11y dev tools)

## Actual result

1. The on-screen name of the sidebar is updated to `History` but the accessible name of the button remains as the previous sidebar view, i.e. `Tree Style Tabs` (which is also the `name` field value in the A11y dev tools)
View from the Firefox browser Dev Tools > Accessibility is attached.
![Button with on-screen text AI Chatbot has accessible name Tree Style Tab in the Accessibility tree](https://github.com/piroor/treestyletab/assets/40773610/898045b7-b824-432a-869d-37b1b9818cb3)

## Environment

 * Platform (OS): macOS (with VoiceOver screen reader) and Windows (with NVDA screen reader) [Fx bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1905771)
 * Version of Firefox:  Nightly 129.0a1 (2024-07-01)
 * Version (or revision) of Tree Style Tab: 4.0.19

**Comment by piroor** [comment]
This looks to be a bug of Firefox itself. We can see same problem with other sidebar addons, like Sidebery. Please file a bug at bugzilla.mozilla.org instead here.

**Comment by anna-yeddi** [comment]
> Please file a bug at bugzilla.mozilla.org instead here.

It's linked in the issue too.

Thank you for your investigation. I'll add it to the Bugzilla ticket for further investigations :)

**Comment by piroor** [comment]
Oh, sorry I missed the link...

**Comment by piroor** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1905771 is now fixed.
