### ISSUE TITLE
[Bug] TST has made it unusably slow to open new tabs

### ISSUE THREAD

**Issue by cdavie-artium** [piroor/treestyletab#3591]
## Steps to reproduce

1. Have a bunch of tabs open and/or unloaded _[Note: I'm not sure whether the number of tabs is actually relevant.]_
2. Open a new tab.

## Expected result

A new tab should open immediately.

## Actual result

A new tab takes a long time to open (5-30 seconds!)

Disabling the TST extension fixes the issue; tabs open immediately again.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 129.0b2, developer edition
 * Version (or revision) of Tree Style Tab: 4.0.20

**Comment by piroor** [comment]
More information helpful for debugging is required. For example:

* Does this depend on the number of tabs in a window?
* Does this depend on the total number of all tabs across all windows?
* Is there any hidden tab?

And [performance profile](https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-collect-a-performance-profile) may also help debugging.

**Comment by cdavie-artium** [comment]
I'm about to leave for vacation, so I'll have to respond to most of these
questions when I get back.

I can say that there are LOTS of tabs that are hidden & unloaded, though!
