### ISSUE TITLE
[Bug] Opening tab in new window works, but the sidebar (with TST) is closed instead of open. Have to open it manually. 

### ISSUE THREAD

**Issue by StudioNirin** [piroor/treestyletab#3594]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a tab
 4. Right-click, open in new window
 5. New window will open, but TST sidebar is closed. 

## Expected result

Sidebar with TST should be open by default in the new window. 

## Actual result

It isn't open by default.

## Environment

 * Platform (OS): Windows 11
 * Version of Firefox: 128
 * Version (or revision) of Tree Style Tab: 4.0.20

**Comment by piroor** [comment]
Sadly it is a problem of FIrefox itself. TST and any other WebExtensions API based addons cannot control initial state of the sidebar for new windows.

**Comment by irvinm** [comment]
@piroor we should probably close this one.  There is not likely to ever be any changes with regards to this.

**Comment by piroor** [comment]
I've researched again to consider possibility to implement the feature "controlling visibility of TST sidebar for newly opened windows", and finally I realized that it is sadly impossible. The API to open sidebar is not callable except handlers for the toolbar button or keyboard shortcuts.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sidebarAction/open
The restriction is clearly designed behavior, so I think it won't be loosen. I hope to keep this issues tracker as the place to track unresolved problems possible resolved, so I close this for now.

**Comment by MithicSpirit** [comment]
Is there an upstream issue for showing the sidebar automatically on new windows?

**Comment by piroor** [comment]
There are two possible way to do "show TST sidebar in newly opened window", and they have different blockers.

Idea 1:

1. Call [`windows.create()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/create) with an option to specify the initial sidebar contents.
2. But there is no such option to do that. We cannot open a new window with opened sidebar.

Idea 2:

1. Call [`windows.create()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/create).
2. Call [`sidebarAction.open()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sidebarAction/open) to open the sidebar in the window.
3. But the operation is not allowed. We cannot open TST sidebar for a newly opened window. As described at the API document, this kind operation is intentionally restricted.

**Comment by MithicSpirit** [comment]
Seems to be fixed now.

**Comment by piroor** [comment]
Firefox saves the last sidebar state when the last browser window is closed. 
https://searchfox.org/mozilla-central/rev/e6733c6143dc6a1bd32c9c65d685528deb1ba895/browser/components/sidebar/browser-sidebar.js#440-449
If you see a new browser window with closed sidebar, I recommend you to try closing the last browser window with opened sidebar and restart Firefox.
