### ISSUE TITLE
[Bug] group-tab.html & --column-width inconsistencies

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#3595]
## Abstract
Since https://github.com/piroor/treestyletab/issues/2607#issuecomment-643746408, this has generally worked well and group-tab.html pages with only 1 column was displayed with full width while multi-column were set to the value specified via --column-width.  (No issues once multi-column kicks in)

However, in recent weeks\months, I am seeing group-tab.html examples with only one column that are being clipped to the --column-width value while they don't need to be.  

## Relevant CSS Used:
`:root.group-tab { --column-width: 30em; }`

## Example 1 - Working Fine
![image](https://github.com/user-attachments/assets/1f99a317-c403-4a7b-ab09-fdfc1caed9ec)

![image](https://github.com/user-attachments/assets/cfb5fb82-52a1-490f-a891-3211f359beed)

## Example 2 - Not Working
![image](https://github.com/user-attachments/assets/5c3c2c44-86d5-42d8-a1ec-b04923dbab63)

![image](https://github.com/user-attachments/assets/5d81f003-53ca-44e8-98e0-72450e12b85d)

## Example 3 - Not Working
![image](https://github.com/user-attachments/assets/8b50c522-72a3-4751-8e08-340f646d8999)

![image](https://github.com/user-attachments/assets/0a1ebe57-d824-4f0b-8f27-e05952646d71)

## Example 4 - Working Fine
![image](https://github.com/user-attachments/assets/d2eda122-6ab5-49f7-83b5-2543b7624049)

![image](https://github.com/user-attachments/assets/54d2a8e7-5113-4209-bf31-ff0327c8c3ad)

## Steps to reproduce

I'm still working on a more basic reproducible scenario, but wanted to see if you had any early thoughts.

## Expected result

- Single column list should use the the full width
- Multi column list should use width specified by --column-width if it exists

## Actual result
- Single column is sometimes being clipped to --column-width
- Multi column is working fine

## Environment

 * Platform (OS): Windows 11 23H2
 * Version of Firefox: v128
 * Version (or revision) of Tree Style Tab: 4.0.20

**Comment by piroor** [comment]
Is the user style sheet is applied on the failure case? Could you see the right pane in the DOM inspector?
![image](https://github.com/user-attachments/assets/37734306-17ad-4aa0-922c-9056e25ac641)
On my case the style rule is applied to the root `html` element as this screenshot. If your style sheet is not applied on the failure case, something error may block the initialization process of the group tab page. Otherwise Firefox's CSS rendering system may cancels the value your specified by some reason.

**Comment by irvinm** [comment]
@piroor the failure is that the `--column-width: 30em;` *IS* being applied when it should not.

It looks to me that the Javascript around this should leave out the `column-width:` style when it is determined to be a single column, but then applies the `column-width: calc(var(--column-width, 20em));` to restrict the column width to either `--column-width` if user defined or `20em` by default if multi-column.  In both working and non-working examples, it looks like `--column-width` is properly defined.

## Not working - Single column being trimmed
![image](https://github.com/user-attachments/assets/a6b03877-3de6-4fd2-ae7d-2ab8880e0e9b)

## Working - Single column not being trimmed
![image](https://github.com/user-attachments/assets/18fba6d6-dbc5-42d2-9be5-88611d1456ed)

**Comment by piroor** [comment]
I've realized that I missed labels are cropped in your screenshots. Long labels are not cropped and shown fully with line-breaks by default. These differences may affect to this problem. Do you use more other style rules?

**Comment by irvinm** [comment]
My CSS is related ... (Sigh, I am sorry about that).  

I removed everything and it worked.  I then added back all group-tab and some other items until I was able to reproduce.  I then started removing items until it went away and was left with this.

```
:root.group-tab { --column-width: 30em; }

:root.group-tab li {
	overflow: clip;
	width: unset;
}

#tabs span.link span.label {
	white-space: nowrap;
	overflow: clip;
	width: 100%;
	text-overflow: ellipsis;
}
```

I had forgot that I had wanted each URL on the group-tabs page to be single line in nature (felt that was sufficient to understanding the destination) which involved changing some items around white-space and overflow.

Without the "li" CSS, the multi-column URLs don't get clipped properly to stay within the column.  Without the span.label items, individual line items on the group-tab page aren't restricted to 1 line.

However, with both I see that single column pages sometimes work, but sometimes don't.  (Per previous screenshots)

In either case, this isn't a TST problem and hence closing.  I will investigate further on my end.  If anything jumps out at you, I would appreciate any feedback.

**Comment by irvinm** [comment]
Using just the CSS from above and inspecting group-tab examples of working and not working, I think I see why this CSS behaves differently.

In cases that are working, the UL does not have a "column-width" style applied to it.  Any LI items under it that are clipped should just be clipped to the parent UL which is not restricted.

![image](https://github.com/user-attachments/assets/518ea0bb-9983-4e05-af33-573576c82c65)

In cases that are failing, the UL has ... `style="column-width: calc(var(--column-width, 20em));` ... which means LI items under that will be clipped to the size of the UL which in this case is the 30em.

![image](https://github.com/user-attachments/assets/be8b3f0b-5f5a-4930-93f8-e07e82b53b05)

Since TST is applying that style, is it possible that TST isn't applying the style properly?  Maybe I could try to step thru the code that applies the `column-width: calc(var(--column-width, 20em));`.

**Comment by irvinm** [comment]
Ok, I have a reproducible scenario:

- Install Firefox 128.0.2 (Windows)
- Install TST 4.0.20
- Insert the following CSS into TST

```
:root.group-tab { --column-width: 30em; } 

:root.group-tab li {
	overflow: clip;
  	white-space: nowrap;
	width: unset;
}

#tabs span.link span.label {
	white-space: nowrap;
  	overflow: clip;
  	width: unset;
}
```

- Create a group tab
- Open new child tab and open:  https://www.tomshardware.com/pc-components/hdds/toshiba-x300-pro-20tb-12tb-hdd-review/2
- See that the column is being truncated to 30em.  (Remove the --column-width CSS and it will truncate to 20em)
- ![image](https://github.com/user-attachments/assets/75ef1210-3a51-4ccb-b2b6-ba80eaf3a250)
- Open a different group tab
- Open new child tab and open: https://www.tomshardware.com/reviews/gpu-hierarchy,4388-2.html
- See that the column is not being truncated.
- ![image](https://github.com/user-attachments/assets/783924b6-9436-4de9-9d45-85af99227b0b)

In both cases, it is the desired result that single-column rendering should not have the column-width applied.  I am not sure why in this case one of the tabs works and the other does not.  I am guessing there is something about the metadata and\or metadata length.

I did start stepping thru the code and see that everything is being handled and applied here in the code blocks below.  I will continue to investigate when I have time.
https://github.com/piroor/treestyletab/blob/aeb6cad892fc167fe2c150a60e3a9cc271e45318/webextensions/resources/group-tab.js#L503-L509

https://github.com/piroor/treestyletab/blob/aeb6cad892fc167fe2c150a60e3a9cc271e45318/webextensions/resources/group-tab.js#L585-L615

**Comment by irvinm** [comment]
Another example site:  https://wallpaperswide.com/

## Group tab that includes this site (clipped rows)
![image](https://github.com/user-attachments/assets/c787c21e-3472-4fb0-8e0d-35a28434a25c)

## Group tab by simply moving the tab outside (proper rows)
![image](https://github.com/user-attachments/assets/885d5524-593c-437c-a4e1-1eb16890be67)

**Comment by irvinm** [comment]
Last example:  https://github.com/kamranahmedse/developer-roadmap (clips when in, fine when out)

It looks to me that it is related to the length of the "title" ... in each of these cases, these tabs had the longest "title" value.

![image](https://github.com/user-attachments/assets/681c16fd-6c0d-484e-9717-2e4b7c8d9020)

**Comment by irvinm** [comment]
Another data point ... when the "reflow()" is kicked off, the title is presently properly (obviously before the --column-width CSS is applied) and the width of the client area is sufficient to be able to display the entire title.

## Start of reflow
![image](https://github.com/user-attachments/assets/dca4bdba-2417-4f5f-9fc8-22e28a42aded)

## After reflow is complete
![image](https://github.com/user-attachments/assets/3f11f03a-ef65-4278-9172-e9ff67a9d2ad)

**Comment by piroor** [comment]
I've introduced a change 63b55b4 which changes the method to determine to show the tree in multiple columns or single column. TST shows the tree in multiple columns only when its actual height is larger than the container. It should work whether items are cropped or line-broken.

**Comment by irvinm** [comment]
I tried the latest dev build and everything seems to be working as expected now.  Thank you so much!
