### ISSUE TITLE
Any way to visually space tab trees without breaking drag&drop?

### ISSUE THREAD

**Issue by Baerbeisser** [piroor/treestyletab#3598]
## Abstract
I use a custom theme in which i want to separate open tab trees for visibility.
But this causes the drag&drop indicator (to drag a tab as a child element) to be misaligned.
It looks like this: 
![Bildschirmfoto_2024-07-29_15-29-44](https://github.com/user-attachments/assets/e5ddac39-1823-4b84-b148-996f1963ae20)

## Steps to see the situation
Use Photon theme and add this snippet:

```
/* space between trees  (root level tabs) */
tab-item[data-level="0"]:not(.subtree-collapsed) {
  margin-top: calc(var(--tab-size) / 4);
  /*border-top: 1px solid lightgrey;*/
}
```

## Expected result
This but with trees separated:
![Bildschirmfoto_2024-07-29_15-57-50](https://github.com/user-attachments/assets/a249d316-6af0-4ffc-bc74-c96a6993fde7)

Best would would be if drag&drop handler is calculated per tree (instead of the whole sidebar). But i guess this is a bit much asked.
Is there a CSS variable or workaround with which i can correct it?
I tried with height instead of margin but that has the same issues.

## Actual (present) result
drag&drop indicator gets misaligned, with *margin-top \* nr. of open trees* the further down.

## Environment

 * Platform (OS): Linux but independent
 * Version of Firefox: 128.0 esr
 * Version (or revision) of Tree Style Tab: 4.0.20

**Comment by piroor** [comment]
The CSS hack is not suitable for TST 4.0 and later. See also discussions in #3592.

**Comment by Baerbeisser** [comment]
Ok, any built-in way to achieve the same or something similiar?

**Comment by piroor** [comment]
Sadly there is no alternative method for now. As I told at https://github.com/piroor/treestyletab/issues/3592#issuecomment-2236106252 we need to implement new helper addon to do that with newly designed API, but such an API may reduce performance if I design it carelessly...

**Comment by Baerbeisser** [comment]
Fine, this works too.
```
tab-item[data-level="0"][data-child-ids] {
  /*margin-top: calc(var(--tab-size) / 4);*/
  border-left: 3px solid var(--text-unread);
}
```
![Bildschirmfoto_2024-07-29_17-18-53](https://github.com/user-attachments/assets/e4ef3a40-b8cf-429c-8a38-666f4dabd96f)
![Bildschirmfoto_2024-07-29_17-19-14](https://github.com/user-attachments/assets/3c3ca93b-e736-4b39-a35c-a3453a8e92d1)

Thanks for the time!
