### ISSUE TITLE
Makes loading some websites slow

### ISSUE THREAD

**Issue by kkot** [piroor/treestyletab#360]
I recently noticed that loading a site 'antyweb.pl' is very slow.
It took 10 seconds between hitting Enter until CPU went idle.
So I created a new profile - it took 5 seconds to load same website (until idle). So I started disabling extensions one by one in my old profile and discovered that TST is the problem.

I tested it many times and result is always the same - 10 seconds with TST, 5 seconds without.

Without TST Firefox seems to work faster (but I didn't test any other websites because most websites load fast).

I know that my report is not very specific. I just thought that it would make no harm to signal the problem.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
