### ISSUE TITLE
[Bug] TST More Tree Commands "Create New Group from tabs" Context Menu Item Breaks Trees In TreeStyleTab v4.0.15-Latest(4.0.20)

### ISSUE THREAD

**Issue by joshuagames987** [piroor/treestyletab#3601]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install any version of TST between version 4.0.15-latest(4.0.20) manually or automatically found here: https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/versions/ version 4.0.14 doesn't appear to have this issue, which is how I've pinpointed it began in version 4.0.15
 3. Install TST More Tree Commands
 4. Create a tree of 2 or more layers deep, or drag one tab onto another in the TST sidebar
 5. Right click any tab with another tab attached to it & use TST More Tree Commands's context menu item "Operate Tree->Create New Group from tabs"

### Tree Structure Diagram:
Before:
- A
  - B

After:
- Group Tab Named "Group"
  - A
- B

## Expected result

- Group Tab Named "Group"
  - A
    - B

## Actual result
After:
- Group Tab Named "Group"
  - A
- B

## Environment

 * Platform (OS): Linux Manjaro(Arch Based Distro)
 * Version of Firefox:  123.0.1
 * Version (or revision) of Tree Style Tab:  4.0.15-latest(4.0.20)

**Comment by piroor** [comment]
Sorry I transferred this issue to the TST More Tree Commands project yesterday but I've realized that it need to be fixed by TST side so I've transferred this back again.

**Comment by piroor** [comment]
After some testing I've realized that the command breaks tree structure unexpectedly when tabs in existing trees are partially selected. I've introduced changes to keep tree structure as possible as we can on such situations.
https://github.com/piroor/treestyletab/commit/db914f4e96696397c102b57a39e99c704788b88f
https://github.com/piroor/treestyletab/commit/ffeb85c7d8570710d5e6e577b9b6db261cd72f9a
https://github.com/piroor/treestyletab/commit/2ca7ab2fced031c029d77baa871c267a35ac3c2b
