### ISSUE TITLE
[Enhancement] (Persistent Stick/Unstick Tab to Edges after reloading Firefox)

### ISSUE THREAD

**Issue by SHHSSH** [piroor/treestyletab#3603]
Hi @piroor,

I'm looking to request a persistent function for the Stick/Unstick Tab to Edges after reloading Firefox as to regularly have to stick my main trees/folders is incredibly tedious when having a large sidebar content.

If this is at all possible it would be immensely appreciate I am sure for those who utilise the relatively new stick feature.

Thanks.

**Comment by piroor** [comment]
Sorry I missed that this happens when tree structure is restored without cache. The commit f760644 should fix it.

**Comment by SHHSSH** [comment]
@piroor Yeah it's weird, I think it works sometimes though... so I was about to close the issue again, thanks for the clarification.
