### ISSUE TITLE
[Bug] session tab not restored

### ISSUE THREAD

**Issue by ZevSuk** [piroor/treestyletab#3604]
when you close the browser. The session is saved. But the one that was open at the moment of closing is not opened. 
If I restore the tabs, the one that was selected does not open.
see screenshot

when I closed it. The 2nd one was highlighted. That's why the session name is assigned from it. But when I open the session, it is the one that is not restored. All tabs are restored except this one.
I noticed that google tabs are restored. The problem is with the YouTube tabs. I can't trace the exact pattern yet.

**Comment by irvinm** [comment]
@ZevSuk do you know if that tab is actually being restored (and TST is just not showing it) or if the tab is NOT being restored (which would be a TSM issue)?  Can you disable your CSS to hide the native tab bar and try again?  Also, of the 140 tabs being restored, is it just the 1 or are there others?

Also, I have 3 addons I wrote that you can use for your consideration related to this situation:
1. https://addons.mozilla.org/en-US/firefox/addon/toggle-native-tab-bar/ - Provides an easy way to toggle the native tab bar using the addon button.
2. https://addons.mozilla.org/en-US/firefox/addon/reload-discarded-tabs/ - Reloads & discards each tab restored via TSM to resolve the favicon from the default globe to the websites icon.
3. https://addons.mozilla.org/en-US/firefox/addon/tst-active-and-total-tabs-ctr/ - Active and total tab counter placed at the bottom of the TST sidebar and on the addon button.

**Comment by ZevSuk** [comment]
1/  NOT being restored
Exactly not restored.

2/ an you disable your CSS to hide the native tab bar and try again
What is this? Where is this?

3/ Also, of the 140 tabs being restored, is it just the 1 or are there
others?
The number of tabs doesn't matter. It happens that out of 10 tabs, when you
open it, it still doesn't open the one that was highlighted when you closed
it.

Also, I have 3 addons I wrote that you can use for your consideration
related to this situation:

I'm not interested in addons. As I am completely satisfied with what I have
and what I was looking for. Your "tab session" is the best. A long time ago
even put money. I just didn't update it for a year. Here recently updated,
and noticed such a bug. So, somewhere in the last update the bug crept in.

чт, 8 серп. 2024 р. о 13:46 Mike Irvin ***@***.***> пише:

**Comment by ZevSuk** [comment]
Just checked a couple options.
100% doesn't open
(lost), the tab exactly YouTube video. The other sites are opening
open normally. (Well, at least the 3 that I opened).

Of the add-ons I have only 3 of these
I'll try to disable those 2 more.

[image: Monosnap Управление дополнениями — Mozilla Firefox.jpg]

чт, 8 серп. 2024 р. о 14:31 Руслан ***@***.***> пише:

**Comment by irvinm** [comment]
> Just checked a couple options. 100% doesn't open (lost), the tab exactly YouTube video. The other sites are opening open normally. (Well, at least the 3 that I opened). Of the add-ons I have only 3 of these I'll try to disable those 2 more. [image: Monosnap Управление дополнениями — Mozilla Firefox.jpg] чт, 8 серп. 2024 р. о 14:31 Руслан ***@***.***> пише:

If the tab is not being restored, it is not a TST issue, but a TSM issue.  If you disable TST, you should see the same behavior.  You may want to file an issue in that project.

**Comment by ZevSuk** [comment]
yes ))
I got confused. I apologize. I'm used to yours.) And TSM becomes invisible

чт, 8 серп. 2024 р. о 15:06 Mike Irvin ***@***.***> пише:
