### ISSUE TITLE
[Bug] Scrolling of tabs is broken on Nightlies

### ISSUE THREAD

**Issue by vflaux** [piroor/treestyletab#3605]
## Abstract

Scrolling tabs is broken in Firefox Nightlies since they removed "overflow/underflow events" by disabling "layout.overflow-underflow.content.enabled_in_addons" pref.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1907460 & https://bugzilla.mozilla.org/show_bug.cgi?id=1897595

This can be fixed for now by re-enabling the pref in about:config. But the option might be removed one day.

## Steps to reproduce

 1. Start Firefox Nightly (since 2024-08-06-21-12-39) with clean profile.
 2. Install TST.
 3. Open tabs until it fill all the vertical space so we can scroll
 4. Try to scroll

## Expected result

You should be able to scroll the tabs

## Actual result

Nothing moves

## Environment

 * Platform (OS): Windows 11
 * Version of Firefox: Nightlies since build 2024-08-06-21-12-39 : https://ftp.mozilla.org/pub/firefox/nightly/2024/08/2024-08-06-21-12-39-mozilla-central/
 * Version (or revision) of Tree Style Tab: 4.0.21

**Comment by csarven** [comment]
Ditto on:
* Platform (OS): Ubuntu 24.04 LTS
* Version of Firefox: 131.0a1 (2024-08-07) (64-bit)
* Version (or revision) of Tree Style Tab: 4.0.21

Can confirm that setting `layout.overflow-underflow.content.enabled_in_addons` to `true` (and then `false`) in `about:config` seems to bring and persist scrolling within the same browser session, i.e., once the browser is closed and reopened, the scrolling issue remains.

I've also moved the sidebar to the left and right but it did not resolve the scrolling issue.

Have also closed/opened (<kbd>F1</kbd>) sidebar and the issue remained.

**Comment by vflaux** [comment]
According to this comment https://bugzilla.mozilla.org/show_bug.cgi?id=1912224#c3, this should be already fixed by this commit https://github.com/piroor/treestyletab/commit/fb01a8ca455735913b495b0323ecffda2853ca73.
I tried with dev builds before & after this commit and I can confirm that it fixes the issue.
We just have to wait for new a release of TST.

**Comment by piroor** [comment]
I've uploaded TST 4.0.22 including the fix.
