### ISSUE TITLE
[Enhancement] (Option to toggle if TST is visible with Fullscreen window or not)

### ISSUE THREAD

**Issue by SHHSSH** [piroor/treestyletab#3609]
Hi @piroor,

Just enquiring if there is an option at all otherwise requesting an implentation of such that allows for TST to be hidden when the client fullscreens? 

This specifically allows for a more conducive flow for those who want a commonly universally used hotkey(F11) to be able to be optimised in an additional way, e.g; a user prioritises a browser windows at about 80% of its monitor's resolution to allow for more application usage visually of other tasks on PC, but regularly wants to "Maximize" their visual scope through both fullscreen and wanting to remove TST's sidebar. 

I thought to myself couldn't I just do this on my own after writing this by setting the hotkey to F11 to show TST, but as with many limitations within FF's Hotkey options, obviously that is not allowed. Therefore to have an entirely separate key for the toggling of TST's sidebar, it becomes noticeably momentum breaking.

Thank you for any considerations.

**Comment by SHHSSH** [comment]
![capture_005_15082024_133525](https://github.com/user-attachments/assets/5cea836c-9162-45e1-a83a-4ca66e4e0ece)

Thank you for this update, hopefully it's cleared up, I'll close my often in the next few days.

**Comment by piroor** [comment]
Sadly it is impossible to implement the feature, because toggling of the sidebar UI is blocked when it is called from functions except handlers of keyboard shortcuts or clicking on the toolbar button.

**Comment by irvinm** [comment]
@SHHSSH if you want something that might work for you, you can add this to your userChrome.css:

```
#main-window[inFullscreen] #sidebar-box {
  display:none !important;
  width: 0px !important;
}
```

**Comment by SHHSSH** [comment]
> @SHHSSH if you want something that might work for you, you can add this to your userChrome.css:
> 
> ```
> #main-window[inFullscreen] #sidebar-box {
>   display:none !important;
>   width: 0px !important;
> }
> ```

Thank you very much, it works exactly as I require.
