### ISSUE TITLE
[Bug] "Open this options page in more wide space" link broken

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#3614]
## Abstract
Looks like the "Open this options page in more wide space" link from the "Options" page has changed.

The link is now:  moz-extension://UUID/options/options.html#!

Removing the "#!" from the link works fine.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open options page
 4. Click on the "Open this options page in more wide space"

## Expected result
To see options in its own page.

## Actual result
Blank page is rendered.

## Environment

 * Platform (OS): Windows 11 (23H2)
 * Version of Firefox:  129.0.1
 * Version (or revision) of Tree Style Tab:  4.0.22

**Comment by piroor** [comment]
Thanks, I missed that. The commit bb14293 should fix this.
