### ISSUE TITLE
[Enhancement] If a permission is missing, give feedback (instead of do nothing)

### ISSUE THREAD

**Issue by JustMyGithub** [piroor/treestyletab#3622]
## Abstract
I tried to bookmark tabs from TST and nothing happened. I serached in different location in my bookmarks, then did a web search. I noticed that bookmark management is an optional permission that you need to grant and now it works.

The user should get information that a permission is missing and optinally how to set it, Even better if TST could trigger an "ask for permission" dialogue of firefox (don't know if that is possible)

## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open some Tabs and
 4. Try to bookmarkt them within TST

## Expected result
"Permission missing" info or "give permission" dialogue

## Actual (present) result
nothing happens

## Environment

 * Platform (OS): Win 10
 * Version of Firefox: 129.0.2 
 * Version (or revision) of Tree Style Tab: 4.0.22

**Comment by piroor** [comment]
TST is designed to show a desktop notification about the missing permission, on such cases. Did you disabled desktop notifications of Firefox globally?

**Comment by JustMyGithub** [comment]
Oh, ok. I did never notice anything reporting only via the notification center and yes, it was not enabled for Firefox
