### ISSUE TITLE
[Enhancement] The context menu in the Floorp browser lacks native options for tabs

### ISSUE THREAD

**Issue by Denpan1** [piroor/treestyletab#3629]
## Abstract
The context menu in the Floorp browser lacks native options specifically split window options. Here is a link to show how the feature in Floorp should work https://blog.ablaze.one/4502/2024-09-00/ .

## Steps to see the situation

 1. Start Floorp v11.18.1 (64-bit) | Firefox: 128.3.0 with clean profile on Win10 22H2.
 2. Install TST v4.0.22.
 3. Open a few tabs.
 4. Left-click a tab to see the context menu.
 5. Try to find split window options in the menu.

## Expected result
Having the split window options in the menu.

![image](https://github.com/user-attachments/assets/0a67f1ac-3c16-4cfe-a0b5-b030f66da1f0)

## Actual (present) result
Those options are missing.
![image](https://github.com/user-attachments/assets/642a418c-54fe-4b83-867b-6223cf674c18)

## Environment

 * Platform (OS):  Win10 22H2
 * Version of Firefox: 128.3.0 | Floorp Version 11.18.1 (64-bit)  
 * Version (or revision) of Tree Style Tab: v4.0.22

**Comment by piroor** [comment]
Floorp specific context menu commands can be added and activated only on Floorp, if Floorp provide ability to call those features from WebExtensions addons via API.

Otherwise - if there is no such API - a forked version TST with Experiments may be a solution. Indeed current Waterfox's tabs sidebar is based on TST.

**Comment by Denpan1** [comment]
Oh sorry i meant right-click in step 4

**Comment by Denpan1** [comment]
Oh ok thank you

**Comment by piroor** [comment]
Here are Experiments modules on Waterfox Sidebar:
https://github.com/BrowserWorks/Waterfox/tree/fc3cbba5b84902fce15dd968ceeb24498825fca2/waterfox/browser/components/sidebar/experiments
https://github.com/BrowserWorks/Waterfox/blob/fc3cbba5b84902fce15dd968ceeb24498825fca2/waterfox/browser/components/sidebar/manifest.json#L247-L290

and here is the list of Waterfox specific modules depending on those Experiments APIs:
https://github.com/BrowserWorks/Waterfox/blob/fc3cbba5b84902fce15dd968ceeb24498825fca2/waterfox/browser/components/sidebar/sidebar/index-ws.js
https://github.com/BrowserWorks/Waterfox/blob/fc3cbba5b84902fce15dd968ceeb24498825fca2/waterfox/browser/components/sidebar/sidebar/tab-preview.js
https://github.com/BrowserWorks/Waterfox/blob/fc3cbba5b84902fce15dd968ceeb24498825fca2/waterfox/browser/components/sidebar/sidebar/workaround-for-bug-1875100.js
https://github.com/BrowserWorks/Waterfox/blob/fc3cbba5b84902fce15dd968ceeb24498825fca2/waterfox/browser/components/sidebar/background/index-ws.js
https://github.com/BrowserWorks/Waterfox/blob/fc3cbba5b84902fce15dd968ceeb24498825fca2/waterfox/browser/components/sidebar/background/prefs.js
https://github.com/BrowserWorks/Waterfox/blob/fc3cbba5b84902fce15dd968ceeb24498825fca2/waterfox/browser/components/sidebar/background/handle-autoplay-blocking.js
https://github.com/BrowserWorks/Waterfox/blob/fc3cbba5b84902fce15dd968ceeb24498825fca2/waterfox/browser/components/sidebar/background/handle-chrome-menu-commands.js
https://github.com/BrowserWorks/Waterfox/blob/fc3cbba5b84902fce15dd968ceeb24498825fca2/waterfox/browser/components/sidebar/background/sharing-service.js
