### ISSUE TITLE
[Bug] TST writes to disk every time tab is clicked

### ISSUE THREAD

**Issue by ValdikSS** [piroor/treestyletab#3631]
## Abstract

TST seem to sync its internal state to disk every time any action is performed, such as switching between tabs, which results in unnecessary higher wear of disk (SSD).

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Launch `fatrace -f W` on Linux to monitor disk writes
 4. Switch tabs
 5. See lines like `/home/valdikss/.mozilla/firefox/ym25otji.wefwef/storage/default/moz-extension+++1bfe5851-3afc-4bfa-951f-64287da9bee2/idb/798144174PeegramraonteSnt.sqlite-wal` every time the tab is switched

Extension storage UID could be seen in `about:debugging#/runtime/this-firefox`. This is TST storage directory.

## Expected result

TST should not write to disk on every action.

## Actual result

TST writes to disk on tab change (and other minor actions as well)

## Environment

 * Platform (OS): Linux Fedora 39
 * Version of Firefox: 130
 * Version (or revision) of Tree Style Tab: 4.0.22

**Comment by piroor** [comment]
Does disabled cache (remind that you need to unlock expert options) solve this problem?

**Comment by piroor** [comment]
Screenshot of the option:
![image](https://github.com/user-attachments/assets/4e2bf41b-e7d8-4874-8b16-b30daa94f99e)

**Comment by ValdikSS** [comment]
Yes, with this option unchecked there are no longer writes on every tab click.
