### ISSUE TITLE
[Bug] Indexed DB tracks browsing history

### ISSUE THREAD

**Issue by HanabishiRecca** [piroor/treestyletab#3637]
## Abstract

Indexed DB tracks browsing history. There is `TabFavIconHelper` database with `effectiveFavIcons` table which stores addresses of every page you visit.
Even worse, it tracks history of private windows (if you allowed the extension to run in private windows of course)! And it does not remove the data when you clear the browser history! I'm not sure if it stores the data indefinitely of just for a very long time, but it grows quite large.

This is a very serious privacy concern in my opinion.

I disabled the tree cache, but it did not change anything. Please disable history tracking or make an option to do so.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Use TST for a while.
 4. Open the extension in debug mode and observe the indexed DB contents.

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 131.0
 * Version (or revision) of Tree Style Tab: 4.0.23

**Comment by piroor** [comment]
Thanks, I missed about possibility that urls stores in the IndexedDB are used in other purposes and TST violates the basic policy of the private browsing. I've introduced a change to switch the stored key information from raw URL to SHA1 hash, as a workaround. Does it solve the privacy issue you pointed?

**Comment by piroor** [comment]
The corresponding change at the library side:
https://github.com/piroor/webextensions-lib-tab-favicon-helper/commit/65319f9d466b346718487c18fc71a896d1e6faec

Already stored URLs are cleared by dropping of object stores at the migration process.

**Comment by HanabishiRecca** [comment]
> I've introduced a change to switch the stored key information from raw URL to SHA1 hash, as a workaround. Does it solve the privacy issue you pointed?

It should, I think.

But I still have a question though. Why it need to be stored in the first place? If you need a favicon cache, Firefox already does that afaik. Or at least store per domain, why full urls?

**Comment by piroor** [comment]
This mechanism was originally introduced because all "favIconUrl"s were raw URL in old days. And there still be no guarantee that the "favIconUrl" is data: URI cached by Firefox.

Anyway, we don't need to generate data: URL manually for "favIconUrl" given as data: URI. I've introduced more change to bypass caching mechanism for such cases, with the commit https://github.com/piroor/webextensions-lib-tab-favicon-helper/commit/6597ebd60889ee3cd93e1dd27872d5af9478da38.

**Comment by HanabishiRecca** [comment]
Looks promising, thank you.
