### ISSUE TITLE
[Bug] Firefox Add-on Signing required? Add-on disabled

### ISSUE THREAD

**Issue by sayboltm** [piroor/treestyletab#3638]
## Abstract
Firefox is forcing enforcement of disabling non-signed add-ons
 
## Steps to reproduce

 1. Start Firefox 

## Expected result
Tree-style tab should load 

## Actual result

Add-on does not load, refuses to load stating:

Tree Style Tab could not be verified for use in Firefox and has been disabled. 

Firefox says read this: 

https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

## Environment

 * Platform (OS): 
 * Version of Firefox: 130.0.1
 * Version (or revision) of Tree Style Tab: 
 * Release notes say: 
 4.0.23 (2024.9.11)

 * But firefox says:
 * 
Version
4.0.23
Last Updated
October 6, 2024

**Comment by sayboltm** [comment]
Literally after 30 minutes of various distractions, after finishing gathering info and typing that, the add-on has loaded though I lost many windows. Maybe this is a firefox issue? Closing.

Though maybe this add-on should support this if it is coming down the pipeline.

**Comment by sayboltm** [comment]
Actually this is still a problem. I don't know how/why it "fixed itself" (and ran unsigned anyway) after I posted that. Re-opening....

**Comment by piroor** [comment]
Any screenshot? And, any error is reported in the browser console (Ctrl-Shift-J) ?

**Comment by sayboltm** [comment]
Argh theres a bug in the bug reporting: 
When closing an issue and then re-opening, I have no way to re-add the "needs-triage" label!

**Comment by sayboltm** [comment]
Thanks for the tip,
I do not see any logging seemingly related to this or other disabled extensions (I also use OpenList, which has also been disabled but I haven't opened an issue there yet) in the browser console. it appears completely disabled.

**Comment by piroor** [comment]
Sorry I forgot to note that you need to go to `about:config` and set `extensions.logging.enabled` to `true` to see logs around the addon manager module of Firefox itself. Turn it and restart Firefox, and see the browser console again, then you'll see logs about disabled addons.
