### ISSUE TITLE
[Bug] Expand state seems not to be known after browser start

### ISSUE THREAD

**Issue by behhNa** [piroor/treestyletab#3639]
## Abstract

If you drag a tab (or group) onto a collapsed tab group it will expand it but all other currently expanded groups will collapse.
This seems only to be true if you didn't touch a group before.
This means, if you already expanded/collapsed one group in the current session, this one group will stay in the state it is. All others are still affected.
After a browser restart the state seems to be 'blank' again.

This issue only occurs on expanded groups. Already collapsed will not expand (nor shouldn't).

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open multiple tabs and trees
 4. Expand all tab groups but one
 
 5.1. Restart Firefox and drag tab "E" onto (collapsed) group "C_2"

Example 1: 

> A (expanded)
> -- A_1
> -- A_2 (expanded)
> ---- A_2_1
> B
> C (expanded)
> -- C_1
> -- C_2 (collapsed)
> ---- C_2_1
> D (expanded)
> -- D_1
> -- D_2
> E

 5.2. Restart Firefox and drag tab "E" onto (collapsed) group "C"

It seems that subgroups (like "A_2" and "C_2") are only affected if the dragged tab is pulled onto another subgroup.

Example 2: 

> A (expanded)
> -- A_1
> -- A_2 (expanded)
> ---- A_2_1
> B
> C (collapsed)
> -- C_1
> -- C_2 (expanded)
> ---- C_2_1
> D (expanded)
> -- D_1
> -- D_2
> E

## Expected result

Example 1: Tab group "A", "A_2" and "D" should stay expanded.

Example 2: Tab group "A", "A_2", "C_2" and "D" should stay expanded.

## Actual result

Example 1: Tab group "A", "A_2" and "D" get collapsed.

Example 2: Tab group "A" and "D" get collapsed. "A_2" and "C_2" stay expanded.

## Environment

 * Platform (OS): Win10
 * Version of Firefox: 131.0.2
 * Version (or revision) of Tree Style Tab: 4.0.23

**Comment by irvinm** [comment]
Sorry, I didn't review all of the details of your scenario, but have you tried disabling this option after enabling "unlock expert options"?

![image](https://github.com/user-attachments/assets/90cfd5d8-95ed-4a63-a54d-46058ddab392)

**Comment by behhNa** [comment]
Hey, thanks for the answer.
Yeah I have that option disabled as well. Unfortunately it doesn't seem to change the behavior.

**Comment by piroor** [comment]
There is another option related to the behavior: TST Options => Unlock Expert Options => Drag and Drop => Expand collapsed tree with hovering over... => Collapse other trees when collapsed tree is auto-expanded
![image](https://github.com/user-attachments/assets/d398bbca-be79-4177-8b54-2ce460af14e4)
Could you try unchecking it?

**Comment by behhNa** [comment]
That is the solution.
I checked all options to find something related but I clearly wasn't thorough enough. 
Sorry for the wrong report as a bug. Thank you!
