### ISSUE TITLE
[Feature Request] Lock tab

### ISSUE THREAD

**Issue by SHHSSH** [piroor/treestyletab#3641]
There are some programs like -https://github.com/tablacus/TablacusExplorer - that provide a capability to "Lock" a tab, whereas even if a user was to click on a link from that tab and that link was intended to open in that current tab, it does not and it forces itself to a new tab for that content. This can be extremely useful and productive for users who regularly click on links from a stream type tab or various others etc. though they require that tab to always be in its current state(not position) because it's essentially a main tab of sorts.

It would also prevent the tab from being closed via Ctrl+W etc.

Thanks in advance for any consideration and sorry for the somewhat convoluted explanation.

@piroor

**Comment by SHHSSH** [comment]
Also I believe this could be a useful feature for TST users as a whole, though it could be considered apart of the additional options and features offered in TST More Tree Commands.

**Comment by piroor** [comment]
[TST Lock](https://addons.mozilla.org/firefox/addon/tst-lock/) looks to be the solution. See also the related discussions at #2104.
