### ISSUE TITLE
[Bug] Transfering tab to mobile devices.

### ISSUE THREAD

**Issue by alith** [piroor/treestyletab#3644]
Hello!

First of all, thanks a lot for your hard work on this life-changing/saving, extension. I've been using it for years now, and I don't know how I would manage without.

My problem is this: I can transfer tab from my mobile to my computer (that's obviously the most useful way), but I can't do it the other way: I believed you replaced the "send tab to another device" option from the contextual menu, for it to be able to transfer trees. The disadvantage of this is that you have to have a Firefox with TST installed on the receiving device to be able to register it with the extension on the sending machine. And TST for Firefox for mobile doesn't exist, because it would be as useless as a cat-flap on submarine.

So, I see several solutions to this(from the simplest to the most complicated... IMHO):
 - put the options in the extension settings whether to display send tab to device and/or send tree to device (one being the original one, the other yours)
 - implement a "TST receiver" extension for Firefox android, that would simply flatten and open the tab/tree sent.
 - complete your "send tab to device" functionality for it to be able to register Firefox for mobile as a TST-less valid target.
 
 Thanks again for your hard work. You're awesome. I love you.

**Comment by piroor** [comment]
In short: it is impossible for now due to restrictions of WebExtensions API.
As you know we need a TST receiver addon on Android:
https://github.com/piroor/treestyletab#user-content-feature-requests-send-tab-tree-to-device-does-not-work
but Firefox for Android does not support sync APIs:
https://github.com/piroor/send-tabs-to-device-simulator?tab=readme-ov-file#send-tabs-to-device-simulator
so the receiver addon cannot receive data sent from your desktop.

**Comment by irvinm** [comment]
@alith why don't you just use the native tab mechanism to send tabs from desktop to mobile?  You can multi-select tabs and initiate "Send X tabs to device".  Not exactly the same as sending a "tree", but a workaround.

**Comment by alith** [comment]
@piroor Sorry to bother you with an already documented issue. Thanks again for your work.

@irvinm My mobile doesn't appear in the devices. It never did. Because there isn't a feasible TST extension for FF on android mobile

Anyway, thanks for the quick answer! :)

**Comment by alith** [comment]
duplicate of known issue.

**Comment by alith** [comment]
fingers crossed, one day [this](https://connect.mozilla.org/t5/ideas/customizable-hotkeys/idi-p/4979) gets implemented, and I won't have to keep the horizontal (almost) useless bar^^

**Comment by irvinm** [comment]
@alith I was saying that EVEN without TST installed, you should be able to send tabs from your desktop/computer to your mobile as long as both are using "Firefox Sync".  (Nothing to do with TST)

Also, if you want to hide/show the native tab bar on the fly, you could use my addon:  https://addons.mozilla.org/en-US/firefox/addon/toggle-native-tab-bar/  I normally hide the tab bar myself.


![image](https://github.com/user-attachments/assets/bb6750e8-ef28-4012-a5b8-4807fab817ab)
