### ISSUE TITLE
Scrolling Broken in Firefox Update

### ISSUE THREAD

**Issue by prncevince** [piroor/treestyletab#3647]
## Abstract

Scrolling of the TST sidebar seems to have broken. I'm using Firefox 132.0. I believe that it was broken in v131 as well. 

I'm running macOS 14.6.1.

## Steps to reproduce

Add enough tabs to your session to have more tabs than what can be viewed in the TST sidebar. Then, try to scroll.

## Expected result

You should be able to scroll the Sidebar up/down to view tabs outside of the length of the Sidebar view. A scrollbar should also appear when doing this.

## Actual result

Nothing happens when scrolling. No scrollbar. No scrolling.

## Environment

 * Platform (OS): macOS 14.6.1
 * Version of Firefox:  132.0
 * Version (or revision) of Tree Style Tab:  4.0.17

**Comment by piroor** [comment]
This does not happen for me with TST 4.0.24 on Windows 11, Firefox 132. Could you try newer version TST?

**Comment by prncevince** [comment]
Fixed on update to 4.0.23 👍
