### ISSUE TITLE
[Bug] Autohide expands behind window content

### ISSUE THREAD

**Issue by ned-martin** [piroor/treestyletab#3648]
## Abstract
TST is set to autohide. When mouse hover it should expand over the top of the window, but it is now expanding behind the window content.

## Steps to reproduce

 1. Upgrade Firefox to 133.0b2 when TST is set to auto-hide and expand on hover. This works on previous versions of Firefox.

## Actual result

TST auto-hidden
![image](https://github.com/user-attachments/assets/53c38f4a-a42d-4100-8d85-4cc50656702a)

TST with mouse hover - now expanded *behind* the window content
![image](https://github.com/user-attachments/assets/86f8a252-5021-40eb-9f9d-2d3fd4129393)

How it should work
 
<img width="185" alt="2024-11-01_16-44-04" src="https://github.com/user-attachments/assets/073c2db5-1c8c-41eb-bc7b-5742534e95ea">

## Environment

 * Platform (OS): Windows 11
 * Version of Firefox: 133.0b2 
 * Version (or revision) of Tree Style Tab: 4.0.23

**Comment by piroor** [comment]
Autohide is not a feature of TST, it is a userChrome.css customization topic. Thus I move this from issues to discussions.
