### ISSUE TITLE
[Bug] Moving parent tab has unexpected(?) behaviour

### ISSUE THREAD

**Issue by N1ftyB1z** [piroor/treestyletab#3651]
## Abstract
Dragging a parent tab (not root parent) to move it promotes the First Child, when it should(?) Promote All Children. 

## Steps to reproduce

 1. Have tabs set up like so:
     a. (RootParent)
          a.i. (Parent, Child of RP)
               a.i.1 (Child)
               a.i.2
          a.ii.
 2. Move a.i out of the tree.

## Expected result

My desired behaviour for moving the parent tab (not root parent) out of the tree is for the children of that tab to all promote/outdent – the same behaviour as when deleting the tab. If this behaviour isn't a bug can it please be added as an option? 

This is desired behaviour as it's a way to 'outdent' every tab below the selected parent tab (to get the parent tab on the same depth/level as the first child), without having to select all of the children manually then drag those tabs — Which is useful for putting a tree under a group (as a label for bookmarking, etc.) when the tree consists of 1 tab with lots of children, for instance, as the result of an initial google search and following many links in new tabs. 

## Actual result

Dragging a parent tab (not root parent) to move it promotes the First Child, when it seems as though it should promote Promote All Children based on the settings menu. This persists when trying different settings in the Tree Behaviour and Drag and Drop categories in the Options menu, such as setting 'Promote All Children to the parent level always' (I've attached my current settings for these categories below), as well as when disabling TST add-ons. 

### Drag & Drop options:
<img width="493" alt="DragDrop" src="https://github.com/user-attachments/assets/089b962d-d096-48ea-9336-c2ba4ed46d6d">

### Tree Behaviour options:
<img width="477" alt="TreeBehaviour" src="https://github.com/user-attachments/assets/a7e58ef0-b3cf-42dc-a4c7-e2155d073239">

I'm not sure if this is a bug, or if i'm missing an option in the settings (it was a bit confusing what does what between the options in the Tree Behaviour and Drag and Drop categories, though I think I understand them now from looking into them). 

This behaviour seems to contrast to the behaviour when deleting the tab, as well as the behaviours when moving or deleting a root parent tab:

### Close Root Parent: (result as expected)
<img width="253" alt="TSTCloseRootParent" src="https://github.com/user-attachments/assets/972f01a2-d4fd-4819-a914-096cbfefeda6">

### Move Root Parent: (result as expected)
<img width="253" alt="TSTMoveRootParent" src="https://github.com/user-attachments/assets/968f3d9e-b57f-4bea-96bd-c84ca1f5612e">

### Close Parent 2 / Sub-parent: (result as expected)
<img width="253" alt="TSTCloseParent2" src="https://github.com/user-attachments/assets/fecf5892-2261-4348-acc1-17a24017ca7f">

### Move Parent 2 / Sub-parent: (unexpected result)
<img width="253" alt="TSTMoveParent2_Unexpected" src="https://github.com/user-attachments/assets/a39be2dd-a01a-4f4b-a882-139a8b094cf6">

*'Feature' and 'Suspended' tabs should be in-line / same depth with each other.

## Environment

 * Platform (OS): Windows 10 Home, OS build 19045.5011
 * Version of Firefox: 132.0 (64-bit)
 * Version (or revision) of Tree Style Tab: 4.0.23 (2024.9.11)

**Comment by piroor** [comment]
Thanks, I've pushed a change to apply the chosen behavior on a solo tab drag-and-drop case.
