### ISSUE TITLE
[Bug] Group tab content not loading

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#3655]
## Abstract
4.0.24 breaks loading of the tabs under group-tab.html

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Create group-tab.html
 4. See that loading spinner never stops and tab information never displays
 5. Notice error in console

![image](https://github.com/user-attachments/assets/21ec65e5-eb0e-480f-b3b1-4ab2852b0616)

![image](https://github.com/user-attachments/assets/ccb74cf9-cdf6-44d9-9228-b8d1d04e4990)

## Expected result
List of children under the group-tab are displayed on group-tab.html

## Actual result
Spinner never finishes

## Environment

 * Platform (OS): Windows 11
 * Version of Firefox:  132.0.1
 * Version (or revision) of Tree Style Tab:  4.0.24

**Comment by Rhialto** [comment]
+1. Also happens here. Another operating system (NetBSD) and Firefox version, also not a fresh install but my heavily used one. But the symptoms are the same.

**Comment by johnbwang** [comment]
I think something related is also happening with `get-tree` API call. When I call that, I get the error `Error: tab.favIconUrl is undefined`.

**Comment by piroor** [comment]
Sorry it is my fault. The regression is made from an external library and the problem should be fixed with commits https://github.com/piroor/webextensions-lib-tab-favicon-helper/commit/7400c97a15adc0ea2343d2de3beb381e44a0cb1f and https://github.com/piroor/treestyletab/commit/6503b609d410712191149610278d729733a97ed0 .

**Comment by irvinm** [comment]
Fix looks good.  Thanks!
