### ISSUE TITLE
[Enhancement] TST "Bookmark tab" interface vs. Firefox "Bookmark current tab" interface

### ISSUE THREAD

**Issue by MuhMuhGH** [piroor/treestyletab#3657]
## Abstract
Would it be possible to integrate TST and Firefox in such a way as to enable TST to use the Firefox bookmark management interface?
It offers significant advantages over the TST "Add bookmark" interface, like being able to create new folders, move bookmarks around, etc.
It would be really terrific if this could be done.

## Environment

 * Platform (OS): Linux Mint 22 Wilma base: Ubuntu 24.04 noble Cinnamon v: 6.2.9 tk: GTK v: 3.24.41 wm: Muffin v: 6.2.0 vt: 7 dm: LightDM v: 1.30.0
 * Version of Firefox:  Mozilla Firefox for Linux Mint mint-001 - 1.0 version 132.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab:  4.0.24 (2024.10.29)

**Comment by SHHSSH** [comment]
Heh... I wish. Check out bookmark search plus though, it's a pretty good add on.

**Comment by piroor** [comment]
Comparison of both dialogs

native:
![image](https://github.com/user-attachments/assets/d824fad1-0c14-4758-b9c9-b01d3f85cb50)

TST (note: the sidebar header bar should be hidden for a popup, it may be a bug of Firefox itself):
![image](https://github.com/user-attachments/assets/6fdafc9a-b702-4aa0-93b0-331c6552e7c4)

**Comment by piroor** [comment]
Analysis:

* Tags and keywords can't be added by TST due to restrictions of WebExtensions API, so we need to think only about creating new folders.
* Firefox's dialog just provides ability to create a new subfolder, and it is not removed via the UI. We need to use the bookmarks toolbar or something other UI to remove created folder.

**Comment by piroor** [comment]
I've updated the dialog implementation to simulate Firefox's bookmark creation dialog.
![image](https://github.com/user-attachments/assets/510c28e7-de12-4a1f-98d1-95d450120be5)
