### ISSUE TITLE
[Bug] [Duplicate of #3655] Group tab overview not working anymore

### ISSUE THREAD

**Issue by marekhanzlik** [piroor/treestyletab#3660]
## Abstract
When you click the group tab, normally you see new page with the list of all children. This stopped working.
Now there is just a loading icon and never finishes loading

## Steps to reproduce
Don't have any

## Expected result
Show the list of children tabs

## Actual result
Just a loading icon is shown indefinetely

It looks like it crashes in file `group-tab.js::274` on function `window.l10n.updateDocument();`. Because of unhandled exception, execution of remaining code is skipped.

Errors that pop up in console
```
l10s: apply title="__MSG_groupTab_options_dismiss__"
baseURI: "moz-extension://80bd9745-8010-4512-8035-2a9f72ffe0a6/resources/group-tab.html?title=ToRead"
childNodes: NodeList []
  length: 0
  <prototype>: NodeListPrototype { item: item(), keys: keys(), values: values(), … }
firstChild: null
isConnected: false
lastChild: null
localName: "title"
name: "title"
namespaceURI: null
nextSibling: null
nodeName: "title"
nodeType: 2
nodeValue: "Dismiss this hint"
ownerDocument: HTMLDocument moz-extension://80bd9745-8010-4512-8035-2a9f72ffe0a6/resources/group-tab.html?title=ToRead
ownerElement: <button id="dismissOptionHint" title="Dismiss this hint">
parentElement: null
parentNode: null
prefix: null
previousSibling: null
specified: true
textContent: "Dismiss this hint"
value: "Dismiss this hint"
<prototype>: AttrPrototype { localName: Getter, value: Getter & Setter, name: Getter, … }
l10n-classic.js:19:15


Error: tab.favIconUrl is null
```

## Environment

 * Platform (OS): Ubuntu
 * Version of Firefox: 132.0.1
 * Version (or revision) of Tree Style Tab: 4.0.24

**Comment by irvinm** [comment]
Duplicate of https://github.com/piroor/treestyletab/issues/3655. (Fixed already in dev builds)

**Comment by marekhanzlik** [comment]
Sorry for duplicate, looks like my search skills are poor :(  
Closing, thanks for the fix!
