### ISSUE TITLE
Add an option to set max nest level

### ISSUE THREAD

**Issue by ChipZhang** [piroor/treestyletab#3667]
When I open a link from a parent tab, the child tab is nested.
When I open the link n the child tab, the new tab further nested.
This means, in a normal web navigate, the nest level just soon becomes very large.

THIS IS RATHER ANNOYING!

I just need two levels: the parent the and all children tabs.
A tab opened in a children tab should not be nested further.

**Comment by piroor** [comment]
There is an expert option to limit maximum visual level of the tree. See the "Unlock Expert Options" checkbox and the "Appearance" section.

Please remind that TST constructs tree of tabs internally based on relations of tabs, even if you set the maximum visual level of the tree. Grand-child tabs of a child tab will be rearranged based on internal tree structure.
