### ISSUE TITLE
[Enhancement] Add right click menu option: ~"Send the content of all child tabs to [your configured LLM] along with this prompt:"

### ISSUE THREAD

**Issue by torevor** [piroor/treestyletab#3674]
When doing research on a topic, I will typically do a search and then open up 10++ tabs.  It takes a long time to read through all the tabs, so the ability to simply right click the parent (search) tab, enter a prompt for what you would like it to do with all of the content of the child tabs, and send all off this off to an LLM of your choice, and return the results in a new tab (ideally, the LLM itself, if that's possible) would be POWERFUL.

Another nice option would be the ability to highlight text in a page, and then send that off to an LLM, along with a prompt.

In both cases, the ability to click a microphone button to voice dictate the prompt would be a nice bonus, if that's possible.

I don't think anything like this exists out there at the moment.

**Comment by piroor** [comment]
I'm negative to add this feature as a built-in of TST, from some reasons:

* TST concentrates to provide basic features about tree management. Sending contents to LLM looks too far from the project purpose.
* Firefox provides `openerTabId` information and we can collect tree of tabs with regular WebExtensions way. This means that we can implement an addon providing this feature compatible with any tree-visual tab addons not only TST.

Here is a list of addons providing extra features to TST:
https://github.com/piroor/treestyletab/wiki/Helper-addons-extending-functionality-of-TST
It is welcome to list the new addon if you successfully implement the feature.
