### ISSUE TITLE
Replace F1 hotkey

### ISSUE THREAD

**Issue by 7OH** [piroor/treestyletab#3679]
This addon have not modificable hotkey F1 for show\hide tree.
More and more developers IDEs mirate to cloud and prograamers need to work in browser.
In IDE - F1 hotkey always binded for help (or Ctrl-F1).
So - we need ability to change F1 hotkey to user hotkey.
And (if possible) F2 in TST Bookmarks Subpanel plugin - too.

**Comment by piroor** [comment]
Did you try Add-on manager => Extensions => Tools for all add-ons (top-right gear button) => Manage Extension Shortcuts?
![image](https://github.com/user-attachments/assets/7b77b866-402b-4152-abc5-29bc185219cc)

**Comment by 7OH** [comment]
Thanks.
You opened my eyes.
So many years using FF and miss that ability.
