### ISSUE TITLE
[Bug] Scrollbar without steppers

### ISSUE THREAD

**Issue by osmin1** [piroor/treestyletab#3680]
## Abstract
After update from version 3.8.24 to the newest (4.0.25) steppers on scrollbars (buttons which scroll by only one line) disappeared. Is it a bug or a feature? I've noticed many projects "kill" steppers nowadays.
## Steps to reproduce

I have bunch of customizations, so I cannot really start with a clean slate, unless I export all the customizations and import them to a new profile, which would kill the purpose of clean install.
I've read styling guidelines which dealt with scrollbars, but there was nothing about steppers there.

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Expected result
Steppers to be present.

## Actual result
No steppers on scrollbars.
## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: Librewolf 133.0-3. -->
 * Version (or revision) of Tree Style Tab: 4.0.25

**Comment by piroor** [comment]
The default width of the scrollbar on TST is "thin" but thin scrollbar cannot have steppers on some environment (e.g. Windows 11) so you may need to use full width scrollbar.
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#show-scrollbar-with-regular-width

**Comment by piroor** [comment]
It looks to be "fixed" with customization, so I mark this issue as "wontfix".

**Comment by osmin1** [comment]
I didn't know. I will try your solution. Although it means in Windows 10 it is also the case - not just in Win11. :)
Thanks.

EDIT: Yes, it does work...
