### ISSUE TITLE
[Enhancement] Add additional loading options for dragged urls (e.g., load tab in background)

### ISSUE THREAD

**Issue by JeffreyMercado** [piroor/treestyletab#3682]
## Abstract

There are settings under the "More..." context menu that allows configuration when dropping a URL onto an open tab. Allows us to set whether we want to replace the tab it was dropped on, open a new child tab, or even switch to the new tab immediately.

Some times (most times) I want to drag a url from another external application to create the tab, but load it in the background (or unloaded but pending?) so no media plays. Usually this is YouTube links and I'm dragging video links, once the tab is created, it immediately starts playing. I want to be able to have the same settings when I open a new child tab from the parent window, only start playing when I switch to the tab (I do this to queue up videos to watch later).  I do _not_ want to disable autoplay for YouTube videos globally.

I want to have more control over how new tabs are created this way. And it seems like it's possible to prevent loading a tab completely based on other options (e.g., "Keep tabs pending (unloaded) when tabs are accidentally focused...").

![image](https://github.com/user-attachments/assets/e7c56351-030a-42a4-91c9-2156da04ae68)

![image](https://github.com/user-attachments/assets/86b99812-c638-41d1-b45e-2f2eb74680e3)

## Steps to see the situation

 1. Open youtube.com
 2. Drag any video on the home page to the sidebar

## Expected result

I should remain on the home page tab, a new tab is opened with the dragged url ready view (similar to middle/ctrl clicking). The video should _not_ be playing until I switch to it.

## Actual (present) result

I remain on the home page tab, a new tab is opened with the dragged url and starts playing.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 133.0.3 Stable
 * Version (or revision) of Tree Style Tab: 4.0.25

**Comment by piroor** [comment]
Hmm... Firefox's native tab bar has no such option (I researched https://searchfox.org/mozilla-central/rev/6f4bc07bd9eb07ed34774841ecf3b1f3678791e8/browser/components/tabbrowser/content/tabs.js#1167 and https://searchfox.org/mozilla-central/rev/6f4bc07bd9eb07ed34774841ecf3b1f3678791e8/browser/components/tabbrowser/content/tabbrowser.js#1947 ) so I have less reason to implement that from the project policy. But other hand TST has an expert option to open tabs with pending state from bookmarks. So it looks reasonable adding this option.

**Comment by piroor** [comment]
Done by 4983283.

**Comment by JeffreyMercado** [comment]
I may have closed this prematurely since it hasn't reached release yet, but the change looks good to me and it's just a matter of time until it's approved.
