### ISSUE TITLE
Firefox hangs

### ISSUE THREAD

**Issue by Zarniwhoop** [piroor/treestyletab#370]
Firefox keeps hanging for me at random odd intervals.It started doing this quite recently - perhaps in the last two weeks? At first I thought it was a recent flash player update but I updated and then even disabled flash player and firefox kept hanging. Today I decided to check all my add-onsand eventually came to the conclusion that TreeStyleTabs was causing it.

Firefox 15.01

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
