### ISSUE TITLE
Use weakmap to store data, instead of DOM Attribute

### ISSUE THREAD

**Issue by saneyuki** [piroor/treestyletab#372]
I seem that TST should use `WeakMap` to store some data instead of DOM Attribute.  It will be a little touch to the DOM tree. So it _may_ be fast.

My proposal:
- Use WeakMap to store some data.
- Add API methods to access their stored data.

What do you think about this?

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
