### ISSUE TITLE
Add a branch which develop for next ESR release.

### ISSUE THREAD

**Issue by saneyuki** [piroor/treestyletab#376]
I propose to add a new branch which develop for next ESR release.

If we introduce it, we will be able to develop gradually with new features that will add to next ESR.

**Comment by irvinm** [comment]
@piroor should we close this?

**Comment by piroor** [comment]
I gave up to support ESR60 on the master branch, and versions for ESR60 (TST 2.7) is not maintained anymore. I close this for now. After the ESR68 is released and I need to give up to support it, I should rethink about this.
