### ISSUE TITLE
Clear modules complex dependency

### ISSUE THREAD

**Issue by saneyuki** [piroor/treestyletab#377]
I think that the current design of tree style tab is complex. Some modules make complex dependency relations with `__proto__` property.

For expample:
- `TreeStyleTabBrowser` -> `TreeStyleTabWindow` -> `TreeStyleTabUtils` -> `window['piro.sakura.ne.jp'].prefs`

This will causes poor maintainability.  So we need to split this complex dependency relations.

I thought, 1st, we need to split `TreeStyleTabUtils` from `TreeStyleTabBrowser` & `TreeStyleTabWindow`. But some utility methods of `TreeStyleTabUtils` is using in their objects.

Thus, we should divide `TreeStyleTabUtils` into utility object and base object.
I think a plan to dividing.
1. Rename from `TreeStyleTabUtils` to `TreeStyleTabBase` (And also change the file name.)
2. Add new `TreeStyleTabUtils` & Move utility methods to it.

What do you think?

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
