### ISSUE TITLE
Firefox crash with TreeStyleTab and GreaseMonkey when a second FireFox window opens

### ISSUE THREAD

**Issue by haozhun** [piroor/treestyletab#378]
When I have a second FireFox window, e.g. "Open link in new window" or "File -> New Windows", FireFox crashes.

Through disabling and reenabling plugins, I figure out this happens only when both GreaseMonkey and TreeStyleTab are enabled.

FireFox version: 15.0.1
OS: Mac OS X 10.8.2

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
