### ISSUE TITLE
Torbutton and dragging

### ISSUE THREAD

**Issue by Gurtz** [piroor/treestyletab#382]
It seems that having Torbutton 1.4.6.2 enabled in Firefox 15.0.1 under Linux (Ubuntu 10.04) with Tree Style Tab  (0.14.2012081101) is causing drag and drop to not work. Tabs can not be dragged from one location to another. The rest of the plugin works (as the "Disable plugins during Tor usage" setting is UNchecked), but drag and drop will not work. I have not been able to work out which settings are causing the problem, but when Torbutton is DISabled, drag and drop works correctly. Thanks for a great plugin!!

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
