### ISSUE TITLE
annoying visual glitch appearing

### ISSUE THREAD

**Issue by kkira13** [piroor/treestyletab#383]
I use tree style tab in aero mode and personal titlebar to get this look, and when I do so, an annoying line appears, which you can see in image. Once I messed with tree style xpi and it disappeared, can you please tell me where can I find the parameter for that line, so I can remove it ?  

http://www.imagebam.com/gallery/wh3aef2ey5chbaofhn4o71tu4ojrdlsa/

http://101.imagebam.com/download/9AV3wl3qMFQKWcwgdnx8Lg/21295/212948350/PIC1.jpg

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
