### ISSUE TITLE
Feature Request: Support for Firefox Tab Groups (Panorama)

### ISSUE THREAD

**Issue by FunkMonkey** [piroor/treestyletab#388]
It would be nice if TreeStyleTab could support [Firefox Tab Groups](http://support.mozilla.org/en-US/kb/tab-groups-organize-tabs) (or Panorama as it was once called).

Tab groups would provide a secondary hierarchy that allows easy switching between visible tabs. 

TreeStyleTab could show the list of existing groups above the tabs or at the bottom.

Showing tab groups should probably be optional as not everyone uses / is aware of this firefox feature.

**Comment by piroor** [comment]
The Panorama feature will be removed on Firefox 45. So, this will also be just a compatibility issue with another addon https://addons.mozilla.org/ja/firefox/addon/tab-groups-panorama/ , not an issue around Firefox's built-in feature.

**Comment by piroor** [comment]
Because I don't use the feature anymore, I have less motivation around this issue...

**Comment by piroor** [comment]
Anyway, buttons to switch groups is not a target of TST - it should be done by the Tab Groups addon or others. I close this to triage.
