### ISSUE TITLE
Tabs go missing

### ISSUE THREAD

**Issue by macaddict06** [piroor/treestyletab#390]
Every so often (particularly if FF has been open for a few days), the tabs start to act very funny. Eventually, new tabs will not show up on the sidebar (as opposed to appearing at the bottom, as they should), and those withing a hierarchy are no longer visible (even when clicking the arrow to display them). Strangely, they can still be navigated to using the cntrl+tab/cntrl+shift+tab method and everything works fine.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
