### ISSUE TITLE
Visual glitch in a form of a vertical bar.

### ISSUE THREAD

**Issue by kindaro** [piroor/treestyletab#392]
It is exactly twice as far from the side of the screen as the right edge of the tree tab bar, and it behaves similarly in the respect that dragging it does resize the size of the tree tab bar, the distance between the glitch and left side of the screen remaining twice as wide as between the right side of the tree tab bar and left side of the screen. The glitch doesn't have the button that toggles visibility of the tab bar though, and it's a bit thinner, apparently.
This is how it looks like:
http://postimage.org/image/rzlygyk9p/
(the glitch may be seen clearly right over the text).

It appears when I use javascript to toggle the bar via keyboard, as described in this issue
https://github.com/piroor/treestyletab/issues/156
(with a bit of a difference in that I've changed nnoremap command into map -d as the former is currently deprecated and not supported in pentadactyl, and my hotkey is C-A-Tab).

I have all my other add-ons, except pentadactyl, switched off, and the problem still remains.
Firefox 16.0.1, TreeStyleTab 0.14.2012081101

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
