### ISSUE TITLE
TST incompatible with "How Many Times Can I Back"

### ISSUE THREAD

**Issue by private-lock** [piroor/treestyletab#397]
TST 0.14.2012081101 -> http://piro.sakura.ne.jp/xul/_treestyletab.html.en
How Many Times Can I Back? 0.2.2011012001 -> http://piro.sakura.ne.jp/xul/_historycounter.html.en
- The indicator triangel changes to + button and moves to the right of the tab next to the close button.
- Clicking anywhere on the tab makes the childlist fold. Only the tiny number indicator (3) for the number of children will activate the tab itself.
- Middle-Click on links appends Tabs to the end (not as expected as a child)
- There were errors in the console from TST-code

**Comment by wsmwk** [comment]
@private-lock is this not a duplicate of issue 261 ?

**Comment by private-lock** [comment]
Phewwww... this is 4 years old. I admit, I don't recall exactly ... for now, I'd close it as a duplicate, since #261 is about older versions anyway and superseded by this.

Looks like I should give HMTCIB another try ...

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
