### ISSUE TITLE
16.02: crashes bookmarks

### ISSUE THREAD

**Issue by Swaenaar** [piroor/treestyletab#398]
I just spent 4 hours trying to find out which of my 137 installed add ons was causing Firefox to freeze whenever I wanted to bookmark a page/browse through my bookmarks. I even created a COMPLETELY NEW PROFILE (that is a lot of work if you have a lot of extensions with their settings...), I even reinstalled Firefox; nothing. Finally, it turns out this extension is causing it (can you imagine disabling 137 extensions and then testing which one is causing the problem?). 

- Bookmark a tab: firefox freezes
- Open all bookmarks and click one (or a folder): firefox freezes.

Note, of course, I isolated the problem to this extension by all other 136 being disabled.

Can't use my firefox with this extension, so uninstalled it. Too bad, because the idea is great and when working would definitely gotten a donation from me for a cup of coffee and some cake.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
