### ISSUE TITLE
after upgrade to firefox 16.0.1 stopped functioning

### ISSUE THREAD

**Issue by mirkobern** [piroor/treestyletab#402]
after a browser restart that upgraded firefox to 16.0.1 the addon stopped functioning completely as if it's not installed.

firefox 16.0.1   on fedora 16  

i tried to disable and reenable the addon, restarted firefox many times between them but to no avail.

i manually upgraded  tree style tab  to the latest release on site,  the 14.0.2012111201,
but nothing changed...

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
