### ISSUE TITLE
Pinned tabs are too small

### ISSUE THREAD

**Issue by FrzMe** [piroor/treestyletab#403]
Using tree style tabs 0.14.2012111201 with Firefox 17 (beta channel - built from http://hg.mozilla.org/releases/mozilla-beta/rev/036da70b61f9 ) my tabs on the right the pinned tabs are displayed slightly too small (too narrow and too short) as seen here: http://i.imgur.com/NiNh0.png (Standard tab style)

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
