### ISSUE TITLE
Tabs no longer showing

### ISSUE THREAD

**Issue by delgado92651** [piroor/treestyletab#407]
Love your extension, all of a sudden TST started having major problems, can not longer see tabs at all. I am using FF 16.0.2.
 
 Problem seemed to start with version 0.14.2012111001, I went back to version 0.14.2012081101, which seemed to fixed problem for awhile, all of a sudden the problem reappeared yesterday, in a slightly different form, now I can see the tabs on the side but maybe only 2 to 3 pixels of the tab. Cannot read anything on the tab. Tried updating to  0.14.2012111201, back to old problem. Same problem on desktop and my laptop, both running Win 7. Any suggestions.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
