### ISSUE TITLE
Impossible to drag&drop two-tab group onto another tab

### ISSUE THREAD

**Issue by jaens** [piroor/treestyletab#409]
With the new "blank space" animation:
When dragging a group of tabs, it's impossible to drag&drop two tabs (one parent, one child) into another, single tab (to make them a child of that tab)

The single tab just keeps jumping to be either before or after the two tabs, never offering a possibility of dropping the two tabs ON the single tab.

The underlying cause is the same as for issue #399 probably.

(theme: Plain, animation effects: disabled)

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
