### ISSUE TITLE
100% cpu problem with all released FF versions (possibly fixed!?)

### ISSUE THREAD

**Issue by aardvark2zz** [piroor/treestyletab#412]
TST is the best addon and is the MAIN reason I stay with FF. CONGRATULATIONS.

It seems to have cleared itself with the latest FF official TST 0.14.2012111201 and RES 4.1.5 which were updated around the same time (also FF went to 17.0) a few days ago (on my pc).

I suspect it has something to do with thumbnail state/update !?

I've had this 100% cpu problem for more than 6 months with all released FF versions up to FF 16.0.2.  It wipes out a laptop battery.

The problem occurred with the TST and RES* (Reddit Enhancement Suite) addons enabled and consistently when I would do the following : (Note * : Problem occurs with both RES addon or RES greasemonkey script !)

- Open reddit.com in a tab with 100 titles (and make the images visible)
- Open more than 5 of the comment threads in new (hidden) tabs until FF uses >700 MB of RAM (I have 4 GB)
- CPU goes to 100 % forever until I move away from the reddit.com tab to any other tab.

If I go back to the main reddit.com it will most likely go back again to 100% cpu as I scroll down. To stop it I have to go away from this main reddit.com tab.

edit: This seems to apply only with the main reddit.com page. (also with reddit.com/top/)

With ALOT of tedious poking around, for months, using JIT Inspector and Gecko Profiler to look around. I have the following notes ...

This also happens with a new profile with only the addons mentioned here.

I'd rather you ask me questions than me ramble on.

I have a Gecko Profiler 5 MB file that I can submit later.  Vista 32, A/V off, AERO off, SuperFetch off, FF disk cache using RAM.

The following are 9 print-screen images of JIT Inspector : 
Image numbers : 19 to 71 in increasing order, 
with 19 being the expanded details at the top of JIT Inspector, 
and 71 being the expanded details of the bottom of JIT Inspector.

http://imgur.com/a/cSe3u/

Edit: spelling and added note *
...

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
