### ISSUE TITLE
TabMixPlus conflict with tree on top

### ISSUE THREAD

**Issue by gkuenning** [piroor/treestyletab#414]
I previously reported (not via Github, I think) that when the tab bar is on top, tree tabs don't collapse properly.  I discovered today that this is caused by a conflict with Tab Mix Plus: when TMP is enabled, TST doesn't shrink the tree, but when TMP is turned off, TST works "right" (i.e., the way I suspect the author intended and the way I like).

More specifically,  the problem when TMP is enabled is that the tabs to the right of the tree root keep  their width, but have their title text replaced by a very pretty gray gradient, instead of  being made very narrow.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
