### ISSUE TITLE
false dragstart

### ISSUE THREAD

**Issue by LexLuxus** [piroor/treestyletab#415]
when one has many tabs, and / or computer is slow, a click on a tab fires onDrag().
Given the circumstances, I don't think there's an easy fix, other that disabling the tab dragging as an option. Maybe double click activates dragging or something.
Currently this behaviour is very annoying, as I am loving this extension for many years now! I can't live without it!

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
