### ISSUE TITLE
When I close a tab, TT change the tab group.

### ISSUE THREAD

**Issue by LBdN** [piroor/treestyletab#416]
If I have two tabs group, if I close a tab in one of them, the other tab group get loaded with some but not all tabs from the first group. It seems to happen if, before I move tabs from tabs from one group to another.  It is really painful to see the tabs I have logically sorted by group to move back to their old one, in a semi-chaotic manner. 

The behavior is not automatic, and I don't see what really triggers it. Some hidden state is clearly not updated, but I cannot say more. 

My version is FF17.0/Linux/32bits. But it also happened with the older version of FF. Just didn't report it before.

L.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
