### ISSUE TITLE
Open child tab error

### ISSUE THREAD

**Issue by her34** [piroor/treestyletab#418]
Firefox 17
Tree Style Tab 0.14.2012111201
Tab Mix Plus 0.4.0.3.1 
QuickDrag 2.1.3.23 

If you open a link in a new tab using right click menu on link, the new tab opens correctly as a child tab.

If you drag link to open, the new tab appears incorrectly as a parent tab.

This problem does not happen in Firefox 16 with same extensions.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
