### ISSUE TITLE
Thin white line appearing on the top of the window.

### ISSUE THREAD

**Issue by Imfego** [piroor/treestyletab#427]
What steps will reproduce the problem?
1. Combo of TST + Hide Caption Titlebar Plus + Total Toolbar is installed;
2. all the toolbars (address bar, bookmark bar, etc) are relocated to the bottom of the Firefox window;
3. in TST, any non-default Tab Bar skin is selected.
- - - - -
What is the expected output?

Clean display of top sections for all website in Firefox window.
- - - - -
What do you see instead?

An artificial thin white line in the top of the window, especially visible when the web page’s top section  is not white.
- - - - -
System info:

* TST 0.14.2012122901 
* Firefox 17.0.1
* Windows XP, SP3

- - - - -
Additional comments:

Problem is that when non-default styles in TST are activated, a thin white horizontal line is being displayed at the top margin of the window. It looks very ugly and ruins the visual experience of the topless window that I am trying to create and goes away only if the default Tab Bar skin is selected in TST.

Pics 1-3: WIth non-default style activated (whit line visible):
![Screenshot_1](https://f.cloud.github.com/assets/2667134/35117/6b42ed74-51a1-11e2-892d-0527453c3ff0.png)
![Screenshot_2](https://f.cloud.github.com/assets/2667134/35118/6b441708-51a1-11e2-9ce6-42bf2aa9c09f.png)
![Screenshot_3](https://f.cloud.github.com/assets/2667134/35119/6b46ba62-51a1-11e2-925c-ec610b4de338.png)
Pic 4: default style chosen, line is gone:
![Screenshot_4](https://f.cloud.github.com/assets/2667134/35120/6b6b8a18-51a1-11e2-9b65-49d4cc3bdd2f.png)

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
