### ISSUE TITLE
Wrong scrollbar since FF18

### ISSUE THREAD

**Issue by Tragen** [piroor/treestyletab#448]
Since FF18, the scrollbar for the tabs draws incorrectly while I scroll.
The normal window scrollbar works. I tried it with
a fresh installation and it's the same. Anybody else with this problem?

![tst](https://f.cloud.github.com/assets/1700241/63132/6c1d66ac-5db8-11e2-93f9-33cc5971704e.png)

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
