### ISSUE TITLE
"Bookmark Dialog" does not show sometime

### ISSUE THREAD

**Issue by mrkingmidas** [piroor/treestyletab#451]
"Bookmark Dialog" ("Star" press open this) sometimes does not show. Display dialog can return if TST "off", restart FireFox, "on" TST, restart (simple FireFox restart does not help). For some time the dialogue appears, then it repeats again

**Comment by Anbcorp** [comment]
Hi,

I can confirm this bug with the latest release of both your plugin and firefox 39. The bookmark button (the star) works only to add a bookmark and doesn't pop the dialog. And it doesn't act as a toggle switch either (one can only add a bookmark, not remove it, using the star button).

Same behaviour with ctrl+d.

Thanks for your help,

**Comment by romainfun** [comment]
dup #887

**Comment by piroor** [comment]
Can I close this as a dup of #887?

**Comment by Anbcorp** [comment]
I think so, the fix for #887 fixed this for me
