### ISSUE TITLE
For middle click on hyperlink, open new tab as a sibling of the current tab.

### ISSUE THREAD

**Issue by Balfa** [piroor/treestyletab#452]
I think the New Tabs options screen should have a setting called:
"For middle click on hyperlink, open new tab as [DropDown]", with the usual choices in the dropdown.
With "hyperlink" being any link on a page

It may seem like this is removing the core functionality of Tree Style Tab altogether, but I prefer to use the tree 100% manually. I.e., if there are tabs I want grouped under another, I'll group them myself, otherwise, everything should be a sibling.

Thanks for the great addon!

**Comment by piroor** [comment]
For now I have no plan to add more options for this situation, sorry. If you want to open the link in new sibling tab, please do it by dragging a link and drop it onto a tab or between tabs.

**Comment by piroor** [comment]
I close this for triage.
