### ISSUE TITLE
Tab Utilities makes the TST tabs unreadable unless Tab Utils *also* set to have tabs on left.

### ISSUE THREAD

**Issue by DavidRosen** [piroor/treestyletab#455]
With TST and Tab Utilities installed, I see (not consistently) the tabs appearing on the left where they should, *but* each tab is rotated so that it is very tall and too thin to read.  Seems to happen somewhat more consistently if I am also using Vertical Toolbar.  Sometimes starts happening only after I do a Customize... in a given session.

Workaround: tell Tab Utilities to put the tabs on the left as well (took a long time to find this workaround).

TST 0.14.2012122901
"Firefox 17" (actually PaleMoon variant)
Windows 7/WoW64

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
