### ISSUE TITLE
Tree's scrollbar style is wrong since FF20 beta1

### ISSUE THREAD

**Issue by constb** [piroor/treestyletab#467]
I'm used to having a thin scrollbar in tree on the left. Unfortunately, after I updated from FF19beta6 to FF20beta1, it's now a windows standard thick bar on the right.
![tstbug](https://f.cloud.github.com/assets/1006766/187794/14a804d4-7d90-11e2-88bc-4ba24b39f23e.png)

This issue complements tree rendering issues #436, #462 and #464.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
