### ISSUE TITLE
open in new window behavoir

### ISSUE THREAD

**Issue by muescha** [piroor/treestyletab#472]
**What i have:**
- a parent item with childs

![Bildschirmfoto 2013-03-02 um 14 48 32](https://f.cloud.github.com/assets/184316/212905/5fab1114-8340-11e2-93c1-2b40d48681c8.png)

**what i do:**
- i drag the parent and move a little around. i can see while i drag that there is the parent AND the childs are moving

![Bildschirmfoto 2013-03-02 um 14 45 04](https://f.cloud.github.com/assets/184316/212906/7486590e-8340-11e2-881b-d6fb186350f7.png)

**then i do:**
- i drag it outside of the window

**what i get:**
- the parent tab is opened in a new window

**what i expected:**
- the parent tab AND the child tabs are opened in a new window

**Context menu**

the same expectation (move the tree to a new window) i had with the context menu command "open in new window" (because i know the tree while dragging)

maybe add a new command for context menu: "open tree in new window"

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
