### ISSUE TITLE
[feature request] Keyboard shortcut to toggle complete tree tab bar

### ISSUE THREAD

**Issue by kaushikgopal** [piroor/treestyletab#476]
Issue #156 hints at this feature. I would like to have a keyboard shortcut to toggle the visibility of my tab bar.

Currently there is a "hold Ctrl key for x msec" option which works fine, but a toggle "sticky" like behavior would be really nice.

So for example hitting Cmd+Alt+T will hide/show the tab bar. 

Advantage 1: If i'm a keyboard junkie i don't have to wait for xmsec as i'm constantly switching tabs.
Advantage 2:On OSX holding Ctrl and then clicking anywhere activates the right click of my mouse which gets mildly annoying.

Loving Treestyle tabs btw. Rock on!

**Comment by piroor** [comment]
Now code snippets for keyboard customization addons are available: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-keyboard-shortcuts
