### ISSUE TITLE
[Feature Request] Always shown tabs overlaying the webpage

### ISSUE THREAD

**Issue by VivienV** [piroor/treestyletab#477]
Is it possible to make it so that the tabs do no push the webpage to the side when always shown?

If you set the tab bar to hidden, it will be displayed over the webpage. Is it possible to have that behavior when setting it to always show?

I browse in a widescreen monitor, so there is always lots of blank horizontal space. The tab bar would very very rarely display over actual content, so it makes sense that instead of pushing the webpage to the side, it actually displayed the tab bar over it.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
