### ISSUE TITLE
Bookmark library becomes unresponsive with large number of bookmarks

### ISSUE THREAD

**Issue by cryptobear** [piroor/treestyletab#478]
When there are a large number of bookmarks in the bookmarks library, attempting to click on a bookmark from the bookmark library window causes Firefox to look up and there are frequent alerts that chrome://treestyletab/content/bookmarksOverlayEditable.js is not responding. Without TST, the bookmarks library is very snappy no matter how many bookmarks are displayed. The search/filtering works at full speed, but any attempt to actually click a bookmark in the library window causes the aforementioned lock up.

Thanks in advance for anything you can do to troubleshoot this! :)

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
