### ISSUE TITLE
[meta] strict mode compatibility

### ISSUE THREAD

**Issue by saneyuki** [piroor/treestyletab#482]
We need to increase the compatibility for strict mode. Because:
- Gaze ECMAScript.next
- Increase the code maintainability.

**Comment by lv7777** [comment]
I suggest using lint option(e.g. ESLint,JSLint).

**Comment by piroor** [comment]
Is it done automatically by Travis.CI or something?

**Comment by lv7777** [comment]
Oh... That never crossed my mind.
It sounds good.

relate #104

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
