### ISSUE TITLE
consistent behavior when Closing tabs

### ISSUE THREAD

**Issue by mjm716** [piroor/treestyletab#483]
Fantastic addon! One request/functional issue:

Usually on a child tab, the behavior is clear - close child and focus goes to parent.

However on orphan/single tabs, when closing the focus jumps ?randomly? elsewhere, often to a tab within another group, even if that group was previously closed

Can the behavior be consistent? 
e.g. closing a tab always puts focus on tab directly above?

**Comment by digital-carver** [comment]
I'm seeing a variant of this, in that there *is* consistent behaviour in my case, only not the behaviour I would like. Whenever I close a tab (that is neither parent nor child), the focus goes to the **next** tab in order (downwards), whereas I would prefer it to go to the **previous** tab in order (upwards). 

Is there a config option that controls this?

**Comment by piroor** [comment]
Basic logic of next focused tab when the current tab is closed is:

 * If the tab was opened from a link (or something) and focused automatically as a foreground tab, then back to the original tab. This is a built-in feature of Firefox itself, not of TST.
 * If the tab had any child, focus to the first child (except when you choose the "close all children" option when a parent tab is closed.)
 * If the tab had no child and there is a next sibling tab, focus to the next sibling.
 * If the tab is the last child of a parent, focus to the parent.

However, if there are any other tab related addon, the behavior can be modified.
