### ISSUE TITLE
Make compatibility for removed the ability to not 'Always show the tab bar'

### ISSUE THREAD

**Issue by saneyuki** [piroor/treestyletab#486]
Firefox 23 removes the ability to not 'Always show the tab bar': https://bugzilla.mozilla.org/show_bug.cgi?id=855370 (http://hg.mozilla.org/mozilla-central/rev/b0e27a5ae2b6).

I grep-ed TST repository, there is some codes which might be related to 'Always show the tab bar'. We need to make the compatibility for it.

**Comment by piroor** [comment]
Done by c901a1ce82a7f3aba32c4d5dce4e0195e0e3c7d9
