### ISSUE TITLE
Cut-off thick scroll bar with sidebar style on Windows

### ISSUE THREAD

**Issue by FichteFoll** [piroor/treestyletab#494]
Well, to be honest I can't even remember how long this issue existed for me or whether it has always been there but I now came to the conclusion that it's rather annoying. So, I'll let the screenshots explain which I took with a newly created FireFox 21b profile and TST 0.14.2013040601:

![sidebar](http://i.imgur.com/n3RGuZX.png)
As you can see, the scroll bar is cut-off to be somehow "slim" but it actually shows the standard thick Windows sidebar instead which looks off.

Then, when opening the tab popup by clicking that down arrow this is what I get:
![popup](http://i.imgur.com/CVCFS4v.png)
This looks okay you might say but when I scroll on that view the scroll bar does not behave like it should. I can't really explain it but instead of, like, moving downwards when I scroll downwards it moves in the opposite direction. If you can't reproduce this I can record a screencast or similar to visualize it.

I'm not too sure if the second issue here is somewhat related but I'll gladly try to help you gather information if you need any.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.

**Comment by FichteFoll** [comment]
I'm still seeing this with 0.16.2015122501 on FF44.

![2016-02-12_14 37 37](https://cloud.githubusercontent.com/assets/931051/13008388/53197bbe-d196-11e5-93ef-4ffdffa36232.png)

**Comment by piroor** [comment]
OK, but it can't be fixed for now - firefox doesn't shrink scrollbar buttons with native appearance for narrow scrollbars. To Fix this "bug", I'll have to provide completely custom CSS rules to define appearance of scrollbar related elements just for the single narrow scrollbar in the tab bar. As my comment https://github.com/piroor/treestyletab/issues/240#issuecomment-183332275 it is painfully hard work for me...

**Comment by piroor** [comment]
Fixed by recent commits.

**Comment by FichteFoll** [comment]
Thank you!

**Comment by FichteFoll** [comment]
I assume the intended fix is to center the scrollbar in the space available? Because that's how it looks for me now. That's probably the best solution to this issue, at least on my side.

I'm currently running into #1072 because of a color override (as can be seen in the above screenshot), but I hope this will still look good once the fix gets shipped.

**Comment by piroor** [comment]
Finally I combined both method, old (setting max-width) and new (centering with negative margins). The scrollbar itself and its contents are now narrowed by max-width. Scroll buttons on Windows cannot be narrowed by max-width, so they are now centered by negative margins (dynamically calculated). And one more trick, overflow-ed scroll buttons by negative margins are now clipped by CSS3 clip-path with an SVG rectangle mask.
