### ISSUE TITLE
[Feature Req.] Reload Parents

### ISSUE THREAD

**Issue by ldgbc** [piroor/treestyletab#495]
There is already an option to reload children, but no way to reload parent.

The way I use tree style tab is children tab are usually close when I am done with them, and do a refresh on all the parent tab for update/new thing. Currently reloading of parent must be done individually.

**Comment by piroor** [comment]
I've added a [code snippets](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-keyboard-shortcuts) to do it.

```javascript
TreeStyleTabService.getAncestorTabs(gBrowser.selectedTab).forEach(function(aTab) {
  gBrowser.reloadTab(aTab);
});
```

I have no plan to add such a feature to TST but you can do it via TST's API for other addons. Some addons which provide ability to define custom command with JavaScript will help you.
