### ISSUE TITLE
Proposal: Use Timer.jsm which is buit-in Firefox module.

### ISSUE THREAD

**Issue by saneyuki** [piroor/treestyletab#498]
At Firefox 22 later, Firefox got Timer.jsm which provides setTimeout/clearTimeout functions.

* https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Timer.jsm
* http://mxr.mozilla.org/mozilla-central/source/toolkit/modules/Timer.jsm

I think that we can replace `modules/lib/jstimer.jsm` with `Timer.jsm` on next ESR-24.

How about do you think?

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
