### ISSUE TITLE
Turn off tab animations

### ISSUE THREAD

**Issue by onlbk** [piroor/treestyletab#499]
Tree Style Tab is great but you added tab animations that really ruins Tree Style Tab. It is a really bad idea to have a user interface target around. This isn't a videogame, keep things simple.

Please turn off tab animations

**Comment by stiv-sigmal** [comment]
But due to tabs’ animation it's impossible to include one tab (or tab-tree) into other! I try to drag one tab to other, but see only animation of dragging tab onto other and returning it back. Or swapping these tabs. I try hard dozens of times, but that is not work!

**Comment by piroor** [comment]
See also: [556717 – about:config option to disable chrome animations](https://bugzilla.mozilla.org/show_bug.cgi?id=556717 "556717 – about:config option to disable chrome animations")

**Comment by piroor** [comment]
I close this for triage.
