### ISSUE TITLE
Tab Bar Position 'left side' does not work

### ISSUE THREAD

**Issue by ursus-pastor** [piroor/treestyletab#502]
Hi, 

when setting the Tab Bar Position to 'left side' under Options -> Appearance all tabs are collapsed to one point - 

changing it to another position (e.g. 'right side' ) and back fixes it - it is somewhat annoying though - 

I am using ff 20 (build 20130326150557) and tst 0.14.2013040601 

let me know if i can post any further info - thanks -

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
