### ISSUE TITLE
Tab Bar doesn't scroll when Facebook is the selected tab

### ISSUE THREAD

**Issue by mb247** [piroor/treestyletab#507]
Hi,
If auto hide tab bar completely or partly is selected and the active tab is Facebook,
scrolling in the tab bar when the mouse is over it doesn't work. You have to use the Scrollbar.
This happens always on Facebook. Most other tabs and websites seems to work ok, so far. Needs more testing.
It seems there is a problem with the mouse focus.

My System:
Macbook Pro with OS X 10.6.8
Firefox 20.0
Tree Style Tab  0.14.2013040601

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
