### ISSUE TITLE
Need to research the influence by removing window.__SS_*

### ISSUE THREAD

**Issue by saneyuki** [piroor/treestyletab#508]
- [867097 – Remove re-use of __SS_data, and the superfluous __SS_tabStillLoading property](https://bugzilla.mozilla.org/show_bug.cgi?id=867097)
- [867118 – Remove browser.__SS_data and use a WeakMap instead](https://bugzilla.mozilla.org/show_bug.cgi?id=867118)
- [868026 – [Session Restore] Remove window.__SS_dyingCache and replace it with some appropriate use of WeakMap](https://bugzilla.mozilla.org/show_bug.cgi?id=868026)

We need to research the influence by these changes.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
