### ISSUE TITLE
[Feature Request] Combining trees to a new parent based on title / url keyword matches

### ISSUE THREAD

**Issue by chwt** [piroor/treestyletab#509]
I am thinking of a possibility to easily group / combine trees of a Firefox window: The user specifies a grouping keyword. The treestyletab add-on then creates a new tree into which all trees of which **its parent** matching the keyword, e.g. in the title and/or URL, are **moved**.
The resulting new tree could be previewed in a dialog window.

Further, an undo is simply done by removing the newly created dummy parent.

**Comment by piroor** [comment]
I close this for triage.
