### ISSUE TITLE
Vertical tabs move to the left while tab 'viewport' moves to the right

### ISSUE THREAD

**Issue by ripdog** [piroor/treestyletab#513]
Screenshot: ![tst bug](https://f.cloud.github.com/assets/174944/563961/f9061c82-c52b-11e2-8297-17d9f55f72d1.jpg)

As you can see, it appears that the canvas on which the tabs are placed has randomly grown greatly to the right - and the view shifts off the tabs.

Bug does not occur reliably - just happens on a random interaction of any kind with the tabbar, typically after Firefox has been open for hours, but time period appears to be random.

This is a mild version of the bug, often it will move to the point I can't see any of the tabs. The click target for the tabs always extends the full size of the viewport, so I can still click them. 

When I click a different tab (does not happen with ctrl-tab or anything else afaik), the viewport toggles between leftmost and rightmost - in effect, the tabbar becomes visible or invisible. When visible, looks like this: (note the reduced margins on the left)
![tst bug 2](https://f.cloud.github.com/assets/174944/563973/fe19c2cc-c52c-11e2-92b9-0c64a18e9f86.jpg)
When bug is NOT occurring: (note normal margins on left)
![tst bug 3](https://f.cloud.github.com/assets/174944/563972/f74a9048-c52c-11e2-9195-9aab9e85f882.jpg)
I know some CSS, (and I'm running my own theme, as you can see) so I've been trying to fix or at least pin down the cause of this for a while. I have set max-width to 207px for every relevant element I could find in DOM inspector, with no luck. (I mean I found the elements in the inspector then added max-width rules to my css.)

Bug occurs with or without my theme. I run hundreds of tabs (mostly unloaded) in quite complex trees, so that may be a contributing factor.

These are some sample box models for two tabs - they have some very high numbers and very low numbers, I don't know if this is normal.

![tabmodel1](https://f.cloud.github.com/assets/174944/563959/ee09f434-c52b-11e2-9b63-82d9e3ef5782.jpg)
![tabmodel2](https://f.cloud.github.com/assets/174944/563960/ee35eb34-c52b-11e2-8944-e0471fbb9939.jpg)

BTW piroor I love you, your addons, and your english is awesome! Thanks in advance.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
