### ISSUE TITLE
Add option to disable scrollbar

### ISSUE THREAD

**Issue by ripdog** [piroor/treestyletab#514]
I simply scroll my tabs with my mouse wheel, so the scrollbar is both ugly and unnecessary. It's already possible to remove the scrollbar, by setting `extensions.treestyletab.tabbar.narrowScrollbar.size` to 0.1px (0 breaks it for some reason).

I think a GUI option for this would be nice for less technical people.

**Comment by joeytwiddle** [comment]
An alternative way to hide the scrollbar is to visit [about:config](about:config) and set

`extensions.treestyletab.tabbar.narrowScrollbar.size` to `0.10px`
