### ISSUE TITLE
Installed TreeStyleTab But it Won't Show Up???

### ISSUE THREAD

**Issue by montanakyle** [piroor/treestyletab#516]
I have installed the TreeStyleTab addon, also have installed a few other addons and I notice this one and some others are not showing up? I have used this in the past but I have not used firefox for 6+ months and am coming back from Google and notice some of my addons are not showing up even though they are enabled and I have the latest update of Firefox. And they are showing as compatible. So am I missing something here???

Thanks for any assistance you can lend.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
