### ISSUE TITLE
Tabs not opening nested in current Firefox Aurora (23)

### ISSUE THREAD

**Issue by lsblakk** [piroor/treestyletab#517]
Hi, 

I use tree style tabs and in the past week I've noticed that out Bugzilla "open all in tabs" no longer opens all the tabs nested under the originating tab. Instead the first tab opens nested and the rest open at the same level as the originating tab.  Obviously this throws off the intent of how I use the addon.  Not sure if this is an addon bug or a Firefox side bug.

STR:
1. Have a bugzilla.mozilla.org account
2.  Have both the https://addons.mozilla.org/en-US/firefox/addon/bugzillajs/ and tree style tabs extensions installed
3. Do a bug search like https://bugzilla.mozilla.org/buglist.cgi?cmdtype=dorem&remaction=run&namedcmd=approval-beta%3F&sharer_id=272375&list_id=6731292
4. Click on "open all in tabs" from the bottom footer options

Expected results:
all the bugs open, nested, under the search results tab

Actual results:
first bug opens nested, the others open at same level
![screen shot 2013-06-05 at 3 16 35 pm](https://f.cloud.github.com/assets/208595/614078/7ab75598-ce14-11e2-9620-59880bf4a507.png)

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
