### ISSUE TITLE
drag'n'drop to Collapsed tab group

### ISSUE THREAD

**Issue by LordRaahhh** [piroor/treestyletab#519]
If I drag a tab to a collapsed tab group the moved tab does become a child, however it is still visible.

Example:
Tab A (Shown)
Tab B (Group/Collapsed)
--Child 1 (Hidden)
--Child 2 (Hidden)

Dragging Tab A to Tab B results in:
Tab B (Group/Collapsed)
--Child 1 (Hidden)
--Child 2 (Hidden)
--Tab A (now Child 3/Shown)

I would expect Tab A to be hidden as well. I have auto expand/collapse off. 

Using Current TST on TenFourFox 17(Firefox ESR17)

**Comment by piroor** [comment]
Seems expired. Now TST always expands a collapsed tree when a new child is attached.
