### ISSUE TITLE
Restoring session screws tabs order

### ISSUE THREAD

**Issue by mkravchuk** [piroor/treestyletab#532]
Hi,

I have found issue. With disable plugin TabMixPlus this issue want happend, i will post this to them, but if this can help to improve communication with TabMixPlus plugin i will leave my findings.

---

I didnt find the way to debug plugin, so after 1.5 days try and fail aproach i'm hapy 
  to provide at least close infomation of the place where issue happend :)
Also, this issue happend to me before, and usualy when i have lot of tabs.

Issue consist in unwanted moving one of the root tab to wrong position as child tab of another tree.
And when issue once happend, this unwanted move is happening all the time when firefox is restarted.

I have found that this problem cause by function 
  _restoreTabPosition : function TSTBrowser_restoreTabPosition(aTab, aNextTab) 
  {
  } 
in file "browser.js".
Avoiding execution of this function will fix the problem.

I'm sending sessionstore*.js to test issue.
Issue is 100% reproducable for versions of firefox 14,21,22.

I recommend to test with second file sessoinstore_2.js.
Correct behaviour will be when root tab "Twitter Bootstrap" stays as it root position.
Wrong, when it will became child for the tab "Node".

---

-- File Details --

Folder "xml" store xml versions of sessionstore*.js files, for easier comparission.
correct-and-incorrect-processing.png - simple issue description.
detailed.png                         - detailed issue behaviour.
copysession.bat                      - copies session, and deletes firefox plugins cache

---

-- Steps to reproduce issue --
1. Copy file "sessionstore_1.js" to Firefox profile folder as "sessionstore.js"
2. Open Firefox 
3. Check position fo tab "Twitter Bootstrap" - it has to be root tab.
4. Restart Firefox 
5. Re-Check position fo tab "Twitter Bootstrap" - tab is moved to wrong position.

---

SORRY THAT I CANNOT ATTACH sessionstore_2.js BECAUSE OF GITHUB LIMITATION - PLEASE CONTACT BY BY EMAIL ! 
IT SAYS: "Unfortunately we don't support that file type yet. Please use PNG, GIF, or JPG."

mkravchuk@gmail.com
Miro

![correct-and-incorrect-processing](https://f.cloud.github.com/assets/730846/832510/c9a2b464-f25d-11e2-8f6f-58666f45463e.png)

**Comment by wsmwk** [comment]
@mkravchuk @Coldblackice  We've gone through many releases of these addons and firefox.  Do you still see this problem?

**Comment by Coldblackice** [comment]
@wsmwk In my experience, it's been fixed!

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
