### ISSUE TITLE
Whole tabs sidebar black on standalone image viewer

### ISSUE THREAD

**Issue by tbs** [piroor/treestyletab#536]
Screenshot: http://i.minus.com/iq3qaYbw3Tcae.png

This is a known bug?

To reproduce: open an image in standalone viewer (not sure if need to be a huge one as in screenshot), minimize Firefox for ~5-10 minutes, restore the window, now the tabs sidebar is black, hovering the mouse restore it.

The issue is on Firefox or in Tree Style Tabs?

Image used in test: http://s.glbimg.com/po/tt/f/original/2013/02/26/firefox-logo-full.png

Tested on current Nightly addon+browser version.

**Comment by piroor** [comment]
Seems expired.
