### ISSUE TITLE
Request: option to disable create new window

### ISSUE THREAD

**Issue by ybijbwbe2** [piroor/treestyletab#540]
With TST, it's easy to organize everything in 1 window. However if you drag a tab off of a firefox window, then a new window gets created. This accidentally happens on laptops many times because trackpad is less accurate.

Can you add option to disable create new window? So if tabs get dragged off firefox window then nothing happens.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
