### ISSUE TITLE
Small conflict with Sidebars List extension: tab bar isn't updated after exiting from fullscreen mode

### ISSUE THREAD

**Issue by Infocatcher** [piroor/treestyletab#546]
Sidebars List: https://addons.mozilla.org/addon/sidebars-list/

By default Sidebars List uses different splitter width for maximized and not maximized window.
TST correctly updates after maximize/restore, but not after exiting from fullscreen mode.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
