### ISSUE TITLE
Both 2201 and 2301 stop FF 17.0.8 (ESR) working

### ISSUE THREAD

**Issue by gsomgsomgsom** [piroor/treestyletab#550]
When I start clean new profile with only tree style tab plugin, everything is OK. But when I start my working profile with any of plugin versions listed in topic - I have FF stucked and after some time message saying:

"
A script on this page may be busy, or it may have stopped responding. You can stop the script now, or you can continue to see if the script will complete.

Script: resource://treestyletab-modules/browser.js:1875"

String number can also be 1832 or 30x (don't clearly remember). If I press continue FF is stucked again and then get to the same message with other error string number.

I have tried to disable all extensions, plugins, languages; clear history, cache, cookies, opened windows. Nothing helps. So now I reverted back to 0.14.2013052901, cause it works correctly.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
