### ISSUE TITLE
Simplify the yucky transparent bloated shadowy themes with your own userChrome.css

### ISSUE THREAD

**Issue by joeytwiddle** [piroor/treestyletab#551]
I was not very keen on the default themes.

Metal and Sidebar looked kinda nice, but all that transparency made them hard to read, and may have even been slowing things down.

The simpler themes were too damn tall.  I want to fit more tabs in less vertical space!  (My tree is on the left.)  I also found the shadowed text ugly to read and again slow.

After 11 sleepless nights and 283 reboots of Firefox, I produced the following CSS file to address a few of these issues:

https://gist.github.com/joeytwiddle/6358913

If you are as desperate as I was, you can drop it in your `$profileFolder/chrome/userChrome.css` file.  You may want to adapt it, but it's somewhere to start from.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
