### ISSUE TITLE
Expanded tabs shrink on mouse hover

### ISSUE THREAD

**Issue by ohthere** [piroor/treestyletab#552]
When I bring the mouse cursor close to the righter part of expanded tabs, they shrink automatically.  It happens whether I expand them by holding Control button or by hovering mouse cursor.  It also happens although the cursor is still in the tab area, not in the content area.

It is inconvenient because I want to close each tab with one click after expanding them.  I cannot do it now because when they shrink, 'close' buttons disappear.

I use TST 0.14.2013082301, with FF 23.0.1 on OS X 10.8.4.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
