### ISSUE TITLE
Can't "Gather to a New Tree" (grayed out)

### ISSUE THREAD

**Issue by Coldblackice** [piroor/treestyletab#553]
When selecting a number of tabs (with Multiple Tab Handler), the option of "Gather to a New Tree" is grayed out and unselectable. This seems to happen when you have any sub-tabs selected that are trees themselves.

Could we permit this "Gather to New Tree" function to be used, even if there are sub-trees in the multi-tab selection? Either nesting any sub-trees in a new tree, or perhaps an option to strip out and sub-trees in the process of gathering to a new one.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
