### ISSUE TITLE
Hide the tab bar when only one tab

### ISSUE THREAD

**Issue by Ron999** [piroor/treestyletab#557]
In version 0.14.2013082201 of TST, the behavior was changed in regards to hiding the tab bar when there is only one tab:

 "Fixed: On Firefox 23 and later, ignore the preference "hide the tab bar when there is only one tab" because it was available on Firefox 22 or older versions." (from https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/versions/). 

However, Tab Mix Plus still has this option, so it would be better NOT to ignore this preference, at least when the Tab Mix Plus extension is present.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
