### ISSUE TITLE
Backup or Sync TST preferences? 

### ISSUE THREAD

**Issue by digital-carver** [piroor/treestyletab#562]
I'm trying to find a way to backup TST's settings and easily restore them in a new computer. To be clear I'm not looking to restore the tabs or a tree structure, I just wish to backup and restore the various extensions.treestyletab. settings. 

I came across [this commit](https://github.com/saneyuki/treestyletab/commit/5042651b8187ac3456d190eedfef125d09686b1f) which seems to indicate TST automatically backs up settings during uninstallation and restores them on a reinstall (I'm guessing), but there's no explicit backup/restore button as far as I see. Is there an easy way to achieve this?

**Comment by piroor** [comment]
> Is there a way I can run this new script against my Firefox installation? I could then also reuse it when I install Firefox on a new OS or something. 

[user.js](http://kb.mozillazine.org/User.js_file) will help you. If you use TST in an enterprise environment, [MCD](https://developer.mozilla.org/en-US/docs/MCD,_Mission_Control_Desktop_AKA_AutoConfig) also.

> if I synced these preferences as above, then when I install TST on a new Firefox, will it overwrite the synced preferences? 

On recent versions, TST now doesn't override Firefox's preferences. You'll see better result after sync.
