### ISSUE TITLE
"Phantom" closed tabs not going away

### ISSUE THREAD

**Issue by Coldblackice** [piroor/treestyletab#565]
Occasionally, there are some tabs that, when I click the "X" to close them, the tab does not disappear from the tree, even though the browser view switches to another open tab.

When I click on the "X" again, the button visually clicks, but nothing happens -- the "phantom" tab still remains.

When I click on the phantom-tab to view it, the browser only switches the view to the next closest tab -- thus, I can't actually view the tab anymore.

EDIT:

I tried grabbing a phantom tab and moving it around the tree. On the first move, when I let go of it, it visually "landed" on top of another tab, overlapping most of the tab it was on top of, in a bit of visual corruption. When I tried dragging it to another spot, after I let go of the mouse, the phantom tab disappeared entirely.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
