### ISSUE TITLE
Ungathering tabs from trees

### ISSUE THREAD

**Issue by Coldblackice** [piroor/treestyletab#566]
I seem to remember seeing the ability to "ungather" tabs from trees, but can't find it now.

For example, if I have a tree of tabs (and perhaps even multiple sub-trees of tabs nested within that tree), we could multi-select all of the tabs/trees/sub-trees, and then right-click and "ungather", which would put all of the selected tabs to the root level, evenly.

This was important because often, trees start to get "corrupted", where open sub-tabs in a tree will put them in a different tree entirely, or at least won't properly nest the tab visually within the sub-tree structure.

**Comment by piroor** [comment]
Seems expired.
