### ISSUE TITLE
Tree hierarchy stops "obeying" correctly

### ISSUE THREAD

**Issue by Coldblackice** [piroor/treestyletab#567]
I occasionally find times when tabs suddenly stop "obeying" a tree/sub-tree's visual hierarchical structure, where instead of a new tab putting itself visually into the sub-tree of the opening tab, it will instead get visually placed "outside" the tree, sometimes even "above" the tree.

I believe this is happening from a "collision" with tab-unloading/reloading through the extension "UnloadTab" (https://addons.mozilla.org/en-US/firefox/addon/unloadtab/?src=api).

To work around the issue, I have to select all the tabs and gather them to a new window, which removes the tree hierarchy, and I then have to manually resort them into trees.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
