### ISSUE TITLE
Performance issue when scrolling in pages.

### ISSUE THREAD

**Issue by ghost** [piroor/treestyletab#568]
It seems that TST is part of the reason I'm experiencing very laggy scrolling in Firefox.

Pictured is the output of the built-in profiler while scrolling a fairly simple [page](https://developer.mozilla.org/en-US/docs/Performance/Profiling_with_the_Built-in_Profiler). As you can see, it appears to be taking up half the processing time of everything that's happening and this performance difference with TST on and off is noticeable on my machine.

![profiler](https://f.cloud.github.com/assets/1509018/1270685/ae2af3a0-2d0d-11e3-9929-643930918c3c.png)

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
