### ISSUE TITLE
Feature Request: Middle-Click tab close button to Close Tree

### ISSUE THREAD

**Issue by ivanatpr** [piroor/treestyletab#570]
I often find myself wanting to close a whole tree and I figured a nice **single-click** way of going about it would be to make it so that middle clicking an individual tab's close button closes the tree instead of just the one tab (i.e. close the current tab and any children). 

Seems like a power-user feature, so maybe expose the functionality through a setting that is disabled by default?

**Comment by bughit** [comment]
@piroor

You explicitly support a mode of never auto-collapsing, which I prefer as it lets you see what you have open.

In this mode closing expanded sub-trees is probably the most common tab-bar operation, next to switching tabs. It would be helpful to have a single click action for it.

Currently there are two single click actions to close a tab (close button left click, tab middle click) but none to close a tree.  Seems like an imbalance, two is probably more than one needs for single tabs, and none is less than one needs for trees.

Please reconsider an optional close button middle click to close the tree.

**Comment by piroor** [comment]
@bughit TST 2.x provides [an API to implement such a feature](https://github.com/piroor/treestyletab/wiki/API-for-other-addons#when-a-tab-is-clicked). Here is a small example:

```javascript
const TST_ID = 'treestyletab@piro.sakura.ne.jp';
function registerToTST() {
  browser.runtime.sendMessage(TST_ID, {
    type: 'register-self',
    name: 'Close Tree with Middle Click on Closebox',
    icons: browser.runtime.getManifest().icons,
    listeningTypes: ['ready', 'tab-mousedown']
  });
}
browser.runtime.onMessageExternal.addListener((message, sender) => {
  switch (sender.id) {
    case TST_ID:
      switch (message.type) {
        case 'ready':
          registerToTST();
          break;
        case 'tab-mousedown':
          if (message.button == 1 && message.closebox)
            (function closeFromChildren(tab) {
              if (tab.children) {
                for (const child of tab.children) {
                  closeFromChildren(child);
                }
              }
              browser.tabs.remove(tab.id);
            })(message.tab);
          return Promise.resolve(false);
      }
      break;
  }
});
registerToTST();
```

Because it is easily implemented via API, I have no plan to implement it as a built-in feature. Instead I hope you (or someone) develop such a helper addon compatible with TST and release it.
