### ISSUE TITLE
Pale Moon does not start anymore since update to 0.14.2013100901

### ISSUE THREAD

**Issue by mkq** [piroor/treestyletab#574]
![palemoon__treestyletabs__0 14 2013100901](https://f.cloud.github.com/assets/1584258/1322300/607643ea-3423-11e3-9706-4785055dd7f7.PNG)
After updating from 0.14.2013052901 to 0.14.2013100901, Pale Moon (24.0.2 32 bit, on Windows 7) fails to start. The palemoon.exe process keeps consuming some CPU and a lot of memory, but no window comes up. The screenshot shows approximately the first 4 minutes. CPU usage looks less flat when looking at individual cores (i have a quad core with HyperThreading).

Then i used safe mode to try other versions:
- 0.14.2013082301: empty window frame shown, freezes
- 0.14.2013082201: empty window frame shown, freezes
- 0.14.2013052901: okay

With another profile with very little add-ons, the new version 0.14.2013100901 does work. So i haven't tried any other versions there.

_____ My add-ons as shown by Infolister _____
Last updated: Sun, 13 Oct 2013 15:32:06 GMT
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:24.0) Gecko/20130925 Firefox/24.0 PaleMoon/24.0.2
Extensions (enabled: 70, disabled: 34):

    Adblock Plus 2.2.4
    Add-on Compatibility Reporter 2.0.1
    Aero Window Title 1.6 [disabled]
    All-in-One Gestures 0.26
    All-in-One Sidebar 0.7.18
    App Button Color 1.0 [disabled]
    Autoclose Bookmark&History Folders 0.6.2.2
    AutoFormer 0.4.2.2
    BabelFish 1.96 [disabled]
    Back Forward separate 1.3 [disabled]
    Back IS Close 2.1 [disabled]
    Back to Close 1.11
    Back to Owner Tab 0.3.2012122901 [disabled]
    Back/Forward History Tweaks (restartless) 1.0.1
    BetterPrivacy 1.68
    Blacken 1.5.6
    Bookmark Favicon Changer 1.74
    CacheIt! 2.0.3
    checkCompatibility 1.3
    CheckFox 0.9.2
    Classic Compact Options 20.0 [disabled]
    Click Search 1.6
    Context Highlight 0.3.4
    Context Search RG 1.1
    Cookie Monster 1.1.0
    CSS Toolbox 0.1
    Customizable Shortcuts 0.5.11.1 [disabled]
    Cycle Input Focus 1.0.0
    Dictionary Tooltip 1.7 [disabled]
    DictionarySearch 10.0.0 [disabled]
    DOM Inspector 2.0.14
    Download Manager Tweak 0.9.8
    Download Statusbar 0.9.10
    DownloadHelper 4.9.15
    Downloads Context Menu 1.5
    eBay Sidebar for Firefox 2.5.7
    enhanced findbar 0.9.0 [disabled]
    Fastest Search 2.31 [disabled]
    FlashVideoReplacer 2.1.15 [disabled]
    Free Download Manager plugin 1.5.7.6 [disabled]
    Greasemonkey 1.9
    HeadingsMap 2.0.5
    Hide Caption Titlebar Plus 2.7.3 [disabled]
    How Many Times Can I Back? 0.2.2011012001 [disabled]
    InfoLister 0.10.4a3
    iReader 1.0.7 [disabled]
    keyconfig 20110522
    Link Alert 1.0.2
    Link Status Redux 2.3
    LinkSidebar 1.0.3
    Live HTTP headers 0.17
    LoL 1.5
    Movable Firefox Button 1.4 [disabled]
    Mozilla Archive Format 2.0.9
    Multi Smart Search 2.0.20110408
    Nav Bar on Title Bar 1.0 [disabled]
    New tab toolbar button 1.1
    NextPlease 0.9.2
    NoScript 2.6.6.7
    NoSquint 2.1.9
    NoUn Buttons 1.1.4.1
    Open In Current Tab 0.3
    Open With 5.3.1
    OpenInWindow 1.2.1
    OptimizeGoogle 0.79.1
    Pale Moon Commander 1.0.1
    PopupSound 0.1.6
    PrefBar 6.2.0
    Preserve Download Modification Timestamp 2011.03.21.22
    Prevent Tab Overflow 7.1 [disabled]
    Quick Translator 1.0
    refspoof 0.9.5
    Restart 0.0.0.9m
    Restart Firefox 0.5 [disabled]
    Save Images 0.9.4
    Search Marker 1.0.7 [disabled]
    Searchbar Autosizer 2.0.20
    Session Manager 0.8.0.7
    Show Anchors 2.3
    Sidebar Bookmark Selector 3.0
    Site navigation bar 2.1 [disabled]
    Smart Referer 0.0.11 [disabled]
    Speed Dial 0.9.6.15
    Status-4-Evar 2013.02.16.23 [disabled]
    Stealthy 2.5
    Style Sheet Chooser II 3.0.0.1 [disabled]
    StyleSheet Chooser Plus 1.2.2 [disabled]
    Stylish 1.3.2
    Tab Mix Plus 0.4.1.0
    Tab Sidebar 2.5 [disabled]
    Tab Utilities 1.5.1 [disabled]
    TabGroups Manager 2011.11.28.1 [disabled]
    TabGroups Menu 0.9.1 [disabled]
    TableTools2 1.17
    Tabs Always In Titlebar 1.2 [disabled]
    Tabs Menu 1.4.8
    Titlebar Tweaker 1.31 [disabled]
    Toggle Word Wrap 1.9
    Toolbar Buttons 1.0
    Tree Style Tab 0.14.2013052901
    UI Fixer 1.4.4 [disabled]
    Unsorted Bookmarks Folder Menu 3.0.1
    Uppity 1.5.8
    Work Offline 2.0

Themes (21):

    Aero Improved 1.0.1.0
    Anowia 2 1260925626
    Classic Compact 20.0.1
    Color Toolbar Icons 2.6.4
    Dark manubar 1260925626
    Default 24.0.2
    Firefox 2 theme for Firefox 4+ 2.0.1 [selected]
    FirefoxOxygen 1262648531
    Fractal flame 1260925626
    Gray - Drop-Down Menu Match 1282894022
    miniFoxFlat 0.4.3
    Modern Toolbar Icons 2.6.4
    Opaque + ClearTabs 1.5
    QSQ 3.0.3
    Rock Solid 1260925626
    silver2
    Strata Toolbar Icons 2.6.4
    StrataStripe 3.3
    Three toolbar readability 1268498958
    Winestripe Realfox 4 3.0.1
    Winstripe Toolbar Icons 2.6.4

Plugins (1):

    Shockwave Flash

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
