### ISSUE TITLE
Can't move pinned tab to be 1st in list

### ISSUE THREAD

**Issue by mjessome** [piroor/treestyletab#585]
Reproduce by:
1. Pin a bunch of tabs
2. Grab the last pinned one (rightmost) and try to drag it to the first spot.

Workaround:
1. Grab pinned tab and move it to be 2nd left-most.
2. Grab left-most tab and move it right one spot.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
