### ISSUE TITLE
Vimperator conflict: Selected tab shows above input window

### ISSUE THREAD

**Issue by mjessome** [piroor/treestyletab#586]
Conflict with the vimperator addon if the list of tabs go below where the vimperator bar comes up to.

Reproduction:
1. open tabs so that the vimperator input window covers it
2. select a tab near the bottom.
3. Pop up the vimperator input window

The selected tab shows up above the vimperator window. See bottom left of screenshot.
![screen shot 2013-11-05 at 1 42 56 pm](https://f.cloud.github.com/assets/485012/1477887/3fe3419e-4663-11e3-9121-cacc20f9a6ac.png)

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
