### ISSUE TITLE
Move to use Promise

### ISSUE THREAD

**Issue by saneyuki** [piroor/treestyletab#588]
I think we should move to use `Promise`, which will be specified [ECMAScript](https://github.com/domenic/promises-unwrapping/blob/master/README.md) & [DOM Living Standard](http://dom.spec.whatwg.org/#promises).

`Promise` would replace JSDeferred. But Gecko 28 implementation is only DOM, and [toolkit promise modules](https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm) isn't compatible with the latest ES&DOM Promise, so we should not use it immediately.

ECMAScript 6 will freeze its features until the end of 2013. We need to wait it.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
