### ISSUE TITLE
Graphical glitches with Windows Aero theme

### ISSUE THREAD

**Issue by soar** [piroor/treestyletab#591]
There are some drawing glitches in browser plugin frames, such as Adobe Flash or Java. They looks like this:

http://joxi.ru/0656Utg5CbAiGVLdDHQ
http://joxi.ru/A7F6Utg5CbBNG8MlfWo

This problem is permanent and appears when I have enabled Windows Aero theme and select any theme in TreeStyleTab options. If "Default" theme is selected:

http://joxi.ru/7a56Utg5CbAIHN_lWRk

I get normal fonts in this windows:

http://joxi.ru/Dq96Utg5CbAiGZb9Tvs

But "Default" theme is so ugly, i can't use it :)

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
