### ISSUE TITLE
Bugs in Firefox 4

### ISSUE THREAD

**Issue by nyctef** [piroor/treestyletab#60]
Using the tab bar on the left, it covers anything along the bottom of the window such as Download Statusbar ( https://addons.mozilla.org/en-us/firefox/addon/download-statusbar/ ) or the Find toolbar. Screenshot: http://img27.imageshack.us/img27/7036/overlapp.png

Also, when Firefox is maximized, if the tab bar is just long enough that the add new tab button (labelled "+") covers the bottom of the screen, then the scroll bar will flicker on and off.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
