### ISSUE TITLE
List Tabs in Group

### ISSUE THREAD

**Issue by PantherX** [piroor/treestyletab#600]
As an enhancement, would it be possible to list the tabs vertically instead of horizontally so make maximum use of screen space? I have attached a picture showing this suggest feature.
![list tabs](https://f.cloud.github.com/assets/5349122/1509465/1c1cf59c-4a4c-11e3-8c45-cd30d3f3cba6.png)

**Comment by piroor** [comment]
By f5198c31aa1f48d757ecef984d9116bb4807d3cc now tree in a group tab is shown with multiple columns.

**Comment by piroor** [comment]
Done by recent commits.
