### ISSUE TITLE
Extentd Middle-Click capibilities to other add-ons

### ISSUE THREAD

**Issue by PantherX** [piroor/treestyletab#603]
Using middle-click, I can open a new tab as a sibling of the current tab. However, when I do the same with Private Tab Icon (https://addons.mozilla.org/en-US/firefox/addon/private-tab/), it doesn't work.

I have requested this feature and the author of Private Tab has implemented it (https://github.com/Infocatcher/Private_Tab/issues/117). Thus, if you too can implement it, it would be great.

**Comment by piroor** [comment]
For a long time I missed this issue. Sorry.

Now TST opens new tabs opened by other addons with "relatedToCurrent:true" internal option as children of the current tab, so new tabs from the addon also become children for me. Can I close this?

**Comment by PantherX** [comment]
Yes, I have tested it and it works. Thank you.
