### ISSUE TITLE
Autoscroll (of background loading tabs) problematic

### ISSUE THREAD

**Issue by titoBouzout** [piroor/treestyletab#604]
Hi Piro, the amount of issues here, does not encourage me to report this, but I'll try!

I've an issue with "automatic scrolling" of the tabbar when I open many tabs at the same time. These tabs are also hidden with aTab.setAttribute('hidden', true);, then makes non-sense "move the scroll of the tabbar" because there is nothing to see.

This is only reproducible if you load lots of tabs in trees. I usually run ChromeBookmarklets, which execute actions in these tabs, to automate tasks and save of my time. But the autoscroll makes me stop an wait till these actions are execute, becuase if I click the Tabbar I dont know which Tab will get the click, as is moving up and down frequently.

Then, maybe I would like to ask for a preference to stop autoscroll.

Many thanks!

**Comment by piroor** [comment]
bd3f2969a777fcb6389f0da16af261fdbecd4150 and 8581e3abc55d53672700eb4db8778ffc59ef766d should fix this.

**Comment by titoBouzout** [comment]
Thanks a lot @piroor, Im no longer using Firefox since like three years ago or so. The only thing I miss are your extensions. Good luck, thanks for all

**Comment by piroor** [comment]
Thank you for a response!
