### ISSUE TITLE
Tree Style Tabs doesn't work too well with Australis

### ISSUE THREAD

**Issue by fitzgen** [piroor/treestyletab#607]
* Window max/min/close buttons in the wrong place

* Tabs are styled incorrectly

* pinned tabs not clickable

* Weird lines above pinned tabs

* weird line above the url bar

![screen shot](https://f.cloud.github.com/assets/74571/1567468/69af9528-509e-11e3-92a6-af4a4ac9512b.png)

**Comment by piroor** [comment]
Seems expired.
