### ISSUE TITLE
How to reuse Tree Style Tab sidebar in another addons?

### ISSUE THREAD

**Issue by vovcacik** [piroor/treestyletab#621]
Hi, 
I would like to reuse TST unshrinked sidebar in my own addon. Is it possible? Can you point me the right direction and possibly comment on it.

Thank you!

**Comment by piroor** [comment]
A Vimperator pugin written by caisui possibly gives you some hints.
https://gist.github.com/caisui/1245345

**Comment by vovcacik** [comment]
At the end I actually decided to go with Firefox XBL and [scrollmap][] was born.

[scrollmap]: https://addons.mozilla.org/cs/firefox/addon/scrollmap/
