### ISSUE TITLE
Private indicator is not shown on OSX with Australis

### ISSUE THREAD

**Issue by saneyuki** [piroor/treestyletab#624]
## env
* http://hg.mozilla.org/mozilla-central/rev/1401e4b394ad
* OSX 10.9
* TST 0.14.2013120100a011302

## Issue
* Any private indicator is not shown on OSX with Australis
  * This is caused after removed special styles for "tabs on bottom".
* See screenshot.
![ss](https://f.cloud.github.com/assets/180104/1692155/cd17e772-5e73-11e3-9f5f-53abf9353375.png)

**Comment by piroor** [comment]
Is this still there?

**Comment by saneyuki** [comment]
Yes. I confirmed this problem is not reproucible. Thank you!
