### ISSUE TITLE
Not seemless theme between titlebar and navigation bar

### ISSUE THREAD

**Issue by saneyuki** [piroor/treestyletab#625]
## env
- http://hg.mozilla.org/mozilla-central/rev/1401e4b394ad
- OSX 10.9
- TST 0.14.2013120100a011302
# Issue

![ss](https://f.cloud.github.com/assets/180104/1692198/aace2ac2-5e74-11e3-9cfc-b612ab7fc103.png)

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
