### ISSUE TITLE
Place tabs counter before the thumbnail of "Informational Tabs"

### ISSUE THREAD

**Issue by weynhamz** [piroor/treestyletab#627]
![treestyletab-couter-position-issue](https://f.cloud.github.com/assets/816673/1693364/762ddef2-5e8d-11e3-9482-35685819fc42.png)

See the pic attached, it looks a bit odd, if choosing to place the thumbnail to the right of the tab.

**Comment by piroor** [comment]
Fix by a change of Informational Tab https://github.com/piroor/informationaltab/commit/966f82aafed6e54dfefd5da41b74cc0b5b5a7e7f and TST's change 2a750342bbe4343c846e6cc13a9b9610cd835355
