### ISSUE TITLE
(Feature request) Auto-hide tab bar when browser window is not active

### ISSUE THREAD

**Issue by QuietThud** [piroor/treestyletab#629]
My tab bar is set to hide automatically; if the FF window becomes inactive before the tab bar has hidden, the tab bar gets stuck. 

This is a problem because the tab bar is on the left side of my browser, and I often pass through the left border when moving quickly to select another open window (such as when reading something in FF while making notes in Notepad). 

I have to bring the browser back into focus to get the tab bar to hide so it's not hovering over my reading. It is not a big deal, but it would be nice if the tab bar were set to hide automatically when the browser is not in focus. Thank you!

**Comment by piroor** [comment]
Done by 72bb2f1a089f88d2ebcf509bc215352beccc94eb
