### ISSUE TITLE
Incompatible with Focus Last Selected Tab add-on

### ISSUE THREAD

**Issue by protist** [piroor/treestyletab#63]
With Firefox 4.0, Tree Style Tab 0.11.2011032401 and Focus Last Selected Tab 0.9.6.2, Focus Last Selected Tab is broken.
What is expected: after closing a tab, select the previously-selected tab.
What occurs: after closing a tab, the tab immediately to the right (or down in vertical mode) is selected.

**Comment by syliew** [comment]
neither "Focus Last Selected Tab 0.9.6.2" nor https://addons.mozilla.org/en-US/firefox/addon/fww-flst/ work with tst enabled, though both extensions work on their own.
