### ISSUE TITLE
Bottom-most tab is invisible

### ISSUE THREAD

**Issue by hotsphink** [piroor/treestyletab#632]
I am using 0.14.2013112901 with Firefox 28 (with Australis). It's looking very good to me, with one remaining problem: when I have more tabs than will fit on the screen, the bottom one is not displayed.

I am attaching a screenshot where the last tab should be this github page, but it's not visible. (I can use ctrl-pgdn to access it.) Seems like an off-by-one error or something.

![tst-bottom](https://f.cloud.github.com/assets/78649/1736321/eaf3c2d6-6362-11e3-80af-817b539e6ffe.png)

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
