### ISSUE TITLE
Tab position shifts on restart when new children are on top.

### ISSUE THREAD

**Issue by solf** [piroor/treestyletab#637]
- Set insertion position of a new child to 'Insert to the top of the tree'.
- Open e.g. google search result on top level.
- Open a bunch of links with middle-click (in background). These are added as children to google page with the last opened link on top.
- Select one of the children tabs somewhere in the middle (not the one on top or the bottom).
- Close Firefox
- Open Firefox

Tab position shifts down by one (among children).

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
