### ISSUE TITLE
Tree Style Tabs conflicting with Vimperator--tabs not fully concealed by overlay

### ISSUE THREAD

**Issue by zzbennett** [piroor/treestyletab#639]
When Tree Stye Tabs is set on partial hide and the vimperator command area is opened up, this is what happens: 
![screen shot 2013-12-28 at 11 47 37 am](https://f.cloud.github.com/assets/1134147/1818349/e67e175e-6ff8-11e3-9a3b-57dd4b3456f4.png)

It seems that the tabs should be completely obscured by the vimperator window, but they are only partially obscured. The tabs themselves still show up over the vimperator window. I'm not sure whether this is a vimperator issue or a TST issue. I only noticed it when I switched to partially hidden tabs this morning (I've used fully hidden tabs for a long time).

I'm using TST v. 0.14.2013112901, vimperator v. 3.8.2 and firefox 25.0.1

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
