### ISSUE TITLE
(major issue) Scrollbar missing, tabs unreachable + hi CPU load

### ISSUE THREAD

**Issue by mayhemer** [piroor/treestyletab#641]
- when number of tabs in the sidebar is more then it fits the height, the scroll bar doesn't appear -> the most bellow tabs cannot be reached with mouse
- when I expand a tab so that I get the above described situation, browser goes with very high CPU since TST does something in a loop, see https://bugzilla.mozilla.org/show_bug.cgi?id=958308

This is a major performance and usability issue.

Firefox Nightly, TST 0.14.2013121400a220654 (no update avail)

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.

**Comment by mayhemer** [comment]
I think this is fixed in the current (webext) verrsion.  Thanks!
