### ISSUE TITLE
higher cpu usage with non-default TST theme

### ISSUE THREAD

**Issue by wsmwk** [piroor/treestyletab#642]
Firefox seems slower when TST option is set to use non-default theme such as mixed.  It may also depend on tab position "leftside".  TST 0.14.2013121400a220654 and current nightly build

I haven't benchmarked this yet, so this is not backed by data,  Hope to supply gecko profile in a couple days.

I also supplied a profile at https://github.com/piroor/treestyletab/issues/641 but that might have been caused by memchaser addon

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
