### ISSUE TITLE
Address bar does not show the URL of the currently selected tab

### ISSUE THREAD

**Issue by Sebster7** [piroor/treestyletab#643]
This may be a Session Manager add-on bug, although I would not expect that to be interfering with the address bar...

It seems that <b>from time to time</b>, when I restore a large Session Manager session with more than one window following an out-of-memory crash, the address bar in one or more windows shows blank (or whatever I put into it) instead of the URL of the selected tab.  Clicking on another tab does not update the address bar.  The only resolution is to kill Firefox and restart the session again.

I have had this issue occasionally over a period of several months, with different versions of Firefox and treestyletab (both are currently up-to-date release versions, 26.0 and TST 0.14.2013112901).

Any ideas? (Apart from Session Manager I don't think I should have any add-ons affecting behaviour. No other tab add-ons except for IE Tab 2 and IE Tab Plus, both of which I rarely use.)

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
