### ISSUE TITLE
Ver.0.14.2014020901 for Mozilla Firefox   On MAC OS X 10.9.1

### ISSUE THREAD

**Issue by Ajeet-Ganga** [piroor/treestyletab#658]
Till recent time treestyletab was working just fine without any hitches.
Just today,  it stopped working. (There is no tree-style tab on my firefox)

So I downloaded and installed the latest version and the problem persists still.
(Of course I did try couple of times restart the firefox.)

Here are the versions I use :
Browser 
Ver.0.14.2014020901 for Mozilla Firefox
OS 
MAC OS X 10.9.1

**Comment by piroor** [comment]
Seems expired.
