### ISSUE TITLE
Unable to see navbar on osx fullscreen mode

### ISSUE THREAD

**Issue by superosku** [piroor/treestyletab#659]
When this add-on is enabled on osx it hides the navbar and it is impossible to access it. Moving mouse to top of the screen does not show navbar.
Setting 'Autohide -> for fullscreen mode' does not have any effect.
Versions:
Treestyletab: 0.14.2014013001
Firefox: 27.0

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
