### ISSUE TITLE
Auto-shrink mode: current tab at bottom of tree - not visible in tree after Firefox window resized.

### ISSUE THREAD

**Issue by trismarck** [piroor/treestyletab#660]
Lets suppose the current tab is at the bottom of the tree. If I resize the Firefox window (to be precise, shrink the window vertically), that tab will not be visible in the tree anymore. I don't know if I'd want the tree to scroll when the current tab is _in the middle_ of the tree (~ not at the bottom of the tree), but if the current tab _is_ at the bottom of the tree, I think it would be desired for TST to scroll the window to the current tab.
![treestyletab-at bottom-scroll](https://f.cloud.github.com/assets/4901124/2136636/66e7de08-9316-11e3-9a1d-098908f84114.jpg)

**Comment by piroor** [comment]
Fixed by 55fa276
