### ISSUE TITLE
Playing nicely with Tab Mix Plus - font colours, etc. 

### ISSUE THREAD

**Issue by TheBlackRoom** [piroor/treestyletab#661]
Hi, a recent update to Tab Mix Plus (TMP) has seen some features limited to users of TreeStyleTab (TST). For me the thing I now miss from TMP is the colouring of the font text used in the tabs to show their current state, e.g. Unread, Unloaded, Current, etc,

Apparently there were some conflicts with TMP and TST's background colouring so the TMP author has tried to overcome these but in the process has disabled some of the other features.

There is currently a discussion on this problem here and maybe you can discuss with TMP author?:
http://tmp.garyr.net/forum/viewtopic.php?f=2&t=18544

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
