### ISSUE TITLE
Bookmark tree error

### ISSUE THREAD

**Issue by john12ik2** [piroor/treestyletab#662]
Tree Style Tab Ver.0.14.2014020901

New TST does not restore bookmark tree.

If you set bookmarks tree structure inside a bookmark folder to look like this
Tab1
.....Tab2
.....Tab3
Tab4
.....Tab5

Then you open all bookmarks using "open all in tabs", the structure opens like this:
Tab1
.....Tab2
.....Tab3
.....Tab4
.....Tab5

tree style tab 0.14.2013112901 works correctly for bookmarks. All newer version have bookmark error

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
