### ISSUE TITLE
[Feature Req.] Keyboard-shortcut like CTRL-TAB to switch between trees (or sub-trees)

### ISSUE THREAD

**Issue by Coldblackice** [piroor/treestyletab#665]
Could we get the ability to switch between tab *trees* like we can switch between individual tabs (like when we use CTRL-TAB)?

I use CTRL-TAB and CTRL-SHIFT-TAB all the time to navigate between tabs. What would be *fantastic* is if we could assign another keyboard shortcut to switch between tab *trees*, like so:

A[12(i.ii.**HERE*iii.)3(i.ii.iii.)]
B[123]
C[123]
D[123]

["Switch to next tab-tree" key-shortcut]

A[12(i.ii.iii.)3(i.ii.iii.)] 
B*HERE*[123]
C[123]
D[123]

OR, the jump could even be customized, like instead of switching to next *ground-level tree* (probably most useful), it could switch to the next immediate tree *or* subtree in ordering (whichever's next). So:

A[12(i.ii.*HERE*iii.)3(i.ii.iii.)]
B[123]
C[123]
D[123]

-->

A[12(i.ii.iii.)3*HERE*(i.ii.iii.)]
B[123]
C[123]
D[123]

-->

A[12(i.ii.iii.)3(i.ii.iii.)]
B*HERE*[123]
C[123]
D[123]

<--

A[12(i.ii.iii.)3*HERE*(i.ii.iii.)]
B[123]
C[123]
D[123]

**Comment by piroor** [comment]
I have no plan to add new keyboard shortcuts for those commands, but I've written code snippets to do that.
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-keyboard-shortcuts
