### ISSUE TITLE
Keyboard Shortcut for tab bar

### ISSUE THREAD

**Issue by sunilkonduru** [piroor/treestyletab#666]
I am using a 13.3 inch macbook air. So, when I am using tree style tabbing it is occupying lot of space. It will be great if we can have a keyboard shortcut for closing and opening the vertical tab bar. Somewhere I found pressing ctrl for long enough time would close it. It was not working, I tried the same in my linux machine, It doesnt work. Is there any shortcut for closing the tab bar? Thanks.

**Comment by piroor** [comment]
I have no plan to add keyboard shortcut for the feature. See also https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-keyboard-shortcuts
