### ISSUE TITLE
High CPU usage and browser crashes after some time on FF 28

### ISSUE THREAD

**Issue by fignuts** [piroor/treestyletab#667]
When tree style tabs is enabled with FF 28 on win 8.1 the browser will begin to "lag" after being open for some time (~5 minutes). CPU usage spikes every ~10-20 seconds and freezes the browser UI. These CPU spikes become more frequent over time until eventually the browser locks up and is force closed by windows. Restarting the browser resets this cycle and it will work properly for ~5 minutes before the CPU spikes begin again. Resetting firefox and disabling all other addons had no effect on this behavior.

**Comment by piroor** [comment]
Seems expired. If you still see this problem on latest Firefox (44), please report again with more details - how to reproduce the problem from scratch. You'll start Firefox with blank profile with a command line option like; `"c:\program files (x86)\mozilla firefox\firefox.exe" -no-remote -profile "%temp%\firefox-blank-profile"`
