### ISSUE TITLE
Tree isn't restored correctly using Session Manager

### ISSUE THREAD

**Issue by alexeyr** [piroor/treestyletab#668]
With TreeStyleTab 0.14.2014020901 and Session Manager 0.8.0.8, some tabs I moved before restarting Firefox are restored in their old location in the tree.

**Comment by designatevoid** [comment]
I seemingly had the same problem with FireFox 31.7.0, Tree Style Tab 0.15.20153061 and Session Manager 0.8.1.6 but somehow Session Manager just wiped out the Tree Style Tab configuration and set the tabs back to the default position (top).  After I set the config to display tabs on the left as before Tree Style Tab worked normally.

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by imraro** [comment]
Tree Style Tab  0.16.2015111001  with Session Manager 0.8.1.8 works great for me

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
