### ISSUE TITLE
Wiki page collecting keyboard shortcuts

### ISSUE THREAD

**Issue by alexeyr** [piroor/treestyletab#669]
In another issue you mentioned there are no plans to provide keyboard shortcuts and instead KeySnail or other similar extensions should be used. It would be good to have this in the add-on description along with a link to a page with code for shortcuts.

**Comment by piroor** [comment]
I've created a new wiki page for this purpose,
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-keyboard-shortcuts

**Comment by jnachtigall** [comment]
@piroor I guess this is not working anymore with the WebExtensions version (I use FF 58 Nightly atm). I am looking for a shortcut for [Close the current and all descendant tabs](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-keyboard-shortcuts#close-the-current-and-all-descendant-tabs). ATM I have to move mouse to tab => right click on the tab => Tab Tree Style => "Close this tree"

**Comment by piroor** [comment]
TST 2.0.x doesn't provide any shortcut except F1 to toggle the sidebar itself. Sorry but I have no plan to do around more keyboard shortcuts until better WebExtensions APIs are landed. See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1215061

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
