### ISSUE TITLE
Open folder inside another folder doesn't work

### ISSUE THREAD

**Issue by lolshock** [piroor/treestyletab#673]
If I open a bookmark folder which has another folder in it TST completely ignores this second folder. In my opinion it should create another dummy tab as a child of the first dummy tab.

**Comment by piroor** [comment]
I agree that it is useful, but currently I cannot implement it by my hand. Pull request for this feature is required...

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
