### ISSUE TITLE
Tree Style Tab in Australis forces titlebar to always appear

### ISSUE THREAD

**Issue by lewisl9029** [piroor/treestyletab#674]
I've customized Firefox by placing everything along the Titlebar in a single row for quite a while now. 
http://imgur.com/NSUJXdF

And with the Classic Theme Restorer addon, I found that this is still possible in Australis (FF29 beta). 
http://imgur.com/UYBmgC3

However, as soon as I enable Tree Style Tab, it seems to completely disable the ability to place anything in the Titlebar.
http://imgur.com/PFLcTRF

Even specialized addons like Personal Titlebar can't seem to override this behavior in Australis, whereas in pre-Australis (FF28 stable), this configuration works perfectly fine.
http://imgur.com/H6p6DRc

Probably not the most widespread issue ever. But I'd appreciate it if some could take a look at it.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
