### ISSUE TITLE
[Feature Request] Flashing tab denotes running video

### ISSUE THREAD

**Issue by alphaa10** [piroor/treestyletab#679]
When I run Firefox 28 in Windows XPPro, I use Tree Style Tabs to keep many tabs open, for later use. This is a great convenience, since I do not have to find the web links later. 

When I open a tab linked to a YouTube video, your excellent program allows me to keep the tab open, but without forcing me to run the video to which the tab links. And if the video tab starts to play, I simply can pause the video, and usually that is enough to stop the video. 

However, when Firefox opens a previous session which contains video tabs, Tree Style Tabs sometimes permits the video tabs to begin play automatically. This creates bedlam and confusion, and robs me of bandwidth. Compounding the problem, I cannot determine which of the tabs is playing a video. I must open each of the tabs, in turn, to find out which videos are running and pause each of them, once again.

For that reason, it would be a wonderful feature for Tree Style Tabs to flash the tab which is running a video. In that way, I quickly can determine which of the tabs to open, in order to pause the video play.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
