### ISSUE TITLE
conflict with vimperator tabnumbers

### ISSUE THREAD

**Issue by finbarrocallaghan** [piroor/treestyletab#682]
broken vimperator tab numbering shown

![kom2](https://cloud.githubusercontent.com/assets/448416/2648523/5f006f84-bf58-11e3-9f2f-510c4c4da19b.png)

I think [this](http://code.google.com/p/vimperator-labs/source/browse/common/content/tabs.js#1155) is the vimperator code which breaks when treestyletab is enabled

it works fine once treestyletab is disabled, any ideas?

Mozilla/5.0 (X11; Linux x86_64; rv:27.0) Gecko/20100101 Firefox/27.0

**Comment by elonwoo** [comment]
I have this problem too.
TST Tab bar position top, works fine
TST Tab bar position left, not work very perfect

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0
Vimperator	3.10.1
Tree Style Tab	0.15.2015061300a003855
