### ISSUE TITLE
Autohide/Autoshrink does not work correctly in Australis

### ISSUE THREAD

**Issue by jlacson** [piroor/treestyletab#686]
![firefoxbug](https://cloud.githubusercontent.com/assets/2222566/2751871/62acce36-c8f2-11e3-9bee-13c76f86c0e2.png)
The tab bar will re-expand / reshow however only the part that was once visible will be clickable and it does not look the same aesthetically as it does on non australis Firefox.

Also, on a semi-unrelated note, the close button does not show up anymore.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
