### ISSUE TITLE
"close" buttons not showing on tabs in FF 29.

### ISSUE THREAD

**Issue by kyleki** [piroor/treestyletab#690]
The little "X" is not showing on the right side of my tabs when using FF 29.
![treestyle_missing_x](https://cloud.githubusercontent.com/assets/7441821/2831829/eb524230-cfbd-11e3-9c2e-97de3e42053d.png)

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
