### ISSUE TITLE
Claim page on Flattr

### ISSUE THREAD

**Issue by waldyrious** [piroor/treestyletab#691]
The [Flattr page for this repo](https://flattr.com/thing/1812329/piroortreestyletab-on-GitHub) is unclaimed, which doesn't let me make further flattrs or subscribe for automatically flattring treestyletab monthly. @piroor can you claim that page?

**Comment by piroor** [comment]
Thanks, but sorry, I have no plan about any donation because I hope to keep me as the prime user of this project. i hope to keep having a privilege to say "no" about requests not matched to my vision. Instead, please fork this project freely for your purpose if needed.

**Comment by waldyrious** [comment]
I don't see that as a problem -- you're always free to refuse any feature request, even from people who donated to you. That's the difference between a donation and a bounty :) a donation is unconditional, a way to say thanks for what you've *already* done.

If you still prefer to avoid that, I totally understand, so allow me to thank you here for the wonderful extension -- it's hands down the main reason I use Firefox rather than chrome, I can't work anymore without it! Cheers.

**Comment by piroor** [comment]
Thanks again. I understand the difference of donation and consideration, however, I'll feel pressures if I actually get donation. Anyway, I'm glad about offers like this :)
