### ISSUE TITLE
Firefox 29 (Australis) opening new tab in a tree scrolls to the beginning of the list

### ISSUE THREAD

**Issue by cp-tar** [piroor/treestyletab#697]
It's pretty much what it says in the title: a middle click opening a tab will open the tab as it is supposed to, but the tab list will scroll all the way to the beginning. With lots of tabs, it can become really annoying.
If a new tab is opened automatically from a left click (i.e. a link designed to open in a new tab), this does not happen; only middle click tabs, and possibly other tabs not immediately given focus, are affected.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
