### ISSUE TITLE
Extension compatibility problem with Sort and Search Customization

### ISSUE THREAD

**Issue by alta88** [piroor/treestyletab#698]
With the Sort and Search Customization Dialog extension, and Tree Style Tab v050102, customization is broken (buttons don't display, exit won't work, restart required).

It was an easy choice which one to disable..

Btw, as the author of TotalToolbar, I'd like to note it's no longer supported; I know there may have been compatibility workarounds in TST.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
