### ISSUE TITLE
Drag'n'Drop tree to another window loses child tabs

### ISSUE THREAD

**Issue by dotbugfix** [piroor/treestyletab#699]
Dragging a tree, say, that looks like this:

```
- Tab1
-- Tab2
-- Tab3
```

by dragging `Tab1` and dropping it to another Firefox window has this behavior:
- The entire tree structure is replicated fine (as in you see a tree with correct placement of child tabs)
- `Tab1` appears perfectly
- `Tab2` and `Tab3` are now the 'New Tab' page  (which, for me is about:blank)

I described the simplest possible scenario here, but it can be extrapolated to any depth and any no. of tabs - only the topmost parent survives the drop!

Can reproduce on Firefox 28.0 on Ubuntu 13.10. v0.14.2014020901 of the TreeStyleTabs add-on.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
