### ISSUE TITLE
Gray bar 22px from top when autohidden on left or right sides in FF29

### ISSUE THREAD

**Issue by csmarshall** [piroor/treestyletab#701]
Upgraded to FF29 on OSX last night and now when using _any_ theme except for "metal" and "sidebar" a 1px line appears about 22px off the top of window when the tab bar is hidden.  When the tab bar is expanded the line disappears.  

The screenshots below are on FF29 with all other plugins disabled.

![screen shot 2014-05-04 at 16 03 39](https://cloud.githubusercontent.com/assets/1200112/2874306/f5124b22-d3e0-11e3-9508-89a6478fb6b2.png)

![screen shot 2014-05-04 at 16 02 51](https://cloud.githubusercontent.com/assets/1200112/2874307/f513b674-d3e0-11e3-82dd-9747c6def511.png)

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
