### ISSUE TITLE
title bar disappears when using non default theme

### ISSUE THREAD

**Issue by edwinwongsf** [piroor/treestyletab#706]
Not sure if this is a Firefox bug or the add-on

https://bugzilla.mozilla.org/show_bug.cgi?id=1006202

This only happens on one specific profile as of now. Can't repro with a new or different profile.
1. install Tree Style Tab add-on
2. install theme (not default)

actual:
title bar disappears

workaround:
switch theme to default (grey) this solves the problem

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
