### ISSUE TITLE
Incompatibility with Compact Menu 2 (FF29 - Win7)

### ISSUE THREAD

**Issue by efcis** [piroor/treestyletab#707]
Hi !

I'm using Compact Menu 2 to save space, and get the whole menus. It's located at the top left of my FF window, to the left of the Address Bar.

Unfortunately, with FF 29, if Compact Menu 2 is enabled, all tabs of TreeStyleTab are no longer displayed :-(  I get an empty space instead.

Thanks for your help !

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
