### ISSUE TITLE
Colorful Tabs Hack is Gone in Latest Update

### ISSUE THREAD

**Issue by TLConklin** [piroor/treestyletab#713]
Love this extension. Have my entire company using this extension since I found it years ago. Makes working in the many pages and applications we use daily, so much easier to organize. 

Since the update today however, the "Colorful Tabs" hack that made all unique tab trees the same color - is no longer working. 

Can we get that hack back? It was super helpful to organize the tabs that belong to each tree.

**Comment by piroor** [comment]
I gave up to keep compatibility with other addons around theme. Instead, "Default" is recommended for those cases.
