### ISSUE TITLE
Can't drag tree onto a non-tree tab

### ISSUE THREAD

**Issue by ceribik** [piroor/treestyletab#716]
In the following situation, you can't drag Tab B (which contains subtabs) onto Tab A:

Tab A
Tab B
~ Tab B1

in order to get the following:
Tab A
~ Tab B
~~~ Tab B1

If you add a subtab (that isn't a tree) to Tab A, then it works fine.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
