### ISSUE TITLE
FF 29 100% cpu usage

### ISSUE THREAD

**Issue by rsamd5** [piroor/treestyletab#720]
After updating FF 29.0.1 with active Tree Style Tab  often eats 100% of cpu.

Extensions:
Session Manager	0.8.1.1	true	{1280606b-2510-4fe0-97ef-9b5a22eafe30}
Adblock Plus	2.6	true	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
FireGestures	1.8.6	true	firegestures@xuldev.org
Tab Mix Plus	0.4.1.4pre.140414a1	true	{dc572301-7619-498c-a57d-39143191b318}
Tree Style Tab (Древовидный стиль вкладок)	0.14.2014051101	true	treestyletab@piro.sakura.ne.jp

if i disable Tree Style Tab then problem is gone away.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
