### ISSUE TITLE
No automatic child tabs.

### ISSUE THREAD

**Issue by mattbel78** [piroor/treestyletab#721]
I don't use NoScript and I use the latest, 2014051101, on FF 25. I use AllTabsHelper, that could be it (and a few other extensions) but otherwise, they are working together. I also use Informational Tab and MTH. I don't see "extensions.treestyletab.autoAttachNewTabsAsChildren" in about:config, there must be something there. I tried adding it with true or default (it disappeared), no change. Middle click or right click are the same. Drag'n drop works fine, and then the next links stay in the tree any way I open them. Any hope for me? Love your stuff but no coder. Thanks.

**Comment by PublicKeys** [comment]
I am also having this issue using FF 38 and latest plug in on a Mac. I also tried adding "extensions.treestyletab.autoAttachNewTabsAsChildren" as setting it to true. This may have started with Yosemite.

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by piroor** [comment]
Seems expired.
