### ISSUE TITLE
Switching Panorama groups results in tree corruption

### ISSUE THREAD

**Issue by kulmegil** [piroor/treestyletab#722]
1. clean start, no session restored
2. build some tabs - open some site, spawn few child tabs at least
3. create a panorama group.
   Either new group (ctrl+shit+e) or sending some existing tabs using context menu: "Move to Group" will do
4. fast switch to new group using CTRL + ` (tilde key) hotkey, change tab
5. switch back to old group, change tab
6. switch back to new group
7.  it shouldn't take long to notice that tabs deattach and magiccaly move to another pano group. Otherwise repeat steps 4-6, add some random actions - shouldn't take long to reproduce

**Comment by Sherris** [comment]
I just experienced a similar problem using Firefox 36.  Switched to a different group, then switched back to my original group and the (200+) tabs were reordered.  It looks like the tree hierarchies I set up are all intact, but they got scattered all over the place.  It has only happened once so far - subsequent group switches haven't given me different order again - but it was a bad once and I'm afraid it may happen again.
