### ISSUE TITLE
I think delay for autohide is bug

### ISSUE THREAD

**Issue by VVelda** [piroor/treestyletab#725]
Hello,
I have tip on improvement of this add-on. I use this add-on in it hidden appereance with delayed showing after focusing bar. But I think this delay should be ignore when I blur panel bar. I would like to panel bar disappear immedeately after I blur it. :-) What do you think about? :-)

Nice day,
add-on is nice ;-)
Jan Velecký

**Comment by piroor** [comment]
Done by 534c8090527d48b1e458eab0bdf61b7f39364f97 and f28946b5f8ca8a36c60f1a397ee3aa6c8aba1a58.
