### ISSUE TITLE
Pinned tab click and visual effect problem in Firefox 29

### ISSUE THREAD

**Issue by Nununene** [piroor/treestyletab#726]
Hello, when updated to Firefox29, treestyle with Pinned tab get click trigger zone error.
please see the attach
![ff29_treestyle](https://cloud.githubusercontent.com/assets/7614818/3006552/cee3cf92-de36-11e3-9a39-6d39ba023153.png)

For example, The Facebook tab's clickable zone will be like that red rectangle,
also rounded edge's effect will show like that

**Comment by casrep** [comment]
I've noticed something about pinned tabs when using the default Firefox theme. There is an ellipses succeeding the favicon as if it is trying to display the the page title along side it. Is there a way to specify that pinned tabs don't get a page title? That may be an good avenue of research.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
