### ISSUE TITLE
Open link as next|previous|first|last new tree

### ISSUE THREAD

**Issue by Coldblackice** [piroor/treestyletab#727]
Often while browsing, I'll see a link that I want to read later. I ctrl-click or middle-click it, which opens it as a new child in the current tree I'm working in. This leads to much disorganization, with random tabs getting mixed in with the trees, deeper and deeper. The trees quickly lose their purpose.

What would be *great* is if we had the ability to open a link as another tree, with potential options being:

-open link as *next* new base-tree
-open link as *previous* new base-tree

So if I'm currently browsing in a tab-tree dedicated to "Programming" and I come across a link to a news article on politics, I could do CTRL-ALT-click and it would open as a new tab in the *next* new tree (ground-level base tree).

Similar to this, another request is the ability to open links into "pre-defined" trees:

Let's say I use the very first top tab-tree as my "free-time" tree, where I want links to go that I'll read later after work. If I see a link I want to read later, I could press CTRL-1-click to send it to the top tree. Or CTRL-9-click to send it into the last/bottom base tree.

Ideally, some way to open a link outside of the current tree I'm working in. I know I can do this manually, clicking and dragging the new tab out, but that takes time and interrupts the workflow. Additionally, even after years of using TST, it's still pretty hard to click and drag tabs to the right spot where you want them to go :) Maybe I'm just too uncoordinated.

Thanks,

**Comment by piroor** [comment]
New actions triggered by new modifier keys are hard to be implemented. Instead, dragging a link and dropping it between tabs will open a new tab there.
