### ISSUE TITLE
FF29 right tab bar tabs appear on left in new windows/after toolbar custimaization

### ISSUE THREAD

**Issue by bensowden** [piroor/treestyletab#728]
When opening a new window or when customizing the toolbar (bar with address bar, etc. in) the tabs leave the tab bar on the right and hover over the web content on the left of the screen. 

They revert back to the correct place when the window is resized or the bookmark toolbar is turned on/off or if the tree style tab preferences are opened and the side is changed from right to some other side and back again.

This started happening when I installed FF29, exiting and re-opening FF does not cause this issue.

![ffbug](https://cloud.githubusercontent.com/assets/4046078/3012524/f64a5d4e-df3a-11e3-9553-c45f40fce6a0.jpg)

**Comment by piroor** [comment]
Is this problem still there?

**Comment by Niluge-KiWi** [comment]
I don't remember seeing this issue for quite some time now.
You can close the issue. If I encounter it again I'll come back here.

**Comment by piroor** [comment]
Thanks!
