### ISSUE TITLE
Since Iceweasel 29, Tree Style Tabs freezes the browser

### ISSUE THREAD

**Issue by gagou9** [piroor/treestyletab#730]
Hello !

I'm under Debian Wheezy.

Since the last update, Tree Style Tabs just doesn't work properly.

It makes Iceweasel freeze for between 10 and 30 seconds before giving hand, and then it's not possible to use the tabs, some are just hidden, clicking on one brings you to another one, some are kinda blinking, stuff like that.

I have 4 tab groups, of 13, 16, 16, and 23 tabs opened.

Addons installed :
- 4or6
- Private Tab
- Addblock Edge
- User Agent Switcher
- Vimperator
- Video without Flash

Thanks for this great addon by the way :)

Gaël

**Comment by piroor** [comment]
Seems expired.
