### ISSUE TITLE
moving tabs upwards causes out-of-order tabs on restart

### ISSUE THREAD

**Issue by sumyungguy** [piroor/treestyletab#735]
I'm having continuing frustration with tabs not being restored in the correct order. I don't know if this is related to #676, but it is definitely _not_ related to Tab Mix Plus, Tab Utilities, or Session Manager addons, nor tab groups, nor duplicating tabs with children. It is not helped by using the nightly development build.

Using a brand new, clean profile, with NO extensions other than Tree Style Tab. The problem is the same with the current release, or the nightly 0.14.2014052700a104704. All default Firefox settings, except "show my windows and tabs from last time". The results are consistent, and I can reproduce them every time.
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:29.0) Gecko/20100101 Firefox/29.0 

Open four tabs as shown, in alphabetical order:
![screenshot_07](https://cloud.githubusercontent.com/assets/5410893/3182777/8b47efd0-ec59-11e3-87de-f5853fad3627.png)

If you move a tab down in the list, the order will stay the same after restart:
![screenshot_09](https://cloud.githubusercontent.com/assets/5410893/3182805/08020dda-ec5a-11e3-90c5-9f0fc9b21c98.png)

But, starting again in alphabetical order, if you move a tab upwards like this:
![screenshot_10](https://cloud.githubusercontent.com/assets/5410893/3182809/2f321328-ec5a-11e3-8317-441d142c55cf.png)

Then after restart, the tabs will be out of order:
![screenshot_11](https://cloud.githubusercontent.com/assets/5410893/3182812/3ece52e2-ec5a-11e3-9770-8838272f4685.png)

Now you can put them back in alphabetical order and they will stay that way, but only if you only move tabs downwards.

Also if you move a tab upwards into a tree:
![screenshot_12](https://cloud.githubusercontent.com/assets/5410893/3182832/c7445d06-ec5a-11e3-9793-3c9117ac5e90.png)

Then after restart, tabs are again out of order:
![screenshot_14](https://cloud.githubusercontent.com/assets/5410893/3182835/dd5d5d18-ec5a-11e3-8e1c-81aeb770464b.png)

But moving a tab downwards into a tree is ok.

**Comment by sumyungguy** [comment]
There seems to be a regression on this... With latest Firefox (41.0.1) and TST nightly (0.151.2015100200a162618), I'm again seeing the behavior I described in the original post. However, I'm not seeing the one I described on Oct 22, 2014.

I don't know with what versions this started again, I only noticed it now.

**Comment by piroor** [comment]
@sumyungguy I couldn't reproduce this problem on Ubuntu, Firefox 41, and TST latest nightly. Any other addon around tabs, like Tab Mix Plus?

**Comment by sumyungguy** [comment]
I'm using a brand new, clean profile, with NO extensions other than Tree Style Tab. All default preferences, except "show my tabs from last time". I can reproduce it 100% of the time.
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:41.0) Gecko/20100101 Firefox/41.0

I tested on Windows 7, also with a clean profile and Firefox 41.0.1. I don't see the behavior I described in the original post, but I do see the behavior I described on Oct 22, 2014 above.

**Comment by piroor** [comment]
Thanks. I've confirmed that the problem told at https://github.com/piroor/treestyletab/issues/735#issuecomment-60080927 appears on my environment. Rearranged children tabs are restored with different order.

**Comment by piroor** [comment]
Recent commits should fix the problem https://github.com/piroor/treestyletab/issues/735#issuecomment-60080927 so could you try the [development build](http://piro.sakura.ne.jp/xul/xpi/nightly/)? @sumyungguy

**Comment by sumyungguy** [comment]
I did some more testing. There is different behavior with different TST versions, and different between Mac and Windows. The version of Firefox doesn't make any difference.

The new 2015-10-06 nightly fixes bugs on Windows, but makes Mac worse:

There are two issues I described. In the first post, https://github.com/piroor/treestyletab/issues/735#issue-35023724:
BUG1 - "Moving a tab with no parent upwards, the tab that was just above it is also moved, after restore. Moving tabs downwards works as expected."

And, in https://github.com/piroor/treestyletab/issues/735#issuecomment-60080927
BUG2 - "Moving a child tab upwards in its tree, the tab that was just above it is also moved, after restore. Moving tabs downwards works as expected."

So BUG1 and BUG2 are the same, except the first is tabs with no parents, the second is child tabs moved in their own tree.

We may see either BUG1 or BUG2, but never both together.

These are the versions I tested:
*Here, Mac and Windows have the same BUG1:*
TST release 2014-05-11 - Mac: BUG1, Windows: BUG1
TST nightly 2014-05-27 - Mac: BUG1, Windows: (probably BUG1, but I don't have the nightly anymore)
*Here BUG1 is fixed, but BUG2 is introduced, in Mac and Windows:*
TST nightly 2014-10-01 - Mac: BUG2, Windows: (probably BUG2, but I don't have the nightly anymore)
TST release 2014-12-01 - Mac: BUG2, Windows: BUG2
TST release 2015-03-06 - Mac: BUG2, Windows: BUG2
*Here, Mac has regression to BUG1, Windows still has BUG2:*
TST release 2015-09-02 - Mac: BUG1 (regression), Windows: BUG2
*Here, Mac still has BUG1, which gets worse; but Windows has no bugs:*
TST nightly 2015-10-06 - Mac BUG1*, Windows: no bugs found
*-with latest nightly 2015-10-06, on Mac, moving tabs with no parent downwards, not only upwards, now also moves the tab that was just above it. So on Mac, the new nightly is worse than before. On Windows, both bugs seem to be fixed.

Please let me know if there's something else I can help to test...

**Comment by piroor** [comment]
The problem can still appear on some environments, because the problem was possibly caused by wrong meta data stored to each tab. If you don't see the problem with newly opened window, you possibly have to restructure your tabs at the main window.

Anyway, I think that debug information at your environment can help me. Could you run the script `JSON.stringify(gBrowser.treeStyleTab.dumpTreeInformation())` on the [Browser Console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console) before restarting (with expected order) and after (with broken order) and paste both results at here?

**Comment by sumyungguy** [comment]
Ok, I did this:
1. made a newly opened window, and created the four tabs.
2. moved the last tab to the first position.
3. after restart the last tab is now in the second position, with the third tab in the first position.

In every case, the output of the script is the same:

```
"[{"id":"TAB-0","insertBefore":"TAB-1"},{"id":"TAB-1","insertBefore":"TAB-2","insertAfter":"TAB-0"},{"id":"TAB-2","insertBefore":"TAB-3","insertAfter":"TAB-1"},{"id":"TAB-3","insertBefore":"TAB-0","insertAfter":"TAB-2"}]"
```

Also to report, that the latest release version 0.16.2015111001 on the Mac has the additional problem that moving tabs downwards, not only upwards, now causes re-ordered tabs on restart. This makes session restoring more unstable, so at the moment I am stuck with 0.15.20150902901.

Thanks...

**Comment by piroor** [comment]
Thanks. I've confirmed that the last tab had a wrong "insertBefore" information. It doesn't cause your problem for me but it may be the reason why tabs are wrongly ordered on your PC. The commit 184555c solves such broken information after tab reordering. Could you try the latest development build again?

**Comment by sumyungguy** [comment]
Ok, good, both problems I described above are now fixed, thanks!

But we are not quite out of the woods yet... in testing some more, I also found this:
![screenshot_143](https://cloud.githubusercontent.com/assets/5410893/11540439/13e8e598-992d-11e5-85c6-495d204be399.png)
If I set up tabs as pictured, the script result is:
`"[{"id":"TAB-0","children":"TAB-1","insertBefore":"TAB-2","actualChildren":[{"id":"TAB-1","parent":"TAB-0"}]},{"id":"TAB-2","insertBefore":"TAB-3","insertAfter":"TAB-0"},{"id":"TAB-3","insertAfter":"TAB-2"}]"`
Then I move the second tab out of the tree, like this:
![screenshot_144](https://cloud.githubusercontent.com/assets/5410893/11540545/a1dd78aa-992d-11e5-9a8e-a01f9e5930a3.png)
And the result is:
`"[{"id":"TAB-0","insertBefore":"TAB-2"},{"id":"TAB-1"},{"id":"TAB-2","insertBefore":"TAB-3","insertAfter":"TAB-0"},{"id":"TAB-3","insertAfter":"TAB-2"}]"`
Tab 1 has no insert information. After restart, it looks like this:
