### ISSUE TITLE
Firefox doesn't start with TST enabled

### ISSUE THREAD

**Issue by Opennat** [piroor/treestyletab#736]
Two days ago my Firefox session crashed, and after starting again it does not firing up. After some attempts to start it, then after trying to disable each addons one-by-one, I determined, that TST is the problem :/

With TST disabled, Firefox starts flawlessly (as it doing usually), spending 1-2 min to be ready to use (1,4Gb memory at start, 1,9Gb in the process of use). With TST enabled, Firefox starts to grew up to 2,1-2.2Gb memory, stucks at this point for 2-3 minutes, then quickly starts eating memory (around 2 min to reach all available 12Gb, then eats all swap in same manner, and after that - crashed).

Tried all versions of TST from April up to current nightly version as of 27/05, but no success.

I never had any problems with TST for last 4-5 years, so asking for methods, how to determine, what is caused this behavior?

Session contains nearly 900 tabs/1 window. Last opened tabs (before session crash) I have closed (which I thought could be a problem).

Last updated addon is NoScript, so I disabled him, but FF anyway doesn't start (if TST enabled).

Here is the spec:
Firefox: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0

List of addons:
about:addons-memory	8	true	about-addons-memory@tn123.org
All Tabs Helper	0.2.8	true	alltabshelper@alltabshelper.org
Classic Theme Restorer	1.1.8	true	ClassicThemeRestorer@ArisT2Noia4dev
Clean Links	2.6.0	true	{158d7cb3-7039-4a75-8e0b-3bd0a464edd2}
Cookie Monster	1.2.0	true	{45d8ff86-d909-11db-9705-005056c00008}
FEBE	7.3.0.1	true	{4BBDD651-70CF-4821-84F8-2B918CF89CA3}
GNotifier	1.7.9	true	jid1-OoNOA6XBjznvLQ@jetpack
Google/Yandex search link fix	1.4.1	true	jid0-XWJxt5VvCXkKzQK99PhZqAn7Xbg@jetpack
Greasemonkey	1.15	true	{e4a8a97b-f2ed-450b-b12d-ee082ba24781}
HTTPS-Everywhere	3.5.1	true	https-everywhere@eff.org
InlineDisposition	1.0.2.4	true	{123647d5-da43-4344-bfe2-fc093bdf8f5e}
LastPass	3.1.1	true	support@lastpass.com
Normal "Open In" dialog	2.6	true	normalopenindialog@miksan
NoScript	2.6.8.28	true	{73a6fe31-595d-460b-a920-fcc0f8843232}
Pure URL	1.2.4	true	pure-url@jetpack
RefControl	0.8.16	true	{455D905A-D37C-4643-A9E2-F6FEFAA0424A}
Restartless Restart	9	true	restartless.restart@erikvold.com
Right Links	0.3.8.3	true	{B5F5E8D3-AE31-49A1-AC42-78B7B1CC5CDC}
Session Manager	0.8.1.2	true	{1280606b-2510-4fe0-97ef-9b5a22eafe30}
Tab Mix Plus	0.4.1.3.1	true	{dc572301-7619-498c-a57d-39143191b318}
Tree Style Tab	0.14.2014052700a104704	true	treestyletab@piro.sakura.ne.jp
Ubuntu Firefox Modifications	2.7	true	ubufox@ubuntu.com

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
