### ISSUE TITLE
Tabbar corruption when clicking tabs with specific content

### ISSUE THREAD

**Issue by Valentin-N** [piroor/treestyletab#737]
I've had this issue for more than a couple of years, but it has finally annoyed me enough to post a bug report.

Whenever I click a tab with specific content (will come back to this later) I will imediately get tabbar corruption where some tabs or just their border become invisible. The tabs that get corrupted are always not the one I click. The corruption is automatically fixed when moving the mouse over the corrupted tabs.

Here is an example of the tabbar corruption:
![tst_issue](https://cloud.githubusercontent.com/assets/1926716/3208819/5db91478-ee47-11e3-80d6-046dfef00b74.png)

I have to note that I've tried most of the skins, but only the "Default (specified by the Theme)" skin is unaffected by this issue. Since moving to FF 29, the default skin does not make sense when used with TST, so I'm forced to use one of the other bundled skins, which show corruption.

Over time I've observed that what triggers this corruption is clicking specific tabs with images. The image doesn't have to be large, but only specific images trigger this problem. One such example is this: http://www.tesco.ie/groceries/MarketingContent/Sites/Retail/superstore/Online/p/i/home/new_ghp_images/anon/promo-anon.jpg

The corruption doesn't happen immediately, sometimes it happens after the browser has been running for as little as 5 minutes, other times it takes days.

My setup:
- Windows 7 x64 / Windows 8.1 x64 (happens on both)
- Firefox stable 29.0.1 (but has been happening for a long long time)
- TST is the only installed extension that modifies the GUI
- The problem appears on several machines with various hardware. The graphics cards I've tested on are Intel/AMD/Nvidia.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
