### ISSUE TITLE
bug in fixed tab

### ISSUE THREAD

**Issue by CB9TOIIIA** [piroor/treestyletab#738]
I found a bug where the tab is locked and you want to minimize.

![y45645](https://cloud.githubusercontent.com/assets/1074710/3268160/a8949b30-f2d8-11e3-8a51-c35d4072022c.gif)

![sdf43](https://cloud.githubusercontent.com/assets/1074710/3268147/828fe2d2-f2d8-11e3-9a7e-91f188849ae4.gif)

**Comment by piroor** [comment]
This seems to be already fixed on recent versions for me. Can I close this?

**Comment by CB9TOIIIA** [comment]
yep
