### ISSUE TITLE
Tree not restored with many tabs since FF29+

### ISSUE THREAD

**Issue by Tragen** [piroor/treestyletab#739]
I have 8 windows with over 1000 tabs.
Everything is working in FF28. When I update to
FF29 or FF30 and I try to restore my last session,
only one or two windows are correctly restored.
All other windows will have the tabs on the first level.
I can manually load each single window and the
tree is restored correctly. But loading the complete
session with all tabs at once doesn't work.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
