### ISSUE TITLE
TST mysteriously stopped working

### ISSUE THREAD

**Issue by silverdrake3** [piroor/treestyletab#740]
I'm running TST in Firefox 26 on Linux Mint.  Yesterday (June 22nd) my tabs reset to the default position.  I tried disabling the add-on, uninstalling/reinstalling, disabling all other add-ons, but no luck.  TST is the reason I use Firefox and I would be very sad to lose this functionality.

If there are any details I should add, please let me know.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
