### ISSUE TITLE
High CPU usage (onTabbarOverflow)

### ISSUE THREAD

**Issue by CyberShadow** [piroor/treestyletab#746]
Sometimes Firefox starts consuming 100% of one CPU core, even when idle with no tabs open (except the new tab page). TreeStyleTabs seems to be the cause.

I have recorded a JS profile. It seems to indicate a lot of `onTabbarOverflow` calls.

Please see the JS profile:
http://dump.thecybershadow.net/85b2fae3645631a635b1e3991b4ee86b/Profile%201.json.7z

**Comment by wsmwk** [comment]
@CyberShadow do you still see this problem with newer versions?
(I have not never it, so perhaps something else needs to trigger it)

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
