### ISSUE TITLE
Tab bar overlaps vimperator status bar

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [piroor/treestyletab#747]
Hi,

When installing TST, the tab bar at the left goes from the top to the bottom of the browser window. Unfortunately, at the bottom Vimparator displays its status and command prompt bar, so the last element of the tab sidebar overlaps the prompt.

Maybe you could detect this and automatically make the tab bar a bit shorter, so it doesn't overlap?

Thanks and good job on this neat extension!

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
