### ISSUE TITLE
Can't drag links to tab bar, if installed NoScript

### ISSUE THREAD

**Issue by Infocatcher** [piroor/treestyletab#748]
Just try to drop any link to tab bar: nothing happens and all draggable things (links, bookmarks, etc.) becomes not draggable.

Tested with Firefox 31.0, <a href="https://addons.mozilla.org/firefox/addon/noscript/">NoScript</a> 2.6.8.33, 2.6.8.34, Tree Style Tab 0.14.2014051101, 0.14.2014070300a020408 (latest).

Also all works fine in Firefox 30.0.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
