### ISSUE TITLE
Dragging from Bookmarks breaks dragging cabilities

### ISSUE THREAD

**Issue by Astromere** [piroor/treestyletab#755]
Attempting to drag a Bookmark from the Bookmark Toolbar into any position on TST fails and then breaks all dragging abilities (nesting, re-ordering, etc) until Firefox is rebooted.  No recently installed Addons and disabled anything recently updated with no change.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
