### ISSUE TITLE
vertical tab bar does not resize, only one tab visible

### ISSUE THREAD

**Issue by awayand** [piroor/treestyletab#756]
when using the vertical view of tab bar with pentadactyl, there is only one visible tab, the others are not visible. does not occur when using horizontal view. not sure if this is a pentadactyl bug or tree style tab bug, but thought I would mention it.

**Comment by piroor** [comment]
Link to the Pentadactyl's thread: https://groups.google.com/forum/#!topic/dactyl-bugs/0JjO8REYoiU

**Comment by piroor** [comment]
Is this problem still there?

**Comment by jnpkrn** [comment]
Cannot speak for others but

> modulo '+' Open a new tab button under the bottom tab in the vertical layout
> overflowing to pentadactyl's line

still stand for me.

firefox-44.0-5.fc22.x86_64
Tree Style Tab 0.17.2016031101
Pentdactyl as of https://github.com/5digits/dactyl/commit/0b835e187b17559b7d39aad1f6886b17d36b0c27

I learned to live with that, e.g., when I want to see the full URL
of the current tab, I hit Shift+O (edit current URL) and the status
line will be brought into the foreground instantly.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
