### ISSUE TITLE
how to donate to developers?

### ISSUE THREAD

**Issue by Kebap** [piroor/treestyletab#761]
Hello, I love this extension, and have been using it for a long time. It would be great as a default option in Firefox! However, I can't find a way how to donate to the fabulous developers of this addon? Please show me a way. Thank you and best wishes.

**Comment by piroor** [comment]
Thanks, but sorry, I have no plan about any donation because I hope to keep me as the prime user of this project. i hope to keep having a privilege to say "no" about requests not matched to my vision. Instead, please fork this project freely for your purpose if needed.

**Comment by HamsterHuey** [comment]
@piroor - I ended up here looking to find out if I could donate. I respect your standpoint on donations 👍 . At least I wanted to pay you back by letting you know how grateful I am for your continued support of this outstanding add on. I have been using it for many many years now. I cannot be on the internet without it. It is the first extension I install on Firefox on every computer I ever touch and I continue to get more friends and family into using it. I can't even quantify just how much it has improved my productivity when working on many different things on the web (I say this while I have 60+ tabs open in FF currently :-). Best wishes and thanks again for all your hard work!

**Comment by kernc** [comment]
This. ↑

**Comment by akeeton** [comment]
I second @HamsterHuey's response and it's truly fantastic that @piroor is still contributing to this delightful extension.

It's difficult to remember a time when I haven't used Tree Style Tabs (OK, maybe I wasn't using it with Mozilla Phoenix :P).  TST is *the* reason Firefox is my go-to browser.  I wish everyone knew about!

**Comment by 3d73a4a412** [comment]
Well it seems clear piroor is not doing this for the donations, it took me awhile to find this. I too wanted to express my gratitude, this is one of the first and few addons that I add when using firefox - to say its indispensable would be a gross understatement. If piroor decides in the future to accept donations I will happily get in line! THANK YOU PIROOR!!!!!!!

**Comment by alith** [comment]
Well, I was looking for a donation option to contribute, after many many years of use, and...
Well, thanks a lot.
And also. Thanks for proving me wrong about the web being less and less free, and more and more ad oriented or money pursuing. Long live the FOSS.
Thanks.

**Comment by piroor** [comment]
I'm working as an engineer at a FOSS friendly company @clear-code providing commercial support for Firefox and Thunderbird for a long time. There are large benefit on our business that I'm keeping me an expert of Firefox, thus my boss allows me to develop Firefox addons during our business hours when I'm not busy in tasks. I think you won't need to worry about the death of this project while our business is still alive, even if there are no donation way. Thanks!

**Comment by MasterKia** [comment]
> Thanks for proving me wrong about the web being less and less free, and more and more ad oriented or money pursuing. **_Long live the FOSS._**

@alith 
The Free in FOSS doesn't mean "free of charge", it means "free as in freedom (libre)"; a software [that respects your _**freedom**_](https://gnu.org/philosophy/free-sw.html) as a user.

FOSS: Free/Libre and open-source software

**Comment by alith** [comment]
I thought that was the difference between free software and open license software.
The article you linked speak at length of the difference between open source soft and free open source soft. And also freedom of speech and not free beer.
But what do we call free (beer) software then? Is freeware still something meaningful?

**Comment by MasterKia** [comment]
> The article you linked speak at length of the difference between open source soft and free open source soft

That's true, but the article does point out that _nearly all "open source" programs are in fact free (as in freedom)._

"Open Source" is based on [practical advantages only](https://www.gnu.org/philosophy/open-source-misses-the-point.html)  and says that if you "open source" your software, then users can "add features and fix bugs" for you.

Free Software says that if you want your software to respect the user's freedom, it should have the four freedoms.


In the end, some people created the word "FOSS" to avoid the confusion of "free of charge" and "free as in freedom"; but I think it wasn't a good idea because now people would think FOSS means "Free of charge and open-source software".
So [FLOSS is a better term to use](https://www.gnu.org/philosophy/words-to-avoid.en.html#FLOSS) in my opinion. But I mostly use the term "Free/Libre software".

> what do we call free (beer) software then? Is freeware still something meaningful?

Yes. "[Freeware](https://www.gnu.org/philosophy/words-to-avoid.en.html#Freeware)" or "free of charge" software should work.
Wikipedia users the term "Freeware" to refer to non-free (proprietary) software that are free of charge.
For example: "[CPU-Z is a freeware](https://en.m.wikipedia.org/wiki/CPU-Z) system monitoring application".

**Comment by arthur-tacca** [comment]
I just want to add my grateful thanks for your work on this plugin.

I found this issue after the release of version 3.9.21 did not go so well for some people (including me). I suspect you will get some annoyed posts about it, but you and I know that bugs will sometimes happen! So I had wanted to donate to compensate for any negativity you might get. Instead, I will just say: thanks again for all your hard work ❤️

**Comment by MicIcarus** [comment]
Similar to others here, I've been trying to figure out how to donate and help the ongoing support of this extension (I can only imagine how much work it takes to continually support this project!)
Happy to hear that it's currently not needed, but if anything changes, I'll be the first in line to donate!
I love (need) TST to help manage over 1000 tabs in multiple windows for work & research.  Can't really live without TST!
Thank you again for creating this "perfect" solution!  It's stable, resource efficient, the hierarchical tabbing is beautiful and keeps all my research pages organized in an intuitive format for analysis!

**Comment by LupinIII** [comment]
After using the extension for so long, I also would have liked to give something. Do I remember correctly and 昔々 😉 TST (or it's predecessor) was available as a XUL-addon that ran in Netscape Communicator already? If it was, I've been using this extension for over two decades.

I'm glad to hear that your company is fine with it and even kind of supports you doing this. But at the same time I now hope that your retirement isn't coming too soon 😉. I wouldn't know what to do without TST. I can't use a browser without it! TST is just how browser tabs should have been all along.

ほんま に ありがとう ございます。
