### ISSUE TITLE
Introducing tab groups to treestyletab

### ISSUE THREAD

**Issue by nyanpasu** [piroor/treestyletab#770]
![43974](https://cloud.githubusercontent.com/assets/6234817/4517354/107926a4-4c2e-11e4-83d7-7477df9bd5ee.png)

Is it possible to group tabs manually like in [Vertical Tabs](https://addons.mozilla.org/en-US/firefox/addon/vertical-tabs/)?

At the moment you can only group tabs under other tabs. It would be nice if you were able to manually group them under a name.

**Comment by piroor** [comment]
There are too many subjects so I close this for now. If you see any problem or feature request around it, please open new issue for each individual subject.

**Comment by derekbasch** [comment]
I know this is closed but another vote for a context-menu item that would create groups.

Thanks for the great plugin!

**Comment by tompropst** [comment]
Adding a reasonable work-around here...
If you have one group tab created (as described many ways above), quickly create others from the context menu with "Duplicate Tab". Then just rename and you're set.

**Comment by igoralmeida** [comment]
Sorry for bumping this, but what would be the best fix/workaround for this:
> 4. Any chance to have left click on a tab not to autoload the selected tab, for instance for drag-drop operations?

Having quite a few tabs and tab groups means that reorganizing them involves clicking on tabs I'm not really interested right now... If I could drag'n'drop without restoring(?) them (say, holding Alt when dragging) that would be a huge performance benefit.

**Comment by derekbasch** [comment]
@igoralmeida try using the Tab Suspender add-on. It has an option for not loading selected tabs.

https://addons.mozilla.org/en-US/firefox/addon/tab-suspender-tab-unloader/

**Comment by igoralmeida** [comment]
@derekbasch Thanks, but unfortunately that one is deprecated and the newer version does not seem to do that
I think the minimal functionality for this use-case is to simply prevent a tab from loading/showing up in the viewer when dragging. I could not find extensions or bugs that mention this...

**Comment by derekbasch** [comment]
@igor the deprecated version will still work with Quantum. It has an experimental feature that you can enable for now. I imagine the dev will port all the plugin features to the new version shortly.

 
 
  On Mon, Jan 29, 2018 at 1:02 PM, Igor Almeida<notifications@github.com> wrote:   
@derekbasch Thanks, but unfortunately that one is deprecated and the newer version does not seem to do that
I think the minimal functionality for this use-case is to simply prevent a tab from loading/showing up in the viewer when dragging. I could not find extensions or bugs that mention this...

**Comment by igoralmeida** [comment]
@derekbasch ah right, I didn't even try to read everything, sorry about that.
Indeed it "helps", since the viewport is updated with a simple "tab is unloaded" page.
One thing I also did was to install Multiple Tab Handler, which allows Ctrl-click to select several tabs. Also helps.

Though much of my problem is now moot since I inadvertently closed a 100+ subtree before I managed to organize it, of which I recovered only 10... -_-

**Comment by qwitwa** [comment]
The solution I'm happy with is just to set my homepage to the URL above and click the home icon in the toolbar whenever I want a new tab group, which works fine, unlike some of the addons that try to change the new tab page but can't support the "about:" URL scheme.

**Comment by qwitwa** [comment]
My above solution seems to have been broken by a recent firefox update.

**Comment by ptbrowne** [comment]
It is also possible to use the search feature of bookmarks to easily create a group.

Add a bookmark with location "about:treestyletab-group?title=%s" and keyword "tst" and then you can create a group from the location bar with "tst nameofthegroup".

**Comment by emvaized** [comment]
@piroor 
Could you please reconsider this after so many years and the continued interest in this feature from users? 
I don't really think that one more context menu entry to 'create tab group' would bring too much complexity.

And at the same time it makes no sense to create whole separate TST Addon just to add that context menu entry.

**Comment by piroor** [comment]
It is beyond the scope of TST project so it won't become a built-in command of TST. Instead how about adding TST More Tree Commands to extend the context menu?:
https://addons.mozilla.org/firefox/addon/tst-more-tree-commands/
https://github.com/piroor/tst-more-tree-commands#authors-comment-from-piroor

**Comment by emvaized** [comment]
Thanks for link, it makes total sense. I did not know about this extension.

However, I just tried it, and 'Create group' entry is always greyed out for me for some reason. Am I doing something wrong?

UPD: I figured it out, user needs to select multiple tabs first for this option to become available. I guess I should create new issue about enabling it in single tab's menu, which will create new group with all descendant tabs.

**Comment by Makishima** [comment]
Sorry for writing in the closed ticket but maybe anyone know compatible extension that could organize groups by color?
Like in Edge
![изображение](https://user-images.githubusercontent.com/5548003/190109623-56f396cf-e99c-49a3-b817-a7e105b7dea7.png)

**Comment by irvinm** [comment]
@Makishima there seem to be a few addons for TST and colors, but none that do exactly what you are looking for.  There are probably other addons (non-TST specific) that deal with coloring, but they are unlikely to handle the case of coloring by tree.

https://addons.mozilla.org/en-US/firefox/addon/tst-colored-tabs/
https://addons.mozilla.org/en-US/firefox/addon/tst-colorize-tabs/

**Comment by PubliqPhirm** [comment]
> You can open a group tab with a URI, "about:treestyletab-group?title=foobar"

I used this to create a keyword one can use to create new TST folders.

1. Open the Bookmark manager
2. Create a new bookmark with URL of `about:treestyletab-group?title=%s`
3. Give it a keyword.  I used `tst`.
4. To create a TST folder named "fhqwhgads", I type `tst fhqwhgads` in the URL bar and smash that enter key.

**Comment by mambusskruj** [comment]
> It is beyond the scope of TST project so it won't become a built-in command of TST. Instead how about adding TST More Tree Commands to extend the context menu?: https://addons.mozilla.org/firefox/addon/tst-more-tree-commands/ https://github.com/piroor/tst-more-tree-commands#authors-comment-from-piroor

@piroor This is life-saving for me. Thank you! I was needed to group a related number of tabs with some jobs running. And I wanted to provide clear comment on what to do next with these tabs once jobs are finished. So tab grouping with the ability to name group title helps me a lot.
