### ISSUE TITLE
Some elements of the tab bar hides vimperator plugin's elements

### ISSUE THREAD

**Issue by nyanpasu** [piroor/treestyletab#771]
![2014-10-06-032456_1440x900_scrot](https://cloud.githubusercontent.com/assets/6234817/4519667/857631d0-4cc5-11e4-9373-9642867a3202.png)

Bottom-left: The foreground text of TST is drawn over vimperator's window.

**Comment by timss** [comment]
I believe this is due to wrong, or a rather agressive `z-index` used with the Tree Style Tab skin. This is especially true when using auto hide:

	/* put resizer under tabs, and raise up tabs */
	.treestyletab-tabbar-toolbar[treestyletab-mode="vertical"][treestyletab-tabbar-autohide]
	> *,
	.treestyletab-tabbar-toolbar[treestyletab-mode="vertical"][treestyletab-tabbar-autohide]
	> #tabbrowser-tabs,
	.treestyletab-toolbar-inner-box[treestyletab-tabbar-autohide]:not([treestyletab-tabbar-fixed="true"])
	> *,
	.treestyletab-toolbar-inner-box[treestyletab-tabbar-autohide]:not([treestyletab-tabbar-fixed="true"])
	> #tabbrowser-tabs {
		position: relative;
		z-index: 2;
	}
	.treestyletab-tabbar-toolbar[treestyletab-mode="vertical"][treestyletab-tabbar-autohide]
	#treestyletab-tabbar-resizer-box {
		position: absolute;
		bottom: 0;
		left: 0;
		right: 0;
		top: 0;
		z-index: 1;
		line-height: 0 !important; /* to avoid an useless space above the splitter */
		font-size: 0 !important; /* to avoid an useless space above the splitter */
	}

From [`treestyletab.css`](https://github.com/piroor/treestyletab/blob/master/content/treestyletab/treestyletab.css). Not sure what would be the best fix for this.

For more information you might take a look at #843 which fixes a similar issue.

**Comment by timss** [comment]
I believe this can be closed as of d6be4e6 and #843

**Comment by piroor** [comment]
Is this already solved? Can I close this?

**Comment by nyanpasu** [comment]
Issue still persists as of ee0937e

**Comment by piroor** [comment]
I couldn't reproduce this with the combination:

 * Ubuntu 14.04LTS
 * Firefox 44.0.2
 * TST latest development build 27783578643d61e3fa73cd53cfa64e0596538e68
 * Vimperator 3.11.3

Steps to verify:

 1. Install both addons.
 2. Type "t".
 3. The list of commands starting with "t" is shown as I expected.

If you still see the problem, could you describe detailed steps to reproduce?
See also: https://github.com/piroor/treestyletab/blob/master/CONTRIBUTING.md

**Comment by nyanpasu** [comment]
Can confirm it also works for me recently.
