### ISSUE TITLE
Keyboard Shortcuts for modifying tree

### ISSUE THREAD

**Issue by Nadaron** [piroor/treestyletab#772]
Thanks for this great Addon!

I don't know if this a bug or if I am to dumb ... Under features on the homepage there's listed:
> If you focus to the tab bar, Ctrl-Up/Down/Right/Left can be used to modify tree.

This doesn't work for me. I click on a Tab and try moving it around in the tree with Ctrl-Up/Down/Right/Left.

Tree Style Tab 0.14.2014051101
Firefox 32.0.3 on Windows 8.1

**Comment by piroor** [comment]
It was a feature of Firefox itself. you need to re-activate it by userChrome.css. See also: https://github.com/piroor/treestyletab/issues/836#issuecomment-76598502

**Comment by sumyungguy** [comment]
Note: a good solution is to create custom shortcuts using the "Move tab" scripts of TST. That way, it's not necessary to re-activate the tab focus feature in userChrome.

Details here:
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-keyboard-shortcuts
