### ISSUE TITLE
Improve response of tab dragging

### ISSUE THREAD

**Issue by SicariusNoctis** [piroor/treestyletab#778]
Tab dragging seems clunky and awkward.

I think a simple solution to this would be to disable "previewing" the movement of the tab. In other words, keep the tree the same until the user releases the tab. This increases speed (less redraws) and also prevents the tabs from moving around while the user tries to position the dragged tab.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
