### ISSUE TITLE
TST disappears with All-In-One Sidebar (toggling with grip)

### ISSUE THREAD

**Issue by joeytwiddle** [piroor/treestyletab#783]
I don't have auto-hide or auto-shrink.  I have "Show tab bar always" and I click the grip when I want to hide or show TST manually.

With All-In-One Sidebar installed, clicking to hide works, but when I click the grip again to show TST, the grip disappears and TST does not appear!  Now I can't get it back...

(I can get it back if I go to preferences and temporary enable auto-hiding and get it to open again.)

***A workaround for any other users experiencing this:  Do not click the grip to re-open TST.  Instead drag the grip open.  That will avoid the issue of TST and its grip disappearing.***

(PS: I would be very happy if TST could be one of the icons in All-In-One Sidebar, but I know that's a long shot!)

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
