### ISSUE TITLE
 Fails to hack GM_openInTab in Greasemonkey 2.3

### ISSUE THREAD

**Issue by mitsuba-clover** [piroor/treestyletab#785]
In Greasemonkey 2.3, the implementation of GM_openInTab is moved from components/greasemonkey.js to modules/miscapis.js, which breaks TST's hack to cooperate with it.
See: greasemonkey/greasemonkey@d2822b79eaec63ab2f8aa7646a82bdf3350a312e

**Comment by piroor** [comment]
Can I close this?

**Comment by mitsuba-clover** [comment]
I'm sorry for not managing the issue I opened. It seems TST 0.16.2015110701 (and 0.16.2015110801) resolved this issue.
Thank you!

**Comment by piroor** [comment]
Thanks!
