### ISSUE TITLE
Issue with extra space above the tab bar

### ISSUE THREAD

**Issue by HatsInACat** [piroor/treestyletab#786]
I recently upgraded to FF33 and I noticed that during the huge move from 26, there's been this extra space above the tab bar that is directly because of Tab Tree (I disabled every other addon to make sure). It can be seen in this first picture here http://puu.sh/cFkiH.jpg

When I disabled the addon ( and enabled the rest ) I ended up with this http://puu.sh/cFkjJ.jpg

Is there some error on the addon's fault that it can't merge with the min/max/close buttons area anymore? Fiddling with Firefox's Customize settings didn't fix it, and I'd like to continue to use the app but without the annoyance of forcibly lower tabs.

**Comment by piroor** [comment]
Seems expired. If you see this problem again, please open new issue with more detailed steps to reproduce: https://github.com/piroor/treestyletab/blob/master/CONTRIBUTING.md
