### ISSUE TITLE
[Mac] [Firefox Developer Edition] [35.0a2 (2014-11-11)] TST disappears when FF incognito opens in full screen

### ISSUE THREAD

**Issue by agarwav** [piroor/treestyletab#789]
Steps to repro:
1. Open FF Developer Edition in full screen (mac) (Cmd + Shift + F).
2. Open Incognito Window from this FF window (Cmd + Shift + P).
3. The incognito window will open in full screen mode but TST disappears.
4. Bring the incognito window from full screen mode to small mode. TST appears and stays when incognito window is again switched to full screen mode.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
