### ISSUE TITLE
Trees always expanded on FF startup

### ISSUE THREAD

**Issue by korg250** [piroor/treestyletab#792]
All trees are shown as expanded in the start of FF. There's no option to change that.

Using FF 33.1.1 with TST 0.15.2014111301.

**Comment by piroor** [comment]
This still doesn't appear on my environment. Could you explain details how to reproduce this?
See also: https://github.com/piroor/treestyletab/blob/master/CONTRIBUTING.md

**Comment by piroor** [comment]
I close this for now. If the problem is still there, please add a comment.
