### ISSUE TITLE
Tree Style Tab + Tabs On Bottom

### ISSUE THREAD

**Issue by jcford73** [piroor/treestyletab#797]
I read and understand the your explanation of why double-clicking on the tree background doesn't open a new tab. Per your suggestion, I downloaded your separate Tabs On Bottom addon to add this functionality. However, the combination of the two addons cause the browser's title bar to disappear entirely and the toolbar buttons become obscured by the windows minimize, maximize and close buttons.

http://i.imgur.com/EDvxnM0.png

**Comment by FillInTheBlank** [comment]
I tried that and it didn't work.
The thread is also from 2011 and is in regards to FF4

**Comment by JCinDE** [comment]
I used the instructions in that link to apply a style through Stylish and it worked perfectly for me.

**Comment by npblubb** [comment]
Well it does work for me (that's why i linked it) although i made a slight modification:

#navigator-toolbox > #TabsToolbar 
{
  -moz-binding: url("chrome://global/content/bindings/toolbar.xml#toolbar")!important;
}

userChrome.css must be in a chrome folder in your profile in AppData\Roaming.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
