### ISSUE TITLE
Open Link in Background Tab opens tab at the very end of the tree not as a child tab

### ISSUE THREAD

**Issue by talentedmrripley** [piroor/treestyletab#800]
After upgrading to 33.1.1 the open in background doesn't work correctly.  I right click on a link and choose the Open Link in Background Tab and it opens it at the very end of the entire tree.  Choosing Open Link in New Tab works correctly.  I have tried removing and reinstalling the addon as well as grabbing the latest version from your website.  Neither has resolved the issue.

Turns out this was a conflict with Tab Mix Plus.  Updating to the latest dev version, 0.4.1.6pre14111a1, seems to have resolved the issue.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
