### ISSUE TITLE
 Misplaced tabs after clicking "Exit Customize" when using Tree Style Tab add-on.

### ISSUE THREAD

**Issue by vijaykm2** [piroor/treestyletab#806]
I created this bug earlier in bugzilla and they asked me to report it here. Here are steps to recreate this bug:

User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0
Build ID: 20141125180439

Steps to reproduce:
1. Create a new profile and install Tree Style Tab add-on (https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/ )
2. Change options to set tabs
   
   on right side of screen.
3. Click on Menu and Customize.
4. Click on Exit Customize.
5. Try clicking on links and images on left side of page.

Actual results:
1. Tabs appeared on left side of screen out of tab bar.
2. Clicking on links, images and buttons that are on left side of the page doesn't work.

Expected results:
1. Tabs should appear on right side of screen inside tab bar.
2. All links, images and buttons on the page should work.

Attaching screenshot.

I tried this on both Windows 7 and Linux but this bug happens only on Windows 7.
![tree style tab bug screenshot](https://cloud.githubusercontent.com/assets/6619551/5384679/34b0dfee-8081-11e4-9ffc-ca1b205877cc.PNG)

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
