### ISSUE TITLE
Firefox (V34 + 0.15.2014120101) opens child windows with incorrect width.

### ISSUE THREAD

**Issue by phorham** [piroor/treestyletab#808]
Currently using Firefox V 34.0.5 + Tree Style Tabs  0.15.2014120101

When Firefox opens a child window the width is too narrow, I'm guessing as I've not measured it, by the width of the vertical tabs. As shown in the following images.

First is correct - Firefox 34 + 0.14.2014051101
Second is incorrect - Firefox 34 +  0.15.2014120101

![vertical_tab_correct_window](https://cloud.githubusercontent.com/assets/10154510/5394513/31305650-8136-11e4-9e9d-e825c8149e64.png)
![vertical_tab_incorrect_window](https://cloud.githubusercontent.com/assets/10154510/5394516/388151a2-8136-11e4-9ea8-9a32101b5cde.png)

**Comment by phorham** [comment]
Problem still present with Firefox V35 + TST 0.15.2014120101

**Comment by phorham** [comment]
Sorry, "mousehappy", closed in error, re-opened.

**Comment by piroor** [comment]
Is there any testcase or concrete steps to reproduce it?

**Comment by phorham** [comment]
Not easily :)

This happens when I access the "Connection Status" page of a Netgear router.

This appears to be the (router) code which opens the child window:

function newwindow(F)
{
if((F.status.value =="checked")||(F.EncapPTelstra.value=="checked")||(F.EncapAolDhcp.value=="checked"))
    window.open('enatherstatus.htm', 'enstatherstatus', 'width=380,height=450,status=yes');
else if((F.EncapPPTP.value =="checked"))
    window.open('pptpstatus.htm', 'pptpstatus', 'width=380,height=320,status=yes');
else
  window.open('pppoestatus.htm', 'pppoestatus', 'width=380,height=320,status=yes');
}



I've occasionally seen this happen on "real" web pages, sorry, I don't recall which but will make a note when I see it again.

**Comment by piroor** [comment]
Thansk, I've tested with a testcase like `window.open('/index.html', 'aaaa', 'width=380,height=450,status=yes');`. However the tab bar is hidden in the newly opened window for me. TST is designed to be disabled for windows opened with some flags as a popup window. So I think this is caused by a conflict with other addons. Any other tab-related addon like Tab Mix Plus?

**Comment by phorham** [comment]
Thanks for looking at this problem.

It's not a conflict with another addon, as when I disable all other addons the window is still opened "incorrectly" ... however, :)

If I create a new Firefox profile and install TST the window opens correctly, ie, with no vertical tab bar, as shown below:

![tst-new-profile](https://cloud.githubusercontent.com/assets/10154510/6694937/675f72a2-ccd5-11e4-9668-639ce4bde99b.png)

Interestingly, I've never seen the window open without the vertical tab bar, when working "correctly" (with TST 0.14.2014051101), it has always opened as shown in the first image of this thread.

I guess it's something in my Firefox profile ??

**Comment by piroor** [comment]
The tab bar is a part of toolbars. If you use some custom userChrome.css rule to show toolbar elements always, or other hidden prefs to do it, then it possibly cause problems like this.

**Comment by phorham** [comment]
OK. Thanks for the pointer :)

Eventually found that I had 'user_pref("dom.disable_window_open_feature.toolbar", true);' set in "prefs.js"

Apologies for believing that TST was to blame.

**Comment by piroor** [comment]
Don't mind! ;-)
