### ISSUE TITLE
New TST breaks Firefox 34 search

### ISSUE THREAD

**Issue by haarp** [piroor/treestyletab#810]
It seems the new 0.15.2014120101 version breaks plenty of things.

(TST + Classic Theme Restorer breaks the layout)

But for me, it seems to break the search too (in combination with various other addons, I'm still trying to determine a list of which ones are affected). Basically, the search bar doesn't react to the enter key or mouse clicks on the "go" button anymore. It starts working again when I disable TST.

**Comment by haarp** [comment]
Actually, let me revive this. It appears that TST is indeed the cause of this.

I've now reached Firefox 37.0.1 and this bug remains. I can reproduce it now.

1. Enter customize in the main menu
2. Exit customize
3. Search broken!

When go button or enter is pressed in the search at this point, I get these logs:

ReferenceError: original is not defined windowHelper.js line 334 > eval:2:20

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by wsmwk** [comment]
@haarp please reply to previous question from @piroor , and do you still see this problem? ?

**Comment by haarp** [comment]
No, this doesn't happen anymore.
