### ISSUE TITLE
Tabs started opening in undesired order, and 'grouping' together

### ISSUE THREAD

**Issue by secret-agent-girl** [piroor/treestyletab#813]
If there's a more appropriate way to report this and get some help with it, please let me know!

Previously when I opened any new tab from a link, it appeared as the last tab, appended to the bottom of the list of all tabs. (I have it set to vertical tabs on the left side of the screen.)

Now, a new tab is opening just below the tab I opened it from.

In addition, when several new tabs are opened from more than one page, gaps appear between these groups.

I think the most recent automatic update to this add-on is the cause. 

I've tried adjusting the options, but can't seem to find one that makes the add-on work the way it used to. I want these gaps to go away, and I want newly opened tabs to appear at the bottom of the list. Which setting(s) control this behavior?

Tree style tab 0.15.2014120101
Firefox 33.1
Windows 7

![temp](https://cloud.githubusercontent.com/assets/10223656/5514892/3c114232-8816-11e4-9fb2-96474a7cd67e.jpg)

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
