### ISSUE TITLE
TST Tabs remain in middle of web area after OmniSidebar closed

### ISSUE THREAD

**Issue by chronometric** [piroor/treestyletab#814]
When one opens the OmniSidebar (mine is on the left), it pushes the TST tab bar to the right by a proportionate amount. However, when the OmniSidebar is closed (shortcut key or X button), the TST tab bar returns to its proper place at the very left of the screen—but the tabs themselves remain in the web content area, in the place the TST tab bar was located when OmniSidebar was open. When in this state, the tabs appear "washed out" and highly transparent, and seem to act fairly normally; they are clickable/openable, closeable, re-openable, moveable, and the scrollbar to the left of the tabs operates as normal. 

![omnibar1](https://cloud.githubusercontent.com/assets/6432099/5499230/b046b5e2-86f9-11e4-8055-ccd5fcffc3af.jpg)
![omnibar2](https://cloud.githubusercontent.com/assets/6432099/5499231/b4dd2cb2-86f9-11e4-8604-36f6a8d0806b.jpg)

The fix is easy: If you grab the right edge of the TST tab area (gray resizing bar) and move it the smallest amount, the tabs will all immediately return to the TST tab area at the left side of the screen, where they normally live. There appear to be no other problems or anomalies associated with this event. However, needless to say, it makes using the omnisidebar for bookmarks, addons, or any other frequent functions quite awkwardl

The anomaly is eminently reproducible: install a new FF Portable (presently 34.0.5), install TST and then OmniSidebar. Close and reopen. OmniSidebar opens with the bookmark pane by default, and closing this will cause the behavior described with the one tab open in the browser. The behavior does not change significantly when the open tabs reach 700 or more.

**Comment by chronometric** [comment]
This *may* have been solved in a recent nightly build (2/27, and since the last "HTTP" release from the author's page) along with FF 35.0.1; I asked @tomlut from duplicate issue #828 to test his browser. 

However, I wanted to point out that something extremely similar is happening in the current FF nightly (also with TST nightly). As reported in #849, opening the sidebar via CTRL+B and then closing it, will leave the list of tabs floating above the web page area when the tab bar returns left:

![Uploading omnibar 3 nightly.jpg . . .]()

The workaround is the same: move the tab bar right-hand divider slightly. If the preexisting width of the tabs was beyond a certain value, the divider will reappear under the floating tabs, and cannot be manipulated. In this case, resizing the window should free it back up.

**Comment by chronometric** [comment]
This *may* have been solved in a recent nightly build (2/27; certainly only since the last "HTTP" release from the author's page) along with FF 35.0.1; hopefully @tomlut from duplicate issue #828 can coonfirm this in his software.


However, I wanted to point out that something extremely similar is happening in the current FF nightly (also with TST nightly). As reported in #849, opening the sidebar via CTRL+B and then closing it, will leave the list of tabs floating above the web page area when the tab bar returns left.

The **workaround** is the same: *move the tab bar right-hand divider slightly*. If the preexisting width of the tabs was beyond a certain value, the divider will reappear under the floating tabs, and cannot be manipulated. In this case, resizing the window should free it back up.

> EDIT: Apparently issue #849 was fixed, and committed an hour after I found the nightly working(?).

**Comment by piroor** [comment]
This doesn't happen for me with the latest development build. Can I close this?

**Comment by chronometric** [comment]
Still working good for me, thanks a lot!
