### ISSUE TITLE
Tab detach new window location

### ISSUE THREAD

**Issue by wafflepancakes** [piroor/treestyletab#817]
With this add-on disabled when you drag a tab off your main window you can drag it to another monitor and the new window will open up there. With this add-on enabled when you drag it to another monitor it snaps back and maximizes on the same monitor it was on. 

That's when you have Firefox maximized on the screen. When its not maximized the new window opens up in the default new window location (down and to the right a little) regardless of where you drag it.

Its inconvenient to drag the tab off the main window and then drag the new window where you want instead of in one click and drag. I did not see any option to turn this off.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
