### ISSUE TITLE
Strange behavior with xmonad

### ISSUE THREAD

**Issue by vtdmhd** [piroor/treestyletab#818]
If the tab bar on the side is hidden, sometimes the web page is clickable only in the region that would be visible if the tab bar were not hidden. A window layout change fixes that, but it is anoying.

I've been trying to make the bug reproducible, but I was not able to produce a MWE --- it seems that this happens at random. However, I am willing to assist (e.g., install a version with logging and share the logs) in  eliminating this bug.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
