### ISSUE TITLE
Links from Gmail Panel open as child of current tab (Repeat of Issue #510)

### ISSUE THREAD

**Issue by Faelights** [piroor/treestyletab#820]
Hi there,

I filed Issue #510 last year; thank you again for the prompt response and fix!

Unfortunately, it seems like the issue has cropped up again in the latest version of TST. I've already installed nightly build 0.15.20144120200a034137 and the issue persists.

Just a quick summary of the problem: when clicking on links in emails from Gmail Panel, those links open as child tabs of the current focused tab, rather than as individual tabs. So when I click on one link, it opens as a focused child tab, then when I click on a second link immediately after, that previous child tab becomes the parent tab of the newest child tab, and so on for each link afterwards. If I change the focused tab, the next link I click will become the child tab of that focused tab.

Thanks,

-- Fae

**Comment by Faelights** [comment]
Hi,

Just wondering if there has been any progress on this issue... thank you!

-- Fae.

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by Faelights** [comment]
Yes, it's still happening.

**Comment by piroor** [comment]
Thanks, confirmed on my environment and the commit f26193f55f9c76dd7518b39370f051139e432faf fixes this issue for me. Could you try the development build?

**Comment by Faelights** [comment]
Seems to work, thank you! =D
