### ISSUE TITLE
New tabs appended to end instead of as child of current tab, in Firefox Nightly

### ISSUE THREAD

**Issue by nnethercote** [piroor/treestyletab#822]
https://bugzilla.mozilla.org/show_bug.cgi?id=1108555 changed something about Firefox that breaks TST's handling of new tabs -- they now get appended at the end of the tab list, instead of being appended to the current tab's child list. See https://bugzilla.mozilla.org/show_bug.cgi?id=1108555#c10.

**Comment by mikeconley** [comment]
This sounds a lot like issue 760 rearing its head again - the patch in bug 1108555 changed the signature of openLinkIn again, so perhaps the regex in windowHelper isn't matching properly?

**Comment by LordJZ** [comment]
#816 should fix this. Works for me on latest nighty.

**Comment by Daniellynet** [comment]
Thanks a ton, @LordJZ! 
Can confirm it also works for me on the latest nightly.

**Comment by ripdog** [comment]
Thanks LordJZ. Here's a prebuilt XPI for convenience, until piroor comes out of hiding again.

http://a.pomf.se/hrnvbs.xpi

**Comment by ttsda** [comment]
Same on OS X, thanks @ripdog, that fixed it.

**Comment by Vest** [comment]
Just in case, the last time when I got this issue, the nightly build helped me: http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by Daniellynet** [comment]
@Vest, yes, but a change in the nightlies made it not work again, and @piroor is busy with other things right now, so @LordJZ's fix isn't getting commited into the nightly TST.

**Comment by ibrahima** [comment]
Thanks @LordJZ and @ripdog , the fix still works on the latest nightly!

**Comment by piroor** [comment]
Can I close this issue?

**Comment by nnethercote** [comment]
> Can I close this issue?

Yes. I have confirmed that the new nightly build of TST works correctly in a trunk build of mozilla-central. Thank you for the updated nightly build.
