### ISSUE TITLE
Tabs disappearing

### ISSUE THREAD

**Issue by jfm30204** [piroor/treestyletab#824]
With tree visible on the left, sometimes individual tabs disappear. When you click the border to hide the tree and then click to show it again, all tabs have disappeared.

I love TST, but I can't have this.

Other extensions are:
Download Helper
Flashblock
LastPass
Pocket
Session Manager
TabHunter

**Comment by jfm30204** [comment]
Update:  I disabled all other extensions, except Session Manager, and the tabs are still disappearing. I hope that there is a fix for this. Otherwise, I have to consider TST too unstable to use.

**Comment by jfm30204** [comment]
Update:  Problem does not occur with Auto Hide option. Only with Show Tab Bar Always option.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
