### ISSUE TITLE
Parent tab closes and 1 of the hidden children tabs becomes the parent to the remaining child tabs

### ISSUE THREAD

**Issue by aardvark2zz** [piroor/treestyletab#825]
Bug that has existed for many releases. Repeatable. Great addon !!

With ONE parent tab with several children tabs. Hide children tabs. Click close parent (should also close all children tabs as happens with the case with the OTHER parent tabs with children tabs). Instead of closing the parent tab and all its children tabs, and replacing this with 1 new tab, instead the parent tab closes and 1 of the hidden children tabs becomes the parent to the remaining child tabs; children tabs also become un-hidden.

left tabs, FF 31.3.0 ESR (and most FF versions), all TST versions (now have 0.15.2014120200a034137), TMP 0.4.1.6

**Comment by piroor** [comment]
This doesn't happen for me on Firefox 44.0.2 + TST, without Tab Mix Plus. If this is a TMP-specific problem, then I need your contribution (pull request) because I don't use TMP.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
