### ISSUE TITLE
Tabs opened with middle mouse button on Linux don't spwan as child tabs

### ISSUE THREAD

**Issue by seanegoodwin** [piroor/treestyletab#826]
Using the latest nightly builds of treestyletab and Firefox, opening a tab by clicking on a link in a page with the middle mouse button causes it to spawn as a independent tab and not as a child tab. Right click -> open link in new tab works as expected, as does the middle mouse button in Windows.

**Comment by Daniellynet** [comment]
Refer to #816. 
@piroor needs to commit it (assuming its backwards compatible?) at some point. 
Easy to fix it yourself, though.

**Comment by timss** [comment]
Can confirm that the fix in #816 indeed works. 
Firefox 37 (Aurora), Linux. 

Should probably close this issue.
