### ISSUE TITLE
ctrl key以外の タブバーの表示・非表示

### ISSUE THREAD

**Issue by tarotarotarotaro** [piroor/treestyletab#827]
ctrl key以外でタブバーの表示・非表示をしたいです
例えばshiftなど

下記のトグルのような方法で指定可能でしょうか？

TreeStyleTabBrowserAutoHide.toggleMode();

**Comment by piroor** [comment]
ブラウザウィンドウ内の名前空間であれば、`TreeStyleTabService.toggleAutoHide();`で可能です。

**Comment by tarotarotarotaro** [comment]
ご連絡ありがとうございます。

開閉のトグル
TreeStyleTabBrowserAutoHide.toggleMode();
や
TreeStyleTabService.toggleAutoHide();
ではなく

押下中のみツリータブが表示される事をしたいです。
ctrlキー押下中のみタブを表示
を
別キーでしたいです
下記の様な事です
nmap キー :javascript<Space>TreeStyleTabService.押下中のみツリータブが表示();<CR>

**Comment by piroor** [comment]
メソッド1つでそれを実現する、という機能は残念ながら今は無いですね……

 * `ｇBrowser.treeStyleTab.showTabbar()`は、タブバーが非表示の時なら表示して、表示されている時は何もしない
 * `ｇBrowser.treeStyleTab.hideTabbar()`は、タブバーが表示されている時なら非表示にして、非表示の時は何もしない

という2つのメソッドはあるので、これを使ってどうにかするしかないかなあ、と思います。
例えばですが、こんなのとか。

~~~
function showAndHideTabbar() {
  ｇBrowser.treeStyleTab.showTabbar();
  if (window.hideTabbarTimer) {
    window.clearTimeout(window.hideTabbarTimer);
  }
  window.hideTabbarTimer = window.setTimeout(function() {
    ｇBrowser.treeStyleTab.hideTabbar();
    window.hideTabbarTimer = null;
  }, 100);
}
~~~

これを何らかのキーボード操作に割り当てておくと、キーリピートがかかる度にこの処理が実行されて、キーから指を離したらタイマーで自動的にタブバーが隠れる、という風になるのではないでしょうか。

**Comment by tarotarotarotaro** [comment]
希望通りです
ソース読んで苦戦していましたが、質問してよかったです

ありがとうございます

**Comment by tarotarotarotaro** [comment]
firefox 38.0.5
ツリー型タブ (Tree Style Tab) 0.15.2015030601.1-signed 

にて

gBrowser.treeStyleTab.showTabbarが動作しなくなりました。

可能でしたらご対応をお願いします
