### ISSUE TITLE
Incompatible with OmniSidebar

### ISSUE THREAD

**Issue by tomlut** [piroor/treestyletab#828]
When OmniSidebar is opened it pushes the tree tabs to the right correctly but leaves them there when OmniSidebar is closed.

**Comment by chronometric** [comment]
@tomlut: I reported this problem in #814, as well as a workaround to reset the position manually: just jiggle the tab width bar slightly.

**Comment by chronometric** [comment]
@tomlut: I was just troubleshooting a different problem, and may have found a solution. It seems that using the current nightly development build of TST on FF v35.0.1 has stopped the tab bar from "sticking" over the web page...at least in a fresh install I haven't used much yet.

Could you uninstall TST, restart FF, and then install the TST nightly from the author's page: http://piro.sakura.ne.jp/xul/xpi/nightly/  (treestyletab.xpi).

**Comment by piroor** [comment]
This doesn't happen for me with the latest development build. Can I close this?

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
