### ISSUE TITLE
Scroll down button overlaps with addon bar

### ISSUE THREAD

**Issue by Tragen** [piroor/treestyletab#831]
![firefox](https://cloud.githubusercontent.com/assets/1700241/6007229/fcd5598e-ab18-11e4-86cf-a8347a198825.png)

The scroll down button of TST overlaps with the "The Addon Bar (Restored)"
https://addons.mozilla.org/en-US/firefox/addon/the-addon-bar/

**Comment by piroor** [comment]
I couldn't reproduce this issue with TST latest development build with Firefox 36, and the addon bar addon. Is this already fixed? http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by Tragen** [comment]
I found the reason. I added this to my userchrome.css so that a double click on the empty gray area opens a new tab.

> #navigator-toolbox > #TabsToolbar 
> {
>   -moz-binding: url("chrome://global/content/bindings/toolbar.xml#toolbar")!important;
> }

Do you know a solution for this?

**Comment by piroor** [comment]
How about this?

    #navigator-toolbox > #TabsToolbar {
      -moz-binding: url("chrome://treestyletab/content/treestyletab.xml#toolbar")!important;
    }

**Comment by Tragen** [comment]
Thank you very much. You are my hero.
