### ISSUE TITLE
Tabs unhide incorrectly on PureZC but nowehere else

### ISSUE THREAD

**Issue by newstarshipsmell** [piroor/treestyletab#834]
On the website [PureZC](http://www.purezc.net/), when I move the mouse to the right, the hidden tab tree unhides itself too soon, so I can't click on anything along the right side of pages on this site. This behavior has not occurred on any other site I've browsed - only this one. I have the settings configured to only unhide the tab tree if I move within a few pixels of the right side of the page, so I don't know why it unhides with the mouse cursor much farther to the left on this site.

If I move my mouse to the right of this red line, it will unhide the tabs:
![screenshot](http://i.imgur.com/NNoW8cB.jpg)
Then the tabs will remain open until I move it left past the inside edge of the tree, as expected:
![screenshot](http://i.imgur.com/I4bGSLe.jpg)

Otherwise, TST add-on works fantastically, and is one of the few I can't live without.

[My TST config](http://i.imgur.com/cwNSHAs.jpg)

[My Firefox add-ons](https://addons.mozilla.org/en-US/firefox/collections/sunrisefirefly/cur/?sort=name) (plus [Bookmark Favicon Changer](https://sites.google.com/site/sonthakit/bookmarkfaviconchanger), [Enhanced Steam](http://firefox.enhancedsteam.com/) and **Organize Search Engines**)

I'm running Firefox 35.0 on Windows 7 x64.

**Comment by piroor** [comment]
Some changes are introduced around calculation of event coordinates by recent commits. Could you try the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by newstarshipsmell** [comment]
Whoops! Sorry I never replied - just came back here because Fx 40.0 + TST has killed my bookmarking dialogs (https://github.com/piroor/treestyletab/issues/887) and wanted to see if it was a known bug. Happy to say that the bug I reported resolved itself months ago and I didn't even notice - presumably due to an update that fixed it.
