### ISSUE TITLE
Supporting PageUp, PageDown, Home, End keys in the tab list

### ISSUE THREAD

**Issue by reikred** [piroor/treestyletab#836]
I frequently find myself with more tabs in a window than what will fit in the vertical tab list. There is the scrollbar for navigating among tabs, but even with the "large scrollbar" setting, paging through the tabs is cumbersome and requires precise mouse operations.

Suggestion: A feature to use the the PageUp, PageDown, Home, End keys to scroll in the tab list would be very useful. I operate my (linux) window manager in focus-follows-mouse mode, and I see that TST is already aware that my mouse is over the vertical tab list, because it highlights the tab underneath the cursor. Hence it ought to be doable to have the tab list react to PageUp, PageDown, Home, End if it is detected that the cursor is inside the tab list.

A related observation: I use the "tabhunter" extension to do textual search for tabs (searches by partial name, and across multiple windows), and that works well, but when tabhunter selects a window and a tab, TST does NOT "warp" or scroll to the selected tab. I wonder if it might be possible always to ensure that the currently displayed tab gets centered in the scroll window when a new tab is selected,  even if  the tab was not selected via mouse operations? Or maybe have a "warp-to-current-tab" keyboard shortcut (say Ctrl-Home might be reasonable) to the same effect. 

Alternatively, having a tab search/filter function integrated into TST would be very useful. Generally searches ought to match against either tab name or  URL, and should work across all open windows (like tabhunter does), but with an optional restriction to search/filter only in the current window. Ctrl-F while over the tab list might be a good and standard shortcut.

**Comment by piroor** [comment]
Generic operations for scrollable box is disabled for the tab bar by Firefox itself. To re-enable it you just have to put following code into your userChrome.css. Then, you can move focus to the tab bar by clicking on a tab, and PageUp/PageDown/Home/End/Ctrl-Home/Ctrl-End keys are available while any tab has its focus ring.

~~~
.tabbrowser-tab {
  -moz-user-focus: normal !important;
}
~~~

**Comment by reikred** [comment]
I have tried the above mod to userChrome.css, but it did not work (firefox restart). Scrollwheel works in the tab pane, even before the  userChrome mod, but PageUp etc do work no matter what, at least not for me. Any ideas?

**Comment by piroor** [comment]
Hmm, I've tried the CSS on Firefox 44 and confirmed that it only partially works for me. Home/End work for me, but PageUp/PageDown don't.

**Comment by piroor** [comment]
I don't know why, but now PageUp/Down seems not available on the tab bar. Instead, you can select next/previous tab by shortcuts Ctrl-PageUp/PageDown. It is available even if you don't use the userChrome.css.
