### ISSUE TITLE
Tabs Disappear in full-screen mode on MAC

### ISSUE THREAD

**Issue by gmccord** [piroor/treestyletab#837]
Latest FF, MACOS Yosemite with all updates. When I put FF in "full screen" mode,  the tabs do not show. This does not seem to happen on my Windows 8.1 system or in any of the windowed modes on FF/Mac. attached are before and after screen shots
![screen shot 2015-02-06 at 9 57 44 am](https://cloud.githubusercontent.com/assets/10776351/6082380/aff7252c-ade6-11e4-8fb9-9b44bbafe91a.png)
![screen shot 2015-02-06 at 9 58 01 am](https://cloud.githubusercontent.com/assets/10776351/6082382/b2776afa-ade6-11e4-83a5-7dae0535edfe.png)

**Comment by adamwong246** [comment]
:+1:

**Comment by piroor** [comment]
This doesn't happen on my testing environment:

 * OS X 10.9.5
 * Firefox 36
 * TST latest development build

Is this OS X Yosemite specific issue? Because I cannot update this testing environment I cannot try Yosemite by myself.

**Comment by gmccord** [comment]
OK, I tried it again, and it appears that this is a cockpit error on my part. I wasn't moving the mouse pointer to the correct location when the addin was set to enable autohide in full-screen mode.

Thanks for looking at it, you can close this out.

Gray

GRAY D. McCORD
CHIEF TECHNOLOGY OFFICER \\ CONTACT INFO<http://tinyurl.com/mng7bh4>
