### ISSUE TITLE
window.open + tree style tab

### ISSUE THREAD

**Issue by thle01** [piroor/treestyletab#838]
I am using Firefox add-ons: Tree Style Tab and when I use my Javascript to open new tab

function Open_Jobs() {
if(jQuery("a[href~='DWPJobPerformanceHistory']").each(function(index, a) {
    window.open(a.href, '_blank');
});};
the result look like this http://imgur.com/tKCnMm8, but I like to make it look like this http://imgur.com/vkQs5ng

Thank you for taking your time to help me.

**Comment by piroor** [comment]
This is same to #812.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
