### ISSUE TITLE
Change key to show when always-hide is on from control to something else

### ISSUE THREAD

**Issue by robinhoodexe** [piroor/treestyletab#841]
Hi

I'd like to change the key that shows/hides the tab bar from control to something else, preferebly tab. When holding control down a click immitates a rightclick, which makes changing tabs impossible (since all one can do is rightclick on a tab).

I have looked at the source, but I'm not really good at coding, and couldn't figure out how to change it.

**Comment by piroor** [comment]
The tab bar is expanded by ctrl key mainly for the feature to switch tabs by ctrl-tab/ctrl-shift-tab. By some reasons I think that I cannot (or should not) add extra keyboard shortcuts for TST's features. So I recommend you to define custom keyboard shortcut by any other addon which is designed to provide customizable keyboard shortcuts. A script like `TreeStyleTabService.toggleAutoHide()` will toggle the visibility of the tab bar.

**Comment by robinhoodexe** [comment]
Alright, adding ``TreeStyleTabService.toggle.AutoHide()`` to [Keyconfig](http://forums.mozillazine.org/viewtopic.php?t=72994) did work, but I'd like to get the functionallity of the ctrl key, which only shows the tab bar when the key is pressed, and not when it's not, while ``TreeStyleTabService.toggle.AutoHide()`` shows or hides the tab bar whenever the key is pressed (and not hold).

**Comment by piroor** [comment]
`toggle.AutoHide` => `toggleAutoHide` ?

**Comment by robinhoodexe** [comment]
My bad, I meant ``TreeStyleTabService.toggle.AutoHide()``.

**Comment by squromiv** [comment]
@piroor 
> A script like TreeStyleTabService.toggleAutoHide() will toggle the visibility of the tab bar.
>  toggle.AutoHide => toggleAutoHide ?Thanks a lot. Very-very-very useful information for me.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
