### ISSUE TITLE
With ColorfulTabs the horizontal tab bar is scrolled to place a clicked tab to the far right.

### ISSUE THREAD

**Issue by JKKO** [piroor/treestyletab#842]
[ColorfulTabs](https://addons.mozilla.org/firefox/addon/colorfultabs/) 
Example: https://i.imgur.com/LulnWYf.gif

**Comment by piroor** [comment]
Thanks. The commit  0afae1c65503dddba06a006e893b1ea7513c3ce7 fixes this issue for me.

**Comment by JKKO** [comment]
Yeah, that fixes it for me as well, thanks.
