### ISSUE TITLE
pinned tabs do not "reflow" when in auto-hide mode

### ISSUE THREAD

**Issue by adamwong246** [piroor/treestyletab#845]

**Comment by piroor** [comment]
This is by design. If pinned tabs are reflowed for both shrunken and expanded tab bar, other regular tabs bounce annoyingly.

**Comment by piroor** [comment]
Not only non-pinned tabs but also pinned tabs. It is too annoying that to-be-clicked tabs escape from the mouse pointer by reflowing.
