### ISSUE TITLE
Feature Request: Exclude Windows filter

### ISSUE THREAD

**Issue by rothgar** [piroor/treestyletab#847]
When creating a new window for some apps/single tab windows (chat window, etc.) it would be very handy to have TST hidden or disabled by default. I cannot find a way to make specific windows (eg talkgadget.google.com) disable TST in favor of limiting boarders and window chrome.

Here's an example of Chrome vs Firefox with TST for a Google Hangout window

![chat windows](http://i.imgur.com/VmwfZLf.png)

Having an advanced option to blacklist specific URLs could be very useful in this case.

**Comment by piroor** [comment]
I think this problem can be caused by other addons. I've tested Nightly 39.0a1 with TST nightly but Gmail's chat window is shown without tab bar as expected. And, I designed TST to be disabled when a browser window is opened with flags (window size, position, etc.)

**Comment by rothgar** [comment]
I upgraded my system to Fedora 21 which brought along Firefox 36. I just tested here and all appears to be working. Sorry for the superfluous issue.
