### ISSUE TITLE
Misaligned apptab favicon in Nightly

### ISSUE THREAD

**Issue by tbs** [piroor/treestyletab#850]
Apptabs favicon is misaligned in **Nightly** with **Tab Mix Plus** and **Tree Style Tab** installed.

Both extensions dev "edition" in default config and Firefox clean profile.

**Screenshot:**

![screenshot](https://cloud.githubusercontent.com/assets/768954/6405908/1a18c8a8-be08-11e4-9467-9c0bd0d2b76d.png)

Not sure which extension is causing this behavior, then I'm reporting to both dev.

**Platform:** Windows 8 x64.

**Comment by piroor** [comment]
Does this still happen when only TST is activated?

**Comment by tbs** [comment]
No, for both extensions.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
