### ISSUE TITLE
[Feature Request] Auto hide tab bar adjustable for each window

### ISSUE THREAD

**Issue by HakanSiktas** [piroor/treestyletab#851]
Having one Firefox window on the small laptop screen and one on a huge external monitor makes the auto hide feature a little troublesome because it applies to all Firefox windows at once.
Having the ability to adjust this for each window separately would benefit those use cases where people need both the reduced browser chrome and the increased tab overview at the same time.

**Comment by piroor** [comment]
By recent changes, this feature is landed. Try the latest development build!
http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by HakanSiktas** [comment]
Confirmed. Thank you, sir. :+1:
