### ISSUE TITLE
Feature Request: "Title Tabs" as tree parents

### ISSUE THREAD

**Issue by Sherris** [piroor/treestyletab#854]
In grouping my tabs into various trees, I find that while many pages naturally form groups, there is often no natural parent. I have been adding tabs with Google search results as the parent as kind of a "dummy" tab.

I would love to have the option to create a dummy tab with a custom title/header and no content to act as a parent to a tree or sub-tree.

For example, if I am storing recipe pages, I might have a summy title tab called "Recipes", then sub-tabs called "Chicken Recipes" and "Vegetable Recipes" and the actual pages under those parents.

**Comment by irvinm** [comment]
Just put this in the URL bar:  "about:treestyletab-group?Recipes"

**Comment by piroor** [comment]
As irvinm said, TST already has a feature like "dummy tab" with the URI "about:treestyletab-group". Title given as a query parameter will be used as the title. It is originally introduced to create natural tree for tabs opened from a bookmark folder.

**Comment by Drag0nR3b0rn** [comment]
I'd like to second the Op. It'd be nice if the was some kind of a menu to discover this functionality - as it's quite useful but very hard do discover.

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by bytesnz** [comment]
A easy(er) to create dummy would be awesome - one that you could rename easily. There is the "New Container Tab" (FF57dev), which could to extended/changed so that clicking on it creates a dummy tab and selects it's title for editing. The current Container tab functionality isn't that helpful for me as I normally have multiple sets of tabs open for work and for personal use, so just being able to create the dummy tab easily name it would be awesome. BTW, you have kept me using Firefox, so awesome peeps, keep up the good work!

**Comment by irvinm** [comment]
The new method with TST 2.x is different but still not obvious.

Just enter into the URL:  

moz-extension://7f7ecbf7-65ca-44e0-9cf9-57344070b700/resources/group-tab.html?title=Github&temporary=true

Check https://github.com/piroor/treestyletab/issues/1353 for more info.

**Comment by bytesnz** [comment]
Ah cool. Works once you have the correct __ID for the extension
`moz-extension://<Unique plugin id>/resources/group-tab.html?title=<title>&temporary=true`
Had to get it by opening a folder of bookmarks and copying it from the folder tab that was created. Is it worth merging / closing one of these two issues (this and #1353) as they are talking about the same thing?

**Comment by bytesnz** [comment]
As a temporary measure, I made a bookmark with the link
```javascript:window.location = `moz-extension://<INSERT_YOUR_TREE_STYLE_ID_HERE>/resources/group-tab.html?title=${prompt('Name%20of%20group?')}&temporary=true`;```, which works wonders when you open it in a new tab.

**Comment by MikeRatcliffe** [comment]
Just a quick note to say that the easiest way I can find to get the bookmark URL is:

1. Open about:debugging
2. Copy the internal UUID from Tree Style Tabs
3. The URL you need to use for creating folders is moz-extension://UUID/resources/group-tab.html?title=Github&temporary=true

But it would be great if you could add an "Add Folder..." option to the context menu.

**Comment by piroor** [comment]
By recent commits, now TST automatically redirects "about:treestyletab-group" to the internal "moz-extension:" URL, so you'll open new group tab more easily.

**Comment by sfleiter** [comment]
A keyword search can be used for this functionality and better usability, too.
See http://kb.mozillazine.org/Using_keyword_searches
I created one bookmark with address "about:treestyletab-group?%s" and keyword "tg".
By entering "tg example" (without quotation marks) in the url bar a tab named "example" in TST is now created,

**Comment by kkot** [comment]
@sfleiter Great tip thanks.

I think it would be useful to add option in _Additional Context Menu Item_ to add tab group which would just ask for name and add new tab.

I like this tab group option:
![obraz](https://user-images.githubusercontent.com/1009806/33208163-cd8e1398-d110-11e7-84f8-fb4d0ecbc7fa.png)

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
