### ISSUE TITLE
"Invert tab contents" makes twisty snatch clicks from tab closing & selection

### ISSUE THREAD

**Issue by foghawk** [piroor/treestyletab#855]
OSX, FF36, TST 0.15.2014120101. I keep tabs on the right side and like to use the inverted contents option, but this makes the 'show/hide children' button take over the tab. Tabs with children can't be closed (the button highlight and tooltip appear correctly, but clicking the button expands or collapses the tab's tree), and they usually can't be selected either (clicking on the body of the tab expands or collapses the tab's tree instead of changing the current tab). Occasionally clicking on a tab will both expand or collapse its tree _and_ select it, but I haven't been able to reproduce this consistently.

**Comment by piroor** [comment]
Any screenshot?

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
