### ISSUE TITLE
Scroll wheel in tab bar scrolls slowly

### ISSUE THREAD

**Issue by kini** [piroor/treestyletab#856]
**Summary**: when I rotate the scroll wheel on my mouse quickly, the tab bar does not scroll quickly.

I have a mouse with "non-smooth scrolling". I mean that the scroll wheel rotates by discrete units. So in TST, if I place the mouse pointer on the tab bar and rotate the wheel downward by one unit, the tab bar scrolls down by ~3 tabs. If I rotate the wheel downward by one more unit, the tab bar scrolls down by ~3 more tabs. If I slowly move the scroll wheel by 10 individual units with pauses in between, then the tab bar scrolls down by ~30 tabs. But if I quickly move the scroll wheel by 10 units, then the tab bar scrolls down by much less than 30 tabs. It should scroll by 30 or more than 30 tabs. (I didn't experience this issue with scrollbars in other parts of the Firefox interface.)

I'm using the latest TST nightly and the latest Firefox nightly on Windows 7.

**Comment by piroor** [comment]
Sorry, this regression should be fixed by recent commits. Please try new development build again?

**Comment by kini** [comment]
It's fixed! Thank you :)
