### ISSUE TITLE
Tab bar does not expand anymore when "Auto hide tab bar" is enabled

### ISSUE THREAD

**Issue by HakanSiktas** [piroor/treestyletab#857]
This happens with TSB 0.15.2015031900a181223 on Firefox 36.0.1 and both Windows and OS X.

edit: Build 0.15.2015030601 from AMO does not show this issue.

**Comment by jimbo1qaz** [comment]
Me too.

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by jimbo1qaz** [comment]
New bug: The expanded tab bar blows up to enormous sizes whenever you
resize the unexpanded bar beyond the expanded would-be size. Will create
bug report tomorrow.

**Comment by piroor** [comment]
The "auto hide tab bar" feature still seems working correctly for me. Could you describe detailed steps to reproduce? For example:

 1. Start Firefox with clear profile.
 2. Install TST ver.xx.
 3. Restart Firefox.
 4. Right click on the tab bar and check "Auto Shrink tab bar".
 5. ....

**Comment by HakanSiktas** [comment]
I can't reproduce the initial issue anymore with 0.16.2015122501 on any platform. Should we close this issue?

**Comment by piroor** [comment]
Thank you confirmation. I close this for now, then please report again if it appear again on your environment.
