### ISSUE TITLE
On the selected tab, Firefox icons are appearing when they should not in some themes.

### ISSUE THREAD

**Issue by ryho** [piroor/treestyletab#861]
![tabbug](https://cloud.githubusercontent.com/assets/2478057/6852307/4bc7267a-d3ba-11e4-944e-9a1bf276d1d3.png)
See the image. This started happening after Firefox updated to 36.0.2 (maybe it was 36.0.3... I'm on 36.0.4 now)

**Comment by piroor** [comment]
This doesn't happen for me on Windows 7 and Ubuntu. Is this Windows 8 specific issue?

**Comment by ryho** [comment]
I'm using Windows 7
I removed and re-installed the extension and the bug has gone away. Not sure why it started or why it only applied to some of the themes.
I'll close the issue
