### ISSUE TITLE
Is it possible to transfer tabs from one machine to another?

### ISSUE THREAD

**Issue by gcovell** [piroor/treestyletab#862]
Hi -- Is it possible to transfer a set of tabs from one machine to another? Is there a preferences file someplace that can be moved from machine to machine? Firefox sync didn't preserve the tabs. Thanks.

**Comment by Daniellynet** [comment]
I know the tabs info are stored in the sessionstore file (C:\Users\*\AppData\Roaming\Mozilla\Firefox\Profiles\*.default\sessionstore-backups\recovery.js) on Windows. 
Could try copying that file over from one machine to another, and see if the reloads those tabs on start (show my windows and tabs from last session checked in FF config), or if they’re in the history dropdown as restore closed window. 
From: gcovell 
Sent: 26 Mar 2015 22:11
To: piroor/treestyletab 
Subject: [treestyletab] Is it possible to transfer tabs from one machine to another? (#862)

Hi -- Is it possible to transfer a set of tabs from one machine to another? Is there a preferences file someplace that can be moved from machine to machine? Firefox sync didn't preserve the tabs. Thanks.

**Comment by gcovell** [comment]
Yes, that did work. I found sessionstore.js in that directory and copied it over.
Now, I went from Windows to Mac. But on Mac, there's no status bar space and so the little icon which lets me switch between different tab collections doesn't appear. Fortunately the keyboard command, Command+Shift+E works.

**Comment by Daniellynet** [comment]
Ah, awesome! Glad to know it works! :)

**Comment by gcovell** [comment]
I had to migrate sessionstore.js again -- seems obvious, but you have to move the file when when Firefox is not running. Took me a few minutes to realize this.
