### ISSUE TITLE
please update for FF37

### ISSUE THREAD

**Issue by littledude072** [piroor/treestyletab#865]
no child support ;P

**Comment by NicolasP** [comment]
Updating to 0.15.2015030601 (using this link: http://piro.sakura.ne.jp/xul/xpi/confirm.cgi?treestyletab.xpi) fixed it for me.

**Comment by littledude072** [comment]
thanks for the quick tip, works just fine with that version. if only we could edit our reviews on the addon pages

**Comment by auscompgeek** [comment]
If you prefer downloading over HTTPS, the latest version is on AMO pending review: https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/versions/

**Comment by seren** [comment]
This is a problem for me as well, but only on Ubuntu; OS X is working fine. Using version 0.15.2015030601 with FF 37.0.1 on both platforms. Very strange.
