### ISSUE TITLE
Startup crashes on 2015-04-03 Nightly

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#866]
Crash report: https://crash-stats.mozilla.com/report/index/3c9aff8a-0d75-446f-9813-fbffd2150403

Steps to reproduce:
Install Tree Style Tab 0.15.2015030601 in a new profile in Nightly 20150403 build. Restart the browser

Actual result:
Nightly crashes on startup.

Bug report in bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1150906

**Comment by tonysan** [comment]
Also reproducible on Firefox Nightly 40.

**Comment by tonysan** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1150906

**Comment by kini** [comment]
This should be fixed on the latest nightly.

**Comment by Daniellynet** [comment]
Can confirm the latest nightly fixes the issue!

**Comment by Fanolian** [comment]
Fixed by Bug 1150906.
