### ISSUE TITLE
[Feature request] New theme which allows custom tab-title font styles & colors

### ISSUE THREAD

**Issue by auralarch** [piroor/treestyletab#867]
**_Background Info_**
I have an aging, but fairly powerful machine with a decent amount of RAM (Xeon 5670- hexacore CPU- with 24 GB of triple channel DDR3), a reasonably matched GPU & a multi-monitor setup (w/ 4 displays)...  I put this setup together to accommodate my working habits.  I tend to work with a lot of open tabs at once, sometimes 2-3 windows with lots of tabs.  TreeStyleTabs has been an indispensable tool for allowing me to maintain some order to that chaos & be productive.  However, there is one feature that would be extremely valuable to my productivity & efficience.  (I know this because I've grown accustomed to it being provided by another addon which I use in a secondary FF profile).
**_The Request_**
That is: the ability to customize the style & color of tab-titles based on the status of those tabs (current active tab, unseen tabs which are loaded or unloaded, and already seen tabs).
**_The Reasoning, Explanation & Justification_**
This is extremely useful for keeping track of lots of open tabs!  Being able to organize tabs in trees is also extremely useful, but each of those organizational tools is limited in its scope & utility by itself... And the two systems are not inherently, mutually exclusive; in fact the two systems compliment & enhance the value of each other!
This ability to customize font style & color of tab titles is a feature that is actually already provided by TabMixPlus, but is not compatible with TreeStyleTabs. The only thing preventing them from working together is either a technical problem or an arbitrary decision made by one of the developers.  There is no "real" reason why these two systems can not co-exist...  Technical problems can be solved & arbitrary decisions can be changed.
Both addons provide features which I find extremely helpful but sadly I am forced to try to choose between them- but this is so difficult that I began using two profiles.
Many of the features of these addons ARE able to function together, but of all those features of TMP which are incompatible with or broken by TreeStyleTabs this one is simply too useful & valuable to give up.  If only it were not necessary to make such a compromising decision!!!

**_Current Status_**
Actually the font styles which are defined by TMP ARE effective with TST but not the font colors (the background colors are ignored by TST as well; however, that is not a big deal for me personally. Although I would utilize that control as well if it were available).
I understand that conflicts between other addons are sometimes unavoidable & certain features of one addon may cease to work with another due to the API they are (or are not) using...  So, perhaps my request is not as simple as it seems to me.  I do not understand exactly how the features of these addons are implemented.
But if it is impossible for TST to utilize the font colors defined by TMP, perhaps you could create a new theme or define some unique method of your own which allows for such customization within the TST API itself (even if it's not part of the GUI and is only accessible through the about:config interface).

**_Closing Argument_**
Perhaps this feature is of no practical value to you personally; that is perfectly understandable.  But surely you are aware that everyone's brain works a bit differently in the way we process, categorize & utilize information; and what may not seem interesting or useful to you may be extremely useful & helpful to others whose brain has different methods of conceptualizing & processing information.
If you are only interested in developing features which you find useful for yourself, that is unfortunate but understandable- after all, you do offer your extensions free of charge so it is unfair to expect you to develop features which you yourself do not have any use for!  And I wish to be clear that I do VERY much appreciate that you do make your extensions available and I do NOT expect you to do anything.  I only politely request that you consider my proposals.

**THANK YOU very much** for your time & consideration!!!
(I apologize if my request has become too detailed & includes excessive information that is of little/no value to you.  I am by nature a very thorough & comprehensive individual.  Some appreciate this, others do not. It is not my wish to offend!)

**Comment by irvinm** [comment]
auralarch, you might want to consider using "Cyberfox".  It is a 64-bit compiled version of Firefox and it has all of this functionality built in.

![2015-04-04_19-20-50](https://cloud.githubusercontent.com/assets/979729/6995091/bef0503a-daff-11e4-9658-439e4d800bed.png)

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
