### ISSUE TITLE
タブ位置が勝手に変更されてしまいます

### ISSUE THREAD

**Issue by Tokkey1994** [piroor/treestyletab#868]
ツールバーのカスタマイズ機能を二回ほど使用するとタブの位置が左から勝手に上に変更されてしまうようです。 "about:config"でいうところの"extensions.treestyletab.tabbar.position" がtopに勝手に変更されてしまうようです。
友人にも試してもらうと再現がとれました。

自分の環境
Windows 7
firefox 37.0.1
ツリー型タブ 0.15.2015030601

友人の環境
Windows Vista
firefox 36.0.0
ツリー型タブ 0.15.2015030601

**Comment by piroor** [comment]
この問題は最新の開発版でも再現するでしょうか？
http://piro.sakura.ne.jp/xul/xpi/nightly/

Firefox 43以降の場合はパッケージの署名を要求しないように設定を変える必要があるのでご注意下さい。
Firefox 44以降では設定を無効化できませんので、Firefox Developer EditionまたはNightlyを使う必要があります。

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
