### ISSUE TITLE
Auto-hidden tabs won't show again until left-clicking after closing a tab via FireGestures

### ISSUE THREAD

**Issue by ClefAria** [piroor/treestyletab#869]
I am using version 0.15.2015031900a181223.

After closing a tab with a gesture (via FireGestures 1.8.7; the gesture I use is holding down the right mouse button, then dragging down, then right, then releasing the button), I need to left-click on the next page somewhere before the auto-hide begins working at all again (until I do, the tab bar won't pop out of the left no matter what)

**Comment by ClefAria** [comment]
I am now using version 0.15.2015061300a003855 of Tree Style Tab, and version 1.8.7.1-signed of FireGestures. This issue continues to persist for me. Am I the only one experiencing the above?

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by ClefAria** [comment]
Yes, mentioned in the other issue that the latest development build finally fixed the issue. Thanks again!
