### ISSUE TITLE
Middle click not opening links as child tabs in FF 37

### ISSUE THREAD

**Issue by laggingreflex** [piroor/treestyletab#870]
Recent update to Firefox 37 has broken something. Middle clicking on links used to open new tabs as child tabs. Not anymore. Now all links opened with middle click go at the bottom. 

Same with Ctrl+click

Only middle-click with "Go" arrow in the address bar works as expected.

**Comment by hposca** [comment]
#865 solves this.
Don't know when it will become available at "firefox add-ons store".

**Comment by laggingreflex** [comment]
Indeed. Thanks! I shall close this issue then.
