### ISSUE TITLE
Middle click on links no longer opens new tab as child to current

### ISSUE THREAD

**Issue by fredrikaslund** [piroor/treestyletab#873]
New tabs used to open as child to current tab in tab tree. This no longer works in firefox_37.0+build2-0ubuntu1_amd64.deb or firefox_37.0.1+build1-0ubuntu0.14.10.1_amd64.deb.

When downgrading to firefox_33.0+build2-0ubuntu0.14.10.1_amd64.deb tabs open as child tabs to current when middle clicking links again.

May have something to do with the setting browser.tabs.insertRelatedAfterCurrent that is forced to false.

**Comment by hposca** [comment]
As I posted in #870 , #865 solved this. At least for me.

**Comment by seren** [comment]
This is a problem for me as well, but only on Ubuntu; OS X is working fine. Using version 0.15.2015030601 with FF 37.0.1 on both platforms. Very strange.

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by piroor** [comment]
Seems expired.

**Comment by seren** [comment]
Sorry, I don't have access to an Ubuntu box currently. Still working fine on OS X. Probably fixed since no one else has commented.
