### ISSUE TITLE
returned to default tab behaivior after customizing toolbar

### ISSUE THREAD

**Issue by s2514** [piroor/treestyletab#875]
I clicked menu -> customize to move around stuff on my toolbar. 
![capture](https://cloud.githubusercontent.com/assets/11976441/7178652/70b87188-e3fe-11e4-997f-5927cd12c857.PNG)
When I exited the customization screen firefox went back to default tab behavior. I tried uninstalling and reinstalling the extension to no avail.
Do you know how I can fix this?

**Comment by tbs** [comment]
This is a current bug, I can replicate the behavior on my end. There is no solution until @piroor fix it.

This idea to not close tickets in issues list is making many bug reports being ignored, two mine still open for months but he never checks it again.

**Comment by s2514** [comment]
I poked around in the settings and it seems that it just reset it to show at the top. I set it to show on the left again and it works now.

![capture](https://cloud.githubusercontent.com/assets/11976441/7196231/d8294b24-e49b-11e4-851e-32ea20ef7126.PNG)

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
