### ISSUE TITLE
middle click  behaviour broken on FireFox 37x

### ISSUE THREAD

**Issue by cnuche** [piroor/treestyletab#877]
When using FF 37x the behaviour of middle click changes, it will no longer build a tree, it will just open this as a new tab, so you have to build the tree manually.
However, right clicking on the link and select 'open in a new tab' still works to build the tree automatically.

I love this add-on, very useful, but building up the tree manually every-time is a pain, I have checked the settings for the add-on on about:config and they are the same, not sure what changed on FF 37 but this should be addressed.

Regards,
Christian.

**Comment by cnuche** [comment]
#865 solves this.
Updating to 0.15.2015030601 ("Download Latest Version" on http://piro.sakura.ne.jp/xul/_treestyletab.html.en#download)

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by piroor** [comment]
Seems expired.
