### ISSUE TITLE
Expanding a tree does not collapse expanded tree

### ISSUE THREAD

**Issue by Chazfr** [piroor/treestyletab#879]
Expanded tab tree does not collapse when another is expanded. Firefox 37.0.2 print screen of version and settings... http://prntscr.com/6wo2yd

**Comment by hposca** [comment]
Have you updated your plugin as in #870 ?
Tested with 37.0.2 here and still works.

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by piroor** [comment]
Seems expired.
