### ISSUE TITLE
Gather to new tree broken with collapsed tree

### ISSUE THREAD

**Issue by MadscientistCC** [piroor/treestyletab#880]
If you select a group of collapsed trees and perform "Gather to new tree",
the last tree in the selection will lose all of its child tabs.

This bug doesn't happen if you select a group of expanded trees.

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by MadscientistCC** [comment]
Btw thanks for the response.

I just tried it and yes it still happens.

**Comment by piroor** [comment]
Thanks, confirmed!

**Comment by piroor** [comment]
I've realized that this is an issue of Multiple Tab Handler.
https://github.com/piroor/multipletab/commit/d8aa8e095283170179cc60f5501f7ade585afdab
https://github.com/piroor/multipletab/commit/e282b81c0a85e9c5ea542a65910ab0ffa7bf2bf1
These commits should fix this problem.

**Comment by MadscientistCC** [comment]
Thanks for the fix. It works great!
