### ISSUE TITLE
New tabs opens second new tab in wrong location

### ISSUE THREAD

**Issue by bedge** [piroor/treestyletab#881]
After the last firefox update (38.0), this started happening, I updated to the latest plugin rev, the 0.15.2015030601 snapshot and that did not help.

Opening a new tab is supposed to open it below the current tab. 
This works for the first new tab, 
For the second and later tabs, it skips the next tab and opens it one below that.

Initial condition:
![Image of Initial condition](http://home-nim-com.s3.amazonaws.com/bedge/public/initial.png)
Open a new tab from tab1 - looks good, under my current tab:

![open 1st new tab](http://home-nim-com.s3.amazonaws.com/bedge/public/tab1.png)
Open another new tab from tab1, and instead of below the 1st tab, it skips the next tab and opens below that.

![open 2nd new tab](http://home-nim-com.s3.amazonaws.com/bedge/public/tab2.png)

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by bedge** [comment]
It's fixed in the 
	treestyletab.xpi 	06-Nov-2015 15:59
build.

thanks!
