### ISSUE TITLE
High CPU usage when tabs go numerously

### ISSUE THREAD

**Issue by keihiro2** [piroor/treestyletab#882]
Windows 7 x64
Firefox: 37.0.2
Tree Style Tab: 0.15.2015030601

When tabs go numerously almost the height of Firefox window like attached images,
CPU usages hits 100% for one core of the CPU.

image No.1 (Left-Bottom of window) -> OK
![no1](https://cloud.githubusercontent.com/assets/12115391/7334487/c881816a-eb48-11e4-99e4-af9cf7f0ebe0.JPG)

image No.2 (Left-Bottom of window) -> CPU 100%
![no2](https://cloud.githubusercontent.com/assets/12115391/7334490/d0d6bbfa-eb48-11e4-9443-300b43328119.JPG)

If tabs go more than the height of Firefox window with scroll bar or go less, it goes fine again.
So, this issue may be occur only at this boundary.

image No.3 (Left-Bottom of window) -> OK
![no3](https://cloud.githubusercontent.com/assets/12115391/7334493/dbfb7778-eb48-11e4-9ee4-4793ad5de5d0.JPG)

**Comment by heftig** [comment]
This only seems to happen when the new tab button in on the tab bar. Maybe the code that controls the new tab button's position and the code that toggles scrollbar visibility are interacting badly, causing constant oscillation between two states.

**Comment by keihiro2** [comment]
Thank you for your reply.
Other add-on(Tab mix plus)'s option "show New Tab Button" may be conflicting each other.
Turned this option OFF and looks working good now.

**Comment by heftig** [comment]
I don't have tab mix plus installed. I can remove or add the new tab button via the Customize interface.

**Comment by heftig** [comment]
This is still an issue.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
