### ISSUE TITLE
Bug preventing bookmarks star menu to open

### ISSUE THREAD

**Issue by tbs** [piroor/treestyletab#883]
One more bug to TST bugs collection, now in last Nightly build (both, FIrefox and addon) it is preventing the star menu to open (to edit bookmar title/location, shortcut ctrl+d). Clicking the star does nothing.

Tested on Windows only.

**Comment by Fanolian** [comment]
Maybe bug 1159462.

**Comment by tbs** [comment]
Thanks, the bug has been fixed in today Nightly build.

**Comment by Fanolian** [comment]
Still not working for me even though bug 1159462 is fixed...
There are a couple of changes to bookmark due to Bug 951651.

**Comment by tbs** [comment]
Same thing here, the bug back few days after the fix.

**Comment by Daniellynet** [comment]
Can confirm.

**Comment by heftig** [comment]
Now also on dev edition (40.0a2).

    *************************
    A coding exception was thrown and uncaught in a Task.
    Full message: ReferenceError: aTask is not defined
    Full stack: StarUI._doShowEditBookmarkPanel@chrome://treestyletab/content/bookmarksOverlayEditable.js line 51 > eval:4:9
    StarUI.showEditBookmarkPopup<@chrome://browser/content/browser.js:5008:7
    TaskImpl_run@resource://gre/modules/Task.jsm:314:40
    TaskImpl_handleResultValue@resource://gre/modules/Task.jsm:393:7
    TaskImpl_run@resource://gre/modules/Task.jsm:322:13
    TaskImpl@resource://gre/modules/Task.jsm:275:3
    createAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:249:14
    PlacesCommandHook.bookmarkPage<@chrome://browser/content/browser.js:5235:1
    TaskImpl_run@resource://gre/modules/Task.jsm:314:40
    TaskImpl@resource://gre/modules/Task.jsm:275:3
    createAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:249:14
    PCH_bookmarkCurrentPage@chrome://browser/content/browser.js:5328:5
    BUI_onCommand@chrome://browser/content/browser.js:6545:7
    oncommand@chrome://browser/content/browser.xul:1:1
    *************************

**Comment by Tobithy** [comment]
Thanks for the tip heftig. 

For anyone else having the problem, here's exactly what I did to work around it for now. As heftig indicated, if you use tree bookmarks this will likely break them (honestly, I don't even know what tree bookmarks are or where to turn them on). 

1) Download the .xpi file, either the current build or the Firefox approved build
2) Unzip the .xpi file
3) Use a text editor to open ./content/treestyletab/bookmarksOverlayEditable.js
4) Go to line 49, and put /* at the beginning of the line to start the running comment. 
5) Go to line 70 and put */ at the end of the line to stop the running comment
6) Save the file
7) go back to the location where the files were unzipped, and zip everything up into a new file
8) Change the extension from .zip to .xpi
9) Drag the .xpi file into firefox and choose to install it. Restart, and now bookmark star menu works.

**Comment by heftig** [comment]
Or just clone this repository and create a file named `extensions/treestyletab@piro.sakura.ne.jp` in your profile which contains the path to the repo.

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by Fanolian** [comment]
This is fixed.
