### ISSUE TITLE
Search bar does not work due to Bug 1134769 (DEPRECATION WARNING: getBrowserSelection)

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#884]
I'm using current Nightly and TST 0.15.2015030601 in Win8.1

Steps to reproduce:
0. Install TST in a new profile in Nightly.
1. load any page other than about:newtab (about:home is fine)
2. Type something in the search bar (not URL bar)
3(important). Unfocus search bar by clicking somewhere else.
4. Press the arrow icon to try to perform a search. (Or the magnifying glass icon if you have one-click search disabled)

Actual result:
No searches are performed. In browser console / error console, it shows:
>DEPRECATION WARNING: getBrowserSelection
>You may find more details about this deprecation at: https://bugzilla.mozilla.org/show_bug.cgi?id=1134769
>chrome://browser/content/browser.js 16149 getBrowserSelection
>resource://treestyletab-modules/window.js 284 TSTWindow_shouldOpenSearchResultAsChild
>resource://treestyletab-modules/window.js 1305 TSTWindow_onBeforeBrowserSearch
>chrome://treestyletab/content/windowHelper.js 354 TSTWH_initToolbarItems/searchbar.doSearch
>chrome://browser/content/search/search.xml 497 handleSearchCommand
>chrome://browser/content/browser.xul 1 onclick
>null 0 null

Expected result:
A search is performed.

**Comment by jerryhuang01** [comment]
can confirm the same issue in ff 38b9 x64 win7 x64. after disabling the ext the search box works.

**Comment by ivanatpr** [comment]
Looks like this same issue is also causing the Firefox context menu "Search Google for [selection]" feature to break. I get the same deprecation warning as above followed by the following error message:

>getBrowserSelection doesn't support child process windows1 <unknown>


WORKAROUND: Setting "extensions.treestyletab.autoAttach.searchResult"=0 in "about:config" seems to fix it.

**Comment by ivanatpr** [comment]
Forgot to mention. I'm using Firefox Developer Edition/Aurora 40.0a2 (2015-05-19) with tree style tab  0.15.2015030601 **with multiprocess turned ON**. The context menu bug goes away if you turn off multi-process.

**Comment by jerryhuang01** [comment]
can confirm that ivanatpr's workaround fixed the search box problem (finally!!!). ff 38.05b2 x64 win7 x64. many thanks.

**Comment by hjri** [comment]
thanks for a workaround!

**Comment by piroor** [comment]
Like http://mxr.mozilla.org/mozilla-central/source/browser/base/content/content.js#75 I think I have to introduce new frame script to send selected text from the content process to the chrome process. But the mechanism will be used only by the handling of the searchbar search. It seems too complex for just a feature: "open search result tab as a child of the current tab, when a selected text is dragged from the content area and dropped to the searchbar"...

**Comment by piroor** [comment]
I've implemented the one told at https://github.com/piroor/treestyletab/issues/884#issuecomment-152071829 so could you try the latest development build?

**Comment by Fanolian** [comment]
Confirm fixed. Thanks.
