### ISSUE TITLE
Multiple issues including #875 (video with demo)

### ISSUE THREAD

**Issue by pennybuster** [piroor/treestyletab#885]
Hi everyone. Thanks piroor for this very useful extension! I want to help at least with identifying issues.

I'm using Linux Mint 17.1 Rebecca (package base Ubuntu Trusty), Firefox 37.0.2, Tree Style Tab nightly version 0.15.2015031900a181223 in "auto hide" mode.

The list of issues is:
1. To set a custom width size it's necessary to reset the Tab bar position, selecting option "Top" and then "Leftside" again, or to restart Firefox.
2. Same as issue #875. After entering Customize section and exiting, the sensitive area to auto show the tab bar is set on the top edge. To fix the problem, it's necessary to do the same as last issue: to reset the Tab bar position or to restart Firefox.
3. With some tabs, a parallel line appears and it's not possible to resize the tab bar width because the two-headed arrow doesn't show up there.

Video with demonstration hosted on Dropbox: https://www.dropbox.com/s/l7vcy8as7lavx8h/VID_20150506_110006348.mp4?dl=0

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

Anyway, please report different issues as separate issue for each. I cannot close an issue forever if it includes very hard bug even if other bugs are fixed. Such issue confuses me.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
