### ISSUE TITLE
Star UI arrow panel(Edit Bookmarks) does not popup due to landing Bug 951651

### ISSUE THREAD

**Issue by alice0775** [piroor/treestyletab#887]
Just for your record.

Tree Style Tab0.15.2015051100a192056 does not work nicely on Aurora40.0a2 and Nightly41.0a1.

After landing Bug 951651, Star UI arrow panel(Edit Bookmarks) does not popup.

**Comment by tbs** [comment]
When this bug will be fixed?

**Comment by ametaireau** [comment]
I confirm this doesn't work on nightly as of now.

**Comment by wenbinleo** [comment]
This bug effects Firefox 40 beta now.

**Comment by jmozmoz** [comment]
I can also confirm this problem with Firefox 40 beta

**Comment by alice0775** [comment]
Firefox 40 has been released. 
And TST died. 
Thanks

**Comment by Miccovin** [comment]
Hi, is it possible to fix this horrible Bug??? I cannot use STRG+D or the Bookmark-Star. This is so essential, that i have to remove Tree Style Tab if this is not working. Hope you will find a solution. :/

My system: xubuntu 14.04, Firefox 40.0, TST 0.15.2015030601.1-signed

**Comment by mindrones** [comment]
Confiming this bug: appeared after upgrading to Firefox 40.0.

**Comment by tbs** [comment]
Sad how this addon is each day more dead, really wish Mozilla had vertical tabs built in to Firefox.

**Comment by Daniellynet** [comment]
Maybe we can try talking to someone from Mozilla about it, unless someone already did that and got bad results?

**Comment by mindrones** [comment]
@tbs @Daniellynet I don't think this kind of comments really help motivating developers, no?
It's free and open source software after all :)

**Comment by Daniellynet** [comment]
@mindrones Oh I know, sorry! 
I just get the feeling that @piroor is busy with other projects right now, and mostly keeps this project on his back burner. :s
But this is open source, true. Could have other people trying to fix this, as they have with other issues we've encountered before.
I'd help, but my JS knowledge (or coding in general) is practically non-existent... Maybe one day I'll be good enough to contribute to TST.

**Comment by taoeffect** [comment]
Yes, I also wish Mozilla would pick up this extension and integrate it into FF.

This bug is super annoying. Bookmarking by clicking the star does add the bookmark to the unfiled bookmarks, so you have to now manually open that up, scroll to the bottom of the unfiled bookmarks, and then add keywords there.

**Comment by eToThePiIPower** [comment]
@mindrones's bug report seems to be the key.

I tried a quick fix by deleting lines 50-56 in content/treestyletab/bookmarksOverlayEditable.js, and it seems to quash this bug. I want to dive in a bit deeper to see if there are any side effects before sending in a pull request, since I don't know this code base well (at all, really). There's probably a better way to do it.

**Comment by taoeffect** [comment]
@eToThePiIPower Very cool, thanks so much for looking into this! \*_crosses fingers_\* (<= BTW, I bet no one can guess how I did the markdown for that. ^_^)

**Comment by Daniellynet** [comment]
@eToThePiIPower so I decided to test it out by deleting lines 50-56 in the same file, and sure it works now, but only some of it seems to be working?
After I bookmark it and press the star again, it seems to be locked in place like so: ![example](http://i.imgur.com/KPAMdSb.png). 
My CTRL + W function to close down tabs is broken too after this step. 

Firefox version: 
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:43.0) Gecko/20100101 Firefox/43.0 ID:20150816091433

**Comment by hofst** [comment]
@eToThePiIPower 
Can confirm that bookmark window is working when deleting the lines, but ctrl-w is broken in firefox stabel 40.0.2. If you had the time to look into this I would be very grateful

**Comment by Miccovin** [comment]
Maybe someone you know the extension named "userchromeJS". For this there exists a script named addbookmarkinlastusedfolder.js. The Script causes the same Star-/Ctrl+D-bug after updating to Firefox 40. Someone found a solution to fix this in the script - look here (in german):
http://www.camp-firefox.de/forum/viewtopic.php?p=975388#p975388
You have to look at the following posts - there is the explanation. Maybe someone helps this to fix the buggy TST finally completely.

**Comment by eToThePiIPower** [comment]
Thanks for the reports on CTRL-w failing, I noticed that myself soon after I wrote the post.

I tried wrapping the problem lines (51-56) in a try-catch block and that seems to be working better. It seems that the eval expression fails the first time the bookmark button is pressed, but if it isn't run on subsequent times the problem with CTRL-W (and showing "remove bookmark") occur.

I'll be sending up a PR tomorrow hopefully; I want to keep it running locally for the moment just in case there are other problems.

**Comment by hofst** [comment]
Your PR seems to be working for me :) (windows 10, firefox 40.0.2 stable)

thanks a lot

**Comment by piroor** [comment]
Those patching around line 50 can be rewritten with replacing of functions like 80938e8, because they `eval()` just insert simple method call at the head of each function, However there still other errors...

**Comment by piroor** [comment]
For developers I describe the background of the commit 4abc4413e98ee99bc1008c29df6414636c990811. I hope that this helps you to resolve bugs like this in future versions.

As the comment of 80938e8 TST fails to patch to `gEditItemOverlay.initPanel`.
Steps to find the change which produces this error:

 1. Find the definition of the target method: http://mxr.mozilla.org/mozilla-central/search?string=initPanel
 2. See the code: http://mxr.mozilla.org/mozilla-central/source/browser/components/places/content/editBookmarkOverlay.js#165
 3. See change logs of the file from the "Hg logs" link: http://hg.mozilla.org/mozilla-central/filelog/d5cf4e7900df/browser/components/places/content/editBookmarkOverlay.js
 4. Open "diff" links in tabs and find the commit which removes the line: `if (this._itemType == Ci.nsINavBookmarksService.TYPE_BOOKMARK) {` I've found it: http://hg.mozilla.org/mozilla-central/rev/d84b62b367b4
 5. Compare the current definition of `gEditItemOverlay.initPanel` and the removed codes to find where is the correct location to insert our codes. The old patching aims to execute inserted codes only for simple bookmarks, so, the variable `isBookmark` seems to be good information to do it. In other works, we can put our code anywhere after the variable is defined. Then I decided to put my codes before the line: `let showOrCollapse =`, like:
    
        TreeStyleTabUtils.doPatching(gEditItemOverlay.initPanel, 'gEditItemOverlay.initPanel', function(aName, aSource) {
            return eval(aName+' = '+aSource.replace(
                'let showOrCollapse =',
                'TreeStyleTabBookmarksServiceEditable.initParentMenuList(); $&'
            ));
        }, 'TreeStyleTab');
    
 6. Separate codes for each Firefox version (See also https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIVersionComparator ) like:
    

        // for Firefox 40 and later, after Bug 951651
        if (Services.vc.compare(Services.appinfo.platformVersion, '40') >= 0) {
            TreeStyleTabUtils.doPatching(gEditItemOverlay.initPanel, 'gEditItemOverlay.initPanel', function(aName, aSource) {
                return eval(aName+' = '+aSource.replace(
                    'let showOrCollapse =',
                    'TreeStyleTabBookmarksServiceEditable.initParentMenuList(); $&'
                ));
            }, 'TreeStyleTab');
        }
        else {
        // for Firefox 39 and olders
            TreeStyleTabUtils.doPatching(gEditItemOverlay.initPanel, 'gEditItemOverlay.initPanel', function(aName, aSource) {
                return eval(aName+' = '+aSource.replace(
                    'if (this._itemType == Ci.nsINavBookmarksService.TYPE_BOOKMARK) {',
                    '$& TreeStyleTabBookmarksServiceEditable.initParentMenuList();'
                ));
            }, 'TreeStyleTab');
        }

**Comment by piroor** [comment]
The commit dd2f17dd5359d6c92ad1e4c8006ca9c5b833b0d4 fixes the error: `treestyletab: doPatching: gEditItemOverlay._showHideRows is missing! utils.js:319:0`

The commit http://hg.mozilla.org/mozilla-central/rev/d84b62b367b4 removes `gEditItemOverlay._showHideRows` also. We have to insert our code to new location. Because the new version `gEditItemOverlay.initPanel` seems to contain the task of old `gEditItemOverlay._showHideRows`, I decided to insert my code to `gEditItemOverlay.initPanel` again, at its tail.

**Comment by piroor** [comment]
My private server for a service hook is still down, so the "nightly build" never been updated automatically. Sorry.

**Comment by piroor** [comment]
One more commit 5380304aa8688e7d725a206e70188afd1a526e19. I realized that there is no reason to initialize my custom UI when it is hidden, so it becomes to be executed only when the UI is visible.

**Comment by Daniellynet** [comment]
Thank you so much for the fix, @piroo !
Seems to work without issues on my end!

**Comment by taoeffect** [comment]
@piroor @Daniellynet or anyone else, where is the link to the version with the fix?

It would be great if there was a link to the nightly builds in the README.md or something.

(Thanks so much for fixing this btw!)

**Comment by Daniellynet** [comment]
@taoeffect 
I just downloaded the zip from [here](https://github.com/piroor/treestyletab), removed a few files (compared folders/files to the current version I had), zipped it and changed the extension from .zip to .xpi. :)

**Comment by taoeffect** [comment]
@Daniellynet Heh, OK, maybe I will try to hold out for a more official release. Thanks though for the tip.

**Comment by Daniellynet** [comment]
No problem! I'm just impatient and wanted to try out the fix as fast as possible, haha.

**Comment by klemens** [comment]
@taoeffect I have "compiled" a nightly based on 5380304aa8688e7d725a206e70188afd1a526e19 with the included make.sh buildscript, if you cannot wait :wink:: https://sync.schoelhorn.eu/f/27770b1311/?raw=1

**Comment by taoeffect** [comment]
Thanks @klemens, but it turned out to be remarkably simple to create the .xpi. All you need to do is clone this repo and type `make`. :smile: 

(Thanks for making that simple @piroor!)

**Comment by shearer12345** [comment]
Thanks @klemens - works great for me.

Thanks everyone for figuring it out.
Thanks @piroor for making TST :-)

**Comment by Miccovin** [comment]
Thx for the great work - works here too!

It is possible to make an official and SIGNED update? This version is not signed so we will not be able to use it with Firefox 41 - it comes out in 4 weeks. The countdown is running...

**Comment by nh2** [comment]
Can I donate to TreeStyleTab somehow? This bug reminded me that I've been using it for > 5 years and that it's quite an important tool for me.

**Comment by IshmaelYavitz** [comment]
I'm confused: is this bug really fixed?

I've tried both the XPI that @klemens provided and cloning the source directly.  When I use either, clicking the star of an already-bookmarked page *does* open the bookmark dialog - but it's completely empty.

In other words, yes the dialog pops up, but it's still completely broken.

I'm on FF 40.0.2 on Windows 7 SP1.

**Comment by klemens** [comment]
It is at least fixed for me: it works both when using the star button and when using the properties of a bookmark on the bookmarks toolbar. I am using firefox 40.0.2 on a current Arch linux (4.1.6).

**Comment by IshmaelYavitz** [comment]
Whoops: the breakage is caused by the Tree Style Tab extension - not this extension.

**Comment by IshmaelYavitz** [comment]
I double-checked: when using a version of the extension that contains the fix, the bookmark properties dialog is still empty when I click the star.  I also checked in OS X 10.10 - it doesn't work properly there either.  So Firefox >= 40 on either Win7 SP 1 or OS X 10.10.

Since this ticket is about the dialog not popping up at all, and since the bookmark dialog seems to be broken in other areas of Firefox, I've opened #930: Bookmark properties dialog broken since Firefox 40.

**Comment by gene-pavlovsky** [comment]
I was having the same issue, with Add Bookmark Here as well.
Only after I installed the latest update for ABH, as well as the nightly TST from this thread (compiled by Klemens), the bookmark feature started working again.

**Comment by Frogwing** [comment]
I absolutely love TST too. Using it with the latest version of Firefox but bookmarking isn't working for me either like for the rest of you. The star isn't clickable and Ctrl+D doesn't do anything so there is no comfortable way for me to edit bookmarks.
Will this fix soon be added as a released fix so I can just update TST? I'm not a developer and I'm not comfortable to go in and try to custom fix things.

Thank you for this wonderful addon!

**Comment by varac** [comment]
I can confirm that the custom addon from https://github.com/piroor/treestyletab/issues/887#issuecomment-132389816 fixes this bug for on FF 40.0.3 (ubuntu 15.04).

**Comment by nh2** [comment]
> @taoeffect I have "compiled" a nightly based on 5380304 with the included make.sh buildscript

Confirming too that this fix works for me. @piroor Kindly asking for a signed upload :)

**Comment by free5lot** [comment]
Thank you @piroor, and please update the version at
https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/

This issue was significant so the addon can get a lower rating there because of this bug. Thanks.

**Comment by theoden-dd** [comment]
@piroor, thank you for making fix as simple as
```shell
git clone https://github.com/piroor/treestyletab/
make
```

Considering more casual users I'm absolutely agree with @free5lot: please update https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/ for the good of the addon reputation.

**Comment by piroor** [comment]
Is this already fixed on the master/HEAD? (You can try the development build: http://piro.sakura.ne.jp/xul/xpi/nightly/ ) Then, please close this. I hope to concentrate to fix unsolved bugs.

**Comment by alice0775** [comment]
I can verify to fix the problem.

**Comment by varac** [comment]
hugh, why was this issue closed without further explanation ? 
Is it fixed, and if so, is the fix included in addon that can be found on the mozialla adons download page ?

**Comment by Miccovin** [comment]
Is it really fixed? For me it is not - e.g. I could not open tabgroups.  
It seems I am the only one still having problems. 
But it is not so important - I am using another addon now.

**Comment by piroor** [comment]
If you see more other bugs, please report each topic as each issue, because unclear subject issue is hard to be tracked.

**Comment by mindrones** [comment]
@piroor any reason why this fix hasn't been pushed to the mozilla addons site? It would be nice to see it distributed via addons updates, no?

**Comment by piroor** [comment]
@mindrones I uploaded the new released version to AMO at 2015-09-29 but it is awaiting editor's review. Current status is:

> Queue Position: 140 of 159

**Comment by mindrones** [comment]
For those landing here in the future, the latest version (which as of now also fixes this issues) can be found at https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/versions/ as Firefox won't probably upgrade this addon automatically (see #970 for explanation).
