### ISSUE TITLE
TreeStyleTabService.getLastDescendantTab(gBrowser.mCurrentTab))が,ツリーが1つの時nullを返す

### ISSUE THREAD

**Issue by ncaq** [piroor/treestyletab#888]
ツリーが1つの状態で,`TreeStyleTabService.getLastDescendantTab(gBrowser.mCurrentTab))`を実行すると,`null`が返却されます.

ツリーが1つの状態と言うのは,次の図のような状態です.

![single_tree](https://cloud.githubusercontent.com/assets/2913112/7670673/faa6ea3e-fce8-11e4-91e8-1bede9ceaa0e.png)

Abstruct~タブが返されることを期待しましたが,`null`が返されます.

独立したタブを追加すると,Abstruct~タブが返されます.

私のやりたかったことは,`TreeStyleTabService.getDescendantTabs`で取得した配列の末尾を参照することで出来ましたが,バグかもしれないと思ったので報告します.

**Comment by piroor** [comment]
すみません、見落としていました。
XPathベースのやり方はこのケースだと却って分かりにくくトラブルの元のようなので、XPathを使わないでやるようにしました。
