### ISSUE TITLE
Standard firefox menu inaccessible

### ISSUE THREAD

**Issue by Caleb9** [piroor/treestyletab#891]
Disclaimer: I'm using Cyberfox 38.0.1 (64 bit compilation of Firefox).

The standard firefox menu (File, Edit, View and so on) does not appear after pressing alt when Tree Style Tab is installed. It is also impossible to set it to be always displayed.

**Comment by irvinm** [comment]
I have Cyberfox 38.0.1 and TST (0.15.2015051100a192056) and have no problem accessing the menu when hitting ALT.  Just an FYI.

**Comment by Caleb9** [comment]
I have it installed on two separate Windows 8.1 systems, both with the same set of addons and it doesn't show in any of them. Here's a screenshot of all the addons I have:
![screenshot 3](https://cloud.githubusercontent.com/assets/7767011/7858784/70896088-053b-11e5-9c64-c8e048fabe52.png)

**Comment by Caleb9** [comment]
BTW uninstalling the TST doesn't solve the problem but resetting Cyberfox and installing all the other addons, the menu is accessible. As soon as I install TST it doesn't show up anymore.

**Comment by Caleb9** [comment]
I discovered that this bug is present only in Cyberfox, Firefox using the same profile doesn't suffer from it.

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by piroor** [comment]
Seems expired.
