### ISSUE TITLE
[Suggestion] Open page source as a child tab

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#892]
[Bug 1067325](https://bugzilla.mozilla.org/show_bug.cgi?id=1067325) introduces a new default behaviour that page source is open as a new tab instead of a new window (via Ctrl-U or context menu>View Page Source).
Currently TST opens the page source as the last parent tab. I think it is logical to open it as a child of the current tab.

The bug will probably be uplifted to Firefox 40.

**Comment by piroor** [comment]
Thanks, I forgot this. The commit b83a92bdb00cdbf77e313ad665e62c0ce2d9d35a does this.
