### ISSUE TITLE
[Feature Request] Keyboard shortcut to show/hide tab bar

### ISSUE THREAD

**Issue by rubaboo** [piroor/treestyletab#894]
Alternatively, could you provide the code to toggle it, so I could make a keyboard shortcut myself using Keyconfig add-on.

By the way, I found that clicking on the grippy does not work consistently to show/hide the tab bar. The behavior is like described in #538. 

My environment: Windows 7, Firefox 38.0.1,  Tree Style Tab 0.15.2015030601.

**Comment by hposca** [comment]
Actually, if you hold the Ctrl key, while the tab bar is hidden, it is shown.

Don't know if this helps, but looks like the event (aEvent.ctrlKey) is defined here:

    content/treestyletab/content-utils-autohide.js
    modules/window.js

And actions that use this event are here:

    modules/browser.js
    modules/base.js
    modules/tabbarDNDObserver.js

**Comment by nameanyone** [comment]
Showing the tab bar with Ctrl down is different in that it is overlayed on top of content. It is meant to be temporary. I, on the other hand, want to have the bar mostly open, but hide it when the content is too wide.

**Comment by AndydeCleyre** [comment]
@piroor why is this out-of-purpose? Many extensions offer keyboard shortcut triggers.

**Comment by Mooninaut** [comment]
I would like to see this implemented.

**Comment by yang-zhang** [comment]
This would be a great improvement.

**Comment by josduj** [comment]
To anyone still looking for this feature, Hide Tabbar extension seems to work.

**Comment by shelt** [comment]
@piroor how is this out of purpose? The bookmarks and history sidebars replace the tabs sidebar. Since there are shortcuts for those, there should be shortcuts to switch back, no?

**Comment by piroor** [comment]
Now you can toggle TST's sidebar panel with F1 key, on TST 2.0.x.

**Comment by SicariusNoctis** [comment]
Is there any way to change which key? I use F1 for my dropdown terminal.

**Comment by piroor** [comment]
Sadly it is impossible for now. The keyboard shortcut is hard coded here:

https://github.com/piroor/treestyletab/blob/e1a71fce2aec7144f644f5c7afaf3f50d9b481d4/webextensions/manifest.json#L51-L56

and it can't be reassigned dynamically. There are number of bugs around keyboard shortcut and one of them can solve it:

 * [1303384 - UI for re-assigning command shortcuts](https://bugzilla.mozilla.org/show_bug.cgi?id=1303384 "1303384 - UI for re-assigning command shortcuts")
 * [1320332 - Support overriding existing keybinding through WebExtensions](https://bugzilla.mozilla.org/show_bug.cgi?id=1320332 "1320332 - Support overriding existing keybinding through WebExtensions")
 * [1215061 - Better keyboard shortcut support](https://bugzilla.mozilla.org/show_bug.cgi?id=1215061 "1215061 - Better keyboard shortcut support")
 * [1267145 - Add ability to disable keyboard shortcuts of Firefox itself](https://bugzilla.mozilla.org/show_bug.cgi?id=1267145 "1267145 - Add ability to disable keyboard shortcuts of Firefox itself")

**Comment by dmusican** [comment]
F1 works great for hiding it, thanks for posting that here. It would be helpful if that appeared in the menu bar under View, Sidebar, so I could have discovered it without having to land here. :)

**Comment by rubaboo** [comment]
I'm closing this. Thank you for fixing it. And thanks to other commenters for their support.

**Comment by stevelandeyasana** [comment]
For anyone else discovering this via Google search: if you're on a Mac, you can do this from the Keyboard prefpane. `System Preferences -> Keyboard -> Shortcuts -> App Shortcuts`

<img width="542" alt="screenshot 2018-12-11 14 06 08" src="https://user-images.githubusercontent.com/38225497/49833317-f6386400-fd4d-11e8-81da-5d8b3c99ca26.png">

**Comment by Mrostgaard** [comment]
@stevelandeyasana 
Does this still work? When i follow your instructions and try to press my combination this doesn't work. How do i find the name of the Menu title? (in case it has changed)

**Comment by d8aninja** [comment]
I did the above (Keyboard > App Shortcuts) and it worked ... for a day? Now the same shortcut is sitting there in the menu, but it does not work in Firefox to open/close the tabs on the left side.  I even deleted it, redid it the same way, and it still does not work...any ideas?
![image](https://user-images.githubusercontent.com/3494773/89124064-6189f900-d491-11ea-89e4-1e5e57fffbdd.png)

**Comment by blindstitch** [comment]
I must press function-F1 to get F1 on my laptop keyboard and is extremely awkward to type all the time, I would love to have the ability to add my own keybinding.

**Comment by irvinm** [comment]
![image](https://user-images.githubusercontent.com/979729/152666472-b7b8839f-1e46-438c-8b13-04edaeed81da.png)

**Comment by blindstitch** [comment]
> ![image](https://user-images.githubusercontent.com/979729/152666472-b7b8839f-1e46-438c-8b13-04edaeed81da.png)

Thanks so much! Been a firefox user since I was 15, can't believe I hadn't seen this...
