### ISSUE TITLE
Tabs don't move for social sidebar

### ISSUE THREAD

**Issue by nkestrel** [piroor/treestyletab#895]
**Steps to reproduce:**

1. Move tabs to right side.
2. Activate a service that uses the social sidebar (https://activations.cdn.mozilla.net), eg delicious.
3. Show the social sidebar (appears on right hand side).
4. Resize or open/close the social sidebar.

**Expected results:**

Tabs should move to accommodate the social sidebar.

**Actual results:**

Tabs do not respond to social sidebar changes and remain in the same position.

**Comment by piroor** [comment]
Recent commits 0ac67fc and 38f01ba should fix this issue.

**Comment by nkestrel** [comment]
Looks like this was already fixed in 0.15.20150902901

**Comment by piroor** [comment]
OK, I close this.
