### ISSUE TITLE
Compatibility with Tab Badge and Noise Control

### ISSUE THREAD

**Issue by darktrojan** [piroor/treestyletab#898]
Hello, I make the add-ons [Tab Badge](https://addons.mozilla.org/firefox/addon/tab-badge/) and [Noise Control](https://addons.mozilla.org/firefox/addon/noise-control/). Both add-ons add icons to the tab, next to the close button, like this:

![](https://i.imgur.com/PMnZ4NG.png)

With TST enabled, the tab's contents lose their normal order: 

![](https://i.imgur.com/EnDUtlG.png)

I'm trying to think of a good solution. The best I can think of at the moment is for TST to fire an event after setting the ordinal attributes. At that point I can rearrange the elements I added into the right place.

**Comment by piroor** [comment]
Thanks. 12757cf2c34e611864483d1dee3470f53b518514 and 75050af4926ecdb1e26edaa14e162d50a18481ba should fix this.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
