### ISSUE TITLE
"Auto Shrink tab bar" doesn't work correctly

### ISSUE THREAD

**Issue by Infocatcher** [piroor/treestyletab#900]
Width of vertical tab bar becomes smaller, but doesn't expanded automatically.
(but all works fine in "Auto Hide" mode)

Tested with latest Tree Style Tab 0.15.2015051100a192056 + Firefox 31.7.0, 34.0.5, 35.0.1, 36.0.4, 37.0.2, 38.0.5 and latest Nightly.

**Comment by ned-martin** [comment]
Happening on Firefox 42b1 as well.

Auto hide works, but in auto shrink, there is no way to make the tab bar expand.

**Comment by piroor** [comment]
As #942 this seems to be fixed on the master/HEAD.

**Comment by Infocatcher** [comment]
Initial issue now looks fixed, but now appears another bug with <a href="https://addons.mozilla.org/firefox/addon/tab-scope/">Tab Scope</a> extension: tab bar will be shrinked after showing of preview.

**Comment by piroor** [comment]
I couldn't reproduce this issue on Nightly 45.0a and Firefox 41.0.2, with Tab Scope 1.6.2.1 + TST 5111cf446bf2b0abd2d7db406a5ce2119abdf4c4. Any other step to reproduce?

**Comment by Infocatcher** [comment]
Looks fixed for me now, thanks!
