### ISSUE TITLE
Auto hide behaviour is reversed after going into fullscreen once

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#903]
Using current Nightly (2015-06-14) and TST nightly.

STR:
1. Install TST in a new profile. 
2. Leave auto hide setting as default I.e. Normal window: always show; Full screen: auto hide
3. Enter and exit full screen by a HTML5 youtube video, or use this test case: https://bug1173866.bugzilla.mozilla.org/attachment.cgi?id=8621346

Actual result:
Before entering full screen, tab bar behaves as expected.
After going into full screen, tab bar always shows.
Exiting full screen tab bar auto hides in normal windows.

There are a few changes in Nightly recently about fullscreen that may be relevant:
[Bug 1161802](https://bugzilla.mozilla.org/show_bug.cgi?id=1161802) - Put document in fullscreen state and trigger the event after sizemodechange
[Bug 1173866](https://bugzilla.mozilla.org/show_bug.cgi?id=1173866) - DOM fullscreen broken in e10s (DOM fullscreen fails on the other than the first tab)

**Comment by Fanolian** [comment]
Actually, tab bar should not be available in fullscreen videos. Recent Nightlies break TST's behaviour.

**Comment by Daniellynet** [comment]
Yep, can confirm the issue.

**Comment by Fanolian** [comment]
Another patch that may be relevant.
[Bug 1176233](https://bugzilla.mozilla.org/show_bug.cgi?id=1176233) - Simplify fullscreen code

Now when entering fullscreen, tab bar is shown but not the tabs. 
Exiting fullscreen causes tab bar to be auto hidden.

**Comment by ripdog** [comment]
This happens to me, but about a week ago the behaviour changed. Now, instead of a tab bar on the left when in fullscreen, there is a big grey bar about the same size and shape as the tab bar. It is not usable as a tab bar.

**Comment by heftig** [comment]
Doing this works around it:

```diff
diff --git i/modules/browser.js w/modules/browser.js
index d91f39d..8398a9d 100644
--- i/modules/browser.js
+++ w/modules/browser.js
@@ -5123,7 +5123,7 @@ TreeStyleTabBrowser.prototype = inherit(TreeStyleTabWindow.prototype, {
 	onBeforeFullScreenToggle : function TSTBrowser_onBeforeFullScreenToggle() 
 	{
 		if (this.position != 'top') {
-			var isEnteringFullScreenMode = !this.window.fullScreen;
+			var isEnteringFullScreenMode = this.window.fullScreen;
 			// entering to the DOM-fullscreen (ex. YouTube Player)
 			if (this.document.mozFullScreen && isEnteringFullScreenMode) {
 				this.setTabbrowserAttribute(this.kDOM_FULLSCREEN_ACTIVATED, true);
```

**Comment by Daniellynet** [comment]
@heftig Oh my gooooosh, thank you so much! It works beautifully!

**Comment by ripdog** [comment]
Hi all,

I built a fully functional TST for current nightly. Applied @jryans fix for animations and the fullscreen fix by @heftig. Thanks to both!

As usual, if you don't trust me, build it yourself, it's pretty easy. http://www.mediafire.com/download/krbueigd4z2ux66/treestyletab.xpi

If you aren't on nightly, this probably won't work very well for you.

**Comment by piroor** [comment]
The patch introduced at #903 breaks my Firefox 39.
I thinks the fix must be done only for newer versions of Firefox.

**Comment by tbs** [comment]
Can you release the Nightly release with this fix on http://piro.sakura.ne.jp/xul/xpi/nightly/ please.

TY.

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by Fanolian** [comment]
This is fixed. Thanks.
