### ISSUE TITLE
TST not activating after FF restart 

### ISSUE THREAD

**Issue by lvinsel** [piroor/treestyletab#904]
Most of the time when I get out of Firefox and after most reboots, I have to:
1. remove Tree Style Tabs
2. restart Firefox
3. add TST to Firefox, install and reboot
to make TST work again.

It works fine then and remembers my tabs.

This has been happening for months.  I really love TST and wouldn't go through the hassle if it wasn't so great.

**Comment by lvinsel** [comment]
I forgot to mention this is on a Windows 7 machine.

**Comment by HPG1972** [comment]
I'm having a similar experience: I install it, it works for a bit, then stops working. I'm on Firefox 38.0.5, Win 7.

**Comment by lvinsel** [comment]
I was on version 32, I just upgraded.  I thought I was on automatic 
updates.

I've got a bunch of security addons and Sandboxie that I am going to 
start disabling, to see if any of them are in conflict. Adblock Plus, 
Lastpass, Noscript, Privacy Badger.

**Comment by vikramls** [comment]
@lvinsel Can you check if the option "Tab bar position" is set correctly for you? I ran into a similar? issue where hitting customize on the burger bar caused all tabs to show up on top. The fix was to select the "Leftside" radio button in my case.

**Comment by lvinsel** [comment]
Yes it is set correctly now.  But I will check it the next time that it 
happens.  It is intermittent.

**Comment by lvinsel** [comment]
Yes TST failed to load again today and I checked the "Tab bar position" in the options.  The option was set to leftside.  I tried various setting to see if it would correct and load.  No luck.  I had to remove TST, restart FF, Load TST, and restart FF to get it working again.

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by lvinsel** [comment]
I did remove "Tree Style Tabs" for awhile and have been using "Tree 
Tab".  However, I like TST better and would like to help testing your 
development.

I installed the Firefox Developers Addition (v44.0a2).

How do I install the TST nightly build?

**Comment by lvinsel** [comment]
I'm on Windows 7

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
