### ISSUE TITLE
Second tab in list is invisible when firefox opens on Linux.

### ISSUE THREAD

**Issue by derram** [piroor/treestyletab#908]
http://i.imgur.com/5gZurTW.png

Only way to fix is it to middle click to close the tab or disable, restart, enable, restart.

**Comment by piroor** [comment]
Doesn’t happen on my Ubuntu 14.04LTS, Firefox 40, TST HEAD@master. Could you report the platform information, version (edition) of Firefox, and other customizations including addons? Of course it will really help me that you find the smallest conditions to reproduce the issue by yourself.

**Comment by rdmad** [comment]
Have this happening on two different machines. One ubuntu mate and the other xubuntu. Both running 15.10 and ff 43. Disabling KeeFox in both cases managed to fix the problem, so I'm guessing that there may be an issue with the two addons.

**Comment by piroor** [comment]
Thanks, confirmed with KeeFox. Something blocks to set `fadein="true"` for the tab.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
