### ISSUE TITLE
"Unresponsive script" on startup

### ISSUE THREAD

**Issue by indeyets** [piroor/treestyletab#913]
The issue started with late Firefox-40 builds (or recent nightly treestyletab build?) and persists to current Firefox-41.

Whenever I have TreeStyleTab enabled I get the following dialog:

![add-ons manager 2015-07-10 11-34-44](https://cloud.githubusercontent.com/assets/13445/8615101/852d298c-26f8-11e5-98cf-c749e6502e01.jpg)

`Unresponsive script`, `chrome://browser/content/tabbrowser.xml:5674`

Active tab is responsive before dialog appears, stalled afterwards, no matter what I chose. Other tabs have "New tab" titles and are never fully initialized. Browser works just fine if I disable treestyletab.

**Comment by indeyets** [comment]
I'm not sure what would be the proper procedure for debugging this (clicking "Debug script" doesn't seem useful). Screenshot lists all enabled extensions.

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by indeyets** [comment]
I don't have the profile which had that behavior anymore. I'll close as I don't have a way to verify fix for this
