### ISSUE TITLE
TST is incompatible with BackTrack Tab History add-on

### ISSUE THREAD

**Issue by Drugoy** [piroor/treestyletab#914]
If both add-ons are installed and working - sometimes (or always, not sure) I get stuck unable to open a new tab: neither with a middle click on any link on any page, nor with 'new tab' button right from the tab-bar.
When that happens Error Console yields this:
```ReferenceError: onBeforeFunction is not defined chrome://treestyletab/content/windowHelper.js line 204 > eval:5:0```

**Comment by sumyungguy** [comment]
http://backtrack.byalexv.co.uk/FirstRun.html
"Compatibility with other add-ons"
"Certain other add-ons use a deprecated method of modifying browser functions (string patching with eval) that is not compatible with the newer, recommended, method that BackTrack uses. For this reason, a special backwards compatibility mode is available for BackTrack. If you are experiencing compatibility issues with another add-on, it can be enabled by toggling the preference "extensions.backtrack.stringPatchCompatibility" to true, then restarting Firefox."

**Comment by Drugoy** [comment]
Thanks.
