### ISSUE TITLE
Many TST features are broken since 2015-07-21 build (due to removal of mozRequestAnimationFrame?)

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#915]
Nightly 2015-07-21 build, TST 0.15.2015030601.1-signed
Reference bug: [Bug 909154](https://bugzilla.mozilla.org/show_bug.cgi?id=909154) - Consider removing support for the prefixed mozRequestAnimationFrame 

Since this build, many TST features are not working. I don't know if all of them relates to mozRequestAnimationFrame.

New issues since 2015-07-21 build:
1. Warning in Error console when I try to open TST's option window:
>Error: aWindow.mozRequestAnimationFrame is not a function
>Source File: resource://treestyletab-modules/lib/animationManager.js
>Line: 123

2. Tab bar cannot be put on right/bottom side
3. Tab bar do not refresh properly. Sometimes when I open a new tab, it does not show on tab bar but I can ctrl-tab to it.

**Comment by ripdog** [comment]
Hi all,

I built a fully functional TST for current nightly. Applied @jryans fix here and the fullscreen fix by @heftig. Thanks to both!

As usual, if you don't trust me, build it yourself, it's pretty easy. http://www.mediafire.com/download/krbueigd4z2ux66/treestyletab.xpi

If you aren't on nightly, this probably won't work very well for you.

**Comment by ldgbc** [comment]
Thank ripdog, be better if you have forked TST and release it on Github rather than use Mediafire.

**Comment by ripdog** [comment]
Just a temporary solution for lazy people. Piroor has returned so the
master should be usable now.


On Fri, Jul 24, 2015, at 09:15 AM, ldgbc wrote:
> Thank ripdog, be better if you have forked TST and release it on
> Github rather than use Mediafire.


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/piroor/treestyletab/issues/915#issuecomment-124242377

**Comment by ClefAria** [comment]
I can see that my currently-installed version has the described changes, but this issue:

https://github.com/gomita/firegestures/issues/98

still persists. I'm using the nightly from September 25 2015, and Firefox 41.0.
