### ISSUE TITLE
Removal of mozRequestAnimationFrame broke TST

### ISSUE THREAD

**Issue by nnethercote** [piroor/treestyletab#919]
https://bugzilla.mozilla.org/show_bug.cgi?id=909154 removed the prefixed version of `mozAnimationRequestFrame` from Firefox. As a result, Tree Style Tab is no longer working.

Here's an example of what TST should look like. This is the revision just before bug 909154's patch landed:
![tst1](https://cloud.githubusercontent.com/assets/1940286/8898686/a8b024b2-33dd-11e5-8dba-41ed75a0d33f.png)

Here's what it looks like afterwards:
![tst2](https://cloud.githubusercontent.com/assets/1940286/8898687/ad4e2e1a-33dd-11e5-8c4c-cf99b2517730.png)

There is no nesting of tabs; clicking on the +/- buttons does nothing; middle-clicking on links does nothing; Ctrl-T does nothing. It's totally unusable.

**Comment by nnethercote** [comment]
I'm using version 0.15.2015030601.

**Comment by nnethercote** [comment]
I found version 0.15.2015061300a003855 at http://piro.sakura.ne.jp/xul/xpi/nightly/ and it's working, even though when I look in the .xpi file I still see uses of mozRequestionAnimationFrame. So now I'm confused.

Finding the latest version of TST is a confusing task.

**Comment by nnethercote** [comment]
> I found version 0.15.2015061300a003855 at http://piro.sakura.ne.jp/xul/xpi/nightly/ and it's working, even though when I look in the .xpi file I still see uses of mozRequestAnimationFrame. So now I'm confused.

Today that version had the problem, so I hand-edited the .xpi file to change the two calls to `mozRequestAnimationFrame` to `requestAnimationFrame` and that fixed the problem again. So this appears to basically be a "get the code in the repository, which is good, into distributed .xpi files" issue.

**Comment by CrashNBurn71** [comment]
I switched back to [Nightly 2015-07-19](http://archive.mozilla.org/pub/firefox/nightly/2015-07-19-03-02-19-mozilla-central/firefox-42.0a1.en-US.win64.zip), for now anyways. 
There's another NULL error with nightlies 07-21 thru 07-27.

Looks like Mozilla's updates are going to break User Style Manager, and Session Manager as well. Lovely... I'll be done with FireFox if that's the case. Stylish is garbage (and when it breaks, you can't even access your css styles, as it DB stores them instead of plain text files).

**Comment by nnethercote** [comment]
I [blogged](https://blog.mozilla.org/nnethercote/2015/07/28/a-work-around-for-tree-style-tab-breakage-on-firefox-nightly-caused-by-mozrequestanimationframe-removal/) about this, including my explanation of the work-around (which is to modify the code in-place).

**Comment by CrashNBurn71** [comment]
Mozilla has deprecated "LET" - which is used by TST and other extensions. That hammer will drop soon I imagine.

**Comment by asutherland** [comment]
Thanks for blogging about this, nnethercote, my sanity is much improved by having TreeStyle Tabs back!

CranNBurn71, let as a whole is not deprecated.  Let is an ES2015 standard.  But Firefox/Gecko's JS Engine SpiderMonkey had some speculative features as part of the SpiderMonkey specific JS1.7 and JS1.8 releases.  The pieces that didn't make it into the standard are being deprecated and removed, such as let expressions (https://bugzilla.mozilla.org/show_bug.cgi?id=1023609), but most existing code should be able to be made happy with a small amount of work.

**Comment by CrashNBurn71** [comment]
@asutherland 
Thanks. It looks like most of the extensions using **let** that I can see are utilizing the block-scoping. Which makes the Browser Console error-output highly suspect, as it is just logging a deprecation message for ***any*** usage of **let**.

**Comment by jryans** [comment]
This seems like a duplicate of #915, which should be fixed by 008a520efdcbdc7653b29feb4f76cd30759814e5 in master.

**Comment by nnethercote** [comment]
Indeed, it is a dup of #915.
