### ISSUE TITLE
Add "visibility: collapse" for collapsed child tab(s)

### ISSUE THREAD

**Issue by asamuzaK** [piroor/treestyletab#926]
When tabbar style is "None" (Firefox default) and child tab(s) is collapsed, parent tab:hover doesn't work.
That's because there is transparent child tab(s) over the parent tab.
Child tab(s) shoud be collapsed, not only opacity:0.

Solution proposal:
Add CSS for collapsed child tab(s).
Maybe around content/treestyletab/treestyletab.css#L43 ?

.tabbrowser-tab[treestyletab-parent][treestyletab-collapsed][treestyletab-collapsing-phase="collapse"] {
	visibility: collapse;
}

**Comment by piroor** [comment]
I think that this rule should do it:

~~~
/* collapse/expand tree of tabs */
.tabbrowser-tabs[treestyletab-allow-subtree-collapse="true"]
  .tabbrowser-tab[treestyletab-collapsed-done="true"] {
	visibility: collapse;
}
~~~

If it doesn't work, something jams TST to set the attribute `treestyletab-collapsed-done`. Any other tab-related addon, full theme, or others? What platform?

**Comment by asamuzaK** [comment]
Other tab-related addons:
ブックマークを新しいタブで開く (Open Bookmarks in New Tab)
リンクを新しいタブで開く
I disabled both for test, but no changes.

Platform etc.:
Win10 64bit
Firefox Dev Edition (42a2)
Happens on both Default theme and Dev Edition theme.

I don't see "treestyletab-collapsed-done" attribute in collapsed tab.
(list below are treestyletab related attributes I got with InspectorWidget)

style="margin-left: 12px ! important; margin-top: -32px ! important; opacity: 0 ! important;"
treestyletab-allow-subtree-collapse="true"
treestyletab-collapsed="true"
treestyletab-collapsing-phase="collapse"
treestyletab-id="tab-&lt;1441011764603-407&gt;"
treestyletab-insert-after="tab-&lt;1441012084418-61019&gt;"
treestyletab-nest="1"
treestyletab-parent="tab-&lt;1441011757607-22870&gt;"
treestyletab-y-offset="32"

**Comment by piroor** [comment]
Does this still happen? Then, do you use any userChrome.css rule (or something) to disable animation effect around opening/closing tabs? I think such CSS rules possibly blocks TST to set the attribute `treestyletab-collapsed-done`.

**Comment by asamuzaK** [comment]
Checked with userCrome.css disabled, and it seems to work fine.
Thanks.
