### ISSUE TITLE
Mad tabs go back to default firefox tabs?

### ISSUE THREAD

**Issue by Kocrachon** [piroor/treestyletab#928]
I am on Ubuntu 12.04 (can upgrade, work related) and I am on firefox 40.0 for Ubuntu. I had treestyle tabs working, but after messing around with my Toolbar customizing, it switched back to the default tab style.I tried removing and install treestyle tabs agian, but the same crappy ones are still there.

Anyone got an idea how to make them come back?

**Comment by Kocrachon** [comment]
Never mind, was able to just click and drag it...

**Comment by chronometric** [comment]
I ran into this problem in FF 41 after moving a few buttons on the toolbar. I tried un/installing and different settings, but was unable to get the tab tree sidebar to reappear. 

I was unable to locate something to drag as @Kocrachon did, either in the FF customize window or the primary interface. Can you explain in more detail how you were able to change back from the default horizontal tabs?
