### ISSUE TITLE
adding a bookmark is fine, but editing (clicking star again) doesn't work

### ISSUE THREAD

**Issue by bettabacon** [piroor/treestyletab#929]
I've been using TST for ages. I love it!  However, when I upgraded FF to v40.x, adding a bookmark worked, but then clicking the star again in the toolbar didn't bring up the edit dialog, where I could add tags. I have to open up all bookmarks and find the site to make edits there. I found the problem by disabling all extensions and adding each one-by-one, and in regression. TST stood out as the problem extension. I regretfully have disabled it, but I hope Piro will make an update soon. I'll be watching for it. 
Using Mac OS X 10.7 with FF v40.0.2. I couldn't find out where to add this trouble ticket, so I apologize is this isn't protocol.

**Comment by Daniellynet** [comment]
Your luck would be that it *just* got fixed. #887

**Comment by piroor** [comment]
I close this.
