### ISSUE TITLE
Bookmark properties dialog broken since Firefox 40 when installed alongside Add Bookmark Here 2 extension

### ISSUE THREAD

**Issue by IshmaelYavitz** [piroor/treestyletab#930]
When both the Tree Style Tab extension and the Add Bookmark Here 2 extension are installed, the bookmark properties dialog - including both editing an existing bookmark (via the bookmarks toolbar) and creating a new one - is completely broken.

The following repro steps illustrate one incarnation of the bug:

1. Turn on the bookmarks toolbar via View -> Toolbars -> Bookmarks Toolbar.
2. Have 1 or more bookmarks in the Bookmarks Toolbar.
3. Right-click a bookmark in the Bookmarks Toolbar, choose Properties.

Expected result:

The bookmarks properties dialog is shown, with the fields populated according to the values stored in bookmark.

Actual result:

A bookmarks properties dialog is shown, but every field is blank.

.
Editing bookmarks via the Library (e.g. Bookmarks menu -> Show all bookmarks) works fine - but it doesn't use the bookmarks properties dialog.

However, creating *new* bookmarks via the Library is broken.

Here are repro steps for that:

1.  Open Library.
2.  Go to anywhere in the tree underneath any of the children of All Bookmarks i.e. underneath one of Bookmarks Toolbar, Bookmarks, Menu, or Unsorted Bookmarks.
3.  Right click empty space, choose "New Bookmark..."  A dialog will pop up.
4.  Change the title from "New Bookmark" to "Test".
5.  Set the location to "http://example.com/".  (The location in the dialog is initially blank.)
6.  Click the "Add" button.

Expected result:

A new bookmark is added with the title "Test" and the location "http://example.com/".

Actual result:

A new bookmark is added with the title "New Bookmark" and a blank location.

.
So it seems that the bookmark dialog is broken everywhere in Firefox >= 40.0.

I've confirmed this in Firefox 40.0 and 40.0.2, under Windows 7 SP1 and OS X 10.10.

.
Support for the Add Bookmark Here 2 extension is handled by a single (un-threaded) post on forums.mozillazine.org.  Here is a link to what is - at the moment - the most recent page of the thread: http://forums.mozillazine.org/viewtopic.php?f=48&t=522643&start=765

And a direct link to the comment I added to the post: http://forums.mozillazine.org/viewtopic.php?f=48&t=522643&p=14304983#p14304983

The author or maintainer of the extension has the username yuoo2k.

I think a lot of people find both extensions indispensable, so I hope that you guys can work together.  :)

.
BTW, this was made additionally difficult to diagnose previously because of the following bugs:

#887 - Star UI arrow panel(Edit Bookmarks) does not popup due to landing Bug 951651
#929 - adding a bookmark is fine, but editing (clicking star again) doesn't work

So to anyone trying to reproduce this, it's important to use a build of Tree Style Tab that contains the fix described in #887.

(Note that #887 is about clicking the blue star and not having anything pop up at *all*, whereas this ticket is about the popped-up dialog subsequently being broken there and everywhere else in Firefox.)

**Comment by IshmaelYavitz** [comment]
This may actually be an issue with the Add Bookmark Here extension.  Bugs in both extensions are making it difficult to track down the root cause.  Feel free to close this and I'll open a new ticket if necessary.

**Comment by michaelk42** [comment]
Add Bookmark Here 2 is not required for TST to break bookmarking. I've never had that, and the problem exists even when TST is the only add-on enabled.

**Comment by IshmaelYavitz** [comment]
So, the author of Add Bookmark Here 2 released an updated version that resolves these problems for me personally.

Here's a link to his post about the update: http://forums.mozillazine.org/viewtopic.php?f=48&t=522643&start=765#p14306747

If I see future problems with the combination - or with TST installed by itself - I'll be sure to come back here and comment.

**Comment by piroor** [comment]
I've tested TST HEAD@master on Firefox 40.0.3 with Add Bookmarks Here 2  40.0.20150829, and they seem to work fine for me. Can I close this? Or, this still appear on some situations?

**Comment by IshmaelYavitz** [comment]
@piroor You can close this.  Thanks.

**Comment by piroor** [comment]
Thanks.
