### ISSUE TITLE
Cannot select theme or twisties

### ISSUE THREAD

**Issue by SlugFiller** [piroor/treestyletab#935]
In the latest git version (commit cbf0cbd47e) the theme and twisties selection in the options are not displayed correctly. Only the "default" and "none" options appear correctly, while the others are invisible. For the theme, two arrows pointing left and right are visible, but no themes. It is still possible to manually set either through about:config

Tested on Nightly 43.0a1 (2015-09-01) on Windows

**Comment by ned-martin** [comment]
Still an issue on 0.15.2015092500a153759

**Comment by piroor** [comment]
The commit b607f36 should fix this. Try the latest development build to confirm it!
http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by SlugFiller** [comment]
Tested with commit b607f36586b29a9cd1a64656354c39d34e26fc2f on Nightly 44.0a1 (2015-09-25). Problem appears to be fixed.

**Comment by piroor** [comment]
Can I close this issue?

**Comment by ned-martin** [comment]
Fixed for me.

**Comment by piroor** [comment]
Thanks, I close this.
