### ISSUE TITLE
Child Tabs Not Being Created By Link Clicks

### ISSUE THREAD

**Issue by AskKim** [piroor/treestyletab#936]
Neither click, nor ctrl-leftclick, on a link, cause the link to be opened as a child tab of the parent. 

Clicking or ctrl-leftclick'ing the link causes the link to open at the bottom of the tree stack at the same tier as the parent. 

Firefox 40.0.3  
Tree Style Tab 0.15.2015030601.1-signed

Verified, in settings that "Insertion position of new child tabs" is set to "Insert to the top of the tree, as the first child. Rather than the "Append to the last of the tree", which seems to be what the add-on is doing. 

Tabs can be manually clicked and dragged into the child position, so the position itself does still exist.

**Comment by AskKim** [comment]
Problem vanished on deactivating most of my other add-ons. I'll have to troubleshoot this further as apparently there is a conflict somewhere.

**Comment by romedius** [comment]
Had a similar problem. it works again with the nightly build.
For a certain amount of tabs it works fine, after ~30 the tabs are not visible any more.
I can change to the opened tabs with ctrl + tab. / ctrl + shift +tab.
FF version: Iceweasel (Debian) 38.2.1

**Comment by piroor** [comment]
Is this already fixed on the master/HEAD? (You can try the development build: http://piro.sakura.ne.jp/xul/xpi/nightly/ ) Then, please close this. I hope to concentrate to fix unsolved bugs.

**Comment by piroor** [comment]
I close this.
