### ISSUE TITLE
Autoshrink will not expand

### ISSUE THREAD

**Issue by ned-martin** [piroor/treestyletab#942]
In FF42.0b1 with TST 0.15.2015091400a190734, when set to auto-shrink, there is no way to expand the tab bar.

**Comment by ned-martin** [comment]
Auto-hide works. Auto-shrink does not - well, it is shrunk but can't expand.

Doesn't seem to be any related errors in console.

**Comment by piroor** [comment]
Thanks. I think the commit a43b31b should fix this issue. Could you try the development build and confirm that the bug is certainly fixed?: http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by ned-martin** [comment]
Autoshrink appears to be working now using 0.15.2015092500a153759 on FF 42.0b1

Thanks.

**Comment by mausalimi** [comment]
this seems to be the same as i posted long ago?
https://github.com/piroor/treestyletab/issues/860

better description here though, i agree. :)

**Comment by piroor** [comment]
@mausalimi Does the latest development build still reproduces #860 for you?

**Comment by mausalimi** [comment]
@piroor 
it does work fine now, just tested.

thanks for fixing this. :100:

**Comment by ned-martin** [comment]
There is however an annoying new "feature" that is present now. Doing anything to the tabs causes the expanded tab bar to shrink again.

For example, mouse over shrunk tab bar to expand it. Then click the "x" to close a tab. The tab bar shrinks again. Dragging tabs, rearranging tabs, closing tabs using keyboard shortcuts, etc. all cause the tab bar to shrink again.

**Comment by piroor** [comment]
The commit 5913bf1f86e3f054005b86b2a80d9217319c9d7a should fix the problem: https://github.com/piroor/treestyletab/issues/942#issuecomment-143528517

@ned-martin please report another issue as a new issue, instead of an extra comment of already closed issue, because such comments are hard to be tracked...
