### ISSUE TITLE
Tab bar completely broken in Firefox 42b1

### ISSUE THREAD

**Issue by disastranagant** [piroor/treestyletab#944]
My tab bar isn't updating at all since this update.

**Comment by KipperK** [comment]
The latest nightly has this fixed for me: http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by piroor** [comment]
Is this already fixed on the master/HEAD? (You can try the development build: http://piro.sakura.ne.jp/xul/xpi/nightly/ ) Then, please close this. I hope to concentrate to fix unsolved bugs.

**Comment by vtdmhd** [comment]
only "Default" theme is visible in Preferences and "Tree twisties"can only be set to "None"
Other things seem to work

**Comment by piroor** [comment]
@vtdmhd The commit b607f36 should fix it.

**Comment by disastranagant** [comment]
looks like the nightly worked
