### ISSUE TITLE
Firefox v44 (nightly) audio-activity/ mute icon bleeds out of pinned tabs

### ISSUE THREAD

**Issue by Happy-Dude** [piroor/treestyletab#945]
In the latest Firefox nightly, Mozilla has an icon next to tabs with which we can see that there is (HTML5) audio from the tab and that we can click to mute it. 

However, for pinned tabs, the icon shows up besides the favicon, making both icons bleed to the pinned-areas of the tabs to the side of it. See image below:

<img width="50" alt="screen shot 2015-09-25 at 11 14 06 am" src="https://cloud.githubusercontent.com/assets/1098725/10105845/9b473fb8-6376-11e5-9af7-f9bef9afe5b2.png">

The way Firefox (with TreeStyleTabs disabled is like the following) handles this is by making the audio icon smaller and at the corner of the tab:
<img width="75" alt="screen shot 2015-09-25 at 11 20 52 am" src="https://cloud.githubusercontent.com/assets/1098725/10105966/9284bb0c-6377-11e5-96dc-e8a920b9d593.png">

Let me know if I can provide any more information to help fix this issue :) !

**Comment by piroor** [comment]
7fe5a517f70b89a7998c58b48e4057ea7ceb0515
06fb2d4f2f07d34a2a26176af7e4f34b79f7a740
3a3d0945c71b63aa0a69237ccc0378b46cae57c1
These commits should fix this issue. Please try the development build: http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by Happy-Dude** [comment]
@piroor -- it's not perfect, but definitely better than the previous situation. (The hover-over circle on the volume icon still bleeds a bit over the top.)

<img width="55" alt="screen shot 2015-10-03 at 9 49 32 am" src="https://cloud.githubusercontent.com/assets/1098725/10263226/11ea6012-69b4-11e5-9c6a-14eacdd2405b.png">

**Comment by piroor** [comment]
Which platform, which theme (skin) of TST itself?

**Comment by Happy-Dude** [comment]
Mac OS X, mixed theme.

**Comment by Happy-Dude** [comment]
27d9164 and e2aaae0 fixed this issue, closing :)
