### ISSUE TITLE
Autoshrink shrinks when closing, moving, etc. tab

### ISSUE THREAD

**Issue by ned-martin** [piroor/treestyletab#946]
Fairly minor issue, but an annoying new "feature" that is present now. Doing anything to the tabs causes the expanded tab bar to shrink again.

For example, mouse over shrunk tab bar to expand it. Then click the "x" to close a tab. The tab bar shrinks again. Dragging tabs, rearranging tabs, closing tabs using keyboard shortcuts, etc. all cause the tab bar to shrink again.

**Comment by piroor** [comment]
How about TST 04b06ef08439c25a528040aa907b3b2694b366d0 (or later)? http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by ned-martin** [comment]
Cool, seems to stay open now. It is still occasionally closing but I haven't worked out a consistent pattern to when it does yet.

**Comment by piroor** [comment]
Currently I cannot reproduce this issue with TST 5111cf446bf2b0abd2d7db406a5ce2119abdf4c4 on Nightly 45.0a1. If you still see the issue, could you describe detailed steps to reproduce from scratch (with new clean profile)? You can start Firefox with new blank profile with the command line option `-profile` like: `firefox.exe -profile c:\path\to\blank\directory`

**Comment by ned-martin** [comment]
Unable to replicate.

I think it is fixed.

Thanks :)

**Comment by piroor** [comment]
Thank you for confirmation.
