### ISSUE TITLE
New tabs open, but do not have a visible tab in Firefox 42.0b1

### ISSUE THREAD

**Issue by bz922x** [piroor/treestyletab#947]
In Firefox 42.0b1 on Windows 10 Home, opening a new tab (control T, click the + on the tab bar, or File>New Tab) opens the tab, but the tab list displayed by Tree Style Tab does not add the new tab. Tab navigation using ctrl-tab and ctrl-shift-tab works, but the tab does not display in the tab bar.

This is such a fundamental break, that I am not sure what information would assist in debugging, so please ask if there is additional information that would be of use.

**Comment by piroor** [comment]
Is this already fixed on the master/HEAD? (You can try the development build: http://piro.sakura.ne.jp/xul/xpi/nightly/ ) Then, please close this. I hope to concentrate to fix unsolved bugs.

**Comment by piroor** [comment]
Firefox 42.0b1 + TST 04b06ef08439c25a528040aa907b3b2694b366d0 seem to work for me.

**Comment by bz922x** [comment]
Well, ... yes and no. The nightly build fixed the fundamental break. Yea!! Thank you.

But, it uncovers a more subtle interaction. When add-ons X-Notifier (3.5.14) and TreeStyleTab are both enabled, opening a child tab (middle click or control click) will open as an independent tab instead of a child tab. I'll report this interaction to X-Notifier as well.

So thank you for the fix. If I find out more on the X-Notifier interaction I'll post again.
Should I close this issue and open a new bug report for the X-Notifier interaction?

**Comment by piroor** [comment]
I've tried X-Notifier with Gmail, but ctrl-click on a mail opens new child tab as I expected. Could you explain more details how to reproduce the problem?

**Comment by bz922x** [comment]
And updating to the latest X-Notifier clears the issue. Since the old X-Notifier and new X-Notifier seem to claim the same version numbers, I am completely lost. But with the problem fixed, I propose to declare victory and leave.

**Comment by piroor** [comment]
Don't worry!
