### ISSUE TITLE
Second windows autoshrink starts with "Auto hide tab bar" unticked

### ISSUE THREAD

**Issue by ned-martin** [piroor/treestyletab#948]
I use "Session Manager" to auto-open multiple windows. I have TST set to auto-shrink. In the first window to open it works, but in all other windows, it is not shrunk and it has "Auto hide tab bar" unticked. I simply tick "Auto hide tab bar" and it starts to work again.

Seems to happen whenever second windows open even if it's not Session Manager that has done it, but I haven't tried with it uninstalled.

Has happened on all recent versions of FF and TST.

**Comment by piroor** [comment]
I've tried with TST development build on Firefox 41 without Session Manager, with three windows, but all windows are restarted with activated "auto hide tab bar" feature. Is this a Session Manager addon specific issue?

**Comment by ned-martin** [comment]
I did some further testing.

It only happens when I have the Keefox plugin 1.5.3 enabled.

https://addons.mozilla.org/en-US/firefox/addon/keefox/?src=external-kforg-download

**Comment by piroor** [comment]
Hmm, I've tested with following steps but the problem still doesn't happen for me.

 1. Start Firefox 41.0.2.
 2. Install Keefox 1.5.3, User Agent Switcher 0.7.3.1, Session Manager 0.8.1.8, and Tree Style Tab latest development build (5111cf446bf2b0abd2d7db406a5ce2119abdf4c4)
 3. Configure Firefox to start with last tabs and windows.
 4. Click and turn on the item "auto hide tab bar" in the tab bar's context menu. Then the tab bar becomes shrunken.
 5. Open new window.
 6. Exit Firefox.
 7. Start Firefox again.

Then, all windows are restored with shrunken tab bar for me. And, when I open the context menu on the tab bar, the item "auto hide tab bar" is checked on both windows. Any other missing condition to reproduce?

**Comment by ned-martin** [comment]
No, just installing Keefox and User Agent Switcher causes it for me, with all other extentions disabled, in multiple profiles. I have not tried again with any newer dev. builds so perhaps it is fixed? I will update my versions of everything later and see if it still occurs.

**Comment by piroor** [comment]
I didn't research but any exception raised from addons' initialization process (including TST) can cause this issue by their installation order. Anyway, recent commits on TST about "auto hide" feature can affect to this problem.

**Comment by ned-martin** [comment]
I did not reinstall User Agent Switcher to test (the combination seems too obscure), however I have not had this problem again.
