### ISSUE TITLE
Whole "tree" of tabs detaches and opens in new window

### ISSUE THREAD

**Issue by ned-martin** [piroor/treestyletab#949]
I don't know how to report this one... and it may not be TST at all...

Every so often a whole "tree" of tabs will just magically detach from the tab bar and open themselves in a new window. I can not figure out what causes it but I don't think I am clicking anywhere at the time.

Have had this problem for several versions of TST and FF now.

**Comment by SlimeQ** [comment]
this sounds very similar to an issue I've been having. randomly a tab will get stuck to my cursor as i pass over it, causing a new window to be created on my next click. I'd imagine if the tab happened to be a parent, its children would come with as well. I'm on i3wm on Ubuntu 14.04

**Comment by piroor** [comment]
It is a feature of TST itself: dragging a parent tab and dropping it at outside of the tab bar moves the tree of tabs belonging to the dragged tab from the window to a new window. So, if you saw it even if you don't want to do drag-and-drop, then it is possibly caused by slowing down of your system. On a slow system, a generic operation can be recognized as a drag-and-drop operation: pressing the left mouse button down on a parent tab, releasing the button, and moving the mouse cursor out from the tab bar area without any pressed button.

**Comment by ned-martin** [comment]
I think it's a compatibility issue with either Classic Theme Restorer or Firebug... but unsure how to test this further.

I do not think it is related to accidentally dragging and dropping, or the system being slow etc.

**Comment by piroor** [comment]
Or, TST moves whole tree to a new window for the command "Move to New Window" in the context menu on a parent tab. Any command or shortcut provided by thoese addons?

**Comment by SlimeQ** [comment]
i don't have classic theme restorer but i do have firebug, that might be worth looking into

**Comment by ned-martin** [comment]
I realise this isn't very useful for troubleshooting... but it appears to happen to me "randomly". As far as I can tell, I have not typed anything specific, and I haven't done anything in particular with the mouse. I don't believe I've recently moused over the tab or clicked on a tab or anything like that. I will let you know if I can figure out a pattern in it, but I can't so far.

**Comment by ned-martin** [comment]
A whole tree just detached on me. I had moused over a link in the middle of a page at the time, but had not clicked on it. As soon as I moved the mouse, the tree detached itself into a new window. The mouse was nowhere near the tab bar, and I wasn't using any keyboard keys. I hadn't actually clicked the mouse button at all - was just moving it.

All very confusing.

**Comment by marrak** [comment]
I have the same problem after upgrade to newest version.
I noticed that it detaches tab after:
refresh tab and then click left mouse button or press mouse scroll button
Probably it does not affects every websites but I get this error e.g. for:
http://liveonsat.com/daily.php?start_dd=11&start_mm=10&start_yyyy=2015&end_dd=11&end_mm=10&end_yyyy=2015
I've installed 0.15.2015030601.1-signed and there is no problem, works well.

**Comment by piroor** [comment]
Do you activate the "auto hide tab bar" feature? If a link which will be covered under automatically shown tab bar is clicked, it is possibly handled as a click on a tab automatically shown. Hmm, but https://github.com/piroor/treestyletab/issues/949#issuecomment-145844409 seems saying that my guess is not true...

**Comment by marrak** [comment]
Yep, I have tab bar hidding enabled.

**Comment by marrak** [comment]
@piroor Any update on this issue? It's more important since march 15 version does not work with latest FF :/ (UI layout broken)
Do you need more info to reproduce? Or you have more important work to do or no time...?
I can add that I use treestyletab with right placed tabs - maybe it is important(?)
Thanks for update :)

**Comment by ned-martin** [comment]
My tabs are left-placed. I am still unable to reliably replicate this issue. It happens to me regularly, but I cannot tell you what steps cause it. It seems random.

**Comment by alexander121** [comment]
The tabs of firefox when being dragged are opened in a new window.

That must be the problem.

Solution :
Disable detach and tear off tab Add On 
https://addons.mozilla.org/el/firefox/addon/bug489729-disable-detach-and-t/

**Comment by piroor** [comment]
I think #663 is caused by same reason.

**Comment by ned-martin** [comment]
Possibly, however I have had the tabs detach into a new window when I have not clicked the mouse at all (though usually it does happen on a click)

**Comment by ned-martin** [comment]
Just happened to me. I hit ctrl+t to get a new tab, and instead the current tab detached and opened in a new window. I did not click anywhere at the time.

This is what was in the browser console at the time:

```
15:27:10.134 TypeError: aTab.__treestyletab__contentBridge is undefined 1 autoHide.js:458:3

15:27:11.768 TypeError: aTabBrowser.tabContainer is undefined 1 base.js:910:1

15:27:12.309 TypeError: b.mTabContainer is undefined 1 browser.js:5951:7

tabview assert: should already be linked
TabItems_update@chrome://browser/content/tabview.js:5670:7
TabItems_init/this._eventListeners.attrModified@chrome://browser/content/tabview.js:5549:9
_tabAttrModified@chrome://browser/content/tabbrowser.xml:1305:11
set__visuallySelected@chrome://browser/content/tabbrowser.xml:5926:11
moveTabTo@chrome://browser/content/tabbrowser.xml:2898:13
TSTBrowser_onTabOpen@resource://treestyletab-modules/browser.js:3210:5
TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2895:1
addTab@chrome://tabmixplus/content/changecode.js line 179 > eval:156:92
TMP_BrowserOpenTab@chrome://tabmixplus/content/changecode.js line 179 > eval:64:17
BrowserOpenNewTabOrWindow@chrome://tabmixplus/content/changecode.js line 179 > eval:5:5
oncommand@chrome://browser/content/browser.xul:1:1
```

**Comment by ned-martin** [comment]
I also get ```16:43:59.594 TST.ownerToolbar is null 1 browserUIShowHideObserver.js:170:0``` and the new tab is created in the existing browser window. It is not created in the new window with the detached tabs. The new window is however the active window.

**Comment by piroor** [comment]
Is this Tab Mix Plus specific issue? Could you confirm that the problem appears even if you disable TMP?

**Comment by ned-martin** [comment]
It just happened then with TMP disabled.

**Comment by marrak** [comment]
I investigated this problem by reverting selected commits and trying generated on my device xpi file.
The problem was intruduced by this commit: 
SHA-1: 445ebbcf35d463059b00ec505886ee7def27b826
* Update visibility of tab bar by status change of related elements more robustly #848

I hope it helps you to fix this problem. If not I will try to prepare patch working well on latest version.

**Comment by marrak** [comment]
Temporaory workaround for this bug (tested by me:D )
in file modules/browserUIShowHideObserver.js:139
replace:
target.__treestyletab_mutationObserver_lastState = this.serializeBoxState(target);
with:
this.lastSize = this.serializeBoxSize();
and it is working :)

I guess I broke sth (not so important I hope) so please sb from the treestyletab team to look at it and prepare better fix :)

**Comment by piroor** [comment]
I've added some codes to output debug information. Could you try it and report the result?

Steps to report:

 1. Install the latest development build of TST from http://piro.sakura.ne.jp/xul/xpi/nightly/
 2. Go to about:config.
 3. Set `extensions.treestyletab.debug.browserUIShowHideObserver` to `true`.
 4. Open the browser console by Ctrl-Shift-J.
 5. Activate only the "Logging" button and deactivate all others.
 6. Click the "Clear" button.
 7. Reproduce the problem.
 8. Copy all logs in the console and paste it to here.

And, this latest development build includes a change which possibly affect to the workaround https://github.com/piroor/treestyletab/issues/949#issuecomment-181506148 
It will help my debugging, if you post logs for both cases: with and without the workaround.

**Comment by ned-martin** [comment]
I have installed that and done as you say. I will let you know when/if the tabs detach. I have no way of making it happen so I just have to wait. It sometimes takes a while and sometimes it happens heaps.

**Comment by piroor** [comment]
Thanks. If you have too many logs, please post last (recent) 200 lines.

**Comment by marrak** [comment]
I'm unable to reproduce the problem on this nightly version :) 
Debug log - while I was trying to reproduce the same as earlier (now no problem):
`[treestyletab:browserUIShowHideObserver] onAttributeModified window#main-window. / window#main-window. / width, null => 1366
[treestyletab:browserUIShowHideObserver]  => skip modification with no state change
[treestyletab:browserUIShowHideObserver] onAttributeModified window#main-window. / window#main-window. / height, null => 768
[treestyletab:browserUIShowHideObserver]  => skip modification with no state change`

BTW. I noticed that this version has another problem - if I open many bookmarks they are opening in one group. Is it intentional?

**Comment by ned-martin** [comment]
So far I have not had the problem.

**Comment by piroor** [comment]
> BTW. I noticed that this version has another problem - if I open many bookmarks they are opening in one group. Is it intentional?

Could you describe this with details or screenshots? It may be a regression I didn't know.

**Comment by marrak** [comment]
1. Several bookmarks in one directory added
2. Open all in tabs
3. On earlier versions every bookmark is open in new tab, not grouped, not on separate tree
4. Now bookmarks open in one group (tree)
Screenshot: http://i65.tinypic.com/2nrfyhy.jpg

**Comment by piroor** [comment]
Thanks. Could you see the value of the "Parent tab" field in the properties dialog for all bookmarks in the folder? If all following bookmarks have the title of the first bookmark in the folder as their "Parent tab", your old result is correct and the current is wrong. However, if all bookmarks in the folder have "(nothing)" as their "Parent tab", then they should be opened as grouped tabs under a dummy tab (current result is correct and old result is wrong.)

**Comment by marrak** [comment]
OK. I have (nothing). So if it is now correct - what should I change to open all bookmarks in separate tabs (not grouped)?
BTW. In TST preferences I have in 'New tabs' -> open as separate tabs (default Fireox)

**Comment by piroor** [comment]
>  BTW. In TST preferences I have in 'New tabs' -> open as separate tabs (default Fireox) selected.

Thanks. Then they should be opened separate tabs. Sorry I misunderstood your report. Could you collect debug log? Steps:

 1. Go to about:config.
 2. Turn `extensions.treestyletab.debug.bookmark` to `true`.
 3. Open the browser console (Ctrl-Shift-J) and click "Clear".
 4. Deactivate all buttons except the "Logging".
 5. Open bookmarks from a folder.

**Comment by piroor** [comment]
OK, I've realized what causes the problem. The commit ea99c3c should fix it.

**Comment by marrak** [comment]
Checked nightly version - works great! Thanks.
