### ISSUE TITLE
Fullscreen html5 content apptabs half visible

### ISSUE THREAD

**Issue by tbs** [piroor/treestyletab#950]
This problem is back it seems:

![html5 fullscreen](https://cloud.githubusercontent.com/assets/768954/10192601/d7f2779e-
6753-11e5-8c9f-e434ef856a90.png) ![html5 fullscreen](http://ultraimg.com/images/2015-09-30_09-13-58.png)

(screenshot from Youtube top right corner)

Windows 10 (8,7,any) + Nighly + [TST nightly](http://piro.sakura.ne.jp/xul/xpi/nightly/).

To reproduce is simple, just turn some tab(s) to apptab, open a html5 content (ie. video players) in fullscreen mode and voilà.

**Comment by piroor** [comment]
Confirmed on Ubuntu.

**Comment by piroor** [comment]
The commit 20ada7e5d8fc5b11df7ce70bdd4f77ee335fde6b fixes this issue on Ubuntu. Could you try the development build on your Windows 10?

**Comment by tbs** [comment]
Problem solved. Thanks for the new xpi build piroor.
