### ISSUE TITLE
autohide goes crazy when two windows are open

### ISSUE THREAD

**Issue by SlimeQ** [piroor/treestyletab#951]
when two firefox windows are open, autohide seems to break on one of the windows. fullscreening youtube after this break seems to cause the same issue mentioned in  #943

**Comment by piroor** [comment]
The referenced issue #943 seems to be fixed by recent changes. Is this also?

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
