### ISSUE TITLE
Open a new tab '+' bar disappeared

### ISSUE THREAD

**Issue by mr-brunes** [piroor/treestyletab#954]
Hi

For some reason the open a new tab bar with a "+" sign (at the bottom of all the tabs) has gone.
Any idea where it went? I can't see any option that is related in FF or TST.

**Comment by Sublyminal29** [comment]
Can second that, the + new tab is completely gone fix it please.

**Comment by piroor** [comment]
Could you describe versions of TST and Firefox? And, the issue you saw is possibly already fixed on the latest development build. Could you try it? http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by mr-brunes** [comment]
Hi
I was using TST = 0.15.20150902901, FF 41.0.2.
Then I tried nightly 0.151.2015102700a004307 but it made no difference.

**Comment by piroor** [comment]
Any other tabbar-related addons?

**Comment by mr-brunes** [comment]
Nope. I disabled all other extensions and the problem remained. However another instance of FF with TST and similar plugins etc. displays fine.

**Comment by piroor** [comment]
Hmm. Could you attach a screenshot? And, if possible, could you inspect that what CSS rule hides the button, by the browser toolbox? https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox

**Comment by samilizzy** [comment]
I had the same problem. It turns out that it's firefox that's not working, not Tree Style Tab. See here for solution: https://support.mozilla.org/en-US/questions/1014810

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
