### ISSUE TITLE
Session is lost on FF 44 (nightly)

### ISSUE THREAD

**Issue by hjri** [piroor/treestyletab#955]
After restarting browser only one tab is shown, blank\home tab. `about:sessionrestore` shows nothing. Session manager sometimes helps but barely works (most tabs show up blank)

**Comment by ramLlama** [comment]
This happens to me as well. As stated in #956, disabling TST fixes both this issue as well as #956.

**Comment by hjri** [comment]
works in nightly version of TST

**Comment by piroor** [comment]
Thanks, I close this.
