### ISSUE TITLE
Firefox menu doesn't work on FF 44 (nightly)

### ISSUE THREAD

**Issue by hjri** [piroor/treestyletab#956]
App menu (burger menu, the one in the upper right corner) simply doesn't work when TST is active. Also customization doesn't work either. Disabling TST helps.

**Comment by sovereignsoftware** [comment]
Confirming this happens to me too. Customize and hamberger menu don't work. Disabling TST fixes the problem.

**Comment by ramLlama** [comment]
This happens to me as well, along with #955. Disabling TST fixes both.

**Comment by tushar-suresh** [comment]
Can confirm that this happens on 44.0a1 . The bookmarks toolbar also disappears at start up but can get it back by disabling toolbar and reenabling it.

Disabling TST fixes these problems.

**Comment by piroor** [comment]
The latest development build seems fine for me. Could you try it?
http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by hjri** [comment]
works in nightly version of TST

**Comment by piroor** [comment]
Thanks. I close this.

**Comment by wsmwk** [comment]
I experienced this and https://github.com/piroor/treestyletab/issues/955 aka https://bugzilla.mozilla.org/show_bug.cgi?id=1215747

FWIW the Firefox regression range is 2015-10-07 works, 2015-10-08 fails.
