### ISSUE TITLE
When going to fullscreen and coming back, sidebar overlaps menu

### ISSUE THREAD

**Issue by SlugFiller** [piroor/treestyletab#957]
If going to fullscreen, e.g. by watching a YouTube video, and then returning to windowed mode, while having enough tabs to scroll, the top of the tab sidebar overlaps the address bar and top menu.

This appears to be related to HTML5 video fullscreen, and doesn't happen when simply pressing F11. Resizing the window, or maximizing and restoring, fixes the problem.

Tested with Nightly 44.0a1 (2015-10-14), commit 8185bafaae584c1b7f5faeee873c0e231e621a10

**Comment by althafh** [comment]
Experiencing the same problem.

**Comment by specious** [comment]
Check issue #941 - I think this has been solved.

**Comment by SlugFiller** [comment]
@specious Commit 8185bafaae584c1b7f5faeee873c0e231e621a10 is from 18 days ago. The last post on the issue you linked is from 30 days ago. So no, it's impossible for it to have been solved by that time.

**Comment by piroor** [comment]
I couldn't reproduce this on Ubuntu, Nightly 45.0a1, TST ee0937ee43f371818f2eab2384d56e74f3b2bab3. Any screenshot?

**Comment by SlugFiller** [comment]
Tested on Nightly 44.0a1 (2015-10-28), with commit d911e243c60f499cf04cb2ddc5f30d78ede4e0f9 on Windows. Image below (Notice the upper left corner):
![Image](http://i.imgur.com/zyS3TfI.png)

**Comment by piroor** [comment]
Thanks. Confirmed on my Windows PC, and the commit 8b2af7ce6fb6ea1b51776d698d19ff8e930676b7 fixes this issue for me.

**Comment by SlugFiller** [comment]
Confirmed fixed
