### ISSUE TITLE
Spammy dump call in base.js

### ISSUE THREAD

**Issue by heftig** [piroor/treestyletab#958]
The `new child tab is requested` dump at https://github.com/piroor/treestyletab/blob/master/modules/base.js#L1511 can get rather spammy. Could you please wrap it in a `if (DEBUG)`?

**Comment by piroor** [comment]
Thanks. By recent commits, some `dump()` unwrapped lazily are now deactivated by secret preferences like `extensionsl.treestyletab.debug.base'. They all `dump()`s are disabled by default.
