### ISSUE TITLE
Feature request: copy all URLs of a tree of tabs

### ISSUE THREAD

**Issue by mindrones** [piroor/treestyletab#959]
It would be nice to be able to copy URLs of all tabs of a (sub) tree.

Example use case:

- I'm in a ecommerce page listing all products of a certain category
- I open all interesting links in a new tab, so that the current tab becomes the root of a sub tree
- I inspect all sub pages, eventually closing some tabs
- when I'm done, I'd like to mail all links of the sub tree tabs
- it would be nice to do: right click, "Copy all URLs of this tree" or similar

**Comment by piroor** [comment]
My another addon "Multiple Tab Handler" provides similar feature. Try it please!
https://addons.mozilla.org/en-US/firefox/addon/multiple-tab-handler/

**Comment by mindrones** [comment]
Ah nice, didn't know about it.
I've installed it and tried but it doesn't put the list of URIs in my clipboard. I'll report this issue in the `multipletab` repo when time will permit. 
Thanks!
