### ISSUE TITLE
Context search doesn't work with e10s and TST

### ISSUE THREAD

**Issue by hjri** [piroor/treestyletab#961]
This bug has been around for quite a lot of time.

1. Enable e10s (Electrolysis) in Firefox Nightly (not sure if it is present in beta and aurora)
2. Open any tab, select any text in page
3. Open context menu -> seach "<the text you selected>" in <your search engine>"
4. Nothing happens.

Disabling TST or e10s helps.

**Comment by hjri** [comment]
And IIRC console shows error similar to one in #884

**Comment by piroor** [comment]
The commit ee0937ee43f371818f2eab2384d56e74f3b2bab3 should fix this. However, for the web search toolbar item I still have to do something.

**Comment by piroor** [comment]
I close this.
