### ISSUE TITLE
Seperators, Tab Groups

### ISSUE THREAD

**Issue by muratkarakus7** [piroor/treestyletab#962]
Could you please support virtual grouping of tabs under a special separator. For instance, i want to create a separator "social media" and drag all related tabs under it so that i can easily fold it off.

**Comment by piroor** [comment]
How about `about:treestyletab-group` tabs or Firefox's tab groups feature?

Anyway TST is not designed to use flat tabs with simple groups. I think other vertical tab addons designed for the case should help you.
