### ISSUE TITLE
Persist tree structure when exporting bookmarks

### ISSUE THREAD

**Issue by devilj** [piroor/treestyletab#963]
first of all, let me thank you for this wonderful add-on - one of the very few reasons i'm still using FF. i'm a big fan of keeping things organized. being able to capture the structure of of work i've been doing as structure of open tabs in an open window or in saved bookmarks is really helpful. however, there is no way to export this information when exporting bookmarks using regular FF export. i believe this is due to how this information is stored.
so, the question is - is there any way to generate html file that would show the tree structure? either using some post-export transformation on what regular export generates or through additional TST menu item.

**Comment by piroor** [comment]
TST stores its custom information as annotations, so we have to export annotations to HTML and import them.

Related information: [416611 – support importing tags from bookmarks.html exports (del.icio.us and others)](https://bugzilla.mozilla.org/show_bug.cgi?id=416611 "416611 – support importing tags from bookmarks.html exports (del.icio.us and others)") By this bug Firefox 43 and later imports tags from exported HTML. I think that patching for `exportToFile` and `importFromFile` (or other methods) defined at http://mxr.mozilla.org/mozilla-central/source/toolkit/components/places/BookmarkHTMLUtils.jsm can solve this issue.

**Comment by piroor** [comment]
However currently I have no time to do it. I'm waiting any pull request!

**Comment by devilj** [comment]
are you saying that API for it should be available with FF 43, but you still need to add support for the feature?

as for PR - i'd be glad to do it myself, but currently i don't have bandwidth to learn a completely new area such as writing FF plugins.

**Comment by piroor** [comment]
TST still needs some more codes to export/import metadata of bookmarks, because  Firefox 43 still not support exporting/importing of "annotations" stored by addons. The bug 416611 is just for "tags".

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
