### ISSUE TITLE
numbered tabs

### ISSUE THREAD

**Issue by shanemikel** [piroor/treestyletab#965]
It would be a useful addition to have an option for numbered tabs.  This would be helpful for people that use extensions like pentadactyl for total keyboard navigation.

**Comment by piroor** [comment]
I heard that the addon Vimperator had an feature to show index for each tab (or UI element) to focus on it directly. Pentadactyl doesn't have it?

**Comment by piroor** [comment]
Anyway, because it is not a feature related to "tree", I won't implement it to TST. Sorry.

**Comment by shanemikel** [comment]
Oh, it looks like the feature is there.. my bad.
