### ISSUE TITLE
Error is logged at browser startup

### ISSUE THREAD

**Issue by asamuzaK** [piroor/treestyletab#966]
log message in browser console:
treestyletab: doPatching: [object XULElement]._setEffectAllowedForDataTransfer is missing! utils.js:329:0

**Comment by asamuzaK** [comment]
forgot to note the environment
WIn10 64 + Firefox Dev Edition (44a2)

**Comment by piroor** [comment]
Which version of Tree Style Tab?

**Comment by asamuzaK** [comment]
0.151.2015110200a161605

**Comment by piroor** [comment]
Thanks. I've confirmed the error message and it is triggered by a change introduced by the bug:

 * [1207594 – Drop a link on tab bar doesn't work](https://bugzilla.mozilla.org/show_bug.cgi?id=1207594 "1207594 – Drop a link on tab bar doesn't work")
 * [mozilla-central: changeset 269705:dcd16953417b](http://hg.mozilla.org/mozilla-central/rev/dcd16953417b "mozilla-central: changeset 269705:dcd16953417b")

**Comment by piroor** [comment]
The error should go away by these commits:

 * 1029b40e0970e934fa20f217197127e2713bc72e
 * 0fbea3cfbf01944313c85c2066418eb3c8bfefca
 * e8941963d4381fe9e6aa49e59d264a6f9e5471a7
 * b417c4542593db62fbe01f1497a485c9cfd160cd
