### ISSUE TITLE
Enter key in location field ignored

### ISSUE THREAD

**Issue by paxe** [piroor/treestyletab#967]
I have had to disable this because I can no longer go to URLs entered, although I can still follow links by clicking on existing pages. I don't even see what this has to do with your addon, and it feels like a conflict with something else, but I do observe that disabling treestyletab fixes the problem for me.

**Comment by piroor** [comment]
Too less information...

 * Version of Firefox (38.x, 41.x, Nightly, etc.)
 * Version of Tree Style Tab (latest on AMO, latest on piro.sakura.ne.jp, etc.)
 * Any other tab-related addon like Tab Mix Plus?
 * Does this happen when all other addons (except TST) are disabled?
 * Does this still happen with the latest development build of TST? http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by paxe** [comment]
This was happening to me with latest AMO version of Tree Style Tab, on at least latest Debian (Iceweasel 38.4) and Windows (Firefox 42.0), and going back a few versions as well. However in beating on this off and on for a few days, I was never able to isolate the problem to just Tree Style Tab... I was also never able to disable all other addons because at some point the addons menu would fail to bring up the addons window, so then it was gone for good (until returning to a clean install).

Yes, I have Tab Mix Plus and even a few other tab-related addons, but I haven't found reason to blame any of them.

I was close to giving up this just before I looked at your list of questions again. I hadn't yet tried the latest development build of TST, so now I have, and that appears to have fixed the problem! As a bonus, I also am unable to repeat the misery of the disappearing addons window.

**Comment by piroor** [comment]
You can start Firefox with a new clean profile with the `-profile` option, like:

~~~
$ mkdir /tmp/fxprofile
$ /usr/bin/firefox -profile /tmp/fxprofile
~~~

It will help you to find out what causes the problem.

**Comment by piroor** [comment]
If your Firefox is always running, then you need to add another option `-no-remote` to start another process of Firefox, like: `/usr/bin/firefox -profile /tmp/fxprofile -no-remote`

**Comment by paxe** [comment]
Thanks for the suggestions, but I do know enough to make sure FF isn't running when re-testing with different addons. Also, as I may not have made clear before, I was never able to repeat the problem when starting clean, and then installing TST and other addons... only by starting with my bloated config. I'm satisfied  that TST is (likely) the main culprit, but it does seem to also need something else to make it go wonky. I'll let you know if I ever get some clue what that might be.
