### ISSUE TITLE
特定の状況下でタイトルバーが消える

### ISSUE THREAD

**Issue by tanakah** [piroor/treestyletab#968]
・Cyberfox 42 64bit （Firefox42でもバグがおこるのを確認）
・TSTはNightlyのtreestyletab.xpi 	04-Nov-2015 11:59 	を使用
・Tab Mix Plusは不使用

TSTオプションのFix position and width tab barがチェックされている時、ツールバーのハンバーガーボタンからCustmizeへ進み、Custmizeを終了させるとタイトルバーが消えるバグが発生します。Fix position and width tab barが未チェックだとこのバグは起こりません。

**Comment by piroor** [comment]
ありがとうございます。処理のタイミングが変わって問題が起こるようになっていました。 7ffc1f3 で直ったと思います。

**Comment by tanakah** [comment]
迅速な対応有難うございます。
こちらの環境でも問題なく動作するようになりました。
