### ISSUE TITLE
New tab bar '+' does not work with Firefox 42.0

### ISSUE THREAD

**Issue by afrie1** [piroor/treestyletab#969]
New tab bar '+' does not work with Firefox 42.0.

**Comment by piroor** [comment]
This doesn't happen on my environment:

 * Ubuntu
 * Firefox 42
 * TST b417c45 (available at http://piro.sakura.ne.jp/xul/xpi/nightly/ )

Any other tab-related addon like Tab Mix Plus?

**Comment by afrie1** [comment]
No I have no other tab-related addons. It has happened with an older version of Tree Style Tab.
Now I have tried your nightly build version and it worked - thank you.
