### ISSUE TITLE
New tab doesn't show up

### ISSUE THREAD

**Issue by mindrones** [piroor/treestyletab#970]
In the preferences, I clicked on `Auto Hide tab bar` and tabs got jammed:

![screen shot 2015-11-04 at 13 44 54](https://cloud.githubusercontent.com/assets/1309648/10938418/5c49f5b4-82fa-11e5-9e72-f8a7eb7d7c54.png)

then I got back to `Show tab bar always` but it didn't fix it, so I restarted Firefox.

Now I can see the tree area but now new tabs won't show up in the tree area, which makes this addon practically unusable as I can't see/move tabs.

This is what I get in the Browser console:

**Opening a new tab**

... by double clicking on the tree area.

```
TypeError: aWindow.mozRequestAnimationFrame is not a function animationManager.js:123:5
```
where `animationManager.js` is `view-source:resource://treestyletab-modules/lib/animationManager.js`

**Closing the same invisible tab**

... by pressing `Cmd-W`.

```
namedNodes.counter is null
TSTBrowser_initTabContentsOrder@resource://treestyletab-modules/browser.js:1210:5
TSTBrowser_updateInvertedTabContentsOrder/this.timers[key]<@resource://treestyletab-modules/browser.js:1326:6
setTimeout_timer@resource://gre/modules/Timer.jsm:30:5
 base.js:594:0
```
where `base.js` is `view-source:resource://treestyletab-modules/base.js`

**Closing a visible tab**

Same goes closing it with a middle click on the tab or using `Cmd-W`.

`TypeError: aTab.__treestyletab__contentBridge is undefined autoHide.js:431:3`

where `autoHide.js` is `view-source:resource://treestyletab-modules/autoHide.js`

----
Tree Style Tab 0.15.2015030601.1-signed
OS X Yosemite 10.10.5
Firefox 42.0

**Comment by piroor** [comment]
A new version is already released. See: https://addons.mozilla.org/ja/firefox/addon/tree-style-tab/versions/?page=1#version-0.15.20150902901

**Comment by mindrones** [comment]
Ah that's great! All is OK, including the annoying bookmarks bug, thanks a lot!
Btw, do you know why Firefox wasn't fetching this update?

**Comment by piroor** [comment]
Auto-update is probably disabled by the status "preliminary reviewed".
https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews#Preliminary_Review
However TST never passes the "full review" because there are dirty `eval()` hacks.

**Comment by mindrones** [comment]
OK. I'd like to help you with this wonderful addon, but the code base is huge. Hope I'll find some time to learn it a bit, thanks!
