### ISSUE TITLE
Multiple issues main/adressbar 

### ISSUE THREAD

**Issue by clareyboy** [piroor/treestyletab#971]
Tree-style - latest AMO 28september
Firefox Developer edition 44.0a2
disabled other add-ons / new profile

When enabled the main bar becomes bugged with the following results:
The hamburger 'open menu' doesn't work anymore.
Bookmarks toolbar I have placed next to the urlbar disappears.

Tree-style tab functions as normal.

**Comment by piroor** [comment]
Does this happen with the latest development build?: http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by clareyboy** [comment]
The problem is fixed in your nightly version.

**Comment by piroor** [comment]
OK, I close this.
