### ISSUE TITLE
TypeError: this.formatAccessKey is not a function is logged at browser startup

### ISSUE THREAD

**Issue by asamuzaK** [piroor/treestyletab#972]
Error seems to be related to Tree Style Tab.

TypeError: this.formatAccessKey is not a function
label-control_XBL_Constructor()	text.xml:62
BrowserUIShowHideObserver_onMutation/<()	browserUIShowHideObserver.js:85
forEach()	self-hosted:216
BrowserUIShowHideObserver_onMutation()	browserUIShowHideObserver.js:81
BrowserUIShowHideObserver_onInit/this.observer<()	browserUIShowHideObserver.js:62

Win10 64 + Firefox 44.0a2
Tree Style Tab 0.151.2015110400a115911

**Comment by piroor** [comment]
Thanks, d8f4a178738ed970f1174c6afaf3fa7d13359ac5 should fix this.
