### ISSUE TITLE
Auto shrink not working on Firefox 42

### ISSUE THREAD

**Issue by lgp171188** [piroor/treestyletab#974]
I use Firefox 42 on Ubuntu 15.10. When I configure the hiding behaviour to auto-shrink, I am unable to expand the tab bar by focussing on it or by holding Ctrl. At the same time, auto-hide works properly. Please let me know if you need any more information.

**Comment by piroor** [comment]
Does the problem still appear on the latest development build? http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by lgp171188** [comment]
Yay, it works with the latest nightly :)
