### ISSUE TITLE
BrowserSearch._loadSearch does not work

### ISSUE THREAD

**Issue by jeberger** [piroor/treestyletab#979]
There is a typo in `BrowserSearch._loadSearch`: [line 223 of windowHelper.js](https://github.com/piroor/treestyletab/blob/master/content/treestyletab/windowHelper.js#L223) should be:

```js
return this.__treestyletab__loadSearch.call(this, aSearchText, aUseNewTab, aPurpose);
```

**Comment by vohzi** [comment]
Yes I can confirm, just noticed that right-click "search with google" wasn't working anymore.

**Comment by piroor** [comment]
Sorry. Fixed by 7328221.

**Comment by vohzi** [comment]
I'm sorry I'm quite new to Github, but where can I find the updated .xpi ?

**Comment by piroor** [comment]
Available at http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by vohzi** [comment]
Thanks, it's fixed now :)
