### ISSUE TITLE
positioning of tab sidebar is wrong

### ISSUE THREAD

**Issue by themahnamahna** [piroor/treestyletab#980]
As you can see in the screenshot, the "sidebar" with the tree style tabs starts directly unter the windowmanager window instead of under the bookmark toolbar. 

Issue first occured with update to:
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0
currently using Tree Style Tab 0.16.2015110701

![tst1](https://cloud.githubusercontent.com/assets/15712738/11019390/82dc38cc-85f7-11e5-9a78-860400644de0.png)

regards
TheMahnaMahna

**Comment by piroor** [comment]
This doesn't happen on my Windows 7, Firefox 42. Any other condition to reproduce this? For example:

 * Other tab related addons
 * Full screen state
 * "Auto hide" state
 * Number of tabs

**Comment by themahnamahna** [comment]
Hm, after switching tab positions to "above" and back to "right" it seems to work correctly again. I will do some more tests and report back or close within the day, sorry

**Comment by andrebeat** [comment]
This is also happening to me on Firefox 44.0a2.

![sidebar](https://dl.dropboxusercontent.com/u/7018537/Screen%20Shot%202015-11-09%20at%2000.10.29.png).

**Comment by andrebeat** [comment]
081acb2 fixed this for me.
