### ISSUE TITLE
'Search Google for' no longer works

### ISSUE THREAD

**Issue by aembleton** [piroor/treestyletab#981]
I'm running Firefox 42.0 on Linux Mint.

When I select some text on a webpage and right-click on it and select 'Search Google for' nothing happens.  This was working a couple of days ago so I think it must be a recent fix.

If I disable Tree Style Tabs then the Search Google thing works.

**Comment by TheSweetLily** [comment]
It's fixed in the latest nightly. :) #979

**Comment by piroor** [comment]
A new version including this fix has been released (also on AMO). I close this.
