### ISSUE TITLE
[Firefox Dev & Nightly] New Bookmark Folder and Properties Broken (and other critical functionality repeatedly broken)

### ISSUE THREAD

**Issue by xeonx1** [piroor/treestyletab#982]
"New Bookmark Folder" and right click (bookmark/folder > "Properties" are still broken for Tree Style Tabs. This occurs only with Firefox Developer Edition and Firefox Nightly (at least with 64-bit versions of Dev and Nightly, probably 32-bit as well), and can't be reproduced with Firefox stable.

As seen in the below screenshot, these dialogs show up without any fields except Sort by Title checkbox.  This occurs for both the latest XPI release (v0.16.2015110801) and the latest from GitHub. 

![broken new bookmark folder and properties dialog for firefox dev and nightly](https://cloud.githubusercontent.com/assets/4053734/11027579/91a162d2-866b-11e5-96a6-2f1f6537cd6d.png)

Though the Add Bookmark (star dialog), at least, was finally fixed (for now) for Tree Style Tabs - after being broken continually for a year - the New Folder and Bookmark Properties dialog issues remain.

Even worse, a few days ago, after a Firefox and/or extension update, both Tree Style Tabs (latest XPI release) and Multiple Tab Handler broke critical functionality for Firefox Dev and Nightly 64-bit, resulting in Firefox no longer showing dialogs and drop-downs, including the Firefox main app (hamburger) menu, LastPass, Add Bookmark, New Bookmark folder, and even addon install dialogs. 

Though the last commit/release resolved some of that for Tree Style Tabs, other related issues remain for Tree Style Tabs, and even the latest in GitHub hasn't fixed the more critical issues for Multiple Tab Handler. See the related issue reported for Multiple Tab Handler (https://github.com/piroor/multipletab/issues/101).
____________________

The most recent temporary workaround for this in Tree Style Tab (and similarly in Multiple Tab Handler) is:
   Add "return;" after line 25 in \treestyletab\res\bookmarkMultipleTabs_bookmarkPropertiesOverlay.xul
____________________

The use of regex-based "patching" to extend dialogs like BookmarkPropertiesDialog has broken other core functionality for Tree Style Tabs for about a year, and off an on before that since 2011,  despite 10+ issue reports (https://github.com/piroor/treestyletab/issues?utf8=%E2%9C%93&q=bookmark+star), emails, reports in extension reviews, and even known commited workarounds in GitHub forks (https://github.com/piroor/treestyletab/compare/master...jryans:bookmarks-40#diff-a7f4aa525b98b1a229d5ebe3580fd374) (though even that workaround is no longer sufficient by itself). 

Considering this, and that Firefox and extension updates have resulted in even more critical issues occurring, even despite workarounds being applied, I would *highly suggest the following*:

1. Releasing an updated XPI ASAP with at least the above workaround, to restore core Firefox bookmark functionality and prevent another catastrophic breaking of Firefox
2. Making Add/Edit Bookmark dialog enhancements optional features that are disabled by default
3. Testing regularly with Firefox Dev and/or Nightly editions 64-bit
4. Finding a safer alternative to regex-based "patching" of dialogs like "BookmarkPropertiesDialog" (eg. injecting via DOM / inserting child elements instead)

____________________
My configuration:

I have Firefox Developer Edition 64-bit and a Windows 10 x64 PC, and confirmed that Tab Tree Style was the source of these issues, by reproducing the issues after disabling all other extensions and then seeing the issues resolved after disabling Tab Tree Style as well. I then did the same with Multiple Tab Handler to confirm the related (and even more severe) issues occurring with it.

**Comment by piroor** [comment]
The commit d295128e4a431a32cac4bf6724e511476cf0476e should fix this. It's not a workaround.

**Comment by xeonx1** [comment]
piroor,
Can you please provide a signed release of latest version from GIT (which has my fix patch / GIT pull request) for both Tree Style Tab and Multiple Tab Handler?
I just reverted back to using the latest release other than my patched GIT working copy, and the issue remains. I then switched to your unsigned nightly release, and was surprised to find the same issue still occurring with it. Anyone using Tree Style Tab with Multiple Tab Handler still has Firefox essentially completely broken, without the ability to add or even edit bookmarks.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
