### ISSUE TITLE
Toolbox minimize maximize close button located out of place

### ISSUE THREAD

**Issue by lgp171188** [piroor/treestyletab#983]
Firefox 42, OS X 10.10.5 and Tree Style Tab (nightly and the version released in addons.mozilla.org). Please see the screenshot attached.
<img width="1440" alt="screen shot 2015-11-09 at 1 20 09 pm" src="https://cloud.githubusercontent.com/assets/218870/11028460/c6dd6d8c-86e4-11e5-84a2-19122b42bf92.png">

**Comment by lgp171188** [comment]
The nightly available on 5 November 2015 worked fine and didn't have this issue.

**Comment by piroor** [comment]
Seems a regression from the commit a6eb66c21627719a7de61aca57211ef7cfcee2e1.

**Comment by piroor** [comment]
This should be fixed by 081acb238bde6a9098c72cff914a9bc3f4dcd91c.

**Comment by lgp171188** [comment]
Yes, the issue is fixed now :)

**Comment by andrebeat** [comment]
I can confirm that this is also fixed for me.

**Comment by piroor** [comment]
Thanks. I close this.
