### ISSUE TITLE
タブの閉じるボタンが楕円になる

### ISSUE THREAD

**Issue by tanakah** [piroor/treestyletab#984]
・Firefox42 64bitを使用
・TSTはNightlyのtreestyletab.xpi     09-Nov-2015 17:28 を使用
・Tab Mix Plusなどのタブ機能拡張アドオンは未使用

バグではないのかもしれないですが報告です。
タブの閉じるボタンが以前は円形だったものが楕円形になってます。
![ss](https://cloud.githubusercontent.com/assets/683605/11029823/ee95f01a-870c-11e5-9a1e-f10536dd67cc.png)

**Comment by piroor** [comment]
OS Xでタブバーの幅が16ピクセルに縮められてしまう問題の対処で幅ではなく高さを制限するようにスタイル指定を上書きしているのが原因ではないかと思います。
このアイコンの元々の高さまたは幅を指定しているCSSのルールの定義箇所を調べていただくことはできますでしょうか？（ブラウザツールボックスのInspectorで調べられます）

**Comment by tanakah** [comment]
自分が使っているOSも表記するべきでした。すみません。
Windows10 64bit版を使っています。

chrome://browser/content/browser.xulを開いてしばらくInspectorとにらめっこしてみましたが、どのアイコンが閉じるボタンとして使われているのかわかりませんでした。

**Comment by piroor** [comment]
とりあえず 38df1c2 でタブの閉じるボタンにはスタイル指定を適用しないようにしてみました。どうでしょうか。

**Comment by tanakah** [comment]
対応有難うございます。以前のようなスタイルに戻りました。

**Comment by tanakah** [comment]
Metalテーマでは未だに楕円形のままになっているのを確認しましたのでReopenしました。
![a](https://cloud.githubusercontent.com/assets/683605/11604621/6f1fe892-9b32-11e5-8c81-e129baeee213.png)

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
