### ISSUE TITLE
Missing Title Bar and shift down of the control buttons on OSX

### ISSUE THREAD

**Issue by digitalred** [piroor/treestyletab#986]
the title bar is completely missing or shifted down so that the red/yellowand green buttons in the upper left corner are not on top of the "Go Back Page" button.  I am on OSX 10.10.5, Firefox 42.0 and Tree Style Tabs 0.16.2015110801.  When I disable Tree Styles Tabs the title bar comes back and when I enable it, the menu bar disappears again.
![treetabs issues](https://cloud.githubusercontent.com/assets/15733149/11038464/292bb962-86d1-11e5-85a0-c4e10615b982.jpg)

**Comment by piroor** [comment]
Duplicated #983
