### ISSUE TITLE
Can't create new tabs in Firefox 42.0

### ISSUE THREAD

**Issue by minosniu** [piroor/treestyletab#987]
After upgrading to Firefox 42.0, I am no longer able to click the blank area for a new tab. It also fails to respond to "Cmd-t" to create a new tab.

* MacOS 10.10.5
* Firefox 42.0
* Addons: vimperator, easyDragToGo, FireGestures

**Comment by piroor** [comment]
I didn't test with addons you listed, but the commit e06d99d possibly fixes this if it is originated from same reason.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
