### ISSUE TITLE
New Tab or ctrl+t has no effect and sidebar button disappear on click to expand

### ISSUE THREAD

**Issue by ggaussling** [piroor/treestyletab#990]
New Tab or ctrl+t has no effect on firefox 42 with latest tree style tab 0.16.2015111001

**Comment by ggaussling** [comment]
Webmailcheck 3.1.3 is the culprit: http://web.de/

**Comment by ggaussling** [comment]
What keeps beeing disfunctional: If I click to cover the sidebar and then klick in the middle on the left stripe with the vertical slim button to re-expand the slider/sidebar, then the left slim stripe disappears, and I have to open a new tab to make the sidebar again visible. Sorry, I'm not a native speaker. I hope it is understandable what I mean.

**Comment by ggaussling** [comment]
https://lh3.googleusercontent.com/--WE1zp_-8JM/VkR5yUKapbI/AAAAAAAABHM/wA46-ZgFExA/s2048-Ic42/%25255BUNSET%25255D.png

https://lh3.googleusercontent.com/-M4oaB6Vbyuw/VkR59tWSRvI/AAAAAAAABHU/qwiXmuL81O8/s2048-Ic42/%25255BUNSET%25255D.png

**Comment by ggaussling** [comment]
There are duplicates of this bug.
web.de mailcheck 3.1.3
https://addons.mozilla.org/de/firefox/addon/webde-mailcheck/

**Comment by piroor** [comment]
After e06d99d problems around the new tab button don't happen on my environment.

**Comment by piroor** [comment]
1a1e609b9de68e6b9f417633abed1fb79a63cc75 should fix another problem https://github.com/piroor/treestyletab/issues/990#issuecomment-156080194

**Comment by ggaussling** [comment]
piroor, thank you very much! Are those patches applied in new binaries? Unfortunately I'm not a programmer and therefor don't want to patch and compile stuff myself.

**Comment by piroor** [comment]
See the comment https://github.com/piroor/treestyletab/issues/668#issuecomment-154328206

**Comment by ggaussling** [comment]
Thank you the nightly under http://piro.sakura.ne.jp/xul/xpi/nightly/ works great! One can install it in FF 42 by klick the 'allow' Butlon on Install-Tooltip. No abou:config tweaks necessary.
