### ISSUE TITLE
Bug: bookmark properties

### ISSUE THREAD

**Issue by sl5ne** [piroor/treestyletab#993]
In firefox 42 and TST 0.16.2015111001 the bookmark properties box is broken. Try right clicking a bookmark from favorties toolbar or side bar.

older version 0.16.2015110801 works.

**Comment by tbs** [comment]
+1 missing it very much.

**Comment by piroor** [comment]
Duplicated #989?

**Comment by tbs** [comment]
Yep, fixed.

Thank you.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.
