### ISSUE TITLE
[User Agent Switcher] in Second window TST Child Tabs isn't working when Firefox Restarts

### ISSUE THREAD

**Issue by toruyamaguchi** [piroor/treestyletab#995]
--in English--

TST child tabs isn't working correctly in second window when Firefox with multiple windows Restarts.
These child tabs change to Parent Tabs, so in second window All tabs are not tree after FF restarts.
But in first window tab tree maintain pre-restart condition correctly.

This issue occurs in Firefox 41 before and in 3 windows.

-Environment-
Firefox 42 (Release)
Tree Style Tab 0.16.2015111001
Windows 10 64bit

---

--in Japanese--

Firefoxを複数ウィンドウで利用しています。
再起動後、ウィンドウの2枚目移行のツリーが崩壊して階層がなくなり、全て親タブとなってしまいます。
このとき、1枚目のウィンドウに関してはツリーが再起動前と全く同じ状態で維持されています。

この現象は
・41以前のFirefoxでも確認済み
・ウィンドウが3枚のときも発生
です。

-利用環境-
Firefox 42 (Release)
ツリー型タブ 0.16.2015111001
Windows 10 64bit

**Comment by piroor** [comment]
以下の環境で問題が再現しませんでした。

 * Ubuntu, Firefox 42.0, TST 0ed972459b8509a4b1d71cf0d41a0360b0989221
 * Ubuntu, Nightly 45.0a1 2015-11-17, TST 0ed972459b8509a4b1d71cf0d41a0360b0989221

（TSTの最新開発版は http://piro.sakura.ne.jp/xul/xpi/nightly/ でダウンロードできます）

セッション周りの不具合は、他のアドオンとの衝突か、もしくはセッション情報そのものが壊れている可能性があります。
空フォルダを作成して `firefox.exe -profile c:\path\to\folder` といった要領でパスを指定するとクリーンな状態のFirefoxを起動できますので、そこから問題を再現できるか確認していただけますでしょうか？

**Comment by richardb64** [comment]
This sounds like the same problem as #260. It's still happening 100% of the time for me, on both Windows and Linux. It's almost become automatic for me to apply the workaround (close and reopen a tab, in each window...) every time Firefox restarts, but it'd be good to fix the problem properly!

**Comment by Picotin** [comment]
Could it be related to #832?
Which, for me and a few others, is apparently related to [User Agent Switcher](https://addons.mozilla.org/en-US/firefox/addon/user-agent-switcher/)…

**Comment by toruyamaguchi** [comment]
新規プロファイルを作成して他のアドオンとの衝突を再現しようと試みましたが、新しいプロファイルではこの現象を再現できませんでした。
まだ原因の特定ができていませんが、何か分かりましたら報告させて頂きます。

**Comment by toruyamaguchi** [comment]
User Agent Switcher is disabled, in Second Window TST child tabs works correctly!
Thanks to your comments I identified cause.

**Comment by piroor** [comment]
Hmm, I've tried following combination but they work for me.

 * Firefox 44.0.2
 * TST latest development build
 * User Agent Switcher 0.7.3.1-signed

Any other condition to reproduce?

**Comment by toruyamaguchi** [comment]
On my profile used daily User Agent Switcher is matter probably. 
So I installed following add-ons in a new profile, but not work correctly in second window too.
- TST 0.16.2016021201
- User Agent Switcher 0.7.3.1-signed

--Environment--
- Windows 10 64bit
- Firefox 64bit 44.0.2 (Release)

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
