### ISSUE TITLE
"Open new blank tab as" = always independent tab

### ISSUE THREAD

**Issue by hmijail** [piroor/treestyletab#996]
"Open new blank tab as" (in the New Tabs prefs) does not seem to work: when I click cmd+T (I'm in a Mac), an independent tab is created, no matter what I select in this option.

The other options do seem to work correctly.

Firefox 43 beta 3 (but I don't think I have seen this work in the last few major Firefox versions)
Tree Style Tab 0.16.2015111001

**Comment by piroor** [comment]
Is this OS X specific issue? Or, any other trigger like tab-related addons including Tab Mix Plus? I couldn't reproduce this. A new tabs is opened as a child of the current tab, by the preference.

 * Ubuntu, Firefox 42.0, TST 0ed972459b8509a4b1d71cf0d41a0360b0989221
 * Ubuntu, Nightly 45.0a1 2015-11-17, TST 0ed972459b8509a4b1d71cf0d41a0360b0989221

You can try the development build of TST from http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by hmijail** [comment]
I tried in a new profile with only TST installed, and it does seem to work OK even with the 0.16.2015111001 version.
I don't think I have any other tab-related addon installed though. (But I have lots of other addons)

**Comment by piroor** [comment]
If you are using the Speed Dial addon, this seems to be duplicated #994 and the commit e06d99d should fix it.

**Comment by hmijail** [comment]
Sorry! I just realized that I DID have a tab-related add-on: All Tabs Helper, which does have an option to change where a new tab should be created ("at the end of the tab bar (default)" and "next to the current tab"; but actually both just create the new tab at the end of the tree as an independent tab). 
Once disabled, the "Open new blank tab as" preference in Tree Style Tab does work as expected.
