### ISSUE TITLE
Moving tab upwards doesn't indent/dedent (keyboard only)

### ISSUE THREAD

**Issue by jimbo1qaz** [piroor/treestyletab#998]
(Firefox 42 on Windows 7 x64)

This bug occurs when you move tabs using the keyboard (ctrl-shift-pageup/down)

When tab1 is moved upwards...
and tab2 (just above tab1) is **the first child**...
and tab3 (parent of tab2) is not a top-level tab...

tab1 will not be indented or dedented to match tab2.

You cannot move glitch-indented tabs down at all... if there are no children correctly located below the parent.

By opening new tabs from glitch-dedented tabs, you can end up with children from two parent tabs in the same indentation group.

Moving tabs through this whole mess is fun. So is collapsing random tabs.

Moving the parent tab will undo the initial move, undoing this glitch.

This bug sometimes disables after messing around with tabs, and reenables after messing around some more.

**Comment by piroor** [comment]
Duplicated #735?

**Comment by jimbo1qaz** [comment]
I don't think so. #735 describes incorrect tab restore, this bug report
describes incorrect keyboard movement, and tab parenting/indentation.

**Comment by sumyungguy** [comment]
Fyi, I was able to reproduce this behavior as described, on OS X. tab1 became a child of tab3, but its indentation matched its parent rather than the child. I was able to reproduce it only once. In subsequent attempts the tab was correctly indented. I didn't see anything obvious to indicate that it's related to #735

**Comment by jimbo1qaz** [comment]
Edited original post.

The moving tab's parent does not need to be an only child, only the first child.

**Comment by piroor** [comment]
Sorry, I missed the paragrah: "This bug occurs when you move tabs using the keyboard (ctrl-shift-pageup/down)". I've confirmed the case:

![01](https://cloud.githubusercontent.com/assets/70062/11446007/14e7c77c-9575-11e5-91c3-51ee5bcc4aba.png)
Ctrl-Shift-PageUp,
![02](https://cloud.githubusercontent.com/assets/70062/11446011/171afcb2-9575-11e5-9969-bdea82341c88.png)
Ctrl-Shift-PageUp,
![03](https://cloud.githubusercontent.com/assets/70062/11446012/18bee1be-9575-11e5-85c4-3a4bff8f5b52.png)
Then the tab "Mozilla Japan" should become the first child of the "Tabs on Bottom" tab but iit has wrong indent.

Is this same to yours? If not, could you describe again with screenshots like them?

**Comment by piroor** [comment]
I've confirmed this:

> By opening new tabs from glitch-dedented tabs, you can end up with children from two parent tabs in the same indentation group.

And I've realized that the tree structure is unexpectedly broken. The commit 6cf8e5e fixes my problem, so could you try the (unsigned) development build? http://piro.sakura.ne.jp/xul/xpi/nightly/
